### ISSUE TITLE
equalsIgnoreCase instead of equals

### ISSUE THREAD

**Issue by bedirhan** [dependency-check/DependencyCheck#1]
testAnalyze of org.codesecure.dependencycheck.analyzer.JarAnalyzerTest line 75 uses equals for string comparison which fails the "implementation-url" comparison. I've changed that to equalsIgnoreCase and compiled successtully.

```
        if (e.getName().equalsIgnoreCase("implementation-url") && e.getValue().equals("http://jetty.mortbay.org")) {
            found = true;
            break;
        }
```

**Comment by jeremylong** [comment]
I will take care of this shortly.

**Comment by jmanico** [comment]
What a sweet tool Jeremy.....

## 

Jim Manico
(808) 652-3805

On Nov 20, 2012, at 4:11 AM, Jeremy Long notifications@github.com wrote:

I will take care of this shortly.

—
Reply to this email directly or view it on
GitHubhttps://github.com/jeremylong/DependencyCheck/issues/1#issuecomment-10555672.

**Comment by jeremylong** [comment]
Thanks for reporting this; the issue is now fixed.

**Comment by bedirhan** [comment]
no problem. thanks for the quick response.
