### ISSUE TITLE
Maven "mvn package" error

### ISSUE THREAD

**Issue by lucaddepar** [dependency-check/DependencyCheck#10]
I've been trying to compile DependencyCheck with Maven 3.0.4, Java 1.6.0_27 and got into errors like: generics are not supported, for-each loops are not supported, ... 

To fix, please add the following lines within `<properties></properties>` in pom.xml

``` xml
<maven.compiler.target>1.6</maven.compiler.target>
<maven.compiler.source>1.6</maven.compiler.source>
```

Thanks. Keep up the good work!

Cheers,
Luca

**Comment by jeremylong** [comment]
Compiler plugin was added to the pom with a source and target of 1.6.
