### ISSUE TITLE
Feature Request: Emit message if lock file exists for updating NVD

### ISSUE THREAD

**Issue by aaronweaver** [dependency-check/DependencyCheck#1000]
If dependency checker is stopped before the update finishes the lock file remains in the data directory. Running dependency checker again "hangs" as it appears to wait for the lock file to be removed. Perhaps show a message that a lock file exists with the option to remove it.

**Comment by jeremylong** [comment]
That is a really good idea - thanks for the suggestion. I suppose we could provide the instructions to remove the lock file and database...

**Comment by ChristopherSchultz** [comment]
This would be helpful for https://github.com/jeremylong/DependencyCheck/issues/1027
