### ISSUE TITLE
False positive for velocity-tools-2.0.jar

### ISSUE THREAD

**Issue by MatthiasDiehl** [dependency-check/DependencyCheck#1001]
False positive on velocity-tools-2.0.jar - reported as cpe:/a:apache:struts:2.0.0

Dependency checker treated velocity-tools jar (Version 2.0) as struts version (Version 2.0). Many  vulnerabilites are found.

```xml
<dependency>
    <groupId>org.apache.velocity</groupId>
    <artifactId>velocity-tools</artifactId>
    <version>2.0</version>
</dependency>
```

**Comment by jeremylong** [comment]
Thanks for reporting the FP

**Comment by jeremylong** [comment]
What version of dependency-check are you using?  When I went to resolve this issue it looks like this FP was previously fixed?

**Comment by MatthiasDiehl** [comment]
I am using version 2.01.  I've tested it with 3.0.2 and I can confirm that the FP is resolved. Thanks!
