### ISSUE TITLE
Suppress button is broken in HTML report

### ISSUE THREAD

**Issue by miklosme** [dependency-check/DependencyCheck#1002]
The `Suppressing False Positives` guide says `In the report next to each CPE identified there is a suppress button`. This seems to be broken, because no suppression button is present in the html report. By checking the source, I made the modal appear, but then the "complete the doc" button was broken again.

<img width="454" alt="screen shot 2017-11-21 at 17 20 38" src="https://user-images.githubusercontent.com/8769273/33083950-fd2bab7e-cee0-11e7-80bc-58f7ed4cbafb.png">

**Comment by jeremylong** [comment]
What browser are you using and what version of dependency-check are you using?

**Comment by miklosme** [comment]
The latest Jenkins [OWASP Dependency-Check Plugin](https://wiki.jenkins.io/display/JENKINS/OWASP+Dependency-Check+Plugin) 3.0.2

And the latest Chrome and Firefox.

Also:

![screen shot 2017-11-23 at 16 26 01](https://user-images.githubusercontent.com/8769273/33179943-68b9be86-d06b-11e7-8833-69b027f0279a.png)

**Comment by jeremylong** [comment]
@stevespringett could this be related to the CSP headers?

**Comment by stevespringett** [comment]
If the HTML report is being viewed from the jobs workspace and the default Jenkins CSP is used, the Dependency-Check HTML report will not function correctly. Downloading the report from Jenkins and viewing it locally is an acceptable workaround and is the only solution short of relaxing or disabling the default Jenkins CSP configuration.

**Comment by miklosme** [comment]
I'm not viewing the report in jenkins, but downloading it.

**Comment by jeremylong** [comment]
I have no idea what is going on with your system. If you save the report to your desktop and then open the report from your desktop everything should work. I can open the HTML report in Chrome, Firefox, and Safari and all features in the report work.
