### ISSUE TITLE
Proxy authentication not working with gradle plugin

### ISSUE THREAD

**Issue by cleanerx** [dependency-check/DependencyCheck#1005]
gradle dependencyCheckAnalyze --info

config is

dependencyCheck {
	proxy {
		server="www-proxy.my.company"
		port=8080
		username="myuser"
		password="myuser"
//		nonproxyhosts="*"
	}
}
settings are correct. I figured nonproxyhosts cannot be set and fails the task

--- snip ---

16:41:00.838 [DEBUG] [sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@4d8c751e5 pairs: {CONNECT nvd.nist.gov:443 HTTP/1.1: null}{User-Agent: Java/1.8.0_144}{Host: nvd.nist.gov}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Proxy-Connection: keep-alive}
16:41:00.870 [DEBUG] [sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@3ad77a014 pairs: {null: HTTP/1.0 407 Proxy Authentication Required}{Server: squid/3.1.23}{Mime-Version: 1.0}{Date: Sun, 26 Nov 2017 15:41:00 GMT}{Content-Type: text/html}{Content-Length: 3315}{X-Squid-Error: ERR_CACHE_ACCESS_DENIED 0}{Vary: Accept-Language}{Content-Language: en}{Proxy-Authenticate: Basic realm="Squid proxy-caching web server"}{X-Cache: MISS from www-proxy.vi.vector.int}{X-Cache-Lookup: NONE from www-proxy.vi.vector.int:8080}{Via: 1.0 www-proxy.vi.vector.int (squid/3.1.23)}{Connection: keep-alive}
16:41:00.870 [DEBUG] [org.owasp.dependencycheck.utils.Downloader] Exception details
java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.0 407 Proxy Authentication Required"
	at sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2124)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at org.owasp.dependencycheck.utils.Downloader.getLastModified(Downloader.java:268)
	at org.owasp.dependencycheck.utils.Downloader.getLastModified(Downloader.java:235)
	at org.owasp.dependencycheck.data.update.NvdCveUpdater$TimestampRetriever.call(NvdCveUpdater.java:507)
	at org.owasp.dependencycheck.data.update.NvdCveUpdater$TimestampRetriever.call(NvdCveUpdater.java:480)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by jeremylong** [comment]
This looks very similar to issue #718 - where we re-enabled basic auth for proxies by setting:

```java
System.setProperty("jdk.http.auth.tunneling.disabledSchemes", "");
``` 
This was documented in the [release notes](http://www.oracle.com/technetwork/java/javase/8u111-relnotes-3124969.html) for Java 8u111.

Can you try setting one additional environment variable to an empty string? Try using the following to the execution:

```bash
gradle -Djdk.http.auth.proxying.disabledSchemes="" dependencyCheckAnalyze --info
```

**Comment by cleanerx** [comment]
It does not fix the problem:
gradle -Djdk.http.auth.proxying.disabledSchemes="" -Djdk.http.auth.tunneling.disabledSchemes="" dependencyCheckAnalyze --info

:dependencyCheckAnalyze (Thread[Task worker for ':',5,main]) started.
IO Exception: Unable to tunnel through proxy. Proxy returns "HTTP/1.0 407 Proxy
Authentication Required"

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

I'm wondering why this is prefixed with jdk since the release notes indicate it is set for the runtime environment.

**Comment by jeremylong** [comment]
Unfortunately, I have no way of debugging the issue you are facing. You may need to talk to your networking folk, find out what proxy is being used, how it is configured, etc.
