### ISSUE TITLE
Handle parallel updates

### ISSUE THREAD

**Issue by janmaterne** [dependency-check/DependencyCheck#1008]
Version: dependency-check-maven:2.1.1

I started the build of three different projects. At last their 'check' goal is run simultanisly.
So I have three different projects trying to update the same database.
Here I got a SQL error (If I remember right, it was a primary key constraint).

I had a look at the sources:
org.owasp.dependencycheck.Engine.doUpdates(boolean)
    H2DBLock dblock = new H2DBLock(settings);
    dblock.lock();
    openDatabase(false, false);

org.owasp.dependencycheck.utils.H2DBLock.lock()
    - lockfile = ${data.directory}/dc.update.lock
    - create logfile-directory if necessary
    - delete logfile if present and older than 30min
    - write a "magic string" into the logfile
    - if the own magic string is in the logfile
      -- the lock is given otherwise
      -- retry the lock-gaining with sleep=10sec up to 120 times (1200sec=20min)

I can't see any problem. :-(
Just want to let you know.

BTW
There the fixed value in the log statement while you are using the constant in the real code:
  debug("... for 10 seconds ...")
  sleep(SLEEP_DURATION)

H2DBLock:148-150
  LOGGER.debug("Sleeping thread {} ({}) for 10 seconds because an exclusive lock on the database could not be obtained ({})",
      Thread.currentThread().getName(), magic, timestamp.toString());
  Thread.sleep(SLEEP_DURATION);

**Comment by jeremylong** [comment]
You indicate that you are using 2.1.1; ff you upgrade to 3.0.2 parallel updates are supported.

**Comment by janmaterne** [comment]
Thanks. I updated the build.
