### ISSUE TITLE
error to connect to the database 

### ISSUE THREAD

**Issue by ammy1999** [dependency-check/DependencyCheck#1011]
I add the dependency check as a plugin maven : 
`<plugin>
                 <groupId>org.owasp</groupId>
                 <artifactId>dependency-check-maven</artifactId>
                 <version>3.0.2</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <suppressionFiles>
                        <suppressionFile>suppressions.xml</suppressionFile>
                    </suppressionFiles>
                </configuration>
            </plugin>`
but I got this error 
[ERROR] Failed to execute goal org.owasp:dependency-check-maven:3.0.2:check (default) on project core-rh: Fatal exception(s) analyzing Core RH: Unable to continue dependency-check analysis.
[ERROR] Unable to connect to the database

**Comment by jeremylong** [comment]
Is that the only error message? Can you re-run with the -X option and provide the log?

**Comment by ammy1999** [comment]
when I add  

> <configuration>
                    <connectionString>jdbc:h2:file:%s;AUTOCOMMIT=ON;</connectionString>
                    <suppressionFiles>
                        <suppressionFile>suppressions.xml</suppressionFile>
                    </suppressionFiles>
                </configuration> 

or MVSTORE=TRUE it works , I can't fix the problem !!

**Comment by ammy1999** [comment]
then when I add ` <connectionString>jdbc:h2:file:%s;AUTOCOMMIT=ON;</connectionString>
                <suppressionFiles>
                    <suppressionFile>suppressions.xml</suppressionFile>
                </suppressionFiles>
            </configuration> `

it doesn't work , I can't uterstand why because when I check the source code of dependency check : 

> `data.connection_string=jdbc:h2:file:%s;MV_STORE=FALSE;AUTOCOMMIT=ON;
`

**Comment by jeremylong** [comment]
Try removing the connection string from the configuration. Then delete (if using Maven) . ~/.m2/repository/org/owasp/dependency-check-data

Then try re-running dependency-check.

**Comment by ammy1999** [comment]
it works, thanks @jeremylong  
but Can I konw exactly what is the role of MVSTRORE and what 's mean the line added !!

**Comment by jeremylong** [comment]
MVSTORE has to do with the newer file format of the H2 database itself. As some of the checks that are in dependency-check rely on the old name/format of the database I opted not continue using the older database format (for now).
