### ISSUE TITLE
Allow replacing Maven Central URL with an internal Artifactory URL

### ISSUE THREAD

**Issue by jacek99** [dependency-check/DependencyCheck#1013]
Due to SOC2 certification, it is prohibited for any build system to reach out to external internet. Hence, all of our build machines are locked down and can access internal network only.

Need to be able to re-point the Maven Central scan to our internal Artifactory URL instead.

Without this, the Gradle plugin is unusable as part of an automated CI build, as it cannot reach Maven Central due to locked down network firewall rules.

**Comment by jacek99** [comment]
Our build servers have whitelisted the URL for the vulnerability DB, so that one is OK as an exception.

But whitelisting Maven Central is not allowed by our security compliance team.

**Comment by stevespringett** [comment]
This can be done using the Nexus analyzer.  Change the Nexus URL to point to your internal repository. This requires Nexus Pro as the APIs required are not available in the non-pro edition.

**Comment by stevespringett** [comment]
https://jeremylong.github.io/DependencyCheck/analyzers/nexus-analyzer.html

**Comment by jacek99** [comment]
So I presume

    dependencyCheck {
        analyzers {
            centralEnabled=false
            nexusEnabled=true
            nexusUrl = <internal nexus pro URL>
        }
    }

would be the way to do it?

**Comment by mprins** [comment]
I don't think it will work for Artifactory ATM, [there seems no analyzer for Artifactory](https://github.com/jeremylong/DependencyCheck/tree/master/dependency-check-core/src/main/java/org/owasp/dependencycheck/analyzer) so you'd just have to turn it off (or upgrade to nexus **pro**)

see also #60

**Comment by stevespringett** [comment]
Refer to the CLI, Ant, Maven and Gradle docs for instructions on how to set it up. It all works about the same. For the Jenkins plugin, analyzers are configurable in the Global Settings. All slaves will inherit the Nexus analyzer info from the master.

**Comment by jacek99** [comment]
Forgive me for asking, as it is not clear...what happens if we disable the Maven Central & Nexus Pro analyzers (since we only have Artifactory)?

Does the tool become useless at this point? Or will it still use the dependency graph from Gradle to figure out all the libraries in an application and scan them against the vulnerability database?

**Comment by stevespringett** [comment]
The Central and Nexus analyzers and primarily intended to improve the quality of evidence. They look at the SHA1 hash of the dependency and retrieve the metadata about the dependency from Central or Nexus. Dependency-Check installations without access to Central or Nexus will continue to function. You may need to disable the Central analyzer so it doesn't violate your companies policy.

**Comment by jacek99** [comment]
Thank you for the clarification
