### ISSUE TITLE
reportOutputDirectory is undocumented in the Maven plugin

### ISSUE THREAD

**Issue by mackncheesiest** [dependency-check/DependencyCheck#1018]
`reportOutputDirectory` is currently undocumented in the [configuration page](https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html) for the DependencyCheck Maven plugin.

Having the option documented would be beneficial.

**Comment by jeremylong** [comment]
The `reportOutputDirectory` is not directly configured in the plugin; rather this is bound to the reporting `outputDirectory`. It is showing up in the plugin help due to the creation of a single mojo that can be used as both a build plugin or a site plugin. To configure the `reportOutputDirectory` you must configure the reporting section like this:

```xml
    <reporting>
        <outputDirectory>${basedir}/target/reports</outputDirectory>
        <plugins>
            <plugin>
                <groupId>org.owasp</groupId>
                <artifactId>dependency-check-maven</artifactId>
                <version>3.1.0-SNAPSHOT</version>
                <configuration>
                    <format>ALL</format>
                </configuration>
            </plugin>
        </plugins>
    </reporting>
```

I will update the javadoc.

**Comment by mackncheesiest** [comment]
Ah, that makes sense. I wonder if there is then a way to mark it as `<editable>false</editable>` in the autogenerated `plugin.xml` so that it doesn't appear as a suggested parameter for the plugin during pom configuration.

I believe marking the parameter as `@Parameter(..., readonly = true)` in the same Java code would stop it from being suggested, but not sure it would necessarily play well with how the rest of the plugin behaves.

**Comment by jeremylong** [comment]
@mackncheesiest thanks for the suggestion - marking the parameter as `readonly` does in fact remove it from the `help:describe`.  Thanks!
