### ISSUE TITLE
False positive on library org.eclipse.persistence.moxy-2.7.0.jar - reported as cpe:/a:git_project:git:2.7.0

### ISSUE THREAD

**Issue by JanICT** [dependency-check/DependencyCheck#1022]
Using version 3.0.2 of the dependency-check-maven plugin.

False positive on library org.eclipse.persistence.moxy-2.7.0.jar and org.eclipse.persistence.core-2.7.0.jar - reported as cpe:/a:git_project:git:2.7.0 cpe:/a:git:git:2.7.0

```xml
            <dependency>
                <groupId>org.eclipse.persistence</groupId>
                <artifactId>org.eclipse.persistence.moxy</artifactId>
                <version>2.7.0</version>
            </dependency>
```

**Comment by jeremylong** [comment]
Thanks for reporting this

**Comment by JanICT** [comment]
You are welcome, I appreciate your work, thank you!
