### ISSUE TITLE
Springboot dependencies - io.netty:netty-codec-http:jar:4.0.27.Final / logback-kafka-appender:jar:1.1.0

### ISSUE THREAD

**Issue by javixeneize** [dependency-check/DependencyCheck#1026]
Hi

I have those two dependencies in springboot that have been flagged as vulnerable

The latest springboot version doesnt have those dependencies upgraded to a patched version

I know there is an open issue (by me) about springboot false positives. Should those two issues be added to that springboot false positives list?

Thanks

**Comment by jeremylong** [comment]
No - these should likely remain their own FP report.  I'll take a look at them in the near future.
