### ISSUE TITLE
Quitting dependency-check during an update leaves stale lock file

### ISSUE THREAD

**Issue by ChristopherSchultz** [dependency-check/DependencyCheck#1027]
Launch dependency-check and, while it is performing a database update, press `CTRL-C` to quit the process. Immediately launch dependency-check again and the tool hangs after printing:

```
[dependency-check] SLF4J: Class path contains multiple SLF4J bindings.
[dependency-check] SLF4J: Found binding in [jar:file:/Users/chris/packages/dependency-check-ant/dependency-check-ant.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[dependency-check] SLF4J: Found binding in [jar:file:/Users/chris/packages/dependency-check-ant/lib/dependency-check-ant-3.0.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[dependency-check] SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
[dependency-check] SLF4J: Actual binding is of type [org.owasp.dependencycheck.ant.logging.AntLoggerFactory]
```

A bit of Googling led me to this issue: https://github.com/jeremylong/DependencyCheck/issues/1000

Deleting the lock file allowed me to resume my work.

It would be nice if dependency-check would clean-up after itself in case it gets interrupted. (If possible). Otherwise, perhaps https://github.com/jeremylong/DependencyCheck/issues/1000 is enough to mitigate this problem.

I happen to be using the Apache ant task, if that makes any difference.

(Thanks for the great tool!)

**Comment by jeremylong** [comment]
I'll do some research on this one - some changes that need to be made are updating the error reporting per issue #1000 and updating the purge task (and related) to remove the lock file.

**Comment by ChristopherSchultz** [comment]
I haven't dived into the code for dependency-check. If it's somewhat straightforward, I might be able to produce a PR.

**Comment by jeremylong** [comment]
Thanks for reporting this issue - I got to learn something new regarding shutdown hooks. This makes ODC much more stable!

**Comment by ChristopherSchultz** [comment]
Thanks for the quick response!

**Comment by djjorjinho** [comment]
Hello,

Are we planning to handle these stale locks on KILL signals? Am I wrong to point out this solution only handles SIGINT?
