### ISSUE TITLE
UpdateOnly very slow

### ISSUE THREAD

**Issue by CarlInglisBJSS** [dependency-check/DependencyCheck#1031]
```
bin/dependency-check.sh \
--updateonly \
--connectionString jdbc:mysql://owasp/dependencycheck \
--dbDriverPath /usr/share/java/mysql-connector-java.jar \
--dbDriverName com.mysql.jdbc.Driver \
--dbPassword [mydbpassword] \
--dbUser [mydbuser
```

I have created the DB using the `initialize-mysql.sql` script from this repo.

The above command is being killed by our three hour job timeout. How long should this update take to update our MySQL DB? 

Is there anything I can do to improve the update speed? 

Thanks.

**Comment by jeremylong** [comment]
Unfortunately, I do not use an external database outside of limited testing. Batch support, which should improve the performance some, will be included in the next release. However, the first run is always the slowest. After you get the initial pull of data from the NVD loaded as long as you run the update at least once a week only a small amount of data is pulled down and processed.

**Comment by CarlInglisBJSS** [comment]
OK, thanks - I think I may have hit issues with RDS IO throttling on the database . If I get a certain fix then I'll add it here, otherwise I'll close it.
