### ISSUE TITLE
False positive: io.vertx:vertx-config-kubernetes-configmap

### ISSUE THREAD

**Issue by msrb** [dependency-check/DependencyCheck#1035]
False positive on library [vertx-config-kubernetes-configmap-3.5.0.jar](http://central.maven.org/maven2/io/vertx/vertx-config-kubernetes-configmap/) - reported as cpe:/a:kubernetes:kubernetes:3.5.0
```xml
<dependency>
   <groupId>io.vertx</groupId>
   <artifactId>vertx-config-kubernetes-configmap</artifactId>
   <version>3.5.0</version>
</dependency>
```

**Comment by jeremylong** [comment]
Thanks for the PR fixing the issue!
