### ISSUE TITLE
command line not working with proxy

### ISSUE THREAD

**Issue by rickcoup** [dependency-check/DependencyCheck#1038]
I am trying to run the command line. But got the below error. Any thought please?
```
$ /c/devtools/dependency-check/bin/dependency-check.bat -project web -s . -o web -proxyserver webproxy.zzz.com -proxyport 8080 -proxyuser zzz -proxypass zzz
[INFO] Checking for updates
[INFO] starting getUpdatesNeeded() ...
[WARN] Unable to download the NVD CVE data; the results may not include the most recent CPE/CVEs from the NVD.
[WARN] Unable to update Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.
[ERROR] No documents exist

Unable to continue dependency-check analysis.
[ERROR] One or more fatal errors occurred
[ERROR] Unable to download the NVD CVE data.
[ERROR] No documents exist
```

**Comment by jeremylong** [comment]
Please delete the data directory (you can run `dependency-check.bat -purge`). Then re-run dependency-check adding `-log odc.log`.  More details about the error will be in the log file and I can assist more if you can post the log file here.

**Comment by ashishWaghmare** [comment]
I am getting below error 
[ERROR] IO Exception: HEAD request returned a non-200 status code
[ERROR] IO Exception: HEAD request returned a non-200 status code
[ERROR] IO Exception: HEAD request returned a non-200 status code

**Comment by stevespringett** [comment]
@ashishWaghmare have you tried with v3.1.2? The NVD changed their URLs and we've released a new version in response.
