### ISSUE TITLE
--exclude not working in jenkins pipeline

### ISSUE THREAD

**Issue by matskinner** [dependency-check/DependencyCheck#1039]
### Some background info
I'm running dockerized OWASP Dependency Check in a Jenkins pipeline. This may be difficult to reproduce, as I'm running everything via Jenkins pipeline.

### Steps to produce

My pipeline downloads a Git repo into a `$WORKSPACE`; in this case it's:
`/var/jenkins_home/workspace/-apps_sample-app_owasp-vuln-PQBR4APAMLGFQWLJM2FRRCRMRPQJF4HT2FRYTY3GEIFOLW4CE4GA/`

I have a directory I want to exclude:
`$WORKSPACE/test/`

Inside that directory (just a random jar to test if the directory is being excluded):
```
$ ls $WORKSPACE/test
api.jar
```

Option I'm using to exclude that directory:
`--exclude $WORKSPACE/test`

My pipeline downloads and runs the container. 
(Commands broken into multiple lines for readability)
```
docker pull owasp/dependency-check
```
```
docker run --rm --volumes-from a2d28e5ee94058497d9500632576390d47164aeac601e05db38467a6aad77442 
owasp/dependency-check 
--data /tmp 
--log /var/jenkins_home/workspace/-apps_sample-app_owasp-vuln-PQBR4APAMLGFQWLJM2FRRCRMRPQJF4HT2FRYTY3GEIFOLW4CE4GA/owasp_logs 
--out /var/jenkins_home/workspace/-apps_sample-app_owasp-vuln-PQBR4APAMLGFQWLJM2FRRCRMRPQJF4HT2FRYTY3GEIFOLW4CE4GA 
--scan /var/jenkins_home/workspace/-apps_sample-app_owasp-vuln-PQBR4APAMLGFQWLJM2FRRCRMRPQJF4HT2FRYTY3GEIFOLW4CE4GA 
--format ALL 
--failOnCVSS 11 
--project OWASP_dependency_check 
--disablePyDist 
--disablePyPkg 
--disableNodeJS 
--disableNSP 
--disableCentral 
--disableNuspec 
--disableAssembly 
--disableRubygems 
--disableBundleAudit 
--disableCocoapodsAnalyzer 
--disableSwiftPackageManagerAnalyzer 
--disableAutoconf 
--disableCmake 
--disableComposer 
--exclude /var/jenkins_home/workspace/-apps_sample-app_owasp-vuln-PQBR4APAMLGFQWLJM2FRRCRMRPQJF4HT2FRYTY3GEIFOLW4CE4GA/test
```
It downloads the CVEs and executes the scan as expected.

When I view the report, it lists several vulnerabilities within the excluded directory. Ex:
```
Dependency: api.jar: mongo-java-driver-3.0.2.jar
File Path: /var/jenkins_home/workspace/-apps_sample-app_owasp-vuln-PQBR4APAMLGFQWLJM2FRRCRMRPQJF4HT2FRYTY3GEIFOLW4CE4GA/test/api.jar/lib/mongo-java-driver-3.0.2.jar
MD5: c076502371b3b170b829c9b163a87081
SHA1: 7d3880dec6c8a2f07c1f544776c326834b513712
```

I know logs are very helpful when debugging, however no logs are being generated. I'm not sure why. 
```
ls -l /var/jenkins_home/workspace/-apps_sample-app_owasp-vuln-PQBR4APAMLGFQWLJM2FRRCRMRPQJF4HT2FRYTY3GEIFOLW4CE4GA/owasp_logs/
total 0
```

Any help is greatly appreciated. Thank you,
Mat

**Comment by stevespringett** [comment]
`--exclude` is not a valid option. 
`--scan` supports Ant style patterns. Refer to the documentation for details.

**Comment by stevespringett** [comment]
Actually, never mind. It appears you are using the Dependency-Check command line interface in Jenkins Pipeline, correct? 

I saw pipeline and automatically assumed you were using the Jenkins plugin, but it appears that's not the case. So disregard my previous comment.

**Comment by matskinner** [comment]
Correct, I'm using the CLI; _not_ the Jenkins plugin.

**Comment by jeremylong** [comment]
The `--exclude` option uses Ant style paths - try using `--exclude $WORKSPACE/test/**`.

**Comment by matskinner** [comment]
Unfortunately, that didn't work either.

Maybe this will help. Here is how I generate my command:

## Step 1
Get list of excluded directories from a CSV config file and turn it into the form:
`--exclude dir_A --exclude dir_B etc...`
In this case, I'm excluding `test/**`. 
```
EXCLUDE = sh(script: "echo ${EXCLUDE_CONFIG} | sed 's/,/ --exclude /g'", returnStdout: true).trim()
EXCLUDE = "--exclude $WORKSPACE/${EXCLUDE}"
```


## Step 2
Define arguments (`--exclude` args added in step 3).
```
def ARGS = "\
          --data /tmp \
          --log $WORKSPACE/owasp_logs \
          --out $WORKSPACE \
          --scan $WORKSPACE \
          --format ALL \
          --failOnCVSS ${CVSS_THRESHOLD} \
          --project ${PROJECT_NAME} \
          --disablePyDist \
          --disablePyPkg \
          --disableNodeJS \
          --disableNSP \
          --disableCentral \
          --disableNuspec \
          --disableAssembly \
          --disableRubygems \
          --disableBundleAudit \
          --disableCocoapodsAnalyzer \
          --disableSwiftPackageManagerAnalyzer \
          --disableAutoconf \
          --disableCmake \
          --disableComposer"
```

## Step 3
Pull/update and run. 
```
        sh "docker pull owasp/dependency-check"
        sh "docker run --rm \
          --volumes-from ${JENKINS_CONTAINER_ID} \
          owasp/dependency-check \
          ${ARGS} \
          ${EXCLUDE}"
```

## Output
Below is the Jenkins console output. You can see what the full command looks like (broke it into multiple lines for readability). 
Note: my script used the wild card in the `--exclude`; Jenkins substituted it for `api.jar` (which is the file I'm trying to exclude). 

```
docker run --rm 
--volumes-from a2d28e5ee94058497d9500632576390d47164aeac601e05db38467a6aad77442 owasp/dependency-check 
--data /tmp 
--log /var/jenkins_home/workspace/-apps_sample-app_owasp-vuln-PQBR4APAMLGFQWLJM2FRRCRMRPQJF4HT2FRYTY3GEIFOLW4CE4GA/owasp_logs 
--out /var/jenkins_home/workspace/-apps_sample-app_owasp-vuln-PQBR4APAMLGFQWLJM2FRRCRMRPQJF4HT2FRYTY3GEIFOLW4CE4GA 
--scan /var/jenkins_home/workspace/-apps_sample-app_owasp-vuln-PQBR4APAMLGFQWLJM2FRRCRMRPQJF4HT2FRYTY3GEIFOLW4CE4GA 
--format ALL 
--failOnCVSS 11 
--project OWASP_dependency_check 
--disablePyDist 
--disablePyPkg 
--disableNodeJS 
--disableNSP
--disableCentral 
--disableNuspec 
--disableAssembly 
--disableRubygems 
--disableBundleAudit 
--disableCocoapodsAnalyzer 
--disableSwiftPackageManagerAnalyzer 
--disableAutoconf 
--disableCmake 
--disableComposer 
--exclude /var/jenkins_home/workspace/-apps_sample-app_owasp-vuln-PQBR4APAMLGFQWLJM2FRRCRMRPQJF4HT2FRYTY3GEIFOLW4CE4GA/test/api.jar
```

Thanks,
Mat

**Comment by jeremylong** [comment]
The code that is being used to _scan_ the directories is from Ant - specifically, ODC is using [`org.apache.tools.ant.DirectoryScanner`](https://ant.apache.org/manual/api/org/apache/tools/ant/DirectoryScanner.html). Possibly the fully qualified path in the exclude is the issue.  Try `--exclude **/test/**` or possibly a slightly more specific exclude would be: `--exclude test/**`.

**Comment by matskinner** [comment]
Almost works.

**Results:**
- `test/**` situationally works (see below).  
- `test` did not work.
- `**/test/**` threw a syntax error. This approach may work with some tweaking, but would likely cause unwanted exclusions if you had multiple directories with the same name in different locations. It would also have the same issue as `test/**`. 

Bottom line: it looks like `--exclude` uses the directory from `--scan` as a prefix. Thus, only the relative path works. I wouldn't have guessed that, thank you. 

**Problem with `test/**`**

Using `test/**` works when there is _one_ file in that directory (lets call that file `file_A`), as it substitutes to: `--exclude test/file_A`. However, if there are multiple files, only the first is excluded, as it substitutes to: `--exclude test/file_A test/file_B`. We are missing the `--exclude` switch in front of `test/file_B`.

Looking at [the docs](https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html), I think most people (me included) will think `--exlude /path/to/dir` will recursively exclude everything within that directory. 

I could write some scripting to `find` every file with in that directory and exclude it; but I don't think that's how `--exclude` was envisioned to work.

**Comment by jeremylong** [comment]
Using the `--exclude test/**` - can you reproduce what you actually execute (the Output above with the docker run...)? My belief is that the OS shell is actually expanding the ** for your...  To prevent that you need to quote the argument like this: `--exclude "test/**"`.

To see what I mean, run `ls test/**` compared to `ls "test/**"` (the second ls will fail as it does not contain a directory `**`).

**Comment by matskinner** [comment]
I see what you're saying; and you're right, the `**` is being expanded too soon.

`"test/**"` didn't work but `\'test/**\'` did. Reason being:

Variables are being evaluated twice, once by the Jenkins box, then again by the container. 

Ex:

**Using `"test/**"`**
- First eval (by Jenkins): `"test/**"` becomes `test/file_A test/file_B ... etc`.
- Container sees: `--exclude test/file_A test/file_B ... etc`. 

**Using `\'test/**\'`**
- First eval (by Jenkins): `\'test/**\'` becomes `'test/**'`.
- Container sees: `--exclude test/**`. Basically just strips off quotes. 

@jeremylong Thanks for the help. Closing issue (also removed "Bug" from the title).
