### ISSUE TITLE
Communication problem- api.nodesecurity.io, jeremylong.github.io

### ISSUE THREAD

**Issue by xxxvodnikxxx** [dependency-check/DependencyCheck#1040]
Hello, from some time we are getting problem when performing dependency checks.

jobs were working fine, we didnt changed anything- as well as in dependencies, as on infrastructure or on proxy.
Env. server behind proxy, not whitelisted ips are restricted, plugin version- lastest, 3.0.2 at the moment
(we have nvd.nist.gov whitelisted)

Jobs fails on following 
```
09:42:39 [DependencyCheck] Exception Caught: org.owasp.dependencycheck.analyzer.exception.AnalysisException
09:42:39 [DependencyCheck] Cause: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 403 Forbidden"
09:42:39 [DependencyCheck] Message: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 403 Forbidden"
09:42:39 [DependencyCheck] org.owasp.dependencycheck.analyzer.exception.AnalysisException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 403 Forbidden"
09:42:39 [DependencyCheck] 	at org.owasp.dependencycheck.analyzer.NspAnalyzer.analyzeDependency(NspAnalyzer.java:272)
09:42:39 [DependencyCheck] 	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:137)
09:42:39 [DependencyCheck] 	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
09:42:39 [DependencyCheck] 	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
09:42:39 [DependencyCheck] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
09:42:39 [DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
09:42:39 [DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
09:42:39 [DependencyCheck] 	at java.lang.Thread.run(Thread.java:745)
09:42:39 [DependencyCheck] Caused by: java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 403 Forbidden"
09:42:39 [DependencyCheck] 	at sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2084)
09:42:39 [DependencyCheck] 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
09:42:39 [DependencyCheck] 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
09:42:39 [DependencyCheck] 	at org.owasp.dependencycheck.data.nsp.NspSearch.submitPackage(NspSearch.java:114)
09:42:39 [DependencyCheck] 	at org.owasp.dependencycheck.analyzer.NspAnalyzer.analyzeDependency(NspAnalyzer.java:174)
09:42:39 [DependencyCheck] 	... 7 more
09:42:39 [DependencyCheck] 
09:42:39 Build step 'Invoke OWASP Dependency-Check analysis' changed build result to FAILURE
```

After some searching, we got the info plugin is trying to communicate to other sites- on HTTPS, 443, with jeremylong.github.io and api.nodesecurity.io (As I mentioned above, what is not whitelisted is restricted, we didnt have these sites whitelisted, because there wasnt any reason in the past)
Communication is bellow
```
Dec 19 08:32:40 <our proxy ip> 2017-12-19 08:32:39 12675 <OUR IP> - - - - OBSERVED "Government/Legal;Technology/Internet" - 200 TCP_TUNNELED CONNECT - tcp nvd.nist.gov 443 / - - "Java/1.8.0_60" 165.72.197.34 2370590 977 -
Dec 19 08:34:07 <our proxy ip> 2017-12-19 08:34:06 22 <OUR IP> - - - policy_denied DENIED "Technology/Internet" - 403 TCP_DENIED CONNECT - tcp jeremylong.github.io 443 / - - "Java/1.8.0_60" 165.72.197.33 184 192 -
Dec 19 08:34:10 <our proxy ip> 2017-12-19 08:34:10 72 <OUR IP> - - - policy_denied DENIED "Technology/Internet" - 403 TCP_DENIED CONNECT - tcp api.nodesecurity.io 443 / - - "Java/1.8.0_60" 165.72.197.33 184 190 -
Dec 19 08:41:19 <our proxy ip> 2017-12-19 08:41:17 614 <OUR IP> - - - - OBSERVED "Technology/Internet;Office/Business Applications" - 200 TCP_TUNNELED CONNECT - tcp github.com 443 / - - "Java/1.8.0_60" 165.72.197.33 7351 913 -
Dec 19 08:41:29 <our proxy ip> 2017-12-19 08:41:28 10473 <OUR IP> - - - - OBSERVED "Software Downloads;Content Servers" - 200 TCP_TUNNELED CONNECT - tcp github-production-release-asset-2e65be.s3.amazonaws.com 443 / - - "Java/1.8.0_60" <another IP> 3578 1550 -
Dec 19 08:42:38 <our proxy ip> 2017-12-19 08:42:38 4 <OUR IP> - - - policy_denied DENIED "Technology/Internet" - 403 TCP_DENIED CONNECT - tcp jeremylong.github.io 443 / - - "Java/1.8.0_60" 165.72.197.34 186 192 -
Dec 19 08:42:40 <our proxy ip> 2017-12-19 08:42:39 65 <OUR IP> - - - policy_denied DENIED "Technology/Internet" - 403 TCP_DENIED CONNECT - tcp api.nodesecurity.io 443 / - - "Java/1.8.0_60" 165.72.197.33 184 190 -
```
Can you, please, provide us some info, if it is necessary to communicate with these sites, or not? 
Can you, please, provide us some info about the communication- scheme- in  case of dependency checking? 
It looks like plugin is trying to communicate with these sites first, before nvd database, and in our case it of course fails.

We are confused because it was working before, but not anymore- did changed anything, or?

Thanks for any info.
Pavel Novak

**Comment by stevespringett** [comment]
Is the firewall capable of policy enforcement based on hostname, or does it require an IP address in order to create a whitelist? 

Both of these services are hosted in the cloud and its hard to say what the IP address will be. It depends on what part of the world you’re in and the traffic patterns of the closest servers.

jeremylong.github.io resolves to 4 different IP addresses from my location and appears to use DNS round robin. NSP is only resolving to 1 IP address from my location.

If you don't need to analyze package.json, you can disable the NSP analyzer.

**Comment by xxxvodnikxxx** [comment]
The problem is not about we don't know what (we need) to do (to make it working), but about the thing if it is really necessary- as I mentioned, it was working without allowed github.io as well as nodescurity sites :)- you know security politics and things like that.

And the proxy takes specific IPs, but that is not a problem, I guess until some server migration or moving in infrastructure, it will be accessing still on same IPs.

_Really thank for you post, it is a good point_, but I would like to ask if it is possible to run dependency checks without communication with (from our point) unknown sources (special in that case it was possible in the past), there was evidently communication just with NVD, which makes sense.

I can see jeremylong.io will be some sources from the authors, as well as there will be some secure checks on nodesecurity, etc., but if I will have specific examples, it will be easier to propose to make it tunneled through- eg.

**Comment by jeremylong** [comment]
The check to `jeremylong.github.io` is just a simple version check - it pulls down jeremylong.github.io/DependencyCheck/current.txt and compares the version you are running to the latest published version - if you are behind it prints a warning message indicating you should upgrade. This can be disabled by setting a system property (updater.versioncheck.enabled) to false (i.e. in mvn add `-Dupdater.versioncheck.enabled=false`).

The usage of NSP was added with the updates to support node.js. The root package.json of a node app is parsed and some of the info is sent off to NSP for analysis. The NSP analyzer can be disabled - see the [documentation site](https://jeremylong.github.io/DependencyCheck/) for more details.

**Comment by xxxvodnikxxx** [comment]
Hello Jeremy, thanks a lot for your answer, I think that is enough :)

**Comment by xxxvodnikxxx** [comment]
Uhm, maybe just one more thing- can you direct me, where to put these parameters?
 I was looking into global Jenkins config in section OWASP, but there is probably no field for these parameters or checkboxes for these options...
??? EDIT- maybe _Global properties_ and _Environment variables_ is the right place (under Jenkins configuration, .../configure)?



![image](https://user-images.githubusercontent.com/34677795/34255660-fe48fce0-e651-11e7-9ff4-b7b083f1bf8b.png)

![image](https://user-images.githubusercontent.com/34677795/34255663-0bae2a4a-e652-11e7-9e49-d7761797d5e6.png)


And the same problem about NSP checker, I didnt fine any mention about it on the doc web _/or simply I have no idea where to look/_ only [this](https://jeremylong.github.io/DependencyCheck/analyzers/) where is the dead link, I just found another [thread](https://github.com/jeremylong/DependencyCheck/issues/882) where is mention about
```
<configuration>
   <nspAnalyzerEnabled>false</nspAnalyzerEnabled>
</configuration>
```
But I guess that is from some jenkins profile file, or ??? 
Is it possible to change it globally to be applied to all projects In the best case without Jenkins restart? As well as the current as on the new created? 

I found 
`analyzer.nsp.package.enabled=true`
in your [property file](https://github.com/jeremylong/DependencyCheck/blob/master/dependency-check-core/src/main/resources/dependencycheck.properties) but if I tried to use it in global properties mentioned above- _Global properties_ and _Environment variables_ 

, it is still failing on the same cause.


Thanks a lot for your help

**Comment by xxxvodnikxxx** [comment]
Oh, I apologize.
So basically  `updater.versioncheck.enabled = false` into global properties in the _Manage Jenkins_ options works, I found _Enable Node Security Platform analyzer_ in experimental section.
When we disable both, builds are working fine.

Thank you very much :) 👍
