### ISSUE TITLE
IOS dependencies

### ISSUE THREAD

**Issue by seanboylan** [dependency-check/DependencyCheck#105]
Can I scan aple IOS dependencies using dependency checker?

If not can we get this added to the roadmap.

I have already used dependencychecker to scan android apps and that works very well.

**Comment by jeremylong** [comment]
iOS apps are not currently supported. I will leave this ticket open to keep it on the project teams radar. At the moment there are a few other things that are a higher priority so I'm not sure how soon we can get to this.

**Comment by imbeyondboredom** [comment]
@jeremylong I made something to this effect on a fork - but one of the problems is that ios dependencies can check out git repos at a tag version. This DependencyCheck library wants a definitive file that we can add to the evidence that we get a hash out of. In the case where we have a whole github repo what would be acceptable to you for adding this dependency?

Right now in our fork we create a temporary file and write the dependency string out to it just so it will be included in the scan. 

`File tmpFile = File.createTempFile("dep", "pod");
PrintWriter writer = new PrintWriter(tmpFile);
writer.write(dependencyString);
writer.close();
dependency1.setFilePath(tmpFile.getPath());
dependency1.setActualFilePath(tmpFile.getAbsolutePath());
dependency1.setDisplayFileName(dependencyString);`

How would you like for this to officially work?

**Comment by jeremylong** [comment]
A Swift package manager analyzer and a Coacoa Pods analyzer have been built. As such, iOS dependencies should be covered now.

Note, these are current experimental analyzers. More information can be found here: http://jeremylong.github.io/DependencyCheck/analyzers/index.html
