### ISSUE TITLE
Maven plugin: improve documentation by mentioning how to run it

### ISSUE THREAD

**Issue by php-coder** [dependency-check/DependencyCheck#1050]
I see that both pages (https://github.com/jeremylong/DependencyCheck#maven-plugin and https://jeremylong.github.io/DependencyCheck/dependency-check-maven/) only mentions how to configure a plugin but they don't say how to run it.

I see that we bind `check` goal but it's not clear to what phase it was bind. I tried `mvn compile` and `mvn package` but the plugin wasn't triggered.

Also I just to try it and I'm looking for a way to run it as-is, without binding. `mvn dependency-check-maven:check` didn't work to me. Could you mention that it could be run by command `mvn org.owasp:dependency-check-maven:check` ?

Thanks!

**Comment by mprins** [comment]
See https://jeremylong.github.io/DependencyCheck/dependency-check-maven/plugin-info.html

**Comment by php-coder** [comment]
@mprins I don't see how it should help. Another page with plugin configuration...

**Comment by mprins** [comment]
it lists the available goals, any goal can be run using mvn eg. [dependency-check:check](https://jeremylong.github.io/DependencyCheck/dependency-check-maven/check-mojo.html) can be run as `mvn org.owasp:dependency-check-maven:3.1.0:check` 
Maybe this is a lack of familiarity on how Maven works and you should dive into how that works, eg. Sonatype provides some great references: https://www.sonatype.com/ebooks

**Comment by jeremylong** [comment]
The check and aggregate goals are bound to the `verify` [phase](https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html) by default. This can be changed via configuration (note the addition of the phase element to the execution):

```xml
<plugin>
  <groupId>org.owasp</groupId>
  <artifactId>dependency-check-maven</artifactId>
  <executions>
    <execution>
      <phase>test</phase>
      <goals>
        <goal>check</goal>
      </goals>
    </execution>
  </executions>
</plugin>
```

**Comment by jeremylong** [comment]
The markdown has been updated (including the base README.md). The gh-pages will be updated with the next release.

**Comment by php-coder** [comment]
@jeremylong Thank you!
