### ISSUE TITLE
Maven plugin: wrong path to the report

### ISSUE THREAD

**Issue by php-coder** [dependency-check/DependencyCheck#1051]
At page https://jeremylong.github.io/DependencyCheck/dependency-check-maven/index.html there are 4 places like this:

> Create the DependencyCheck-report.html in the target directory.

But the report has been named `dependency-check-report.html` (and not `DependencyCheck-report.html`).

**Comment by jeremylong** [comment]
Thanks for pointing this out.  The markdown has been updated (along with error messages in the source code). The updates will be included in the next release.
