### ISSUE TITLE
Certificate Error

### ISSUE THREAD

**Issue by ghost** [dependency-check/DependencyCheck#1057]
When using Jenkins Plugin i see below error message in the log files. 

Using Latest 3.1.0 plugin. 

`[DependencyCheck] Performing NVD update only
[DependencyCheck] Unable to update the Dependency-Check database
Build step 'Invoke Dependency-Check NVD update only' changed build result to FAILURE
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
Finished: FAILURE`

```
WARNING: Unable to download the NVD CVE data; the results may not include the most recent CPE/CVEs from the NVD.
Jan 05, 2018 12:44:02 PM org.owasp.dependencycheck.utils.Downloader getLastModified
SEVERE: IO Exception: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Jan 05, 2018 12:44:02 PM org.owasp.dependencycheck.utils.Downloader getLastModified
SEVERE: IO Exception: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Jan 05, 2018 12:44:02 PM org.owasp.dependencycheck.utils.Downloader getLastModified
SEVERE: IO Exception: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Jan 05, 2018 12:44:02 PM org.owasp.dependencycheck.utils.Downloader getLastModified
SEVERE: IO Exception: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Jan 05, 2018 12:44:02 PM org.owasp.dependencycheck.utils.Downloader getLastModified
SEVERE: IO Exception: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Jan 05, 2018 12:44:02 PM org.owasp.dependencycheck.utils.Downloader getLastModified
SEVERE: IO Exception: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Jan 05, 2018 12:44:02 PM org.owasp.dependencycheck.utils.Downloader getLastModified
SEVERE: IO Exception: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Jan 05, 2018 12:44:05 PM org.owasp.dependencycheck.utils.Downloader getLastModified
SEVERE: IO Exception: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Jan 05, 2018 12:44:05 PM org.owasp.dependencycheck.utils.Downloader getLastModified
SEVERE: IO Exception: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Jan 05, 2018 12:44:05 PM org.owasp.dependencycheck.utils.Downloader getLastModified
SEVERE: IO Exception: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

what am i doing wrong. I am just trying to download the latest NVD updates. Running Jenkins under Tomcat.

**Comment by stevespringett** [comment]
The info provided does not help. Can you provide more information:

What Java vendor and Java version is running the Jenkins process (i.e. Oracle JDK 1.8.0_151)

What platform is the NVD update Jenkins job running on?

Are you going through a proxy server?

**Comment by ghost** [comment]
Tomcat 8.0
Java JDK 1.8.53
Windows 2012 R2
Yes going through proxy.

**Comment by stevespringett** [comment]
Oracle Java or OpenJDK?

Have you configured the proxy settings in the Jenkins global config?

Did you by chance read through #561 and #728?

Can you confirm the Java version you're using to run Jenkins supports the following ciphers?

TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA

These are the only ones supported by the NVD.

**Comment by ghost** [comment]
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

Yes I got the proxy settings in Jenkins Global config.

Yes looks like all Chipers listed above do exist

```
Default Cipher
        SSL_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA
        SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA
        SSL_DHE_DSS_WITH_DES_CBC_SHA
        SSL_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA
        SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA
        SSL_DHE_RSA_WITH_DES_CBC_SHA
        SSL_DH_anon_EXPORT_WITH_DES40_CBC_SHA
        SSL_DH_anon_EXPORT_WITH_RC4_40_MD5
        SSL_DH_anon_WITH_3DES_EDE_CBC_SHA
        SSL_DH_anon_WITH_DES_CBC_SHA
        SSL_DH_anon_WITH_RC4_128_MD5
        SSL_RSA_EXPORT_WITH_DES40_CBC_SHA
        SSL_RSA_EXPORT_WITH_RC4_40_MD5
        SSL_RSA_WITH_3DES_EDE_CBC_SHA
        SSL_RSA_WITH_DES_CBC_SHA
        SSL_RSA_WITH_NULL_MD5
        SSL_RSA_WITH_NULL_SHA
        SSL_RSA_WITH_RC4_128_MD5
        SSL_RSA_WITH_RC4_128_SHA
        TLS_DHE_DSS_WITH_AES_128_CBC_SHA
        TLS_DHE_DSS_WITH_AES_128_CBC_SHA256
        TLS_DHE_DSS_WITH_AES_128_GCM_SHA256
        TLS_DHE_RSA_WITH_AES_128_CBC_SHA
        TLS_DHE_RSA_WITH_AES_128_CBC_SHA256
        TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
        TLS_DH_anon_WITH_AES_128_CBC_SHA
        TLS_DH_anon_WITH_AES_128_CBC_SHA256
        TLS_DH_anon_WITH_AES_128_GCM_SHA256
        TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA
        TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
        TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
        TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        TLS_ECDHE_ECDSA_WITH_NULL_SHA
        TLS_ECDHE_ECDSA_WITH_RC4_128_SHA
        TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA
        TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
        TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
        TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        TLS_ECDHE_RSA_WITH_NULL_SHA
        TLS_ECDHE_RSA_WITH_RC4_128_SHA
        TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA
        TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA
        TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256
        TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256
        TLS_ECDH_ECDSA_WITH_NULL_SHA
        TLS_ECDH_ECDSA_WITH_RC4_128_SHA
        TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA
        TLS_ECDH_RSA_WITH_AES_128_CBC_SHA
        TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256
        TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256
        TLS_ECDH_RSA_WITH_NULL_SHA
        TLS_ECDH_RSA_WITH_RC4_128_SHA
        TLS_ECDH_anon_WITH_3DES_EDE_CBC_SHA
        TLS_ECDH_anon_WITH_AES_128_CBC_SHA
        TLS_ECDH_anon_WITH_NULL_SHA
        TLS_ECDH_anon_WITH_RC4_128_SHA
        TLS_EMPTY_RENEGOTIATION_INFO_SCSV
        TLS_KRB5_EXPORT_WITH_DES_CBC_40_MD5
        TLS_KRB5_EXPORT_WITH_DES_CBC_40_SHA
        TLS_KRB5_EXPORT_WITH_RC4_40_MD5
        TLS_KRB5_EXPORT_WITH_RC4_40_SHA
        TLS_KRB5_WITH_3DES_EDE_CBC_MD5
        TLS_KRB5_WITH_3DES_EDE_CBC_SHA
        TLS_KRB5_WITH_DES_CBC_MD5
        TLS_KRB5_WITH_DES_CBC_SHA
        TLS_KRB5_WITH_RC4_128_MD5
        TLS_KRB5_WITH_RC4_128_SHA
        TLS_RSA_WITH_AES_128_CBC_SHA
        TLS_RSA_WITH_AES_128_CBC_SHA256
        TLS_RSA_WITH_AES_128_GCM_SHA256
        TLS_RSA_WITH_NULL_SHA256

```

**Comment by stevespringett** [comment]
To summarize, we have:
- [x] Confirmed use of Oracle Java 1.8.0_151 is running Jenkins
- [x] Confirmed configuration of proxy in global config
- [x] Confirmed required ciphers are available

Can you please run the Dependency-Check [command line utility](https://jeremylong.github.io/DependencyCheck/dependency-check-cli/index.html) and tell us if you experience the same issue or not.

Also, do you have the default truststore or has it been modified? The cert used by the NVD was issued by Symantec which will be untrusted from Chrome in a few months and I'm wondering if your IT folks got a head start. I don't know of a way to untrust intermediate certs globally in Java, but can you confirm that the required root certificate exists?

`keytool -keystore "$JAVA_HOME\jre\lib\security\cacerts" -storepass changeit -list`

The alias I'm looking for is: `verisignclass3g5ca [jdk]`

@jeremylong Any other thoughts?

**Comment by ghost** [comment]
@stevespringett All i am doing is trying to get the NVD updates using "Invoke Dependency-check NVD update only"first before running the dependency checker against my source code. 

I am using the default keystore nothing custom. I do see verisignclass3g5ca .

```
verisignclass3g5ca [jdk], Aug 25, 2016, trustedCertEntry,
Certificate fingerprint (SHA1): 4E:B6:D5:78:49:9B:1C:CF:5F:58:1E:AD:56:BE:3D:9B:67:44:A5:E5
```

**Comment by stevespringett** [comment]
I tested Dependency-Check Jenkins plugin v3.1.0 using the latest Jenkins LTS, Java 1.8.0_151 on Windows 2012 R2 and it works as designed. I'm leaning towards the proxy being the issue but do not have one installed or available.

<img width="1570" alt="screen shot 2018-01-05 at 8 49 09 pm" src="https://user-images.githubusercontent.com/3878933/34635812-61d3035a-f25a-11e7-9ac3-874ff303dd72.png">

**Comment by ghost** [comment]
I am just using the Proxy under Plugins-->Advanced and gave my corporate Proxy information. Also my corporate proxy do require user authentication. So provided host,port,username and password.

**Comment by jeremylong** [comment]
Is the corporate proxy decrypting traffic? I.e. is the certificate issue happening because of the proxy? 

Consider setting up a mirror of the NVD internal to your organization and disabling the CentralAnalyzer and the NSP Analyzer. Alternatively, open a ticket with your network team?

**Comment by ghost** [comment]
There is no problem with any other sites with the same setup. I am guessing
there is something wrong with the network.

Mirror of NVD can this be automated in Jenkins? I am guessing I have to use
the bat file instead of Jenkins plugin?

Thanks,

Varun

**Comment by stevespringett** [comment]
To mirror the NVD, most orgs will opt to setup a cron job (or other type of scheduled task) to perform the mirror. The mirror works best if you have it being served by a web server. 

So for example, the base url to the NVD mirror might be http://myhost/mirrors/nvd

Refer to https://jeremylong.github.io/DependencyCheck/data/mirrornvd.html for the four parameters needed and a tool that is available to automatically perform the mirroring.

By Mirroring, you're also reducing the risk of receiving 400s back from the NVD when conducting too many requests  - thus potentially breaking builds. Mirroring prevents that.

**Comment by ghost** [comment]
Thanks for the information. I might have same problem. If mirroring also going to download files the request might have to still go through proxy.? Instead of Jenkins plugin we are using a binary file and mirroring the NIST data correct?

**Comment by stevespringett** [comment]
Correct. But the download doesn't have to occur on the Jenkins machine. It can occur on any machine in your network that you can setup a scheduled job on and provide the files over HTTP.

If the nist-data-mirror tool does not work for you, you can always mimic the behavior using a simple script and curl.

**Comment by ghost** [comment]
This is the error i see.
```
[ERROR] IO Exception: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException
: unable to find valid certification path to requested target
adding as trusted cert:
trustStore is: JAVA_HOME\cacerts
trustStore type is: pkcs12
trustStore provider is:
the last modified time is: Wed Jan 03 16:28:12 PST 2018
Inaccessible trust store: JAVA_HOME\lib\security\jssecacerts
```

**Comment by jeremylong** [comment]
[This article](https://confluence.atlassian.com/kb/unable-to-connect-to-ssl-services-due-to-pkix-path-building-failed-779355358.html) from Atlassian provides a really good step by step guide to resolving this issue.
