### ISSUE TITLE
False positive for lombok with dependency check 3.1.0

### ISSUE THREAD

**Issue by obecker** [dependency-check/DependencyCheck#1064]
False positive on library org.projectlombok:lombok:1.16.20 - reported as cpe:/a:spice_project:spice:1.16.20

http://repo1.maven.org/maven2/org/projectlombok/lombok/1.16.20/

It seems `spice` is detected because of lombok's description 

`Spice up your java: Automatic Resource Management, automatic generation of getters, setters, equals, hashCode and toString, and more!` 

in the maven pom.

**Comment by jeremylong** [comment]
Thanks, I'll cycle through all the FP reports prior to the next release.

**Comment by rand0m86** [comment]
Still same for 3.1.1.

**Comment by jeremylong** [comment]
I didn't get a chance to go through the FP for the 3.1.1 release - a major issue came about due to changes external to ODC that required 3.1.1 to be released prior to me being able to go through the FP.
