### ISSUE TITLE
NPM dependencies not found

### ISSUE THREAD

**Issue by agtinternational** [dependency-check/DependencyCheck#1065]
Hi,

trying to use the cli scanner but for some reason it doesnt find any dependencies for nodejs.

I see the log with lots of exceptions: [NodePackageAnalyzer] Unable to find node module

even if I executed npm install and node_modules contains the downloaded dependencies.

On projects with 2000 dependencies maybe is listing 7-8 of them only. 

I used the master code.

J

**Comment by jeremylong** [comment]
One possible issue is that dependency-check should be pointed to scan the root of the project directory.  So using [dependency-check-3.1.0](https://bintray.com/jeremy-long/owasp/download_file?file_path=dependency-check-3.1.0-release.zip) on a Node JS project you would:

```shell
$ npm install
$ dependency-check.sh -o ./reports -s . --project myNodeProject
```
Is that what you executed?

**Comment by giulio1979** [comment]
I am actually integrating it into another product, but in theory is the same. I will check about the --project as I dont remember populating anything for that into the Settings object.

J

**Comment by jeremylong** [comment]
I don't believe the CLI would have worked without the `--project` argument - so you wouldn't have gotten any results.  I would make sure the scan is of the directory and not directly pointing to the `package.json`. Also - to really validate the count of dependencies in your project you can run the following (the count will be 1 higher as it includes the project itself):

```shell
npm install
npm ls | sed 's/^[ └│┬├─└]*//' | sed 's/ deduped//' | grep -v ^$ | sort -fu | wc -l
```
