### ISSUE TITLE
Gradle Task: Error occurs with multi-project builds

### ISSUE THREAD

**Issue by amirnawaz** [dependency-check/DependencyCheck#1066]
Unable to resolve dependency for ':SearchBar_withMaterial@debugAndroidTest/compileClasspath': Could not resolve project :app.

Could not resolve project :app.
Required by:
    project :SearchBar_withMaterial
 > Unable to find a matching configuration of project :app:
     - Configuration 'debugApiElements':
         - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
         - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found incompatible value 'Apk'.
         - Found com.android.build.gradle.internal.dependency.VariantAttr 'debug' but wasn't required.
         - Required org.gradle.usage 'java-api' and found compatible value 'java-api'.
     - Configuration 'debugMetadataElements':
         - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
         - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found incompatible value 'Metadata'.
         - Found com.android.build.gradle.internal.dependency.VariantAttr 'debug' but wasn't required.
         - Required org.gradle.usage 'java-api' but no value provided.
     - Configuration 'debugRuntimeElements':
         - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
         - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found incompatible value 'Apk'.
         - Found com.android.build.gradle.internal.dependency.VariantAttr 'debug' but wasn't required.
         - Required org.gradle.usage 'java-api' and found incompatible value 'java-runtime'.
     - Configuration 'previewApiElements':
         - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found incompatible value 'preview'.
         - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found incompatible value 'Apk'.
         - Found com.android.build.gradle.internal.dependency.VariantAttr 'preview' but wasn't required.
         - Required org.gradle.usage 'java-api' and found compatible value 'java-api'.
     - Configuration 'previewMetadataElements':
         - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found incompatible value 'preview'.
         - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found incompatible value 'Metadata'.
         - Found com.android.build.gradle.internal.dependency.VariantAttr 'preview' but wasn't required.
         - Required org.gradle.usage 'java-api' but no value provided.
     - Configuration 'previewRuntimeElements':
         - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found incompatible value 'preview'.
         - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found incompatible value 'Apk'.
         - Found com.android.build.gradle.internal.dependency.VariantAttr 'preview' but wasn't required.
         - Required org.gradle.usage 'java-api' and found incompatible value 'java-runtime'.
     - Configuration 'releaseApiElements':
         - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found incompatible value 'release'.
         - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found incompatible value 'Apk'.
         - Found com.android.build.gradle.internal.dependency.VariantAttr 'release' but wasn't required.
         - Required org.gradle.usage 'java-api' and found compatible value 'java-api'.
     - Configuration 'releaseMetadataElements':
         - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found incompatible value 'release'.
         - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found incompatible value 'Metadata'.
         - Found com.android.build.gradle.internal.dependency.VariantAttr 'release' but wasn't required.
         - Required org.gradle.usage 'java-api' but no value provided.
     - Configuration 'releaseRuntimeElements':
         - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found incompatible value 'release'.
         - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found incompatible value 'Apk'.
         - Found com.android.build.gradle.internal.dependency.VariantAttr 'release' but wasn't required.
         - Required org.gradle.usage 'java-api' and found incompatible value 'java-runtime'.

**Comment by amirnawaz** [comment]
hi ... i want to resolve this error so fast . kindly tell me complete solution thanks :)

**Comment by amirnawaz** [comment]
![image](https://user-images.githubusercontent.com/32749534/34920155-0645a6cc-f990-11e7-8475-f07eab04187c.png)

my this error solved now because of just committing
 // compile project(path: ':app')

**Comment by amirnawaz** [comment]
please describe me about this  // compile project(path: ':app')   
thanks

**Comment by jeremylong** [comment]
This appears to be related to other issues that have been reported for the gradle task. It appears that there is an issue with multi-project builds that I need to look into.

**Comment by alixwar** [comment]
Any progress or plans for this issue @jeremylong?

**Comment by jeremylong** [comment]
This is affecting both the gradle and maven - for aggregate builds with multi-module projects that depend upon each other. I have some ideas, but so far I haven't found a solution.

**Comment by alixwar** [comment]
@jeremylong Do you know of any workarounds meanwhile?

**Comment by jzmanu** [comment]
I have a same problem.

**Comment by jeremylong** [comment]
A major fix for this was implemented in v3.3.1. However, specific to gradle please see https://github.com/jeremylong/dependency-check-gradle/issues/94.  I will be releasing a patch in the next week depending on how some other work goes.
