### ISSUE TITLE
Cause: No space left on device Message: Could not extract GrokAssembly.exe

### ISSUE THREAD

**Issue by Kish-Jadhav** [dependency-check/DependencyCheck#1069]
Hi ,

When I am running dependency checker Jenkins plugin multiple times, I am receiving "No space left on device Message". Ideally, dependency checker plugin should automatically remove the tmp data used by itself.

Can anyone help me out from this error?:
09:23:00 [DependencyCheck] One or more exceptions were thrown while executing Dependency-Check
09:23:00 [DependencyCheck] Exception Caught: org.owasp.dependencycheck.data.update.exception.UpdateException
09:23:00 [DependencyCheck] Message: The download was interrupted; unable to complete the update
09:23:00 [DependencyCheck] org.owasp.dependencycheck.data.update.exception.UpdateException: The download was interrupted; unable to complete the update
09:23:00 [DependencyCheck] 	at org.owasp.dependencycheck.data.update.NvdCveUpdater.performUpdate(NvdCveUpdater.java:269)
09:23:00 [DependencyCheck] 	at org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:119)
09:23:00 [DependencyCheck] 	at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:889)
09:23:00 [DependencyCheck] 	at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:716)
09:23:00 [DependencyCheck] 	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:642)
09:23:00 [DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.executeDependencyCheck(DependencyCheckExecutor.java:172)
09:23:00 [DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.call(DependencyCheckExecutor.java:103)
09:23:00 [DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.call(DependencyCheckExecutor.java:46)
09:23:00 [DependencyCheck] 	at hudson.remoting.LocalChannel.call(LocalChannel.java:45)
09:23:00 [DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.AbstractDependencyCheckBuilder.perform(AbstractDependencyCheckBuilder.java:85)
09:23:00 [DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckBuilder.perform(DependencyCheckBuilder.java:206)
09:23:00 [DependencyCheck] 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
09:23:00 [DependencyCheck] 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
09:23:00 [DependencyCheck] 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
09:23:00 [DependencyCheck] 	at hudson.model.Build$BuildExecution.build(Build.java:206)
09:23:00 [DependencyCheck] 	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
09:23:00 [DependencyCheck] 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
09:23:00 [DependencyCheck] 	at hudson.model.Run.execute(Run.java:1724)
09:23:00 [DependencyCheck] 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
09:23:00 [DependencyCheck] 	at hudson.model.ResourceController.execute(ResourceController.java:97)
09:23:00 [DependencyCheck] 	at hudson.model.Executor.run(Executor.java:421)
09:23:00 [DependencyCheck] 

09:23:00 [DependencyCheck] Exception Caught: org.owasp.dependencycheck.exception.InitializationException
09:23:00 [DependencyCheck] Cause: No space left on device
09:23:00 [DependencyCheck] Message: Could not extract GrokAssembly.exe
09:23:00 [DependencyCheck] org.owasp.dependencycheck.exception.InitializationException: Could not extract GrokAssembly.exe
09:23:00 [DependencyCheck] 	at org.owasp.dependencycheck.analyzer.AssemblyAnalyzer.prepareFileTypeAnalyzer(AssemblyAnalyzer.java:230)
09:23:00 [DependencyCheck] 	at org.owasp.dependencycheck.analyzer.AbstractFileTypeAnalyzer.prepareAnalyzer(AbstractFileTypeAnalyzer.java:73)
09:23:00 [DependencyCheck] 	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.prepare(AbstractAnalyzer.java:108)
09:23:00 [DependencyCheck] 	at org.owasp.dependencycheck.Engine.initializeAnalyzer(Engine.java:817)
09:23:00 [DependencyCheck] 	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:662)
09:23:00 [DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.executeDependencyCheck(DependencyCheckExecutor.java:172)
09:23:00 [DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.call(DependencyCheckExecutor.java:103)
09:23:00 [DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.call(DependencyCheckExecutor.java:46)
09:23:00 [DependencyCheck] 	at hudson.remoting.LocalChannel.call(LocalChannel.java:45)
09:23:00 [DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.AbstractDependencyCheckBuilder.perform(AbstractDependencyCheckBuilder.java:85)
09:23:00 [DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckBuilder.perform(DependencyCheckBuilder.java:206)
09:23:00 [DependencyCheck] 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
09:23:00 [DependencyCheck] 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
09:23:00 [DependencyCheck] 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
09:23:00 [DependencyCheck] 	at hudson.model.Build$BuildExecution.build(Build.java:206)
09:23:00 [DependencyCheck] 	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
09:23:00 [DependencyCheck] 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
09:23:00 [DependencyCheck] 	at hudson.model.Run.execute(Run.java:1724)
09:23:00 [DependencyCheck] 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
09:23:00 [DependencyCheck] 	at hudson.model.ResourceController.execute(ResourceController.java:97)
09:23:00 [DependencyCheck] 	at hudson.model.Executor.run(Executor.java:421)
09:23:00 [DependencyCheck] Caused by: java.io.IOException: No space left on device
09:23:00 [DependencyCheck] 	at java.io.FileOutputStream.writeBytes(Native Method)
09:23:00 [DependencyCheck] 	at java.io.FileOutputStream.write(FileOutputStream.java:326)
09:23:00 [DependencyCheck] 	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1793)
09:23:00 [DependencyCheck] 	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
09:23:00 [DependencyCheck] 	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1744)
09:23:00 [DependencyCheck] 	at org.owasp.dependencycheck.analyzer.AssemblyAnalyzer.prepareFileTypeAnalyzer(AssemblyAnalyzer.java:221)
09:23:00 [DependencyCheck] 	... 20 more

**Comment by jeremylong** [comment]
Dependency-check initially downloads ~900 MB of data. It does delete the data when it is done (or least it makes an attempt to). If you are running multiple instances of dependency-check I would highly suggest changing to use a [centralized database](https://jeremylong.github.io/DependencyCheck/data/database.html) instead of the embedded H2.
