### ISSUE TITLE
Error finding/loading main class org.owasp.dependencycheck.App

### ISSUE THREAD

**Issue by TwilightMercy** [dependency-check/DependencyCheck#1075]
Hello

I’m having troubles running the CLI version of the 3.1.0 tool.

im running the following command:

SCRIPT_PATH/dependency-check.bat —project Test —scan FOLDER_TO_SCAN —out OUTPUT_PATH/report.html

And I get the following error:
Error: Could not find or load main class org.owasp.dependencycheck.App

I confirmed and all the tools files exist, nothing is missing.

**Comment by TwilightMercy** [comment]
Any help? :D

**Comment by jeremylong** [comment]
I've never seen this before and have no idea what is going on.  What OS are you using and what version of java are you using?

**Comment by TwilightMercy** [comment]
Windows server 2012
and latest java version (updated)

**Comment by jeremylong** [comment]
Oracle Java, OpenJDK?  Mind running  `java -version` and providing the results?

Also, are you trying to run `dependency-check.bat` from the command line or via a script? Instead of using 'PATH\TO\SCRIPT\dependency-check.bat` can you try:

```cmd
pushd PATH\TO\SCRIPT
dependency-check.bat —project Test —scan FOLDER_TO_SCAN —out OUTPUT_PATH/report.html
popd
```

**Comment by TwilightMercy** [comment]
What does the pushd and popd help/change the execution of the command?

**Comment by jeremylong** [comment]
I'm trying to narrow down where the problem is.  If you run the `dependency-check.bat` from the directory it exists in vs running it from a different directory affects this (i.e. is the current working directory not being the location of the script causing an issue)..

**Comment by tysonkamp** [comment]
Here's my output (same issue).  Did the OP figure out it's a silly mistake and quit asking?

[snip]\AppSecurity\DependencyCheck\bin>java -version
java version "1.6.0_31"
Java(TM) SE Runtime Environment (build 1.6.0_31-b05)
Java HotSpot(TM) Client VM (build 20.6-b01, mixed mode, sharing)

[snip]\AppSecurity\DependencyCheck\bin>dependency-check.bat --help
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/owasp/dependencycheck/App : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(Unknown Source)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$000(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
Could not find the main class: org.owasp.dependencycheck.App.  Program will exit.

[snip]\AppSecurity\DependencyCheck\bin>

**Comment by TwilightMercy** [comment]
OP figure out?

**Comment by tysonkamp** [comment]
I thought maybe you had discovered a solution and stopped participating in the discussion.  I assume your error was more or less the same as mine.  Hopefully we can get this solved as I'm anxious to show the merits of Dependency Check to my colleagues.

**Comment by jeremylong** [comment]
@tysonkamp Thanks for the JVM information - the minimum required JVM to run dependency-check is 1.7.

**Comment by jeremylong** [comment]
@barronen1 are you positive you are using the latest JVM?  Can you run `java -version` just to be sure? Also, if the error is not the same can you provide the full exception/stacktrace?

**Comment by tysonkamp** [comment]
Thanks Jeremy.  This is totally not your issue but maybe you would know: Is there some reason Oracle's download site for java does not use SSL and does not provide a signature for me to compare to after I download?  I thought these were security basics.

**Comment by tysonkamp** [comment]
Workaround: http://oracle.com download page is insecure, http://java.com is secure.   BTW I'm up and running, thanks again.
