### ISSUE TITLE
HTML output, "fatal error"

### ISSUE THREAD

**Issue by viviparous** [dependency-check/DependencyCheck#108]
Version 1.1.4 CLI

Process any JAR. Default output (HTML).

"INFO: Analysis Starting
[Fatal Error] :6:3: The element type "hr" must be terminated by the matching end-tag "</hr>".
10-Apr-2014 11:14:23 AM org.owasp.dependencycheck.Engine analyzeDependencies
INFO: Analysis Complete"

**Comment by jeremylong** [comment]
Can you run this enabling logging and send me the log file?

Jeremy

**Comment by viviparous** [comment]
Hello Jeremy, the attached contains the stacktrace.

---

On Thu, 4/10/14, Jeremy Long notifications@github.com wrote:

 Subject: Re: [DependencyCheck] HTML output, "fatal error" (#108)
 To: "jeremylong/DependencyCheck" DependencyCheck@noreply.github.com
 Cc: "viviparous" upis1468@yahoo.com
 Received: Thursday, April 10, 2014, 11:58 AM

 Can you run this enabling logging and send
 me the log file?

**Comment by viviparous** [comment]
Seems that you did not receive the attachment.

**Comment by jeremylong** [comment]
Thanks! Basically, this is an ignorable fatal error that comes from the fact that the NexusAnalyzer tries to do a hash identification using a query such as:

https://repository.sonatype.org/service/local/identify/sha1/9977a8d04e75609cf01badc4eb6a9c7198c4c5ea

This was resulting in a 404 (although I'm not sure if the HTTP Status code was actually a 404 or not - I didn't check while the error was happening). The NexusAnalyzer was trying to parse the 404 error page and the SAX Parser being used appears to send a fatal to standard error. I just added some code to check the status code and if it is not 200 we don't attempt to parse the results anymore. This should fix the fatal error message you were seeing.

On a side note, the report should have been generated and would be accurate - although it wouldn't be able to point back to central when the artifact was identified there.

The patch for this bug has been pushed to 1.1.5-SNAPSHOT and I am closing this issue.

Thanks for reporting the bug!
