### ISSUE TITLE
Glassfish false positives

### ISSUE THREAD

**Issue by javixeneize** [dependency-check/DependencyCheck#1080]
Hi

Another false positive detected. Can this be added to the original supression list/

Im using javax.interceptor-api-3.1.jar, and it comes with a vulnerability with CPE cpe:/a:oracle:glassfish:3.1.

Those are different libraries

Thanks

**Comment by jeremylong** [comment]
Thanks, I will do a sweep through all of the FP reports before the next release.

**Comment by jeremylong** [comment]
This appears to be resolved in 3.1.2.
