### ISSUE TITLE
NVD date of update in Dependency Check Report

### ISSUE THREAD

**Issue by sivaswami** [dependency-check/DependencyCheck#1082]
This is more of a feature request:

I use DependencyCheck with local NVD database. The local NVD database will be updated frequently (a week or month). I want to check if the report was created with recent/latest NVD database version or old version.
It would be helpful if the DependencyCheck report contains the Date or Version of the NVD database.

**Comment by stevespringett** [comment]
The JSON and XML reports have this information. Towards the top of the file is the name of the feed along with a timestamp.

```xml
<scanInfo>
    <engineVersion>3.1.1-SNAPSHOT</engineVersion>
    <dataSource>
        <name>NVD CVE 2002</name>
        <timestamp>12/01/2018 23:36:33</timestamp>
    </dataSource>
    <dataSource>
        <name>NVD CVE 2003</name>
        <timestamp>11/01/2018 22:52:31</timestamp>
    </dataSource>
    <dataSource>
        <name>NVD CVE 2004</name>
        <timestamp>06/12/2017 09:20:13</timestamp>
    </dataSource>
    <dataSource>
        <name>NVD CVE 2005</name>
        <timestamp>21/12/2017 12:33:02</timestamp>
    </dataSource>
    <dataSource>
        <name>NVD CVE 2006</name>
        <timestamp>11/01/2018 22:52:48</timestamp>
    </dataSource>
    <dataSource>
        <name>NVD CVE 2007</name>
        <timestamp>11/01/2018 22:53:37</timestamp>
    </dataSource>
    <dataSource>
        <name>NVD CVE 2008</name>
        <timestamp>11/01/2018 22:54:28</timestamp>
    </dataSource>
    <dataSource>
        <name>NVD CVE 2009</name>
        <timestamp>11/01/2018 22:55:16</timestamp>
    </dataSource>
    <dataSource>
        <name>NVD CVE 2010</name>
        <timestamp>13/01/2018 14:56:57</timestamp>
    </dataSource>
    <dataSource>
        <name>NVD CVE 2011</name>
        <timestamp>13/01/2018 14:57:28</timestamp>
    </dataSource>
    <dataSource>
        <name>NVD CVE 2012</name>
        <timestamp>13/01/2018 14:57:56</timestamp>
    </dataSource>
    <dataSource>
        <name>NVD CVE 2013</name>
        <timestamp>13/01/2018 14:58:22</timestamp>
    </dataSource>
    <dataSource>
        <name>NVD CVE 2014</name>
        <timestamp>13/01/2018 14:58:52</timestamp>
    </dataSource>
    <dataSource>
        <name>NVD CVE 2015</name>
        <timestamp>13/01/2018 14:59:33</timestamp>
    </dataSource>
    <dataSource>
        <name>NVD CVE 2016</name>
        <timestamp>14/01/2018 14:24:25</timestamp>
    </dataSource>
    <dataSource>
        <name>NVD CVE 2017</name>
        <timestamp>14/01/2018 14:25:34</timestamp>
    </dataSource>
    <dataSource>
        <name>NVD CVE 2018</name>
        <timestamp>14/01/2018 14:26:51</timestamp>
    </dataSource>
    <dataSource>
        <name>NVD CVE Checked</name>
        <timestamp>24/01/2018 22:22:13</timestamp>
    </dataSource>
    <dataSource>
        <name>NVD CVE Modified</name>
        <timestamp>24/01/2018 22:21:58</timestamp>
    </dataSource>
</scanInfo>
```
Each feed doesn't have a version per-se. But a timestamp should be relevant if you want to verify you're using a recently updated feed.

**Comment by sivaswami** [comment]
@stevespringett  Thanks for your reply.

I see each NVD timestamp is present in JSON and XML files.

I understand correctly, dependency-check creates a h2 database (dc.h2.db) from all these NVD entries.
For example: Here the cumulative database preparation date is Jan 26th.
-rw-r--r-- 1 sivaswami mygrp 313737216 Jan 26 08:50 dc.h2.db

I want to know when I last updated the file dc.h2.db from the report. Is report based on old local  database or new database file.  So it would be helpful to include the line:

Report based on NVD database downloaded on date : Jan 26

in the report.
Your inputs ?

**Comment by stevespringett** [comment]
I don't see how a single field in the database would be useful. I think if someone assumes that all NVD updates will be successful and assumes that environments with NVD mirrors are always kept up-to-date, then a single field in the database might be useful, but in general, I think it would provide a false sense of 'freshness'. Documenting the last update to the H2 database != the last update from the NVD (successful or not).

The way the NVD data feeds work is that the 'modified' feed contains existing CVEs which have been altered from their original state. I think checking that all feeds have valid timestamps and then going off the timestamp of the modified feed, would provide a much better understanding on the freshness of the data.

If the goal is to simply know when the last update was performed on the H2 database, without any regard for the freshness of the data being updated, then checking the files 'last modified' property on the filesystem would suffice.

Currently, these are the database properties that we track timestamps on.

<img width="315" alt="screen shot 2018-01-28 at 2 50 19 pm" src="https://user-images.githubusercontent.com/3878933/35486924-f5a648c0-043a-11e8-9e9c-4e0b22d35c9c.png">

**Comment by sivaswami** [comment]
The timestamps provided by NVD dates don't reveal when I updated my local database. It could be still a past date. 
for example: if I update local database on Jan 29th and Jan 30th chances are more for getting same NVD dates. However I can't really predict when my last sync with NVD has happened. 

@stevespringett ,I agree to your idea of checking the last modified date for NVD filename is good. But if I am sharing the report with someone who doesn't want's to go and check the NVD file in some machine and instead get it in report itself.

**Comment by jeremylong** [comment]
> "It would be helpful if the DependencyCheck report contains the Date or Version of the NVD database."

The only thing that exists are the timestamps. The NVD doesn't publish a version as they have frequent updates.

**Comment by sivaswami** [comment]
Fine with the synchronization timestamp of  the current local database.  It will be same for consecutive runs with same local database (without synchronization)
