### ISSUE TITLE
exclude path in the Jenkins plugin

### ISSUE THREAD

**Issue by metalmorfoza** [dependency-check/DependencyCheck#1083]
Hi,

I want to exclude several directories from the Dependency check. I have a step "Invoke dependency-check analysis", and there is a field "Path to scan", but no "Path to exclude". I was searching for solution, but only one, that I found is "--exclude" in the CLI. Is there a similar parameter in the Jenkins plugin? Plugin version is 3.1.1.
Thank you

**Comment by stevespringett** [comment]
The Jenkins plugin (like most other plugins) utilizes Ant-style patterns. Multiple patterns can be stringed together to create an effective scan path.

If you want to exclude, you will need to omit them when using the patterns. The plugin does not support an exclude path specifically.

**Comment by metalmorfoza** [comment]
Thank you for the answer. 
I already have a pattern to include most of the directories, but that's an error-prone solution, when new modules are added, the plugin won't scan them.

**Comment by jeremylong** [comment]
If using maven builds (guessing Maven as you indicated new modules) - dependency-check should be run as a maven plugin and then use the jenkins publish (steve can provide more details if needed).

**Comment by stevespringett** [comment]
Agreed. If using Maven, use the Maven plugin as you'll get better, more accurate results. Ensure you output the XML report from Maven. Then, in the Jenkins job configuration, remove the Dependency-Check build step, and ensure the Dependency-Check publishing step is added. The publisher will read the report contents from the Maven plugin.
