### ISSUE TITLE
CLI only checks two things with RubyOnRails project: Gemfile.lock and Gemfile.lock:nokogiri and complains "Did not find org.owasp.dependencycheck.analyzer.RubyGemspecAnalyzer"

### ISSUE THREAD

**Issue by philCryoport** [dependency-check/DependencyCheck#1086]
NOTE: I'm not the dev here; I'm the DevOps guy whose previous experience is in large Java and PHP deployments, so I'm learning this stuff on the fly.

* Ruby is 2.3.6
* Rails is 5.0.1

Not sure how to securely send you the Dependency Checker CLI debug log -- obviously, I don't want to advertise which gems we're using in our RubyOnRails project...

Downloaded OWASP Dependency Checker 3.1.1 release and built on Ubuntu x64 with OpenJDK 8.

Ran CLI with:
```
% cd ~/DependencyCheck-3.1.1/dependency-check-cli/target/release/bin
 % ./dependency-check.sh --project "Foo" --scan "/home/bar/foo"
[INFO] Checking for updates
[INFO] Skipping NVD check since last check was within 4 hours.
[INFO] Check for updates complete (65 ms)
[INFO] Analysis Started
[INFO] Finished Archive Analyzer (0 seconds)
[INFO] Launching: [bundle-audit, check, --verbose] from /tmp/dctempc959a0b8-966e-482e-a9f8-acaf9f469e7f
[INFO] Ruby Bundle Audit Analyzer is enabled. It is necessary to manually run "bundle-audit update" occasionally to keep its database up to date.
[WARN] Did not find org.owasp.dependencycheck.analyzer.RubyGemspecAnalyzer.
[INFO] Launching: [bundle-audit, check, --verbose] from /home/pschlesinger/cryoportal-v2
[INFO] Finished Ruby Bundle Audit Analyzer (0 seconds)
[INFO] Finished File Name Analyzer (0 seconds)
[INFO] Finished Dependency Merging Analyzer (0 seconds)
[INFO] Finished Version Filter Analyzer (0 seconds)
[INFO] Finished Hint Analyzer (0 seconds)
[INFO] Created CPE Index (1 seconds)
[INFO] Skipping CPE Analysis for npm
[INFO] Finished CPE Analyzer (1 seconds)
[INFO] Finished False Positive Analyzer (0 seconds)
[INFO] Finished Cpe Suppression Analyzer (0 seconds)
[INFO] Finished NVD CVE Analyzer (0 seconds)
[INFO] Finished Node Security Platform Analyzer (14 seconds)
[INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
[INFO] Finished Dependency Bundling Analyzer (0 seconds)
[INFO] Analysis Complete (16 seconds)
```

The analysis shows that it only finds two gems: `Gemfile.lock` and `Gemfile.lock:nokogiri`.  

Note the `[WARN] Did not find org.owasp.dependencycheck.analyzer.RubyGemspecAnalyzer.` warning.  I can't seem to find documentation of how to reference the RubyGemspecAnalyzer class when running dependency-checker.sh.  Do I edit dependency-checker.sh to force it to add that class (or a JAR which contains that class)?

If I `--enableExperimental`, it finds one additional gem: `redis-store`.  

There should be A LOT more gems being scanned.  

* I am clicking the "show all dependencies" link in the analysis
* I do have bundle-audit installed
* I have run bundle install

I found #477 and tried `bundle-audit --deployment`.  Now when I try running the CLI on my RubyOnRails project, I get the following error whether or not I specify `--enableExperimental`:

```
[WARN] bundle-audit failure
java.io.IOException: Unable to create temporary gem file
        at org.owasp.dependencycheck.analyzer.RubyBundleAuditAnalyzer.createDependencyForGem(RubyBundleAuditAnalyzer.java:478)
        at org.owasp.dependencycheck.analyzer.RubyBundleAuditAnalyzer.processBundlerAuditOutput(RubyBundleAuditAnalyzer.java:329)
        at org.owasp.dependencycheck.analyzer.RubyBundleAuditAnalyzer.analyzeDependency(RubyBundleAuditAnalyzer.java:297)
        at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:136)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

Help???

**Comment by jeremylong** [comment]
The `RubyGemspecAnalyzer` is just a wrapper for [bundler-audit](https://github.com/rubysec/bundler-audit). We take the output from `bundle audit` and format it into the dependency-check format so if using multiple languages/tech stacks you can get a single report format.  That being said - can you run `bundle audit` on your code instead of dependency-check?  Trying to narrow down if the issue...

**Comment by lllama** [comment]
So I have same `java.io.IOException: Unable to create temporary gem file` error being thrown. I can run `bundler-audit` on the projects, so I'm wondering whether the error is related to me running depcheck across a number of repos at the same time. The RoR apps have similar dependencies and it looks like the temp gem file is named after the dependency, so two projects with the same dep will cause `createNewFile()` to error. I'm assuming this is due to multiple thread running at once.

Perhaps mixing in some random chars to the file name, or using a temp file API would help?
