### ISSUE TITLE
.NET Assembly Analyzer could not be initialized

### ISSUE THREAD

**Issue by JiaHeLin** [dependency-check/DependencyCheck#1087]
Reporting Bugs/Errors
.NET Assembly Analyzer could not be initialized and at least one 'exe' or 'dll' was scanned. The 'mono' executable could not be found on the path; either disable the Assembly Analyzer or configure the path mono. On some systems mono-runtime and mono-devel need to be installed.

**Comment by JiaHeLin** [comment]
how to solve this problem

**Comment by jeremylong** [comment]
If you are confident that no .NET code is being scanned, then you can disable the Assembly Analyzer. If you are scanning .NET libraries you need to install mono to enable the Assembly Analyzer to work.  

ODC contains an embedded .NET assembly that is used to collect evidence from assemblies; thus a CLR runtime is required when scanning .NET.

**Comment by JiaHeLin** [comment]
ok,thanks for you answer
