### ISSUE TITLE
Second level jar not analysed

### ISSUE THREAD

**Issue by javixeneize** [dependency-check/DependencyCheck#1089]
Hi

I have noticed that dependency check plugin in jenkins (v 3.1.0) doesnt analyse nested jars. It is, if i have a jar called javi.jar, and inside it there are three more jars, those second level jars are not analysed. The report generated only shows the first level jar

I am not 100% sure but i think that in previous versions it was correctly analysed 

Thanks

**Comment by jeremylong** [comment]
When you say `javi.jar` contains nested jars - what exactly do you mean? How are the JAR files nested? Is this like a spring-boot JAR where you physically have:

- javi.jar
  - nested.jar
  - second.jar
  - third.jar

Or are we talking about a one/uber/shaded JAR where the contents of the three JARs (nested, second, third) are contained in the final java.jar?  Or as a third option are we talking about the nested JARs being transitive dependencies?

**Comment by javixeneize** [comment]
That’s it. Its Javi.jar having spring boot jar inside, an springboot having
its dependencies as well

**Comment by jeremylong** [comment]
ODC by default does analyze nested JAR files. Only thing that might be going on is we had to put some special code in to deal with Spring-boot's executable jar option. Is there any chance you can provide the log file? This gets a little more complicated in Jenkins as you I believe you have to configure the Jenkins logging system to capture the output from `org.owasp.dependencycheck` at a debug level. Alternatively, can you download javi.jar and use the CLI for ODC to scan the jar and provide the log file?

**Comment by javixeneize** [comment]
I just saw what is the problem. When there is an application it analyses the dependencies, but, when you analyse a library it doesnt go through it

Thanks
