### ISSUE TITLE
Ability to compare dependency check reports

### ISSUE THREAD

**Issue by seanboylan** [dependency-check/DependencyCheck#109]
I am using dependency checker as part of our automated source code vulnerability scanning.

Currently I have to manually check the dependency check report at the end of the regular scan. It would be extremely useful is DependencyChecker had the ability to:

1) Compare the results of two dependency checker runs (baseline versus current)
2) Report on any differences between the two reports.
3) Allow an acceptance threshold to be defined based on risk rating (CVSS score)
i.e if the only difference is CVE'S with a score less than 4.3 then consider them to be comparable.

**Comment by jeremylong** [comment]
I apologize about the delayed response... I've been giving this some thought and I do not plan on adding this type of functionality directly into dependency-check. However, there are options to achieve your goals.

1) Consider using Jenkins to run your dependency-check scans. This will have some charts, history, and I believe a listing of "new" entries.
2) Consider using ThreadFix to track the issues identified by dependency-check. ThreadFix is a great vulnerability management system with several very cool features: https://github.com/denimgroup/threadfix
3) We are planning on building a sonar cube plugin - but this has taken a back burner to some of the other tasks we have. This will likely end up allowing similar tracking to Jenkins; but like I said it isn't built yet, so you could either help us build it or wait for it to be completed.
4) While I should know the status of this project - there is also dependency-track: https://github.com/stevespringett/dependency-track

Best Regards,

Jeremy

**Comment by seanboylan** [comment]
Hi Jeremy,

Thank you for the feedback. I did some digging this morning and realised that dependencychecker can generate a vuln html report. I am going to use this as the basis of comparing reports between scans.

My aim here is to automate the process so that manual checking is only required when a new vulnerability is reported.

I would like to work on the sonar plugin but didn't get permission to do so - I will check again.

Sean
