### ISSUE TITLE
update-only goal should ignore autoUpdate setting

### ISSUE THREAD

**Issue by DevInsanity** [dependency-check/DependencyCheck#1090]
In our setup, we have the dependency-check-maven plugin defined in a root pom, from which other projects inherit. We've configured this to use a centralized database (rather than having multiple machines download and maintain their own copies). This pom is configured with autoUpdate set to false.

There is a scheduled task which explicitly executes the update-only goal (using the same pom). However, due to the autoUpdate setting, the update-only goal doesn't actually perform any updates. We've managed to work around this, but it would be nice if the explicit update request was honoured in this circumstance.

**Comment by jeremylong** [comment]
Great suggestion - thanks!
