### ISSUE TITLE
CLI not available in Central

### ISSUE THREAD

**Issue by mosabua** [dependency-check/DependencyCheck#1096]
The zip archive that contains the runnable CLI version of the dependency check is not available in the Central repository. 

See http://repo1.maven.org/maven2/org/owasp/

ArtifactId from https://github.com/jeremylong/DependencyCheck/tree/master/dependency-check-cli is missing. 

Can the deployment to central be changed to include the binary please? 

The reason I am requesting this is that corporate policies and procedures often have a process for Central in place and it is relatively easy to hook into that. Access to a bintray URL (e.g. http://dl.bintray.com/jeremy-long/owasp/dependency-check-3.1.1-release.zip) is a lot harder to get approved and set up and that make adoption of dependency check much easier.

Afaik the Maven build can easily upload the zip as well and bintray could also be configured to sync to Central. Ping me if you need help with testing or setting that up.

**Comment by jeremylong** [comment]
Would it make a difference if the JAR was in a different bintray directory? Or is it just bintray entirely? A know a ton of folks that use bintray and jcenter heavily within their organizations.

**Comment by mosabua** [comment]
We need the full zip archive as well as the JAR and jcenter or bintray would not really help. We can not get that opened up and are forced into creating a custom download and install process.

**Comment by Janpopan** [comment]
can this closed

**Comment by mosabua** [comment]
I have no need for this anymore .. but other users might. And I am not sure what the current situation is. @jeremylong can probably chime in.

**Comment by jeremylong** [comment]
The CLI is available via GitHub Releases. No plans to place the zip into central.
