### ISSUE TITLE
Add functions to send reports to dependency-track.

### ISSUE THREAD

**Issue by stboissdev** [dependency-check/DependencyCheck#1098]
can you add functions to send reports to dependency-track in maven plugin like jenkins plugin?

**Comment by jeremylong** [comment]
This will likely be completed once dependency-track v3 is released.

**Comment by stevespringett** [comment]
Yes, I plan on putting this capability into the dependency-check core module so that dependency-check implementations, such as the maven plugin, would be able to use it.

**Comment by stboissdev** [comment]
thank's for your answers 
I look forward to the release of dependency-track and the integration of this function in dependency-check.

**Comment by stevespringett** [comment]
No longer a best practice.
