### ISSUE TITLE
Containing war/ear not reported with vulnerabilities when contents are

### ISSUE THREAD

**Issue by jeffersonparke** [dependency-check/DependencyCheck#1100]
We're using OWASP Dependency-Check Plugin 3.1.1 (Dependency-Check Core 3.1.1). 

When we scan a directory containing jars, wars, and ears, any jars with vulnerabilities are reported, but when the same jar is contained in a war or ear that war/ear is not reported as having any vulnerabilities. Is this by design? Is there any configuration option to affect this?

Thanks!

**Comment by jeremylong** [comment]
ODC should be interrogating the contents of the WAR/EAR as well. Couple of question:

1. Can you provide the exact command line you are using to scan a WAR where the dependency is not identified?
2. Assuming you are using the CLI - can you add `--log dc.log` to the command line and provide the log file?
