### ISSUE TITLE
DB Connection Access Mode duplicated

### ISSUE THREAD

**Issue by anderruiz** [dependency-check/DependencyCheck#1108]
During the execution of engine.openDatabase(boolean, boolean) a concatenation to DB_CONNECTION_STRING is being done including "ACCESS_MODE_DATA=r" this works the first time, but if a second time is executed then the value is set to:

ACCESS_MODE_DATA=rACCESS_MODE_DATA=r

Which causes an error trying to create a RandomAccessFile with mode=rACCESS_MODE_DATA=r.

Perhaps a protection should be placed so that it includes the ACCESS_MODE_DATA only if it is not present

**Comment by jeremylong** [comment]
Can I ask how you ran into this issue? Where you using the API in a tool you are building or via one of the tools provided by the ODC project (maven, cli, etc.)?  While I just put the fix in - I'm asking because if you were using one of the core tools then there may be another bug in play...
