### ISSUE TITLE
Report files contain an exorbitant amount of whitespace characters

### ISSUE THREAD

**Issue by randomstability** [dependency-check/DependencyCheck#1120]
Java version: "1.8.0_162"

OS: Windows 7 Enterprise 64 bit
Service Pack: SP1
Patch level: Current through February 2018

DependencyCheck version: 3.1.1 CLI

This isn't critical but gives concerns over the robustness of the parsing occurring.

I don't feel I need to provide any example report.  But I used WebGoat as the file to scan (again, like my last report).  Almost half the report file size is from whitespace characters.  This is doubling the size of the output files.

There could easily be multiple sources of this whitespace bloat, but it seems like it could be a simple task to trim whitespace.  I'm no expert so I could be wrong.  Ideally locating the source calls causing this is best,  but that could be tedious.

This is fairly easy to assess using Notepad++ on Windows and removing all double space strings until they are all gone.  Then repeating this for empty lines and tab characters.  Saving out this reduced file can reveal the character count and size difference.

**Comment by stevespringett** [comment]
Your observation is correct. The JSON and XML reports are designed to be both human and machine readable. 

Compressing the HTML report by default might be an acceptable thing to do. I'm not sure about the JSON or XML reports though. This might need to be an option as I find myself going into these reports on a regular basis to view them. Having to add whitespace to make them human readable again just creates a new problem.

But perhaps an option to compress the resulting report might be useful.

**Comment by randomstability** [comment]
Thanks for the explanation.  At the least,  an option/flag would be nice, as I'm not dealing with small HTML reports here.

Also isn't whitespace irrelevant for modern file editors/viewers?  Don't they all format the data in a structured format?  I know a basic text editor won't but why is anyone using one?

**Comment by stevespringett** [comment]
The use case I'm thinking of where whitespace is required is in the Jenkins plugin. In Jenkins, the XML report is used. The HTML report can optionally be generated but cannot be viewed from Jenkins because the report violates the default CSP settings, so most users don't bother. But viewing the XML report from the Jenkins workspace is something I always find myself doing.  So in these cases, the report would need to be human readable.

I recently scanned a Nexus repo with Dependency-Check which resulted in a report exceeding a few hundred megabytes, so I totally understand the need to compress as I could have benefited from that feature myself. :-)

**Comment by jeremylong** [comment]
I just created a branch called [compressHtml](https://github.com/jeremylong/DependencyCheck/branches) that will compress the HTML reports. It could definately use some improvements - or maybe taking a completely different approach and having a _compressed_ html template and an [uncompressed version](https://github.com/jeremylong/DependencyCheck/blob/master/core/src/main/resources/templates/htmlReport.vsl) used when we need to update the template (but this would require recompressing the template each time).

Also, the branch currently only compresses the HTML version. I could see adding a configuration option to pretty print the XML or JSON reports vs. compressed.

**Comment by stevespringett** [comment]
IMO dynamic compression is the way to go. I'm not interested in having to maintain different templates for these because I know they'l get out of sync.

With that said, I wonder if there are performance issues with large reports and dynamic compression.

**Comment by stevespringett** [comment]
One option would be to dynamically create the compressed template during packaging `mvn package`, not have it checked into version control, etc.

**Comment by jeremylong** [comment]
Did a tiny bit of research and found a technique that allows us to keep indentation, etc. for purposes of future editing at the cost of making the template slightly uglier with lots of extra `#**   *#[code]##`. See https://github.com/jeremylong/DependencyCheck/commit/2ebbd30f76a801a8cb05ec87e7b8fed7d45526ba.

**Comment by jeremylong** [comment]
This was included in the 3.2.0 release.  However, the JSON report is still be pretty printed - leaving this ticket open until we can add an option to control this behavior.

**Comment by jeremylong** [comment]
This issue was fully resolved in the 5.x code base.
