### ISSUE TITLE
NodePackageAnalyzer is confused by package-lock.json

### ISSUE THREAD

**Issue by migounette** [dependency-check/DependencyCheck#1122]
Version: 3.1.1

Line 187, I didn't dig too much, but the issue is here, the tool tries to get a name but the package-lock.json does not have one.

  try (JsonReader jsonReader = Json.createReader(FileUtils.openInputStream(dependencyFile))) {
            final JsonObject json = jsonReader.readObject();
            final String parentName = json.getString("name");
            final String parentVersion = json.getString("version");
            final String parentPackage = String.format("%s:%s", parentName, parentVersion);
            processDependencies(json, baseDir, dependencyFile, parentPackage, engine);
        } catch (JsonException e) {
            LOGGER.warn("Failed to parse package.json file.", e);
        } catch (IOException e) {
            throw new AnalysisException("Problem occurred while reading dependency file.", e);
        }

Log:
https://gist.github.com/migounette/fea9bcb88df8000f01e3bb614df5d4ac

It's a project that uses maven front end plugin, npm version 5.x and nodejs 8.9.x

bash-4.2$ ls -l /var/lib/jenkins/workspace/SEE-OWASP/specs/                                                                  total 120
drwxr-xr-x.   2 jenkins jenkins     6 Feb 28 17:54 etc
drwxr-xr-x.   3 jenkins jenkins    36 Feb 28 17:54 node
drwxr-xr-x. 186 jenkins jenkins  8192 Feb 28 17:55 node_modules
**-rw-r--r--.   1 jenkins jenkins 53734 Feb 28 17:55 package-lock.json**
-rw-r--r--.   1 jenkins jenkins  8298 Feb 28 17:52 pom.xml
-rw-r--r--.   1 jenkins jenkins  1595 Feb 28 17:52 rpm-build.mustache
drwxr-xr-x.   2 jenkins jenkins    25 Feb 28 17:55 target

Java command line executed:
``` bash
/bin/java -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8001,suspend=n -classpath '/home/jenkins/dependency-check/plugins/*:/home/jenkins/dependency-check/repo/commons-cli/commons-cli/1.4/commons-cli-1.4.jar:/home/jenkins/dependency-check/repo/org/owasp/dependency-check-core/3.1.1/dependency-check-core-3.1.1.jar:/home/jenkins/dependency-check/repo/com/vdurmont/semver4j/2.1.0/semver4j-2.1.0.jar:/home/jenkins/dependency-check/repo/joda-time/joda-time/1.6/joda-time-1.6.jar:/home/jenkins/dependency-check/repo/org/apache/commons/commons-compress/1.15/commons-compress-1.15.jar:/home/jenkins/dependency-check/repo/org/objenesis/objenesis/2.6/objenesis-2.6.jar:/home/jenkins/dependency-check/repo/commons-io/commons-io/2.6/commons-io-2.6.jar:/home/jenkins/dependency-check/repo/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar:/home/jenkins/dependency-check/repo/org/apache/lucene/lucene-core/5.5.5/lucene-core-5.5.5.jar:/home/jenkins/dependency-check/repo/org/apache/lucene/lucene-analyzers-common/5.5.5/lucene-analyzers-common-5.5.5.jar:/home/jenkins/dependency-check/repo/org/apache/lucene/lucene-queryparser/5.5.5/lucene-queryparser-5.5.5.jar:/home/jenkins/dependency-check/repo/org/apache/lucene/lucene-queries/5.5.5/lucene-queries-5.5.5.jar:/home/jenkins/dependency-check/repo/org/apache/lucene/lucene-sandbox/5.5.5/lucene-sandbox-5.5.5.jar:/home/jenkins/dependency-check/repo/org/apache/velocity/velocity/1.7/velocity-1.7.jar:/home/jenkins/dependency-check/repo/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar:/home/jenkins/dependency-check/repo/commons-lang/commons-lang/2.4/commons-lang-2.4.jar:/home/jenkins/dependency-check/repo/com/h2database/h2/1.4.196/h2-1.4.196.jar:/home/jenkins/dependency-check/repo/org/glassfish/javax.json/1.0.4/javax.json-1.0.4.jar:/home/jenkins/dependency-check/repo/org/jsoup/jsoup/1.11.2/jsoup-1.11.2.jar:/home/jenkins/dependency-check/repo/com/sun/mail/mailapi/1.6.0/mailapi-1.6.0.jar:/home/jenkins/dependency-check/repo/com/google/code/gson/gson/2.8.2/gson-2.8.2.jar:/home/jenkins/dependency-check/repo/org/owasp/dependency-check-utils/3.1.1/dependency-check-utils-3.1.1.jar:/home/jenkins/dependency-check/repo/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar:/home/jenkins/dependency-check/repo/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar:/home/jenkins/dependency-check/repo/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar:/home/jenkins/dependency-check/repo/org/apache/ant/ant/1.9.9/ant-1.9.9.jar:/home/jenkins/dependency-check/repo/org/owasp/dependency-check-cli/3.1.1/dependency-check-cli-3.1.1.jar' -Dapp.name=dependency-check -Dapp.pid=16718 -Dapp.repo=/home/jenkins/dependency-check/repo -Dapp.home=/home/jenkins/dependency-check -Dbasedir=/home/jenkins/dependency-check org.owasp.dependencycheck.App --project SEE-OWASP --scan /var/lib/jenkins/workspace/SEE-OWASP --out /var/lib/jenkins/workspace/SEE-OWASP --format HTML --noupdate --data /home/jenkins/nvdUpdates --disableCentral --proxyserver myweb-proxy-replaced.com --proxyport 8080
```

**Comment by jeremylong** [comment]
If you are only using the front-end maven plugin I might consider disabling the Node and NSP analyzers. Regardless, we will look into the problem.

**Comment by jeremylong** [comment]
I believe this was resolved.
