### ISSUE TITLE
UPDATE For Issue 897 - Still seeing small scanning issues

### ISSUE THREAD

**Issue by randomstability** [dependency-check/DependencyCheck#1128]
I have returned to check on  [Issue #897](https://github.com/jeremylong/DependencyCheck/issues/897) and it may be greatly improved in version 3.1.1, but I've still identified some small differences across multiple runs of the same scan.

**Updated:**
Java version: "1.8.0_162"

OS: Windows 7 Enterprise 64 bit
Service Pack: SP1
Patch level: Current through February 2018

DependencyCheck version: 3.1.1 CLI

========================================

The issues seem to be in the evidence section.  Multiple report runs said there were 31 pieces,  another set of reports said 33.  I have not tested more in-depth to know if it varies by more than this one example.  

Probably not critical enough to focus on yet.  But just in case this indicates that the main findings could also be off, I want to report it here. 

If it helps, these are the results searching for a some example strings.

**Report 1:**
string: ">1.2.17<"
```
Line 12337:  <tr><td>Version</td><td>Manifest</td><td>Bundle-Version</td><td>1.2.17</td><td>High</td></tr>
Line 12388:  <tr><td>Version</td><td>central</td><td>version</td><td>1.2.17</td><td>High</td></tr>
Line 12532:  <tr><td>Version</td><td>file</td><td>version</td><td>1.2.17</td><td>Highest</td></tr>
Line 12594:  <tr><td>Version</td><td>manifest: org.apache.log4j</td><td>Implementation-Version</td><td>1.2.17</td><td>Medium</td></tr>
Line 12672:  <tr><td>Version</td><td>pom</td><td>version</td><td>1.2.17</td><td>Highest</td></tr>
```
string: "manifest: org.apache.log4j"
```
Line 10022:  <tr><td>Product</td><td>manifest: org.apache.log4j</td><td>Implementation-Title</td><td>log4j</td><td>Medium</td></tr>
Line 11565:  <tr><td>Vendor</td><td>manifest: org.apache.log4j</td><td>Implementation-Vendor</td><td>&quot;Apache Software Foundation&quot;</td><td>Medium</td></tr>
Line 12594:  <tr><td>Version</td><td>manifest: org.apache.log4j</td><td>Implementation-Version</td><td>1.2.17</td><td>Medium</td></tr>
```

**Report 2:** 
string: ">1.2.17<" - Missing the two "manifest" entries.
```
Line 12388:  <tr><td>Version</td><td>central</td><td>version</td><td>1.2.17</td><td>High</td></tr>
Line 12532:  <tr><td>Version</td><td>file</td><td>version</td><td>1.2.17</td><td>Highest</td></tr>
Line 12672:  <tr><td>Version</td><td>pom</td><td>version</td><td>1.2.17</td><td>Highest</td></tr>
```
string: "manifest: org.apache.log4j" - missing the Version entry.
```
Line 10022:  <tr><td>Product</td><td>manifest: org.apache.log4j</td><td>Implementation-Title</td><td>log4j</td><td>Medium</td></tr>
Line 11565:  <tr><td>Vendor</td><td>manifest: org.apache.log4j</td><td>Implementation-Vendor</td><td>&quot;Apache Software Foundation&quot;</td><td>Medium</td></tr>
```

**Comment by jeremylong** [comment]
Thanks for the examples. I am going to have to dig into this more and see if I can figure out what is going on.  Has this only been happening in the version evidence?

**Comment by randomstability** [comment]
I have only done minimal testing as shown.  As it is very hard to compare the files with the various whitespace bloat concerns, as well as imperfect text editor (Notepad++) support for huge files .

**Comment by randomstability** [comment]
As a troubleshooting process,  the same applies as my last bug report.  Just run the same scan over and over.  Simply compare the html report file sizes for any differences.  It again happened within 10 report runs.

No clue what testing is done during build,  but this seems like a test process that should be easy to automate and report as a bug at that time.

**Comment by jeremylong** [comment]
I've tested this several times since reported and I'm unable to re-produce the results.  My testing was done using:

```bash
#/bin/bash

./dependency-check.sh -o . -f HTML -f XML -s ~/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar &>/dev/null;
last=`xpath dependency-check-report.xml "count(//dependencies/dependency/evidenceCollected/evidence)" 2>/dev/null`;

for i in `seq 1 100`;
do
    mv ./dependency-check-report.html ./dependency-check-report-last.html;
    mv ./dependency-check-report.xml ./dependency-check-report-last.xml;
    ./dependency-check.sh -o . -f HTML -f XML -s ~/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar &>/dev/null;
    current=`xpath dependency-check-report.xml "count(//dependencies/dependency/evidenceCollected/evidence)" 2>/dev/null`;
    if [ $current -ne $last ]; then
        echo "evidence count is different";
        echo "last: ${last}";
        echo "current: ${current}";
        break;
    fi
    last=$current;
done

echo "done";
```

I've seen no difference in the evidence count over multiple executions.
