### ISSUE TITLE
Building DependencyCheck from source requires Administrator privileges on Windows

### ISSUE THREAD

**Issue by paulirwin** [dependency-check/DependencyCheck#1132]
When building DependencyCheck from source on Windows for the first time (with a clean git workspace) the build fails on `mvn install` if you aren't running as Administrator.

Error message:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:3.0.2:testResources (default-testResources) on project dependency-check-core: D:\Git\DependencyCheck\core\target\test-classes\nodejs\node_modules\dns-sync\node_modules\.bin\shjs: A required privilege is not held by the client. -> [Help 1]
```

This is coming from the dns-sync NPM package. If you then open up a Powershell window as Administrator and run `mvn install` again, it succeeds.

Reproduction steps:
1. From Powershell as a non-administrator, run `git clean -dxf` to remove all files and folders including those that are ignored by .gitignore from your workspace.
2. Run `mvn install`. Build fails.
3. Open a new Powershell window as an administrator in the repo root.
4. Run `mvn install`. Build succeeds.

For obvious reasons it would be ideal if building DependencyCheck from source did not require Administrator privileges 😄 

Apache Maven 3.3.9
Java 1.8.0_144
NPM 5.6.0
Node 8.9.0
Windows 10.0.16299

**Comment by jeremylong** [comment]
Interesting - thanks for the report. I do not have a current windows 10 machine to debug this atm. It might be related to the blocked property (see [Unblock-File](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/unblock-file?view=powershell-6)).  But in reality, the file in question is never actually used/parsed as part of the test cases. We can safely remove the `shjs` files.

**Comment by stefanneuhaus** [comment]
As I have a Windows 10 system at hand I just had a quick try:
- open PowerShell (as a standard user)
- get a fresh `git clone https://github.com/jeremylong/DependencyCheck.git`
- run `mvn install`

I cannot reproduce the issue, the build completed successfully.
