### ISSUE TITLE
./gradlew dependencyCheckUpdate hangs for MariaDB (although it does insert records)

### ISSUE THREAD

**Issue by andrejvanderzee** [dependency-check/DependencyCheck#1134]
I setup MariaDB and run the dependencyCheckUpdate task. As expected, it does download CVE files and inserts records in the database. Then I expect the task to finish, but it hangs forever. Not even sure if it really completed. This is the task:

```
./gradlew dependencyCheckUpdate --info --stacktrace --debug
```

I used this Gradle dependencyCheck configuration:

```
dependencyCheck {

    data {
      driver = "org.mariadb.jdbc.Driver"
      connectionString = "jdbc:mariadb://abc.com/dependencycheck"
      username = "***"
      password = "***"
      driverPath = "/home/andrej/ing/owasp"
    }
}
```

I am using plugin org.owasp.dependencycheck version '3.1.1'

It downloads CVE and updates the database, but the task never ends. Output here in the Gist:

https://gist.github.com/andrejvanderzee/810c712118bf075b0d67a68cc7eadf1d

**Comment by andrejvanderzee** [comment]
Here a shorter non-debug gist:

https://gist.github.com/andrejvanderzee/4564e671ac04a417541d3cfb237f4c54

**Comment by andrejvanderzee** [comment]
It looks like it downloads all: 

```
Download Complete for NVD CVE - 2002  (4123 ms)
Download Complete for NVD CVE - 2003  (2605 ms)
Download Complete for NVD CVE - 2004  (3183 ms)
Download Complete for NVD CVE - 2005  (3916 ms)
Download Complete for NVD CVE - 2006  (5137 ms)
Download Complete for NVD CVE - 2007  (4884 ms)
Download Complete for NVD CVE - 2008  (5064 ms)
Download Complete for NVD CVE - 2009  (4836 ms)
Download Complete for NVD CVE - 2010  (5715 ms)
Download Complete for NVD CVE - 2011  (10074 ms)
Download Complete for NVD CVE - 2012  (5268 ms)
Download Complete for NVD CVE - 2013  (5432 ms)
Download Complete for NVD CVE - 2014  (5669 ms)
Download Complete for NVD CVE - 2015  (5049 ms)
Download Complete for NVD CVE - 2016  (5316 ms)
Download Complete for NVD CVE - 2017  (9354 ms)
Download Complete for NVD CVE - 2018  (2231 ms)
Download Complete for NVD CVE - Modified  (2077 ms)
```

But only processes some: 
```
Processing Started for NVD CVE - 2002
Processing Started for NVD CVE - 2003
Processing Started for NVD CVE - 2004
Processing Started for NVD CVE - 2005
Processing Started for NVD CVE - 2006
Processing Started for NVD CVE - 2007
Processing Started for NVD CVE - 2008
Processing Started for NVD CVE - 2009
```

The list it processes differs per run. Looks like some deadlock condition.

**Comment by andrejvanderzee** [comment]
I am observing the same behavior for MySQL. Looks like table `vulnerability` is actually filled, but _very_ slowly. So slow, that I doubt if its workable. Probably I am doing something wrong? How can I speed up filling the database?

**Comment by andrejvanderzee** [comment]
I found now that the initial update of the MySQL database takes about 6 hours. Incremental updates afterward take just a minute. So this is workable, but I don't understand the insane increase in time for MySQL/MariaDB compared to H2.

**Comment by jeremylong** [comment]
This was discussed on the google group as well.  I still haven't been able to figure out why the initial load takes so long when using MySQL. However, if people are using docker containers for the builds/scans consider running a the ODC database in a container. See https://hub.docker.com/r/stefanneuhaus/dependencycheck-central-mysql/

**Comment by andrejvanderzee** [comment]
A complete `dependencyCheckUpdate` with H2 database in server mode takes `Total time: 5 mins 5.011 secs`, instead of almost 6 hours.

**Comment by andrejvanderzee** [comment]
Ahhh thanks.

> This was discussed on the google group as well. I still haven't been able
> to figure out why the initial load takes so long when using MySQL. However,
> if people are using docker containers for the builds/scans consider running
> a the ODC database in a container. See https://hub.docker.com/r/
> stefanneuhaus/dependencycheck-central-mysql/
>
>
But the  initialization (first update) of this Docker container still takes
a long time I guess?

**Comment by jeremylong** [comment]
Yes - I believe standing up the container the first time does take time. However, @stefanneuhaus could confirm - although the description of the container says it takes ~30 minutes on his machine.

**Comment by stefanneuhaus** [comment]
Correct, starting up the container takes some time. I again did some testing using [dependencycheck-central-mysql](https://hub.docker.com/r/stefanneuhaus/dependencycheck-central-mysql/) on my MacBook Pro 3rd generation Mid 2015 with SSD. The initial update took ~44 min (so it took longer as the indicated ~30 min). I suppose that the update is disk I/O-bound, s.t. on a system w/o SSD this might take significantly longer.

The database data directory is exposed via mount point `/var/lib/mysql` (still to be documented). I also tested initial update times using bind mounts and tmpfs mounts:
- bind mount `-v /my/local/directory:/var/lib/mysql`: ~41 min
- tmpfs mount `--tmpfs /var/lib/mysql`: ~27 min

If you do not care about persistence of the data the tmpfs mount might be a good option, especially on slow HDD. To use it start via:
```docker run -p 3306:3306 --tmpfs /var/lib/mysql stefanneuhaus/dependencycheck-central-mysql```

I might try to tweak the MYSQL performance sometime in the future. If this does not work out I might also consider providing a dockerized H2-based version for those who care about the initial update time.
