### ISSUE TITLE
False positive on swagger-codegen for "PHP"

### ISSUE THREAD

**Issue by TobiX** [dependency-check/DependencyCheck#1139]
Unfortunatly, swagger-codegen contains a whole bunch of "code templates", which trigger detection of other projects, namely PHP and gradle-wrapper.

Dependency:
```xml
     <dependency>
      <groupId>io.swagger</groupId>
      <artifactId>swagger-codegen</artifactId>
      <version>2.3.1</version>
    </dependency>
```

Reported as:
- cpe:/a:gradle:gradle:2.12 (in swagger-codegen-2.3.1.jar/android/gradle-wrapper.jar)
- cpe:/a:php:php:1.0 (in swagger-codegen-2.3.1.jar/php-symfony/testing/pom.xml)

It seems this suppression should get rid of these false positives:

```xml
  <suppress>
    <notes><![CDATA[
   swagger-codegen contains example code which is detected as gradle or PHP
   ]]></notes>
    <gav regex="true">^io\.swagger:swagger-codegen:.*$</gav>
    <cpe>cpe:/a:php:php</cpe>
    <cpe>cpe:/a:gradle:gradle</cpe>
  </suppress>
```

But that didn't work for me, since the embedded templates are detected as their own artifacts... Help?

**Comment by jeremylong** [comment]
Thanks! I will be making a pass through all the FP before the next release.

**Comment by jeremylong** [comment]
While the PHP findings are obviously false positives - I am questioning the claim that gradle is a FP.  This appears to be the gradle-wrapper for 2.1.2.
