### ISSUE TITLE
Exception when generating JSON format on jira plugins

### ISSUE THREAD

**Issue by fsergot** [dependency-check/DependencyCheck#1141]
Hi,

I am trying to use maven owasp dependency checker on my jira plugin custom devs. I am facing an issue when generating a report in JSON format.
A mvn -X command gives the following exception:

> [DEBUG] Malformed JSON?
> com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 72784 column 61 path $.dependencies[272].identifiers[0].name
>     at com.google.gson.stream.JsonReader.syntaxError (JsonReader.java:1568)
>     at com.google.gson.stream.JsonReader.readEscapeCharacter (JsonReader.java:1559)
>     at com.google.gson.stream.JsonReader.nextQuotedValue (JsonReader.java:1014)
>     at com.google.gson.stream.JsonReader.nextString (JsonReader.java:815)
>     at org.owasp.dependencycheck.reporting.ReportGenerator.prettyPrint (ReportGenerator.java:453)
>     at org.owasp.dependencycheck.reporting.ReportGenerator.pretifyJson (ReportGenerator.java:404)

See full log at [https://gist.github.com/fsergot/609c242ca3f294b10c8f8afbe41a1e43](url)

Note this works for other formats (tested with HTML & XML) so just the JSON fails.

**Comment by jeremylong** [comment]
Is there any chance you could share the generated JSON report that is generated? The debug error is stating that the originally output file could not be read in and pretty-printed. So somehow the original template is generating malformed JSON. However, without an example I would be at loss as how to fix the issue.
