### ISSUE TITLE
Scala support

### ISSUE THREAD

**Issue by javixeneize** [dependency-check/DependencyCheck#1142]
Hi

Is scala supported in the original dependency check?

I have seen a plugin for the tool that might be useful, it is https://github.com/albuch/sbt-dependency-check

Have you ever tested it? Would it worth to add it in the next releases?

Thanks

**Comment by jeremylong** [comment]
I have not personally tested the scala plugin - but it does use the standard dependency-check-core. I know consultancies that do use and recommend the sbt plugin and have reported back good results.

**Comment by albuch** [comment]
Hi @javixeneize. I'm the main committer of the plugin, and we use it on many scala and play projects at the company I'm working for for more than a year now. 
As @jeremylong pointed out correctly the plugin is just a wrapper around the dependency-check-core module of this project, so you get the exact same features as with the other plugins for other build tools as long as sbt supports them.
The plugin is timely updated after every releases of a new version of dependency-check.
We always appreciate your feedback via the issue tracker.

**Comment by javixeneize** [comment]
Hi Alex. Congratulations for the good work here ;)

So, it means that if I run my project against the plain dependency check I
will have the same result as with your plugin?

Thabks

**Comment by albuch** [comment]
You should probably get even more accurate results in comparison to the command line client of dependency check as the GAV is directly extracted form your build.sbt
