### ISSUE TITLE
Question regarding suppressions / related dependencies

### ISSUE THREAD

**Issue by goldzahn** [dependency-check/DependencyCheck#1146]
Hi,

I use the command line version to scan and generate HTML reports.
Scanning one of our applications I discovered the following problem:

The war file contains inter alia the following old tomcat jars:
tomcat-embed-el-7.0.56.jar
tomcat-embed-core-7.0.56.jar
tomcat-embed-logging-juli-7.0.56.jar

Report says:
Dependencies Scanned: 132 (44 unique)
Vulnerable Dependencies: 8
Vulnerabilities Found: 37
Vulnerabilities Suppressed: 0

The only tomcat related vulnerable dependency shown is tomcat-embed-core-7.0.56.jar.
But under "Related Dependencies" also tomcat-embed-logging-juli-7.0.56.jar is shown.

Then I suppressed the tomcat findings for tomcat-embed-core-7.0.56.jar in that war file and rerun.

<?xml version="1.0" encoding="UTF-8"?>
<suppressions xmlns="https://jeremylong.github.io/DependencyCheck/dependency-suppression.1.1.xsd">
   <suppress>
      <notes><![CDATA[
      file name: tomcat-embed-core-7.0.56.jar
      ]]></notes>
      <gav regex="true">^org\.apache\.tomcat\.embed:tomcat-embed-core:.*$</gav>
      <cpe>cpe:/a:apache:tomcat</cpe>
   </suppress>
</suppressions>

But then dependency-check still finds 37 vulns, although it mentions 29 suppressed vulns in the report, because now it finds all of the tomcat related vulns in tomcat-embed-logging-juli-7.0.56.jar.

Report says:
Dependencies Scanned: 132 (45 unique)
Vulnerable Dependencies: 8
Vulnerabilities Found: 37
Vulnerabilities Suppressed: 29

As you can see, it now scans 45 instead of 44 unique dependencies. In the first report, under "Showing all dependencies", only tomcat-embed-el-7.0.56.jar and tomcat-embed-core-7.0.56.jar are shown, whereas in the second report also tomcat-embed-logging-juli-7.0.56.jar is shown.

Is this intended? Do I always have to also suppress cves/cpes for any related dependencies?

Regards
Tim

**Comment by jeremylong** [comment]
Yes, this is the current expected behavior. You would need to suppress the related dependencies. One way to make this easier is that you could use a regex on the GAV in the suppression rule that would cover all the related dependencies.
