### ISSUE TITLE
Could not perform NSP analysis

### ISSUE THREAD

**Issue by jammasterj89** [dependency-check/DependencyCheck#1159]
I am using the Jenkins Dependency-Check Plugin to test a node.js project, however I am seeing some NSP invalid payload errors. I have validated the package.json with [package-json-validator](https://www.npmjs.com/package/package-json-validator) and http://package-json-validator.com/, both say that the package.json is valid. However, it is using git ssh keys. Am I seeing these errors because git ssh keys are not supported? I've linked the package.json and the error log below. Thanks for any help!

package.json:
https://gist.github.com/jammasterj89/76b9be234c49c1598eb9a7ef36747407

error log:
https://gist.github.com/jammasterj89/2f4140464dcae4979697e767c6f3c195

versions:
OWASP Dependency-Check Plugin v3.1.1
Jenkins v2.107.1

**Comment by jeremylong** [comment]
Can you run [NSP](https://github.com/nodesecurity/nsp) directly on the project?

```
npm install -g nsp
nsp check
```

**Comment by jammasterj89** [comment]
Sure, the output is:

> $ nsp check
    (+) No known vulnerabilities found

**Comment by jeremylong** [comment]
I've added some additional logging to assist with debugging this issue.  If you can it would be great if you could download and test the current snapshot; otherwise the logging will be in the next release.

**Comment by jammasterj89** [comment]
Sure, can I ask... do you mean git clone it and build it myself or is there a binary somewhere? Thanks for the help!

**Comment by jeremylong** [comment]
The release (3.2.0) contains the additional logging - it would be great to see the log from your failing NSP analysis via ODC.

**Comment by jammasterj89** [comment]
Thanks @jeremylong, I've ran the job again and the error from the console is below, I can't really notice any difference though, do I need to change any of the config of the job? (The repo has been updated since the last run but nothing drastic as far as I know).

https://gist.github.com/jammasterj89/b049f00517bb763b1eb41ce02a7a0731

**Comment by jeremylong** [comment]
Is there any chance you can get a copy of the workspace locally and use the ODC command line util to generate the log?  I'm asking as the logging level from the Jenkins plugin is not detailed enough (alternatively, if you could get Jenkins to log at debug level). The log produced using the debug level logging would be helpful.

**Comment by jammasterj89** [comment]
Sure, I've ran the CLI against the workspace and this it the output .log (it's pretty big, apologies!):

https://gist.github.com/jammasterj89/f570141151cde488fc2d257bc5e4cc49

**Comment by jeremylong** [comment]
Any chance you could provide `xxxxMobile/WebContent/js/lib/package.json`?  That appears to be one of the files that is tripping up the analyzer and I would like to understand why.

Thanks!

**Comment by jammasterj89** [comment]
Sure, please find below:

    {
    "name": "lib",
    "description": "Libs",
    "version": "1.0",
    "main": "main",
    "dojoBuild": "package.js",
    "dojoVersion": "1.9.1"
    }

and the associated package.js in the same directory:

https://gist.github.com/jammasterj89/cbbbbfc750ca87fac8cb01ba8070296c

**Comment by jeremylong** [comment]
One more question - is `xxxxMobile/WebContent/js/lib/package.json` actually an NPM module? Or something else that is also using the name package.json?

**Comment by jammasterj89** [comment]
xxxxMobile/WebContent/js/lib/package.json is an internal package, not NPM. Hope that helps!

**Comment by jammasterj89** [comment]
Fixed in v5.0.2
