### ISSUE TITLE
False positive on library akka-stream-kafka_2.12-0.19.jar

### ISSUE THREAD

**Issue by laszlovandenhoek** [dependency-check/DependencyCheck#1180]
False positive on library com.typesafe.akka:akka-stream-kafka_2.12:0.19 - reported as cpe:/a:akka:akka:0.19
```xml
<dependency>
    <groupId>com.typesafe.akka</groupId>
    <artifactId>akka-stream-kafka_2.12</artifactId>
    <version>0.19</version>
</dependency>
```
Akka defines several separate modules, which don't follow the numbering scheme of Akka proper. Another is com.typesafe.akka:akka-persistence-cassandra:0.83. There are others but they don't seem to share the same group, so they probably won't be false positives.

**Comment by jeremylong** [comment]
These specific FP have been patched - but like similar libraries with a ton of related dependencies a better strategy needs to be implemented...
