### ISSUE TITLE
New Feature: alphasort the Dependencies in dependency-check-report.html

### ISSUE THREAD

**Issue by davewichers** [dependency-check/DependencyCheck#1183]
If you have even 10 or more dependencies, its hard to review the dependency-check-report.html given that the Dependencies are reported in some order other than Alphabetically.

Can it by default, or at least optionally, alphabetically sort the dependencies in the table at the top, and the details below? That make things easier to find and also lump together similar libraries (e.g., spring-*, commons-*).

**Comment by davewichers** [comment]
An example of a similar report, generated by the Maven Versions plugin is here: https://gleclaire.github.io/findbugs-maven-plugin/dependency-updates-report.html

You can see that this report alpha sorts the dependencies by first by their Group ID and then Artifact ID.  In fact, I think DC should do it this way, by alphasorting on the Coordinates column and also moving the Coordinates column to be the 1st column. Or changing the reported columns to match the Versions report, which I like better.

**Comment by jeremylong** [comment]
There is sorting available within the report by clicking on the column. There are a few enhancements that can be made:

* List should be alpha sorted when the report is first loaded
* The sorting should be made case insensitive

**Comment by jeremylong** [comment]
I believe this has been resolved.
