### ISSUE TITLE
chain of dependency 

### ISSUE THREAD

**Issue by Rancho007** [dependency-check/DependencyCheck#1194]
Currently we don't found any option which display full dependency chain in order to identify the vulnerable lib comes from which dependency.

example, 
Project A -> lib xyz.jar
Project B -> Project A
Project C-> Project B

So currently when dependency analyzer executed on Project C it gives result xyz.jar is vulnerable but it does not gives any path where it comes from.

It could be interesting if we can see the xyz.jar comes from which project/root level project.
This will help to identify the project which contains vulnerable jar directly when there are forest of dependencies.

If any options/parameters exists for this, can you provide?

Thank you.

**Comment by jeremylong** [comment]
How are you running dependency-check?  CLI, maven plugin, etc?

What you are asking for should be in the gradle and maven aggregate reports - however, several users have had issues with the aggregate report and I'm still trying to figure out the best way to solve it.

**Comment by jeremylong** [comment]
Additionally, you could run something like `mvn dependency:tree` to identify the root.

**Comment by Rancho007** [comment]
Thank you for your response.

We are using dependency-check using gradle plugin. Indeed it could possible to use gradle dependency to resolve root.  It could be better if the dependency-checker provides this feature. It will also resolve issue like to add gradle project-report plugin or maven dependency tree plugin as specially there are hundreds of projects. It can simply used dependency-check on jenkins pipeline without modifying pom or gradle build. Thx to all dependency-check powerful features we have aggregate result without having two step process.

Thank you.

**Comment by yrobert** [comment]
Hi guys, it would be really great to have this feature in order to easily identify from where comes a specific vulnerability. Especially on modern architecture with multiple components.

**Comment by aikebah** [comment]
I think this is now covered by the 'included by' that is in the reports for versions 8+
