### ISSUE TITLE
Running dependency check on legacy projects does not generate correct report.

### ISSUE THREAD

**Issue by PrahathessRengasamy** [dependency-check/DependencyCheck#1195]
Hey !  I am currently dabbling with dependency  check and dependency track . I ran the CLI  scan (and in jenkins ) against the legacy esapi tool 
https://github.com/ESAPI/esapi-java-legacy 

which in its dependencies has a bunch of vulnerable ones but the report that was generated showed no vulnerabilities though I manually verified most of the dependencies had high level vulnerabilities.
Also tried on few other older projects and the report was the same.

I simply ran the cli program with the scan path as the root folder of the project.
can anyone help ..Thank you
Attached a sample report:
[sample_report.zip](https://github.com/jeremylong/DependencyCheck/files/1895764/sample_report.zip)

**Comment by stevespringett** [comment]
ESAPI is a Maven project. For best results, the Dependency-Check Maven plugin should be used to analyze the ESAPI code base. By doing so, it will analyze the pom, resolve all the dependencies, and check if each of the dependencies have known vulnerabilities.

The CLI will not go to this extreme since it doesn't know what "Maven" is.

**Comment by PrahathessRengasamy** [comment]
Also a followup question How do I use the Maven or other plugins when  automating this process through jenkins

**Comment by stevespringett** [comment]
In Jenkins, create a new job (a Maven build). Then as one of the build steps you can call the Dependency-Check Maven plugin directly.

Dependency-Check can be integrated into a pom, or called without being integrated.

https://jeremylong.github.io/DependencyCheck/dependency-check-maven/index.html has good instructions and examples for integration.

However, plugins can also be called directly without being integrated into pom. Maven uses the following syntax: 
`mvn groupId:artifactId:version:goal`

With this in mind, you might be able to invoke the Dependency-Check Maven plugin from the command line using something like:
`mvn org.owasp:dependency-check-maven:3.1.2:check`

A similar syntax would be specified if you configured the Maven job in Jenkins to do the same.
