### ISSUE TITLE
Problem with some zip-files

### ISSUE THREAD

**Issue by eoftedal** [dependency-check/DependencyCheck#12]
If there are any invalid zip, it crashes. I would prefer it ignored them with a warning

`Exception in thread "main" java.lang.IllegalArgumentException: MALFORMED
    at java.util.zip.ZipCoder.toString(ZipCoder.java:58)
    at java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:297)
    at java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:121)
    at org.owasp.dependencycheck.analyzer.ArchiveAnalyzer.extractFiles(ArchiveAnalyzer.java:257)
    at org.owasp.dependencycheck.analyzer.ArchiveAnalyzer.analyze(ArchiveAnalyzer.java:180)
    at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:313)
    at org.owasp.dependencycheck.App.runScan(App.java:146)
    at org.owasp.dependencycheck.App.run(App.java:123)
    at org.owasp.dependencycheck.App.main(App.java:72)`

**Comment by jeremylong** [comment]
I'll have to go back and double check some error handling. I updated much of the error handling, in other analyzers, to only display a warning with these types of errors. I'll put a test case together and try and have something pushed tonight (8/12) to fix this.

--Jeremy

**Comment by jeremylong** [comment]
Can you confirm what version you are using? I just tested 1.0.1 and did not receive an exception or crash. In fact, it just ran without an issue (or warning) and produced the report.  I will be fixing the issue regarding the lack of a warning about an invalid archive file.

If you are using 1.0.1 - can you provide a zip file that causes the crash?

**Comment by eoftedal** [comment]
```
$: dependency-check-cli/target/release/bin/dependency-check.sh -v
dependency-check-core version 1.0.1
```

I'm not acutally sure which file is causing the problem. I'll try to make it output the path in question.

**Comment by eoftedal** [comment]
Seems to be a non-.jar zip file in one of the folder where one of the files inside the zip has the norwegian letter å in the file name

**Comment by eoftedal** [comment]
Simplest fix may be to switch from catch(IOException) to catch(Exception) on line 296. Not sure if that has other consequences.

**Comment by jeremylong** [comment]
The problem was solved by using commons-compress instead of java.util.zip. In 1.6 and earlier java.util.zip does not support other character sets.

I have pushed 1.0.2-SNAPSHOT to github. Can you please confirm that the problem is solved?

Thanks!

**Comment by eoftedal** [comment]
Fixed

**Comment by eoftedal** [comment]
Thanks for the quick fix!
