### ISSUE TITLE
Results are different in between Dependency Check Jenkins Plugin and CLI Tool

### ISSUE THREAD

**Issue by Kish-Jadhav** [dependency-check/DependencyCheck#1217]
Hi,
When we run dependency check Jenkins Plugin and [Dependency check CLI tool](https://jeremylong.github.io/DependencyCheck/dependency-check-cli/index.html) on same jar i. e. spring-security-core-4.0.4.RELEASE.jar. The CLI tool reports vulnerability whereas JenkinsPlugin(3.1.0) doesn't. 
Are there any differences in running CLI tool verses Jenkins plugin?

**Comment by philippeckel** [comment]
I have a similar issue.

Running 
``
mvn org.owasp:dependency-check-maven:3.1.2:check
``
reports multiple, valid vulnerabilities while the generated dependency-check-report.html says

> Dependencies Scanned: 0 (0 unique)
> Vulnerable Dependencies: 0
> Vulnerabilities Found: 0
> Vulnerabilities Suppressed: 0

**Comment by stevespringett** [comment]
@Kish-Jadhav I cannot reproduce. Here are my results when performing a scan, in a freestyle job, using the Jenkins plugin to perform the scan of the workspace.

![screen shot 2018-04-18 at 3 02 02 pm](https://user-images.githubusercontent.com/3878933/38955220-9846f576-4319-11e8-9af5-b5957d54ecd8.png)

The CLI and Jenkins plugin should produce identical results since they have the same entry point into the ODC core library.

**Comment by Kish-Jadhav** [comment]
Hi @stevespringett , The issue has been resolved once i upgraded plugin from 3.1.0 to 3.1.2. I think, this issue was because I was using latest CLI tool and the plugin was(may be) bit lower.

Thank you all for you time.
Can anyone point me to a document where i can understand the internals of this plugin? I am interested in knowing the difference between the CLI tool and this plugin. Also, as long as NVD database does upgrade, I am expecting that results should not vary between the plugin versions.

**Comment by jeremylong** [comment]
@Kish-Jadhav all incarnations of dependency-check fall into two buckets. They all use the dependency-check-core to analyze the dependencies. However, the difference lies in the way dependencies are collected.

**Maven and Gradle plugins**: use the dependency management within the build tool to identify dependencies. In addition, evidence from the build system is used to assist in identification of the library (such as the coordinates or GAV).
**CLI, Ant, Jenkins**: use a file path to scan for dependencies.

**Comment by jeremylong** [comment]
@peckeltw if the report is showing zero dependencies scanned the plugin is misconfigured.
