### ISSUE TITLE
Enhance Suppression Analyzer to suppress based on GAV

### ISSUE THREAD

**Issue by colezlaw** [dependency-check/DependencyCheck#124]
In a lot of cases, GAV will be more accurate than some of the other types of analysis we do, and could be more broad than a single SHA1, yet more accurate than a `filePath` regex. Would be nice to be able to use GAV criteria in suppressions.

To get to this point, it might be helpful if the POM analyzer included the GAV as an identifier. Right now, only the Nexus analyzer produces a GAV identifier.

**Comment by jeremylong** [comment]
Good idea.  For implementation I'd suggest we make the Jar Analyzer add the
GAV as an identifier (not hyper-linked, and of low confidence) and then if
the Nexus analyzer finds the same GAV - we just update the GAV (adding the
hyperlink and upping the confidence).

**Comment by jeremylong** [comment]
The patch for the JarAnalyzer and NexusAnalyzer have been completed. Still need to update the suppression.xsd and make it possible to suppress based off of a GAV. This will likely be done as part of the update for issue #123 as the schema will need to be updated slightly to support this change too.
