### ISSUE TITLE
Enhancement: Upcoming CVE-ID Syntax Change

### ISSUE THREAD

**Issue by itayhaver** [dependency-check/DependencyCheck#125]
Support the upcoming new CVE ID Syntax change: http://cve.mitre.org/cve/identifiers/syntaxchange.html

The new CVE-ID syntax is variable length and includes: CVE prefix + Year + Arbitrary Digits.

CVE-YYYY-NNNN....N

Thanks.

**Comment by jeremylong** [comment]
This has been supported for over a year.... Well, not completely arbitrary; the CVE id is stored in a varchar(20) - if they hit that many CVEs in a year it'll be a very bad year ;)

Thanks,

--Jeremy
