### ISSUE TITLE
DependencyCheck uses deprecated commons-lang3 classes

### ISSUE THREAD

**Issue by aikebah** [dependency-check/DependencyCheck#1251]
I spotted in a mvn clean install
`[WARNING] /Users/aikebah/NetBeansProjects/DependencyCheck/core/src/main/java/org/owasp/dependencycheck/reporting/ReportGenerator.java:[38,37] org.apache.commons.lang3.text.WordUtils in org.apache.commons.lang3.text has been deprecated`

Looking up the commons-lang text package APIdocs I found that the classes involved have moved to a new Apache commons project: Commons Text.
https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/text/package-summary.html

For the sake of forward stability we should adapt the code to this new project.

I'll work on a PR for this

**Comment by jeremylong** [comment]
Thanks for the PR!
