### ISSUE TITLE
bundle-audit not found on windows 10

### ISSUE THREAD

**Issue by westlakem** [dependency-check/DependencyCheck#1256]
bundle-audit performs correctly when i open the command prompt and run `bundle-audit check --verbose`, however it does not work when I run `C:\Users\westlm1\Downloads\dependency-check-3.1.2-release\dependency-check\bin\dependency-check.bat --project test -s . --out C:\devl\results\test.html -f HTML  -l . --enableExperimental`

```
Exception from bundle-audit process: java.io.IOException: Cannot run program "bundle-audit" (in directory "C:\Users\westlm1\AppData\Local\Temp\dctemp591ab3da-742f-43d4-a920-721d827a11eb"): CreateProcess error=2, The system cannot find the file specified. Disabling Ruby Bundle Audit Analyzer
```

**Comment by jeremylong** [comment]
Can you try explicitly adding the path to `bundle-audit`?

`dependency-check.bat --project test -s . --out C:\devl\results\test.html -f HTML -l . --enableExperimental --bundleAudit [path/to/bundle-audit]
`

**Comment by westlakem** [comment]
@jeremylong I keep getting a `path is incorrect` error: 
```
[WARN] Supplied `bundleAudit` path is incorrect: C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundle-audit-0.1.0
```
I tried with 
`--bundleAudit C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundle-audit-0.1.0`
and
`--bundleAudit C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundle-audit-0.1.0/bin`

EDIT:

also tried
`C:/Ruby23-x64/bin`
and
`C:/Ruby23-x64`
and
`C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-audit-0.6.0`
and
`C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-audit-0.6.0/bin`

Also tried all the above with `\\` instead of `/` with no success

**Comment by westlakem** [comment]
Ok finally got it... I need to give the full executable path... `C:/Ruby23-x64/bin/bundle-audit.bat`
