### ISSUE TITLE
Documentation issue with "jarAnalyzer" property for Maven plugin

### ISSUE THREAD

**Issue by mrrobbins** [dependency-check/DependencyCheck#1261]
Page: https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html

Configuration property "jarAnalyzer" does not exist. Should be "jarAnalyzerEnabled".

**Comment by jeremylong** [comment]
Yes - it should be jarAnalyzerEnabled. Thanks for catching that!
