### ISSUE TITLE
dependency check can not collect evidence for windows dlls 

### ISSUE THREAD

**Issue by mahzad** [dependency-check/DependencyCheck#1262]
I am using [PE Explorer](http://www.pe-explorer.com/peexplorer-tour-dependency-scanner.htm ) for dependencies of my sdk file. The output of tool  was list of windows dlls.

Now ,I want to scan these file such as GDIPLUS. But the report is shown empty result.  why? ( While GDIPLUS is a vulnerable dll)

**Comment by jeremylong** [comment]
ODC can only analyze .NET assemblies. Pretty sure GDIPLUS is not a .NET assembly.
