### ISSUE TITLE
waiting for updates in maven plugin

### ISSUE THREAD

**Issue by mahzad** [dependency-check/DependencyCheck#1263]

**Comment by jeremylong** [comment]
If this is the first time you've run dependency-check you need to allow the update - or run it yourself manually.  The easiest way would be to simply set `<autoupdate>true</autoupdate>`. Alternatively, run `mvn org.owasp:dependency-check-maven:3.1.2:update-only` whenever you download the NVD CVE files from NIST.

**Comment by mahzad** [comment]
@jeremylong  I do according your post. but not working :(
![3](https://user-images.githubusercontent.com/3873092/39742262-1539183c-52b2-11e8-9952-6e2ccdcacd5d.jpg)

**Comment by busbey** [comment]
what worked well for me was using the CLI tool to handle the `updateonly` run that built a local cache, then point the maven build at that.

**Comment by jeremylong** [comment]
@mahzad Please add `-X` to the maven build and provide the build log (you can trim out just the dependency-check section if you want).

**Comment by mahzad** [comment]
@jeremylong  My Problem is solved. I delete dependency-check-data folder and  run ODC again. Thank you.
