### ISSUE TITLE
Invalid signature file digest for Manifest main attributes

### ISSUE THREAD

**Issue by githubhs17** [dependency-check/DependencyCheck#1267]
We are using zookeeper-3.4.10.tar.gz (https://archive.apache.org/dist/zookeeper/zookeeper-3.4.10/zookeeper-3.4.10.tar.gz) in our project. When running the scan we got following error

04:56:41 [INFO] Finished Archive Analyzer (3 seconds)
04:56:41 [INFO] Finished File Name Analyzer (0 seconds)
04:56:43 [WARN] An unexpected error occurred during analysis of '/home/jenkins-master/workspace/build-pipeline-ocscli.scan/dependentImages/prod-search-mesos-framework-zookeeper/contrib/fatjar/zookeeper-3.4.10-fatjar.jar' (Jar Analyzer): Invalid signature file digest for Manifest main attributes
04:56:44 [INFO] Finished Jar Analyzer (3 seconds)
04:56:58 [INFO] Finished Central Analyzer (13 seconds)
04:56:58 [INFO] Finished Assembly Analyzer (0 seconds)
04:56:58 [INFO] Finished Dependency Merging Analyzer (0 seconds)
04:56:58 [INFO] Finished Version Filter Analyzer (0 seconds)
04:56:59 [INFO] Finished Hint Analyzer (0 seconds)
04:57:00 [INFO] Created CPE Index (1 seconds)
04:57:00 [INFO] Skipping CPE Analysis for npm
04:57:03 [INFO] Finished CPE Analyzer (4 seconds)
04:57:03 [INFO] Finished False Positive Analyzer (0 seconds)
04:57:03 [INFO] Finished NVD CVE Analyzer (0 seconds)
04:57:03 [INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
04:57:03 [INFO] Finished Dependency Bundling Analyzer (0 seconds)
04:57:04 [INFO] Analysis Complete (26 seconds)
04:57:05 [ERROR] Invalid signature file digest for Manifest main attributes

**Comment by jeremylong** [comment]
I'm not sure if this is an issue with dependency-check.  In the referenced zookeeper archive I do not see a `zookeeper-3.4.10-fatjar.jar` - so I am assuming part of your build process creates this? If that is the case then the fatjar is being created incorrectly as it is combining the signatures from a signed JAR into the fatjar.  See the [stackoverflow question](https://stackoverflow.com/questions/34855649/invalid-signature-file-digest-for-manifest-main-attributes-exception-while-tryin?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa) on the topic. If you are generating the fat jar you need to configure it to strip the signatures.

**Comment by githubhs17** [comment]
Jeremy, thanks for your fast investigation.
We use this directly from apache.org, we don't build this. You can find the `zookeeper-3.4.10-fatjar.jar` in the referenced zookeeper archive in directory zookeeper-3.4.10.tar`/zookeeper-3.4.10/contrib/fatjar`

**Comment by jeremylong** [comment]
If you test the signature on the provided fatjar you get the following results:

```
$ jarsigner -verify -verbose zookeeper-3.4.10-fatjar.jar 
jarsigner: java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
```

The issue is not with dependency-check. The fatjar was created incorrectly.

**Comment by jeremylong** [comment]
You could configure dependency-check's `<failOnError>false</failOnError>`.

**Comment by githubhs17** [comment]
Jeremy, thanks a lot. About the failOnError configuration: How can I do this, I don't find anything in the documentation. We are using the docker image of owasp/dependency-check. Can you point me to the documentation where I can find informations about configuration. Thx.

**Comment by jeremylong** [comment]
Sorry, assumption on my part. For some reason I thought you were using the maven plugin rather then the docker/cli. I believe the report, etc. will still get created. However, I also just realized that the error will prevent the correct analysis of the fatjar...

The best option would be to contact the zookeeper team and ask about the invalid signature; alternatively you could submit a patch back to the build.xml in the contrib/fatjar. An exclude like the one below likely needs to be added to the file sets being used to generate the fatjar:

```xml
<zipgroupfileset dir="lib" excludes="META-INF/*.SF,META-INF/*.DSA,META-INF/*.RSA"/>
```
