### ISSUE TITLE
The updateonly  command is not working

### ISSUE THREAD

**Issue by mahzad** [dependency-check/DependencyCheck#1268]
I used nist-data-mirror project for downloading copy of NIST files. Now  I can not update files in cli version. what do I do?

The command: 
C:\Users\Administrator\Desktop\dependency-check\bin>dependency-check.bat  --cveU
rl12Modified http://127.0.0.1/mirror-dir/nvdcve-Modified.xml.gz --cveUrl12Modifi
ed http://127.0.0.1/mirror-dir/nvdcve-Modified.xml.gz --cveUrl20Modified http://
127.0.0.1/mirror-dir/nvdcve-2.0-Modified.xml.gz --cveUrl12Base http://127.0.0.1/
mirror-dir/nvdcve-%d.xml  --cveUrl20Base http://127.0.0.1/mirror-dir/nvdcve-2.0-
%d.xml --updateonly
[INFO] Checking for updates
[INFO] Skipping NVD check since last check was within 4 hours.
[INFO] Check for updates complete (109 ms)

C:\Users\Administrator\Desktop\dependency-check\bin>

**Comment by jeremylong** [comment]
The first command will delete the current database.

try:
```
C:\Users\Administrator\Desktop\dependency-check\bin>dependency-check.bat --purge

C:\Users\Administrator\Desktop\dependency-check\bin>dependency-check.bat --cveU
rl12Modified http://127.0.0.1/mirror-dir/nvdcve-Modified.xml.gz --cveUrl12Modifi
ed http://127.0.0.1/mirror-dir/nvdcve-Modified.xml.gz --cveUrl20Modified http://
127.0.0.1/mirror-dir/nvdcve-2.0-Modified.xml.gz --cveUrl12Base http://127.0.0.1/
mirror-dir/nvdcve-%d.xml --cveUrl20Base http://127.0.0.1/mirror-dir/nvdcve-2.0-
%d.xml --updateonly

**Comment by mahzad** [comment]
thanks you
