### ISSUE TITLE
dependecy check could not analyze pom.xml for java 

### ISSUE THREAD

**Issue by praveensutar** [dependency-check/DependencyCheck#1270]
For java related projects, when build is successfully done and jar are created in target directory those are only analyzed by dependecy-check not the pom.xml separatly where all other dependecy are mentioned.

Need to provide feature like to analyze pom.xml.

Thank You in advance

**Comment by stevespringett** [comment]
The DependencyCheck Maven plugin analyzes poms.

https://jeremylong.github.io/DependencyCheck/dependency-check-maven/

**Comment by praveensutar** [comment]
Thank You Steve.

I think its quite hard to understand the example. Do you have any full
documentation to explain it could be great like build process , maven
through directory scanning example, any options in cli to provide only
pom.xml to scan ?

**Comment by stevespringett** [comment]
The CLI doesn’t understand poms which is why we recommend using the maven plugin for maven builds. 

In its simplest form, the plugin can be executed from the command line similar to other maven plugins.

```
mvn org.owasp:dependency-check-maven:check
```

If you want to customize the execution or automate it as part of the build, the examples and the configuration link provides all necessary info.

**Comment by Ramos-dev** [comment]
I am also confused by this. when run org.owasp:dependency-check-maven working perfect，but why can not run cli in pom.xml's current directory?
why“CLI doesn’t understand poms ” ？

**Comment by stevespringett** [comment]
The CLI doesn't have dependencies on Maven core, so it doesn't know how to resolve Maven dependencies. This keeps the CLI lightweight and puts an emphasis on using best-practices. We've always recommended that if a Dependency-Check plugin exists for a given build system (Maven, Gradle, SBT, etc), then users are highly encouraged to use the plugin over the CLI. The results will be much more accurate.
