### ISSUE TITLE
Allow provided-scoped dependencies to be skipped

### ISSUE THREAD

**Issue by jvz** [dependency-check/DependencyCheck#1272]
I have a particular use case here, but I think it applies to most users who use `provided` or `compileOnly` or the equivalent compilation target. Generally, these provided dependencies do not always correspond to the actual provided version. For example, in Jenkins, you would use a provided scope for depending on another Jenkins plugin as said plugin will be provided inside Jenkins separately. Similarly, I could do something like that using Java EE APIs when deploying to Wildfly for example. When the number of modules sharing the same provided dependency grows, the number of false positives from outdated "dependencies" in each module becomes rather difficult to maintain (particularly in the Jenkins scenario).

What I'd like to propose is a feature, potentially disabled by default, that ignores provided dependencies during scans. In my use case, the provided dependencies are scanned already as part of the overall build, so it's pointless to rescan them anyways (besides the fact that those dependencies are not actually included by the application).

I can work on providing a PR, but I wanted to make sure this is an acceptable feature request first.

**Comment by albuch** [comment]
The ability to skip the provided scope is already implemented, see https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html for all configuration parameters.

```xml
           <plugin>
              <groupId>org.owasp</groupId>
              <artifactId>dependency-check-maven</artifactId>
              <version>3.1.2</version>
              <configuration>
                   <skipProvidedScope>true</skipProvidedScope>
              </configuration>
              <executions>
                  <execution>
                      <goals>
                          <goal>check</goal>
                      </goals>
                  </execution>
              </executions>
            </plugin>
```

**Comment by jvz** [comment]
Thanks for the pointer, I can't believe I missed that! And the option also works as a command line option `-DskipProvidedScope=true` which is fantastic for my use case. Thanks!
