### ISSUE TITLE
running maven ODC in another project

### ISSUE THREAD

**Issue by mahzad** [dependency-check/DependencyCheck#1273]
[log.txt](https://github.com/jeremylong/DependencyCheck/files/1997518/log.txt)
Hi
I run  ODC in a maven project using nist-data-mirror method . now in another maven project ,the ODC  is not in Plugins of Maven projects? Why  number of dependencies of scan is  zero!! ( this project have dependencies)
![1](https://user-images.githubusercontent.com/3873092/39956478-739ff908-55f6-11e8-88ae-e91b730b17f1.png)
 while there are ODC folders such as dependency-check-maven subfolder in .m2 repo.

**Comment by jeremylong** [comment]
We would need more information to assist:

1. Can you provide the pom or at least an excerpt from the pom showing that ODC is in the plugins section and not the `pluginManagement` and its configuration.
2. Is this a multi-module project? If it is, please use the aggregate mojo instead of the analyze mojo.
3. How are the dependencies defined?  If they are all in the `test` scope they are skipped, by default, by dependency-check.

**Comment by mahzad** [comment]
Hi,
1. The POM is attached.The ODC is in plugin tag. 
[pom.zip](https://github.com/jeremylong/DependencyCheck/files/1999336/pom.zip)
2. NO, it is a simple project.  I get it from github : [https://github.com/pdurbin/maven-hello-world](url)
3. Please see POM file.  the scope tag is defined. May I delete this tag? Or should I add skipTestScope tag into POM file and set to false?

I dont know why ODC plugin which is installed in repository (.m2) is not known in any project. It  is not in Plugins list in the right panel (Maven Projects window)

**Comment by mahzad** [comment]
@jeremylong  when I delete scope test line. The ODC try to connect to central search URL while that dependency is in .m2 repository !!!

**Comment by jeremylong** [comment]
Using your provided pom.xml I ran `mvn verify` and it successfully executed showing no dependencies as I would expect as `test` dependencies are skipped by default.

Side note, configuring dependency-check with URLs for the update and then saying don't update likely isn't what you wanted and may have caused some of your earlier issues with getting the data to update.
