### ISSUE TITLE
Why searching Central  URL 

### ISSUE THREAD

**Issue by mahzad** [dependency-check/DependencyCheck#1274]
### Reporting Bugs/Errors

I used local repo for my project 
[pom.zip](https://github.com/jeremylong/DependencyCheck/files/1999516/pom.zip)
 my report is created .
![1](https://user-images.githubusercontent.com/3873092/39980842-108ca5dc-5763-11e8-928a-c9ac2e8f4846.png)
 but my project has Error. 
[log.txt](https://github.com/jeremylong/DependencyCheck/files/1999500/log.txt)
what is it mean?why connect to central search while dependencies are in .m2 repo??????

I could run another project before but that project too has above error now.

**Comment by mahzad** [comment]
if i set centralAnalyzerEnabled to false , the error is removed.
but  is it correct action?

**Comment by jeremylong** [comment]
Please see #1193 . If you are using Maven or Gradle plugins - disabling the central analyzer is fine. If you are using the CLI or Ant then slightly less evidence *may* be collected which could result in both false negatives and false positives. For information on how dependency-check works see https://jeremylong.github.io/DependencyCheck/general/internals.html.
