### ISSUE TITLE
Implement Package URL into all standard reports

### ISSUE THREAD

**Issue by stevespringett** [dependency-check/DependencyCheck#1276]
### Abstract
There are inconsistencies in how identifiers are represented in the XML reports, both with regard to schema and the format of data.

### Observations
It appears that the identifier on relatedDependencies is only used for Maven projects which greatly reduces the usefulness of the element. It also appears the dependency-check schema is inconsistent between dependency and relatedDependency. One has a list of identifiers, the other only has a single identifier without any evidence. If a parser is using Jackson, or similar XML to object deserialization technique, both representations would need to be implemented on a single Dependency object resulting in fragile, less than ideal code.

In addition, the identifier on the dependency node has a slightly different format than the single identifier on the relatedDependency node.

### Recognition
Ideally, the solution would be to standardize both the schema and the format of data in the report. However, this may introduce breaking changes throughout the ecosystem.

### Proposed Solution
Leverage the Package URL specification to provide a structured, predictable, and supportable format to identify a components ecosystem and its relevant metadata for every dependency and relatedDependency.

The Package URL specification has already been implemented in Dependency-Track. Refer to https://docs.dependencytrack.org/datasources/routing/

The official Package URL Java implementation is located here: https://github.com/package-url/packageurl-java . This library will automatically create canonicalized Package URLs that adheres to the current specification.

The proposed solution should NOT modify the existing XML schema.

### Examples
```xml
<identifiers>
    <identifier type="maven" confidence="HIGH">
        <name>(org.apache.commons:io:1.3.4)</name>
    </identifier>
    <identifier type="package-url" confidence="HIGH">
        <name>Generated Package URL</name>
        <url>pkg:maven/org.apache.commons/io@1.3.4</url>
    </identifier>
</identifiers>
```
```xml
<identifiers>
    <identifier type="package-url" confidence="HIGH">
        <name>Generated Package URL</name>
        <url>pkg:npm/bootstrap@4.1.1</url>
    </identifier>
</identifiers>
```
```xml
<identifiers>
    <identifier type="package-url" confidence="HIGH">
        <name>Generated Package URL</name>
        <url>pkg:gem/jruby-launcher@1.1.2?platform=java</url>
    </identifier>
</identifiers>
```
```xml
<identifiers>
    <identifier type="package-url" confidence="HIGH">
        <name>Generated Package URL</name>
        <url>pkg:nuget/EnterpriseLibrary.Common@6.0.1304</url>
    </identifier>
</identifiers>
```

**Comment by jeremylong** [comment]
I would completely agree. I've also been reconsidering the entire "related dependencies" concept.

BTW - In your first example:

```xml
    <identifier type="maven" confidence="HIGH">
        <name>(org.apache.commons:io:1.3.4)</name>
    </identifier>
```
There are erroneous placed parentheses around the identifier. This was a mistake and they will be removed in the next version.

**Comment by jeremylong** [comment]
Package URLs are now being used in the 5.x branch. In some cases we are unable to identify a dependency (most common in Cli, Ant, and Jenkins scanning) and thus no package URL will be in the report.

Lastly, we are considering removing the DependencyBundlingAnalyzer which creates the "related dependencies" section of the report.
