### ISSUE TITLE
Register for CPE for DependencyCheck

### ISSUE THREAD

**Issue by colezlaw** [dependency-check/DependencyCheck#128]
Does it make sense for Dependency Check to be able to identify itself by CPE? Should it be registered for a CPE? http://nvd.nist.gov/cpe.cfm says you can just email cpe_dictionary@nist.gov to learn how to submit for your name.

**Comment by jeremylong** [comment]
I don't think we should register this project; I feel the overhead for this type of project is not worth the gain. Steve or Will - do you disagree?

**Comment by stevespringett** [comment]
I agree. I don't think we need to register a CPE at this time.
