### ISSUE TITLE
Does anyone know anything to study about owasp dependency-check-maven?

### ISSUE THREAD

**Issue by JiaHeLin** [dependency-check/DependencyCheck#1287]
I want to understand the use of this plug-in system, and use maven to use it on my project. About  I want to know more related knowledge. Can anyone provide any learning materials in this area?

**Comment by jeremylong** [comment]
There is of course the main [documentation site](https://jeremylong.github.io/DependencyCheck/). I would specifically look at:

* [How it works](https://jeremylong.github.io/DependencyCheck/general/internals.html)
* [Reading the Report](https://jeremylong.github.io/DependencyCheck/general/thereport.html)
* [False Positives](https://jeremylong.github.io/DependencyCheck/general/suppression.html)
* [Internet Access Required](https://jeremylong.github.io/DependencyCheck/data/index.html#)
* [ODC Maven Plugin Usage](https://jeremylong.github.io/DependencyCheck/dependency-check-maven/index.html)
* [ODC Maven Plugin Configuration](https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html)
