### ISSUE TITLE
CWE number is not working inside suppressions

### ISSUE THREAD

**Issue by humayun0156** [dependency-check/DependencyCheck#1291]
I'm using momentjs library and I've got a vulnerability
```
Published Vulnerabilities

NSP-532

Severity:High
CVSS Score: 7.5

Affected versions of `moment` are vulnerable to a low severity regular expression denial of service when parsing dates as strings.

    NSP - Advisory 532: Regular Expression Denial of Service

Vulnerable Software & Versions:

    moment:<2.19.3
```

Actually this is CWE-400   [https://nodesecurity.io/advisories/532](https://nodesecurity.io/advisories/532)
So I tried to suppress the cwe but the following code didn't work.
```xml
<suppress>
        <cwe>400</cwe>
</suppress>
```
Am I missing something?

**Comment by jeremylong** [comment]
In reality - we do not *yet* support a suppression filter for NSP findings. Additionally, while I built the feature, suppressing by CWE is likely a bad practice as that would remove an entire class vulnerabilities rather then a specific CVE. So if another vulnerability was reported as a CWE-400 - it too would be filtered.

**Comment by rochinae** [comment]
hi @jeremylong , not sure if it is related, but I have found out that the suppressions are not used when the report is generated with XML format. If the format is HTML, it works fine. This is an issue for us as we need the XML as we send it to dependency-track tool

**Comment by jeremylong** [comment]
@henry855567 the suppression likely works fine - you are just seeing the "suppressed" entries in the report (the suppressed findings are still in the report - just in a different section). As such, your parser likely needs to be updated.
