### ISSUE TITLE
NullPointerException when running dependency-check.sh

### ISSUE THREAD

**Issue by jorenvh1** [dependency-check/DependencyCheck#1305]
I'm trying to run the dependency checker inside a symfony (php) project. Whenever I run the following command I get a NullPointerException:

`$ /bin/dependency-check/bin/dependency-check.sh --project project --out . --scan .`

I ran this command inside root folder of the project.
This was the exception:

`Exception in thread "main" java.lang.NullPointerException at org.owasp.dependencycheck.Engine.writeReports(Engine.java:1114) at org.owasp.dependencycheck.Engine.writeReports(Engine.java:1134) at org.owasp.dependencycheck.App.runScan(App.java:264) at org.owasp.dependencycheck.App.run(App.java:184) at org.owasp.dependencycheck.App.main(App.java:69)`

I am using: Dependency-Check Core version 3.2.1

**Comment by jeremylong** [comment]
Can you run the following and provide the log file?:

```
/bin/dependency-check/bin/dependency-check.sh --project project --log odc.log --out . --scan .
```

**Comment by jorenvh1** [comment]
Seems like it suddenly works now (maybe because of a restart) but it feels like it's not scanning all my dependencies as I have 20+ dependencies in a project and says it only scanned 9...

**Comment by jeremylong** [comment]
Any chance the project is on github somewhere? Or you have a sample project that behaves the same that you could post?

**Comment by jorenvh1** [comment]
I forgot to add the --enableExperimental option. It's now working for php projects with a composer.lock file. 
This is still not working for podfile.lock projects or package.json projects though...
I'm using this command in the root of every project
`dependency-check --project symfony123  --out . --scan . --enableExperimental`

**Comment by jeremylong** [comment]
@jorenvh1 for podfile.lock - there is an open PR I will be merging soon (#1324). However, until that is merged podfile.lock is not supported/analyzed.

For the package.json projects - more then one packaging system has used the file name. ATM only node.js projects are being analyzed (using NSP).

Can this issue be closed?
