### ISSUE TITLE
install maven ODC manually

### ISSUE THREAD

**Issue by mahzad** [dependency-check/DependencyCheck#1310]
I have installed new maven release in a test system. My real system is in internal network and can not access to internet from it. Can I copy repository files ( such as org>owasp folders and so on ) from test system to real system? Is it correct? and manually install?

**Comment by jeremylong** [comment]
Yes, you can copy the ~/.m2/repository/org/owasp folder.  But there are other dependencies needed also.  Maybe clear you repository and then run dependency-check-maven on a vanilla plain pom.xml with no dependencies. Then the ~/.m2/repository would contain mostly just the stuff needed to run dependency-check...

**Comment by mahzad** [comment]
Thanks
Are NVD CVE data stored in dependency-check-data folder? so I can run ODC using the newest vulnerablities...

**Comment by jeremylong** [comment]
yes
