### ISSUE TITLE
Temporary files generated in Jenkins build

### ISSUE THREAD

**Issue by sjbufton** [dependency-check/DependencyCheck#1317]
Related to issue #934: every build with vulnerabilities generates several MB of tmp files in builds/_«nr»_/workspace_files. Examining the tmp files reveals that they are copies of the project's Spring dependencies' JARs.

Why is it necessary to keep these copies?

(Running the Jenkins plugin 3.2.1 on Jenkins LTS 2.107.2)

**Comment by jeremylong** [comment]
There is no reason to keep these files - minor bug due to order of operations. I have submitted a PR to the jenkins plugin to resolve the issue.

https://github.com/jenkinsci/dependency-check-plugin/pull/24
