### ISSUE TITLE
Access to search.maven.org is in clear HTTP

### ISSUE THREAD

**Issue by ethans** [dependency-check/DependencyCheck#1325]
Security issue:
When running (at least the command line scanner) for JAR files, it accesses most resources in HTTPS but for some reason it accesses **search.maven.org/remotecontent?filepath=** in clear.

This is because the MavenArtifact does this:
private static final String CENTRAL_CONTENT_URL = "//search.maven.org/remotecontent?filepath=";

As opposed to the solrsearch that is configured in the properties file:
analyzer.central.url=**https**://search.maven.org/solrsearch/select

**Comment by ethans** [comment]
After looking into it, I see that it defaults to http (in [CentralSearch.java](https://github.com/jeremylong/DependencyCheck/blob/3b294282f346b01302cde09cbc7439077205fb03/core/src/main/java/org/owasp/dependencycheck/data/central/CentralSearch.java#L173)), and sets HTTPS only if it finds a https attribute.

For a security tool - I find this strange. It should default to HTTPS and use HTTPS only for accessing maven.

**Comment by jeremylong** [comment]
This code hasn't been touched in years - if memory serves, at that time not all artifacts were served over HTTPS. However, that has since changed and the service no longer includes the flag indicating if the artifact could be served over HTTPS. As such, we can get rid of the check for the ability to use HTTPS and just default to secure. Thanks for pointing this out

**Comment by ethans** [comment]
No problem :-)
I'm about to submit the fixed code - just finishing to test it.

**Comment by jeremylong** [comment]
Ack - when I read the report I quickly pushed: https://github.com/jeremylong/DependencyCheck/commit/aece99bc0bc4f5e74b291d94755f8bb515e158d8

I don't think a PR is needed...

**Comment by ethans** [comment]
I was hoping this would be my contribution to a wonderful open source project.
Oh, well...
Good job
