### ISSUE TITLE
JAR libraries not being analysed

### ISSUE THREAD

**Issue by javixeneize** [dependency-check/DependencyCheck#1326]
Hi

I am having some issues when trying to analyse a JAR i have created as a library. 
 Apparently, it cant take any of the dependencies i have inside and it is generating an empty report, as if i didnt have any dependency inside

It works fine when i analyse a JAR that contains a "normalised" application, but it doesnt when it is built as a library

Is this a known issue?

Thanks

**Comment by jeremylong** [comment]
Can you give me some more information? Are you talking about generating a one/uber/shaded JAR? Where the dependencies are exploded inside the generated JAR - or are you talking about a spring boot JAR where the dependencies are copied as is into the JAR?

**Comment by javixeneize** [comment]
HI

Its a jar with the dependencies on it, but it is a library jar that only contains my own code. pom.xml is inside META-INF package

**Comment by jeremylong** [comment]
Ah - so you are saying you are running dependency check on a library being packaged as a JAR and the library you are building is not included in the dependency-check report?  That is expected behavior - as we are only analyzing the dependencies of the project being analyzed.

Does that answer your question/problem?

**Comment by javixeneize** [comment]
hi

Im analysing just my library jar, and none of the dependencies on it are
being analyzed.

It is, I just have library.jar in the project folder, and the report comes
empty

**Comment by jeremylong** [comment]
Can you provide the command you are using to run ODC, add the log option, and provide the log file?

**Comment by javixeneize** [comment]
Apologies

Im using the ODC plugin in Jenkins

I can provide the pom.xml file if you want it

The log does not give you too much information:

[DependencyCheck] Scanning: /home/jenkins/workspace/javitest
[DependencyCheck] Analyzing Dependencies
[Pipeline] publishHTML
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at BUILD level /home/jenkins/workspace/javitest to /var/jenkins_home/jobs/javitest/builds/22/htmlreports/Dependency_20Check_20Report
[Pipeline] publishHTML
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at BUILD level /home/jenkins/workspace/javitest to /var/jenkins_home/jobs/javitest/builds/22/htmlreports/Dependency_20Check_20Vulnerability_20Report
[Pipeline] dependencyCheckPublisher
[DependencyCheck] Collecting Dependency-Check analysis files...
[DependencyCheck] Searching for all files in /home/jenkins/workspace/javitest that match the pattern **/dependency-check-report.xml
[DependencyCheck] Parsing 1 file in /home/jenkins/workspace/javitest
[DependencyCheck] Successfully parsed file /home/jenkins/workspace/javitest/dependency-check-report.xml with 0 unique warnings and 0 duplicates.
Skipping warnings blame since pipelines do not have an SCM link.%n
[DependencyCheck] Computing warning deltas based on reference build #21
[DependencyCheck] Ignore new warnings since this is the first valid build
[DependencyCheck] Plug-in Result: Success - no threshold has been exceeded

The report only shows the mail .jar and does not analyse any dependency inside - I have a spring application inside demo-0.0.1-SNAPSHOT.jar:

Dependencies Scanned: 1 (1 unique)

Dependency	CPE	Coordinates	Highest Severity	CVE Count	CPE Confidence	Evidence Count
demo-0.0.1-SNAPSHOT.jar		demo:demo:0.0.1-SNAPSHOT	 	0		14
