### ISSUE TITLE
False positive on lombok-1.18.0.jar - reported as cpe:/a:spice_project:spice:1.18.0

### ISSUE THREAD

**Issue by javathought** [dependency-check/DependencyCheck#1327]
False positive on lombok-1.18.0.jar - reported as cpe:/a:spice_project:spice:1.18.0
```xml
<dependency>
    <groupId>org.projectlombok</groupId>
    <artifactId>lombok</artifactId>
   <version>1.18.0</version>
</dependency>
```

The cpe refers to linux distributions

**Comment by jeremylong** [comment]
What version of dependency-check are you using? I believe this was fix in 3.2.1 per issue #1064.

**Comment by javathought** [comment]
I'll check it tomorrow.

**Comment by javathought** [comment]
It's ok : 

I'm already on 3.2.1 I've created suppressionFile before upgrade on 3.2.1
