### ISSUE TITLE
Nexus Analyzer should support nexus that requires authentication

### ISSUE THREAD

**Issue by amandel** [dependency-check/DependencyCheck#1330]
When using the nexusAnalyzer there is (AFAIK) no way to give credentials for the Nexus access. 

You get the error:
`Expected 200 result from Nexus, got 401`

Since I call it from Maven it would be good to be able to use the password stored in the settings xml.

**Comment by jeremylong** [comment]
This has been discussed in #977. Please see [my comment](https://github.com/jeremylong/DependencyCheck/issues/977#issuecomment-366230129). I don't have a Nexus Pro to work with to test authentication against. PRs are welcome.

**Comment by amandel** [comment]
Thanks for the feedback and the link to the prior discussion. I did not notice that before. 
Actually I am using Nexus 2 in the open source edition.

**Comment by aikebah** [comment]
Was added in 4.0.2 from [#1643](https://github.com/jeremylong/DependencyCheck/pull/1643) but somehow we missed this ticket for closure
