### ISSUE TITLE
Broken suppression for ICU4J

### ISSUE THREAD

**Issue by GFriedrich** [dependency-check/DependencyCheck#1342]
With #1073 the dependency suppression for ICU4J was changed so that it contains a regular expression (see below).
https://github.com/jeremylong/DependencyCheck/blob/8951e266572d96a69ef6f45f52634409f802421e/core/src/main/resources/dependencycheck-base-suppression.xml#L779
Unfortunately the line starts with `<cpe>` and not with `<cpe regex="true">` which results in no suppression at all.
Please check and fix. Thanks in advance.

EDIT: I took a deeper dive into the code and just saw that activating the regex on the cpe results in the deactivation of the "no-version" check via `cpeHasNoVersion` which in turn means you will need to additionally add a `:.*` to the end of the expression.

**Comment by jeremylong** [comment]
Sorry about that. I don't have test cases on every item in the suppression file automated.

**Comment by GFriedrich** [comment]
Don't worry - sh*t happens! Thank you for fixing. :sunglasses: :+1:
