### ISSUE TITLE
Proxy Issues

### ISSUE THREAD

**Issue by jeremylong** [dependency-check/DependencyCheck#135]
A user has reported an issue with the proxy configuration via the [mailing list](https://groups.google.com/forum/#!topic/dependency-check/b0pbwK6UBvs).

---

starting with version 1.2.2 I get the following warning:

```
Jul 04, 2014 2:44:17 PM org.owasp.dependencycheck.maven.DependencyCheckMojo populateSettings
WARNING: Deprecated configuration detected, proxyUrl will be ignored; use the maven settings to configure the proxy instead
Jul 04, 2014 2:44:19 PM org.owasp.dependencycheck.data.update.NvdCveUpdater update
WARNING: Unable to download the NVD CVE data, unable to update the data to use the most current data.
Jul 04, 2014 2:44:23 PM org.owasp.dependencycheck.Engine analyzeDependencies
INFO: Analysis Starting
```

I use this config in my maven pom.xml:

``` xml
                    <plugin>
                           <groupId>org.owasp</groupId>
                           <artifactId>dependency-check-maven</artifactId>
                           <version>1.2.2</version>
                           <configuration>
                                  <proxyUrl><my.proxy.name></proxyUrl>
                                  <proxyPort><my.proxy.port></proxyPort>
                                  <detail>true</detail>
                                  <logFile>${project.build.directory}/dependency-check.log</logFile>
                           </configuration>
                    </plugin>
```

Log output is:

```
WARNING: Unable to download the NVD CVE data, unable to update the data to use the most current data.
Jul 04, 2014 2:44:19 PM org.owasp.dependencycheck.data.update.NvdCveUpdater update
FINE: null
org.owasp.dependencycheck.utils.DownloadFailedException: Error making HTTP HEAD request.
       at org.owasp.dependencycheck.utils.Downloader.getLastModified(Downloader.java:188)
       at org.owasp.dependencycheck.data.update.UpdateableNvdCve.add(UpdateableNvdCve.java:96)
```

As suggested, I configured the proxy in my maven settings.xml instead:

``` xml
       <proxies>
             <proxy>
                    <active>true</active>
                    <protocol>http</protocol>
                    <host><my.proxy.name></host>
                    <port>><my.proxy.port></port>
             </proxy>
       </proxies>
```

…and deleted the proxy-config from my maven pom.xml

But: Behaviuor is unchanged. So ist seems to me, version 1.2.2 does not honor the proxy-config in the maven settings.xml, at least not, if the proxy uses NTLM-authentication as ours does.

Additionally: When configuering > 1 proxies, the plugin throws a IllegalStageException.

Regards

Thomas

**Comment by herau** [comment]
+1

**Comment by erik-wramner** [comment]
My currently active pull request should fix the proxy issue when there is one active proxy. I have tested it with our setup (Maven 3.x, NTLM proxy that caches passwords after a successful login using for example a browser so user and password are omitted). The problem was that the host was converted into an URL, but it should be just the host as specified in the config file.

**Comment by herau** [comment]
Why not use The maven proxy configuration ? Usually declared in The settings.xml file

**Comment by erik-wramner** [comment]
Yes, this is exactly what the maven plugin does. The problem is that it converts the host from settings.xml into an URL (http://host) but the rest of the code expects a host name. The pull request fixes that.

**Comment by jeremylong** [comment]
The conversion to a URL was part of PR #85, which is the PR that started
pulling proxy information from settings.xml. The reason it was likely
converted to a URL was due to me incorrectly naming the proxy host
configuration parameter as proxy url. The naming issue has been fixed and
thanks to Erik, the proxy host is now correctly used.
