### ISSUE TITLE
Using dependency check to scan python open source components

### ISSUE THREAD

**Issue by petrarca95** [dependency-check/DependencyCheck#1357]
- I want to scan python open source packages/libraries.
- I downloaded the CLI dependency check tool version 3.2.1 from this website:
https://www.owasp.org/index.php/OWASP_Dependency_Check
- I am using Python 3.6.4 on a Windows 64 bit OS

I think my problem is that I am not sure what type of files I can scan. 
Attempted to scan:
-.py file created by myself with open source components import statements inside 
-.python open source module (also a .py file)
-python package (packages in python are normal directories with a __init__.py file inside)

One of the commands ran on cmd:

![dc error](https://user-images.githubusercontent.com/33295958/41984472-c3ccf13e-79fe-11e8-984c-2e68f91e6296.PNG)

**Comment by jeremylong** [comment]
The Python Analyer is described [here](https://jeremylong.github.io/DependencyCheck/analyzers/python.html). Also, I'd suggest reading about [how dependency-check works](https://jeremylong.github.io/DependencyCheck/general/internals.html).

Try running the following (switching backslashes to forward slashes, shortening the scan path so more is analyzed and adding the log file option):

```bash
dependency-check.bat --project Test --scan c:/Users/petra/Anaconda3 --out c:/Users/petra --enableExperimental --log c:/Users/petra/odc.log
```

If that does not work - the log file will provide the clues as to what has gone wrong.

**Comment by petrarca95** [comment]
![image](https://user-images.githubusercontent.com/33295958/42182945-fcccd68a-7e0d-11e8-8d46-0badccf7447c.png)

**Comment by petrarca95** [comment]
![image](https://user-images.githubusercontent.com/33295958/42183101-88c862b2-7e0e-11e8-9961-656f85cb44c9.png)
