### ISSUE TITLE
give jar file as an input

### ISSUE THREAD

**Issue by Kantha4security** [dependency-check/DependencyCheck#1363]
I would like to use dependency check for android apk files.  I'll get jar file only by decompiling the apk file. 

Does dependency check support jar file as an input? because, when I give jar file as an input report showing 0 Vulnerabilities.

**Comment by mprins** [comment]
How are the dependencies of the jar file defined?... 
You would probably need the pom or gradle or other build file to retrieve the dependency metadata

**Comment by jeremylong** [comment]
@Kantha4security you can't analyze just an APK with dependency-check. You can analyze the project that builds an APK using the [dependency-check-gradle](https://jeremylong.github.io/DependencyCheck/dependency-check-gradle/index.html) plugin.
