### ISSUE TITLE
Question: Jenkins Dependency-Check Plugin

### ISSUE THREAD

**Issue by quentinkhoo** [dependency-check/DependencyCheck#1365]
Hi

I would like to ask, with regards to the Dependency Check Plugin within Jenkins, what does "Fixed Vulnerabilities" as shown in the image mean?

![image](https://user-images.githubusercontent.com/33711159/42259680-0f2cb6a6-7f94-11e8-94a9-1791285766f0.png)

Upon clicking the link i get linked to this as shown below
![image](https://user-images.githubusercontent.com/33711159/42259875-dc4669a2-7f94-11e8-98ca-a5f52ba9dfde.png)

But i don't really understand what this is supposed to tell me. If you could provide any insight i'd be grateful.

**Comment by stevespringett** [comment]
There are 7 fewer vulnerabilities in build 40 than there was in the previous build.

**Comment by stevespringett** [comment]
Note: there’s a defect that’s been fixed in the master branch that may make these numbers incorrect. Fix will be available in v3.2.2

https://github.com/jenkinsci/dependency-check-plugin/commit/c185985fb00a0f194758a54173d8086b950e00e9

**Comment by quentinkhoo** [comment]
Hi @stevespringett 

Thank you for the response.Much appreciated :)

**Comment by stevespringett** [comment]
Sure thing. Let us know if you have further questions. Closing.
