### ISSUE TITLE
Exclude subproject/submodules from depdency check

### ISSUE THREAD

**Issue by Rancho007** [dependency-check/DependencyCheck#1370]
Hi,

Is there way to exclude sub project/modules from the dependency check?
Example;
Project commons {
          proj A
          proj B
          proj C
}

I would like to exclude proj B from the report.
Is this feature available?

Thank you.

Kr,
Ranch

**Comment by jeremylong** [comment]
At the moment - not directly.  One could create a suppression file that suppressed everything in the GAV (assuming maven?) for project B.

**Comment by Rancho007** [comment]
Hi,

Ok, thank you for quick and prompt response.

Kr,
Ranch
