### ISSUE TITLE
Analyze a git repo

### ISSUE THREAD

**Issue by mterron** [dependency-check/DependencyCheck#1378]
Please add support for analyzing a git repo.

I'd like to be able to do something like:
```$ dependency-check.sh --project my_project -s git://github.com/a/b.git```
and have the repo automatically downloaded and analyzed.

**Comment by stevespringett** [comment]
In many cases, this feature would not be viable. For Maven and Gradle projects for example, using the command line interface is not recommend as it does not product accurate results - hence why we recommend using native build plugins. For Node projects using Node Package Manager, the tool requires that `npm install` is executed prior to running an analysis.

While this feature would be interesting, it would not produce accurate results.

Execution of Dependency-Check varies depending on the technology stack being built and the build tool used.
