### ISSUE TITLE
Request Information

### ISSUE THREAD

**Issue by Kantha4security** [dependency-check/DependencyCheck#1384]
Hello @jeremylong 

I cloned the repository and using CLI able to run the scans on code bases by changing the database to MYSQL.

Now, I'm trying to understand the process, how it is fetching the NVD feeds and populating the local database and how it is combining this with CVE IDs score to give the risk rating. Also, I'm not able to find android vendor based library issues with this. 

Please help with file names in the repository that are responsible for pulling the NVD fees and populating in the local database and risk rating.

Thank you for your help.

**Comment by jeremylong** [comment]
Updates to the data can be found in [/core/src/main/java/org/owasp/dependencycheck/data/update/nvd
](https://github.com/jeremylong/DependencyCheck/tree/master/core/src/main/java/org/owasp/dependencycheck/data/update/nvd)

Risk ratings are based on the CVVS data provided by the NVD. See 
https://github.com/jeremylong/DependencyCheck/blob/3d463ec38c2ac733a2c0ebc08042a2edc8a976fa/core/src/main/resources/templates/htmlReport.vsl#L869-L875

Regarding android projects - I am actually currently working on this and support should be available in 3.3.0 when it is released.
