### ISSUE TITLE
Invalid Maven Identifiers in Reports

### ISSUE THREAD

**Issue by stevespringett** [dependency-check/DependencyCheck#1393]
### Reporting Bugs/Errors
The XML report contains an identifiers node. For Maven dependencies, a Maven identifier is generated. In some cases, the identifier generated violates the Maven specification.

#### Example
The following dependency will create an invalid Maven identifier in the resulting XML report.
```xml
<dependency>
    <groupId>org.fusesource.jansi</groupId>
    <artifactId>jansi-linux64</artifactId>
    <version>1.7</version>
</dependency>
```
This dependency will create the following Maven identifiers:
```xml
<identifier type="maven" confidence="HIGH">
    <name>org.fusesource.jansi:jansi-${platform}:1.7</name>
</identifier>
<identifier type="maven" confidence="HIGHEST">
    <name>org.fusesource.jansi:jansi-linux64:1.7</name>
</identifier>
```

The first identifier (confidence HIGH) contains characters not allowed in Maven groupId or artifactId fields. As of Maven 2 (possibly earlier), the groupId and artifactId must match the following regex: 

`[A-Za-z0-9_\\-.]+`

Source:
https://github.com/apache/maven/blob/master/maven-model-builder/src/main/java/org/apache/maven/model/validation/DefaultModelValidator.java#L76

POM To Reproduce:
[pom.xml.zip](https://github.com/jeremylong/DependencyCheck/files/2216703/pom.xml.zip)

**Comment by jeremylong** [comment]
Thanks - looks like we have to extend string interpolation to more fields when parsing the pom entries.

**Comment by Mazorius** [comment]
@jeremylong do you have an idea when this will be fixed?
