### ISSUE TITLE
Failed to initialize the RetireJS repo

### ISSUE THREAD

**Issue by ghost** [dependency-check/DependencyCheck#1394]
When the data directory is in a different path than the temporary directory, the retirejs analyzer fails with "Failed to initialize the RetireJS repo" exception. See [https://gist.github.com/bcartolo/d737e07be45a9eb3bfaa4bfcc6cdbdd0](https://gist.github.com/bcartolo/d737e07be45a9eb3bfaa4bfcc6cdbdd0)

**Comment by waded** [comment]
One possible workaround is to disable the RetireJS analyzer for now, e.g. in the Maven plugin config:

    <configuration>
        <retireJsAnalyzerEnabled>false</retireJsAnalyzerEnabled>
    </configuration>

**Comment by ghost** [comment]
Another one is to change the location of the data directory to the same drive of the temporary directory (Or the other way around).

**Comment by stevespringett** [comment]
I also believe we need to remove the check to see if the analyzer is enabled or not prior to downloading. This behavior is inconsistent with other analyzers (like the NVD) which doesn't have this check. I had to 'enable' the retireJs analyzer in order to perform an updateOnly. Without the analyzer enabled, I received the same "Failed to initialize the RetireJS repo" exception.

**Comment by jortkoopmans** [comment]
Also been hitting this problem, breaking my builds. I've rolled back to 3.2.1.

EDIT: Clarifying my setup: running Jenkins master in a docker container, on a CentOS7 host. Various build nodes around it, I've seen this problem occur on linux (CentOS7) based builds using the DependencyCheck.

**Comment by stevespringett** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-52792

**Comment by javixeneize** [comment]
Hi. Is a Jenkins plugin version going to be released for this as well?

Thanks

**Comment by stevespringett** [comment]
@javixeneize jenkins plugin 3.3.1 is already released and has this functionality.

**Comment by javixeneize** [comment]
Hi. It is still failing for me on that version

[DependencyCheck] OWASP Dependency-Check Plugin v3.3.1

[DependencyCheck] Analyzing Dependencies
[DependencyCheck] One or more exceptions were thrown while executing Dependency-Check
[DependencyCheck] Exception Caught: org.owasp.dependencycheck.exception.InitializationException
[DependencyCheck] Cause: jsrepository.json (No such file or directory)
[DependencyCheck] Message: Failed to initialize the RetireJS repo
[DependencyCheck] org.owasp.dependencycheck.exception.InitializationException: Failed to initialize the RetireJS repo

**Comment by jeremylong** [comment]
You would need to provide the debug log - and I might recommend opening a new issue.
