### ISSUE TITLE
AtomicMoveNotSupportedException while initialize the RetireJS repo when temp folder and maven repo are not on the same drive

### ISSUE THREAD

**Issue by RalphEng** [dependency-check/DependencyCheck#1410]
Failed to initialize the RetireJS repo because of `java.nio.file.AtomicMoveNotSupportedException` when temp-file-folder and maven repo folder are not the on the same drive.
At least with Windows7, Java8 is not able to atomic move a file from one disk to an other.

[Stacktrace](https://gist.github.com/RalphEng/1f336bcfac8befc785ad152b469c6a59)

This exception occurs in version 3.3.0.

The exception is cause by line `org.owasp.dependencycheck.data.update.RetireJSDataSource.initializeRetireJsRepo(RetireJSDataSource.java:167): `

`Files.move(tmpFile.toPath(), repoFile.toPath(), StandardCopyOption.REPLACE_EXISTING, StandardCopyOption.ATOMIC_MOVE);`

I think, the issue could been fixed by removing the `StandardCopyOption.ATOMIC_MOVE` flag. But I do not know if it is needed for some other usecase.

**Comment by stevespringett** [comment]
Duplicate of #1394
