### ISSUE TITLE
Classpath Bug in dependency-check.bat

### ISSUE THREAD

**Issue by ed-macke** [dependency-check/DependencyCheck#1413]
The dependency-check.bat incorrectly sets the classpath by using quotes incorrectly.

The included dependency-check.bat incorrectly surrounds only the root folder in quotes, whereas it should be enclosing the entire file in quotes.

The classpath needs each .jar surrounded by quotes, and separated by semicolons, for example:

```set CLASSPATH="foo.jar";"bar.jar"```

But the batch file misplaces the ending quote of each file.

#### Wrong
```set CLASSPATH="%BASEDIR%"\plugins\*;"%REPO%"\commons-cli\commons-cli\1.4\commons-cli-1.4.jar;```

Which assuming a default installation folder, get expanded to the following incorrect classpath (note quote marks before **\plugins** and **\commons-cli**)

```set CLASSPATH="C:\Program Files (x86)\DependencyChecker"\plugins\*;"C:\Program Files (x86)\DependencyChecker\repo"\commons-cli\commons-cli\1.4\commons-cli-1.4.jar;```

#### Correct
If the quotes are correctly placed like this:

```set CLASSPATH="%BASEDIR%\plugins\*";"%REPO%\commons-cli\commons-cli\1.4\commons-cli-1.4.jar";```

The classpath is correctly computed as follows:

```set CLASSPATH="C:\Program Files (x86)\DependencyChecker\plugins\*";"C:\Program Files (x86)\DependencyChecker\repo\commons-cli\commons-cli\1.4\commons-cli-1.4.jar";```

**Comment by jeremylong** [comment]
The bat file is automatically created by the [appassembler-maven-plugin](http://www.mojohaus.org/appassembler/appassembler-maven-plugin/assemble-mojo.html).
