### ISSUE TITLE
Jenkins build stuck during analysing dependencies

### ISSUE THREAD

**Issue by d47zm3** [dependency-check/DependencyCheck#1418]
This is very weird, but my builds are getting stuck during analysis phase (was working yesterday fine, what has changed is new plugin was installed (OWASP ZAP Proxy) and plugin Durable Task Plugin was updated (however downgrading back had no result). Anyone else with same issue? My builds are running on Docker containers, I attached output from OWASP logger as well. Will play more with ZAP plugin to check if it causes issues.

[GIST link](https://gist.github.com/d47zm3/5d43e936a41d032eb30ace39d490fe5a)

**Comment by ahmmadkour** [comment]
We are having the same issue, it stucks forever at "[DependencyCheck] Analyzing Dependencies". It started to happen today.

**Comment by PetterSa** [comment]
I had the same problem, but then I waited some more and got this error message : `[WARNING] Download Failed for NVD CVE - 2006`

Seems like something is down somewhere.

[Full output from the plugin](https://gist.github.com/PetterSa/20591efc673165c28e26bb2a5c27aa4d)

**Comment by ahmmadkour** [comment]
The issue is gone after I upgraded "OWASP Dependency-Check Plugin" in Jenkins to version 3.3.0

**Comment by d47zm3** [comment]
Well, for me it introduces another bug #1394, so it's not really solution, plus it's been working just fine prior to today, it's not ZAP plugin that interferes though, checked that.

EDIT: just tried again and it seems to work fine again, some download mirror issue I guess...

**Comment by jeremylong** [comment]
We have seen issues when one of the external vulnerability repositories has availability issues in the past. This is one of the reason I recommend using a centralized database with a single update node. A great example is https://hub.docker.com/r/stefanneuhaus/dependencycheck-central-mysql/

**Comment by d47zm3** [comment]
Thanks for suggestion, will test it through, closing issue then.
