### ISSUE TITLE
Module Descriptions is horked

### ISSUE THREAD

**Issue by FrugalGuy** [dependency-check/DependencyCheck#142]
http://jeremylong.github.io/DependencyCheck/modules.html gives the list of declared modules and their description.  Maven is repeated, CLI is missing, maybe other issues.

**Comment by jeremylong** [comment]
Thanks for pointing this out. This is an old copy/past issue that was never noticed (by me) when I first created the modules. This has been corrected in the 1.2.4-SNAPSHOT and will be released in the next day or two.
