### ISSUE TITLE
Offline Use

### ISSUE THREAD

**Issue by Boosted2003** [dependency-check/DependencyCheck#1420]
ISSUE:

I am looking to use dependency check fully offline.

I used Steve Springett Nist-Data-Mirror tool to download all the nist cve data. 

https://github.com/stevespringett/nist-data-mirror/blob/master/README.md#user-content-building

Currently I am using powershell to envoke, linux will be next, the command but I am having errors. 

```
PS C:\Users\user\Documents\Software\dependency-check-3.3.0-release\dependency-check\bin> .\dependency-check.bat --project "Test-Code" --cveUrl12Modified 'file:///C:\Users\user\Documents\Software\nist-data-mirror-master\mirror\nvdcve-modified.xml.gz' --cveUrl12Base 'file:///C:\Users\user\Documents\Software\nist-data-mirror-master\mirror\nvdcve-2.0-2018.xml.gz' --scan 'C:\Users\user\Documents\Software\Test-Code'

If one of the CVE URLs is specified they must all be specified; please add the missing CVE URL.
usage: Dependency-Check Core [--advancedHelp] [--cveValidForHours <hours>]
       [--enableExperimental] [--enableRetired] [--exclude <pattern>] [-f
       <format>] [--failOnCVSS <score>] [-h] [--hints <file>] [-l <file>]
       [-n] [-o <path>] [-P <file>] [--project <name>] [-s <path>]
       [--suppression <file>] [--symLink <depth>] [-v]

```
I was curious what I am doing wrong.  I tried searching the past issues and internet but just not coming up with what I am looking. 

Thank you in advance.

**Comment by stevespringett** [comment]
Refer to https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html

```
--cveUrl12Modified
--cveUrl20Modified
--cveUrl12Base
--cveUrl20Base
```

All four of those params need to be specified even if they share the same base url. Additionally, both cveUrl12Base and cveUrl20Base both need the %d placeholder in their URLs as it will be automatically replaced by the years 2002-current.

**Comment by Boosted2003** [comment]
Does one still use %d if you one is referencing nvdcve file on local machine?

**Comment by stevespringett** [comment]
Yes. For example:

```
--cveUrl12Base https://myhost/mirrors/nvd/nvdcve-%d.xml.gz
```

Dependency-Check (at runtime), will replace the %d and start from the year 2002 and proceed to download 2002 through the current year. So, whether it's on the NVD or a mirror doesn't matter. It will still need to download all the mirrored files in order to process them.

```
https://myhost/mirrors/nvd/nvdcve-2002.xml.gz
https://myhost/mirrors/nvd/nvdcve-2003.xml.gz
https://myhost/mirrors/nvd/nvdcve-2004.xml.gz
https://myhost/mirrors/nvd/nvdcve-2005.xml.gz
https://myhost/mirrors/nvd/nvdcve-2006.xml.gz
https://myhost/mirrors/nvd/nvdcve-2007.xml.gz
https://myhost/mirrors/nvd/nvdcve-2008.xml.gz
https://myhost/mirrors/nvd/nvdcve-2009.xml.gz
https://myhost/mirrors/nvd/nvdcve-2010.xml.gz
https://myhost/mirrors/nvd/nvdcve-2011.xml.gz
https://myhost/mirrors/nvd/nvdcve-2012.xml.gz
https://myhost/mirrors/nvd/nvdcve-2013.xml.gz
https://myhost/mirrors/nvd/nvdcve-2014.xml.gz
https://myhost/mirrors/nvd/nvdcve-2015.xml.gz
https://myhost/mirrors/nvd/nvdcve-2016.xml.gz
https://myhost/mirrors/nvd/nvdcve-2017.xml.gz
https://myhost/mirrors/nvd/nvdcve-2018.xml.gz
```

**Comment by Boosted2003** [comment]
That's what I thought I would need to setup a host for the file so they can be accessed via a web url instead of a file url.  Fairly easy and makes it easy to update from a central location so all developers can have access to it.  

Thank you

**Comment by jeremylong** [comment]
A file URL should work - with the %d.
