### ISSUE TITLE
maven plugin should look at more than just java dependencies

### ISSUE THREAD

**Issue by aw-was-here** [dependency-check/DependencyCheck#1421]
It would appear that if a maven project has more than just Java bits, the dependency check plugin doesn't take those extra parts into consideration.

For example, Apache Hadoop has a [package.json](https://github.com/apache/hadoop/blob/bcfc9851f4c6d37d9a119c16ea7d4d253d3b9614/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-ui/src/main/webapp/package.json) that doesn't seem to be getting found despite being in a directory that is part of the (default) scan set.

This is obviously bad for two reasons:

a) To get a complete audit, one is running both the maven plugin and the standalone version on a source tree, doubling the amount of time/resources required
b) Users may be led into a false sense of security because they may believe the maven plugin is actually checking everything.

**Comment by stevespringett** [comment]
The Maven plugin defaults to using standard Maven conventions and scans files in:

- src/main/resources
- src/main/filters
- src/main/webapp

If package.json is located in one of these directories, it will be scanned. If the file is outside the directories defined by Maven conventions, you can use the `scanSet` parameter to specify the directories you want to scan.

Refer to https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html

I did a quick scan of hadoop-yarn-ui using the following command: 
```bash
mvn org.owasp:dependency-check-maven:3.3.0:check
```
and it did find 4 vulnerable Node components using the built-in NSP Analyzer.

**Comment by aw-was-here** [comment]
Hmm. I've been using :aggregate and it definitely does not report on any of the Node components.  Running :check does.  

Maybe I misunderstood what aggregate does. My goal is to get one report for the entirety of the project. If it isn't actually running through all of the modules, that's less than helpful. :(

**Comment by jeremylong** [comment]
This is a bit if an oversight and I'm glad you reported it.  The intent is that the aggregate goal would scan the standard directories - but I can guarantee that right now it does not. As you have seen, the aggregate goal only scans dependencies defined in the pom.xml.

**Comment by jeremylong** [comment]
@aw-was-here is there any chance the project is available on github? If not - can you tell us the project layout for the maven build and where the package.json exists?

**Comment by aw-was-here** [comment]
Awesome, thanks!

Yes, it's definitely on github:  https://github.com/apache/hadoop

It's a large project that has lots of stuff in it:  java, python, node.js, cmake, ... so it's been a great test bed as we write support for dependency check into Apache Yetus (https://github.com/apache/yetus), another ASF project that is focused on build and release tooling.

**Comment by aw-was-here** [comment]
I tested the patch on my machine and it is now showing the node.js vulnerabilities.  Great!

**Comment by stevespringett** [comment]
@aw-was-here Good catch. Thanks for reporting. I've reviewed Jeremy's patch and it looks correct, so I think the next release should fix this issue.
