### ISSUE TITLE
Suppressions file 

### ISSUE THREAD

**Issue by rochinae** [dependency-check/DependencyCheck#1423]
Hello, I have found out that the suppressions are not used when the report is generated with XML format (using the Maven plugin, version 3.2.1). If the format is HTML, it works fine. This is an issue for us as we need the XML as we send it to dependency-track tool. I can notice in the logs that the suppressions file gets loaded:

```
[DEBUG] Loading suppression rules from 'owasp-suppressions.xml'
[DEBUG] 4 suppression rules were loaded.
```

The maven configuration for this execution is the following:

```
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.owasp</groupId>
                        <artifactId>dependency-check-maven</artifactId>
                        <version>3.2.1</version>
                        <configuration>
                            <suppressionFiles>
                                <suppressionFile>owasp-suppressions.xml</suppressionFile>
                            </suppressionFiles>
                            <scanSet>
                                <fileset>
                                    <directory>src/main</directory>
                                </fileset>
                            </scanSet>
                            <format>XML</format>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>check</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>

```
If I change the format to HTML, the 4 elements from the suppressions file are used to detect false positives.

Is that a known issue? Is there a trap I have fallen into? I am using version 3.5.4. Thanks!

**Comment by jeremylong** [comment]
My guess is what you are seeing is actually seeing is the fact that in both the XML, JSON, and HTML reports the suppressed vulnerabilities are actually included in the report.  In the HTML report scroll to the bottom and there is a "Suppressed" section that can be expanded.  For the XML - see the schema: https://github.com/jeremylong/DependencyCheck/blob/master/core/src/main/resources/schema/dependency-check.1.8.xsd#L191

If these CVEs are not in the suppressed section please let me know.

**Comment by rochinae** [comment]
Hi @jeremylong , thanks for your reply. I have checked and you are right. We highlighted the issue because we spotted it in Dependency Track app. It looks this one has a bug where it is not able to take into account the suppression of vulnerabilities.
