### ISSUE TITLE
Maven plugin fails if suppression file is given but does not exist.

### ISSUE THREAD

**Issue by memo42** [dependency-check/DependencyCheck#1428]
The Maven plugin expects the path of the suppression file to be a String.

This fails if you include the plugin in a parent and not all the children have the suppression file.

Using a fileSet might be a solution, but it would still have to work in case the fileSet remains empty.

**Comment by jeremylong** [comment]
Three ways to solve this problem.  If in some cases you don't have a suppression file you can configure:

```xml
<failOnError>false</failOnError>
```

Alternatively, if you have an internal repo (i.e. Nexus, Artifactory, etc.) you could bundle your enterprise suppression file in a JAR and add your suppression JAR as a dependency of dependency-check. That way the suppression file can be loaded from the classpath. 

Lastly, you could host the suppression file on an internal web server and reference the suppression file using `https://example.internal/suppression.xml`.
