### ISSUE TITLE
Dependency Check for Golang

### ISSUE THREAD

**Issue by yznima** [dependency-check/DependencyCheck#1432]
I was wondering if you guys will be interested in integrating DependencyCheck with Golang. I wanted to give it a try but wanted to check with you guys before starting anything

**Comment by jeremylong** [comment]
We are always interested in expanding support for other technology stacks. I have only taken a very cursory look at Golang so I'm not sure how dependencies are managed (other then `go get ...` .  but where the files are stored, if there is a build file that includes package and version numbers, etc.

**Comment by yznima** [comment]
`go get` is mostly helpful when trying to write a simple example but when it comes to reproducible production grade builds, [dep](https://github.com/golang/dep) and [vgo](https://github.com/golang/vgo) are the most common package managers used.

I have mostly used `dep` since `vgo` is a very recent and experimental package manager for go. dep uses [lock](https://golang.github.io/dep/docs/Gopkg.lock.html) file, in `toml` format, to maintain a list of packages and their versions or SHA and resolve them later them on. 

I would like to test how the dependency check would look like with `dep` before doing more with `vgo` specially since most libraries out there use `dep` right now

**Comment by trptcolin** [comment]
@yznima This would be great to have! I don't know this project well, but would love to have it available for Golang. 😸 Are you looking for help on anything?

**Comment by yznima** [comment]
@jeremylong I have a commit available [here](https://github.com/jeremylong/DependencyCheck/pull/1560) where I am able to add dependencies and the html generated view shows each dependency in `Gopkg.lock` as a dependency but it seems like the tool isn't able to warn me when I introduce some dependency that has a vulnerability. Perhaps, I am not setting the correct evidence for a dependency. Do you have any suggestions on how I can debug this a little further?

**Comment by yznima** [comment]
@trptcolin I have been trying to get an initial version working [here](https://github.com/jeremylong/DependencyCheck/pull/1560). I am almost there 🙏

**Comment by jeremylong** [comment]
@yznima Sorry this took so long to get to.  In order to make this analyzer work we had to make a tweak to the CPEAnalyzer to better support modules in go where we do not know what version the NVD would have - so we use an asterisk in those cases.
