### ISSUE TITLE
[Jenkins] Missing failOnCVSS

### ISSUE THREAD

**Issue by mvanini** [dependency-check/DependencyCheck#1434]
Add possibility to change value of CVSS which fail the pipeline (like in CLI/Maven).
Maybe a global configuration with default and per-job specific settings for critical project

**Comment by stevespringett** [comment]
I assume you’re referring to the Jenkins plugin? If so, create an enhancement request at https://issues.jenkins-ci.org and close out this ticket.

If you’re referring to a different implementation, can you be more specific?

**Comment by mvanini** [comment]
Sorry @stevespringett i mistaken repository.
I'll open issue on jenkins's jira.
