### ISSUE TITLE
A glitch in the CliParser

### ISSUE THREAD

**Issue by gbena** [dependency-check/DependencyCheck#1440]
The CliParser is not using the correct Keys for RetireJS.

CLiParser.java:766-768

```
    public boolean isRetireJSDisabled() {
        return hasDisableOption(ARGUMENT.DISABLE_RETIRE_JS, Settings.KEYS.ANALYZER_RETIRED_ENABLED);
    }
```
I believe it should be Settings.KEYS.ANALYZER_**RETIREJS**_ENABLED instead of Settings.KEYS.ANALYZER_RETIRED_ENABLED

**Comment by jeremylong** [comment]
Thank you for noticing the autocomplete/typo. This will be patched in the next release.
