### ISSUE TITLE
Vulnerabilities reported on SQL Server Compact Edition

### ISSUE THREAD

**Issue by softengi** [dependency-check/DependencyCheck#1442]
On running dependency check on Sql Server Compact Edition binaries, the tool reported vulnerabilities in the file System.Data.SqlServerCe.dll.
In the "Published Vulnerabilities", none of the vulnerable software & versions under different CVE's reported, had the Compact Edition mentioned explicitly, though it had different version of SQL Server as affected software. I was unable to verify if the reported vulnerabilities are false positives for Compact Edition that got reported because of SQL Server. Please suggest.

**Comment by jeremylong** [comment]
As SQL Server Compact Edition is not explicitly listed it may not be vulnerable. However, to be sure you would need to contact Microsoft.

One thing to note, the vulnerability is in the common controls. I do not know enough about the compact edition to know if any of the common controls are installed with compact edition.
