### ISSUE TITLE
how to add customize scan to NspAnalyzer?

### ISSUE THREAD

**Issue by Ramos-dev** [dependency-check/DependencyCheck#1454]
We can use dependency.addEvidence to add nodejs module,and scan from api.nodesecurity.io/check,code like:
"// Submits the package payload to the nsp check service
final List<Advisory> advisories = searcher.submitPackage(nspPayload);"
but in our company,we have ourself node module.So How scan I add customize rules in DependencyCheckScanAgent or in something?
#### Example
my package.json
"@mtfe/mtnb": "^0.3.8",
    "@mtfe/react-router-redux": "^4.0.5",
    "@mtfe/s3-sync-cli": "2.1.0",
    "@mtfe/ssoify": "4.0.1",
    "@mtfe/thrift": "^2.2.7",
    "autoprefixer": "^6.3.6",
    "babel-core": "^6.17.0",
    "babel-eslint": "^6.0.2",
    "babel-polyfill": "^6.9.1",
    "basscss": "^8.0.1",
    "brfs": "^1.4.3",

**Comment by jeremylong** [comment]
I'm not sure I understand the question.  If the only thing you are doing is wanting to check for known security issues in your NPM packages - I might suggest just using [npm-audit](https://docs.npmjs.com/cli/audit). Anything dependency-check is doing is just a wrapper around things in the NPM environment; this is generally used for multi-technology projects where a single report is desired.
