### ISSUE TITLE
Nice to have (enhancement): link to release notes

### ISSUE THREAD

**Issue by larrywest42** [dependency-check/DependencyCheck#1455]
_(First,_ Dependency Check _is a great project and I hope your efforts are being sustained by OWASP or some organization.)_

My request comes because I'm looking at updating from 3.2.1 to 3.3.1 ... but I can't tell what's changed.

I had a hard time finding release note: they're not in the normal [GitHub release notes page](https://github.com/jeremylong/DependencyCheck/releases), nor do I see them in either the [Dependency Check](https://jeremylong.github.io/DependencyCheck/) or [dependency-check- maven](https://jeremylong.github.io/DependencyCheck/dependency-check-maven/) home pages.

Update: My bad. Thanks to the mailing list archives, I just found the release notes in a fairly obvious location, [RELEASE_NOTES.md](https://github.com/jeremylong/DependencyCheck/blob/master/RELEASE_NOTES.md) &mdash; please close this ... though adding a link or two to this might be nice for other ignoramuses like me.

**Comment by jeremylong** [comment]
I'll have to do better when tagging the releases - sorry about that.
