### ISSUE TITLE
Broken table formatting in dependency-check-cli/arguments.html

### ISSUE THREAD

**Issue by doshyt** [dependency-check/DependencyCheck#1458]
The table columns seem to be misplaced on the docs page https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html

Apparently, the table formatting is missing starting and ending "|" symbols for most of the rows. My guess would be the different Markdown format standard back when it was first created.

**Comment by jeremylong** [comment]
Thanks!
