### ISSUE TITLE
False negatives when scanning application with dependencies in .class files

### ISSUE THREAD

**Issue by dominik6** [dependency-check/DependencyCheck#1473]
Hello, 
I've stumbled upon the following issue. 

One of the application that I'm scanning is build in a particular way. There is a one big .jar file with all dependencies inside in form of the .class files divided into directories. Dependency Check don't report any vulnerabilities.  

So after extracting the jar file the structure is (part for example):
```
application
   akka 
      AkkaException.class
      ConfigurationException.class
      Done$.class
      Done.class
      Main$.class
      Main$Terminator$$anonfun$receive$1.class
      Main$Terminator.class
      Main.class
      NotUsed$.class
      NotUsed.class
      OnlyCauseStackTrace$class.class
      OnlyCauseStackTrace.class
      Version$.class
      Version.class
   netty
   (and many other deps)
```
edit: It seems that described way of building application is called 'uber-jar' in Maven. 

Now if I zip all the internal directories into .jar files, Dependency Check seems to correctly identify the vulnerabilities (presumably based on the data in Version$.class files).

Is there a way to force Dependency Check to scan also the "extracted" dependencies inside the .jar application (.class files)? Or maybe described behaviour is bug/possible enhancement?

**Comment by isaki** [comment]
If you are using Maven (or Gradle), you can execute the depcheck verification prior to the construction of your uber-jar as part of your build; it will fail your build if there are any vulnerabilities.

**Comment by jeremylong** [comment]
We always recommend using a build plugin integration such as dependency-check-maven or dependency-check-gradle instead of using the CLI.  If, instead of using Uber JAR, the JAR was created using the maven-shade-plugin - enough information is kept that dependency-check can correctly analyze it after the uber/one/shaded JAR was created.
