### ISSUE TITLE
Allow explicit dependencies to be added without artifacts present [enhancement]

### ISSUE THREAD

**Issue by ChristopherSchultz** [dependency-check/DependencyCheck#1474]
Although nowhere in my dependency tree, I know I'm going to be deploying on Java X, Tomcat Y, and using Solr Z for example. I'd like to add those as explicit dependencies so they can be scanned as well as the build-time dependencies that are usually scanned.

This is basically the opposite of the "suppressions" file... it's an "inclusions" file, or something like that.

**Comment by jeremylong** [comment]
While an enhancement can be made - I would suggest looking at [dependency-track](https://docs.dependencytrack.org/) where this functionality already exists.

**Comment by ChristopherSchultz** [comment]
I'll definitely look into that. Any chance these two tools use the same on-disk vuln databases? One of the most onerous things about dependency-check IMHO is downloading the internet before anything gets checked. Doing it twice is unappealing.

**Comment by stevespringett** [comment]
Dependency-Track mirrors the entire contents of the NVD. But it also makes the mirror available to Dependency-Check clients, so you only have to download once and all your internal dependency-check clients can use Dependency-Track as their source for NVD. Refer to https://docs.dependencytrack.org/datasources/nvd/

Aside from that, Dependency-Track v3.2 (releasing next week) supports internal NPM Audit and Sonatype OSS Index scanners in addition to Dependency-Check (which requires the NVD datafeed). Each scanner can be enabled/disabled independently.
