### ISSUE TITLE
Different levels of Severity bw Dependency Check and Dependency Track

### ISSUE THREAD

**Issue by mbarzanti** [dependency-check/DependencyCheck#1478]
I saw Dependency Check has 3 Priority Levels: High, Medium and Low, while Dependency Track has 4: Crtical, High, Medium and Low. Why this difference? It is possibile to unify levels bw the tools?

**Comment by stevespringett** [comment]
Dependency-Track support CVSSv3 as a default. If CVSSv3 scores are not available, it falls back to CVSSv2.

CVSSv3 defines critical, high, medium, and low whereas CVSSv2 defines high, medium, and low.

As of today, Dependency-Check only supports CVSSv2.

If you import dependency-check-report.xml into Dependency-Track, you'll likely see the severity and CVSSv3 scores which are likely different from the dependency-check reports. Once Dependency-Check supports CVSSv3, the discrepancies will disappear. Refer to #707

**Comment by mbarzanti** [comment]
Thanks @ Steve
