### ISSUE TITLE
Question-Help: [ERROR] Unable to load database driver

### ISSUE THREAD

**Issue by SteveParini** [dependency-check/DependencyCheck#1480]
I'm trying to set the db connection string inside the DependencyCheck.property

Evidently there's something wrong with how I'm doing that.

the command-line I'm using is:
dependency-check.bat --updateonly -l .\command-line-log.txt
get  [ERROR] Unable to load database driver

here some more details
DependencyCheck.property db section: https://gist.github.com/SteveParini/ba799791e6e6193a501bc8edaff81d99
```
data.connection_string=jdbc:sqlserver://localhost;databaseName=DependencyChecker;integratedSecurity=true
data.driver_name=Microsoft JDBC Driver 4.1 for SQL Server
data.driver_path="C:\\Program Files\\Microsoft JDBC Driver 4.1 for SQL Server\\sqljdbc_4.1\\enu\\jre7\\sqljdbc41.jar"
```

ErrorLog: https://gist.github.com/SteveParini/959059e361b41270c3da51ea2299598b

```
2018-09-10 14:24:17,004 org.owasp.dependencycheck.data.nvdcve.DriverLoader:159
DEBUG - Unable to load database driver 'Microsoft JDBC Driver 4.1 for SQL Server'
java.lang.ClassNotFoundException: Microsoft JDBC Driver 4.1 for SQL Server
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
...
2018-09-10 14:24:17,004 org.owasp.dependencycheck.data.nvdcve.ConnectionFactory:129
DEBUG - Unable to load database driver
org.owasp.dependencycheck.data.nvdcve.DriverLoadException: Unable to load database driver 'Microsoft JDBC Driver 4.1 for SQL Server'
	at org.owasp.dependencycheck.data.nvdcve.DriverLoader.load(DriverLoader.java:160)
	at org.owasp.dependencycheck.data.nvdcve.DriverLoader.load(DriverLoader.java:134)
	at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.initialize(ConnectionFactory.java:124)
	at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.getConnection(ConnectionFactory.java:231)
	at org.owasp.dependencycheck.data.nvdcve.CveDB.open(CveDB.java:226)
	at org.owasp.dependencycheck.data.nvdcve.CveDB.<init>(CveDB.java:196)
....
```
Thanks in advance

**Comment by mprins** [comment]
you probably need to use the classname of the driver (as the example shows), not some descriptive

**Comment by SteveParini** [comment]
yep thanks.. it took me a while 
For Future reference I found it here:
https://docs.microsoft.com/en-us/sql/connect/jdbc/understanding-java-ee-support?view=sql-server-2017

The driver class name is com.microsoft.sqlserver.jdbc.SQLServerDriver. For JDBC Drivers 4.1, 4.2, and 6.0, the driver is contained in the sqljdbc.jar, sqljdbc4.jar, sqljdbc41.jar, or sqljdbc42.jar files.

For JDBC Driver 6.2, the driver is contained in mssql-jdbc-6.2.2.jre7.jar or mssql-jdbc-6.2.2.jre8.jar.

For JDBC Driver 6.4, the driver is contained in mssql-jdbc-6.4.0.jre7.jar, mssql-jdbc-6.4.0.jre8.jar, or mssql-jdbc-6.4.0.jre9.jar.

For JDBC Driver 7.0, the driver is contained in mssql-jdbc-7.0.0.jre8.jar, or mssql-jdbc-7.0.0.jre10.jar.

The class name is used whenever you load the driver with the JDBC DriverManager class. It's also used whenever you must specify the class name of the driver in any driver configuration. For example, configuring a data source within a Java EE application server might require you enter the driver class name. 

This can be closed I believe.. now I'm getting a different error

ERROR - Database schema does not match this version of dependency-check 
for which l found this closed ticket https://github.com/jeremylong/DependencyCheck/issues/804 

While relevant because of the error, probably worth investigate with a new request since I've the same problem with MS-SQL and all the solutions presented on that thread don't seem to apply... or I'm doing something wrong.

Thanks

**Comment by jeremylong** [comment]
@SteveParini I am assuming you ran the MS SQL initialization script on the database?  https://github.com/jeremylong/DependencyCheck/blob/master/core/src/main/resources/data/initialize_mssql.sql

Can you run a `SELECT * FROM properties' on the database you setup?

**Comment by jeremylong** [comment]
Closing this issue - the remaining problems will be tracked in the new issue #1483.
