### ISSUE TITLE
Silent failure with missing artifact during publish to DependencyTrack

### ISSUE THREAD

**Issue by putz612** [dependency-check/DependencyCheck#1486]
I have added the publish to DependencyTrack to my pipeline however during testing I noticed that if it could not find the artifact the build would fail in the console output it would not really state that it was a hard failure.  Looking at the pipeline steps every stage would show success making harder to determine the cause of the failure.

From the logs

> ........
> [Pipeline] dependencyTrackPublisher
> [DependencyTrack] Publishing artifact to Dependency-Track
> [DependencyTrack] The specified artifact does not exist
> ........
> Finished: FAILURE

**Comment by jeremylong** [comment]
This ticket should probably be opened on the dependency-track project: https://github.com/DependencyTrack/dependency-track

--Jeremy

**Comment by putz612** [comment]
Do they manage the dependency-check upload to dependency-track portion if the Jenkins plugin because the issue is somewhere in that process.  I am unsure who owns that portion of code being that the dependencyTrackPublisher step in my Jenkinsfile comes from the dependency-check plugin.

**Comment by stevespringett** [comment]
The Dependency-Track publisher is part https://github.com/jenkinsci/dependency-check-plugin

However, I don't think there's a whole lot that can be done to improve this issue. Plugins have the ability to set the build status to:

- SUCCESS
- UNSTABLE
- FAILURE
- NOT_BUILT
- ABORTED

If the dependency-check report specified in the job config doesn't exist when it attempts to upload it to Dependency-Track, the plugin will log `The specified artifact does not exist` to the console and set the build to FAILURE. The issue you're describing seems to be more of a Jenkins usability issue. There should be a better way to find out which step in the pipeline had an issue, and I agree.

If there are other things that can be done in the plugin to improve visibility into which step caused the issue, please open a PR and submit an issue to https://issues.jenkins-ci.org.

**Comment by putz612** [comment]
Is there a way to fail the step vs the build so you can see where the failure is?  I was using the verbiage described in another plugin that users were reporting similar results.  Probably the best known is in archiveArtifacts on https://issues.jenkins-ci.org/browse/JENKINS-38005

There is two PR with different ways of failing the step and/or better log messages.  Not very good at Java but I will try to see what I can do to help.
https://github.com/jenkinsci/jenkins/pull/2823
