### ISSUE TITLE
Unable to give --artifactoryUrl parameter in CLI

### ISSUE THREAD

**Issue by XYZ743874** [dependency-check/DependencyCheck#1492]
Hello,
Dep-Check CLI manual lists "--artifactoryUrl" as a parameter:
https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html
However, it would appear that command:
dependency-check.sh --artifactoryUrl <url>
gives an error:
Unrecognized option: --artifactoryUrl

The string/argument is present in https://github.com/jeremylong/DependencyCheck/blob/master/cli/src/main/java/org/owasp/dependencycheck/CliParser.java 
`public static final String ARTIFACTORY_URL = "artifactoryUrl";`
However, as far as I can tell, the variable is not referenced in the source code. This has been tested with Dependency-Check Core version 3.3.2

Is this a bug, not yet implemented or deprecated feature?

#### Example
```
[user@localhost ~]$ ./dependency-check.sh --artifactoryUrl http://artifactory.local
Unrecognized option: --artifactoryUrl
```

**Comment by jeremylong** [comment]
Sorry about that.  This will be fixed in the next release.

--jeremy
