### ISSUE TITLE
No vulnerabilities in Pyhton 2.7 application

### ISSUE THREAD

**Issue by migsolor** [dependency-check/DependencyCheck#1496]
Hello,

We are using dependency check in version 2.7 of Phyton and we have dependencies like "pandas", "numpy" and it does not seem to detect them. It analyzes as dependencies the files "__init__.py.

The report shows no vulnerability and it is rare to use these libraries.

We have tested using the --enableExperimental command and without using it.

Can someone help us? 

Thanks!

**Comment by jeremylong** [comment]
In reality, the Python analysis is experimental and I have not had time to improve it (and as you've seen there is a lot of room for improvement). In the meantime - I might suggest checking out [safety](https://pyup.io/safety/).

**Comment by jeremylong** [comment]
This will be tracked via #548.
