### ISSUE TITLE
Maven Proxy Configuration failure

### ISSUE THREAD

**Issue by mprunet** [dependency-check/DependencyCheck#150]
In DependencyCheckMojo, the proxy IP is prefixed with http://
private String getMavenSettingsProxyServer(Proxy proxy) {
        return new StringBuilder(proxy.getProtocol()).append("://").append(proxy.getHost()).toString();
}

But in URLConnectionFactory  createHttpURLConnection, a Socket Address is created with the prefix http:// . The prefix must be removed.
final SocketAddress address = new InetSocketAddress(proxyUrl, proxyPort);

**Comment by jeremylong** [comment]
This was reported and fixed - see issue #135 and line 819 of the commit: https://github.com/jeremylong/DependencyCheck/commit/e127d734a2f6e2e1c5b8e19cf7dc554874f90d3b
