### ISSUE TITLE
How to configure Local Oracle DB to auto update?

### ISSUE THREAD

**Issue by hemanthacharya** [dependency-check/DependencyCheck#1503]
Hi @jeremylong ,

I am running the dependency analyzer by configuring a local Oracle. Initial set up of changing the Connection_string and the credentials are done. I have also modified the code to run initial_oracle.sql script. But if I just want to autoupdate like how it happens with the h2 db rather than re creating the db structure every time, it seems not to work. 
I see the following error in the logs -  "Unable to update Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities." 
Can you please point out if i am missing anything?
Also, Is there a Doc where I can refer to configure a local Oracle DB instead of h2 DB?

Thanks

**Comment by jeremylong** [comment]
The only limited documentation can be found here: https://jeremylong.github.io/DependencyCheck/data/database.html

If after looking at that you are still having issues we would need to see the full log rather then just the console output to assist further. (i.e. `$ dependency-check.sh --updateOnly --log odc.log ...`(
