### ISSUE TITLE
Nit: Provided Scope should be System Scope (in documentation)

### ISSUE THREAD

**Issue by davewichers** [dependency-check/DependencyCheck#1509]
https://github.com/jeremylong/DependencyCheck/blob/15a134ec8088e42fb8c80633b66e38a7f1d6b5ee/maven/src/main/java/org/owasp/dependencycheck/maven/BaseDependencyCheckMojo.java#L544

This line has a cut/paste error. 'Provided Scope' should be 'System Scope' in this comment.  Fixing this and regenerating the documentation, will fix this typo on: https://jeremylong.github.io/DependencyCheck/dependency-check-maven/check-mojo.html

**Comment by jeremylong** [comment]
Thanks!  The documentation will be updated in the next release.
