### ISSUE TITLE
false positive

### ISSUE THREAD

**Issue by jeremylong** [dependency-check/DependencyCheck#151]
False positive on jersey-client; it is identified as Oracle Client as reported by Erlend Oftedal.

```
  <dependency>
    <groupId>org.glassfish.jersey.core</groupId>
    <artifactId>jersey-client</artifactId>
    <version>2.12</version>
  </dependency>
```

**Comment by jeremylong** [comment]
This has been patched in 1.2.5-SNAPSHOT.

**Comment by Mahersi** [comment]
Hi

Even with the new version of the dependency check plugin 1.2.5,the same problem exists for jersey-client-1.11.jar. 

Best regards
amir

**Comment by jeremylong** [comment]
This is because the group id changed from the 1.x branch to the 2.x branch. I will commit a change shortly to account for this.  Thanks for reporting the false positive!

**Comment by eoftedal** [comment]
@jeremylong Do you prefer to have false positives posted as issues here or posted to the mailing list?

**Comment by jeremylong** [comment]
Yes. Easier to track that way.  Ive considered adding a false positive
reporting feature to the report.

Jeremy

**Comment by jeremylong** [comment]
The patch for this has been pushed to 1.2.6-SNAPSHOT.
