### ISSUE TITLE
Exception Caught: org.owasp.dependencycheck.analyzer.exception.SearchException

### ISSUE THREAD

**Issue by pankajmalhotra** [dependency-check/DependencyCheck#1518]
### Reporting Bugs/Errors
Getting error while executing dependecy check via Jenkins.

#### Example
14:15:14 [DependencyCheck] Exception Caught: org.owasp.dependencycheck.analyzer.exception.SearchException
14:15:14 [DependencyCheck] Message: Could not perform NSP analysis. Invalid payload submitted to Node Security Platform.
14:15:14 [DependencyCheck] org.owasp.dependencycheck.analyzer.exception.SearchException: Could not perform NSP analysis. Invalid payload submitted to Node Security Platform.
14:15:14 [DependencyCheck] 	at org.owasp.dependencycheck.data.nsp.NspSearch.submitPackage(NspSearch.java:168)
14:15:14 [DependencyCheck] 	at org.owasp.dependencycheck.analyzer.NspAnalyzer.analyzeDependency(NspAnalyzer.java:181)
14:15:14 [DependencyCheck] 	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:136)
14:15:14 [DependencyCheck] 	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
14:15:14 [DependencyCheck] 	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
14:15:14 [DependencyCheck] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
14:15:14 [DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
14:15:14 [DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
14:15:14 [DependencyCheck] 	at java.lang.Thread.run(Thread.java:748)
14:15:14 [DependencyCheck] 
14:15:14 Build step 'Invoke Dependency-Check analysis' changed build result to FAILURE

**Comment by stevespringett** [comment]
Then it's likely that running `nsp check` will also fail. If so, try correcting the package.json and resubmit. BTW, nsp was suppose to have been shut down by now, but appears to still be in operation. The NPM Audit analyzer (still being worked on) will likely be included in the next dependency-check release (hopefully).

**Comment by pankajmalhotra** [comment]
I am using Jenkins Plugin, where should I correct package.json file?

**Comment by stevespringett** [comment]
It’s part of the workspace the Jenkins job is building from. Likely checked into version control somewhere.
