### ISSUE TITLE
HTMLReport Bug

### ISSUE THREAD

**Issue by demasb** [dependency-check/DependencyCheck#152]
The HTMLReport output has a bug in the individual Dependency sections "Published Vulnerabilities" block with the functionality of the "Vulnerable Software & Versions: (show all)". When "show all" is selected, the label changes to "undefined", this should toggle between "show all" and "show less" (or something similar). The toggle action functions normally, just the label is undefined.

**Comment by jeremylong** [comment]
Thanks for the report. I actually found this earlier this week and I have already committed the code that fixes the problem. I'm hoping to have a release shortly (prior to AppSec US next week) so the fix will be in a released version within a week.

--Jeremy
