### ISSUE TITLE
Release date of v3.3.3

### ISSUE THREAD

**Issue by dmandalidis** [dependency-check/DependencyCheck#1528]
Hi,

Do you have any idea when v3.3.3 will get released? (Waiting for the maven proxy fix).

Thanks

**Comment by jeremylong** [comment]
I'm hoping to release 3.3.3 tomorrow (Sunday Oct 21st).

**Comment by dmandalidis** [comment]
@jeremylong  Great! Thanks a lot

**Comment by jeremylong** [comment]
It is taking me a little more time due to an issue with the gradle plugin.  3.3.3. should be published this week.
