### ISSUE TITLE
RetireJS full support?

### ISSUE THREAD

**Issue by gbena** [dependency-check/DependencyCheck#1543]
I didnt see any note regarding RetireJS in the latest release 3.3.4, but is RetireJS still considered as experimental analyzer? Is there any plan/ETA to fully support it?

**Comment by jeremylong** [comment]
The RetireJS is fully integrated/supported. It has remained as an experimental partially due to wanting a bit more feedback. With 4.0.0 (the current work effort) we will likely remove the experimental flag.
