### ISSUE TITLE
Node.js file type analyzer

### ISSUE THREAD

**Issue by gbena** [dependency-check/DependencyCheck#1544]
There is a confussion about Node.js file type analyzer support.
Looking at the documentation: https://jeremylong.github.io/DependencyCheck/analyzers/index.html

There is Node.js in the first (full support) and last table (retired). So what is actually it's current status?

Also, now with NPMAnalyzer support, isn't Node.js analyzer now redundant? Do we still need it?

**Comment by jeremylong** [comment]
The NodeJS Package Analyzer attempts to create a more complete SBOM - but does little to nothing towards identifying vulnerabilities. 

I missed removing the Node.js from the retired table. I will update that soon.

**Comment by chakreshkolluru** [comment]
I implemented dependency check plugin in jenkins for Nodejs Application. But the build is taking lot of time to complete. It is taking 1 hour to run one build. Can you help me with this issue?

**Comment by chakreshkolluru** [comment]
One more issue when i run dependency check command line tool ,do i need to enable Retired analyzers for analyzing NodeJS applications?
But i tried without enabling it and getting output. So what is the use of enabling it?
