### ISSUE TITLE
RetireJS URL advanced setting for DependencyCheckMaven plugin not easily configurable

### ISSUE THREAD

**Issue by davewichers** [dependency-check/DependencyCheck#1545]
Looking at: https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html under the RetireJS and Advanced Configuration settings I don't see any way to provide a local URL for the retirejs jsrepository.json file. I have a need to have this file be local, similar to the need to have cveUrl12Base/Modified and cveUrl20Base/Modified be local. 

Apparently the property does exist for DependencyCheck but is not exposed as an easily configurable option for the maven plugin. I would think all the DependencyCheck options would be easily configurable via ALL the DependencyCheck plugins. So while I have a specific need for this particular URL setting (and ALL the other URL settings as well) in the maven plugin, I think this issue applies to lots of configuration settings in many different plugins.

**Comment by albuch** [comment]
FYI: The sbt plugin already exposes the Url and ValidFor settings: https://github.com/albuch/sbt-dependency-check/blob/master/src/main/scala/net/vonbuchholtz/sbt/dependencycheck/DependencyCheckKeys.scala#L54-L55
