### ISSUE TITLE
False positive on anything named *-app

### ISSUE THREAD

**Issue by isaki** [dependency-check/DependencyCheck#1549]
False positive on internal library to a non-public project - reported as cpe:/a:app_project:app:3.3.0

```xml
<dependency>
  <groupId>${project.groupId}</groupId>
  <artifactId>REDACTED-app</artifactId>
  <version>${project.version}</version>
</dependency>
```

This CVE has to due with the Ethereum blockchain; my application has absolutely nothing to do with this once so ever; this is a library for some shared code for various applications built in this project. This seems to affect anything matching `/^\S+-app$/` based on my testing.

**Comment by jeremylong** [comment]
Thanks for the report - I will sweep through all of the FP reports before the next release.
