### ISSUE TITLE
Add the option to scan the dependencyManagement section of a POM

### ISSUE THREAD

**Issue by guidoschreuder** [dependency-check/DependencyCheck#1551]
This would be useful the in case where a super POM or BOM is created that other projects use

**Comment by guidoschreuder** [comment]
@jeremylong just wondering what your opinion on this is

**Comment by jeremylong** [comment]
Interesting - I like the idea. I'll have to take a look at your PR.  However, please understand I'm in the middle of some foundational changes for the 4.x release and so the PR may seem to hang out there longer then I would like.

**Comment by guidoschreuder** [comment]
Not a problem at all, just let me know if i can help
