### ISSUE TITLE
Error on jenkins during dependency-check analysis

### ISSUE THREAD

**Issue by pindi31** [dependency-check/DependencyCheck#1553]
Hi,

I try to configure dependency-check analysis on my project with jenkins.
The version of jenkins is 2.138.2
The version of plugin is 3.3.4

I added the item Invoke Dependency-check upate-only" and "Invoke Dependency-check analysis" with all configurations by default but I have this exception:

[DependencyCheck] Analyzing Dependencies

[DependencyCheck] One or more exceptions were thrown while executing Dependency-Check
[DependencyCheck] Exception Caught: org.owasp.dependencycheck.exception.InitializationException
[DependencyCheck] Cause: bundle-audit initialization failure; this error can be ignored if you are not analyzing Ruby. Otherwise ensure that bundle-audit is installed and the path to bundle audit is correctly specified
[DependencyCheck] Message: Exception from bundle-audit process: java.io.IOException: Cannot run program "bundle-audit" (in directory "C:\Users\svcci\AppData\Local\Temp\dctemp3744ad75-c0ef-4f77-9350-7cdef8c04e5f"): CreateProcess error=2, The system cannot find the file specified. Disabling Ruby Bundle Audit Analyzer
[DependencyCheck] org.owasp.dependencycheck.exception.InitializationException: Exception from bundle-audit process: java.io.IOException: Cannot run program "bundle-audit" (in directory "C:\Users\svcci\AppData\Local\Temp\dctemp3744ad75-c0ef-4f77-9350-7cdef8c04e5f"): CreateProcess error=2, The system cannot find the file specified. Disabling Ruby Bundle Audit Analyzer
[DependencyCheck] 	at org.owasp.dependencycheck.analyzer.RubyBundleAuditAnalyzer.prepareFileTypeAnalyzer(RubyBundleAuditAnalyzer.java:176)
[DependencyCheck] 	at org.owasp.dependencycheck.analyzer.AbstractFileTypeAnalyzer.prepareAnalyzer(AbstractFileTypeAnalyzer.java:83)
[DependencyCheck] 	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.prepare(AbstractAnalyzer.java:107)
[DependencyCheck] 	at org.owasp.dependencycheck.Engine.initializeAnalyzer(Engine.java:825)
[DependencyCheck] 	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:662)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.executeDependencyCheck(DependencyCheckExecutor.java:172)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.call(DependencyCheckExecutor.java:103)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.call(DependencyCheckExecutor.java:46)
[DependencyCheck] 	at hudson.remoting.LocalChannel.call(LocalChannel.java:45)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.AbstractDependencyCheckBuilder.perform(AbstractDependencyCheckBuilder.java:85)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckBuilder.perform(DependencyCheckBuilder.java:206)
[DependencyCheck] 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
[DependencyCheck] 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
[DependencyCheck] 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
[DependencyCheck] 	at hudson.model.Build$BuildExecution.build(Build.java:206)
[DependencyCheck] 	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
[DependencyCheck] 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
[DependencyCheck] 	at hudson.model.Run.execute(Run.java:1819)
[DependencyCheck] 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
[DependencyCheck] 	at hudson.model.ResourceController.execute(ResourceController.java:97)
[DependencyCheck] 	at hudson.model.Executor.run(Executor.java:429)
[DependencyCheck] Caused by: org.owasp.dependencycheck.analyzer.exception.AnalysisException: bundle-audit initialization failure; this error can be ignored if you are not analyzing Ruby. Otherwise ensure that bundle-audit is installed and the path to bundle audit is correctly specified
[DependencyCheck] 	at org.owasp.dependencycheck.analyzer.RubyBundleAuditAnalyzer.launchBundleAudit(RubyBundleAuditAnalyzer.java:151)
[DependencyCheck] 	at org.owasp.dependencycheck.analyzer.RubyBundleAuditAnalyzer.prepareFileTypeAnalyzer(RubyBundleAuditAnalyzer.java:171)
[DependencyCheck] 	... 20 more
[DependencyCheck] Caused by: java.io.IOException: Cannot run program "bundle-audit" (in directory "C:\Users\svcci\AppData\Local\Temp\dctemp3744ad75-c0ef-4f77-9350-7cdef8c04e5f"): CreateProcess error=2, The system cannot find the file specified
[DependencyCheck] 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
[DependencyCheck] 	at org.owasp.dependencycheck.analyzer.RubyBundleAuditAnalyzer.launchBundleAudit(RubyBundleAuditAnalyzer.java:149)
[DependencyCheck] 	... 21 more
[DependencyCheck] Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
[DependencyCheck] 	at java.lang.ProcessImpl.create(Native Method)
[DependencyCheck] 	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
[DependencyCheck] 	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
[DependencyCheck] 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
[DependencyCheck] 	... 22 more
[DependencyCheck] 
Build step 'Invoke Dependency-Check analysis' changed build result to FAILURE

Can you help me

**Comment by stevespringett** [comment]
You have two options. 
1) Install the missing ruby bundle audit cli
2) disable the bundle audit analyzer in the Jenkins global config

**Comment by pindi31** [comment]
I don't find the missing plugin and I don't find the option to disable analyser.
So I installed and launch dependency check in command line to fix the problem but I  would have preferred to use the plugins instead.

Thank you
