### ISSUE TITLE
Failed to initialize the RetireJS repo in Windows 10

### ISSUE THREAD

**Issue by dmandalidis** [dependency-check/DependencyCheck#1554]
After having completed the analysis for a Java project, the plugin tries to delete temporary files where it hangs forever. Tested against both git bash and cmd prompt, both with regular and administrator users. 

The plugin's version in question is 3.3.4 and maven is 3.5.0. Here is the log:

https://gist.github.com/dmandalidis/f1fe926e486599b31fb885833c44ca66

Issue is not reproduced in Linux.

**Comment by dmandalidis** [comment]
Actually, after a very long time the process unfreezes, giving this:

https://gist.github.com/dmandalidis/824dd22458ab9844eed094637c94c8b7

retireJsAnalyzerEnabled is false in my pom.xml

If you 're ok I can change the issue's title to reflect the actual situation.

_edit: retirejs config_

**Comment by jeremylong** [comment]
Looking at the log files it appears you are mirroring the NVD. As such, I'm guessing that you are behind a proxy of some kind and the machine can't pull other data down from the Internet.  The RetireJS analyzer does retrieve a JSON file containing vulnerability information:

https://raw.githubusercontent.com/Retirejs/retire.js/master/repository/jsrepository.json

Apparently, I did not expose the URL configuration property allowing this to be easily mirrored.  However, for the Maven plugin you could simply add:

```
-Danalyzer.retirejs.repo.js.url=[You internal mirror of the jsrepository.json]
```

**Comment by dmandalidis** [comment]
Ok, sorry for the fuss about it, I found the problem and was on my side. Please close the issue, sorry again.

**Comment by Ka2e** [comment]
> Looking at the log files it appears you are mirroring the NVD. As such, I'm guessing that you are behind a proxy of some kind and the machine can't pull other data down from the Internet. The RetireJS analyzer does retrieve a JSON file containing vulnerability information:
> 
> https://raw.githubusercontent.com/Retirejs/retire.js/master/repository/jsrepository.json
> 
> Apparently, I did not expose the URL configuration property allowing this to be easily mirrored. However, for the Maven plugin you could simply add:
> 
> ```
> -Danalyzer.retirejs.repo.js.url=[You internal mirror of the jsrepository.json]
> ```

I'm using DependencyCheck through command line in offline environment，how can I use local jsrepository.json? It seems no param.

**Comment by jansohn** [comment]
@jeremylong please don't swallow errors like these (failed HTTP requests due to proxy settings or similar). It's a nightmare to debug! I've wasted hours trying to find the problem and there was absolutely no error message indicating what the problem was.

It also does not remove the lock file correctly in case of an error when trying to download the jsrepository.json file.

In my case the deprecated `Bypass proxy` global setting in Jenkins caused my update job to always silently fail...
