### ISSUE TITLE
Jenkins plug-in doesn't properly track nested JARs between builds

### ISSUE THREAD

**Issue by scheffelaar** [dependency-check/DependencyCheck#156]
When running a dependency-check build multiple times on a project with multiple copies of spring-struts-3.0.1.RELEASE.jar, which contains the vulnerable com.springsource.org.apache.struts-1.2.9.jar, the Jenkins plug-in will sometimes generate false fixed and new warnings for vulnerabilities in the apache-struts jar. The report will show "fixed" vulnerabilities in one copy of the jar and "new" vulnerabilities of the same type in another copy, for a net of no new vulnerabilities.

This can be annoying if, say, the build is meant to trigger emails on any new vulnerabilities.

I'm guessing this is related to jars-within-jars, as this only happens with this one dependency and it's the only one of its type in my project.

**Comment by stevespringett** [comment]
Have you noticed if the path to the apache struts jar is different each time - perhaps in a different temp folder?

**Comment by scheffelaar** [comment]
The path is different every time this issue occurs, but it's always a legitimate part of the built apps, not in a work directory or anything.

**Comment by stevespringett** [comment]
And to clarify, there are multiple copies of spring-struts-3.0.1.RELEASE.jar? In different paths? 

Also, when you say the paths are different, do you mean the temp directory path is different, or do you mean the paths in the jar or workspace is different?

**Comment by scheffelaar** [comment]
Yup, different copies in different paths. The reason being is that this project spits out a bunch of packaged webapps w/o shared libraries.

I mean that the path in the plug-in report is different, so you get something like:

fixed : vulnerability X in anApp/target/lib/spring-struts-3.0.1-RELEASE.jar/com.springsource.org.apache.struts-1.2.9.jar 
new  : vulernability X in aDifferentApp/target/lib/spring-struts-3.0.1-RELEASE.jar/com.springsource.org.apache.struts-1.2.9.jar 

Those paths are about representative of what I'm seeing, they're not weird or changing from build-to-build or anything.

I'll try to see if I can reproduce this in a simpler setting when I get a chance, to rule out any weirdness due to complexity.

**Comment by scheffelaar** [comment]
Okay, was able to reproduce this by running a job on a folder that just contained a bunch of copies of spring-struts.

```
# find . -type f
./5/spring-struts-3.0.1.RELEASE.jar
./6/spring-struts-3.0.1.RELEASE.jar
./3/spring-struts-3.0.1.RELEASE.jar
./9/spring-struts-3.0.1.RELEASE.jar
./4/spring-struts-3.0.1.RELEASE.jar
./spring-struts-3.0.1.RELEASE.jar
./2/spring-struts-3.0.1.RELEASE.jar
./7/spring-struts-3.0.1.RELEASE.jar
./1/spring-struts-3.0.1.RELEASE.jar
./8/spring-struts-3.0.1.RELEASE.jar
```

After a scan or two I get false fixed and new warnings.
http://imgur.com/NE4S5qk

**Comment by stevespringett** [comment]
Ok, I was finally able to reproduce the issue. Thanks for all your clarification. The issue doesn't appear to be with the Jenkins plugin, but rather the core, as I was able to reproduce the issue with the command line interface as well.

Jeremy, I've forwarded you an archive that I used for testing.

**Comment by jeremylong** [comment]
Sorry this took me so long to get to - it is resolved in the current snapshot. 

Martin - thanks for all the details and answering Steve's questions.

Steve - thanks for the test case.
