### ISSUE TITLE
Scanning NPM modules (package.json) not finding vulnerabilities anymore in 3.3.4, worked in 3.1.1/3.2.1

### ISSUE THREAD

**Issue by AndiDog** [dependency-check/DependencyCheck#1562]
I noticed that a vulnerable project of ours is not found vulnerable anymore with the latest version, so I tested different versions on macOS.

See [package.json, logs and test script](https://gist.github.com/AndiDog/10de751e2fade40e2c44a29e63058cb8).

**Comment by jeremylong** [comment]
Thanks for the bug report! We are heads down re-working some of the core engine. We will try to look at this soon.  Really appreciate the package.json, logs, and test script - that will be really helpful.

**Comment by jeremylong** [comment]
At this point - I believe the 3.x branch is using APIs that are no longer available.
