### ISSUE TITLE
[3.3.4/4.0.0] Unable to resolve system scoped dependency: system:jdk-tools:jar:jdk:system

### ISSUE THREAD

**Issue by ottlinger** [dependency-check/DependencyCheck#1574]
Updated to 3.3.4 and 4.0.0 and build fails with
`16:38:10 [CVE] [ERROR] Failed to execute goal org.owasp:dependency-check-maven:4.0.0:check (default) on project myproject: One or more exceptions occurred during dependency-check analysis: One or more exceptions occurred during analysis:
16:38:10 [CVE] [ERROR] 	Unable to resolve system scoped dependency: system:jdk-tools:jar:jdk:system
16:38:10 [CVE] [ERROR] -> [Help 1]`

configuration used is:
`          <plugin>
            <groupId>org.owasp</groupId>
            <artifactId>dependency-check-maven</artifactId>
            <version>4.0.0</version>
            <executions>
              <execution>
                <goals>
                  <goal>check</goal>
                </goals>
              </execution>
            </executions>
          </plugin>`

while running
`$ dependency-check:check with
Maven Version: 3.5.3
JDK Version: 1.8.0_162 normalized as: 1.8.0-162 on
OS Info: Arch: amd64 Family: unix Name: linux Version: 3.10.0-514.26.2.el7.x86_64
`

Any idea what I should configure in my pom? Which artifact needs system:jdk-tools:jar:jdk:system
(or can I exclude the artifact as is possible with dependencies as said here:
https://stackoverflow.com/questions/8375423/missing-artifact-com-suntoolsjar)

**Comment by mprins** [comment]
`skipSystemScope` should do the trick 
see: https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html

**Comment by gridcellcoder** [comment]
Were running a docker container `maven:3.6.1-jdk-8` and when running `mvn org.owasp:dependency-check-maven:check`

```
root@host:/docker-java-home# mvn --version
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T19:00:29Z)
Maven home: /usr/share/maven
Java version: 1.8.0_212, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "4.18.0-1008-gcp", arch: "amd64", family: "unix"

root@host:/docker-java-home# java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1~deb9u1-b01)
OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode
```

```
Caused by: org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during analysis:
	Unable to resolve system scoped dependency: jdk.tools:jdk.tools:jar:1.8:system
    at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.collectMavenDependencies (BaseDependencyCheckMojo.java:958)
    at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.collectDependencies (BaseDependencyCheckMojo.java:1062)
    at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.scanArtifacts (BaseDependencyCheckMojo.java:841)
    at org.owasp.dependencycheck.maven.AggregateMojo.scanDependencies (AggregateMojo.java:67)
    at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.runCheck (BaseDependencyCheckMojo.java:1282)
    at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.generate (BaseDependencyCheckMojo.java:762)
    at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.generate (BaseDependencyCheckMojo.java:714)
    at org.apache.maven.plugins.site.render.ReportDocumentRenderer.renderDocument (ReportDocumentRenderer.java:239)
```

With `skipSystemScope`  = `true`

```
<plugin>
                <groupId>org.owasp</groupId>
                <artifactId>dependency-check-maven</artifactId>
                <version>5.0.0-M2</version>
                <configuration>
                    <failBuildOnCVSS>8</failBuildOnCVSS>
                    <suppressionFiles>
                        <suppressionFile>${basedir}/project-suppression.xml</suppressionFile>
                    </suppressionFiles>
                    <skipSystemScope>true</skipSystemScope>
                </configuration>

                <executions>
                    <execution>

                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

Do we need to do anything else in the `pom.xml`?

**Comment by ottlinger** [comment]
That did the trick for me @gridcellcoder. Feel free to open a new issue if there's a problem with that.
