### ISSUE TITLE
zaproxy 1.0.0-rc.1 is now available

### ISSUE THREAD

**Issue by binarymist** [dependency-check/DependencyCheck#1575]
There is a [new release](https://www.npmjs.com/package/zaproxy/v/1.0.0-rc.1) of zaproxy available with some [breaking changes](https://github.com/zaproxy/zap-api-nodejs/blob/master/CHANGELOG.md). I'd love to know how you get on with it? Let me know if you need any assistance with upgrading.

**Comment by jeremylong** [comment]
dependency-check does not use zap-api-nodejs.

**Comment by binarymist** [comment]
https://github.com/jeremylong/DependencyCheck/blob/8c6ca08daa7caf1df5d4bd6da4798cbddd46c755/core/src/test/resources/nodeaudit/package.json#L55

**Comment by jeremylong** [comment]
oh - sorry.  That is purely a test resource and it is not actually used. We scan the referenced `package.json` to identify known vulnerable dependencies.

**Comment by binarymist** [comment]
Ah, thanks for the clarification :-)
