### ISSUE TITLE
NullPointerException during analysys

### ISSUE THREAD

**Issue by PalmerEldritch123** [dependency-check/DependencyCheck#1577]
See logs: https://gist.github.com/PalmerEldritch123/f2ee0d3e6df7dd3054966a65f94c2106

Maven plugin version 4.0.0 (happened on 3.3.4 too).
Jenkins plugin version 4.0.0 (happened on 3.3.4 too).

**Comment by jeremylong** [comment]
Looks like some additional error handling is needed to better support package.json files that do not put a version number.  Any chance you can share the project or at least the file(s) that are causing the sanitize to fail?

**Comment by PalmerEldritch123** [comment]
Sure, here are original package.json files from my project:
https://gist.github.com/PalmerEldritch123/d520e76748bfcd362aa071c279e2e03c
https://gist.github.com/PalmerEldritch123/8fa4fb32637177ae814686132aaee6d5

After your comment I added "version" field to both those files. Now following happens:

>[INFO] --- dependency-check-maven:4.0.0:check (default) @ *** ---
>[INFO] Central analyzer disabled
>
>[INFO] Checking for updates
>[INFO] Skipping NVD check since last check was within 4 hours.
>[INFO] Skipping RetireJS update since last update was within 24 hours.
>[INFO] Check for updates complete (95 ms)
>
>[INFO] Analysis Started
>[INFO] Finished Archive Analyzer (0 seconds)
>[INFO] Finished File Name Analyzer (0 seconds)
>[INFO] Finished Jar Analyzer (0 seconds)
>[INFO] Finished Node.js Package Analyzer (0 seconds)
>[INFO] Finished Dependency Merging Analyzer (0 seconds)
>[INFO] Finished Version Filter Analyzer (0 seconds)
>[INFO] Finished Hint Analyzer (0 seconds)
>
>[INFO] Created CPE Index (0 seconds)
>[INFO] Skipping CPE Analysis for npm
>[INFO] Finished CPE Analyzer (1 seconds)
>[INFO] Finished False Positive Analyzer (0 seconds)
>[INFO] Finished NVD CVE Analyzer (0 seconds)
>[WARNING] An unexpected error occurred during analysis of '/svn/jenkins/.jenkins/workspace/***/package-lock.json' (Node Audit Analyzer): null
>[INFO] Finished Node Audit Analyzer (0 seconds)
>[INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
>[INFO] Finished Dependency Bundling Analyzer (0 seconds)
>[INFO] Analysis Complete (2 seconds)

and exception:
https://gist.github.com/PalmerEldritch123/84a8bf20049a0700cc2bbc0b87464ef9

**Comment by pauldambra** [comment]
We've just started seeing this issue too.

`[WARN] An unexpected error occurred during analysis of '/Users/blah/git/foo/package-lock.json' (Node Audit Analyzer): null`

I can run `npm audit` successfully

I'm running (and the package lock was generated using) Node v8.12.0

I don't think I can share it. The only out of the ordinary thing is 2 dependencies in the package.json are included via github links not from npm

e.g.

```
"coop-frontend-toolkit": "github:coopdigital/coop-frontend-toolkit#2.0.0-alpha",
```

**Comment by pauldambra** [comment]
Tried updating package lock and agent to v8.15.0 of node

```
00:14:01.352 [DependencyCheck] OWASP Dependency-Check Plugin v4.0.2
00:14:01.452 [DependencyCheck] Executing Dependency-Check with the following options:
00:14:01.453 [DependencyCheck]  -name = registration-pipeline
00:14:01.454 [DependencyCheck]  -scanPath = /home/jenkins/jenkins-swarm/workspace/registration-pipeline
00:14:01.454 [DependencyCheck]  -outputDirectory = /home/jenkins/jenkins-swarm/workspace/registration-pipeline
00:14:01.454 [DependencyCheck]  -dataDirectory = /home/jenkins/dependency-check-data
00:14:01.454 [DependencyCheck]  -suppressionFile = /home/jenkins/jenkins-swarm/workspace/registration-pipeline/dependency-check-suppressions.xml
00:14:01.454 [DependencyCheck]  -dataMirroringType = none
00:14:01.454 [DependencyCheck]  -isQuickQueryTimestampEnabled = false
00:14:01.454 [DependencyCheck]  -jarAnalyzerEnabled = true
00:14:01.454 [DependencyCheck]  -nodePackageAnalyzerEnabled = true
00:14:01.454 [DependencyCheck]  -nodeAuditAnalyzerEnabled = true
00:14:01.454 [DependencyCheck]  -retireJsAnalyzerEnabled = false
00:14:01.454 [DependencyCheck]  -composerLockAnalyzerEnabled = false
00:14:01.454 [DependencyCheck]  -pythonDistributionAnalyzerEnabled = true
00:14:01.454 [DependencyCheck]  -pythonPackageAnalyzerEnabled = true
00:14:01.454 [DependencyCheck]  -rubyBundlerAuditAnalyzerEnabled = false
00:14:01.454 [DependencyCheck]  -rubyGemAnalyzerEnabled = true
00:14:01.454 [DependencyCheck]  -cocoaPodsAnalyzerEnabled = false
00:14:01.454 [DependencyCheck]  -swiftPackageManagerAnalyzerEnabled = false
00:14:01.454 [DependencyCheck]  -archiveAnalyzerEnabled = true
00:14:01.454 [DependencyCheck]  -assemblyAnalyzerEnabled = true
00:14:01.454 [DependencyCheck]  -msBuildProjectAnalyzerEnabled = false
00:14:01.454 [DependencyCheck]  -nuGetConfigAnalyzerEnabled = false
00:14:01.454 [DependencyCheck]  -nuspecAnalyzerEnabled = false
00:14:01.454 [DependencyCheck]  -centralAnalyzerEnabled = true
00:14:01.454 [DependencyCheck]  -nexusAnalyzerEnabled = false
00:14:01.454 [DependencyCheck]  -artifactoryAnalyzerEnabled = false
00:14:01.454 [DependencyCheck]  -autoconfAnalyzerEnabled = false
00:14:01.454 [DependencyCheck]  -cmakeAnalyzerEnabled = false
00:14:01.454 [DependencyCheck]  -opensslAnalyzerEnabled = true
00:14:01.454 [DependencyCheck]  -showEvidence = true
00:14:01.454 [DependencyCheck]  -formats = XML HTML VULN JSON 
00:14:01.454 [DependencyCheck]  -autoUpdate = true
00:14:01.454 [DependencyCheck]  -updateOnly = false
00:14:01.455 [DependencyCheck] WARNING: Suppression file does not exist. Omitting.
00:14:01.455 [DependencyCheck] Data directory created
00:14:01.905 [DependencyCheck] Scanning: /home/jenkins/jenkins-swarm/workspace/registration-pipeline
00:14:13.777 [DependencyCheck] Analyzing Dependencies
00:18:01.266 [DependencyCheck] One or more exceptions were thrown while executing Dependency-Check
00:18:01.267 [DependencyCheck] Exception Caught: java.lang.NullPointerException
00:18:01.269 [DependencyCheck] Message: null
00:18:01.276 [DependencyCheck] java.lang.NullPointerException
00:18:01.276 [DependencyCheck] 	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:199)
00:18:01.276 [DependencyCheck] 	at org.owasp.dependencycheck.data.nodeaudit.SanitizePackage.sanitize(SanitizePackage.java:53)
00:18:01.276 [DependencyCheck] 	at org.owasp.dependencycheck.analyzer.NodeAuditAnalyzer.analyzeDependency(NodeAuditAnalyzer.java:176)
00:18:01.276 [DependencyCheck] 	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:136)
00:18:01.276 [DependencyCheck] 	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
00:18:01.276 [DependencyCheck] 	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
00:18:01.276 [DependencyCheck] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
00:18:01.276 [DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
00:18:01.276 [DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
00:18:01.276 [DependencyCheck] 	at java.lang.Thread.run(Thread.java:748)
00:18:01.276 [DependencyCheck] 
[Pipeline] dependencyCheckPublisher
00:18:01.286 [DependencyCheck] Skipping publisher since build result is FAILURE
```

**Comment by pauldambra** [comment]
Ah! So, even though we could run npm audit locally it turns out the package.json file didn't have the required name and version fields. Now I've added them it works fine

**Comment by renaudl** [comment]
I do experience as well.
