### ISSUE TITLE
Jenkins plugin loses trace of bcprov-jdk15on.jar vulnerabilities

### ISSUE THREAD

**Issue by pachulo** [dependency-check/DependencyCheck#1578]
We're using the Jenkins plugin to analyze our software and are experimenting a buggy behavior: every time we do a scan the plugin says that we got:
```
12 new vulnerabilities
12 Fixed vulnerabilities
```
And the problem is that all of them are the same vulnerabilities, scan after scan, related to the Bouncy Castle provider: **bcprov-jdk15on.jar**

![image](https://user-images.githubusercontent.com/3256953/48907536-0e604600-ee68-11e8-86a3-c95710e01986.png)

![image](https://user-images.githubusercontent.com/3256953/48907421-a9a4eb80-ee67-11e8-9e90-3ea378a70852.png)

So, it looks like the plugin loses trace of those vulns. Does this happen to anyone else?

**Comment by stevespringett** [comment]
According to the wiki, this was corrected in 3.3.0. https://wiki.jenkins-ci.org/display/JENKINS/OWASP+Dependency-Check+Plugin

If you’re still experiencing issues with the latest 4.0 release, create a ticket here https://issues.jenkins-ci.org

**Comment by pachulo** [comment]
We're using version 3.3.4, so I guess it's not the same issue, so I will create a ticket there, thanks!

**Comment by pachulo** [comment]
Issue opened: https://issues.jenkins-ci.org/browse/JENKINS-54838

**Comment by stevespringett** [comment]
What implementation is producing dependency-check-report.xml? Or is Jenkins plugin also doing the scan?

**Comment by stevespringett** [comment]
No longer relevant with v5.0.0
