### ISSUE TITLE
With 4.0.0 all our internal projects are detected as Jenkins

### ISSUE THREAD

**Issue by TobiX** [dependency-check/DependencyCheck#1596]
I'm not really sure why this is suddenly an issue. All our internal artifacts have this in their MANIFEST.MF:

```
Implementation-URL: http://internal-jenkins.company.com/sites/groupId/artifactId/
```
When switching from DependencyCheck 3.3.4 to 4.0.0, all those modules are suddenly detected as `cpe:/a:jenkins:jenkins`.

Some projects have this in their MANIFEST.MF:
```
X-CI-Job-Name: group/project/release
```
Those are additionally detected as `cpe:/a:jenkins:release`...

When I look at the [diff between those versions](https://github.com/jeremylong/DependencyCheck/compare/v3.3.4...v4.0.0) the only culprit can be the lucene update, right?

I know I can work around this issue with local suppressions, but I wonder if there is a different tweakable which would avoid these kinds of false-positives...

**Comment by Feralus** [comment]
Lot of people have this problem. As you already said it is caused by the upgrade from 3.3.4 to 4.0.0.
It looks like it's enough if version matches.

See other Issues: [1580](https://github.com/jeremylong/DependencyCheck/issues/1580), [1579](https://github.com/jeremylong/DependencyCheck/issues/1579)

**Comment by TobiX** [comment]
Since this is already discussed in #1580, I'll close this issue.
