### ISSUE TITLE
DbStatements properties file for MSSQL

### ISSUE THREAD

**Issue by Rora** [dependency-check/DependencyCheck#1598]
First of all, I want to thank you guys for this awesome tool. 

I'm trying to do a central setup for using MSSQL. Looking at https://github.com/jeremylong/DependencyCheck/tree/master/core/src/main/resources/data I see multiple dbStatements files, but none for MSSQL. I got 2 questions:

1. Do I need to supply a DbStatements.properties file when using a MSSQL db?
2. If so, why is it not listed in https://github.com/jeremylong/DependencyCheck/tree/master/core/src/main/resources/data?

**Comment by jeremylong** [comment]
Sorry for the delayed response.  The extra property files for specific databases are over-rides when the default syntax used either does not work or is extremely inefficient in the given database.  You should be fine using MS SQL.

**Comment by Rora** [comment]
Ok thx!
