### ISSUE TITLE
Gradle 5.0 Support

### ISSUE THREAD

**Issue by nigelsim** [dependency-check/DependencyCheck#1602]
When trying to use org.owasp:dependency-check-gradle:4.0.0 with Gradle 5.0 the following error occurs:
https://gist.github.com/nigelsim/039a4bd45f52dfdea8b7de110a2bf2dc

**Comment by malejpavouk** [comment]
4.0.0.1, but beware there are new FPs in version 4.X due to Lucene update (see other threads)

**Comment by nigelsim** [comment]
Thanks, working now.
