### ISSUE TITLE
Error calling NSPAnalyser

### ISSUE THREAD

**Issue by javixeneize** [dependency-check/DependencyCheck#1607]
Hi

Im having an error when using dependency check plugin in jenkins (4.0.0)

[DependencyCheck] Message: Failed to read results from the Node Security Project (NspAnalyzer); the analyzer is being disabled and may result in false negatives.
[DependencyCheck] org.owasp.dependencycheck.analyzer.exception.AnalysisException: Failed to read results from the Node Security Project (NspAnalyzer); the analyzer is being disabled and may result in false negatives.
[DependencyCheck] 	at org.owasp.dependencycheck.analyzer.NspAnalyzer.analyzeDependency(NspAnalyzer.java:225)
[DependencyCheck] 	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:136)

I am reading that NSP analyser is deprecated

https://github.com/jeremylong/DependencyCheck/blob/8c6ca08daa7caf1df5d4bd6da4798cbddd46c755/core/src/main/resources/META-INF/services/org.owasp.dependencycheck.analyzer.Analyzer

But apparently this is still an option in the jenkins plugin

I assume the solution is to untick that option in jenkins configuration, but, should this option not be removed?

Thanks

**Comment by stevespringett** [comment]
I have no idea where that's coming from, but NSP was removed from the Jenkins plugin awhile ago. There is no option to configure it and the constants in org.owasp.dependencycheck.utils.Settings that the Jenkins plugin relies on, doesn't have NSP as an option.

**Comment by stevespringett** [comment]
Jenkins plugin v5.0.0 no longer has analyzer configuration. Closing.
