### ISSUE TITLE
Node Audit analysis

### ISSUE THREAD

**Issue by alinleonard** [dependency-check/DependencyCheck#1632]
We are using in our pipeline dependency check (jenkins) and with the latest version 4.0.1 we get the following error:

Message: Could not perform Node Audit analysis. Invalid payload submitted to Node Audit API.

[DependencyCheck] org.owasp.dependencycheck.analyzer.exception.SearchException: Could not perform Node Audit analysis. Invalid payload submitted to Node Audit API.

**Note that this error I also get when I use command line also.**

**Comment by githubhs17** [comment]
Got same error "[ERROR] Could not perform Node Audit analysis. Invalid payload submitted to Node Audit API." with docker owasp/dependency-check:4.0.2
