### ISSUE TITLE
org.owasp.dependencycheck.exception.NoDataException: Autoupdate is disabled and the database does not exist

### ISSUE THREAD

**Issue by xiaoyanguoke** [dependency-check/DependencyCheck#1633]
I configure dependency-check on Jenkins，My server has no network permissions, set isAutoupdateDisabled: true，dependencyCheckAnalyzer datadir: '/app/jenkins/dependency-check/nvdcve-2.0-2018.xml.gz'

dependencyCheckAnalyzer datadir: '/app/jenkins/dependency-check/nvdcve-2.0-2018.xml.gz',
                isAutoupdateDisabled: true,
                hintsFile: '', 
                includeCsvReports: false, 
                includeHtmlReports: false, 
                includeJsonReports: false, 
                outdir: '', 
                scanpath: '/app/jenkins/jenkinsworkspace/guanwang/guanwang/ec-web/WEB-INF/lib/*.jar', 
                skipOnScmChange: false, 
                skipOnUpstreamChange: false, 
                suppressionFile: '', 
                includeVulnReports: true,
                zipExtensions: ''

But the following error occurred：
![image](https://user-images.githubusercontent.com/15224735/50208913-67f75a00-03ad-11e9-9205-47c998f06f8c.png)

**Comment by jeremylong** [comment]
Please see [Internet Access Required](https://jeremylong.github.io/DependencyCheck/data/index.html).

**Comment by tiffanyzhou** [comment]
I have the same problem, and the previous configuration was successful, and suddenly reported this error, who can answer what is the cause?

![image](https://user-images.githubusercontent.com/39646571/55865581-3cdd8400-5bb1-11e9-9253-493e00c5ab18.png)

**Comment by jeremylong** [comment]
Please see the documentation regarding this type of setup: https://jeremylong.github.io/DependencyCheck/data/index.html
