### ISSUE TITLE
please suport maven pom.xml check

### ISSUE THREAD

**Issue by hktalent** [dependency-check/DependencyCheck#1644]
please suport maven pom.xml check
thanks 
use 
$mvn org.owasp:dependency-check-maven:check
？

or please collection "mvn org.owasp:dependency-check-maven:check"
for us,thans for you
#1270

**Comment by jeremylong** [comment]
Correct, to analyze a maven build (i.e. pom.xml) you would just use `mvn org.owasp:dependency-check-maven:4.0.1:check` or you could use the aggregate mojo for a multi-module project.
