### ISSUE TITLE
dependency-check can not scan  /root/dependency-check/lib/*.jar

### ISSUE THREAD

**Issue by xiaoyanguoke** [dependency-check/DependencyCheck#1649]
dependencyCheckAnalyzer datadir: '',
                hintsFile: '', 
                includeVulnReports: true,
                includeCsvReports: false, 
                includeHtmlReports: false, 
                includeJsonReports: false, 
                isAutoupdateDisabled: false, 
                outdir: '',
                scanpath: '/root/dependency-check/lib/*.jar', 
                skipOnScmChange: false, 
                skipOnUpstreamChange: false, 
                suppressionFile: '', 
                zipExtensions: ''

jenkins can not scan /root/dependency-check/lib/*.jar 
![image](https://user-images.githubusercontent.com/15224735/50583680-ac065680-0ea5-11e9-8bba-a03e40f1925b.png)

**Comment by jeremylong** [comment]
Are you sure there are actually any files in the directory? If so, are they in the root of the folder or are they in sub-folders?  ODC uses ant style paths so try:

```
scanpath: '/root/dependency-check/lib/**/*.jar',
```

But in general, I wouldn't limit the check to just JAR files. While still expiremental we are including Retire.js scanning to look for vulnerable JavaScript libraries.

**Comment by xiaoyanguoke** [comment]
@jeremylong scanpath: '/root/dependency-check/lib/*.jar',  this directory is really exists and has many jar files.

**Comment by jeremylong** [comment]
To help further we would need to see a debug log. You'll need to configure the logging and then I believe restart Jenkins. I'm not sure if @stevespringett has documented this anywhere explicitly for the ODC Jenkins plugin.

**Comment by xiaoyanguoke** [comment]
@jeremylong 
[Pipeline] { (依赖组件扫描)
[Pipeline] dependencyCheckAnalyzer
[DependencyCheck] OWASP Dependency-Check Plugin v4.0.2
[DependencyCheck] Executing Dependency-Check with the following options:
[DependencyCheck]  -name = dependenct-check
[DependencyCheck]  -scanPath = /root/.jenkins/workspace/dependenct-check/${SCANJARPATH}
[DependencyCheck]  -outputDirectory = /root/.jenkins/workspace/dependenct-check
[DependencyCheck]  -dataDirectory = /root/.jenkins/workspace/dependenct-check/dependency-check-data
[DependencyCheck]  -dataMirroringType = none
[DependencyCheck]  -isQuickQueryTimestampEnabled = true
[DependencyCheck]  -jarAnalyzerEnabled = true
[DependencyCheck]  -nodePackageAnalyzerEnabled = true
[DependencyCheck]  -nodeAuditAnalyzerEnabled = true
[DependencyCheck]  -retireJsAnalyzerEnabled = true
[DependencyCheck]  -composerLockAnalyzerEnabled = true
[DependencyCheck]  -pythonDistributionAnalyzerEnabled = true
[DependencyCheck]  -pythonPackageAnalyzerEnabled = true
[DependencyCheck]  -rubyBundlerAuditAnalyzerEnabled = false
[DependencyCheck]  -rubyGemAnalyzerEnabled = true
[DependencyCheck]  -cocoaPodsAnalyzerEnabled = true
[DependencyCheck]  -swiftPackageManagerAnalyzerEnabled = true
[DependencyCheck]  -archiveAnalyzerEnabled = true
[DependencyCheck]  -assemblyAnalyzerEnabled = true
[DependencyCheck]  -msBuildProjectAnalyzerEnabled = true
[DependencyCheck]  -nuGetConfigAnalyzerEnabled = true
[DependencyCheck]  -nuspecAnalyzerEnabled = true
[DependencyCheck]  -centralAnalyzerEnabled = true
[DependencyCheck]  -nexusAnalyzerEnabled = false
[DependencyCheck]  -artifactoryAnalyzerEnabled = false
[DependencyCheck]  -autoconfAnalyzerEnabled = true
[DependencyCheck]  -cmakeAnalyzerEnabled = true
[DependencyCheck]  -opensslAnalyzerEnabled = true
[DependencyCheck]  -showEvidence = true
[DependencyCheck]  -formats = XML VULN 
[DependencyCheck]  -autoUpdate = true
[DependencyCheck]  -updateOnly = false
[DependencyCheck] Analyzing Dependencies
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS

**Comment by xiaoyanguoke** [comment]
@jeremylong 

[Pipeline] { (依赖组件扫描)
[Pipeline] step
[DependencyCheck] OWASP Dependency-Check Plugin v4.0.2
[DependencyCheck] Executing Dependency-Check with the following options:
[DependencyCheck]  -name = dependenct-check
[DependencyCheck]  -scanPath = /root/dependency-check/lib/*.jar
[DependencyCheck]  -outputDirectory = /root/.jenkins/workspace/dependenct-check
[DependencyCheck]  -dataDirectory = /root/.jenkins/workspace/dependenct-check/dependency-check-data
[DependencyCheck]  -dataMirroringType = none
[DependencyCheck]  -isQuickQueryTimestampEnabled = true
[DependencyCheck]  -jarAnalyzerEnabled = true
[DependencyCheck]  -nodePackageAnalyzerEnabled = true
[DependencyCheck]  -nodeAuditAnalyzerEnabled = true
[DependencyCheck]  -retireJsAnalyzerEnabled = true
[DependencyCheck]  -composerLockAnalyzerEnabled = true
[DependencyCheck]  -pythonDistributionAnalyzerEnabled = true
[DependencyCheck]  -pythonPackageAnalyzerEnabled = true
[DependencyCheck]  -rubyBundlerAuditAnalyzerEnabled = false
[DependencyCheck]  -rubyGemAnalyzerEnabled = true
[DependencyCheck]  -cocoaPodsAnalyzerEnabled = true
[DependencyCheck]  -swiftPackageManagerAnalyzerEnabled = true
[DependencyCheck]  -archiveAnalyzerEnabled = true
[DependencyCheck]  -assemblyAnalyzerEnabled = true
[DependencyCheck]  -msBuildProjectAnalyzerEnabled = true
[DependencyCheck]  -nuGetConfigAnalyzerEnabled = true
[DependencyCheck]  -nuspecAnalyzerEnabled = true
[DependencyCheck]  -centralAnalyzerEnabled = true
[DependencyCheck]  -nexusAnalyzerEnabled = false
[DependencyCheck]  -artifactoryAnalyzerEnabled = false
[DependencyCheck]  -autoconfAnalyzerEnabled = true
[DependencyCheck]  -cmakeAnalyzerEnabled = true
[DependencyCheck]  -opensslAnalyzerEnabled = true
[DependencyCheck]  -showEvidence = true
[DependencyCheck]  -formats = XML VULN 
[DependencyCheck]  -autoUpdate = true
[DependencyCheck]  -updateOnly = false
[DependencyCheck] Analyzing Dependencies
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS

**Comment by xiaoyanguoke** [comment]
@jeremylong this question already resolve.thanks
