### ISSUE TITLE
fatal error on running check goal with Maven plugin 4.0.2

### ISSUE THREAD

**Issue by javabeanz** [dependency-check/DependencyCheck#1651]
When i run mvn org.owasp:dependency-check-maven:check is get :

[ERROR] Failed to execute goal org.owasp:dependency-check-maven:4.0.2:check (default-cli) on project maven: A type incompatibility occured while executing org.owasp:dependency-check-maven:4.0.2:check: org.sonatype.aether.util.DefaultRepositorySystemSession cannot be cast to org.eclipse.aether.RepositorySystemSession
....
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------

I tried this on several maven projects, result is the same.

Maven 3.0.5
java openjdk 1.8.0_191

**Comment by Stephan202** [comment]
Hi @javabeanz, this error happens because the plugin is no longer compatible with Maven 3.0.x. See also #1313.

**Comment by javabeanz** [comment]
ok, thanks for your reply. Centos has this version in the yum repos.

**Comment by javabeanz** [comment]
ok.
