### ISSUE TITLE
Question: Coordinates

### ISSUE THREAD

**Issue by githubhs17** [dependency-check/DependencyCheck#1670]
Extract from Dependency-Check Report:

Dependency | CPE | Coordinates↑ | Highest Severity | CVE Count | CPE Confidence | Evidence Count
-- | -- | -- | -- | -- | -- | --
methods:1.1.2 |   | methods:1.1.2 |   | 0 |   | 4
mime |   | mime:null | Low | 1 |   | 3
mime-db:1.12.0 |   |   |   | 0 |   | 3
mime-db:1.37.0 |   | mime-db:1.37.0 |   | 0 |   | 4
mime-types:2.0.14 |   |   |   | 0 |   | 3
mime-types:2.1.21 |   | mime-types:2.1.21 |   | 0 |   | 4
mime:1.3.4 |   |   |   | 0 |   | 3
mime:1.4.1 |   | mime:1.4.1 |   | 0 |   | 7
minimatch |   | minimatch:null | Low | 1 |   | 3
minimatch:0.3.0 |   |   |   | 0 |   | 3
minimatch:0.4.0 |   |   |   | 0 |   | 3
minimatch:3.0.4 |   | minimatch:3.0.4 |   | 0 |   | 10
minimist:0.0.8 |   | minimist:0.0.8 |   | 0 |  

My questions:
- what is Coordinates ? In the document https://jeremylong.github.io/DependencyCheck/general/thereport.html this is not described
- in the above table there are some **:null** entries. Where is this coming from ? What does this mean ?
- in the above table there are some empty Coordinates. When is the field Coordinates empty ?

Thanks

**Comment by githubhs17** [comment]
Will be lucky if you can answer my questions, especially the second one with the **null** entries. Thanks.

**Comment by mprins** [comment]
"coordinates" are the Maven dependency triplet of <groupId>:<artifactId>:<version>, wher you see a null the version if unknown, for the rest you should check the code

**Comment by jeremylong** [comment]
When the coordinates are null - it is likely that you are using the CLI, ANT, or Jenkins plugin.  If the JAR file does not contain a pom.xml we have no idea what the coordinates of the JAR file is.  There are a few other techniques used to determine the coordinates - but it is null/blank if we can't figure it out.  This did change some in 5.0.0 (column names).
