### ISSUE TITLE
Hard stop on dependency which is not found

### ISSUE THREAD

**Issue by alexanderkjall** [dependency-check/DependencyCheck#1674]
When scanning a project that uses this dependency:

```
        <dependency>
            <groupId>org.jolokia</groupId>
            <artifactId>jolokia-spring</artifactId>
            <version>1.6.0</version>
        </dependency>
```

Then the scanning stops with the following output:

Log output:
```
[ERROR] Unable to resolve system scoped dependency: com.sun:tools:jar:1.8:system
```

Full stacktrace: https://gist.github.com/alexanderkjall/893c6ddb4418944c254180adb387172e

**Comment by aikebah** [comment]
Which is by design, we require all dependencies resolved for a successful run
