### ISSUE TITLE
FP on velocity-tools.jar - reported as `cpe:/a:apache:struts`

### ISSUE THREAD

**Issue by stepio** [dependency-check/DependencyCheck#1676]
False positive on library velocity-tools.jar - reported as `cpe:/a:apache:struts`
```xml
<dependency>
    <groupId>org.apache.velocity</groupId>
    <artifactId>velocity-tools</artifactId>
    <version>2.0</version>
</dependency>
```
Maven reports this "vulnerability" upon scanning WAR file. So it detects it by hash, not by GAV.

SHA1 of `velocity-tools` can be checked here:
https://repo1.maven.org/maven2/org/apache/velocity/velocity-tools/2.0/velocity-tools-2.0.jar.sha1

Proposed suppression rule is (I can create a PR):
```
   <suppress>
      <notes><![CDATA[
      FP for velocity-tools
      ]]></notes>
      <sha1>69936384de86857018b023a8c56ae0635c56b6a0</sha1>
      <cpe>cpe:/a:apache:struts</cpe>
   </suppress>
```

The question is... is such case valuable for the library? Or is it better to suppress it just locally?

**Comment by stepio** [comment]
Ping @jeremylong. Just got an idea.

Have you thought about retrieving `sha1` (and maybe some other) hashes from maven-central using the available `gav` rules ad using them to enrich all the suppression rules automatically?

In my opinion this could resolve all such cases "automagically", without explicit configuration.

**Comment by jeremylong** [comment]
This is resolved in the 6.x releases.
