### ISSUE TITLE
4.0.2: Issue with version range in dependencyManagement and skipDependencyManagement of false

### ISSUE THREAD

**Issue by dranuhl** [dependency-check/DependencyCheck#1677]
Any project that uses `dependencyManagement` with a version range like `[1.0.0,2.0.0)` together with the
new 4.0.2 option `<skipDependencyManagement>false</skipDependencyManagement>` option will lead to errors like the following:

> ...
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.7.1:site (default-site) on project explorer:  Error generating dependency-check-maven:4.0.2:check report: One or more exceptions occurred during dependency-check analysis: One or more exceptions occurred during analysis:
> [ERROR]         Could not find artifact com.example.privatelib:privatelib:jar:[1.0.0,2.0.0) in private (https://www.example.com/maven/private/)
> 

Looking that the web server it shows, that the Maven DependencyCheck plugin uses the version string directly in its lookup operation, instead of using Maven's version resolution first.
For example:
> 127.0.0.1 - - [11/Jan/2019:11:33:34 +0100] "GET /maven/private/com/example/privatelib/privatelib/%5B1.0.0,2.0.0)/privatelib-%5B1.0.0,2.0.0).jar

Instead of using whatever version is the most current one.

**Comment by dranuhl** [comment]
If the OWASP DependencyCheck plugin is used as part of an invoker plugin based IT test, one can facilitate `versions:resolve-ranges` in a first goal execution before the actual dependency-check is been executed as a second goal.

**Comment by dranuhl** [comment]
Issue still exists with 5.2.x versions.

**Comment by jeremylong** [comment]
Please see PR #2365 for details on the fix. There is still a scenario that will cause the analysis to fail.
