### ISSUE TITLE
java.lang.StackOverflowError

### ISSUE THREAD

**Issue by canerce** [dependency-check/DependencyCheck#1691]
Hello,

I'm using dependency-check with jenkins via plugin and I've started to get a StackOverflowError exception for a project. There is no more info on error. Could you help me to solve problem?

If you need more info, please direct me.

**Console Output:** https://gist.github.com/canerce/3f5da712e9e782ece4d13fae421d643f
**OS:** 
`Linux 3.10.0-693.33.1.el7.x86_64 #1 SMP Thu May 24 16:41:13 UTC 2018 x86_64 x86_64 x86_64 `GNU/Linux
**Java:**
```
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)
```
**Jenkins:** ver. 2.150.1

**Comment by markluebbehuesen** [comment]
Hello,

I have the same error.

Whats wrong? Please help
Jenkins 2.107.3
thanks 
Mark

**Comment by jeremylong** [comment]
Sorry for the very delayed reply.  First - please try the 5.0.0 release of the ODC Jenkins plugin: https://wiki.jenkins.io/display/JENKINS/OWASP+Dependency-Check+Plugin

If you still see this error - my best guess is that it is coming from the RetireJS Analyzer.  This analyzer retrieves a file from github and then uses the contained regular expressions to identify JavaScript files.  Try disabling the RetireJS analyzer.  If that solves the problem we'll need to track down exactly what regex is causing the issue.

**Comment by jeremylong** [comment]
See #1969 for a solution.  I am going to close this issue and track the issue though #1969.
