### ISSUE TITLE
Empty Maven report due to sql exception

### ISSUE THREAD

**Issue by javabeanz** [dependency-check/DependencyCheck#170]
When I run the Maven plugin according to example 1 (http://jeremylong.github.io/DependencyCheck/dependency-check-maven/usage.html) then it fails with the following error :8ball: 

<log>
<record>
  <date>2014-11-21T11:36:45</date>
  <millis>1416566205212</millis>
  <sequence>1</sequence>
  <logger>org.owasp.dependencycheck.data.nvdcve.CveDB</logger>
  <level>SEVERE</level>
  <class>org.owasp.dependencycheck.data.nvdcve.CveDB</class>
  <method>getProperties</method>
  <thread>1</thread>
  <message>An unexpected SQL Exception occurred; please see the verbose log for more details.</message>
</record>
</log>

The report shows all dependencies with 0 vulnerabilities.

Maven home: D:\dev\m2\core\apache-maven-3.1.1
Java version: 1.7.0_15, vendor: Oracle Corporation
Java home: D:\jdk1.7.0_15\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"

**Comment by jeremylong** [comment]
Can you re-run the scan adding the logFile configuration and post the log file here?

``` xml
<plugin>
  <groupId>org.owasp</groupId>
  <artifactId>dependency-check-maven</artifactId>
  <version>1.2.6</version>
  <configuration>
    <logFile>${project.build.directory}/dc.log</logFile>
  </configuration>
  <executions>
    <execution>
      <goals>
        <goal>check</goal>
      </goals>
    </execution>
  </executions>
</plugin>
```

**Comment by jeremylong** [comment]
One more question, does the directory '.m2\repository\org\owasp\dependency-check-data' exist and are their files in it?

--Jeremy

**Comment by javabeanz** [comment]
I've added the logfile configuration, but no log file is written. Yes, the maven repo has the maven plugin in it, I've tried several versions now.

**Comment by jeremylong** [comment]
The '.m2\repository\org\owasp\dependency-check-data' directory is not the plugin for the maven plugin, rather it is a directory created by the plugin. I was wondering if files existed in that directory (and if the directory was writable). Try deleting the '.m2\repository\org\owasp\dependency-check-data' directory and re-running.

**Comment by javabeanz** [comment]
no, this folder does not exist. There is an .m2 folder, but not that tree beneath it.

**Comment by jeremylong** [comment]
Interesting...  where is the actual dependency-check-maven-1.2.6.jar located?

**Comment by javabeanz** [comment]
D:\dev\m2\repo\org\owasp\dependency-check-maven\1.2.6\dependency-check-maven-1.2.6

**Comment by jeremylong** [comment]
Are there any files in:

D:\dev\m2\repo\org\owasp\dependency-check-data

Or does that directory not exist?  If for some reason that directory does not exist, you likely will need to configure a 'dataDirectory'. This should be a path to a directory with read/write permissions.

**Comment by jeremylong** [comment]
Any update on this? Were you able to get dependency-check working? If so, I would like to know what solved your problem so I can put this into a FAQ. If not, please let me know the about my previous comment/question.

Best Regards,

Jeremy

**Comment by javabeanz** [comment]
No, it's not yet working, same problem as before. In reply to your previous question : 
That folder D:\dev\m2\repo\org\owasp\dependency-check-data has two files : cve.2.9.h2 and cve.2.9.trace

**Comment by jeremylong** [comment]
Okay, I've got two things to try. First, delete the two files : cve.2.9.h2 and cve.2.9.trace. Then re-run the build. I've seen, in earlier versions, if people had an issue with the download of the NVD data it would cause problems similar to what you are seeing and deleting the files solves the problem. If that fails, I will be publishing an updated version of dependency-check within the next day or two. One of the issues is that logging in dependency-check-maven is broken - so a verbose error log cannot be created.

**Comment by javabeanz** [comment]
removing the directory holding those 2 files did it. Now I have a dependency report with some content, thanks for your help.
