### ISSUE TITLE
improvement: make use of @Nullable and @Nonnull

### ISSUE THREAD

**Issue by SingingBush** [dependency-check/DependencyCheck#1703]
_javax.annotation_ is already available in the project but being used much. Using both `javax.annotation.Nonnull` and `javax.annotation.Nullable` would be helpful.

It's especially handy when your code is being called from Kotlin as the language will force the user to make a safe call with `?.`

**Comment by kwin** [comment]
Please don't use those annotations. For a reasoning look at https://blog.codefx.org/java/jsr-305-java-9/. Other null annotations are  better suited (e.g. Eclipse or IntelliJ ones).

**Comment by SingingBush** [comment]
ah cool, I was originally going to use the Jetbrains ones, went with javax.annotation because it was already in pom
