### ISSUE TITLE
Dependency Check CLI Returning Zero Results

### ISSUE THREAD

**Issue by fergalcoll** [dependency-check/DependencyCheck#1709]
Hi,

I'm running dependency check CLI against WebGoat but its not returning any results? 

See log output below

Gist Link https://gist.github.com/theHackPot/e9f8735769f93b7580eab2b19d47800a

**Comment by stevespringett** [comment]
Isn't WebGoat 8 a Maven project? The CLI doesn't understand Maven. Try using the Dependency-Check Maven plugin instead.

**Comment by fergalcoll** [comment]
That is correct, my bad - thanks
