### ISSUE TITLE
Dependencies Scanned: 0 (0 unique)

### ISSUE THREAD

**Issue by githubhs17** [dependency-check/DependencyCheck#1710]
What does "0 dependencies scanned" mean ? There are about 1300 directories and 20000 files in the scan space.

Scan Information (show all):

    dependency-check version: 4.0.2
    Report Generated On: Jan 28, 2019 at 17:18:05 +00:00
    Dependencies Scanned: 0 (0 unique)
    Vulnerable Dependencies: 0
    Vulnerabilities Found: 0
    Vulnerabilities Suppressed: 0
    ...

**Comment by jeremylong** [comment]
It means that zero dependencies were scanned and analyzed. There is likely an error in how you are running dependency-check. When specifying the scan path the tool uses ant style paths. So if you are trying to scan a nested directory tree use `-s /path/to/repo/**`

**Comment by githubhs17** [comment]
@jeremylong Thanks.
We are using docker, so we use:

`    --scan /src/** \` instead of  `    --scan /src/ \` as in the description

?

**Comment by githubhs17** [comment]
Hi @jeremylong , I tried with **
The result is the same: zero dependencies.

Without ** I have:
--scan /home/jenkins-master/workspace/content-picker-ui_master
=> zero dependencies

With ** I have:
--scan
/home/jenkins-master/workspace/content-picker-ui_master/app
/home/jenkins-master/workspace/content-picker-ui_master/bower_components
/home/jenkins-master/workspace/content-picker-ui_master/bower.json
/home/jenkins-master/workspace/content-picker-ui_master/cert.pem
/home/jenkins-master/workspace/content-picker-ui_master/commit
/home/jenkins-master/workspace/content-picker-ui_master/content_picker_design.pdf
/home/jenkins-master/workspace/content-picker-ui_master/coverage
/home/jenkins-master/workspace/content-picker-ui_master/dist
/home/jenkins-master/workspace/content-picker-ui_master/dist_uncompressed
/home/jenkins-master/workspace/content-picker-ui_master/Jenkinsfile
/home/jenkins-master/workspace/content-picker-ui_master/karma.avt.conf.js
/home/jenkins-master/workspace/content-picker-ui_master/karma.conf.js
/home/jenkins-master/workspace/content-picker-ui_master/key.pem
/home/jenkins-master/workspace/content-picker-ui_master/locales
/home/jenkins-master/workspace/content-picker-ui_master/marathon.json
/home/jenkins-master/workspace/content-picker-ui_master/mock
/home/jenkins-master/workspace/content-picker-ui_master/node_modules
/home/jenkins-master/workspace/content-picker-ui_master/npm-debug.log
/home/jenkins-master/workspace/content-picker-ui_master/npm_publish.sh
/home/jenkins-master/workspace/content-picker-ui_master/package.json
/home/jenkins-master/workspace/content-picker-ui_master/protractor.config.js
/home/jenkins-master/workspace/content-picker-ui_master/PULL_REQUEST_TEMPLATE.md
/home/jenkins-master/workspace/content-picker-ui_master/README.md
/home/jenkins-master/workspace/content-picker-ui_master/service.properties
/home/jenkins-master/workspace/content-picker-ui_master/sonar-project.properties
/home/jenkins-master/workspace/content-picker-ui_master/test
/home/jenkins-master/workspace/content-picker-ui_master/testApp.js
/home/jenkins-master/workspace/content-picker-ui_master/tools
/home/jenkins-master/workspace/content-picker-ui_master/webpack.dev.config.js
/home/jenkins-master/workspace/content-picker-ui_master/webpack.prod.config.js
/home/jenkins-master/workspace/content-picker-ui_master/webpack.prod.uncompressed.config.js
/home/jenkins-master/workspace/content-picker-ui_master/webpack.review.config.js
/home/jenkins-master/workspace/content-picker-ui_master/webpack.test.config.js
=> zero dependencies

Is there a description about dependencies. How does it work ? Is there an example, what it's looking for?

**Comment by jeremylong** [comment]
For node projects - ODC is pretty much just a wrapper around `npm audit`.  Which version of ODC are you using?

**Comment by githubhs17** [comment]
We are using always the latest docker image.
actual -> dependency-check version: 4.0.2

**Comment by jeremylong** [comment]
Sorry for the huge delay on getting back to this question. Have you upgrade to 5.2.2? Are you still having this issue?

One of the other things to try is quoting the path:

>--scan "/home/jenkins-master/workspace/content-picker-ui_master"

Also, 5.2.2 uses the package-lock.json.  We have improvements in place that will be in the next release for node.js projects.
