### ISSUE TITLE
False positive on library affinity-3.1.1.jar - reported as cpe:/a:thread_project:thread:3.1.1

### ISSUE THREAD

**Issue by dldnhf** [dependency-check/DependencyCheck#1718]
False positive on library affinity-3.1.1.jar - reported as `cpe:/a:thread_project:thread:3.1.1`

```xml
<dependency>
   <groupId>net.openhft</groupId>
   <artifactId>affinity</artifactId>
   <version>3.1.1</version>
</dependency>
```

I'm wondering how ODC comes up with this CPE, as I don't find any evidence for vendor "thread_project" or product "thread" in the evicence list (except for the fact that "thread" is part of some product evidence, like the description "Java Thread Affinity library" in the pom.) I'd appreciate any insight into this to better understand how ODC works.

Thanks a lot!

**Comment by aikebah** [comment]
ODC has a Lucene index of all CPEs of the NIST NVD that is consulted for all the found product- and vendor evidences. The result(s) that Lucene returns are validated to ensure that they 'sufficiently' match a dependency (all words of the Lucene result are contained in at least one of the corresponding evidence values). Some stop-words are ignored in this evaluation, such as project.

So yes, the 'Thread' part in the pom name is in the end what triggers this false (LOW confidence) association with the CPE of   `thread_project:thread`.

See also its implementation at
https://github.com/jeremylong/DependencyCheck/blob/main/core/src/main/java/org/owasp/dependencycheck/dependency/naming/CpeIdentifier.java
