### ISSUE TITLE
scanSet of subproject not processed by Gradle plugin dependencyCheckAggregate

### ISSUE THREAD

**Issue by VerachtertAaron** [dependency-check/DependencyCheck#1724]
The logfile of ```dependencyCheckAggregate``` on the root project + a minimal setup in the build.gradle file of the root project and subproject can be found [here](https://gist.github.com/VerachtertAaron/c53c622f32fdf46e889d9902cb6210f1)

I have a project that contains subprojects. The root project has no dependencies of its own, the subprojects have both gradle dependencies from mavencentral and local jar-dependencies. I specified the folder containing the jar-dependencies using the ```scanset``` tag in ```dependencyCheck```.

When I run ```dependencyCheckAnalyze``` on the subproject, I get a report that contains the scanned jar-dependencies. The same is true when I run ```dependencyCheckAggregate``` on the subproject. I did notice that this last task also scans the dependencies of the other subprojects, which I find strange but doesn't really impede me.

However, when I run ```dependencyCheckAggregate``` on the root project, the jar-dependencies are not included in the report. They are included if I include the ```scanset``` tag in the build.gradle file of the root project.

**Comment by jeremylong** [comment]
Your minimal setup is missing the settings.gradle:

settings.gradle
```groovy
rootProject.name = 'aggregate-test'
include 'child'
```

Also, the root project failed to include the plugin:

build.groovy
```groovy
plugins {
  id "org.owasp.dependencycheck" version "4.0.2"
}

allprojects {
    repositories {
        mavenLocal()
        mavenCentral()
    }
    apply plugin: 'java'
    apply plugin: 'org.owasp.dependencycheck'
}
```

Lastly, the child gradle.build you provided did not actually define any dependencies? So I added log4j:

child/build.gradle
```groovy
dependencies {
    implementation group: 'log4j', name: 'log4j', version: '1.2.17'
}
```

Given the above setup when I run `gradle dependencyCheckAggregate` I get a report that includes log4j.
