### ISSUE TITLE
[5.0.0-M1] No documents found Exception if previous h2 database exists in data directory

### ISSUE THREAD

**Issue by albuch** [dependency-check/DependencyCheck#1732]
When a `dc.h2.db` file exists in the data directory after upgrading to 5.0.0-M1 every check fails with an Exception.

```
[error] Failed creating report: One or more exceptions occurred during analysis:
[error] 	No documents exist
org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during analysis:
	No documents exist
	at org.owasp.dependencycheck.Engine.throwFatalExceptionCollection(Engine.java:1102)
	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:647)
```
The NVD update process writes everything in the old `dc.h2.db` but the analyzeDependencies seems to check somewhere else.

After deleting `dc.h2.db` further checks are working and a `dc.mv.db` file is created.

Expected bahaviour: Either delete old database files when running 5.0.0 the first time or add instructions in the Release Notes.

Note: I've had this issue with the SBT plugin where we use the default data directory from dependency-check-core default settings. I haven't tested with the Maven plugin yet, but I guess the issue holds true as well if a user has set a customized data directory setting in the plugin configuration.

**Comment by jeremylong** [comment]
The two databases *should* be able to co-exist side by side.  I'll have to do some more testing on this.

**Comment by jeremylong** [comment]
The base file name has been renamed from "dc" to "odc" in the connection string. This resolves the issue of having the a database with MV_STORE=false in the same directory as the new database that does uses the MV_STORE=true (i.e. the default).
