### ISSUE TITLE
False positive (Swagger1st)

### ISSUE THREAD

**Issue by oporkka** [dependency-check/DependencyCheck#1738]
There's a false positive for [Swagger1st](https://mvnrepository.com/artifact/org.zalando/swagger1st/0.25.0) JAR library. It is reported as cpe:/a:st_project:st:1.2.1::~~~node.js~~

```xml
<dependency>
    <groupId>org.zalando</groupId>
    <artifactId>swagger1st</artifactId>
    <version>0.25.0</version>
</dependency>
```

**Comment by jeremylong** [comment]
Resolved in the 6.x releases.
