### ISSUE TITLE
owasp maven plugin 5.0.0-M1 writes almost 1GB to disk during a repeated check

### ISSUE THREAD

**Issue by jjYBdx4IL** [dependency-check/DependencyCheck#1741]
iostat shows me that for some maven projects the owasp plugin writes almost 1 GB of data to disk, even on a repeated run where there are no database updates, maintenance etc.

Is that as intended? Doesn't that make the plugin unnecessarily slow?

**Comment by albuch** [comment]
I can confirm the database size from my tests as well.

**Comment by jjYBdx4IL** [comment]
Maybe the plugin should remember already analyzed (extracted) dependencies and cache the results while remembering the settings used for the analysis if that has any effect. That could speed up stuff enormously.

**Comment by jeremylong** [comment]
The database does grow during execution - but code has been added to reduce the file size after the update has completed.

**Comment by jjYBdx4IL** [comment]
I think the I/O comes from the ArchiveAnalyzer.

**Comment by jeremylong** [comment]
yes, the ArchiveAnalyzer can cause a lot of disk operations. However, it has nothing to do with the 1GB data file. That is purely the H2 database.
