### ISSUE TITLE
5.0.0-M1 NVD cpe2.3 Lookup error

### ISSUE THREAD

**Issue by RasmusOlesen** [dependency-check/DependencyCheck#1744]
The following cpe returns cves, during the NvdCveAnalyzer phase (NvdCveAnalyzer:64)
cpe:2.3:a:eclipse:jetty:9.2.24:*:*:*:*:*:*:* (or cpe:/a:eclipse:jetty:9.2.24 in version 4)

But
cpe:2.3:a:eclipse:jetty:9.2.24:20180105:*:*:*:*:*:*
doesn't return any cves.

I don't know if this is an issue with the NVD database or the CPEAnalyzer.
But the update field seems to mess up the search/lookup.

I have replicated the same behavior on
https://nvd.nist.gov/products/cpe/search/results?keyword=cpe%3a2.3%3aa%3aeclipse%3ajetty%3a9.2.24%3a20180105%3a*%3a*%3a*%3a*%3a*%3a*&status=FINAL,DEPRECATED&orderBy=CPEURI&namingFormat=2.3

**Comment by jeremylong** [comment]
Fixed in the 6.x releases.
