### ISSUE TITLE
Could not get unknown property 'cveUrlModified'

### ISSUE THREAD

**Issue by edimusrex** [dependency-check/DependencyCheck#1745]
When running the dependency check version v5.0.0-M1 I get the following error

> Execution failed for task ':dependencyCheckAnalyze'.
> Could not get unknown property 'cveUrlModified' for object of type org.owasp.dependencycheck.gradle.extension.CveExtension.

Reverting this back to v4.0.2 works as expected

**Comment by dejan2609** [comment]
Same here (gradle version used: **5.2.1**).

**Comment by dejan2609** [comment]
Update: adding default cve parameters versions explicitly and executing **./gradlew clean --info** produces same error (during configuration phase project fails on evaluation).
Environment: Gradle: 5.2.1 / org.owasp.dependencycheck 5.0.0-M1
```
dependencyCheck {
    cve {
        cveUrlBase='https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-%d.json.gz'
        cveUrlModified='https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-modified.json.gz'
    }
}
```
https://jeremylong.github.io/DependencyCheck/dependency-check-gradle/configuration.html

Interestingly, different project (Maven 3.6.0 / owasp maven plugin 5.0.0-M1) works fine (I will try to create skeleton projects for both of these use cases).

**Comment by jeremylong** [comment]
There is an issue with this that will be resolved fully in M2.  The correct parameter setting would be:

```
dependencyCheck {
    cve {
        urlBase='https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-%d.json.gz'
        urlModified='https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-modified.json.gz'
    }
}
```

**Comment by edimusrex** [comment]
Changing my dependency block to the above suggested unfortunately does not solve my issue,  Here is my dependency block

    dependencyCheck{
         cve {
            urlBase = 'https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-%d.json.gz'
            urlModified = 'https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-modified.json.gz'
        }
        outputDirectory = "${projectDir}/reports"
        suppressionFile = "${projectDir}/gradle/owasp_config/suppress.xml"
        analyzers {
            assemblyEnabled = false
            retirejs { 
                filterNonVulnerable = true
            }
        }
    }

I should add that I am using Gradle 5.1.1

**Comment by dejan2609** [comment]
Thanx @jeremylong, I will wait for M2 and report back here.

**Comment by dejan2609** [comment]
Update: **dependencyCheckAnalyze** works as expected with **5.0.0-M2** and Gradle versions 5.2.1 / 5.3-rc-3 (both with or without `dependencyCheck.cve` block mentioned above).
