### ISSUE TITLE
Use the internal CVE url for jenkins plugin

### ISSUE THREAD

**Issue by llsJllsJ** [dependency-check/DependencyCheck#1748]
I would like to use the internal CVE url for jenkins plugin. 
Are there any options to parse CVE url base on below document?
https://jeremylong.github.io/DependencyCheck/data/mirrornvd.html

**Comment by stevespringett** [comment]
Yes, please see the Jenkins Global Configuration and setup the NVD mirroring there. Refer to the help icon for each field if you run into questions.

**Comment by llsJllsJ** [comment]
Thanks
