### ISSUE TITLE
Option to produce multiple formats

### ISSUE THREAD

**Issue by wkoot** [dependency-check/DependencyCheck#1750]
It would be nice to have `--format` take a comma-separated list of output format to write.
I currently use both xml and html output for the [Dependency-Check Sonar plugin](https://github.com/stevespringett/dependency-check-sonar-plugin#plugin-configuration) (and don't need `ALL`):
```
dependency-check --format XML --out reports/dependency-check.xml
dependency-check --format HTML --out reports/dependency-check.html
```

**Comment by wkoot** [comment]
It would be nice to be able to generate multiple at once, while retaining the option to specify output filename(prefix). I'm not sure if it is desirable to separate that request to another issue, though

**Comment by jeremylong** [comment]
While not coded yet, the 5.x branch will allow the format to be specified multiple times.
