### ISSUE TITLE
Report generation failing with xml parser exception

### ISSUE THREAD

**Issue by pmehtaupgrade** [dependency-check/DependencyCheck#1753]
Getting following error when dependency check is trying to generate report at the end of the analysis:

Parsing of file /home/admin/workspace/XXXl/target/dependency-check-report.xml failed due to an exception: org.xml.sax.SAXParseException; lineNumber: 22; columnNumber: 1389; Element type "software" must be followed by either attribute specifications, ">" or "/>". at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source) at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source) at org.apache.commons.digester.Digester.parse(Digester.java:1916) at org.jenkinsci.plugins.DependencyCheck.parser.ReportParser.parse(ReportParser.java:126) at hudson.plugins.analysis.core.AbstractAnnotationParser.parse(AbstractAnnotationParser.java:54) at hudson.plugins.analysis.core.FilesParser.parseFile(FilesParser.java:323) at hudson.plugins.analysis.core.FilesParser.parseFiles(FilesParser.java:281) at hudson.plugins.analysis.core.FilesParser.parserCollectionOfFiles(FilesParser.java:232) at hudson.plugins.analysis.core.FilesParser.invoke(FilesParser.java:203) at hudson.plugins.analysis.core.FilesParser.invoke(FilesParser.java:31) at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3082) at hudson.remoting.UserRequest.perform(UserRequest.java:212) at hudson.remoting.UserRequest.perform(UserRequest.java:54) at hudson.remoting.Request$2.run(Request.java:369) at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)

This has started happening very recently. Could you please check and let us know if we would need to apply any fix on our side or do we need to wait for new version of dependency-check.

**Comment by pmehtaupgrade** [comment]
@jeremylong could you please confirm if a fix for this is expected to come out soon? Thanks in advance for looking into this.

**Comment by jeremylong** [comment]
What version of dependency-check are you using? I'm assuming you are using the Jenkins plugin...  An initial guess would be that you are using 5.0.0-M1 via Maven or gradle. Then trying to import the XML into using the Jenkins plugin - which won't work.  There is no plans for a milestone release of the Jenkins plugin.

Regardless - that is all speculation. We would need more information to be able to help.

**Comment by pmehtaupgrade** [comment]
Thanks Jermey.

I have checked and yes as you guessed, we are using
dependency-check-maven:5.0.0-M1.
Given there is no new release planned, what are our options, should
downgrade to earlier version going to solve the report generation issues?

-----------
Thanks,
Prakash Mehta

**Comment by cmuchinsky** [comment]
Hit the same issue, any chance the XML format for 5.x could be backwards compatible with 4.x so folks could benefit from the improvements in 5.x in their Jenkins pipelines now? Otherwise as Prakash mentioned, I suspect the only option is to downgrade.

**Comment by cmuchinsky** [comment]
Is this perhaps related to #1779?

**Comment by cmuchinsky** [comment]
For anybody who is interested, I confirmed that the fix associated with #1779 does indeed fix compatibility with the current Jenkins plugin.

**Comment by jeremylong** [comment]
Closing this issue because the issue was due to incompatible versions of ODC and the ODC jenkins plugin.
