### ISSUE TITLE
Question: How to verbose log of dependency-check plugin

### ISSUE THREAD

**Issue by llsJllsJ** [dependency-check/DependencyCheck#1754]
How to verbose log of dependency-check plugin in jenkins? 
My NVD update was failed all the time so it would be better if we can read verbose log to investigate the issue.

**Comment by stevespringett** [comment]
Refer to the Jenkins docs. There a Jenkins logger (in the UI) that you need to specify "org.owasp" and debug

**Comment by llsJllsJ** [comment]
Thanks
