### ISSUE TITLE
owasp maven plugin 5.0.0-M1 ignores outputDirectory option

### ISSUE THREAD

**Issue by PBarri** [dependency-check/DependencyCheck#1756]
After upgrading to the latest version of the maven plugin, the `outputDirectory ` option is being ignored.

The plugin configuration I used can be found at https://gist.github.com/PBarri/c9d63b21ce8293f0edcab6d2e81dc4c6 

The reports are being shown at the default project build directory, instead of the configured directory.

**Comment by PBarri** [comment]
After digging out in the code, the problem might be at the function defined in https://github.com/jeremylong/DependencyCheck/blob/v5.0.0-M1/maven/src/main/java/org/owasp/dependencycheck/maven/BaseDependencyCheckMojo.java#L786 , which seems to ignore the setting defined in the outputDirectory parameter

**Comment by jeremylong** [comment]
I don't know what I was thinking when I removed that code - sorry.  This will be fixed in the next release.
