### ISSUE TITLE
CVSS issues set all to 0.0 

### ISSUE THREAD

**Issue by cristiano-corrado** [dependency-check/DependencyCheck#1757]
The owas dependency-check-cli is used in jenkins freestyle pipeline to scan projects from shell command then the freestyle dsl publishHTML is used. in the report all cvss score are set to 0.0 

<img width="1521" alt="screenshot 2019-02-21 at 13 03 41" src="https://user-images.githubusercontent.com/3243602/53171047-8eb65480-35d9-11e9-9873-d15c3be5059a.png">

**Comment by jeremylong** [comment]
This should be resolved with the 5.0.0 release. Please upgrade to the latest version of ODC.
