### ISSUE TITLE
how we can generate XML format report without defining Plugin in pom.xml 

### ISSUE THREAD

**Issue by awsdora** [dependency-check/DependencyCheck#1761]
i am able to generate all formats using plugin defined in POM , can you  please let me know how  can  we genrate XML report , by mentioning only in Jenkins pipeline script not in Pom

**Comment by stevespringett** [comment]
Jenkins has a built-in "pipeline syntax" option that will generate pipeline snippets for every pipeline-compatible plugin, including Dependency-Check. You simply provide the configuration options you want and it will generate it for you.

https://jenkins.io/blog/2016/05/31/pipeline-snippetizer/
https://go.cloudbees.com/docs/cloudbees-documentation/use/automating-projects/

**Comment by jeremylong** [comment]
You can supply parameters to maven plugins via the command line:
```
mvn org.owasp:dependency-check-maven:5.0.0-M1:check -Dformat=ALL
```
