### ISSUE TITLE
Suppressing an entire folder

### ISSUE THREAD

**Issue by edimusrex** [dependency-check/DependencyCheck#1762]
I am trying to exclude an entire folder without having to pass the --exclude on the command line.  Right now my dependency block looks as so

    dependencyCheck{
        outputDirectory = "${projectDir}/reports"
        suppressionFile = "${projectDir}/gradle/owasp_config/suppress.xml"
        analyzers {
            experimentalEnabled = true
            assemblyEnabled = false
            retirejs { 
                filterNonVulnerable = true
            }
        }
        scanSet = ['build/deploy/scripts']
    }

There is a folder within my scripts folder that I need to ignore, I could suppress the individual cve's but there are over 300.

**Comment by jeremylong** [comment]
Sorry for the delayed response - why would you suppress at the CVE level. It is generally much better to create suppressions at the CPE level. Some of these, depending on the situation, can be a fairly wide spanning suppression rule.  You could create a suppression rule that would just suppress everything in a specific folder by using a regex on the filepath: https://jeremylong.github.io/DependencyCheck/general/suppression.html

Currently the scanSet does not include any exclude functionality.
