### ISSUE TITLE
Minor: Git conflict comment made it into a commit

### ISSUE THREAD

**Issue by srdo** [dependency-check/DependencyCheck#1763]
@jeremylong I think a conflict resolution left some annotations behind. I'd fix it, but you probably have a better idea whether the conflict was resolved correctly.

https://github.com/jeremylong/DependencyCheck/blob/master/maven/src/main/java/org/owasp/dependencycheck/maven/BaseDependencyCheckMojo.java#L635

**Comment by jeremylong** [comment]
Thank you for noticing that.  I'll remove the deprecated parameters (again).
