### ISSUE TITLE
dtrack ui not show xml results - version 3.5.0 

### ISSUE THREAD

**Issue by degilq** [dependency-check/DependencyCheck#1769]
Please delete any un-needed section from the following issue template:

### Reporting Bugs/Errors
When reporting errors, 99% of the time log file output is required. Please post the log file as a [gist](https://gist.github.com/) and provide a link in the new issue.

### Reporting False Positives
When reporting a false positive please include:
- The location of the dependency (Maven GAV, URL to download the dependency, etc.)
- The CPE that is believed to be false positive
  - Please report the CPE not the CVE

#### Example
False positive on library foo.jar - reported as cpe:/a:apache:tomcat:7.0
```xml
<dependency>
   <groupId>org.sample</groupId>
   <artifactId>foo</artifactId>
   <version>1.0</version>
</dependency>
```

**Comment by degilq** [comment]
with version 3.5.0 not can see the xml reports, always is in blank


![image](https://user-images.githubusercontent.com/23441434/53365880-10331d00-3921-11e9-839c-2a350a270556.png)

**Comment by stevespringett** [comment]
Dependency-Track will never show XML reports - in fact, it doesn't have reports. I'm not understanding how a false positive in Dependency-Check has any relation to the UI in Dependency-Track. Two completely different projects.

Are you reporting a false positive in Dependency-Check or a UI issue in Dependency-Track? If UI issue, this is the wrong place to report. If you're reporting a false positive, you haven't provided enough information to determine how it originated.

Can you elaborate please.

**Comment by degilq** [comment]
the problem is the upload report from jenkins or other ci, im using this
scripts for upload dcheck reports

#!/bin/bash

CI_PROJECT_DIR="$1"

CI_PROJECT_NAME="$2"

CI_JOB_ID="$3"

cat > $CI_PROJECT_DIR/payload.json <<HERE

{

"autoCreate": "true",

"projectName": "${CI_PROJECT_NAME}",

"projectVersion": "${CI_JOB_ID}",

"scan": "$(cat $CI_PROJECT_DIR/dependency-check/dependency-check-report.xml
|base64 -)"

}

HERE

curl -X "PUT" "http://xxxxxxxxx:8080/api/v1/scan" -k -H 'Content-Type:
application/json' -H 'X-API-Key: xxxxxxxxxx' -d @payload.json




some time the results over dtrack ui is in blank, how we can debugging the
*dependency-track-embedded.war* applications for take more results?



[image: image.png]

**Comment by stevespringett** [comment]
Please refer to https://docs.dependencytrack.org/usage/cicd/. There's also a good conversation on this topic here: https://github.com/DependencyTrack/dependency-track/issues/160

If you continue to experience issues with uploading, please open an issue for the Dependency-Track project. This ticket was created for Dependency-Check which is not the correct project. https://github.com/DependencyTrack/dependency-track
