### ISSUE TITLE
No proxy not working when it has multiple line with jenkins plugin

### ISSUE THREAD

**Issue by llsJllsJ** [dependency-check/DependencyCheck#1772]
### Reporting Bugs/Errors
OWASP Dependency-Check Plugin version = 4.0.2
Jenkins version =  2.150.2

When trigger job to update NVD Data with mulple noproxy line it fails. It look like it ignore noproxy setting. 
Our proxy has policy to denied all internal url which give us error 403.
We have mirror nist data to our webserver which access by using internal url
fail log
https://gist.github.com/llsJllsJ/cdeb1cbae2d2c96ff15d10df5b5e0805
debug log
https://gist.github.com/llsJllsJ/3223867327441282126c9a1ce56ed9a6

But if it has one line of no proxy, it works fine
success log
https://gist.github.com/llsJllsJ/7e19ec1c9c8a32be2c1fbd347fe13f0a

**Comment by stevespringett** [comment]
Dependency-Check expects proxy hosts to be delimited with either:   , ; |

Jenkins delimits with a newline. So I added a workaround to the Jenkins plugin that replaces all newlines with a comma. This should resolve the issue. I do not have the ability to test any proxy server configuration. Please compile from sources to test and let me know if that resolves the issue or not. If so, I'll release - which will be the last of the 4.x releases.

**Comment by llsJllsJ** [comment]
Hi 

Thanks for workaround
it works fine now
https://gist.github.com/llsJllsJ/fecca8e1645d07e768568ae263961bd1

**Comment by chiemeleakoma** [comment]
Hi, i was wondering if and when will the plugin be rebuilt using the latest version of the cli tool as the current version, 4.0.2 is failing in linux distros regarding GrokAssembly and mono needs to be installed (although it is already installed). This issue has been fixed in the latest build in the cli, version 5.0.0.
Thanks

**Comment by stevespringett** [comment]
@chiemeleakoma The Jenkins plugin isn't built with the CLI and has no relation to it. The Jenkins plugin is it's own implementation, but it is similar to the CLI. 5.0 is not released yet. The Jenkins plugin will not have any 5.0 milestone releases. 

Refer to https://groups.google.com/d/msg/dependency-check/2yMe6-Tg8tU/53SCfThcBQAJ for information on Jenkins plugin 5.0.0 development and voice your opinion to help guide future direction.
