### ISSUE TITLE
How to customize cpe url in jenkins plugin

### ISSUE THREAD

**Issue by llsJllsJ** [dependency-check/DependencyCheck#1782]
Hi,

We are encounter an issue that dependency plugin stuck in 'Initializing CPE Analyzer' step
We believe the issue came from our proxy denied access to below url.
`cpe.url='https://static.nvd.nist.gov/feeds/xml/cpe/dictionary/official-cpe-dictionary_v2.3.xml.gz'`

So it it possible to set a mirror cpe url? like Retire.js Repo because I didn't find in configure page of jenkins

Thanks

**Comment by stevespringett** [comment]
It’s in the global configuration
