### ISSUE TITLE
User properties for Maven plugin?

### ISSUE THREAD

**Issue by OrangeDog** [dependency-check/DependencyCheck#1787]
Can any of the configuration be set via user properties, e.g. from the command line with `-D`?
If so, please document what they are.

**Comment by mprins** [comment]
RTFM https://jeremylong.github.io/DependencyCheck/dependency-check-maven/plugin-info.html

**Comment by OrangeDog** [comment]
Aha. I was using this page https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html

Being used to the layout at http://maven.apache.org/plugins/index.html, I though that was the only Goals documentation you had.
