### ISSUE TITLE
Dependency Check 5.0.0-M1 - Autoupdate is disabled and the database does not exist

### ISSUE THREAD

**Issue by BruGit** [dependency-check/DependencyCheck#1789]
**Describe the bug**
In the shell of a Jenkins job, using dependency-check:check, the build fail for DB not present.
Using that command, it searches for the Dependency Check 5.0.0-M1.

Always in the shell, specifying the version, works with: org.owasp:dependency-check-maven:4.0.2:check

**Log file**
See the attachment please.

**To Reproduce**
I've launched the job from Jenkins with dependency-check:check.
Autoupdate is false and we have a local DB of the last NVID.
Trying with the older version makes the build have success.

**Expected behavior**
It should works like the v4.0.2 without given the error "database does not exist".
[Log.txt](https://github.com/jeremylong/DependencyCheck/files/2946016/Log.txt)

**Comment by jeremylong** [comment]
I believe this has been fixed in 5.0.0-M2. Please retest this with 5.0.0-M2.

**Comment by BruGit** [comment]
Hi Jeremy,
now, using 5.0.0-M2, I've this issue:

 Error resolving version for plugin 'dependency-check-maven:5.0.0-M2' from the repositories [local (/data/jenkins/.m2/repository), Edenred.it-mirror (xxxxxxxx)]: Plugin not found in any plugin repository -> [Help 1]

Is a normal behavior because we don't have in local this plugin?

**Comment by jeremylong** [comment]
If you are using the gradle plugin - 5.0.0-M2 has not been publshed yet.  We had a few additional updates.  It should be released in the next day or two.

**Comment by BruGit** [comment]
Thanks Jeremy, I'll check with the next release.
I confirm again after have tested that works with Issue with org.owasp:dependency-check-maven:4.0.2.

I've updated the Description for make more clear where the command is inserted.

**Comment by helospark** [comment]
Issue is not resolved with 5.0.0-M2
```
[ERROR] Failed to execute goal org.owasp:dependency-check-maven:5.0.0-M2:check (default-cli) on project xxx-service: Fatal exception(s) analyzing xxx-service: One or more exceptions occurred during analysis:
[ERROR] Autoupdate is disabled and the database does not exist
```

Using 4.0.2 version with same configuration and setup works.

**Comment by jeremylong** [comment]
The database schema (and event the file name changed).  I'm assuming you had created the database while connected to the Internet and then used the cached version for future scanning.  This works as long as you are doing something to keep the locally cached database updated.

Most organizations mirror the NVD in their private network; see: https://github.com/stevespringett/nist-data-mirror

**Comment by helospark** [comment]
Thanks for getting back to me Jeremy,
We used the DependencyChecker Jenkins Plugin's "Invoke depenency checker update only" to update the database daily and run mvn dependency-check-maven:check using that database for our builds.

The problem appears to be that the Jenkins plugin's latest version is only 4.0.2, but the Maven plugin is 5.0.0-M2 however as you stated the database schema has changed which caused our issue.
Sorry for the confusion.

**Comment by jeremylong** [comment]
Note that 5.0.0-M2 is a milestone release - not a final release.  We are working to finalize the 5.0.0 release over the next few weeks.
