### ISSUE TITLE
When do you think to deliver next release version?

### ISSUE THREAD

**Issue by elballa** [dependency-check/DependencyCheck#1790]

**Comment by jeremylong** [comment]
5.0.0-M2 (i.e. milestone 2 will be released within the next day or two).

**Comment by elballa** [comment]
Thanks

**Comment by elballa** [comment]
Why is it not yet in the central maven repository?

**Comment by mprins** [comment]
see https://github.com/jeremylong/DependencyCheck/issues/1796#issuecomment-471952481
