### ISSUE TITLE
Central analyzer stuck on unknown dependency (o.o.d.u.Downloader)

### ISSUE THREAD

**Issue by malejpavouk** [dependency-check/DependencyCheck#1793]
**Describe the bug**
Central analyzer gets stuck, when the dependency is not available in central, but available in company repository (in this case artifactory)

** Version of dependency-check used **
The problem occurs using version 4.0.2 of the the Gradle plugin

** Log file **
https://gist.github.com/malejpavouk/d47542e456e59c486bd2e21418df13a8
^^ Partial debug log with the cycling

How it ends up after few minutes:
```
18:16:42.907 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
18:16:42.907 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
18:16:46.321 [WARN] [org.owasp.dependencycheck.analyzer.CentralAnalyzer] Unable to download pom.xml for ojdbc7-12.1.0.2.jar from Central; this could result in undetected CPE/CVEs.
```

**To Reproduce**
```
plugins {
    id 'java'
    id 'org.owasp.dependencycheck' version '4.0.2'
}

group 'test'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
    maven {
        url '{{company artifactory in here}}/artifactory/{{repo-name}}'
    }
}

dependencies {
    compile "com.oracle:ojdbc7:12.1.0.2" 
}

dependencyCheck {
    cveValidForHours 24
    format 'ALL'
    failBuildOnCVSS 11

    analyzers {
        centralEnabled = true
    }
}
```

**Expected behavior**
It should not get stuck (retry for several minutes), it should just report not found in Maven Central

**Additional context**

**Comment by malejpavouk** [comment]
Maybe a second bug. When I remove our maven repository and use there just mavenLocal(). The central analyzer is not enabled at all. Which is also pretty strange behavior

```
18:23:15.642 [DEBUG] [org.owasp.dependencycheck.Engine] Initializing Central Analyzer
18:23:15.642 [DEBUG] [org.owasp.dependencycheck.Engine] Skipping Central Analyzer (not enabled)
```

**Comment by jeremylong** [comment]
There is a retry count in the Central Analyzer that was added due to stability of central.  In this case I would highly recommend disabling the Central Analyzer as it provides no value if you are using dependency-check from a Gradle or Maven build.
