### ISSUE TITLE
Central analyzer not called (but enabled; works with additional repo)

### ISSUE THREAD

**Issue by malejpavouk** [dependency-check/DependencyCheck#1794]
**Describe the bug**
Central analyzer is not called, even though it is explicitly enabled. Works fine when additional repo is configured.

When I remove our maven repository and use there just mavenLocal(). The central analyzer is not enabled at all. Which is also pretty strange behavior

```
18:23:15.642 [DEBUG] [org.owasp.dependencycheck.Engine] Initializing Central Analyzer
...many lines...
18:23:15.642 [DEBUG] [org.owasp.dependencycheck.Engine] Skipping Central Analyzer (not enabled)
(even when log few lines above says: Enabling the Central analyzer)
```

In case where central is not executed, this line is also not in log `Central analyzer enabled: true`, so it seems that `prepareFileTypeAnalyzer(Engine)` method is never called

** Version of dependency-check used **
The problem occurs using version 4.0.2 of the the Gradle plugin

** Log file **
https://gist.github.com/malejpavouk/faa6f459744928b41eba644302b57774

**To Reproduce**
```
plugins {
    id 'java'
    id 'org.owasp.dependencycheck' version '4.0.2'
}

group 'test'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

repositories {
    // uncomment to make central analyzer running
    //maven {
        //url 'http://{{company artifactory}}/artifactory/{{repository}}'
    //}
    mavenLocal()
    mavenCentral()
}

dependencies {
    compile "com.oracle:ojdbc7:12.1.0.2"
    testCompile group: 'junit', name: 'junit', version: '4.12'
}

dependencyCheck {
    cveValidForHours 24
    format 'ALL'
    failBuildOnCVSS 11

    analyzers {
        jarEnabled = true
        centralEnabled = true
    }
}
```

**Expected behavior**
Central is called, when enabled

**Additional context**

**Comment by jeremylong** [comment]
While I will look into this - you really shouldn't enable the central analyzer for Maven or Gradle builds. It adds absolutely nothing to the analysis.  In fact, it may not be calling central because the information it would have gotten from central is already in the collected evidence.

**Comment by jeremylong** [comment]
CentralAnalyzer should not be used with the maven plugin. It does nothing and can only create slower builds when enabled.
