### ISSUE TITLE
Current version not available at Bintray

### ISSUE THREAD

**Issue by hanshenrik** [dependency-check/DependencyCheck#1796]
**Describe the bug**
At the moment, the version specified at https://jeremylong.github.io/DependencyCheck/current.txt (5.0.0-M2) is greater than the newest version available at https://dl.bintray.com/jeremy-long/owasp/ (5.0.0-M1). Shouldn't these be in sync?

**Expected behavior**
The version returned by https://jeremylong.github.io/DependencyCheck/current.txt should be available at https://dl.bintray.com/jeremy-long/owasp/

**Additional context**
A CircleCI task in our team made this assumption, so our build failed because of this. It could be that it is a wrong assumption to make, but if not, I guess it's nice to know, so it can be prevented in the future.

**Comment by dejan2609** [comment]
~Same~ _Similar_ here:


```
* What went wrong:
Plugin [id: 'org.owasp.dependencycheck', version: '5.0.0-M2'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'org.owasp.dependencycheck:org.owasp.dependencycheck.gradle.plugin:5.0.0-M2')
  Searched in the following repositories:
    Gradle Central Plugin Repository
```

**Comment by jeremylong** [comment]
Sorry - I was interrupted mid release yesterday - the milestone release has been pushed to bintray, central, and docker hub.  brew and the gradle plugin will be done shortly.

**Comment by isaki** [comment]
This is not available on Maven Central as of right now (2019-03-11 15:26 UTC).

https://search.maven.org/search?q=g:org.owasp%20AND%20a:dependency-check-maven&core=gav

**Comment by albuch** [comment]
@isaki it most certanly was published, but search index on maven central takes some time to get updated.

**Comment by jeremylong** [comment]
Also - the gradle plugin is still pending.  I should push be able to push the gradle plugin today (maybe tomorrow)...
