### ISSUE TITLE
Do you build your projects before running the check ?

### ISSUE THREAD

**Issue by heepspray** [dependency-check/DependencyCheck#1804]
Hi guys

I am running the tool against a bunch of medium sized .net projects. I have noticed there is a big difference between simply running dependency check on a code base , and actually building the project before running.. after building you will for instance get dependencies for test tools, IDE, and what not. I am running with Experimental enabled in both cases

Are you supposed to build before running, how are you using this tool ?

Thanks

**Comment by jeremylong** [comment]
Yes, you should build the project as the analysis works best when the actual libraries are present (along with the project file). For dotnet core it would be best to publish before scanning.

```
dotnet publish --configuration Release
```

**Comment by heepspray** [comment]
Got it :) thank you for responding
