### ISSUE TITLE
dependencycheck plugin stuck at "Initializing CPE Analyzer" Step

### ISSUE THREAD

**Issue by llsJllsJ** [dependency-check/DependencyCheck#1805]
plugin version 4.0.2
I would like to know is there any issue that cause in stuck in "Initializing CPE Analyzer" Step
Jenkins job could not complet it task.

I was setting verbose log as below but nothing show more than that message
![image](https://user-images.githubusercontent.com/3104233/54415208-29fc9e80-472e-11e9-9b41-2557f387ba04.png)

**Comment by stevespringett** [comment]
Not that I'm aware of
