### ISSUE TITLE
How to get the raw data before processing them into the dependency-check-report.html

### ISSUE THREAD

**Issue by dyang-branch** [dependency-check/DependencyCheck#1807]
Hi Team,

    This tool works great for me but I would like to reprocess the raw data. Is there a way to extract the raw data before it is processed into the dependency-check-report.html page

Thanks
Daniel

**Comment by jeremylong** [comment]
You can write a custom implementation using the [DependencyCheckScanAgent](https://github.com/jeremylong/DependencyCheck/blob/master/core/src/main/java/org/owasp/dependencycheck/agent/DependencyCheckScanAgent.java#L49). Alternatively, use the XML or JSON output format (or use `format=ALL`) and you can more easily process the resulting data.

**Comment by dyang-branch** [comment]
Thanks. That is very helpful reply
