### ISSUE TITLE
Help Needed from an Oracle DBA

### ISSUE THREAD

**Issue by jeremylong** [dependency-check/DependencyCheck#1808]
We need assistance from an Oracle DBA. The following update statement has an error when run against Oracle and I am having difficulty in figuring out how to resolve the problem:

```sql
UPDATE cpeentry 
SET ecosystem = (SELECT q.eco 
                FROM cpeentry e INNER JOIN 
                    (SELECT DISTINCT vendor, product, Min(ecosystem) eco 
                     FROM   cpeentry 
                     WHERE  ecosystem IS NOT NULL 
                     GROUP  BY vendor, product) q 
                ON q.vendor = e.vendor 
                    AND q.product = e.product 
                    AND e.id = cpeentry.id) 
WHERE EXISTS (SELECT * 
              FROM cpeentry e INNER JOIN
                    (SELECT DISTINCT vendor, product, Min(ecosystem) eco 
                     FROM   cpeentry 
                     WHERE  ecosystem IS NOT NULL 
                     GROUP  BY vendor, product) q 
                ON q.vendor = e.vendor 
                    AND q.product = e.product 
                    AND e.id = cpeentry.id) 
AND cpeentry.ecosystem IS NULL 
```

The CPEEntry table has multiple rows for any give vendor/product combination. After the initial update some of the vendor/product pairs may have an ecosystem set and some of the same pairs may have an ecosystem of null:

|product|vendor|version|ecosystem|
|--------|-------|-------|-----------|
|log4j     |log4j    |1.0       |java            |
|log4j     |log4j    |1.1        |java            |
|log4j     |log4j    |1.2        |`[null]`      |

The above update should copy the java ecosystem from the log4j entry that has an ecosystem and update the null entry for log4j.

**Comment by uweplonus** [comment]
Hi Jeremy,
can you please give the exact Oracle DB version and the exact error message that is given back?

Especially the ORA-????? error number is very important to help you.

**Comment by jeremylong** [comment]
So that would be part of the problem - I don't actually have an oracle database setup myself - all of the Oracle PL/SQL was contributed by others. But the error was reported privately. The error is:

```
ORA-00904: "CPEENTRY"."ID": invalid identifier
```

The only thing that needs to be run to test this (as opposed to standing up the whole database using the [initialize script](https://github.com/jeremylong/DependencyCheck/blob/master/core/src/main/resources/data/initialize_oracle.sql)) would be:

```sql
CREATE TABLE cpeEntry (id INT NOT NULL PRIMARY KEY, part CHAR(1), vendor VARCHAR(255), product VARCHAR(255),
version VARCHAR(255), update_version VARCHAR(255), edition VARCHAR(255), lang VARCHAR(20), sw_edition VARCHAR(255), 
target_sw VARCHAR(255), target_hw VARCHAR(255), other VARCHAR(255), ecosystem VARCHAR(255))\\

UPDATE cpeentry 
SET ecosystem = (SELECT q.eco 
                FROM cpeentry e INNER JOIN 
                    (SELECT DISTINCT vendor, product, Min(ecosystem) eco 
                     FROM   cpeentry 
                     WHERE  ecosystem IS NOT NULL 
                     GROUP  BY vendor, product) q 
                ON q.vendor = e.vendor 
                    AND q.product = e.product 
                    AND e.id = cpeentry.id) 
WHERE EXISTS (SELECT * 
              FROM cpeentry e INNER JOIN
                    (SELECT DISTINCT vendor, product, Min(ecosystem) eco 
                     FROM   cpeentry 
                     WHERE  ecosystem IS NOT NULL 
                     GROUP  BY vendor, product) q 
                ON q.vendor = e.vendor 
                    AND q.product = e.product 
                    AND e.id = cpeentry.id) 
AND cpeentry.ecosystem IS NULL 
```

**Comment by aikebah** [comment]
@jeremylong Don't have an oracle DB at hand, but gut feel is that the 
e.id = cpeentry.id 
is a superfluous condition anyhow (apart from the apparent root cause: referencing the cpeentry table from the inner select out of the scope of the inner select where it's already changed into the select resultset that you aliased 'q')

You want to join the compressed single-row per vendor/product aggregate DISTINCT / min(eco) result with the actual cpeentry entries on matching vendor/product, not on matching vendor/product/id (as id is no longer part of an aggregated select result)

**Comment by aikebah** [comment]
On second read: that final AND clause should have been a where clause I think (to limit the results for select q.eco to the entry that matches the outer cpeentry record) rather than an additional JOIN condition
as in

```sql
UPDATE cpeentry 
SET ecosystem = (SELECT q.eco 
                FROM cpeentry e INNER JOIN 
                    (SELECT DISTINCT vendor, product, Min(ecosystem) eco 
                     FROM   cpeentry 
                     WHERE  ecosystem IS NOT NULL 
                     GROUP  BY vendor, product) q 
                ON q.vendor = e.vendor 
                    AND q.product = e.product
                 WHERE e.id = cpeentry.id)
WHERE EXISTS (SELECT * 
              FROM cpeentry e INNER JOIN
                    (SELECT DISTINCT vendor, product, Min(ecosystem) eco 
                     FROM   cpeentry 
                     WHERE  ecosystem IS NOT NULL 
                     GROUP  BY vendor, product) q 
                ON q.vendor = e.vendor 
                    AND q.product = e.product 
                    WHERE e.id = cpeentry.id) 
AND cpeentry.ecosystem IS NULL 
```

**Comment by uweplonus** [comment]
The last `AND` looks good.
What you can try is to use aliases for the tables, especially `cpeentry`. Oracle is sometimes picky with the table names.

**Comment by aikebah** [comment]
@uweplonus You're right... I just found online in Oracle's documentation that 

> The scope of expressions in the ON clause includes the current tables and any tables in outer query blocks to the current SELECT

So using the ON clause for the additional constraint is indeed supported.

**Comment by GFriedrich** [comment]
@jeremylong: Just tested your statement on an Oracle 18.x and the statement is executing without any issues. Not sure what your exact problem might be here.

**Comment by jeremylong** [comment]
@GFriedrich thank you for validating.
