### ISSUE TITLE
Does it support check Nodejs project

### ISSUE THREAD

**Issue by dyang-branch** [dependency-check/DependencyCheck#1813]
Hi,

  I am using this tool to scan a Nodejs project, but the result does not seem correct. What I observed is that, it did not detect any dependency even though package.json file is present.
  Could you please help me to understand how to improve it? (Even I turn on --enableExperimental option, the package.json file is not parsed)

Thanks
Daniel

**Comment by comatoze** [comment]
Hi. I believe you also need to have package-lock.json present and all the dependencies installed. Try running "npm install" in the project root.

**Comment by dyang-branch** [comment]
Thanks Comatoze, I did not find  package-lock.json file under the project.  I did run npm install as npm-check listed all the dependencies. Any other suggestions

Thanks

**Comment by jeremylong** [comment]
Can you provide the command line you are using and which version of ODC you are using?
