### ISSUE TITLE
Maven Report dependency-check-report.html

### ISSUE THREAD

**Issue by BaumannAxel** [dependency-check/DependencyCheck#1815]
When creating a Maven site report with maven 3.6.0 and maven-site-plugin version 3.7.1 and dependency-check-plugin version 5.0.0-M2 the HTML report file dependency-check-report.html is placed in folder target and not in target/site, though there is a broken link in the generated website
which still refs to
../target/site/dependency-check-report.html

With version 4.0.2 of the dependency check plugin everything works fine.

**Comment by danshome** [comment]
I'm seeing the same thing.

**Comment by danshome** [comment]
I've confirmed by moving back to 4.0.2 that the report goes under target/site.

**Comment by ejschoen** [comment]
I think this was also reported as #1756.  The PBarri's analysis there looks correct: although I don't understand how configuration settings get transformed into keys and values, there was code to initialize the output directory in 4.0.2 that isn't in the 5 branch.  I'd be happy to take a stab at fixing the code and making a PR, but it looks like the 5 branch introduces a new implementation for parameters.
