### ISSUE TITLE
gradle dependencyCheck urlModified and urlBase override leads to strange local download path 

### ISSUE THREAD

**Issue by DerSalvador** [dependency-check/DependencyCheck#1819]
**Describe the bug**
`When overriding the default CVE Urls, I see following error. In debug mode, download seems to be successful, 

$ ./gradlew dependencyCheckAnalyze

Debug Output:

18:12:06.963 [DEBUG] [org.owasp.dependencycheck.utils.HttpResourceConnection] Attempting retrieval of https://domain/nvdcve-Modified.xml.gz
18:12:06.979 [DEBUG] [sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@1b255c8e6 pairs: {GET /nvdcve-Modified.xml.gz HTTP/1.1: null}{Accept-Encoding: gzip, deflate}{User-Agent: Java/1.8.0_201}{Host: host}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
18:12:06.992 [INFO] [org.owasp.dependencycheck.data.update.nvd.DownloadTask] Download Complete for NVD CVE - Modified  (29 ms)
18:12:06.996 [INFO] [org.owasp.dependencycheck.data.update.nvd.ProcessTask] Processing Started for NVD CVE - Modified
18:12:06.997 [DEBUG] [org.owasp.dependencycheck.data.update.nvd.NvdCveParser] Parsing cveModified_3552349291949088380.json.gz
18:12:07.031 [ERROR] [org.owasp.dependencycheck.data.update.nvd.NvdCveParser] Error reading NVD JSON data: /tmp/dctemp99510f98-03dc-4dfc-84b9-a9ae1c104411/c

Gradle code:

dependencyCheck {
    autoUpdate='false'
    suppressionFile='https://domain/supressions/owasp-zkb-suppressions'
    cve {
        urlModified='https:// domain/nvdcve-Modified.xml.gz'
        urlBase='https://domain/nvdcve-%d.xml.gz'
    }
}

Error Message:

Checking for updates and analyzing dependencies for vulnerabilities
Error reading NVD JSON data: /tmp/dctempa0ce82ac-1d76-4385-ae48-5e15a358f059/cve2003_9169566902292688448.json.gz
`

** Version of dependency-check used **
org.owasp:dependency-check-gradle:5.0.0-M2

** Log file **
When reporting errors, 99% of the time log file output is required. Please post the log file as a [gradleWdependencyCheckAnalyzeDependencyCheckUrlModifiedAndUrlBaseOverride.log ](https://gist.github.com/DerSalvador/d90bcf576d7366803d30e3a157be4fea) and provide a link in the new issue.

**To Reproduce**
1. Add to the official gradle example following code and place default nvd files on an internal staging arear
2. Code to add
`dependencyCheck {
    autoUpdate='false'
    suppressionFile='https://repo/supressions/owasp-zkb-suppressions'
    cve {
        urlModified='https://repo/nvdcve-Modified.xml.gz'
        urlBase='https://repo/nvdcve-%d.xml.gz'
    }
    data {
        directory='/home/ga767/nvd'
    }
}
`

**Expected behavior**
Same as with default values only that artefacts are download from internal repos

**Additional context**
Urgent

**Comment by jeremylong** [comment]
The issue is that 5.0.0-M2 utilizes the JSON data feeds - not the XML data feeds.
