### ISSUE TITLE
How to break a build after run dependencyPublish plugin

### ISSUE THREAD

**Issue by llsJllsJ** [dependency-check/DependencyCheck#1822]
Hi,
plugin version=4.0.2
Is this jenkins plugin support break a build after read report result?
I didn't find any relate document.

Thanks

**Comment by llsJllsJ** [comment]
I belive it relates to https://github.com/jeremylong/DependencyCheck/issues/900
but do we have any new implement feature about this?

**Comment by pauldambra** [comment]
We use Jenkins Pipelines and do:

```
stage("Dependency Check") {
            steps {
                sh './gradlew dependencyCheckAnalyze'

                dependencyCheckPublisher(
                        canComputeNew: false,
                        defaultEncoding: '',
                        failedTotalAll: '', // fail if greater than M vulns
                        failedTotalHigh: '', // 0 means fail if any high vulns
                        healthy: '',
                        pattern: '',
                        unHealthy: '' //build is unhealthy while there are more than N vulns
                )

                archiveArtifacts(
                        allowEmptyArchive: true,
                        artifacts: '**/dependency-check-report.*',
                        onlyIfSuccessful: false)

                script {
                    if (currentBuild.result == "FAILURE") {
                        error("Dependency Check failed")
                    }
                }
            }
        }
```

So we're manually checking the result and causing the build to error if necessary

**Comment by stevespringett** [comment]
The analysis-core (what the jenkins plugin is built on) features of breaking the build, don't work that well and pipeline support is half-baked.

Refer to https://groups.google.com/d/msg/dependency-check/2yMe6-Tg8tU/53SCfThcBQAJ for current direction.

As it relates to this ticket however, v5 of the Jenkins plugin, when release, will work with both breaking the build as well as putting it into a warning state, and it works with pipeline. This is already being used in the Dependency-Track community and that plugin is being ported over to Dependency-Check.
