### ISSUE TITLE
Guava API Compatibility

### ISSUE THREAD

**Issue by stevespringett** [dependency-check/DependencyCheck#1825]
Modern versions of Guava can be used, however, API compatibility must be restricted to being compatible with v11.0.1.

It is not possible to bundle Guava with the Dependency-Check Jenkins plugin. So Guava is being omitted from the plugin and the Jenkins version supplied is used instead. As of the most current Jenkins versions, this is v11.0.1.

**Comment by stevespringett** [comment]
Experimental Jenkins plugin using 5.0.0-m2 results in the following:

```
FATAL: com.google.common.collect.ImmutableList.toImmutableList()Ljava/util/stream/Collector;
java.lang.NoSuchMethodError: com.google.common.collect.ImmutableList.toImmutableList()Ljava/util/stream/Collector;
	at org.owasp.dependencycheck.Engine$Mode.<init>(Engine.java:157)
```

**Comment by jeremylong** [comment]
Steve - I have reverted ODC-core to guava v11.0.1 and resolved the API compatibility issues.

**Comment by stevespringett** [comment]
Nice - I'll give it a spin.
