### ISSUE TITLE
Potential false Positive on  confluence-rest-api-6.8.2.jar

### ISSUE THREAD

**Issue by pmehtaupgrade** [dependency-check/DependencyCheck#1826]
When reporting a false positive please include:
- The location of the dependency (Maven)
- The CPE that is believed to be false positive
  - Please report the CPE not the CVE - cpe:/a:atlassian:confluence:6.8.2, com.atlassian.confluence:confluence-rest-api:6.8.2

False positive on **confluence-rest-api-6.8.2.jar** - reported as cpe:/a:atlassian:confluence:6.8.2, com.atlassian.confluence:confluence-rest-api:6.8.2

UPDATE - we have upgraded to the most latest version 6.9.3 and dep-check still report the issue.

https://confluence.atlassian.com/doc/confluence-security-advisory-2019-03-20-966660264.html

**Comment by jeremylong** [comment]
As I do not have access to the JAR file I am unable to add a generic suppression rule.  I would recommend you create a local suppression rule if you feel this is a false positive.
