### ISSUE TITLE
Is it possible to configure dependencyCheckPublisher specify lookup directory dependency-check-report.xml

### ISSUE THREAD

**Issue by VassilMarjunits** [dependency-check/DependencyCheck#1838]
I have need to configure **dependencyCheckPublisher**  to lookup for report from specific directory as it is "**outdir: in dependencyCheckAnalyzer**"
Is it possible in some way?

If Im correct, dependencyCheckPublisher looking up for report only in job workspace directory?

My jenkins job is set up to clean allways workspace after build. 
I this case dependencyCheckPublisher cant read reports from job workspace directory. 
Thats why it would be good to let dependencyCheckPublisher read report from defined directory.

`
pipeline {
    agent any
    stages {
        stage('Gradle Build') {
            steps {
                sh './gradlew clean build'
            }
        }

        stage ('OWASP Dependency-Check Vulnerabilities') {
            steps {
                dependencyCheckAnalyzer ( 
                  datadir: '/opt/jenkins/owasp-dependecy-check', 
                  isAutoupdateDisabled: true, 
                  includeVulnReports: true, 
                  hintsFile: '', 
                  includeCsvReports: false, 
                  includeHtmlReports: true, 
                  includeJsonReports: false, 
                  outdir: "/opt/jenkins/owasp-dependecy-check/${JOB_BASE_NAME}", 
                  scanpath: "${WORKSPACE}", 
                  skipOnScmChange: false, 
                  skipOnUpstreamChange: false, 
                  suppressionFile: '', 
                  zipExtensions: ''
                ) 
              
                dependencyCheckPublisher ( 
                  pattern: "/opt/jenkins/owasp-dependecy-check/${JOB_BASE_NAME}/dependency-check-report.xml"
                )
            }
        }    
  	} 
  post {
    always {
  	cleanWs()
    }
  } 
}
`

**Comment by stevespringett** [comment]
Normally, workspaces are cleaned as the last step of a job, and the publisher step being part of the job would not be affected.

I don't think what you're trying to do is possible. I think it's limited to the workspace to prevent abuse, but I may be wrong. I would normally refer you to the author of analysis-core, but that plugin (which dependency-check is currently built on) is unsupported. This will also not be supported in v5 of the jenkins plugin.
