### ISSUE TITLE
Retry for failed connections to Node Audit API

### ISSUE THREAD

**Issue by DanielOstovary** [dependency-check/DependencyCheck#1845]
**Related Problem**
As of [Failed to read results from the NPM Audit API #1685](https://github.com/jeremylong/DependencyCheck/issues/1685) connections to the Node Audit API are sporadically failing. NPM appears to have such availability problems from time to time. 

**Suggested Solution**
I am using the Dependency Check for my nightly build. Therefore its important to me to not have sporadic build failures. I would suggest to retry connecting to the Node Audit API 2-3 times before letting the Dependency Check fail. I could develop this if you accept a pull request for that matter.

**Comment by thib3113** [comment]
Did you have some errors before ?

On my side, I got the same error, but I got some errors before, and I think this error depend on the other errors .

**Comment by jeremylong** [comment]
We do not plan on implementing retry logic. Rather #2423 and/or local analysis are being considered.
