### ISSUE TITLE
Maven Aggregate - Add Module to Report

### ISSUE THREAD

**Issue by jeremylong** [dependency-check/DependencyCheck#185]
Currently the Maven aggregate report does not show which module(s) include the identified dependency. A section should be added to display this. Also, if possible indicate whether it is a transitive dependency.

**Comment by rlyons** [comment]
+1 I was coming here to add this enhancement request and you already created it :)

**Comment by jeremylong** [comment]
The code that resolves this issue has been pushed to the 1.2.9-SNAPSHOT and will be included in the upcoming release.
