### ISSUE TITLE
Update jenkins dependency check plugin to 5.0.0-M2

### ISSUE THREAD

**Issue by yahanvesh** [dependency-check/DependencyCheck#1850]
The jenkins plugin is still on old version 4.0.2
Please update jenkins  plugin also to the latest available version 5.0.0-M2.
@stevespringett  Any idea on the timelines . Thanks

**Comment by stevespringett** [comment]
V5 isn’t released yet and m2 has known dependency issues with Jenkins and cannot be used. Also it’s a partial rewrite and major refactor. See https://groups.google.com/d/msg/dependency-check/2yMe6-Tg8tU/53SCfThcBQAJ
