### ISSUE TITLE
Jenkins plugin not finding vulnerability maven plugin does

### ISSUE THREAD

**Issue by indefire** [dependency-check/DependencyCheck#1852]
**Describe the bug**
I have a legacy ant based project being built through Jenkins. I installed the Jenkins Dependency-Check plugin and have a separate job that updates the database every night. A colleague of mine wrote a quick pom.xml that utilizes the maven dependency-check plugin that lists the ant dependencies in the pom.xml directly (instead of just relying on the jar analyzer).  The Jenkins plugin does not find vulnerabilities related to commons-compress-1.11.jar and itextpdf-5.5.8.jar. However, the maven plugin does find these vulnerabilities.

** Version of dependency-check used **
Jenkins plugin version 4.0.2 (latest)
Maven plugin (5.0.0-M2)

** Log file **
Total time: 1 minute 21 seconds
[DependencyCheck] OWASP Dependency-Check Plugin v4.0.2
[DependencyCheck] Executing Dependency-Check with the following options:
[DependencyCheck]  -name = **************************_Build
[DependencyCheck]  -scanPath = *****************************

[DependencyCheck]  -outputDirectory = ******************_Build/workspace
[DependencyCheck]  -dataDirectory = ****************/OWSASP-NVD
[DependencyCheck]  -dataMirroringType = none
[DependencyCheck]  -proxyServer = *************
[DependencyCheck]  -proxyPort = *****
[DependencyCheck]  -proxyUsername = *******
[DependencyCheck]  -proxyPassword = ********
[DependencyCheck]  -isQuickQueryTimestampEnabled = true
[DependencyCheck]  -jarAnalyzerEnabled = true
[DependencyCheck]  -nodePackageAnalyzerEnabled = true
[DependencyCheck]  -nodeAuditAnalyzerEnabled = true
[DependencyCheck]  -retireJsAnalyzerEnabled = true
[DependencyCheck]  -composerLockAnalyzerEnabled = true
[DependencyCheck]  -pythonDistributionAnalyzerEnabled = true
[DependencyCheck]  -pythonPackageAnalyzerEnabled = true
[DependencyCheck]  -rubyBundlerAuditAnalyzerEnabled = false
[DependencyCheck]  -rubyGemAnalyzerEnabled = true
[DependencyCheck]  -cocoaPodsAnalyzerEnabled = true
[DependencyCheck]  -swiftPackageManagerAnalyzerEnabled = true
[DependencyCheck]  -archiveAnalyzerEnabled = true
[DependencyCheck]  -assemblyAnalyzerEnabled = true
[DependencyCheck]  -msBuildProjectAnalyzerEnabled = true
[DependencyCheck]  -nuGetConfigAnalyzerEnabled = true
[DependencyCheck]  -nuspecAnalyzerEnabled = true
[DependencyCheck]  -centralAnalyzerEnabled = true
[DependencyCheck]  -nexusAnalyzerEnabled = false
[DependencyCheck]  -artifactoryAnalyzerEnabled = false
[DependencyCheck]  -autoconfAnalyzerEnabled = true
[DependencyCheck]  -cmakeAnalyzerEnabled = true
[DependencyCheck]  -opensslAnalyzerEnabled = true
[DependencyCheck]  -showEvidence = true
[DependencyCheck]  -formats = XML HTML VULN 
[DependencyCheck]  -autoUpdate = false
[DependencyCheck]  -updateOnly = false
[DependencyCheck] Scanning: *********************/lib
[DependencyCheck] Scanning: ***************************/WebContent/WEB-INF/lib
[DependencyCheck] Analyzing Dependencies
Build step 'Invoke Dependency-Check analysis' changed build result to SUCCESS

**Expected behavior**
Expected: Jenkins dependency-check plugin would find the same vulnerabilities as the maven plugin.
Actual: Maven plugin finds additional vulernabilities

**Comment by stevespringett** [comment]
Build plugins for Maven, SBT, Gradle, etc exist so they can analyze their respective ecosystem. The Dependency-Check command-line utility for example, analyzes files on the filesystem. But it doesn't know what a pom is or how to parse it. If you want to be able to analyze a pom, the Maven plugin can do this. The Jenkins plugin is a reimplementation of the command-line utility. It does not understand what a pom is and will never be able to properly analyze it.

- Alway use native build plugins for ecosystems that have them and produce XML reports
- Use the Jenkins plugin (publisher step only) to analyze the XML produced from a build plugin

**Comment by indefire** [comment]
Thank you Steve for your quick reply, however, it seems as though I was not clear enough. I will try to rephrase the issue as succinctly as possibly.

Existing ant build, after the ant build I have the job configured to kick off Dependency-Check. It does find some vulnerabilities properly by specifying WEB-INF/lib directory.

To verify the dependency check's findings, I have a SEPARATE maven pom.xml that specifies the same dependencies that the ant script specifies and the maven plugin is ran INDEPENDENTLY (not part of the same Jenkins job) and finds more vulnerabilities.

**Comment by stevespringett** [comment]
The Ant build plugin is a wrapper around the command line functionality. It doesn't support Ivy. If there was support for Ivy and your build used Ivy, the results should be (nearly) identical to that of the Maven plugin.

But the Ant plugin is doing the same type of file scan as the cli in the WEB-INF/lib folder in your case, so the accuracy of the results is not going to be as good as if you were using a dependency-management solution like Maven.

**Comment by indefire** [comment]
Thank you Steve, you answered my question perfectly. This is what I get from this explanation: I should not trust the Jenkins Dependency-Check plugin and should just use the maven plugin as an additional step in the build process to get more accurate results.

Thank you so much!
