### ISSUE TITLE
CPEAnalyzer can't find proper CPE because of query limit

### ISSUE THREAD

**Issue by Nekto89** [dependency-check/DependencyCheck#1853]
DependencyCheck can't find CPE for popular libraries because of query limit in CPEAnalyzer.

[fake_cmake.zip](https://github.com/jeremylong/DependencyCheck/files/3069856/fake_cmake.zip)

Example of CPE that are found without fix:
- cpe:/a:cryptopp:crypto++:7.0.0
cpe:/a:cryptopp:crypto++_library:7.0.0
- cpe:/a:gnu:zlib:1.2.11
- cpe:/a:intel:threading_building_blocks:2019.u2
- cpe:/a:intel:integrated_performance_primitives:9.0.0
- cpe:/a:grassroots_dicom_project:grassroots_dicom:2.8.8

I've tried changing
https://github.com/jeremylong/DependencyCheck/blob/85e0c9219a08a7479e7afb0a3d381424632eb315/core/src/main/java/org/owasp/dependencycheck/analyzer/CPEAnalyzer.java#L93
 to
`private static final int MAX_QUERY_RESULTS = 5000;`

This leads to much better results:
- cpe:2.3:a:cryptopp:crypto\+\+:7.0.0:*:*:*:*:*:*:*
cpe:2.3:a:cryptopp:crypto\+\+_library:7.0.0:*:*:*:*:*:*:*
- cpe:2.3:a:gnu:zlib:1.2.11:*:*:*:*:*:*:*
- cpe:2.3:a:sqlite:sqlite:3.24.0.0:*:*:*:*:*:*:*
- cpe:2.3:a:intel:threading_building_blocks:2019.u2:*:*:*:*:*:*:*
- cpe:2.3:a:libpng:libpng:1.6.34:*:*:*:*:*:*:*
- cpe:2.3:a:libtiff:libtiff:4.0.10:*:*:*:*:*:*:*
- cpe:2.3:a:libexpat:expat:2.2.5:*:*:*:*:*:*:*
cpe:2.3:a:libexpat_project:libexpat:2.2.5:*:*:*:*:*:*:*
- cpe:2.3:a:python:python:3.7:beta:*:*:*:*:*:*
cpe:2.3:a:python_software_foundation:python:3.7.0:*:*:*:*:*:*:*
- cpe:2.3:a:boost:boost:1.67.0:*:*:*:*:*:*:*
- cpe:2.3:a:minizip_project:minizip:1.1:*:*:*:*:*:*:*
- cpe:2.3:a:openssl:openssl:1.0.2o:*:*:*:*:*:*:*
cpe:2.3:a:openssl_project:openssl:1.0.2o:*:*:*:*:*:*:*
- cpe:2.3:a:intel:integrated_performance_primitives:9.0.0:*:*:*:*:*:*:*
- cpe:2.3:a:grassroots_dicom_project:grassroots_dicom:2.8.8:*:*:*:*:*:*:*	

The problem occurs using versions v5.0.0-M2 and v4.0.2 of the cli

**Comment by jeremylong** [comment]
The query limit is a choice between FP and FN.  I can see why, in the case of make files we may want to use a higher query limit. I am almost wondering if we should create a per ecosystem query limit - not sure if the gain would be worth the effort.

Options:
1. Expose the query limit as number
2. Expose the query limit as a field like `searchDepth` with values of low, medium, and high
3. Expose the query limit as a field like `audience` with values like DevOps, Developer, and Security
4. Keep the query limit (mostly) internal and set per ecosystem query limits.  Analyzers that pull more evidence like Java would have a lower query limit whereas things like make files would have a higher query limit.

@stevespringett @aikebah @stefanneuhaus - any opinion on this one?  While I feel option 4 might be the best - I am concerned about having a large enough sample size to accurately set the query limit.  What we have now is my analysis of Java to get to a balance of FP/FN and the query limit is set at 25.

**Comment by stevespringett** [comment]
I feel like this should be a mostly internal thing (option 4) with an unsupported way to override it in the event a user runs into issues. I think a lack of data on our part (for make and a few other things) will make configuration a short-term requirement as we sort it out. But I also don't want to go all-in and have it in Settings.java either. I think it can likely be simpler than that; env variable or something. Otherwise, we have to expose this thing to all the implementations which is not what we want to do.

**Comment by aikebah** [comment]
In my opinion the tweaking of the lucene index (which I consider the query limit to be part of) should be viewed as an internal concern of DC. If another indexing/searching mechanism would've been used for the CPE-matching magic we would have other dials to fine-tune the search with respect to FP/FN rates. Even with the drawbacks mentioned I feel that option 4 would be the best way forward.

**Comment by jeremylong** [comment]
This will be included in the next release.
