### ISSUE TITLE
Dependency checker not failing on CVSS

### ISSUE THREAD

**Issue by din-eshch** [dependency-check/DependencyCheck#1854]
Hello, I created a wrapper around ```dependency-check.sh``` so that individual repo owners using dependency checker in their pipelines don't mess with ```failonCVSS```.

My wrapper looks like this (```odc-wrapper.sh```)

```
#!/bin/sh
...
...
sh dependency-check.sh \
    --scan /src \
    --project "$APP_NAME" \
    --out /report/dependency-check-report.html \
    --enableExperimental \
    --failOnCVSS 1 \
    --cveValidForHours 24 \
    --log /report/full-log.txt 
```

Dockerfile looks like this

```
...
...
ENTRYPOINT ["/usr/share/dependency-check/bin/odc-wrapper.sh"]
```

Repo owners do this during the build

```
...
...
    docker run --rm \
    --volume /tmp/source-code:/src \
    --volume /tmp/report:/report \
    odc-wrapper \
    --project "$APP_NAME" 
```

```src``` directory has some bugs with CVSS > 1. When I look at the ```/report/full-log.txt```, I see that the program ends with ```DEBUG - Exit code: 1``` as expected.

However, this did not break the build. I don't know if this is a bug in dependency checker or my wrapper. Somehow the exit code doesn't get passed back to my wrapper.

**Comment by din-eshch** [comment]
The build system is calling out the bugs too. But it doesn't break the build.
```
00:00  INFO: Vulnerability found: jquery below 1.9.0b1

00:00  INFO: Vulnerability found: jquery below 1.12.0

00:00  INFO: Vulnerability found: jquery below 1.12.0
```

**Comment by jeremylong** [comment]
If you are using the command line you would have to use the return code to know if you should fail anything.  Dependency-check is working as expected.
