### ISSUE TITLE
What is the proper stage in jenkins pipeline

### ISSUE THREAD

**Issue by llsJllsJ** [dependency-check/DependencyCheck#1855]
Hi,

I would like to know if I am going to include this plugin to our jenkins pipeline. What is the best practice to add this stage in jenkins pipeline
Should it be before or after build stage? As I have tested, result are different when this stage present before or after build stage.

Thanks

**Comment by stevespringett** [comment]
Depends on the ecosystem and what's being built (and how). Normally, Dependency-Track would be one of the later steps in a build.
