### ISSUE TITLE
Why do authentication(r?) and baseSeverity have a '>' suffix in the json velocity template?

### ISSUE THREAD

**Issue by jamesratzlaff** [dependency-check/DependencyCheck#1857]
The fields/keys [authenticationr](https://github.com/jeremylong/DependencyCheck/blob/85e0c9219a08a7479e7afb0a3d381424632eb315/core/src/main/resources/templates/jsonReport.vsl#L155) and [baseSeverity](https://github.com/jeremylong/DependencyCheck/blob/85e0c9219a08a7479e7afb0a3d381424632eb315/core/src/main/resources/templates/jsonReport.vsl#L173) (also located at [line 220](https://github.com/jeremylong/DependencyCheck/blob/85e0c9219a08a7479e7afb0a3d381424632eb315/core/src/main/resources/templates/jsonReport.vsl#L220) and [line 238](https://github.com/jeremylong/DependencyCheck/blob/85e0c9219a08a7479e7afb0a3d381424632eb315/core/src/main/resources/templates/jsonReport.vsl#L238) in jsonReport.vsl ) end with a '>'.  At a glance it looks like a possible spelling and xml-copy-paste error. It also makes auto-json serialization for certain things like protobufs not doable. Are these fields intentionally named this way?

**Comment by jeremylong** [comment]
Thanks for letting us know!  Simple copy/paste error.
