### ISSUE TITLE
Configure with jenkins salve

### ISSUE THREAD

**Issue by labrute** [dependency-check/DependencyCheck#1860]
Hello,

I'm trying to create a dependency check job, with only this task into the build (to keep DB up to date)
My job is executed by a jenkins slave, and i have this error : 
`[DependencyCheck] Performing update only
[DependencyCheck] Unable to update the Dependency-Check database
Build step 'Invoke Dependency-Check update only' changed build result to FAILURE
Finished: FAILURE`

I guess there i have a directory permission issue but i'm not sure.
What should i do to see full log and to configure plugin working with slave ?

Thx.

**Comment by stevespringett** [comment]
Check the Jenkins logs (enable debug for org.owasp if you need to)
