### ISSUE TITLE
How to configure the plugin - using Gradle Kotlin DSL ?

### ISSUE THREAD

**Issue by bastman** [dependency-check/DependencyCheck#1861]
Hi, could you please add a documentation how to configure the plugin using Kotlin DSL for gradle. 

Current docs explains it for groovy dsl.

e.g. groovy dsl:

```
dependencyCheck {
    failOnError=false
}
```

I wonder, how port that one to Kotlin DSL.

Thanks a lot for your help.

**Comment by lukas-krecan** [comment]
This works for me  (different use-case, hope it helps)
```
dependencyCheck {
    analyzers(closureOf<org.owasp.dependencycheck.gradle.extension.AnalyzerExtension> {
        assemblyEnabled = false
    })
}
```

**Comment by beloglazov91** [comment]
> 
> 
> This works for me (different use-case, hope it helps)
> 
> ```
> dependencyCheck {
>     analyzers(closureOf<org.owasp.dependencycheck.gradle.extension.AnalyzerExtension> {
>         assemblyEnabled = false
>     })
> }
> ```

@lukas-krecan Could you show here the full config? 

Just I see only:

```
* What went wrong:
Script compilation errors:

  Line 18: dependencyCheck {
           ^ Unresolved reference: dependencyCheck

  Line 19:     analyzers(closureOf<org.owasp.dependencycheck.gradle.extension.AnalyzerExtension> {
               ^ Unresolved reference: analyzers
```

**Comment by hakanai** [comment]
Wondering the same thing at the moment. Also getting the same error as the previous comment.

  Line 18: dependencyCheck {
           ^ Unresolved reference: dependencyCheck
