### ISSUE TITLE
Using Azure MSSQL  Database takes too long to update

### ISSUE THREAD

**Issue by adusumillipraveen** [dependency-check/DependencyCheck#1862]
We started using database mirror for dependency check and both the initial load and updates are very slow . 

We are using Gradle task running from Jenkins to update Azure Managed MSSQL data base. The initial load took around 5 days to complete , but then we increased the IOPS and CPU , it is now relatively faster. Still, the updates takes more than an hour timing out our builds.

 Is there a known solution for this and any recommendations around it ? Which database is proven to be quicker among all ? Any suggestions would be really helpful.

Gradle version : 5.2.1
Database : Azure MSSQL
Driver : 'mssql-jdbc', version: '7.2.1.jre8'
OWASP DB version : 3.0
OWASP Gradle Plugin version : 4.0.2

**Comment by jeremylong** [comment]
We have not optimized the import/update when using a different database than the embedded H2 - PRs are more than welcome.

That being said, most organizations that use a centralized database like this have the scanning nodes configured so that they do not update the database.  They then setup a specific job to run the updates on a periodic basis (every four to 24 hours).

**Comment by adusumillipraveen** [comment]
@jeremylong Thanks for your quick response.Yes, we have setup a separate job configured to update the database and all our application builds have autoupdate set to false . So, is it usual to have DB updates for more than an hour  for databases other than H2?

**Comment by jeremylong** [comment]
Unfortunately - I think the answer is yes.  I don't run ODC using a centralized database myself so I don't have a lot of experience with how long updates normally take.  But I have seen the initial load take a VERY long time.  We have not had anyone submit a PR to enhance how we handle the initial load and updates for centralized databases - but I bet a lot could be done to improve the load time.

**Comment by adusumillipraveen** [comment]
Thanks, we have moved to postgresql on Azure and it is relatively faster compared to MSSQL. The initial setup took for around 2.5 hours but the daily updates completed in less than 10 minutes from Jenkins.
