### ISSUE TITLE
Question regarding JAR and POM analysis via CLI

### ISSUE THREAD

**Issue by adamday2** [dependency-check/DependencyCheck#1867]
Hello,

Based on the following:
https://jeremylong.github.io/DependencyCheck/analyzers/index.html
I see that the pom files are scanned, but when running the CLI and performing a scan against my application's jar file, I do not see any of the dependencies in my pom.xml listed in the output.

Is this the intended functionality?

I realize that there are ways around this such as including all of the dependency jars in the scan or using the maven plugin, but wanted to ensure that I correctly understood of the usage of the tool.

**Comment by jeremylong** [comment]
The language on that page needs to be updated - the pom.xml is only analyzed if they are embedded within a JAR. If you are analyzing a maven project you should use the [maven plugin](https://jeremylong.github.io/DependencyCheck/dependency-check-maven/index.html).

**Comment by adamday2** [comment]
Thanks for the quick response @jeremylong !

> ...the pom.xml is only analyzed if they are embedded within a JAR...

To clarify, if I'm scanning a single (non-shaded) jar, and the jar includes `META-INF/maven/foo.bar/bar/pom.xml` the dependencies in that pom would or would not be analyzed?

**Comment by jeremylong** [comment]
No - we would not look at the dependencies defined within the shaded jar. If you have `shaded.jar` and it when it was built it used the shade plugin to incorporate `a.jar`, `b.jar`, and `c.jar`.  Inside of `shaded.jar` you would have `META-INF/maven/company/a/pom.xml`, `META-INF/maven/company/b/pom.xml`, and `META-INF/maven/company/c/pom.xml`.  In this case dependency-check would create 3 virtual dependencies, "a", "b", and "c", and use the information in the respective pom files as evidence for CPE identification.

The only time the dependencies section of a pom.xml is "analyzed" is when using the maven plugin. While I say analyzed - I feel that is slightly incorrect. ODC never reads the pom.xml itself; instead it relies on the dependency resolution of maven.

**Comment by adamday2** [comment]
That answers all of my questions - thank you!
