### ISSUE TITLE
Do not require POM for update-only maven goal

### ISSUE THREAD

**Issue by mprins** [dependency-check/DependencyCheck#1868]
**Is your feature request related to a problem?**
When running `mvn org.owasp:dependency-check-maven:4.0.2:update-only` without a pom.xml Maven fails and complains "Goal requires a project to execute but there is no POM in this directory (/tmp). Please verify you invoked Maven from the correct directory."

**Describe the solution you'd like**
It would be nice to be able to run `mvn org.owasp:dependency-check-maven:4.0.2:update-only` without a project to update the local cache of the NVD data from NIST. There is in fact no need for having a pom file as all parameters can be specified on the command line.

**Describe alternatives you've considered**
Create a no-op maven project and run that.

**Additional context**
I would like to run a batch process on my build server to update this data once a day without stalling the first build of the day.

I've also tried with 5.0.0-M2 with identical results.

Part of this problem may be caused because the UpdateMojo extends the BaseDependencyCheckMojo which has other unwanted side-effects such as stating that the pluging should be used as a report in the [generated documentation](https://jeremylong.github.io/DependencyCheck/dependency-check-maven/update-only-mojo.html) along with some parameters that just don't make sense for the update goal.

**Comment by mprins** [comment]
The quick workaround is:

```
echo '<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.owasp</groupId>
    <artifactId>owasp-update</artifactId>
    <version>0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
</project>' > /tmp/pom.xml
```
and then: `-f /tmp/pom.xml org.owasp:dependency-check-maven:4.0.2:update-only`

**Comment by jeremylong** [comment]
Alternatively, you can use the CLI version of dependency-check to update the maven data.  However, there is no way to run the maven goal without a pom.xml; this is just how maven works.

**Comment by mprins** [comment]
> this is just how maven works.

this is simply not true; there are plenty of maven goals that do not require a maven project to run, basically all of the artifact generators `mvn archetype:generate`, generally any `help` goal, such as `org.owasp:dependency-check-maven:4.0.2:help` and many more

using the CLI is inconvienient because it doesn't know about the maven repository where the data is stored

**Comment by jeremylong** [comment]
Learn something new everyday...  This will be included in the next release.

**Comment by mprins** [comment]
Apparently it should be as simple as adding `requiresProject = false` 

```
@Mojo(requiresProject = false, ...)
public class MyMojo extends AbstractMojo  { ... }
```
See e.g.. https://stackoverflow.com/a/36861025
