### ISSUE TITLE
False Positive on tinify - exclusion does not work

### ISSUE THREAD

**Issue by stefangohlkedreamit** [dependency-check/DependencyCheck#1870]
False positive on library okhttp-3.10.0.jar - reported as cpe:2.3:a:squareup:okhttp3:3.10.0:*:*:*:*:*:*:* 
```xml
        <dependency>
            <groupId>com.tinify</groupId>
            <artifactId>tinify</artifactId>
            <version>1.6.4</version>
            <exclusions>
                <exclusion>
                    <groupId>com.squareup.okhttp3</groupId>
                    <artifactId>okhttp</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>3.14.1</version>
        </dependency>
```
In org.owasp:dependency-check-maven:5.0.0-M2 exclusion does not seem to be working. In the report it is shown as "tinify-1.6.4.jar: okhttp-3.10.0.jar", this is not correct as the dependency tree is:
+- com.tinify:tinify:jar:1.6.4:compile
|  \- com.google.code.gson:gson:jar:2.8.5:compile
\- com.squareup.okhttp3:okhttp:jar:3.14.1:compile
   \- com.squareup.okio:okio:jar:1.17.2:compile

 In version 4.0.2 it is working as it should.

**Comment by jeremylong** [comment]
This was changed to a question as dependency-check is working as expected.  In the report from 5.0.0-m2 - take a look at the path to the okhttp.jar.  You will see that tinify has an embedded copy of the dependent JAR files.

**Comment by stefangohlkedreamit** [comment]
Do you have any idea how to fix this? Should I ask the tinify developers for support? I was wondering because org.owasp:dependency-check-maven:4.0.2 did not seem to mark this as a problem.

**Comment by stefangohlkedreamit** [comment]
I sent a short email to the tinify support team asking them to update the version of okhttp.
