### ISSUE TITLE
maven-plugin: Support suppressions from external dependencies

### ISSUE THREAD

**Issue by kwin** [dependency-check/DependencyCheck#1878]
Currently the only way to add suppressions is via absolute file paths.
This does not work well for complex maven projects, where you are interested to inherit suppression from the parent (which is not part of the reactor).

It would be nice if suppressions could be either provided in an inline fashion (i.e. within the pom.xml) or could be also loaded from a dependency file (in zip/jar format)

There is very similar feature already available in the formatter-maven-plugin which should give some hints on how to implement this: https://code.revelc.net/formatter-maven-plugin/examples.html#Basic_Configuration_Using_External_Resource

**Comment by TobiX** [comment]
This works for me:
```xml
        <plugin>
          <groupId>org.owasp</groupId>
          <artifactId>dependency-check-maven</artifactId>
          <configuration>
            <suppressionFile>my-owasp-suppressions.xml</suppressionFile>
          </configuration>
          <dependencies>
            <dependency>
              <groupId>my.company</groupId>
              <artifactId>owasp-suppressions</artifactId>
              <version>1.0.5</version>
            </dependency>
          </dependencies>
        </plugin>
```

The artifact `my.company:owasp-suppressions` contains `my-owasp-suppressions.xml` and it is consulted by the Maven plugin.

**Comment by kwin** [comment]
Perfect, maybe this can be clarified then in the docs?

**Comment by kwin** [comment]
I cannot get it to work, even when executing with `-X` I don't see that the suppressions are taken into consideration. Also no error/info is being emitted to suppressions at all. What log entry should I be looking for to debug this further?

**Comment by TobiX** [comment]
```
[INFO] Created CPE Index (1 seconds)
[INFO] Skipping CPE Analysis for npm
[DEBUG] Loading suppression rules from 'my-owasp-suppressions.xml'
[DEBUG] 11 suppression rules were loaded.
[DEBUG] Starting CPE Analyzer
[DEBUG] Parallel processing with up to 8 threads: CPE Analyzer.
...
[DEBUG] Initializing Vulnerability Suppression Analyzer
[DEBUG] Loading suppression rules from 'my-owasp-suppressions.xml'
[DEBUG] 11 suppression rules were loaded.
[DEBUG] Starting Vulnerability Suppression Analyzer
[DEBUG] Parallel processing with up to 8 threads: Vulnerability Suppression Analyzer.
```

**Comment by kwin** [comment]
Works now, sorry for the noise, something was wrong with my configuration.

**Comment by jeremylong** [comment]
@TobiX thanks for answering this!

I really need to put together a deployment guide that covers things like this.

**Comment by jeremylong** [comment]
The documentation has been updated.
