### ISSUE TITLE
consider mapping docker volumes to host user

### ISSUE THREAD

**Issue by sellersj** [dependency-check/DependencyCheck#1883]
**Is your feature request related to a problem? Please describe.**
The files written to the mapped volume should match the account running the docker command.

**Describe the solution you'd like**
The files read / written should have the correct user:group

**Describe alternatives you've considered**
Didn't yet?

**Additional context**
I changed it, overriding the user, user's uid:gid, as well as adding the z flag for the mapped volume.

Aside: I changed the version to be a variable since there's a pull part as well.
```
docker run --rm \
    -e user=$USER \
    -u $(id -u ${USER}):$(id -g ${USER}) \
    --volume $(pwd):/z \
    --volume "$DATA_DIRECTORY":/usr/share/dependency-check/data:z \
    --volume $(pwd)/"$REPORT_DIRECTORY":/report:z \
    owasp/dependency-check:$DEP_CHECK_VERSION \
    --noupdate \
    --scan /src \
    --format "ALL" \
    --project "My OWASP Dependency Check Project" \
    --out /report
```

**Comment by jeksmith** [comment]
Thank you for this. 

It looks like there is a small problem with the first volume arg missing a colon. I assume it should be `--volume $(pwd):/:z`
