### ISSUE TITLE
Error during command line Angular scan

### ISSUE THREAD

**Issue by vaishravin** [dependency-check/DependencyCheck#1896]
Hi Team,

We are scanning an Angular project using command line. We were prompted to run npm install. Post that we scanned again and we got the below warnings and errors, but the report was generated. Can we consider this as a valid report. Can you suggest any changes to be done so that warnings/errors are fixed. We get a message stating that there maybe false negatives. This is for a critical deliverable. Please help us.

We are using Dependency Check 4.0.2. Let us know if any other additional information is required.

[INFO] Checking for updates
[INFO] Skipping NVD check since last check was within 4 hours.
[INFO] Skipping RetireJS update since last update was within 24 hours.
[INFO] Check for updates complete (10271 ms)
[INFO] Analysis Started
[INFO] Finished Archive Analyzer (4 seconds)
[INFO] Finished File Name Analyzer (0 seconds)
[WARN] Unable to find node module: Path of nodemodule\async-foreach\package.json
[WARN] Unable to find node module: Path of nodemodule\block-stream\package.json
[WARN] Unable to find node module: Path of nodemodule\font-awesome\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\abbrev\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\ansi-regex\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\aproba\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\are-we-there-yet\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\balanced-match\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\brace-expansion\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\chownr\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\code-point-at\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\concat-map\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\console-control-strings\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\core-util-is\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\debug\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\deep-extend\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\delegates\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\detect-libc\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\fs-minipass\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\fs.realpath\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\gauge\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\glob\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\has-unicode\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\iconv-lite\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\ignore-walk\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\inflight\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\inherits\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\ini\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\is-fullwidth-code-point\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\isarray\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\minimatch\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\minimist\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\minipass\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\minizlib\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\mkdirp\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\ms\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\needle\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\node-pre-gyp\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\nopt\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\npm-bundled\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\npm-packlist\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\npmlog\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\number-is-nan\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\object-assign\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\once\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\os-homedir\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\os-tmpdir\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\osenv\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\path-is-absolute\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\process-nextick-args\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\rc\node_modules\minimist\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\rc\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\readable-stream\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\rimraf\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\safe-buffer\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\safer-buffer\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\sax\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\semver\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\set-blocking\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\signal-exit\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\string-width\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\string_decoder\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\strip-ansi\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\strip-json-comments\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\tar\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\util-deprecate\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\wide-align\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\wrappy\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\node_modules\yallist\package.json
[WARN] Unable to find node module: Path of nodemodule\fsevents\package.json
[WARN] Unable to find node module: Path of nodemodule\fstream\package.json
[WARN] Unable to find node module: Path of nodemodule\gaze\package.json
[WARN] Unable to find node module: Path of nodemodule\globule\node_modules\glob\package.json
[WARN] Unable to find node module: Path of nodemodule\globule\package.json
[WARN] Unable to find node module: Path of nodemodule\in-publish\package.json
[WARN] Unable to find node module: Path of nodemodule\js-base64\package.json
[WARN] Unable to find node module: Path of nodemodule\lodash.assign\package.json
[WARN] Unable to find node module: Path of nodemodule\lodash.mergewith\package.json
[WARN] Unable to find node module: Path of nodemodule\nan\package.json
[WARN] Unable to find node module: Path of nodemodule\node-gyp\node_modules\ajv\package.json
[WARN] Unable to find node module: Path of nodemodule\node-gyp\node_modules\assert-plus\package.json
[WARN] Unable to find node module: Path of nodemodule\node-gyp\node_modules\aws-sign2\package.json
[WARN] Unable to find node module: Path of nodemodule\node-gyp\node_modules\aws4\package.json
[WARN] Unable to find node module: Path of nodemodule\node-gyp\node_modules\extend\package.json
[WARN] Unable to find node module: Path of nodemodule\node-gyp\node_modules\fast-deep-equal\package.json
[WARN] Unable to find node module: Path of nodemodule\node-gyp\node_modules\form-data\package.json
[WARN] Unable to find node module: Path of nodemodule\node-gyp\node_modules\glob\package.json
[WARN] Unable to find node module: Path of nodemodule\node-gyp\node_modules\har-schema\package.json
[WARN] Unable to find node module: Path of nodemodule\node-gyp\node_modules\har-validator\package.json
[WARN] Unable to find node module: Path of nodemodule\node-gyp\node_modules\http-signature\package.json
[WARN] Unable to find node module: Path of nodemodule\node-gyp\node_modules\json-schema-traverse\package.json
[WARN] Unable to find node module: Path of nodemodule\node-gyp\node_modules\mime-db\package.json
[WARN] Unable to find node module: Path of nodemodule\node-gyp\node_modules\mime-types\package.json
[WARN] Unable to find node module: Path of nodemodule\node-gyp\node_modules\nopt\package.json
[WARN] Unable to find node module: Path of nodemodule\node-gyp\node_modules\oauth-sign\package.json
[WARN] Unable to find node module: Path of nodemodule\node-gyp\node_modules\performance-now\package.json
[WARN] Unable to find node module: Path of nodemodule\node-gyp\node_modules\qs\package.json
[WARN] Unable to find node module: Path of nodemodule\node-gyp\node_modules\request\package.json
[WARN] Unable to find node module: Path of nodemodule\node-gyp\node_modules\safe-buffer\package.json
[WARN] Unable to find node module: Path of nodemodule\node-gyp\node_modules\semver\package.json
[WARN] Unable to find node module: Path of nodemodule\node-gyp\node_modules\tough-cookie\node_modules\punycode\package.json
[WARN] Unable to find node module: Path of nodemodule\node-gyp\node_modules\tough-cookie\package.json
[WARN] Unable to find node module: Path of nodemodule\node-gyp\node_modules\uri-js\package.json
[WARN] Unable to find node module: Path of nodemodule\node-gyp\node_modules\uuid\package.json
[WARN] Unable to find node module: Path of nodemodule\node-gyp\package.json
[WARN] Unable to find node module: Path of nodemodule\node-sass\node_modules\ajv\package.json
[WARN] Unable to find node module: Path of nodemodule\node-sass\node_modules\ansi-styles\package.json
[WARN] Unable to find node module: Path of nodemodule\node-sass\node_modules\assert-plus\package.json
[WARN] Unable to find node module: Path of nodemodule\node-sass\node_modules\aws-sign2\package.json
[WARN] Unable to find node module: Path of nodemodule\node-sass\node_modules\aws4\package.json
[WARN] Unable to find node module: Path of nodemodule\node-sass\node_modules\chalk\package.json
[WARN] Unable to find node module: Path of nodemodule\node-sass\node_modules\cross-spawn\package.json
[WARN] Unable to find node module: Path of nodemodule\node-sass\node_modules\extend\package.json
[WARN] Unable to find node module: Path of nodemodule\node-sass\node_modules\fast-deep-equal\package.json
[WARN] Unable to find node module: Path of nodemodule\node-sass\node_modules\form-data\package.json
[WARN] Unable to find node module: Path of nodemodule\node-sass\node_modules\glob\package.json
[WARN] Unable to find node module: Path of nodemodule\node-sass\node_modules\har-schema\package.json
[WARN] Unable to find node module: Path of nodemodule\node-sass\node_modules\har-validator\package.json
[WARN] Unable to find node module: Path of nodemodule\node-sass\node_modules\http-signature\package.json
[WARN] Unable to find node module: Path of nodemodule\node-sass\node_modules\json-schema-traverse\package.json
[WARN] Unable to find node module: Path of nodemodule\node-sass\node_modules\mime-db\package.json
[WARN] Unable to find node module: Path of nodemodule\node-sass\node_modules\mime-types\package.json
[WARN] Unable to find node module: Path of nodemodule\node-sass\node_modules\oauth-sign\package.json
[WARN] Unable to find node module: Path of nodemodule\node-sass\node_modules\performance-now\package.json
[WARN] Unable to find node module: Path of nodemodule\node-sass\node_modules\qs\package.json
[WARN] Unable to find node module: Path of nodemodule\node-sass\node_modules\request\package.json
[WARN] Unable to find node module: Path of nodemodule\node-sass\node_modules\safe-buffer\package.json
[WARN] Unable to find node module: Path of nodemodule\node-sass\node_modules\supports-color\package.json
[WARN] Unable to find node module: Path of nodemodule\node-sass\node_modules\tough-cookie\node_modules\punycode\package.json
[WARN] Unable to find node module: Path of nodemodule\node-sass\node_modules\tough-cookie\package.json
[WARN] Unable to find node module: Path of nodemodule\node-sass\node_modules\uri-js\package.json
[WARN] Unable to find node module: Path of nodemodule\node-sass\node_modules\uuid\package.json
[WARN] Unable to find node module: Path of nodemodule\node-sass\package.json
[WARN] Unable to find node module: Path of nodemodule\psl\package.json
[WARN] Unable to find node module: Path of nodemodule\sass-graph\node_modules\glob\package.json
[WARN] Unable to find node module: Path of nodemodule\sass-graph\package.json
[WARN] Unable to find node module: Path of nodemodule\scss-tokenizer\node_modules\source-map\package.json
[WARN] Unable to find node module: Path of nodemodule\scss-tokenizer\package.json
[WARN] Unable to find node module: Path of nodemodule\stdout-stream\package.json
[WARN] Unable to find node module: Path of nodemodule\tar\package.json
[WARN] Unable to find node module: Path of nodemodule\yargs\node_modules\camelcase\package.json
[WARN] Unable to find node module: Path of nodemodule\yargs\node_modules\y18n\package.json
[WARN] Unable to find node module: Path of nodemodule\yargs\package.json
[WARN] Unable to find node module: Path of nodemodule\yargs-parser\node_modules\camelcase\package.json
[WARN] Unable to find node module: Path of nodemodule\yargs-parser\package.json
[INFO] Finished Node.js Package Analyzer (11 seconds)
[INFO] Finished Dependency Merging Analyzer (0 seconds)
[INFO] Finished Version Filter Analyzer (0 seconds)
[INFO] Finished Hint Analyzer (0 seconds)
[INFO] Created CPE Index (3 seconds)
[INFO] Skipping CPE Analysis for npm
[INFO] Finished CPE Analyzer (4 seconds)
[INFO] Finished False Positive Analyzer (0 seconds)
[INFO] Finished NVD CVE Analyzer (0 seconds)
[WARN] An error occurred while analyzing 'D:\xxx\package-lock.json' (Node Audit Analyzer).
[WARN] An error occurred while analyzing 'D:\xxx\package-lock.json' (Node Audit Analyzer).
[INFO] Finished Node Audit Analyzer (24 seconds)
[INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
[INFO] Finished Dependency Bundling Analyzer (1 seconds)
[INFO] Analysis Complete (48 seconds)
[ERROR] Failed to read results from the NPM Audit API (NodeAuditAnalyzer); the analyzer is being disabled and may result in false negatives.
[ERROR] Failed to read results from the NPM Audit API (NodeAuditAnalyzer); the analyzer is being disabled and may result in false negatives.

Thanks & Regards,
Vaishnavi Ravindran

**Comment by jeremylong** [comment]
In reality - the node analysis is currently just using the exact same analysis as [npm audit](https://docs.npmjs.com/cli/audit). Unless you have a reason to use ODC (i.e. other technology stacks being scanned) I would recommend just using `npm audit`.  That being said - I believe some improvements have been made and are available in 5.0.0-M3. Note this is a milestone release.

**Comment by jeremylong** [comment]
Another improvement for node.js will be included in the next release.
