### ISSUE TITLE
im4java causes the maven report to fail

### ISSUE THREAD

**Issue by sellersj** [dependency-check/DependencyCheck#1898]
**Describe the bug**
Having the im4java dependency causes a failure
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 
           http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.example</groupId>
  <artifactId>Zminimal</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>jar</packaging>
  <dependencies>
    <dependency>
      <groupId>org.im4java</groupId>
      <artifactId>im4java</artifactId>
      <version>1.4.0</version>
    </dependency>
  </dependencies>
</project>
```
Running the command
```
mvn --batch-mode org.owasp:dependency-check-maven:4.0.2:check  org.owasp:dependency-check-maven:4.0.2:aggregate -Dformat=ALL -DskipProvidedScope=true -DautoUpdate=false -DnuspecAnalyzerEnabled=false -DassemblyAnalyzerEnabled=false -DnodeAuditAnalyzerEnabled=false -DnodeAnalyzerEnabled=false -DrubygemsAnalyzerEnabled=false -DbundleAuditAnalyzerEnabled=false
```

** Version of dependency-check used **
4.0.2 of the maven plugin

** Log file **
[ERROR] Failed to execute goal org.owasp:dependency-check-maven:4.0.2:check (default-cli) on project Zminimal: Execution default-cli of goal org.owasp:dependency-check-maven:4.0.2:check failed: Invocation of method 'getVulnerableSoftware' in  class org.owasp.dependencycheck.dependency.Vulnerability threw exception java.lang.IllegalArgumentException: Comparison method violates its general contract! at templates/htmlReport.vsl[line 902, column 23] -> [Help 1]

**To Reproduce**
1. Make a empty maven project
2. Add the above dependency
3. Run the command with the latest updated data

**Expected behavior**
This used to work. It could be new upstream error report is causing this to throw an exception now.

**Additional context**
None.

**Comment by jeremylong** [comment]
Try the 5.0.0-M3 milestone release please:
```
mvn --batch-mode org.owasp:dependency-check-maven:5.0.3-M3:check  org.owasp:dependency-check-maven:5.0.3-M3:aggregate -Dformat=ALL -DskipProvidedScope=true -DautoUpdate=false -DnuspecAnalyzerEnabled=false -DassemblyAnalyzerEnabled=false -DnodeAuditAnalyzerEnabled=false -DnodeAnalyzerEnabled=false -DrubygemsAnalyzerEnabled=false -DbundleAuditAnalyzerEnabled=false
```

**Comment by jeremylong** [comment]
I just verified that the 5.0.0-M3 milestone release does resolve this issue.

**Comment by sellersj** [comment]
That works for me too. Do you know an aprox timeline for when 5.0.0 will come out?

If you'd like, you can close this ticket or wait until the release. I am happy with either.

Thank you for your help.

**Comment by jeremylong** [comment]
5.0.0 will be out fairly soon.  The M3 release was what I believe to be the last stabilization release.  The only issue left is the Jenkins plugin.

**Comment by kumarchatla** [comment]
> Try the 5.0.0-M3 milestone release please:
> 
> ```
> mvn --batch-mode org.owasp:dependency-check-maven:5.0.3-M3:check  org.owasp:dependency-check-maven:5.0.3-M3:aggregate -Dformat=ALL -DskipProvidedScope=true -DautoUpdate=false -DnuspecAnalyzerEnabled=false -DassemblyAnalyzerEnabled=false -DnodeAuditAnalyzerEnabled=false -DnodeAnalyzerEnabled=false -DrubygemsAnalyzerEnabled=false -DbundleAuditAnalyzerEnabled=false
> ```

Is there a way we can add global suppression file to this command?
