### ISSUE TITLE
After configurate dependency check and rebuild but no vulnerability trend display

### ISSUE THREAD

**Issue by tiffanyzhou** [dependency-check/DependencyCheck#1899]
My Jenkins version is 2.150.1, and I configurate dependency check to my job, part of the jobs are show the vulnerability trend, but there are still a few jobs that don't show the vulnerability trend,even though a lot of vulnerabilities information are scanned. 
Can someone tell me why? thanks.

![image](https://user-images.githubusercontent.com/39646571/57347988-fca8fb80-7186-11e9-8179-41044dcbfa87.png)

![image](https://user-images.githubusercontent.com/39646571/57348055-3da11000-7187-11e9-9a8c-ebecfe71ba85.png)

The same configuration, other job can show the vulnerability trend as belows:

![image](https://user-images.githubusercontent.com/39646571/57348167-adaf9600-7187-11e9-8f2c-a428b7ecbbf6.png)

**Comment by stevespringett** [comment]
No idea. Analysis core (which is responsible for displaying trends and results) is no longer supported. So the issue will not be investigated. DC v5 is a rewrite of the publisher and removal of analysis core so this shouldn’t be an issue in v5.  See https://groups.google.com/d/msg/dependency-check/2yMe6-Tg8tU/53SCfThcBQAJ
