### ISSUE TITLE
Maven Plugin - report aggregation

### ISSUE THREAD

**Issue by jeremylong** [dependency-check/DependencyCheck#19]
Need to add aggregation capabilities to the Maven plugin.

**Comment by rlyons** [comment]
Awesome.  Already in your roadmap.  This is exactly the functionality I was looking for (aggregation).  Consider this comment to be a bump in interest :+1:

**Comment by herau** [comment]
+1

**Comment by jeremylong** [comment]
The changes to support report aggregation have been committed to 1.2.5-SNAPSHOT and will be released with the next version. This issue is considered closed.
