### ISSUE TITLE
Possible to suppress javascript pkg findings?

### ISSUE THREAD

**Issue by cdaller** [dependency-check/DependencyCheck#1903]
I get a finding on a dependency of a javascript library, which is not in use in production mode. So I want to suppress the finding.
But I have not yet found a way to set cve, cpe or cwe for the finding of the javascript package. The identifier of the package in the report is "pkg:javascript/handlebars.js@4.0.5".

![dependency_check_pkg](https://user-images.githubusercontent.com/1531978/57517245-b387b180-7316-11e9-8401-b00a8529c458.png)

**Comment by stevespringett** [comment]
Not possible at the moment. Refer to #892 for the enhancement request.

**Comment by thib3113** [comment]
the way I use on my side, is to exclude the file from the analyse with : 
`-exclude node_modules/taskgroup/docs/assets/biscotto.js --exclude node_modules/moment-duration-format/test/vendor/jquery.js` ( and repeat the `--exclude` )
