### ISSUE TITLE
Random failures on Travis and AppVeyor - Failed to request component-reports

### ISSUE THREAD

**Issue by adamretter** [dependency-check/DependencyCheck#1918]
**Describe the bug**
On Travis and AppVeyor - I am seeing my build fail on the Maven goal `org.owasp:dependency-check-maven:5.0.0-M3:check` with the error `Failed to request component-reports`. My build consists of 51 modules, and the module it fails on varies from build to build.

** Version of dependency-check used **
Maven plugin version 5.0.0-M3

** Log file **
```
[ERROR] Failed to execute goal org.owasp:dependency-check-maven:5.0.0-M3:check (default) on project exist-cache: One or more exceptions occurred during dependency-check analysis: One or more exceptions occurred during analysis:
[ERROR] 	Failed to request component-reports
[ERROR] -> [Help 1]
```

**To Reproduce**
Run the build here: https://travis-ci.com/eXist-db/exist/builds/111687162 or here https://ci.appveyor.com/project/AdamRetter/exist/builds/24526217/

**Expected behavior**
The plugin should work.

**Additional context**
Tried OpenJDK 8, 9, 10 and Oracle JDK 11.
Maven version 3.6.0

**Comment by rruizt** [comment]
Same here with Maven 3.5.4, OpenJDK 8 running on Jenkins

**Comment by adamretter** [comment]
@jeremylong So is this considered fixed in `5.0.0`? Our Travis and AppVeyor CI does seem to be passing now :-) Thanks

**Comment by malejpavouk** [comment]
we still experience this issue with 5.0.0 and gradle plugin

use case; I am running a battery of tests against our custom plugin (which applies DepCheck). Each test runs against new instance of project (there are dozens of them). It seems that the caching does not mitigate the issue for multi-project builds such as this.

**Comment by shark-horse** [comment]
Just ran into this today with 5.0.0 via the Maven plugin. Our project is a multi-module project, about 10 modules, but only one actually uses the dependency-check plugin.
1. We upgraded _and_ a new vulnerability was updated such that dependency-check reported it. 3 nightly builds worked as designed this way.
2. I updated our suppression file to suppress this one (we are not actually vulnerable).
3. Next build failed with `Failed to request component-reports` etc. Also, two consecutive builds from my machine failed the same way, but all builds thereafter (both machines) succeeded.

Does `Failed to request component-reports` indicate failure to fetch a resource that is then cached for future builds?

**Comment by jeremylong** [comment]
Failed to request component-reports indicates that there was an error obtaining information from the OSS Index. In several cases the OSS Index results will contain vulnerability information that is not contained in the NVD. However, if there is an error occurring in the OSS Index (i.e. returning a 500) there is very little we can do.  I know that there were some networking issues over the past few days that affected the Maven Central APIs hosted by Sonatype. These issues may have also affected Sonatype's OSS Index as well.

**Comment by adamretter** [comment]
@jeremylong Would it be possible to make the error message clearer, perhaps if we can detect an HTTP error code when requesting the OSS Index, we could also show that to the user and indicate that the problem is not with your plugin, but rather a network issue?
