### ISSUE TITLE
Clarifying CPE identifier generation

### ISSUE THREAD

**Issue by dominicfollett** [dependency-check/DependencyCheck#1920]
This is not a question about the Spec. I'd like to know if you have a README or other documentation that explains the weights of evidence you use to determine:

1. How the confidence level for the combination of attributes `Type`, `Source`, `Name` and `Value` is calculated.
2. How you construct the CPE identifier - which attribute values do you decide to use from the evidence for vendor,  version, product name etc.

I'd also like to know what kinds of lookup you do with the CPE identifier once you have created one. Do you:

1. Search the NIST product database?
2. Only search NVD for CVEs?

**Comment by jeremylong** [comment]
Please see https://jeremylong.github.io/DependencyCheck/general/internals.html. Does that answer your questions?

**Comment by dominicfollett** [comment]
Thanks, I've read this. I am looking for more information. Is there anything you'd recommend I look at, even a source file?

**Comment by jeremylong** [comment]
1. The confidence of each piece of evidence is determined by each analyzer that adds the evidence. For instance see: https://github.com/jeremylong/DependencyCheck/blob/f34b9425aa69e49ba15e71915533b9a805848057/core/src/main/java/org/owasp/dependencycheck/analyzer/JarAnalyzer.java#L605-L606

2. A Lucene index is generated that contains all of the vendor/product pairs. We use the evidence in each bucket (vendor or product) in Lucene queries to identify vendor/product matches.  If one is found then we utilize the version evidence to determine the version number to specify. See the CPEAnalyzer: https://github.com/jeremylong/DependencyCheck/blob/f34b9425aa69e49ba15e71915533b9a805848057/core/src/main/java/org/owasp/dependencycheck/analyzer/CPEAnalyzer.java#L249

3. We then use the identified CPE values to search the locally cached NVD data. See the NvdCveAnalyzer: https://github.com/jeremylong/DependencyCheck/blob/f34b9425aa69e49ba15e71915533b9a805848057/core/src/main/java/org/owasp/dependencycheck/analyzer/NvdCveAnalyzer.java#L53

We also use RetireJS, Node Audit, and OSS-Index Analyzers to identify vulnerabilities that may not be contained in the NVD.  In these cases we are basically wrapping someone else's tool/service. These are all found in the Analyzer package: https://github.com/jeremylong/DependencyCheck/tree/master/core/src/main/java/org/owasp/dependencycheck/analyzer

**Comment by dominicfollett** [comment]
Thanks!
