### ISSUE TITLE
CPE Confidence field wrongly populated in CSV for 5.0.0-M3

### ISSUE THREAD

**Issue by piyushml20** [dependency-check/DependencyCheck#1926]
CPE Confidence field is getting populated with 'pkg:maven/com.google.guava/guava@21.0' in CSV report. Issue is applicable to all the minor version of 5. Tested 5.0.0-M1, 5.0.0-M2, 5.0.0-M3 Maven plugin.

'pkg:maven/com.google.guava/guava@21.0' reflects "Build Coordinates" CSV field of version 4.x report which is missing in 5.x

**Comment by piyushml20** [comment]
Issue is applicable to all the minor version of 5.
Tested 5.0.0-M1, 5.0.0-M2, 5.0.0-M3

**Comment by piyushml20** [comment]
@jeremylong any particular reason to remove  "Build Coordinates" CSV field from v5.x
In my opinion that was good way of knowing exactly which JAR is vulnerable specially needed when we  have different GAV parameters for same JAR. I understand one can deduce value of GAV from "Identifiers" field but it needs some processing. As an example,  'pkg:maven/com.google.guava/guava@21.0' needs some processing whereas previous v4.x value of 'com.google.guava:guava:21.0' was much easy to consume.

**Comment by jeremylong** [comment]
In 5.0 we started using Package URL (see [purl-spec](https://github.com/package-url/purl-spec)). Dependency-check scans more than just JAR files and the GAV coordinates do not exist in other package managers.

**Comment by piyushml20** [comment]
Thanks, that makes sense.
