### ISSUE TITLE
Add support for suppressionURL (with default)

### ISSUE THREAD

**Issue by ST-DDT** [dependency-check/DependencyCheck#1928]
**The issue**

Currently false positives will only be updated/removed by newer releases of this plugin.

**Describe the solution you'd like**

It would be nice if the plugin would automatically try to fetch the latest suppression file from github or a different configurable source (proxy). This could be achieved by adding and using a `suppressionURL` (s) property that defaults to https://raw.githubusercontent.com/jeremylong/DependencyCheck/master/core/src/main/resources/dependencycheck-base-suppression.xml (?)

**Describe alternatives you've considered**

Manually share the suppression file with all developers (already possible but error-prone).

**Comment by jeremylong** [comment]
Pretty sure this is supported already.  Just put a full URL into the suppression file path.  Probably needs to be documented better.  

For another option see https://github.com/jeremylong/DependencyCheck/issues/1878

**Comment by ST-DDT** [comment]
I wasn't aware, that you can refer to URLs there already.

>  Probably needs to be documented better.

I would appreciate that. Thanks for your help.

**Comment by ST-DDT** [comment]
Please also update the javadocs for the `suppresionFIle`/`suppressionFiles` properties in [`BaseDependencyCheckMojo`](https://github.com/jeremylong/DependencyCheck/blob/master/maven/src/main/java/org/owasp/dependencycheck/maven/BaseDependencyCheckMojo.java#L270) as they will be converted to the help that will be displayed in IDEs.

![suppresionFile tooltip eclipse](https://user-images.githubusercontent.com/1579362/58106543-9097b000-7be8-11e9-8b79-e6cab91b2fc7.png)
