### ISSUE TITLE
Problem DependencyCheck in Jenkins

### ISSUE THREAD

**Issue by akravchenkov** [dependency-check/DependencyCheck#1930]
I'm trying to use the DependencyCheck plugin in Jenkins for the first time, I'm getting the below error. Thank You!

[DependencyCheck] Analyzing Dependencies
[DependencyCheck] One or more exceptions were thrown while executing Dependency-Check
[DependencyCheck] Exception Caught: org.owasp.dependencycheck.data.update.exception.UpdateException
[DependencyCheck] Message: The download was interrupted; unable to complete the update
[DependencyCheck] org.owasp.dependencycheck.data.update.exception.UpdateException: The download was interrupted; unable to complete the update
[DependencyCheck] 	at org.owasp.dependencycheck.data.update.NvdCveUpdater.performUpdate(NvdCveUpdater.java:274)
[DependencyCheck] 	at org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:119)
[DependencyCheck] 	at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:899)
[DependencyCheck] 	at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:716)
[DependencyCheck] 	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:642)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.executeDependencyCheck(DependencyCheckExecutor.java:172)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.call(DependencyCheckExecutor.java:103)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.call(DependencyCheckExecutor.java:46)
[DependencyCheck] 	at hudson.remoting.LocalChannel.call(LocalChannel.java:45)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.AbstractDependencyCheckBuilder.perform(AbstractDependencyCheckBuilder.java:85)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckBuilder.perform(DependencyCheckBuilder.java:206)
[DependencyCheck] 	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
[DependencyCheck] 	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
[DependencyCheck] 	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
[DependencyCheck] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[DependencyCheck] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[DependencyCheck] 	at java.lang.Thread.run(Thread.java:748)
[DependencyCheck] 
[DependencyCheck] Exception Caught: org.owasp.dependencycheck.exception.InitializationException
[DependencyCheck] Cause: /var/jenkins_home/workspace/Development/SharePointTestPipeline/dependency-check-data/jsrepository.json (No such file or directory)
[DependencyCheck] Message: Failed to initialize the RetireJS repo
[DependencyCheck] org.owasp.dependencycheck.exception.InitializationException: Failed to initialize the RetireJS repo
[DependencyCheck] 	at org.owasp.dependencycheck.analyzer.RetireJsAnalyzer.prepareFileTypeAnalyzer(RetireJsAnalyzer.java:178)
[DependencyCheck] 	at org.owasp.dependencycheck.analyzer.AbstractFileTypeAnalyzer.prepareAnalyzer(AbstractFileTypeAnalyzer.java:83)
[DependencyCheck] 	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.prepare(AbstractAnalyzer.java:107)
[DependencyCheck] 	at org.owasp.dependencycheck.Engine.initializeAnalyzer(Engine.java:825)
[DependencyCheck] 	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:662)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.executeDependencyCheck(DependencyCheckExecutor.java:172)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.call(DependencyCheckExecutor.java:103)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.call(DependencyCheckExecutor.java:46)
[DependencyCheck] 	at hudson.remoting.LocalChannel.call(LocalChannel.java:45)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.AbstractDependencyCheckBuilder.perform(AbstractDependencyCheckBuilder.java:85)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckBuilder.perform(DependencyCheckBuilder.java:206)
[DependencyCheck] 	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
[DependencyCheck] 	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
[DependencyCheck] 	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
[DependencyCheck] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[DependencyCheck] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[DependencyCheck] 	at java.lang.Thread.run(Thread.java:748)
[DependencyCheck] Caused by: java.io.FileNotFoundException: /var/jenkins_home/workspace/Development/SharePointTestPipeline/dependency-check-data/jsrepository.json (No such file or directory)
[DependencyCheck] 	at java.io.FileInputStream.open0(Native Method)
[DependencyCheck] 	at java.io.FileInputStream.open(FileInputStream.java:195)
[DependencyCheck] 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
[DependencyCheck] 	at org.owasp.dependencycheck.analyzer.RetireJsAnalyzer.prepareFileTypeAnalyzer(RetireJsAnalyzer.java:173)
[DependencyCheck] 	... 18 more
[DependencyCheck] 
[Pipeline] dependencyCheckPublisher

[DependencyCheck] Skipping publisher since build result is FAILURE

**Comment by stevespringett** [comment]
looks like a connectivity issue to me. Is there a proxy server in your environent? Does Jenkins (no the OS but Java itself) have access to the Internet?

**Comment by akravchenkov** [comment]
There is a proxy server and it is configured in Jenkins. Jenkins has internet access.
I added: true to the artifactoryUseProxy parameter and it all worked.
What is artifactoryUseProxy: true?
Thank!

**Comment by jeremylong** [comment]
The `artifactoryUseProxy` configuration only affects the `ArtifactoyAnalyzer` and should have no affect on the download of the NVD.

**Comment by akravchenkov** [comment]
Thank You!

**Comment by aljazglavac** [comment]
Hello, the  "solution" above, did not solve my problem. Are there any other alternatives/solution/things that i can try?
