### ISSUE TITLE
Junit report generation doesn't show skipped (suppressed) count

### ISSUE THREAD

**Issue by Bluexin** [dependency-check/DependencyCheck#1933]
**Describe the bug**
Junit report doesn't show the count for suppressed vulnerabilities.

**Version of dependency-check used**
Maven plugin v5.0.0-M3

**To Reproduce**
Files can be found in [this gist](https://gist.github.com/Bluexin/868546812e67ad39cfa732f187ac9486).
Use attached POM file, which includes a false positive (on `jwks-rsa-java`), suppressed trough the attached `dependency-checker-suppression.xml`.
Run dependency check (`mvn clean verify`).
Inspect resulting junit report (`target/dependency-check/dependency-check-junit.xml`).
See the missing `skipped` count in the report.

**Expected behavior**
The `skipped` attribute contains the suppressed count.

**Comment by jeremylong** [comment]
Thanks for the bug reports!
