### ISSUE TITLE
5.0.0-M3: HTML report can't be disabled with formats option in Maven plugin

### ISSUE THREAD

**Issue by albuch** [dependency-check/DependencyCheck#1934]
**Describe the bug**
With the new option of defining multiple report `formats` there is no way to disable the default HTML report set for `format`.

**Version of dependency-check used**
5.0.0-M3

**To Reproduce**
```
		<plugin>
		  <groupId>org.owasp</groupId>
		  <artifactId>dependency-check-maven</artifactId>
		  <version>5.0.0-M3</version>
		  <configuration>
			<formats>
				<format>JSON</format>
			</formats>
		  </configuration>
		  <executions>
			  <execution>
				  <goals>
					  <goal>check</goal>
				  </goals>
			  </execution>
		  </executions>
		</plugin>
```

**Expected behavior**
Only JSON report is generated.

**Actual behaviour**
JSON and HTML report are generated.

**Aditional context**
There is an awkward workaround by setting one of the formats from `formats` as the value for `format`. But I think this is not intuitive and cumbersome. 
```
 <configuration>
       <format>JSON</format>
	<formats>
		<format>JSON</format>
                 <format>JUNIT</format>
	</formats>
</configuration>
```

**Comment by jeremylong** [comment]
Thanks for the PR!
