### ISSUE TITLE
5.0.0-M3: HTML report Vulnerable Software & Versions not displayed properly

### ISSUE THREAD

**Issue by albuch** [dependency-check/DependencyCheck#1937]
**Describe the bug**
The Vulnerable Software & Versions string is not properly generated. It is always displayed with the string
```
* $enc.html($vuln.matchedVulnerableSoftware.toString())
* ...
```
See https://gist.github.com/albuch/2186cb4885e296d859ad0d1d4efa4e23 

If the list can be opened the uncollapsed list is displayed correctly.

**Version of dependency-check used**
5.0.0-M3

**To Reproduce**
1. Create HTML report for at least one vulnerable dependency

**Expected behavior**
Correctly displayed Vulnerable Software & Versions

**Comment by jeremylong** [comment]
Thanks for pointing this out!  This appears to mainly affect findings from the RetireJS analyzer.
