### ISSUE TITLE
CPEAnalyzer fails to identify products with "-" in product name

### ISSUE THREAD

**Issue by jpstotz** [dependency-check/DependencyCheck#1942]
**Version of dependency-check used**
Version 5.0.0-M3 using dependency-check-core

**Describe the bug**
All entries in the CPE database that contain the character "`-`" can not be resolved by the `CPEAnalyzer`.
_Edit: I noticed that there is a second factor that has to be fulfilled to trigger this bug: The "word" before or after the `-` has to be of length one or two._

I created for example a dependency for an artifact with:
`groupId=zeroturnaround`
`artifactId=zt-zip`.

The CPEAnalyzer therefore searches for `vendor search: {zeroturnaround=1}` and `product search: {zt-zip=1}`. 

I checked the database and the CPE table has the following entry:
    
    ID        PART     VENDOR            PRODUCT       VERSION ...
    156896    a        zeroturnaround    zt-zip        *        

However the log I can see that in the end no CPE was identified.

**Log file**
```
[DEBUG] vendor search: {zeroturnaround=1}
[DEBUG] product search: {zt-zip=1}
[DEBUG] vendor search: {zeroturnaround=1}
[DEBUG] product search: {zt-zip=1}
[DEBUG] vendor search: {zeroturnaround=1}
[DEBUG] product search: {zt-zip=1}
[DEBUG] vendor search: {zeroturnaround=1}
[DEBUG] product search: {zt-zip=1}
```

**To Reproduce**
```
    Logger cpeLogger = (Logger) LoggerFactory.getLogger(CPEAnalyzer.class);
    cpeLogger.setLevel(Level.DEBUG);

    try (Engine engine = new Engine(new Settings())) {

        Dependency dependency = new Dependency(true);
        dependency.addEvidence(EvidenceType.VENDOR, "", "groupid", "zeroturnaround", Confidence.HIGHEST);
        dependency.addEvidence(EvidenceType.PRODUCT, "", "artifactid", "zt-zip", Confidence.HIGHEST);
        dependency.addEvidence(EvidenceType.VERSION, "", "version", "1.0.0", Confidence.HIGHEST);

        for (Analyzer a : engine.getAnalyzers()) {
            AbstractAnalyzer aa = (AbstractAnalyzer) a;
            if (!(aa instanceof CPEAnalyzer)) {
                aa.setEnabled(false);
            }
        }
        engine.addDependency(dependency);
        engine.analyzeDependencies();

        if (dependency.getVulnerableSoftwareIdentifiers().size() == 0) {
            System.err.println("No CPE found -> BUG!");
        } else {
            System.out.println("CPE(s) found: " + dependency.getVulnerableSoftwareIdentifiers());
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
```

**Expected behavior**

**Additional context**
I tried to debug this problem and found out that the entry is correctly loaded from database, however method `verifyEntry` fails.

**Comment by jpstotz** [comment]
Looks like this bug is already foreseen in a TODO code comment:
https://github.com/jeremylong/DependencyCheck/blob/7b472e5ca269d895756dd83c85aca75db05def59/core/src/main/java/org/owasp/dependencycheck/analyzer/CPEAnalyzer.java#L608-L609

**Comment by jeremylong** [comment]
Thanks for the PR!
