### ISSUE TITLE
Invalid 'out' argument with multiple formats

### ISSUE THREAD

**Issue by maartengo** [dependency-check/DependencyCheck#1943]
**Describtion**
When running the scanner with multiple formats (e.g. HTML and XML) the scanner will throw the following error: "Invalid 'out' argument: 'C:\ExampleDir\'". This only happens when called with two -f parameters and one --out parameter.

** Version of dependency-check used **
The problem occurs using version v5.0.0-M3 of the the cli

** Error **
Invalid 'out' argument: 'D:\1\_work\129\s/DependencyCheckReports/'
usage: Dependency-Check Core [--advancedHelp] [--cveValidForHours <hours>]
       [--enableExperimental] [--enableRetired] [--exclude <pattern>] [-f
       <format>] [--failOnCVSS <score>] [-h] [--hints <file>]
       [--junitFailOnCVSS] [-l <file>] [-n] [-o <path>] [-P <file>]
       [--project <name>] [-s <path>] [--suppression <file>] [--symLink
       <depth>] [-v]

**To Reproduce**
Call the scanner in the following way:
dependency-check.bat -f HTML -f XML --scan Folder --out $(System.DefaultWorkingDirectory)/DependencyCheckReports/ --project Project --noupdate --enableExperimental

**Expected behavior**
Both XML and HTML are generated as expected when only given a single -f parameter, but run twice (once with -f XML, the second time with -f HTML).

**Comment by jeremylong** [comment]
This error message occurs when the specified directory does not exist. I've updated the error messages (and added an attempt to create the output directory if it does not exist).
