### ISSUE TITLE
How to check npm audit via Jenkins plugin?

### ISSUE THREAD

**Issue by OrangeDog** [dependency-check/DependencyCheck#1958]
I've got a NodeJS project and I was trying to write a Jenkinsfile to check the dependencies.
Both `package.json` and `package-lock.json` are checked in.

I tried this, but the resulting xml has an empty list of dependencies.
I also tried without specifying the `scanpath`, then the depenency list was all of my source files, and none of the actual dependencies.

```groovy
pipeline {
  agent any
  tools { nodejs 'v10.15.3' }
  stages {
    stage('Audit') {
      dependencyCheckAnalyzer scanpath: '${WORKSPACE}/package-lock.json',
                              datadir: '/home/jenkins/.m2/repository/org/owasp/dependency-check-data/3.0/',
                              outdir: '', suppressionFile: '', hintsFile: '', zipExtensions: '',
                              isAutoupdateDisabled: false, includeHtmlReports: false,
                              includeVulnReports: false, includeJsonReports: false, includeCsvReports: false,
                              skipOnScmChange: false, skipOnUpstreamChange: false
      dependencyCheckPublisher unstableTotalAll: '0'
    }
}
```
Plugin version is 4.0.2.

**Comment by stevespringett** [comment]
Scanpath is not necessary as it will default to ${WORKSPACE} if not specified.

That's an interesting place for datadir. I would not advise that location as the data thats stored in thge datadir has nothing to do with Maven.

Ensure that the NPM Audit analyzer is enabled in the Jenkins global configuration.

**Comment by OrangeDog** [comment]
> Scanpath is not necessary

As I said, with the default it includes all the source files as "dependencies", and nothing from package-lock.

> That's an interesting place for datadir

Most other builds are using the maven plugin. This is an easy way to save space on copies of the database.

> Ensure that the NPM Audit analyzer is enabled

It is, yes.

**Comment by OrangeDog** [comment]
Was a Groovy error. Using single quotes means that `${WORKSPACE}` is not expanded.
🤦‍♂

**Comment by jblamotte** [comment]
No need to specify the scanpath in my case.

Working syntax :

```groovy
  stages {
    stage('dtrack') {
      steps {
        dependencyCheckAnalyzer datadir: '/a/path/to/store/jsrepository', hintsFile: '', includeCsvReports: true, includeHtmlReports: true, includeJsonReports: true, includeVulnReports: true, isAutoupdateDisabled: false, outdir: '', scanpath: '', skipOnScmChange: false, skipOnUpstreamChange: false, suppressionFile: '', zipExtensions: ''
      }
    }
```
