### ISSUE TITLE
Is the project still using SonarCloud? Are fixes for issues welcome?

### ISSUE THREAD

**Issue by dvmarcilio** [dependency-check/DependencyCheck#1963]
Hello,

I found the project in SonarCloud (https://sonarcloud.io/project/issues?id=org.owasp%3Adependency-check-parent&resolved=false). My first question would be if it's still in use.

If yes, I'm willing to submit pull requests with fixes for some kind of issues. Is that something of interest for the project?

Thank you!

**Comment by jeremylong** [comment]
I'll be honest that I obviously haven't spent a lot of time looking at SonarCloud since it was setup; I have spent more time on [codacy](https://app.codacy.com/project/OWASP_Reviews/DependencyCheck/dashboard). 

That being said - PRs are always welcome.

**Comment by dvmarcilio** [comment]
Thanks! I will submit some pull requests so we can debate their usefulness.
