### ISSUE TITLE
Version 4.0.2 can not download NVD

### ISSUE THREAD

**Issue by emartynov** [dependency-check/DependencyCheck#1970]
**Describe the bug**
I constantly see the next messages:

```
An exception occurred downloading NVD CVE - 2008
Some CVEs may not be reported.
```

** Version of dependency-check used **
The problem occurs using version 4.0.2 of the gradle plugin.

** Log file **
https://gist.github.com/emartynov/73291c24c2fb8e09e8c2f9aa69941ac2

**Comment by mprins** [comment]
seems pretty clear from your log that this is a problem connecting to https://nvd.nist.gov/ and not a bug

**Comment by jeremylong** [comment]
The entire downloading of the NVD has been re-written for the soon to be published 5.0.0. The NVD has changed their rate limiting.  You can try the 5.0.0-M3 milestone release to see the changes - or wait hopefully less then a week for the 5.0.0 release.

**Comment by superjulius** [comment]
I also faced the download issue with the CLI 4.0.1

Download issue seems to be related to the concurrent downloads performed. See https://github.com/jeremylong/DependencyCheck/issues/1558

I installed latest CLI 5.0.0-M3 which fixed the problem for me (limit the concurrent download to 2)

**Comment by emartynov** [comment]
We have 60 modules in the app. Probably all of them are trying to download files that might make things complicated.

**Comment by jeremylong** [comment]
@emartynov if the 60 modules are all in a single build - there should be no issue as the update process use a lock and waits to make sure only one instance of ODC is updating the database at a time.
