### ISSUE TITLE
Errors while building dependency check code

### ISSUE THREAD

**Issue by niddhig** [dependency-check/DependencyCheck#1972]
Hi,

I have download the dependency-check code from github and i am trying to build it, but the test cases are failing. Skipping the test cases while building also isn't helping as the artifact created by it is being used in another module.

Here is the test case failure i am getting:
[ERROR] Tests run: 6, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.679 s <<< FAILURE! - in org.owasp.dependencycheck.analyzer.CPEAnalyzerIT
[ERROR] testDetermineCPE_full(org.owasp.dependencycheck.analyzer.CPEAnalyzerIT)  Time elapsed: 0.036 s  <<< ERROR!
java.lang.StringIndexOutOfBoundsException: String index out of range: -7
	at org.owasp.dependencycheck.analyzer.CPEAnalyzerIT.testDetermineCPE_full(CPEAnalyzerIT.java:85)

[INFO] Running org.owasp.dependencycheck.analyzer.DependencyBundlingAnalyzerIT
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in org.owasp.dependencycheck.analyzer.DependencyBundlingAnalyzerIT
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   EngineModeIT.testEvidenceCollectionAndEvidenceProcessingModes:100 » StringIndexOutOfBounds
[ERROR]   EngineModeIT.testStandaloneMode:116 » StringIndexOutOfBounds String index out ...
[ERROR]   DependencyCheckScanAgentIT.testComponentMetadata:50 » StringIndexOutOfBounds S...
[ERROR]   CPEAnalyzerIT.testDetermineCPE_full:85 » StringIndexOutOfBounds String index o...
[ERROR]   RubyBundleAuditAnalyzerIT.testAddCriticalityToVulnerability:153 » StringIndexOutOfBounds
[ERROR]   RubyBundleAuditAnalyzerIT.testDependenciesPath:204 » StringIndexOutOfBounds St...
[INFO] 
[ERROR] Tests run: 56, Failures: 0, Errors: 6, Skipped: 2
[INFO] 
[INFO] 

I got an exception before in test case in Utils module before. I added the @ignore annotation to it to get past it and to build the code. Now i am getting the above exception.

If i run the test case individually then it passes, but as part of the build process, it fails.

Any help is appreciated. 

Thanks!

**Comment by jeremylong** [comment]
Are you behind a proxy?  One of the things I have done is mirror the NVD locally and then updated my settings.xml:

```xml
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                          https://maven.apache.org/xsd/settings-1.0.0.xsd">
    <profiles>
        <profile>
            <id>default</id>
            <properties>
                <odc.cve.url.base>file:///Users/jeremy/nvd/nvdcve-1.0-%d.json.gz</odc.cve.url.base>
                <odc.cve.url.modified>file:///Users/jeremy/nvd/nvdcve-1.0-modified.json.gz</odc.cve.url.modified>
            </properties>
        </profile>
    </profiles>
    <activeProfiles>
        <activeProfile>default</activeProfile>
    </activeProfiles>
</settings>
```

**Comment by niddhig** [comment]
Hi, Thanks for the quick response. I am not behind any proxy. Besides, running the test classes or test cases individually is working fine. Its only at the build time, they are failing.

Thanks,
Niddhi

**Comment by jeremylong** [comment]
What version of maven and java are you using?  Are you building in an IDE or command line?
