### ISSUE TITLE
Cannot suppress OSSINDEX findings

### ISSUE THREAD

**Issue by Quiark** [dependency-check/DependencyCheck#1973]
In version 5, vulnerabilities from OSSINDEX were added but there seems to be no way to suppress these entries.

**Describe the solution you'd like**
If there is a way to suppress, the HTML report should have the button that shows how to do it, just like the NVD ones.

**Comment by stevespringett** [comment]
Related to: #892

**Comment by emartynov** [comment]
So what can I do to suppress it now?

**Comment by emartynov** [comment]
Or I should not update to 5.x until it is fixed?

**Comment by jeremylong** [comment]
Currently there is no capability to suppress some of the OSS Index findings. We will try and get to the issue soon.  The downside is that some of the 4.x users have been reporting issues updating the database - this issue was resolved in 5.0.0.

**Comment by emartynov** [comment]
Clear, appreciate your hard work. Actually, we are users that have the download issue with 4.x :)
