### ISSUE TITLE
Jenkinsfile: Temp folder + debug logging in a docker slave?

### ISSUE THREAD

**Issue by MJoeWatson** [dependency-check/DependencyCheck#1974]
I currently have a Jenkinsfile which will trigger the dependency checks to run within a docker container slave (completely ephemeral). 

1. I found that when I changed the temporary folder the 'dependencyCheckUpdateOnly' would work, but.. only once. It would then break after the first time when you rebuild that specific Jenkins job. It would log:
`Unable to update the Dependency-Check database`

2. I would like to enable debug logging so that I can look into this problem. I've noticed people saying that the logger can look for 'org.owasp' however I'm not sure how you can enable debug logging in the first place through the Jenkinsfile.

Question:

1. Is it possible to get the dependency checker working through ephemeral docker containers? It seems like there is some saved state/ cache on the master (the only thing I can think of). In case you are wondering, I have tried a centralised database, but had similar issues.

2. Can you enable the debug logs through the Jenkinsfile? If not, what are the alternatives? 

Thanks!

**Comment by jeremylong** [comment]
Can you share the command you have in your `Jenkinsfile` that executes dependency-check?

**Comment by MJoeWatson** [comment]
Thanks for responding so quickly. Config w. Output (dependencyCheckUpdateOnly) and Jenkinsfile:

https://gist.github.com/MattWatson-/11b3686d6d4e4fb6332cd32f5e6de0b3

**Comment by MattWatson-** [comment]
Thanks for responding so quickly. Config and Jenkinsfile:

<script src="https://gist.github.com/MattWatson-/11b3686d6d4e4fb6332cd32f5e6de0b3.js"></script>

**Comment by jeremylong** [comment]
As to configuring the logging levels for ODC - see https://support.cloudbees.com/hc/en-us/articles/115002626172-Configure-Loggers-for-Jenkins.

**Comment by MattWatson-** [comment]
> As to configuring the logging levels for ODC - see https://support.cloudbees.com/hc/en-us/articles/115002626172-Configure-Loggers-for-Jenkins.

Unfortunately I've already attempted this, but with no success. No debug information is revealed.
![image](https://user-images.githubusercontent.com/7837615/59032496-b7034f80-8866-11e9-98d4-79402a9155af.png)

**Comment by MJoeWatson** [comment]
So it seems like many of the CVEs are being downloaded apart from some recent ones. 

https://gist.github.com/MattWatson-/d0fca76e23e0e86de45b2113e4028019

**Comment by MJoeWatson** [comment]
It seems to be a rate limit problem, do you think that's the case?

**Comment by MJoeWatson** [comment]
Confirmed. It was an issue with rate limiting. Created a mirror and then I could just use that without any issues
