### ISSUE TITLE
Support Basic Auth for NVD Mirror Urls

### ISSUE THREAD

**Issue by devtribe** [dependency-check/DependencyCheck#1977]
If i'm using an url like this `https://username:password@someMirror.com/nist-data-mirror/nvdcve-1.0-modified.json.gz` i'm getting a `[org.owasp.dependencycheck.utils.HttpResourceConnection] IO Exception connecting to`.
In the Debug Log there is the info that it's an 401 Unauthorized.

We need a way to authorize not only for a proxy, but also for a mirror.

**Comment by jeremylong** [comment]
Sorry for the delayed response - but this should already exist.  On the cli you can specify the `--proxypass` and `--proxyuser` (see [the configuration documentation](https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html)).  There is a similar configuration for the other ODC interfaces (maven, gradle, ant, etc.).

Does that work?

**Comment by artursmolarek** [comment]
I can confirm the same problem when I am using mvn package with the following configuration:

```
<plugin>
  <groupId>org.owasp</groupId>
  <artifactId>dependency-check-maven</artifactId>
  <version>5.2.2</version>
  <configuration>
    <cveValidForHours>0</cveValidForHours>
    <cveUrlBase>https://username:password@mirror.url/nvdcve-1.0-%d.json.gz</cveUrlBase>
    <cveUrlModified>https://username:password@mirror.url/nvdcve-1.0-modified.json.gz</cveUrlModified>
  </configuration>
  <executions>
    <execution>
      <goals>
        <goal>check</goal>
      </goals>
    </execution>
  </executions>
</plugin>
```

```
Caused by: org.owasp.dependencycheck.utils.DownloadFailedException: Error retrieving https://username:password@mirror.url/nvdcve-1.0-modified.meta; received response code 401.
```

```
$ curl https://username:password@mirror.url/nvdcve-1.0-modified.meta
lastModifiedDate:2019-09-25T20:02:25-04:00
size:8633018
zipSize:379246
gzSize:379102
sha256:40F563316124B2D3484F90E1D6ABFF495E03AE85CED7A611975609A8EF883834
```

**Comment by jeremylong** [comment]
@artursmolarek When configuring the Maven plugin - consider using the settings.xml to store the proxy credentials: https://maven.apache.org/guides/mini/guide-proxies.html

Then in plugin configuration specify the `mavenSettingsProxyId`.

**Comment by bernermic** [comment]
I too tried the basic-auth way, which is not working. Finding this thread I tried to set proxyuser & proxypassword. But result stays the same.

```
dependencyCheck {
        cve {
        urlModified = "https://mirror.url/nvdcve-1.1-modified.json.gz"
        urlBase = "https://mirror.url/nvdcve-1.1-%d.json.gz"
    }
    proxy {
        username = "mirror-user"
        password = "mirror-password"
    }
}
```


Leads to `[org.owasp.dependencycheck.utils.HttpResourceConnection] Error retrieving https://mirror.url/nvdcve-1.1-modified.meta; received response code 401.`

Curl request against my mirror works as described above.
```
curl -I https://mirror-user:mirror-password@mirror.url/nvdcve-1.1-modified.json.gz
HTTP/1.1 200 OK
```

**Comment by vdotjansen** [comment]
@jeremylong I have added a pull request for this enhancement, could you have a quick look.

@devtribe, @artursmolarek & @bernermic could you test if my enhancement also works for your situations?
