### ISSUE TITLE
v5 estimated release date

### ISSUE THREAD

**Issue by CarlInglis** [dependency-check/DependencyCheck#1978]
Hi, I was wondering if there's any estimated release date for v5. 

We've been hit by the throttling issue that's cropped up and I'm currently investigating the mirroring approach as suggested in other threads. However if the new release is due in the next couple of weeks it'll be difficult for me to justify spending time implementing the mirroring approach, especially since we already use a central database approach to reduce our bandwidth usage.

Thanks in advance for any info you can give.

**Comment by jeremylong** [comment]
I'm literally trying to finalize the release - but I've had some other issues consuming my time.  I really hope that I will be able to push 5.0.0 this weekend.

**Comment by jeremylong** [comment]
We released 5.0.0 today.
