### ISSUE TITLE
Jenkins plugin v5.0.0

### ISSUE THREAD

**Issue by javixeneize** [dependency-check/DependencyCheck#1980]
Hi

I have seen that the new version of dependency check uses Sonatype OSS, which is a great addition.

Any indication on when this new version of the Jenkins plugin is going to be released with that improvement?

Thanks

**Comment by jeremylong** [comment]
I'm hoping we can have time to work on the Jenkins plugin soon (PRs are welcome). However, you can use the maven or gradle plugins and generate the new JUNIT report format and publish the report to track and visualize any findings. Note - you will get better results using the maven or gradle plugin (or SBT plugin) as opposed to using the CLI, Ant, or Jenkins plugins to scan.

**Comment by stevespringett** [comment]
Jenkins plugin is likely a few weeks away and is not backward compatible.

Refer to https://groups.google.com/d/msg/dependency-check/2yMe6-Tg8tU/53SCfThcBQAJ

**Comment by stevespringett** [comment]
v5.0.0 Released
https://groups.google.com/d/msg/dependency-check/A0FaSpuXDlk/Z1jO3wSmAwAJ

Background info
https://groups.google.com/d/msg/dependency-check/Gab2ZpmTptU/BbqVkufkCAAJ
