### ISSUE TITLE
Jenkins Plugin 5.0.0 not yet published

### ISSUE THREAD

**Issue by pmehtaupgrade** [dependency-check/DependencyCheck#1982]
**Describe the bug**
We updated dependency check maven plugin to version 5.0.0 this morning and ever since in the dependency check results, we see following -
**Severity:** Low for all the issues, even the once that should have CVSS of >=7
**CVSS:** score 0.0 for all the issues reported.
**CWE:** "-" for all the issues reported.

** Version of dependency-check used **
The problem occurs using version 5.0.0 of the the  maven plugin.

**To Reproduce**
1. Run dependency check scan
2. go to 'Dependency-Check Vulnerabilities'
3.  Click on 'Overview' tab
4. See missing/incorrect values for Severity/CVSS/CWE

**Expected behavior**
Correct values for Severity/CVSS/CWE

**Additional context**
Had the same issue with the milestone(5.0.0-M3) version as well, it was working as expected earlier to that.

**Comment by albuch** [comment]
Quoting @stevespringett from the mailing list (assuming you are using Jenkins plugin from the steps to reproduce):

> If you’re using Dependency-Check maven plugin v5 and using it with the current version of the Jenkins plugin (v4.x), it likely will not work, or work really poorly.
> 
> The XML schema between versions 1.x and 4.x didn’t change all that much - only minor things here and there. Major changes to the XML schema were introduced in Dependency-Check v5. So the Jenkins plugin v4.x and lower will not be able to properly read XML reports from Dependency-Check v5.
> 
> V5 of the Jenkins plugin will also not be able to read reports generated from previous versions of Dependency-Check. It’s not backward compatible, and like Dependency-Check v5 itself, has breaking changes.
> 
> V5 of the Jenkins plugin normalizes severity to Critical, High, Medium, Low, and Unassigned and will no longer focus on CVSS scores. Findings from Retire.js often do not include CVSS scores and NPM removed all CVSS scores from their API shortly after they acquired NSP. For findings that do have CVSS scores, CVSSv2 and CVSSv3 scores will be displayed in the UI, just not in a sortable way.

**Comment by stevespringett** [comment]
v5.0.0 Released
https://groups.google.com/d/msg/dependency-check/A0FaSpuXDlk/Z1jO3wSmAwAJ

Background info
https://groups.google.com/d/msg/dependency-check/Gab2ZpmTptU/BbqVkufkCAAJ
