### ISSUE TITLE
MySQL Database Query Errors

### ISSUE THREAD

**Issue by CarlInglis** [dependency-check/DependencyCheck#1983]
**Describe the bug**
An error is reported:
```
02:05:36  [INFO] Begin database maintenance
02:05:36  [ERROR] An unexpected SQL Exception occurred; please see the verbose log for more details.
```

**Version of dependency-check used**
5.0.0
DB: MySQL 5.6 on AWS RDS

**Log file**
```
2019-06-11 01:05:25,419 org.owasp.dependencycheck.data.nvdcve.CveDB:1483
INFO  - Begin database maintenance
2019-06-11 01:05:25,432 org.owasp.dependencycheck.data.nvdcve.CveDB:1498
ERROR - An unexpected SQL Exception occurred; please see the verbose log for more details.
2019-06-11 01:05:25,436 org.owasp.dependencycheck.data.nvdcve.CveDB:1499
DEBUG -
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'dependencycheck.CPEENTRY' doesn't exist
```

**Additional context**
I suspect this is a case sensitive tablenames issue.

"In MySQL, databases correspond to directories within the data directory. Each table within a database corresponds to at least one file within the database directory (and possibly more, depending on the storage engine). Triggers also correspond to files. Consequently, the case sensitivity of the underlying operating system plays a part in the case sensitivity of database, table, and trigger names. This means such names are not case-sensitive in Windows, but are case-sensitive in most varieties of Unix. " 
https://dev.mysql.com/doc/refman/5.6/en/identifier-case-sensitivity.html

I am going to try a parameter change on the RDS instance. If that works I'll update this ticket and close it so the information is retained for others.

**Comment by jeremylong** [comment]
Sorry about that.  The external databases were apparently not tested enough. We will be releasing a fix shortly.  In the meantime I updated the offending query so that if you wanted to build from source and test the fix you can.

```sql
UPDATE_ECOSYSTEM=UPDATE cpeEntry u SET u.ecosystem = (SELECT q.eco FROM cpeEntry e INNER JOIN (SELECT DISTINCT vendor, product, MIN(ecosystem) eco FROM cpeEntry WHERE ecosystem is not null GROUP BY vendor, product) q ON q.vendor = e.vendor AND q.product = e.product AND e.id = u.id) WHERE exists (SELECT * FROM cpeEntry e INNER JOIN (SELECT DISTINCT vendor, product, MIN(ecosystem) eco FROM cpeEntry WHERE ecosystem is not null GROUP BY vendor, product) q ON q.vendor = e.vendor AND q.product = e.product AND e.id = u.id) AND u.ecosystem is null
```

**Comment by CarlInglis** [comment]
Setting the RDS parameter got us past this error.

**Process**
1 - rename the tables from mixed case to all lower case
2 - modify the RDS parameter group attached to your DB (you may need to create a new one) to set the `lower_case_table_names ` parameter to `1`.

**Comment by CarlInglis** [comment]
@jeremylong No worries - I've got a fix for now (as above). I'll wait for the next release. :)

**Comment by CarlInglis** [comment]
@jeremylong Unfortunately I'm now getting 
```
INFO  - Begin database maintenance
2019-06-11 10:30:08,470 org.owasp.dependencycheck.data.nvdcve.CveDB:1498
ERROR - An unexpected SQL Exception occurred; please see the verbose log for more details.
2019-06-11 10:30:08,472 org.owasp.dependencycheck.data.nvdcve.CveDB:1499
DEBUG - 
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'u.id' in 'on clause'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
```
Do you want a new ticket for this?

**Comment by jeremylong** [comment]
no- I'll continue working off of this ticket.  Sorry for any inconvenience.

**Comment by jeremylong** [comment]
I am seeking help fixing one of the SQL update statements.  We have a fairly complicated update that we have been able to get to work in postgres, oracle, and H2.

```sql
UPDATE cpeEntry 
SET ecosystem = (SELECT q.eco
        FROM cpeEntry e INNER JOIN
            (SELECT DISTINCT vendor, product, MIN(ecosystem) eco
				FROM cpeEntry
				WHERE ecosystem IS NOT NULL
				GROUP BY vendor, product) q 
            ON q.vendor = e.vendor
                AND q.product = e.product
                AND e.id = cpeEntry.id)
WHERE EXISTS(SELECT * FROM cpeEntry e INNER JOIN
            (SELECT DISTINCT vendor, product, MIN(ecosystem) eco
            FROM cpeEntry
            WHERE ecosystem IS NOT NULL
            GROUP BY vendor , product) q ON q.vendor = e.vendor
                AND q.product = e.product
                AND e.id = cpeEntry.id)
        AND cpeEntry.ecosystem IS NULL	
```

The above update statement currently has the following error:
> Error Code: 1054. Unknown column 'cpeEntry.id' in 'on clause'

The purpose of the update is that if we have:

|Vendor|Product|Ecosystem|
|-------|--------|-----------|
|owasp|odc       |java            |
|owasp|odc       |java            |
|owasp|odc       |[null]            |

Running the above update would cause the last row's ecosystem to be updated to `java`.

**Comment by CarlInglis** [comment]
Removing "cpeEntry" from "cpeEntry.id" seems to resolve the specific issue, but I then get 

```
ERROR 1093 (HY000): You can't specify target table 'cpeEntry' for update in FROM clause
```

"You cannot update a table and select from the same table in a subquery. " - https://dev.mysql.com/doc/refman/5.6/en/update.html

https://stackoverflow.com/questions/45494/mysql-error-1093-cant-specify-target-table-for-update-in-from-clause gives some suggestions which I'll look at as soon as I get some time.

**Comment by CarlInglis** [comment]
I've tried the suggestion in the StackOverflow (nesting the query) and I'm still getting the same error. The other possibility suggested is to create temporary tables but that would require code changes.

**Comment by jeremylong** [comment]
The following appears to work:

```sql
SET SQL_SAFE_UPDATES = 0;
UPDATE cpeEntry n INNER JOIN
    (SELECT DISTINCT vendor, product, MIN(ecosystem) eco
    FROM cpeEntry
    WHERE ecosystem IS NOT NULL
    GROUP BY vendor , product) e 
  ON e.vendor = n.vendor
  AND e.product = n.product 
SET n.ecosystem = e.eco
WHERE n.ecosystem IS NULL;
SET SQL_SAFE_UPDATES = 1;
```
