### ISSUE TITLE
dependency-check-5.0.0-release.zip Bad signature

### ISSUE THREAD

**Issue by goldzahn** [dependency-check/DependencyCheck#1985]
Hi,
I can't verify the signature of the current release. Verifying older releases has never been a problem.

# gpg -v  --verify dependency-check-5.0.0-release.zip.asc dependency-check-5.0.0-release.zip
gpg: Signature made Sun Jun  9 14:20:47 2019 CEST using RSA key ID EA37F9A6
gpg: using PGP trust model
gpg: BAD signature from "Jeremy Long <jeremy.long@gmail.com>"
gpg: binary signature, digest algorithm SHA256

sha256sum dependency-check-5.0.0-release.zip
7127af1b57ad9c47b94339467185aedcc074a3be9c43a3f6eddc7defdcb08e8e

sha256sum dependency-check-5.0.0-release.zip.asc
b1b55b818c59260fe07c4770e814311644ad68d4501f62a83b7bedb8811cd256

# gpg -v  --verify dependency-check-4.0.2-release.zip.asc dependency-check-4.0.2-release.zip
gpg: Signature made Tue Jan  1 16:19:07 2019 CET using RSA key ID EA37F9A6
gpg: using PGP trust model
gpg: Good signature from "Jeremy Long <jeremy.long@gmail.com>"

Primary key fingerprint: F951 4E84 AE37 0828 8374  BBBE 0975 86CF EA37 F9A6
gpg: binary signature, digest algorithm SHA256

Regards

**Comment by Kampfmoehre** [comment]
I have the same problem, I am building my own docker image with dependency check:
```
ADD https://bintray.com/jeremy-long/owasp/download_file?file_path=dependency-check-${DEPENDENCY_CHECK_VERSION}-release.zip /tmp/dependency-check.zip
ADD https://bintray.com/jeremy-long/owasp/download_file?file_path=dependency-check-${DEPENDENCY_CHECK_VERSION}-release.zip.asc /tmp/dependency-check.zip.asc
RUN apk add --no-cache ca-certificates gnupg nodejs nodejs-npm python2 make gcc g++ && \
  gpg --keyserver hkp://keys.gnupg.net --recv-keys F9514E84AE3708288374BBBE097586CFEA37F9A6 && \
gpg --verify /tmp/dependency-check.zip.asc
```

This gives me the following error:
```
gpg: directory '/root/.gnupg' created
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key 097586CFEA37F9A6: public key "Jeremy Long <jeremy.long@gmail.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: assuming signed data in '/tmp/dependency-check.zip'
gpg: Signature made Sun Jun  9 12:20:47 2019 UTC
gpg:                using RSA key F9514E84AE3708288374BBBE097586CFEA37F9A6
gpg: BAD signature from "Jeremy Long <jeremy.long@gmail.com>" [unknown]
```

**Comment by jeremylong** [comment]
During the release I accidentally rebuilt the cli without updating the signature.  I have verified the file and updated the signature.
