### ISSUE TITLE
[ERROR] Unable to download meta file - nvd json feeds

### ISSUE THREAD

**Issue by neil-n-brown** [dependency-check/DependencyCheck#1987]
Hi,

**Re:  [ERROR] Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-modified.json.gz**

Since upgrading to the latest Maven release 5.0.0 we are seeing errors downloading meta files from nvd json feeds. Above is one such example of the error we are seeing in our Bamboo (CI/CD) build log. Full log details are below.

We are able to wget the file from the Bamboo server itself (where the dependency check is installed). We don't think there should be any proxy issues. However, we are currently investing this further to see if any additional proxy config is required on the dependency check plugin itself. 

Does anyone have any ideas as to why this issue might be happening (other than proxy issues)?

Please let us know if there is any further info you require.

**Bamboo Build Log:**
build	12-Jun-2019 14:42:36	[INFO] Checking for updates
build	12-Jun-2019 14:42:36	[ERROR] Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-modified.json.gz
build	12-Jun-2019 14:42:36	[INFO] Skipping RetireJS update since last update was within 24 hours.
build	12-Jun-2019 14:42:36	[WARN] Unable to update 1 or more Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.
build	12-Jun-2019 14:42:36	[ERROR] Unable to continue dependency-check analysis.
build	12-Jun-2019 14:42:36	[ERROR] One or more fatal errors occurred
build	12-Jun-2019 14:42:36	[ERROR] Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-modified.json.gz
build	12-Jun-2019 14:42:36	[ERROR] No documents exist
simple	12-Jun-2019 14:42:36	Failing task since return code of [/u01/app/bamboo/BAMBOO_HOME/temp/ESB-FSCTD1-CI-7-ScriptBuildTask-4733630983096221027.sh] was 243 while expected 0
simple	12-Jun-2019 14:42:36	Finished task 'Dependency Vulnerability Check' with result: Failed
command	12-Jun-2019 14:42:36	Substituting variable: ${bamboo.M2_REPO} with /home/hkbmbprd/.m2/repository
simple	12-Jun-2019 14:42:36	Starting task 'Housekeep Maven Repository' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script

**Comment by jeremylong** [comment]
First, that error might be a little disingenuous. The URL it is having trouble downloading is https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-modified.meta. If you enabled debug logging you may see a more descriptive error message too.

Any chance you might have multiple jobs running at the same time pulling the NVD data?  I know that they do have some throtteling going on to prevent abuse.  Many people use the [nist-data-mirror](https://github.com/stevespringett/nist-data-mirror) to mirror the NVD locally in their organization.

**Comment by neil-n-brown** [comment]
Hi Jeremy,

We are only running one build plan at a time but I explore the possibility of an NVD mirror once we have ruled out the other possibilities.  Forgive my ignorance but how do we enable debugging?

There is a chance it could be a firewall issue. My network team is checking if the site is white-listed. 

If that is there case will it be sufficient to white-list connectivity to nvd.nist.gov  OR are there also other sites that Dependency Check connects to that we should also add to the white-list?

**Comment by neil-n-brown** [comment]
**Thank you!**

Hi Jeremmy, 

Just to keep you updated. Our mistake we were not aware there was another team running builds with dependency check at the same time as us.

When we tried a single build we do not encounter the issue.  We are now looking into setting up the NVD mirror. Thanks again for your swift responses and solution - much appreciated.

**One question**, is it only NVD that has this issue or will there be other repos that we need to mirror?

**Comment by jeremylong** [comment]
ODC also uses RetireJS so you might want to mirror https://raw.githubusercontent.com/Retirejs/retire.js/master/repository/jsrepository.json - however, I have not heard of any blocking due to too many requests to this resource (yet).

If you are using the CentralAnalzyer (enabled in Jenkins, CLI, and Ant integrations) you may run into throttling issues.  It definitely improves the analysis but can cause issues (increased scan time, 429 - too many request errors, etc.).  Instead we recommend using the native build plugin integration using maven, gradle, or sbt.

**Comment by neil-n-brown** [comment]
I have removed the query that was in this comment box as the issue was resolved.

**Comment by neil-n-brown** [comment]
@jeremylong 

I've now set up the nist data mirror and have dependency check pointing to that instead. This has resolved my issues with NVD. However, I'm encountering a few issues with Central Analyzer and Sonatype OSS Index Analyzer.

In your opinion should these two analyzers be mandatory?  I'm trying to weigh up the pros and cons of disabling them.

My configuration is that I'm using Maven for Builds and Dependency Check CLI. But I am not using the ODC maven plugin

**Comment by jeremylong** [comment]
The central analyzer is not "required" - but in cases where a JAR file does not contain an embedded pom.xml - it will pull down the pom from central and add the evidence to the analysis (see [how ODC works](https://jeremylong.github.io/DependencyCheck/general/internals.html)).  This can create false negatives (i.e. dependency-check was not able to identify the library).

Regarding the OSS Index Analyzer - in some cases, the OSS Index contains vulnerability information that is not in the NVD. So disabling this can cause known vulnerabilities to not be reported.

**Comment by neil-n-brown** [comment]
Thanks @jeremylong much appreciated.
