### ISSUE TITLE
Error during dependency check analysis : The download was interrupted; unable to complete the update

### ISSUE THREAD

**Issue by Hystreal** [dependency-check/DependencyCheck#1988]
Hello,

i'm using dependency-check plugin on Jenkins (v4.0.2) and i have an error during the analysis since June 6th 2019 : 

[DependencyCheck] OWASP Dependency-Check Plugin v4.0.2
[DependencyCheck] Executing Dependency-Check with the following options:
[DependencyCheck]  -name = scope-ws-analyse
[DependencyCheck]  -scanPath = D:\Jenkins\workspace\scope-ws-analyse\ReferAssembly\**\*.dll
[DependencyCheck]  -outputDirectory = D:\Jenkins\workspace\scope-ws-analyse\htmlreports\DependencyCheck_Report
[DependencyCheck]  -dataDirectory = D:\Jenkins\workspace\scope-ws-analyse\dependency-check-data
[DependencyCheck]  -suppressionFile = D:\Tools\TMA\Package_Compile_Install\Data\Global_dependency_check_suppressions.xml
[DependencyCheck]  -dataMirroringType = none
[DependencyCheck]  -isQuickQueryTimestampEnabled = true
[DependencyCheck]  -jarAnalyzerEnabled = true
[DependencyCheck]  -nodePackageAnalyzerEnabled = true
[DependencyCheck]  -nodeAuditAnalyzerEnabled = true
[DependencyCheck]  -retireJsAnalyzerEnabled = true
[DependencyCheck]  -composerLockAnalyzerEnabled = false
[DependencyCheck]  -pythonDistributionAnalyzerEnabled = true
[DependencyCheck]  -pythonPackageAnalyzerEnabled = true
[DependencyCheck]  -rubyBundlerAuditAnalyzerEnabled = false
[DependencyCheck]  -rubyGemAnalyzerEnabled = false
[DependencyCheck]  -cocoaPodsAnalyzerEnabled = false
[DependencyCheck]  -swiftPackageManagerAnalyzerEnabled = false
[DependencyCheck]  -archiveAnalyzerEnabled = true
[DependencyCheck]  -assemblyAnalyzerEnabled = true
[DependencyCheck]  -msBuildProjectAnalyzerEnabled = true
[DependencyCheck]  -nuGetConfigAnalyzerEnabled = true
[DependencyCheck]  -nuspecAnalyzerEnabled = true
[DependencyCheck]  -centralAnalyzerEnabled = true
[DependencyCheck]  -nexusAnalyzerEnabled = false
[DependencyCheck]  -artifactoryAnalyzerEnabled = false
[DependencyCheck]  -autoconfAnalyzerEnabled = false
[DependencyCheck]  -cmakeAnalyzerEnabled = false
[DependencyCheck]  -opensslAnalyzerEnabled = true
[DependencyCheck]  -showEvidence = true
[DependencyCheck]  -formats = XML HTML 
[DependencyCheck]  -autoUpdate = true
[DependencyCheck]  -updateOnly = false
[DependencyCheck] Output directory created
[DependencyCheck] Data directory created
[DependencyCheck] Scanning: D:\Jenkins\workspace\scope-ws-analyse\ReferAssembly\MongoDB.Bson.dll
[DependencyCheck] Scanning: D:\Jenkins\workspace\scope-ws-analyse\ReferAssembly\MongoDB.Driver.dll
[DependencyCheck] Scanning: D:\Jenkins\workspace\scope-ws-analyse\ReferAssembly\Oracle.ManagedDataAccess.12.1.24160719\bin\x64\Oracle.ManagedDataAccessDTC.dll
[DependencyCheck] Scanning: D:\Jenkins\workspace\scope-ws-analyse\ReferAssembly\Oracle.ManagedDataAccess.12.1.24160719\bin\x64\Oracle.ManagedDataAccessIOP.dll
[DependencyCheck] Scanning: D:\Jenkins\workspace\scope-ws-analyse\ReferAssembly\Oracle.ManagedDataAccess.12.1.24160719\bin\x86\Oracle.ManagedDataAccessDTC.dll
[DependencyCheck] Scanning: D:\Jenkins\workspace\scope-ws-analyse\ReferAssembly\Oracle.ManagedDataAccess.12.1.24160719\bin\x86\Oracle.ManagedDataAccessIOP.dll
[DependencyCheck] Scanning: D:\Jenkins\workspace\scope-ws-analyse\ReferAssembly\Oracle.ManagedDataAccess.12.1.24160719\lib\net40\Oracle.ManagedDataAccess.dll
[DependencyCheck] Scanning: D:\Jenkins\workspace\scope-ws-analyse\ReferAssembly\TA2Net.Db.dll
[DependencyCheck] Scanning: D:\Jenkins\workspace\scope-ws-analyse\ReferAssembly\TA2Net.Drv.dll
[DependencyCheck] Scanning: D:\Jenkins\workspace\scope-ws-analyse\ReferAssembly\TA2Net.Dto.dll
[DependencyCheck] Scanning: D:\Jenkins\workspace\scope-ws-analyse\ReferAssembly\TA2Net.Utilities.dll
[DependencyCheck] Scanning: D:\Jenkins\workspace\scope-ws-analyse\ReferAssembly\log4net.dll
[DependencyCheck] Analyzing Dependencies
[DependencyCheck] One or more exceptions were thrown while executing Dependency-Check
[DependencyCheck] Exception Caught: org.owasp.dependencycheck.data.update.exception.UpdateException
[DependencyCheck] Message: The download was interrupted; unable to complete the update
[DependencyCheck] org.owasp.dependencycheck.data.update.exception.UpdateException: The download was interrupted; unable to complete the update
[DependencyCheck] 	at org.owasp.dependencycheck.data.update.NvdCveUpdater.performUpdate(NvdCveUpdater.java:274)
[DependencyCheck] 	at org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:119)
[DependencyCheck] 	at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:899)
[DependencyCheck] 	at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:716)
[DependencyCheck] 	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:642)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.executeDependencyCheck(DependencyCheckExecutor.java:172)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.call(DependencyCheckExecutor.java:103)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.call(DependencyCheckExecutor.java:46)
[DependencyCheck] 	at hudson.remoting.LocalChannel.call(LocalChannel.java:45)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.AbstractDependencyCheckBuilder.perform(AbstractDependencyCheckBuilder.java:85)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckBuilder.perform(DependencyCheckBuilder.java:206)
[DependencyCheck] 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
[DependencyCheck] 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
[DependencyCheck] 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
[DependencyCheck] 	at hudson.model.Build$BuildExecution.build(Build.java:206)
[DependencyCheck] 	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
[DependencyCheck] 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
[DependencyCheck] 	at hudson.model.Run.execute(Run.java:1816)
[DependencyCheck] 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
[DependencyCheck] 	at hudson.model.ResourceController.execute(ResourceController.java:97)
[DependencyCheck] 	at hudson.model.Executor.run(Executor.java:429)
[DependencyCheck] 

Does anyone have any ideas as to why this issue might be happening knowing that it works before June 6th ?

Please let me know if there is any further info you require.

Best regards

**Comment by jeremylong** [comment]
We had started to see reports of download issues with 4.x. Please try the recent 5.0.0 release.

**Comment by Hystreal** [comment]
Indeed it works with the recent version. Do you have a release date about the jenkins plugin ?

**Comment by jeremylong** [comment]
The jenkins plugin requires a near complete re-write - which is underway. We are hoping within a month.

**Comment by jeremylong** [comment]
I'm closing this issue as the core library has been updated to resolve this.

**Comment by willwh** [comment]
> The jenkins plugin requires a near complete re-write - which is underway. We are hoping within a month.

Is there somewhere I can help contribute to that? :)

Sorry for the necro post, answering my own question: https://github.com/jenkinsci/dependency-check-plugin

**Comment by stevespringett** [comment]
@whitfin It's complete. v5.0.2 is the latest available. Please see https://wiki.jenkins.io/display/JENKINS/OWASP+Dependency-Check+Plugin and the migration wiki https://github.com/jenkinsci/dependency-check-plugin/wiki/v5-Migration
