### ISSUE TITLE
Sonatype oss scan request fails if dependency does not have a version

### ISSUE THREAD

**Issue by jamesratzlaff** [dependency-check/DependencyCheck#1993]
When making a POST request to https://ossindex.sonatype.org/api/v3/component-report with payload
```json
{"coordinates":["pkg:pypi/redis@3.2.1","pkg:pypi/hy@0.17.0","pkg:pypi/jsonobject","pkg:pypi/eventlet@0.25.0","pkg:pypi/jsonobject@0.9.9","pkg:pypi/flask-socketio@4.1.0","pkg:pypi/flask@1.0.3"]} 
```
a 400 error is returned with the message "Missing coordinates version"

** Version of dependency-check used **
The problem occurs using version 5.0.0 of core/cli

** Log file **
https://gist.github.com/jamesratzlaff/2b69c6229ec6fa1df10857420af9d4ae

**To Reproduce**
1.Be sure to have both the analyzer.python.distribution.enabled=true and analyzer.python.package.enabled=true (they're enabled by default)
1. Scan a project that has the python package jsonobject-0.9.9.tar.gz 
    * __init__.py resolves to the package **pkg:pypi/jsonobject**
    * jsonobject.egg-info\\PKG-INFO resolves to the package pkg:pypi/jsonobject@0.9.9
3. When the oss analyzer uses pkg:pypi/jsonobject in the request, it fails due to the missing coordinate version

**Expected behavior**
The OSS Analyzer should ideally exclude dependencies with no version or dependencies that result in an invalid syntax from being analyzed.

**Comment by stevespringett** [comment]
In purl, the version is optional. So a valid purl may not have a version. However, OSS Index requires one for vulnerability identification.

**Comment by jamesratzlaff** [comment]
When the purl with no version is removed, the oss analyzer works great (huge value add). Would it be possible to exclude dependencies that don't have specific enough coordinates from the oss analyzer?
