### ISSUE TITLE
Oracle: failure to update the DB using version 5.0.0

### ISSUE THREAD

**Issue by Jidehem** [dependency-check/DependencyCheck#1994]
**Describe the bug**

** Version of dependency-check used **
The problem occurs using version 5.0.0 of the the maven plugin
with DB initialized with patched version of initialize_oracle.sql
[initialize_oracle_5.sql.txt](https://github.com/jeremylong/DependencyCheck/files/3287132/initialize_oracle_5.sql.txt).

** Log file **
See below

**To Reproduce**
1. Setup connection to the Oracle DB
2. Run mvn dependency-check-maven:5.0.0:update-only
3. The update fails with an error (see error log)
[maven-error.log](https://github.com/jeremylong/DependencyCheck/files/3287142/maven-error.log)

**Expected behavior**
The update of the data works without issue.

**Additional context**
N/A

**Comment by jeremylong** [comment]
Please run `mvn org.owasp:dependency-check-maven:update-only -X` to run the update with debug logging enabled. Please provide the more detailed log.

Thanks!

**Comment by Jidehem** [comment]
Here is the detailed log: [maven-error-detailed.log](https://github.com/jeremylong/DependencyCheck/files/3290247/maven-error-detailed.log)

**Comment by Jidehem** [comment]
Note: initially, the DB tables are empty. After running `mvn`, the DB has data in only 2 tables:
PROPERTIES:
![image](https://user-images.githubusercontent.com/647939/59503705-606ac680-8ea1-11e9-8e3c-9a7045f2d825.png)
VULNERABILITY:
![image](https://user-images.githubusercontent.com/647939/59503742-809a8580-8ea1-11e9-92b5-b085ab42ebcb.png)

**Comment by Jidehem** [comment]
By checking the code, it seems that the issue comes from assumption made about the structure of the generated key. However, the javadoc of `Statement.getGeneratedKeys()` states :
> If the columns which represent the auto-generated keys were not specified,
> the JDBC driver implementation will determine the columns which best represent the auto-generated keys.

Maybe that using the overload `PreparedStatement prepareStatement(String sql, String columnNames[])` and passing the ID column names will work ?

**Comment by Jidehem** [comment]
Note: the fix to initialize Oracle DB is available in this PR: https://github.com/jeremylong/DependencyCheck/pull/1996

**Comment by jeremylong** [comment]
@Jidehem Thank you for the PR!  Truly appreciated!

**Comment by jeremylong** [comment]
I have updated the code to explicitly call out the column that should be returned. This works in H2 and MySQL - hoping it works in Oracle as well. However, I do not currently have an Oracle database or MS SQL database setup for testing.

**Comment by Jidehem** [comment]
I could test it on Oracle. Is there any nightly build or similar available through maven dependencies to allow testing without compiling ?

**Comment by jeremylong** [comment]
Snapshots are deployed to bintray: https://dependencycheck.jfrog.io/dependencycheck/libs-snapshot

```xml
<repository>
   <id>odc</id>
   <name>odc</name>
   <url>https://dependencycheck.jfrog.io/dependencycheck/libs-snapshot</url>
</repository>
```
Use version: `5.1.0-SNAPSHOT`

**Comment by Jidehem** [comment]
The fix is working for Oracle (tested on version 12.1.0.2.0 of Oracle with version `5.1.0-SNAPSHOT`)

Note: I had to use `<pluginRepository>`instead of `<repository>` :

```xml
<pluginRepositories>
    <pluginRepository>
        <id>odc</id>
        <name>odc</name>
        <url>https://dependencycheck.jfrog.io/dependencycheck/libs-snapshot</url>
    </pluginRepository>
</pluginRepositories>
```

**Comment by jeremylong** [comment]
Awesome!  thanks for validating.
