### ISSUE TITLE
Not able to see data in the Database

### ISSUE THREAD

**Issue by niddhig** [dependency-check/DependencyCheck#1995]
I am trying to connect to the H2 database when i used the cli-command for dependency-check.
The location of the database i am trying to access:
/Users/ngarg/.m2/repository/org/owasp/dependency-check-data/4.0/odc.mv.db
Username and password from the settings file:
data.user=dcuser
data.password=DC-Pass1337!

I am able to connect successfully but i don't see any tables there. I guess its creating a new one and not opening the one which was already created.

Any help is appreciated!

**Comment by jeremylong** [comment]
If you are using the same connection string with a different path - that will fail as we updated settings in the connection string when we moved to the 4.0 schema. Specifically, we removed the MV_STORE=false:

https://github.com/jeremylong/DependencyCheck/blob/e149cbeb303d8f2f5f819b70e1887c63ea2c4af3/core/src/main/resources/dependencycheck.properties#L29

**Comment by niddhig** [comment]
I am able to connect now. Thanks for your quick response. I was giving the db name as 'dc.mv.db' while only giving 'dc' worked.

Now i am trying to connect postgresql instead of H2. I ran the script provided on the postgresql and updated the dbstatements in the code as given.

These are my new settings for postgresql in dependencycheck.properties:
data.directory=[JAR]/data
#if the filename has a %s it will be replaced with the current expected version
#data.file_name=dc.mv.db
data.file_name=postgres
data.version=4.1

#The analysis timeout in minutes
odc.analysis.timeout=20

#data.connection_string=jdbc:h2:file:%s;AUTOCOMMIT=ON;LOG=0;CACHE_SIZE=65536;
#data.connection_string=jdbc:mysql://localhost:3306/dependencycheck
data.connection_string=jdbc:postgresql://localhost:5432/dependencycheck;

#user name and password for the database connection. The inherent case is to use H2.
#As such, this unsecure username/password exist.
data.user=dcuser
data.password=DC-Pass1337!

#The following are only used if the DB Driver is not JDBC4 compliant and/or the driver
#is not in the current classpath. Setting these properties will add the give path(s) to
#the class loader and then register the driver with the DriverManager. If the class is
#not in the path you must specify both the driver name (aka the fully qualified driver name)
#and the driver path. The driver path can be a semi-colon separated list of files/directories
#to ensure any and all needed files can be added to the classpath to load the driver.
#For non-JDBC4 drivers in the classpath only the driver_name needs to be set.
#For MOST situations these properties likely do not need to be set.
#data.driver_name=org.h2.Driver
data.driver_name=org.postgresql.Driver
data.driver_path=


These were the only fields i changed. I compiled the code and run using cli but the data is not populated in the tables. 

Looking forward for any pointers.

Thanks,
Niddhi

**Comment by jeremylong** [comment]
To help further we would need the debug log:

```
dependency-check.sh --updateonly --log odc.log
```

**Comment by niddhig** [comment]
Please find attached odc.log for your reference.

Can it be because of the data path:

/Users/ngarg/code/dc/DependencyCheck/cli/target/release/data


Thanks,

Niddhi

**Comment by jeremylong** [comment]
The log was not attached to your last post.

**Comment by niddhig** [comment]
It is not letting me attach the file. I replied through the email hoping that it will be attached but looks like it still didn't got attached. 

I tried zipping it and attaching still it didn't allow. Removing the extension also didn't work.

Is there any other way i can send it to you?

Thanks,
Niddhi

**Comment by jeremylong** [comment]
Post the file as a gist and reference the gist: https://gist.github.com/

**Comment by niddhig** [comment]
https://gist.github.com/niddhig/a4d780e5e5f9623367076621e3e9fd43

**Comment by jeremylong** [comment]
So in this case it appears that the update worked correctly and you should be able to connect to the database using the connection string:
```
jdbc:h2:file:/Users/ngarg/code/dc/DependencyCheck/cli/target/release/data/odc;AUTOCOMMIT=ON;LOG=0;CACHE_SIZE=65536;
```
If you grab the platform independent zip from the H2 download site: http://www.h2database.com/html/download.html

There will be a `bin/h2.sh` that you can execute to start the web console (just one of the many ways to connect to an H2 database). I've also successfully used several IDEs (Intellij, Netbeans, etc.) to connect to the database.

**Comment by niddhig** [comment]
I am trying to use postgresql instead of H2. When I use H2, data gets
populated fine. But when i use postgresql, i don’t see the data being
popultaed in postgresql tables.


Thanks,
Niddhi

**Comment by jeremylong** [comment]
Right - so I asked to see the log and you gave me the log of when it was working with H2...  Not much I can do there.  Can you provide the log when you run this using postgres?

**Comment by niddhig** [comment]
This is the logs which got generated after i changed those settings in the
file for postgresql. Looks like i am missing some changes.

**Comment by jeremylong** [comment]
A log was not attached to the above post?

**Comment by niddhig** [comment]
Hi,

Pardon me for the previous logs, they were not correct.

These are the errors i am getting:
[ERROR] Tests run: 8, Failures: 0, Errors: 7, Skipped: 0, Time elapsed: 1.902 s <<< FAILURE! - in org.owasp.dependencycheck.taskdefs.DependencyCheckTaskIT
[ERROR] testRetireJsConfiguration(org.owasp.dependencycheck.taskdefs.DependencyCheckTaskIT)  Time elapsed: 1.42 s  <<< ERROR!
org.apache.tools.ant.BuildException: 
org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during analysis:
	Unable to connect to the dependency-check database
	at org.owasp.dependencycheck.taskdefs.DependencyCheckTaskIT.testRetireJsConfiguration(DependencyCheckTaskIT.java:176)
Caused by: org.owasp.dependencycheck.exception.ExceptionCollection: 
One or more exceptions occurred during analysis:
	Unable to connect to the dependency-check database
	at org.owasp.dependencycheck.taskdefs.DependencyCheckTaskIT.testRetireJsConfiguration(DependencyCheckTaskIT.java:176)

[ERROR] testAddDirSet(org.owasp.dependencycheck.taskdefs.DependencyCheckTaskIT)  Time elapsed: 0.048 s  <<< ERROR!
org.apache.tools.ant.BuildException: 
org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during analysis:
	Unable to connect to the dependency-check database
	at org.owasp.dependencycheck.taskdefs.DependencyCheckTaskIT.testAddDirSet(DependencyCheckTaskIT.java:97)
Caused by: org.owasp.dependencycheck.exception.ExceptionCollection: 
One or more exceptions occurred during analysis:
	Unable to connect to the dependency-check database
	at org.owasp.dependencycheck.taskdefs.DependencyCheckTaskIT.testAddDirSet(DependencyCheckTaskIT.java:97)

[ERROR] testAddFileSet(org.owasp.dependencycheck.taskdefs.DependencyCheckTaskIT)  Time elapsed: 0.063 s  <<< ERROR!
org.apache.tools.ant.BuildException: 
org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during analysis:
	Unable to connect to the dependency-check database
	at org.owasp.dependencycheck.taskdefs.DependencyCheckTaskIT.testAddFileSet(DependencyCheckTaskIT.java:62)
Caused by: org.owasp.dependencycheck.exception.ExceptionCollection: 
One or more exceptions occurred during analysis:
	Unable to connect to the dependency-check database
	at org.owasp.dependencycheck.taskdefs.DependencyCheckTaskIT.testAddFileSet(DependencyCheckTaskIT.java:62)

[ERROR] testSuppressingSingle(org.owasp.dependencycheck.taskdefs.DependencyCheckTaskIT)  Time elapsed: 0.05 s  <<< ERROR!
org.apache.tools.ant.BuildException: 
org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during analysis:
	Unable to connect to the dependency-check database
	at org.owasp.dependencycheck.taskdefs.DependencyCheckTaskIT.testSuppressingSingle(DependencyCheckTaskIT.java:143)
Caused by: org.owasp.dependencycheck.exception.ExceptionCollection: 
One or more exceptions occurred during analysis:
	Unable to connect to the dependency-check database
	at org.owasp.dependencycheck.taskdefs.DependencyCheckTaskIT.testSuppressingSingle(DependencyCheckTaskIT.java:143)

[ERROR] testSuppressingCVE(org.owasp.dependencycheck.taskdefs.DependencyCheckTaskIT)  Time elapsed: 0.055 s  <<< ERROR!
org.apache.tools.ant.BuildException: 
org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during analysis:
	Unable to connect to the dependency-check database
	at org.owasp.dependencycheck.taskdefs.DependencyCheckTaskIT.testSuppressingCVE(DependencyCheckTaskIT.java:119)
Caused by: org.owasp.dependencycheck.exception.ExceptionCollection: 
One or more exceptions occurred during analysis:
	Unable to connect to the dependency-check database
	at org.owasp.dependencycheck.taskdefs.DependencyCheckTaskIT.testSuppressingCVE(DependencyCheckTaskIT.java:119)

[ERROR] testSuppressingMultiple(org.owasp.dependencycheck.taskdefs.DependencyCheckTaskIT)  Time elapsed: 0.046 s  <<< ERROR!
org.apache.tools.ant.BuildException: 
org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during analysis:
	Unable to connect to the dependency-check database
	at org.owasp.dependencycheck.taskdefs.DependencyCheckTaskIT.testSuppressingMultiple(DependencyCheckTaskIT.java:160)
Caused by: org.owasp.dependencycheck.exception.ExceptionCollection: 
One or more exceptions occurred during analysis:
	Unable to connect to the dependency-check database
	at org.owasp.dependencycheck.taskdefs.DependencyCheckTaskIT.testSuppressingMultiple(DependencyCheckTaskIT.java:160)

[ERROR] testAddFileList(org.owasp.dependencycheck.taskdefs.DependencyCheckTaskIT)  Time elapsed: 0.044 s  <<< ERROR!
org.apache.tools.ant.BuildException: 
org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during analysis:
	Unable to connect to the dependency-check database
	at org.owasp.dependencycheck.taskdefs.DependencyCheckTaskIT.testAddFileList(DependencyCheckTaskIT.java:79)
Caused by: org.owasp.dependencycheck.exception.ExceptionCollection: 
One or more exceptions occurred during analysis:
	Unable to connect to the dependency-check database
	at org.owasp.dependencycheck.taskdefs.DependencyCheckTaskIT.testAddFileList(DependencyCheckTaskIT.java:79)


Configurations for the postgresql:
data.connection_string=jdbc:postgresql://localhost:5432/postgres;
data.driver_name=org.postgresql.Driver
data.driver_path=

Do i need to mention the driver_path? 

Thanks for your patience.

**Comment by jeremylong** [comment]
The driver must be on the classpath.  This can be done multiple ways and setting the `data.driver_path` is one of them. The log above appears that you are trying to build dependency-check as oppose to using dependency-check.  Note, a base build will not populate a complete database as it limits the NVD files being imported to save on build time.
