### ISSUE TITLE
Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-modified.json.gz

### ISSUE THREAD

**Issue by Mayabhai** [dependency-check/DependencyCheck#2002]
Hi Team,

We have downloaded DCT 5.0.0 and tried to run through CLI, but it is giving us the error as:

[INFO] Checking for updates
[ERROR] Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-modified.json.gz
[ERROR] Failed to initialize the RetireJS repo
[WARN] Unable to update 1 or more Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.
[ERROR] Unable to continue dependency-check analysis.
[ERROR] One or more fatal errors occurred
[ERROR] Failed to initialize the RetireJS repo
[ERROR] No documents exist

Not sure what I am missing here.

**Comment by jeremylong** [comment]
My guess is you are behind a proxy that is blocking access to the NVD and github (two locations where data files are downloaded from); please see https://jeremylong.github.io/DependencyCheck/data/index.html.  

To get a more detailed error report please execute:

```
dependency-check.sh --purge
dependency-check.sh --updateonly --log odc.log
```
More detailed error messages as to what exactly has gone wrong will be in the `odc.log` file.

**Comment by davewichers** [comment]
I'm having exactly the same problem, except I'm self hosting the files offline. I can download the https://mysite/somepath/json/cve/1.0/nvdcve-1.0-modified.json.gz file no problem using dependency-check-maven:5.0.0-M2, but NOT with 5.0.0, so something must have changed between the two versions related to downloading files like this.

Looks Like I can do what you suggest above by doing these:

dependency-check-maven:purge
dependency-check-maven:update-only

Except I can't find how to enable/configure logging for the dependency-check-maven plugin at: https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html

How do I turn on logging like you suggest above, but for the maven plugin? If you explain how, I'll look at those logs to see if I can find out what's going wrong. But the download IS available, so it's not a proxy blocking problem.

**Comment by jeremylong** [comment]
@davewichers logging for Maven is enabled by supplying `-X` as a parameter. This turns on debug logging for Maven.  Example:

```
mvn org.owasp:dependency-check-maven:5.0.0:check -X
```

**Comment by jeremylong** [comment]
With 5.0.0 you need to have the full mirror of the NVD JSON files (including the json.gz and the meta files).  This can be achieved using the [nist-data-mirror](https://github.com/stevespringett/nist-data-mirror).

**Comment by davewichers** [comment]
Apparently it is the missing nvdcve-1.0-modified.meta file that is missing, not the nvdcve-1.0-modified.json.gz file, even though that is what the error message is actually saying. Something like:

Unable to download meta file: nvdcve-1.0-modified.json.gz

Which is obviously misleading. This is caused by a set of related bugs in this file:

https://github.com/jeremylong/DependencyCheck/blob/master/core/src/main/java/org/owasp/dependencycheck/data/update/NvdCveUpdater.java (lines 355-363) - where the set of error messages use the variable url, when they should be using the variable metaUrl instead.

One final question: I'll work on getting that file to fix my setup. Do I need ALL the meta files, i.e., modified.meta plus recent.meta, plus one for each of the years? Or just this modified.meta file?

**Comment by jeremylong** [comment]
You need all of the meta files - using the nist-data-mirror is the easiest way to ensure you have all the files.  And yes - I agree the error message is confusing and it will be updated.

**Comment by jeremylong** [comment]
Minor update - with regard to the meta data files. You do not need the recent meta data file. ODC does not use any of the "recent" files. Only the modified and then 2012-[current year].

**Comment by shubhankar1114** [comment]
Facing the same issue  :

![image](https://user-images.githubusercontent.com/52689846/65935979-93c56700-e438-11e9-8ee2-75874a033b61.png)

**Comment by ghost** [comment]
@shubhankar1114 Please take a look at #2222 and try the `Dcom.sun.security.enableAIAcaIssuers=true` option.
