### ISSUE TITLE
CLI failing with exit code -14

### ISSUE THREAD

**Issue by aoxley** [dependency-check/DependencyCheck#2004]
**Describe the bug**
When running dependency-check CLI on a linux box (redhat) via a jenkins job, I am getting an exception thrown, and the job is failing with exit code -14. It is scanning a folder that i have filled with jar files (I have used the maven copy dependency plugin to scan the pom and put the files into the folder).

I am also getting the same exit code when trying to run the same CLI via a windows OS on the same codebase (this time though the log does not show an exception being thrown).

Interestingly, even though it is exiting in both cases, it is still generating all the output files - but I don't know if these are complete or not.

** Version of dependency-check used **
CLI version 3.3.4-RELEASE

** Log file **
Logs files in gist:
https://gist.github.com/aoxley/d7da58dfb48b0cde94ccc7e342e1cae4

This includes both what jenkins log, as well as the log generated by CLI on redhat and windows.

**To Reproduce**
Unfortunately this is a private repo so a little hard to give an exact reproduction step. The command however being run is:

`dependency-check.bat --proxyserver <IP_ADDRESS> --proxyport <PORT> --proxyuser <USER> --proxypass <PASSWORD> --project "test project" --scan "C:\Temp\code\target\dependency-check" --out "C:\Temp\code" --format "ALL" --log "C:\Temp\code\target\dependency-check.log"`

As mentioned, it is scanning a folder filled with jar files. Hopefully the logs may give some clue as to what is happening.

**Comment by jeremylong** [comment]
This is a known issue that could affect all releases prior to 5.0.0. Please upgrade to the latest version of dependency-check. If you must keep using the version of ODC the only way to make it reliable work would be to setup an internal mirror of the NVD: https://github.com/stevespringett/nist-data-mirror

Note - if you are using the Jenkins plugin to import and track the findings you will have to wait a few more weeks while the 5.0.0 version of the Jenkins plugin is released.

**Comment by aoxley** [comment]
Thanks so much jeremy. I'll take a look at upgrading if I can (I was having to play around with a few different components versions to get ones that played nicely). 
I'll close this off now.
Cheers.
