### ISSUE TITLE
Jenkins Slave configuration 

### ISSUE THREAD

**Issue by matteoturra** [dependency-check/DependencyCheck#2005]
I schedule a nightly job on master node to update the dependency-check database with "Invoke Dependency-Check update only" step specifying a Data directory where it store it's data. The intent is to update it for all the other builds that use it. Otherwise every build performing the dependency-check will try to update it.

The other builds run on slaves deployed on other servers, they can't see this directory to get the updated CVE data. 

Which is the best configuration?
* Use a shared directory between master and slaves
* Use one directory per slave and run the update only job on each slave
* alternatives ?

**Comment by jeremylong** [comment]
An alternative would be to use an centralized database - see https://jeremylong.github.io/DependencyCheck/data/database.html.  When setting this up create one node that does the update - we still haven't worked on the performance of the update (initial update can takes several hours, incremental updates still take longer than you would want a build waiting). Then configure all scanning nodes with autoupdate=false.

A shared directory would also be an okay option. However, again - I would have a single node/job run daily to perform the updates and configure all scanning to be done with autoupdate=false.

**Comment by matteoturra** [comment]
Thanks @jeremylong. 

Can the dependencytrack database works as this centralized database?

I use dependecyCheck because I haven't found a gradle plugin to generate BOM and send it to dependencyTrack. This project https://github.com/CycloneDX/cyclonedx-gradle-plugin is not yet released. 

After a Jenkins update I have this error:
```
14:02:21  See the dependency-check report for more details.
14:02:22  > Task :dependencyCheckAnalyze FAILED
14:02:22  FAILURE: Build failed with an exception.
14:02:22  
14:02:22  * What went wrong:
14:02:22  Execution failed for task ':dependencyCheckAnalyze'.
14:02:22  > One or more exceptions occurred during analysis
14:02:22  
14:02:22  * Try:
14:02:22  Run with --info or --debug option to get more log output. Run with --scan to get full insights.
14:02:22  
14:02:22  * Exception is:
14:02:22  org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':dependencyCheckAnalyze'.
.....
14:02:22  Caused by: org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during dependency-check analysis
```

I suppose this error is related to the weird message 
```
14:14:58  Download Complete for NVD CVE - 2010  (15707 ms)
14:14:58  An exception occurred downloading NVD CVE - 2010
14:14:58  Some CVEs may not be reported.
```
few lines above. It's it?

Thats why I'm looking a more resilient solution to download CVE db updates in a separate job. But this Job  with "Invoke Dependency-Check update only":

```xml
<builders>
 <org.jenkinsci.plugins.DependencyCheck.DependencyCheckUpdateOnlyBuilder plugin="dependency-check-jenkins-plugin@4.0.2">
  <skipOnScmChange>false</skipOnScmChange>
  <skipOnUpstreamChange>false</skipOnUpstreamChange>
  <datadir>${HOME}/owasp-checkdep-data</datadir>
 </org.jenkinsci.plugins.DependencyCheck.DependencyCheckUpdateOnlyBuilder>
</builders>
```
but this job get an error too:

```
[DependencyCheck] OWASP Dependency-Check Plugin v4.0.2
[DependencyCheck] Executing Dependency-Check with the following options:
[DependencyCheck]  -name = OWASP Dependency-Check update
[DependencyCheck]  -outputDirectory = /home/jenkins/agent/workspace/CI-Utils/OWASP Dependency-Check update
[DependencyCheck]  -dataDirectory = /home/jenkins/owasp-checkdep-data
[DependencyCheck]  -dataMirroringType = none
[DependencyCheck]  -isQuickQueryTimestampEnabled = true
[DependencyCheck]  -jarAnalyzerEnabled = false
[DependencyCheck]  -nodePackageAnalyzerEnabled = false
[DependencyCheck]  -nodeAuditAnalyzerEnabled = false
[DependencyCheck]  -retireJsAnalyzerEnabled = true
[DependencyCheck]  -composerLockAnalyzerEnabled = false
[DependencyCheck]  -pythonDistributionAnalyzerEnabled = false
[DependencyCheck]  -pythonPackageAnalyzerEnabled = false
[DependencyCheck]  -rubyBundlerAuditAnalyzerEnabled = false
[DependencyCheck]  -rubyGemAnalyzerEnabled = false
[DependencyCheck]  -cocoaPodsAnalyzerEnabled = false
[DependencyCheck]  -swiftPackageManagerAnalyzerEnabled = false
[DependencyCheck]  -archiveAnalyzerEnabled = false
[DependencyCheck]  -assemblyAnalyzerEnabled = false
[DependencyCheck]  -msBuildProjectAnalyzerEnabled = false
[DependencyCheck]  -nuGetConfigAnalyzerEnabled = false
[DependencyCheck]  -nuspecAnalyzerEnabled = false
[DependencyCheck]  -centralAnalyzerEnabled = false
[DependencyCheck]  -nexusAnalyzerEnabled = false
[DependencyCheck]  -artifactoryAnalyzerEnabled = false
[DependencyCheck]  -autoconfAnalyzerEnabled = false
[DependencyCheck]  -cmakeAnalyzerEnabled = false
[DependencyCheck]  -opensslAnalyzerEnabled = false
[DependencyCheck]  -showEvidence = true
[DependencyCheck]  -formats = XML 
[DependencyCheck]  -autoUpdate = true
[DependencyCheck]  -updateOnly = true
[DependencyCheck] Performing update only
[DependencyCheck] Unable to update the Dependency-Check database
Build step 'Invoke Dependency-Check update only' changed build result to FAILURE
```
without any other error messages!

Could be an network problem?

**Comment by jeremylong** [comment]
This is unfortunately not an uncommon problem with the pre 5.0.0 releases.  We have made several changes to help with this.  However, the 5.0.0 version of the jenkins plugin has not been released yet.  Another option would be to mirror the NVD locally and use the mirror to update ODC.

https://github.com/stevespringett/nist-data-mirror/
