### ISSUE TITLE
ossIndex Suppression Doesn't Quite Work w/ Maven plugin for 5.0.0

### ISSUE THREAD

**Issue by davewichers** [dependency-check/DependencyCheck#2009]
**Describe the bug**
Per: https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html, if you set: ossIndexAnalyzerEnabled=false, that should disable the attempt to connect to the Sonatype OSS Index, and presumably also turn off OSS Index Analysis since you can't get the data.

When I set ossIndexAnalyzerEnabled=false, the stack trace goes away, but I still get an error that the OSS Index Analysis was not completed. So I think this disable feature for this new type of analysis wasn't completed implemented properly.

**Version of dependency-check used**
The problem occurs using version 5.0.0 of the maven plugin.

**Expected behavior**
When someone sets: ossIndexAnalyzerEnabled=false, they shouldn't get any errors related to OSS Index Analysis.

**Comment by rjimgal** [comment]
Try using 'ossindexAnalyzerEnabled' instead.

**Comment by davewichers** [comment]
OK. Using the lowercase i in index works. Seems like ALL these flags should be case insensitive though so picky details like this don't matter.

**Comment by jeremylong** [comment]
@davewichers unfortunately - I do not believe you can easily make the parameters to maven case insensitive.

**Comment by davewichers** [comment]
OK. So are you going to change it to be: ossIndexAnalyzerEnabled, or leave it as: ossindexAnalyzerEnabled and change the documentation to match what it actually is?

**Comment by jeremylong** [comment]
The documentation was updated - the property will remain `ossindexAnalyzerEnabled`.
