### ISSUE TITLE
Bug in sleep time between retries causes maven plugin to appear to hang

### ISSUE THREAD

**Issue by slowteetoe** [dependency-check/DependencyCheck#2013]
**Describe the bug**
search.maven.org (used by the Central Analyzer, for example) is currently returning a 504 Gateway Timeout.  This causes the retry logic to take effect, but to the end user, it appears that the dependency check hangs indefinitely.

It looks to me like there was an unintentional doubling of the sleeping time between retries - i.e. it is being multiplied by 4 each time (instead of doubled), so by the time we get to the 6th retry, the sleep time is ~102 mins  instead of ~1.6 mins (see the try/catch block in https://github.com/jeremylong/DependencyCheck/blob/908c45ba5a1e9ff5b3c4f3690c217b957b6cb0f6/core/src/main/java/org/owasp/dependencycheck/analyzer/CentralAnalyzer.java#L257)

** Version of dependency-check used **
The problem occurs using version 5.0.0 of the the maven plugin.

** Log file **
Not very helpful without timestamps, but [gist](https://gist.github.com/slowteetoe/e2afd9404e1e9a3e3a0206de71aa5891)

**To Reproduce**
1. Enable debug log levels
2. Force a http error for the Central Analyzer plugin, so that it enters the retry logic
3. Observe the retry behavior

**Expected behavior**
I expected the retry logic to complete (and possibly fail) within a reasonable timeframe.  Instead, it appears as though the plugin hangs (and our build does not complete)

**Additional context**
As an example, https://search.maven.org/solrsearch/select?q=1:3a738b513c9a2491d82d5522a20b497c574cd949&wt=xml is currently returning a 504

**Comment by jeremylong** [comment]
This has already been resolved in the current snapshot and will be released with the next version:

https://github.com/jeremylong/DependencyCheck/blob/8e3d53fa89dc59ee0901a8cd0fb99e3c45cb1b98/core/src/main/java/org/owasp/dependencycheck/analyzer/CentralAnalyzer.java#L265-L283

**Comment by jeremylong** [comment]
In addition, I have added checks to fail more quickly when we are unable to connect to MavenCentral.

**Comment by slowteetoe** [comment]
Thanks!
