### ISSUE TITLE
Error when try to use DC offline (DC ver. 5.0.0)

### ISSUE THREAD

**Issue by ErezDasa** [dependency-check/DependencyCheck#2014]
Hi,

I want to use DC completly offline so I mirror thr NVD according to this guide:
https://jeremylong.github.io/DependencyCheck/data/mirrornvd.html

Now i'm running the folloeing command:

`dependency-check.bat --project test -s C:\jars  --cveUrlBase C:\temp\NVD --cveUrlModified C:\temp\NVD  --retireJsUrl C:\temp\Json`

I've got this error:

`[INFO] Checking for updates`

`[ERROR] Meta file url is invalid: C:\temp\NVD`

`[ERROR] Inavlid URL for RetireJS repository (C:\temp\Json)`

`[WARN] Unable to update 1 or more Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.`

`[ERROR] Unable to continue dependency-check analysis.`

`[ERROR] One or more fatal errors occurred`

`[ERROR] Inavlid URL for RetireJS repository (C:\temp\Json)`

`[ERROR] No documents exist`

How can i solve this problem please?

Thank you!

**Comment by mprins** [comment]
perhaps you need to add a protocol to the URLs such as `file://`

**Comment by ErezDasa** [comment]
Thank you, Now it's starting to download the NVD files from the local folders, Once the download finished i got those errors:

`[INFO] Download Started for NVD CVE - Modified`
`[INFO] Download Complete for NVD CVE - Modified  (11 ms)`
`[INFO] Processing Started for NVD CVE - Modified`
`[INFO] Processing Complete for NVD CVE - Modified  (409 ms)`
`[INFO] Begin database maintenance`
`[INFO] End database maintenance (27162 ms)`
`Exception in thread "main" java.lang.ClassCastException: sun.net.www.protocol.file.FileURLConnection cannot be cast to java.net.HttpURLConnection
        at org.owasp.dependencycheck.utils.URLConnectionFactory.createHttpURLConnection(URLConnectionFactory.java:189)
        at org.owasp.dependencycheck.data.update.RetireJSDataSource.initializeRetireJsRepo(RetireJSDataSource.java:156)
        at org.owasp.dependencycheck.data.update.RetireJSDataSource.update(RetireJSDataSource.java:101)`
        `at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:915)`
        `at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:717)`
        `at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:652)`
        `at org.owasp.dependencycheck.App.runScan(App.java:246)`
        `at org.owasp.dependencycheck.App.run(App.java:179)`
       ` at org.owasp.dependencycheck.App.main(App.java:74)`

**Comment by jeremylong** [comment]
Sorry about that.  Apparently I like re-implementing the wheel...  I updated the code to download the RetireJS repo to use an already implemented and more robust download method.  This will be included in the next release.

**Comment by ErezDasa** [comment]
Thank you @jeremylong 
Until the next update I found a workaround. 
The first command is:

`dependency-check.bat --project test -s C:\temp\code  --cveUrlBase file:///C:/temp/Json/nvdcve-1.0-%d.json.gz --cveUrlModified file:///C:/temp/Json/nvdcve-1.0-modified.json.gz   --retireJsUrl file:///C:/temp/Js`

After DC built the "data" folder with the DB file I got the error message.

Than I write the same command and add "-n" for no updates and the scanning generate a report (finally...)

(anyway there are still error message when the scan is finished:
`[ERROR] Failed to initialize the RetireJS repo` )

Do you have any idea when the next version will be released?

Thank you again!

Erez

**Comment by jeremylong** [comment]
Another option would be to run in update only mode and then copy the retire JS file into the data directory.

We are hoping to push out the next release this week.
