### ISSUE TITLE
Gradle plugin 5.0.0 Build failure

### ISSUE THREAD

**Issue by din-eshch** [dependency-check/DependencyCheck#2016]
This is the only error message I see in the debug logs

```An error occurred while analyzing '/home/jenkins/.gradle/caches/5.4.1/generated-gradle-jars/gradle-api-5.4.1.jar' (Sonatype OSS Index Analyzer).```

Is there way to tell the gradle plugin to ignore/exclude certain paths or the geenrated gradle jars?

**Comment by jhunzik** [comment]
I saw something similar to this after upgrading to 5.0.0 from 5.0.0-M2: 
`An error occurred while analyzing '/Users/joshhunziker/.gradle/caches/modules-2/files-2.1/org.projectlombok/lombok/1.18.8/448003bc1b234aac04b58e27d7755c12c3ec4236/lombok-1.18.8.jar' (Sonatype OSS Index Analyzer).
`
For a workaround, I had to disable the OSS Index Analyzer with 
```
dependencyCheck {
        analyzers {
            ossIndexEnabled = false
        }
}
```
Could this possibly be a bug with the analyzer?

**Comment by jeremylong** [comment]
There is not an issue with the analyzer. Rather, the OSS Index service was unavailable for a period of time.
