### ISSUE TITLE
Sonatype OSS Index Analyzer analysis receiving HTTP 500 and failing the build

### ISSUE THREAD

**Issue by roddy** [dependency-check/DependencyCheck#2019]
**Describe the bug**
Sonatype OSS Index Analyzer analysis is throwing an exception because it receives an HTTP 500 response when getting the component report. This causes the Maven plugin mojo to fail, which causes the build to fail after the `check` goal.

This only started happening today, with no changes to this particular project (it's built on a schedule), so it's using the same dependencies that succeeded last week. 

**Version of dependency-check used**
Maven plugin version 5.0.0.

**Log file**
When running Maven with debug and error flags, the exception in [this gist](https://gist.github.com/roddy/96db28fc27d4d6a66093e88f17464856) is logged. There is nothing else relevant logged when running Maven with the `-X -e` flags.

**Expected behavior**
The error should not occur and the build should complete successfully.

**Additional context**
Issue (unsurprisingly) disappears when analysis is disabled. This may possibly be an issue only with certain dependencies. A separate project failed in the same way when when attempting to generate a report for `org/springframework/spring-beans/4.3.15.RELEASE/spring-beans-4.3.15.RELEASE.jar`. All dependency jars are retrieved from Maven central.

Both of these projects successfully built last week (20 June 2019) with no changes to their configuration and using the exact same dependencies (eg. the local m2 repository still has the same jars and metadata.)

Maven configuration of plugin:
```xml
<plugin>
  <groupId>org.owasp</groupId>
  <artifactId>dependency-check-maven</artifactId>
  <version>5.0.0</version>
  <configuration>
    <format>ALL</format>
    <skipProvidedScope>true</skipProvidedScope>
    <skipRuntimeScope>true</skipRuntimeScope>
    <assemblyAnalyzerEnabled>false</assemblyAnalyzerEnabled>
  </configuration>
  <executions>
    <execution>
      <goals>
        <goal>check</goal>
      </goals>
    </execution>
  </executions>
</plugin>
```

**Comment by albuch** [comment]
Duplicate of #2017

**Comment by jeremylong** [comment]
Unfortunately - when an external service is reporting a 500 error there is not much the dependency-check code can do other than report the service is failing.  It appears to be back up and running again.

**Comment by roddy** [comment]
It would be better if it didn't fail the whole build -- or do I need to file a feature request for that?

**Comment by afspear** [comment]
@roddy, I agree. @jeremylong, is there a reason it needs to fail the build?

**Comment by roddy** [comment]
@jeremylong - I possibly phrased my initial post poorly. The bug I was reporting wasn't that the external service was failing; it was that the maven plugin was failing the build due to these circumstances. If that's the intended behavior it needs to be documented somewhere, because it was entirely unexpected on this side of things. At most I would have expected this to flip the status to unstable similar to a Maven unit test failure.

**Comment by jeremylong** [comment]
With the case of dependency analysis - just because a build passed last week does not mean it should pass this week - new vulnerabilities may have been published. ODC failed because it was not able to complete its checks.  If you want to make the build more stable you can configure `<failOnError>false</failOnError>`.

**Comment by roddy** [comment]
Failing the build because vulnerabilities are found, or vulnerability threshholds are crossed makes sense. But that's not the same as having a vulnerability database/API go down and being able to not contact it. In my case, you could publish a million new vulnerabilities which all trigger in my service, and I'm not going to fail my build, because that how I've got it configured (which is the default, coincidentally.) Conflating the use cases isn't helping us in this case.

`<failOnError>` is a useful configuration but overly broad, I think. Not knowing what other "error" cases there might be, I don't want to change it on a whim. Destabilizing the build (eg. making it unstable like a failed unit test) would have been more useful and allow us to have been alerted that something is wrong with the build, but still allow the thing to _build_.

**Comment by jeremylong** [comment]
I completely understand what you are asking for - I just need help figuring out how to achieve the goal.  We absolutely need to start putting the errors into the report so they are more visible. That would allow you to set `failOnError` to false, let the build pass, and then after the fact determine if the scan was successful.  Any other ideas?
