### ISSUE TITLE
CLI searches nexus with an upper case hash when it's expecting a lower case one

### ISSUE THREAD

**Issue by sellersj** [dependency-check/DependencyCheck#202]
If you have the following dependency in your project, with the dependency check using nexus:

``` XML
<dependency>
    <groupId>org.springframework.ws</groupId>
    <artifactId>spring-ws-core</artifactId>
    <version>2.2.0.RELEASE</version>
</dependency>
```

If you run a maven report, you get different information compared to if you run a CLI report. I think that this is because the tool generates a sha1 hash that's upper case which doesn't match anything in nexus.

As a work around to nexus, the dependency check should lower case the hash before sending it.

I've opened a ticket with nexus.
https://issues.sonatype.org/browse/NEXUS-8324

**Comment by sellersj** [comment]
As a work around I modified the org.owasp.dependencycheck.utils.Checksum#getHex(byte[]) method to use .toLowerCase(Locale.ENGLISH) on the string before returning the hash. It now is able to search nexus and match the jar.

**Comment by jeremylong** [comment]
a patch was committed to resolve this issue.

Thanks for the bug report!

--Jeremy
