### ISSUE TITLE
unable to parse pom.xml

### ISSUE THREAD

**Issue by tiffanyzhou** [dependency-check/DependencyCheck#2022]
When I run jenkisn job , OWASP throw a PomParseException, and the detail show the XML structure error, but I check che XML structure is correct.
beside, I set the scanPath to pom.xml and jar path, the jenkins job both  show normally.

[DependencyCheck] OWASP Dependency-Check Plugin v4.0.2
[DependencyCheck] Executing Dependency-Check with the following options:
[DependencyCheck]  -name = fms-report-build
[DependencyCheck]  -scanPath = /data/fleet-services/workspace/workspace/fms-report-build
[DependencyCheck]  -outputDirectory = /data/fleet-services/workspace/workspace/fms-report-build/target
[DependencyCheck]  -dataDirectory = /data/cv/NVDUpdate
[DependencyCheck]  -dataMirroringType = none
[DependencyCheck]  -isQuickQueryTimestampEnabled = true
[DependencyCheck]  -jarAnalyzerEnabled = true
[DependencyCheck]  -nodePackageAnalyzerEnabled = false
[DependencyCheck]  -nodeAuditAnalyzerEnabled = false
[DependencyCheck]  -retireJsAnalyzerEnabled = false
[DependencyCheck]  -composerLockAnalyzerEnabled = false
[DependencyCheck]  -pythonDistributionAnalyzerEnabled = true
[DependencyCheck]  -pythonPackageAnalyzerEnabled = true
[DependencyCheck]  -rubyBundlerAuditAnalyzerEnabled = false
[DependencyCheck]  -rubyGemAnalyzerEnabled = false
[DependencyCheck]  -cocoaPodsAnalyzerEnabled = false
[DependencyCheck]  -swiftPackageManagerAnalyzerEnabled = false
[DependencyCheck]  -archiveAnalyzerEnabled = true
[DependencyCheck]  -assemblyAnalyzerEnabled = true
[DependencyCheck]  -msBuildProjectAnalyzerEnabled = false
[DependencyCheck]  -nuGetConfigAnalyzerEnabled = false
[DependencyCheck]  -nuspecAnalyzerEnabled = true
[DependencyCheck]  -centralAnalyzerEnabled = true
[DependencyCheck]  -nexusAnalyzerEnabled = false
[DependencyCheck]  -artifactoryAnalyzerEnabled = false
[DependencyCheck]  -autoconfAnalyzerEnabled = true
[DependencyCheck]  -cmakeAnalyzerEnabled = true
[DependencyCheck]  -opensslAnalyzerEnabled = true
[DependencyCheck]  -showEvidence = true
[DependencyCheck]  -formats = XML HTML 
[DependencyCheck]  -autoUpdate = false
[DependencyCheck]  -updateOnly = false
[DependencyCheck] Scanning: /data/fleet-services/workspace/workspace/fms-report-build
[DependencyCheck] Analyzing Dependencies
[DependencyCheck] One or more exceptions were thrown while executing Dependency-Check
[DependencyCheck] Exception Caught: org.owasp.dependencycheck.analyzer.exception.AnalysisException
[DependencyCheck] Cause: org.owasp.dependencycheck.xml.pom.PomParseException: Unable to parse pom '/tmp/dctempbe0ad386-f8d2-4d93-9bd1-c601b38baba6/check2575735241557126718tmp/6516/pom.xml'
[DependencyCheck] Message: A error occurred extracing evidence from RTAFmsEmailAdaptar-1.0-20170601.050247-1.jar, analysis may be incomplete; please see the log for more details.
[DependencyCheck] org.owasp.dependencycheck.analyzer.exception.AnalysisException: A error occurred extracing evidence from RTAFmsEmailAdaptar-1.0-20170601.050247-1.jar, analysis may be incomplete; please see the log for more details.
[DependencyCheck] 	at org.owasp.dependencycheck.analyzer.JarAnalyzer.analyzeDependency(JarAnalyzer.java:294)
[DependencyCheck] 	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:136)
[DependencyCheck] 	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
[DependencyCheck] 	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
[DependencyCheck] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[DependencyCheck] 	at java.lang.Thread.run(Thread.java:748)
[DependencyCheck] Caused by: org.owasp.dependencycheck.analyzer.exception.AnalysisException: org.owasp.dependencycheck.xml.pom.PomParseException: Unable to parse pom '/tmp/dctempbe0ad386-f8d2-4d93-9bd1-c601b38baba6/check2575735241557126718tmp/6516/pom.xml'
[DependencyCheck] 	at org.owasp.dependencycheck.xml.pom.PomUtils.readPom(PomUtils.java:82)
[DependencyCheck] 	at org.owasp.dependencycheck.analyzer.JarAnalyzer.analyzePOM(JarAnalyzer.java:389)
[DependencyCheck] 	at org.owasp.dependencycheck.analyzer.JarAnalyzer.analyzeDependency(JarAnalyzer.java:284)
[DependencyCheck] 	... 7 more
[DependencyCheck] Caused by: org.owasp.dependencycheck.xml.pom.PomParseException: Unable to parse pom '/tmp/dctempbe0ad386-f8d2-4d93-9bd1-c601b38baba6/check2575735241557126718tmp/6516/pom.xml'
[DependencyCheck] 	at org.owasp.dependencycheck.xml.pom.PomParser.parse(PomParser.java:69)
[DependencyCheck] 	at org.owasp.dependencycheck.xml.pom.PomUtils.readPom(PomUtils.java:62)
[DependencyCheck] 	... 9 more
[DependencyCheck] Caused by: org.owasp.dependencycheck.xml.pom.PomParseException: org.xml.sax.SAXParseException; lineNumber: 267; columnNumber: 11; XML document structures must start and end within the same entity.
[DependencyCheck] 	at org.owasp.dependencycheck.xml.pom.PomParser.parse(PomParser.java:98)
[DependencyCheck] 	at org.owasp.dependencycheck.xml.pom.PomParser.parse(PomParser.java:66)
[DependencyCheck] 	... 10 more
[DependencyCheck] Caused by: org.xml.sax.SAXParseException; lineNumber: 267; columnNumber: 11; XML document structures must start and end within the same entity.
[DependencyCheck] 	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
[DependencyCheck] 	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
[DependencyCheck] 	at org.owasp.dependencycheck.xml.pom.PomParser.parse(PomParser.java:94)
[DependencyCheck] 	... 11 more
[DependencyCheck] 
Build step 'Invoke Dependency-Check analysis' changed build result to FAILURE

**Comment by jeremylong** [comment]
If you unzip `RTAFmsEmailAdaptar-1.0-20170601.050247-1.jar` - take a look at the pom.xml files contained in the META-INF directory. Do any exist and do they look well formed?

**Comment by tiffanyzhou** [comment]
I unzipped the RTAFmsEmailAdaptar-1.0-20170601.050247-1.jar file ,and found the pom.xml in META-INF directory, but it looks correct.
I have uploaded this pom file, could you please help to check if there is any problem?  thanks a lot.

[pom.zip](https://github.com/jeremylong/DependencyCheck/files/3327901/pom.zip)

**Comment by jeremylong** [comment]
So funny thing - in order to deal with some other issues around doctype definitions we implemented an rather naive InputStream that would skip to the start of the `<project>` node.  However, this causes your completely valid `pom.xml` to fail parsing because it has a commented out project node at the top of the pom.xml:


```xml
<!-- <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"> -->
	
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
```

So while we try to figure out the best way to handle this and the other issues that have been reported - could you simply remove the comment from the top of the pom.xml?
