### ISSUE TITLE
gradle dependencyCheckAnalyze 5.0.0 task fails with NPE if the NVD database cannot be downloaded 

### ISSUE THREAD

**Issue by jthurne** [dependency-check/DependencyCheck#2023]
**Describe the bug**
In some cases (and I'm not entirely sure which cases), the Gradle dependencyCheckAnalyze plugin will fail with a NullPointerException if it is unable to update the local vulnerability database (for example, if the NVD site is down, or as in the example here, if the NVD site returns 403 HTTP responses to all HTTP requests). The NPE causes the build to fail.

A workaround is to set autoUpdate to false in the task configuration in the project's build.gradle (which prevents the task from trying to download updates). This workaround is not suitable for Continuous Integration servers or builds.

** Version of dependency-check used **
The problem occurs using version 5.0.0 of the the gradle plugin. I'm using Gradle 5.2.1.

** Log file **
See [this build log](https://gist.github.com/jthurne/2caea8312b7890d751929e9dbd9aa948) (generated using `gradle --info --stacktrace dependencyCheckAnalyze`)

**To Reproduce**
Try to run dependencyCheckAnalyze when the NVD website is down. You may be able to simulate this by setting a local HTTP sever that always returns `403 Forbidden` for every request and pointing the plugin to that instead of the real NVD website.

**Expected behavior**
The analysis should proceed with the previously cached data, and the build should not fail.

**Additional context**
My task configuration:

```
dependencyCheck {
    format = 'ALL'
    failOnError = false
    suppressionFile = "$rootDir/owasp-suppressions.xml"
    hintsFile = "$rootDir/owasp-hints.xml"
    scanConfigurations += "default"
    analyzers {
        assemblyEnabled = false
    }
}
```

**Comment by dh1337** [comment]
Is there anything we can do to help fixing this?
I also added my NPE [log](https://gist.github.com/denishamann1337/389e98e2f21c10b507e5f89296fd5d56)

**Comment by dh1337** [comment]
I found the corresponding issue in the gradle-plugin: https://github.com/jeremylong/dependency-check-gradle/issues/135
Thanks for taking care!
