### ISSUE TITLE
False Positive on [javax.servlet.jstl]

### ISSUE THREAD

**Issue by nohn** [dependency-check/DependencyCheck#2024]
False positive on library jstl-1.2.jar - reported as `cpe:2.3:a:apache:standard_taglibs:*:*:*:*:*:*:*:*`
```xml
<!-- https://mvnrepository.com/artifact/javax.servlet/jstl -->
<dependency>
    <groupId>javax.servlet</groupId>
    <artifactId>jstl</artifactId>
    <version>1.2</version>
</dependency>
```

**Comment by jeremylong** [comment]
What version of dependency-check are you using?

**Comment by nohn** [comment]
dependency-check-maven 5.0.0

**Comment by jeremylong** [comment]
This is actually reported by the OSS Index analyzer.  In this case - if you feel this is a false positive please create a suppression file for your local analysis.  This can be done using 5.1.0 or higher.

**Comment by jeremylong** [comment]
Another option would be to create a report here: https://ossindex.sonatype.org/report-vulnerability
