### ISSUE TITLE
False Positive on spring-security-jwt

### ISSUE THREAD

**Issue by OrangeDog** [dependency-check/DependencyCheck#2027]
False positive on library spring-security-jwt-1.0.10.RELEASE.jar - reported as `cpe:2.3:a:org.springframework.security:spring-security-jwt:1.0.10.RELEASE:*:*:*:*:*:*:*`
```xml
<dependency>
   <groupId>org.springframework.security</groupId>
   <artifactId>spring-security-jwt</artifactId>
   <version>1.0.10.RELEASE</version>
</dependency>
```
New problem in 5.0.0 (from 4.0.2).
This reports CWE-79 from OSSINDEX, but that was [apparently fixed years ago](https://github.com/spring-projects/spring-security-oauth/issues/889).

**Comment by OrangeDog** [comment]
I've reported it https://github.com/OSSIndex/vulns/issues/15
The actual "Report advisory/correction" button didn't work, so that may not be the right place.

**Comment by jeremylong** [comment]
As this is an OSS Index finding - we should wait for them to resolve the issue.  In the meantime, using 5.1.0 or higher you can suppress this finding in your local system.
