### ISSUE TITLE
Question: Suppress from

### ISSUE THREAD

**Issue by malejpavouk** [dependency-check/DependencyCheck#2035]
It is possible to have a "until" in suppression rules to limit scope of suppression evalution. Is it also possible to somehow suppress all violations of CVEs newer than some date?

---

Use case: When we build our application, we want to have reproducible builds - once build succeeds, it all subsequent builds of the same commit/tag must consistently succeed. But with default behavior of DepCheck it is possible that some index will get updated, and the analysis will fail.

**Comment by jeremylong** [comment]
"Until" was already added - see the page on false positives that provides examples of suppression rules: https://jeremylong.github.io/DependencyCheck/general/suppression.html

New CVEs could be published and the build could "break" depending on your configuration. My suggestion would to not have the dependency-check fail the build when vulnerabilities are detected (i.e. leave the `failBuildOnCVSS` at the default of 11).

**Comment by malejpavouk** [comment]
ok, thx
