### ISSUE TITLE
Error in Dependency check scans 5.0.2 and 4.0.2

### ISSUE THREAD

**Issue by vaishravin** [dependency-check/DependencyCheck#2036]
Error in Dependency check scans 5.0.2 and 4.0.2 

We are trying to scan a Java project in command line utility. We tried with both 4.0.2 and 5.0.2 and we are getting errors. Please advise. 
4.0.2  :
[ERROR] IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve
-2.0-2002.xml.gz: sun.security.validator.ValidatorException: PKIX path building
failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to fi
nd valid certification path to requested target
[ERROR] IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve
-2.0-2007.xml.gz: sun.security.validator.ValidatorException: PKIX path building
failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to fi
nd valid certification path to requested target
[ERROR] IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve
-2.0-2010.xml.gz: sun.security.validator.ValidatorException: PKIX path building
failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to fi
nd valid certification path to requested target
[ERROR] IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve
-2.0-2009.xml.gz: sun.security.validator.ValidatorException: PKIX path building
failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to fi
nd valid certification path to requested target
[ERROR] IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve
-2.0-2018.xml.gz: sun.security.validator.ValidatorException: PKIX path building
failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to fi
nd valid certification path to requested target
[ERROR] IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve
-2.0-2008.xml.gz: sun.security.validator.ValidatorException: PKIX path building
failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to fi
nd valid certification path to requested target
[WARN] Unable to download the NVD CVE data; the results may not include the most
recent CPE/CVEs from the NVD.
[WARN] Unable to update Cached Web DataSource, using local data instead. Results
may not include recent vulnerabilities.
[INFO] Analysis Started
[INFO] Finished File Name Analyzer (0 seconds)
[ERROR] IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve
-2.0-2011.xml.gz: sun.security.validator.ValidatorException: PKIX path building
failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to fi
nd valid certification path to requested target
[ERROR] IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve
-2.0-2006.xml.gz: sun.security.validator.ValidatorException: PKIX path building
failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to fi
nd valid certification path to requested target
[ERROR] IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve
-2.0-2003.xml.gz: sun.security.validator.ValidatorException: PKIX path building
failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to fi
nd valid certification path to requested target
[ERROR] IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve
-2.0-2005.xml.gz: sun.security.validator.ValidatorException: PKIX path building
failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to fi
nd valid certification path to requested target
[ERROR] IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve
-2.0-2004.xml.gz: sun.security.validator.ValidatorException: PKIX path building
failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to fi
nd valid certification path to requested target
[ERROR] IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve
-2.0-2010.xml.gz: sun.security.validator.ValidatorException: PKIX path building
failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to fi
nd valid certification path to requested target

5.0.0:
[Error] Failed to initialise the retire.js repo
[warn]Unabl to update 1 or more cached web datasource, using local data instead. Results may not include recent vulnerabilities.
[Errors]Unable to continue dependency check analysis
[Error]one or more fatal error occured
[error]Failed to initialize the retirejs repo
[error]no document exists.

**Comment by mprins** [comment]
> [ERROR] IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve
-2.0-2002.xml.gz: sun.security.validator.ValidatorException: PKIX path building
failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to fi
nd valid certification path to requested target

Your JVM cannot validate the TLS certificate, probabably you are missing root certificates or your "cacerts" file is corrupt

**Comment by jeremylong** [comment]
See https://confluence.atlassian.com/kb/unable-to-connect-to-ssl-services-due-to-pkix-path-building-failed-779355358.html as referenced in previous tickets (https://github.com/jeremylong/DependencyCheck/issues/1057).

What version of Java are you using?

**Comment by vaishravin** [comment]
We are using Java version 1.8.0_131. I checked the link provided. But we don't use Jira. We just use the standalone utility.

**Comment by jeremylong** [comment]
You misunderstood the point of the link; the article is a general guide on trust store issues - it is not directly related to Jira.

**Comment by vaishravin** [comment]
I tried adding it to the keystore after importing the .cer certificate with the below.
keytool -importcert -file <path> and was imported. Even then am facing the error. Again I will relook the link provided.

#5: ObjectId: 2.5.29.17 Criticality=false
SubjectAlternativeName [
  DNSName: nvd.nist.gov
  DNSName: icat.nist.gov
  DNSName: web.nvd.nist.gov
  DNSName: static.nvd.nist.gov
  DNSName: services.nvd.nist.gov
  DNSName: checklists.nist.gov
  DNSName: scap.nist.gov
  DNSName: beacon.nist.gov
  DNSName: usgcb.nist.gov
  DNSName: fdcc.nist.gov
  DNSName: csrc.nist.gov
  DNSName: sbc.nist.gov
  DNSName: scrm.nist.gov
  DNSName: auth.nvd.nist.gov
]
Trust this certificate? [no]:  yes
Certificate was added to keystore
