### ISSUE TITLE
Invalid credentials provided for OSS Index

### ISSUE THREAD

**Issue by edmacke** [dependency-check/DependencyCheck#2041]
Just installed v 5.1.0 of DependencyCheck.

I didn't change anything except to fix the batch file bug related to classpath.

Upon running, I'm getting _[WARN] An error occurred while analyzing 'foo.jar' (Sonatype OSS Index Analyzer)_. Then, later, _[ERROR] Invalid credentials provided for OSS Index_

What is going on?

**Comment by edmacke** [comment]
Update: installed v5.2.0, and the error is still happening.

It also appears to be machine-dependent; I can run the app on one machine and it scans fine, but on another machine the error happens.

**Comment by jeremylong** [comment]
Have you configured credentials for the OSS Index Analyzer?

**Comment by edmacke** [comment]
No, I just install the app and run it. I don't see anything in the doc about having to configure creds for OSS Index Analyzer, nor would I know what credentials to provide. Also, if credentials are something I'm supposed to configure, why does the app work out-of-the-box for most machines, but fails for others? Thanks!

**Comment by jeremylong** [comment]
On the machine that is failing - can you provide the log file (i.e. `dependency-check.sh -s target -o . -l odc.log`)?

**Comment by edmacke** [comment]
Sorry, I meant to do that in the previous post and forgot.

On line 4101, we get a WARN that something is wrong, then on line 9723 we see the invalid credentials.

[dc.log](https://github.com/jeremylong/DependencyCheck/files/3427003/dc.log)

**Comment by jeremylong** [comment]
@jdillon any idea why the OSS Index is returning a 401 in this case?  No credentials were provided.

**Comment by jdillon** [comment]
@jeremylong ATM no I'm not sure why a 401 would be returned w/o credentials.

> It also appears to be machine-dependent; I can run the app on one machine and it scans fine, but on another machine the error happens.

... sounds a bit fishy, any idea what might be different between systems where it fails (with odd 401) and systems where it does not?

**Comment by jdillon** [comment]
@edmacke Do you know if using the REST API directly from the system which you mentioned has trouble with ODC also returns a 401?

https://ossindex.sonatype.org/rest

Or if one of the other integrations, like the Maven Plugin ( https://sonatype.github.io/ossindex-maven/maven-plugin/ ) also behaves oddly too on that system?

**Comment by edmacke** [comment]
I don't know. We have our developers install the application on their local machines, which is basically just copying the app to "c:\program files" and adding to the path. We don't do any configuration, we don't use the API, we don't use the Maven plugin.... we just always run it from the CLI.

**Comment by jdillon** [comment]
@edmacke what I'm asking is if you can try one of the other options, to help isolate the `machine-dependent` problem from ODC.  For example if you use the REST api directly with curl or something if it also behaves the same with a 401 then its clearly not an issue with ODC, or the ossindex-client.

ATM just trying to see if more information about the `machine-dependent` problem can be uncovered.

**Comment by agilang** [comment]
I had the same problem and found out that my machine was internally using proxy credentials and it got timed out. When browsed some websites, it asked for password and once done. it worked fine.

**Comment by jeremylong** [comment]
Due to a lack of response from the original reporter - I am closing this issue.  If the problem persists - please re-report the problem.
