### ISSUE TITLE
Not seeing release 5.1.0

### ISSUE THREAD

**Issue by Jarl-dev** [dependency-check/DependencyCheck#2042]
In the release notes 5.1.0 is mentioned and there is a link for it on the Owasp page for the command line version.

But from what I can see that download is still using the old suppression xsd (version 1.2)

Am I correct in that 5.1.0 is not fully released yet?

**Comment by jeremylong** [comment]
Not sure I understand your question.  5.1.0 is fully released.  If you generate a new suppression rule/file using the 5.1.0 HTML report it will utilize the 1.3 schema.  However, you can still use suppression files that use the 1.2 XSD.  We try to keep things backwards compatible.

**Comment by Jarl-dev** [comment]
I do not see 5.1.0 on the releases tab in Github.
But the issue must be that we did not generate a new file, but still used the old one.
I will test that. Thank you.

We are getting a 404 on https://jeremylong.github.io/DependencyCheck/dependency-suppression.1.3.xsd which is referenced in the xml though

**Comment by jeremylong** [comment]
So...  you ever feel really stupid after performing a release?  Kind of like I do right now? I did everything except run:

```
git push origin master --tags
```

As such, the gh-pages did not get updated nor did the release get added to github.  I just pushed the tag which should update everything.
