### ISSUE TITLE
Dependency-Check fails with below errors

### ISSUE THREAD

**Issue by pkattaqsr-admin** [dependency-check/DependencyCheck#2044]
Dependency-Check fails with below errors, Is there a switch to ignore these errors and continue with report other than excluding these files
[WARN] An unexpected error occurred during analysis of 'netstandard2.0\bin\Microsoft.IdentityModel.Clients.ActiveDirectory.Platform.dll' (Assembly Analyzer): null
[ERROR]
java.lang.NullPointerException: null

[WARN] An unexpected error occurred during analysis of 'netstandard2.0\bin\Microsoft.IdentityModel.Clients.ActiveDirectory.dll' (Assembly Analyzer): null
[ERROR]
java.lang.NullPointerException: null

**Comment by jeremylong** [comment]
This was fixed with #2000 and #1848.
