### ISSUE TITLE
dependency check failing with the following error

### ISSUE THREAD

**Issue by HarshitMit** [dependency-check/DependencyCheck#2045]
When running the dependency check version 5.0.0 , the scan keeps failing with the following issue

[ERROR] Error retrieving https://search.maven.org/remotecontent?filepath=cn/easyproject/xdb6/12.1.0.2.0/xdb6-12.1.0.2.0.pom; received response code 404.
[ERROR] Error retrieving https://search.maven.org/remotecontent?filepath=cn/easyproject/xdb6/12.1.0.2.0/xdb6-12.1.0.2.0.pom; received response code 404.
[ERROR] Error retrieving https://search.maven.org/remotecontent?filepath=cn/easyproject/xdb6/12.1.0.2.0/xdb6-12.1.0.2.0.pom; received response code 404.
[ERROR] Error retrieving https://search.maven.org/remotecontent?filepath=cn/easyproject/xdb6/12.1.0.2.0/xdb6-12.1.0.2.0.pom; received response code 404.
[ERROR] Error retrieving https://search.maven.org/remotecontent?filepath=cn/easyproject/xdb6/12.1.0.2.0/xdb6-12.1.0.2.0.pom; received response code 404.
[ERROR] Error retrieving https://search.maven.org/remotecontent?filepath=cn/easyproject/xdb6/12.1.0.2.0/xdb6-12.1.0.2.0.pom; received response code 404.
[ERROR] Analysis task was cancelled.
[WARN] An unexpected error occurred during analysis of '/tmp/dctempf13ffeec-fe05-4220-aea5-0bc963fcbbcc/check8297358656620688052tmp/1/WEB-INF/lib/xdb6-11.2.0.jar' (Central Analyzer): java.lang.InterruptedException: sleep interrupted
[ERROR] 
org.owasp.dependencycheck.analyzer.exception.UnexpectedAnalysisException: java.lang.InterruptedException: sleep interrupted

could you please let me know how we can skip this step and proceed with the check even if this fails. Any help is much appreciated. Thanks

**Comment by cy4n** [comment]
you can disable the Central analyzer if you mean that by "this step"

**Comment by HarshitMit** [comment]
The scan is working fine after invoking OWASP scan through the maven plugin.
