### ISSUE TITLE
A bit logic improvement

### ISSUE THREAD

**Issue by bigstinky86** [dependency-check/DependencyCheck#2051]
Hi there,

During a code testing with usage of the dependency-check cli we've found out that with several report types set in cli arguments it runs as much times as output formats specified (-f flag).

I'd like to suggest improvement as it dosen't make sense to run scan in this way. I believe it should be better to run scan one time and the report generation as much as was specified in cli args :)

**Comment by jeremylong** [comment]
Thanks for noticing the error and submitting the PR!  We are likely going to be pushing a release this weekend.
