### ISSUE TITLE
Error querying CPE data.

### ISSUE THREAD

**Issue by derek126** [dependency-check/DependencyCheck#2055]
I am using the Jenkins plugin (5.0.0) with version 5.1.0

14:12:22 [DependencyCheck] [INFO] Created CPE Index (2 seconds)
14:12:28 [DependencyCheck] [WARN] An error occurred querying the CPE data. See the log for more details.
14:12:28 [DependencyCheck] [INFO] Unable to parse: product:() AND vendor:()
14:12:28 [DependencyCheck] org.apache.lucene.queryparser.classic.ParseException: Cannot parse 'product:() AND vendor:()': Encountered " ")" ") "" at line 1, column 9.
14:12:28 [DependencyCheck] Was expecting one of:
14:12:28 [DependencyCheck]     <NOT> ...
14:12:28 [DependencyCheck]     "+" ...
14:12:28 [DependencyCheck]     "-" ...
14:12:28 [DependencyCheck]     <BAREOPER> ...
14:12:28 [DependencyCheck]     "(" ...
14:12:28 [DependencyCheck]     "*" ...
14:12:28 [DependencyCheck]     <QUOTED> ...
14:12:28 [DependencyCheck]     <TERM> ...
14:12:28 [DependencyCheck]     <PREFIXTERM> ...
14:12:28 [DependencyCheck]     <WILDTERM> ...
14:12:28 [DependencyCheck]     <REGEXPTERM> ...
14:12:28 [DependencyCheck]     "[" ...
14:12:28 [DependencyCheck]     "{" ...
14:12:28 [DependencyCheck]     <NUMBER> ...
14:12:28 [DependencyCheck]     <TERM> ...
14:12:28 [DependencyCheck]     
14:12:28 [DependencyCheck] 	at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:114)
14:12:28 [DependencyCheck] 	at org.owasp.dependencycheck.data.cpe.CpeMemoryIndex.parseQuery(CpeMemoryIndex.java:286)
14:12:28 [DependencyCheck] 	at org.owasp.dependencycheck.analyzer.CPEAnalyzer.searchCPE(CPEAnalyzer.java:398)
14:12:28 [DependencyCheck] 	at org.owasp.dependencycheck.analyzer.CPEAnalyzer.determineCPE(CPEAnalyzer.java:260)
14:12:28 [DependencyCheck] 	at org.owasp.dependencycheck.analyzer.CPEAnalyzer.analyzeDependency(CPEAnalyzer.java:696)
14:12:28 [DependencyCheck] 	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
14:12:28 [DependencyCheck] 	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
14:12:28 [DependencyCheck] 	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
14:12:28 [DependencyCheck] 	at java.util.concurrent.FutureTask.run(Unknown Source)
14:12:28 [DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
14:12:28 [DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
14:12:28 [DependencyCheck] 	at java.lang.Thread.run(Unknown Source)
14:12:28 [DependencyCheck] Caused by: org.apache.lucene.queryparser.classic.ParseException: Encountered " ")" ") "" at line 1, column 9.
14:12:28 [DependencyCheck] Was expecting one of:
14:12:28 [DependencyCheck]     <NOT> ...
14:12:28 [DependencyCheck]     "+" ...
14:12:28 [DependencyCheck]     "-" ...
14:12:28 [DependencyCheck]     <BAREOPER> ...
14:12:28 [DependencyCheck]     "(" ...
14:12:28 [DependencyCheck]     "*" ...
14:12:28 [DependencyCheck]     <QUOTED> ...
14:12:28 [DependencyCheck]     <TERM> ...
14:12:28 [DependencyCheck]     <PREFIXTERM> ...
14:12:28 [DependencyCheck]     <WILDTERM> ...
14:12:28 [DependencyCheck]     <REGEXPTERM> ...
14:12:28 [DependencyCheck]     "[" ...
14:12:28 [DependencyCheck]     "{" ...
14:12:28 [DependencyCheck]     <NUMBER> ...
14:12:28 [DependencyCheck]     <TERM> ...
14:12:28 [DependencyCheck]     
14:12:28 [DependencyCheck] 	at org.apache.lucene.queryparser.classic.QueryParser.generateParseException(QueryParser.java:931)
14:12:28 [DependencyCheck] 	at org.apache.lucene.queryparser.classic.QueryParser.jj_consume_token(QueryParser.java:813)
14:12:28 [DependencyCheck] 	at org.apache.lucene.queryparser.classic.QueryParser.Query(QueryParser.java:252)
14:12:28 [DependencyCheck] 	at org.apache.lucene.queryparser.classic.QueryParser.Clause(QueryParser.java:359)
14:12:28 [DependencyCheck] 	at org.apache.lucene.queryparser.classic.QueryParser.Query(QueryParser.java:244)
14:12:28 [DependencyCheck] 	at org.apache.lucene.queryparser.classic.QueryParser.TopLevelQuery(QueryParser.java:215)
14:12:28 [DependencyCheck] 	at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:109)
14:12:28 [DependencyCheck] 	... 11 common frames omitted
14:12:28 [DependencyCheck] [WARN] An error occurred querying the CPE data. See the log for more details.
14:12:28 [DependencyCheck] [INFO] Unable to parse: product:() AND vendor:()
14:12:28 [DependencyCheck] org.apache.lucene.queryparser.classic.ParseException: Cannot parse 'product:() AND vendor:()': Encountered " ")" ") "" at line 1, column 9.
14:12:28 [DependencyCheck] Was expecting one of:
14:12:28 [DependencyCheck]     <NOT> ...
14:12:28 [DependencyCheck]     "+" ...
14:12:28 [DependencyCheck]     "-" ...
14:12:28 [DependencyCheck]     <BAREOPER> ...
14:12:28 [DependencyCheck]     "(" ...
14:12:28 [DependencyCheck]     "*" ...
14:12:28 [DependencyCheck]     <QUOTED> ...
14:12:28 [DependencyCheck]     <TERM> ...
14:12:28 [DependencyCheck]     <PREFIXTERM> ...
14:12:28 [DependencyCheck]     <WILDTERM> ...
14:12:28 [DependencyCheck]     <REGEXPTERM> ...
14:12:28 [DependencyCheck]     "[" ...
14:12:28 [DependencyCheck]     "{" ...
14:12:28 [DependencyCheck]     <NUMBER> ...
14:12:28 [DependencyCheck]     <TERM> ...
14:12:28 [DependencyCheck]     
14:12:28 [DependencyCheck] 	at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:114)
14:12:28 [DependencyCheck] 	at org.owasp.dependencycheck.data.cpe.CpeMemoryIndex.parseQuery(CpeMemoryIndex.java:286)
14:12:28 [DependencyCheck] 	at org.owasp.dependencycheck.analyzer.CPEAnalyzer.searchCPE(CPEAnalyzer.java:398)
14:12:28 [DependencyCheck] 	at org.owasp.dependencycheck.analyzer.CPEAnalyzer.determineCPE(CPEAnalyzer.java:260)
14:12:28 [DependencyCheck] 	at org.owasp.dependencycheck.analyzer.CPEAnalyzer.analyzeDependency(CPEAnalyzer.java:696)
14:12:28 [DependencyCheck] 	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
14:12:28 [DependencyCheck] 	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
14:12:28 [DependencyCheck] 	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
14:12:28 [DependencyCheck] 	at java.util.concurrent.FutureTask.run(Unknown Source)
14:12:28 [DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
14:12:28 [DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
14:12:28 [DependencyCheck] 	at java.lang.Thread.run(Unknown Source)
14:12:28 [DependencyCheck] Caused by: org.apache.lucene.queryparser.classic.ParseException: Encountered " ")" ") "" at line 1, column 9.
14:12:28 [DependencyCheck] Was expecting one of:
14:12:28 [DependencyCheck]     <NOT> ...
14:12:28 [DependencyCheck]     "+" ...
14:12:28 [DependencyCheck]     "-" ...
14:12:28 [DependencyCheck]     <BAREOPER> ...
14:12:28 [DependencyCheck]     "(" ...
14:12:28 [DependencyCheck]     "*" ...
14:12:28 [DependencyCheck]     <QUOTED> ...
14:12:28 [DependencyCheck]     <TERM> ...
14:12:28 [DependencyCheck]     <PREFIXTERM> ...
14:12:28 [DependencyCheck]     <WILDTERM> ...
14:12:28 [DependencyCheck]     <REGEXPTERM> ...
14:12:28 [DependencyCheck]     "[" ...
14:12:28 [DependencyCheck]     "{" ...
14:12:28 [DependencyCheck]     <NUMBER> ...
14:12:28 [DependencyCheck]     <TERM> ...
14:12:28 [DependencyCheck]     
14:12:28 [DependencyCheck] 	at org.apache.lucene.queryparser.classic.QueryParser.generateParseException(QueryParser.java:931)
14:12:28 [DependencyCheck] 	at org.apache.lucene.queryparser.classic.QueryParser.jj_consume_token(QueryParser.java:813)
14:12:28 [DependencyCheck] 	at org.apache.lucene.queryparser.classic.QueryParser.Query(QueryParser.java:252)
14:12:28 [DependencyCheck] 	at org.apache.lucene.queryparser.classic.QueryParser.Clause(QueryParser.java:359)
14:12:28 [DependencyCheck] 	at org.apache.lucene.queryparser.classic.QueryParser.Query(QueryParser.java:244)
14:12:28 [DependencyCheck] 	at org.apache.lucene.queryparser.classic.QueryParser.TopLevelQuery(QueryParser.java:215)
14:12:28 [DependencyCheck] 	at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:109)
14:12:28 [DependencyCheck] 	... 11 common frames omitted
14:12:28 [DependencyCheck] [WARN] An error occurred querying the CPE data. See the log for more details.
14:12:28 [DependencyCheck] [INFO] Unable to parse: product:() AND vendor:()
14:12:28 [DependencyCheck] org.apache.lucene.queryparser.classic.ParseException: Cannot parse 'product:() AND vendor:()': Encountered " ")" ") "" at line 1, column 9.
14:12:28 [DependencyCheck] Was expecting one of:
14:12:28 [DependencyCheck]     <NOT> ...
14:12:28 [DependencyCheck]     "+" ...
14:12:28 [DependencyCheck]     "-" ...
14:12:28 [DependencyCheck]     <BAREOPER> ...
14:12:28 [DependencyCheck]     "(" ...
14:12:28 [DependencyCheck]     "*" ...
14:12:28 [DependencyCheck]     <QUOTED> ...
14:12:28 [DependencyCheck]     <TERM> ...
14:12:28 [DependencyCheck]     <PREFIXTERM> ...
14:12:28 [DependencyCheck]     <WILDTERM> ...
14:12:28 [DependencyCheck]     <REGEXPTERM> ...
14:12:28 [DependencyCheck]     "[" ...
14:12:28 [DependencyCheck]     "{" ...
14:12:28 [DependencyCheck]     <NUMBER> ...
14:12:28 [DependencyCheck]     <TERM> ...
14:12:28 [DependencyCheck]     
14:12:28 [DependencyCheck] 	at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:114)
14:12:28 [DependencyCheck] 	at org.owasp.dependencycheck.data.cpe.CpeMemoryIndex.parseQuery(CpeMemoryIndex.java:286)
14:12:28 [DependencyCheck] 	at org.owasp.dependencycheck.analyzer.CPEAnalyzer.searchCPE(CPEAnalyzer.java:398)
14:12:28 [DependencyCheck] 	at org.owasp.dependencycheck.analyzer.CPEAnalyzer.determineCPE(CPEAnalyzer.java:260)
14:12:28 [DependencyCheck] 	at org.owasp.dependencycheck.analyzer.CPEAnalyzer.analyzeDependency(CPEAnalyzer.java:696)
14:12:28 [DependencyCheck] 	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
14:12:28 [DependencyCheck] 	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
14:12:28 [DependencyCheck] 	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
14:12:28 [DependencyCheck] 	at java.util.concurrent.FutureTask.run(Unknown Source)
14:12:28 [DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
14:12:28 [DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
14:12:28 [DependencyCheck] 	at java.lang.Thread.run(Unknown Source)
14:12:28 [DependencyCheck] Caused by: org.apache.lucene.queryparser.classic.ParseException: Encountered " ")" ") "" at line 1, column 9.
14:12:28 [DependencyCheck] Was expecting one of:
14:12:28 [DependencyCheck]     <NOT> ...
14:12:28 [DependencyCheck]     "+" ...
14:12:28 [DependencyCheck]     "-" ...
14:12:28 [DependencyCheck]     <BAREOPER> ...
14:12:28 [DependencyCheck]     "(" ...
14:12:28 [DependencyCheck]     "*" ...
14:12:28 [DependencyCheck]     <QUOTED> ...
14:12:28 [DependencyCheck]     <TERM> ...
14:12:28 [DependencyCheck]     <PREFIXTERM> ...
14:12:28 [DependencyCheck]     <WILDTERM> ...
14:12:28 [DependencyCheck]     <REGEXPTERM> ...
14:12:28 [DependencyCheck]     "[" ...
14:12:28 [DependencyCheck]     "{" ...
14:12:28 [DependencyCheck]     <NUMBER> ...
14:12:28 [DependencyCheck]     <TERM> ...
14:12:28 [DependencyCheck]     
14:12:28 [DependencyCheck] 	at org.apache.lucene.queryparser.classic.QueryParser.generateParseException(QueryParser.java:931)
14:12:28 [DependencyCheck] 	at org.apache.lucene.queryparser.classic.QueryParser.jj_consume_token(QueryParser.java:813)
14:12:28 [DependencyCheck] 	at org.apache.lucene.queryparser.classic.QueryParser.Query(QueryParser.java:252)
14:12:28 [DependencyCheck] 	at org.apache.lucene.queryparser.classic.QueryParser.Clause(QueryParser.java:359)
14:12:28 [DependencyCheck] 	at org.apache.lucene.queryparser.classic.QueryParser.Query(QueryParser.java:244)
14:12:28 [DependencyCheck] 	at org.apache.lucene.queryparser.classic.QueryParser.TopLevelQuery(QueryParser.java:215)
14:12:28 [DependencyCheck] 	at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:109)
14:12:28 [DependencyCheck] 	... 11 common frames omitted
14:12:40 [DependencyCheck] [INFO] Finished CPE Analyzer (21 seconds)

I have not been able to figure this one out. Any thoughts?

**Comment by jeremylong** [comment]
Looking at the errors and code I can see how this might occur.  Additional checks have been added that should resolve this issue in the next release.
