### ISSUE TITLE
Unable to update the Dependency-Check database

### ISSUE THREAD

**Issue by tiffanyzhou** [dependency-check/DependencyCheck#2057]
I configuretion a NVD database , when I run a jenkins job to update the Dependency-Check database, then always FAILURE

[DependencyCheck] OWASP Dependency-Check Plugin v4.0.2
[DependencyCheck] Executing Dependency-Check with the following options:
[DependencyCheck]  -name = Auto-update-NVD
[DependencyCheck]  -outputDirectory = /data/cv/workspace/Auto-update-NVD
[DependencyCheck]  -dataDirectory = /data/cv/NVDUpdate
[DependencyCheck]  -dataMirroringType = none
[DependencyCheck]  -isQuickQueryTimestampEnabled = true
[DependencyCheck]  -jarAnalyzerEnabled = false
[DependencyCheck]  -nodePackageAnalyzerEnabled = false
[DependencyCheck]  -nodeAuditAnalyzerEnabled = false
[DependencyCheck]  -retireJsAnalyzerEnabled = true
[DependencyCheck]  -composerLockAnalyzerEnabled = false
[DependencyCheck]  -pythonDistributionAnalyzerEnabled = false
[DependencyCheck]  -pythonPackageAnalyzerEnabled = false
[DependencyCheck]  -rubyBundlerAuditAnalyzerEnabled = false
[DependencyCheck]  -rubyGemAnalyzerEnabled = false
[DependencyCheck]  -cocoaPodsAnalyzerEnabled = false
[DependencyCheck]  -swiftPackageManagerAnalyzerEnabled = false
[DependencyCheck]  -archiveAnalyzerEnabled = false
[DependencyCheck]  -assemblyAnalyzerEnabled = false
[DependencyCheck]  -msBuildProjectAnalyzerEnabled = false
[DependencyCheck]  -nuGetConfigAnalyzerEnabled = false
[DependencyCheck]  -nuspecAnalyzerEnabled = false
[DependencyCheck]  -centralAnalyzerEnabled = false
[DependencyCheck]  -nexusAnalyzerEnabled = false
[DependencyCheck]  -artifactoryAnalyzerEnabled = false
[DependencyCheck]  -autoconfAnalyzerEnabled = false
[DependencyCheck]  -cmakeAnalyzerEnabled = false
[DependencyCheck]  -opensslAnalyzerEnabled = false
[DependencyCheck]  -showEvidence = true
[DependencyCheck]  -formats = XML 
[DependencyCheck]  -autoUpdate = true
[DependencyCheck]  -updateOnly = true
[DependencyCheck] Performing update only
[DependencyCheck] Unable to update the Dependency-Check database
Build step 'Invoke Dependency-Check update only' changed build result to FAILURE
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
Notifying upstream projects of job completion
Finished: FAILURE

------------------------------------------------------------------------------------
I found in the  /data/cv/NVDUpdate directory had a dc.lock.db and even if I deleted this file, it will automatically generate a new one immediately.

[data/cv/NVDUpdate]$ ll
-rw-r--r--  1 ei eu  100 Jul 10 09:17 dc.lock.db

[09:21][data/cv/NVDUpdate]$ rm -rf ./dc.lock.db

[09:21][data/cv/NVDUpdate]$ ll
-rw-r--r--  1 ei eu  100 Jul 10 09:21 dc.lock.db

---------------------------------------------------------------------------------------
I tried to re-install a new mirror database. When I update the Dependency-Check database, the new mirror database will automatically create a dc.lock.db file in the directory. Why?

How to solve the problem of automatic creation of this dc.lock.db file?

**Comment by jeremylong** [comment]
The lock file is necessary to ensure multiple instances do not try to update the database at the same time. ODC should remove the lock file when the update is complete.

Please upgrade to the latest version of dependency-check. If you are still having issues please enable debug logging for dependency-check and provide the log file.

**Comment by tiffanyzhou** [comment]
After a few hours, the dc.lock.db file can be deleted and  I set my jenkins job to update the dependency-check database at 8:00pm. The next day, the dc.lock.db file still created. so I can't normally update the database daily.

[DependencyCheck] Unable to update the Dependency-Check database
Build step 'Invoke Dependency-Check update only' changed build result to FAILURE
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
Notifying upstream projects of job completion
Finished: FAILURE

**Comment by jeremylong** [comment]
Please upgrade to the latest version of dependency-check. If you are still having issues please enable debug logging for dependency-check and provide the full log file.

**Comment by tiffanyzhou** [comment]
Yes, after upgrading to the latest version, dependency-check does not report errors any more, but occasionally on builds, there are errors that do not seem to affect the final result.
I did not find where can be configured, should I just ignore it?

[DependencyCheck] [INFO] Checking for updates
[DependencyCheck] [INFO] Skipping NVD check since last check was within 4 hours.
[DependencyCheck] [INFO] Skipping RetireJS update since last update was within 24 hours.
[DependencyCheck] [INFO] Check for updates complete (6 ms)
[DependencyCheck] [INFO] Analysis Started
[DependencyCheck] [INFO] Finished Archive Analyzer (6 seconds)
[DependencyCheck] [INFO] Finished File Name Analyzer (0 seconds)
[DependencyCheck] [INFO] Finished Jar Analyzer (0 seconds)
[DependencyCheck] [INFO] Finished Central Analyzer (5 seconds)
[DependencyCheck] [ERROR] ----------------------------------------------------
**[DependencyCheck] [ERROR] .NET Assembly Analyzer could not be initialized and at least one 'exe' or 'dll' was scanned. The 'dotnet' executable could not be found on the path; either disable the Assembly Analyzer or configure the path dotnet core.**
[DependencyCheck] [ERROR] ----------------------------------------------------
[DependencyCheck] [INFO] Finished Dependency Merging Analyzer (0 seconds)
[DependencyCheck] [INFO] Finished Version Filter Analyzer (0 seconds)
[DependencyCheck] [INFO] Finished Hint Analyzer (0 seconds)
[DependencyCheck] [INFO] Created CPE Index (1 seconds)
[DependencyCheck] [INFO] Finished CPE Analyzer (2 seconds)
[DependencyCheck] [INFO] Finished False Positive Analyzer (0 seconds)
[DependencyCheck] [INFO] Finished NVD CVE Analyzer (0 seconds)
[DependencyCheck] 00:00  INFO: Vulnerability found: jquery below 1.9.0b1
[DependencyCheck] 00:00  INFO: Vulnerability found: jquery below 1.12.0
[DependencyCheck] 00:00  INFO: Vulnerability found: jquery below 1.12.0
[DependencyCheck] 00:00  INFO: Vulnerability found: jquery below 3.4.0
[DependencyCheck] [INFO] Finished RetireJS Analyzer (0 seconds)
[DependencyCheck] [INFO] Finished Sonatype OSS Index Analyzer (1 seconds)
[DependencyCheck] [INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
[DependencyCheck] [INFO] Finished Dependency Bundling Analyzer (0 seconds)
[DependencyCheck] [INFO] Analysis Complete (16 seconds)
[DependencyCheck] Collecting Dependency-Check artifact

**Comment by jeremylong** [comment]
Exactly like the error message says - the scanner found at least one `dll` or `exe` while scanning - which are the file extensions that are examined by the AssemblyAnalyzer (i.e. .net code).  You can either install dotnet core and see if the scanner finds anything wrong with those files (they may not be .net, but they might be?). Alternatively, just disable the AssemblyAnalyzer.

**Comment by tiffanyzhou** [comment]
After I upgraded to the latest version, I found that I can't disable the AssemblyAnalyzer in Jenkins. where can I configure disable AssemblyAnalyzer? I don't see the disable AssemblyAnalyzer configuration in the Configure System either.

**Comment by stevespringett** [comment]
@tiffanyzhou in v4.0.2 and previous of the Jenkins plugin, there is a global option titled 'Enable assembly analyzer'. If you uncheck this option, the AssemblyAnalyzer will be disabled.

Note in v5.0.0 and higher, this is entirely changed. Refer to https://github.com/jenkinsci/dependency-check-plugin/wiki/v5-Migration

**Comment by tiffanyzhou** [comment]
@stevespringett Yes, I know that there are changes in the new version. That's why I want to know how to disable AssemblyAnalyzer in the new version in Jenkins.
Can you provide me with a specific operation?

**Comment by stevespringett** [comment]
@tiffanyzhou v5 using the CLI. There's nothing to configure in Jenkins. Use the instructions for the CLI
https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html
