### ISSUE TITLE
5.1.0 UpdateException

### ISSUE THREAD

**Issue by mbarzanti** [dependency-check/DependencyCheck#2065]
# Reporting Errors
I'm using Dependency-Track 5.1.0 and I have the following exception:

org.owasp.dependencycheck.data.update.exception.UpdateException: The download was interrupted; unable to complete the update
11/07/2019 12:38:31 	at org.owasp.dependencycheck.data.update.NvdCveUpdater.performUpdate(NvdCveUpdater.java:274)
11/07/2019 12:38:31 	at org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:119)
11/07/2019 12:38:31 	at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:899)
11/07/2019 12:38:31 	at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:716)
11/07/2019 12:38:31 	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:642)

Please help me to solve the problem.
Thanks

**Comment by jeremylong** [comment]
We would need more information than the above error.  What command are you using to run ODC?  Please provide the full debug log (if using the CLI just add `-l odc.log`).

**Comment by mbarzanti** [comment]
It was a proxy problem. I opened another issue for asking you how to configure dependency-check CLI behind a proxy
