### ISSUE TITLE
False Positive on javax.el-api-3.0.1-b06

### ISSUE THREAD

**Issue by elion** [dependency-check/DependencyCheck#2066]
False positive on library javax.el-api-3.0.1-b06.jar

```
<dependency>
    <groupId>javax.el</groupId>
    <artifactId>javax.el-api</artifactId>
    <version>3.0.1-b06</version>
</dependency>
```

https://mvnrepository.com/artifact/javax.el/javax.el-api/3.0.1-b06

**Comment by jeremylong** [comment]
Using 5.1.0 I do not see this FP.  What version of dependency-check are you using?

**Comment by elion** [comment]
You are correct. I was using old version 4.0.2.
