### ISSUE TITLE
 Failed to request component-reports: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 403 Forbidden"

### ISSUE THREAD

**Issue by SoftBanX** [dependency-check/DependencyCheck#2067]
Dependency-Check Core version 5.1.0 everything is fine behind proxy but this:

DEBUG - autoload off: VM system will not automatically reload global library macros
2019-07-11 16:11:52,553 org.owasp.dependencycheck.App:202
ERROR - Failed to request component-reports: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 403 Forbidden"
2019-07-11 16:11:52,554 org.owasp.dependencycheck.App:203
DEBUG - unexpected error
org.owasp.dependencycheck.analyzer.exception.AnalysisException: Failed to request component-reports: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 403 Forbidden"
	at org.owasp.dependencycheck.analyzer.OssIndexAnalyzer.analyzeDependency(OssIndexAnalyzer.java:162)

dependency-check.sh --proxyserver 10.1.1.1 --proxyport 4444 --project Testing --out . --scan /tmp/ggg

**Comment by jeremylong** [comment]
Looking up the error I found this: https://stackoverflow.com/questions/41505219/unable-to-tunnel-through-proxy-proxy-returns-http-1-1-407-via-https

Can you try running the following:

```bash
export JAVA_OPTS='-Djdk.http.auth.tunneling.disabledSchemes=""'
dependency-check.sh --proxyserver 10.1.1.1 --proxyport 4444 --project Testing --out . --scan /tmp/ggg
```

**Comment by SoftBanX** [comment]
Sorry no dice, I even hard coded Dhttps.proxyHost etc in script same issue.
The proxy does NOT require auth, and everything else works sweet.
Forgot to mention the error prior:

```
[WARN] An error occurred while analyzing '/tmp/ggg/foo.jar' (Sonatype OSS Index Analyzer).
[INFO] Finished Sonatype OSS Index Analyzer (0 seconds)
[INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
[INFO] Finished Dependency Bundling Analyzer (0 seconds)
[INFO] Analysis Complete (4 seconds)
^C[ERROR] Failed to request component-reports: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 403 Forbidden"
```

**Comment by SoftBanX** [comment]
doh sorry found the issue, local proxy config -closing
