### ISSUE TITLE
Use Retire.js to scan Node

### ISSUE THREAD

**Issue by ericbram** [dependency-check/DependencyCheck#2068]
OWASP DC 5.x.x and above claims support for Retire.js.  Looking at the code however, it looks like it only supports the Retire.js scanning of javascript files, and not node files.  Is this correct?

Looking at the [Retire.js command line usage](https://github.com/RetireJS/retire.js/tree/master/node), you can see that the --path command scans both javascript and node modules.

The fact that DepedencyCheck is already set up to map CVE->CWE means it's set up perfectly to really maximize the use of Retire.js, but the lack of node file support means Retire.js can't fully be eliminated from a scanning perspective.

**Comment by jeremylong** [comment]
RetireJS is used to scan client side JavaScript in ODC.  For node we are relying on the same APIs used by `npm audit`. Have you found vulnerabilities in node using RetireJS that are not also found by `npm audit`?

**Comment by mohanrajanna15** [comment]
To add to the @ericbram 's point, ODC never scans package.json or package-lock.json in my private project. Not sure what is the issue. I want to really demonstrate the benefits on ODC to my company but I am stuck at the first step.

it picks up the vulnerability from retire.js but not from node packages
[INFO] Finished Node Audit Analyzer (0 seconds)
00:00  INFO: Vulnerability found: angularjs below 1.6.9

but if I run NPM Audit in the same folder it reads vulnerabilities from package.json


My command:
dependency-check -s .
The folder has package.json and package-lock.json but nothing works

**Comment by ericbram** [comment]
I've definitely found that NPM Audit and Retire.js Node scanner do not match.  In the applications I've scanned, there is overlap, but often times both scanners find things that the other doesn't report.  So it sounds like for now, I will be running both scanners, at least until (if) the Retire.js node scanning is incorporated.

**Comment by jeremylong** [comment]
@ericbram thanks for the feedback - I'll look into what it would take to incorporate the node scanning from RetireJS.

@mohanrajanna15 have you run `npm install` prior to running dependency-check?

**Comment by ericbram** [comment]
Thanks!  I know Retire.js still reports "depcheck" as experimental outputformat too:  https://github.com/RetireJS/retire.js/tree/master/node

**Comment by ddsultan** [comment]
Apparently, Retirejs has been only client side focused since NPM 6. https://twitter.com/retirejs/status/988364601078185984

**Comment by eoftedal** [comment]
Author of retirejs here. The node package scanning is deprecated and no longer updated. 
npm audit should be used and this issue should be closed. 
retirejs’ focus is now to fins javascript files not mentioned in package.json, pom.xml, Gemfile etc, and detect unmanaged copies of libraries etc

**Comment by jeremylong** [comment]
Thanks for the update!
