### ISSUE TITLE
CSV bad format

### ISSUE THREAD

**Issue by andreluizf** [dependency-check/DependencyCheck#2071]
** Describe the bug **
The file header is joining the first line of the report.
Logstash can not parse the file due to badly formatted file

** Version of dependency check used **
The problem occurs using version 5.1.0 (maven plugin)

** Log file **
[https://gist.github.com/andreluizf/82d037f03802f73c77423af88857e6ff]

**Reproduce**
run maven clean install default for report generation

**Expected behavior**
at the end of the header line needs \ r \ n

** Additional Context **
Add any other context on the problem here.

**Comment by jeremylong** [comment]
what version of ODC are you using?
