### ISSUE TITLE
5.1.1 not yet available

### ISSUE THREAD

**Issue by OrangeDog** [dependency-check/DependencyCheck#2075]
[v5.1.1](https://github.com/jeremylong/DependencyCheck/releases/tag/v5.1.1) was released yesterday, and [current.txt](https://jeremylong.github.io/DependencyCheck/current.txt) has been updated, but it is not available in [Maven Central](https://mvnrepository.com/artifact/org.owasp/dependency-check-maven).

**Comment by OrangeDog** [comment]
It looks like the [release notes](https://github.com/jeremylong/DependencyCheck/blob/v5.1.1/RELEASE_NOTES.md) are also missing.

**Comment by mprins** [comment]
https://mvnrepository.com/ != Central
Use https://search.maven.org/

**Comment by jeremylong** [comment]
Please see https://search.maven.org/artifact/org.owasp/dependency-check-maven/5.1.1/maven-plugin

Regarding the release notes - they are published,  they just got missed in the v5.1.1 tag. https://github.com/jeremylong/DependencyCheck/blob/master/RELEASE_NOTES.md#version-511-2019-07-15

**Comment by OrangeDog** [comment]
Looks like I checked too early, then forgot to use `-U` when trying again.
