### ISSUE TITLE
dependency-check behind a proxy

### ISSUE THREAD

**Issue by mbarzanti** [dependency-check/DependencyCheck#2078]
I'm using dependency-check CLI behind a proxy.
I obtain the following error:
Dependency Scan --> org.owasp.dependencycheck.data.update.exception.UpdateException: Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-modified.meta

Is there any way to configure a proxy for nvd updates?

**Comment by albuch** [comment]
Hi @mbarzanti , you can find all configuration parameters of CLI including proxy related settings (e.g. `-proxyserver`, `-proxyport`, `-proxypass`, `-proxyuser`) documented in the wiki: https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html

**Comment by mbarzanti** [comment]
It runs. Thanks
