### ISSUE TITLE
Add analyzer of C/C++ project source and build files

### ISSUE THREAD

**Issue by dwvisser** [dependency-check/DependencyCheck#208]
Example scenario:
- Developer wants to use the “foo” library.
- However, to make it “easy to install” and not depend on the version (if any) installed on the system, she creates a “foo” subdirectory and _copies the entire foo library_ into that subdirectory.
- Further, the “foo” subdirectory has a “configure.in” file, and **that file** tells us the version of _foo_.
- Then, her top-level build system will cd into the foo library, and build, when needed.  (Typically with a recursive make).  The final executable will the embed the “.o” file in this “foo/” subdirectory.

The proposal here is to create an Analyzer that that is able to scan for some common ways of embedding version information in C/C++ build files. Further, items like the license and copyright comment headers can be mined for name and vendor information.

I'm planning on implementing this in a little while.

**Comment by jeremylong** [comment]
I know several people have asked for C/C++ support. I think this area of research is definitely worth-while. However, I am concerned about the false positive rates an analyzer like this might produce.

--Jeremy
