### ISSUE TITLE
DependencyCheck-CLI does not parse build.gradle?

### ISSUE THREAD

**Issue by ghost** [dependency-check/DependencyCheck#2080]
Version : DependencyCheck-CLI 5.1.1

DependencyCheck-CLI 5.1.1 doesn't seem to parse build.gradle which contains a vulnerable version of fastjson dependency.

command i use: ./dependency-check.sh -s <directory>

Any thing i'm missing?

**Comment by jeremylong** [comment]
To scan gradle projects you need to use the [dependency-check-gradle](https://jeremylong.github.io/DependencyCheck/dependency-check-gradle/index.html) plugin.
