### ISSUE TITLE
Dependency check v5 in jenkins

### ISSUE THREAD

**Issue by javixeneize** [dependency-check/DependencyCheck#2081]
Hi

I have been using DC V4 for long time in the jenkins pipelines, using the method dependencyCheckAnalyzer. In this new version this method does not exist anymore

Is there any documentation on how to use this new version of dependency check in the pipelines?

Thanks

**Comment by stevespringett** [comment]
Use the pipeline sniplet generator included with Jenkins. It provides most options. See also https://github.com/jenkinsci/dependency-check-plugin/wiki/v5-Migration

**Comment by javixeneize** [comment]
Thanks. The arguments i need to pass are the same ones as if i was using the CLI, isnt it? Something like this:

-s mypath --project myname --disableCentral  --disableRetireJS -f JSON

Or does it need a new format?

**Comment by stevespringett** [comment]
Same as the CLI.
