### ISSUE TITLE
Showing Vulnerabilities in Jenkins with DependencyCheck 5.0.2

### ISSUE THREAD

**Issue by LHommeDeBat** [dependency-check/DependencyCheck#2086]
Hi,

I'm using the dependency check for maven with version 5.0.0 for checking my projects and creating the xml reports. I want to use the jenkins plugin to display the vulnerabilities after each build. However, they do not seem to show up since updating to jenkins plugin version 5.0.2. They did show up in version 4.0.2 but the CVSS scores were all at 0.0 and all severities were at low because that version did not seem to be compatible with 5.0.0.

This is how it looks like in jenkins now: 
![Unbenannt](https://user-images.githubusercontent.com/43963121/61624413-d28cb300-ac78-11e9-8f84-dc4aa2cd6a61.PNG)

Can you tell me what am I doing wrong?

Thanks in advance.

**Comment by stevespringett** [comment]
No idea. Severity distribution is saved with the results for every build. Having one but not the other should not be possible.
