### ISSUE TITLE
CPE showing null for ossindex in csv report 5.2.0

### ISSUE THREAD

**Issue by Shahriman89** [dependency-check/DependencyCheck#2087]
**Describe the bug**
CPE showing null for ossindex in csv report 5.2.0

** Version of dependency-check used **
maven 5.2.0

** Log file **
(https://github.com/jeremylong/DependencyCheck/files/3419897/dependency-check-report.zip)

**To Reproduce**

**Expected behavior**
CPE value display

**Additional context**
Suppression with CPE regex is not working

**Comment by jeremylong** [comment]
Did you mean that the CPE is blank or the CWE is showing `null`?

**Comment by Shahriman89** [comment]
CPE is blank.

**Comment by jeremylong** [comment]
I have not been able to reproduce this in my environment.  Can you tell me exactly how you are running ODC? Via maven, cli, ???

**Comment by Shahriman89** [comment]
Maven
