### ISSUE TITLE
Setting risk gate thresholds via jenkins groovy dsl seed job?

### ISSUE THREAD

**Issue by jordankoehn** [dependency-check/DependencyCheck#2090]
On the old version of the jenkins plugin (pre 5.x.x), you could set the thresholds to make the job unstable or fail via the typical publisher thresholds method. On the new version risk gate thresholds are used and I can't seem to track down the correct syntax.

`dependencyCheck("path/to/test-results/dependency-check/dependency-check-report.xml") { ??? }`

**Comment by stevespringett** [comment]
As defined in https://github.com/jenkinsci/dependency-check-plugin/blob/master/src/main/java/org/jenkinsci/plugins/DependencyCheck/ThresholdCapablePublisher.java

- unstableTotalCritical
- unstableTotalHigh
- unstableTotalMedium
- unstableTotalLow
- failedTotalCritical
- failedTotalHigh
- failedTotalMedium
- failedTotalLow
- unstableNewCritical
- unstableNewHigh
- unstableNewMedium
- unstableNewLow
- failedNewCritical
- failedNewHigh
- failedNewMedium
- failedNewLow

**Comment by jordankoehn** [comment]
UPDATE: 
`dependencyCheck("path/to/test-results/dependency-check/dependency-check-report.xml") { ??? }`
is the old format.

New format is
dependencyCheckPublisher() {
        pattern("path/to/test-results/dependency-check/dependency-check-report.xml")
        unstableTotalCritical(0)
        unstableTotalHigh(0)
        unstableTotalLow(0)
        unstableTotalMedium(0)
 }
