### ISSUE TITLE
Sonatype OSS Index Analyzer - Failed to request component-reports errors

### ISSUE THREAD

**Issue by neil-n-brown** [dependency-check/DependencyCheck#2091]
If I leave the Sonatype OSS Index Analyzer enabled I get the following error which then fails my builds:

"An error occurred while analyzing '#########/lib/Saxon-HE-9.6.0-3.jar' (Sonatype OSS Index Analyzer)
Failed to request component-reports errors"

I am using Dependency Check 5.0.0 CLI.  Does anyone have any idea of what could be causing this issue and how i could go about troubleshooting?

Thanks

**Comment by jeremylong** [comment]
Can you generate the debug log (i.e. add `-l odc.log`) and post the log?

**Comment by neil-n-brown** [comment]
Sure, please see file attached.
[odc.log](https://github.com/jeremylong/DependencyCheck/files/3440093/odc.log)

**Comment by jeremylong** [comment]
If you look at the log file you will see:

> Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authorization Required"

It looks like you are behind a proxy that requires authentication for some resources?

**Comment by neil-n-brown** [comment]
This is strange because I have the proxy details specified in the CLI argument and I dont have any issues reaching the other sites.

To add to this I can also access the OSS Index using the same proxy details on a different machine.

Do you know what domain I would need to specify for a proxy bypass for OSS?

**Comment by jeremylong** [comment]
The URL for the OSS Index is https://ossindex.sonatype.org
