### ISSUE TITLE
Increase connection timeout via maven

### ISSUE THREAD

**Issue by grossjonas** [dependency-check/DependencyCheck#2092]
I see that there is a [Settings class with a connection timeout](https://github.com/jeremylong/DependencyCheck/blob/master/utils/src/main/java/org/owasp/dependencycheck/utils/Settings.java#L220).

How can I change the default value by using my pom.xml?

**Comment by jeremylong** [comment]
Yes - see the [dependency-check-maven configuration page](https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html) and look for `connectionTimeout`.  This controls the connection timeout when downloading external resources over HTTP/S.

**Comment by grossjonas** [comment]
Thanks for pointing me there - i somehow missed that.
