### ISSUE TITLE
failOnCVSS does not work with vulnerabilities that do not have a CVSS score

### ISSUE THREAD

**Issue by Jarl-dev** [dependency-check/DependencyCheck#2093]
We are using the command line version of the DependencyCheck (5.0.2) with "--failOnCVSS 5".
This normally works in getting an error if a high enough vulnerability is found.

But now we have the following vulnerabilities, but yet we dont get the error as a result:

NPM-1012: https://www.npmjs.com/advisories/1012
NPM-1013: https://www.npmjs.com/advisories/1013

These are listed in the report with a severity of 'high'.
So I would expect this to be over the 5 thresshold.

What could be the reason it is not seeing these as enough reason to throw an error?

And is there any way to see the actual numeric value of the severity for NPM vulnerabilities? 
Similar to how its shown for CVE's

**Comment by jeremylong** [comment]
This affects the `failOnCVSS` and `junitFailOnCVSS`. Some vulnerability data does not include an actual CVSS score. For purposes of `failures` ODC will be updated to map the severity to a CVSS score.

**Comment by dwaynebailey** [comment]
Would it work to add an option to `failWithoutCVSS` to fail when CVSS scores are missing?

_Edit:_ In fact my setting is `failBuildOnCVSS = 0` shouldn't that cover `null` also?

**Comment by jeremylong** [comment]
This issue also affected the JUnit report.  Both have been corrected.
