### ISSUE TITLE
Cannot see Dependency-Check Results in Jenkinks plugin

### ISSUE THREAD

**Issue by mbarzanti** [dependency-check/DependencyCheck#2095]
I'm using ODC 5.0.2 Jenkins Plugin.
It sets results to UNSTABLE with or without  thresholds and does not show neither Trends nor Results.
Build Arguments:
--project  DCTest --scan OSSTest --enableExperimental --disableArchive --log SRSCAdep.log --cveValidForHours 24 --enableRetired --junitFailOnCVSS 11
Publisher is configured

### Possible Bug
This is the Job's console output:
Started by user Administrator
Running as SYSTEM
Building in workspace /var/lib/jenkins/jobs/DCTest/workspace
[DependencyCheck] [INFO] Checking for updates
[DependencyCheck] [INFO] Skipping NVD check since last check was within 24 hours.
[DependencyCheck] [INFO] Skipping RetireJS update since last update was within 24 hours.
[DependencyCheck] [INFO] Check for updates complete (10 ms)
[DependencyCheck] [INFO] 
[DependencyCheck] 
[DependencyCheck] Dependency-Check is an open source tool performing a best effort analysis of 3rd party dependencies; false positives and false negatives may exist in the analysis performed by the tool. Use of the tool and the reporting provided constitutes acceptance for use in an AS IS condition, and there are NO warranties, implied or otherwise, with regard to the analysis or its use. Any use of the tool and the reporting provided is at the user’s risk. In no event shall the copyright holder or OWASP be held liable for any damages whatsoever arising out of or in connection with the use of this tool, the analysis performed, or the resulting report.
[DependencyCheck] 
[DependencyCheck] 
[DependencyCheck] [INFO] Analysis Started
[DependencyCheck] [INFO] Finished File Name Analyzer (0 seconds)
[DependencyCheck] [INFO] Finished Jar Analyzer (0 seconds)
[DependencyCheck] [INFO] Finished Central Analyzer (0 seconds)
[DependencyCheck] [INFO] Finished Assembly Analyzer (0 seconds)
[DependencyCheck] [INFO] Finished Python Package Analyzer (0 seconds)
[DependencyCheck] [INFO] Finished Dependency Merging Analyzer (0 seconds)
[DependencyCheck] [INFO] Finished Version Filter Analyzer (0 seconds)
[DependencyCheck] [INFO] Finished Hint Analyzer (0 seconds)
[DependencyCheck] [INFO] Created CPE Index (3 seconds)
[DependencyCheck] [INFO] Finished CPE Analyzer (5 seconds)
[DependencyCheck] [INFO] Finished False Positive Analyzer (0 seconds)
[DependencyCheck] [INFO] Finished NVD CVE Analyzer (0 seconds)
[DependencyCheck] 00:00  INFO: Vulnerability found: jquery below 1.9.0b1
[DependencyCheck] 00:00  INFO: Vulnerability found: jquery below 1.12.0
[DependencyCheck] 00:00  INFO: Vulnerability found: jquery below 1.12.0
[DependencyCheck] 00:00  INFO: Vulnerability found: jquery below 3.4.0
[DependencyCheck] 00:01  INFO: Vulnerability found: bootstrap below 4.3.1
[DependencyCheck] 00:01  INFO: Vulnerability found: bootstrap below 4.1.2
[DependencyCheck] 00:01  INFO: Vulnerability found: bootstrap below 4.1.2
[DependencyCheck] 00:01  INFO: Vulnerability found: bootstrap below 4.1.2
[DependencyCheck] [INFO] Finished RetireJS Analyzer (4 seconds)
[DependencyCheck] [INFO] Finished Sonatype OSS Index Analyzer (0 seconds)
[DependencyCheck] [INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
[DependencyCheck] [INFO] Finished Dependency Bundling Analyzer (1 seconds)
[DependencyCheck] [INFO] Analysis Complete (14 seconds)
Build step 'Invoke Dependency-Check' changed build result to SUCCESS
[DependencyCheck] Collecting Dependency-Check artifact
[DependencyCheck] Unable to find Dependency-Check reports to parse
Build step 'Publish Dependency-Check results' changed build result to UNSTABLE
Finished: UNSTABLE

#### Log
Attached log contains no errors
[SRSCAdep.log](https://github.com/jeremylong/DependencyCheck/files/3427444/SRSCAdep.log)

**Comment by stevespringett** [comment]
The Jenkins plugin issue tracker is here:
https://issues.jenkins-ci.org/

If you're using a pipeline job, there's a known issue for that
https://issues.jenkins-ci.org/browse/JENKINS-58381

PR's are encouraged

**Comment by mbarzanti** [comment]
Sorry Steve,
Thank you for the suggestion
