### ISSUE TITLE
False Positive on library org.apache.commons:commons-crypto:1.0.0

### ISSUE THREAD

**Issue by chnp01** [dependency-check/DependencyCheck#2097]
False positive on library org.apache.commons:commons-crypto:1.0.0 - reported as cpe:/a:apache-ssl:apache-ssl:1.0.0

<dependency>
    <groupId>org.apache.commons</groupId>
    <artifactId>commons-crypto</artifactId>
    <version>1.0.0</version>
</dependency>

**Comment by jeremylong** [comment]
This FP does not occur in the current release. Please upgrade to 5.2.0 or later.
