### ISSUE TITLE
--exclude option on the CLI doesn't work

### ISSUE THREAD

**Issue by dbsanfte** [dependency-check/DependencyCheck#2099]
**Describe the bug**
The --exclude option + glob isn't parsed properly on the command line. The CLI errors out and doesn't recognize it as an option, but suggests it in the very next message... 

** Version of dependency-check used **
5.2.0 cli

** Log file **
```
/tmp/dependency-check/bin/dependency-check.sh --project ${PROJECT_KEY} --noupdate --disableCentral --scan ${WORKSPACE} --out . -f XML --disableAssembly --disableBundleAudit --disableRubygems --dbDriverName org.postgresql.Driver --dbDriverPath /tmp/postgresql.jar --connectionString "jdbc:postgresql://our-database:5432/owasp" --dbUser ${DB_USERNAME} --dbPassword ${DB_PASSWORD} --exclude **/node_modules/node-gyp/node_modules/tar/**
Unrecognized option: --exclude **/node_modules/node-gyp/node_modules/tar/**
usage: Dependency-Check Core [--advancedHelp] [--cveValidForHours <hours>]
       [--enableExperimental] [--enableRetired] [--exclude <pattern>] [-f
       <format>] [--failOnCVSS <score>] [-h] [--hints <file>]
       [--junitFailOnCVSS] [-l <file>] [-n] [-o <path>] [-P <file>]
       [--prettyPrint] [--project <name>] [-s <path>] [--suppression
       <file>] [--symLink <depth>] [-v]
```

**To Reproduce**
1. Run dependency-check CLI with `--exclude **/*.java` or something
2. Watch it explode

**Expected behavior**
I want it to exclude files that match the glob

**Comment by dbsanfte** [comment]
Any updates? This is somewhat painful. We're unable to exclude stuff and I'm having to disable dependencycheck on projects now, which is dangerous. :O

**Comment by jeremylong** [comment]
Try using quotes.

--exclude "**/*.java"


--Jeremy

**Comment by derhecht** [comment]
@jeremylong it does not work either :(

**Comment by derhecht** [comment]
wait! using single quotes does work! @jeremylong thx for the tip.
