### ISSUE TITLE
Different number of findings when run on Java 7 vs Java 8

### ISSUE THREAD

**Issue by dylemma** [dependency-check/DependencyCheck#210]
Example input file: http://archive.apache.org/dist/struts/2.3.20/struts-2.3.20-all.zip
If I set a `DEPCHECK_INPUT` variable to point to the downloaded copy of that struts zip, fill in the remaining variables with the relevent file paths, and run this command line:

`java -classpath "%DEPCHECK_CLASSPATH%" "-Dbasedir=%DEPCHECK_BASEDIR%" org.owasp.dependencycheck.App --app dependency-check --scan "%DEPCHECK_INPUT%" --format XML --data "%DEPCHECK_DATADIR%" --out "%DEPCHECK_OUTPUT%"`

The output file has 120 vulnerabilities when run on Java 8, and only 74 when run on Java 7.
(I passed the `-version:1.7` flag before the `-classpath` argument to run on Java 7)
The actual versions I'm running are:

```
java -version
```

> java version "1.8.0_20"
> Java(TM) SE Runtime Environment (build 1.8.0_20-b26)
> Java HotSpot(TM) 64-Bit Server VM (build 25.20-b23, mixed mode)

and

```
java -version:1.7 -version
```

> java version "1.7.0_17"
> Java(TM) SE Runtime Environment (build 1.7.0_17-b02)
> Java HotSpot(TM) 64-Bit Server VM (build 23.7-b01, mixed mode)

Though I expect any version of 7 vs 8 will encounter the same issue. I'm running on Windows 7, FWIW.

**Comment by hansjoachim** [comment]
Thanks for reporting. This has possibly the same underlying issue as in #206.

**Comment by jeremylong** [comment]
Thanks for the report. I will try to dig into this over the weekend and figure out what is going on that is causing the difference between Java 7 and 8.

--Jeremy

**Comment by jeremylong** [comment]
I believe Hans is correct and that issue #206 was the culprit. Can you confirm whether or not most of the vulnerabilities from the report run under JDK8 were for Spring related bugs?

**Comment by dylemma** [comment]
It looks like only a few (7 out of 120) of the vulnerabilities were spring-related, and all of them were present in both java 7 and 8 result sets. In the Java 8 results, most of the "extra" findings were in `<fileName>struts-2.3.20-all.zip: juli-6.0.18.jar</fileName>`, and a couple in `<fileName>struts-2.3.20-all.zip: dwr-1.1.1.jar</fileName>`. There was one finding in `<fileName>struts-2.3.20-all.zip: xwork-core-2.3.20.jar</fileName>` in the java 7 set that was missing in the java 8 set.

**Comment by jeremylong** [comment]
I was just able to finish testing of the patch I pushed yesterday and it appears to have resolved the problem.  Basically, the JAXB binding worked better in JDK8 then JDK7. I just stripped out the generated JAXB bindings and replaced them with a simple SAX parser that is more robust.

This patch will be included in the next release.
