### ISSUE TITLE
.NET Assembly Analyzer could not be initialized

### ISSUE THREAD

**Issue by annfalotaibi** [dependency-check/DependencyCheck#2103]
We are trying to use the latest version of dependency check, and it keeps giving us this error:

**.NET Assembly Analyzer could not be initialized and at least one 'exe' or 'dll' was scanned. The 'dotnet' executable could not be found on the path; either disable the Assembly Analyzer or configure the path dotnet core.**

The strange thing is that when we get back to the old version, it works fine, but the new one doesn't!

***We are using Windows by the way.

**Comment by Mayabhai** [comment]
Hi Team,

I referred this site for above issue:
 https://github.com/jeremylong/DependencyCheck/issues/1087

But I want solution for Windows. Please help.

**Comment by jeremylong** [comment]
Do you have dotnet core installed?  The old version of dependency-check utilized .net - the new version of dependency-check utilizes dotnet core.  If `dotnet` is not on the path you may need to tell ODC the path to the `dotnet` executable.

**Comment by Mayabhai** [comment]
Thanks alot. But my application uses .net and not  .net core. What should I do in that case?

**Comment by jeremylong** [comment]
Install dotnet core as ODC uses a dotnet core assembly to analyze all .net DLL/EXE.

**Comment by Mayabhai** [comment]
okay.. and then --dotnet command to ODC. right?

**Comment by jeremylong** [comment]
Sure - unless `dotnet` is on the path.  Then the `--dotnet [path]` may not be needed.

**Comment by Mayabhai** [comment]
I have installed dontnet core and tried to run.But its showing below error now:
An error occurred with the .NET AssemblyAnalyzer

**Comment by emartynov** [comment]
I on mac with android project and I see this warning. False positive?

**Comment by jeremylong** [comment]
@emartynov it means somewhere, possibly even buried inside a JAR (or AAR) file is an EXE or DLL.  It may not be a .net binary - but it is attempting to scan it.  Because ODC does not have access to dotnet core it can't run the contained `GrokAssembly` to collect information from the DLL. You can always disable the assembly analyzer.

**Comment by jeremylong** [comment]
@Mayabhai please generate a debug log to get more details about the error: `-l odc.log`

**Comment by abccbaandy** [comment]
@emartynov 
if you are using lombok, take a look this
https://github.com/rzwitserloot/lombok/issues/2084

**Comment by emartynov** [comment]
Thanks! But we are not, at least not directly.

**Comment by jygalipeau** [comment]
I got the same exception as Mayabhai with .NET Assembly Analyzer.  I've joined my log file.
[odc.log](https://github.com/jeremylong/DependencyCheck/files/3647874/odc.log)

I've got a java.io.IOException: CreateProcess error=5, Access is denied.

I'm running ODC on Win 10 (64bits) computer.

I've tried to run the batch file under Administrator but it doesn't help.  I always got the same exception. GrokAssembly doesn't want to run.

I've installed .NET Core 3.0.100.

**Comment by jygalipeau** [comment]
Hi All,
Finally I found a solution to my problem mentioned above.  I have installed .NET Core 2.0 SDK (v2.1.202), because it doesn't to work for now with .NET Core SDK (v3.0.100).

Maybe Jeremy you could write a note in the readme file or in the wiki about the required version .NET Core SDK that we must install to run ODC .NET Assembly Analyzer.

Thanks.

**Comment by kgb-financial-com** [comment]
Summing up the current state, using OWASP dependency check 5.2.2 command line with Windows 10:

- It works with .NET Core 2.x SDK, including the most recent version 2.2.402, when installed using the installer.
- It does not work if only the .NET Core runtime is installed. In that case, error message is that 'dotnet' executable could not be found (although it is present in the path).
- It does not work with .NET Core 3.x. In that case, error message is that an error occurred with the .NET AssemblyAnalyzer.

**Comment by arochai** [comment]
Hi !
I have the same problem.
I have install the .NET Core 2.2 SDK (v2.2.207) - Windows x64 Installer
The path is ok : C:\Program Files\dotnet\
But i am still facing this error on windows 10:
[ERROR] .NET Assembly Analyzer could not be initialized and at least one 'exe' or 'dll' was scanned. The 'dotnet' executable could not be found on the path; either disable the Assembly Analyzer or configure the path dotnet core.

Thank you in advance. Arnaud

**Comment by jeremylong** [comment]
In some cases the environment path on your command line is different than the `path` within the JVM.  In this case you will see the error "...dotnet executable could not be found on the path..." The error message gives you the exact steps you need to use to resolve the issue. See the [CLI documentation](https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html) - you just need to add `--dotnet c:/path/to/dotnet`.

**Comment by jeremylong** [comment]
With the soon to be released 5.4 we will be moving from dotnet 2.x to dotnet 3.1.
