### ISSUE TITLE
Parameter skipArtifactType doesn't work in maven plugin v5.2.0

### ISSUE THREAD

**Issue by sesto** [dependency-check/DependencyCheck#2105]
I want to skip dependency check for the Spring framework.
My plugin configuration is:
```
             <plugin>
                <groupId>org.owasp</groupId>
                <artifactId>dependency-check-maven</artifactId>
                <version>5.2.0</version>
                <configuration>
                    <formats>HTML,XML</formats>
                    <dataDirectory>/dependency-check-data/</dataDirectory>
                    <skipArtifactType>^org\.springframework\..*$</skipArtifactType>
                </configuration>
                <executions>
                    <execution>
                        <phase>none</phase>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```
What I can see that Spring framework dependencies are being scanned and vulnerabilities reported.
The suppression via xml works like this:
```
<suppress>
        <gav regex="true">^org\.springframework\..*$</gav>
        <cpe regex="true">.*</cpe>
 </suppress> 
```
But I don't want the packages being scanned in first place
** Version of dependency-check used **
The problem occurs using version 5.2.0 of the the maven plugin

** Log file **
https://gist.github.com/sesto/503a9d156dc341bfb49293f31c3f9dc3
**Expected behavior**
Types of `org.springframework` should not been scanned

**Comment by jeremylong** [comment]
`^org\.springframework\..*$` is not a valid dependency type in Maven.  Types would be things like jar, pom, test-jar, etc.  We have not yet implemented the feature you are looking for - to filter specific artifacts by group or artifactId.

**Comment by sesto** [comment]
Thank you for clearing this out. Can you clarify this in the documentation of the maven plugin? At the moment, it is not clear at all what is meant by "artifact type".

**Comment by jeremylong** [comment]
Yes, we will update the documentation to include an example. Would naming it "dependencyType" have made it more clear?

**Comment by sesto** [comment]
I  not sure that renaming will make it clearer. I think the example will be
fine
