### ISSUE TITLE
Add analyzer for object (compiled) files with embedded code name and version number

### ISSUE THREAD

**Issue by dwvisser** [dependency-check/DependencyCheck#211]
Write the analyzer that leverages the spec defined in #212. This will likely involve treating binary files as text (ASCII?), and throwing away unprintable characters.

**Comment by jeremylong** [comment]
It might be possible to do identification based off of a `strings` analysis of a binary - but I have a feeling this might be fairly unreliable. I don't see #212 being viable (but possibly the SWID tags could be).

**Comment by jeremylong** [comment]
See comments on PR #298.
