### ISSUE TITLE
Link Jenkins to nist-data-mirror data

### ISSUE THREAD

**Issue by ConRock5000** [dependency-check/DependencyCheck#2111]
Hi, I upgraded to the DependencyCheck v5 plugin in Jenkins. I was getting the 'unable to download meta file' error so I installed and configured nist-data-mirror.
I cannot figure out where to set cveUrlBase or cveUrlModified though.
I tried setting them in my build.gradle file but it appeared to have no effect on the Jenkins build.
Also, can a file path be used or only http when setting these variables?
Thanks

**Comment by stevespringett** [comment]
If you're using Gradle to perform a scan, then refer to the gradle docs

https://jeremylong.github.io/DependencyCheck/dependency-check-gradle/configuration.html

If you're using the Jenkins plugin to perform a scan, refer to the CLI docs

https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html

**Comment by ConRock5000** [comment]
Hi, thank you. I understand the new CLI wrapper now I believe.

When my Jenkins task runs it finds to url of the nist data mirror and then an update is performed. Is that normal?
Afterwards I get could not connect to central search. Is that related to the mirror configuration or is there another mirror I need to configure?
Thank you for any assistance.

**Comment by jeremylong** [comment]
The CentralAnalyzer is different than the NVD.  ODC, when the CentralAnalyzer is enabled, will use the SHA hash of the JAR files and lookup the GAV from Maven Central and download the pom.xml.  If your build servers cannot reach out to Maven Central you can disable the CentralAnalyzer.  

If you have a Nexus or Artifactory you can disable the CentralAnalyzer and enable either the Nexus Analyzer or Artifactory Analyzer - which attempt to perform the same type of analysis.

**Comment by ConRock5000** [comment]
Thank you for the explanation.

I had errors for the rest of the analysers so I disabled them all with the CLI switches.

What would be the equivalent of version 4 of dependency check on Jenkins; which analysers were on?

**Comment by jeremylong** [comment]
Please see the 4.0.2 properties file: https://github.com/jeremylong/DependencyCheck/blob/0c3961197e87abc0cd925a14440c411a4db584bf/core/src/main/resources/dependencycheck.properties#L105-L141

**Comment by ConRock5000** [comment]
Hi, I have been stumped as to why I can no longer reach nvd, maven central, etc. All of this worked in 4. Is there an additional proxy that needs to be configured now? Was there a proxy in the background being used in 4 on Jenkins?
Sorry if these have been asked in other threads in other ways.

**Comment by jeremylong** [comment]
ODC can use a proxy if you configure one.  However, by default the tool connects directly out to the NVD, Central, Github, etc.
