### ISSUE TITLE
How to know next major and minor versions of a vulnerable dependancy?

### ISSUE THREAD

**Issue by dasarinarednra12345** [dependency-check/DependencyCheck#2113]
I am using dependancy-scan cli to scan a war for vulnerabilities. When we are working with maven plugin I am able to see the available versions for all dependancies but cli is not producing the file containing available versions, Next Major and Minor versions etc.. Could somebody help me in this issue?

**Comment by jeremylong** [comment]
The file containing the available versions is not from the dependency-check plugin. That is generated by the [versions:dependency-updates-report](https://www.mojohaus.org/versions-maven-plugin/dependency-updates-report-mojo.html).

Just using the CLI - I don't know of an automated way to get the next major/minor versions available.
