### ISSUE TITLE
Suppression XML Schema Question

### ISSUE THREAD

**Issue by Writtscher** [dependency-check/DependencyCheck#2116]
Hi. We are using version 5.1.0. When we execute the dependencyCheck task of the gradle plugin we get a full report. That is fine. But the problem in the report is, that the Suppress-Button opens a small pop up that has a invalid xml (at least for us). It generates

```
<suppress>
   <notes><![CDATA[
   file name: XXX.jar
   ]]></notes>
   <packageUrl regex="true">^pkg:maven/XXX\.XXX/XXX@.*$</packageUrl>
   <cve>XXX</cve>
</suppress>
``` 
According to the schema https://jeremylong.github.io/DependencyCheck/dependency-suppression.1.1.xsd the field **packageUrl** is bad.. Should be **gav**

Why do we get this bad xml part?

**Comment by jeremylong** [comment]
If you use the "Complete XML" button in the lower left of the create suppression dialog it will give you the headers w/ schema.  The current suppression schema is 1.3 which includes the packageUrl element (and it is also backward compatible with the older schemas).

**Comment by jeremylong** [comment]
See https://jeremylong.github.io/DependencyCheck/dependency-suppression.1.3.xsd

**Comment by Writtscher** [comment]
Thank you jeremy, you are right! Good to know.
