### ISSUE TITLE
How to exclude test scoped dependencies in Jenkins Plugin?

### ISSUE THREAD

**Issue by bbarman4u** [dependency-check/DependencyCheck#2117]
How to exclude test scoped dependencies in Jenkins Plugin? I am noticing the test scoped dependencies in a maven project and its subsequent dependencies even though they are not in the final packaged version in the project lib( as in the maven packaging we only specify "runtime" which excludes test scoped libraries) are getting reported when using the Jenkins Plugin for dependency check ? We have many projects and it will be maintenance headache to add the dependency check mojo to each and every pom, hence would prefer a solution where the CI can manage it.

**Comment by stevespringett** [comment]
The Jenkins plugin is a wrapper around the command-line interface. The CLI doesn't understand Maven. Use the Dependency-Check Maven plugin if you want to exclude specific scopes.

https://jeremylong.github.io/DependencyCheck/dependency-check-maven/index.html

**Comment by bbarman4u** [comment]
@stevespringett thanks for clearing that up. But I was wondering how the CLI works ? Does it also implicitly looks at the pom.xml of a maven project? Should it not only scan the jars that I specify in the cli argument for "--scan" and ignore the pom.xml dependencies?

**Comment by stevespringett** [comment]
The CLI looks at files on the filesystem. It doesn't resolve dependencies in a pom as it doesn't know what a pom is. If you point it to a directory containing a bunch of jars, it will unzip each one and discover evidence from them with varying degrees of confidence.

If you have a maven project, the results you get with the maven plugin will be far superior to a scan using only the cli as the evidence in the pom will be the highest confidence evidence.

**Comment by bbarman4u** [comment]
@stevespringett Thanks for the suggestion, I am now looking into the maven plugin but I realized that with the maven plugin when different applications are scanned in the CI server, they will tend to download the NVD database again and again for each CI Job since mostly every CI job will be using their isolated m2 repository path to avoid conflicts with different applications. I could not understand from the different configurations available, is there a config where I can specify the default path of the cached and downloaded NVD database so that all jobs can use the same downloaded file and can benefit from improved performance? I can separately update this NVD file only separately as required on a schedule. Any suggestions or pointers is appreciated. !!

**Comment by stevespringett** [comment]
Refer to https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html for Maven usage, specifically dataDirectory.
