### ISSUE TITLE
DependencyBundlingAnalyzer - flag to disable?

### ISSUE THREAD

**Issue by siromega** [dependency-check/DependencyCheck#2118]
I am running into an issue with a large modern Angular project - the dependency check is timing out on the DependencyBundlingAnalyzer part. I reviewed the documentation and there is no way to disable (that I could tell) this part of the scan to at least be able to complete a scan. 

The log files generated are gigabytes (2GB+) during the scan. It looks like DependencyBundlingAnalyzer is checking every single JS file against every other file in the project. The logs are filled with things like this 

> 2019-08-01 09:42:40,574 org.owasp.dependencycheck.analyzer.DependencyBundlingAnalyzer:286
> DEBUG - IdentifiersMatch=false (concat.js, rounding-precision.js)

Is there a way to disable this portion of the scan? 

I am running this on a Windows 10 OS, Java 8.

**Comment by jamesratzlaff** [comment]
If you create a .properties file and add
```
analyzer.dependencybundling.enabled=false
```
You should be able to use the "-p" cli argument to reference that properties file which will disable the bundle analyzer.

**Comment by siromega** [comment]
That successfully disabled that part of the scan. I'm having other issues, but I'll close this one.

**Comment by mjdavies** [comment]
Can you do this via the command line arguments?

https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html

Something like --disableBundling

**Comment by jeremylong** [comment]
That is not yet exposed as an argument to the cli.   Instead of the properties file route you could also use `export JAVA_OPTS=-Danalyzer.dependencybundling.enabled=false` (swap export for set if you are on windows).

**Comment by mjdavies** [comment]
Thanks Jeremy.  I went down the properties file route in the end, relatively painless.
