### ISSUE TITLE
500 status code during Gradle OSSIndex plugin call

### ISSUE THREAD

**Issue by wraschke** [dependency-check/DependencyCheck#2121]
**Describe the bug**
Our builds use the Gradle OSSIndex plugins to scan for vulnerabilities.

Often this scan is successful and there are no problems. Yet lately, though intermittent but frequently, the builds run into this:

`Caused by: java.net.ConnectException: Server Error (500)
	at net.ossindex.common.request.OssIndexHttpClient.performPostRequest(OssIndexHttpClient.java:122)
	at net.ossindex.common.request.PackageRequest.run(PackageRequest.java:121)
	at net.ossindex.gradle.audit.DependencyAuditor.runAudit(DependencyAuditor.java:69)`

**Version of dependency-check used**
The problem occurs using version 5.1.1 of the the Gradle plugin.

**Log file**
Full exception stack is at https://gist.github.com/wraschke/84a80af92ed7136fab624b8467a8263e.

There isn't more information from the server other than this status code.

**To Reproduce**
Not sure how an outsider user could reproduce in our particular environment.

**Expected behavior**
We don't expect a 500 status code from the server.

**Additional context**
The source for the plugin class making POST request appears to be at https://github.com/OSSIndex/java-api/blob/master/src/main/java/net/ossindex/common/request/OssIndexHttpClient.java. I'm presuming the POST request is being made to https://ossindex.sonatype.org/v2.0/<uri>

**Comment by jeremylong** [comment]
If you are using the OSS Index Gradle client (i.e. not ODC) you probably want to open the ticket within their repo: https://github.com/OSSIndex/ossindex-gradle-plugin/issues

This does not look related to dependency-check at all.
