### ISSUE TITLE
Enable Node.js Package Analyzer & Node Audit Analyzer with CLI.

### ISSUE THREAD

**Issue by happysloths** [dependency-check/DependencyCheck#2122]
I am running scans on an archive of a NodeJS package, however I am noticing that the Node.js Package Analyzer & Node Audit Analyzer are not enabled:

> 2019-08-01 16:45:23,624 org.owasp.dependencycheck.Engine:824
> DEBUG - Initializing OpenSSL Source Analyzer
> 2019-08-01 16:45:23,624 org.owasp.dependencycheck.Engine:756
> DEBUG - Starting OpenSSL Source Analyzer
> 2019-08-01 16:45:23,629 org.owasp.dependencycheck.Engine:807
> DEBUG - Parallel processing with up to 4 threads: OpenSSL Source Analyzer.
> 2019-08-01 16:45:23,630 org.owasp.dependencycheck.AnalysisTask:86
> DEBUG - Begin Analysis of '/tmp/dctemp859bd764-12fe-4f35-8a02-4c997f2f6055/check3973697460524363650tmp/2/include/node/openssl/opensslv.h' (OpenSSL Source Analyzer)
> 2019-08-01 16:45:23,632 org.owasp.dependencycheck.Engine:675
> INFO  - Finished OpenSSL Source Analyzer (0 seconds)
> 2019-08-01 16:45:23,632 org.owasp.dependencycheck.Engine:824
> DEBUG - Initializing CMake Analyzer
> 2019-08-01 16:45:23,632 org.owasp.dependencycheck.Engine:677
> DEBUG - Skipping CMake Analyzer (not enabled)
> 2019-08-01 16:45:23,632 org.owasp.dependencycheck.Engine:824
> DEBUG - Initializing Node.js Package Analyzer
> 2019-08-01 16:45:23,632 org.owasp.dependencycheck.Engine:677
> **DEBUG - Skipping Node.js Package Analyzer (not enabled)**
> 2019-08-01 16:45:23,632 org.owasp.dependencycheck.Engine:824
>...
>2019-08-01 16:45:26,922 org.owasp.dependencycheck.data.nvdcve.CveDB:521
> DEBUG - Cache miss for cpe:/a:openssl_project:openssl:1.0.2l
> 2019-08-01 16:45:26,928 org.owasp.dependencycheck.Engine:675
> INFO  - Finished NVD CVE Analyzer (0 seconds)
> 2019-08-01 16:45:26,928 org.owasp.dependencycheck.Engine:824
> DEBUG - Initializing Node Audit Analyzer
> 2019-08-01 16:45:26,929 org.owasp.dependencycheck.Engine:677
> **DEBUG - Skipping Node Audit Analyzer (not enabled)**
> 2019-08-01 16:45:26,929 org.owasp.dependencycheck.Engine:824
> DEBUG - Initializing RetireJS Analyzer
> 2019-08-01 16:45:26,930 org.owasp.dependencycheck.utils.Settings:841
> DEBUG - Settings.getDataFile() - file: './data'
> 2019-08-01 16:45:26,967 org.owasp.dependencycheck.Engine:756
> DEBUG - Starting RetireJS Analyzer
> 2019-08-01 16:45:26,967 org.owasp.dependencycheck.Engine:807
> DEBUG - Parallel processing with up to 4 threads: RetireJS Analyzer.

I did not notice any specific flags in the documentation on how I would explicitly enable those analyzers. An example command that was run:

```
./bin/dependency-check.sh --enableExperimental --format CSV -l ./scan.log -s /path/to/archive/target.tar.bz2 --project /path/to/archive/target -o ./report/location
```

Is there something I am missing to enable the Node.js Package Analyzer & Node Audit Analyzer?

**Edit:** This is on both version 4.0.1 and version 5.2.0

**Comment by jeremylong** [comment]
For node - try expanding the target.tar.bz2, running `npm install` in the target node app, and then running ODC on the root of the project.

**Comment by happysloths** [comment]
Thanks and I appreciate the guidance.

Does the **Node.js Package Analyzer** operate independently on `package.json` files + fully installed `node_modules` directories or does it only work in conjunction with the **Node Audit Analyzer** which utilizes the `package-lock.json` and the NPM Audit API?

**Comment by jeremylong** [comment]
This will be updated in 5.3.0 which will be released soon.  In general for node analysis we need a package-lock or npm-shrinkwrap. The package.json and node_modules directory are used to enrich the report to create a more complete BOM - and we are adding an experimental analyzer that will be retrieving information from the NVD as well.
