### ISSUE TITLE
JSON and HTML Reports Always Report ZERO Vulnerabilities with v5 and Jenkins

### ISSUE THREAD

**Issue by mecorusfc** [dependency-check/DependencyCheck#2123]
**Describe the bug**
When using the v5 version of Dep Check from the Jenkins plugin, I'm able to put in --format parameters and specify JSON, HTML, etc...  However, the only real report that comes out of v5 now with real data is the XML report.  It always comes out and appears to be fed to the html/css formatter (or dep track, or whatever) so that the web page has the vulnerability data.  But if I have a need to copy the reports elsewhere (to a place where deleting a Jenkins job run doesn't delete the scan report data), the only really useful report is XML.  Why allow the JSON and HTML reports to be output if they will always be 1-pagers saying ZERO vulnerabilities no matter how many vulnerabilities are really put out in the XML?  Should the JSON and HTML even be allowed or is it a miss that needs to be fixed?

** Version of dependency-check used **
v5 with the Jenkins Plugin for v5

** Log file **
No log information other than saying the files exist.

**To Reproduce**
Run an OWASP Dep Check Jenkins job with v5 for a project that has more than zero vulnerabilities.  The result is that more than zero vulnerabilities is reported in the XML file as expected but both the JSON and HTML files are output with ZERO vulnerabilities which is very misleading.

**Expected behavior**
More than zero vulnerabilities should be reported in all three reports (JSON, HTML, XML) if there are more than zero vulnerabilities found.

**Additional context**

**Comment by jeremylong** [comment]
Can you please post the exact pipeline command you are using?

**Comment by mecorusfc** [comment]
Here is what it was before I took out the JSON and XML parms:

steps.dependencycheck additionalArguments:
        '--scan ./ --format XML --format HTML --format JSON --prettyPrint --suppression ./OWASPFalsePositiveSuppression.xml --out ./ --data /home/jenkins/tools --cveUrlBase http://ourmirror.com/nvdcve-1.0-%d.json.gz --cveUrlModified http:// ourmirror.com/nvdcve-1.0-modified.json.gz',
        odcInstallation: 'OWASP Dependency Check v5', skipOnScmChange: false, skipOnUpstreamChange: false

Nothing I did would make the XML and JSON reports be anything other than a default report with zero vulnerabilities.  I remember too that these default reports also showed that nothing was scanned, zeros across the board, yet the XML report was quite accurate and usable.  It (the XML) also appears to be fed into the mechanism for Jenkins to display the vulnerabilities page.

Michael Corum

**Comment by jeremylong** [comment]
I have no idea why those two reports would be blank.  Can you add `--log ./odc.log` and see if there are any errors in the log file?
