### ISSUE TITLE
NullPointerException in CliParser

### ISSUE THREAD

**Issue by AstridS** [dependency-check/DependencyCheck#2124]
**Describe the bug**
When analyzing a multi-module maven project, there's a NullPointerException in CliParser

** Version of dependency-check used **
The problem occurs using version 5.2.1 of the the cli via Jenkins

** Log file **
15:55:52 [DependencyCheck] Exception in thread "main" java.lang.NullPointerException
15:55:52 [DependencyCheck] 	at org.owasp.dependencycheck.CliParser.validatePathExists(CliParser.java:213)
15:55:52 [DependencyCheck] 	at org.owasp.dependencycheck.CliParser.validateArgs(CliParser.java:131)
15:55:52 [DependencyCheck] 	at org.owasp.dependencycheck.CliParser.parse(CliParser.java:90)
15:55:52 [DependencyCheck] 	at org.owasp.dependencycheck.App.run(App.java:112)
15:55:52 [DependencyCheck] 	at org.owasp.dependencycheck.App.main(App.java:80)

Please fix this or add logging, what's wrong.
I tried adding --log owasp.log, but no logfile was written.

Best regards

**Comment by jeremylong** [comment]
Can you please provide the exact pipeline command used?  The issue appears to be with the output path (i.e. `-o ./reports`).  I can see why this might cause an NPE after looking at the code - but I was hoping to know exactly what you had used.

**Comment by AstridS** [comment]
Thanks for your reply!
It's a standard Jenkins job, not a pipeline. When I use the pipeline snippet generator with my configuration, I get
`dependencyCheck additionalArguments: '''--format XML
--format HTML
--prettyPrint
--out target''', odcInstallation: '5.x Latest'`
where "5.x Latest" is 5.2.1, which was installed by Jenkins with "install from dl.bintray.com".

**Comment by jeremylong** [comment]
Can you try changing the `--out target` to `--out ./target`?

**Comment by AstridS** [comment]
Yes, it works with `--out ./target`.
Thank you for your help!
