### ISSUE TITLE
jenkins plugin (4.0.2) - report not generated

### ISSUE THREAD

**Issue by javixeneize** [dependency-check/DependencyCheck#2126]
Hi

Im still using the old plugin v4.0.2 in jenkins. For any reason the xml report is not being generated

It completes the scan without any issue, but when trying to access to the dependency-check-report.xml it does not exist

[Pipeline] sh
[DependencyCheck] One or more exceptions were thrown while executing Dependency-Check
[DependencyCheck] Exception Caught: org.owasp.dependencycheck.exception.NoDataException
[DependencyCheck] Message: No documents exist
[DependencyCheck] org.owasp.dependencycheck.exception.NoDataException: No documents exist

The pipeline has always been working. It just started to fail today. Any idea what could be the problem?

Thanks

**Comment by jeremylong** [comment]
No - additionally, we are no longer supporting releases earlier than 5.0.0. Please consider upgrading soon.

With the release of 5.0.0 we moved from the NVD XML data feeds to the NVD JSON data feeds.  Please see https://nvd.nist.gov/General/News/XML-Vulnerability-Feed-Retirement.

**Comment by jeremylong** [comment]
The current release is 5.2.1. Please see the supported version in [SECURITY.md](https://github.com/jeremylong/DependencyCheck/blob/master/SECURITY.md).
