### ISSUE TITLE
Missing dependency-check-vulnerability files with v5.x

### ISSUE THREAD

**Issue by githubhs17** [dependency-check/DependencyCheck#2131]
Before we used docker container owasp/dependency-check:4.0.2 with argument '--format ALL':
all dependency-check-report and dependency-check-vulnerability files are created.

Now we are using docker container owasp/dependency-check:latest (actual 5.2.1) with same arguments, but now only all dependency-check-report files are created and no dependency-check-vulnerability files.

And I can't find any information that there was a change in reporting. Please help. Thanks.

**Comment by jeremylong** [comment]
The dependency-check-vulnerability report was removed in 5.0.0. It was duplicative of the other reports. The formats available are HTML, XML, JSON, JUNIT, and CSV formats (and of course ALL which will produce all 5 reports).

**Comment by cmapyopc** [comment]
@jeremylong It's a fair point to drop complexity if the information is available anyway.

But the dependency-check-vulnerability used to concisely show you what is important (high 
 score) yet not taken care of (neither suppressed, nor fixed). I struggle to find this information in the other reports other than parsing the suppression file and one of the reports and comparing CVEs above certain score, etc.

Can you suggest a better way?

(for what it's worth: I'm using owasp the sbt plugin. Until recently I was using an old version which used pre-5.x. An [announcement](https://twitter.com/ctxt/status/1176114135630798848) made me upgrade to a more recent one. This is how I ran into the problem.)

**Comment by jeremylong** [comment]
Use the csv report. It is nearly identical to the old vulnerability report.

Jeremy
