### ISSUE TITLE
JsonObject Exception when scanning .NET apps

### ISSUE THREAD

**Issue by annfalotaibi** [dependency-check/DependencyCheck#2133]
I have an issue when trying to scan .NET apps, some applications produce exceptions in the report similar to the one here: https://github.com/jeremylong/DependencyCheck/issues/2079

However I already disabled RetireJS, but it is still producing the same issue.

**Comment by jeremylong** [comment]
@AmazingPerson03 Sorry about the delay in response. Are you still seeing this issue with the latest version of ODC? If you are - any chance you can provide a stack trace?
