### ISSUE TITLE
java.lang.NoSuchMethodError due to a signature of com.google.common.base.Preconditions.checkState

### ISSUE THREAD

**Issue by vemv** [dependency-check/DependencyCheck#2134]
**Describe the bug**

When running `org.owasp/dependency-check-core "5.2.0"` through https://github.com/rm-hull/lein-nvd, I can get the following exception:

```
{:type java.lang.NoSuchMethodError
   :message "com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;)V"
   :at [org.sonatype.ossindex.service.client.cache.DirectoryCache <init> "DirectoryCache.java" 83]}
```

**Version of dependency-check used**
`org.owasp/dependency-check-core "5.2.0"` through https://github.com/rm-hull/lein-nvd

**Log file**

```
{:type org.owasp.dependencycheck.exception.InitializationException
   :message "Unexpected Exception"
   :at [org.owasp.dependencycheck.Engine initializeAnalyzer "Engine.java" 862]}
  {:type java.lang.NoSuchMethodError
   :message "com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;)V"
   :at [org.sonatype.ossindex.service.client.cache.DirectoryCache <init> "DirectoryCache.java" 83]}]
 :trace
 [[org.sonatype.ossindex.service.client.cache.DirectoryCache <init> "DirectoryCache.java" 83]
  [org.sonatype.ossindex.service.client.cache.DirectoryCache$Configuration create "DirectoryCache.java" 315]
  [org.sonatype.ossindex.service.client.internal.OssindexClientImpl <init> "OssindexClientImpl.java" 96]
  [org.owasp.dependencycheck.data.ossindex.OssindexClientFactory create "OssindexClientFactory.java" 120]
  [org.owasp.dependencycheck.analyzer.OssIndexAnalyzer prepareAnalyzer "OssIndexAnalyzer.java" 130]
  [org.owasp.dependencycheck.analyzer.AbstractAnalyzer prepare "AbstractAnalyzer.java" 102]
  [org.owasp.dependencycheck.Engine initializeAnalyzer "Engine.java" 842]
  [org.owasp.dependencycheck.Engine analyzeDependencies "Engine.java" 678]
  [nvd.task.check$scan_and_analyze$fn__94495 invoke "check.clj" 50]
  [nvd.task.check$scan_and_analyze invokeStatic "check.clj" 49]
  [nvd.task.check$scan_and_analyze invoke "check.clj" 44]
  [nvd.task.check$_main invokeStatic "check.clj" 66]
  [nvd.task.check$_main invoke "check.clj" 62]
```

**To Reproduce**

Hard to. The test suite of https://github.com/rm-hull/lein-nvd passes. It's in my project that the error happens. It's a private one with _many_ dependencies.

**Additional context**

I double-checked that Guava at `28.0-jre` is the version being loaded into the classpath. I did so by running Clojure tooling `lein deps :tree`, and also by inspecting  the classpath with `ps aux`.

Other than Guava, is there another dependency which I should pay attention to? It seems plausible that a wrong dependency is being loaded.

**Comment by vemv** [comment]
I could work around it by downgrading guava from `"24.1.1-jre"` to `"20.0"`.

That itself triggers a NVD warning though...

I think the fault is in the `org.sonatype.ossindex/ossindex-service-client "1.2.0"` package, which assumes guava v20 as per https://mvnrepository.com/artifact/org.sonatype.ossindex/ossindex-service-api/1.2.0 :

![image](https://user-images.githubusercontent.com/1162994/63160427-06f85280-c01e-11e9-9e6b-8055d8d43309.png)

**Comment by jeremylong** [comment]
I do not believe this is an issue with core dependency-check. This looks more related to the lein-nvd implementation.

**Comment by vemv** [comment]
Not sure if I agree, but I'm ok with closing the issue since I have documented a fix here.

**Comment by jeremylong** [comment]
Dependency-check-core depends on guave 28.0-jre. So I'm not sure how 'downgrading from "24.1.1-jre" to "20.0" as a work around' is a core dependency-check issue.  If a downgrade is needed in the lein-nvd implementation it should be done there.

With the core project we have been trying to keep our dependencies up-to-date - but with things like guava we have also been trying to ensure that we do not use any of the latest features so we don't break integrations that must use an earlier version of guava.

**Comment by vemv** [comment]
There are many layers involved (DependencyCheck, lein-nvd, ossindex-service-client, Lein's dependency resolution algo) so trying to determine a 'culprit' would be a quite futile exercise and certainly not my intention.

Personally I'm happy to have found/documented a fix and I congratulate you for the great work on the v5 release!
