### ISSUE TITLE
how to disable ruby bundle analyzer in jenkins pipeline for 5.2.1 version?

### ISSUE THREAD

**Issue by marcinprzybysz86** [dependency-check/DependencyCheck#2135]
hi, 
i've installed 5.2.1 jenkins plugin but got an error :
10:28:48 [DependencyCheck] [ERROR] Exception from bundle-audit process: java.io.IOException: Cannot run program "bundle-audit" (in directory "/tmp/dctempee8b025e-234d-4f29-95f7-93213a509ab6"): error=2, No such file or directory. Disabling Ruby Bundle Audit Analyzer

and the job is marked as fail therefore. How to write in jenkins pipeline to disable this analyzer?
I've used:

>  dependencyCheck additionalArguments: 'analyzers	{ bundleAuditEnabled=false }', odcInstallation: 

but didn't help. Thanks in advance

**Comment by jeremylong** [comment]
If you are receiving that message that means there is Ruby code that you are trying to scan. If you disable the bundle audit analyzer you could create false negatives (i.e. undetected vulnerable components).  Instead I would suggest installing bundle-audit:

```
gem install bundler-audit
bundle audit update
```

Alternatively, to disable the analyzer you use the same syntax as the CLI: https://jeremylong.github.io/DependencyCheck/dependency-check-cli/index.html

**Comment by marcinprzybysz86** [comment]
Thank you for the reply. 
I've finally disabled this bundle-audit as we don't have any Ruby code, all is written in Java. 

I'll try to verbose output to log file and let you know why it classified some file as Ruby content.

**Comment by ivyheasty** [comment]
@marcinprzybysz86 mind sharing how did you disable the bundle-audit?

**Comment by marcinprzybysz86** [comment]
unable to check which file is treated as ruby code, but we're pretty sure there's no ruby inside our code. I'll use it with the switch bundleAuditEnabled=false
