### ISSUE TITLE
Incorrect dll versions identified

### ISSUE THREAD

**Issue by RasmusOlesen** [dependency-check/DependencyCheck#2138]
We just did a scan of LibreOffice 6.2.5 Portable MultilangualStandard for windows.
And the analyzer failed to identify the following versions and instead used the number found in the filename.

python3.dll
ExifTool: 3.5.7
OWASP-Engine: 3.0.0

python35.dll
ExifTool: 3.5.7
OWASP-Engine: 3.5.0

libxml2.dll
ExifTool: 2.9.9
OWASP-Engine: 2.0.0

ssleay32.dll
ExifTool: 1.0.2r
OWASP-Engine:32.0.0

I know that not all dll's contain version metadata, but i dont really think that the Java GAV approach works either.

**Comment by jeremylong** [comment]
Dependency-check is not intended to scan binary executables - in this case it is trying to treat a native DLL as a dot net assembly. We need to do a better job of throwing an exception for native binaries (or others) from the `AssemblyAnalyzer`.

**Comment by jeremylong** [comment]
A new PE Analyzer should make this better - but only for PE as opposed to other binary formats.
