### ISSUE TITLE
Analyze SWID tags

### ISSUE THREAD

**Issue by dwvisser** [dependency-check/DependencyCheck#214]
@jeremylong made a great suggestion on #212. It should be possible, with the assistance of the [TagVault](http://tagvault.org/about/) resource, to analyze [SWID tags](http://tagvault.org/swid-tags/what-are-swid-tags/) present on a system. There is even a [document](http://tagvault.org/documents/2013/06/cpe-integration.pdf) and associated [blog post](http://tagvault.org/2012/04/23/cpe-integration/) proposing how CPEs should be generated/mapped from SWID tags.

**Comment by jeremylong** [comment]
I have not really seen any use of SWID (unfortunately). I'm going to close this enhancement request and if the usage increases we will create a new enhancement request.
