### ISSUE TITLE
DependencyCheck files outside of the folder specified

### ISSUE THREAD

**Issue by ktlim86** [dependency-check/DependencyCheck#2148]
Hello,

I have a problem where I used version 5.0.0-M2. The problem is I have removed the problematic dll from the folder that I wish to scan but the dependencycheck still scanned the dll but it is in another folder C:\Users\User\AppData\Local\Temp\dctempb8e8dc2b-974f-4fb5-b674-95014d9397e5\check21571493770273509tmp\4\lib\net45\BotDetect.Web.UI.Mvc.dll
Strangely, I noticed it is able to get the removed above DLL back into the AppData Local. 
Can you please advise what should I do to get the dependencycheck to scan the folder that I specified?

**Comment by ktlim86** [comment]
Hello! Any status on this one?

**Comment by jeremylong** [comment]
First, please consider upgrading dependency-check; you are using a milestone release (5.2.1 is the latest).

Second, when DLL files are found in zip, jar, war, bz2, etc. archive files - they are extracted to a temporary location, analyzed, and then deleted.  We should update the error message to use a different path (the one that points to the file in the directory scanned).
