### ISSUE TITLE
Ignore compile only dependency

### ISSUE THREAD

**Issue by emartynov** [dependency-check/DependencyCheck#2149]
**Is your feature request related to a problem? Please describe.**
Sometimes we are getting compile-time dependency vulnerability findings. This is false positive in my understanding. 

**Describe the solution you'd like**
Could owasp check ignore compile only dependencies?

**Describe alternatives you've considered**
Is it possible to suppress all compile dependencies in xml?

**Comment by jeremylong** [comment]
[Compile is the default scope](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scope) for Maven - and implies runtime. 

Are you thinking provided scope? Those can cause FP and there is a way to exclude them. Provided is a way to say I need the servlet API - but it will be provided at runtime by my JEE container.

**Comment by emartynov** [comment]
Hey, sorry for the miscommunication. I was talking about gradle [compileOnly](https://blog.gradle.org/introducing-compile-only-dependencies) which corresponds to `provided` in maven.

**Comment by jeremylong** [comment]
See `skipProvidedScope`: https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html

**Comment by jeremylong** [comment]
Posted this to the dependency-check-gradle issue tracker.

**Comment by jeremylong** [comment]
Pretty sure this can be accomplished using existing features:

```groovy
dependencyCheck {
   skipConfigurations = ['compileOnly', 'compileClasspath']
}
```
