### ISSUE TITLE
Running dependency-check on multi module build

### ISSUE THREAD

**Issue by johno1985** [dependency-check/DependencyCheck#2152]
Maven version: 3.6.1
Dependency check version: 5.2.1

Hi,

I have a multi module maven build and am trying to determine the correct configuration for running dependency check from the top level and generating a collated report of all sub modules. Please can you help?

I have the following config in my parent pom:

```
<pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.owasp</groupId>
                    <artifactId>dependency-check-maven</artifactId>
                    <version>${owasp-maven-plugin.version}</version>
                    <executions>
                        <execution>
                            <phase>none</phase>
                            <goals>
                                <goal>check</goal>
                            </goals>
                        </execution>
                    </executions>
                    <configuration>
                        <format>html</format>
                        <outputDirectory>${project.basedir}/target</outputDirectory>
                        <failBuildOnCVSS>0</failBuildOnCVSS>
                        <cveValidForHours>168</cveValidForHours>
                        <centralAnalyzerEnabled>false</centralAnalyzerEnabled>
                        <nexusAnalyzerEnabled>false</nexusAnalyzerEnabled>
                        <pyDistributionAnalyzerEnabled>false</pyDistributionAnalyzerEnabled>
                        <pyPackageAnalyzerEnabled>false</pyPackageAnalyzerEnabled>
                        <rubygemsAnalyzerEnabled>false</rubygemsAnalyzerEnabled>
                        <cmakeAnalyzerEnabled>false</cmakeAnalyzerEnabled>
                        <autoconfAnalyzerEnabled>false</autoconfAnalyzerEnabled>
                        <composerAnalyzerEnabled>false</composerAnalyzerEnabled>
                        <nodeAnalyzerEnabled>false</nodeAnalyzerEnabled>
                        <nuspecAnalyzerEnabled>false</nuspecAnalyzerEnabled>
                        <assemblyAnalyzerEnabled>false</assemblyAnalyzerEnabled>
                        <retireJsAnalyzerEnabled>false</retireJsAnalyzerEnabled>
                    </configuration>
                </plugin>
           </plugins>
</pluginManagement>
```

I have 9 sub modules, each with the following config:

```
<plugins>
            <plugin>
                <groupId>org.owasp</groupId>
                <artifactId>dependency-check-maven</artifactId>
                <configuration>
                    <suppressionFile>${project.parent.basedir}/owasp-suppressions.xml</suppressionFile>
                </configuration>
            </plugin>
</plugins>
```

I am running `mvn dependency-check:check` from the top level, but the report appears to only show information from the top-level (parent) project.

**Comment by mprins** [comment]
use the aggregate goal: `mvn dependency-check:aggregate`

eg 
```xml
...
<goals>
    <goal>check</goal>
</goals>
```

Also you can use the suppression file at the top level only, configured in the `<pluginManagement` section.

see: https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html

some example (pom config + Jenkins pipeline command):

https://github.com/flamingo-geocms/flamingo/blob/16e31944b2c6e1977c21f28edda92af6f2f673b9/pom.xml#L666-L676

https://github.com/flamingo-geocms/flamingo/blob/16e31944b2c6e1977c21f28edda92af6f2f673b9/Jenkinsfile#L80-L83

**Comment by jeremylong** [comment]
You should add the dependency-check plugin to the build or reporting section of your parent pom. I use the `<inherited>false</inherited>` (see [documentation](https://maven.apache.org/guides/mini/guide-configuring-plugins.html#Using_the_inherited_Tag_In_Build_Plugins)) at this level - so we don't re-run dependency-check on the child projects.  Lastly, you want to use, as @mprins pointed out, the aggregate goal:

```xml
<goals>
    <goal>aggregate</goal>
</goals>
```

There is then no need to put anything dependency-check related in the child projects.

**Comment by johno1985** [comment]
> use the aggregate goal: `mvn dependency-check:aggregate`
> 
> eg
> 
> ```
> ...
> <goals>
>     <goal>check</goal>
> </goals>
> ```
> 
> Also you can use the suppression file at the top level only, configured in the `<pluginManagement` section.
> 
> see: https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html
> 
> some example (pom config + Jenkins pipeline command):
> 
> https://github.com/flamingo-geocms/flamingo/blob/16e31944b2c6e1977c21f28edda92af6f2f673b9/pom.xml#L666-L676
> 
> https://github.com/flamingo-geocms/flamingo/blob/16e31944b2c6e1977c21f28edda92af6f2f673b9/Jenkinsfile#L80-L83

Hi @mprins 
I tried that originally but only the parent project was scanned, the child projects appear to be skipped:

```
[INFO] idam-commons-utils ................................. SUCCESS [ 11.794 s]
[INFO] commons-core ....................................... SKIPPED
[INFO] commons-validation ................................. SKIPPED
[INFO] commons-security ................................... SKIPPED
[INFO] commons-server ..................................... SKIPPED
[INFO] commons-ldap ....................................... SKIPPED
[INFO] commons-ldap-test .................................. SKIPPED
[INFO] commons-client ..................................... SKIPPED
[INFO] commons-validator .................................. SKIPPED
[INFO] commons-test ....................................... SKIPPED
```

Also, when the report was generated, it only had a report for the top-level

**Comment by johno1985** [comment]
> You should add the dependency-check plugin to the build or reporting section of your parent pom. I use the `<inherited>false</inherited>` (see [documentation](https://maven.apache.org/guides/mini/guide-configuring-plugins.html#Using_the_inherited_Tag_In_Build_Plugins)) at this level - so we don't re-run dependency-check on the child projects. Lastly, you want to use, as @mprins pointed out, the aggregate goal:
> 
> ```
> <goals>
>     <goal>aggregate</goal>
> </goals>
> ```
> 
> There is then no need to put anything dependency-check related in the child projects.

Hi @jeremylong 
OK, I'll try that, but which goal do I use from the mvn command line, check or aggregate?

**Comment by jeremylong** [comment]
aggregate

**Comment by johno1985** [comment]
> aggregate

Hi @jeremylong,

If I run the ```aggregate``` goal from the command line then only the top-level project gets scanned, the rest are skipped. Running the ```check``` goal seems to scan all projects though

**Comment by johno1985** [comment]
Also @jeremylong 
If I run ```check```, it seems that that the check succeeds but the report states that there are no suppressions when there are indeed several. I removed the suppressions, re-run and the check passes. When I run ```aggregate```, the check fails, I re-added the suppressions and the build passes but again, all sub-modules appear to be skipped. Also, only a report for the top-level project appears to be generated

**Comment by mprins** [comment]
> Also, only a report for the top-level project appears to be generated

this is why it is called an aggregate, it shows all of your project in 1 aggregate, if it just scanned the paren - which should have no dependencies - your report would be empty

**Comment by schapsl** [comment]
Hi @jeremylong  
> There is then no need to put anything dependency-check related in the child projects.

What about 

```
<configuration>
    <skip>true</skip>
</configuration> 
```
in child projects? Can i still do that then?

Thx.
Lars

**Comment by jeremylong** [comment]
I think what you would be looking for is `<inherited>false</inherited>`.  This is not in the configuration section - but at the plugin definition level.  See https://maven.apache.org/guides/mini/guide-configuring-plugins.html#Using_the_inherited_Tag_In_Build_Plugins

**Comment by schapsl** [comment]
Hi @jeremylong ,
thank you for the answer and sorry i didn't make it clear enough. I want to skip only certain "children". Let's say 3 out of 30. So far, i had the plugin in every child pom (via parent pom) and set skip=true for the ones I didn't want to process.

But with the new plugin version, i get 27 result files and my Jenkins shows me 27 results for the build job which is not helpful. :-(
Before I hab only one result shown in the Jenkins build (which might have been wrong from the start).

How can i select/deselect the child modules when goal is aggregate and inherit=false? I don't see how.

I'm already using a suppression file, but I can't get the same result as if I am skipping whole modules.

Thanks
Lars

**Comment by jeremylong** [comment]
At the moment - there is no way to skip specific children in an aggregate report.  Also, without putting inherited=false in the parent you will receive an aggregate report generated for the parent that will contain everything AND an aggregate report for each child (aggregating itself and any of its child poms). 

One option to explore would be to setup a profile that excluded the children you don't want to include and run dependency-check under that profile.
