### ISSUE TITLE
Proxy with nist-data-mirror

### ISSUE THREAD

**Issue by 2fortunately** [dependency-check/DependencyCheck#2159]
Hello team. In my issue i had problems like in [#2039](https://github.com/jeremylong/DependencyCheck/issues/2039) and [#1679](https://github.com/jeremylong/DependencyCheck/issues/1679) and to fix them i need to use proxy and nist-data-mirror.
In our project we use proxy server, and i need to update NVD & RetireJS. If i start dependency check without proxy configuration and with NVD & RetireJS configuration - NVD & RetireJS can success update, but DependencyCheck fails cause haven't got internet connection:
If i start  with proxy parametrs and with NVD & RetireJS parametrs DependecyCheck correct work first 4 hour when skips NVD check (Skipping NVD check since last check was within 4 hours). After 4 hours dependency check fail cause can't connect to nist-data-mirror via proxy. 
So can i somehow to first update dependency check without proxy and then start check project with proxy? Somehow like this:
just updates bases
dependencyCheck additionalArguments: '--cveUrlBase http://192.168.1.10:8082/nist/nvdcve-1.0-%d.json.gz --cveUrlModified http://192.168.1.10:8082/nist/nvdcve-1.0-modified.json.gz --retireJsUrl http://192.168.1.10:8082/js/jsrepository.json', odcInstallation: 'dependency-check-5.2.1'
just checks
dependencyCheck additionalArguments: '--scan /var/jenkins_home/workspace/devproject --format XML --format HTML --proxyserver 192.168.1.2 --proxyport 3128 --disableOssIndexCache --disableCentralCache --disableNodeAuditCache', odcInstallation: 'dependency-check-5.2.1'
OR can you add some command line true/false argument like --nexusUsesProxy , --artifactoryUseProxy ? To example --cveUrlUseProxy and --retireJsUseProxy
OR can you add some command line argument like linux or jenkins no proxy configuration? To example --noProxyHost , --noProxy , --proxyException with Parameters like "127.0.0.1, localhost, *.cnn.com, 192.168.1.10, domain.com:8080" or --noProxy 127.0.0.1 --noProxy localhost --noProxy *.cnn.com --noProxy 192.168.1.10 --noProxy domain.com:8080

**Comment by jeremylong** [comment]
The proxy may not be proxying the NVD.  Consider running this in two steps:

dependency-check --updateonly
dependency-check --noupdate [setup proxy] ...

**Comment by mum-viadee** [comment]
I'm facing a similar problem. Whe have a mirror of the NVD in our company that is not reachable throught the company proxy.  If I use the proxy settings, the NVD update fails. If I don't use the proxy settings, the update succeeds, but the NPM Audit Analyser fails. 

Of course the workaround you've presented would work for us, but it would be handy to have an commandline agrument for setting non proxied hosts.

**Comment by jeremylong** [comment]
While not exposed as a property yet in the CLI you could do something like:

```
export JAVA_OPTS=-Dproxy.nonproxyhosts=non.proxy.host
```

**Comment by jeremylong** [comment]
TODO: expose the non-proxy host configuration to the CLI, Ant, etc.

**Comment by jeremylong** [comment]
Turns out `--nonProxyHosts` was already implemented.
