### ISSUE TITLE
Initialisation of non-H2 database 

### ISSUE THREAD

**Issue by anthonyharrison** [dependency-check/DependencyCheck#216]
I am trying to use Postgresql as my database engine and by correctly specifying the driver name, path and connectionstring I am able to connect to Postgresql. However, it is unable to continue because there is no database schema available. The default schema (data/initialize.sql) is only for the H2 database and it would be useful if the location of an alternative database schema could be specified as an additional command line parameter e.g dbSchemaFile.

**Comment by jeremylong** [comment]
While I can add this, my original intent was that if someone were going to use a more robust DB engine they would just create the database, create the user, modify the schema file as appropriate for their database and then execute dependency-check to update the db.

I always saw the use of a more robust database as a way to only have one server on the network need to connect out to the NVD to download the NVD CVE data. You could put dependency-check on a server that could connect to the Internet and use that to update the internal database. Then other instances of dependency-check could be running internally to perform scans. However, to increase the accuracy of dependency-check there are many times that Central is queried for information about the given JAR file. If most of your dependency-check scans cannot connect to Central you may have additional false negatives. This can be solved by using an internal Nexus server (or other repo server AFTER an analyzer has been built to query it).

**Comment by jeremylong** [comment]
Documentation pertaining to using a centralized database server has been added. For now see [database.md](https://github.com/jeremylong/DependencyCheck/blob/master/src/site/markdown/data/database.md). This will be added to the [documentation site](https://jeremylong.github.io/DependencyCheck/) in the next release.
