### ISSUE TITLE
DownloaderIT unit test fails

### ISSUE THREAD

**Issue by kilinitt** [dependency-check/DependencyCheck#2160]
**Describe the bug**
Cloning from GitHub and running `mvn install` fails due to DownloaderIT unit test failure.

**Log Output**
> [ERROR]   DownloaderIT.testFetchFile:42 » MalformedURL no protocol

**Additional context**
Looks like ${odc.cve.url.base} and ${odc.cve.url.modified} in pom.xml are not set, resulting in the corresponding properties being set to blank, and overwriting the local properties files.

```xml
<property> 
   <name>cve.url.base</name> 
   <value>${odc.cve.url.base}</value>
</property>
<property>
   <name>cve.url.modified</name>
   <value>${odc.cve.url.modified}</value>
</property>
```
Commenting them out in pom.xml fixed it for me. Thanks.

**Comment by mprins** [comment]
use `mvn -s settings.xml install` or specify the properties yourself

**Comment by kilinitt** [comment]
Thank you @mprins. Closing it...

**Comment by jeremylong** [comment]
Yeah - we should put the `mvn -s settings.xml install` into the README.md...
