### ISSUE TITLE
Unable to resolve system scoped dependency: com.sun.java:tools:jar:1.8.0_141:system

### ISSUE THREAD

**Issue by piotr-sumo** [dependency-check/DependencyCheck#2164]
**Describe the bug**
`aggregate` fails with `Unable to resolve system scoped dependency: com.sun.java:tools:jar:1.8.0_141:system` despite `<skipSystemScope>true</skipSystemScope>` setting enabled.

** Version of dependency-check used **
The problem occurs using version 5.2.1 of the the maven plugin.

**To Reproduce**
1. Add `<skipSystemScope>true</skipSystemScope>` to config
2. Run `dependency-check:aggregate`
3. See `[ERROR] Unable to resolve system scoped dependency: com.sun.java:tools:jar:1.8.0_181:system`

**Expected behavior**
`aggregate` ignores system scoped dependency as required by config setting.  

**Additional context**
`check` works as expected and ignores system scoped dependency.

**Comment by jeremylong** [comment]
Any chance you can share your pom?

**Comment by piotr-sumo** [comment]
I'm working on minimizing our pom so that the bug can be reproduced

**Comment by piotr-sumo** [comment]
@jeremylong while working on the pom I found misconfiguration on our side. I'm therefore closing this issue.
