### ISSUE TITLE
JAVA_OPTS in the wrong order to be usefull

### ISSUE THREAD

**Issue by kdeenkhoorn** [dependency-check/DependencyCheck#2172]
With version 4.02 and also 5.2.1 i have noticed a wrong placement of the $JAVA_OPTS in the cli verision of the tool.
The startup file states:
`
exec "$JAVACMD" $JAVA_OPTS  \
  -classpath "$CLASSPATH" \
  -Dapp.name="dependency-check" \
  -Dapp.pid="$$" \
  -Dapp.repo="$REPO" \
  -Dapp.home="$BASEDIR" \
  -Dbasedir="$BASEDIR" \
  org.owasp.dependencycheck.App \
  "$@"
`

But if you whant to use a JAVA_OPTS from the environment, fir example:

export JAVA_OPTS="-Ddownloader.quick.query.timestamp=false" 

this results in an error at startup.

This can be solved for example by moving this variable after the classpath in the commandline like:

`
exec "$JAVACMD" -classpath "$CLASSPATH"  "$JAVA_OPTS"  \
  -Dapp.name="dependency-check" \
  -Dapp.pid="$$" \
  -Dapp.repo="$REPO" \
  -Dapp.home="$BASEDIR" \
  -Dbasedir="$BASEDIR" \
  org.owasp.dependencycheck.App \
  "$@"
`

Thnaks for the great tool.

Klaas Eenkhoorn

**Comment by aikebah** [comment]
What error do you get at startup? 
Because the issue is not with the position of the $JAVA_OPTS. A `-D<name>=<value>` is accepted by java before and after the `-classpath` option (which is logical because both are just interchangeable '-options' choices)

```text
Usage: java [-options] class [args...]
           (to execute a class)
   or  java [-options] -jar jarfile [args...]
           (to execute a jar file)
where options include:
    -d32	  use a 32-bit data model if available
    -d64	  use a 64-bit data model if available
    -server	  to select the "server" VM
                  The default VM is server,
                  because you are running on a server-class machine.


    -cp <class search path of directories and zip/jar files>
    -classpath <class search path of directories and zip/jar files>
                  A : separated list of directories, JAR archives,
                  and ZIP archives to search for class files.
    -D<name>=<value>
                  set a system property
    -verbose:[class|gc|jni]
                  enable verbose output
    -version      print product version and exit
    -version:<value>
                  Warning: this feature is deprecated and will be removed
                  in a future release.
                  require the specified version to run
    -showversion  print product version and continue
    -jre-restrict-search | -no-jre-restrict-search
                  Warning: this feature is deprecated and will be removed
                  in a future release.
                  include/exclude user private JREs in the version search
    -? -help      print this help message
    -X            print help on non-standard options
    -ea[:<packagename>...|:<classname>]
    -enableassertions[:<packagename>...|:<classname>]
                  enable assertions with specified granularity
    -da[:<packagename>...|:<classname>]
    -disableassertions[:<packagename>...|:<classname>]
                  disable assertions with specified granularity
    -esa | -enablesystemassertions
                  enable system assertions
    -dsa | -disablesystemassertions
                  disable system assertions
    -agentlib:<libname>[=<options>]
                  load native agent library <libname>, e.g. -agentlib:hprof
                  see also, -agentlib:jdwp=help and -agentlib:hprof=help
    -agentpath:<pathname>[=<options>]
                  load native agent library by full pathname
    -javaagent:<jarpath>[=<options>]
                  load Java programming language agent, see java.lang.instrument
    -splash:<imagepath>
                  show splash screen with specified image
See http://www.oracle.com/technetwork/java/javase/documentation/index.html for more details.
```

**Comment by kdeenkhoorn** [comment]
Unfortunately it does matter, the error i'm getting is:
Error: Could not find or load main class "-Ddownloader.quick.query.timestamp=false"

`
/var/lib/jenkins/tools/org.jenkinsci.plugins.DependencyCheck.tools.DependencyCheckInstallation/NPLCM-dependency-check-5.2.1-exp/dependency-check/bin/dependency-check.sh --project spring-petclinic-weblogic-12c-pipeline --connectionString jdbc:oracle:thin:@******** --dbDriverName oracle.jdbc.driver.OracleDriver --dbUser **** --dbPassword '****' --proxyserver ******* --proxyport 8080 --connectiontimeout 60 --scan ./ --format XML --log ./logfile.log --noupdate
Error: Could not find or load main class "-Ddownloader.quick.query.timestamp=false" 
`
My jenkinsjob definition:

`
withEnv(['JAVA_OPTS="-Ddownloader.quick.query.timestamp=false"']) {
                     withCredentials([usernamePassword(credentialsId: '******', passwordVariable: 'password', usernameVariable: 'username')]) {
                        sh "${scannerHome}/bin/dependency-check.sh --project 'spring-petclinic-weblogic-12c-pipeline' \
                                                                   --connectionString 'jdbc:oracle:thin:@********' \
                                                                   --dbDriverName oracle.jdbc.driver.OracleDriver \
                                                                   --dbUser \'${username}\' \
                                                                   --dbPassword \'${password}\' \
                                                                   --proxyserver ******* \
                                                                   --proxyport 8080 \
                                                                   --connectiontimeout 60 \
                                                                   --scan './' \
                                                                   --format XML \
                                                                   --log ./logfile.log \
                                                                   --noupdate"
                     }
                    }
`

**Comment by aikebah** [comment]
Which matches my suspicion that the root cause is not the position of JAVA_OPTS.

Java does not recognize the `-Ddownloader.quick.query.timestamp=false` as a CLI -option which makes it then interpret it as the class-name. The class-name is the first non-`-options` argument to java and anything that follows are the command line arguments for the main method of that class.

Try using withEnv(['JAVA_OPTS=-Ddownloader.quick.query.timestamp=false']) I suspect that the quotes in the withEnv are causing your issue and suspect that they are in some way escaped by the withEnv Jenkins code so that they end up with actual quotes being present in the environment variable value.

**Comment by kdeenkhoorn** [comment]
My error, it does indeed work like this:
`
withEnv(['JAVA_OPTS=-Ddownloader.quick.query.timestamp=false']) {
 sh "${scannerHome}/bin/dependency-check.sh --connectionString 'jdbc:oracle:thin:...
}
`
Had to remove the dubble quotes.

**Comment by kdeenkhoorn** [comment]
Issue can be closed.
