### ISSUE TITLE
Maven proxy config works from windows PC, but not RH Jenkins node

### ISSUE THREAD

**Issue by csphils** [dependency-check/DependencyCheck#2173]
Here is the situation:  I use a cert along with a proxy to access the nvd.  It works on windows and not on a RH box.  I get an error "Using the configured proxy username and password" but I'm haven't configure them.  Any ideas?

Win10 client:
- Proxy setting in `~/.m2/settings.xml` with server and port
- Cert file in `$JAVA_HOME/jre/lib/security/cacerts`
- `-Djavax.net.ssl.trustStore=/path/to/cacerts` also worked
- `-Ddownloader.quick.query.timestamp=false` was also required to stop failing 95%
- Apache Maven 3.3.9 
- Java version: 1.8.0_45, vendor: Oracle Corporation

RH server:
- Proxy setting in ~/.m2/settings.xml 
- Cert file in $JAVA_HOME/jre/lib/security/cacerts
- Also tried -Djavax.net.ssl.trustStore=/path/to/cacerts
- Apache Maven 3.3.9 
- Java version: 1.8.0_212, vendor: Oracle Corporation

The proxy has worked on my desktop with the configs above, but I can't get it to work on the RH box.  I don't have CLI access but I can modify jobs.  

I use the following parameters to run it (or use a config in the POM):
- ` mvn org.owasp:dependency-check-maven:3.3.4:aggregate`

Here is the error I get:
```
[DEBUG] Checking for updates from: https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2005.xml.gz
[DEBUG] Checking for updates from: https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2014.xml.gz
[DEBUG] Available Protocols:
[DEBUG] SSLv2Hello
[DEBUG] SSLv3
[DEBUG] TLSv1
[DEBUG] TLSv1.1
[DEBUG] TLSv1.2
**[DEBUG] Using the configured proxy username and password**
[WARNING] Unable to download the NVD CVE data; the results may not include the most recent CPE/CVEs from the NVD.
```

No Username or Password is defined that I can find on either box.  I've looked in the global settings and my settings, and I've also tried to override them from the command line. 

I've read some articles about NTLM but haven't been able to understand enough to test.

**Comment by aikebah** [comment]
Modify the job to run the `mvn help:effective-settings` for your project on both boxes and compare them.

The log message appears to stem from https://github.com/jeremylong/DependencyCheck/blob/6cad6f389c4fd0f745d267116989c14106be9a2c/utils/src/main/java/org/owasp/dependencycheck/utils/URLConnectionFactory.java#L96

Which is guarded by non-null username and password from the proxy. From a quick first look at the source of those (dependency-check) Settings they appear to be resolved from the Maven Settings object for the active proxy (the first in Maven's proxy list that is 'active' unless also the property 'mavenSettingsProxyId' is set, in that case it returns the Maven Settings proxy that has that Id.

**Comment by csphils** [comment]
Thanks for that effective settings goal. really great tool.  

Here is the proxy section for both machines.  There are differences in the <server> section with multiple username/password/id's, and an additional <repository> on the RH box, but nothing different related to the proxy.

```
    <proxy>
      <username />
      <password />
      <host>proxy.foo.blah.com</host>
      <nonProxyHosts>*.blah.com|*.blah.com</nonProxyHosts>
      <id>BLAHproxy</id>
    </proxy>
```
**Update:**
I removed the username and password, resulting in the following effective-pom and new error.

```
    <proxy>
      <host>proxy.foo.blah.com</host>
      <nonProxyHosts>*.blah.com|*.blah.com</nonProxyHosts>
      <id>BLAHproxy</id>
    </proxy>
```

```
java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 BLAHauthenticationrequired"
	at sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2142)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162)
	at org.owasp.dependencycheck.utils.Downloader.getLastModified(Downloader.java:268)
	at org.owasp.dependencycheck.utils.Downloader.getLastModified(Downloader.java:235)
	at org.owasp.dependencycheck.data.update.NvdCveUpdater$TimestampRetriever.call(NvdCveUpdater.java:512)
	at org.owasp.dependencycheck.data.update.NvdCveUpdater$TimestampRetriever.call(NvdCveUpdater.java:485)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[DEBUG] Setting: downloader.quick.query.timestamp='false'
[DEBUG] Exception details
```
**Another update:**
I'm wondering if the proxy uses NTLM.  Read this article and am thinking it could have something to do with it: https://docs.oracle.com/javase/8/docs/technotes/guides/net/http-auth.html
