### ISSUE TITLE
What are the precise maven-site-plugin dependencies (doxia)?

### ISSUE THREAD

**Issue by beargiles** [dependency-check/DependencyCheck#2177]
I've been chasing my tail for a few hours trying to get the maven-site-plugin (doxia) dependencies set up. With a dependency on 'doxia-module-markdown:1.8' and 1.9 I get

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site 
(default-cli) on project snaps: Execution default-cli of goal org.apache.maven.plugins:maven-site-plugin:3.3:site failed: A required class was missing while executing 
org.apache.maven.plugins:maven-site-plugin:3.3:site: 
org/apache/maven/doxia/siterenderer/DocumentContent
[ERROR] -----------------------------------------------------
```

I can add an explicit dependency for doxia-site-renderer that still has that class but then I can't find a different class, repeat. I eventually reached the point where there was one dependency on a class that did not exist after doxia-core:1.4 and a different dependency on a class that didn't exist prior to doxia-core:1.5!

I'm using maven-site-plugin:3.3. With versions 3.1 and 3.2 I get an error on no org/sonatype/aether/graph/DependencyFilter.

I could chase my tail some more but it's clear other people aren't having this problem. I'm trying to run this in a project with a LOT of dependencies there could be some subtle dependencies that I'll need to force.

A simple "mvn dependency:tree" on a working configuration may be enough to tell me what I need.

Thanks.

**Comment by mprins** [comment]
It mostly depends on your maven version.
 I would suggest using a current maven release (3.6.2) and a current maven-site-plugin (3.8.2 )
As you may have guessed the 2013 version your are using is incompatible with other  up2date plugins.

see also: https://maven.apache.org/plugins/maven-site-plugin/history.html 


Also `mvn dependency:tree` will not show plugin dependencies for your project!

**Comment by aikebah** [comment]
In order to get current (as @mprins properly recommends) you can call in the help of the [maven versions plugin](https://www.mojohaus.org/versions-maven-plugin/).

mvn versions:display-plugin-updates will analyze your project and show the current version for all your out-of-date plugins.
