### ISSUE TITLE
Any artifacts with a groupId that start with com.google get flagged for chrome bugs

### ISSUE THREAD

**Issue by sellersj** [dependency-check/DependencyCheck#218]
I found it with gson, but I tested a couple others too and they all seem to get flagged with the same bugs. Flagged using both the maven plugin and command line.

dependency-check version: 1.2.10

e.g.

``` xml
    <dependency>
      <groupId>com.google.code.gson</groupId>
      <artifactId>gson</artifactId>
      <version>2.3.1</version>
    </dependency>
    <dependency>
      <groupId>com.google.gerrit</groupId>
      <artifactId>gerrit-extension-api</artifactId>
      <version>2.11</version>
    </dependency>
    <dependency>
      <groupId>com.google.apis</groupId>
      <artifactId>google-api-services-sqladmin</artifactId>
      <version>v1beta4-rev5-1.20.0</version>
    </dependency>
```

**Comment by jeremylong** [comment]
Thank you for the bug report. This one isn't as simple as some of the other false positives that have been reported - and you may have pointed out a deeper bug in the system as I don't see why v8 was flagged from some of the libraries.  Regardless, I'll download several more com.google.X libraries and tune things to ensure that they are not erroneously flagged.

--Jeremy

**Comment by jeremylong** [comment]
Patches have been applied to 1.2.11-SNAPSHOT to resolve this issue and will be included in the next release.

Thanks for the bug report!

Jeremy
