### ISSUE TITLE
Server 'artifactory' not found in the settings.xml file

### ISSUE THREAD

**Issue by maksymgendin** [dependency-check/DependencyCheck#2181]
**Describe the bug**
I have dependency-check-maven plugin configured as a build plugin which runs on the **verify** phase (default) and executes the **check** goal. Additionally I have the Artifactory analyzer enabled by setting **artifactoryAnalyzerEnabled** to **true** and I have a custom URL (our internal artifactory server: https://artifact.ourdomain.com/artifactory) which I provide to **artifactoryAnalyzerUrl**.
When I run **mvn verify** - it fails with the exception from the issue title (exception is thrown in org.owasp.dependencycheck.maven.BaseDependencyCheckMojo#configureServerCredentials). 

**Version of dependency-check used**
The problem occurs using version 5.1.0 of the the maven plugin.

**Log file**
https://gist.github.com/maksymgendin/4ec4d29c888f9c7f977b74699d3954c0

**Expected behavior**
I have nothing special to configure for our internal Artifactory server - no authentication or so. In my opinion there is no reason to create an empty server block just for avoiding this error:
```
<servers>
  <server>
    <id>artifactory</id>
  </server>
</servers>
```
Please adapt your code not to fail if there is no such server block in the settings.xml.

**Comment by maksymgendin** [comment]
Problem is the set **defaultValue** attribute for **artifactoryAnalyzerServerId** property:
```java
@Parameter(property = "artifactoryAnalyzerServerId", defaultValue = "artifactory")
```

**Comment by jeremylong** [comment]
I just removed the default values - they should not have been there.
