### ISSUE TITLE
How can a  use the maven central analyser without  Internet access

### ISSUE THREAD

**Issue by kdeenkhoorn** [dependency-check/DependencyCheck#2187]
All,

I have a OWASP dependency checker installation living in an environment without internet access.
The CVE database is supplied to me and updated,

Now the maven central analyser fails on accessing search.maven.com.
Also i have a nexus OSS 3 and not Pro version. How can i make use of my nexus OSS installation to provide data to the maven central analyser, or is my only option in this setup to disable this scanner ?
The nexus OSS 3 server has configured maven central as proxy repository by the way.

Thanks in advance.

**Comment by aikebah** [comment]
Unsure about OSS3, but Nexus OSSv2 works fine for our on-premise installation... so you could just try configuring the rest-api URL of your Nexus OSSv3 instance as the Nexus URL and enable the nexusAnalyzer (which will disable the Central Analyzer automatically)

**Comment by jeremylong** [comment]
Best would be to use ODC as a build plugin (mvn, gradle, sbt, or lein) and disable the central analyzer.  All of the information gained by using the central analyzer is obtained directly from the dependency management system in the build tool.
