### ISSUE TITLE
CVSSv2 and CVSSv3

### ISSUE THREAD

**Issue by mjdavies** [dependency-check/DependencyCheck#2190]
Hi there

We've been using version 4.0.2 of the Dependency Check Jenkins Plugin for a while now, and we're about to upgrade.

As a test, I downloaded the 5.2.1 version of the dependency check cli and ran that against our codebase.

The 5.2.1 results include far more vulnerabilities, including numerous critical ones.  All the new vulnerabilities are graded using the CVSSv3_BaseSeverity.

The 4.0.2 jenkins plugin output ONLY includes the vulnerabilities that are graded with the CVSSv2_Severity.

Am I doing something wrong with how I'm using the 4.0.2 jenkins plugin?  Is there a way that I could see the vulnerabilities that don't have a CVSSv2_Severity rating in 4.0.2?

Anny help, greatly appreciated.

**Comment by jeremylong** [comment]
The version of the CVSS used entirely depends on the data in the NVD.  The 5.x versions use the JSON data feeds from the NVD which has the CVSSv3 for more recent (within the last year? maybe farther back).  But the older CVE entries still only have CVSSv2 data.

**Comment by mjdavies** [comment]
Thanks for getting back to me Jeremy.

So is version 4.0 not picking up all the vulnerabilities?  That's what it appears to be doing to me, unless I'm doing something wrong with the tool.

One thing I noticed is we don't see any vulnerabilities in the 4.0.2 jenkins output with a source from OSSINDEX.

>         dependencyCheckAnalyzer datadir: '/home/jenkins/owasp/updates',
>         hintsFile: '',
>         includeCsvReports: true,
>         includeVulnReports: true,
>         includeHtmlReports: false,
>         includeJsonReports: false,
>         isAutoupdateDisabled: true,
>         outdir: '',
>         scanpath: '',
>         skipOnScmChange: false,
>         skipOnUpstreamChange: false,
>         suppressionFile: '',
>         zipExtensions: ''

**Comment by jeremylong** [comment]
Correct - the JSON data feeds have a lot more information that makes the ODC analysis more effective.  In addition - next month the NVD XML data feeds will go away and all users will need to upgrade to 5.x.

**Comment by mjdavies** [comment]
Thanks for the explanation Jeremy.
