### ISSUE TITLE
docker: FileNotFoundException: /usr/share/dependency-check/data/jsrepository.json (Permission denied)

### ISSUE THREAD

**Issue by githubhs17** [dependency-check/DependencyCheck#2192]
Getting error **FileNotFoundException: /usr/share/dependency-check/data/jsrepository.json (Permission denied)** using docker run with image owasp/dependency-check:latest

This is a **Permission denied** inside the docker container

20:52:25  [INFO] Checking for updates
20:52:43  [INFO] NVD CVE requires several updates; this could take a couple of minutes.
20:52:43  [INFO] Download Started for NVD CVE - 2002
20:52:43  [INFO] Download Started for NVD CVE - 2003
20:52:43  [INFO] Download Complete for NVD CVE - 2003  (2134 ms)
20:52:43  [INFO] Processing Started for NVD CVE - 2003
20:52:43  [INFO] Download Started for NVD CVE - 2004
20:52:45  [INFO] Download Complete for NVD CVE - 2002  (4517 ms)
20:52:45  [INFO] Processing Started for NVD CVE - 2002
20:52:45  [INFO] Download Started for NVD CVE - 2005
20:52:46  [INFO] Download Complete for NVD CVE - 2004  (3321 ms)
20:52:46  [INFO] Download Started for NVD CVE - 2006
20:52:46  [INFO] Processing Started for NVD CVE - 2004
20:52:49  [INFO] Download Complete for NVD CVE - 2005  (4149 ms)
20:52:49  [INFO] Download Started for NVD CVE - 2007
20:52:49  [INFO] Processing Started for NVD CVE - 2005
20:52:52  [INFO] Download Complete for NVD CVE - 2006  (6033 ms)
20:52:52  [INFO] Download Started for NVD CVE - 2008
20:52:52  [INFO] Processing Started for NVD CVE - 2006
20:52:55  [INFO] Download Complete for NVD CVE - 2007  (5824 ms)
20:52:55  [INFO] Download Started for NVD CVE - 2009
20:52:55  [INFO] Processing Started for NVD CVE - 2007
20:52:59  [INFO] Download Complete for NVD CVE - 2008  (6155 ms)
20:52:59  [INFO] Download Started for NVD CVE - 2010
20:52:59  [INFO] Processing Started for NVD CVE - 2008
20:53:01  [INFO] Download Complete for NVD CVE - 2009  (5321 ms)
20:53:01  [INFO] Processing Started for NVD CVE - 2009
20:53:01  [INFO] Download Started for NVD CVE - 2011
20:53:05  [INFO] Download Complete for NVD CVE - 2010  (6623 ms)
20:53:05  [INFO] Download Started for NVD CVE - 2012
20:53:05  [INFO] Processing Started for NVD CVE - 2010
20:53:11  [INFO] Download Complete for NVD CVE - 2012  (5922 ms)
20:53:11  [INFO] Download Started for NVD CVE - 2013
20:53:11  [INFO] Processing Started for NVD CVE - 2012
20:53:11  [INFO] Download Complete for NVD CVE - 2011  (10781 ms)
20:53:11  [INFO] Download Started for NVD CVE - 2014
20:53:11  [INFO] Processing Started for NVD CVE - 2011
20:53:18  [INFO] Download Complete for NVD CVE - 2013  (6339 ms)
20:53:18  [INFO] Processing Started for NVD CVE - 2013
20:53:18  [INFO] Download Started for NVD CVE - 2015
20:53:18  [INFO] Download Complete for NVD CVE - 2014  (6476 ms)
20:53:18  [INFO] Download Started for NVD CVE - 2016
20:53:18  [INFO] Processing Started for NVD CVE - 2014
20:53:23  [INFO] Download Complete for NVD CVE - 2015  (5605 ms)
20:53:23  [INFO] Download Started for NVD CVE - 2017
20:53:23  [INFO] Processing Started for NVD CVE - 2015
20:53:24  [INFO] Download Complete for NVD CVE - 2016  (6673 ms)
20:53:24  [INFO] Download Started for NVD CVE - 2018
20:53:24  [INFO] Processing Started for NVD CVE - 2016
20:53:34  [INFO] Download Complete for NVD CVE - 2017  (10797 ms)
20:53:34  [INFO] Processing Started for NVD CVE - 2017
20:53:34  [INFO] Download Started for NVD CVE - 2019
20:53:39  [INFO] Download Complete for NVD CVE - 2018  (14057 ms)
20:53:39  [INFO] Processing Started for NVD CVE - 2018
20:53:39  [INFO] Download Complete for NVD CVE - 2019  (5443 ms)
20:53:39  [INFO] Processing Started for NVD CVE - 2019
20:53:39  [ERROR] java.util.concurrent.ExecutionException: org.owasp.dependencycheck.analyzer.exception.UnexpectedAnalysisException: org.h2.jdbc.JdbcSQLException: The database is read only; SQL statement:
20:53:39  DELETE FROM reference WHERE cveid = ? [90097-196]
20:53:39  org.owasp.dependencycheck.data.update.exception.UpdateException: java.util.concurrent.ExecutionException: org.owasp.dependencycheck.analyzer.exception.UnexpectedAnalysisException: org.h2.jdbc.JdbcSQLException: The database is read only; SQL statement:
20:53:39  DELETE FROM reference WHERE cveid = ? [90097-196]
20:53:39  	at org.owasp.dependencycheck.data.update.NvdCveUpdater.performUpdate(NvdCveUpdater.java:298)
20:53:39  	at org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:125)
20:53:39  	at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:922)
20:53:39  	at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:723)
20:53:39  	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:653)
20:53:39  	at org.owasp.dependencycheck.App.runScan(App.java:251)
20:53:39  	at org.owasp.dependencycheck.App.run(App.java:183)
20:53:39  	at org.owasp.dependencycheck.App.main(App.java:80)
20:53:39  Caused by: java.util.concurrent.ExecutionException: org.owasp.dependencycheck.analyzer.exception.UnexpectedAnalysisException: org.h2.jdbc.JdbcSQLException: The database is read only; SQL statement:
20:53:39  DELETE FROM reference WHERE cveid = ? [90097-196]
20:53:39  	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
20:53:39  	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
20:53:39  	at org.owasp.dependencycheck.data.update.NvdCveUpdater.performUpdate(NvdCveUpdater.java:288)
20:53:39  	... 7 common frames omitted
20:53:39  Caused by: org.owasp.dependencycheck.analyzer.exception.UnexpectedAnalysisException: org.h2.jdbc.JdbcSQLException: The database is read only; SQL statement:
20:53:39  DELETE FROM reference WHERE cveid = ? [90097-196]
20:53:39  	at org.owasp.dependencycheck.data.nvdcve.CveDB.updateVulnerabilityGetVulnerabilityId(CveDB.java:1008)
20:53:39  	at org.owasp.dependencycheck.data.nvdcve.CveDB.updateVulnerability(CveDB.java:927)
20:53:39  	at org.owasp.dependencycheck.data.update.nvd.NvdCveParser.parse(NvdCveParser.java:99)
20:53:39  	at org.owasp.dependencycheck.data.update.nvd.ProcessTask.importJSON(ProcessTask.java:139)
20:53:39  	at org.owasp.dependencycheck.data.update.nvd.ProcessTask.processFiles(ProcessTask.java:152)
20:53:39  	at org.owasp.dependencycheck.data.update.nvd.ProcessTask.call(ProcessTask.java:113)
20:53:39  	at org.owasp.dependencycheck.data.update.nvd.ProcessTask.call(ProcessTask.java:40)
20:53:39  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
20:53:39  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
20:53:39  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
20:53:39  	at java.base/java.lang.Thread.run(Thread.java:834)
20:53:39  Caused by: org.h2.jdbc.JdbcSQLException: The database is read only; SQL statement:
20:53:39  DELETE FROM reference WHERE cveid = ? [90097-196]
20:53:39  	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
20:53:39  	at org.h2.message.DbException.get(DbException.java:179)
20:53:39  	at org.h2.message.DbException.get(DbException.java:155)
20:53:39  	at org.h2.message.DbException.get(DbException.java:144)
20:53:39  	at org.h2.engine.Database.checkWritingAllowed(Database.java:1935)
20:53:39  	at org.h2.table.Table.checkWritingAllowed(Table.java:1186)
20:53:39  	at org.h2.engine.User.hasRight(User.java:114)
20:53:39  	at org.h2.engine.User.checkRight(User.java:100)
20:53:39  	at org.h2.command.dml.Delete.update(Delete.java:57)
20:53:39  	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
20:53:39  	at org.h2.command.Command.executeUpdate(Command.java:260)
20:53:39  	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:207)
20:53:39  	at org.owasp.dependencycheck.data.nvdcve.CveDB.updateVulnerabilityGetVulnerabilityId(CveDB.java:998)
20:53:39  	... 10 common frames omitted
20:53:40  [WARN] Unable to save property 'VersionCheckOn' with a value of '1568228019' to the database
20:53:40  [ERROR] Failed to initialize the RetireJS repo
20:53:40  org.owasp.dependencycheck.data.update.exception.UpdateException: Failed to initialize the RetireJS repo
20:53:40  	at org.owasp.dependencycheck.data.update.RetireJSDataSource.initializeRetireJsRepo(RetireJSDataSource.java:151)
20:53:40  	at org.owasp.dependencycheck.data.update.RetireJSDataSource.update(RetireJSDataSource.java:97)
20:53:40  	at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:922)
20:53:40  	at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:723)
20:53:40  	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:653)
20:53:40  	at org.owasp.dependencycheck.App.runScan(App.java:251)
20:53:40  	at org.owasp.dependencycheck.App.run(App.java:183)
20:53:40  	at org.owasp.dependencycheck.App.main(App.java:80)
20:53:40  Caused by: org.owasp.dependencycheck.utils.DownloadFailedException: Download failed, unable to copy 'https://raw.githubusercontent.com/Retirejs/retire.js/master/repository/jsrepository.json' to '/usr/share/dependency-check/data/jsrepository.json'
20:53:40  	at org.owasp.dependencycheck.utils.Downloader.fetchFile(Downloader.java:91)
20:53:40  	at org.owasp.dependencycheck.utils.Downloader.fetchFile(Downloader.java:68)
20:53:40  	at org.owasp.dependencycheck.data.update.RetireJSDataSource.initializeRetireJsRepo(RetireJSDataSource.java:149)
20:53:40  	... 7 common frames omitted
20:53:40  Caused by: java.io.FileNotFoundException: /usr/share/dependency-check/data/jsrepository.json (Permission denied)
20:53:40  	at java.base/java.io.FileOutputStream.open0(Native Method)
20:53:40  	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
20:53:40  	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
20:53:40  	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
20:53:40  	at org.owasp.dependencycheck.utils.Downloader.fetchFile(Downloader.java:86)
20:53:40  	... 9 common frames omitted
20:53:40  [WARN] Unable to update 1 or more Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.
20:53:40  [ERROR] Unable to continue dependency-check analysis.
20:53:40  [ERROR] One or more fatal errors occurred
20:53:40  [ERROR] Failed to initialize the RetireJS repo
20:53:40  [ERROR] No documents exist

**Comment by adrielldagasuan** [comment]
This might not be a bug with the docker image, but is more likely that your data directory doesn't have the correct permissions. It's showing that it can't access a path inside the docker container but only because it's a volume mount.

```
#!/bin/sh

OWASPDC_DIRECTORY=$HOME/OWASP-Dependency-Check
DATA_DIRECTORY="$OWASPDC_DIRECTORY/data"
REPORT_DIRECTORY="$OWASPDC_DIRECTORY/reports"

if [ ! -d "$DATA_DIRECTORY" ]; then
    echo "Initially creating persistent directories"
    mkdir -p "$DATA_DIRECTORY"
    chmod -R 777 "$DATA_DIRECTORY"

    mkdir -p "$REPORT_DIRECTORY"
    chmod -R 777 "$REPORT_DIRECTORY"
fi

# Make sure we are using the latest version
docker pull owasp/dependency-check

docker run --rm \
    --volume $(pwd):/src \
    --volume "$DATA_DIRECTORY":/usr/share/dependency-check/data \
    --volume "$REPORT_DIRECTORY":/report \
    owasp/dependency-check \
    --scan /src \
    --format "ALL" \
    --project "My OWASP Dependency Check Project" \
    --out /report
    # Use suppression like this: (/src == $pwd)
    # --suppression "/src/security/dependency-check-suppression.xml"```

**Comment by jeremylong** [comment]
@githubhs17 have you had a chance to double check the mount point permissions?  What command did you use to run the analysis using the docker image?

**Comment by AntoineGa** [comment]
i have faced the same issue and solved it by removing the previous jsrepository.json

**Comment by jeremylong** [comment]
A solution to this might be using an updated script per #1883.
