### ISSUE TITLE
how to install from zip/tar in Jenkins (v5.0.2)

### ISSUE THREAD

**Issue by javixeneize** [dependency-check/DependencyCheck#2198]
Hi

Im trying to make DC V5 work in Jenkins by using the Extract *.zip/*.tar.gz option in the global tool configuration.

Looks like it is installing the tool in the slave where im running dependency check, but i was expecting it to be installed in the main jenkins. Is there any option to install this in the main jenkins node?

Thanks

**Comment by stevespringett** [comment]
Jenkins will install tools on the node that's executing a job. To install on master, just ensure the master node is the one doing the work. Create a temp job if you have to and restrict access to only the master.

**Comment by javixeneize** [comment]
I ended up doing a shell script to store the file in a persistent volume and check if the file exists. It would be a good feature to have flexibility to configure the path of the tool, as it always try to execute it in the home folder, isnt it?

**Comment by stevespringett** [comment]
The path of the installation and the overall installation process is handled by Jenkins Infra. Install path can already be customized when doing so manually, but I do not believe the automated install has that option. If that is important to you, you'll need to create an enhancement request with the Jenkins core or Jenkins Infra team.
