### ISSUE TITLE
Gradle integration

### ISSUE THREAD

**Issue by mrniko** [dependency-check/DependencyCheck#220]
Please, publish this way of gradle integration in wiki. It helps to other developers:

``` ant
configurations {
    depCheck
}

dependencies {
    depCheck "org.owasp:dependency-check-ant:1.2.10"
}

task checkDeps << {
    ant.taskdef(name: 'checkDepsTask', 
                classname: 'org.owasp.dependencycheck.taskdefs.DependencyCheckTask', 
                classpath: configurations.depCheck.asPath)

    ant.checkDepsTask() {
               path {
                     pathelement(path: sourceSets.main.runtimeClasspath.asPath)
               }
    }
}
```

**Comment by jeremylong** [comment]
Thanks, I will include this in the documentation. However, I think the longer term goal will be to write a [Gradle plugin](http://gradle.org/docs/current/userguide/custom_plugins.html).

**Comment by jeremylong** [comment]
Documentation was added to the site; which will be released with the next version. However, a PR was submitted for a full fledged Gradle plugin that will be incorporated soon.
