### ISSUE TITLE
Question: Collect information through CLI from a plain textfile?

### ISSUE THREAD

**Issue by dagobertdebug** [dependency-check/DependencyCheck#2201]
Hi Fellows

My use case is to collect information from various sources (e.g. operating system, network equipment, etc.) and let it be analyzed through DependencyCheck.

Is it possible to let the CLI collect information from a plain textfile instead of .jar or others?

If yes, what format is required for such textfile? Or is there a workaround how to achieve this?

Many thanks and best regards,
Dago

**Comment by stevespringett** [comment]
There’s a scan agent class which you can use to supply dependency check evidence necessary for analysis. You’d likely have to write your own importer.

There’s also https://dependencytrack.org/

**Comment by dagobertdebug** [comment]
Thanks for sharing! 

Could you please help me with starting such an importer or point me in the right direction?

Greetings,
Dago
