### ISSUE TITLE
Enhancement: Ruby gem analysis

### ISSUE THREAD

**Issue by xpert98** [dependency-check/DependencyCheck#221]
Like jars, Ruby gems also require analysis to determine potential security issues and I don't know of any other products that offer that functionality.

**Comment by jtmelton** [comment]
Dawn (https://github.com/thesp0nge/dawnscanner) and brakeman (https://github.com/presidentbeef/brakeman) both offer this to some extent.

**Comment by jeremylong** [comment]
John,

Thanks!  There is also bundler-audit (
https://github.com/rubysec/bundler-audit) which is more focused
specifically on vulns in the dependent gems. I believe the others you
listed do a similar thing with regard to vulns in gems - but they also do
more.  Note - I do not work in the ruby world at all, so if someone else
could comment on this please do.

--Jeremy

**Comment by jeremylong** [comment]
As this is really covered by other projects in the Ruby community I do not believe dependency-check should add support for Ruby.
