### ISSUE TITLE
Depenedency Check HTML Report Summary and Suppressed Vulnerabilities section fails to display respective content

### ISSUE THREAD

**Issue by hastaf** [dependency-check/DependencyCheck#2213]
**Describe the bug**
Once the Dependency-Check HTML report is generated, the report fails to show a full list of vulnerabilities scanned while clicking on the link **Showing Vulnerable Dependencies (click to show all)**.
Secondly, When you click on the **suppress** button besides each vulnerability, it fails to click and create a dialogue box.

Using dependency checked version 5.2.1-release (CLI).

**Expected behavior**
Clicking the  **Showing Vulnerable Dependencies (click to show all)** and  **suppress** button should display respective content.

**Additional context**
A workaround for me was to save the HTML file and open it using the browser. Then clicking on  **Showing Vulnerable Dependencies (click to show all)** and  **suppress** button solved the issue.

**Comment by jeremylong** [comment]
Are you trying to view the file from Jenkins?  [Jenkins has a CSP](https://wiki.jenkins.io/display/JENKINS/Configuring+Content+Security+Policy) that disallows JavaScript.

**Comment by hastaf** [comment]
Yes I was viewing it from Jenkins. Your right, it was our Jenkins server blocking the loading of inline images and scripts for owasp dependency check reports. 
I will go ahead and close the ticket
