### ISSUE TITLE
Upgrading maven-dependency-check from 5.1.1 to 5.2.x give validation error on accessing Liquibase XSD files (accessExternalSchema property)

### ISSUE THREAD

**Issue by enachec** [dependency-check/DependencyCheck#2216]
Hello,

We are using Liquibase and OWASP dependency check plugin version 5.1.1 - JDK 8.

While upgrading the maven-dependency-check plugin to any 5.2.x version an error is thrown related to Liquibase changelog.xml files which refers to http (not https) external XSD.

`[ERROR] Failed to execute goal org.liquibase:liquibase-maven-plugin:3.5.3:updateSQL (generate-mysql-script-delta) on project XXX: Error setting up or running Liquibase: Error parsing line 6 column 138 of src/main/resources/db/changelog-4.1.2-delta.xml: schema_reference: Failed to read schema document 'dbchangelog-3.4.xsd', because 'http' access is not allowed due to restriction set by the accessExternalSchema property.  -> [Help 1]`

Adding `-Djavax.xml.accessExternalSchema=all` to command line doesn't help at all.

From the actual behavior it seems like starting with 5.2.x version the plugin overwrites or enforce javax.xml.accessExternalSchema=https and it doesn't restore it back once the parsing is finished. 

dependency-check is executed first by the Maven reactor and then Liquibase. Unfortunately on Liquibase side there is no solution yet.

**Comment by jeremylong** [comment]
Sorry for the delay in fixing this.  I'm not sure I'm entirely happy with the fix I implemented - but you when 5.2.3 is released you should be able to  set `-Djavax.xml.accessExternalSchema=all`.  I'm hoping the release will be this weekend.

**Comment by enachec** [comment]
Hello,

No worries, once released I will make some tests on our side and confirm the result.

Thanks

**Comment by rpsandiford** [comment]
While this works - it does require the javax.xml.accessExternalSchema setting to be explicitly set before things will work.  Prior to 5.2.0, no such explicit setting was required.

**Comment by jeremylong** [comment]
fair enough - I just added one additional cleanup step that will be included in the next release.

**Comment by rpsandiford** [comment]
Thanks!  That looks good from a code review point of view!
