### ISSUE TITLE
CVE's missing for Node libraries

### ISSUE THREAD

**Issue by dmhatre08** [dependency-check/DependencyCheck#2218]
We are using OWASP dependency check version 1.4.5, which is finding CVE's from NVD source for node libraries without internet access.

We are planning to upgrade to latest version, but latest version requires the internet access to reach the NPM source if we need to use Node Audit Analyzer.

Is there any way to use the latest version of dependency checker offline and still get the CVE's related to node libraries through NVD source?

**Comment by jeremylong** [comment]
No - at the moment the node analysis is a wrapper around the APIs used by `npm audit`.

**Comment by dmhatre08** [comment]
ok. Thank you.
