### ISSUE TITLE
 unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by niania0** [dependency-check/DependencyCheck#2224]
./dependency-check.sh -update
[INFO] Checking for updates
[INFO] starting getUpdatesNeeded() ...
[ERROR] IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2003.xml.gz: sun.security.validator.ValidatorException: PKIX path building failed:  find valid certification path to requested target
[ERROR] IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2018.xml.gz: sun.security.validator.ValidatorException: PKIX path building failed:  find valid certification path to requested target
[ERROR] IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2012.xml.gz: sun.security.validator.ValidatorException: PKIX path building failed:  find valid certification path to requested target
[ERROR] IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2011.xml.gz: sun.security.validator.ValidatorException: PKIX path building failed:  find valid certification path to requested target
[ERROR] IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2002.xml.gz: sun.security.validator.ValidatorException: PKIX path building failed:  find valid certification path to requested target
[ERROR] IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-Modified.xml.gz: sun.security.validator.ValidatorException: PKIX path building faile to find valid certification path to requested target
[ERROR] IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2009.xml.gz: sun.security.validator.ValidatorException: PKIX path building failed:  find valid certification path to requested target
[ERROR] IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2013.xml.gz: sun.security.validator.ValidatorException: PKIX path building failed:  find valid certification path to requested target
[ERROR] IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2007.xml.gz: sun.security.validator.ValidatorException: PKIX path building failed:  find valid certification path to requested target
[ERROR] IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2015.xml.gz: sun.security.validator.ValidatorException: PKIX path building failed:  find valid certification path to requested target
[ERROR] IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2014.xml.gz: sun.security.validator.ValidatorException: PKIX path building failed:  find valid certification path to requested target
[ERROR] IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2005.xml.gz: sun.security.validator.ValidatorException: PKIX path building failed:  find valid certification path to requested target
[WARN] Unable to download the NVD CVE data; the results may not include the most recent CPE/CVEs from the NVD.
[INFO] If you are behind a proxy you may need to configure dependency-check to use the proxy.
[ERROR] Unable to download the NVD CVE data.

**Comment by niania0** [comment]
due to this question, I can download the "nvdcve" data. How can i import "nvdcve" ? such as useing some command,

**Comment by FrankS77** [comment]
Same exception on my side: Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by ghost** [comment]
This is a duplicate of #2222 and can be closed.

**Comment by jeremylong** [comment]
Closing this issue as it is a duplicate of #2222.  A work around has been documented in #2222.
