### ISSUE TITLE
Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-modified.meta

### ISSUE THREAD

**Issue by proo4509** [dependency-check/DependencyCheck#2225]
**Describe the bug**

[ERROR] Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-modified.meta

** Version of dependency-check used **
5.2.2. (tried 5.2.1. as well)

** Log file **
no log was made

**To Reproduce**
1. dependency-check.bat
4. [ERROR] Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-modified.meta

**Expected behavior**
1. run dependency-check.bat without errors

**Additional context**
no

**Comment by ghost** [comment]
duplicate of #2222, please close
