### ISSUE TITLE
AutoconfAnalyzer setting key is not the right one

### ISSUE THREAD

**Issue by lrnthbrt** [dependency-check/DependencyCheck#2236]
**Describe the bug**
To enable AutoconfAnalyzer from java properties, one need to use "-Danalyzer.python.distribution.enabled=true" instead of "-Danalyzer.autoconf.enabled=true" (which also enable the Python Distribution Analyzer, obviously).

**Version of dependency-check used**
The problem occurs using version 5.2.2 of the the cli 

**Log file**
**To Reproduce**
**Expected behavior**
**Additional context**

Patch is probably self explanatory:
```patch
diff --git a/core/src/main/java/org/owasp/dependencycheck/analyzer/AutoconfAnalyzer.java b/core/src/main/java/org/owasp/dependencycheck/analyzer/AutoconfAnalyzer.java
index 1f85effc3..303d775e5 100644
--- a/core/src/main/java/org/owasp/dependencycheck/analyzer/AutoconfAnalyzer.java
+++ b/core/src/main/java/org/owasp/dependencycheck/analyzer/AutoconfAnalyzer.java
@@ -150,7 +150,7 @@ public class AutoconfAnalyzer extends AbstractFileTypeAnalyzer {
      */
     @Override
     protected String getAnalyzerEnabledSettingKey() {
-        return Settings.KEYS.ANALYZER_PYTHON_DISTRIBUTION_ENABLED;
+        return Settings.KEYS.ANALYZER_AUTOCONF_ENABLED;
     }
 
     @Override
```

If the above patch is not sufficient, I can do a pull request with this patch.

**Comment by jeremylong** [comment]
Thank you for identifying this bug. The fix will be included in the next release.
