### ISSUE TITLE
 Dependency check fail with below ERROR in gradle 4.0

### ISSUE THREAD

**Issue by abinstephen** [dependency-check/DependencyCheck#2237]
Dependency check fail with below ERROR in gradle 4.0
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
      //mavenCentral()
    }
  }
  dependencies {
    classpath "org.owasp:dependency-check-gradle:3.1.2"
    classpath "org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:2.7.1"
  }
}

allprojects {
  version = '4.0'

  repositories {
    mavenCentral()
  }
  apply plugin: "org.owasp.dependencycheck"

  dependencyCheck {
    autoUpdate=false
    failOnError=false
    format='ALL'
   
  }  

}
}

2:32:58.359 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Task worker,5,main]] finished, busy: 26.509 secs, idle: 0.001 secs
12:32:58.359 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Task worker Thread 6,5,main]] finished, busy: 0.0 secs, idle: 26.509 secs
12:32:58.360 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Task worker Thread 4,5,main]] finished, busy: 0.0 secs, idle: 26.509 secs
12:32:58.360 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Task worker Thread 3,5,main]] finished, busy: 0.0 secs, idle: 26.51 secs
12:32:58.360 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Daemon worker,5,main]] finished, busy: 0.0 secs, idle: 26.508 secs
12:32:58.359 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Task worker Thread 2,5,main]] finished, busy: 0.0 secs, idle: 26.51 secs
12:32:58.360 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Task worker Thread 7,5,main]] finished, busy: 0.0 secs, idle: 26.507 secs
12:32:58.360 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Task worker Thread 5,5,main]] finished, busy: 0.0 secs, idle: 26.509 secs
12:32:58.361 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Completing Build operation 'Run tasks'
12:32:58.370 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
12:32:58.370 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
12:32:58.370 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
12:32:58.370 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
12:32:58.370 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':dependencyCheckAggregate'.
12:32:58.371 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Analysis failed.
12:32:58.371 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
12:32:58.371 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
12:32:58.371 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Run with --stacktrace option to get the stack trace. 
12:32:58.371 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] 
12:32:58.372 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED in 28s
12:32:58.372 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] 1 actionable task: 1 executed
12:32:58.372 [DEBUG] [org.gradle.internal.work.DefaultWorkerLeaseService] Worker lease root.1 completed (0 worker(s) in use)
12:32:58.373 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Daemon worker: released lock on root.1
12:32:58.373 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Completing Build operation 'Run build'
12:32:58.375 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Releasing file lock for task history cache (/jenkins/workspace/Scoring_Engine_feature_CI-QSGHA77EFTPHFSSGMX33TM54QOATTEIJXGMH6IOMQDGHVNDNFVWQ/.gradle/4.0/taskHistory)
12:32:58.375 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on task history cache (/jenkins/workspace/Scoring_Engine_feature_CI-QSGHA77EFTPHFSSGMX33TM54QOATTEIJXGMH6IOMQDGHVNDNFVWQ/.gradle/4.0/taskHistory).
12:32:58.376 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory] Resolution result cache closed. Cache reads: 0, disk reads: 0 (avg: 0.0 secs, total: 0.0 secs)
12:32:58.376 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory] Resolution result cache closed. Cache reads: 0, disk reads: 26 (avg: 0.0 secs, total: 0.021 secs)
12:32:58.377 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.ResolutionResultsStoreFactory] Deleted 4 resolution results binary files in 0.002 secs
12:32:58.377 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Cache Plugin Resolution Cache (/jenkins/.gradle/caches/4.0/plugin-resolution) was closed 0 times.
12:32:58.377 [DEBUG] [org.gradle.workers.internal.WorkerDaemonFactory] Stopping 0 worker daemon(s).
12:32:58.377 [INFO] [org.gradle.workers.internal.WorkerDaemonFactory] Stopped 0 worker daemon(s).
12:32:58.379 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Releasing file lock for Artifact transforms cache (/jenkins/.gradle/caches/transforms-1)
12:32:58.379 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on Artifact transforms cache (/jenkins/.gradle/caches/transforms-1).
12:32:58.379 [DEBUG] [org.gradle.deployment.internal.DefaultDeploymentRegistry] Stopping 0 deployment handles
12:32:58.379 [DEBUG] [org.gradle.deployment.internal.DefaultDeploymentRegistry] Stopped deployment handles
12:32:58.379 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Cache Generated Gradle JARs cache (/jenkins/.gradle/caches/4.0/generated-gradle-jars) was closed 0 times.
12:32:58.380 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Releasing file lock for file hash cache (/jenkins/workspace/Scoring_Engine_feature_CI-QSGHA77EFTPHFSSGMX33TM54QOATTEIJXGMH6IOMQDGHVNDNFVWQ/.gradle/4.0/fileHashes)
12:32:58.380 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on file hash cache (/jenkins/workspace/Scoring_Engine_feature_CI-QSGHA77EFTPHFSSGMX33TM54QOATTEIJXGMH6IOMQDGHVNDNFVWQ/.gradle/4.0/fileHashes).
12:32:58.380 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Releasing file lock for artifact cache (/jenkins/.gradle/caches/modules-2)
12:32:58.380 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache artifact-at-repository.bin (/jenkins/.gradle/caches/modules-2/metadata-2.23/artifact-at-repository.bin)
12:32:58.380 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache module-metadata.bin (/jenkins/.gradle/caches/modules-2/metadata-2.23/module-metadata.bin)
12:32:58.381 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on artifact cache (/jenkins/.gradle/caches/modules-2).
12:32:58.381 [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] The daemon has finished executing the build.
12:32:58.482 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClient] Received result Failure[value=org.gradle.initialization.ReportedException: org.gradle.internal.exceptions.LocationAwareException: Execution failed for task ':dependencyCheckAggregate'.] from daemon DaemonInfo{pid=31473, address=[dede3bcd-2b88-43d0-8722-8dc97e4164ce port:40726, addresses:[/127.0.0.1]], state=Idle, lastBusy=1570206645841, context=DefaultDaemonContext[uid=ec0bb70f-d109-4b0f-bc44-4748d7a74d36,javaHome=/usr/java/jdk1.8.0_201-amd64,daemonRegistryDir=/jenkins/.gradle/daemon,pid=31473,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]} (build should be done).
12:32:58.482 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 1: dispatching class org.gradle.launcher.daemon.protocol.Finished
12:32:58.483 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 1: connection stop

**Comment by jeremylong** [comment]
org.owasp:dependency-check-gradle:3.1.2 is no longer supported.  Please try version 5.2.2.

In fact, all version prior to 5.0.0 will stop working Oct 9th, 2019 as the NVD will no longer maintain the XML data feed used by earlier version.

**Comment by jeremylong** [comment]
I also noticed that you havec `autoUpdate=false` - if you are not providing an existing database ODC will fail.

**Comment by abinstephen** [comment]
Hi Jeremylong/Dependencycheck

H2 database will automatically start right

Do we need to anything for that.

Any config changes, I am new to this so can you please provide more details
on that

Thank
You

**Comment by jeremylong** [comment]
You need to run with autoupdate=true at least once with access to the Internet.  You can do this with `--updateonly` if you want. Then you can go to an offline mode. The H2 database will get generated automatically.  Then you need to run the update at least once every 7 days to keep the database current.

**Comment by abinstephen** [comment]
That helps thank you Jeremylong
