### ISSUE TITLE
Add nodesecurity.io to list of related projects

### ISSUE THREAD

**Issue by dwvisser** [dependency-check/DependencyCheck#224]
From dependency-check list:

> Thanks, I hadn't seen that project. I'll add it to my list of "related projects" that I am building. (see
> https://github.com/jeremylong/DependencyCheck/blob/master/src/site/markdown/related.md).
> --Jeremy
> 
> On Tue, Apr 28, 2015 at 11:20 AM, Visser, Dale dvisser@ida.org wrote:
> It looks like https://nodesecurity.io/ is dealing with the problem of vulnerable dependencies in the 
> node.js/npm space, and doing it quite nicely. They provide both the database and the tooling. 
> Browsing a few of their advisories, I see that they give a “CVE status” as well.

**Comment by jeremylong** [comment]
done
