### ISSUE TITLE
Central Analyzer is disabled in maven plugin

### ISSUE THREAD

**Issue by MichaelVetter** [dependency-check/DependencyCheck#2241]
The documentation says that the Central Analyzer is enabled in the default configuration:
https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html
But when I run the maven plugin without a special configuration the Central Analyzer is disabled. The problem occurs using version 5.2.2 of the maven plugin.

Here is an extract of the debug output:
...
analyzer.central.enabled='true'
[DEBUG] Properties updated via merge:
analyzer.central.enabled='false'
[DEBUG] Central Analyzer has been disabled

When I set the property centralAnalyzerEnabled to true the Central Analyzer works.

Is the documentation not up to date or is there an other problem?

**Comment by jeremylong** [comment]
The documentation has been updated. By default everything that you would gain from using the Central Analyzer is already available in the build - as such, the Central Analyzer is disabled in the Maven and Gradle plugin.

**Comment by MichaelVetter** [comment]
Thank you, but as described in #2242 the Central Analyzer makes a difference in our use case.
