### ISSUE TITLE
False Positive on MimeTypesMap

### ISSUE THREAD

**Issue by mdesousa** [dependency-check/DependencyCheck#2249]
False positive on library https://www.nuget.org/packages/MimeTypesMap/
Reported as ```cpe:2.3:a:mime_project:mime:1.0.4:*:*:*:*:*:*:*  (Confidence:High)```

This was with DependencyCheck 5.2.2

**Comment by jeremylong** [comment]
I just checked this with 5.3.1-snapshot and it appears to be fixed.
