### ISSUE TITLE
Use Stupid Table Plugin for sortable table columns in report

### ISSUE THREAD

**Issue by dwvisser** [dependency-check/DependencyCheck#225]
From dependency-check list:

> The Vulnerability report already uses JQuery [Stupid Table Plugin](https://github.com/joequery/Stupid-Table-Plugin)
> (see https://github.com/jeremylong/DependencyCheck/blob/master/dependency-check-core/src/main/resources/templates/VulnerabilityReport.vsl)
> When I added this to the vulnerability report there was no comparable table in the main 
> dependency-check report. However, since that was added we should probably add in the Stupid
> Table Plugin to the primary report.

**Comment by jeremylong** [comment]
duplicate of #222
