### ISSUE TITLE
False Positive on Cake.SqlServer

### ISSUE THREAD

**Issue by mdesousa** [dependency-check/DependencyCheck#2250]
False positive on https://www.nuget.org/packages/Cake.SqlServer/
Reported as ```cpe:2.3:a:sqlserver_project:sqlserver:2.0.1:*:*:*:*:*:*:*  (Confidence:High)```

This was with DependencyCheck 5.2.2

**Comment by jeremylong** [comment]
I just tested this with 5.3.1-snapshot and this appears to be resolved.
