### ISSUE TITLE
Failure of dependency scan via OWASP DC v 5.2.2. with proxy server

### ISSUE THREAD

**Issue by a6k8s4** [dependency-check/DependencyCheck#2254]
Hi team,

Could you please check the snapshot attached and let us know the reason for failure of dependency scan via OWASP DC v 5.2.2.

We have set the proxy server properly in the Linux box and are able to wget the nvd website.

![C329D83D-AAF3-4C64-BCEC-20C995AD566D](https://user-images.githubusercontent.com/17820968/66694823-7c5a6980-ecd5-11e9-8713-a846ac604e21.png)

**Comment by mprins** [comment]
the reason for failing analysys is: the tool cannot download the vulnerability database.
probably you have not setup proxy in the tool or for the user running the tool or the proxy is doing something wrong, but you really have not provided enough information. At least show us the env for the user and the python script.

**Comment by a6k8s4** [comment]
The content of the python file is as follows: 

```
import os
import time
import argparse
from datetime import datetime
os.chdir("/opt/Jenkins/dependency-check-5.2.2-release/dependency-check/bin")
date_time = datetime.now().strftime("%m%d%Y%H%M%S")
class DCT:

    def __init__(self,inpath,outpath,project):

        self.inpath = inpath
        self.outpath = outpath
        self.project = project

    def dependencyRunCommand(self):

        try:
            cmd = './dependency-check.sh --project "'+ self.project +'" --enableExperimental \
                  --enableRetired --disableAssembly --scan "'+ self.inpath +'" --out "'+ self.outpath +'" \
                  --format "ALL" --proxyserver "xxxxx" --proxyport "xxx" --proxyuser "\
                  xxxxx" --proxypass "xxxx"'
            os.system(cmd)
            raise Exception

        except Exception as e:
            print(e) 
```



Even I tried running the dependency-check.sh alone in the terminal as follows:

./dependency-check.sh --project "xxxx" --enableExperimental --enableRetired --scan "/opt/Jenkins/workspace/xxxxx" --out "/opt/Jenkins/workspace/xxxxx/xxx" --format "ALL" --proxyserver "xxxx" --proxyport "xxxx" --proxyuser "xxxx" --proxypass "xxxx" 

Both of these gave the same out come as depicted in the screen shot provided earlier.

**Comment by jeremylong** [comment]
This is a good article for resolving this type of connectivity error (yes, this applies even though we aren't using an 'Atlassian' product): https://confluence.atlassian.com/kb/unable-to-connect-to-ssl-services-due-to-pkix-path-building-failed-error-779355358.html

**Comment by a6k8s4** [comment]
Yes we have done the needfull . But still getting same error.

![Untitled](https://user-images.githubusercontent.com/17820968/66756177-10375b80-eeb7-11e9-869e-6c21af0b0418.png)

**Comment by MichaelVetter** [comment]
Maybe this debug option helps analysing the cause of the problem:
export JAVA_OPTS=-Djavax.net.debug=ssl

**Comment by aikebah** [comment]
@a6k8s4 you only show wget (which uses Linux CA truststores) and the dependency-check call without custom trust-stores, which uses Java CA truststores). Did you actually try running the SSLPoke class until that managed to successfuly run as described in the Atlassian article that jeremylong referenced?

Gut feel: your proxy acts as a MITM to allow scanning traffic for suspicious (virus, malware) traffic and re-encrypts traffic with an untrusted certificate (issued automatically by a internal CA of the proxy) for which you didn't add the CA root cert to the CA trust store of the JVM that runs dependencycheck.

**Comment by amitkmohapatra** [comment]
@a6k8s4 , the root cause provided by @aikebah is true. You seem to be under an organisation proxy server. Get in touch with you proxy team and try importing the updated certificates using the following commands. hope it will resolve your issue.

$JAVA_HOME/bin/keytool -import -alias Cert1 -keystore $JAVA_HOME/jre/lib/security/cacerts -file <Path_of_certificate_file>

**Comment by a6k8s4** [comment]
Thank you all for the explanations and it worked out for us.
