### ISSUE TITLE
Upgrade to version5

### ISSUE THREAD

**Issue by mjdavies** [dependency-check/DependencyCheck#2258]
Hi there

Could someone point me at some instructions on how to upgrade from version4 to version5?

I've been following the old instructions to install the jenkins plugin, then used a separate jenkins job to populate a database to use.

Then I've been doing the following, or an approximation of it in jenkinsfiles in my multi branch pipeline.

```
`stage ("OWASP Vulnerability Scan") {
            steps {
                dependencyCheckAnalyzer datadir: '/path/to/owasp/updates',
                hintsFile: '',
                includeCsvReports: false,
                includeVulnReports: false,
                includeHtmlReports: false,
                includeJsonReports: false,
                isAutoupdateDisabled: true,
                outdir: '',
                scanpath: '',
                skipOnScmChange: false,
                skipOnUpstreamChange: false,
                suppressionFile: '',
                zipExtensions: ''
                dependencyCheckPublisher canComputeNew: false,
                failedTotalHigh: "10",
                failedTotalNormal: "100",
                failedTotalLow: "100"
                archiveArtifacts allowEmptyArchive: true,
                artifacts: '**/dependency-check-report.xml',
                onlyIfSuccessful: true
            }
        }`
```

I've found this

https://jenkins.io/doc/pipeline/steps/dependency-check-jenkins-plugin/

and this

https://wiki.jenkins.io/display/JENKINS/OWASP+Dependency-Check+Plugin

But I'm really struggling on how to proceed now.

Happily write up a blog post once I've worked it out.

**Comment by stevespringett** [comment]
https://github.com/jenkinsci/dependency-check-plugin/wiki/v5-Migration

**Comment by mjdavies** [comment]
Thanks Steve
