### ISSUE TITLE
Custom Notes and Severity

### ISSUE THREAD

**Issue by jeremylong** [dependency-check/DependencyCheck#226]
Add the ability for an organization to customize the notes and severity.

**Comment by harrybstoner** [comment]
Are you talking about suppression notes? That is what I would like - a "reason" element where we could explain why the issue was suppressed. For now I have manually added text inside of the notes element. Common reasons: not used, not applicable, fixed.

**Comment by jeremylong** [comment]
No, this was note meant for the suppression notes - but that is a good idea. The suppression currently has a notes section that could be added to the report.

**Comment by jeremylong** [comment]
Closing this issue in favor of #651 as I do not plan on implementing the custom severity.
