### ISSUE TITLE
False Positive on several Datomic libraries

### ISSUE THREAD

**Issue by jkemperman** [dependency-check/DependencyCheck#2261]
False positives on several supporting datomic libraries, all reported as different versions of the same incorrect core datomic library.

|Package|Reported as|
|-|-|
|[pkg:maven/com.datomic/client@0.8.69](https://ossindex.sonatype.org/component/pkg:maven/com.datomic/client@0.8.69)|[`cpe:2.3:a:cognitect:datomic:0.8.69:*:*:*:*:*:*:*`](https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Acognitect&cpe_product=cpe%3A%2F%3Acognitect%3Adatomic&cpe_version=cpe%3A%2F%3Acognitect%3Adatomic%3A0.8.69)|
|[pkg:maven/com.datomic/client-api@0.8.13](https://ossindex.sonatype.org/component/pkg:maven/com.datomic/client-api@0.8.13)|[`cpe:2.3:a:cognitect:datomic:0.8.13:*:*:*:*:*:*:* `](https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Acognitect&cpe_product=cpe%3A%2F%3Acognitect%3Adatomic&cpe_version=cpe%3A%2F%3Acognitect%3Adatomic%3A0.8.13)|
|[pkg:maven/com.datomic/query-support@0.8.16](https://ossindex.sonatype.org/component/pkg:maven/com.datomic/query-support@0.8.16)|[`cpe:2.3:a:cognitect:datomic:0.8.16:*:*:*:*:*:*:* `](https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Acognitect&cpe_product=cpe%3A%2F%3Acognitect%3Adatomic&cpe_version=cpe%3A%2F%3Acognitect%3Adatomic%3A0.8.16)|
|[pkg:maven/com.datomic/client-impl-shared@0.8.49](https://ossindex.sonatype.org/component/pkg:maven/com.datomic/client-impl-shared@0.8.49)|[`cpe:2.3:a:cognitect:datomic:0.8.49:*:*:*:*:*:*:* `](https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Acognitect&cpe_product=cpe%3A%2F%3Acognitect%3Adatomic&cpe_version=cpe%3A%2F%3Acognitect%3Adatomic%3A0.8.49)|

Ran with dependency check 5.2.2.

**Comment by aikebah** [comment]
@jeremylong This is an issue similar to #2191 - a product that uses multiple different versions for its components. My gut feel would be that we need some new logic in DC that can in some way determine that a library belongs to a certain package of multiple-versions modules and determine the appropriate release bundle version of it for comparison with CPEs.

**Comment by jeremylong** [comment]
For dependencies with a GAV - I know we could consider everything with the same group and then try to perform some level analysis to try and figure out what the "core" framework is. Currently, the `DependencyBundlingAnalyzer` tries to do this (after CPE identification).
