### ISSUE TITLE
how to point to xml feed in <cveUrlModified></cveUrlModified>

### ISSUE THREAD

**Issue by abisekwins29** [dependency-check/DependencyCheck#2266]
Hi Team,

How can we use company XML CVE feed for owasp dependency check.
We are behind proxy and cant go to  https://nvd.nist.gov/.

I read in documentation to use below config properties for custom CVE data feed
                    <cveUrlModified></cveUrlModified>
                    <cveUrlBase></cveUrlBase> 

but in all examples saw the json feed files URL only.
As in our organisation we have XML feed (only *.xml.gz NO *.meta) . I tried XML feed file URL but not working.

        <plugin>
              <groupId>org.owasp</groupId>
              <artifactId>dependency-check-maven</artifactId>
              <version>5.2.1</version>
              <configuration>
                    <cveUrlModified>/localrepo/nvdcve-1.1-modified.xml.gz</cveUrlModified>
                    <cveUrlBase>/localrepo/nvdcve-1.1-%d.xml.gz</cveUrlBase>
                </configuration>
              <executions>
                  <execution>
                      <goals>
                          <goal>check</goal>
                      </goals>
                  </execution>
              </executions>
            </plugin>

Please let me know how this can be achieved.

Thanks in advance.

**Comment by aikebah** [comment]
XML Feeds of NIST have been removed, so you should be using JSON feeds. See [NIST announcement](https://nvd.nist.gov/general/news/XML-Vulnerability-Feed-Retirement) as the XML-feeds your company has locally only contain historical CVEs
