### ISSUE TITLE
ConnectionPool configuration

### ISSUE THREAD

**Issue by kaimago** [dependency-check/DependencyCheck#227]
Hi, 

all our maven-builds use a parent-pom where we configured a central dataDirectory for the DependencyCheck. In this way not every job needs to update the nvd-data and we can improve the performance of the maven-build.

Because we have a lot of builds, I think we running sometimes in a connectionpool problem.

In the log I just see this : 

org.owasp.dependencycheck.data.nvdcve.DatabaseException: Unable to connect to the database
at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.initialize(ConnectionFactory.java:154)

A configuration possibility for setting the MaxConnections and a LoginTimeout would be great.
Is there a way to solve this problem ?

Best Regards 
Kai

**Comment by jeremylong** [comment]
I am currently writing documentation to cover this type of deployment. You'll notice in the configuration settings that you can specify a different connection string (see the [configuration documentation](https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html)). As such, you could run H2 (the default database engine) in [server mode](http://www.h2database.com/html/features.html#connection_modes).

There is an even more advanced option to actually use a completely different database engine by specifying the database driver name and if needed the driver path. However, you may want to wait on the documentation to be complete before doing this.

--Jeremy

**Comment by jeremylong** [comment]
The documentation has been added to the repo [here](https://github.com/jeremylong/DependencyCheck/blob/master/src/site/markdown/data/database.md) and it will be added to the standard site documentation with the next release.
