### ISSUE TITLE
Documentation of CLI arguments incomplete

### ISSUE THREAD

**Issue by aikebah** [dependency-check/DependencyCheck#2270]
**Describe the bug**
As indicated in [a comment](https://github.com/jeremylong/DependencyCheck/issues/2244#issuecomment-543046506) in issue #2244 comments at least the --hints option of the CLI is missing in the documentation.

** Version of dependency-check used **
The problem occurs using documentation for version 5.2.2 of the the cli

**Expected behavior**
Documentation is in sync with the actual command-line arguments.

**Comment by aikebah** [comment]
@jeremylong Docs are still incomplete and there's a discrepancy between CliParser and the documentation regarding which options are standard (--help) and which are advanced (--advancedHelp)
Also spotted some documented arguments which are not yet implemented.

I'll send a PR for the various omissions soonish. Would like to hear your feedback on the differences on standard/advanced between docs and implementation, I'll leave them as is for now in the PR:

An overview of the omissions and differences that I found:

| CLI-Option | Documentation | CliParser |
| --- | --- | --- |
| \-\-hints | part of advanced options | part of standard options |
| \-\-propertyFile | part of advanced options | part of standard options |
| \-\- nexusUser | **not documented** | part of advanced options |
| \-\- nexusPass | **not documented** | part of advanced options |
| \-\-bundleAuditWorkingDirectory | **not documented** | part of advanced options |
| \-c | **Shortcut for \-\-connectiontimeout not present** | Shortcut for \-\-connectiontimeout present |
| \-\-ossIndexUsername | part of advanced options | **not implemented** |
| \-\-ossIndexPassword | part of advanced options | **not implemented** |
| \-\-junitFailOnCVSS | *\<score\>* parameter present | **\<score\> parameter absent in help message** |
| \-\-prettyprint | Properly documented | **help message is the message of failOnCVSS** |

**Comment by jeremylong** [comment]
Thanks again for the review and PR!  I moved the properties and hints to the advanced help section.
