### ISSUE TITLE
Setting a --registry variable for node scans

### ISSUE THREAD

**Issue by mjdavies** [dependency-check/DependencyCheck#2275]
Hi there

Is it currently possible to pass a --registry value of https://registry.npmjs.org/ into the dependency check cli, or a .properties file, in order to scan node projects with the dependency check cli?

Our project uses our internal nexus cache, so that's setup in a .npmrc file, but the internal nexus cache is unable to respond to npm audit requests.

https://issues.sonatype.org/browse/NEXUS-16954

**Comment by jeremylong** [comment]
Not at this time. However, the analyzer does not use the `npm audit` command - instead ODC goes directly to https://registry.npmjs.org.

**Comment by mjdavies** [comment]
Ahh, thanks Jeremy.

I thought I'd read somewhere that the node analyser is a wrapper around npm audit?

**Comment by jeremylong** [comment]
It is a wrapper around the npm audit API.
