### ISSUE TITLE
Update Documentation: <ossindexAnalyzerEnabled>false</ossindexAnalyzerEnabled>

### ISSUE THREAD

**Issue by abisekwins29** [dependency-check/DependencyCheck#2278]
In our organisation, we cant connect to outside while doing dependency check.  without \<ossindexAnalyzerEnabled\>false\</ossindexAnalyzerEnabled\>, at the time of scan it tries to connect to ossindex.sonatype.org. 
But when we disabled \<ossindexAnalyzerEnabled\>false\</ossindexAnalyzerEnabled\>, it worked fine. 
We could not get much documentation to read except https://jeremylong.github.io/DependencyCheck/data/index.html  which says "OWASP dependency-check includes support to consult the Sonatype OSS Index to enrich the report with supplemental vulnerability information."

Does having \<ossindexAnalyzerEnabled\>false\</ossindexAnalyzerEnabled\> will not impact vulnerability scan in any way?

Here is plugin config in pom:
              \<groupId\>org.owasp\</groupId\>
              \<artifactId\>dependency-check-maven\</artifactId\>
              \<version\>5.2.1\</version\>
              \<configuration\>
                  \<cveUrlModified\>${owasp.cveUrlModified}\</cveUrlModified\>
                  \<cveUrlBase\>${owasp.cveUrlBase}\</cveUrlBase\>
                  \<retireJsUrl\>${owasp.retireJsUrl}\</retireJsUrl\>
                  \<ossindexAnalyzerEnabled\>false\</ossindexAnalyzerEnabled\>
                  \<suppressionFile\>${owasp.suppressionFile}\</suppressionFile\>
           \</configuration\>

**Comment by aikebah** [comment]
Without the OSS Index Analyzer you will miss the following:
- No reporting of vulnerabilities that are registered in Sonatype OSS Index, but not (yet) registered or classified in NIST NVD
- Potentially fewer references when CVEs are also registered/classified in NIST NVD, when Sonatype OSS Index has more references

See also [OSSIndexAnalyzer's enrich method](https://github.com/jeremylong/DependencyCheck/blob/55c43710df587cbf2d15364a5fcc5a9aa71d8127/core/src/main/java/org/owasp/dependencycheck/analyzer/OssIndexAnalyzer.java#L230)

**Comment by abisekwins29** [comment]
Thans for the details.
What are the suggested way in case of scenario where connecting outside is not allowed at the time of scan?

Is there any way of having kind of feed on own premises like cve json feed from NIST NVD?

**Comment by jeremylong** [comment]
Unfortunately no - if you are truly running ODC without internet connectivity you will have to disable the OSS Index Analyzer and the Node Audit Analyzer.  I'll update the documentation on this.
