### ISSUE TITLE
Database error while updating CVE

### ISSUE THREAD

**Issue by phoenixadb** [dependency-check/DependencyCheck#2279]
**Describe the bug**
Error while updating CVE with DependencyCheck when using a MariaDB database on Debian.

** Version of dependency-check used **
The problem occurs using version 5.2.2 of the cli.

** Log file **
fatal: []: FAILED! => {"changed": true, "cmd": ["$HOME/dependency-check_5.2.2/bin/dependency-check.sh", "--dbDriverName", "org.mariadb.jdbc.Driver", "--connectionString", "jdbc:mariadb://localhost/dependencycheck_5_2_2", "--dbUser", "**********", "--dbPassword", "********", "--project", "DependencyCheckTest", "--format", "ALL", "--enableExperimental", "--scan", "$HOME/DependencyCheckTest/**", "--dbDriverPath", "/usr/share/java/mariadb-java-client-2.4.1.jar"], "delta": "0:28:57.770031", "end": "2019-10-22 14:47:07.344132", "msg": "non-zero return code", "rc": 243, "start": "2019-10-22 14:18:09.574101", "stderr": "", "stderr_lines": [], "stdout": "[INFO] Checking for updates\n[INFO] NVD CVE requires several updates; this could take a couple of minutes.\n[INFO] Download Started for NVD CVE - 2002\n[INFO] Download Started for NVD CVE - 2003\n[INFO] Download Complete for NVD CVE - 2003  (2633 ms)\n[INFO] Download Started for NVD CVE - 2004\n[INFO] Processing Started for NVD CVE - 2003\n[INFO] Download Complete for NVD CVE - 2002  (3510 ms)\n[INFO] Download Started for NVD CVE - 2005\n[INFO] Download Complete for NVD CVE - 2004  (2322 ms)\n[INFO] Download Started for NVD CVE - 2006\n[INFO] Download Complete for NVD CVE - 2005  (4023 ms)\n[INFO] Download Started for NVD CVE - 2007\n[INFO] Download Complete for NVD CVE - 2006  (4636 ms)\n[INFO] Download Started for NVD CVE - 2008\n[INFO] Download Complete for NVD CVE - 2007  (7970 ms)\n[INFO] Download Started for NVD CVE - 2009\n[INFO] Processing Complete for NVD CVE - 2003  (15700 ms)\n[INFO] Processing Started for NVD CVE - 2002\n[INFO] Download Complete for NVD CVE - 2008  (5121 ms)\n[INFO] Download Started for NVD CVE - 2010\n[INFO] Download Complete for NVD CVE - 2009  (9708 ms)\n[INFO] Download Started for NVD CVE - 2011\n[INFO] Download Complete for NVD CVE - 2010  (13189 ms)\n[INFO] Download Started for NVD CVE - 2012\n[INFO] Download Complete for NVD CVE - 2012  (9913 ms)\n[INFO] Download Started for NVD CVE - 2013\n[INFO] Download Complete for NVD CVE - 2011  (21725 ms)\n[INFO] Download Started for NVD CVE - 2014\n[INFO] Download Complete for NVD CVE - 2013  (9260 ms)\n[INFO] Processing Complete for NVD CVE - 2002  (36417 ms)\n[INFO] Processing Started for NVD CVE - 2004\n[INFO] Download Started for NVD CVE - 2015\n[INFO] Download Complete for NVD CVE - 2015  (3979 ms)\n[INFO] Download Started for NVD CVE - 2016\n[INFO] Download Complete for NVD CVE - 2014  (14743 ms)\n[INFO] Download Started for NVD CVE - 2017\n[INFO] Download Complete for NVD CVE - 2016  (10126 ms)\n[INFO] Download Started for NVD CVE - 2018\n[INFO] Download Complete for NVD CVE - 2017  (16307 ms)\n[INFO] Processing Complete for NVD CVE - 2004  (29282 ms)\n[INFO] Processing Started for NVD CVE - 2005\n[INFO] Download Started for NVD CVE - 2019\n[INFO] Download Complete for NVD CVE - 2018  (20142 ms)\n[INFO] Download Complete for NVD CVE - 2019  (17827 ms)\n[INFO] Processing Complete for NVD CVE - 2005  (43735 ms)\n[INFO] Processing Started for NVD CVE - 2006\n[INFO] Processing Complete for NVD CVE - 2006  (64923 ms)\n[INFO] Processing Started for NVD CVE - 2007\n[INFO] Processing Complete for NVD CVE - 2007  (58680 ms)\n[INFO] Processing Started for NVD CVE - 2008\n[INFO] Processing Complete for NVD CVE - 2008  (82517 ms)\n[INFO] Processing Started for NVD CVE - 2009\n[INFO] Processing Complete for NVD CVE - 2009  (82191 ms)\n[INFO] Processing Started for NVD CVE - 2010\n[INFO] Processing Complete for NVD CVE - 2010  (123683 ms)\n[INFO] Processing Started for NVD CVE - 2012\n[INFO] Processing Complete for NVD CVE - 2012  (151355 ms)\n[INFO] Processing Started for NVD CVE - 2011\n[INFO] Processing Complete for NVD CVE - 2011  (400671 ms)\n[INFO] Processing Started for NVD CVE - 2013\n[INFO] Processing Complete for NVD CVE - 2013  (134003 ms)\n[INFO] Processing Started for NVD CVE - 2015\n[INFO] Processing Complete for NVD CVE - 2015  (90079 ms)\n[INFO] Processing Started for NVD CVE - 2014\n[INFO] Processing Complete for NVD CVE - 2014  (99732 ms)\n[INFO] Processing Started for NVD CVE - 2016\n[INFO] Processing Complete for NVD CVE - 2016  (84395 ms)\n[INFO] Processing Started for NVD CVE - 2017\n[INFO] Processing Complete for NVD CVE - 2017  (85485 ms)\n[INFO] Processing Started for NVD CVE - 2018\n[INFO] Processing Complete for NVD CVE - 2018  (79350 ms)\n[INFO] Processing Started for NVD CVE - 2019\n[INFO] Processing Complete for NVD CVE - 2019  (53571 ms)\n[INFO] Download Started for NVD CVE - Modified\n[INFO] Download Complete for NVD CVE - Modified  (3676 ms)\n[INFO] Processing Started for NVD CVE - Modified\n[INFO] Processing Complete for NVD CVE - Modified  (4505 ms)\n[INFO] Begin database maintenance\n[ERROR] An unexpected SQL Exception occurred; please see the verbose log for more details.\n[ERROR] Unexpected SQL Exception\norg.owasp.dependencycheck.data.update.exception.UpdateException: Unexpected SQL Exception\n\tat org.owasp.dependencycheck.data.update.NvdCveUpdater.performUpdate(NvdCveUpdater.java:324)\n\tat org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:125)\n\tat org.owasp.dependencycheck.Engine.doUpdates(Engine.java:922)\n\tat org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:723)\n\tat org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:653)\n\tat org.owasp.dependencycheck.App.runScan(App.java:251)\n\tat org.owasp.dependencycheck.App.run(App.java:183)\n\tat org.owasp.dependencycheck.App.main(App.java:80)\nCaused by: java.sql.SQLSyntaxErrorException: (conn=723) Unknown column 'u.id' in 'on clause'\n\tat org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:242)\n\tat org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:171)\n\tat org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:238)\n\tat org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:230)\n\tat org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:157)\n\tat org.mariadb.jdbc.ClientSidePreparedStatement.executeUpdate(ClientSidePreparedStatement.java:192)\n\tat org.owasp.dependencycheck.data.nvdcve.CveDB.cleanupDatabase(CveDB.java:1553)\n\tat org.owasp.dependencycheck.data.update.NvdCveUpdater.performUpdate(NvdCveUpdater.java:322)\n\t... 7 common frames omitted\nCaused by: java.sql.SQLException: Unknown column 'u.id' in 'on clause'\n\tat org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1594)\n\tat org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1453)\n\tat org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1415)\n\tat org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:288)\n\tat org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:221)\n\t... 11 common frames omitted\n[WARN] Unable to update 1 or more Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.\n[ERROR] Unable to continue dependency-check analysis.\n[ERROR] One or more fatal errors occurred\n[ERROR] Unexpected SQL Exception\n[ERROR] No documents exist", "stdout_lines": ["[INFO] Checking for updates", "[INFO] NVD CVE requires several updates; this could take a couple of minutes.", "[INFO] Download Started for NVD CVE - 2002", "[INFO] Download Started for NVD CVE - 2003", "[INFO] Download Complete for NVD CVE - 2003  (2633 ms)", "[INFO] Download Started for NVD CVE - 2004", "[INFO] Processing Started for NVD CVE - 2003", "[INFO] Download Complete for NVD CVE - 2002  (3510 ms)", "[INFO] Download Started for NVD CVE - 2005", "[INFO] Download Complete for NVD CVE - 2004  (2322 ms)", "[INFO] Download Started for NVD CVE - 2006", "[INFO] Download Complete for NVD CVE - 2005  (4023 ms)", "[INFO] Download Started for NVD CVE - 2007", "[INFO] Download Complete for NVD CVE - 2006  (4636 ms)", "[INFO] Download Started for NVD CVE - 2008", "[INFO] Download Complete for NVD CVE - 2007  (7970 ms)", "[INFO] Download Started for NVD CVE - 2009", "[INFO] Processing Complete for NVD CVE - 2003  (15700 ms)", "[INFO] Processing Started for NVD CVE - 2002", "[INFO] Download Complete for NVD CVE - 2008  (5121 ms)", "[INFO] Download Started for NVD CVE - 2010", "[INFO] Download Complete for NVD CVE - 2009  (9708 ms)", "[INFO] Download Started for NVD CVE - 2011", "[INFO] Download Complete for NVD CVE - 2010  (13189 ms)", "[INFO] Download Started for NVD CVE - 2012", "[INFO] Download Complete for NVD CVE - 2012  (9913 ms)", "[INFO] Download Started for NVD CVE - 2013", "[INFO] Download Complete for NVD CVE - 2011  (21725 ms)", "[INFO] Download Started for NVD CVE - 2014", "[INFO] Download Complete for NVD CVE - 2013  (9260 ms)", "[INFO] Processing Complete for NVD CVE - 2002  (36417 ms)", "[INFO] Processing Started for NVD CVE - 2004", "[INFO] Download Started for NVD CVE - 2015", "[INFO] Download Complete for NVD CVE - 2015  (3979 ms)", "[INFO] Download Started for NVD CVE - 2016", "[INFO] Download Complete for NVD CVE - 2014  (14743 ms)", "[INFO] Download Started for NVD CVE - 2017", "[INFO] Download Complete for NVD CVE - 2016  (10126 ms)", "[INFO] Download Started for NVD CVE - 2018", "[INFO] Download Complete for NVD CVE - 2017  (16307 ms)", "[INFO] Processing Complete for NVD CVE - 2004  (29282 ms)", "[INFO] Processing Started for NVD CVE - 2005", "[INFO] Download Started for NVD CVE - 2019", "[INFO] Download Complete for NVD CVE - 2018  (20142 ms)", "[INFO] Download Complete for NVD CVE - 2019  (17827 ms)", "[INFO] Processing Complete for NVD CVE - 2005  (43735 ms)", "[INFO] Processing Started for NVD CVE - 2006", "[INFO] Processing Complete for NVD CVE - 2006  (64923 ms)", "[INFO] Processing Started for NVD CVE - 2007", "[INFO] Processing Complete for NVD CVE - 2007  (58680 ms)", "[INFO] Processing Started for NVD CVE - 2008", "[INFO] Processing Complete for NVD CVE - 2008  (82517 ms)", "[INFO] Processing Started for NVD CVE - 2009", "[INFO] Processing Complete for NVD CVE - 2009  (82191 ms)", "[INFO] Processing Started for NVD CVE - 2010", "[INFO] Processing Complete for NVD CVE - 2010  (123683 ms)", "[INFO] Processing Started for NVD CVE - 2012", "[INFO] Processing Complete for NVD CVE - 2012  (151355 ms)", "[INFO] Processing Started for NVD CVE - 2011", "[INFO] Processing Complete for NVD CVE - 2011  (400671 ms)", "[INFO] Processing Started for NVD CVE - 2013", "[INFO] Processing Complete for NVD CVE - 2013  (134003 ms)", "[INFO] Processing Started for NVD CVE - 2015", "[INFO] Processing Complete for NVD CVE - 2015  (90079 ms)", "[INFO] Processing Started for NVD CVE - 2014", "[INFO] Processing Complete for NVD CVE - 2014  (99732 ms)", "[INFO] Processing Started for NVD CVE - 2016", "[INFO] Processing Complete for NVD CVE - 2016  (84395 ms)", "[INFO] Processing Started for NVD CVE - 2017", "[INFO] Processing Complete for NVD CVE - 2017  (85485 ms)", "[INFO] Processing Started for NVD CVE - 2018", "[INFO] Processing Complete for NVD CVE - 2018  (79350 ms)", "[INFO] Processing Started for NVD CVE - 2019", "[INFO] Processing Complete for NVD CVE - 2019  (53571 ms)", "[INFO] Download Started for NVD CVE - Modified", "[INFO] Download Complete for NVD CVE - Modified  (3676 ms)", "[INFO] Processing Started for NVD CVE - Modified", "[INFO] Processing Complete for NVD CVE - Modified  (4505 ms)", "[INFO] Begin database maintenance", "[ERROR] An unexpected SQL Exception occurred; please see the verbose log for more details.", "[ERROR] Unexpected SQL Exception", "org.owasp.dependencycheck.data.update.exception.UpdateException: Unexpected SQL Exception", "\tat org.owasp.dependencycheck.data.update.NvdCveUpdater.performUpdate(NvdCveUpdater.java:324)", "\tat org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:125)", "\tat org.owasp.dependencycheck.Engine.doUpdates(Engine.java:922)", "\tat org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:723)", "\tat org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:653)", "\tat org.owasp.dependencycheck.App.runScan(App.java:251)", "\tat org.owasp.dependencycheck.App.run(App.java:183)", "\tat org.owasp.dependencycheck.App.main(App.java:80)", "Caused by: java.sql.SQLSyntaxErrorException: (conn=723) Unknown column 'u.id' in 'on clause'", "\tat org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:242)", "\tat org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:171)", "\tat org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:238)", "\tat org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:230)", "\tat org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:157)", "\tat org.mariadb.jdbc.ClientSidePreparedStatement.executeUpdate(ClientSidePreparedStatement.java:192)", "\tat org.owasp.dependencycheck.data.nvdcve.CveDB.cleanupDatabase(CveDB.java:1553)", "\tat org.owasp.dependencycheck.data.update.NvdCveUpdater.performUpdate(NvdCveUpdater.java:322)", "\t... 7 common frames omitted", "Caused by: java.sql.SQLException: Unknown column 'u.id' in 'on clause'", "\tat org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1594)", "\tat org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1453)", "\tat org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1415)", "\tat org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:288)", "\tat org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:221)", "\t... 11 common frames omitted", "[WARN] Unable to update 1 or more Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.", "[ERROR] Unable to continue dependency-check analysis.", "[ERROR] One or more fatal errors occurred", "[ERROR] Unexpected SQL Exception", "[ERROR] No documents exist"]}

**To Reproduce**
1. Install MariaDB
2. Create the database and users as indicated in the DependencyCheck documentation (use https://dl.bintray.com/jeremy-long/owasp/dependency-check-5.2.2-release.zip)
3. Download and unarchive DependencyCheck https://dl.bintray.com/jeremy-long/owasp/dependency-check-5.2.2-release.zip
4. Add mariadb-java-client-2.4.1.jar
5.  Launch an analyze: $HOME/dependency-check_5.2.2/bin/dependency-check.sh --dbDriverName org.mariadb.jdbc.Driver --connectionString jdbc:mariadb://localhost/dependencycheck_5_2_2 --dbUser ***** --dbPassword ***** --project  DependencyCheckTest --format ALL --enableExperimental --scan $HOME/DependencyCheckTest/** --dbDriverPath /usr/share/java/mariadb-java-client-2.4.1.jar

**Expected behavior**
No MySQL error at this step

**Additional context**
The database is used as a centralized cache database. The command line provided is only used to populate the database.

**Comment by phoenixadb** [comment]
The problem comes from this query : 
`UPDATE cpeEntry u SET u.ecosystem = (SELECT q.eco FROM cpeEntry e INNER JOIN (SELECT DISTINCT vendor, product, MIN(ecosystem) eco FROM cpeEntry WHERE ecosystem is not null GROUP BY vendor, product) q ON q.vendor = e.vendor AND q.product = e.product AND e.id = u.id) WHERE exists (SELECT * FROM cpeEntry e INNER JOIN (SELECT DISTINCT vendor, product, MIN(ecosystem) eco FROM cpeEntry WHERE ecosystem is not null GROUP BY vendor, product) q ON q.vendor = e.vendor AND q.product = e.product AND e.id = u.id) AND u.ecosystem is null;
ERROR 1054 (42S22): Unknown column 'u.id' in 'on clause'`

File dbStatements.properties at line 45.

**Comment by jeremylong** [comment]
Any chance you could re-run this with the `--log odc.log` option added to the CLI and then provide the full log?  Specifically looking for a debug statement, "Database product: ...".  I'd like to know what is reported on that line and I don't have a MariaDB setup.

**Comment by phoenixadb** [comment]
Hi @jeremylong, please find attached the log file.
[odc.log](https://github.com/jeremylong/DependencyCheck/files/3762999/odc.log)

**Comment by jeremylong** [comment]
@aikebah thank you for the PR!
