### ISSUE TITLE
Unsupported Dependency-Check schema version detected

### ISSUE THREAD

**Issue by tediroca** [dependency-check/DependencyCheck#2285]
**Describe the bug**
Unable to run dependency-check analysis when using version 5.0.2.

** Version of dependency-check used **
5.0.2

** Log file **
```
DependencyCheck] Collecting Dependency-Check artifact
[DependencyCheck] Unable to parse /var/lib/jenkins/workspace/some_path/dependency-check-report.xml
[DependencyCheck] Unsupported Dependency-Check schema version detected
Finished: SUCCESS
```

**To Reproduce**
1. Update to dependency-check jenkins plugin 5.0.2.
2. Run the analysis.

**Expected behavior**
Analysis is succesfully executed

**Additional context**
Analysis fails to run

**Comment by mprins** [comment]
you probably need to reconfigure the plugin, there are breaking changes from 4.x

**Comment by aikebah** [comment]
Which version of DependencyCheck did you configure to run to produce the report? The [dependency-check Jenkins plugin version 5 and above](https://wiki.jenkins.io/display/JENKINS/OWASP+Dependency-Check+Plugin) only supports reading reports produced by DependencyCheck 5 and above (CLI/Maven plugin/Gradle plugin/Ant task

> Publisher parses Dependency-Check XML reports generated from Dependency-Check v5.0 and higher

If you use the 5.0.2 plugin to run the analysis as well, you need to make sure that you configure a 5.x version of DependencyCheck to run the analysis. If you only use the publisher you need to make sure that the plugin embedded in your build script that produces the report is a version 5 or above.

**Comment by tediroca** [comment]
Thanks both for you help. I didn't realize the plugin had change that much for the last versions, so reconfiguring it fixed the problem.
