### ISSUE TITLE
npm audit doesn't match report

### ISSUE THREAD

**Issue by henry-zektser-vineti** [dependency-check/DependencyCheck#2297]
**Describe the bug**
`npm audit` returns 604 vulns, dependency-check only finds 14

** Version of dependency-check used **
The problem occurs using version 5.2.2 of the the cli

**To Reproduce**
1. Run `npm audit`
2. Observe results;
```
found 604 vulnerabilities (127 low, 3 moderate, 474 high) in 98668 scanned packages
  run `npm audit fix` to fix 471 of them.
  127 vulnerabilities require semver-major dependency updates.
  6 vulnerabilities require manual review. See the full report for details.
```
3. run `dependency-check.sh --format HTML --enableExperimental -s './**/*'`
4. open HTML report
5. Observe results
```
dependency-check version: 5.2.2
Report Generated On: Sat, 2 Nov 2019 11:16:11 -0400
Dependencies Scanned: 72852 (36886 unique)
Vulnerable Dependencies: 10
Vulnerabilities Found: 14
Vulnerabilities Suppressed: 0
```

**Expected behavior**
Results should match

**Comment by thib3113** [comment]
Hello, @henryz-vineti can you share your package.json to test ? ( I just need the dependencies part, you can obfuscate the other parts )
PS : i'm not the developper of this projet, just I'm using it for node too, so can interest me

**Comment by jeremylong** [comment]
Can this be tested using 5.2.3 (or 5.2.4 will be released in the morning).  We made changes in 5.2.3 that might address this issue.
