### ISSUE TITLE
There was an issue getting Nexus status. Disabling analyzer

### ISSUE THREAD

**Issue by PeterFromWiesbaden** [dependency-check/DependencyCheck#230]
We are newbies with Dependency-Check. After a lot of trial and error we have got a check running which actually loads the database from downloaded nvdcve-files and returns a report

However we still get a warning that there is an issue getting Nexus status:

Mai 07, 2015 3:09:12 PM org.owasp.dependencycheck.Engine analyzeDependencies
Information: Analysis Starting
Mai 07, 2015 3:09:13 PM org.owasp.dependencycheck.analyzer.NexusAnalyzer initializeFileTypeAnalyzer
Warnung: There was an issue getting Nexus status. Disabling analyzer.
Mai 07, 2015 3:09:17 PM org.owasp.dependencycheck.Engine analyzeDependencies
Information: Analysis Complete

This is our definition in a maven pom:
                   <centralAnalyzerEnabled>false</centralAnalyzerEnabled>
                    <nexusAnalyzerEnabled>true</nexusAnalyzerEnabled>
                    <nexusUrl>https://machine.domain/nexus</nexusUrl>
                    <nexusUsesProxy>true</nexusUsesProxy>

I have read in another issue that the nexus url usually ends  with /service/local/. This is not the case at our company. Have we setup Nexus wrong?

We have absolutely no idea what to do. Any help is welcome.

Peter

**Comment by PeterFromWiesbaden** [comment]
Just realized that service/local is the REST-api URL. So I changed my settings to

Result is still the same.
`<centralAnalyzerEnabled>false</centralAnalyzerEnabled>`
`<nexusAnalyzerEnabled>true</nexusAnalyzerEnabled>`
`<nexusUrl>https://machine.domain:8443/nexus/service/local/</nexusUrl>`
`<nexusUsesProxy>true</nexusUsesProxy>`

**Comment by jeremylong** [comment]
I just updated the JavaDoc to emphasize that we are looking for the service end point. The [documentation site](https://jeremylong.github.io/DependencyCheck/) was changed recently to reflect that the nexus configuration is looking for the service end point. 

Glad you were able to get it working.
