### ISSUE TITLE
Need information regarding "packages" object in dependency-check-report.json

### ISSUE THREAD

**Issue by Anshu2405** [dependency-check/DependencyCheck#2303]
Previously , we were using ODC maven plugin v4.0.2 to scan java projects. Recently, we got a requirement to run ODC latest v5.2.2 against node projects.
In order to do so, we are using dependency check tool after enabling --enableExperimental flag in the command. 

We noticed few output report differences .
In 4.2.2, we could see identifiers object which contains CPEs having type as either CPE or Maven and confidence level.

      "identifiers": [
        {
          "name": "cpe:/a:pivotal_software:spring_framework:4.1.6",
          "type": "cpe",
          "confidence": "HIGHEST",
          "url": "https://web.nvd.nist.gov/view/vuln/search-results?adv_search=true&cves=on&cpe_version=cpe%3A%2Fa%3Apivotal_software%3Aspring_framework%3A4.1.6"
        },
        {
          "name": "org.springframework:spring-aop:4.1.6.RELEASE",
          "type": "maven",
          "confidence": "HIGHEST"
        },
        {
          "name": "cpe:/a:springsource:spring_framework:4.1.6",
          "type": "cpe",
          "confidence": "LOW"
        }
      ],
But in 5.2.2 , instead of "identifiers" there is "packages" object in JSON which provides "id","confidence" and "url" information.

     "packages": [
        {
          "id": "pkg:npm/request",
          "confidence": "HIGHEST"
        }
      ],

Please help with the below queries:
1. Can we consider both the objects similar and use the package confidence level? Also, we always  get confidence level as "HIGHEST" in v5.2.2.
2. Where can we get matching CPE information(name & confidence) in the latest version?

**Comment by jeremylong** [comment]
In 5.x we split the identifiers into two collections: "packages" and "vulnerabilityIds".  In retrospect - `packages` may not have been the best name but it is what we have.  These contain the [Package URL](https://github.com/package-url/purl-spec) when one could be determined.  The `vulnerabilityIds` contain the CPE identifiers.

**Comment by Anshu2405** [comment]
Thanks for your reply. Please help with few more details.

I could see vulnerabilityIds only in JAR vulnerabilities and packages in case of Node JS vulnerabilities.

1. Is there any way to get CPE identifiers(both name & confidence) for JavaScript files too?
2. How to retrieve  package information in case of Jar vulnerabilities?

Output of V4.0.2:
{
      "name": "org.springframework:spring-aop:4.1.6.RELEASE",
      "type": "maven",
      "confidence": "HIGHEST"
    },

**Comment by Anshu2405** [comment]
Hi @jeremylong ,

Could you please update on the above queries. These are really important for my project.

Or let us know if we get vulnerabilityIds information only in jar vulnerabilities and package information in case of Node JS vulnerabilities.

Thanks,
Anshul

**Comment by jeremylong** [comment]
ODC does not generally produce a CPE for JavaScript files.  The package information is contained within the Package URL in the packages section.
