### ISSUE TITLE
Is there a quick way to switch Dependency Check 4.0.2 NVD feeds from xml to Json?

### ISSUE THREAD

**Issue by rich200** [dependency-check/DependencyCheck#2311]
We have been using Dependency Check 4.0.2 to generate XML output for upload which is only version supported by Dependency Track 3.5.  Since Dependency Check 4.0.2 is using NVD XML fedd which retired on Wednesday October 16th, it caused Dependency Check 4.0.2 failed. 

Can you please provide suggestion on how to change Dependency Check 4.0.2 to use NVD Json Feeds instead of XML Feeds?

**Comment by jeremylong** [comment]
Use dependency-check 5.2.2 or higher.  ODC 4.x is no longer supported.
