### ISSUE TITLE
Argument which print the actual version of vulnerabilities bases

### ISSUE THREAD

**Issue by 2fortunately** [dependency-check/DependencyCheck#2315]
**Is your feature request related to a problem? Please describe.**
For our Security team will be cool if we can provide the version of vulnerabilities bases which checks dependencies in project. 

**Describe the solution you'd like**
Add a new argument which will print the actual version of vulnerabilities bases

**Describe alternatives you've considered**
We can just print by curl https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-modified.meta and https://raw.githubusercontent.com/Retirejs/retire.js/master/repository/jsrepository.json

**Comment by jeremylong** [comment]
We don't keep track of the `lastModifiedDate` of all of the NVD files.  We only keep track of the modified. This is already written into the reports; below is from one of the HTML reports.

```
NVD CVE Modified: 2019-11-11T15:02:18
```

One of the reasons we don't keep track of them all - if we have updated within the last seven days we only update based on the modified JSON file.

**Comment by 2fortunately** [comment]
Ok, thanks for answer
