### ISSUE TITLE
v1-2-10 HTML output doesn't group libraries completely (was Batik-ext and Batik-util both vuln and not vuln)

### ISSUE THREAD

**Issue by demasb** [dependency-check/DependencyCheck#232]
When command line Dependency Check is run on two or more applications at one time (multiple -s entries), the HTML output report does not group all the vulnerabilities found in one output (via Related Dependencies). 

In the case of the Batik libraries (batik-css-1.7, batik-ext-1.7, and batik-util-1.7) for example, the report listed App1.war: batik-css-1.7.jar vuln with Related Dependencies: App1.war: batik-ext-1.7.jar, App1.war: batik-util-1.7.jar and App2.war: batik-css-1.7.jar. A second vuln was found in App2.war: batik-ext-1.7.jar with Related Dependencies App2.war: batik-util-1.7.jar. 

The last two are repeats of the first vuln but for the second App2. Since the first vuln listed included entries for both Apps, should it have included the other two entries as well?

**Comment by jeremylong** [comment]
The way it was intended to work is you would only have a single entry for batik with all of the related batik jar files listed as related dependencies. I'll try to replicate the problem on my side. However, due to some upcoming travel this may take me a while to test/fix.

**Comment by demasb** [comment]
Jeremy,

Thanks, attached are a couple of pared down application war files that I was able to test with. They are really basic, just the Batik libraries in both. This is the command I ran:
dependency-check.bat -a BatikTest -s App1.war -s App2.war
There will be two vulnerable dependencies in the html report, one will have 3 Related Dependencies, the other will have 1. Like you said, there should have been just one vulnerable library with 5 Related Dependencies.

Thanks
Bill

**Comment by jeremylong** [comment]
After further testing a bug was identified that caused the same dependency in WAR2 to be combined as a related dependency in WAR1. The intended functionality is that when using the CLI interface, if you scanned two separate WAR files that contained the exact same files you would get a vulnerable dependency listed for each WAR file. As such, in the updated version you should see both WARs have vulnerable listings for batik; but when you look at the related dependencies you should only see ones related within the same WAR.

The patch for the bug identified during the research has been added to 1.2.12-SNAPSHOT and will be included in the next release.

--Jeremy
