### ISSUE TITLE
Error when generating pretty XML report

### ISSUE THREAD

**Issue by MichaelVetter** [dependency-check/DependencyCheck#2320]
The pretty report is generated in the file dependency-check-report.xml.pretty but it is not copied to a dependency-check-report.xml file and there is an error message. Without the pretty setting it works fine.

The problem occurs using version 5.2.3 of the the cli and the maven plugin.
With the cli we use these parameters:
```
-f HTML -f XML --prettyPrint
```
** Log file extract**
2019-11-11 15:19:35,998 org.apache.velocity.runtime.VelocimacroFactory:385
DEBUG - added VM writeXmlException: source=org.apache.velocity.Template@57b75756
2019-11-11 15:19:36,027 org.apache.velocity.runtime.parser.node.ASTMethod:181
DEBUG - Object 'org.owasp.dependencycheck.dependency.CweSet' does not contain method isEmpty() at templates/xmlReport.vsl[line 227, column 18]
2019-11-11 15:19:36,100 org.apache.velocity.runtime.parser.node.ASTMethod:181
...
2019-11-11 15:19:36,917 org.owasp.dependencycheck.reporting.ReportGenerator:510
ERROR - Unable to generate pretty report, caused by: Failed to delete original file 'C:\winapp\dependency-check-5.2.3\.\dependency-check-report.xml.pretty' after copy to 'C:\winapp\dependency-check-5.2.3\.\dependency-check-report.xml'

**Comment by jeremylong** [comment]
The 5.2.3 release has more than 1 issue...  We will be releasing 5.2.4 shortly - and re-evaluating the QA being done with each release.

**Comment by MichaelVetter** [comment]
The problem alread occured with older versions. I just did not have the time to report it.

**Comment by MichaelVetter** [comment]
The main problem is not fixed with the new release. Does the test work in your environment?
I assume that the method pretifyXml in ReportGenerator needs to be rewritten like pretifyJson to close the Streams ( see https://stackoverflow.com/questions/49626912/java-io-ioexception-failed-to-delete-original-file-movefiletodirectory).
