### ISSUE TITLE
HTML Report not generated in combination with failOnCVSS

### ISSUE THREAD

**Issue by ingokofler** [dependency-check/DependencyCheck#2325]
**Describe the bug**
I use the latest Docker image to run a vulnerability scan a JAR file for vulnerabilities. I am using the flags `--format ALL --failOnCVSS 7`. If the scan success, the reports are created however if the scan fails due to an detected vulnerability, the HTML report is not generated.

** Version of dependency-check used **
owasp/dependency-check:3.2.1

** Log file **
https://gist.github.com/ingokofler/80d99c41a523dc243363aa06cb1d097f

**To Reproduce**
Run a dependency check on a JAR file with a known vulnerability. Use the flags `--format ALL --failOnCVSS 7`.

```
/usr/share/dependency-check/bin/dependency-check.sh \
          -l /dev/stdout \
          --data nvdData \
          --scan app/app.jar \
          --out reports \
          --format ALL \
          --failOnCVSS 7 \
          --suppression suppressed-dependencies.xml \
          --project myProject
```

**Expected behavior**
Execution should fail with an exit code != 0. Both HTML and JUnit report should exist.

**Additional context**

**Comment by jeremylong** [comment]
I am unable to reproduce this problem.  Using the latest docker image `owasp/dependency-check:5.2.4` I was able to scan without the failOnCVSS flag and ran:

```
$ ./test-docker.sh
$ echo $?
0
```

I then added the `--failOnCVSS 5` ran the scan and the reports were generated and I then ran:
```
$ ./test-docker.sh
$ echo $?
1
```

Where `test-docker.sh` is basically the shell script found here: https://github.com/jeremylong/DependencyCheck#docker

**Comment by ingokofler** [comment]
shame on me. this was not an issue related to the Docker image and the script itself but rather on the way how I integrated it in my GitLab CI pipeline. Since the job failed the HTML report was simply not uploaded.
