### ISSUE TITLE
PyPi version obsolete

### ISSUE THREAD

**Issue by jeffchamblee** [dependency-check/DependencyCheck#2331]
I have been getting dependency check from PyPi (https://pypi.org/project/dependency-check/). Now I realize that the version is very old (0.2.0). How can I get an up to date version in a Python environment? I'd like to continue using pip because I need to install it automatically in a continuous integration pipeline.

**Comment by mprins** [comment]
The python version was not published by this project. Please see the origin readme at https://github.com/jhermann/dependency-check-py
It seems there is a way to do what you want using pip but not PyPi
