### ISSUE TITLE
RetireJS reports JSON Error

### ISSUE THREAD

**Issue by bscheller-iso** [dependency-check/DependencyCheck#2333]
**Describe the bug**

** Version of dependency-check used **
I used the bat script and the version 5.2.2.

** Log file **
2019-11-19 16:04:27,877 org.owasp.dependencycheck.Engine:856
DEBUG - 
org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]

**To Reproduce**
We use a Proxyserver. I first started the DC without the Proxy. After setting him and another start of the tool the mentioned error occured. It pointed out that an empty jsrepository.json file was created. But the DC stated that the update was not 24 h past so no new update started.

**Comment by mprins** [comment]
you want to inspect network traffic from your proxy to your client to see if it is the actual data or if the proxy is giving you bogus data eg. error pages

**Comment by bscheller-iso** [comment]
No. I only executed the dependency check on an Java Library. Due to the missing proxy server configuration the json file for retireJS was empty. Further executions at the same day using the right proxy server config did not solve the problem, because there is the 24 hours interval. Only after 24 hours the json file is downloaded again.

**Comment by jeremylong** [comment]
A better error message should be provide - indicating that the user should run the purge command or manually delete the offending file
