### ISSUE TITLE
Unexpected exception occurred initializing RetireJS Analyzer depends on plugin location in dependencies

### ISSUE THREAD

**Issue by jimshowalter** [dependency-check/DependencyCheck#2342]
We had:

buildscript
dependencies {
classpath "net.ltgt.gradle:gradle-apt-    classpath "org.owasp:dependency-check-gradle:${owaspVersion}"

and moved it lower in the list of classpath plugins, and we got "Unexpected exception occurred initializing RetireJS Analyzer".

Initialization of the OWASP plugin appears to be order-dependent!

**Comment by jeremylong** [comment]
We would need much more information to understand what is going on in this case.  Can you provide a `gradle.build` that demonstrates the issue?

**Comment by jeremylong** [comment]
Actually - after thinking about this a little more my best guess is that the local retire.js repository was corrupted.  All you would need to do is run `./gradlew dependencyCheckPurge` to restore functionality.  The next release should include better error reporting for this condition.
