### ISSUE TITLE
Re-instaurate identifiers field in json report

### ISSUE THREAD

**Issue by javixeneize** [dependency-check/DependencyCheck#2344]
Hi

In dependency check v4 json report, there was a field called "identifiers", that was useful to retrieve the real name of the dependency that was analysed

          "identifiers": [
            {
              "type": "maven",
              "id": "org.springframework.boot:spring-boot-starter:2.1.0.RELEASE"
            }
          ]

I cant see this anymore in the report generated in v5. I think this field was useful and should be added back to the report

Thanks

**Comment by jeremylong** [comment]
The identifiers node was replaced with packages:

```json
      "packages": [
        {
          "id": "pkg:maven/com.datomic/client@0.8.81",
          "confidence": "HIGH",
          "url": "https://ossindex.sonatype.org/component/pkg:maven/com.datomic/client@0.8.81"
        }
```

This uses the Package URL (see [purl-spec](https://github.com/package-url/purl-spec)) syntax and allows for a more flexible/accurate way of describing the various dependencies across different ecosystems.  It is trivial to translate a package URL into a maven GAV for Maven dependencies.

**Comment by javixeneize** [comment]
Happy with that then :)

Thanks Jeremy!
