### ISSUE TITLE
Is it possible to add custom fields in suppressionFiles ?

### ISSUE THREAD

**Issue by fmarot** [dependency-check/DependencyCheck#2347]
Hello, just a minor question maybe leading to a feature request:

is it possible to add custom fields to the suppressionFiles (xml) ? It seems to me that it is being validated toward the xsd file so I cannot. I think it would be usefull to be able to have this file "augmented" with company specific fields. But as it is now we can only add either XML comments (but this is unstructured data) or maintain another file besides the suppressionFiles.

Nevertheless thank you very much for your good work helping us secure the software :)

**Comment by jeremylong** [comment]
Do you mean something like a `notes` or `reason` field?

**Comment by fmarot** [comment]
I know of the `notes` field but not the `reason` field. Nevertheless, I was looking for some custom fields that would not be included in the default html template. They would be visible only for coders editing the xml file. If it is not possible, no need to create a feature request or anything, this was just a simple question ;)

**Comment by jeremylong** [comment]
Added `dependency-hint.1.4.xsd` that includes a notes node on the `hint` node.  Note, the notes node is not available for duplicatingHints.

**Comment by fmarot** [comment]
Thank you very much @jeremylong !
