### ISSUE TITLE
Allow custom ProjectReference naming in BaseDependencyCheckMojo to improve reporting

### ISSUE THREAD

**Issue by jamesratzlaff** [dependency-check/DependencyCheck#2350]
**Is your feature request related to a problem? Please describe.**
When reading an aggregate report created by the maven plugin, I have come across projects that have modules with the same value for the ```<name>``` element. Since the [collectMavenDependencies method in BaseDependencyMojo uses project.getName() + ":" + dependencyNode.getArtifact().getScope()](https://github.com/jeremylong/DependencyCheck/blob/1df1e8ecd8cc7e46d2cb132d70fe7a62bad27150/maven/src/main/java/org/owasp/dependencycheck/maven/BaseDependencyCheckMojo.java#L1115) to create the project name, it makes it almost impossible to distinguish these hap-hazardly named projects in the generated report. 

**Describe the solution you'd like**
Since I'm extending the BaseDependencyMojo to create a custom goal, the easiest thing would be to factor out project.getName() + ":" + dependencyNode.getArtifact().getScope() into it's own  method that is visible enough to be Overridden

```java
protected String generateProjectReferenceName(MavenProject project, DependencyNode
 dependencyNode){
    return project.getName() + ":" + dependencyNode.getArtifact().getScope();
}
```
and calling ```generateProjectReferenceName(project, dependencyNode)``` instead of [statically in-lining the value when calling engine.scan in collectMavenDependencies](https://github.com/jeremylong/DependencyCheck/blob/1df1e8ecd8cc7e46d2cb132d70fe7a62bad27150/maven/src/main/java/org/owasp/dependencycheck/maven/BaseDependencyCheckMojo.java#L1115).

Having this would allow my sub class to override that method so I can generate a name that's more unique.

**Describe alternatives you've considered**
I've considered going in to the project and tracking down and modifying/removing each module's defined name in their respective pom if duplicates are found, but that would take forever.  An alternative to the solution I mentioned above is a bit more complex but more configurable. 

Instead of having just an overrideable method we could have:

```java
private static final String DEF_PROJ_REF_NAMING(MavenProject project, DependencyNode
 dependencyNode){
    return project.getName() + ":" + dependencyNode.getArtifact().getScope();
}

//...

@Parameter(property = "projectReferenceNamingClass")
private String projectReferenceNamingClass;

private BiFunction<MavenProject, DependencyNode, String> projectReferenceNaming;

//...

public BiFunction<MavenProject,DependencyNode,String> getProjectReferenceNaming(){
    if(this.projectReferenceNaming == null){
        this.projectReferenceNaming=BaseDependencyCheckMojo::DEF_PROJ_REF_NAMING;
        if(this.projectReferenceNamingClass!=null){
            try {
                /* TODO: add code that creates an object instance of the specified by 
                 * projectReferenceNamingClass and assigns it to 
                 * this.projectReferenceNaming. 
                 */
            } catch(Exception e){
                /* If instance creation fails then the
                 * projectReferenceNamingClass field should by set to null and the
                 * exception should be logged so we don't spam the logs
                 */    
                getLog().error(e.getMessage(), e);
                this.projectReferenceNamingClass = null;
             }           
        }
    }
    return this.projectReferenceNaming;
}

public void setProjectReferenceNaming(BiFunction<MavenProject, DependencyNode, String>
 namingFunc){
    this.projectReferenceNaming=namingFunc;
}

protected void generateProjectReferenceName(MavenProject project, DependencyNode
 dependencyNode) {
    try{
        getProjectReferenceNaming().apply(project, dependencyNode);
    } catch(Exception e){
        getLog().warn(String.format("The provided naming function failed with message %s,"+ 
            "using default function instead",e.getMessage()));
        return DEF_PROJ_REF_NAMING(project, dependencyNode);
   }
}
```

This would allow a user to define the name of a class that implements BiFunction<MavenProject, DependencyNode, String> as one of the parameters when running the plugin.  This also has safeguards so it falls back to the original behavior if anything goes wrong when creating an instance if the named class or running the set BiFunction itself.

**Comment by jeremylong** [comment]
Any chance you could submit this as a PR?

**Comment by jamesratzlaff** [comment]
Sure can, I'll try to get it in sometime this week.
