### ISSUE TITLE
IllegalStateException: Transaction is closed

### ISSUE THREAD

**Issue by OrangeDog** [dependency-check/DependencyCheck#2352]
**Describe the bug**
An exception when processing the vulnerability data, causing mojo to fail.

**Version of dependency-check used**
The problem occurs using version 5.2.4 of the the maven plugin

**Log file**
https://gist.github.com/OrangeDog/1a4b631306df81688665d6668a9622ac

**To Reproduce**
Unsure. It's only happening on one installation (a CI machine), but happens every time.

**Expected behavior**
No such exceptions.

**Comment by OrangeDog** [comment]
Deleting the data directory (~/.m2/repository/org/owasp/dependency-check-data/4.0/) appears to have fixed it for the next run.

**Comment by jeremylong** [comment]
Somehow the database got corrupted.  Deleting the h2 database appears to have fixed the issue.

**Comment by OrangeDog** [comment]
It happened again. Is the data directory (before I deleted it) of any use?

**Comment by jeremylong** [comment]
Unfortunately no.  We are looking at completely refactoring the data load which should resolve this.

**Comment by OrangeDog** [comment]
I suspect my root cause was disk space exhaustion.
