### ISSUE TITLE
False Positive on async-http-client-netty-utils-2.10.1.jar

### ISSUE THREAD

**Issue by reidrac** [dependency-check/DependencyCheck#2369]
I believe this is the same as in  issue #1068.

False positive on library async-http-client-netty-utils-2.10.1.jar reported as:
- `cpe:2.3:a:asynchttpclient_project:async-http-client:2.10.1:*:*:*:*:*:*:*`
- `cpe:2.3:a:netty:netty:2.10.1:*:*:*:*:*:*:*`

There's also netty-reactive-streams-2.0.3.jar being reported as `cpe:2.3:a:netty:netty:2.0.3:*:*:*:*:*:*:*`; so I its exactly as in the aforementioned issue, but different versions.

Thanks!

**Comment by jeremylong** [comment]
I'm not able to reproduce this using the latest version of dependency-check - I believe this has already been resolved.

**Comment by reidrac** [comment]
We use dependency-check via sbt-dependency-check that is currently using 5.2.4 AFAIK, and I'm still experiencing the issue.

Let me know what I can do to help.

**Comment by jeremylong** [comment]
I just retested this with 6.0.3-SNAPSHOT and do not see this showing as a false positive.
