### ISSUE TITLE
variable parameter in Jenkins pipeline

### ISSUE THREAD

**Issue by fipsmassa** [dependency-check/DependencyCheck#2370]
Is ist possible to replace the parameter of an additional argument with a variable when invoking dependency check in a jenkins pipeline?
E. g. the path to a suppression file looks like this at the moment and works perfectly well: 

`dependencyCheck additionalArguments: --suppression /test/suppression.xml'`

But since I want to use a shared library in jenkins the path should be replaced with a placeholder that is filled with a value when the shared library step is called. So the parameter of the suppression-argument should look something like this: 

`--suppression "${suppressionFile}"`

Do I just fail at the syntax here or is this not possible? 

Thanks

**Comment by stevespringett** [comment]
Of course, per the Jenkins documentation, environment variables are available via the `env` variable which can be used anywhere in the pipeline.

https://jenkins.io/doc/book/pipeline/jenkinsfile/#using-environment-variables

So, something like `env.suppressionFile` or `${env.suppressionFile}` is what you want. You'll obviously need to specify the value of suppressionFile prior to using it.

**Comment by fipsmassa** [comment]
Thank you. I use a scripted pipeline so I tried the withEnv step. Setting it up an echoing it works well: 
`withEnv (['file=suppressionGlobal.xml']){
    echo "${env.file}"
}` --> suppression.xml

but when I want to use the variable as an parameter for the additionalArguments it does not work: neither
`dependencyCheck additionalArguments:' --suppression "${env.file}"' ` nor 
`dependencyCheck additionalArguments: '--suppression "${file}"'` 
--> This leads to a warning/error 
`Suppression file does not exist` [...] `Unable to create an Input Stream for ${file}` (even though the file exists)

However if I parametrize the pipeline, I can use the variables in the additionalArgument list perfectly well, e.g. 
`String file= getParam("file", 'suppression.xml')`
`dependencyCheck additionalArguments: '--suppression "${file}"'` --> this works

Do I still miss something in the variable part?

**Comment by stevespringett** [comment]
I have no idea. I'm at my limit for knowing how variables in pipeline work. You may want to ask the folks in the Jenkins Users group to see how it works.

https://groups.google.com/forum/#!forum/jenkinsci-users

**Comment by adrielldagasuan** [comment]
Did you try this?
`dependencyCheck additionalArguments: "--suppression ${file}"` (wrapping it entirely with double-quotes)
