### ISSUE TITLE
Scan of local .m2 folder

### ISSUE THREAD

**Issue by frydaykg** [dependency-check/DependencyCheck#2375]
I use OWASP Dependency Checker to scan code in pipelines. I do it after building of it.

I found that some project use local maven repository e.g.:
`/jenkins/workspace/MyProject/.m2/`

Should I scan this folder or better to exclude it? I think the second option is better cause .m2 could contains plugins, test libraries etc

**Comment by jeremylong** [comment]
The .m2 folder should be skipped in this scenario.

**Comment by frydaykg** [comment]
Now I have more gereral question:
what default folders should I exclude in cases when I am scanning source code after build?

Should I scan node_modules directory? Should I scan it if I don't use NPM analyzer?
Should I scan gradle directory?

**Comment by jeremylong** [comment]
Scan the build artifacts and dependencies.  I'm not sure what your environment looks like.

However, I would suggest using the maven or gradle dependency-check plugin as part of the build instead of just using the CLI - you will get slightly better results.

**Comment by frydaykg** [comment]
Unfortunately I should provide single service for a huge number of build and configurations that's why CLI is my best option.

When i scan node_modules I mostle look for vulnerabilities of dependencies of my dependencies?  Am I right? The same for any other local repository.

**Comment by jeremylong** [comment]
In cases of supporting a ton of different projects - have you considered something like:

```bash
if test -f "pom.xml"; then
   mvn org.owasp:dependency-check-maven:aggregate
   publish ./target/dependency-check.xml
elif  test -f "build.gradle"; then
   gradle --init-script /path/to/customDependencyCheckConfig.gradle dependencyCheckAggregate
   publish ./build/reports/dependency-check.xml
else
   dependency-check.sh -s . -o . -f XML
   publish ./dependency-check.xml
fi
```

Of course the above is psuedo-code and would need the correct publish mechanism added.  For gradle see the documentation on [init-scripts](https://docs.gradle.org/current/userguide/init_scripts.html) - I haven't done this myself yet, but basically you could more correctly cover gradle and maven builds out of the box with just a little scripting to detect the build system used.
