### ISSUE TITLE
5.2.4 Maven Plugin - Database Download Failure

### ISSUE THREAD

**Issue by glsutter** [dependency-check/DependencyCheck#2377]
Just upgraded to ODC 5.2.4. Using Maven plugin within a maven:3-alpine Docker container. Getting this initial error:
[ERROR] Download Failed for NVD CVE - 2018
Some CVEs may not be reported. Reason: Download failed, unable to copy 'https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2018.json.gz'
Looks like the download for 2011-2017 were fine. 

Later, at the end of the output, getting this error:
[ERROR] 	java.util.concurrent.ExecutionException: org.owasp.dependencycheck.analyzer.exception.UnexpectedAnalysisException: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: Transaction is closed [1.4.196/4]" [50000-196]
[ERROR] 	No documents exist

Can't seem to figure out where this is coming from? Could it be that I need a server certificate in the Docker container? Anyone seem this error before? I couldn't find a match when searching the Issues. Thanks.

**Comment by jeremylong** [comment]
unfortunately - I would suggest purging the data directory and trying the download again. I'm not sure what happened - but it is likely not a cert issue if 2011-2017 were fine.

**Comment by patsevanton** [comment]
I have repo 1.0 and 1.1
```
nvdcve-1.0-modified.meta                           05-Jul-2019 07:04                 165
nvdcve-1.0-recent.json.gz                          05-Jul-2019 07:05             1308075
nvdcve-1.0-recent.json.zip                         05-Jul-2019 07:05             1308215
nvdcve-1.0-recent.meta                             05-Jul-2019 07:05                 165
nvdcve-1.1-2002.json.gz                            10-Jan-2020 07:07             1407884
nvdcve-1.1-2002.json.zip                           10-Jan-2020 07:07             1408020
nvdcve-1.1-2002.meta                               10-Jan-2020 07:07                 165
```
After clean files 1.0 that ok.
Error dont have.

**Comment by glsutter** [comment]
This problem resolved on the third or fourth run of the pipeline where we're using dependency check. Not sure what changed, possibly the cache was purged? In any case, issue is resolved.
