### ISSUE TITLE
OWASP reports no vulnerability from NPM when package-lock.json is not present

### ISSUE THREAD

**Issue by Anshu2405** [dependency-check/DependencyCheck#2379]
Hi,

I am running OWASP CLI against Node project but could see Node Audit Analyzer is disabled and output JSON doesn't report any NPM vulnerability. 
I believe it is due  to the unavailability of package-lock.json/npm-shrinkwrap.json file during analysis.

DEBUG - Initializing Node Audit Analyzer
DEBUG - Skipping Node Audit Analyzer (not enabled)

Is there any way to enable Node Audit Analyzer when pacakge-lock.json file is not present in the project ?

**Comment by jeremylong** [comment]
Unfortunately no.  In fact, you cannot run `npm audit` without a package-lock.json or alternatively an `npm-shrinkwrap.json`:

```bash
08:21 $ npm audit
npm ERR! code EAUDITNOLOCK
npm ERR! audit Neither npm-shrinkwrap.json nor package-lock.json found: Cannot audit a project without a lockfile
npm ERR! audit Try creating one first with: npm i --package-lock-only
```
