### ISSUE TITLE
Node Dependencies in submodules not being processed

### ISSUE THREAD

**Issue by adrielldagasuan** [dependency-check/DependencyCheck#2380]
Hi,

I have a maven project which has node dependencies in one of its submodules. Running the depencency-check-maven:aggregate goal in that submodule correctly identifies the node dependencies and it's vulnerabilities (although I have to include `{project.build.directory}/src/webpack` as part of the scanSet). However running the exact same goal from the root/parent pom doesn't trigger the Node.js Package Analyzer or Node Audit Analyzer.

Snippet of log when running from the parent pom:
```[INFO] Analysis Started
[INFO] Finished Archive Analyzer (3 seconds)
[INFO] Finished File Name Analyzer (0 seconds)
[INFO] Finished Jar Analyzer (1 seconds)
[INFO] Finished Dependency Merging Analyzer (0 seconds)
[INFO] Finished Version Filter Analyzer (0 seconds)
[INFO] Finished Hint Analyzer (0 seconds)
[INFO] Created CPE Index (2 seconds)
[INFO] Finished CPE Analyzer (4 seconds)
[INFO] Finished False Positive Analyzer (0 seconds)
[INFO] Finished NVD CVE Analyzer (0 seconds)
[INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
[INFO] Analysis Complete (14 seconds)
```

Snippet of log when running the goal from the submodule:
```[INFO] Analysis Started
[INFO] Finished Archive Analyzer (0 seconds)
[INFO] Finished File Name Analyzer (0 seconds)
[INFO] Finished Node.js Package Analyzer (1 seconds)
[INFO] Finished Dependency Merging Analyzer (0 seconds)
[INFO] Finished Version Filter Analyzer (0 seconds)
[INFO] Finished Hint Analyzer (0 seconds)
[INFO] Created CPE Index (2 seconds)
[INFO] Finished CPE Analyzer (2 seconds)
[INFO] Finished False Positive Analyzer (0 seconds)
[INFO] Finished NVD CVE Analyzer (0 seconds)
[INFO] Finished Node Audit Analyzer (0 seconds)
[INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
[INFO] Analysis Complete (5 seconds)
```

**Comment by adrielldagasuan** [comment]
Just for additional information, the version we're using is 5.2.4. Also, if I place the absolute path in the scanSet, then it works.

absolute path works:
```
<scanSet>
    <fileSet><directory>submodule/target/sources/webpack</directory></fileSet>
    <fileSet><directory>${project.basedir}/src/main/resources</directory></fileSet>
    <fileSet><directory>${project.basedir}/src/main/webapp</directory></fileSet>
</scanSet>
```

project.build.directory (which is ${project.basedir}/target) doesn't work:
```
<scanSet>
    <fileSet><directory>${project.build.directory}/sources/webpack</directory></fileSet>
    <fileSet><directory>${project.basedir}/src/main/resources</directory></fileSet>
    <fileSet><directory>${project.basedir}/src/main/webapp</directory></fileSet>
</scanSet>
```
Is the scanset only evaluated during the start of execution or does it get evaluated everytime it runs into a maven module?

**Comment by jeremylong** [comment]
Unfortunately - the `project.basedir` is evaluated for the aggregate (i.e. top most) build. As such, when the plugin gets path from the configured scanSet the path has already been converted to a full/canonical path. As such, using the `${project.basedir}` will not work for aggregate builds.  However, there is a solution - don't use the project variables. If you make the paths relative to the build they will be evaluated correctly for each child-module.

```xml
<scanSet>
    <fileSet><directory>target/sources/webpack</directory></fileSet>
    <fileSet><directory>src/main/resources</directory></fileSet>
    <fileSet><directory>src/main/webapp</directory></fileSet>
</scanSet>
```

I have updated the documentation to clearly spell this out.
