### ISSUE TITLE
Maven Plugin is running RetireJS analysis without using enableExperimental

### ISSUE THREAD

**Issue by Anshu2405** [dependency-check/DependencyCheck#2381]
Maven plugin is analyzing JavaScript files present inside Jar files even though we have not set enableExperimental property as true. 

Version: 5.2.4

Logs:
[[1;36mDEBUG[m] Initializing RetireJS Analyzer
[[1;36mDEBUG[m] Settings.getDataFile() - file: '/scratch/anssshar/MavenPlugin/DEVCS4.1_PROD/oscs'
[[1;36mDEBUG[m] Starting RetireJS Analyzer
[[1;36mDEBUG[m] Parallel processing with up to 2 threads: RetireJS Analyzer.
[[1;36mDEBUG[m] Begin Analysis of '/tmp/dctempd9a694ff-7ea5-4443-862f-d9a721de6f8a/check6106691534885933897tmp/38/org/apache/commons/validator/javascript/validateUtilities.js' (RetireJS Analyzer)
[[1;36mDEBUG[m] Begin Analysis of '/tmp/dctempd9a694ff-7ea5-4443-862f-d9a721de6f8a/check6106691534885933897tmp/38/org/apache/commons/validator/javascript/validateRequired.js' (RetireJS Analyzer)
[[1;36mDEBUG[m] Begin Analysis of '/tmp/dctempd9a694ff-7ea5-4443-862f-d9a721de6f8a/check6106691534885933897tmp/38/org/apache/commons/validator/javascript/validateInteger.js' (RetireJS Analyzer)
[[1;36mDEBUG[m] Begin Analysis of '/tmp/dctempd9a694ff-7ea5-4443-862f-d9a721de6f8a/check6106691534885933897tmp/38/org/apache/commons/validator/javascript/validateMask.js' (RetireJS Analyzer)
[[1;36mDEBUG[m] Begin Analysis of '/tmp/dctempd9a694ff-7ea5-4443-862f-d9a721de6f8a/check6106691534885933897tmp/38/org/apache/commons/validator/javascript/validateFloatRange.js' (RetireJS Analyzer)
[[1;36mDEBUG[m] Begin Analysis of '/tmp/dctempd9a694ff-7ea5-4443-862f-d9a721de6f8a/check6106691534885933897tmp/38/org/apache/commons/validator/javascript/validateDate.js' (RetireJS Analyzer)
[[1;36mDEBUG[m] Begin Analysis of '/tmp/dctempd9a694ff-7ea5-4443-862f-d9a721de6f8a/check6106691534885933897tmp/38/org/apache/commons/validator/javascript/validateMinLength.js' (RetireJS Analyzer)
[[1;36mDEBUG[m] Begin Analysis of '/tmp/dctempd9a694ff-7ea5-4443-862f-d9a721de6f8a/check6106691534885933897tmp/38/org/apache/commons/validator/javascript/validateMaxLength.js' (RetireJS Analyzer)
[[1;36mDEBUG[m] Begin Analysis of '/tmp/dctempd9a694ff-7ea5-4443-862f-d9a721de6f8a/check6106691534885933897tmp/38/org/apache/commons/validator/javascript/validateEmail.js' (RetireJS Analyzer)
[[1;36mDEBUG[m] Begin Analysis of '/tmp/dctempd9a694ff-7ea5-4443-862f-d9a721de6f8a/check6106691534885933897tmp/38/org/apache/commons/validator/javascript/validateIntRange.js' (RetireJS Analyzer)
[[1;36mDEBUG[m] Begin Analysis of '/tmp/dctempd9a694ff-7ea5-4443-862f-d9a721de6f8a/check6106691534885933897tmp/38/org/apache/commons/validator/javascript/validateCreditCard.js' (RetireJS Analyzer)
[[1;36mDEBUG[m] Begin Analysis of '/tmp/dctempd9a694ff-7ea5-4443-862f-d9a721de6f8a/check6106691534885933897tmp/38/org/apache/commons/validator/javascript/validateShort.js' (RetireJS Analyzer)
[[1;36mDEBUG[m] Begin Analysis of '/tmp/dctempd9a694ff-7ea5-4443-862f-d9a721de6f8a/check6106691534885933897tmp/38/org/apache/commons/validator/javascript/validateByte.js' (RetireJS Analyzer)
[[1;36mDEBUG[m] Begin Analysis of '/tmp/dctempd9a694ff-7ea5-4443-862f-d9a721de6f8a/check6106691534885933897tmp/38/org/apache/commons/validator/javascript/validateFloat.js' (RetireJS Analyzer)
[[1;34mINFO[m] Finished RetireJS Analyzer (0 seconds)

To Reproduce:

Add below dependency in pom.xml and run in debug mode.
	<dependency>
         <groupId>commons-validator</groupId>
         <artifactId>commons-validator</artifactId>
         <version>1.2.0</version>
	</dependency>

Expected behavior:
RetireJS Analyzer should be skipped as enableExperimental flag is set to false by default.

If this is the default behavior, then how we can disable RetireJS analysis in plugin.

**Comment by jeremylong** [comment]
The retire JS analyzer was promoted and is no longer considered experimental as of the 5.0.0 release.
