### ISSUE TITLE
Local NVD Mirror Usage

### ISSUE THREAD

**Issue by abdulahjamak-abh** [dependency-check/DependencyCheck#2383]
Hi, 
is the (maven) plugin set to use local NVD mirror just by specifying `<cveUrlModified>` to the url of _nvdcve-1.1-modified.json.gz_ and `<cveUrlBase>` to the url of the mirror + _nvdcve-1.1.-%d.json.gz_? Each time the analysis is started using `mvn dependency-check:check ` with the plugin set up in the build part of _pom.xml_ with `<failBuildOnCVSS>` set to _0_ **only one** _GET /nvdcve-1.1-modified.meta_ request is registered in the mirror server logs.

**Comment by jeremylong** [comment]
If the local database has been updated within the last 7 days - when you run ODC it will only download the modified version However, if you run it without an existing database it will download all of them.  If you have an existing database and execute an update beyond the 7 day window - it will download some/most of the files.

**Comment by abdulahjamak-abh** [comment]
Thank you!

**Comment by abdulahjamak-abh** [comment]
> If the local database has been updated within the last 7 days - when you run ODC it will only download the modified version However, if you run it without an existing database it will download all of them. If you have an existing database and execute an update beyond the 7 day window - it will download some/most of the files.

**Comment by abdulahjamak-abh** [comment]
Thank you!
