### ISSUE TITLE
v5 syntax

### ISSUE THREAD

**Issue by GeralltH** [dependency-check/DependencyCheck#2384]
Hi, 

we're using the dependency check v5.1.0 on a Jenkins multibranch pipeline. Since the update past v5.0.0 where there was a re-write, we can't find any documentation of the new syntax. We've seen "dependencyCheckAnalyzer" has gone to "dependencyCheck", but can't find any usage examples of it. We've tried to work it out ourselves but keep getting 

> [DependencyCheck] A Dependency-Check installation was not specified. Please configure the build and specify a Dependency-Check installation to use.

It seems someone else was having the same issue here: 
[https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/jenkinsci-users/GyNU7mckWNQ/dVUoFLf2FgAJ](url)

Is there any documentation for this, or can any be added? 

Thanks.

**Comment by stevespringett** [comment]
Per the [v5 migration wiki](https://github.com/jenkinsci/dependency-check-plugin/wiki/v5-Migration) the analyzer uses the CLI, so refer to the [CLI documentation](https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html). 

As for the Jenkins publisher documentation, there isn't any, never has been. But online help is available for non-pipeline jobs, and for pipeline jobs, Jenkins itself automatically produces the publisher documentation and has a snippet generator to generate the pipeline syntax automatically.

**Comment by GeralltH** [comment]
Solved the issue by not using it.
