### ISSUE TITLE
Some NPM vulnerabilities do not have hash information for the json output

### ISSUE THREAD

**Issue by adrielldagasuan** [dependency-check/DependencyCheck#2387]
**Describe the bug**
Missing sha1/md5 values for node dependencies in the json output. Weirdly enough, these values appear in the csv and html outputs.

** Version of dependency-check used **
5.2.4

** Log file **
Example of object with no sha1:
```
{ 
   "isVirtual":true,
   "fileName":"clean-css:2.2.16",
   "filePath":"D:\\path\\to\\clean-css\\file\\package-lock.json",
   "projectReferences":[  ],
   "evidenceCollected":{  },
   "vulnerabilities":[  ]
}
```
Record in csv output (which contains the hash):
`Project,"Mon, 16 Dec 2019 03:10:06 GMT",clean-css:2.2.16,D:\path\to\clean-css\file\package-lock.json,"","",8adb284e44ec758a1b0ff0a39bac266e,d07fbb7b0c8aa20fb52db8239ea55f817c2cad00,"","",785,"",Version of `clean-css` prior to 4.1.11 are vulnerable to Regular Expression Denial of Service (ReDoS). Untrusted input may cause catastrophic backtracking while matching regular expressions. This can cause the application to be unresponsive leading to Denial of Service.,NPM,"","","","","","","",3`

Example of object with a sha1:
```
{ 
   "isVirtual":false,
   "fileName":"hawk:1.0.0",
   "filePath":"D:\\path\\to\\hawk\\file\\package.json",
   "md5":"c345071e423284ad5743cdb3e4975950",
   "sha1":"f9ca4472b1f310ba11e82b7ac4c10d020aa8af74",
   "sha256":"cb90336e7d4bf3a0bad14090dec8c0b71c7129b17e2d228e674f8ea42c773ae7",
   "description":"HTTP Hawk Authentication Scheme",
   "projectReferences":[  ],
   "relatedDependencies":[  ],
   "evidenceCollected":{  },
   "packages":[  ],
   "vulnerabilities":[  ]
}
```
Record in csv output (which contains the hash):
`Project,"Mon, 16 Dec 2019 03:10:06 GMT",hawk:1.0.0,D:\path\to\hawk\file\package.json,HTTP Hawk Authentication Scheme,"",c345071e423284ad5743cdb3e4975950,f9ca4472b1f310ba11e82b7ac4c10d020aa8af74,pkg:npm/hawk@1.0.0,"",77,"","Versions of `hawk` prior to 3.1.3, or 4.x prior to 4.1.1 are affected by a regular expression denial of service vulnerability related to excessively long headers and URI's.",NPM,"","","","","","",HIGHEST,10`

**To Reproduce**
1.` mvn org.owasp:dependency-check-maven:aggregate` on a project with node dependencies

**Expected behavior**
The json output should contain the information as it contains most of the information, including suppressed vulnerabilities.

**Additional context**
The HTML output also contains the hash information.

**Comment by jeremylong** [comment]
The actual bug is that in these cases I do not believe a SHA1 should be being displayed in the CSV report - as it is not the real SHA1 for the module.

**Comment by adrielldagasuan** [comment]
Does that mean then that the correct report is the one produced in the JSON output?

**Comment by jeremylong** [comment]
yes
