### ISSUE TITLE
Consider using native Ant logging instead of java.util.logging

### ISSUE THREAD

**Issue by awood** [dependency-check/DependencyCheck#239]
I'm using the Dependency Check ant task, but using it from Ruby via the [Apache Buildr](http://buildr.apache.org) too.  I parse the generated XML to display the results to users and therefore want to suppress the output from the Ant task.  Since the ant task is using java.util.logging directly I don't really have a way to suppress the output.  If it were using [Ant's native logging functionality](http://javadoc.haefelinger.it/org.apache.ant/1.8.1/org/apache/tools/ant/Task.html#log%28java.lang.String%29) then I could access the Ant BuildListener and suppress or redirect the output to /dev/null.

If this sounds like something you would be interested in, I would be happy to write the code and provide a pull request.

**Comment by jeremylong** [comment]
This is planned as part of the fix for issue #164.  I will try to include
this in the next major point release (1.3).

In addition to ant logging for the ant task I plan on also using maven
logging for the maven plugin, etc.

--jeremy

**Comment by jeremylong** [comment]
While some tweaks may still occur - the base adapter for ant has been committed to 1.2.12-SNAPSHOT and will be included in the next release.
