### ISSUE TITLE
DependencyCheck report mismatch Yarn audit

### ISSUE THREAD

**Issue by ibakayoko** [dependency-check/DependencyCheck#2393]
**Dependency check version**
Dependency-Check Core version 5.2.4

 **package.json**
{
  "dependencies": {
    "axios": "0.18.0",
    "foreman": "2.0.0",
    "graphql-code-generator": "0.5.5",
    "html-webpack-plugin": "3.2.0",
    "newrelic": "4.1.4"
  }
}

**Yarn Audit**
Mac-C:test-dependency-check ib$ **yarn audit**
yarn audit v1.16.0
warning package.json: No license field
warning No license field
....
4 vulnerabilities found - Packages audited: 252
Severity: 1 Moderate | 2 High | 1 Critical
✨  Done in 0.62s.

**Dependency Check Report**
Mac-C:test-dependency-check ixb$ dependency-check -f ALL -s .
[INFO] Checking for updates
[INFO] Skipping NVD check since last check was within 4 hours.
[INFO] Skipping RetireJS update since last update was within 24 hours.
[INFO] Check for updates complete (8 ms)
[INFO] 

Dependency-Check is an open source tool performing a best effort analysis of 3rd party 

[INFO] Analysis Started
[INFO] Finished File Name Analyzer (0 seconds)
[INFO] Finished Dependency Merging Analyzer (2 seconds)
[INFO] Finished Version Filter Analyzer (0 seconds)
[INFO] Finished Hint Analyzer (0 seconds)
[INFO] Created CPE Index (2 seconds)
[INFO] Finished CPE Analyzer (2 seconds)
[INFO] Finished False Positive Analyzer (0 seconds)
[INFO] Finished NVD CVE Analyzer (0 seconds)
[INFO] Finished RetireJS Analyzer (3 seconds)
[WARN] Unable to determine Package-URL identifiers for 2712 dependencies
[INFO] Finished Sonatype OSS Index Analyzer (0 seconds)
[INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
[INFO] Finished Dependency Bundling Analyzer (1 seconds)
[INFO] Analysis Complete (9 seconds)

**Report**
dependency-check version: 5.2.4
Report Generated On: Wed, 18 Dec 2019 16:14:38 -0500
Dependencies Scanned: 3258 (2712 unique)
Vulnerable Dependencies: 0
Vulnerabilities Found: 0
Vulnerabilities Suppressed: 0
NVD CVE Checked: 2019-12-18T13:51:25
NVD CVE Modified: 2019-12-18T12:06:51
VersionCheckOn: 2019-12-10T13:10:18

====
Thanks for helping us understand why we have the mismatch

**Comment by jeremylong** [comment]
For dependency-check to work - you need to have a package-lock.json or npm-shrinkwrap.json file present.   ODC does not support yarn.lock files.

**Comment by sarod** [comment]
FYI #1416 requests support for yarn
