### ISSUE TITLE
Jenkins 2.176.2 plugin version 5.1.0 Could not find or load main class 'self

### ISSUE THREAD

**Issue by bainss** [dependency-check/DependencyCheck#2399]
**Describe the bug**
If I install the dependency-check plugin and  using a freestyle pipeline (running on the jenkins master) with a build step as follows.

invoke dependency-check

`--scan /var/jenkins_home/owasp/global --format XML`

I have a stage that calls the dependency-check as part of my multibranch pipeline...

` podTemplate(label: 'jnlp') {
        node('jnlp') {
            container('gradle') {

                checkout scm
                 try {
                utils.printColour("OWASP: about to call OWASP Dependency Checker ${targetBranch}", 'green')
                sh('mkdir -p build/owasp')
                dependencyCheck additionalArguments: '''--scan ./
                                --format XML
                                --out build/owasp/dependency-check-report.xml
                                ''', odcInstallation: '5.1.0'
                } catch (err) {
                    error("OWASP failed: " + artifactId + err.message)

                } finally {

                dependencyCheckPublisher pattern: 'build/owasp/dependency-check-report.xml'
                }
                cleanWs()
            }
        }
    }`
this works as exoected  but I want to run on the jenkins master so I can cache the NVD and the stage in my sourcecode pipelines use the cache

so I would use 

`
        node('master') {

                checkout scm
                 try {
                utils.printColour("OWASP: about to call OWASP Dependency Checker ${targetBranch}", 'green')
                sh('mkdir -p build/owasp')
                dependencyCheck additionalArguments: '''--scan ./
                                --format XML
                                --out build/owasp/dependency-check-report.xml
                                ''', odcInstallation: '5.1.0'
                } catch (err) {
                    error("OWASP failed: " + artifactId + err.message)

                } finally {

                dependencyCheckPublisher pattern: 'build/owasp/dependency-check-report.xml'
                }
                cleanWs()
    }`

If I set like this.. I get the following in my logs..

[2019-12-28T18:36:32.885Z] Unpacking https://dl.bintray.com/jeremy-long/owasp/dependency-check-5.2.4-release.zip to /var/jenkins_home/tools/org.jenkinsci.plugins.DependencyCheck.tools.DependencyCheckInstallation/5.2.4 on Jenkins

[2019-12-28T18:36:33.799Z] [DependencyCheck] Error: Could not find or load main class 'self';

** Version of dependency-check used **

version 5.1.0 ÷

** Log file **
[gist](https://gist.github.com/bainss/20345ee524d90d9e3b4a24356a3e0411) 

**To Reproduce**

**Expected behavior**

**Additional context**
Running as SYSTEM
Building in workspace /var/jenkins_home/workspace/exp-nvd-updater
[DependencyCheck] Error: Could not find or load main class 'self';
Build step 'Invoke Dependency-Check' changed build result to FAILURE
Finished: FAILURE

**Comment by stevespringett** [comment]
The Jenkins plugin is simply a wrapper around the CLI. The CLI is stating that it cannot load the main class.

Glancing at the gist, it appears there may be a platform mismatch. The odcInstallation appears to be a typical *nix path, but the job is running as SYSTEM (the highest-privilege Windows account). The master node is likely Windows whereas the worker nodes are likely Linux.

I think the fix would be to simply create an odcInstallation specific to Windows so that the master node can find and execute it.
