### ISSUE TITLE
H2 Server Mode --> Substring fileName / Simple DbUser

### ISSUE THREAD

**Issue by kaimago** [dependency-check/DependencyCheck#240]
Hi,

i setup the dependency checker with H2 in server mode.
For the client I setup a connectionString like this "jdbc:h2:tcp://localhost/%s"
Because it is a tcp connection the filename isn't substringed.

if (connStr.startsWith("jdbc:h2:file:") && fileName.endsWith(".h2.db")) {
                fileName = fileName.substring(0, fileName.length() - 6);
}

Can you change the code to something like this ?

if ((connStr.startsWith("jdbc:h2:file:") || connStr.startsWith("jdbc:h2:tcp:"))
  && fileName.endsWith(".h2.db")) {
                fileName = fileName.substring(0, fileName.length() - 6);
}

Besides it would be helpfull when the dependencyChecker has a default db-user with only rights to read.

Best Regards
Kai

**Comment by jeremylong** [comment]
If you are running H2 in server mode, there should be no reason to include the %s (which injects the version number of the database schema as the file name). If you've named the database 2.9 then just specify the full URI: jdbc:h2:tcp://localhost/2.9

Feel free to reopen this ticket or post to the user group if you have more questions or comments.

Regards,

Jeremy

**Comment by kaimago** [comment]
Hi Jeremy,

in my opionen %s would be also helpfull for server mode. (you don't have to care about version und filename). 
But you are right is no big deal to do it an other way.

Anyway i switched to H2 MixedMode, so I don't have this issue anymore.

Thanks & Regards
Kai
