### ISSUE TITLE
Java version required to build

### ISSUE THREAD

**Issue by JStyle21** [dependency-check/DependencyCheck#2402]
Hi,

I'm trying to build the project based on the instructions (yes i know releases exist but i need to build)
My java is OpenJDK 11 which is required by another project i think (i didn't install it manually for sure)
I'm getting the following error on utils:
```

encycheck/utils/ExpectedObjectInputStream.java:[20,15] cannot access java.io.IOException
[ERROR]   bad class file: /modules/java.base/java/io/IOException.class
[ERROR]     class file has wrong version 55.0, should be 53.0
```

I'm using Ubuntu for this and currently the other java version is 8 so i tried switching and this error disappeared while another appeared at the same utils...

Now i'm wondering since i checked the project pom and it mentioned java 1.7 while the class version is assumes is 53 which is java 9.
I'm really confused which java is needed and why wasn't it added to the dependencies.

Please suggest, thanks.

**Comment by jeremylong** [comment]
We use JDK 8 to build - one of the downfalls of maintaining a library like this is we need to stay at the lowest common denominator.  You can see this in both the pom and travis.yml:

https://github.com/jeremylong/DependencyCheck/blob/1dd037fa5ccfb3145817c9d5aec3263a5b2145c4/pom.xml#L433-L434


https://github.com/jeremylong/DependencyCheck/blob/1dd037fa5ccfb3145817c9d5aec3263a5b2145c4/.travis.yml#L35

**Comment by JStyle21** [comment]
Thanks for replying however it seems i need JDK11 for other projects and since you use maven and not gradle it's a bit annoying to control the compiler (no IDE), i did stumble on the following
http://maven.apache.org/plugins/maven-compiler-plugin/examples/compile-using-different-jdk.html

I've tried adding it to the settings and pom files but it doesn't seems to pick it up, any idea why?

**Comment by JStyle21** [comment]
I manged to go through that problem by setting JAVA_HOME to 1.8's path but now it fails on another issue
`
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.22.2:verify (default) on project dependency-check-core: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/user/projects/dependencyCheck/core/target/failsafe-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.22.2:verify (default) on project dependency-check-core: There are test failures.

Please refer to /home/user/projects/dependencyCheck/core/target/failsafe-reports for the individual test results.
Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.

`

**Comment by JStyle21** [comment]
It failed on
`
https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2020.meta; received 404 -- resource not found
`
which i then changed to
`
https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-recent.json.gz
`
in settings.xml then it failed on

`
[ERROR] Failures: 
[ERROR]   CPEAnalyzerIT.testAnalyzeDependency:308->callAnalyzeDependency:345 jrebel:zt-zip:1.0 identifier not found
[ERROR]   CPEAnalyzerIT.testDetermineIdentifiers:259->callDetermieIdentifiers:287 jrebel:zt-zip:1.0 identifier not found
[ERROR] Errors: 
[ERROR]   EngineModeIT.testEvidenceCollectionAndEvidenceProcessingModes:100 » ExceptionCollection
[ERROR]   EngineModeIT.testStandaloneMode:116 » ExceptionCollection One or more exceptio...

`

**Comment by jeremylong** [comment]
Try something like:
```
git clone --branch 'v5.2.4' --depth 1 https://github.com/jeremylong/DependencyCheck.git
cd DependencyCheck
docker run -it --rm --name dependency-check -v "$(pwd)":/usr/src/mymaven -w /usr/src/mymaven maven:3.6.3-jdk-8-slim mvn -s settings.xml clean install -DskipTests=true
```

Note - the above is skipping the test cases.  To get this to work for 5.2.4 with the test cases you would have to wait until the NVD publishes the 2020 JSON files and you would have to extend the docker container `maven:3.6.3-jdk-8-slim` to include `Go`.

**Comment by JStyle21** [comment]
Thanks that worked :)

Quick question on the note, i've seen that you pushed some new commits based on this i wonder why did the docker version had to use skip tests while the regularly cloned version (including the new commits) didn't have a problem running the tests?

Also what is up with the NVD date dependency? why not take recent instead of next year's?

**Comment by jeremylong** [comment]
Updated commits fix an issue with the NVD not having published a 2020 JSON data feed yet.

**Comment by JStyle21** [comment]
That wasn't exactly what i've asked but i got your point and after checking the code i think i understand the answers i was looking for and how you use NVD.

Just a quick side note (i hope you don't find this annoying)
Going through the code i ended up in the properties file, btw the only reason this is a question and not a pull request is that i don't know how the project works inside out so i thought i'd ask.

```
#the original URL and modified URL should be the same; this is used to detect if we are using an internal NVD CVE copy
cve.url.original=https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.json.gz
cve.url.modified=https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.json.gz
cve.url.base=https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-%d.json.gz
cve.cpe.startswith.filter=cpe:2.3:a:

max.download.threads=2
# the path to the modified nvd cve xml file.
cve.url-1.2.modified=https://nvd.nist.gov/feeds/xml/cve/1.2/nvdcve-modified.xml.gz
#cve.url-1.2.modified=http://nvd.nist.gov/download/nvdcve-modified.xml
#the original URL and modified URL should be the same; this is used to detect if we are using an internal NVD CVE copy
cve.url-2.0.original=https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-Modified.xml.gz
cve.url-2.0.modified=https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-Modified.xml.gz
#cve.url-2.0.modified=http://static.nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-modified.xml
cve.url-1.2.base=https://nvd.nist.gov/feeds/xml/cve/1.2/nvdcve-%d.xml.gz
#cve.url-1.2.base=http://nvd.nist.gov/download/nvdcve-%d.xml
cve.url-2.0.base=https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-%d.xml.gz
#cve.url-2.0.base=http://static.nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-%d.xml

```

1. I can understand the modified version and how it compares the delta against the original but why do you need cve.url.original? i couldn't find it being used anywhere in the code and the comment isn't clear what is an internal NVD copy?
2. Not sure why do need so many versions of the NVD feeds but it seems NVD retired the XML feeds so all those URL's are broken now
https://nvd.nist.gov/General/News/XML-Vulnerability-Feed-Retirement
i would only update CPE to JSON and remove the duplicates apart from the base and modified

**Comment by jeremylong** [comment]
Most of those URLs were just old code that needed to be removed.  Regarding the `original` value - that is used in one place to determine if an internal NVD mirror is being used. If it is, the check for a new version of ODC is disabled.
