### ISSUE TITLE
NET Assembly analyser Linux

### ISSUE THREAD

**Issue by JStyle21** [dependency-check/DependencyCheck#2404]
Hi,

Does NET Assembly analyser run on linux? i have dotnet core installed but DependencyCheck doesn't pick it up...

```
dotnet --version
3.1.100
```

I've also read https://github.com/jeremylong/DependencyCheck/issues/1464
and tried with v2 but it still didn't pick it up

**Comment by jeremylong** [comment]
Have you tried adding `--dotnet <path>` to tell ODC where the executable is?

**Comment by JStyle21** [comment]
I did, i tried to point it to both the SDK's paths, i tried with both runtime's as well.
What path does it expect to have? the only example i saw had a .exe extension but this is linux so that was part of the reason for asking.

**Comment by vdotjansen** [comment]
Could you check what happens when you pass the following parameter: -Danalyzer.assembly.dotnet.path=/usr/bin/dotnet (to the correct dotnet path).

**Comment by jeremylong** [comment]
@JStyle21 try adding the `--log odc.log` and reviewing this for clues as to what is going on.

**Comment by JStyle21** [comment]
Thanks @vdotjansen  and @jeremylong 
The log file helped understand the situation, i used the wrong path :(
Now it works, although as mentioned in #1464 it only works with the 2.2 runtime and not with the 3.1
