### ISSUE TITLE
Can we use dependency check plugin to only analyze the dependencies contained in the jar

### ISSUE THREAD

**Issue by IshwaryaMullaiSelvapandian** [dependency-check/DependencyCheck#2406]
I am running dependency check plugin from the command line as "mvn verify org.owasp:dependency-check-maven:5.2.4:check" to generate a CVE report.

I am only concerned with CVEs that show in the jars that are deployed.
but I think the dependency check plugin analyzes everything in the pom and doesn't look at the jar.

Is it possible to use dependency check plugin in a way, it only analyzes the dependencies contained in the jar?

**Comment by mprins** [comment]
You can specify to skip certain scopes using any of `skipProvidedScope...skipTestScope` see https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html or you can use the commandline version to point to your jar file
