### ISSUE TITLE
failOnError for CLI 

### ISSUE THREAD

**Issue by jpeterso** [dependency-check/DependencyCheck#2409]
I am using the CLI version of DC (5.2.1) and would like to implement the failOnError=false option when passing in parameters. But that doesn't seem to exist in the CLI version. Seems to be there for the Ant/Maven modules. Can this option be turned on when using the CLI?

**Comment by jeremylong** [comment]
This already is done by default. You can check the return code like this:

```bash
dependency-check.sh -s . -o .
if [ $? -eq 0 ]; then
    echo OK
else
    echo FAIL
fi
```

**Comment by togurosec** [comment]
@jeremylong, if I want to use failOnError=true option in parameters, there is a way in the CLI version?

**Comment by jeremylong** [comment]
The CLI already returns a non-zero value if it fails. There is no need to add a parameter - you just need to check the return code of the command.
