### ISSUE TITLE
File-resource leak in RetireJsAnalyzer

### ISSUE THREAD

**Issue by Vampire** [dependency-check/DependencyCheck#2414]
**Describe the bug**
Due to whatever reason - which is not the topic here - dependency-check checks the jmockit.jar.
After extracting it, there are two JavaScript files.
After the `RetireJsAnalyzer` did its work, those files are locked and cannot be deleted, which then causes an error in `ArchiveAnalyzer#closeAnalyzer` as it cannot delete the files.
I think the error is in `RetireJsAnalyzer#analyzeDependency` in the line `final byte[] fileContent = IOUtils.toByteArray(new FileInputStream(dependency.getActualFile()));`, as the `FileInputStream` never gets closed.
After I injected a `close()` call using debugger evaluations, this does not happen and the files can properly be deleted.

**Version of dependency-check used**
The problem occurs using version 5.2.4 of the gradle plugin

**Comment by jeremylong** [comment]
This has been fixed and will be included in the 5.3.0 release. We are now wrapping the FileInputStream in a try with resources:

https://github.com/jeremylong/DependencyCheck/blob/d169ea7d0d0f48e90bcbd06ee94d96b4620203bd/core/src/main/java/org/owasp/dependencycheck/analyzer/RetireJsAnalyzer.java#L254
