### ISSUE TITLE
How set local "RetireJS repo" ?

### ISSUE THREAD

**Issue by patsevanton** [dependency-check/DependencyCheck#2424]
I use DependencyCheck without internet.
I download nist-data.
But how set local "RetireJS repo" ?

**Comment by jeremylong** [comment]
Please take a look at the [documentation site](https://jeremylong.github.io/DependencyCheck/). Depending on which implementation you are using this varies (i.e. CLI vs Maven vs ...). The CLI argument would be `--retireJsUrl <url>`.

**Comment by patsevanton** [comment]
Thanks!
But i dont find `--retireJsUrl <url>` in [documentation site](https://jeremylong.github.io/DependencyCheck/)

**Comment by jeremylong** [comment]
[documentation site](https://jeremylong.github.io/DependencyCheck/) -> [Command Line Tool](https://jeremylong.github.io/DependencyCheck/dependency-check-cli/index.html) -> [Configuration](https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html).
