### ISSUE TITLE
Extracting Vulnerabilities from JSON report

### ISSUE THREAD

**Issue by JStyle21** [dependency-check/DependencyCheck#2432]
Hi,

I'm interested in getting vulnerabilities only and as far i've seen they contain the component name in the description field, i just wanted to ask if there is a better approach than parsing the JSON file and extracting the vulnerabilities via the values?

Thanks

**Comment by jeremylong** [comment]
You could use the CSV report format and just delete the fields you don't want.

**Comment by JStyle21** [comment]
That's not a bad idea but i meant programmatically, that's why i thought JSON would be easier to work with.

**Comment by jeremylong** [comment]
CSV files can be loaded programmatically:

python: https://docs.python.org/3/library/csv.html
java: https://commons.apache.org/proper/commons-csv/
etc.

**Comment by JStyle21** [comment]
Thanks!
