### ISSUE TITLE
Analysis faillure

### ISSUE THREAD

**Issue by Brasco** [dependency-check/DependencyCheck#2438]
After the update to the new version I am not able to analyze certain projects with the maven plugin

The problem occurs using version 5.3.0 of the maven plugin (on mvn 3.6.2)

**Log file**
```
[ERROR] Failed to execute goal org.owasp:dependency-check-maven:5.3.0:check (exec2) on project PROJECT1: One or more exceptions occurred during dependency-check analysis: One or more exceptions occurred during analysis:                                                                        
[ERROR]         org.glassfish.json.JsonStringImpl cannot be cast to javax.json.JsonObject             
[ERROR] -> [Help 1]                                                                                   
[ERROR]
```

**Comment by jeremylong** [comment]
I'm not able to re-produce this issue.  What version of Maven are you using (`mvn --version`)? I just tested this with 3.3.9 and 3.6.1.

**Comment by Brasco** [comment]
In fact I am using the 3.6.2. I have noticed that the second error  (now removed from the bug description) is not due to your plugin, it is simply a dependency missing from the developers. Instead the first error message happen since the upgrade to the new version of owasp-dependency-check plugins.
Thank you a lot.
Let me know if can help you.
