### ISSUE TITLE
unable to generate CPE index for very old jars after updating to 5.3.0

### ISSUE THREAD

**Issue by sellersj** [dependency-check/DependencyCheck#2440]
**Describe the bug**
For a very old jakarta jar, it fails to create a "Created CPE Index".

**Version of dependency-check used**
5.3.0 of the maven plugin

**Log file**
[INFO] Created CPE Index (1 seconds)
[WARNING] An error occurred while analyzing '/Users/sellersj/.m2/repository/taglibs/taglibs-unstandard/20060829/taglibs-unstandard-20060829.jar' (CPE Analyzer).
...
[ERROR] Failed to execute goal org.owasp:dependency-check-maven:5.3.0:check (default-cli) on project dependency-check-530-update: One or more exceptions occurred during dependency-check analysis: One or more exceptions occurred during analysis:
[ERROR] 	Unable to create a CPE for apache:standard_taglibs:-
[ERROR] -> [Help 1]

**To Reproduce**
I've created an example project
1. Clone https://github.com/sellersj/dependency-check-530-update
2. Run the command in the readme
3. See the error that's in the readme.

**Expected behavior**
This has worked up to now, including in 5.2.4

**Additional context**
The groupId / artifactId I found this issue on was slightly different, but I believe that it is the same jar.
This could be related to #2438

**Comment by jeremylong** [comment]
The logic was updated to account for the version number of `20060829`.  The fix will be included in the next release. Thanks for the bug report!
