### ISSUE TITLE
Database server redownloads all 

### ISSUE THREAD

**Issue by marky-mark** [dependency-check/DependencyCheck#2443]
**Describe the bug**
We followed the example on https://jeremylong.github.io/DependencyCheck/data/database.html.
This worked fine and we can see the data inside the mysql dependencycheck database. We could also see dependency check updates skipping over when there are no more items to download.
Today we discover that the dependency check updates are ignoring what is in the database and redownloading everything.
On observation we see the metadata timestamp has changed to the 22nd (today), e.g. https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2004.meta.

**Version of dependency-check used**
The problem occurs using version 5.3.0 of the maven plugin

**Log file**
[here](https://gist.github.com/marky-mark/a37b6df358a52d3f7b4239a8a90d807e) 

**To Reproduce**
1. Data was loaded from a few weeks ago
2. Update the database 

**Expected behavior**
Expected to skip over the updates in the database.

**Additional context**
None

**Comment by marky-mark** [comment]
Looking at [nvd vulnerabilities section](https://nvd.nist.gov/vuln)

Modified -> CVE has been amended by a source (CVE Primary CNA or another CNA). Analysis data supplied by the NVD may be no longer be accurate due to these changes.

I believe there must have been an error with the vulnerabilities and requires all to be redownloaded for accuracy.

**Comment by jeremylong** [comment]
Also, if it was more than 7 days since the last successful update - ODC might re-download most if not all of the JSON files.

**Comment by marky-mark** [comment]
Thanks for the update
