### ISSUE TITLE
"[ERROR] Missing package.lock or npm-shrinkwrap.lock file" since few days

### ISSUE THREAD

**Issue by nzin-appdirect** [dependency-check/DependencyCheck#2445]
**Describe the bug**
A new version of dependency-check fails when a package-lock is not present
We have some repositories that have a package.json, but no package-lock.json.
if it is the case, since few days, we have this error message (I guess it is linked to this new commit https://github.com/jeremylong/DependencyCheck/blame/master/core/src/main/java/org/owasp/dependencycheck/analyzer/NodePackageAnalyzer.java#L130)

```
[ERROR] Exception occurred initializing Node.js Package Analyzer.
[ERROR] Missing package.lock or npm-shrinkwrap.lock file: Unable to scan a node project without a package-lock.json or npm-shrinkwrap.json.
```
I am aware of this discussion: https://github.com/jeremylong/DependencyCheck/issues/2337

but we think it shouldn't fail, i.e.if it misses the package.lock then it takes the latest version supported by the package.json

**Version of dependency-check used**
The problem occurs using version 5.2.4 of the cli (in a docker image)

Also we use dependency-check with some options:
```
/usr/share/dependency-check/bin/dependency-check.sh --enableExperimental --disableRetireJS --disableOssIndex --disableCentral --scan ${env.WORKSPACE} --noupdate --format ALL
```

**Log file**
```
+ /usr/share/dependency-check/bin/dependency-check.sh --enableExperimental --disableRetireJS --disableOssIndex --disableCentral --scan /var/jenkins/workspace/service-pipeline_PR-108 --noupdate --format ALL --out /var/jenkins/workspace/service-pipeline_PR-108/report
[INFO] 

Dependency-Check is an open source tool performing a best effort analysis of 3rd party dependencies; false positives and false negatives may exist in the analysis performed by the tool. Use of the tool and the reporting provided constitutes acceptance for use in an AS IS condition, and there are NO warranties, implied or otherwise, with regard to the analysis or its use. Any use of the tool and the reporting provided is at the user’s risk. In no event shall the copyright holder or OWASP be held liable for any damages whatsoever arising out of or in connection with the use of this tool, the analysis performed, or the resulting report.


[INFO] Analysis Started
[INFO] Finished File Name Analyzer (0 seconds)
[ERROR] Exception occurred initializing Node.js Package Analyzer.
[INFO] Finished Dependency Merging Analyzer (0 seconds)
[INFO] Finished Version Filter Analyzer (0 seconds)
[INFO] Finished Hint Analyzer (0 seconds)
[INFO] Created CPE Index (2 seconds)
[INFO] Finished NPM CPE Analyzer (2 seconds)
[INFO] Created CPE Index (1 seconds)
[INFO] Finished CPE Analyzer (1 seconds)
[INFO] Finished False Positive Analyzer (0 seconds)
[INFO] Finished NVD CVE Analyzer (0 seconds)
[INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
[INFO] Finished Dependency Bundling Analyzer (0 seconds)
[INFO] Analysis Complete (3 seconds)
[ERROR] Missing package.lock or npm-shrinkwrap.lock file: Unable to scan a node project without a package-lock.json or npm-shrinkwrap.json.
script returned exit code 242
```

**To Reproduce**
not sure how to reproduce outside, except running with the same args with no package-lock.json

**Expected behavior**
it shouldn't exit with an error, but should try to scan with latest version

**Comment by mprins** [comment]
please try with the current release [5.3.0] to see if this problem persists, some things were reworked for the node scanner

**Comment by nzin-appdirect** [comment]
> please try with the current release [5.3.0] to see if this problem persists, some things were reworked for the node scanner

cool, I will!

**Comment by jeremylong** [comment]
This is expected behavior and there is no intention to resolve this issue.  If you do not have a `package-lock.json` or `npm-shrinkwrap.json` file present `npm audit` will also fail.

**Comment by nzin-appdirect** [comment]
If someone else comes across this ticket, in fact when using "--disableOssIndex" I have this issue, when I dont specify "--disableOssIndex" I dont have the issue. (which can be problematic when you include a java dependency that contains a package.json without a package-lock.json)

**Comment by anacantor** [comment]
Bom dia, desculpe, eu estou presentando um problema... Erro 0x800f0831 para instalar o Hyper -V de Microsoft que eu preciso para o docker de VSC, algum me poderia por gentileza disser que eu posso fazer, ya que por os process normais não me deixa. Obrigada
