### ISSUE TITLE
If local NVD data Mirror is down for instance, how to access NIST through internet

### ISSUE THREAD

**Issue by ajayveluru1981** [dependency-check/DependencyCheck#2447]
I have configured NVD data mirror in Kubernetes. I am accessing it from POM xml of Maven Java project. I am using <cveUrlBase> and <cveUrlModified> tags in order to do this. It is working fine.

My question is that what is local data mirror does not available for instance, how can i reach out to NIST through internet? Can someone help me in this regard? Thank you in advance.

**Comment by jeremylong** [comment]
Remove the configuration to use the local data mirror. The defaults will kick in and pull the JSON files from NIST.

**Comment by ajayveluru1981** [comment]
Thank you @jeremylong. But here i am looking for this solution.
1. My project always look at local data mirror which is configured in kubernetes.
2. For instance, if it fails, how to connect to internet with out changing the pom xml. 

I am looking here kind of if else condition. Can we redirect to internet when local data mirror fails. Do we have any configuration properties to do this?

As per my understanding, currently we have only one option, either connect to internet or connect to local data mirror. If one of these fails, how to switch to other mode with out failing the build.

Could you please throe some light here.

**Comment by jeremylong** [comment]
Consider using the CLI to download the data from your local mirror into the
data directory. Check for a failure in the script and if it failed try the
NVD.  There is nothing in ODC that will do this for you - but a script
would be a simple solution.

--Jeremy
