### ISSUE TITLE
How to check vulnerabilities related with the web application server running?

### ISSUE THREAD

**Issue by willpowerforever** [dependency-check/DependencyCheck#245]
Dear All,

The tool looks great to me. But I found it is not able to detect the vulnerability related with the application server the application running. Or is there anyway for us to extend it? Since the application server version is relatively unchanged for long time. I am thinking if we can put the version information somewhere so DependencyCheck will be able to see it and check its known vulnerabilities.

Thanks!
Will

**Comment by willpowerforever** [comment]
I found I can actually add a PlatformAnalyzer and basically add all platform technologies to a file for instance, let says .plt. Then I can have the Engine check them.

**Comment by jeremylong** [comment]
That would be one way to accomplish this. You could also utilize [OWASP Dependency-Track](https://www.owasp.org/index.php/OWASP_Dependency_Track_Project).

--Jeremy
