### ISSUE TITLE
Docker scan script doesn't scan current folder

### ISSUE THREAD

**Issue by hashier** [dependency-check/DependencyCheck#2451]
**Describe the bug**

The Docker-linux-script from the readme, doesn't scan the source code in the current folder.

**Version of dependency-check used**
HEAD (12a3a16b04e69080b2e85be86408e533aff851a8)

**To Reproduce**
1. Go to any source folder locally
2. Use the linux docker script from the readme
3. run it

**Expected behavior**
Scanning of the source code in the current directory

** Actualy behavior**
Nothing gets scanned

**Comment by jeremylong** [comment]
Thanks for the PR!
