### ISSUE TITLE
package-lock.json inside war not processed using CLI

### ISSUE THREAD

**Issue by chriseins** [dependency-check/DependencyCheck#2454]
**Describe the bug**
I packed a package-lock.json inside a war file and used the CLI to scan it. Some warnings about none existing node_modules directories appeared on the console which I thought could be ignored. However the generated report does not contain the js vulnerabilities.
The behavior seems to be different for directories. I unzipped my war file into a directory and scanned it again. Vulnerabilities are listed in the generated reports. 

**Version of dependency-check used**
The problem occurs using version 5.2.5 of the cli

**Log file**
Console output using a war file:
https://gist.github.com/chriseins/fcff8f12a073e9dc4b1847f28fe32b7e

Console output using a folder:
https://gist.github.com/chriseins/f0c51a72ec95ad4c20bf492ff0fa0798

**To Reproduce**
1. Create a war file with a package-lock.json containing a vulnerabilities at root level. I used this package-lock.json: https://gist.github.com/chriseins/68afa8f7db1b36715532fa2c60a6456a
2. scan the war file

**Expected behavior**
No difference between scanning a war file or a directory

**Comment by jeremylong** [comment]
Unfortunately, we can't scan a package-lock.json file buried in a WAR.  The current node analyzers only work on an actual node project that contains at a minimum a package.json and package-lock.json and preferably with the node_modules installed.
