### ISSUE TITLE
jenkins plugin: support default additionalArguments

### ISSUE THREAD

**Issue by valentijnscholten** [dependency-check/DependencyCheck#2459]
**Usecase**
In a larger Jenkins install, I would like to centralize/customize the OCD NVD database location specify and leave the updating of the database to a specific (nightly) jenkins job.
This is to avoid throttling/banning by the NVD server, as well as to avoid locking issues with concurrent builds.

**Problem:**

Currently in v5 every job has to specify these parameters in the pipeline:

`--data /var/lib/jenkins/nvd-database --noupdate`

Problems is that some people forget this or don't do this. It's also a lot of maintenance when the data dir changes.
Especially with having 100s of Jenkinsfile to update acros 100s of git repositories :-)

**Suggested solution:**

Allow configuration of a set of default `additionalArguments` that are automatically used by every Jenkins job.

So specify globally or per OCD:

`--data /var/lib/jenkins/nvd-database --noupdate`

**Possible alternative:**

Allow a environment variable to be configure the data dir and/or update flag and have these picked up by `dependency-check.sh/bat`

 I have considered writing a wrapper function, but the downside for that is that the wrapper will not be visible in the Pipeline Syntax helper in Jenkins.

**Comment by stevespringett** [comment]
Global configurations use to be implemented. They caused the opposite problem in that sometimes you wanted a job not to use global config or slightly different config. Having the ability to override global configs, etc, introduced a lot of unnecessary complexity in both configuration and in the maintenance of the Jenkins plugin code base. Global configs were removed in v5.

For a Jenkins-specific solution, I would recommend creating a Jenkins shared library which could be globally accessible, reusable, and overridable. If that doesn't work, then I would recommend exploring environment variables as a possible solution.
