### ISSUE TITLE
Javascript check doesn't work

### ISSUE THREAD

**Issue by willpowerforever** [dependency-check/DependencyCheck#246]
Hi Guys,

I tried the javascript scan. It seems doesn't do the check. Then, I took a look at the JavaScriptAnalyzer source and found the implementation actually is not complete. The pattern for the information collection is never used. Does it mean you are still working on it?

Thanks!
Will

**Comment by jeremylong** [comment]
The javascript analyzer was started - but never completed. If you would like to check the JavaScript libraries used by your application I would highly recommend looking at the Retire.js project listed in the [Related Work](https://jeremylong.github.io/DependencyCheck/related.html).

As Retire.js is available and there are other things to work on with dependency-check the work on the JavaScript analyzer has been postponed.

--Jeremy
