### ISSUE TITLE
not  able to scan the  python code, its  shows  0 dependencies

### ISSUE THREAD

**Issue by szemmour-rh** [dependency-check/DependencyCheck#2461]
i'm trying  to scan the python  dependency but  it  shows nothing.

the  testing  python code  is :  https://github.com/jhermann/dependency-check-py.git

i'm using  the docker image

i'v tried  with  /src/**  and  it  didn't work

i'v added  :   --enableExperimental   and  still not  able to detect  the dependencies

the  html report  shows  :
Project: app
Scan Information (show less):

    dependency-check version: 5.2.4
    Report Generated On: Tue, 4 Feb 2020 17:29:22 -0500
    Dependencies Scanned: 0 (0 unique)
    Vulnerable Dependencies: 0
    Vulnerabilities Found: 0
    Vulnerabilities Suppressed: 0
    NVD CVE Checked: 2020-02-04T17:29:08
    NVD CVE Modified: 2020-02-04T16:02:04
    VersionCheckOn: 2020-02-04T17:29:08

apparently  its not able to detect  the dependencies.

Is  there a specific any details  that need  to  be in the  repo in  order to be  scanned correctly ?

**Comment by jeremylong** [comment]
Duplicate of #1496. Python analysis is experimental and there are several enhancements that need to be made. To resolve this we likely need to implement https://github.com/jeremylong/DependencyCheck/issues/548.  The last rounds of updates have focused on node.js - the team will likely look at enhancing python analysis soon.

**Comment by jhermann** [comment]
You can close this one though, because detecting zero deps in a zero-deps project seems OKish.

**Comment by jeremylong** [comment]
This will be tracked via #548 going forward.
