### ISSUE TITLE
Let dependency-check report inlcude maven coordinates of the affected dependency

### ISSUE THREAD

**Issue by reallyinsane** [dependency-check/DependencyCheck#2466]
When using dependency-check report I'm always searching for the dependency containing the vulnerability. The filename is specified in the report but you have to parse it with lots of problems. When analysing the report I'd like to identify the dependency with its maven coorindates - groupId, artifactId and version.

 As the JarAnalyzer already has this information this needs to be set in the Dependency domain object. Reports can then also write this information.

**Comment by jeremylong** [comment]
This information is already in the report using the [purl specification](https://github.com/package-url/purl-spec). We use this as we analyze multiple types of dependencies from other ecosystems. For all dependencies from a Maven build (and most from the Jar analyzer) you will see something like:

```xml
<identifiers>
  <package confidence="HIGH">
    <id>pkg:maven/commons-logging/commons-logging@1.2</id>
  </package>
</identifiers>
```

Which is very simple to read and aligns to the Group, Artifact, Version used by Maven.  If you are trying to use this information programmatically - there are many available libraries(https://github.com/package-url/purl-spec#known-implementations).

**Comment by reallyinsane** [comment]
Oh my god, I missed that part.
