### ISSUE TITLE
Can i use DependencyCheck to scan pom files only?

### ISSUE THREAD

**Issue by JStyle21** [dependency-check/DependencyCheck#2470]
Hi,

I'm looking to analyze the pom files as they contain the dependencies without providing the entire source of a project or building anything, is that possible?

**Comment by jeremylong** [comment]
To scan `pom.xml` files you would need to use the ODC maven plugin. In cases of supporting a ton of different projects - consider using a script something like:

```bash
if test -f "pom.xml"; then
   mvn org.owasp:dependency-check-maven:aggregate
   publish ./target/dependency-check.xml
elif  test -f "build.gradle"; then
   gradle --init-script /path/to/customDependencyCheckConfig.gradle dependencyCheckAggregate
   publish ./build/reports/dependency-check.xml
else
   dependency-check.sh -s . -o . -f XML
   publish ./dependency-check.xml
fi
```

For the above gradle step to work you need to see the documentation on [init-scripts](https://docs.gradle.org/current/userguide/init_scripts.html) - I haven't done this myself yet, but basically you could more correctly cover gradle and maven builds out of the box with just a little scripting like the above.

**Comment by mprins** [comment]
You still need full dependency resolution, which is part of the pre-build steps in maven, normally 
this will download all of the dependencies, but this depends on the type of artifact.

if you don't build the projects you may be missing things, eg. javascript libs that are rolled into .war files, shaded dependencies, ...

**Comment by JStyle21** [comment]
@mprins Thanks and yes i'm aware of this but my needs are different i just want to work with single files containing the dependencies and versions, not scan entire projects looking so such info.

@jeremylong Thanks for the info i will test it out and update on my attempts.

**Comment by JStyle21** [comment]
@jeremylong 
Ok my mistake i think i misunderstood your answer a bit, looking back at it now i don't think it works well with what i'm using which is the docker version.
i think i might be able to change the scan behavior from the app but per your answer i will need to build my own version, correct?

**Comment by jeremylong** [comment]
Docker is just the CLI. If you want to analyze a pom - you need to be integrated into a build environment.  You can have the tools all point to the same data directory.

**Comment by JStyle21** [comment]
i understand but at this situation i'm looking at the pom file as an XML file and not a project file.
I can see for Javascript it can work with a file that only contains library and version, can't it work the same for pom?

**Comment by jeremylong** [comment]
Nope.  For pom.xml we need the maven build system.

Jeremy

**Comment by JStyle21** [comment]
Ok maybe i can work around it, what about other cases like the JS i mentioned. forget about the pom what are other type of files that can be scanned the way i mentioned?

**Comment by jeremylong** [comment]
See https://jeremylong.github.io/DependencyCheck/analyzers/index.html

**Comment by jeremylong** [comment]
Also - the reason we do not just analyze a `pom.xml` outside of the Maven build is that we would not be able to resolve the transitive dependencies. We would only have limited evidence for CPE identification for the direct dependencies. Additionally, pom files can become very complex with properties, profiles, dependency-management section, parent poms, etc.  It is better to let the Maven do its job and handle to complexities.

**Comment by JStyle21** [comment]
What would be the best approach to use OWASP dependencyCheck as a standalone?

i can't get most analyzers to work at the moment since i'm not using the build tools or the full project
if we forget about any false positives or negatives for a moment how can i just feed it a file with names of libraries and get it to scan against the DB it has?

Can i do it with a custom analyzer? or do i have to write my own tool for this?

**Comment by jeremylong** [comment]
Completely understand you might not be in the build system - but if you have a pom and Maven installed can you just run `mvn org.owasp:dependency-check-maven:5.3.0:check`? Alternatively, have the developers run `mvn dependency:copy-dependencies` and give you the target/dependencies directory.  

Otherwise - you'll have to write your own analyzer for Dependency-Check.  You can stub one out using:

`mvn archetype:generate -B -DarchetypeArtifactId=dependency-check-plugin -DarchetypeGroupId=org.owasp -DarchetypeVersion=5.3.0 -DgroupId=org.mine -DartifactId=pom-scanner -Dversion=1.0.0`  

This will give you a plugin skeleton that you could then customize the generated `src/main/java/org/mine/CustomAnalyzer.java` to read in pom.xml files and process the dependencies section.  But I'll warn you going this route you have to deal with property substation, dependency-management section layered on top of the dependency section. Plus you won't be reading in the transitive dependencies - to get those you would have to download the pom files (recursively) for every dependency. Plus you can have profiles that can affect how dependencies are resolved and possibly a settings.xml...  I might be missing things that can also complicate resolving the dependencies...  All this is why I rely on the build system.

**Comment by OrangeDog** [comment]
> I might be missing things that can also complicate resolving the dependencies...

Parent poms and imported poms :)

**Comment by JStyle21** [comment]
@jeremylong 
Thank you for the detailed response, let me try to explain a bit more.
I'm in a situation where what i need is a tool that can take a list of components + versions and search\cross reference those with public issues.

So i could probably whip something up with various sources since each language has it's own source etc. but i thought i could save me a lot of trouble be taking this tool as a base so honestly all i wanted is access to the searching capabilities and i would provide the input, however as you mentioned since it's so bundled with the build system it's a problem.

It's not like i'm complaining or criticizing the work, i'm not. this project is awesome regardless of my situation and i'm not anti build systems or maven it's just that i need a different approach here.

Going back to the subject, i'm not sure i would need to deal with transitive dependencies or child dependencies, for the first step i would just like to provide the dependencies list myself then in step two i would try to make it work with the main pom and advance from there to other deeper situation but by no means i'm going to cover entire projects with this nor have i ever planned to.

I will try to create a custom analyzer but since i'm not great with Java and i'm not familiar with the code i might come back here for questions if that's ok? :)

**Comment by jeremylong** [comment]
Consider looking at dependency-track - it might fit your needs better.

**Comment by JStyle21** [comment]
I'm aware of this project but it seemed more focused on CI than what i need and it has no support from CMD mode or any import abilities apart from BOM.

Back to the original plan or adding a custom analyzer vs writing my own script for this.
The real benefits for me of using an existing project is no need to handle the CVE sources or their DB plus having more analyzers.

**Comment by JStyle21** [comment]
One more question regarding your earlier comment how do i integrate my custom analyzer into the project? i mean CustomAnalyzer.java should be inside the jar file, where and how do i add it?

**Comment by jeremylong** [comment]
If you used the archtype referenced above you would get a JAR file that has everything needed. You would just place the JAR file in the `dependency-check/plugins` directory and it should be active.  Note that if you renamed the analyzer you would have to update (in your project) the `src/main/resources/META-INF/services/org.owasp.dependencycheck.analyzer.Analyzer` to include the fully qualified class name.

**Comment by JStyle21** [comment]
Sorry Java isn't my strong side, still a bit confused
all i got is a new folder called pom-scanner that has the hierarchy based on the archtype with all the values i've provided with the command you specified, no Jar file there.
Apart from the core\target jar file which is the whole program the only other relevant one i could find is /archetype/target/dependency-check-plugin-5.3.2-SNAPSHOT.jar but that seems like a general plugin jar file and does not contain anything i've added or changed.

Also the plugins folder doesn't exist, do i need to create one?

**Comment by jeremylong** [comment]
Full explanation:

1. Create a maven project from the ODC archtype:
```
$ mvn archetype:generate -B -DarchetypeArtifactId=dependency-check-plugin -DarchetypeGroupId=org.owasp -DarchetypeVersion=5.3.0 -DgroupId=org.mine -DartifactId=pom-scanner -Dversion=1.0.0
...
$ cd pom-scanner/
```
2. Edit `src/main/java/org/mine/CustomAnalyzer.java` to implement your analyzer. If you rename the class you will also have to rename the entry contained in the file `src/main/resources/META-INF/services/org.owasp.dependencycheck.analyzer.Analyzer` (when you create the project from step one this file has only a single line: `org.mine.CustomAnalyzer`).

3. Build the project from the command (or you can use an IDE) - but from the command line you would run (you could also use `mvn install`):

```
mvn package
```

4. Copy the `pom-scanner/target/target/pom-scanner-1.0.0.jar` into the `plugins` directory of the ODC CLI.

5. Run ODC - you should see your custom analyzer execute.

**Comment by JStyle21** [comment]
Thanks!

Got it to work, now i just need to develop the plugin :)

**Comment by robross0606** [comment]
> To scan `pom.xml` files you would need to use the ODC maven plugin. In cases of supporting a ton of different projects - consider using a script something like:
> 
> ```shell
> if test -f "pom.xml"; then
>    mvn org.owasp:dependency-check-maven:aggregate
>    publish ./target/dependency-check.xml
> elif  test -f "build.gradle"; then
>    gradle --init-script /path/to/customDependencyCheckConfig.gradle dependencyCheckAggregate
>    publish ./build/reports/dependency-check.xml
> else
>    dependency-check.sh -s . -o . -f XML
>    publish ./dependency-check.xml
> fi
> ```
> 
> For the above gradle step to work you need to see the documentation on [init-scripts](https://docs.gradle.org/current/userguide/init_scripts.html) - I haven't done this myself yet, but basically you could more correctly cover gradle and maven builds out of the box with just a little scripting like the above.

I'd _love_ to do this but, in cases where a pipeline is run on docker containers (such as GitLab), I have yet to find an existing Docker container that can run all three of these flavors using one script.  AFAIK, the OWASP containers are based on Alpine Linux which only goes up to Maven 3.8.5 even if we wanted to install it using `apk`.
