### ISSUE TITLE
Using the OWASP dependencyCheck to generate separate reports for java modules instead of one large report

### ISSUE THREAD

**Issue by nt10307** [dependency-check/DependencyCheck#2475]
I'm trying to break the dependency check report generated by my Jenkins CI pipeline into multiple reports (one per module) because having one giant report can get rather large and hard to read. This is the code I have so far to accomplish this:

`if(fileExists('pom.xml')) {
   def pom = readMavenPom file: 'pom.xml'
   pom.modules.each {
     dependencyCheck additionalArguments: "--scan ./${it} --format CSV --out owasp-reports/${it}-dependency-check-report.csv", odcInstallation: "${env.DEPENDENCY_CHECK}"
     dependencyCheck additionalArguments: "--scan ./${it} --format JSON --out owasp-reports/${it}-dependency-check-report.json", odcInstallation: "${env.DEPENDENCY_CHECK}"
     dependencyCheck additionalArguments: "--scan ./${it} --format HTML --out owasp-reports/${it}-dependency-check-report.html", odcInstallation: "${env.DEPENDENCY_CHECK}"
   }
}`

I'm getting files generated with the appropriate names, but no dependencies are scanned. However, this appropriately generates a large report containing all the child modules

`dependencyCheck additionalArguments: '--scan ./ --format XML --format JSON --format HTML --format CSV --out owasp-reports', odcInstallation: "${env.DEPENDENCY_CHECK}"
`
Is it possible to use this approach or something close to it?  There are going to be lots of projects and asking each project owner to throw the maven plugin in their poms isn't ideal.

**Comment by nt10307** [comment]
I have also tried this to no avail:
`pom.modules.each {
			dir("${it}"){
				dependencyCheck additionalArguments: "--scan ./ --format CSV --out ../owasp-reports/${it}-dependency-check-report.csv", odcInstallation: "${env.DEPENDENCY_CHECK}"
				dependencyCheck additionalArguments: "--scan ./ --format JSON --out ../owasp-reports/${it}-dependency-check-report.json", odcInstallation: "${env.DEPENDENCY_CHECK}"
				dependencyCheck additionalArguments: "--scan ./ --format HTML --out ../owasp-reports/${it}-dependency-check-report.html", odcInstallation: "${env.DEPENDENCY_CHECK}"
			}
		}`

**Comment by jeremylong** [comment]
I would highly recommend using the Maven or gradle plugin instead of Jenkins to do the scans. I have provided a high level outline of how you could accomplish this in [#2470](https://github.com/jeremylong/DependencyCheck/issues/2470#issuecomment-584600953).
