### ISSUE TITLE
--jspath or --path support for retireJS

### ISSUE THREAD

**Issue by thanarino** [dependency-check/DependencyCheck#2476]
**Is your feature request related to a problem? Please describe.**
The CLI version of RetireJS implements these parameters, and I am currently working on a project which does not have a package.json, or package-lock.json, the dependencies are all in a folder. In my testing, RetireJS can scan filenames and comments of the JS dependencies, and outputs appropriate vulnerable dependencies.

**Describe the solution you'd like**
It would be very helpful if the --jsPath or --path parameters of retireJs are supported.

**Describe alternatives you've considered**
None yet.

**Additional context**
Dependency-check logs read: "Finished RetireJS Analysis (0 seconds)" There are no logs that indicate that there are no package.json or package-lock.json in the project.

**Comment by jeremylong** [comment]
The ODC implementation of RetireJS does not use the package.json or package-lock.json. The RetireJS implementation within ODC only covers the client side JS. The node.js scanner of Retire.JS has not been implemented yet.

**Comment by thanarino** [comment]
thanks for clarifying, setting the scanSet parameter in dependencyCheck worked as well.
