### ISSUE TITLE
dev dependencies not being skipped

### ISSUE THREAD

**Issue by csavory** [dependency-check/DependencyCheck#2482]
**Describe the bug**
As a follow up to [https://github.com/jeremylong/DependencyCheck/issues/1806](https://github.com/jeremylong/DependencyCheck/issues/1806) I was testing the cli with --nodeAuditSkipDevDependencies flag enabled. But now my build is getting flagged for a dependency of one my dev dependenies.  However, "npm audit --production" does not flag this JQuery dependency.  This is on a new/clean Angular project built by the Angular CLI. 

**Version of dependency-check used**
The problem occurs using version 5.3.0 of the Command Line Tool

**Log file**
Gist has a limit of 100MB and my log file is 4.68 GB.  I can zip it an use something like https://wetransfer.com/ to send it to you. What would you like me to do? 

**To Reproduce**
1. Using package.json below, run npm install
2. Run: npm audit --production - Verify no vulnerabilities
3. Run: dependency-check --project "Platform Admin" --format XML --format HTML --scan ./ --nodeAuditSkipDevDependencies
4. Verify that there are multiple JQuery vulnerabilities found that are part of a dev dependency selenium-webdriver 

**Expected behavior**
Zero vulnerabilities from dependency-check when using the flag nodeAuditSkipDevDependencies

**Additional context**

`{
  "name": "platform-admin",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "test-headless-with-coverage": "ng test --watch=false --browsers=ChromeHeadless --code-coverage",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.2.14",
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "core-js": "^2.5.4",
    "rxjs": "~6.5.4",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.22",
    "@angular/cli": "~8.3.22",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.0.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.5.3"
  }
}`

**Comment by jeremylong** [comment]
I'm pretty sure I know what is going on.  Can you re-run the analysis with `--disableNodeJS`:

```
dependency-check --project "Platform Admin" --format XML --format HTML --scan . 
--nodeAuditSkipDevDependencies --disableNodeJS`
```

Are the dev dependencies still being flagged?

**Comment by csavory** [comment]
Looks like --disableNodeJS disables the Node Package Analyzer, but not the Node Audit Analyzer which seems to be finding these dev dependencies.  Here is the output of the two builds w/ and w/o.

I did some searching in the SeleniumHQ project and the dependencies being flagged are not listed in the project's package.json, but rather the files are embedded within the project itself. 
https://github.com/SeleniumHQ/selenium/blob/master/common/src/web/js/jquery-1.4.4.min.js

Here are the two builds

`dependency-check --project "Test" --format XML --format HTML --scan . --nodeAuditSkipDevDependencies`

```
[INFO] Checking for updates
[INFO] Download Started for NVD CVE - Modified
[INFO] Download Complete for NVD CVE - Modified  (2153 ms)
[INFO] Processing Started for NVD CVE - Modified
[INFO] Processing Complete for NVD CVE - Modified  (1911 ms)
[INFO] Begin database maintenance
[INFO] Updated the CPE ecosystem on 3 NVD records
[INFO] Cleaned up 5 orphaned NVD records
[INFO] End database maintenance (4629 ms)
[INFO] Begin database defrag
[INFO] End database defrag (8287 ms)
[INFO] Check for updates complete (20232 ms)
[INFO] 

Dependency-Check is an open source tool performing a best effort analysis of 3rd party dependencies; false positives and false negatives may exist in the analysis performed by the tool. Use of the tool and the reporting provided constitutes acceptance for use in an AS IS condition, and there are NO warranties, implied or otherwise, with regard to the analysis or its use. Any use of the tool and the reporting provided is at the user’s risk. In no event shall the copyright holder or OWASP be held liable for any damages whatsoever arising out of or in connection with the use of this tool, the analysis performed, or the resulting report.


[INFO] Analysis Started
[INFO] Finished Archive Analyzer (0 seconds)
[INFO] Finished File Name Analyzer (0 seconds)
[WARN] No lock file exists - this will result in false negatives; please run `npm install --package-lock`
[WARN] Analyzing `/var/folders/dj/ckvgkdz501v2kzcfw9846znw0000gn/T/dctempd5bb51b0-8461-4d2b-a844-9716d4023d8c/check7877920696590669917tmp/21/package/package.json` - however, the node_modules directory does not exist. Please run `npm install` prior to running dependency-check
[WARN] No lock file exists - this will result in false negatives; please run `npm install --package-lock`
[WARN] Analyzing `/var/folders/dj/ckvgkdz501v2kzcfw9846znw0000gn/T/dctempd5bb51b0-8461-4d2b-a844-9716d4023d8c/check7877920696590669917tmp/5/package/package.json` - however, the node_modules directory does not exist. Please run `npm install` prior to running dependency-check
[WARN] No lock file exists - this will result in false negatives; please run `npm install --package-lock`
[WARN] Analyzing `/var/folders/dj/ckvgkdz501v2kzcfw9846znw0000gn/T/dctempd5bb51b0-8461-4d2b-a844-9716d4023d8c/check7877920696590669917tmp/16/package/package.json` - however, the node_modules directory does not exist. Please run `npm install` prior to running dependency-check
[WARN] No lock file exists - this will result in false negatives; please run `npm install --package-lock`
[WARN] Analyzing `/var/folders/dj/ckvgkdz501v2kzcfw9846znw0000gn/T/dctempd5bb51b0-8461-4d2b-a844-9716d4023d8c/check7877920696590669917tmp/17/package/package.json` - however, the node_modules directory does not exist. Please run `npm install` prior to running dependency-check
[WARN] No lock file exists - this will result in false negatives; please run `npm install --package-lock`
[WARN] Analyzing `/var/folders/dj/ckvgkdz501v2kzcfw9846znw0000gn/T/dctempd5bb51b0-8461-4d2b-a844-9716d4023d8c/check7877920696590669917tmp/2/package/package.json` - however, the node_modules directory does not exist. Please run `npm install` prior to running dependency-check
[WARN] No lock file exists - this will result in false negatives; please run `npm install --package-lock`
[WARN] Analyzing `/var/folders/dj/ckvgkdz501v2kzcfw9846znw0000gn/T/dctempd5bb51b0-8461-4d2b-a844-9716d4023d8c/check7877920696590669917tmp/9/package/package.json` - however, the node_modules directory does not exist. Please run `npm install` prior to running dependency-check
[WARN] No lock file exists - this will result in false negatives; please run `npm install --package-lock`
[WARN] Analyzing `/var/folders/dj/ckvgkdz501v2kzcfw9846znw0000gn/T/dctempd5bb51b0-8461-4d2b-a844-9716d4023d8c/check7877920696590669917tmp/8/package/package.json` - however, the node_modules directory does not exist. Please run `npm install` prior to running dependency-check
[WARN] No lock file exists - this will result in false negatives; please run `npm install --package-lock`
[WARN] Analyzing `/var/folders/dj/ckvgkdz501v2kzcfw9846znw0000gn/T/dctempd5bb51b0-8461-4d2b-a844-9716d4023d8c/check7877920696590669917tmp/19/package/package.json` - however, the node_modules directory does not exist. Please run `npm install` prior to running dependency-check
[WARN] No lock file exists - this will result in false negatives; please run `npm install --package-lock`
[WARN] Analyzing `/var/folders/dj/ckvgkdz501v2kzcfw9846znw0000gn/T/dctempd5bb51b0-8461-4d2b-a844-9716d4023d8c/check7877920696590669917tmp/11/package/package.json` - however, the node_modules directory does not exist. Please run `npm install` prior to running dependency-check
[WARN] No lock file exists - this will result in false negatives; please run `npm install --package-lock`
[WARN] Analyzing `/var/folders/dj/ckvgkdz501v2kzcfw9846znw0000gn/T/dctempd5bb51b0-8461-4d2b-a844-9716d4023d8c/check7877920696590669917tmp/14/package/package.json` - however, the node_modules directory does not exist. Please run `npm install` prior to running dependency-check
[INFO] Finished Node.js Package Analyzer (4 seconds)
[INFO] Finished Dependency Merging Analyzer (79 seconds)
[INFO] Finished Version Filter Analyzer (0 seconds)
[INFO] Finished Hint Analyzer (0 seconds)
[INFO] Created CPE Index (2 seconds)
[INFO] Finished CPE Analyzer (2 seconds)
[INFO] Finished False Positive Analyzer (0 seconds)
[INFO] Finished NVD CVE Analyzer (0 seconds)
[INFO] Finished Node Audit Analyzer (3 seconds)
00:05  INFO: Vulnerability found: jquery below 1.6.3
00:05  INFO: Vulnerability found: jquery below 1.9.0b1
00:05  INFO: Vulnerability found: jquery below 1.12.0
00:05  INFO: Vulnerability found: jquery below 3.4.0
00:48  INFO: Vulnerability found: jquery-ui-dialog below 1.10.0
00:48  INFO: Vulnerability found: jquery-ui-dialog below 1.12.0
01:03  INFO: Vulnerability found: jquery below 1.6.3
01:03  INFO: Vulnerability found: jquery below 1.9.0b1
01:03  INFO: Vulnerability found: jquery below 3.4.0
[INFO] Finished RetireJS Analyzer (83 seconds)
[INFO] Finished Sonatype OSS Index Analyzer (17 seconds)
[INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
[INFO] Finished Dependency Bundling Analyzer (75 seconds)
[INFO] Analysis Complete (266 seconds)
```


`dependency-check --project "Test" --format XML --format HTML --scan . --nodeAuditSkipDevDependencies --disableNodeJS`

```
[INFO] Checking for updates
[INFO] Skipping NVD check since last check was within 4 hours.
[INFO] Skipping RetireJS update since last update was within 24 hours.
[INFO] Check for updates complete (130 ms)
[INFO] 

Dependency-Check is an open source tool performing a best effort analysis of 3rd party dependencies; false positives and false negatives may exist in the analysis performed by the tool. Use of the tool and the reporting provided constitutes acceptance for use in an AS IS condition, and there are NO warranties, implied or otherwise, with regard to the analysis or its use. Any use of the tool and the reporting provided is at the user’s risk. In no event shall the copyright holder or OWASP be held liable for any damages whatsoever arising out of or in connection with the use of this tool, the analysis performed, or the resulting report.

[INFO] Analysis Started
[INFO] Finished Archive Analyzer (0 seconds)
[INFO] Finished File Name Analyzer (0 seconds)
	[INFO] Finished Dependency Merging Analyzer (79 seconds)
[INFO] Finished Version Filter Analyzer (0 seconds)
[INFO] Finished Hint Analyzer (0 seconds)
[INFO] Created CPE Index (3 seconds)
[INFO] Finished CPE Analyzer (3 seconds)
[INFO] Finished False Positive Analyzer (0 seconds)
[INFO] Finished NVD CVE Analyzer (0 seconds)
[WARN] The Node Package Analyzer has been disabled; the resulting report will only contain the known vulnerable dependency - not a bill of materials for the node project.
[INFO] Finished Node Audit Analyzer (0 seconds)
00:07  INFO: Vulnerability found: jquery below 1.6.3
00:07  INFO: Vulnerability found: jquery below 1.9.0b1
00:07  INFO: Vulnerability found: jquery below 1.12.0
00:07  INFO: Vulnerability found: jquery below 3.4.0
00:51  INFO: Vulnerability found: jquery-ui-dialog below 1.10.0
00:51  INFO: Vulnerability found: jquery-ui-dialog below 1.12.0
01:04  INFO: Vulnerability found: jquery below 1.6.3
01:04  INFO: Vulnerability found: jquery below 1.9.0b1
01:04  INFO: Vulnerability found: jquery below 3.4.0
[INFO] Finished RetireJS Analyzer (82 seconds)
[INFO] Finished Sonatype OSS Index Analyzer (0 seconds)
[INFO] Finished Vulnerability Suppression Analyzer (1 seconds)
[INFO] Finished Dependency Bundling Analyzer (62 seconds)
[INFO] Analysis Complete (231 seconds)
```

**Comment by nuclearglow** [comment]
We're seeing a similar issue. We have an Angular project and use the following `dependency-checker` CLI args: `--disableNodeAuditCache --nodeAuditSkipDevDependencies`
In the resulting report, `handlebars 4.4.3` is being reported, but as `npm ls handlebars` reveals:
```shell
├─┬ @compodoc/compodoc@1.1.10
│ └── handlebars@4.4.3 
├─┬ jest@24.9.0
│ └─┬ jest-cli@24.9.0
│   └─┬ @jest/core@24.9.0
│     └─┬ @jest/reporters@24.9.0
│       └─┬ istanbul-reports@2.2.6
│         └── handlebars@4.4.3  deduped
└─┬ npm-audit-html@1.3.4
  └── handlebars@4.4.3  deduped
```
The parent dependencies are all devDependencies. However, we have found that this being a deduped dependency, the `package-lock.json` tracks this as a direct dependency:
```json
{
  "dependencies": {
    "handlebars": {
      "version": "4.4.3",
      "resolved": "https://nexus.dwpsoftware.hu/repository/npm-all/handlebars/-/handlebars-4.4.3.tgz",
      "dev": true,
  }
}
```
The hint that this is `dev` does not seem to be handled...

**Comment by NancyChunlan** [comment]
We have the same issue here. the maven option -DnodeAuditSkipDevDependencies=true can not work as expected.

**Comment by jeremylong** [comment]
As indicated above - there are multiple ways that the scanning occurs:
1. The NodeAuditAnalyzer uses the package.json and package-lock.json information to query the node audit API and return the results.  This will correctly skip the dev dependencies.
2. The Node Package Analyzer - which attempts to identify dependency information from the files on disk (not the package or package-lock). This analyzer is likely causing most of the issues and probably needs to be deprecated within ODC.  I would recommend using `--disableNodeJS` for now.
3. The RetireJS Analyzer - which is a wrapper around RetireJS scanner. Note, the current implementation does not use the node analysis, rather it was implemented to detect client side JS issues such as a vulnerable version of JQuery that is in the src directory of an application. Depending on the configuration of the scan if you include the node_modules - this analyzer may also pick up dev dependencies.

**Comment by csavory** [comment]
Thank you @jeremylong 

I added a temporary workaround by adding `--disableNodeJS` and `--disableRetireJS`

**Comment by nuclearglow** [comment]
Hello @jeremylong, thanks for your feedback. We have added `--disableNodeJS` and `--disableRetireJS` but the problem persists. Another example:

In the SonarQube report, there is a vulnerability reported:
`package-lock.json`
```
"acorn": {
   "version": "6.3.0", // CVSS 7.5 ...
   "dev": true
}
```

`npm ls acorn@6.3.0`

```
├─┬ @angular-devkit/build-angular@0.803.17
│ └─┬ webpack@4.39.2
│   └── acorn@6.3.0 
└─┬ jest-preset-angular@7.1.1
  └─┬ jest-environment-jsdom-thirteen@1.0.1
    └─┬ jsdom@13.2.0
      ├── acorn@6.3.0  deduped
      └─┬ acorn-globals@4.3.4
        └── acorn@6.3.0  deduped
```

Since Jest and Angular-Devkit are Dev Dependencies, they are still getting picked up... Do you  have an idea why that is?

**Comment by jeremylong** [comment]
@nuclearglow can you provide the `package.json` and `package-lock.json`?

**Comment by nuclearglow** [comment]
edited: depublished

**Comment by rbhawar** [comment]
We are also observing the similar issue. Is there any update on this? TIA.

**Comment by jeremylong** [comment]
We were not skipping dev dependencies in the package-lock.json - this has been fixed with f7de368.

**Comment by ghost** [comment]
Just for the record, if someone is as confused as I was about this issue.

There was a fix in `6.0.2` for this issue, but it contains a bug. The bug is fixed with https://github.com/jeremylong/DependencyCheck/commit/f7de368fc5580f152dd19434bf550239abcacc94 and this will be part of `6.0.3`.

**Comment by H3llK33p3r** [comment]
Hi, please reopen this issue or change it to set the correct fix version to the next 6.0.3.

**Comment by antoineclarose** [comment]
Hello all, is there any progress on this? When is 6.0.3 planned for?
6.0.3 including this functionality would really be game-changing. We are getting many false positives currently due to this.

**Comment by albuch** [comment]
`v6.0.3` was released 2 weeks ago: https://github.com/jeremylong/DependencyCheck/releases/tag/v6.0.3

**Comment by orgrimm9** [comment]
We observe this with v6.1.6, any thoughts on this? We had to add both --disableNodeJS --nodeAuditSkipDevDependencies for the scan to not pick up dev dependencies.

**Comment by jlczuk** [comment]
Can the --disableNodeJS  and --nodeAuditSkipDevDependencies be specified when running the dependency checker Jenkins plugin?

**Comment by Stew130** [comment]
> --disableNodeJS --nodeAuditSkipDevDependencies

Build Steps > Invoke Dependency-Check > Arguments:

--disableNodeJS 
--nodeAuditSkipDevDependencies
--format XML
--format HTML
--format CSV
