### ISSUE TITLE
Avoid recomputing file hashes unnecessarily

### ISSUE THREAD

**Issue by dbevacqua** [dependency-check/DependencyCheck#2485]
**Is your feature request related to a problem? Please describe.**
When a `Dependency` is created for a given file, the file's checksums are computed, regardless of whether this has been done before. In a multi-module Maven project with many common dependencies, this can slow checks considerably. For example, for the project I'm currently working on, ~50k checksums are computed for ~9k files. The scan takes nearly two minutes.

**Describe the solution you'd like**
Cache the checksum for a given hash function and file

**Describe alternatives you've considered**
I experimented with an implementation of `Checksums` which used Guava hashing and this appeared to speed up checks by ~15%. It is also quite concise, e.g.

```
HashCode hashCode = Files.hash(file, Hashing.md5());
```

**Additional context**
Profiling suggests that the vast majority of CPU time is spent computing file checksums, so this is definitely a hotspot

**Comment by jeremylong** [comment]
Thanks for the PR!
