### ISSUE TITLE
skipDependencyManagement=false does not handle reactor projects appropriately

### ISSUE THREAD

**Issue by aikebah** [dependency-check/DependencyCheck#2494]
Based on previous bad experiences with the maven-release-plugin and multimodule projects that had sibling-dependencies we've adopted a practice of version-managing sibling dependencies in the top-level parent of a multimodule project

```
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>sibling2</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

When such a multimodule project is aggregate-scanned by DependencyCheck it results in
```
[INFO] Unable to resolve org.owasp.test.aggregate.issue-nnn:sibling2:1.0.0-SNAPSHOT as it has not been built yet - creating a virtual dependency instead.
....
[ERROR] Failed to execute goal org.owasp:dependency-check-maven:5.3.1-SNAPSHOT:aggregate (default) on project parent: One or more exceptions occurred during dependency-check analysis: One or more exceptions occurred during analysis:
[ERROR] 	Could not find artifact org.owasp.test.aggregate.issue-nnn:sibling2:jar:1.0.0-SNAPSHOT
[ERROR] 	Could not find artifact org.owasp.test.aggregate.issue-nnn:sibling2:jar:1.0.0-SNAPSHOT
[ERROR] 	Could not find artifact org.owasp.test.aggregate.issue-nnn:sibling2:jar:1.0.0-SNAPSHOT
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.owasp:dependency-check-maven:5.3.1-SNAPSHOT:aggregate (default) on project parent: One or more exceptions occurred during dependency-check analysis
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
...
Caused by: org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during analysis:
	Could not find artifact org.owasp.test.aggregate.issue-nnn:sibling2:jar:1.0.0-SNAPSHOT
	Could not find artifact org.owasp.test.aggregate.issue-nnn:sibling2:jar:1.0.0-SNAPSHOT
	Could not find artifact org.owasp.test.aggregate.issue-nnn:sibling2:jar:1.0.0-SNAPSHOT
    at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.collectDependencyManagementDependencies (BaseDependencyCheckMojo.java:1089)
```

The problem occurs using version 5.3.0 of the maven plugin

**To Reproduce**
1. Create a new multimodule project with sibling-dependency between child-modules using the above mentioned strategy 
2. Run a dependency-check:aggregate with skipDependencyManagement=false 
3. See the build fail with the mentioned error (and stacktrace when adding maven CLI argument -e)

**Expected behavior**
dependencyManagement would detect that dependencyManagement references a reactor project and use a virtual dependency for that, just like is done with the actual use of this managed dependency inside the sibling project (which triggers the first INFO message referenced above).

**Comment by aikebah** [comment]
As you might've guessed from the logs I'm already working on a test-case and following that will work on a fix and do a PR

**Comment by aikebah** [comment]
@jeremylong Looking at the counterpart implementation for regular dependencies I'm suspecting a logic-error there. At https://github.com/jeremylong/DependencyCheck/blob/648253b85bccb21835884eb981fe786fedc20ade/maven/src/main/java/org/owasp/dependencycheck/maven/BaseDependencyCheckMojo.java#L1165 the ArtifactResolverException will always be swallowed/ignored if the current run is not an aggregate, as the first clause would yield true the addException is set to false.
I would expect the condition to be 
```
if (!aggregate) { 
  //doNothing - ArtifactResolverException should be reported
} else if (addReactorDependency(engine, dependencyNode.getArtifact()))
  addException = false;
}
```
When you agree I can take that fix alongside my coding for the dependencyManagement case.

**Comment by jeremylong** [comment]
Thanks for the PR!
