### ISSUE TITLE
One report for different projects

### ISSUE THREAD

**Issue by wojteo** [dependency-check/DependencyCheck#2497]
I have many projects (gradle and maven) configured to generate DC reports. However I would like to have it in one place (preferably HTML) for easier tracking of overall changes. 

Is it currently possible to for example merge/aggregrate reports from different projects?
Or are there any free 3rd party tools like DependencyTrack (which unfortunately doesn't support DC anymore) ?

**Comment by jeremylong** [comment]
Unfortunately no. There is no functionality to merge the reports. One option might be to use the Sonar plugin.

**Comment by wojteo** [comment]
Thank you :)
