### ISSUE TITLE
False Positive on org.jetbrains.kotlinx:kotlinx-coroutines-core:1.1.1

### ISSUE THREAD

**Issue by DennisHartrampf** [dependency-check/DependencyCheck#2499]
False positive on library `org.jetbrains.kotlinx:kotlinx-coroutines-core:1.1.1` - reported as `cpe:2.3:a:jetbrains:kotlin:*:*:*:*:*:*:*:* versions up to (excluding) 1.3.30`

```xml
<dependency>
  <groupId>org.jetbrains.kotlinx</groupId>
  <artifactId>kotlinx-coroutines-core</artifactId>
  <version>1.1.1</version>
</dependency>
```

**Comment by ilya-g** [comment]
To avoid further false positives of this kind (see also #2346) it makes sense to avoid matching `org.jetbrains.kotlinx` maven group id with CPE name `cpe:2.3:a:jetbrains:kotlin:*:*:*:*:*:*:*:*`
