### ISSUE TITLE
Default enabled analyzers for CLI

### ISSUE THREAD

**Issue by ghost** [dependency-check/DependencyCheck#2503]
I've read the CLI Options [here](https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html), but I could not find which Analyzers are enabled by default in CLI as their default values are empty.

**Comment by jeremylong** [comment]
They are all enabled by default (which is why you only see options to disable) - with the exception of those marked [experimental](https://jeremylong.github.io/DependencyCheck/analyzers/index.html). To enable those you must specify `--enableExperimental`.

**Comment by ghost** [comment]
> They are all enabled by default (which is why you only see options to disable) - with the exception of those marked [experimental](https://jeremylong.github.io/DependencyCheck/analyzers/index.html). To enable those you must specify `--enableExperimental`.

Thank you @jeremylong for the info!
