### ISSUE TITLE
False Positive on gradle-wrapper.jar

### ISSUE THREAD

**Issue by mjmccormac** [dependency-check/DependencyCheck#2510]
False positive on gradle-wrapper.jar v5.6.4 - reported as cpe:2.3:a:gradle:gradle:3.5.1:*:*:*:*:*:*:*

I have a project using gradle v5.6.4, however dependency-check CLI is flagging it as gradle v3.5.1 because the checksums are wrong. 

Actual checksums for v3.5.1 are:
md5sum: e3b2b2f23f1539699c9825efcc4c1074  gradle-wrapper.jar
sha1sum: 0148a9cda5963b8c837b07379ac4b9ce1a838aaf  gradle-wrapper.jar
sha256sum: b18a1114ebe81fb7502d40ad9a4f86cef82fff244a865ad45533b4d5e7ff0cc8  gradle-wrapper.jar

**Comment by jeremylong** [comment]
This is resolved in the 6.0.x releases of ODC.
