### ISSUE TITLE
Question about 0 Vulnerability Dependencies and CPEs

### ISSUE THREAD

**Issue by huynhp24** [dependency-check/DependencyCheck#2514]
Hello! I've learned a lot of new things about SCAs as well as NVD CPE/CVE concepts recently because of your tool. I am an intern new to the industry and find it inspiring to see that much of it is held up by charitable effort such as yours.

I've been working solely on node projects as I've been getting to know your tool the past few weeks. I was wondering if there was an option for the CLI dependency-check to list a dependency even if there are no vulnerabilities found. I pored over the documentation of this tool, ran many scans, looked through the NVD CPE dictionary to confirm that the package was there (as well as in the npm registry, where I got it), but when there are no vulnerabilities, the package is not shown in any of the output from the dependency-check scan.

Is this due to the fact that the node analyzers depend solely on npm audit, which returns only vulnerabilities? I saw that in #2122 you stated that you were making a tool for 5.3.0 which would cause it to look into the NVD for node projects, which I saw in the Dependency-Check CLI documentation makes up the backbone of this tool.

From what I could see for other types besides node, the ability to see 0 vulnerability dependencies is there, but not for node. Are these plans for the near future?

I apologize for any ignorant assumptions I may have taken in this. Pointing out any of it would help.

**Comment by jeremylong** [comment]
The report includes the vulnerable and non-vulnerable dependencies already.  In the HTML report there is a toggle right below the summary. In the report just click the link to show all.


> ### Summary
> Display: <a href="#">Showing Vulnerable Dependencies (click to show all)</a>

**Comment by huynhp24** [comment]
I'm sorry, there must be an error in my setup I need to track down. The node analyzers currently give me no results that aren't identical to what shows up from `npm audit`. Exactly the same results are displayed and nothing more (or less), even after clicking 'show all'. To clarify, I have the package-lock without the build.

**Comment by jeremylong** [comment]
You need to run `npm install` before running the analysis (currently) to get the dependencies not returned by npm audit. However, this has the downside that you can't skip the dev dependencies. There are plans to improve this - but that is how it works today.

**Comment by huynhp24** [comment]
Ah. I understand. Thank you for your time and for the clarification.
