### ISSUE TITLE
DependencyCheck scan only few files in Python project 

### ISSUE THREAD

**Issue by ErezDasa** [dependency-check/DependencyCheck#2524]
Hi,

I'm  try to scan the popular python project- "[Anaconda](https://github.com/Anaconda-Platform/anaconda-project)"

I'm using `--enableExperimental` but the results show only 12 dependencies:

```
dependency-check version: 5.3.0
Report Generated On: Tue, 10 Mar 2020 11:11:21 +0200
Dependencies Scanned: 12 (6 unique)
Vulnerable Dependencies: 0
Vulnerabilities Found: 0
Vulnerabilities Suppressed: 0
NVD CVE Checked: 2020-03-10T11:03:16
NVD CVE Modified: 2020-03-10T07:02:05
VersionCheckOn: 2020-03-10T11:03:16
```

Any idea why this is happened and how can i fix it so the DependencyCheck will scan the whole files in the project?!

Thnk you @jeremylong

**Comment by mprins** [comment]
see #548 and other issues referencing the experimental nature of the python scanner

**Comment by ErezDasa** [comment]
Thank you @mprins , do you know if version 5.3.1 should improve those results?
@jeremylong there is any news / roadmap for full Python scan?

**Comment by jeremylong** [comment]
@ErezDasa as was mentioned above there are several bugs/enhancement requests around python.  We will eventually get to it - but PRs are welcome.

**Comment by ErezDasa** [comment]
Thank you very much.
