### ISSUE TITLE
Where can I download DC for cli version 5.3.1?

### ISSUE THREAD

**Issue by ErezDasa** [dependency-check/DependencyCheck#2532]
there is only version 5.3.0 [here](https://owasp.org/www-project-dependency-check/)

Thank you @jeremylong

**Comment by jeremylong** [comment]
Missed updating the owasp page on the last release. It has been fixed.  For future reference the main readme on github has all of the usage instructions (including how to download it). Also, it is hosted on bintray here: https://bintray.com/jeremy-long/owasp
