### ISSUE TITLE
Markup injection in HTML report template

### ISSUE THREAD

**Issue by jupenur** [dependency-check/DependencyCheck#2535]
**Describe the bug**
The default HTML report template is vulnerable to markup injection due to reliance on `$enc.javascript` without `$enc.html` in nested contexts.

**Version of dependency-check used**
Dependency-Check Core version 5.3.1 (cli)

**Log file**
n/a

**To Reproduce**
1. Rename the `core/src/test/resources/javascript/ember.js` file to `"><iframe src=javascript:alert(1)>.js`
2. Run Dependency-Check against the renamed file
3. Open the generated HTML report in a browser
4. Observe a JavaScript `alert` dialog opening

**Expected behavior**
Markup injection should not be possible. All untrusted JavaScript strings should be encoded using both `$enc.javascript` *and* `$enc.html`.

**Additional context**
PR on the way.

**Comment by jeremylong** [comment]
Thanks for pointing this out - I seriously know better and have pointed this exact thing out in reviews...

Rather than fix the encoding per your PR - we are going to remove the use of the event attributes completely and instead bind the events.

**Comment by jeremylong** [comment]
We will release 5.3.2 this weekend.
