### ISSUE TITLE
Tasks failing behing proxy without a user or password since 5.3.1

### ISSUE THREAD

**Issue by markusadelsberger** [dependency-check/DependencyCheck#2546]
**Describe the bug**
Since the version 5.3.1 the any tasks fail for me. The problem seems to be the proxy configuration, the plugin attempts to load a username and a password, which our proxy does not use. When I set the required values in the gradle.properties (systemProp.http.proxyUser/proxyPassword), the plugin fails to find the method getNonProxyHosts().

**Version of dependency-check used**
The problem occurs using version 5.3.1 of the gradle plugin, rolling back to 5.3.0 resolves the issue.

**Log file**
I added 4 log files as [gist](https://gist.github.com/markusadelsberger/4557fa6157630172035acd214da78aac):

- [no_user_stacktrace.txt](https://gist.github.com/markusadelsberger/4557fa6157630172035acd214da78aac/raw/e620183197399ed29256ce14bec2470a7158c0b0/no_user_stacktrace.txt): Running in my default setup, with added switch --stacktrace
- [no_user_info.txt](https://gist.github.com/markusadelsberger/4557fa6157630172035acd214da78aac/raw/e620183197399ed29256ce14bec2470a7158c0b0/no_user_info.log): Running in my default setup, with added switch --info
- [bogo_user_stacktrace.log](https://gist.github.com/markusadelsberger/4557fa6157630172035acd214da78aac/raw/e620183197399ed29256ce14bec2470a7158c0b0/bogo_user_stacktrace.log): I added the properties `systemProp.http.proxyUser`, `systemProp.http.proxyPassword`, `systemProp.https.proxyUser` and `systemProp.https.proxyPassword`, with the values `user` and `password`, this gave me a different error.
- [bogo_user_info.log](https://gist.github.com/markusadelsberger/4557fa6157630172035acd214da78aac/raw/e620183197399ed29256ce14bec2470a7158c0b0/bogo_user_info.log): Same as bogo_user_stacktrace.log, but with added switch --info

**To Reproduce**
1. Use a proxy, set in gradle properties:

- `systemProp.proxySet=true`
- `systemProp.http.keepAlive=true`
- `systemProp.http.proxyHost=proxy`
- `systemProp.http.proxyPort=3128`
- `systemProp.http.nonProxyHosts=*.internal.domain|localhost|192.168.*|127.0.*`
- `systemProp.https.proxyHost=proxy`
- `systemProp.https.proxyPort=3128`
- `systemProp.https.nonProxyHosts=*.internal.domain|localhost|192.168.*|127.0.*`

2. Run the task `dependencyCheckAnalyze` or `dependencyCheckAggregate`

**Expected behavior**
The tasks should run.

**Additional context**
I am running the tasks on subprojects, maybe that makes a difference.

**Comment by Marx314** [comment]
duplicate of https://github.com/jeremylong/DependencyCheck/issues/2539 and https://github.com/jeremylong/dependency-check-gradle/issues/181

**Comment by markusadelsberger** [comment]
Agreed, is a duplicate, I'll close mine.
