### ISSUE TITLE
Downloader doesn't send SSL Client Certificates

### ISSUE THREAD

**Issue by JoepWeijers** [dependency-check/DependencyCheck#2555]
**Describe the bug**
We access our suppression files over the web (they are hosted on a Sonatype Nexus repository). Our company policy requires an SSL Client certificate to be sent when accessing that server remotely. 

I have the certificate set up and working for Maven. I copied that setup to a JAVA_TOOL_OPTIONS environment variable: `-Djavax.net.ssl.trustStore=[PATH_TO].jks -Djavax.net.ssl.trustStorePassword=[REDACTED] -Djavax.net.ssl.keyStore=[PATH_TO].p12 -Djavax.net.ssl.keyStoreType=pkcs12 -Djavax.net.ssl.keyStorePassword=[REDACTED] -Djavax.net.debug=all`

But the OWASP Dependency checker fails to access our suppression files, since it doesn't send my SSL Client Certificate, despite picking up the JAVA_TOOL_OPTIONS.

**Version of dependency-check used**
The problem has been verified to be present in version 5.2.1 of the cli and Maven. Since it is present in core, it probably affects all other versions as well.

**Log file**
https://gist.github.com/JoepWeijers/04ff717e81c8b576ad5ad4fd4a247ffc

**Expected behavior**
I expect the SSL Client certificates to be send with the request.

**Additional context**
In [URLConnectionFactory#L237](https://github.com/jeremylong/DependencyCheck/blob/master/utils/src/main/java/org/owasp/dependencycheck/utils/URLConnectionFactory.java#L237), you call the `new SSLSocketFactoryEx(settings);`, which sets the keystores and truststores to null, effectively removing them. 

The `SSLSocketFactoryEx` was introduced in 2014 with code copied from StackOverflow written in 2009. Maybe this can be replaced with something more modern that supports the keystores and truststores out of the box? If not (I can understand the wish to not introduce extra dependencies for http clients, or the wish for being compatible with very old java versions), could you then make it possible that the keystores and truststores are not completely ignored?

**Comment by JoepWeijers** [comment]
Seems issue #242 is also running into this when running the test suite back in 2015, but the provided solution there (skipping the tests) is not applicable for me.

**Comment by jeremylong** [comment]
In a lot of ways I want to rip out the current proxy configuration within ODC.  For your setup, if you have all of the correct proxy settings for Java setup - could you also just add `-Djava.net.useSystemProxies=true` to JAVA_OPTS and just not configure any proxy information in ODC itself? Alternatively, just setup all of the core Java proxy settings in JAVA_OPTS (`http.proxyHost`, `http.proxyPort`,...)?

**Comment by JoepWeijers** [comment]
Hi Jeremy thanks for the reply, but I'm not using a proxy. I have an SSL Client certificate that has to be sent with every request to my server.

**Comment by jeremylong** [comment]
My mistake - pretty sure this isn't working by default because we have an `SSLSocketFactory` extension that was put in place so older JVMs could download the data files from the NVD. I don't think this is actually needed anymore and I'm debating removing the extension.  In the meantime I have added

**Comment by jeremylong** [comment]
This should be fixed in the next release.
