### ISSUE TITLE
Is there a link for the latest stable build for the CLI client?

### ISSUE THREAD

**Issue by gtludwig** [dependency-check/DependencyCheck#2568]
We use this fantastic tool in our pipelines and would like to avoid having to update the link every time there is a new release.

We current download from: 

`https://dl.bintray.com/jeremy-long/owasp/dependency-check-5.3.1-release.zip`

And I was hoping to get the URL as something like:

`https://dl.bintray.com/jeremy-long/owasp/dependency-check-LATESTSTABLE.zip`

Is there such a thing already available?

**Comment by jeremylong** [comment]
The way most people do this is to call something like:

```
current=`curl https://jeremylong.github.io/DependencyCheck/current.txt` \
&& curl -O https://dl.bintray.com/jeremy-long/owasp/dependency-check-$current-release.zip
```

**Comment by jeremylong** [comment]
I suppose we should document that somewhere...
