### ISSUE TITLE
The root path doesn't contain parent files pom.xml

### ISSUE THREAD

**Issue by idaking** [dependency-check/DependencyCheck#2573]
Hi,jeremylong
I am using the maven plugin to scan the projects of spring, but I encounter this following problem:
The root path doesn't contain parent files pom.xml, while each file folder of child project contains one pom.xml, which forces jenkins or me to enter child project and carry out the scanning each time. However, I hope to accomplish the scanning logic similar to "aggregate".  Otherwise, I must create a file in which I need to put the tag of "modules" artificially.
I would appreciate it very much if you could tell me how to deal with this kind of situation.

**Comment by jeremylong** [comment]
I'm really not sure I understand the problem as described.  Do you have a sample project or can you describe the project layout?
