### ISSUE TITLE
Can I write the Jenkins global tool configuration for the Dependency Check as code?

### ISSUE THREAD

**Issue by Jonerc** [dependency-check/DependencyCheck#2578]
Hi,

We are using the Jenkins Dependency-Check plugin. We use Docker containers for our local and live Jenkins servers and all plugin configuration is handled by Groovy code.

Have you an example of configuring the Jenkins Dependency-Check global tool configuration as code? Or documentation on the configuration classes?

Apologies if I have missed this, I have been searching high and low for an example, and it may be that I cannot see the wood for the trees.

**Comment by stevespringett** [comment]
You might want to check the Jenkins Users Google Group: https://groups.google.com/d/forum/jenkinsci-users

Since this functionality is specific to Jenkins and not the Dependency-Check plugin, you're more likely to find people with examples there.

**Comment by Jonerc** [comment]
Okay will do, thanks for the quick response.
