### ISSUE TITLE
AnalysisException after mis-identifying component with the name "security"

### ISSUE THREAD

**Issue by nguyenquoc** [dependency-check/DependencyCheck#2579]
**Describe the bug**
I have a maven component that has coordinates like:
```
<groupId>com.mycompany.security</groupId>
<artifactId>security-spi</artifactId>
```
dependency-check incorrectly identifies the component as "security-framework_project:security-framework:-", and then errors out when it cannot locate CPE's for that component, which has nothing to do with my component other than they both have the name "security".

My security-spi jar file is archived in a top level spring-boot application jar. dependency-check can exclude the top level jar, but cannot exclude child jar's within the top level jar (e.g. "dependency-check -s . --exclude '**/security*.jar' " does not do what I expect it to do, and has no effect on excluding the undesired results)

**Version of dependency-check used**
The problem occurs using version 5.3.0-5.3.2 of the cli

**Log file**
Command line output: 
https://gist.github.com/nguyenquoc/7f9c0d220ff2d11924f1a2822077dbb9

Relevant error from log file is:
https://gist.github.com/nguyenquoc/6a20e5bec3a5731562285dcb28dff4ac

Sorry, I couldn't figure out how to upload the 73 MB log file to gist.

**To Reproduce**
1. create a maven artifact:
```
<groupId>com.mycompany.security</groupId>
<artifactId>security-spi</artifactId>

```
2. run dependency-check on it

**Expected behavior**
dependency-check could give a warning, but it should not error out, since I rely on the error status to determine whether there is a vulnerability.

**Additional context**
An alternative fix would be to provide a way to exclude child jars within a parent jar.

**Comment by jeremylong** [comment]
This is not a bug exactly - rather this is just a false positive that can occur. Please see https://jeremylong.github.io/DependencyCheck/general/internals.html.

**Comment by nguyenquoc** [comment]
I don't agree that this is a false positive. I can suppress false positive with:

`dependency-check --suppression <suppression_file>`

That does not work in this case because dependency-check not reporting a vulnerability, but is throwing an error because it cannot find information about the component that it is looking for:

`
[ERROR] Unable to create a CPE for security-framework_project:security-framework:-
`

**Comment by jeremylong** [comment]
@nguyenquoc sorry about misunderstanding the issue here - however, I am unable to reproduce this issue. I would need the full log (`-l odc.log`) or a sample project.

**Comment by nguyenquoc** [comment]
The problem does not occur with dependency-check 6.0.2. Thanks very much for unknowingly fixing the problem! Issue closed since it no longer occurs with the latest version.
