### ISSUE TITLE
Does DependencyCheck Support Nexus OSS version 3.19.1-01?

### ISSUE THREAD

**Issue by alienscience** [dependency-check/DependencyCheck#2582]
I am having problems getting the dependency check to work with a private Nexus. I believe this is caused by DependencyCheck not supporting Nexus OSS version 3.

Am  I right that this Nexus OSS version is not supported, or should I keep trying?

**Comment by jeremylong** [comment]
I do not have a nexus server. The nexus support was provided via a PR. In reality - if you are using Maven or Gradle you will not get any benefit from using the Nexus Analyzer.
