### ISSUE TITLE
dependency-check-core seems to pull in vulnerable jquery-3.4.1

### ISSUE THREAD

**Issue by jwkoelewijn** [dependency-check/DependencyCheck#2593]
**Describe the bug**

dependency-check-core has as one of its template/scripts jquery-3.4.1 which is vulnerable, resulting in false positives.

I have chosen to report this as a bug, rather than a false positive, as it does not report on my own pulled in jquery version, but rather on the one dependency-check-core has bundled, as can be seen in the screenshot:

**Version of dependency-check used**
The problem occurs using version 3.5.1 of the dependency-check (cli, gradle plugin, maven plugin, etc.)

**Log file**
When reporting errors, 99% of the time log file output is required. Please post the log file as a [gist](https://gist.github.com/) and provide a link in the new issue.

https://gist.github.com/jwkoelewijn/e903f4efc50aab202b830a9787528b70

**Expected behavior**
I would expect my own pulled in jquery to be checked, rather than the one pulled in by dependency-check

**Additional context**
Noticed the problem after a genuine vulnerability was reported on jquery < 3.5.0, which caused us to update after a new version was released on webjars. However, dependency check would keep failing. After careful investigation, turned out the vulnerability existed within the dependency-check jar file.

**Comment by jeremylong** [comment]
After review of the reported vulnerability we do not believe the HTML report is affected. The jquery upgrade will be included in the next release.
