### ISSUE TITLE
Maven build hangs

### ISSUE THREAD

**Issue by iriusrisk** [dependency-check/DependencyCheck#26]
Added the plugin to maven build.  Run mvn package, the build hangs at the dependency-check plugin and doesn't proceed (Waited 30 minutes).

mvn -X output:

[DEBUG] Configuring mojo org.owasp:dependency-check-maven:1.0.2:check from plugin realm ClassRealm[plugin>org.owasp:dependency-check-maven:1.0.2, parent: sun.misc.Launcher$AppClassLoader@affc70]
[DEBUG] Configuring mojo 'org.owasp:dependency-check-maven:1.0.2:check' with basic configurator -->
[DEBUG](f) autoUpdate = true
[DEBUG](f) description = A report providing details on any published vulnerabilities within project dependencies. This report is a best effort but may contain false positives and false negatives.
[DEBUG](f) externalReport = false
[DEBUG](f) failBuildOnCVSS = 8.0
[DEBUG](f) format = HTML
[DEBUG](f) name = Dependency-Check
[DEBUG](f) outputDirectory = /home/training/spring-secure-sample/target
[DEBUG](f) reportName = dependency-check-report
[DEBUG](s) reportOutputDirectory = /home/training/spring-secure-sample/target/site
[DEBUG](f) project = MavenProject: net.continuumsecurity:spring-secure-sample:1.0-SNAPSHOT @ /home/training/spring-secure-sample/pom.xml
[DEBUG] -- end configuration --

**Comment by jeremylong** [comment]
Unfortunately I've seen this happen too. What is taking so long is that it
is downloading the entire NVD from NIST.

The two reasons that can cause this to hang:
1) Slow internet connection (even on a fast connection I've waited 15
minutes, but I've also seen it take 20+ minutes).
2) Glitch in the downloading, I've seen it hang on a single file. I've
tried to figure out a reason for this and even setting a connection timeout
doesn't seem to help.

Solution/workaround: This only happens during the initial download of data.
Run the build with dependency-check enabled before going to bed and let it
run for as long as it needs. If subsequent builds are run (on any project)
using the plugin at least once every seven days only a tiny XML file needs
to be downloaded and processed.

Additionally, I am working on a new batch update mode that will be much
faster. I'm hoping to have this finished soon (but I also have to find a
host to distribute the batch file).

In the meantime, I'll try and figure out why the info/warning messages
stopped appearing in the maven builds as they give a clue as to why the
process is taking so long.

Best Regards,

Jeremy

**Comment by iriusrisk** [comment]
Left it overnight and it worked.  It is a thing of beauty :)
