### ISSUE TITLE
[ERROR] java.io.EOFException: Expected to read bytes from the stream

### ISSUE THREAD

**Issue by darshanmhatre** [dependency-check/DependencyCheck#2601]
**Describe the bug**
I am getting EOF exception while running DependencyCheck-5.3.2. 
Note: I am still getting dependency-check-report.xml

**Version of dependency-check used**
The problem occurs using version 5.3.2 of the DependencyCheck(Cli)

**Log file**
WHS-1625:decompscript darshanmhatre$ ~/Downloads/dependency-check-5.3.2/bin/dependency-check.sh --project testing --scan ./webgoat/ --format XML -disableOssIndex --enableExperimental --disableCentral --disableRetireJS
[INFO] Checking for updates
[INFO] Skipping NVD check since last check was within 4 hours.
[INFO] Check for updates complete (80 ms)
[INFO] 

Dependency-Check is an open source tool performing a best effort analysis of 3rd party dependencies; false positives and false negatives may exist in the analysis performed by the tool. Use of the tool and the reporting provided constitutes acceptance for use in an AS IS condition, and there are NO warranties, implied or otherwise, with regard to the analysis or its use. Any use of the tool and the reporting provided is at the user’s risk. In no event shall the copyright holder or OWASP be held liable for any damages whatsoever arising out of or in connection with the use of this tool, the analysis performed, or the resulting report.

[INFO] Analysis Started
[INFO] Finished Archive Analyzer (0 seconds)
[INFO] Finished File Name Analyzer (0 seconds)
[INFO] Finished Jar Analyzer (0 seconds)
[ERROR] ----------------------------------------------------
[ERROR] .NET Assembly Analyzer could not be initialized and at least one 'exe' or 'dll' was scanned. The 'dotnet' executable could not be found on the path; either disable the Assembly Analyzer or add the path to dotnet core in the configuration.
[ERROR] ----------------------------------------------------
[INFO] Finished Python Distribution Analyzer (0 seconds)
[WARN] An error occurred while analyzing '/Users/darshanmhatre/decompscript/webgoat/jna-4.1.0.jar/com/sun/jna/w32ce-arm/jnidispatch.dll' (PE Analyzer).
[INFO] Finished PE Analyzer (0 seconds)
[INFO] Finished Dependency Merging Analyzer (0 seconds)
[INFO] Finished Version Filter Analyzer (0 seconds)
[INFO] Finished Hint Analyzer (0 seconds)
[INFO] Created CPE Index (1 seconds)
[INFO] Finished NPM CPE Analyzer (1 seconds)
[INFO] Created CPE Index (0 seconds)
[INFO] Finished CPE Analyzer (1 seconds)
[INFO] Finished False Positive Analyzer (0 seconds)
[INFO] Finished NVD CVE Analyzer (0 seconds)
[INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
[INFO] Finished Dependency Bundling Analyzer (0 seconds)
[INFO] Analysis Complete (4 seconds)
[ERROR] java.io.EOFException: Expected to read bytes from the stream

**To Reproduce**
Link for the codebase : https://github.com/darshanmhatre/webgoat.git
Depcheck command used : dependency-check-5.3.2/bin/dependency-check.sh --project testing --scan ./webgoat/ --format XML -disableOssIndex --enableExperimental --disableCentral --disableRetireJS
**Expected behavior**
It should run without java.io.EOFException.

**Comment by jeremylong** [comment]
A patch will be included in the next release.
