### ISSUE TITLE
[WARN] Exception extracting archive 'InetSuiteNet.zip'

### ISSUE THREAD

**Issue by melucas** [dependency-check/DependencyCheck#2602]
How do I resolve this warning message when running dependency-check on Windows 10 with the latest Java updates installed:

[WARN] Exception extracting archive 'InetSuiteNet.zip'

The command line used is:
"dependency-check.bat" -scan "H:/Code/" --project "Code" --out "H:/Code/_ScanReports" --disableNodeAudit

**Comment by jeremylong** [comment]
Add `--log odc.log` to get more information about the error.  Is InetSuiteNet.zip a standard zip file? Can you extract its contents using another tool or is the file corrupted in some way?

**Comment by melucas** [comment]
The log file does not contain the error message or the name of the zip file.
However, I did do a search of source code folders I was scanning and found InetSuiteNet.zip.  It is a 3rd party provided password protected zip file.  That solves my problem.  I thought it was and update DependencyCheck was trying to download.

Thanks for the help!
