### ISSUE TITLE
Dependency check is blocked forever during Initialization of the CPE Analyzer

### ISSUE THREAD

**Issue by doctorhorribe** [dependency-check/DependencyCheck#2603]
[dc-maven-blocking-REDACTED.txt](https://github.com/jeremylong/DependencyCheck/files/4509679/dc-maven-blocking-REDACTED.txt)
Hi,
On our server the dependency check is always blocked. The last lines of output that we see, in debug mode, are these ones:
```
[main] [INFO] Analysis Started
[main] [INFO] Finished Archive Analyzer (0 seconds)
[main] [INFO] Finished File Name Analyzer (0 seconds)
[main] [INFO] Finished Jar Analyzer (0 seconds)
[main] [INFO] Finished Dependency Merging Analyzer (0 seconds)
[main] [INFO] Finished Version Filter Analyzer (0 seconds)
[dc-maven-blocking-REDACTED.txt](https://github.com/jeremylong/DependencyCheck/files/4509669/dc-maven-blocking-REDACTED.txt)

[main] [INFO] Finished Hint Analyzer (0 seconds)
[main] [DEBUG] Initializing CPE Analyzer
```

We are using the version 5.3.2. I tried to debug the code, the blocking occurs when opening the local copy of the CPE database.
This happens on a Linux server used for build. When I however copy the Java projects to my local Windows machine and run the code there, then it's all fine.

I attach the full output from the maven goal, with debug mode. Specific information, like paths and URLs, are redacted.

Do you know whether these issues were experienced by someone before? If so, how do we bypass it? It's clearly related to platform/settings, since on my local PC it works with the same code. However copying everything on local is immensely impractical.

Thank you very much for your help.
Kind regards,
Daniel.
[dc-maven-blocking-REDACTED.txt](https://github.com/jeremylong/DependencyCheck/files/4509688/dc-maven-blocking-REDACTED.txt)

**Comment by jeremylong** [comment]
Sorry for the extremely delayed response - I missed this question previously.  I'm not sure why it would be blocking here - is the build server memory constrained in any way?  Does this occur in 6.0.x?
