### ISSUE TITLE
Windows 10, Apache Maven plugin: Pretty printed JUnit report can't be renamed

### ISSUE THREAD

**Issue by bohni** [dependency-check/DependencyCheck#2605]
**Describe the bug**
Pretty printed JUnit report keeps `.pretty` file extension, because deleting file fails.
Works on Manjaro Linux, fails on Windows 10 (Home and Pro)

```
dependency-check-junit.xml.pretty
````

**Version of dependency-check used**
```
<plugin>
    <groupId>org.owasp</groupId>
    <artifactId>dependency-check-maven</artifactId>
    <version>5.3.2</version>
    <configuration>
        <formats>junit</formats>
        <prettyPrint>true</prettyPrint>
    </configuration>
</plugin>
```

**Log file**
```
[INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
[INFO] Finished Dependency Bundling Analyzer (0 seconds)
[INFO] Analysis Complete (29 seconds)
[ERROR] Unable to generate pretty report, caused by: Failed to delete original file 'C:\...\path\...\target\dependency-check-junit.xml.pretty' after copy to 'C:\...\path\...\target\dependency-check-junit.xml'
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```
**To Reproduce**
1. Create Java-Maven-Project
2. Add dependency-check-maven plugin to pom.xml with configuration (see above)
2. run `mvn clean dependency-check:check`
3. Open target folder
4. See filename with wrong extension

**Expected behavior**
junit filename should have `.pretty` extension removed, leading to `.xml` extension

**Comment by jeremylong** [comment]
I'm not able to exactly reproduce the described problem. However, I believe I may have found the issue. Your configuration is slightly wrong - you need to specify `<format>` not `<formats>`:

So your configuration would look like:
```xml
    <configuration>
        <format>junit</format>
        <prettyPrint>true</prettyPrint>
    </configuration>
```

or
```xml
    <configuration>
        <formats>
            <format>junit<format>
         </formats>
        <prettyPrint>true</prettyPrint>
    </configuration>
```

I have also improved the input validation of the formats; which will be included in 5.4.0.

**Comment by bohni** [comment]
OK, sorry - I use JUNIT and HTML as formats and removed HTML for readability...

Here is a sample project, that does not work. 
It is created as a simple download from start.spring.io changing only maven coordinates .
Then adding the depoendency-check-maven plugin to pom.xml

https://github.com/bohni/dep-check

format and formats both do not work.

**Comment by jeremylong** [comment]
I'm still unable to reproduce as I'm on a mac - but I believe this should be fixed. We added a short sleep between the delete and rename operations.

**Comment by bohni** [comment]
Ah, ok. Mac OS is based on Linix/Unix. I can confirm, that on Linux this also works with current version.

Will try fixed version on Windows.

Thanks.

**Comment by valentijnscholten** [comment]
I had to add ".pretty"in my unit tests as well to get them to work on Windows 10, could be the same issue: https://github.com/jeremylong/DependencyCheck/pull/2609/files#diff-4bfdc0a6f106eff1520fda1d570e25d9R193
