### ISSUE TITLE
Initial download took 6 hours - where can I obtain debug/logs?

### ISSUE THREAD

**Issue by namloc2001** [dependency-check/DependencyCheck#2611]
Hi, I'm running this on OpenShift, deploying via helm charts. Using v5.3.2 and a separate postgresql database accessed via K8s service, it took ~6hrs to perform a database load from scratch. I checked CPU and RAM for both dependency check and postgres, majority or time CPU idle for both was >70% and RAM always appeared to have a large cache quantity as well as unused.

Dep Check has 3CPU and 4GB RAM
Postgresql has 4CPU and 4GB RAM

I'd like to try and do some root cause analysis, but can't find any documentation on this. Thanks in advance, Matt.

Log of duration:
![image](https://user-images.githubusercontent.com/30868661/80281369-7cb2d300-8702-11ea-9b09-5050eb5da987.png)

File sizes during download/process etc:
![image](https://user-images.githubusercontent.com/30868661/80281379-8e947600-8702-11ea-910d-5dc0c3ce0ea0.png)

**Comment by jeremylong** [comment]
The CLI options can be found here: https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html

You can generate a log file by adding `--log odc.log`.

We've had several reports that creating the external databases can take a LONG time. However, we have not had time to debug the problem.

**Comment by aravindparappil46** [comment]
I can confirm that the problem still [exists](https://github.com/jeremylong/DependencyCheck/issues/2700) with the latest version. It took **13+ hours** for me (didn't finish yet. Had to stop the process)
Is there a known temporary workaround/band-aid for this? Like, using an older version?

**Comment by severn-everett** [comment]
@aravindparappil46 The step to remove the CPE ecosystem was introduced in `5.3.1`, so reverting back to `5.3.0` worked for us.

**Comment by jeremylong** [comment]
@aravindparappil46  PR #2610 does improve the performance of that step considerably - this will be included in the 6.0.0 release.
