### ISSUE TITLE
Alternatives to local Nexus server

### ISSUE THREAD

**Issue by mr-duke** [dependency-check/DependencyCheck#2617]
Hi,
The documentation says:
> If Central cannot be reached, it is highly recommended to setup a Nexus server within your organization and to configure dependency-check to use the local Nexus server.

Are there alternative repositories dependency-check can use if there's no Nexus server available in the organization? If so, do they need special configuration?

**Comment by jeremylong** [comment]
That documentation needed to be updated. The Central and Nexus Analyzers only assist the CLI and Ant plugin. If you are using Maven, Gradle, sbt, etc. there is no real benefit to using the Central or Nexus Analyzers. In fact, in the Maven and Gradle plugins these are disabled by default.

If you are using the Ant plugin or CLI - then there is a chance that for your Java dependencies that you may have an increase in false positives and false negatives.

**Comment by mr-duke** [comment]
Thank you!
