### ISSUE TITLE
DependencyCheck build failed at Core module

### ISSUE THREAD

**Issue by ryalamanchi** [dependency-check/DependencyCheck#2621]
**Describe the bug**
I cloned the latest D-C repo and ran maven install command as per instructions in the README. The test (ReportGeneratorIT.testGenerateReport) in the Core module failed with the error below.
 
`git clone --depth 1 https://github.com/jeremylong/DependencyCheck.git`
`mvn -s settings.xml install`

**Error:**
[ERROR] Failures:
[ERROR]   ReportGeneratorIT.testGenerateReport:76->generateReport:206 //DependencyCheck/core/target/test-reports/Report.xml.pretty (No such file or directory)
[ERROR] Errors:
[ERROR]   VulnerabilitySuppressionAnalyzerIT.testAnalyze:71->BaseTest.getResourceAsFile:92 » NullPointer
Error at: https://github.com/jeremylong/DependencyCheck/blob/master/core/src/test/java/org/owasp/dependencycheck/reporting/ReportGeneratorIT.java#L193
[INFO] Dependency-Check ................................... SUCCESS [  9.680 s]
[INFO] Dependency-Check Utils ............................. SUCCESS [ 36.582 s]
[INFO] Dependency-Check Core .............................. FAILURE [06:06 min]
[INFO] Dependency-Check Command Line ...................... SKIPPED
[INFO] Dependency-Check Ant Task .......................... SKIPPED
[INFO] Dependency-Check Maven Plugin ...................... SKIPPED
[INFO] Dependency-Check Plugin Archetype .................. SKIPPED

This might be the **root cause**: 
By looking at review changes, 4 days back, added changes to ReportGeneratorIT.generateReport: 
https://github.com/jeremylong/DependencyCheck/pull/2609/files/425da786b3c626bff3282c567d1f7b84d0a2f86a

**Version of dependency-check used**
org.owasp:dependency-check-parent:5.3.3-SNAPSHOT

**Error log** in failsafe-report --> org.owasp.dependencycheck.reporting.ReportGeneratorIT.txt:
-------------------------------------------------------------------------------
Test set: org.owasp.dependencycheck.reporting.ReportGeneratorIT
-------------------------------------------------------------------------------
Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 36.164 s <<< FAILURE! - in org.owasp.dependencycheck.reporting.ReportGeneratorIT
testGenerateReport(org.owasp.dependencycheck.reporting.ReportGeneratorIT)  Time elapsed: 6.793 s  <<< FAILURE!
java.lang.AssertionError: //DependencyCheck/core/target/test-reports/Report.xml.pretty (No such file or directory)
	at org.owasp.dependencycheck.reporting.ReportGeneratorIT.generateReport(ReportGeneratorIT.java:206)
	at org.owasp.dependencycheck.reporting.ReportGeneratorIT.testGenerateReport(ReportGeneratorIT.java:76)

**Additional Info**
- Not behind any proxy 
- java version "1.8.0_73"
- Apache Maven 3.3.9
- getting the same error in IDE & CLi

Any help is appreciated.

**Comment by jeremylong** [comment]
Sorry about this.  The build was unstable for a bit.  Should be fixed now.
