### ISSUE TITLE
gradle-plugin does not create XML report

### ISSUE THREAD

**Issue by aristasi** [dependency-check/DependencyCheck#2624]
Hi all,

I use `'org.owasp:dependency-check-gradle:5.3.2'` `gradle 4.1` and I add in `build.gradle`:
```
dependencyCheck {
    autoUpdate=false
    cveValidForHours=1
    format='XML'
}
```
I also tried `format='ALL'`. 

When I use the command locally: 
`/gradlew dependencyCheckAnalyze -Ddownloader.quick.query.timestamp=false -Pformat=XML` 
or 
`/gradlew dependencyCheckAnalyze `
I take only an html report in build/reports folder. Does anyone know how could I create an XML report? 

Thanks!

**Comment by jeremylong** [comment]
I just re-tested this with gradle 4.1 and everything worked on my system. So a couple of questions:

1. You have `autoUpdate=false` - have you run an update recently?
2. Do you have a multi-project build? If so, try running `gradle clean dependencyCheckAggregate`.

Your configuration appears to be correct - so the last thing would be to run `gradle dependencyCheckAnalyze --debug` and review the output for any errors.
