### ISSUE TITLE
FailOnVulnerability Flag 

### ISSUE THREAD

**Issue by DanielOstovary** [dependency-check/DependencyCheck#2625]
I have integrated the ODC in my build process in a way that if the ODC finds a vulnerability the build fails. For that I use the flag failOnCVSS=0 (i.e. the ODC should fail if vulnerabilities with CVSS >= 0 are found). If the ODC fails, I know I need to take action (e.g. hot-fix/patch a vulnerability or suppress a false-positive). Unfortunately not every vulnerability has a CVSS, so the ODC does not always fail when it finds a vulnerability. I encountered this problem with the recent jQuery 3.4 XSS vulnerability (https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/). Though the ODC reported this vulnerability, it did not fail because the vulnerability has no CVSS.

An option to always let the ODC fail when it finds a vulnerability would be great. This would allow users of the ODC to integrate the ODC in their build process and always know if they need to take action, not only for vulnerabilities that have a CVSS. 

Best regards,
Daniel

**Comment by shm0sby** [comment]
I'd really appreciate that. Currently I didn't know there were vulnerabilities which are not rated.

**Comment by jeremylong** [comment]
When 6.0.4 is released - when you put zero as the `failOnCvssScore` the build will fail on any vulnerability.
