### ISSUE TITLE
False Positive on org.slf4j:log4j-over-slf4j:1.7.30

### ISSUE THREAD

**Issue by IdamkinI** [dependency-check/DependencyCheck#2626]
False positive on library `log4j-over-slf4j-1.7.30.jar` - reported as `cpe:2.3:a:apache:log4j:1.7.30:*:*:*:*:*:*:*`
```xml
<!-- https://mvnrepository.com/artifact/org.slf4j/log4j-over-slf4j -->
<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>log4j-over-slf4j</artifactId>
    <version>1.7.30</version>
</dependency>
```

Might be related to #2619

**Comment by chadlwilson** [comment]
Are you still seeing this? My issue on the linked ticket went away at some point in the last few months; so perhaps this can be closed.

**Comment by jeremylong** [comment]
Tested with 6.0.2 and this isn't being reported.

**Comment by Snipx** [comment]
Reproduced with 6.0.2 on my machine but works well with 6.0.3
