### ISSUE TITLE
dependency-check-report.html is not being generated with aggregate goal and modules option

### ISSUE THREAD

**Issue by vveider** [dependency-check/DependencyCheck#2635]
**Describe the bug**
Running `org.owasp:dependency-check-maven:5.2.0:aggregate` goal on project generates single HTML report, while adding `-pl module1, module2,... -am` does not.

**Version of dependency-check used**
maven plugin 5.2.0

Are there any undocumented limitations about that?

**Comment by mprins** [comment]
- does that also happen with a current version of the plugin?
- does your parent pom have all modules listed?

**Comment by vveider** [comment]
Found that problem is solved with adding final module name (from root `pom.xml`). Guess it is not the problem of OWASP, but some documentation update seems to be required.

Can I help with that somehow?

**Comment by jeremylong** [comment]
We accept PRs - the documentation is in the repo. If something is unclear or a tip can be added - please submit a PR.

Thanks!

**Comment by vveider** [comment]
@jeremylong - can you pinpoint the exact path to documentation, or should I make PR for README in root?

**Comment by jeremylong** [comment]
Each src/site directory contains the markdown used to generate the documentation site: https://jeremylong.github.io/DependencyCheck/

Maven documentation: https://github.com/jeremylong/DependencyCheck/tree/master/maven/src/site/markdown
Main page: https://github.com/jeremylong/DependencyCheck/tree/master/src/site/markdown
