### ISSUE TITLE
Unable to update dependency-check database

### ISSUE THREAD

**Issue by Trojans-dev** [dependency-check/DependencyCheck#2636]
I was getting these error while I was running a scan.
![image](https://user-images.githubusercontent.com/65243538/81718970-0c45d900-949a-11ea-8ef3-3e8414b15966.png)

**Comment by Trojans-dev** [comment]
Can you please look at these issue and tell me the solution how can I solve this as soon as possible.

**Comment by mprins** [comment]
please describe what you are doing and provide full debug log, right now it just looks like you're doing it wrong.

using the template really helps: https://github.com/jeremylong/DependencyCheck/issues/new?assignees=&labels=bug&template=bug_report.md&title=

**Comment by Trojans-dev** [comment]
I downloaded 5.3.2 version from the GitHub and I started scanning the job from Jenkins and Mean while I got these error.
Will it take much time for connecting to the database?

**Comment by Trojans-dev** [comment]
Iam unable to connect to NVD database

**Comment by jeremylong** [comment]
We would need the details of what you are trying to do - i.e. the actual commands, configurations, and the actual log file to assist.  We can't assist with vague "it doesn't work" style questions.
