### ISSUE TITLE
Unable to connect dependency-check database

### ISSUE THREAD

**Issue by Trojans-dev** [dependency-check/DependencyCheck#2637]
**Describe the bug**
Unable to connect to NVD database

**Version of dependency-check used**
The problem occurs using version X.X.X of the __5.3.2__ (cli, gradle plugin, maven plugin, etc.)

**Log file**
![image](https://user-images.githubusercontent.com/65243538/81773257-8b242b80-9505-11ea-8ec3-1f28e0a5c2fa.png)

**To Reproduce**

**Expected behavior**
If I connect to NVD database scan should become success

**Additional context**

**Comment by Trojans-dev** [comment]
Can you solve the issue as soon as possible?

**Comment by Trojans-dev** [comment]
![image](https://user-images.githubusercontent.com/65243538/81776896-55834080-950d-11ea-8201-d48a8724ce71.png)
Now I was getting these exception

**Comment by jeremylong** [comment]
You would need to provide the actual log file from ODC as opposed to just a stack trace. If you are using the command line you would just add `--log odc.log`.  Looking at what you have posted it appears to be a file permission issue.
