### ISSUE TITLE
Scan JS npm -  NodeAuditAnalyzer failed

### ISSUE THREAD

**Issue by ErezDasa** [dependency-check/DependencyCheck#2648]
Version - 5.3.2

When I try to scan JS dependencies iv'e got this errors+warn:

```
[INFO] Analysis Started
[INFO] Finished File Name Analyzer (0 seconds)
```
**[WARN] Analyzing `C:\xxxxxxx\package-lock.json` - however, the node_modules directory does not exist. Please run `npm install` prior to running dependency-check
[WARN] Analyzing `C:\xxxxxxx\npm-shrinkwrap.json` - however, the node_modules directory does not exist. Please run `npm install` prior to running dependency-check**

```
[INFO] Finished Node.js Package Analyzer (0 seconds)
[INFO] Finished Dependency Merging Analyzer (0 seconds)
[INFO] Finished Version Filter Analyzer (0 seconds)
[INFO] Finished Hint Analyzer (0 seconds)
[INFO] Created CPE Index (1 seconds)
[INFO] Finished CPE Analyzer (1 seconds)
[INFO] Finished False Positive Analyzer (0 seconds)
[INFO] Finished NVD CVE Analyzer (0 seconds)
```
**[ERROR] NodeAuditAnalyzer failed on C:\xxxxxxxx\package-lock.json**
**[WARN] An error occurred while analyzing 'C:\xxxxxxxx\package-lock.json' (Node Audit Analyzer).**

```
[INFO] Finished Node Audit Analyzer (2 seconds)
[INFO] Finished RetireJS Analyzer (0 seconds)
[INFO] Finished Sonatype OSS Index Analyzer (0 seconds)
[INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
[INFO] Finished Dependency Bundling Analyzer (0 seconds)
[INFO] Analysis Complete (4 seconds)
```
**[ERROR] Could not perform Node Audit analysis. Invalid payload submitted to Node Audit API**.`

Anyway, despite those errors, the scan is finished and I've got my report but i'm afraid the report are not completed because of those errors and maybe i missed some vulnerabilities.

Any ideas?

Thank you!

**Comment by ErezDasa** [comment]
@jeremylong any help will be appreciated.
Thank you!

**Comment by jeremylong** [comment]
I'm not sure how much more help I could be.  Did you read the error message and do what it stated?  I.e. run `npm install` on your node application?
