### ISSUE TITLE
"Content is not allowed in prolog." error in Azure DevOps when specifying an xml file

### ISSUE THREAD

**Issue by ojasp** [dependency-check/DependencyCheck#2654]
I have added an xml file to our source control and it looks like a legit xml file ot me, however the build fails because Dependency checker cannot parse the xml file. Here is the contents of the xml file:

```
<?xml version="1.0" encoding="UTF-8"?>
<suppressions xmlns="https://jeremylong.github.io/DependencyCheck/dependency-suppression.1.3.xsd">
   <suppress>
      <notes><![CDATA[
      file name: Microsoft.VisualStudio.Web.CodeGeneration.Design:2.2.4
      ]]></notes>
      <packageUrl regex="true">^pkg:nuget/Microsoft\.VisualStudio\.Web\.CodeGeneration\.Design@.*$</packageUrl>
      <cpe>cpe:/a:microsoft:visual_studio_code</cpe>
   </suppress>
</suppressions>
```
I have tried to parse the file with and without the xml tag in the first line but I get the same error both the times. Please help!

**Comment by ojasp** [comment]
For anyone else who comes across this, if you are using Visual Studio to create an xml, then the default encoding is utf-8-BOM. I had to open the file in Notepad++ and change the encoding to utf-8. Once I checked it in, the dependency checker task ran successfully.

**Comment by jeremylong** [comment]
Correct handling of the BOM was just implemented for both reading the suppression files and hint files. This will be included in the next release.
