### ISSUE TITLE
How to generate aggregated report for multi-module maven project through maven command?

### ISSUE THREAD

**Issue by nasifimtiazohi** [dependency-check/DependencyCheck#2656]
Hi, 

I want to generate an aggregated report in CSV format for a multi-module maven project.

I can do it through editing the `pom.xml` file by adding (once I have already run a check):

```
                     <plugin>
	             <groupId>org.owasp</groupId>
	                <artifactId>dependency-check-maven</artifactId>
	                <version>5.3.2</version>
	                <configuration>
	                <reportSets>
	                    <reportSet>
	                        <reports>
	                            <report>aggregate</report>
	                        </reports>
	                    </reportSet>
	                </reportSets>
	                </configuration>
	            </plugin>
```
Although it still only works for `html` format. Doesn't work when I add the `csv` format. I get a blank csv file in the root target directory no matter what I do.

However, for my purpose I don't have the ability to edit the `pom.xml` file. I need to do it through a maven command. Something like:
`mvn org.owasp:dependency-check-maven:check -Dformat=CSV -D<aggregate>`
How can I do it?

**Comment by nasifimtiazohi** [comment]
Ok, seems like 
`mvn org.owasp:dependency-check-maven:aggregate -Dformat=CSV` has done the trick.

**Comment by akomakom** [comment]
> -Dformat=CSV

Is this expected to work in the current version?  This has no effect for me, I only get HTML (default).  Tried all formats, both `-Dformat` and `-Dformats`, etc.  Didn't work with 5.3.2 either: ` mvn org.owasp:dependency-check-maven:5.3.2:aggregate -Dformat=CSV`

It would be great not to have to modify many established poms just to run a scan.

**Comment by jeremylong** [comment]
`mvn org.owasp:dependency-check-maven:5.3.2:aggregate -Dformat=CSV` produces the CSV output on my machine.  Are you sure you didn't typo it and put -Dformats=CVS?
