### ISSUE TITLE
False Positive on gradle

### ISSUE THREAD

**Issue by tmyroadctfig** [dependency-check/DependencyCheck#2657]
We've got a false positive on one of our internal jars for gradle. The report has:
`cpe:2.3:a:gradle:gradle:0.4.0:*:*:*:*:*:*:*  (Confidence:Low) `

And I think it's coming from a line in the MANIFEST.MF which has:
```
Manifest-Version: 1.0
Built-With: gradle-5.0, groovy-2.5.4
```

Seems to be another variation of "built-by":
https://github.com/jeremylong/DependencyCheck/blob/master/core/src/main/java/org/owasp/dependencycheck/analyzer/JarAnalyzer.java#L114

**Comment by jeremylong** [comment]
Thank you for pointing out the fix location for this - really appreciate it!
