### ISSUE TITLE
Reactor dependencies not cought

### ISSUE THREAD

**Issue by mbenz89** [dependency-check/DependencyCheck#2662]
When analyzing maven reactor projects, reactor dependencies are not properly resolved if they are non-snapshot dependencies. In the case of snapshot dependencies, the following block is taken that adds the reactor dependency to the list of all dependencies: https://github.com/jeremylong/DependencyCheck/blob/a479c8c1a58b8d06c78dbf391f4d73be81a23ef6/maven/src/main/java/org/owasp/dependencycheck/maven/BaseDependencyCheckMojo.java#L1218

In the case of non-snapshot reactor dependencies, the dependency will never be added to the list of dependencies. E.g., when analyzing https://github.com/eclipse-cognicrypt/CogniCrypt, the dependency `de.cognicrypt.core` located in `plugins/de.cognicrypt.core/target/classes` will not be added to the list of dependencies during the analysis of the `de.cognicrypt.crysl.handler` reactor module.

It seems that transitive dependencies of this reactor dependencies are still added. Thereby no vulnerabilities go missing. But the dependency collection mechanism just does not return the full picture. 

I wonder if this is a deliberate decision. If so, why are snapshot reactor modules added but non-snapshot modules not? From my current point of view, the reactor dependencies should be added by removing the `isSnapshot` check and change the call to `addReactorDependency` in https://github.com/jeremylong/DependencyCheck/blob/a479c8c1a58b8d06c78dbf391f4d73be81a23ef6/maven/src/main/java/org/owasp/dependencycheck/maven/BaseDependencyCheckMojo.java#L1218
.

If you agree, I could open a PR. I wanted to check in if there is a misconception on my side first, though.

**Comment by aikebah** [comment]
Only snapsots are considered there as they are subject to change over time and therefor should not rely on the dependency information retrieved from the repository, which may be stale (as per #1527), but use the dependency information in the reactor.
