### ISSUE TITLE
What is the correct syntax for enabling python analyzer on jenkins

### ISSUE THREAD

**Issue by anshbansal** [dependency-check/DependencyCheck#2663]
I tried using this syntax for doing the dependency check on Jenkins but it is not showing up any vulnerabilities for our code. 

```
stage("Dependency Check Vulnerabilities") {
            steps {
                dependencyCheck skipOnUpstreamChange: false, odcInstallation: 'DefaultDependencyCheck', additionalArguments: ''
                dependencyCheckPublisher pattern: '**/dependency-check-report.*'

                archiveArtifacts allowEmptyArchive: true, artifacts: '**/dependency-check-report.html'
                archiveArtifacts allowEmptyArchive: true, artifacts: '**/dependency-check-report.xml'

            }
        }
```

Then I added https://pypi.org/project/insecure-package/0.1.0/ into the requirements.txt to see if that is picked up. It still showed there are no vulnerabilties. That leads me to believe that this is not working for python code. The same stage worked for Java projects. I looked at the docs and it seems that the python analyzer is enabled by default. Is there a way to do verbose logging to see what is happening here?

**Comment by ds-o** [comment]
You probably need to add --enableExperimental for Python.

https://jeremylong.github.io/DependencyCheck/analyzers/python.html

**Comment by anshbansal** [comment]
I remember reading somewhere that this is enabled by default. I can try using this. This would go in additionalArguments as a string?
