### ISSUE TITLE
jenkins plugin: 

### ISSUE THREAD

**Issue by cigfthomas** [dependency-check/DependencyCheck#2669]
I'm using the dependency check 5.3.2 in a shared library pipeline script to check a node project. The Global Tools Config is installing 5.3.2 on an ECS based slave

npm install runs prior and a package-lock.json is created.

This scan 
dependencyCheck additionalArguments: '--noupdate --scan ./src --format ALL --prettyPrint' , odcInstallation: 'Owasp532'

results in 
[DependencyCheck] [WARN] Unable to determine Package-URL identifiers for 103 dependencies

this scan
dependencyCheck additionalArguments: '--noupdate --scan . --format ALL --prettyPrint' , odcInstallation: 'Owasp532'

results in messages like:
[DependencyCheck] [WARN] Exception extracting archive 'cb-never-called-1.0.1.tgz'.
[DependencyCheck] [INFO] Finished Archive Analyzer (1 seconds)
[DependencyCheck] [INFO] Finished File Name Analyzer (2 seconds)
[DependencyCheck] [ERROR] ----------------------------------------------------
[DependencyCheck] [ERROR] .NET Assembly Analyzer could not be initialized and at least one 'exe' or 'dll' was scanned. The 'dotnet' executable could not be found on the path; either disable the Assembly Analyzer or add the path to dotnet core in the configuration.
[DependencyCheck] [ERROR] ----------------------------------------------------
[DependencyCheck] [WARN] node module fsevents seems optional and not installed, skip it
[DependencyCheck] [WARN] node module fsevents seems optional and not installed, skip it
[DependencyCheck] [WARN] node module fsevents seems optional and not installed, skip it
[DependencyCheck] [WARN] node module fsevents seems optional and not installed, skip it
[DependencyCheck] [WARN] No lock file exists - this will result in false negatives; please run `npm install --package-lock`
[DependencyCheck] [WARN] Analyzing `/tmp/dctempa231de86-7c14-47c6-96be-1e1e342763e3/check189314590070056783tmp/2/package/package.json` - however, the node_modules directory does not exist. Please run `npm install` prior to running dependency-check
[DependencyCheck] [WARN] No lock file exists - this will result in false negatives; please run `npm install --package-lock`
[DependencyCheck] [WARN] Analyzing `/tmp/dctempa231de86-7c14-47c6-96be-1e1e342763e3/check189314590070056783tmp/4/package/package.json` - however, the node_modules directory does not exist. Please run `npm install` prior to running dependency-check

It seems like I have the scan path incorrect.  What am I entering incorrectly?

**Comment by jeremylong** [comment]
The warning you are seeing is due to an archive file that contains a package.json file and no package-lock.json.

**Comment by cigfthomas** [comment]
Thanks for your response. I am having an issue with getting the scan path correct or understanding where the ODC plugin is at in the filesystem.  Running npm audit is successful but this cmd in a groovy script has errors like it isn't finding the package-lock:
**dependencyCheck additionalArguments: '--noupdate --scan /home/jenkins/workspace/TouchpointHarness_dev --format ALL --prettyPrint, odcInstallation: 'Owasp532'**




Here is what an ls -la returns in the same script. The package-lock is present.



/home/jenkins/workspace/TouchpointHarness_dev

drwxr-sr-x    9 jenkins  jenkins       4096 Jul 11 21:14 .
drwxr-sr-x    4 jenkins  jenkins       4096 Jul 11 21:12 ..
-rw-r--r--    1 jenkins  jenkins        134 Jul 11 21:12 .editorconfig
-rw-r--r--    1 jenkins  jenkins       6072 Jul 11 21:12 .env
-rw-r--r--    1 jenkins  jenkins          0 Jul 11 21:12 .eslintignore
-rw-r--r--    1 jenkins  jenkins       1905 Jul 11 21:12 .eslintrc.js
drwxr-sr-x    8 jenkins  jenkins       4096 Jul 11 21:12 .git
-rw-r--r--    1 jenkins  jenkins        349 Jul 11 21:12 .gitignore
-rw-r--r--    1 jenkins  jenkins         56 Jul 11 21:12 .jsbeautifyrc
-rw-r--r--    1 jenkins  jenkins         56 Jul 11 21:12 .npmrc
-rw-r--r--    1 jenkins  jenkins        323 Jul 11 21:12 .prettierrc.json
drwxr-sr-x    2 jenkins  jenkins       4096 Jul 11 21:12 .vscode
-rw-r--r--    1 jenkins  jenkins       3306 Jul 11 21:12 Jenkinsfile-OLD
-rw-r--r--    1 jenkins  jenkins       1295 Jul 11 21:12 Jenkinsfile-curr
-rw-r--r--    1 jenkins  jenkins         51 Jul 11 21:12 JenkinsfileNodeJs
-rw-r--r--    1 jenkins  jenkins       3722 Jul 11 21:12 README.md
drwxr-sr-x 1221 jenkins  jenkins      36864 Jul 11 21:14 node_modules
-rw-r--r--    1 jenkins  jenkins     636844 Jul 11 21:13 package-lock.json
-rw-r--r--    1 jenkins  jenkins       2145 Jul 11 21:14 package.json
drwxr-sr-x    2 jenkins  jenkins       4096 Jul 11 21:12 pdfs
drwxr-sr-x    2 jenkins  jenkins       4096 Jul 11 21:12 public
drwxr-sr-x   24 jenkins  jenkins       4096 Jul 11 21:12 src
