### ISSUE TITLE
False Negative, unsure, Geronimo-jms

### ISSUE THREAD

**Issue by wisechoice** [dependency-check/DependencyCheck#267]
DependencyCheck returns this as one entry:

geronimo-jms_1.1_spec-1.0.jar   cpe:/a:apache:geronimo:1.0  org.apache.geronimo.specs:geronimo-jms_1.1_spec:1.0 High    3   HIGHEST 9

Downloading the 1.x series of Apache Geronimo I was not sure if the CPE was for this as this is the only jar used?

**Comment by jeremylong** [comment]
Do you mean False Positive? This is one of the tough questions with the use of dependency-check; if there are larger bundles of components under a single main identifier. My suggestion is go read the CVE description, go look for the CVE reference in the bugtrack, and if you still can't determine what in Geronimo was actually vulnerable - post a question to the libraries mailing list.

This is the current intended functionality of dependency-check. If a geronimo library is being used any geronimo related CVEs will be listed.
