### ISSUE TITLE
Referring to issue #1425: "maven plugin: unable to configure scanset from the command line"

### ISSUE THREAD

**Issue by gerib** [dependency-check/DependencyCheck#2671]
**Describe the bug**
Same as in issue #1425:

> it doesn't appear setting the scanSet from the command line of the maven plugin works

**Version of dependency-check used**
Maven plugin v5.3.2

**Log file**
https://gist.github.com/gerib/0790f6e9e860ca4d8d3534cad1dddd4b

**To Reproduce**
1. `mvn org.owasp:dependency-check-maven:check -DscanSet.fileSet=['src/main'] -X>check.log`
2. Search `check.log` for `scanSet`:

 ```` java
 ...
 [DEBUG]   (f) scanSet = []
 ...
 ````

**Expected behavior**
Like:
```` java
...
[DEBUG]   (f) scanSet = [org.apache.maven.shared.model.fileset.FileSet@6d1dcdff]
...
````
when declared in POM:
```` xml
<plugin>
  <groupId>org.owasp</groupId>
  <artifactId>dependency-check-maven</artifactId>
  <version>5.3.2</version>
  <configuration>
    <scanSet>
      <fileSet>
        <directory>src/main</directory>
      </fileSet>
    </scanSet>
  </configuration>
<plugin>
````

**Additional context**
This `-D...` syntax has been mentioned in [a comment in issue #1425](https://github.com/jeremylong/DependencyCheck/issues/1425#issuecomment-503492150) and [added to the doc](https://github.com/jeremylong/DependencyCheck/commit/6e3b4cfece64d3043f946cb915e727642c4cda1d) by @jeremylong afterwards.

See als answer https://stackoverflow.com/a/59767817/1744774 and its comments.

The [Maven File Management API example page](https://maven.apache.org/shared/file-management/examples/mojo.html) doesn't mention the `@Parameter` annotation with `(property = "...")`.

**Comment by jeremylong** [comment]
Thanks for pointing this out. I could have sworn this was working previously - but apparently it is not.  I've added a `scanDirectory` parameter that can be used.
