### ISSUE TITLE
Serious connectivity issues to NIST server

### ISSUE THREAD

**Issue by mr-duke** [dependency-check/DependencyCheck#2679]
Hello,
recently I've been encountering recurring connectivity issues to the NIST-server while using Dependency-Check within both our GitLab and Jenkins pipelines.
Here are some of the error messages I got:

`INFO] Checking for updates
[ERROR] Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta
org.owasp.dependencycheck.data.update.exception.UpdateException: Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta
    at org.owasp.dependencycheck.data.update.NvdCveUpdater.getMetaFile (NvdCveUpdater.java:347)
    at org.owasp.dependencycheck.data.update.NvdCveUpdater.getUpdatesNeeded (NvdCveUpdater.java:385)
    at org.owasp.dependencycheck.data.update.NvdCveUpdater.update (NvdCveUpdater.java:122)`

`[ERROR] Failed to execute goal org.owasp:dependency-check-maven:5.3.2:aggregate (default-cli) on project XXX: Fatal exception(s) analyzing XXX: One or more exceptions occurred during analysis:
 [ERROR] 	Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta
 [ERROR] 	No documents exist`

I was wondering if this is a known problem and what could be done about it ? It's breaking too many builds in our team right now, thus I really need to find a solution 
(I think it doesn't have anything to do with Dependency-Check itself, does it?)

**Comment by mprins** [comment]
I may be a network issue on your site, I haven't seen any problems updating for months.

You can set up a local mirror instead of using the live version.

I have a job running `mvn -U org.owasp:dependency-check-maven:update-only` once a day in Jenkins to keep an updated cache

**Comment by jeremylong** [comment]
Info on mirroring the NVD locally can be found here: https://jeremylong.github.io/DependencyCheck/data/mirrornvd.html

**Comment by mr-duke** [comment]
Thank you, guys! I will consider that option.
