### ISSUE TITLE
Update documentation for "Mirroring the NVD from NIST"

### ISSUE THREAD

**Issue by blaksec** [dependency-check/DependencyCheck#268]
The four properties mentioned in Item #2 of https://jeremylong.github.io/DependencyCheck/data/mirrornvd.html does not seem to be correct, at least for CLI module. 

I ended up using the following to override the default URLs to get my copy of Dependency Check working with local copies of the NVD files.
- cve.url-1.2.modified
- cve.url-2.0.modified
- cve.url-1.2.base
- cve.url-2.0.base

For example
- cve.url-1.2.modified=file:///myNVDcopy/mvdcve-Modified.xml.gz
- cve.url-2.0.modified=file:///myNVDcopy/mvdcve-2.0-Modified.xml.gz
- cve.url-1.2.base=file:///myNVDcopy/mvdcve-%d.xml.gz
- cve.url-2.0.base=file:///myNVDcopy/mvdcve-2.0-%d.xml.gz

This is a hidden but very useful feature. Perhaps makes sense to make it more visible inside the individual module documentation (.cli doc has no mention of it at all I believe)

**Comment by jeremylong** [comment]
Thanks for reporting this. The CLI is the only version that does not expose these configuration options - I'll add these options to the next release.

**Comment by jeremylong** [comment]
The arguments have been added to the CLI; documentation still needs to be updated.

**Comment by dwvisser** [comment]
I succeeded in using this today. Here's the script I'm using to point have testing runs point to the local files I downloaded using [nist-data-mirror](https://github.com/stevespringett/nist-data-mirror):

``` sh
#!/bin/sh
REPO=/home/dale/git/DependencyCheck
CLI_SCRIPT=$REPO/dependency-check-cli/target/release/bin/dependency-check.sh
NVD=file:///home/dale/NVD
ARGS="--app Test --out /tmp --log /tmp/dependency-check-log.txt --cveUrl20Base $NVD/nvdcve-2.0-%d.xml.gz --cveUrl12Base $NVD/nvdcve-%d.xml.gz --cveUrl20Modified $NVD/nvdcve-2.0-Modified.xml.gz --cveUrl12Modified $NVD/nvdcve-Modified.xml.gz"
$CLI_SCRIPT $ARGS $@
```

**Comment by jeremylong** [comment]
The documentation has been updated and the patch for this issue will be included in the next release.
