### ISSUE TITLE
How to get the analysis report result？

### ISSUE THREAD

**Issue by LChloe** [dependency-check/DependencyCheck#2685]
I am currently using the DependencyCheck plugin of jenkins, and now I have obtained the DependencyCheck analysis report through the pipeline.
The analysis report is as follows:
![图片](https://user-images.githubusercontent.com/27614399/85936867-357ad580-b931-11ea-9d01-40f1ebb01ee4.png)
I need to get the corresponding analysis report now. Does anyone know the corresponding interface for querying the analysis report data?
I tested the following tests through the developer mode
`/jenkins/$stapler/bound/a43609e2-fadf-4e4d-a2e4-9395fd8325ca/getSeverityDistributionJson`

version
OWASP Dependency-Check Plugin：5.1.1
jenkins：2.150.1

**Comment by aikebah** [comment]
The report should be in your Jenkins job workspace (without customized report format arguments only the XML report will be present) Note: best place for information on the Jenkins-plugin is that plugins github issues. See [its github project](https://github.com/jenkinsci/dependency-check-plugin)
