### ISSUE TITLE
False Positive on Microsoft.AspNet.FriendlyUrls.Core

### ISSUE THREAD

**Issue by christopher-gill** [dependency-check/DependencyCheck#2686]
False positive on Microsoft.AspNet.FriendlyUrls.Core - reported as `cpe:2.3:a:microsoft:asp.net:*:*:*:*:*:*:*:*`

  <package id="Microsoft.AspNet.FriendlyUrls" version="1.0.2" targetFramework="net48" />
  <package id="Microsoft.AspNet.FriendlyUrls.Core" version="1.0.2" targetFramework="net48" />

Location to download package: https://www.nuget.org/packages/Microsoft.AspNet.FriendlyUrls.Core/

I think this may be a false positive as I have been unable to find any refrences to it being vulnerable, similarly when running audit.net & safenuget they do not report it to be vulnerable

**Comment by jeremylong** [comment]
In testing with 6.0.3-SNAPSHOT - these FP appear to be resolved.  I did add a rule for another library while researching the reported FP.  Thanks!

**Comment by christopher-gill** [comment]
Brilliant thanks @jeremylong
