### ISSUE TITLE
Request for backporting the fix implemented for Issue#2445 in ODC v5.3.2

### ISSUE THREAD

**Issue by Anshu2405** [dependency-check/DependencyCheck#2687]
Hi Team,

I have faced similar issue  https://github.com/jeremylong/DependencyCheck/issues/2455  many times while running CLI v5.3.2 in my project. I noticed the issue will be fixed in the upcoming version i.e. 6.0.0.
As I have already uptaken v5.3.2 and will not be able to consume  the latest version 6.0.0 for a while, could you please backport the code fix  in older version i.e. ODC v5.3.2 too.

**Comment by jeremylong** [comment]
Unfortunately, I do not plan on back-porting the patch to 5.3.2.
