### ISSUE TITLE
Correct Ant Documentation - reportFormat

### ISSUE THREAD

**Issue by jeremylong** [dependency-check/DependencyCheck#269]
Current documentation lists 'format', it should be 'reportFormat'.

https://jeremylong.github.io/DependencyCheck/dependency-check-ant/configuration.html

**Comment by hmolsen** [comment]
the same holds for reportoutputdirectory

**Comment by jeremylong** [comment]
The markdown files have been updated and the new site will be published with the next release of dependency-check. Thanks again for reporting the incorrect documentation.

--Jeremy
