### ISSUE TITLE
--exclude option is ignored for CLI run

### ISSUE THREAD

**Issue by KOVALKO2** [dependency-check/DependencyCheck#2695]
I'm configuring GitLabCI job and need to exclude some folders from scanning scope.
I've tried many different formats of path for --exclude CLI param, but without success. checked also documentation.
My last try is:
`./dependency-check/bin/dependency-check.sh Core -s ./ --project MyProj-FE --disableAssembly --exclude 'tests/**' --exclude 'dependency-check/**' -o ./reports -f ALL --prettyPrint`
But folders are still included into scanning scope.

How to exclude them correctly (with all the content inside)?
I couldn't provide log because it may contain some sensitive data.

**Comment by jeremylong** [comment]
Sorry about the delayed response - the excludes uses [Ant syntax](https://ant.apache.org/manual/api/org/apache/tools/ant/DirectoryScanner.html). My guess is that you need to update to use: `--exclude '**/tests/**/*'`.

**Comment by KOVALKO2** [comment]
Thanks a lot! This form works well. It wasn't clear for me without examples how to build this correctly.
