### ISSUE TITLE
Suddenly getting strange error with dependecy-ant-check "Failed to request component-reports"

### ISSUE THREAD

**Issue by MMirabito** [dependency-check/DependencyCheck#2696]
Dear all,

I am wondering if you could help me. We are suddenly getting the following exception when dependecy-ant-check V5.3.0  is running in our CI/CD pipeline. The issue appears to point to
 
**org.sonatype.ossindex.service.client.transport.Transport$TransportException: Unexpected response; status: 500** Does this mean that some service is not available and if so how do i find out which one? 

Thanks in advance for any help or guidance on how to resolve the issue.

max

`
04-Jul-2020 13:38:40	D:\Atlassian\ApplicationData\BAMBOO\xml-data\build-dir\XOXO-DEV-JOB1\build-dependency-cve.xml:67: One or more exceptions occurred during analysis:
04-Jul-2020 13:38:40	org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during analysis:
04-Jul-2020 13:38:40	        Failed to request component-reports
04-Jul-2020 13:38:40	        at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:718)
04-Jul-2020 13:38:40	        at org.owasp.dependencycheck.taskdefs.Check.callExecuteAnalysis(Check.java:1636)
04-Jul-2020 13:38:40	        at org.owasp.dependencycheck.taskdefs.Check.execute(Check.java:1593)
04-Jul-2020 13:38:40	        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
04-Jul-2020 13:38:40	        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
04-Jul-2020 13:38:40	        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
04-Jul-2020 13:38:40	        at java.lang.reflect.Method.invoke(Method.java:498)
04-Jul-2020 13:38:40	        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
04-Jul-2020 13:38:40	        at org.apache.tools.ant.Task.perform(Task.java:350)
04-Jul-2020 13:38:40	        at org.apache.tools.ant.Target.execute(Target.java:448)
04-Jul-2020 13:38:40	        at org.apache.tools.ant.Target.performTasks(Target.java:469)
04-Jul-2020 13:38:40	        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
04-Jul-2020 13:38:40	        at org.apache.tools.ant.Project.executeTarget(Project.java:1370)
04-Jul-2020 13:38:40	        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
04-Jul-2020 13:38:40	        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
04-Jul-2020 13:38:40	        at org.apache.tools.ant.Main.runBuild(Main.java:849)
04-Jul-2020 13:38:40	        at org.apache.tools.ant.Main.startAnt(Main.java:228)
04-Jul-2020 13:38:40	        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:283)
04-Jul-2020 13:38:40	        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
04-Jul-2020 13:38:40	Next Exception:
04-Jul-2020 13:38:40	org.owasp.dependencycheck.analyzer.exception.AnalysisException: Failed to request component-reports
04-Jul-2020 13:38:40	        at org.owasp.dependencycheck.analyzer.OssIndexAnalyzer.analyzeDependency(OssIndexAnalyzer.java:145)
04-Jul-2020 13:38:40	        at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
04-Jul-2020 13:38:40	        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
04-Jul-2020 13:38:40	        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
04-Jul-2020 13:38:40	        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
04-Jul-2020 13:38:40	        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
04-Jul-2020 13:38:40	        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
04-Jul-2020 13:38:40	        at java.lang.Thread.run(Thread.java:748)
04-Jul-2020 13:38:40	Caused by: org.sonatype.ossindex.service.client.transport.Transport$TransportException: Unexpected response; status: 500
04-Jul-2020 13:38:40	        at org.sonatype.ossindex.service.client.transport.HttpUrlConnectionTransport.post(HttpUrlConnectionTransport.java:106)
04-Jul-2020 13:38:40	        at org.sonatype.ossindex.service.client.internal.OssindexClientImpl.doRequestComponentReports(OssindexClientImpl.java:204)
04-Jul-2020 13:38:40	        at org.sonatype.ossindex.service.client.internal.OssindexClientImpl.requestComponentReports(OssindexClientImpl.java:170)
04-Jul-2020 13:38:40	        at org.owasp.dependencycheck.analyzer.OssIndexAnalyzer.requestReports(OssIndexAnalyzer.java:197)
04-Jul-2020 13:38:40	        at org.owasp.dependencycheck.analyzer.OssIndexAnalyzer.analyzeDependency(OssIndexAnalyzer.java:138)
04-Jul-2020 13:38:40	        ... 7 more
04-Jul-2020 13:38:40	
04-Jul-2020 13:38:40	Total time: 8 seconds
`

**Comment by albuch** [comment]
Can confirm, we saw the same issue with a couple of pipelines over the weekend.

**Comment by jeremylong** [comment]
Could have been an issue with the OSS Index Service - is are the issues still happening?

**Comment by MMirabito** [comment]
Hi @jeremylong and @albuch thanks for the confirmation on my side it magically started working again so I think the OSS Index service must have been temporarily down.

Thanks,
max
