### ISSUE TITLE
Html output css definition is missing ';'

### ISSUE THREAD

**Issue by thawkins** [dependency-check/DependencyCheck#2697]
when generating html output the embedded css for the "th" tag has a statement that is missing a ';' line terminator. the text-align: left statement is not terminated.

```
th {
                text-align:left
                vertical-align:text-top;
                padding:6px;
                margin:0px;
                border-bottom:1px;
                border-color: black;
            }
```
**Version of dependency-check used**
 5.3.2

**To Reproduce**
1. generate any report to html
2. check html output
3. see missing ';'

**Expected behavior**
generated html/css  is expected to be valid,  spotted issue opening report.html output file in IntelliJ editor with html validation enabled.

**Comment by jeremylong** [comment]
Thanks for pointing this out. This will be included in the next release.
