### ISSUE TITLE
How to disable reporting rubies?

### ISSUE THREAD

**Issue by aTylkowski** [dependency-check/DependencyCheck#2712]
I'm trying to run dependency-check on my project and I do generate a dependency-check report, but I would like to omit rubies (rubyzip:1.2.3). How can I do this or by what command? I didn't come across it on the internet

**Comment by Marx314** [comment]
Suppression file?
https://jeremylong.github.io/DependencyCheck/general/suppression.html

**Comment by jeremylong** [comment]
You can also include an ant style exclusion using the `--exclude` argument:

```
--exclude '**/ruby.zip'
```

Of course the above example likely is not using the correct path so you would need to update it for your own situation.
