### ISSUE TITLE
GitHub 'watch releases' feature is not working with DependencyCheck

### ISSUE THREAD

**Issue by MichaelVetter** [dependency-check/DependencyCheck#2720]
GitHub watch releases feature is not working with DependencyCheck and this might be due to the way how releases are done, see
https://github.community/t/not-getting-release-notification-despite-watching-releases/1792/6
"Without adding a message to the release, it only counts as a “tag” and not as a full release. Part of the confusion comes from the fact that when a project isn’t using full releases, it shows the project tags under the releases tab."

In other projects like this the notification feature is working:
https://github.com/zaproxy/zaproxy/releases

Would it be possible to change the releases for DependencyCheck in a way that the requirements for notifications are fulfilled?

**Comment by jeremylong** [comment]
https://github.com/jeremylong/DependencyCheck/releases/tag/v6.0.0
