### ISSUE TITLE
Telerik.Web.UI.dll

### ISSUE THREAD

**Issue by roxton001** [dependency-check/DependencyCheck#2726]
Hello,

we are trying to use your plugin to check any 3rd party libraries for vulnerabilities.

However, we tested it on Telerik.Web.UI 2013.2.717.40 library and no vulnerability was identified despite the fact the vulnerability for this library really [exists](https://nvd.nist.gov/products/cpe/detail/663834?keyword=cpe:2.3:a:telerik:ui_for_asp.net_ajax:2013.2.717:*:*:*:*:*:*:*&status=FINAL,DEPRECATED&orderBy=CPEURI&namingFormat=2.3)

![image](https://user-images.githubusercontent.com/9051831/87769679-45922080-c81e-11ea-9717-3a13f057506f.png)

Your tool works perfectly with a newer version of the Telerik library:
![image](https://user-images.githubusercontent.com/9051831/87770258-16c87a00-c81f-11ea-888c-0fce0929a50e.png)

Can you please somebody help us with this issue? 

Thanks

**Comment by jeremylong** [comment]
For the scan that does not detect Telerik correctly:
1. what version of ODC are you using?
2. Please provide the log file (from the cli just add `--log=odc.log`
3. If possible, can you scan just the Telerik control and provide the XML version of the report?
4. What version of dotnet core are you using?

**Comment by roxton001** [comment]
1. Dependency-Check Core version 5.3.2
2. [log.txt](https://github.com/jeremylong/DependencyCheck/files/4937565/log.txt)
3. [dependency-check-report.zip](https://github.com/jeremylong/DependencyCheck/files/4937572/dependency-check-report.zip)
4. dotnet --version 3.1.302

**Comment by jeremylong** [comment]
I do not use the Telerik controls - so I'm not sure about this. Are there separate DLLs for the base Web UI and AJAX? Or are the ajax bits embedded in the Web UI DLL?

**Comment by jeremylong** [comment]
Also - could you provide the XML report for the new DLL that was identified?

**Comment by roxton001** [comment]
> Also - could you provide the XML report for the new DLL that was identified?

I just realized that the tool has not found any vulnerabilities for the newer version, it just generates CPE for the file. Sorry for misleading



> I do not use the Telerik controls - so I'm not sure about this. Are there separate DLLs for the base Web UI and AJAX? Or are the ajax bits embedded in the Web UI DLL?

Will have to check and let you know

**Comment by roxton001** [comment]
ok, it seems it's embedded. Now I tried a different version of the same library and the tool has identified the vulnerability.

Here is the result
[dependency-check-report.zip](https://github.com/jeremylong/DependencyCheck/files/4938176/dependency-check-report.zip)

**Comment by jeremylong** [comment]
The hints file update that will resolve the issue will be included in the 6.0.0 release.

**Comment by roxton001** [comment]
Thanks!

**Comment by Ingrown29** [comment]
Hi Jeremy,

I would like to reopen this issue due problem with this Telerik.Web.UI library in version 2013.2.717.40 as mentioned above. I tried to check it with ODC multiple times with several versions of that library which are working as expected but in this specific version is no vulnerability found, despite of the CPE [exists](https://nvd.nist.gov/products/cpe/detail/663834?namingFormat=2.3&orderBy=CPEURI&keyword=cpe:2.3:a:telerik&status=FINAL).

**Here are some info:** 
1. ODC v6.0.2
2. dotnet v3.1.402
3. [odc.log](https://github.com/jeremylong/DependencyCheck/files/5378174/odc.log)
4. [dependency-check-report.zip](https://github.com/jeremylong/DependencyCheck/files/5378164/dependency-check-report.zip)

Can you please help me to find out what's causing that no vulnerability is found?

Thank you!
