### ISSUE TITLE
SonarQube scanner stops with Metric 'critical_severity_vulns' should not be computed by a Sensor error

### ISSUE THREAD

**Issue by charlesk40** [dependency-check/DependencyCheck#2728]
SonarQube integration worked fine until we upgraded to the following:

```
SonarQube Scanner 3.3.0.1492
SonarQube server 8.4.0
https://github.com/dependency-check/dependency-check-sonar-plugin/releases/download/2.0.5/sonar-dependency-check-plugin-2.0.5.jar

```

We tried the latest org.owasp:dependency-check-maven:5.3.2 but still fails and not sure where the issue is.

`00:03:15 INFO: Sensor CheckstyleSensor [checkstyle] (done) | time=126ms
00:03:15 INFO: Sensor Dependency-Check [dependencycheck]
00:03:15 INFO: Process Dependency-Check report
00:03:15 INFO: We doesn't found any Project configuration file e.g. pom.xml, gradle.build and can not link dependencies
00:03:15 INFO: Linking 9 dependencies to project
00:03:15 INFO: ------------------------------------------------------------------------
00:03:15 INFO: EXECUTION FAILURE
00:03:15 INFO: ------------------------------------------------------------------------
00:03:15 INFO: Total time: 12.443s
00:03:15 INFO: Final Memory: 38M/555M
00:03:15 INFO: ------------------------------------------------------------------------
00:03:15 ERROR: Error during SonarQube Scanner execution
00:03:15 ERROR: Metric 'critical_severity_vulns' should not be computed by a Sensor
00:03:15 ERROR: `

Removing the following properties from the sonar-project.properties makes the scan pass but we lose the dependecy check reports.

```
sonar.dependencyCheck.reportPath=target/dependency-check-report.xml
sonar.dependencyCheck.htmlReportPath=target/dependency-check-report.html

```

Any help would be greatly appreciated.
Thank you.

**Comment by jeremylong** [comment]
This is the wrong issue board for the sonar plugin. Please use https://github.com/dependency-check/dependency-check-sonar-plugin/issues
