### ISSUE TITLE
Download-error while running pipeline

### ISSUE THREAD

**Issue by Nilozzz** [dependency-check/DependencyCheck#2737]
While running the pipeline we get the following errormessage, probably because the firewall of our organization is blocking this. (We only got acces to Azure Devops-URL's). Is it necessary to call this URL? Can't we install the package manually?

Downloading Dependency Check installer...
##[debug]GET https://dl.bintray.com/jeremy-long/owasp/dependency-check-5.3.2-release.zip with 0-byte payload
##[debug]STDERR: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
##[error]System.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.

**Comment by jeremylong** [comment]
I don't support the Azure Devops. I'm not sure if you can configure that URL somewhere else.  Consider asking the question here: https://github.com/dependency-check/azuredevops/issues
