### ISSUE TITLE
Enhance dependency-suppression to allow suppression on confidence level

### ISSUE THREAD

**Issue by Com3t** [dependency-check/DependencyCheck#2738]
It would be wonderful if we could limit dependency-check output to show only those vulnerabilities associated with components identified with high confidence.

Enhancement request is to update https://jeremylong.github.io/DependencyCheck/dependency-suppression.1.3.xsd to allow specifying a minimal confidence level to show in output.

**Comment by jeremylong** [comment]
I haven't implemented this for many reasons - most of which you will end up masking real vulnerabilities.  The better solution would be to spend a few minutes on your app and build a suppression file for any incorrect matches.
