### ISSUE TITLE
Forbidden! When accessing bintray release 5.3.2

### ISSUE THREAD

**Issue by maartengo** [dependency-check/DependencyCheck#2739]
**Describe the bug**
When accessing the bintray release of the dependency check it returns a "Forbidden!" message instead of the expected .zip.
I'm not sure if this is a problem within bintray, or if something else has been changed.
Occurs on different machines in different networks and locations. 

**Version of dependency-check used**
Not a bug in the dependency-check itself.

**Log file**
Downloading: https://dl.bintray.com/jeremy-long/owasp/dependency-check-5.3.2-release.zip
##[error]Unexpected HTTP response: 403

**To Reproduce**
1. Go to 'https://dl.bintray.com/jeremy-long/owasp/dependency-check-5.3.2-release.zip'
2. See error

**Expected behavior**
Expected a zip to be downloaded when accessing the page.

**Additional context**
![image](https://user-images.githubusercontent.com/46345801/89039194-2670b400-d331-11ea-819e-a660eba2633a.png)

**Comment by pha5matis** [comment]
This error is for all downloads not just 5.3.2.

**Comment by cybernot** [comment]
We have the same problem. This is blocking our release pipeline, please fix this quickly.

**Comment by hbouissoumer** [comment]
Same for us, it blocks all our pipelines. Any idea when this will be fixed?

**Comment by nattymachado** [comment]
Hi we are having the same problem on our pipelines and it is blocking us too.

**Comment by jeremylong** [comment]
Unfortunately, it looks like this won't be fixed until tomorrow.

**Comment by cybernot** [comment]
@jeremylong  do you have a suggestion for a workaround ? do you have an ETA of when maybe it'll be fixed ? Thanks

**Comment by jeremylong** [comment]
See my comment above - should be fixed tomorrow.  Work around - consider hosting the CLI locally in your environment (if you don't have a copy consider building from source), alternatively, use the docker image.

**Comment by nattymachado** [comment]
Sorry, I am a little confused with this comment:
```
Unfortunately, it looks like this won't be fixed tomorrow.
```

Will be the issue fixed tomorrow?

**Comment by jeremylong** [comment]
Sorry - I missed "until".  This won't be fixed until tomorrow.

**Comment by mecorusfc** [comment]
This is a critical issue for anybody using the Jenkins plugin since it loads every time.  We have to run multiple scans every day and we are already falling behind.  Even if you want to turn off the auto-install and install it once yourself into your own docker image, we need to get to that zip file at least one time.  We are completely prevented - this is pretty serious.

**Comment by mecorusfc** [comment]
Trying different things.  Looks like the Maven build fails on the latest release so we are trying to find a way to use the docker image - pulling it, running it locally and then copying out the install to make our own zip - hopefully. - Jeremy is there any way you can make that zip available (say, 5.3.2) on any other repository?

**Comment by jeremylong** [comment]
A maven build should not be affected by this issue unless you are invoking the command line - which isn't the best option. Maven builds should use the maven plugin.

You can simple clone the repo, checkout tag v5.3.2 and build the zip yourself and host in a location for your organization.

**Comment by jeremylong** [comment]
This should now be resolved.

**Comment by mecorusfc** [comment]
Thanks so much.  I've verified this is working again.  We'll work on a backup plan in case this happens again.  

By the way, can you explain what happened on bintray?  If it happens in the future, is there a better way for us to report it?  Maybe directly to bintray somehow?  Thanks, Mike

**Comment by jeremylong** [comment]
The account hit a rate limit.

**Comment by mecorusfc** [comment]
Has the rate limit been increased?  I ask because we have many more scans to run and also more often.

**Comment by jeremylong** [comment]
I've been monitoring this situation - and we *might* hit the limit again this month. However, I highly recommend people to update their scripts and point directly to the CLI or Ant Task hosted on the github [releases](https://github.com/jeremylong/DependencyCheck/releases/tag/v6.0.2):

CLI: https://github.com/jeremylong/DependencyCheck/releases/download/v6.0.2/dependency-check-6.0.2-release.zip
Ant: https://github.com/jeremylong/DependencyCheck/releases/download/v6.0.2/dependency-check-ant-6.0.2-release.zip

**Comment by ChandrashekarAppaji** [comment]
@jeremylong 
Unable to download owasp -latest version[or any version] using Jenkins Plugin . Getting Forbidden or 403 Error, May i know the reason please? All our pipelines  are failing.
 FATAL: Failed to install https://dl.bintray.com/jeremy-long/owasp/dependency-check-6.0.1-release.zip 
java.io.IOException: Server returned HTTP response code: 403 for URL: https://dl.bintray.com/jeremy-long/owasp/dependency-check-6.0.1-release.zip
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3061)
	at java.net.URLConnection.getHeaderFieldLong(URLConnection.java:629)
	at java.net.URLConnection.getContentLengthLong(URLConnection.java:501)
	at java.net.URLConnection.getContentLength(URLConnection.java:485)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentLength(HttpsURLConnectionImpl.java:412)
	at org.jvnet.robust_http_client.RetryableHttpStream.<init>(RetryableHttpStream.java:90)

**Comment by mecorusfc** [comment]
We got 43 scans with that error below this morning.  I’m curious why this couldn’t be somehow cached by the Jenkins plugin.  In the past, it was.  Then, when the new version came out, it stopped being cached.

How long until we can run our scans again?

Thanks,

Michael Corum
VP, Technical Architecture Solutions

RGA Reinsurance Company
16600 Swingley Ridge Road
Chesterfield, Missouri 6301701706
T 636.736.7066
www.rgare.com

**Comment by cblegare** [comment]
As a tip,

Run with a specific environment variable.  Example one-liner, using the python package:

```shell
DEPENDENCY_CHECK_URL="https://github.com/jeremylong/DependencyCheck/releases/download/v6.0.2/dependency-check-6.0.2-release.zip" dependency-check --scan ./src --enableExperimental --format "ALL" --out build/reports --symLink 50
```

**Comment by jeremylong** [comment]
For the latest - you can use the github release URL above.  For 5.x - you'll likely have to wait until the 1st before things clear up...

**Comment by JohnAntonioCollins** [comment]
> I've been monitoring this situation - and we _might_ hit the limit again this month. However, I highly recommend people to update their scripts and point directly to the CLI or Ant Task hosted on the github [releases](https://github.com/jeremylong/DependencyCheck/releases/tag/v6.0.2):
> 
> CLI: https://github.com/jeremylong/DependencyCheck/releases/download/v6.0.2/dependency-check-6.0.2-release.zip
> Ant: https://github.com/jeremylong/DependencyCheck/releases/download/v6.0.2/dependency-check-ant-6.0.2-release.zip

Is there a way to Verify the cryptographic integrity of your download? (CLI)
-thanks

**Comment by jeremylong** [comment]
Yes - just like with Bintray. Take a look at the release assets:

https://github.com/jeremylong/DependencyCheck/releases/tag/v6.0.2

**Comment by abhimangalms** [comment]
[https://dl.bintray.com/drummer-aidan/maven/androidx/leanback/leanback](https://dl.bintray.com/drummer-aidan/maven/androidx/leanback/leanback) is forbidden.

I replaced jcenter() with mavenCentral(). Still the issues exist.

and fixed the by replacing the leanback dependency with "androidx.leanback:leanback:1.1.0-rc01"

**Comment by jeremylong** [comment]
Please see:
https://github.com/jeremylong/DependencyCheck/blob/main/RELEASE_NOTES.md#version-602-2020-09-27
https://github.com/jeremylong/DependencyCheck/blob/main/RELEASE_NOTES.md#version-612-2021-03-08

And finally:
https://github.com/jeremylong/DependencyCheck/blob/main/SECURITY.md
