### ISSUE TITLE
Error scanning nodejs project - ruby analyser

### ISSUE THREAD

**Issue by javixeneize** [dependency-check/DependencyCheck#2744]
Hi

Im running dependency check in a nodejs application, and i have an error triggered by the bundle-audit analyser.

[ERROR] Exception from bundle-audit process: java.io.IOException: Cannot run program "bundle-audit" (in directory "/tmp/dctemp7bdb764f-c63f-4027-83af-8f57f7f0ada0"): error=2, No such file or directory. Disabling Ruby Bundle Audit Analyzer

It is only happening with this specific application, i have never seen this before. Any idea what might be the problem? I have no ruby code in the project.

Thanks

**Comment by jeremylong** [comment]
Any chance you could run generate the log file for this project (`-l odc.log`) and post more details?

My guess is that there is a `Gemfile.lock` file in an archive somewhere in the project and you do not have Ruby installed.
