### ISSUE TITLE
I am not been able to perform dependency check on my dll file.Can you share the set of instructions how to perform dependency check on dll on windows os?

### ISSUE THREAD

**Issue by nishantshri08** [dependency-check/DependencyCheck#2746]
Please delete any un-needed section from the following issue template:

### Reporting Bugs/Errors
When reporting errors, 99% of the time log file output is required. Please post the log file as a [gist](https://gist.github.com/) and provide a link in the new issue.

### Reporting False Positives
When reporting a false positive please include:
- The location of the dependency (Maven GAV, URL to download the dependency, etc.)
- The CPE that is believed to be false positive
  - Please report the CPE not the CVE

#### Example
False positive on library foo.jar - reported as cpe:/a:apache:tomcat:7.0
```xml
<dependency>
   <groupId>org.sample</groupId>
   <artifactId>foo</artifactId>
   <version>1.0</version>
</dependency>
```

**Comment by nishantshri08** [comment]
I am not getting the report as output while running the following command on my DLL file on my windows on on CLI mode 
dependency-check.bat --project "Autoscape" --scan "C:\autoscape-geofence-master\autoscape-geofence-master\src\Autoscape.Geofence.API\bin\Debug" --out "C:\autoscape-geofence-master\autoscape-geofence-master\cvcOutput" --format "ALL"

**Comment by nishantshri08** [comment]
Please help me which step need to taken here to resolve the issue

**Comment by jeremylong** [comment]
Add `--enableExperimental` as the PE analyzer is still considered experimental.

**Comment by nishantshri08** [comment]
Hi Jeremylong,
 
I used the following cli command but still not getting the reports generated 
dependency-check.bat --project "Autoscape" --enableExperimental --enableRetired --scan "C:\autoscape-geofence-master\autoscape-geofence-master\src\Autoscape.Geofence.API\bin\Debug" --out "C:\autoscape-geofence-master\autoscape-geofence-master\cvcOutput" --format "ALL"
C:\autoscape-geofence-master\autoscape-geofence-master\src\Autoscape.Geofence.API\bin\Debug\netcoreapp3.1

**Comment by nishantshri08** [comment]
Below is the message i am getting on running the above command 
'C:\autoscape-geofence-master\autoscape-geofence-master\src\Autoscape.Geofence.API\bin\Debug\netcoreapp3.1' is not recognized as an internal or external command,
operable program or batch file.

**Comment by jeremylong** [comment]
try quoting the path that you are scanning:

```
dependency-check.bat --project "Autoscape" --enableExperimental
--enableRetired --scan
"C:\autoscape-geofence-master\autoscape-geofence-master\src\Autoscape.Geofence.API\bin\Debug"
--out "C:\autoscape-geofence-master\autoscape-geofence-master\cvcOutput"
--format "ALL"
"C:\autoscape-geofence-master\autoscape-geofence-master\src\Autoscape.Geofence.API\bin\Debug\netcoreapp3.1"
```

**Comment by nishantshri08** [comment]
Below is the result quoting:-

C:\Users\Amit Khandelwal\Downloads\dependency-check-5.3.2-release\dependency-check\bin>dependency-check.bat --project "Autoscape" --enableExperimental

C:\Users\Amit Khandelwal\Downloads\dependency-check-5.3.2-release\dependency-check\bin>--enableRetired --scan
'--enableRetired' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Amit Khandelwal\Downloads\dependency-check-5.3.2-release\dependency-check\bin>"C:\autoscape-geofence-master\autoscape-geofence-master\src\Autoscape.Geofence.API\bin\Debug"
'"C:\autoscape-geofence-master\autoscape-geofence-master\src\Autoscape.Geofence.API\bin\Debug"' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Amit Khandelwal\Downloads\dependency-check-5.3.2-release\dependency-check\bin>--out "C:\autoscape-geofence-master\autoscape-geofence-master\cvcOutput"
'--out' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Amit Khandelwal\Downloads\dependency-check-5.3.2-release\dependency-check\bin>--format "ALL"
'--format' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Amit Khandelwal\Downloads\dependency-check-5.3.2-release\dependency-check\bin>"C:\autoscape-geofence-master\autoscape-geofence-master\src\Autoscape.Geofence.API\bin\Debug\netcoreapp3.1"

**Comment by jeremylong** [comment]
You do realize that when you copy and paste from github you are likely copying carriage returns?  Copy the command, put it into notepad, make sure you remove all the new lines, and then paste it into a command prompt.

**Comment by nishantshri08** [comment]
I tryed below but still facing the issue:
C:\Users\Amit Khandelwal\Downloads\dependency-check-5.3.2-release\dependency-check\bin>dependency-check.bat --project "Autoscape" --enableExperimental --enableRetired --scan "C:\autoscape-geofence-master\autoscape-geofence-master\src\Autoscape.Geofence.API\bin\Debug" --out "C:\autoscape-geofence-master\autoscape-geofence-master\cvcOutput" --format "ALL" "C:\autoscape-geofence-masterautoscape-geofence-master\src\Autoscape.Geofence.API\bin\Debug\netcoreapp3.1"

C:\Users\Amit Khandelwal\Downloads\dependency-check-5.3.2-release\dependency-check\bin>dependency-check.bat --project "Autoscape" --enableExperimental --enableRetired --scan "C:\autoscape-geofence-master\autoscape-geofence-master\src\Autoscape.Geofence.API\bin\Debug" --out "C:\autoscape-geofence-master\autoscape-geofence-master\cvcOutput" --format "ALL" "C:\autoscape-geofence-masterautoscape-geofence-master\src\Autoscape.Geofence.API\bin\Debug\netcoreapp3.1"

C:\Users\Amit Khandelwal\Downloads\dependency-check-5.3.2-release\dependency-check\bin>```dependency-check.bat --project "Autoscape" --enableExperimental --enableRetired --scan "C:\autoscape-geofence-master\autoscape-geofence-master\src\Autoscape.Geofence.API\bin\Debug" --out "C:\autoscape-geofence-master\autoscape-geofence-master\cvcOutput" --format "ALL" "C:\autoscape-geofence-masterautoscape-geofence-master\src\Autoscape.Geofence.API\bin\Debug\netcoreapp3.1"```
'```dependency-check.bat' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Amit Khandelwal\Downloads\dependency-check-5.3.2-release\dependency-check\bin>dependency-check.bat --project "Autoscape" --enableExperimental --enableRetired --scan "C:\autoscape-geofence-master\autoscape-geofence-master\src\Autoscape.Geofence.API\bin\Debug" --out "C:\autoscape-geofence-master\autoscape-geofence-master\cvcOutput" --format "ALL" "C:\autoscape-geofence-masterautoscape-geofence-master\src\Autoscape.Geofence.API\bin\Debug\netcoreapp3.1"```

**Comment by nishantshri08** [comment]
Hi Jeremylong,
It would be of great help if you can help me to resolve the issue. The command line is not scanning the file also let me know which all files should be available in the file to scan the project.
