### ISSUE TITLE
asm-delegate seemingly confused with something called DeleGate??

### ISSUE THREAD

**Issue by mebigfatguy** [dependency-check/DependencyCheck#2750]
**Describe the bug**
This artifact:
https://search.maven.org/search?q=asm-delegate
https://github.com/mebigfatguy/asm-delegate

Seems to be confused for something called DeleGate

https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Adelegate&cpe_product=cpe%3A%2F%3Adelegate%3Adelegate&cpe_version=cpe%3A%2F%3Adelegate%3Adelegate%3A0.2.0

And misreporting

**Version of dependency-check used**
Using the ant based check 5.3.2

**Log file**
When reporting errors, 99% of the time log file output is required. Please post the log file as a [gist](https://gist.github.com/) and provide a link in the new issue.

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by jeremylong** [comment]
Just tested this with 6.0.2 and it appears to be resolved.
