### ISSUE TITLE
How to scan a repository containing both multi-module maven project and Node.js project?

### ISSUE THREAD

**Issue by nasifimtiazohi** [dependency-check/DependencyCheck#2762]
I am trying to scan this project - https://github.com/openmrs/openmrs-module-coreapps that has both multimodule `maven` project (with a root `pom.xml` file)  and a Node.js project (with a root `package.json` file). Ideally, I would like to have vulnerable dependency report for both maven project in an aggregated way and the Node.js project with some way to distinguish between Java and JavaScript packages.

If I run the cli tool in the repository path, with the command `dependency-check --enableExperimental --format CSV --scan ./`, the generated report contains 606 vulnerabilities all javascript packages.

If I run the maven plugin with the the command `mvn org.owasp:dependency-check-maven:aggregate -Dformat=CSV`, the generated report contain 771 vulnerabilities with 602 being maven packages and 169 JavaScript packages. I am not sure if the maven plugin has experimental analyzer enabled but seems like it still detects javascript packages but not all when run through cli tool.

What is the best approach for me in this case so that I can ensure I am correctly getting vulnerability report for both Maven and JavaScript packages?

**Comment by mprins** [comment]
using a configured maven plugin will give you the best results. See  https://jeremylong.github.io/DependencyCheck/dependency-check-maven/aggregate-mojo.html for all the option and defaults

**Comment by jeremylong** [comment]
Additionally, make sure that `npm install` runs before the dependency-check analysis occurs.

**Comment by nasifimtiazohi** [comment]
Running `mvn org.owasp:dependency-check-maven:aggregate -Dformat=CSV -DenableExperimental` returned 1151 vulnerabilities; 603 from maven, 533 from npm, and 15 just from javascript. I guess this works.

However, for comparison I'd still put the result of `dependency-check --enableExperimental --format CSV --scan ./ --disableRubygems --disableBundleAudit`. It returns 615 vulnerabilities. 529 of which from npm, and 86 from javascript. I ran both scans at the same time, so why javascript vulnerability count is off I don't know.
However, the command exits with 
`[ERROR] class org.glassfish.json.JsonStringImpl cannot be cast to class javax.json.JsonObject (org.glassfish.json.JsonStringImpl and javax.json.JsonObject are in unnamed module of loader 'app')` which is why I think the command does not proceed to scanning maven packages.
