### ISSUE TITLE
Can I get a json result when I use it as a maven plugin。

### ISSUE THREAD

**Issue by ghost** [dependency-check/DependencyCheck#2775]
Can I get a json result when I use it as a maven plugin。
Currently I can only get html results。

**Comment by mprins** [comment]
html is the default, you can configure the plugin to any or all formats using https://jeremylong.github.io/DependencyCheck/dependency-check-maven/check-mojo.html#format

**Comment by ghost** [comment]
> html is the default, you can configure the plugin to any or all formats using https://jeremylong.github.io/DependencyCheck/dependency-check-maven/check-mojo.html#format


Thank you very much for your answer, I want to know if I can get the json result, when I use it like this on the command line "mvn org.owasp:dependency-check-maven:check"

**Comment by ghost** [comment]
i got it "mvn org.owasp:dependency-check-maven:check -Dformat=ALL"
