### ISSUE TITLE
Incorrect CPE classification for quartz-scheduler

### ISSUE THREAD

**Issue by Rob-Conan** [dependency-check/DependencyCheck#2776]
**Describe the bug**
Dependency Check when scanning pkg:maven/org.quartz-scheduler/quartz@1.8.4 fails to successfully generate the CPE required to match against the NVD

**Version of dependency-check used**
CLI and version used: 5.3.2

**Log file**
Scan results for this module: https://gist.github.com/Rob-Conan/3f04d98fe9b1140c493434277b95fde3

**To Reproduce**
When scanning the above module the evidence collected does not provide the information capable of generating the correct CPE to match against the NVD.
The issue itself was fixed in v2.3.2 as per this thread: https://github.com/quartz-scheduler/quartz/issues/467

**Expected behavior**
Return the correct CPE and CVE finds https://nvd.nist.gov/vuln/search/results?form_type=Advanced&cves=on&cpe_version=cpe%3A%2Fa%3Asoftwareag%3Aquartz%3A1.8.4

**Comment by jeremylong** [comment]
The fix will be included in the 6.0.0 release.
