### ISSUE TITLE
Scan fails without error message

### ISSUE THREAD

**Issue by chillheart** [dependency-check/DependencyCheck#2778]
**Describe the bug**

I am running dependency check in an Azure Pipeline and the steps fails at the end with an exit code 1.

The scan is being initiated using a Powershell script:

```
# Setting Java Memory to 8G, disabling dependency bundling
$Env:JAVA_OPTS="-Xss16m -Xmx1024m"

# Running DependencyCheck
D:\dependency-check\bin\dependency-check.bat `
    --project "ProjectName" `
    --scan "$(Build.SourcesDirectory)\Web\ProjectName\" `
    --out "$(Common.TestResultsDirectory)\dependency-check" `
    --log "$(Build.ArtifactStagingDirectory)\dependency-check.log" `
    --format HTML `
    --format JUNIT `
    --format JSON `
    --failOnCVSS 0 `
    --enableExperimental `
    --exclude "/.vscode/"
```
I ran the scan with verbose logs and there are no error messages or warning that I was able to find.

**Version of dependency-check used**
The problem occurs using version 5.3.2 of the CLI

**Log file**

The log file is ~150MB so I created a repo with a zipped log file.

https://github.com/chillheart/dependecychecklog

**To Reproduce**

1. Initiate the scan using the powershell script above.
2. Scan iterates through all of the analyzers
3. App exits with exit code of 1

**Expected behavior**
The scan should complete successfully if no errors occurred or report the error in the log if it did occur.

**Comment by jeremylong** [comment]
A negative return code means that there was an actual error, a return code of 1 means that the scan ran but found vulnerabilities above the `--failOnCVSS 0` setting - so if it found ANY vulnerabilities with this setting the scan fails. If you do not want the scan to fail for vulnerabilities being found - remove the setting or configure it to be 11. If you remove this setting you would get a return code of 0 - meaning no errors occurred.

**Comment by chillheart** [comment]
OK, thank you, that allowed the pipeline to complete and upload the report to SonarQube.
