### ISSUE TITLE
v6.0 and current.txt

### ISSUE THREAD

**Issue by thib3113** [dependency-check/DependencyCheck#2795]
Hello, 

maybe I'm too fast ( maybe I need to wait a little more for an automatic process ), but it seems that this file : https://github.com/jeremylong/DependencyCheck/blob/gh-pages/current.txt always says we are in 5.3.2 ( and not 6.0.0 ) . 

Is that normal ? ( in fact, I use this file with a script, to check if an update is available, and to update dependencyCheck )

**Comment by jeremylong** [comment]
Fixed now - small glitch this morning with the CI.
