### ISSUE TITLE
Gradle: No such property outputDirectory

### ISSUE THREAD

**Issue by willis7** [dependency-check/DependencyCheck#280]
When changing the task configuration using the `dependencyCheck` extension I get the following error.

```
A problem occurred evaluating script.
> No such property: outputDirectory for class: com.tools.security.extension.DependencyCheckConfigurationExtension_Decorated
```

I have forked the repo and will be making a fix with tests, but I opened this for tracking purposes.

**Comment by jeremylong** [comment]
Thanks for the PR - I merged it this morning.
