### ISSUE TITLE
MySQL compatibility broken

### ISSUE THREAD

**Issue by stefanneuhaus** [dependency-check/DependencyCheck#2807]
When running an analysis connected to a MYSQL database with DC version 6.0.0 (using the Gradle plugin 6.0.0.1) I get errors like:
```
An error occurred while analyzing '/Users/stefanneuhaus/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-starter-json/2.3.3.RELEASE/8c40b22a0635989ecc58f35d82fd55445be8822f/spring-boot-starter-json-2.3.3.RELEASE.jar' (NVD CVE Analyzer).
```

Observed while updating [dependencycheck-central-mysql-docker](https://github.com/stefanneuhaus/dependencycheck-central-mysql-docker) for DC v6 compatiblity.

**Comment by jeremylong** [comment]
I'll release 6.02 next weekend.
