### ISSUE TITLE
generate wrong report ver 6.0.0

### ISSUE THREAD

**Issue by sysmat** [dependency-check/DependencyCheck#2818]
**Describe the bug**
It show CVE for lib(io.jsonwebtoken:jjwt:0.9.1) but when I go to actual CVE it show ruby and another thing, but when doing report with ver 5.3.2 there is not CVE for json lib

**Version of dependency-check used**
The problem occurs using version 6.0.0 of the ____ (maven plugin,)

**Log file**
```
jjwt-0.9.1.jar | cpe:2.3:a:json_project:json:0.9.1:*:*:*:*:*:*:* | pkg:maven/io.jsonwebtoken/jjwt@0.9.1 | HIGH | 2 | High | 28
```

**To Reproduce**

**Expected behavior**
The same result as with ver 5.3.2

**Additional context**

**Comment by mprins** [comment]
Not a bug, but a false positive. 
see also #2792 and #2794

**Comment by jeremylong** [comment]
I just tested this with 6.0.2 and it appears to be resolved. I had contacted the NVD about a few of the vendor names related to json_project - so that likely resolved this one.
