### ISSUE TITLE
False Positive on Microsoft.DiaSymReader.Native

### ISSUE THREAD

**Issue by aarongoldenthal** [dependency-check/DependencyCheck#2819]
False positive on Nuget package [Microsoft.DiaSymReader.Native.*.dll](https://www.nuget.org/packages/Microsoft.DiaSymReader.Native/) - reported as `cpe:2.3:a:dia:dia:64:*:*:*:*:*:*:*` (for at least x86 and amd64 versions).

**Comment by jeremylong** [comment]
I just tested this with the latest build and not seeing this.  What version of ODC are you using and

**Comment by mushu999** [comment]
Still an issue in v6.5.0 of dependency checker...

Microsoft.DiaSymReader.Native.x86.dll
File Path: C:\...\bin\roslyn\Microsoft.DiaSymReader.Native.x86.dll
MD5: 4ff7094e3edfda47ced912012044296b
SHA1: c6f3c9d81713687dc3820d8cabf14c2a32208d27
SHA256:f21da9fb831ac943736135b6ee109a4b352511b8d6c07cb03c66b61996d1ddc9
