### ISSUE TITLE
gradle build doesnt fail when there are vulnerabilities

### ISSUE THREAD

**Issue by networkandcode** [dependency-check/DependencyCheck#2822]
I was trying the OWASP dependency check for Gradle in a Jenkins pipeline, it found vulnerabilities, but the build still passes... am I doing this correctly
Version: 5.3.2

commands tried:
```
gradle dependencyCheckAnalyze 
gradle -b build.gradle build -x test
```
rest of the settings are default.

```
> Task :dependencyCheckAnalyze
Checking for updates and analyzing dependencies for vulnerabilities
A new version of dependency-check is available. Consider updating to version 6.0.1.
----------------------------------------------------
Found 33 vulnerabilities in project <projectname>

BUILD SUCCESSFUL in 3m 46s
1 actionable task: 1 executed
```

**Comment by jeremylong** [comment]
You need to configure the `failBuildOnCVSS` to the threshold you want to fail on.  If you want it to fail on any vulnerability set the value to zero (0).

https://jeremylong.github.io/DependencyCheck/dependency-check-gradle/configuration.html

**Comment by networkandcode** [comment]
thanks @jeremylong , it worked
is there a gradle cli equivalent to do the dependency check steps with a single command, rather than modifying build.gradle.
