### ISSUE TITLE
"Unable to parse MSBuild project file" exception when using version 5.3.2

### ISSUE THREAD

**Issue by MugdhaShukla** [dependency-check/DependencyCheck#2823]
When we are running the Owasp Dependency check tool in Azure DevOps pipeline we are getting below exception

org.owasp.dependencycheck.analyzer.exception.AnalysisException: org.owasp.dependencycheck.data.nuget.MSBuildProjectParseException: Unable to parse MSBuild project file
exception: org.owasp.dependencycheck.analyzer.exception.AnalysisException: org.owasp.dependencycheck.analyzer.exception.AnalysisException: org.owasp.dependencycheck.data.nuget.MSBuildProjectParseException: Unable to parse MSBuild project file
org.owasp.dependencycheck.analyzer.MSBuildProjectAnalyzer.analyzeDependency(MSBuildProjectAnalyzer.java:170)
org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
java.util.concurrent.FutureTask.run(Unknown Source)
java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
java.lang.Thread.run(Unknown Source)

Can we get help for this? What needs to be done?

**Comment by jeremylong** [comment]
Can you post your `csproj` file?

**Comment by MugdhaShukla** [comment]
[log_17_30498.zip](https://github.com/jeremylong/DependencyCheck/files/5260826/log_17_30498.zip)
 I have attached the log file for the error. 

Most of the error are "Content is not allowed in prolog "

**Comment by jeremylong** [comment]
I just wrapped the input stream with a `BOMInputStream` to resolve the content is not allowed in prolog error. This will be included in the next release.
