### ISSUE TITLE
Document a quick git clone

### ISSUE THREAD

**Issue by javabeanz** [dependency-check/DependencyCheck#283]
Current git repo is over 1 GB in size, which is abnormally huge for a java project in git. please document ways to make quick git clones, so developers do not drag along all history and have to wait over 45 minutes for a default git clone to finish. For instance, a shallow clone saves a lot of time. See also  : http://blogs.atlassian.com/2014/05/handle-big-repositories-git/
I wonder if github will allow for forks for these kind of sizes. A major cleanup of the repo would be my urgent advice.

**Comment by jeremylong** [comment]
The main problem is that there are a few binaries in the test resources. I made changes to the largest of these - thus the recent increase in bloat. This was previously an issue (see #129); I will perform similar cleanup shortly.

**Comment by jeremylong** [comment]
History has been re-written to remove large blobs from the repo. I will document the shallow clone in the readme.md soon.

**Comment by javabeanz** [comment]
Super ! default clone is now back to under 4 minutes.

**Comment by jeremylong** [comment]
I have also documented the shallow clone in the readme.md:

``` bash
git clone --depth 1 git@github.com:jeremylong/DependencyCheck.git
```
