### ISSUE TITLE
missing / wrong grant in initialize_postges.sql

### ISSUE THREAD

**Issue by amandel** [dependency-check/DependencyCheck#2831]
**Describe the bug**
Permission set in initialize_postgres.sql seems wrong.

**Version of dependency-check used**
The problem occurs using version 6.0.1

**Context**
In https://github.com/jeremylong/DependencyCheck/blob/b1e4e84a0b6230e5eedd85b6e85420db9fbb83f2/core/src/main/resources/data/initialize_postgres.sql#L89

the GRANT refers to a function that is defined already in line 74 the code should be more likely a grant for the function defined just above:

```SQL
GRANT EXECUTE ON FUNCTION public.merge_ecosystem(varchar(255),varchar(255),varchar(255)) TO dcuser;
```

**Comment by jeremylong** [comment]
Thanks! I just updated the sql.
