### ISSUE TITLE
Maven plugin throws a NullPointerException on purge

### ISSUE THREAD

**Issue by jashaj** [dependency-check/DependencyCheck#2832]
**Describe the bug**
When running `mvn org.owasp:dependency-check-maven:6.0.1:purge` it throws a NullPointerException.

**Version of dependency-check used**
Maven plugin version 6.0.1 on macOS 10.15 with AdoptOpenJDK 11 and Maven 3.6.3_1.

**Log file**
Debug output: https://gist.github.com/jashaj/d5077e2291049b166dc4c9cea4615916 

**To Reproduce**
1. First build the project with `mvn clean install`
2. Run the check with `mvn oorg.owasp:dependency-check-maven:aggregate`. No vulnerabilities found.
3. Purge the database with `mvn org.owasp:dependency-check-maven:purge`

**Expected behavior**
The purge should succeed even if there's nothing to purge

**Comment by jeremylong** [comment]
Thanks for pointing this out - a fix will be included in the next release.
