### ISSUE TITLE
aws-json-protocol-2.13.76.jar Vulnerabilities 

### ISSUE THREAD

**Issue by RaghunathE** [dependency-check/DependencyCheck#2833]
**Describe the bug**
We are seeing Vulnerability on latest NVD for aws-json-protocol-2.13.76.jar

reference link:
https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Ajson_project&cpe_product=cpe%3A%2F%3Ajson_project%3Ajson&cpe_version=cpe%3A%2F%3Ajson_project%3Ajson%3A2.13.76

**Log file**

CWE-78 | Improper Neutralization of Special Elements used in an OS Command ('OS Command Injection')
his affects the package json before 10.0.0. It is possible to inject arbritary commands using the parseLookup function.
CWE-78 Improper Neutralization of Special Elements used in an OS Command ('OS Command Injection')

CVSSv2:
Base Score: MEDIUM (6.5)
Vector: /AV:N/AC:L/Au:S/C:P/I:P/A:P
CVSSv3:
Base Score: HIGH (7.2)
Vector: CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:H/I:H/A:H

Regards
Raghunath 

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by chadlwilson** [comment]
Can you check on `6.0.2`? This is possibly fixed along with #2794

**Comment by jeremylong** [comment]
This has been fixed in code and will be released in 6.0.3.

**Comment by RaghunathE** [comment]
> Can you check on `6.0.2`? This is possibly fixed along with #2794

Resolved in 6.0.2
