### ISSUE TITLE
[ERROR] Unable to connect to the dependency-check database while running dependency check

### ISSUE THREAD

**Issue by Vijayhv** [dependency-check/DependencyCheck#2834]
Hi,

Am getting the below error while running dependency check.
[ERROR] One or more fatal errors occurred
[ERROR] Unable to connect to the dependency-check database

I have installed a local Oracle Database version 19c which comes with ojdbc8.jar
Have tried using ojdbc8.jar as well in the below command.
Have also tried downloading and using ojdbc6.jar
Below is the command am trying to execute.

dependency-check.bat --project "mvel2-2.4.8.Final"  --disableCentral --out "D:\ABC\EFG\HIJ\AABB\data" --scan "D:\ABC\EFG\HIJ\AABB\data"  --dbDriverName "oracle.jdbc.OracleDriver" --dbPassword "user1" --dbUser "abc123" --dbDriverPath "C:\Oracle\LocalDB\Oracle_db_setup\lib\ojdbc6.jar"  --connectionString "jdbc:oracle:thin:/@localhost:1521:mydb"

Could you kindly help in understanding what is going wrong.

**Comment by jeremylong** [comment]
Please see the release notes for 6.0.0: https://github.com/jeremylong/DependencyCheck/blob/main/RELEASE_NOTES.md#version-600-2020-09-07 and #2755.
