### ISSUE TITLE
VerifyError on gradle dependencyCheckAnalyze

### ISSUE THREAD

**Issue by dan-lind** [dependency-check/DependencyCheck#2838]
**Describe the bug**
After all NVD CVEs have been downloaded, I get
`java.lang.VerifyError: class com.fasterxml.jackson.databind.deser.SettableBeanProperty$Delegating overrides final method com.fasterxml.jackson.databind.deser.SettableBeanProperty.getDeclaringClass()`

**Version of dependency-check used**
The problem occurs using version org.owasp:dependency-check-gradle:6.0.1 and openjdk version "11.0.8" 2020-07-14 LTS

**Log file**
https://gist.github.com/dan-lind/25c6f54accab060c9abfa30c3123f81e

**To Reproduce**
run ` gradle dependencyCheckAnalyze`

**Expected behavior**
Expected scan to finish

**Comment by jeremylong** [comment]
Can you verify what version of jackson-databind is in the build by running:

```
gradle buildEnvironment | grep jackson-databind
```

**Comment by dan-lind** [comment]
I thought I had found the issue, as `gradle buildEnvironment | grep jackson-databind` showed that a plugin I had was pulling in a very old version of jackson-databind. I removed that plugin, and now it looks fine

```
$ gradle buildEnvironment | grep jackson-databind
|    |    +--- com.fasterxml.jackson.core:jackson-databind:2.11.2
|    |    |    \--- com.fasterxml.jackson.core:jackson-databind:2.11.2 (*)
|    |    |    +--- com.fasterxml.jackson.core:jackson-databind:2.11.2 (*)
|    |    +--- com.fasterxml.jackson.core:jackson-databind:2.11.2 (*)
|    |    |    \--- com.fasterxml.jackson.core:jackson-databind:2.11.2 (*)
```

But to my suprise, re-running `gradle dependencyCheckAnalyze` still gives me the exact same exception...

**Comment by jeremylong** [comment]
Did you run a clean between builds?

**Comment by dan-lind** [comment]
Yes I did!

**Comment by jeremylong** [comment]
I know this is one last stupid question...  I'm only asking as I can't reproduce this.  After removing the plugin and running clean - did you re-check `gradle buildEnvironment | grep jackson-databind`?

**Comment by dan-lind** [comment]
That was not a stupid question! Apparently I didn't run `gradle buildEnvironment | grep jackson-databind` again after cleaning, and for some reason an old docker plugin had pulled an old version of jackson-databind back in. Now it works!
Thanks for your patience 🥇

**Comment by dsvensson** [comment]
Getting the same issue here with latest version of this plugin:

```
Caused by: java.util.concurrent.ExecutionException: java.lang.VerifyError: class com.fasterxml.jackson.databind.deser.SettableBeanProperty$Delegating overrides final method com.fasterxml.jackson.databind.deser.SettableBeanProperty.getDeclaringClass()Ljava/lang/Class;
```

All entries in buildenv checks out... 
```
./gradlew buildEnvironment | grep jackson-databind
|         |    |    +--- com.fasterxml.jackson.core:jackson-databind:2.12.2
|         |    |    |    |         +--- com.fasterxml.jackson.core:jackson-databind:2.12.2 (c)
|         |    +--- com.fasterxml.jackson.core:jackson-databind:2.12.2 (*)
|         |    |    \--- com.fasterxml.jackson.core:jackson-databind:2.12.2 (*)
```

I used to have https://plugins.gradle.org/plugin/com.patdouble.awsecr enabled which depends on 2.6 something. I removed it per recommendation above, and as you can see, all versions are at 2.12.2. Any ideas what I might be missing?

Reverting to version 5.3.2.1 of the plugin fixes the problem. Will try to nail it down to the point of breakage.
