### ISSUE TITLE
zip files no no longer downloadable from bintray. 

### ISSUE THREAD

**Issue by sydseter** [dependency-check/DependencyCheck#2840]
**Describe the bug**
All zip files at https://dl.bintray.com/jeremy-long/owasp/ are unavailable. The status Forbidden is returned when I try to download from the list directly or though bintray's webportal. It doesn't look like other projects on bintray has any issues and the bintray hasn't reported any issues with their services: https://status.bintray.com/

**Version of dependency-check used**
All

**Log file**
NP

**To Reproduce**
1. Go to 'https://dl.bintray.com/jeremy-long/owasp/'
2. Click on 'any link'
3. See error

**Expected behavior**
Download should happen.

**Additional context**
NP

**Comment by gtudan** [comment]
Looks like #2739 strikes again. 
Could we please have the binary for 5.3.2 on the GitHub Release?

**Comment by sydseter** [comment]
Thanks for the info. Yes, so it appears. Got the latest zip from here: https://github.com/jeremylong/DependencyCheck/releases

**Comment by sydseter** [comment]
I guess that is where we need to get them from now on.

**Comment by gtudan** [comment]
It would still be cool if we could get the binaries for the 5.x from GitHub. We're not yet ready to update to 6 everywhere.

**Comment by jeremylong** [comment]
Unfortunately - I don't have the 5.3.2 CLI or Ant task locally anymore. We'll need to wait until after the first when we can download from bintray again.

**Comment by gtudan** [comment]
@jeremylong It's a new month and bintray is back - here's your chance ;-)

**Comment by jeremylong** [comment]
done
