### ISSUE TITLE
Report diff between plugin / cli

### ISSUE THREAD

**Issue by nzk1912** [dependency-check/DependencyCheck#2846]
same maven project,
analysis with maven plugin model and cli model.
the html report :
   two model, File Path,MD5 SHA1  SHA256  is ok
bug, Description and Lincnse info :  plugin model is ok,   cli model  is null.
why?

**Comment by mprins** [comment]
because the maven plugin benefits from the dependency management tool that maven is and the cli doesn't

**Comment by nzk1912** [comment]
> because the maven plugin benefits from the dependency management tool that maven is and the cli doesn't


I don't think so. The jar package is found in both ways. Where are the descriptions and license information read from?
I think it is read from the jar, at least the license information is like this, because there is a license file in the jar.
I have tried many times. A small number of descriptions and licenses can also be obtained in the CLI mode, but most of them are still not available. However, there are both descriptions and licenses in the plugin mode.

**Comment by nzk1912** [comment]
> because the maven plugin benefits from the dependency management tool that maven is and the cli doesn't

I know ,you are right ,thank you~

plugin model,read maven repository files,   a same name pom file with the jar ~ info  here.
