### ISSUE TITLE
Unable to parse MSBuild project file" exception when using version 6.0.2

### ISSUE THREAD

**Issue by MugdhaShukla** [dependency-check/DependencyCheck#2847]
Hi,

We updated the Owasp version from 5.3.2 to 6.0.2 but still getting the same exception.
I have attached the logs with this question.

[17.txt](https://github.com/jeremylong/DependencyCheck/files/5305807/17.txt)

**Comment by mprins** [comment]
> `[Fatal Error] :2:1: Content is not allowed in prolog.`

seems your csproj files are not valid XML, probably a BOM is the first character of the file making them invalid XML

**Comment by jeremylong** [comment]
Any chance you can post your `csproj` file?

**Comment by MugdhaShukla** [comment]
[Propay.AuthenticatedDevice.Service.txt](https://github.com/jeremylong/DependencyCheck/files/5317784/Propay.AuthenticatedDevice.Service.txt)

**Comment by mprins** [comment]
As I suspected:

```
└─ $ ▶ file Propay.AuthenticatedDevice.Service.txt 
Propay.AuthenticatedDevice.Service.txt: XML 1.0 document, UTF-8 Unicode (with BOM) text, with CRLF line terminators

```

You will need to fix the files by removing the UTF-8 BOM, eg. using a text editor like notepad++ or a powershell script like https://gallery.technet.microsoft.com/scriptcenter/How-to-remove-UTF8-Byte-a66fc0b2

**Comment by jeremylong** [comment]
Sorry about that - I put a BOM stream in to resolve this but forgot to call `BOMInputStream.getBOM()` to actual read/skip the BOM. This will be fixed in the next version.

**Comment by MugdhaShukla** [comment]
Thanks, When we will have the 6.0.3 version out
