### ISSUE TITLE
plugin freezes during scanning

### ISSUE THREAD

**Issue by VolhaRS** [dependency-check/DependencyCheck#2849]
Hello,
during scanning of one component of our java application, the plugin is freezing. We try dependency check cli and Jenkins plugin and the result is the same. After 30 minutes, scanning ends with an error "[ERROR] Analysis task was cancelled."

![image](https://user-images.githubusercontent.com/52915455/94703414-77a81e80-0347-11eb-9b83-d4e1825ef39f.png)

Logfile in attachments
[logs.txt](https://github.com/jeremylong/DependencyCheck/files/5307208/logs.txt)

**Comment by jeremylong** [comment]
Looking at the log - things don't make sense to me...  In that we have:

```
2020-09-30 18:11:14,815 org.owasp.dependencycheck.data.nvdcve.CveDB:412
DEBUG - Entering finalize
2020-09-30 18:41:14,638 org.owasp.dependencycheck.Engine:1159
ERROR - Analysis task was cancelled.
```

CveDB line 412 is just calling some fairly straightforward resource cleanup. I just added a bunch more logging that will be included in 6.0.3.

**Comment by VolhaRS** [comment]
I have rerun scanning with the 6.0.3 plugin version. Logs in attachments
[debug.log](https://github.com/jeremylong/DependencyCheck/files/5516432/debug.log)

**Comment by jeremylong** [comment]
This looks to be getting hung on `bundle.js` with the RetireJS analyzer. My guess is bundle.js is a fairly large file?

There is a hard 30 minute timeout that can be extended:

```shell
export JAVA_OPTS='-Dodc.analysis.timeout=90'
```
