### ISSUE TITLE
tmp is not cleaned up properly - causes high inode utilization

### ISSUE THREAD

**Issue by blaksec** [dependency-check/DependencyCheck#286]
When running on large trees, the temp directory gets quickly filled up with consecutively-named folders. Some folders are empty, some contain directory structures of the jar files it was analyzing (no files, just folders). 

Is that by design? i.e. do these have to stay created till the scan finishes? or can they be deleted after individual artefact was processed. This might not be an issue when processing a handful of files but becomes one when periodically scanning larger systems with hundreds of jars.

**Comment by jeremylong** [comment]
The files get extracted to these directories (zip, tgz, war, ear) and these files need to be around for the entire duration of the scan. However, Settings.cleanup() is supposed to delete these directories; although I have seen things (such as empty directories get left) - this has been on my list to figure out but I haven't had any luck.

--Jeremy

**Comment by jeremylong** [comment]
A change was added to DC that might fix the issue in 1.3.0. I have added another attempt to delete the temp files in 1.3.1-SNAPSHOT.

**Comment by jeremylong** [comment]
Further testing on my system has not been able to reproduce the issue (I had seen this occur previously).
