### ISSUE TITLE
H2 database performance decreased with v6

### ISSUE THREAD

**Issue by aikebah** [dependency-check/DependencyCheck#2861]
**Describe the bug**
As [discussed on the maillist](https://groups.google.com/forum/#!topic/dependency-check/Tw0rBVedT5g) users observed a significant slow-down with Dependency Check v6.
I did some digging around and found a suspect that upon initial testing appears to be valid: e1753080478061327216eb9988a0f3ccddf72992 removed (accidentally I suppose, given the effects) the cpeEntry index from the H2 database, slowing down getCPEs significantly due to full-table scans .

**Version of dependency-check used**
The problem occurs using version 6.0.2 of the maven plugin

**Logs**
Extracts from logs for DependencyCheck 6.0.3 snapshot without the index on Jim Sellers' repository (total runtime :
[INFO] Finished CPE Analyzer (4 seconds)
[INFO] Finished CPE Analyzer (2 seconds)
[INFO] Finished CPE Analyzer (2 seconds)
[INFO] Finished CPE Analyzer (2 seconds)
[INFO] Finished CPE Analyzer (2 seconds)
[INFO] Finished CPE Analyzer (2 seconds)
[INFO] Finished CPE Analyzer (2 seconds)
[INFO] Finished CPE Analyzer (2 seconds)
[INFO] Finished CPE Analyzer (2 seconds)
[INFO] Finished CPE Analyzer (2 seconds)
[INFO] Finished CPE Analyzer (2 seconds)
[INFO] Total time:  01:00 min

A total of 24 seconds reported as spent in the CPE Analyzer

Extracts from logs for DependencyCheck 6.0.3 snapshot with the index on Jim Sellers' repository:
[INFO] Finished CPE Analyzer (2 seconds)
[INFO] Finished CPE Analyzer (1 seconds)
[INFO] Finished CPE Analyzer (1 seconds)
[INFO] Finished CPE Analyzer (0 seconds)
[INFO] Finished CPE Analyzer (0 seconds)
[INFO] Finished CPE Analyzer (0 seconds)
[INFO] Finished CPE Analyzer (0 seconds)
[INFO] Finished CPE Analyzer (0 seconds)
[INFO] Finished CPE Analyzer (0 seconds)
[INFO] Finished CPE Analyzer (0 seconds)
[INFO] Finished CPE Analyzer (0 seconds)
[INFO] Total time:  42.489 s

A total of 4 seconds reported as spent in the CPE Analyzer 

**To Reproduce**
1. Clone Jim Sellers' repository
2. Run his script
3. Observe the significant difference in total run time

**Expected behavior**
Only minor differences in speed due to new datamodel

**Additional context**
PR to restore the index will follow after I've locally validated that all tests properly pass

**Comment by jeremylong** [comment]
Thank you for investigating this - and the PR! This will be in the 6.0.3 release - I'm just trying to cleanup the FP reports before publishing so probably next weekend....
