### ISSUE TITLE
DEV dependencies still not skipped with --nodeAuditSkipDevDependencies

### ISSUE THREAD

**Issue by sebastienroux** [dependency-check/DependencyCheck#2864]
Hello,

Dev dependencies are still analyzed and reported as false positives despite the use of --nodeAuditSkipDevDependencies flag.

Command : 
`dependency-check.sh --format ALL  --project  "$CI_PROJECT_NAME" --failOnCVSS  0 --nodeAuditSkipDevDependencies --disableArchive --scan .`

CLI Version 6.0.2

For example : node-sass modules declared as "dev" in package.json
Here the result of analysis (html/json) and package-lock.json / package.json

https://gofile.io/d/ecl1Iz 

Thanks :)

**Comment by jeremylong** [comment]
The fix for this has already been committed to code and will be included in 6.03.

**Comment by sebastienroux** [comment]
> The fix for this has already been committed to code and will be included in 6.03.

Hello @jeremylong , i tried with dev version 6.0.3:SNAPSHOT with maven and dev dependancies are still in the report :(

**Comment by jeremylong** [comment]
@sebastienroux can you provide a sample package.json and package-lock.json?

**Comment by jeremylong** [comment]
@sebastienroux also - have you disabled the NodeJS analyzer via `--disableNodeJS`?  The nodeJS analyzer is on track to be drastically changed or retired. It may only be needed for the `vendor` directory in the future - but I have to do some more reading/testing before making a final decision on that.
