### ISSUE TITLE
False Positive on [msal4j]

### ISSUE THREAD

**Issue by DeCaMil** [dependency-check/DependencyCheck#2865]
False positive on library pkg:maven/com.microsoft.azure/msal4j@1.6.2: - reported as:
* `cpe:2.3:a:http_authentication_library_project:http_authentication_library:1.6.2`
* `cpe:2.3:a:microsoft:authentication_library:1.6.2:*:*:*:*:*:*:*`

**Comment by jeremylong** [comment]
I added a base suppression rule for the http_authentication_library. However, I'm not convinced `cpe:2.3:a:microsoft:authentication_library:1.6.2:*:*:*:*:*:*:*` is a false positive.
