### ISSUE TITLE
Running 6.0.2 cli fails with upgrade_4.2.sql not found

### ISSUE THREAD

**Issue by briankavanaugh** [dependency-check/DependencyCheck#2867]
**Describe the bug**
I just updated our command line version from 5.3 to 6.0.2. Running it fails with :java.io.FileNotFoundException: data\upgrade_4.2.sql (The system cannot find the path specified). In searching for this error, I was pointed to https://github.com/jeremylong/DependencyCheck/tree/main/core/src/main/resources/data. However, upgrade_4.2.sql isn't there; the most recent version is upgrade_4.1.sql.

**Version of dependency-check used**
The problem occurs using version 6.0.2 of the cli

**Comment by NiklasA** [comment]
@briankavanaugh: I could solve it with: `mvn org.owasp:dependency-check-maven:6.0.2:purge`. It seems like that there is another cache/database/store whatever, which will be deleted by the purge command.

**Comment by jeremylong** [comment]
I just update the error message for this scenario.  However, this is documented in both the release notes and the [README.md](https://github.com/jeremylong/DependencyCheck#600-upgrade-notice).
