### ISSUE TITLE
Upgrade h2 to 1.4.200

### ISSUE THREAD

**Issue by sellersj** [dependency-check/DependencyCheck#2869]
**Describe the bug**
Upgrade h2. The data.zip file has to be upgraded

**Version of dependency-check used**
6.0.2

**To Reproduce**
1. The h2 database can't simply be upgraded with the h2 format stored in data.zip. It has to be exported an imported
http://www.h2database.com/html/tutorial.html#upgrade_backup_restore

**Expected behavior**
For dependency check to work with 1.4.200
I expect if people are upgrading, they will have to delete the h2 database.

**Additional context**
Steps to fix it:

cd src/test/resources 
mvn dependency:get -Dartifact=com.h2database:h2:1.4.199
mvn dependency:get -Dartifact=com.h2database:h2:1.4.200

unzip data.zip
mv data.zip data.zip.old

java -cp ~/.m2/repository/com/h2database/h2/1.4.199/h2-1.4.199.jar org.h2.tools.Script -url jdbc:h2:./dc -user "dcuser" -password DC-Pass1337\! -script backup.sql 

mv dc.mv.db dc.mv.db.old

java -cp ~/.m2/repository/com/h2database/h2/1.4.200/h2-1.4.200.jar org.h2.tools.RunScript -url jdbc:h2:./dc -user "dcuser" -password DC-Pass1337\! -script backup.sql 

zip data.zip dc.mv.db

# cleanup
rm backup.sql 
rm data.zip.old
rm dc.mv.db.old

**Comment by pwagland** [comment]
Hasn't this PR been superseded by #3928? That is, should this one be closed?

**Comment by sellersj** [comment]
Agreed. This can be closed.
