### ISSUE TITLE
CveDB loadCpeEcosystemCache loads cache with (vendor,vendor) pairs

### ISSUE THREAD

**Issue by aikebah** [dependency-check/DependencyCheck#2871]
**Describe the bug**
While looking at how to incorporate the changes for Oracle I stumbled upon a bug in CveDB. https://github.com/jeremylong/DependencyCheck/blob/9780493d25791e3fa938d1c77c3b52a82af830ea/core/src/main/java/org/owasp/dependencycheck/data/nvdcve/CveDB.java#L865
When loading the EcoSystemCache from the DB it loads the vendor in both Left and Right of the pair used as the map key, rather than loading vendor in Left and product in Right

**Version of dependency-check used**
The problem occurs using version 6.X of the core

**Log file**
N/A spotted on code inspection.

**Expected behavior**
Left of the pair gets filled with vendor, Right of the pair gets filled with product

**Additional context**
If no-one else gets to it to code a fix I'll work on creating one after finishing the Oracle support for the DC v6 database changes.

**Comment by jeremylong** [comment]
omg - thank you for noticing this.  I'll get it updated shortly.
