### ISSUE TITLE
6.0.3-SNAPSHOT : Dev dependencies still not skipped despite the nodeAuditSkipDevDependencies flag

### ISSUE THREAD

**Issue by sebastienroux** [dependency-check/DependencyCheck#2875]
**Describe the bug**
Despite the --nodeAuditSkipDevDependencies flag, dev dependencies are still analyzed and showed on the report

**Version of dependency-check used**
MAven Dependency-Check Core version 6.0.3-SNAPSHOT

**To Reproduce**
```
./cli/target/release/bin/dependency-check.sh
      --format ALL
      --failOnCVSS  0
      --nodeAuditSkipDevDependencies
      --disableArchive
      --scan .
```

[dependency-check-report.html.txt](https://github.com/jeremylong/DependencyCheck/files/5347071/dependency-check-report.html.txt)
[package-lock.json.txt](https://github.com/jeremylong/DependencyCheck/files/5347074/package-lock.json.txt)
[package.json.txt](https://github.com/jeremylong/DependencyCheck/files/5347076/package.json.txt)
[dependency-check-report.json.txt](https://github.com/jeremylong/DependencyCheck/files/5347090/dependency-check-report.json.txt)

**Additional context**
I made a gitlab integration with dep-check : https://gitlab.com/boloss/test-dependency-check

If you run a pipeline on master, it use CLI 6.0.2 and creating 2 parallel jobs : 1 installing with npm , the other one installing with yarn/synp. Then analysing with dep-check.
-> Last pipeline https://gitlab.com/boloss/test-dependency-check/-/pipelines/199721327 (you can download artifacts in each jobs)

If you run a pipeline on branch version/maven-dev-snapshot, same but with maven Dependency-Check Core version 6.0.3-SNAPSHOT.
https://gitlab.com/boloss/test-dependency-check/-/pipelines/199720933

**Comment by jeremylong** [comment]
Can you retest whether or not dev dependencies are skipped if you include `--disableNodeJS` in the execution?  The NodeJS analyzer will likely soon be removed or possibly re-purposed to only look at `vendor` directory.

**Comment by sebastienroux** [comment]
@jeremylong it's working with --disableNodeJS and no more tons of false positives :)
