### ISSUE TITLE
Dependency-Check-Ant with nvd mirror

### ISSUE THREAD

**Issue by EvgeniaPatsoni** [dependency-check/DependencyCheck#2889]
I have created a local mirror of the NVD database and managed to successfully call the mirrored files and generate a report using _dependency-check-maven_ plugin, in a maven project. However, I now need to call the mirrored files in an _ant_ project, but since I am not at all familiar with ant I cannot seem to make it work properly. 

Could you please let me know how and where I should use _cveUrl12Modified_ and _cveUrl12Base_ properties? 
Here is my build.xml file.

```
<?xml version="1.0" encoding="UTF-8"?>
<project name="Project_Name"  default="sonar" basedir="." xmlns:sonar="antlib:org.sonar.ant">

  <!-- Dependency check property -->
  <property name="dependency-check.home" value="dependency-check-ant"/>
  <property name="project-dependencies" value="lib/.."/>
  <path id="dependency-check.path">
    <pathelement location="${dependency-check.home}/dependency-check-ant.jar"/>
    <fileset dir="${dependency-check.home}/lib">
      <include name="**/*.jar"/>
    </fileset>
  </path>
  <taskdef resource="dependency-check-taskdefs.properties">
    <classpath refid="dependency-check.path" />
  </taskdef>
  <target name="dependency-check" description="Dependency-Check Analysis">
    <dependency-check projectname="Project_Name" reportoutputdirectory="target" reportformat="ALL">
      <fileset dir="${project-dependencies}">
        <include name="**/*.jar"/>
      </fileset>
    </dependency-check>
  </target>
  <target name="dependency-check-update" description="Dependency-Check Update">
    <dependency-check-update />
  </target>
</project>
```
Thanks

**Comment by mprins** [comment]
https://jeremylong.github.io/DependencyCheck/dependency-check-ant/configuration.html describes these are properties, so they should be added to the task; in XML terms they are attributes on the `dependency-check` node, like `reportoutputdirectory` is.

**Comment by EvgeniaPatsoni** [comment]
@mprins Thank you, I added the properties to the task as you mentioned and it worked. 
I will paste the `dependency-check` node definition for anyone who faces the same issue.

```
<dependency-check projectname="Project_Name" reportoutputdirectory="target"
                      cveUrlModified="file:///nist_repo/nvdcve-1.1-modified.json.gz" cveUrlBase="file:///nist_repo/nvdcve-1.1-2020.json.gz" reportformat="ALL">
```
