### ISSUE TITLE
Dead links at OWASP page

### ISSUE THREAD

**Issue by dwvisser** [dependency-check/DependencyCheck#289]
On https://www.owasp.org/index.php/OWASP_Dependency_Check, under "Presentation", the following links are dead:
- dependency-check (PDF)
- dependency-check (PPTX)

**Comment by jeremylong** [comment]
Issue was caused by BFG - I didn't realize it would nuke items in the gh-pages branch. I have added the three files that had been deleted back.

--Jeremy
