### ISSUE TITLE
Error in reading/parsing stream from golang projects

### ISSUE THREAD

**Issue by Anshu2405** [dependency-check/DependencyCheck#2890]
**Describe the bug**

Dependency checker tool is throwing below errors during the analysis for golang project. Below are the last lines.
[INFO] Starting analyzing the json dependency report at : <path>/dependency-check-report.json
[ERROR] Error reading stream
[ERROR] Error reading stream
[ERROR] Error parsing stream

**Version of dependency-check used**
6.0.2

**Log file**

In the dependency checker html file, we see below analysis exceptions. Apart from the ERROR stated above, there are no further errors seen in the dependency checker execution log.

Error - 1 : Error reading stream
exception: org.owasp.dependencycheck.analyzer.exception.AnalysisException: Error reading stream
org.owasp.dependencycheck.data.golang.GoModJsonParser.process(GoModJsonParser.java:85)
org.owasp.dependencycheck.analyzer.GolangModAnalyzer.analyzeDependency(GolangModAnalyzer.java:310)
org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)
Cannot auto-detect encoding, not enough chars
cause: javax.json.JsonException: Cannot auto-detect encoding, not enough chars
org.glassfish.json.UnicodeDetectingInputStream.detectEncoding(UnicodeDetectingInputStream.java:130)
org.glassfish.json.UnicodeDetectingInputStream.<init>(UnicodeDetectingInputStream.java:75)
org.glassfish.json.JsonParserImpl.<init>(JsonParserImpl.java:95)
org.glassfish.json.JsonReaderImpl.<init>(JsonReaderImpl.java:73)
org.glassfish.json.JsonProviderImpl.createReader(JsonProviderImpl.java:136)
javax.json.Json.createReader(Json.java:225)
org.owasp.dependencycheck.data.golang.GoModJsonParser.process(GoModJsonParser.java:71)
org.owasp.dependencycheck.analyzer.GolangModAnalyzer.analyzeDependency(GolangModAnalyzer.java:310)
org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

Error - 2 : Error reading stream
exception: org.owasp.dependencycheck.analyzer.exception.AnalysisException: Error reading stream
org.owasp.dependencycheck.data.golang.GoModJsonParser.process(GoModJsonParser.java:85)
org.owasp.dependencycheck.analyzer.GolangModAnalyzer.analyzeDependency(GolangModAnalyzer.java:310)
org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)
Cannot auto-detect encoding, not enough chars
cause: javax.json.JsonException: Cannot auto-detect encoding, not enough chars
org.glassfish.json.UnicodeDetectingInputStream.detectEncoding(UnicodeDetectingInputStream.java:130)
org.glassfish.json.UnicodeDetectingInputStream.<init>(UnicodeDetectingInputStream.java:75)
org.glassfish.json.JsonParserImpl.<init>(JsonParserImpl.java:95)
org.glassfish.json.JsonReaderImpl.<init>(JsonReaderImpl.java:73)
org.glassfish.json.JsonProviderImpl.createReader(JsonProviderImpl.java:136)
javax.json.Json.createReader(Json.java:225)
org.owasp.dependencycheck.data.golang.GoModJsonParser.process(GoModJsonParser.java:71)
org.owasp.dependencycheck.analyzer.GolangModAnalyzer.analyzeDependency(GolangModAnalyzer.java:310)
org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)
Error - 3 : Error parsing stream
exception: org.owasp.dependencycheck.analyzer.exception.AnalysisException: Error parsing stream
org.owasp.dependencycheck.data.golang.GoModJsonParser.process(GoModJsonParser.java:83)
org.owasp.dependencycheck.analyzer.GolangModAnalyzer.analyzeDependency(GolangModAnalyzer.java:310)
org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)
Invalid token=COMMA at (line no=1058, column no=4, offset=35261). Expected tokens are: [STRING]
cause: javax.json.stream.JsonParsingException: Invalid token=COMMA at (line no=1058, column no=4, offset=35261). Expected tokens are: [STRING]
org.glassfish.json.JsonParserImpl.parsingException(JsonParserImpl.java:450)
org.glassfish.json.JsonParserImpl.access$1100(JsonParserImpl.java:79)
org.glassfish.json.JsonParserImpl$ObjectContext.getNextEvent(JsonParserImpl.java:511)
org.glassfish.json.JsonParserImpl.next(JsonParserImpl.java:376)
org.glassfish.json.JsonParserImpl.getObject(JsonParserImpl.java:335)
org.glassfish.json.JsonParserImpl.getValue(JsonParserImpl.java:182)
org.glassfish.json.JsonParserImpl.getArray(JsonParserImpl.java:328)
org.glassfish.json.JsonParserImpl.getArray(JsonParserImpl.java:164)
org.glassfish.json.JsonReaderImpl.readArray(JsonReaderImpl.java:129)
org.owasp.dependencycheck.data.golang.GoModJsonParser.process(GoModJsonParser.java:72)
org.owasp.dependencycheck.analyzer.GolangModAnalyzer.analyzeDependency(GolangModAnalyzer.java:310)
org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Expected behavior**

Report should be clean without any analysis errors.

**Comment by agisbert** [comment]
Same here

**Comment by jeremylong** [comment]
Any chance someone can provide the go.mod and go.sum so this can be reproduced?  What OS is being used?

**Comment by agisbert** [comment]
So, in my case, the error occurred after an issue downloading a go module;

```
[WARN] Warnings from go go: github.com/prometheus/client_golang@v1.4.1: git init --bare in /home/dependencycheck/go/pkg/mod/cache/vcs/3785b9359e0a97a9dc849585696cf17189b86b713b7e59c2842fb3c44d3ff610: exec: "git": executable file not found in $PATHgo: github.com/gorilla/mux@v1.7.4: git init --bare in /home/dependencycheck/go/pkg/mod/cache/vcs/6a3c85c1fa560af3c11df6bfabdc0a25c69c3127a5822875d586b38142c71189: exec: "git": executable file not found in $PATHgo: error loading module requirements
[WARN] An error occurred while analyzing '/builds/blabla/go.mod' (Golang Mod Analyzer).
[INFO] Finished Golang Mod Analyzer (0 seconds)
[INFO] Finished Dependency Merging Analyzer (0 seconds)
[INFO] Finished Version Filter Analyzer (0 seconds)
[INFO] Finished Hint Analyzer (0 seconds)
[INFO] Created CPE Index (0 seconds)
[INFO] Finished NPM CPE Analyzer (0 seconds)
[INFO] Created CPE Index (1 seconds)
[INFO] Finished CPE Analyzer (1 seconds)
[INFO] Finished False Positive Analyzer (0 seconds)
[INFO] Finished NVD CVE Analyzer (0 seconds)
[WARN] Unable to determine Package-URL identifiers for 3 dependencies
[INFO] Finished Sonatype OSS Index Analyzer (0 seconds)
[INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
[INFO] Finished Dependency Bundling Analyzer (0 seconds)
[INFO] Analysis Complete (2 seconds)
[ERROR] Error reading stream
```
The issue was just that I didn't have git installed when running it... Of course, installing git solved... false-positive, at least in my case.

**Comment by jeremylong** [comment]
So the warnings line was enough to resolve the issue.

**Comment by itsecforu** [comment]
> So the warnings line was enough to resolve the issue.

what's means? how to solve it?

**Comment by jeremylong** [comment]
It seemed like `git` was not installed - installing git, rebuilding, and re-running the scan solved the issue.  It is amazingly difficult to solve a problem unless someone can provide a failing project. If you can provide a test case - please open a new ticket.

**Comment by itsecforu** [comment]
> It seemed like `git` was not installed - installing git, rebuilding, and re-running the scan solved the issue. It is amazingly difficult to solve a problem unless someone can provide a failing project. If you can provide a test case - please open a new ticket.

Thx u a lot!
