### ISSUE TITLE
Support bzip2 archive format in ArchiveAnalyzer

### ISSUE THREAD

**Issue by dwvisser** [dependency-check/DependencyCheck#290]
The bzip2 archive format is enjoying increasing popularity. The core Apache Ant library includes the needed `InputStream` class (see https://git-wip-us.apache.org/repos/asf?p=ant.git;a=tree;f=src/main/org/apache/tools/bzip2). I believe this lives in the org.apache.ant:ant dependency already being used in dependency-check-ant, and so could very easily be made a dependency of dependency-check-core as well.

**Comment by jeremylong** [comment]
This can be added - but we should be using the code in [commons-compress](https://commons.apache.org/proper/commons-compress/apidocs/org/apache/commons/compress/compressors/bzip2/BZip2CompressorInputStream.html).

**Comment by dwvisser** [comment]
Even better. 😊

**Comment by jeremylong** [comment]
Dale - thanks for the PR!
