### ISSUE TITLE
ODC Arguments in Jenkins

### ISSUE THREAD

**Issue by mahzad** [dependency-check/DependencyCheck#2900]
in Jenkins invoke Dependency-check Arguments, I used bellow command :
 --format HTML --suppression  supress.xml 
![1](https://user-images.githubusercontent.com/3873092/96404983-1ad2b200-11e9-11eb-9cb9-87a4b6905d17.png)

supress.xml copied from ODC supress button report and stored in root of workspace.
![2](https://user-images.githubusercontent.com/3873092/96404158-0b526980-11e7-11eb-909e-fb67ef11e144.png)
 but in report HTML file , suppress does not work; in other mean the CVE is not removed.

Why? What is wrong?

**Comment by jeremylong** [comment]
The jenkins plugin is still seeking a new maintainer: https://github.com/jenkinsci/dependency-check-plugin#seeking-new-maintainer
