### ISSUE TITLE
Why are there vulnerable dependencies in core's pom.xml?

### ISSUE THREAD

**Issue by FRB-JIM** [dependency-check/DependencyCheck#2911]
Have there been any thoughts to updating the maven dependencies?  I am having trouble compiling because so many of the components are quarantined by our Nexus IQ instance:

- rhino 1.7.7.2
- spring-web 2.5.5
- spring-expression 3.0.0.RELEASE
- dojo-war 1.3.0
- strust2-core 2.1.2 -- 25 Critical/High.. THIS ONE IS ESPECIALLY BAD!
- admingui 4.0

There may be more, I just haven't gotten that far.  

It just seems a little ironic that a security tool about reviewing 3rd party dependencies would be using so many vulnerable dependencies.

**Comment by jeremylong** [comment]
We don't *use* these dependencies. These are test dependencies used to test the functionality of ODC (unit/integration). If you look at all of these in the POM you will notice they are all marked as `scope: test` and `optional: true`:

https://github.com/jeremylong/DependencyCheck/blob/f9b4f4136ec4c4e4d1d944faa64a3c8880794616/core/pom.xml#L354-L360

You can probably build using `-Dmaven.test.skip`.
