### ISSUE TITLE
maven plugin config ignored

### ISSUE THREAD

**Issue by delanym** [dependency-check/DependencyCheck#2921]
As per https://groups.google.com/g/dependency-check/c/haul5dBsOt8

Configuration settings in the pom are ignored. They work on the command line.
For example, to disable the .NET analyzer works, and to set a proxy

<build>...

      <plugin>
        <groupId>org.owasp</groupId>
        <artifactId>dependency-check-maven</artifactId>
        <version>6.0.2</version>
        <configuration>
            <cveUrlModified>http://warren/repository/nvd/1.1/nvdcve-1.1-modified.json.gz</cveUrlModified>
            <cveUrlBase>http://warren/repository/nvd/1.1/nvdcve-1.1-%d.json.gz</cveUrlBase>
            <assemblyAnalyzerEnabled>false</assemblyAnalyzerEnabled>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>check</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

**Comment by jeremylong** [comment]
How are you invoking dependency-check? Where is the plugin configuration located in the pom?

**Comment by delanym** [comment]
Its in build section. I invoke with `mvn org.owasp:dependency-check-maven:check`

**Comment by delanym** [comment]
It works when in the reporting section, invoked with `mvn site`

**Comment by jeremylong** [comment]
Either I'm not following your issue or I can't reproduce it... If I configure:

```xml
    <build>
        <plugins>
            <plugin>
              <groupId>org.owasp</groupId>
              <artifactId>dependency-check-maven</artifactId>
              <version>6.0.2</version>
                <configuration>
                  <assemblyAnalyzerEnabled>false</assemblyAnalyzerEnabled>
                  <format>ALL</format>
              </configuration>
              <executions>
                  <execution>
                      <goals>
                          <goal>check</goal>
                      </goals>
                  </execution>
              </executions>
            </plugin>
        </plugins>
    </build>
```
Then execute:
```
$ mvn org.owasp:dependency-check-maven:check -X > odc.log
```

I can then find in the logs:

```
[DEBUG] Setting: analyzer.assembly.enabled='false'
[DEBUG] Setting: analyzer.artifactory.parallel.analysis='true'
[DEBUG] Loaded Analyzer Archive Analyzer
[DEBUG] Loaded Analyzer File Name Analyzer
[DEBUG] Loaded Analyzer Jar Analyzer
[DEBUG] Loaded Analyzer Hint Analyzer
[DEBUG] Loaded Analyzer CPE Analyzer
[DEBUG] Loaded Analyzer False Positive Analyzer
[DEBUG] Loaded Analyzer Dependency Bundling Analyzer
[DEBUG] Loaded Analyzer Dependency Merging Analyzer
[DEBUG] Loaded Analyzer NVD CVE Analyzer
[DEBUG] Loaded Analyzer Vulnerability Suppression Analyzer
[DEBUG] Loaded Analyzer Central Analyzer
[DEBUG] Loaded Analyzer Nexus Analyzer
[DEBUG] Loaded Analyzer Artifactory Analyzer
[DEBUG] Loaded Analyzer Nuspec Analyzer
[DEBUG] Loaded Analyzer Nugetconf Analyzer
[DEBUG] Loaded Analyzer MSBuild Project Analyzer
[DEBUG] Loaded Analyzer Assembly Analyzer
[DEBUG] Loaded Analyzer OpenSSL Source Analyzer
[DEBUG] Loaded Analyzer Node.js Package Analyzer
[DEBUG] Loaded Analyzer Node Audit Analyzer
[DEBUG] Loaded Analyzer RetireJS Analyzer
[DEBUG] Loaded Analyzer Ruby Bundle Audit Analyzer
[DEBUG] Loaded Analyzer Version Filter Analyzer
[DEBUG] Loaded Analyzer Sonatype OSS Index Analyzer
[DEBUG] Settings.getDataFile() - file: '[JAR]/../../dependency-check-data/5.0'
```
As you can see the assembly analyzer is not loaded. Note - it does print out the settings as loaded from properties file in the core JAR; however, it is later set as seen in the above log.

Now, if you used the above configuration and tried to run `mvn site` the configuration would not be used from the build section. You need to configure and use it as either a site plugin and run it via `mvn site` or as a build plugin and run it via `mvn verify`, `mvn org.owasp:dependency-check-maven:check`, or whatever other goal you attach it to.
