### ISSUE TITLE
Add Linux support for Azure DevOps Dependency Check task

### ISSUE THREAD

**Issue by tylercranston** [dependency-check/DependencyCheck#2939]
**Is your feature request related to a problem? Please describe.**
Yes, when Linux agent is used Dependency Check task does not work - https://marketplace.visualstudio.com/items?itemName=dependency-check.dependencycheck

**Describe the solution you'd like**
Task completes as expected on Linux.

**Describe alternatives you've considered**
Running task on Windows currently, but Windows is much slower to build than Linux.

**Additional context**
N/A

**Comment by mprins** [comment]
I think you'll need to talk to the people maintaining the Azure DevOps extension for your feature request, notably [@emjohn20](https://twitter.com/emjohn20) as listed in the contributors on that page

**Comment by tylercranston** [comment]
@mprins In the Azure DevOps Marketplace for the Dependency Check Extension (https://marketplace.visualstudio.com/items?itemName=dependency-check.dependencycheck) the Support link points to here, I now realize the repository is actually here https://github.com/dependency-check/azuredevops

Thanks!
