### ISSUE TITLE
Cannot be compiled with Java 6

### ISSUE THREAD

**Issue by stevespringett** [dependency-check/DependencyCheck#294]
Although the source and target specify Java 6, Dependency-Check cannot be compiled with Java 6, but can be compiled with Java 7. Java 6 is currently the requirement for Jenkins.

Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project dependency-check-core: Compilation failure
[ERROR] src/main/java/org/owasp/dependencycheck/utils/DCResources.java:[33,8] Failed to locate resource bundle [dependencycheck-resources] for locale [en] for enum type [org.owasp.dependencycheck.utils.DCResources]

**Comment by stevespringett** [comment]
We may want to use animal-sniffer-maven-plugin or simply configure CloudBees to use Java 6 to catch these types of issues earlier.

**Comment by colezlaw** [comment]
I submitted a PR fixing the issue from the logger, but it appears that
maybe the maven-plugin-plugin being used is specific to 1.7 or newer.
Utile, core, and the Jenkins plugin build on 1.6, now. I believe only the
Maven plugin is currently failing on (my) 1.6

**Comment by jeremylong** [comment]
plugin-plugin was reverted to the previous version and the 'quick' fix of disabling a test under JDK 1.6 (and 1.8) resolves the issue on my linux box. However, changing Jenkins to use JDK 1.6 fails with an 'ERROR: Failed to parse POMs': https://dependency-check.ci.cloudbees.com/job/dependency-check/314/console

Steve - can you confirm that it build correctly on your system under 1.6?

**Comment by colezlaw** [comment]
I'm not positive what's different about CloudBees 1.6 than any other 1.6,
so I built a docker box to test it on.

$ docker run -ti colezlaw/dependencycheck-openjdk-6 bash
...

# cd DependencyCheck

# mvn clean package install

**Comment by stevespringett** [comment]
FYI, on my local system, it builds fine on Oracle Java 6.

—Steve

On August 1, 2015 at 3:31:42 PM, colezlaw (notifications@github.com) wrote:

I'm not positive what's different about CloudBees 1.6 than any other 1.6,
so I built a docker box to test it on.

$ docker run -ti colezlaw/dependencycheck-openjdk-6 bash
...

# cd DependencyCheck

# mvn clean package install
