### ISSUE TITLE
How to config CVE_START_YEAR ?

### ISSUE THREAD

**Issue by nzk1912** [dependency-check/DependencyCheck#2941]
Purpose: only synchronize vulnerability information after 2018

I searched in the source code. In the NvdCveUpdater class, I found:

`final int startYear = settings.getInt ( Settings.KEYS.CVE_START_YEAR, 2002);`

～excited ～ 

However, the startup parameter was not found this config item.

What can i do?  or  code?  ~~

**Comment by jeremylong** [comment]
While not exposed as a standard parameter you can specify this via JAVA_OPTS:

```bash
export JAVA_OPTS='-Dcve.startyear=2018'
```

Alternatively, if using the CLI you could create a properties file with the `cve.startyear` and include it via `-P custom.prop`.

**Comment by nzk1912** [comment]
> While not exposed as a standard parameter you can specify this via JAVA_OPTS:
> 
> ```shell
> export JAVA_OPTS='-Dcve.startyear=2018'
> ```
> 
> Alternatively, if using the CLI you could create a properties file with the `cve.startyear` and include it via `-P custom.prop`.

thanks  ~   perfect

**Comment by jeremylong** [comment]
Also, with 6.4.1 the start year is now configurable without having to use the `JAVA_OPTS`.
