### ISSUE TITLE
Error 403 when running the Azure DevOps OWASP Extention 

### ISSUE THREAD

**Issue by divbasson** [dependency-check/DependencyCheck#2945]
**Describe the bug**
Azure DevOps pipeline gives an 403 on the download step using the OWASP extension.

**Version of dependency-check used**
6.0.2

**Log file**
Starting: Run OWASP dependency check
Task         : OWASP Dependency Check
Description  : Checks your dependencies for known vulnerabilities.
Version      : 0.9.0
Author       : Info Support
Help         : Uses the OWASP dependency check cli tool to scan for known vulnerabilities. [View the extension on the marketplace](https://marketplace.visualstudio.com/items?itemName=InfoSupport.infosupport-owasp-dependecy-checker)
Started execution of OWASP Dependency Check task
Installing owasp-dependency-check executable
Downloading: https://github.com/jeremylong/DependencyCheck/releases/download/v6.0.2/dependency-check-6.0.2-release.zip
**##[error]Unexpected HTTP response: 403**
Finishing: Run OWASP dependency check

**To Reproduce**
1. Install Azure DevOps extension 
2. In your yaml pipeline add the extension and configure all required variables.
3. Run pipeline

**Expected behavior**
Pipeline should complete and the OWASP report should be generated.

**Comment by mprins** [comment]
I think you'll need to talk to the people maintaining the Azure DevOps extension for your feature request, notably [@emjohn20](https://twitter.com/emjohn20) and https://github.com/dependency-check/azuredevops as listed in the contributors on that page

BTW that file download without problems for me

**Comment by aikebah** [comment]
@mprins this appears to be a different integration in azure devops, created by the IT company info support (https://www.infosupport.com/).
https://marketplace.visualstudio.com/items?itemName=InfoSupport.infosupport-owasp-dependecy-checker&ssr=false#overview

But I see on the Q&A page of it that @divbasson is already in contact with them on the issue.
