### ISSUE TITLE
6.0.3 not visible in Jenkins

### ISSUE THREAD

**Issue by niajthat** [dependency-check/DependencyCheck#2946]
6.0.3 was released 6 days ago. I am using the latest available OWASP Dependency-Check Plugin (v5.1.1) in Jenkins but I cannot find 6.0.3 in the list of available versions. I can see all versions up to 6.0.2.
What am I missing ?

**Comment by aikebah** [comment]
As per the [release-notes of 6.0.2](https://github.com/jeremylong/DependencyCheck/releases/tag/v6.0.2) the hosting of release-binaries for OWASP dependency-check has been migrated to Github.

I think you're looking for them in bintray?

After checking binTray I see that it's still been published there as well....

From what I see in the Jenkins plugin there doesn't appear to be any 'magic version discovery'. Could it be that your Jenkins admin has not yet configured 6.0.3 as an available tool version?

**Comment by jeremylong** [comment]
Please see https://plugins.jenkins.io/dependency-check-jenkins-plugin/ - specifically https://issues.jenkins.io/browse/JENKINS-63459

The jenkins plugin is currently seeking a new maintainer. As such, the jenkins plugin is likely behind a bit.

**Comment by ankurja** [comment]
> Could it be that your Jenkins admin has not yet configured 6.0.3 as an available tool version?

I am facing the same issue. There is no such configuration option in Jenkins plugin. I believe the Jenkins plugin automatically looks for new versions from bintray, not sure why it is showing every version from 0.3.2.4 up to 6.0.2 but not 6.0.3. The migration of release-binaries to GitHub probably explains this or could be a bug in the plugin which is causing it to skip 6.0.3 even though it is available in bintray.

**Comment by jeremylong** [comment]
The binaries are in both places still and https://jeremylong.github.io/DependencyCheck/current.txt contains 6.0.3. The download paths should still work. But again - the Jenkins plugin is seeking a new maintainer.  This might be a good first issue to help with.

**Comment by niajthat** [comment]
Not sure what changed on bintray/plugin but I am able to see 6.0.3 coming up in Jenkins now.
