### ISSUE TITLE
Maven site plugin fails with com/fasterxml/jackson/core/JsonProcessingException

### ISSUE THREAD

**Issue by osyniakov** [dependency-check/DependencyCheck#2947]
**Maven site plugin fails with com/fasterxml/jackson/core/JsonProcessingException**
Missing "jackson-core" dependency in "dependency-check-utils" module:

```
<dependency>
        <groupId>com.fasterxml.jackson.core</groupId>
        <artifactId>jackson-core</artifactId>
</dependency>

```
**Version of dependency-check used**
The problem occurs using version 6.0.3 of the maven plugin.

**Log file**
[dependency-check-logfile.txt](https://github.com/jeremylong/DependencyCheck/files/5513161/dependency-check-logfile.txt)

**Comment by jeremylong** [comment]
I'm confused about the reported issue as I am able to both run mvn site on the primary dependency-check project and I can run the dependency-check-maven plugin when configured as a site report. Both work without adding jackson as a dependency.

What are you running that produces this error?

**Comment by osyniakov** [comment]
@jeremylong Thanks for checking.  
I created sample project to reproduce the issue: https://github.com/osyniakov/JsonProcessingException
Please check-out project and run the command: `./mvnw clean site:site`
Same build passes if I downgrade dependency-check-maven to 6.0.2.
Sorry for confusion I should have added sample project before.

**Comment by jeremylong** [comment]
I'm not seeing the same behavior.

```bash
$ git clone https://github.com/osyniakov/JsonProcessingException.git
$ cd JsonProcessingException
$ ./mvnw clean site:site

[INFO] Finished Sonatype OSS Index Analyzer (0 seconds)
[INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
[INFO] Finished Dependency Bundling Analyzer (0 seconds)
[INFO] Analysis Complete (2 seconds)
[INFO] Generating "Dependency Information" report --- maven-project-info-reports-plugin:3.0.0:dependency-info
[INFO] Generating "About" report         --- maven-project-info-reports-plugin:3.0.0:index
[INFO] Generating "Plugin Management" report --- maven-project-info-reports-plugin:3.0.0:plugin-management
[INFO] Generating "Plugins" report       --- maven-project-info-reports-plugin:3.0.0:plugins
[INFO] Generating "Summary" report       --- maven-project-info-reports-plugin:3.0.0:summary
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.016 s
[INFO] Finished at: 2020-11-12T06:36:51-05:00
[INFO] ------------------------------------------------------------------------
```

Jackson is used in the core library of dependency-check and jackson-core is included as a transitive dependency.

**Comment by osyniakov** [comment]
@jeremylong thank you for a prompt reply. I tried running my test project on different PC and build passed without issues. 
Looks like there is a problem with my environment.
