### ISSUE TITLE
Which url:s are required to be allowed in the firewall in order for the dependency checker to work?

### ISSUE THREAD

**Issue by rogeroberg** [dependency-check/DependencyCheck#2951]
It would be great if you could add the internet sites required by the dependency checker to work in https://jeremylong.github.io/DependencyCheck/data/index.html 

Today it only mentions that internet is required, but not which sites. Adding the info will make the firewall openings easier to accomplish.

**Comment by jeremylong** [comment]
Look in the properties file for the URLs used; 

https://github.com/jeremylong/DependencyCheck/blob/main/core/src/main/resources/dependencycheck.properties

**Comment by rogeroberg** [comment]
Thx!!!
