### ISSUE TITLE
support VulnDB

### ISSUE THREAD

**Issue by hcjcn** [dependency-check/DependencyCheck#2953]
**Is your feature request related to a problem? Please describe.**
support VulnDB

**Describe the solution you'd like**
support VulnDB

**Describe alternatives you've considered**

**Additional context**

**Comment by mprins** [comment]
Please elaborate your request, what does VulnDB bring that the current providers don't or why is it better?
it seems VulnDB.com / https://vulndb.cyberriskanalytics.com/ is geared towards products/applications and not dependencies - which is the scope of this tool

**Comment by jeremylong** [comment]
@mprins VulnDB is a private, more comprehensive, version of the NVD that also includes libraries. Last stats I heard a few years ago they had 40k+ more vulnerabilities than the NVD - I'm not sure where they stand today.  In general, they also include new vulnerabilities faster than the NVD.

One of the reasons I haven't worked on a VulnDB integration is that 1. VulnDB is a for pay subscription, 2. ODC is currently 100% FOSS and uses no data sources that require a subscription, and 3. all of my time on the ODC is purely volunteer (not even used as part of my day job).  I'm not saying it won't happen - it just isn't on the top of my todo list.
