### ISSUE TITLE
Unable to connect to the dependency-check database  

### ISSUE THREAD

**Issue by 777yL** [dependency-check/DependencyCheck#2954]
An error occurred when running SonarQube analysis on Azure DevOps pipelines, but adding server.servler.context-path=/xxxxx to the application.properties of the project, there would be no problem if the pipelines were re-executed. How to solve the problem that pipelines can run without context-path.

ERROR] Failed to execute goal org.owasp:dependency-check-maven:6.0.1:aggregate (default-cli) on project demo:Fatal exception(s) analyzing demo: One or more exceptions occurred during analysis:
[ERROR] 	Unable to connect to the dependency-check database
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by joseurena3** [comment]
did you delete the old database as documented for the 6.0 upgrade?  

 https://github.com/jeremylong/DependencyCheck#600-upgrade-notice
`maven: mvn org.owasp:dependency-check-maven:6.0.0:purge`
