### ISSUE TITLE
False Positive on [library]

### ISSUE THREAD

**Issue by mangokd** [dependency-check/DependencyCheck#2957]
False positive on library resteasty.jar - reported as resteasy-spring-boot-starter-3.5.0.Final.jar (pkg:maven/org.jboss.resteasy/resteasy-spring-boot-starter@3.5.0.Final, cpe:2.3:a:redhat:resteasy:3.5.0:*:*:*:*:*:*:*) 
```xml
            <dependency>
                <groupId>org.jboss.resteasy</groupId>
                <artifactId>resteasy-spring-boot-starter</artifactId>
                <version>3.5.0.Final</version>
            </dependency>
```

**Comment by twwd** [comment]
It seems that there is a bug for CPE matching for packages with hyphens in the name, see #2972 or #2940.

**Comment by jeremylong** [comment]
It seems people don't read [How dependency-check works](https://jeremylong.github.io/DependencyCheck/general/internals.html).
