### ISSUE TITLE
getInt not implemented for class oracle.jdbc.driver.T4CRowidAccessor 

### ISSUE THREAD

**Issue by kaimago** [dependency-check/DependencyCheck#296]
Running DependencyCheck with an Oracle Database not working.

![getgeneratedkey-dbutils](https://cloud.githubusercontent.com/assets/5519015/9006099/e3c3591c-3783-11e5-82fa-f00f1af9efeb.png)

I hope that there is a way, that DependencyCheck also support an Oracle database.

This should work for the oracle jdbc driver

OracleResultSet keys = (OracleResultSet) ps.getGeneratedKeys();
keys.next();
ROWID rowID = keys.getROWID(1);

**Comment by jeremylong** [comment]
I do not have an Oracle DB to test against. However, per https://docs.oracle.com/cd/B19306_01/java.102/b14355/jdbcvers.htm#CHDDEAED the code needs to explicitly state which columns are auto-generated. The 1.2.11 code base used the `Statement.RETURN_GENERATED_KEYS` when preparing the statements. I just committed a change that will hopefully resolve this.

You can either try the 1.2.12-SNAPSHOT (compile from source) or wait a few days for the 1.3 release to confirm whether or not this issue has been resolved.

--Jeremy

**Comment by kaimago** [comment]
With 1.3.0 it seems to work with oracle DB. Thanks !!!

The first import takes hours, but that's ok.
