### ISSUE TITLE
what the diff that command?

### ISSUE THREAD

**Issue by nzk1912** [dependency-check/DependencyCheck#2961]
mvn dependency-check:aggregate 
mvn org.owasp:dependency-check-maven:aggregate 

maven multi module ,run first command return error,run second command is ok.

what the diff two command?

**Comment by mprins** [comment]
show us the config of the plugin in your pom en we may be able to tell you why it errors, as for the diff, is in the maven book, one calls a configured plugin phase, the other calls an unknown and probably unconfigured plugin

**Comment by jeremylong** [comment]
Information on the goal prefix can be found https://maven.apache.org/guides/introduction/introduction-to-plugin-prefix-mapping.html

I know `mvn dependenc-check:aggregate` works on some systems. In you settings.xml you should be able to add:
```xml
<pluginGroups>
  <pluginGroup>org.owasp</pluginGroup>
</pluginGroups>
```
To get `mvn dependency-check:aggregate` to work.
