### ISSUE TITLE
Retire JS repository update fails in Docker

### ISSUE THREAD

**Issue by kazigk** [dependency-check/DependencyCheck#2963]
**Describe the bug**
Retire JS repository update fails in Docker if you use script provided in README.md.
It's stuck on `[WARN] Retire JS repository is empty or missing - attempting to force the update`

**Version of dependency-check used**
Latest official Docker image, digest hash:
`sha256:2bab30d8c5670c972f4c18d497fbded29992ac5b8efbe85a9d77caa97ba9a041`

**To Reproduce**
1. Follow the readme (use Docker)
2. Run scan on Node.js code

**Expected behavior**
It just works.

**Additional context**
I'm running Docker 19.03.13 on Ubuntu 20.04, but it shouldn't make any difference.

For now as a workaround I did the following:
```
FROM owasp/dependency-check:latest
USER root
RUN chmod 777 /usr/share/dependency-check/data
USER dependencycheck
```

**Comment by jeremylong** [comment]
Did you use the latest suggested script to run the container?

https://github.com/jeremylong/DependencyCheck#docker

**Comment by kazigk** [comment]
Thank you for your response. The script is all ok. I customized it a bit to fit my environment and I missed one thing.

I'm really sorry for filing an issue, closing now.
