### ISSUE TITLE
gradle-plugin 6.0.3 fails to create report with openjdk 11.0.1

### ISSUE THREAD

**Issue by dkrowl** [dependency-check/DependencyCheck#2967]
**Describe the bug**
gradle-plugin 6.0.3 fails to create report with openjdk 11.0.1 2018-10-16 (build 11.0.1+13)

**Version of dependency-check used**
The problem occurs using version 6.0.3 of the gradle plugin.
Tested with Gradle versions 5.7 -> 6.7

**To Reproduce**

1. configurate Gradle task:

```groovy
dependencyCheck {
    outputDirectory = "build/reports/dependency-check"
    failOnError = false
    format = 'ALL'
}
```

2. run gradle task `dependencyCheckAnalyze` with openjdk11.
3. Nothing is generated in the outputDirectory.

**Expected behavior**
Same steps with openjdk8 generates the files on outputDirectory:
dependency-check-junit.xml
dependency-check-report.csv
dependency-check-report.html
dependency-check-report.json
dependency-check-report.xml

**Comment by aschwarte10** [comment]
We are observing the same behavior in our CI environment (also with 6.0.2 of the plugin). Any chance this can be fixed? Are there any workarounds?

**Comment by aschwarte10** [comment]
For future reference and others who might be running into this: we found the following workaround 

Using an absolute path for the report output, seems to work

```
dependencyCheck {
  outputDirectory rootProject.file('target/reports/dependencies').absolutePath
  ...
}
```

Note: it turns out that when using a relative path, the report is written to the gradle daemon directory, e.g. in my case to

```
~/.gradle/daemon/6.7/target/reports/dependencies/dependency-check-report.html
```

**Comment by jeremylong** [comment]
Added info level logging to assist with identifying where the files are written. However, a different and more standard solution would be to use `${buildDir}`:
```gradle
dependencyCheck {
    outputDirectory = "${buildDir}/reports/dependency-check"
    failOnError = false
    format = 'ALL'
}
```
