### ISSUE TITLE
False Positive on xercsImpl-2.12.0

### ISSUE THREAD

**Issue by eramirez-cs** [dependency-check/DependencyCheck#2969]
With 6.0.3 seeing issue around xercsImpl/2.12.0 and looks to be false positive
This issue was reported previously 
https://github.com/jeremylong/DependencyCheck/issues/2570
but it still happens.

###Example
False positive on https://mvnrepository.com/artifact/xerces/xercesImpl/2.12.0 - reported as
cpe:2.3:a:exist-db:exist:2.12.0
```<!-- https://mvnrepository.com/artifact/xerces/xercesImpl -->
<dependency>
    <groupId>xerces</groupId>
    <artifactId>xercesImpl</artifactId>
    <version>2.12.0</version>
</dependency>
```
exist-db:exist:2.12.0 seems unrelated above xercsImpl-2.12.0 which is used and appears to be false positive

**Comment by jeremylong** [comment]
Just tested with 6.0.4-SNAPSHOT and this is no longer being reported.
