### ISSUE TITLE
 caused by DownloadFailedException: Error downloading file https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta; unable to connect.

### ISSUE THREAD

**Issue by chenxiulin90** [dependency-check/DependencyCheck#2983]
my pom
              <dependency>
			<groupId>org.owasp</groupId>
			<artifactId>dependency-check-maven</artifactId>
			<version>6.0.3</version>
		</dependency>

                           <plugin>
				<groupId>org.owasp</groupId>
				<artifactId>dependency-check-maven</artifactId>
				<version>6.0.3</version>
				<executions>
					<execution>
						<goals>
							<goal>check</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
but 
Failed to execute goal org.owasp:dependency-check-maven:6.0.3:check (default-cli) on project campus: Fatal exception(s) analyzing campus: One or more exceptions occurred during analysis:
[ERROR]         UpdateException: Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta
[ERROR]                 caused by DownloadFailedException: Download failed, unable to retrieve 'https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta'; Error downloading file https://nvd.nis
t.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta; unable to connect.
[ERROR]                 caused by DownloadFailedException: Error downloading file https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta; unable to connect.
[ERROR]                 caused by SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find
 valid certification path to requested target
[ERROR]                 caused by ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[ERROR]                 caused by SunCertPathBuilderException: unable to find valid certification path to requested target
[ERROR]         NoDataException: No documents exist
[ERROR] -> [Help 1]

**Comment by mprins** [comment]
Seems your java runtime fails to recognise the TLS certificate or signing chain that nvd.nist.org uses. Check you certificate store

**Comment by jeremylong** [comment]
See #728

**Comment by chenxiulin90** [comment]
thanks,I solved the problem through your reply

**Comment by mkienenb** [comment]
Note that this problem is likely caused by using an older JRE.   A newer JRE will provide the missing certificate.
