### ISSUE TITLE
Dependency check fail at end

### ISSUE THREAD

**Issue by hadescastillo** [dependency-check/DependencyCheck#2985]
Hello, I would like to know if it is possible to configure the plugin in a way that the build fails if we find any vulnerability but only at the end of the process, meaning that the report will complete and all the dependencies are scanned before the fail.

What we want to accomplish is have a step in our CI/CD that fails on vulnerabilities but we want to have a full report of all the dependencies. At the moment the build fails if we find a vulnerability (as expected) but this means that the build stop at this point. Is there a way to allow the scan to finish and only fail at the end?

**Comment by jeremylong** [comment]
Yes - that is how ODC works. Just set failBuildOnCVSS=0. See the [documentation](https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html).

**Comment by hadescastillo** [comment]
Hi @jeremylong thanks for your reply. And if we were to have multiple java modules (one module failing will cause the other modules to skip the execution), how could we accomplish what I mentioned above and run the full scan of multiple modules and fail at the end?

**Comment by jeremylong** [comment]
In the parent pom (assuming maven) use the aggregate goal with `<inherited>false</inherited>` per https://maven.apache.org/guides/mini/guide-configuring-plugins.html#Using_the_inherited_Tag_In_Build_Plugins

**Comment by hadescastillo** [comment]
Ok thank you very much, closing!
