### ISSUE TITLE
How not to show the zero values ​​after scanning?

### ISSUE THREAD

**Issue by Sysobas** [dependency-check/DependencyCheck#2986]
Hi Jeremy.

First of all I would like to know if there is a post scan call that when showing the data in the report, the records that are zeroed, do not appear, as the file is too big for viewing.

This call can be during execution or after execution?

Second, is it possible to sort these records by severity?

Att,
Bertino

**Comment by jeremylong** [comment]
By zeroed - you mean have no identified vulnerabilities?

**Comment by Sysobas** [comment]
No, on the contrary, many files are registered that have the counter reset, and the file html are large with more than 50mb.

**Comment by jeremylong** [comment]
What counter are we talking about?

Dealing with large scans - we do have a planned feature to only report vulnerable dependencies which will reduce the size some. You can also use one of the other report formats instead of HTML.  Alternatively, is there a way to break the scan up into small pieces?

**Comment by Sysobas** [comment]
Jeremy

I tried to send an attachment as a sample but unfortunately it exceeds the
capacity

Att,
Bertino



Em qua., 2 de dez. de 2020 às 10:12, Jeremy Long <notifications@github.com>
escreveu:

**Comment by jeremylong** [comment]
circling back to this issue....  What type of project is this? I'm betting it is node.js and you have the RetireJS analyzer enabled. For node.js projects I would highly recommend disabling the RetireJS analyzer and the nodeJS Analyzer (at least in ODC 6.0.x and earlier). The RetireJS Analyzer is looking for client side JS and scans every JS file and creates an entry in the report for every single one...  The node JS analyzer is currently just producing tons of false positives.
