### ISSUE TITLE
configure local NVD data cache

### ISSUE THREAD

**Issue by delanym** [dependency-check/DependencyCheck#2989]
In the Maven plugin I want to configure the location of the local cache of NVD data.
I'd like to set it to ${user.home}/.m2/nvd-cve

How can I do this?

**Comment by jeremylong** [comment]
Sorry for the unbelievably delayed response. The cache is contained within the data directory. You can change the data directory location: https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html
