### ISSUE TITLE
Track backport patch version numbers

### ISSUE THREAD

**Issue by dwvisser** [dependency-check/DependencyCheck#299]
As has been [mentioned](https://github.com/jeremylong/DependencyCheck/issues/212#issuecomment-92097142) in the thread for #212, Linux distributions like Fedora and Ubuntu use backport patches. E.g., version 1.2 is vulnerable, version 1.3 is not, but Fedora's "1.2-patch7" is NOT vulnerable.  The NVD _should_ track this, but it doesn't always do so.  One solution is that dependency-check could support the use of "supplemental" database(s) that adds missing information, e.g., that "Fedora 1.2-patch7 is not vulnerable".

**Comment by jeremylong** [comment]
Is there any place backport information like this can be obtained and is (easily) programmatically consumable? Or are you seeing this as a feature that organizations could maintain their own list?

ATM - I have no plans to create a database that must be hand curated.
