### ISSUE TITLE
Which analyzer must i use on angular and NodeJs Projects

### ISSUE THREAD

**Issue by sebastienroux** [dependency-check/DependencyCheck#2993]
Hello,

I tried a lot of parameters for my analisys on angular projects and nodejs projects.

I'm using : 
 - disableNodeAudit on angular projects
 - disableNodeJs on nodejs projects

Are these settings good ? 

Which settings do you recommand for theses projects ?

**Comment by jeremylong** [comment]
I would likely disable NodeJS and the RetireJS.  Which makes the current implementation almost equivalent to just calling `npm audit`.

**Comment by sebastienroux** [comment]
> I would likely disable NodeJS and the RetireJS. Which makes the current implementation almost equivalent to just calling `npm audit`.

@jeremylong On both angular and node projects? 
disableNodeJs and disableRetireJS ?

**Comment by evanjmg** [comment]
@jeremylong  would you just recommend npm audit then? Seems unnecessary if it's doing the same thing?
