### ISSUE TITLE
Dependency Check on Python Project

### ISSUE THREAD

**Issue by shiv-acharii** [dependency-check/DependencyCheck#3003]
I am reviewing this tool for local setup and next, I will be doing on the Azure Devops pipeline

**I have a Python project in my Local PC with the below folder structure and Path:**

![image](https://user-images.githubusercontent.com/13836633/101448328-d7750400-394c-11eb-82a3-783e2724288e.png)

Now I have run the below command to check
```
dependency-check.bat --project "12_Keyword Spotting" --scan "C:\2_My_Project"
```
**But I am getting below errors**
![image](https://user-images.githubusercontent.com/13836633/101448461-1440fb00-394d-11eb-8760-2b9a7ecc1059.png)

My  **dependency-check-report.html**  is not been generated in the python project. Could you please help me with the setup.

**Comment by shiv-acharii** [comment]
Now I have changed my path to the project directory:

![image](https://user-images.githubusercontent.com/13836633/101449692-43f10280-394f-11eb-9bb6-c83a31537c70.png)

**No errors or warnings: but still no report file is generated in the folder with dependency-check-report.html**

**Comment by jeremylong** [comment]
Please see #548. We accept PRs - but currently there is only limited support for Python. See the Python reference here: https://jeremylong.github.io/DependencyCheck/analyzers/index.html

Python is an experimental analyzer that likely needs a complete overhaul and add support for requirements.txt per #548.

**Comment by jeremylong** [comment]
Also - in terms of the report you likely need to add `-o .`
