### ISSUE TITLE
False Positive on jdbc-socket-factory-core

### ISSUE THREAD

**Issue by breucode** [dependency-check/DependencyCheck#3005]
`jdbc-socket-factory-core` seems to be mistaken for `mysql:mysql`

https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory
https://mvnrepository.com/artifact/com.google.cloud.sql/jdbc-socket-factory-core

Dependency: `jdbc-socket-factory-core-1.2.0.jar`
Vulnerability ID: `cpe:2.3:a:mysql:mysql:1.2.0:*:*:*:*:*:*:*`

**Comment by jeremylong** [comment]
Using 6.0.4 - I'm not seeing this FP.  I did find a few related FP when testing and I have added suppression rules for them.
