### ISSUE TITLE
Unable to suppress CVE_2020_17527

### ISSUE THREAD

**Issue by Mvbraathen** [dependency-check/DependencyCheck#3008]
Hi! 
I am looking for tips to suppress CVE_2020_17527. I have tried the following: 

```
`   <suppress until="2021-01-04Z">
      <notes>
         <![CDATA[
         file name: hardware-server.jar: tomcat-embed-core-9.0.39.jar
         ]]>
      </notes>
      <packageUrl regex="true">^pkg:maven/org\.apache\.tomcat\.embed/tomcat\-embed\-core@.*$</packageUrl>
      <cpe>cpe:/a:apache:tomcat</cpe>
   </suppress>
   <suppress until="2021-01-04Z">
      <notes>
         <![CDATA[
         file name: hardware-server.jar: tomcat-embed-core-9.0.39.jar
         ]]>
      </notes>
      <packageUrl regex="true">^pkg:maven/org\.apache\.tomcat\.embed/tomcat\-embed\-core@.*$</packageUrl>
      <cpe>cpe:/a:apache_software_foundation:tomcat</cpe>
   </suppress>
   <suppress until="2021-01-04Z">
      <notes>
         <![CDATA[
         file name: hardware-server.jar: tomcat-embed-core-9.0.39.jar
         ]]>
      </notes>
      <packageUrl regex="true">^pkg:maven/org\.apache\.tomcat\.embed/tomcat\-embed\-core@.*$</packageUrl>
      <cpe>cpe:/a:apache_tomcat:apache_tomcat</cpe>
   </suppress>`
```

This is the report: 
![image](https://user-images.githubusercontent.com/16756739/101629792-2a6cbb00-3a22-11eb-8190-3104297083dd.png)

**Comment by jeremylong** [comment]
How are you calling dependency check? Can you provide the log file (command line add `-l odc.log`).

**Comment by Mvbraathen** [comment]
Hi again, 
i found the reason for the malfunctioning suppress. Needed to add -websocket in the mix aswell. This was reported differently in the different depcheck reports, so was a coincidence that a colleague realized that my suppress aimed at something else than what was reported for him. Seems a bit weird, but at least it's okay now. Thanks for the swift response. 
![image](https://user-images.githubusercontent.com/16756739/101673484-8271e480-3a57-11eb-8fac-45b6f35809d6.png)
