### ISSUE TITLE
Remove/suppress engine disclaimer

### ISSUE THREAD

**Issue by mattnelson** [dependency-check/DependencyCheck#3011]
**Is your feature request related to a problem? Please describe.**
Reduce logging output created by the disclaimer.
https://github.com/jeremylong/DependencyCheck/commit/6f0481f7505eeae3053aa7d2b56a31f9b56eaf87

```
[INFO] --- dependency-check-maven:5.3.2:check (default) @ my-module ---
[INFO]

Dependency-Check is an open source tool performing a best effort analysis of 3rd party dependencies; false positives and false negatives may exist in the analysis performed by the tool. Use of the tool and the reporting provided constitutes acceptance for use in an AS IS condition, and there are NO warranties, implied or otherwise, with regard to the analysis or its use. Any use of the tool and the reporting provided is at the user’s risk. In no event shall the copyright holder or OWASP be held liable for any damages whatsoever arising out of or in connection with the use of this tool, the analysis performed, or the resulting report.


[INFO] Analysis Started
```

**Describe the solution you'd like**
Remove the disclaimer. The project license should already cover what is mentioned in the disclaimer.
https://github.com/jeremylong/DependencyCheck/blob/main/LICENSE.txt

**Describe alternatives you've considered**
Add a property to accept/suppress the disclaimer.

**Additional context**
n/a

**Comment by mprins** [comment]
I think this message is an important one and should be kept, perhaps even at a higher logging level such as "warning". Removing the message does nothing to reduce the number of questions from people with absolute trust in this tool about false positives/negatives that we see.

Note that Maven already provides options to configure logging output using properties and command-line options

**Comment by jeremylong** [comment]
I 100% agree with @mprins on this.
