### ISSUE TITLE
False Positive on failureaccess.jar

### ISSUE THREAD

**Issue by stefanscheidt** [dependency-check/DependencyCheck#3019]
False positive on library failureaccess.jar - reported as `cpe:2.3:a:google:guava:1.0.1:*:*:*:*:*:*:*`
```xml
<dependency>
  <groupId>com.google.guava</groupId>
  <artifactId>failureaccess</artifactId>
  <version>1.0.1</version>
</dependency>
```

**Comment by jeremylong** [comment]
Not sure what version of ODC you are using - a suppression was added for this 8 months ago:

https://github.com/jeremylong/DependencyCheck/blob/f44ce343aee0480b048cfd67b681dd8addeefb3c/core/src/main/resources/dependencycheck-base-suppression.xml#L1370-L1376

**Comment by stefanscheidt** [comment]
Sorry for causing you unnecessary work. I will check this in future!
