### ISSUE TITLE
"at least one 'exe' or 'dll' was scanned" but there are none in the project

### ISSUE THREAD

**Issue by jakub-bochenski** [dependency-check/DependencyCheck#3020]
**Describe the bug**
I get the warning about
```
.NET Assembly Analyzer could not be initialized and at least one 'exe' or 'dll' was scanned. The 'dotnet' executable could not be found on the path; either disable the Assembly Analyzer or add the path to dotnet core in the configuration.
```
but theere are no such files in the project

**Version of dependency-check used**
The problem occurs using version 6.0.3 of the gradle plugin

**Log file**
```
$ find . -iname '*.dll'
$ find . -iname '*.exe'
$
```

**Expected behavior**
The warning doesn't appear. It would be nice if the warning printed the path to the file it found

**Comment by infa-spritman** [comment]
I am having the same issue on both Linux machine and Mac Machine. Any remedy?

**Comment by jeremylong** [comment]
The DLL or EXE may be embedded in a JAR, ZIP, or other archive.

--Jeremy

**Comment by jakub-bochenski** [comment]
That's correct, there were a bunch of DLLs e.g.
```
net.java.dev.jna/jna/5.5.0/e0845217c4907822403912ad6828d8e0b256208/jna-5.5.0.jar
   207872  2019-06-22 17:22   com/sun/jna/win32-x86/jnidispatch.dll
   246784  2019-06-22 17:01   com/sun/jna/win32-x86-64/jnidispatch.dll
```

Still printing the location of the found files might be helpful

**Comment by mprins** [comment]
> Still printing the location of the found files might be helpful

did you run with debug logging?

**Comment by jakub-bochenski** [comment]
No
I guess this means debug logging prints it?

**Comment by mprins** [comment]
noit sure, but it might

**Comment by jakub-bochenski** [comment]
actually how do you enable debug in gradle plugin?

tried running `./gradlew dependencyCheckAggregate -i` - it outputs some extra info (e.g. database updates) but not said file paths

**Comment by mprins** [comment]
> actually how do you enable debug in gradle plugin?

sorry; I only use Maven

**Comment by jakub-bochenski** [comment]
yep, well what I get with `-i` is what Maven prints by default

**Comment by jakub-bochenski** [comment]
it's kind of there if you enable `-d`, but the output is so verbose it's really hard to find (if you think Maven debug output is verbose you haven't seen the Gradle one)

```
2020-12-17T11:36:54.186+0100 [DEBUG] [org.owasp.dependencycheck.analyzer.DependencyBundlingAnalyzer] IdentifiersMatch=false (logback-classic-1.2.3.jar, webp-imageio-0.1.6.jar: webp-imageio.dll)
```

**Comment by jeremylong** [comment]
Another way to identify these would be to look at the HTML, XML, or JSON reports. In the HTML you may need to click the `Display: Showing Vulnerable Dependencies (click to show all)` button to see all the dependencies - but you should be able to search for `.dll` and see which archive includes the DLL.

**Comment by jakub-bochenski** [comment]
This might be a bit inconvenient:
 - you have to install mono first
 - there might not be any vulnerabilities found actually

**Comment by jeremylong** [comment]
Mono is no longer needed. ODC moved to dotnet core - so you would need to install dotnet core.

**Comment by jakub-bochenski** [comment]
Right,  still installing additional packages (at ~ 150MB) might be problematic in some situations
