### ISSUE TITLE
NPE org.owasp.dependencycheck.Engine.throwFatalExceptionCollection (Engine.java:1084)

### ISSUE THREAD

**Issue by AxelNennker** [dependency-check/DependencyCheck#3022]
**Describe the bug**
A Null Pointer Exception occurs during `mvn org.owasp:dependency-check-maven:6.0.3:aggregate`

**Version of dependency-check used**
The problem occurs using version 6.0.3 of the maven plugin

**Log file**
 [command output with stacktrace](https://gist.github.com/AxelNennker/d07d0f16c7a2560a0e092406eb4ea02b) and provide a link in the new issue.

**To Reproduce**
1. git clone https://github.com/hzi-braunschweig/SORMAS-Project.git
2. cd SORMAS-Project/sormas-base
3. add dependency-check-maven plugin version 6.0.3 to pom.xml
4. mvn org.owasp:dependency-check-maven:6.0.3:aggregate

You need a recent version of maven and at least Java11

**Expected behavior**
no npe

**Additional context**

**Comment by agostoni** [comment]
In my case the problem was that the pom file in one of my modules was named as 'pom2.xml', instead of the conventional pom.xml. 

The dependency check failed with the mentioned NPE on every module that had a dependency on the module with the 'pom2.xml'. For me the workaround was to rename all poms to pom.xml. Maybe this info helps in debugging too.

**Comment by nhumblot** [comment]
Hello,

```
	<modules>
		<module>../sormas-widgetset</module>
		<module>../sormas-api</module>
		<module>../sormas-backend</module>
		<module>../sormas-ear</module>
		<module>../sormas-rest</module>
		<module>../sormas-ui</module>
		<module>./dependencies/serverlibs.pom</module>
		<module>../sormas-cargoserver</module>
	</modules>
```
`<module>./dependencies/serverlibs.pom</module>` is causing the issue.

I've submitted a first batch of commits. If you checkout this branch https://github.com/nhumblot/DependencyCheck/tree/3022-fix-npe, `mvn org.owasp:dependency-check-maven:6.1.6-SNAPSHOT:aggregate` ends up without error and generate a report for the project you shared.

Still, at this point, the dependency causing the issue: `de.symeda.sormas:sormas-serverlibs:1.60.0-SNAPSHOT` is not really picked up and analyzed. Maintainers of the project will probably want some of these changes not merged upstream to keep a fail fast approach. I can still open a PR as is if requested by the maintainers.

I'm going to continue to work on it before submitting a pull request. At this point, `sormas-serverlibs` is not analyzed. Given the [Maven documentation](https://maven.apache.org/pom.html#aggregation-or-multi-module), such declaration of module is allowed and looks to not be supported right now. I'll continue the investigation to fix the issue.
