### ISSUE TITLE
cveUser and cvePass for dependency-check.sh CLI

### ISSUE THREAD

**Issue by rjpearce** [dependency-check/DependencyCheck#3028]
Hello,

I'm working on a mirror of NVD database in a JFrog/Artifactory artifactory repo which requires authorisation.

I have set the --cveUrlBase and --cveUrlModified correctly but there seems to be no way to set the username and password when using the CLI client.

In the Maven dependency check there is <cveUser> and <cvePassword> setting.
Is there any way of setting these for the CLI client?

Thank you and Merry Christmas.

**Comment by jeremylong** [comment]
Sorry about the missing arguments. You can create a properties file with:

```properties
cve.user=user
cve.password=pass
```

Then include the properties using the `--propertyfile custom.properties` in the CLI.

**Comment by jeremylong** [comment]
While the CLI argument is being added in the next release - I would recommend continuing to use the properties file to avoid storing credentials in the history...

**Comment by rjpearce** [comment]
Awesome thank you @jeremylong do you have a link I can use to buy you a coffee/beer?

**Comment by jeremylong** [comment]
@rjpearce only thing I have setup is GH sponsors: https://github.com/sponsors/jeremylong

**Comment by rjpearce** [comment]
Thanks. @jeremylong I haven't been able to get it working using the properties file.
When I run the dependency check it gets a 401 response (un-authorised). 

I can see from the log output that cve.username and cve.password is being correctly picked up:

cve.password='********'
cve.user='foo'

However it looks like when the request is made to the server no basic auth is added to request.
I setup a simple Python http server and I get the following output when running dependency-check.sh

User-Agent: Java/14.0.1
Host: 192.168.1.38:8000
Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
Connection: keep-alive

if I use curl the basic auth is present:
curl -u user:pw http://192.168.1.38:8000/artifactory/third-party/nist-nvd-mirror/nvdcve-1.1-modified.meta

Authorization: Basic dXNlcjpwdw==
User-Agent: curl/7.64.1
Accept: */*

I have tried to follow the NvdCve updates through the code by I'm getting rather lost and confused.
Do you know where the logic exists to check for the cve.username and cve.password and call addBasicAuthentication in the UrlConnectionFactory before making the request?

Let me know if there is more debugging I can do additional things to try.

**Comment by jeremylong** [comment]
The CVE creds are used in two places:
https://github.com/jeremylong/DependencyCheck/blob/41ae5d5fcf9ff7c97f852e5069302813b4ce996e/core/src/main/java/org/owasp/dependencycheck/data/update/nvd/DownloadTask.java#L128
https://github.com/jeremylong/DependencyCheck/blob/52c689c635ca301145796c4f3abdbf385e1f3027/core/src/main/java/org/owasp/dependencycheck/data/update/NvdCveUpdater.java#L340

From there you can trace into the Downloader and eventually end up at:

https://github.com/jeremylong/DependencyCheck/blob/52c689c635ca301145796c4f3abdbf385e1f3027/utils/src/main/java/org/owasp/dependencycheck/utils/HttpResourceConnection.java#L202-L204

Which then calls:
https://github.com/jeremylong/DependencyCheck/blob/52c689c635ca301145796c4f3abdbf385e1f3027/utils/src/main/java/org/owasp/dependencycheck/utils/URLConnectionFactory.java#L161-L173

**Comment by jeremylong** [comment]
@rjpearce with the recent release - are you still having issues with the basic auth?

**Comment by rjpearce** [comment]
Hi Jeremy,

Thank you, Sorry for the slow response.
I have run a quick re-test with 6.0.5 using the new command line args for cveUser/cvePass and everything is working as expected. 

We ended up not using Artifactory for our solution. We switched to a very simple solution by building a Docker container based on owasp/dependency-check that has runs dependency-check with --updateonly.

This leverages depedency-checks existing ability to cache NVD data to build a daily docker image. We then tag the docker image and consume it in other CI/CD jobs.
 
Below is the code I used to ascertain auth sanity:

#### Source info: https://hub.docker.com/r/owasp/dependency-check
```bash
docker pull owasp/dependency-check:$DC_VERSION
docker run --rm \
    -e user=$USER \
    -u $(id -u ${USER}):$(id -g ${USER}) \
    --volume $(pwd):/src:z \
    --volume "$DATA_DIRECTORY":/usr/share/dependency-check/data:z \
    --volume $(pwd)/odc-reports:/report:z \
    owasp/dependency-check:$DC_VERSION \
    --scan /src \
    --format "ALL" \
    --project "$DC_PROJECT" \
    --cveUser 'foo' \
    --cvePassword 'secret' \
    --cveUrlBase http://host.docker.internal:8000/nvdcve-1.1-%d.json.gz \
    --cveUrlModified http://host.docker.internal:8000/nvdcve-1.1-modified.json.gz \
    --out /report
```
#### A simple web server
```python
import http.server
import socketserver
import base64

class GetHandler(http.server.SimpleHTTPRequestHandler):
    def do_GET(self):
        expected_auth = b'Basic ' + base64.b64encode('{}:{}'.format('foo', 'secret').encode('ascii'))
        actual_auth = self.headers.get('Authorization', '').encode('ascii')
        if expected_auth == actual_auth:
          print('Credentials valid')
        else:
          print('Credentials invalid')
        print('Headers -------')
        print(self.headers)
        print('--------')
        http.server.SimpleHTTPRequestHandler.do_GET(self)

PORT = 8000
Handler = GetHandler

with socketserver.TCPServer(("", PORT), Handler) as httpd:
    print("Listening on port", PORT)
    httpd.serve_forever()
```
#### Output
```bash
Listening on port 8000
**Credentials valid**
Headers -------
Authorization: Basic Zm9vOnNlY3JldA==
Accept-Encoding: gzip, deflate
User-Agent: Java/14.0.2
Host: host.docker.internal:8000
Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
Connection: keep-alive
```
