### ISSUE TITLE
Downloading the CLI with gradle

### ISSUE THREAD

**Issue by thomasleplus** [dependency-check/DependencyCheck#3029]
Hello,

I would like to use Dependency Check in a CI/CD pipeline but I have the following constraint: each step in my pipeline is running in a locked down docker image (meaning I can't download or install any binary). The only thing that I am allowed to do is run gradle tasks that can download dependencies from my company's Nexus artifact server. The server proxies approved dependency from the usual repos (Maven Central etc.).

Unless I am mistaken, I don't think that the Dependency Check gradle plugin is applicable here because my step received the build folder of the application created by a previous step. At this point my build.gradle is pretty much empty, I don't have the application's dependencies in gradle nor can I easily replicate them. And I haven't seen a way to point the gradle plugin to an existing build folder.

So I was thinking that I could use the Dependency Check CLI. I wanted to use gradle to download the dependency-check-cli jar and it's dependencies, and then run it as a simple Java task. But I can't find the dependency-check-cli jar in the Maven Central repo. Am I missing something? Is there a way to download the CLI from a maven repo?

Cheers,

Tom

**Comment by jeremylong** [comment]
The CLI is not included in Maven central.  It can be downloaded via the github releases.  You can get the current published version of ODC using:

https://jeremylong.github.io/DependencyCheck/current.txt

You can then download the CLI using: 

https://github.com/jeremylong/DependencyCheck/releases/download/v6.0.3/dependency-check-6.0.3-release.zip

Of course I would suggest replacing `6.0.3` with the contents of the above current.txt to keep up to date.

**Comment by thomasleplus** [comment]
Hi Jeremy,

Thanks for the quick reply. I'll do it the way you suggest. But unless you have a specific reason not to publish the CLI jar to Maven Central, I would like to suggest that you consider it. I have other tools that I run using gradle and what I find particularly convenient is that I can make them automatically use the latest version major, minor or patch version leveraging gradle's dependency management system and our local Nexus repo for caching. My `build.gradle` file would look something like this:

```
plugins {
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {
    runtimeOnly 'org.owasp:dependency-check-cli:6.0.+'
}

application {
    mainClassName = 'org.owasp.dependencycheck.App'
}
```

It's pretty simple and then I'd just Dependency Check like this:

`gradle run --args="--project=..."`

Just my two cents.

Cheers,

Tom
