### ISSUE TITLE
Suppress by fileName

### ISSUE THREAD

**Issue by elzibubble** [dependency-check/DependencyCheck#3032]
**Is your feature request related to a problem? Please describe.**
It's mildly annoying to have to escape magic characters in filePath regexen.

**Describe the solution you'd like**
There's a fileName value in the JSON report, allowing us to apply suppressions based on this would usually not require a regex and hence avoid the need for escaping.

**Describe alternatives you've considered**
I understand there's a magic button in the HTML report / SonarQube. Apparently I'm some kind of relic and prefer writing them by hand. I feel like relying on a tool to overcome XSD shortcomings is pragmatic but suboptimal?

**Additional context**
None

**Comment by jeremylong** [comment]
Apparently there is also documentation on the suppression file: https://jeremylong.github.io/DependencyCheck/general/suppression.html

In the example see line 14 and line 21.

**Comment by elzibubble** [comment]
That refers to filePath, not fileName.
