### ISSUE TITLE
Can't disable MSBuild Analyzer from CLI

### ISSUE THREAD

**Issue by RyanMcC** [dependency-check/DependencyCheck#3035]
**Describe the bug**
There's no CLI option that disables the MSBuild Analyzer, the only way to do so is with a `.properties` file.

If I understand it correctly, there should be a `disableMsBuild` option in https://github.com/jeremylong/DependencyCheck/blob/main/cli/src/main/java/org/owasp/dependencycheck/CliParser.java and then it needs to be used in https://github.com/jeremylong/DependencyCheck/blob/main/cli/src/main/java/org/owasp/dependencycheck/App.java `populateSettings` to overwrite `ANALYZER_MSBUILD_PROJECT_ENABLED`.

**Version of dependency-check used**
The problem occurs using version 6.0.3 of the cli

**Comment by jeremylong** [comment]
Thanks for pointing out the miss when the MSBuild Analyzer was added.  You can disable via JAVA_OPTS:
```bash
export JAVA_OPTS='-Danalyzer.msbuildproject.enabled=false'
```

**Comment by RyanMcC** [comment]
That works great for now, thanks!

**Comment by jeremylong** [comment]
This will be included in the next release.

**Comment by daxin09pp** [comment]
hi @jeremylong,
I use the Windows Bat version of Dependent-Check. How can I desable MSBuild Analyzer?

**Comment by daxin09pp** [comment]
I use the new version dependency-check(6.0.5), but there is other issue. Could you help me to see how to solve it? #3090
