### ISSUE TITLE
All vulnerabilities are not reported in one run

### ISSUE THREAD

**Issue by niajthat** [dependency-check/DependencyCheck#3036]
Using dependency-check 6.0.3 with Jenkins OWASP Dependency-Check Plugin v5.1.1.

Not sure whether the problem is with dependency-check or with Jenkins plugin, but when I run a scan I do not get to see ALL vulnerabilities in one run. In the initial run, scan reported around 10 vulns and when I added a suppression to them, it started showing more. And this continues..

![image](https://user-images.githubusercontent.com/73612953/102921339-13c25d00-4441-11eb-8149-b54bae3860e6.png)

![image](https://user-images.githubusercontent.com/73612953/102921382-276dc380-4441-11eb-809d-b09551b2c8ef.png)

![image](https://user-images.githubusercontent.com/73612953/102921431-36547600-4441-11eb-8f59-bb5aa90ce04b.png)

**Comment by jeremylong** [comment]
If you look at the HTML report before adding the suppression file you would see a "related dependencies" section that is minimized. ODC attempts to bundle related JARs into a single entry to avoid duplication. For instance you might have several "spring" related jars that are all at version 3.5.1 - in general the fix would be to upgrade them all at the same time. As such, ODC bundles these together.

In most cases, the suppression rules can be modified to include all of the related JARs by modifying the regex to be a bit broader.

**Comment by niajthat** [comment]
Thanks for that. I can see them under the section you mentioned. The important thing then is to always look at HTML report, not just what gets displayed under dependency check results in Jenkins build, that makes one believe these are the only vulns, which is not correct. 
I think have a warning or information message on Jenkins report would help. Something like - _There could be more vulnerabilities detected in related files, which are not displayed here. Check HTML report for complete list of vulnerabilities_.
