### ISSUE TITLE
relatedDependencies uses fileName instead of displayFileName

### ISSUE THREAD

**Issue by RyanMcC** [dependency-check/DependencyCheck#3056]
**Describe the bug**

In cases where you have related dependencies that are shaded, the `<fileName>` in XML reports is formatted differently than it is for the root `dependency`. This seems to be because the XML report is using `fileName` instead of `displayFileName` for `relatedDependencies`, and shaded dependencies have different formats for `fileName`/`displayFileName`

This is seen here in the [xmlReport.vsl](https://github.com/jeremylong/DependencyCheck/blob/main/core/src/main/resources/templates/xmlReport.vsl#L96), where `relatedDependencies` use `FileName`, while the root `dependency` uses `DisplayFileName` (on line 74)

In contrast, in the [jsonReport.vsl](https://github.com/jeremylong/DependencyCheck/blob/main/core/src/main/resources/templates/jsonReport.vsl#L76), both the root `dependency` and the `relatedDependencies` use `DisplayFileName`.

**Version of dependency-check used**
The problem occurs using version 6.0.3 of the cli

**To Reproduce**
Analyze any two dependencies that have the same shaded dependency.

**Expected behavior**
`relatedDependencies` should use the `DisplayFileName` for its `<fileName>` in XML reports.

**Comment by jeremylong** [comment]
Thanks for pointing this out. The XML report will be updated in the 6.0.5 release.
