### ISSUE TITLE
False Positive on taglibs-standard-impl

### ISSUE THREAD

**Issue by Marx314** [dependency-check/DependencyCheck#3057]
False positive on library taglibs-standard-impl-1.2.5.jar - reported as ```cpe:2.3:a:tag_project:tag:*:*:*:*:*:*:*:*```
https://mvnrepository.com/artifact/org.apache.taglibs/taglibs-standard-impl/1.2.5

```xml
<!-- https://mvnrepository.com/artifact/org.apache.taglibs/taglibs-standard-impl -->
<dependency>
    <groupId>org.apache.taglibs</groupId>
    <artifactId>taglibs-standard-impl</artifactId>
    <version>1.2.5</version>
</dependency>
```

**Comment by bretik** [comment]
The same FP is being reported on:
- tagsoup-1.2.1.jar
- jstl-api-1.2.jar
