### ISSUE TITLE
Suppression pop up text is wrong if previous suppression text was modified.

### ISSUE THREAD

**Issue by harrybstoner** [dependency-check/DependencyCheck#306]
Against version 1.2.11. Firefox 39.0. In the HTML report, click the "suppress" button then modify the notes text with something custom. Copy the text somewhere. Click the "suppress" button for another issue but the text shown is for the previous issue suppressed.

**Comment by jeremylong** [comment]
The textarea for the suppression notes is now readonly. I have no idea what browser quirk was causing the issue. This may change your desired workflow (slightly) in that you will have to edit the note in a text editor instead of directly in the HTML report.
