### ISSUE TITLE
Anyone else failing to get updates?

### ISSUE THREAD

**Issue by Muzamri** [dependency-check/DependencyCheck#3060]
The semi-colon at the end is causing the failure.

![dep-check-update-failure](https://user-images.githubusercontent.com/5036921/103876249-62911780-510e-11eb-978c-29b6ed4cfb08.png)

**Comment by jeremylong** [comment]
No issue on my end. I'm able to run the update and download https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2021.meta

The semi-colon you are seeing is only in the log message - it is not part of the URL used. See https://github.com/jeremylong/DependencyCheck/blob/c73d0b9685b6acca5bde10e164ab83a23d10b954/core/src/main/java/org/owasp/dependencycheck/data/update/NvdCveUpdater.java#L350-L351

**Comment by Muzamri** [comment]
Ah, I see -- thank you for your time.
