### ISSUE TITLE
False Positive on lang-tag-1.5.jar 

### ISSUE THREAD

**Issue by kajh** [dependency-check/DependencyCheck#3061]
Please see https://groups.google.com/g/dependency-check/c/r1_tG9pVBSM

False positive on library lang-tag-1.5.jar - reported as cpe:2.3: a:tag_project:tag:1.5:*:*:*:*:*:*:*)

(I had to add a space before "a:" because of the formatting)

```xml
<dependency>
    <groupId>com.nimbusds</groupId>
    <artifactId>lang-tag</artifactId>
    <version>1.5</version>
</dependency>
```

**Comment by aikebah** [comment]
Should be fixed by fix for #3043 for which a fix is included in the brand-new 6.0.5 version, but @jeremylong Shouldn't we add tag_project as a generic CPE suppression as it's a go project so that it should not hit for Java/.NET/node.js project artifacts?
