### ISSUE TITLE
How to include manual CPE check

### ISSUE THREAD

**Issue by Thibaud-R** [dependency-check/DependencyCheck#3065]
Hi,

I am using the maven plugin on the 6.0.5 version.

I would like to include in our DependencyCheck report, CVE regarding the provided environment.
I already include CVE for our provided Tomcat, using a maven dependency with a provided scope, but I don't know how to check CVE on the provided JRE.

Is there a way to add manually the check of CVE on a dedicated CPE ? 
Currently, I did it manually by [searching on the NVD site](https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&seach_type=all&query=cpe:2.3:a:oracle:jre:1.8.0:update_251:*:*:*:*:*:*) but having everything in the report would be great.

Thanks,
Thibaud

**Comment by jeremylong** [comment]
Unfortunately, that is not a current capability within dependency-check. Have you looked at dependency-track? It works differently then dependency-check and may provide what you are looking for.

**Comment by Thibaud-R** [comment]
OK, thanks a lot for your quick answer.
I will take a look to dependency-track,

For the moment, I use a system dependency with a "system" jar.
But the matching of dependency version with CPE version is not straight equivalent (and with oracle:jre:1.8.0:update_252) ...
