### ISSUE TITLE
Incorrect fallback Go CLI invocation

### ISSUE THREAD

**Issue by jupenur** [dependency-check/DependencyCheck#3069]
**Describe the bug**
The Go CLI invocation here is incorrect and completely broken: https://github.com/jeremylong/DependencyCheck/blob/120587d/core/src/main/java/org/owasp/dependencycheck/analyzer/GolangModAnalyzer.java#L220-L224

Unclear how that ever could have worked.

The correct invocation would probably be something like `go list -json -m -mod readonly all` instead.

**Version of dependency-check used**
6.0.5 cli.

**To Reproduce**
1. Try to run the Go Analyzer
2. Observe `Invalid token=EOF at (line no=1, column no=0, offset=-1). Expected tokens are: [CURLYOPEN, SQUAREOPEN, STRING, NUMBER, TRUE, FALSE, NULL]`

This is because DependencyCheck expects JSON output, but the CLI invocation is broken and only prints to stderr.

**Expected behavior**
The Go Analyzer should run without errors.

**Additional context**

**Comment by jeremylong** [comment]
Thanks for the bug report. The fix will be included in the next release.

**Comment by jupenur** [comment]
@jeremylong the fix is still missing `-mod`

**Comment by jeremylong** [comment]
Thank you for catching that. The patch has been updated.
