### ISSUE TITLE
SSL Error when using GitHub Actions and trying to download the NVD file.

### ISSUE THREAD

**Issue by tunderwood** [dependency-check/DependencyCheck#3072]
**Describe the bug**
For one of our projects, we are getting a `Received fatal alert: unrecognized_name` error when trying to update the NVD metadata file on GitHub Actions.

**Version of dependency-check used**
The problem occurs using version 5.3.2 and 6.0.5 of the Gradle plugin 

**Log file**
https://gist.github.com/tunderwood/9661f19a84cbd5a27e8dd667ef6ba0b8

**To Reproduce**
The issue does not impact all our projects so it's not incredibly reproducible. We simply run dependencyCheckAnalyse on an Ubuntu-Latest Github Actions runner and for some projects it fails and for others it does not

**Expected behavior**
The DependencyCheck Analyse task suceeds

**Additional context**

We use the Gradle plugin in several projects which are built on GitHub. They should all have identical configurations however one of our projects started failing around 12/20/20. We didn't make any code changes to the projects prior to the build failing (we have an automated weekly build that began failing). The dependency check analyzes task succeeds when run locally. 

I don't know if this is an issue with the plugin or with GitHub Actions but I thought I'd see if there were ideas as to the root cause.  Thanks!

**Comment by jeremylong** [comment]
Interesting...  I've found one article that looks relevant on SO: https://stackoverflow.com/questions/55903477/received-handshake-warning-unrecognized-name

Any possible difference in the version of Java being used between the instances that succeed and the one that fails?

**Comment by tunderwood** [comment]
We found the issue. It turns out this specific project had the SNI extension set to false in gradle.properties. Removing that configuration fixed the problem. 

Thanks!
