### ISSUE TITLE
Typo in ComposerLockAnalyzer.java

### ISSUE THREAD

**Issue by KuSh** [dependency-check/DependencyCheck#3075]
Hi,

Commit ff057b1ab5291b2f862330b3a52a0c305fabcd2a introduced by @jeremylong seems to contain a mistake for core/src/main/java/org/owasp/dependencycheck/analyzer/ComposerLockAnalyzer.java file

See, https://github.com/jeremylong/DependencyCheck/blob/2ac9f926543858e0a61f189ac87e58cedd7c1dc6/core/src/main/java/org/owasp/dependencycheck/analyzer/ComposerLockAnalyzer.java#L56

It expose composer.lock files as being part of Ecosystem.PYTHON instead of Ecosystem.PHP

Regards,
Nicolas

**Comment by jeremylong** [comment]
Thanks - looks like a copy/paste issue. This has been fixed in code.
