### ISSUE TITLE
Objective_C and Swift iOS projects - Vulnerabilities not showing properly

### ISSUE THREAD

**Issue by ravichalla** [dependency-check/DependencyCheck#3077]
The problem with dependencies and finding of vulnerability  in **Objective-C** iOS projects using Dependency-Checker-CLI project https://github.com/jeremylong/DependencyCheck
The vulnerabilities are not properly showing for a 
--> Objective-c iOS project.
--> Swift iOS project.

Swift - Just I think, the new format of iOS package.swift might be causing issue.

**Comment by jeremylong** [comment]
We believe this was fixed in a recent release but did not see remember to close this issue.
