### ISSUE TITLE
Dependencies not detected on package-lock-json

### ISSUE THREAD

**Issue by calderaax** [dependency-check/DependencyCheck#3079]
**Describe the bug**
We implemented dependency check as a job in pipelines of all projects in our gitlab as part of the ci/cd process. Last month the projects were being analyzed without problems and the report output showed a lot of dependencies. Yesterday a lot of the developers teams told us that the same projects are detecting 0 dependencies, we tested the package-lock.json and it seems ok, not too many modifications just added some new dependencies and deleted others.

**Version of dependency-check used**
The problem occurs using version 5.3.2 and 6.0.5  of the cli

**Log file**

_logs_532.txt_ (log output using version 5.3.2)
https://gist.github.com/calderaax/6beb4f3d7ce15c9bb31d46675c750c89
_logs_605.txt_ (log output using version 6.0.5)
https://gist.github.com/calderaax/81e6d51180700bc08a1da5b31cc58c31

_good_package-lock.json_ (december 2020 package-lock.json working fine)
https://gist.github.com/calderaax/131844db189799e352bfb5ba847b35b1
_report_ok.json_. (report of the december 2020 package-lock.json)
https://gist.github.com/calderaax/8d5ca87ca35332c5c4412a68de90811b

_bad_package-lock.json_. (january 2021 package-lock.json **not** working fine)
https://gist.github.com/calderaax/8361ac8c3f9be6207e014334209ea6f8
_report_bad.json_ (report of the january 2021 package-lock.json)
https://gist.github.com/calderaax/75fc01fbbf62b9b0d19b745b265ad7da

**To Reproduce**
1. Download **good_package-lock.json** rename it to **package-lock.json**
2. Execute dependency check to scan that file  `dependency-check  --project "My App Name" --scan "/tmp/project"`
3. See results
4. Download **bad-lock.json** rename it to **package-lock.json**
5. Execute dependency check to scan that file  `dependency-check  --project "My App Name" --scan "/tmp/project"`
6. Compare results (good package lock shows dependencies, bad package lock doesn't show any)

**Expected behavior**
Both cases should show the amount of dependencies and possible vulnerabilities

**Additional context**
Some changes were made, some dependencies were upgraded, added new ones and deleted others. 
The structure of the json file was tested and is ok. We recreate the package-lock serveral times but the problem persist

**Comment by jeremylong** [comment]
So I downloaded the "bad" lock file.  Ran `npm install` and then ran:
```bash
$npm audit      
found 0 vulnerabilities
```

ODC does not create an SBOM - for npm it only lists the vulnerable packages.

**Comment by calderaax** [comment]
The problem is in the result file, in the "good" lock file the result is a json with a list of the dependencies even when no vulnerabilities are found (in this case vuln were found but in other cases no vuln were found but the list of dependencies are shown in the json file).

`"dependencies": [
    {
      "isVirtual": true,
      "fileName": "axios:0.19.2",
      "filePath": "/code/package-lock.json?axios",
      "projectReferences": [
        "delivery: transitive"
      ],
etc
etc
`

In the "bad" lock file result that list is empty.
` "dependencies": []`

It seems like it couldn't read the dependencies from the package-lock.json

**Comment by calderaax** [comment]
If there are not vulnerable dependencies is it ok that the html report shows: 

`Dependencies Scanned: 0 (0 unique)`
![image](https://user-images.githubusercontent.com/13373845/114229040-4dae6500-9945-11eb-8b46-145f99d17817.png)
