### ISSUE TITLE
Dependency check 6.0.5 Error with .NET AssemblyAnalyzer 

### ISSUE THREAD

**Issue by mithrandir1589** [dependency-check/DependencyCheck#3080]
Hello, 

I'm having the followwing error **[WARN] An error occurred with the .NET AssemblyAnalyzer, please see the log for more details.** when running dependency check 6.0.5, I test the same project in another machine and works without any problem. I'm wondering if the netCore SKD version is related with the issue. The current version of netCore is 2.2.109. Any guidance will be appreciated. 

Thanks.

**Comment by jeremylong** [comment]
I am currently using 3.1.  You can download the GrokAssembly.zip directly and test it out: https://github.com/jeremylong/DependencyCheck/raw/v6.1.0/core/src/main/resources/GrokAssembly.zip

You can just run it on itself: `/GrokAssembly GrokAssembly.dll`
