### ISSUE TITLE
Add Sarif file format support

### ISSUE THREAD

**Issue by jason-edstrom** [dependency-check/DependencyCheck#3081]
**Is your feature request related to a problem? Please describe.**
I love the information that this provides, but I would like to be able to report the information in the GitHub Security tab.  That upload requires a Sarif file format.

**Describe the solution you'd like**
I would like the plugin to generate a sarif file for upload.

**Describe alternatives you've considered**
Currently using the junit xml file to provide some traceability
I would be willing to use the sonarqube plugin, but I'm using sonarcloud currently.

**Additional context**
![JUnit workaround](https://user-images.githubusercontent.com/2515629/104660027-67644700-568b-11eb-9996-0a49c37f79d2.png)
![security-tab](https://user-images.githubusercontent.com/2515629/104660073-7a771700-568b-11eb-80de-d3cc0d005ee1.png)

**Comment by jeremylong** [comment]
Initial implementation via #3083. I'm sure we could do better.  One thing this does not do is include the relatedDependencies section.
