### ISSUE TITLE
False Positive on sonar-java-plugin

### ISSUE THREAD

**Issue by TobiX** [dependency-check/DependencyCheck#3086]
False positive on library `sonar-java-plugin-6.9.0.23563.jar` - reported as `cpe:2.3:a:sonarsource:sonarqube:6.9.0.23563`
```xml
    <dependency>
      <groupId>org.sonarsource.java</groupId>
      <artifactId>sonar-java-plugin</artifactId>
      <version>6.9.0.23563</version>
      <type>sonar-plugin</type>
    </dependency>
```

While the scanner plugins are tightly integrated with SonarQube, they don't follow the same version scheme.

Since there are some artifacts from the same project (https://github.com/SonarSource/sonar-java) shaded into the 6.9.0 jar, I'd suggest something along the lines of:
```xml
<suppress>
   <notes><![CDATA[sonar-java-plugin and shaded artifacts]]></notes>
   <packageUrl regex="true">^pkg:maven/org\.sonarsource\.java/(sonar\-java\-plugin|external\-reports|java\-checks|java\-frontend|java\-jsp|java\-surefire)@.*$</packageUrl>
   <cpe>cpe:/a:sonarsource:sonarqube</cpe>
</suppress>
```

**Comment by aikebah** [comment]
No need for such a complex regex. The groupId org.sonarsource.java is already reserved for the sonar java analyzer project, which is separate from the sonarqube project. So the groupId can be used as the suppression filter.
