### ISSUE TITLE
Possible to ignore issues for specific modules from aggregation?

### ISSUE THREAD

**Issue by ghost** [dependency-check/DependencyCheck#3087]
Hi,

Is there any way of excluding dependency issues from certain modules from a aggregation dependency-check?

I have a multi-module Maven project where several of the modules are test frameworks. If I simply exclude them from the reactor I get dependency resolution exceptions and the `excludes` config parameter seems to only exclude transitive dependencies, not modules found in the reactor.

Here is a minimal project that shows the problem: https://github.com/viktor-thell-seal/ignore-test-dep

I'm using the Maven plugin version 6.0.5.

**Comment by jeremylong** [comment]
Please see the notes in the PR. This will be included in the next release.

**Comment by ghost** [comment]
@jeremylong Awsome, thanks!

I tested locally and it works well using the config you showed in the PR. However, I was hoping it might be enough to add the property `<dependency-check.skip>true</dependency-check.skip>` in the child modules but that is not working. 

Is that expected?

**Comment by spatel2s** [comment]
Hi,
I have used this property in one my child module, but it skipped all the child modules from the check.
Can you please check that Or there is something else i am missing?
