### ISSUE TITLE
Report generated suppressions for node modules don't work

### ISSUE THREAD

**Issue by SpenceUK** [dependency-check/DependencyCheck#3092]
**Describe the bug**
The generated suppression.xml snippets produced from the dependency check report do not suppress npm package failures.

**Version of dependency-check used**
org.owasp:dependency-check-maven:5.3.0:check

**To Reproduce**
have this in your package-lock when running the check:
`package-lock.json?ini (pkg:npm/ini@1.3.5) : 1589, CWE-471: Modification of Assumed-Immutable Data (MAID)`

**Expected behavior**
generated snippet will suppress the vulnerability

**Additional context**
Generated snippets:
`<suppress>
   <notes><![CDATA[
   file name: ini:1.3.5
   ]]></notes>
   <packageUrl regex="true">^pkg:npm/ini@.*$</packageUrl>
   <vulnerabilityName>1589</vulnerabilityName>
</suppress>`

`<suppress>
   <notes><![CDATA[
   file name: ini:1.3.5
   ]]></notes>
   <sha1>1d18d6aa3898eecb5b1768d8bb933224740e90fe</sha1>
   <vulnerabilityName>CWE-471: Modification of Assumed-Immutable Data (MAID)</vulnerabilityName>
</suppress>`

**Comment by jeremylong** [comment]
Just installed ini:1.3.5, run ODC, generated the following suppression file:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<suppressions xmlns="https://jeremylong.github.io/DependencyCheck/dependency-suppression.1.3.xsd">
   <suppress>
      <notes><![CDATA[
      file name: ini:1.3.5
      ]]></notes>
      <packageUrl regex="true">^pkg:npm/ini@.*$</packageUrl>
      <vulnerabilityName>CWE-471: Modification of Assumed-Immutable Data (MAID)</vulnerabilityName>
   </suppress>
</suppressions>
```

Re-ran ODC and the vulnerability was suppressed. Consider upgrading to the latest version of ODC.
