### ISSUE TITLE
ERROR: Unable to lock database: Permission denied

### ISSUE THREAD

**Issue by mhalt** [dependency-check/DependencyCheck#3093]
Hello @jeremylong ! I'm hoping that you can advise me. I'm trying to add OWASP DC to my GitLab CI/CD pipeline. The workflow will be run OWASP DC (script) then import the XML scan results to OWASP Defect Dojo (after script) but I'm having issues with the last part. The script is run against the DC container. If you could also review my DC command syntax, I would be appreciative. 

I was receiving curl command not found so I added it. 
```
/bin/sh: eval: line 104: curl: not found
- apk add --no-cache curl
```

But now I'm getting permission denied for adding the curl command that I need to import the report. 
```
ERROR: Unable to lock database: Permission denied
ERROR: Failed to open apk database: Permission denied
```

**Do you know how I can achieve this without modifying the DC DOCKERFILE?**

Here is the YAML code for the GitLab CI Job:

```
# Scan Dependencies for known Vulnerabilities 
# -----------------------------------------    
dependencycheck:
  stage: security
  variables:
    SCAN_TYPE: scan_type="Dependency Check" 
    REPORT: gl-dependency-check-report.xml
  image:
      name: owasp/dependency-check
      entrypoint: [""] 
  script:
      - /usr/share/dependency-check/bin/dependency-check.sh -v
        --format XML 
        --enableExperimental 
        --suppression=$CI_PROJECT_DIR/dependency_check_suppressions.xml
        --scan=$CI_PROJECT_DIR
        --out=$REPORT
  artifacts:
    paths:
      - $REPORT         
  after_script:
    - apk add --no-cache curl
    - curl -v -X POST "${DOJO_URL}" 
      --header "${DOJO_AUTH}" 
      --header "${DOJO_CONTENT}" 
      --form "${ENGAGEMENT}" 
      --form 'verified="true"' 
      --form 'active="true"' 
      --form 'lead="1"' 
      --form 'tags="gitlab"' 
      --form "${SCAN_TYPE}" 
      --form 'minimum_severity="Info"' 
      --form 'skip_duplicates="true"' 
      --form 'close_old_findings="false"' 
      --form 'file=@"gl-dependency-check-report.xml"'  
```

**Comment by jeremylong** [comment]
It appears that there are no volumes setup. As such, this will fail. I see that this might be possible using [config.toml](https://docs.gitlab.com/runner/configuration/advanced-configuration.html)

**Comment by Louis-2b** [comment]
Owasp_Dependency_Check:
  stage: test
  image:
    name: owasp/dependency-check:latest
    entrypoint: [""]
  before_script:
    - apk add --no-cache python3 py3-pip 
# Naviguer vers le répertoire python où se trouve votre script      
    - cd python
  script:
    - python3 dependency-Check.py 
  only:
    - main
    - /^feature/


Voici le problème que je rencontre...
$ apk add --no-cache python3 py3-pip
ERROR: Unable to lock database: Permission denied
ERROR: Failed to open apk database: Permission denied
ERROR: Job failed: exit code 99
