### ISSUE TITLE
RetireJS makes analysis fail after 20min due to timeout

### ISSUE THREAD

**Issue by so87** [dependency-check/DependencyCheck#3095]
**Describe the bug**
I have a file with TONS of JS dependencies. Run analysis fails. Saw another issue were i could set odc.analysis.timeout=120 to fix timeout but that didn't work. If i disable RetireJS the problem goes away. If i analyze a smaller file the problem goes away.

**Version of dependency-check used**
6.0.3

**Log file**
Cannot provide full log file. Providing error:
Exception Caught: java.util.concurrent.CancellationException

**To Reproduce**
1. launch container
2. export odc.analysis.timeout=120
3. scan large JS file

**Expected behavior**
I expected it to run more than 20min

**Additional context**
I am doing this in a container

**Comment by jeremylong** [comment]
Run with `--log odc.log` and check the top of the log where it outputs the configuration and please check that it is picking up the 120.

**Comment by so87** [comment]
thank you, i had to download your properties file. then add that setting to it, and then the scan completed successfully.
