### ISSUE TITLE
CSV does not output all dependencies. Only dependencies that are vulnerable.

### ISSUE THREAD

**Issue by so87** [dependency-check/DependencyCheck#3096]
**Is your feature request related to a problem? Please describe.**
I want to produce a report that displays all of our dependencies. I end up parsing your CSV file and turning into a better format.

**Describe the solution you'd like**
To include all dependencies in .csv, or include all of them in a different csv like all.csv. 

I should have parsed the XML file, but i didn't. My work around would be to rewrite the python scripts i wrote to parse the XML instead of CSV for metrics as such.

**Comment by jeremylong** [comment]
The CSV report is not intended to provide a list of all dependencies.  Consider using the JSON format.
