### ISSUE TITLE
Feature: Offer direct dependency updates that will fix transitive

### ISSUE THREAD

**Issue by RunFox** [dependency-check/DependencyCheck#3100]
Hello. DC find many transitive dependencies in project, and manual fix all of this may take a lot of time.
I think, that is good idea to include fix of direct dependencies, that also fix transitive dependnecies in report. Of course, it is not always possibe, bit when it is - it will be good practise. It will make reports more useful.

**Comment by jeremylong** [comment]
Many of the use cases for ODC do not include the dependency tree. As such, it is difficult to determine this. However, if you are running a maven or gradle project it is trivial to figure out where the transitive dependencies are coming from by using commands such as `mvn dependency:tree`.
