### ISSUE TITLE
Failure when yarn is not available on the system

### ISSUE THREAD

**Issue by Toilal** [dependency-check/DependencyCheck#3105]
**Describe the bug**
scan fails when yarn is not available on the system

**Version of dependency-check used**
The problem occurs using version 6.1.0

**Log file**

```
[ERROR] Failed to execute goal org.owasp:dependency-check-maven:6.1.0:check (default) on project estamp: One or more exceptions occurred during dependency-check analysis: One or more exceptions occurred during analysis:
[ERROR] 	InitializationException: Unable to read yarn audit output.
[ERROR] 		caused by IOException: Cannot run program "yarn": error=2, Aucun fichier ou dossier de ce type
[ERROR] 		caused by IOException: error=2, Aucun fichier ou dossier de ce type
[ERROR] -> [Help 1]
```

**To Reproduce**

1. Make sur yarn is NOT available in your system
2. Run a scan using maven
3. See error

**Expected behavior**
Yarn audit should be skipped when yarn is not available in the system

**Additional context**

I tried to add `<yarnAuditAnalyzerEnabled>false</yarnAuditAnalyzerEnabled>` in the maven plugin configuration, but maven stills exit with the same error. I'm not sure this option has ben brought into this version of the maven plugin.

Rolling back to 6.0.5 make things works again.

**Comment by RasmusOlesen** [comment]
--disableYarnAudit works for the command line tool.
I don't know if there is an equivalent for the technology you are using.

**Comment by jeremylong** [comment]
I apologize - somehow I missed adding the configuration for `yarnAuditAnalyzerEnabled` to the maven plugin. I will correct that shortly.

**Comment by Toilal** [comment]
Great job @jeremylong. You don't have to apologize though, as you bring this tool for free, you only have to receive many thanks :)
