### ISSUE TITLE
uninterpolated placeholders in HTML report

### ISSUE THREAD

**Issue by wilx** [dependency-check/DependencyCheck#3106]
**Describe the bug**
The generated HTML report contains uninterpolated placeholders:

```
<a href="#l172_$enc.html($enc.url($dependency.Sha1sum))">k8s.io/kubernetes:1.13.0</a>
```

The report is mainly about Go language modules.

The problem occurs using version 6.1.0 of the Maven plugin.

**Comment by jeremylong** [comment]
The fix will be included in the next release.
