### ISSUE TITLE
MSBuild Analyzer not available in all build management tools

### ISSUE THREAD

**Issue by albuch** [dependency-check/DependencyCheck#3116]
I saw that you've recently added CLI arguments for the experimental MSBuild Project Analyzer added with #1133, however it seems the setting is missing in all the other build management integrations. Is there a reason for this, other than unlikelyhood for projects using these build tools? The later wasn't a reason for other related settings (nuspec) to be included in e.g. maven and gradle plugins.

**Comment by jeremylong** [comment]
Missing configuration options have been added and will be included in the next release.
