### ISSUE TITLE
How do I use Node Audit in an environment without the Internet?

### ISSUE THREAD

**Issue by daxin09pp** [dependency-check/DependencyCheck#3129]
When I used Dependent-Check in an environment without the Internet, the report show like this:
`Failed to connect to the NPM Audit API (NodeAuditAnalyzer); the analyzer is being disabled and may result in false negatives.`
Is there a solution to the NPM Audit API like the nvd-mirror in non Internet environment?
Thanks!

**Comment by jeremylong** [comment]
Unfortunately, at the moment this is not possible. There is an enhancement request to allow one to configure local audits or setup a different URL for the audit analysis. However, these have not been implemented yet: #2423 and #1924.

**Comment by daxin09pp** [comment]
Thanks, @jeremylong
