### ISSUE TITLE
Alert user when *.iso files are encountered

### ISSUE THREAD

**Issue by dwvisser** [dependency-check/DependencyCheck#313]
I am writing a documentation page that instructs on how to mount ISO images in the file system in the various operating systems, for the purpose of using Dependency-Check to scan the image. It would be nice if a message informed the user each time a *.iso file is encountered, instructing them that it will be necessary to mount the image if they wish to scan its contents.

I was thinking that possibly this could be accomplished by creating a subclass of `AbstractFileTypeAnalyzer` that logged a warning, and possibly placed the same message in the product evidence, so that reports would also expose the information.

**Comment by jeremylong** [comment]
I have no plans to implement this.
