### ISSUE TITLE
OSS Cache

### ISSUE THREAD

**Issue by VolhaRS** [dependency-check/DependencyCheck#3130]
Hello,
Some of my scannings are failed with the next error:
[ERROR] .NET Assembly Analyzer could not be initialized and at least one 'exe' or 'dll' was scanned. The 'dotnet' executable could not be found on the path; either disable the Assembly Analyzer or add the path to dotnet core in the configuration.
[ERROR] Failed to request component-reports

I think it is related to OSS Index rate limit, but I'm not sure about that. As I can see in the documentation, the dependency check plugin caches OSS information for 24 hours, but at the same time, it tries to get component-reports from OSS API. Can dependency check plugin use only cache?

**Comment by jeremylong** [comment]
This has nothing to do with OSS index. As the error message indicated at least one exe or dll was scanned (it may be buried in a ZIP, JAR, etc.). The assembly analyzer requires dotnet core 3.1. You can either install dotnet core, disable the assembly analyzer, or ignore the warning.
