### ISSUE TITLE
Moving from Bintray?

### ISSUE THREAD

**Issue by javixeneize** [dependency-check/DependencyCheck#3139]
Hi

Currently all the dependency check binaries are stored in bintray, but looks like this service will be stopped soon - https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Is there any plan to move to another plaftorm?

Thanks

**Comment by jeremylong** [comment]
Please see the [6.0.2 release notes](https://github.com/jeremylong/DependencyCheck/blob/main/RELEASE_NOTES.md#version-602-2020-09-27).

**Comment by javixeneize** [comment]
Thanks!
