### ISSUE TITLE
docs - bad hyperlink for suppression file info

### ISSUE THREAD

**Issue by gmanfunky** [dependency-check/DependencyCheck#314]
http://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html

Has a link for false positives. 

It points to http://jeremylong.github.io/DependencyCheck/suppression.html

But should point to https://jeremylong.github.io/DependencyCheck/general/suppression.html

**Comment by jeremylong** [comment]
The links have been fixed in the source repo and will be published with the next release.
