### ISSUE TITLE
CVE is not cleaned when it is rejected

### ISSUE THREAD

**Issue by Lenoiche** [dependency-check/DependencyCheck#3148]
I use a database to store vulnerabilites. Rejected CVEs are not deleted and are still attached to the cpe

The problem occurs using version 6.1.1

I identified the issue 
in `org.owasp.dependencycheck.data.update.nvd.NvdCveParser`
there is a test which return always false for rejected CVEs
`                if (testCveCpeStartWithFilter(cve)) {
                    cveDB.updateVulnerability(cve, mapper.getEcosystem(cve));
                }`

**Comment by jeremylong** [comment]
If there are no application CPEs for a CVE - you are correct, this would leave a rejected CVE in the database. However, as there are no application CPEs associated to the rejected CVE it will never be included in the report as it will never match any of the dependencies identified.

**Comment by Lenoiche** [comment]
Thanks for your reply
But 
- first the CVE is added with the matched cpe in Dependency Check
- NVD withdraw the CVE
- When Dependency Check try to update the rejected CVE, it don't update / delete the CVE because of the test

I use Postgresql as database
