### ISSUE TITLE
Dockerfile ADD failing as the folders mentioned are not available in the code

### ISSUE THREAD

**Issue by SarayuR** [dependency-check/DependencyCheck#3149]
Dockerfile, line 22 :

ADD cli/target/dependency-check-${VERSION}-release.zip /

But there is no target/dependency-check-${VERSION}-release.zip folder under cli folder hence unable to build the image.

**Comment by jeremylong** [comment]
I just added instructions on building the docker container: https://github.com/jeremylong/DependencyCheck#building-the-docker-image

Basically, you need to have built the CLI using at a minimum `mvn package`. Then there is a bash script that extracts the current version from the maven build and creates the image.
