### ISSUE TITLE
ReportException during JSON report generation

### ISSUE THREAD

**Issue by stefanborghys** [dependency-check/DependencyCheck#3152]
Updating the 'dependency-check-maven' maven plugin to version 6.1.0 or 6.1.1 causes the build to fail in a ReportException.
The same build on version 6.0.5 runs without this problem.

The problem occurs using versions 6.1.0 and 6.1.1 of the 'dependency-check-maven' maven plugin
producing following output when building the project.
```
[ERROR] Failed to execute goal org.owasp:dependency-check-maven:6.1.0:check (default) on project medium-vulnerabilities: One or more exceptions occurred during dependency-check analysis: One or more exceptions occurred during analysis:
[ERROR] 	ReportException: Error generating the report for OWASP Dependency Check | Medium Vulnerabilities
[ERROR] 		caused by ReportException: Unable to generate json report
[ERROR] 		caused by JsonParseException: Unexpected character (',' (code 44)): expected a value
[ERROR]  at [Source: (FileInputStream); line: 1, column: 3920]
```
Plugin configuration which might be related: 
```
<formats>ALL</formats>
<prettyPrint>true</prettyPrint>
```

Report configuration which might be related: 
```
<reporting>
    <plugins>
        <plugin>
            <groupId>org.owasp</groupId>
            <artifactId>dependency-check-maven</artifactId>
            <version>${org.owasp.dependency-check-maven.version}</version>
        </plugin>
    </plugins>
</reporting>
```

Dependency of the project's failing (module) build which might be related:
```
<dependencies>
    <dependency>
        <groupId>org.apache.httpcomponents</groupId>
        <artifactId>httpclient</artifactId>
    </dependency>
</dependencies>
```

**To Reproduce**
1. configure 'dependency-check-maven' plugin with configuration to: 
- generate a JSON report (pretty printed)
- execute the 'check' goal
- produce a report (for the maven site) 
2. use dependency 'org.apache.httpcomponents:httpclient:4.0'
3. mvn install
4. a ReportException is thrown during the build

I guess this has been introduced due to regression as no changes where made to the code or dependency versions of the project. 

grts

**Comment by jeremylong** [comment]
i'm unable to reproduce this issue.  Any chance you can share the partially generated JSON report? Can you run the report with `mvn -X ...` and provide any additional log information?

**Comment by jeremylong** [comment]
My guess is that the error is in the SARIF report (which is also a JSON format).

**Comment by jeremylong** [comment]
I found the bug - a fix will be included in 6.1.2.

**Comment by stefanborghys** [comment]
@jeremylong my excuses for not replying. I had hoped to come to this last weekend but hadn't found the time to do so.

I could replicate the issue in an example project i made. [owasp-dependency-check-examples](https://github.com/stefanborghys/maven-examples/tree/main/owasp-dependency-check-examples) 

I will retest when the new version is out. 

Many thanks btw

**Comment by jeremylong** [comment]
@stefanborghys no worries - I anticipate releasing 6.1.2 this weekend.
