### ISSUE TITLE
Tests Fail on Initial Clone

### ISSUE THREAD

**Issue by Will-Low** [dependency-check/DependencyCheck#3157]
**Describe the bug**
Building DependencyCheck using the listed instructions results in a test failure:
```
[ERROR] Failures:
[ERROR]   RubyBundleAuditAnalyzerIT.testAnalysis:128
[ERROR] Errors:
[ERROR]   RubyBundleAuditAnalyzerIT.testAddCriticalityToVulnerability:159 ArrayIndexOutOfBounds
[INFO]
[ERROR] Tests run: 67, Failures: 1, Errors: 1, Skipped: 2
```

A quick glance at `DependencyCheck/core/src/test/java/org/owasp/dependencycheck/analyzer/RubyBundleAuditAnalyzerIT.java` seems to point to an issue with dependency parsing in the test Gemfile.lock files.

**Version of dependency-check used**
- On macOS 10.15.7.
- I'm at commit 3adf3e4fa77473ef6c8ba8cd35b41d9a3457c528.
- Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
- openjdk version "1.8.0_265"
- dotnet 3.1.405
- go version go1.15 darwin/amd64
- bundler-audit 0.7.0.1
- yarn 1.22.10

**Log file**
https://gist.github.com/Will-Low/2f4709d49eb6269521c9c50ca259e057

**To Reproduce**
1. Go to cloned DependencyCheck repo
2. Run `mvn -s settings.xml install`

**Expected behavior**
Tests should be passing.

**Comment by jeremylong** [comment]
Do you have the documented pre-reqs installed?  https://github.com/jeremylong/DependencyCheck#development-prerequisites

**Comment by Will-Low** [comment]
Yes. All prereqs are installed and version information is included above.

**Comment by jeremylong** [comment]
My guess is that somehow the path is not being sent to the JVM correctly - so it can't find bundle audit. There is property for the path: https://github.com/jeremylong/DependencyCheck/blob/084806ee5be3824be00e2971b537dfbf2fba2979/utils/src/main/java/org/owasp/dependencycheck/utils/Settings.java#L536

So you can try setting `JAVA_OPTS=-Danalyzer.bundle.audit.path=path/to/bundle-audit`
