### ISSUE TITLE
Should tool be run against spec files or binaries or both?

### ISSUE THREAD

**Issue by disklosr** [dependency-check/DependencyCheck#3164]
While giving this tool a try on a .NET Core project, I naturally run it against a freshly checked-out code repository without building it and it was able to scan all nuget dependencies of the project. I later learned that this tool can scan built binaries too (*.dll files in my case). So I was wondering if one should necessarily build the source code before analyzing it or not. I gave the docs a quick read but couldn't find an answer to my question.

Thanks

**Comment by jeremylong** [comment]
ideally - you should run `dotnet publish` and scan the entire build (including the project files).
