### ISSUE TITLE
Does --scan accept a filename and what will that do?

### ISSUE THREAD

**Issue by CarlInglisBJSS** [dependency-check/DependencyCheck#3166]
In the documentation for the CLI, ```--scan``` is shown as scanning a path. 

In some code which I have inherited the original author is calling the CLI passing ```--scan build.gradle``` and ```--scan composer.lock```

* Is this valid, or am I correct in my assessment that I should be passing ```--scan .``` for the current directory and ```--scan source-dir``` for other directories?

* If it's given a filename,  will it do something clever and work out dependencies from that file?

* Also, is it acceptable to have multiple ```--scan``` options on the same command line?

Thanks!

**Comment by jeremylong** [comment]
The argument `--scan` can accept any path - including Ant style paths (however, you may need to quote these depending on your os/shell). In general, yes `--scan .` is what should be used.  However, for some node.js projects scanning the entire project directory one may need to disable the RetireJS analyzer.

**Comment by CarlInglisBJSS** [comment]
That's great, thanks @jeremylong - I shall get the scripts updated.
