### ISSUE TITLE
sbt plugin

### ISSUE THREAD

**Issue by lutzh** [dependency-check/DependencyCheck#317]
Hi, 

in the 1.3.0 release notes it reads:
"Logging now uses slf4j in the core and this will make it easier to integrate with other build systems in the future (sbt, ivy, etc.)"

I was wondering, are there any plans, or has any work already been done, to support sbt?

**Comment by jeremylong** [comment]
I've had several requests for an SBT plugin. Unless someone beats me to it I may tackle this as my next plugin.

**Comment by albuch** [comment]
Hi,
I've just published a first version of a sbt plugin to Maven central. https://github.com/albuch/sbt-dependency-check
Cheers

**Comment by jeremylong** [comment]
Alexander - that's awesome! I know several people that will be very excited
about this.

--Jeremy

**Comment by jeremylong** [comment]
Alexander - I just pushed 1.4.0. Can you please email me at jeremy.long @ owasp.org?

**Comment by jeremylong** [comment]
Added links to the SBT plugin on the gh-pages that will be published with the next release.
