### ISSUE TITLE
Osstype Index

### ISSUE THREAD

**Issue by itsecforu** [dependency-check/DependencyCheck#3173]
Hey Jeremy!

The Osstype Index states that they support scanning rpm packets.

 When using their plugin with your product, I try to scan the package folder, but I get a null report .
![dp](https://user-images.githubusercontent.com/38696837/109796119-d0e2e980-7c28-11eb-8bcf-f84749fd1fb5.png)

I registered on their site and indicate flags  `--ossIndexUsername` и ` --ossIndexPassword`

Tell me plz , how to correct scan rpm packages ?

Regargs, have a nice day!

**Comment by jeremylong** [comment]
dependency-check does not support rpm. We use the OSS Index to lookup additional vulnerability information for dependencies and dependency management frameworks that are supported by dependency-check.

**Comment by itsecforu** [comment]
Thx u for fast feedback!

Even if I store packages in artifactory? 

**By the way, do you have any examples for scanning artifactoriy?** 

I can't find a request  to scan my instance.

Trying like this: 

`dependency-check.sh  --enableArtifactory=true  --artifactoryURL=https://jfrog.local--artifactoryApiToken=my token`

**Comment by jeremylong** [comment]
dependency-check doesn't scan artifactory - rather it can pull additional information from Artifactory for a given dependency.

**Comment by itsecforu** [comment]
thx for information
