### ISSUE TITLE
[Sonarqube plugin] Is there anyway to set a global exclude?

### ISSUE THREAD

**Issue by VaughanJ** [dependency-check/DependencyCheck#3178]
SonarScanner will create a ".sonarqube" folder which we want to exclude from the analysis. At the moment I'm using the CLI --exclude to ignore the folder, but it would be nice to set this at a global level. Is this possible?

edit: I have version 1.2.6 installed, so will update to latest.

**Comment by jeremylong** [comment]
I believe this question should be asked on the sonarqube plugin repo (different maintainers): https://github.com/dependency-check/dependency-check-sonar-plugin/issues
