### ISSUE TITLE
Processing for NVD CVE not cached

### ISSUE THREAD

**Issue by hadescastillo** [dependency-check/DependencyCheck#3184]
Hi, I managed to have a docker container with all the "json.gz" and "meta" files from https://nvd.nist.gov which I am now using to serve those files to the plugin
```
<configuration>
    <failBuildOnCVSS>7</failBuildOnCVSS>
    <cveUrlModified>http://localhost/modified.json.gz</cveUrlModified>
    <cveUrlBase>http://localhost/%d.json.gz</cveUrlBase>
</configuration>
```
The files are downloaded immediately on plugin execution but the processing steps takes too long.

_Download Started for NVD CVE - 2019
[INFO] Download Complete for NVD CVE - 2018  (20 ms)
[INFO] Download Started for NVD CVE - 2020
[INFO] Download Complete for NVD CVE - 2019  (30 ms)
[INFO] Download Started for NVD CVE - 2021
[INFO] Download Complete for NVD CVE - 2021  (4 ms)
[INFO] Download Complete for NVD CVE - 2020  (29 ms)
[INFO] Processing Complete for NVD CVE - 2003  (1885 ms)
[INFO] Processing Started for NVD CVE - 2002
[INFO] Processing Complete for NVD CVE - 2002  (3062 ms)
[INFO] Processing Started for NVD CVE - 2004
[INFO] Processing Complete for NVD CVE - 2004  (1684 ms)
[INFO] Processing Started for NVD CVE - 2005
[INFO] Processing Complete for NVD CVE - 2005  (2538 ms)_

Is there a way to have them already processed beforehand? Thank you.

**Comment by jeremylong** [comment]
Take a look at how the github action works: https://github.com/dependency-check/Dependency-Check_Action

This keeps an up-to-date database in the image and its update nightly.

**Comment by hadescastillo** [comment]
Ok will have a look, thanks for the quick reply @jeremylong. Closing now.
