### ISSUE TITLE
False Positive on docker-client

### ISSUE THREAD

**Issue by ghost** [dependency-check/DependencyCheck#3185]
False positive on library docker-client-8.16.0.jar - reported as `cpe:2.3:a:docker:docker:*:*:*:*:*:*:*:*`
```xml
<dependency>
    <groupId>com.spotify</groupId>
    <artifactId>docker-client</artifactId>
    <version>8.16.0</version>
</dependency>
```

**Comment by aikebah** [comment]
@jeremylong Would like to hear your judgement on fixing this (invalid cpe binding) in our base suppression file for a project that is INACTIVE per its [github project](https://github.com/spotify/docker-client/) and has already built a history of outstanding PRs for various [vulnerable dependencies](https://github.com/spotify/docker-client/pulls).

**Comment by jeremylong** [comment]
The problem here is that I don't think docker-client is `docker`.  If there are vulnerable dependencies - those should show up as transitive dependencies...

**Comment by aikebah** [comment]
True, docker-client is not docker (nor spotify:spotify which it also detected) will include suppression of the false CPE matches in my FP fixes... expect to finalize fixing a series of FPs by tomorrow.
Main reason I was wondering whether we should include it in our suppressions is that the project itself appears to be stale by now, not even upgrading its dependencies for vulnerabilities.
