### ISSUE TITLE
Version 6.1.2 not available from https://dl.bintray.com/jeremy-long/owasp/

### ISSUE THREAD

**Issue by dfl-erik** [dependency-check/DependencyCheck#3188]
**Describe the bug**
https://jeremylong.github.io/DependencyCheck/current.txt lists 6.1.2 as the latest version, but 6.1.2 isn't available from https://dl.bintray.com/jeremy-long/owasp/

**Version of dependency-check used**
6.1.2

**Log file**
N/A

**To Reproduce**
1. Get version from https://jeremylong.github.io/DependencyCheck/current.txt 
2. Attempt to download version 6.1.2 from https://dl.bintray.com/jeremy-long/owasp/

**Expected behavior**
Version 6.1.2 should be available for download

**Additional context**
N/A

**Comment by mprins** [comment]
> Expected behavior
Version 6.1.2 should be available for download

Nope, bintray will die soon, check the release notes and the closed issue list eg. https://github.com/jeremylong/DependencyCheck/issues/3182#issuecomment-793156127

**Comment by dfl-erik** [comment]
Thanks for the information.
