### ISSUE TITLE
Spring Security False Positives (again)

### ISSUE THREAD

**Issue by Quantas** [dependency-check/DependencyCheck#319]
It looks like Spring Security 3.2.8 is showing up as a false positive in the dependency check.  This is the current version for the 3.2.8 line and as far as I know, there are no CVE's associated with it. Please let me know if you need further information.

**Comment by jeremylong** [comment]
Actually, I believe this is a correct report. I am still not 100% sure of the relationship between Pivotal, VMWare, and SpringSource - but there are CPE/CVE combos for all three related to Spring. For instance, info one of the Pivotal Spring Framework CVEs can be found here: https://jira.spring.io/browse/SPR-12354

Info on the other can be found here: https://bugzilla.redhat.com/show_bug.cgi?id=1131882

By current version of 3.2.8 - I'm not sure what you mean. There are newer versions of 3.2.x:

``` xml
<dependency>
    <groupId>org.springframework</groupId>
    <artifactId>spring-core</artifactId>
    <version>3.2.14.RELEASE</version>
</dependency>
```

**Comment by jeremylong** [comment]
I just realized you said Spring-Security. That is a false positive and I corrected the issue. Sorry for the misunderstanding on my above comment.

The patch has been added to the core 1.3.1-SNAPSHOT and will be included in the next release.

Best Regards,

Jeremy

**Comment by colezlaw** [comment]
FWIW, Pivotal is a company VMWare started to house lots of projects that
were once under the "vFabric" suite, including Spring, CloudFoundry, and
some other things (unfortunately, the Pivotal site doesn't make that very
clear). So basically, Spring Foundation as an opensource group was bought
by vmware, who then spun off a new company with those folks called Pivotal.

**Comment by Quantas** [comment]
Thanks for the followup and the quick fix @jeremylong
