### ISSUE TITLE
6.1.2 zip not available

### ISSUE THREAD

**Issue by CarlInglisBJSS** [dependency-check/DependencyCheck#3192]
https://jeremylong.github.io/DependencyCheck/current.txt says the latest is 6.1.2 however the latest zip in https://dl.bintray.com/jeremy-long/owasp/ is 6.1.1

**Comment by jeremylong** [comment]
Please see the release notes https://github.com/jeremylong/DependencyCheck/blob/main/RELEASE_NOTES.md - as bintray is shutting down the zip files are now hosted on github.
