### ISSUE TITLE
Analysis completes, but Gradle build fails

### ISSUE THREAD

**Issue by Arc-E-Tect** [dependency-check/DependencyCheck#3194]
**Describe the bug**
I followed the instructions as documented here: https://jeremylong.github.io/DependencyCheck/dependency-check-gradle/index.html
When running the task gradlew dependencyCheckAnalyze as instructed, the build fails with a reported exception that Yarn could not be found and was disabled. After installing yarn, as instructured here: https://github.com/jeremylong/DependencyCheck although not entirely convinced that this would solve the problem, the problem persists.

The error I get is:
```
Exception occurred initializing Yarn Audit Analyzer.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dependencyCheckAnalyze'.
> Analysis failed.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 10s
```
Additional output attached as GIST below, it was generated using:
```
 gradlew dependencyCheckAnalyze -info
```

**Version of dependency-check used**
The problem occurs using version 6.1.2 of the gradle (cli, gradle plugin, maven plugin, etc.)

**Log file**
When reporting errors, 99% of the time log file output is required. Please post the log file as a [gist](https://gist.github.com/ThreeAxis/c3512f3a26bdac379d943849f332985d) and provide a link in the new issue.

**To Reproduce**
1. Clone the repostitory at 'https://github.com/ThreeAxis/arc-e-tect_phonebook/tree/s01e06'
2. Run ./gradlew dependencyCheckAnalyze
3. See error

**Expected behavior**
A build that does not fail, or provide me with an error that tells me how to correct the error

**Additional context**
None

**Comment by jeremylong** [comment]
If you have a yarn lock file and yarn is not installed you will receive this error - and the NPM dependencies will not be analyzed. You can either install yarn (you may need to provide ODC the path to yarn) or disable the yarn analyzer.

**Comment by Arc-E-Tect** [comment]
Thanks for the response. I have yarn installed, runs from the commandline without problems. Installed it because of the error, although I don't use it.
I'll dive into the docs to see how to configure the plugin.

**Comment by Arc-E-Tect** [comment]
Got it to work, next time I will RTFM.

One small suggestion, maybe add on the plugin main page the note on Yarn, it kinda took me by surprise.
