### ISSUE TITLE
False Negatives in Python for tensorflow and scikit-learn due to ECOSYSTEM setup

### ISSUE THREAD

**Issue by MaximilianBlanck** [dependency-check/DependencyCheck#3199]
Hi, 
thank you for developing this great tool, really cool to use it :)
Currently I am checking a [requirements.txt](https://github.com/jeremylong/DependencyCheck/files/6156370/requirements.txt) with dependency-check and found that some python packages (scikit-learn and tensorflow) are not detected correctly because their ECOSYSTEM is set to 'naitve' in the CPEENTRY table.
If I change it manually to 'python' or NULL by connecting to the local 
h2 database, dependency-check maps the cpe correctly and finds corresponding CVEs
I know that python is supported experimentally, but probably it is an easy fix.
![Bildschirmfoto von 2021-03-17 12-58-20](https://user-images.githubusercontent.com/22559508/111464050-985f0780-8720-11eb-91e2-09d53109a4e7.png)
Generated report by dependency-check:
![Bildschirmfoto von 2021-03-17 13-39-58](https://user-images.githubusercontent.com/22559508/111471358-1aebc500-8729-11eb-82b7-912ebb3a0e7a.png)
--> could not map the cpe 

Connecting with `java -jar h2-1.4.199.jar` to the local database `jdbc:h2:dependency-check/data/odc;LOCK_MODE=0;AUTOCOMMIT=ON;CACHE_SIZE=65536;RETENTION_TIME=1000;MAX_COMPACT_TIME=10000;`
and running:
```
UPDATE CPEENTRY SET ECOSYSTEM='python' where product='tensorflow'
UPDATE CPEENTRY SET ECOSYSTEM='python' where product='scikit-learn'
```

Modified the ECOSYSTEM of tensorflow and scikit-learn:
![Bildschirmfoto von 2021-03-17 12-14-19](https://user-images.githubusercontent.com/22559508/111459671-49fb3a00-871b-11eb-8530-c9a1f68fa1e9.png)

Generated report by dependency-check after modifying the ecosystem:
![Bildschirmfoto von 2021-03-17 14-11-39](https://user-images.githubusercontent.com/22559508/111472935-c5181c80-872a-11eb-9a3b-7e6d4234830e.png)
--> is able to map the cpe and finds CVEs

Changing ECOSYSTEMs values is probably not the right way to go, but I thought this is still worth a hint.

Run command (the requirements.txt is in ~/test_project):
`sh dependency-check/bin/dependency-check.sh --project test_project --scan ~/test_project/ --out ~/ --log ~/odc.log --enableExperimental`

Dependency-Check Core version 6.1.2

**Comment by jeremylong** [comment]
Updating the ecosystem might be the correct solution - but it should be updated to MULTIPLE:

```SQL
UPDATE cpeecosystemcache 
SET ecosystem='MULTIPLE'
WHERE vendor='tensorflow' AND product='tensorflow'

UPDATE cpeecosystemcache 
SET ecosystem='MULTIPLE'
WHERE vendor='scikit-learn' AND product='scikit-learn'
```
