### ISSUE TITLE
new --project command line option

### ISSUE THREAD

**Issue by clyderoby** [dependency-check/DependencyCheck#320]
Noticing that the HTML file generated uses "Project:" as the label for the --app command line argument, I propose that there be a synonymous --project command line argument (keeping the --app one for legacy). Also noticing that the "-p" short option is unused (although "-P" is indeed used), the "-p" option can be the short option for --project.

**Comment by jeremylong** [comment]
Thanks for the suggestion. This has been committed to the 1.3.1-SNAPSHOT and will be included in the next release.
