### ISSUE TITLE
Gradle plugin: Dependency is updated in local project and updates transitive but still shows in report

### ISSUE THREAD

**Issue by Grimoren** [dependency-check/DependencyCheck#3200]
**Describe the bug**
Example:

I have a jar from a project that uses spring-web:3.0.2.RELEASE
I updated the version in my project to 5.3.4  but the 3.0.2.RELEASE version still shows on the report 

this is a clip from gradle dependencies
org.springframework:spring-web:3.0.2.RELEASE -> 5.3.4

**Version of dependency-check used**
The problem occurs using version: 6.1.2 of the gradle plugin 

**To Reproduce**
1. Use a jar from a project that has a vulnerability
2. Update the vulnerability to a version that does not have the vulnerability
3. Run the report: ./gradlew build dependencyCheckAnalyze
4. Read the report

**Expected behavior**
The old dependency should not show on the report. 

**Additional context**
The only way to workaround this bug is to either force the version in configurations.all or exclude the dependency from the dependency that is transitively pulling it in.

**Comment by jeremylong** [comment]
Unable to reproduce - do you have a sample project?

**Comment by Grimoren** [comment]
It seems this might be because I am using an artifactory or github enterprise. I attempted to reproduce it with an ordinary maven central configuration and a github project (real-world-spring-boot-app) and com.vladrkrava avro-converter 1.0.1 dependency and does not reproduce. 

I am working with enterprise artifactory and github enterprise and it does cause the issue spring-web version-3.0.2-RELEASE shows up . Perhaps I am just missing  some configuration?

**Comment by Grimoren** [comment]
I need to figure out why gradle is downloading 3.0.2 spring version:


     Downloading https://artifacts.apple.com/libs-release/org/springframework/spring-web/3.0.2.RELEASE/spring-web-3.0.2.RELEASE.pom to /tmp/gradle_download6519589228137454576bin
     Downloading https://artifacts.apple.com/libs-release/org/springframework/spring-parent/3.0.2.RELEASE/spring-parent-3.0.2.RELEASE.pom to /tmp/gradle_download4933164210158627099bin
     
     as well as 5.3.4
     
          Downloading https://artifacts.apple.com/libs-release/org/springframework/spring-web/5.3.4/spring-web-5.3.4.pom to /tmp/gradle_download5158030631649272407bin
     Downloading https://artifacts.apple.com/libs-release/org/springframework/spring-web/5.3.4/spring-web-5.3.4.module to /tmp/gradle_download17398314871530525390bin

and 5.0.1 
     Downloading https://artifacts.apple.com/plugins-release/org/springframework/spring-web/5.0.1.RELEASE/spring-web-5.0.1.RELEASE.pom to /tmp/gradle_download14678095863018694679bin
     
     
     while the real-world-spring-app only has 
     
    Cached resource https://artifacts.apple.com/plugins-release/org/springframework/spring-web/5.2.12.RELEASE/spring-web-5.2.12.RELEASE.jar is up-to-date (lastModified: Tue Dec 08 22:34:12 PST 2020).
    
Cached resource https://repo.maven.apache.org/maven2/org/springframework/spring-web/5.3.4/spring-web-5.3.4.pom is up-to-date (lastModified: Tue Feb 16 03:16:48 PST 2021).

**Comment by Grimoren** [comment]
Ok... I located the issue. It seems compile is the culprit. 

Compile has been deprecated for gradle but I still see them on occasion. It seems using implementation on one and compile on another was the true culprit. Either way not an issue if the correct configuration is used.

**Comment by jeremylong** [comment]
Glad you figured it out.
