### ISSUE TITLE
markdown links on database docs not working when pointing to https resources

### ISSUE THREAD

**Issue by sellersj** [dependency-check/DependencyCheck#3202]
**Describe the bug**
On the following page, some of the links don't render properly. The ones linking to
* dbStatements.properties
* dbStatements_h2.properties
https://jeremylong.github.io/DependencyCheck/data/database.html

Needs to be fixed around:
https://github.com/jeremylong/DependencyCheck/blob/main/src/site/markdown/data/database.md.vm#L36

**Version of dependency-check used**
Website version 6.1.2

**Comment by jeremylong** [comment]
Odd - I'm not seeing the described issue. On https://jeremylong.github.io/DependencyCheck/data/database.html - all of the links look and function correctly to me.

**Comment by sellersj** [comment]
This is what I'm seeing. Sorry for the poor highlighting.

![image](https://user-images.githubusercontent.com/4390/111788649-b3ec1e80-8896-11eb-8445-d91e32655db4.png)

**Comment by jeremylong** [comment]
No idea why the markdown wasn't working correctly.  I just updated this to use an anchor tag.

**Comment by jeremylong** [comment]
The site will be updated with the next release.
