### ISSUE TITLE
The Yarn Audit Analyzer has been disabled. Yarn executable was not found.

### ISSUE THREAD

**Issue by ritvikbhawnani** [dependency-check/DependencyCheck#3204]
I have tried running the following commands on my yarn project using my windows machine:
`'...\dependency-check.bat' --project "OWASP" --scan "."`
`'...\dependency-check.bat' --project "OWASP" --scan "." --yarn 'C:\Program Files (x86)\Yarn\bin\yarn'`

It is not able to find the yarn.
I have called `yarn install` in each directory that contains a yarn.lock.

Any advice would be helpful.

Version: 6.1.2

Below is the output from running the following command:
`dependency-check.bat' --project "OWASP" --scan "." --yarn 'C:\Program Files (x86)\Yarn\bin\yarn'`

**Report**
Unable to read yarn audit output.
exception: org.owasp.dependencycheck.exception.InitializationException: Unable to read yarn audit output.
org.owasp.dependencycheck.analyzer.YarnAuditAnalyzer.prepareFileTypeAnalyzer(YarnAuditAnalyzer.java:175)
org.owasp.dependencycheck.analyzer.AbstractFileTypeAnalyzer.prepareAnalyzer(AbstractFileTypeAnalyzer.java:83)
org.owasp.dependencycheck.analyzer.AbstractAnalyzer.prepare(AbstractAnalyzer.java:102)
org.owasp.dependencycheck.Engine.initializeAnalyzer(Engine.java:786)
org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:622)
org.owasp.dependencycheck.App.runScan(App.java:254)
org.owasp.dependencycheck.App.run(App.java:186)
org.owasp.dependencycheck.App.main(App.java:81)

Cannot run program "yarn": CreateProcess error=2, The system cannot find the file specified
cause: java.io.IOException: Cannot run program "yarn": CreateProcess error=2, The system cannot find the file specified
java.lang.ProcessBuilder.start(Unknown Source)
org.owasp.dependencycheck.analyzer.YarnAuditAnalyzer.prepareFileTypeAnalyzer(YarnAuditAnalyzer.java:153)
org.owasp.dependencycheck.analyzer.AbstractFileTypeAnalyzer.prepareAnalyzer(AbstractFileTypeAnalyzer.java:83)
org.owasp.dependencycheck.analyzer.AbstractAnalyzer.prepare(AbstractAnalyzer.java:102)
org.owasp.dependencycheck.Engine.initializeAnalyzer(Engine.java:786)
org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:622)
org.owasp.dependencycheck.App.runScan(App.java:254)
org.owasp.dependencycheck.App.run(App.java:186)
org.owasp.dependencycheck.App.main(App.java:81)

CreateProcess error=2, The system cannot find the file specified
cause: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
java.lang.ProcessImpl.create(Native Method)
java.lang.ProcessImpl.<init>(Unknown Source)
java.lang.ProcessImpl.start(Unknown Source)
java.lang.ProcessBuilder.start(Unknown Source)
org.owasp.dependencycheck.analyzer.YarnAuditAnalyzer.prepareFileTypeAnalyzer(YarnAuditAnalyzer.java:153)
org.owasp.dependencycheck.analyzer.AbstractFileTypeAnalyzer.prepareAnalyzer(AbstractFileTypeAnalyzer.java:83)
org.owasp.dependencycheck.analyzer.AbstractAnalyzer.prepare(AbstractAnalyzer.java:102)
org.owasp.dependencycheck.Engine.initializeAnalyzer(Engine.java:786)
org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:622)
org.owasp.dependencycheck.App.runScan(App.java:254)
org.owasp.dependencycheck.App.run(App.java:186)
org.owasp.dependencycheck.App.main(App.java:81)
...

**Command Line**
[INFO] Analysis Started
[WARN] Exception extracting archive 'cb-never-called-1.0.1.tgz'.
[INFO] Finished Archive Analyzer (0 seconds)
[INFO] Launching: [bundle-audit, version] from C:\Users\Ritvik\AppData\Local\Temp\dctemp972d9ec9-70f8-4654-a779-6ff040032eea
[ERROR] Exception occurred initializing Ruby Bundle Audit Analyzer.
[INFO] Finished File Name Analyzer (0 seconds)
[INFO] Finished Jar Analyzer (0 seconds)
[INFO] Finished Central Analyzer (0 seconds)
[INFO] Finished Assembly Analyzer (1 seconds)
[WARN] No lock file exists - this will result in false negatives; please run `npm install --package-lock`
[WARN] No lock file exists - this will result in false negatives; please run `npm install --package-lock`
[WARN] No lock file exists - this will result in false negatives; please run `npm install --package-lock`
[WARN] No lock file exists - this will result in false negatives; please run `npm install --package-lock`
[WARN] No lock file exists - this will result in false negatives; please run `npm install --package-lock`
[WARN] No lock file exists - this will result in false negatives; please run `npm install --package-lock`
[WARN] No lock file exists - this will result in false negatives; please run `npm install --package-lock`
[WARN] Unable to find node module: C:\Users\Ritvik\Desktop\Comp Sci 699\ondemand\apps\files\lib\cloudcmd\node_modules\chalk\package.json
[WARN] No lock file exists - this will result in false negatives; please run `npm install --package-lock`
[WARN] No lock file exists - this will result in false negatives; please run `npm install --package-lock`
[WARN] No lock file exists - this will result in false negatives; please run `npm install --package-lock`
[WARN] No lock file exists - this will result in false negatives; please run `npm install --package-lock`
[WARN] No lock file exists - this will result in false negatives; please run `npm install --package-lock`
[WARN] Unable to find node module: C:\Users\Ritvik\Desktop\Comp Sci 699\ondemand\apps\files\lib\cloudcmd\node_modules\checkup\package.json
[WARN] Unable to find node module: C:\Users\Ritvik\Desktop\Comp Sci 699\ondemand\apps\files\lib\cloudcmd\node_modules\criton\package.json
...
[WARN] Provided path to `yarn` executable is invalid.
[WARN] The Yarn Audit Analyzer has been disabled. Yarn executable was not found.
[ERROR] Exception occurred initializing Yarn Audit Analyzer.
...

**Comment by jeremylong** [comment]
try 

`dependency-check.bat' --project "OWASP" --scan "." --yarn 'C:\Program Files (x86)\Yarn\bin\yarn' --log odc.log`

At the top of the log it will print out the properties (likely twice) - check to validate that the path to yarn is correctly being passed in. Also, as I don't have a windows system handy is the executable `yarn`, `yarn.exe`, or something else?

**Comment by ritvikbhawnani** [comment]
Thank you. It looks like the executable is `yarn.cmd`
I was able to resolve the issue by calling the following instead:

`dependency-check.bat' --project "OWASP" --scan "." --yarn 'C:\Program Files (x86)\Yarn\bin\yarn.cmd'`

I'm not sure if it is appropriate to ask a follow-up question here, but should the report contain the same results as running `yarn audit` in each directory? The current report feels a little sparse than I expected it to be.

**Comment by jeremylong** [comment]
In theory - yes, it should be very similar to just running `yarn audit`. Note, that if multiple projects have the same vulnerable dependency it will be collapsed into a single entry in the ODC report.  If you are seeing differences please open a new ticket.

**Comment by ritvikbhawnani** [comment]
Will do. Thanks again.
