### ISSUE TITLE
Gradle plugin compiled with Java 1.8

### ISSUE THREAD

**Issue by apbuteau** [dependency-check/DependencyCheck#321]
I'm trying to use the plugin made available through Gradle:
`build.gradle`

```
    plugins {
        id "dependency.check" version "0.0.6"
    }
```

But when I try to run it against my Java 1.7 project I get the following:
`java.lang.UnsupportedClassVersionError: com/tools/security/plugin/DependencyCheckGradlePlugin : Unsupported major.minor version 52.0`

I suspect this needs to be compiled with the following:

```
    sourceCompatibility = 1.7
    targetCompatibility = 1.7
```

**Comment by jeremylong** [comment]
`targetCompatibility = 1.7` was added so that the plugin can be used under Java 1.7. The next release of the plugin will be usable in Java 1.7 projects.

Thanks!
