### ISSUE TITLE
6.1.3 is not published to Maven repository

### ISSUE THREAD

**Issue by hodjo** [dependency-check/DependencyCheck#3210]
Hi Jeremy, the version 6.1.3 was released a few minutes ago, but it seems not to be published to the Maven repository (https://mvnrepository.com/artifact/org.owasp/dependency-check-core)

**Comment by sellersj** [comment]
It looks like it typically takes 2 hours for it to show up. It's there now.

**Comment by sellersj** [comment]
https://search.maven.org/search?q=g:org.owasp%20a:dependency-check-core%20v:6.1.3

**Comment by albuch** [comment]
The artifact normally is available for download right after publishing, however search indexing on Maven Central is decoupled from the actual publishing and it takes up to a couple of hours to be visible there.

**Comment by hodjo** [comment]
Ok, thanks for your feedback. For a few hours after publishing, it was not available for our CI build too. By now the build succeeds, so I am going to close this issue.
