### ISSUE TITLE
NPE on CPE check on older artifact with non-standard version with dependency check 6.1.3

### ISSUE THREAD

**Issue by sellersj** [dependency-check/DependencyCheck#3212]
**Describe the bug**
When using an older artifact, I get a null pointer exception
```
<dependency>
  <groupId>strutstestcase</groupId>
  <artifactId>strutstestcase</artifactId>
  <version>2.1.4-1.2-2.4</version>
</dependency>
```

**Version of dependency-check used**
6.1.3 of the maven plugin using command
```
 org.owasp:dependency-check-maven:6.1.3:check org.owasp:dependency-check-maven:6.1.3:aggregate -Dformat=ALL -DskipProvidedScope=true -DautoUpdate=false -DnuspecAnalyzerEnabled=false -DassemblyAnalyzerEnabled=false -DnodeAuditAnalyzerEnabled=false -DnodeAnalyzerEnabled=false -DrubygemsAnalyzerEnabled=false -DbundleAuditAnalyzerEnabled=false
```

**Log file**
https://gist.github.com/sellersj/79729bde90105069d3265227b36822c6

**To Reproduce**
Add the strutstestcase to your project and see the error when running the report

**Expected behavior**
The error not to happen

**Additional context**
n/a

**Comment by kkovaletp** [comment]
Maybe this bug is describing same root issue as https://github.com/jeremylong/DependencyCheck/issues/3214 one
