### ISSUE TITLE
False Positive on tagsoup-1.2.1.jar

### ISSUE THREAD

**Issue by jmaharramzade** [dependency-check/DependencyCheck#3215]
False positive on library `tagsoup-1.2.1.jar` - reported as `cpe:2.3:a:tag_project:tag:1.2.1:*:*:*:*:*:*:*`
```xml
<dependency>
    <groupId>org.ccil.cowan.tagsoup</groupId>
    <artifactId>tagsoup</artifactId>
    <version>1.2.1</version>
</dependency>
```

**Comment by aikebah** [comment]
What version of DependencyCheck do you use? Cannot reproduce with 6.1.3

**Comment by jmaharramzade** [comment]
Apologies, the plugin version was behind. Verified with v6.1.3 and no issue. Thanks a lot for looking into this, and sorry for the false flag.
