### ISSUE TITLE
Blocker (regression in 6.1.2): "Unable to find method 'com.google.common.collect.ImmutableList.toImmutableList()Ljava/util/stream/Collector;'"

### ISSUE THREAD

**Issue by alwa** [dependency-check/DependencyCheck#3221]
**Describe the bug**
Cannot evaluate Gradle project. My project uses Android Gradle Plugin version 4.1.2, Gradle version 6.8.3 and Jdk version 11.

**Version of dependency-check used**
The problem occurs using version 6.1.2 (and 6.1.3) of the gradle plugin. It works fine in 6.1.1 and below.

**Log file**
```
Unable to find method 'com.google.common.collect.ImmutableList.toImmutableList()Ljava/util/stream/Collector;'
com.google.common.collect.ImmutableList.toImmutableList()Ljava/util/stream/Collector;
```

**Comment by jeremylong** [comment]
Looks like a dependency conflict in your build environment. No where in ODC is toImmutableList() called: https://github.com/jeremylong/DependencyCheck/search?q=toImmutableList

Pretty sure ODC can use Guava [24.1.1,]

**Comment by alwa** [comment]
Ok thanks. I will investigate on my side.

**Comment by jeremylong** [comment]
In ODC 6.1.4 - I explicitly set the version of Guava to be 24.1.1-jre as opposed to using a version range.

**Comment by alwa** [comment]
I've looked through the gradle dependencies and I don't have any clear conclusion.
I have a transitive dependency to Guava (different version) through a test library called Robolectric but there is apparantly also a (unspecified) direct dependency :

``` 
releaseUnitTestCompileClasspath - Resolved configuration for compilation for variant: releaseUnitTest
...
+--- com.google.guava:guava:{strictly 27.0.1-jre} -> 27.0.1-jre (c)
```

Related:
https://stackoverflow.com/questions/54635950/android-x-truth-guava-test-compile-issue
https://github.com/google/error-prone/issues/528
https://github.com/google/dagger/issues/1700

I have not tried any of the workarounds like adding a direct dependency in my project. It feels like a hack to do so.

**Comment by alwa** [comment]
I've attached the output from my projects dependencies. Note: This is performed using version 6.1.1 of the ODC.

[dependency-tree.txt](https://github.com/jeremylong/DependencyCheck/files/6196763/dependency-tree.txt)

**Comment by alwa** [comment]
I've created a new sample Android project (using the tutorial in Android Studio) and can reproduce the issue easily without adding more code than the reference to the ODC in the plugin section (**build.gradle**):

[MyApplication.zip](https://github.com/jeremylong/DependencyCheck/files/6202621/MyApplication.zip)

To reproduce the issue:
1. Download Android Studio 4.1.3, https://developer.android.com/studio
2. In Android Studio: 
- Import attached sample project "MyApplication"
- Choose from dropdown menu: **File** -> **Sync Project with Gradle Files**

Expected:
Project resolved OK

Actual:
Error:
```
Unable to find method 'com.google.common.collect.ImmutableList.toImmutableList()Ljava/util/stream/Collector;'
com.google.common.collect.ImmutableList.toImmutableList()Ljava/util/stream/Collector;
```

**Comment by jeremylong** [comment]
@alwa One solution is to strictly enforce the use of Guava 28.1-jre:

```groovy
buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath('com.google.guava:guava'){
            version {
                strictly '28.1-jre'
            }
        }
        classpath "com.android.tools.build:gradle:4.1.3"
        classpath("org.owasp:dependency-check-gradle:6.1.3") 
    }
}
```

**Comment by alwa** [comment]
@jeremylong this ticket looks like a duplicate of https://github.com/dependency-check/dependency-check-gradle/issues/213
I'll proceed and close this one if you agree.

As for the provided workaround I don't think it's very appealing to leak dependency information but I guess you had your reasons to enforce strictness on Guava and that there is no way to prevent this from leaking?

**Comment by jeremylong** [comment]
I just bumped guava to `30.1.1-jre` via f861019c9 and retested with your sample project and everything works.
