### ISSUE TITLE
False Positive on kotlin-stdlib-1.4.30.jar

### ISSUE THREAD

**Issue by dingo15** [dependency-check/DependencyCheck#3227]
False positive on library kotlin-stdlib-1.4.30.jar - reported as cpe:2.3:a:jetbrains:kotlin:1.4.0:milestone1::::::
```xml
<dependency>
    <groupId>org.jetbrains.kotlin</groupId>
    <artifactId>kotlin-stdlib</artifactId>
    <version>1.4.30</version>
</dependency>

```

**Comment by aikebah** [comment]
What version of DependencyCheck do you use? Cannot reproduce it with Maven Plugin / DC 6.1.5

**Comment by aikebah** [comment]
Manage to reproduce with gradle plugin

**Comment by aikebah** [comment]
Is essentially a duplicate of #3133, follow up for fix in there
