### ISSUE TITLE
JsonArrayFixingInputStream produces broken output on certain repositories

### ISSUE THREAD

**Issue by rofafor** [dependency-check/DependencyCheck#3232]
**Describe the bug**
JsonArrayFixingInputStream produces broken output on certain repositories.

**Version of dependency-check used**
The problem occurs using version 6.1.3 of the cli. The older release 6.1.2 is working.

**Log file**
```
2021-03-26 18:19:35,948 org.owasp.dependencycheck.App:208
ERROR - Unexpected exit code from go process; exit code: 141
2021-03-26 18:19:35,949 org.owasp.dependencycheck.App:209
DEBUG - unexpected error
org.owasp.dependencycheck.analyzer.exception.AnalysisException: Unexpected exit code from go process; exit code: 141
        at org.owasp.dependencycheck.analyzer.GolangModAnalyzer.analyzeDependency(GolangModAnalyzer.java:295)
        at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
        Suppressed: org.owasp.dependencycheck.analyzer.exception.AnalysisException: Error parsing stream
                at org.owasp.dependencycheck.data.golang.GoModJsonParser.process(GoModJsonParser.java:86)
                at org.owasp.dependencycheck.processing.GoModProcessor.run(GoModProcessor.java:62)
                ... 1 common frames omitted
        Caused by: javax.json.stream.JsonParsingException: Invalid token=COLON at (line no=979, column no=8, offset=36995). Expected tokens are: [COMMA]
                at org.glassfish.json.JsonParserImpl.parsingException(JsonParserImpl.java:450)
                at org.glassfish.json.JsonParserImpl.access$1100(JsonParserImpl.java:79)
                at org.glassfish.json.JsonParserImpl$ArrayContext.getNextEvent(JsonParserImpl.java:557)
                at org.glassfish.json.JsonParserImpl.next(JsonParserImpl.java:376)
                at org.glassfish.json.JsonParserImpl.getArray(JsonParserImpl.java:324)
                at org.glassfish.json.JsonParserImpl.getArray(JsonParserImpl.java:164)
                at org.glassfish.json.JsonReaderImpl.readArray(JsonReaderImpl.java:129)
                at org.owasp.dependencycheck.data.golang.GoModJsonParser.process(GoModJsonParser.java:71)
                ... 2 common frames omitted
```

**To Reproduce**
1. `dependency-check -l scan.log --scan go.mod`
2. See error in log

**Expected behavior**
Successful execution.

**Additional context**
As a quick fix I increased the buffer size and I'm able to execute the scanner succesfully (based on git commit b1bbc4469): 
```
diff --git a/utils/src/main/java/org/owasp/dependencycheck/utils/JsonArrayFixingInputStream.java b/utils/src/main/java/org/owasp/dependencycheck/utils/JsonArrayFixingInputStream.java
index c0b253a69..b2a367a48 100644
--- a/utils/src/main/java/org/owasp/dependencycheck/utils/JsonArrayFixingInputStream.java
+++ b/utils/src/main/java/org/owasp/dependencycheck/utils/JsonArrayFixingInputStream.java
@@ -49,7 +49,7 @@ public class JsonArrayFixingInputStream extends InputStream {
     /**
      * The buffer length.
      */
-    private static final int BUFFER_SIZE = 2048;
+    private static final int BUFFER_SIZE = 8192;
     /**
      * The input stream to be filtered.
      */
```

**Comment by rofafor** [comment]
You can find a sample and test case I'm using here: https://gist.github.com/rofafor/e3858789caecb7c5fbb92efd1fb2989b

This one fails on both default 2k and 8k buffer sizes, but works with 16k :)

**Comment by jeremylong** [comment]
It would be so nice if go actually output correctly formatted JSON... It shouldn't be that hard for them to add commas appropriately....

**Comment by benjsmi** [comment]
Yes, I'm seeing the same problem. Any way to do this without modifying dependency-check source code?

**Comment by benjsmi** [comment]
Yes, I'm seeing the same problem. Any way to do this without modifying dependency-check source code? I guess this would just be because there happens to be a delimiter right on the border/end/beginning of the buffer and that confuses the JSON parser. Ugh that's a tricky one.   It is also _intermittent_.  I was having this issue and then just happened to run it again to check something else and this time it worked like a charm.

**Comment by davidandradeduarte** [comment]
Having the same issue here too:

```
Unexpected exit code from go process; exit code: 141
exception: org.owasp.dependencycheck.analyzer.exception.AnalysisException: Unexpected exit code from go process; exit code: 141
org.owasp.dependencycheck.analyzer.GolangModAnalyzer.analyzeDependency(GolangModAnalyzer.java:297)
org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
java.base/java.lang.Thread.run(Thread.java:831)
```

If I reduce the number of dependencies it eventually runs successfully. I know go is currently in experimental mode but it's mostly unusable.

**Comment by jeremylong** [comment]
What would likely help the most is if someone could open a ticket with GoLang asking that the command below would produces valid JSON:

```shell
go list -json -m -mod=readonly all
```

It currently does not correctly output parsable json:

```json
{
	"Path": "golang.org/x/net",
	"Version": "v0.0.0-20190404232315-eb5bcb51f2a3",
	"Time": "2019-04-04T23:23:15Z",
	"Indirect": true,
	"GoMod": "/Users/jeremy/go/pkg/mod/cache/download/golang.org/x/net/@v/v0.0.0-20190404232315-eb5bcb51f2a3.mod"
}
{
	"Path": "golang.org/x/sys",
	"Version": "v0.0.0-20190412213103-97732733099d",
	"Time": "2019-04-12T21:31:03Z",
	"Indirect": true,
	"GoMod": "/Users/jeremy/go/pkg/mod/cache/download/golang.org/x/sys/@v/v0.0.0-20190412213103-97732733099d.mod",
	"GoVersion": "1.12"
}
{
	"Path": "golang.org/x/text",
	"Version": "v0.3.0",
	"Time": "2017-12-14T13:08:43Z",
	"Indirect": true,
	"GoMod": "/Users/jeremy/go/pkg/mod/cache/download/golang.org/x/text/@v/v0.3.0.mod"
}
```

Note that this does not have commas nor does it have brackets indicating it is an array. Maybe I'm missing something - but this isn't valid json.

**Comment by davidandradeduarte** [comment]
HI @jeremylong, thanks for the reply!

I believe someone pointed this a few years ago, but I don't think they'll change it tbh:
https://github.com/golang/go/issues/27655

It's intended to be a stream of JSON objects instead of a valid json array.

**Comment by jeremylong** [comment]
Pretty sure I found the issue. When I tested against https://github.com/kubernetes/kubernetes. What I found is that there are several `go.mod` files in the `vendor`, `staging`, and `cluster` directories. As dependency-check currently scans the entire directory structure for dependencies - it ends up trying to run `go list -json -m -mod=readonly all` against all of the various `go.mod` files:

```shell
~/Projects/kubernetes/vendor/github.com/russross/blackfriday/v2
$ go list -json -m -mod=readonly all                                                                                       
go: updates to go.mod needed, disabled by -mod=readonly
```

I'm guessing we should skip running this against `go.mod` files in the vendor directory?


BTW - I was able to succesfully run ODC against the go.mod file by running:

```shell
$ dependency-check.sh -o . -s ./go.mod --enableExperimental 
```

In this case it only runs against the single `go.mod` file.

**Comment by davidandradeduarte** [comment]
The repository I'm testing only has one `go.mod` with about 18 dependencies, so I don't think it has something to do with `vendor` folders or multiple `go.mod` files (at least in my case - it can be a different issue). 

Tried
```bash
dependency-check -o . -s ./go.mod --enableExperimental 
```
and errors with
```bash
Unexpected exit code from go process; exit code: 141
exception: org.owasp.dependencycheck.analyzer.exception.AnalysisException: Unexpected exit code from go process; exit code: 141
org.owasp.dependencycheck.analyzer.GolangModAnalyzer.analyzeDependency(GolangModAnalyzer.java:297)
org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
java.base/java.lang.Thread.run(Thread.java:831)
```

I'm running 6.2.2 (latest by the time of writing).

**Comment by jeremylong** [comment]
With #3599 the primary bug has been resolved. In addition we have improved the error reporting so that if an error occurs analyzing a go.mod in the vendor directory you will be able to tell (i.e. we are better about including the file path in the error message). I'm still debating whether or not we should completely skip any go.mod in the vendor directory...
