### ISSUE TITLE
Add support for npm-shrinkwrap.json files

### ISSUE THREAD

**Issue by dwvisser** [dependency-check/DependencyCheck#324]
In writing documentation for the new Node.js analyzer, I added a link to [nsp](https://nodesecurity.io/tools). Reading that page, I noticed that nsp also handles a thing called a [NPM shrinkwrap file](http://blog.nodejs.org/2012/02/27/managing-node-js-dependencies-with-shrinkwrap/), which seems akin to a Ruby Bundler `Gemfile.lock` file. It might be straightforward to extend D-C analysis to these files.

**Comment by paul-enz** [comment]
@jeremylong Any sign of shrinkwrap being supported? When DependencyCheck finds vulnerabilities in nested dependencies the only course of action in npm is to override them with shrinkwrap. (Unless you have come across another way?) Currently DependencyCheck doesn't support shrinkwraps and therefore continues to fail the tests. This is huge, and a major blocker to continued usage of DependencyCheck.

**Comment by jeremylong** [comment]
This was recently merged into the master branch (see https://github.com/jeremylong/DependencyCheck/pull/1006). We have not yet performed a release with this update yet; I'm hoping in about 1 week.

**Comment by paul-enz** [comment]
Great work, looking forward to the release! Thank you.
