### ISSUE TITLE
NullPointerException while scanning cvsclient-71-jenkins-11.jar

### ISSUE THREAD

**Issue by wagde-orca** [dependency-check/DependencyCheck#3240]
**Describe the bug**
scanning cvsclient-71-jenkins-11.jar file withe the latest 6.1.3 causes java.lang.NullPointerException: null

**Version of dependency-check used**
cli 6.1.3

**Log file**
https://gist.github.com/wagde-orca/ebb3d217dc9ba5f270f2b6d36a0deb10

**To Reproduce**
1. mkdir jar_dir
2. cp cvsclient-71-jenkins-11.jar jar_dir
3. ./bin/dependency-check.sh -s jar_dir

**Expected behavior**
the scan will finish successfully

**Additional context**
This bug does not occur in the previous version I used 5.2.4

**Comment by wagde-orca** [comment]
Thanx @jeremylong
Any ETA for 6.1.4?

**Comment by jeremylong** [comment]
should be within 30 minutes... However, what appears to be a random failure already occurred once - so that may delay the release until tomorrow.

**Comment by jeremylong** [comment]
https://github.com/jeremylong/DependencyCheck/actions/workflows/release.yml

**Comment by wagde-orca** [comment]
@jeremylong I still get the same error with 6.1.4 :-(
