### ISSUE TITLE
NullPointerException while scanning com.android.tools.build 

### ISSUE THREAD

**Issue by jitendra93** [dependency-check/DependencyCheck#3245]
**Describe the bug**
scanning com.android.tools.build with the latest 6.1.4 causes NullPointerException. 
com.android.tools.build uses com.google.errorprone and scanning that library throws NPE. 

**Version of dependency-check used**
The problem occurs using version 6.12, 6.1.3 and 6.1.4 of the gradle plugin.

**Log file**
https://gist.github.com/jitendra93/978a9e44e34653708a0ee6e3155095db

**To Reproduce**
1. Create an android project
2. Add this to classpath in root build.gradle.         "classpath("com.android.tools.build:gradle:4.1.1")"

**Expected behavior**
Scan should finish successfully

**Comment by jeremylong** [comment]
Fixed per #3246. I will release 6.1.5 shortly.
