### ISSUE TITLE
NullPointerException while scanning cvsclient-71-jenkins-11.jar

### ISSUE THREAD

**Issue by wagde-orca** [dependency-check/DependencyCheck#3246]
I could not find how to open a closed issue... so this is the link for the original issue opened for 6.1.3... and it still reproduces on 6.1.4
https://github.com/jeremylong/DependencyCheck/issues/3240

this is the error log from 6.1.4
https://gist.github.com/wagde-orca/63cb4aae1df637081c5facb23fdc84c2

**Comment by jeremylong** [comment]
Sorry about testing in your environment.... Apparently there was a second NPE that needed to be fixed.  I've added a regression test case as well as a fix for the NPE.

I'll release 6.1.5 shortly.
