### ISSUE TITLE
java.lang.IllegalStateException on execution from other than c:\

### ISSUE THREAD

**Issue by Kalgar1981** [dependency-check/DependencyCheck#3247]
When launching the scan from other path different than root path in WIndows (C:\), java.lang.IllegalStateException appears stating that the scan path does not exist.

C:\WINDOWS\system32>"C:\Proyectos\SBOM Generator\SBOM Generator\bin\Release\tools\dependency-check\bin\dependency-check.bat" -s "C:\BIDS XT 2" -f XML -o "C:\Proyectos\SBOM Generator\SBOM Generator\bin\Release\temp\temp.xml"
Exception in thread "main" java.lang.IllegalStateException: basedir C:BIDS XT 2 does not exist.
        at org.apache.tools.ant.DirectoryScanner.scan(DirectoryScanner.java:886)
        at org.owasp.dependencycheck.App.scanAntStylePaths(App.java:351)
        at org.owasp.dependencycheck.App.runScan(App.java:247)
        at org.owasp.dependencycheck.App.run(App.java:186)
        at org.owasp.dependencycheck.App.main(App.java:81)

If the same command is launched from c:\ it works with no problem.

C:\>"C:\Proyectos\SBOM Generator\SBOM Generator\bin\Release\tools\dependency-check\bin\dependency-check.bat" -s "C:\BIDS XT 2" -f XML -o "C:\Proyectos\SBOM Generator\SBOM Generator\bin\Release\temp\temp.xml"
[INFO] Checking for updates
[INFO] Skipping NVD check since last check was within 4 hours.
[INFO] Skipping RetireJS update since last update was within 24 hours.
[INFO] Check for updates complete (241 ms)

dependency-check cli v6.1.4, Windows 10 1809

**Comment by jeremylong** [comment]
Looks like we might be processing the backslash as an escape sequence...  I don't have a windows system handy.  Can you try this using forward slashes instead of backslashes in the paths?

**Comment by jim-liu** [comment]
I wasn't able to reproduce this with v6.1.4 on Windows 10 2004 with OpenJDK 8. Here's the command I tried:

`C:\Windows\System32>"C:\Test Tools\dependency-check\bin\dependency-check.bat" -s "C:\Test Files\ant-sample-master" -f XML -o "C:\Test Report\Report.xml"`

If you have Windows 10 2004 handy, perhaps giving it a try.

**Comment by Kalgar1981** [comment]
Seems that the probkem vwas the JAVA version I was using. I have modified the BAT file to use the correct JAVA instance and now it seems to work.

With Java 1.8 (I know it is very old, but computer is connected to enterprise apps and needs that version) it throws the error, and with OpenJDK 12 it works with no problem.

**Comment by tasbin** [comment]
i had same issue on windows today with dependency-check-6.5.3-release. Workaround was different in my case If you launch it for the same folder, this issue appears. Issue disappear if you launch from a parent folder
