### ISSUE TITLE
java.lang.NullPointerException while scanning a dependency with org.owasp.dependencycheck 6.1.4

### ISSUE THREAD

**Issue by abhisheksr01** [dependency-check/DependencyCheck#3248]
Still getting the NPE for **pitest (0.14)** as reported earlier even after updating **dependencycheck to 6.1.4**.

Link to previous issue reported:
https://github.com/jeremylong/DependencyCheck/issues/3235

**Comment by jeremylong** [comment]
Fixed per #3246. I will release 6.1.5 shortly.
