### ISSUE TITLE
dependency-check fails to read content of Package.swift 

### ISSUE THREAD

**Issue by JuhaO81** [dependency-check/DependencyCheck#3252]
Background:
We have many libraries that do include other libraries in them. These are listed in Package.swift. For example take a look firebase Package.swift.
https://github.com/firebase/firebase-ios-sdk/blob/master/Package.swift

Issue: Dependency check fails to check these dependencies and therefore fails to check many dependencies actually used in projects.

Scan was run like this in root of our project
dependency-check --enableExperimental -s .

**Comment by JuhaO81** [comment]
@jeremylong I can see this pr went in. Did it fix the issue? Wanted to try but there is no release yet with this change. Any plans for next release?
https://github.com/jeremylong/DependencyCheck/pull/3443

**Comment by JuhaO81** [comment]
Tested with release 6.3.0 and result is still the same. @jeremylong

**Comment by JuhaO81** [comment]
Noticed that analyzer.swift.package.resolved.enabled=true is missing from dependencycheck.properties. Is there plans to enable it? 

PS
Took the project down, added this config and managed to compile the project but have some run time issues so not able to test my self.

**Comment by jeremylong** [comment]
We accept PRs!

**Comment by JuhaO81** [comment]
Good to know! Lets see what we can do here :)

**Comment by JuhaO81** [comment]
Works with latest. Closing the ticket
