### ISSUE TITLE
False Positive on netty-tcnative-boringssl-static

### ISSUE THREAD

**Issue by amergey** [dependency-check/DependencyCheck#3254]
False positive on library  io.netty.tcnative-boringssl-static_2.0.36.Final.jar - reported as cpe:2.3:a:netty:netty:2.0.36:*:*:*:*:*:*:*
```xml
<dependency>
    <groupId>io.netty</groupId>
    <artifactId>netty-tcnative-boringssl-static</artifactId>
    <version>2.0.36.Final</version>
</dependency>
```

It is a false positive according to https://github.com/netty/netty-tcnative/issues/442

**Comment by nhumblot** [comment]
Hello,

I'm not getting any alert with this dependency when using the latest version (`6.1.5`) of dependency-check. Which version are you using? If I'm lowering the dependency-check version number (tested with `6.1.5`, `6.1.0`, `6.0.0`, `5.3.0`, `5.2.3`, `5.2.2`, `5.2.0`), I start getting the alert with the `5.2.2` version.

This looks to be related with #1573.

There is a suppression rule already registered:
```
    <suppress base="true">
        <notes><![CDATA[
        Suppresses false positives per #1573.
        ]]></notes>
        <gav regex="true">^io\.netty:netty-tcnative-boringssl-static:.*$</gav>
        <cpe regex="true">^cpe:/a:netty(_project)?:netty.*$</cpe>
    </suppress>
```

Last change about this suppression rule is done by commit ec8526d420fe35aa7467535c6922033a905b4b0e

This has been fixed by #2227 released in `5.2.3`.

**Comment by amergey** [comment]
On my side I confirm this is with 6.1.5 I have this false positive reported:
![image](https://user-images.githubusercontent.com/956840/113817164-2e151200-9776-11eb-915a-2eb16f076f5f.png)

**Comment by nhumblot** [comment]
Hello,

I tried to create a minimal working example but I cannot raise the vulnerability.

You will find it here: https://github.com/nhumblot/owasp-dependency-check-test-directory/tree/netty-tcnative-boringssl-static/dependency-check-maven-sample

The pom only import `netty-tcnative-boringssl-static`. I generated `maven_log` by executing the command `mvn clean verify -B -DskipTests > maven_log`. I also added the generated `dependency-check-report.html` file which show no vulnerable dependency.

Are you able to share more data about your configuration or the state of your project that might help me trigger the vulnerability?

Kind regards

**Comment by amergey** [comment]
I will try to provide a simple working example. 

What I can tell now is this issues is raised while scanning the zip of our product containing this jar.

**Comment by amergey** [comment]
So if I launch command line tool by hand scanning a directory with the jar it gives me the vulnerability

![image](https://user-images.githubusercontent.com/956840/114021867-71a07680-9871-11eb-9f69-aa901dc4f3dc.png)

with proposed suppress rule
`<suppress>
   <notes><![CDATA[
   file name: io.netty.tcnative-boringssl-static_2.0.36.Final.jar
   ]]></notes>
   <sha1>06fbf4f302d9f8d0e28ed19d99673e8b8ceff961</sha1>
   <cpe>cpe:/a:netty:netty</cpe>
</suppress>`

It seems lot of false positive are reported from scanning jar using command-line tool, is it considered as a false positive that should be reported here ?

**Comment by amergey** [comment]
By the way using the command line tool scanning jars it reports also vulnerability for io.grpc.netty while it is supposed to be fixed 
(https://github.com/jeremylong/DependencyCheck/issues/2313)
io.grpc.netty_1.37.0.jar reported as cpe:2.3:a:netty:netty:1.37.0:*:*:*:*:*:*:* are there any limitations with command line tool related to vulnerability detection

**Comment by aikebah** [comment]
@amergey I presume this FP is a similar case to #3347? So also a jar file from Maven Central getting osgified by Tycho?
