### ISSUE TITLE
Microsoft.Build.Tasks.CodeAnalysis.dll vulnerability

### ISSUE THREAD

**Issue by shaimaj** [dependency-check/DependencyCheck#3260]
Hello,

I worked on my 1st project and got Dependency check report, shows that (Microsoft.Build.Tasks.CodeAnalysis.dll) as vulnerability.

I am not expert in security related issues, will removing this file will help fix this vulnerability?
Or what should I do to fix it?

**Comment by jeremylong** [comment]
I don't know what CVEs were reported. There is a good change that this is a false positive. I would suggest reading:

https://jeremylong.github.io/DependencyCheck/general/internals.html
https://jeremylong.github.io/DependencyCheck/general/thereport.html
https://jeremylong.github.io/DependencyCheck/general/suppression.html
