### ISSUE TITLE
The stage of Archive Analyzer takes a lot of time

### ISSUE THREAD

**Issue by j0ck66** [dependency-check/DependencyCheck#3264]
Hello,
I have a question for you,why does the archive analyzer take so long?The File size is only 40M.

[The Log]
[INFO] Analysis Started
[INFO] Finished Archive Analyzer (1529 seconds)
[INFO] Finished File Name Analyzer (0 seconds)
[INFO] Finished Jar Analyzer (0 seconds)

**Comment by jeremylong** [comment]
Depending on what is inside the zip - I could see this happening. For instance, if you had the JavaScript analyzer enabled and there was a ton of JS inside the zip. Another one may be if the zip file itself contained several zip files. However, I agree that the archive analyzer could be improved.
