### ISSUE TITLE
`yarn` executable is not detected by DependencyCheck even though it is installed and available in path

### ISSUE THREAD

**Issue by manojVivek** [dependency-check/DependencyCheck#3275]
**Describe the bug**
Dependency-Check fails to run `YarnAuditAnalyzer` with `The Yarn Audit Analyzer has been disabled. Yarn executable was not found.` warning. I have even tried running the process with `--yarn` argument with absolute path of `yarn`. 

**Version of dependency-check used**
The problem occurs using version 6.1.5 of the cli.

**Expected behavior**
`YarnAuditAnalyzer` is run when `yarn` is available in PATH.

**Comment by jeremylong** [comment]
When adding `--yarn path/to/yarn` are you including the file extension?  if you add `--log odc.log` it will print out near the top all of the loaded properties. You can validate what path is being used by reviewing the log.

**Comment by manojVivek** [comment]
@jeremylong Thanks for the prompt reply. I tried both `/usr/bin/yarn` and `/usr/lib/node_modules/yarn/bin/yarn.js` values for that argument. 

And found something strange on the debug logs. For both the values, I can see these values, the `analyzer.yarn.path` is getting initialized as  `/usr/bin/yarn`. 


```
2021-04-12 09:22:41,496 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: analyzer.yarn.path='/usr/bin/yarn'
...
...
2021-04-12 09:24:05,322 org.owasp.dependencycheck.analyzer.YarnAuditAnalyzer:151
DEBUG - Launching: [/usr/bin/yarn, --help]
2021-04-12 09:24:05,488 org.owasp.dependencycheck.analyzer.YarnAuditAnalyzer:168
WARN  - The Yarn Audit Analyzer has been disabled. Yarn executable was not found.
```

Any idea why?

**Comment by manojVivek** [comment]
@jeremylong Thanks for the prompt reply. I tried both `/usr/bin/yarn` and `/usr/lib/node_modules/yarn/bin/yarn.js` values for that argument. 

For both the values, the same error is thrown. Attaching the corresponding logs below:

`/usr/bin/yarn` log:
```
2021-04-12 09:22:41,496 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: analyzer.yarn.path='/usr/bin/yarn'
...
...
2021-04-12 09:24:05,322 org.owasp.dependencycheck.analyzer.YarnAuditAnalyzer:151
DEBUG - Launching: [/usr/bin/yarn, --help]
2021-04-12 09:24:05,488 org.owasp.dependencycheck.analyzer.YarnAuditAnalyzer:168
WARN  - The Yarn Audit Analyzer has been disabled. Yarn executable was not found.
```

`/usr/lib/node_modules/yarn/bin/yarn.js` log:
```
2021-04-13 01:32:19,440 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: analyzer.yarn.path='/usr/lib/node_modules/yarn/bin/yarn.js'
...
...
2021-04-13 01:35:09,143 org.owasp.dependencycheck.analyzer.YarnAuditAnalyzer:151
DEBUG - Launching: [/usr/lib/node_modules/yarn/bin/yarn.js, --help]
2021-04-13 01:35:09,314 org.owasp.dependencycheck.analyzer.YarnAuditAnalyzer:168
WARN  - The Yarn Audit Analyzer has been disabled. Yarn executable was not found.
```


Any idea on what could be wrong?

**Comment by jeremylong** [comment]
Have you tried:
```shell
$ which yarn
/usr/local/bin/yarn
```

To ensure you have the correct path?

**Comment by manojVivek** [comment]
Yes, I did that as well. :) 

Jenkins log:
```
[Pipeline] sh
+ which yarn
/usr/bin/yarn
```

**Comment by jeremylong** [comment]
As I am not sure what is going on... Maybe try:

```
[Pipeline] sh
+ /usr/bin/yarn --help
```

Is there an error reported by yarn itself?

**Comment by manojVivek** [comment]
@jeremylong Thanks for the help, there was a problem with `.npmrc`. Fixing that resolved it.
