### ISSUE TITLE
Dependency-check v6.1.5: Fatal errors seen during analysis

### ISSUE THREAD

**Issue by Anshu2405** [dependency-check/DependencyCheck#3277]
**Describe the bug**
Run is failing during Dependency-check v6.1.5 cli run. Some errors could be seen during JAR analysis but its failing during Retire.js analysis.

**Version of dependency-check used**
6.1.5 & 6.0.3

**Log file**
[INFO] 

Dependency-Check is an open source tool performing a best effort analysis of 3rd party dependencies; false positives and false negatives may exist in the analysis performed by the tool. Use of the tool and the reporting provided constitutes acceptance for use in an AS IS condition, and there are NO warranties, implied or otherwise, with regard to the analysis or its use. Any use of the tool and the reporting provided is at the userâ€™s risk. In no event shall the copyright holder or OWASP be held liable for any damages whatsoever arising out of or in connection with the use of this tool, the analysis performed, or the resulting report.

[INFO] Analysis Started
[INFO] Finished Archive Analyzer (30 seconds)
[INFO] Finished File Name Analyzer (0 seconds)
[Fatal Error] :42:21: Attribute name "w" associated with an element type "name2" must be followed by the ' = ' character.
[Fatal Error] :21:21: Attribute name "w" associated with an element type "name2" must be followed by the ' = ' character.
[Fatal Error] :61:21: Attribute name "w" associated with an element type "name2" must be followed by the ' = ' character.
[WARN] Unable to parse pom '/tmp/dctemp71998a05-c904-4643-b427-da72d87303b1/check5454381280976307431tmp/110/pom.xml'
[WARN] An error occurred while analyzing '/tmp/dctemp71998a05-c904-4643-b427-da72d87303b1/check8149501183144523036tmp/98/WEB-INF/lib/jakarta.annotation-api-1.3.5.jar'.
[Fatal Error] :46:21: Attribute name "w" associated with an element type "name2" must be followed by the ' = ' character.
[Fatal Error] :40:21: Attribute name "w" associated with an element type "name2" must be followed by the ' = ' character.
[WARN] Unable to parse pom '/tmp/dctemp71998a05-c904-4643-b427-da72d87303b1/check5454381280976307431tmp/121/pom.xml'
[WARN] An error occurred while analyzing '/tmp/dctemp71998a05-c904-4643-b427-da72d87303b1/check8149501183144523036tmp/98/WEB-INF/lib/osgi-resource-locator-1.0.3.jar'.
[Fatal Error] :65:21: Attribute name "w" associated with an element type "name2" must be followed by the ' = ' character.
[WARN] Unable to parse pom '/tmp/dctemp71998a05-c904-4643-b427-da72d87303b1/check5454381280976307431tmp/124/pom.xml'
[WARN] An error occurred while analyzing '/tmp/dctemp71998a05-c904-4643-b427-da72d87303b1/check8149501183144523036tmp/98/WEB-INF/lib/jakarta.ws.rs-api-2.1.6.jar'.
[Fatal Error] :42:21: Attribute name "w" associated with an element type "name2" must be followed by the ' = ' character.
[Fatal Error] :46:21: Attribute name "w" associated with an element type "name2" must be followed by the ' = ' character.
[Fatal Error] :21:21: Attribute name "w" associated with an element type "name2" must be followed by the ' = ' character.
[Fatal Error] :61:21: Attribute name "w" associated with an element type "name2" must be followed by the ' = ' character.
[WARN] Unable to parse pom '/tmp/dctemp71998a05-c904-4643-b427-da72d87303b1/check5454381280976307431tmp/153/pom.xml'
[WARN] An error occurred while analyzing '/tmp/dctemp71998a05-c904-4643-b427-da72d87303b1/check8149501183144523036tmp/142/WEB-INF/lib/jakarta.annotation-api-1.3.5.jar'.
[Fatal Error] :40:21: Attribute name "w" associated with an element type "name2" must be followed by the ' = ' character.
[WARN] Unable to parse pom '/tmp/dctemp71998a05-c904-4643-b427-da72d87303b1/check5454381280976307431tmp/159/pom.xml'
[WARN] An error occurred while analyzing '/tmp/dctemp71998a05-c904-4643-b427-da72d87303b1/check8149501183144523036tmp/142/WEB-INF/lib/osgi-resource-locator-1.0.3.jar'.
[Fatal Error] :65:21: Attribute name "w" associated with an element type "name2" must be followed by the ' = ' character.
[WARN] Unable to parse pom '/tmp/dctemp71998a05-c904-4643-b427-da72d87303b1/check5454381280976307431tmp/155/pom.xml'
[WARN] An error occurred while analyzing '/tmp/dctemp71998a05-c904-4643-b427-da72d87303b1/check8149501183144523036tmp/142/WEB-INF/lib/jakarta.ws.rs-api-2.1.6.jar'.
[INFO] Finished Jar Analyzer (1 seconds)
[ERROR] ----------------------------------------------------
[ERROR] .NET Assembly Analyzer could not be initialized and at least one 'exe' or 'dll' was scanned. The 'dotnet' executable could not be found on the path; either disable the Assembly Analyzer or add the path to dotnet core in the configuration.
[ERROR] ----------------------------------------------------
[INFO] Finished Dependency Merging Analyzer (0 seconds)
[INFO] Finished Version Filter Analyzer (0 seconds)
[INFO] Finished Hint Analyzer (0 seconds)
[INFO] Created CPE Index (2 seconds)
[INFO] Finished CPE Analyzer (4 seconds)
[INFO] Finished False Positive Analyzer (0 seconds)
[INFO] Finished NVD CVE Analyzer (0 seconds)
00:02  INFO: Vulnerability found: jquery below 3.5.0
00:02  INFO: Vulnerability found: jquery below 3.5.0
00:09  INFO: Vulnerability found: jquery below 3.4.0
00:09  INFO: Vulnerability found: jquery below 3.5.0
00:09  INFO: Vulnerability found: jquery below 3.5.0
00:10  INFO: Vulnerability found: jquery below 3.5.0
00:10  INFO: Vulnerability found: jquery below 3.5.0
00:12  INFO: Vulnerability found: jquery below 3.5.0
00:12  INFO: Vulnerability found: jquery below 3.5.0
00:14  INFO: Vulnerability found: knockout below 3.5.0-beta
00:19  INFO: Vulnerability found: jquery below 3.5.0
00:19  INFO: Vulnerability found: jquery below 3.5.0
[ERROR] Analysis task was cancelled.
[ERROR] One or more fatal errors occurred

**Expected behavior**
Analysis should be completed without failure.

**Comment by ahanwate** [comment]
Facing same issue

**Comment by jeremylong** [comment]
I'm unable to reproduce the issue. Do you have a sample project? Maybe the full log as suggested by the issue template?
