### ISSUE TITLE
Option to force database rebuild

### ISSUE THREAD

**Issue by awhitford** [dependency-check/DependencyCheck#328]
I recently ran into a problem where the local database was corrupted...  (I don't know how that happened, but...)  I had to manually drop the `dependency-check-data` folder and then re-initiate a `check` (or call `update-only`).

It would be great if there was a goal like `drop` or `purge` that would reset the local database.

Alternatively, an option that automatically dropped/purged upon hitting a database connection problem could be useful to add to the `check` and `aggregate` goals.  (Obviously this only makes sense if the local h2 database is used.)

**Comment by jeremylong** [comment]
This has been committed to the 1.3.1-SNAPSHOT and will be included in the next release.

**Comment by awhitford** [comment]
Thanks for the quick turnaround.

I noticed that you added a purge for the `dc.h2.db` file.  When I had the problem, I noticed that there was another small file (`dc.trace.db`).  I ended up wiping the whole data directory.

Do you happen to know if that other file should be purged too?
