### ISSUE TITLE
[ERROR] java.io.EOFException: Expected to read bytes from the stream

### ISSUE THREAD

**Issue by itsecforu** [dependency-check/DependencyCheck#3286]
Hey, Jeremy!

Im Using dep-check into Docker

Dependency-Check Core version 6.0.5

.Net project

Got the error:

`[ERROR] java.io.EOFException: Expected to read bytes from the stream`

Can u tell me how to fix it?

**Comment by jeremylong** [comment]
Have you tried using 6.1.5?

**Comment by itsecforu** [comment]
is there Docker image?

**Comment by itsecforu** [comment]
https://dl.bintray.com/jeremy-long/owasp/ -there is no 6.1.5
But here https://jeremylong.github.io/DependencyCheck/current.txt it is.

**Comment by mprins** [comment]
@itsecforu Check the release notes on why there are no more bintray downloads.

**Comment by itsecforu** [comment]
@mprins thx for answer, will be depcheck reshosting?

**Comment by itsecforu** [comment]
6.1.6 version doesnt solve it

**Comment by cwilliamsva** [comment]
Seeing this in 6.2.2 as well

**Comment by jeremylong** [comment]
Can you provide a project that replicates the issue?  "It's broke" doesn't really help us fix the problem.

**Comment by itsecforu** [comment]
there are Cyrillic files in the directory, could this affect it?
