### ISSUE TITLE
maven dependencies for maven plugin should use provided scope

### ISSUE THREAD

**Issue by awhitford** [dependency-check/DependencyCheck#329]
Maven 2 and 3 always use the classes from the distro, ignoring declared dependencies for Maven core stuff.  Marking maven distro dependencies as provided avoids risk around including a non thread-safe plexus-utils dependency transitively.

See:  https://cwiki.apache.org/confluence/display/MAVEN/Parallel+builds+in+Maven+3

**Comment by jeremylong** [comment]
Thanks for pointing this out. The change has been committed to 1.3.1-SNAPSHOT and will be included in the next release.
