### ISSUE TITLE
Repeated scans result in different reports

### ISSUE THREAD

**Issue by valentijnscholten** [dependency-check/DependencyCheck#3291]
**Describe the bug**
I have a project which consists of 12 war files, and a shared war. I scan these using the jenkins plugin using `--scan **/*.war`.

The report that is outputted changes from time to time, even when the wars are binary identical to the previous runs.

Dependency check seems to be trying to group things together, or mark some wars as shade by other wars.

What I see is that sometimes war A is reported a dependency with war B as related dependencies. But sometimes it's different or the other way around.

The differences are so big that it's hard see what exactly is going on, but my suspicion is this is caused by having no predictable ordering. (a point mentioned in #2608 - now closed).

**Version of dependency-check used**
The problem occurs using version 6.1.3 of the jenkins cli

**Log file**
I can provide private links to logs offline

**To Reproduce**
Have a project with multiple wars, generated independently of eachother
Have a job copying all the wars into a folder
Scan the wars using the (jenkins) cli with --scan '**/*.war`

**Expected behavior**
When the wars are binary identical, the reports generated by dependency check should be identical as well.

**Comment by valentijnscholten** [comment]
Did some more testing. Without knowing the intention behind the "shading" it's hard to understand what is happening. It looks like when I have a project that has:

A.war, which contains shared.jar
B.war, which contains shared.jar
C.war, which contains shared.jar
shared.jar

If I scan these 4 wars (or **/*.war), it looks like shared.jargets either "grouped" (or "shaded"?) under A.war xor B.war xor C.war. Could depend on filesystem ordering or maybe last update timestamp, haven't found a pattern yet.
But depending on what gets chosen you either get all the vulnerabilities from shared.jarunder only A.war or only B.war or only C.war. And separate from that you get them also under shared.jar. 

Not sure if this is intended, but I would expect all the vulnerabilities to be reported 4 times, once under A, once under B, once under C, once under shared. Does that make sense?
The current behavior only has 2 vulnerabilities in the report which hides the 2 others. And it's unpredictable which 2 get hidden. So if you have a tool like Defect Dojo trying to ingest the findings and keep track of new/mitigated findings things go wrong as it will start flipping findings from open to closed based on the unpredictability.

~~When I remove the shared.jarfrom the scan, it all works as expected. Each vulnerability in shared.jargets outputten 3 times. Once for each of the A/B/C.wars.~~

**Comment by valentijnscholten** [comment]
Just did another run, with different result again using this setup:
A.war, which contains shared.jar
B.war, which contains shared.jar
C.war, which contains shared.jar

run 1 contains "B.war" 34 times
run 2 contains "B.war" 76 times

This with explicit ordering, so --scan A.war --scan B.war --scan C.war

**Comment by valentijnscholten** [comment]
As long as you scan only single wars or unrelated wars, everything seems fine. But the use case we're seeing more and more are applications based on a microservice architecture, with shared code like the shared.jarin the above example.

**Comment by jeremylong** [comment]
99% positive its because of this line: https://github.com/jeremylong/DependencyCheck/blob/3d097c4838d21d861753a0ea77cde92af19fac40/core/src/main/java/org/owasp/dependencycheck/analyzer/AbstractDependencyComparingAnalyzer.java#L92

As we are sorting on just the file name - there is no guaranteed order of files with the same name so the may be grouped differently and this results in a different order for the dependency bundling....

**Comment by valentijnscholten** [comment]
Turns out it was that 1% @jeremylong ;-) That fix didn't solve the problem. I did some digging today and created a PR that makes the data in the report / internal data structures ordered and that seems to make the reports predictable / idempotent. Please let me know if this approach is an acceptable one (more details in PR description). Personally I think reports across runs on the same set of scanned artifacts should be identical, apart from some timestamps maybe.

**Comment by valentijnscholten** [comment]
I can confirm the issues reported are solved by #3343, maybe the PR needs a slight title update to include "... and during analysis" :-)
