### ISSUE TITLE
[DependencyCheck] [ERROR] The execution of the download was interrupted

### ISSUE THREAD

**Issue by faad021** [dependency-check/DependencyCheck#3313]
We are experiencing this issues in our jenkins pipelines since yesterday when scanning for vulnerabilities. Suddenly we get these errors as seen in the log below. The pipelines have been working error free but now they all fail due to this error.

The problem occurs using version 5.1.1 of the jenkins plugin

**Log file**
[DependencyCheck] Could not start Jolokia agent: java.net.BindException: Address already in use
[DependencyCheck] [INFO] Checking for updates
[DependencyCheck] [INFO] Download Started for NVD CVE - Modified
[DependencyCheck] [INFO] Download Complete for NVD CVE - Modified  (1156 ms)
[DependencyCheck] [INFO] Processing Started for NVD CVE - Modified
[DependencyCheck] [ERROR] The execution of the download was interrupted
[DependencyCheck] org.owasp.dependencycheck.data.update.exception.UpdateException: The execution of the download was interrupted
[DependencyCheck] 	at org.owasp.dependencycheck.data.update.NvdCveUpdater.performUpdate(NvdCveUpdater.java:317)
[DependencyCheck] 	at org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:125)
[DependencyCheck] 	at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:855)
[DependencyCheck] 	at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:662)
[DependencyCheck] 	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:592)
[DependencyCheck] 	at org.owasp.dependencycheck.App.runScan(App.java:254)
[DependencyCheck] 	at org.owasp.dependencycheck.App.run(App.java:186)
[DependencyCheck] 	at org.owasp.dependencycheck.App.main(App.java:81)
[DependencyCheck] Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
[DependencyCheck] 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
[DependencyCheck] 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
[DependencyCheck] 	at org.owasp.dependencycheck.data.update.NvdCveUpdater.performUpdate(NvdCveUpdater.java:307)
[DependencyCheck] 	... 7 common frames omitted
[DependencyCheck] Caused by: java.lang.NullPointerException: null
[DependencyCheck] 	at org.owasp.dependencycheck.data.nvdcve.CveDB.updateVulnerabilityInsertReferences(CveDB.java:1169)
[DependencyCheck] 	at org.owasp.dependencycheck.data.nvdcve.CveDB.updateVulnerability(CveDB.java:856)
[DependencyCheck] 	at org.owasp.dependencycheck.data.update.nvd.NvdCveParser.parse(NvdCveParser.java:101)
[DependencyCheck] 	at org.owasp.dependencycheck.data.update.nvd.ProcessTask.importJSON(ProcessTask.java:139)
[DependencyCheck] 	at org.owasp.dependencycheck.data.update.nvd.ProcessTask.processFiles(ProcessTask.java:152)
[DependencyCheck] 	at org.owasp.dependencycheck.data.update.nvd.ProcessTask.call(ProcessTask.java:113)
[DependencyCheck] 	at org.owasp.dependencycheck.data.update.nvd.ProcessTask.call(ProcessTask.java:40)
[DependencyCheck] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[DependencyCheck] 	at java.lang.Thread.run(Thread.java:748)
[DependencyCheck] [WARN] Unable to update 1 or more Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.
[DependencyCheck] [ERROR] Unable to continue dependency-check analysis.
[DependencyCheck] [ERROR] One or more fatal errors occurred
[DependencyCheck] [ERROR] The execution of the download was interrupted
[DependencyCheck] [ERROR] No documents exist
[Pipeline] dependencyCheckPublisher
[DependencyCheck] Collecting Dependency-Check artifact
[DependencyCheck] Unable to find Dependency-Check reports to parse

**Comment by philipwhiuk** [comment]
Duplicate of #3307

**Comment by rmontag-dvt** [comment]
https://twitter.com/NISTcyber/status/1385221317301919745

**Comment by jeremylong** [comment]
This was resolved when the NVD corrected the data feeds.
