### ISSUE TITLE
[QUESTION] Scan depth

### ISSUE THREAD

**Issue by astreiten** [dependency-check/DependencyCheck#3319]
Hello, I have been using this excellent tool to scan Javascript projects and I have a question regarding the depth of the scan.
One of my projects (let's call it "X") had a dependency on a library( let's call this library "Y").
When I ran the scan in "X", it detected 3 vulnerabilities related to "Y". 
I decided to fork from the "Y" repository and fix those vulns myself.  
The thing is that when I ran the scan in the "Y" repo for the first time, it detected approximately 15 vulns. It means that, for the same code, there was a different scan result depending on if I was scanning it from a client or in the repo itself.
Is there any stuff related to the scan depth that am I not understanding? Thank you.

**Comment by mprins** [comment]
Check the scope of the dependencies that you scanned, this tool does not scan code it scans a dependency tree

**Comment by jeremylong** [comment]
I'm assuming this is using npm? In which case, the tool basically wraps `npm audit` - and the dependency tree should be pulled in. However, if you are just scanning JS files on disk it can only scan what is present.
