### ISSUE TITLE
mvn site fails

### ISSUE THREAD

**Issue by awhitford** [dependency-check/DependencyCheck#332]
Cloning from github, running `mvn clean install site` fails.

I'm trying to build using Java 8 Update 60 and Maven 3.3.3 on a Mac.

It appears that the FindBugs 2.5.3 plugin can't handle Java 8?  Updating this to 3.0.1 solves the problem:

``` xml
<reporting.findbugs-plugin.version>3.0.1</reporting.findbugs-plugin.version>
```

**Comment by jeremylong** [comment]
Fixed by pull #333.  Thanks again!

--Jeremy
