### ISSUE TITLE
The Azure Devops step started failing with: `"https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta; received response code 503; Service Unavailable"`

### ISSUE THREAD

**Issue by eloisetaylor5693** [dependency-check/DependencyCheck#3325]
**Describe the bug**
When running a build with this step in an Azure Devops pipeline, it fails, and therefore fails the build
`Error retrieving https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta; received response code 503; Service Unavailable`

**Version of dependency-check used**
The problem occurs using version 6.0.2 of the Azure Devops Step (cli, gradle plugin, maven plugin, etc.)

**Log file**
 [Log output for Azure devops build when OWASP Dependency Check extension failed](https://gist.github.com/eloisetaylor5693/5282eb9cdd534a32d4aa249b0094eb93) 

**To Reproduce**
1. Run build
2. Failure

**Comment by kevinleary** [comment]
Getting the same on Jenkins build 6.0.0 ... Looks like the link is broken - https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2019.meta

**Comment by jody-mcdonnell** [comment]
Also seeing the same thing. When I run "mvn org.owasp:dependency-check-maven:aggregate -DskipTestScope=true" from my command line, I get the following error:

[INFO] Checking for updates
[ERROR] Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-modified.meta; received 404 -- resource not found
org.owasp.dependencycheck.data.update.exception.UpdateException: Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-modified.meta; received 404 -- resource not found

This doesn't seem like an OWASP Dependency-Check issue but a (continuing) NIST issue.

**Comment by kevinleary** [comment]
@eloisetaylor5693 @jody-mcdonnell Try again guys... the link appears to be fixed and working now

**Comment by eloisetaylor5693** [comment]
Working now.  Thanks :)

**Comment by jody-mcdonnell** [comment]
> @eloisetaylor5693 @jody-mcdonnell Try again guys... the link appears to be fixed and working now

Weird...I'm still getting the 404. Maybe it's somehow intermittent?

**Comment by kevinleary** [comment]
@jody-mcdonnell Hmm it looks to be down again... I would say you just gotta catch it at the right time.

**Comment by nhumblot** [comment]
Hello,

https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta appears to be up now.

Could you please close this issue ? It is an issue with the NVD website. Dependency-check cannot do anything about that.

Thank you. :slightly_smiling_face:

**Comment by albuch** [comment]
As a side note: If you want to have a more resiltient pipeline you can always create a local copy of the NVD data feed for example with https://github.com/stevespringett/nist-data-mirror and configure DependecyCheck to use your copy instead.
