### ISSUE TITLE
Firewall whitelist for dependency-check

### ISSUE THREAD

**Issue by daxin09pp** [dependency-check/DependencyCheck#3326]
Hi,

Our dependency-check Server limits outbound traffic on the firewall. Could you please help to list which URLs I need to whitelist on the firewall?

Thanks!

**Comment by albuch** [comment]
You can find this information in the docs: https://jeremylong.github.io/DependencyCheck/data/index.html and if you need concrete URLs have a look at the default settings: https://github.com/jeremylong/DependencyCheck/blob/main/core/src/main/resources/dependencycheck.properties

**Comment by daxin09pp** [comment]
@albuch Thanks~
BTW, I see the description for Sonatype OSS Index in https://jeremylong.github.io/DependencyCheck/data/index.html is 
**'OWASP dependency-check includes support to consult the Sonatype OSS Index to enrich the report with supplemental vulnerability information.'**
So even if I was unable to connect to OSSIndex, it didn't affect the results, just a little bit less information for all of the vulnerabilities?

**Comment by albuch** [comment]
That is correct, the OSS Index Analyzer currently only adds additional References for Vulnerabilities found by other analyzers like NVD CVE Analyzer: https://github.com/jeremylong/DependencyCheck/blob/main/core/src/main/java/org/owasp/dependencycheck/analyzer/OssIndexAnalyzer.java#L238

**Comment by jeremylong** [comment]
In some cases the OSS Index Analyzer does find vulns not found by ODC by itself.

**Comment by daxin09pp** [comment]
Thanks! @jeremylong @albuch 
BTW, I see the config file https://github.com/jeremylong/DependencyCheck/blob/main/core/src/main/resources/dependencycheck.properties show that:
**# the URL for searching NPM Audit API
analyzer.node.audit.url=https://registry.npmjs.org/-/npm/v1/security/audits
analyzer.node.audit.use.cache=true**
Can I change the node audit url when i use the CLI version Dependency-check? We have Proget Server to privide the npm audit api. Thanks!

**Comment by jeremylong** [comment]
The node audit URL has not been exposed as a CLI argument. However, you
could add a properties file of your own to change the property (via
--propertyfile)
or even set it via JAVA_OPTS=-D*analyzer.node.audit.url=...*

*--jeremy*

**Comment by daxin09pp** [comment]
> In some cases the OSS Index Analyzer does find vulns not found by ODC by itself.

Thanks. You are right. I found that some CVEs could not be reported if I turned off ossindex.
