### ISSUE TITLE
meta-file generation generates invalid url (".jmeta" instad of ".meta") when using cveUrlModified in pom.xml

### ISSUE THREAD

**Issue by freddiN** [dependency-check/DependencyCheck#3338]
**Describe the bug**
When using cveUrlModified / cveUrlBase to point to a local nvd mirror, downloading the meta file fails becuse the url is not created correctly: The resulting filename has a "j" prefixed, e.g. "nvdcve-1.1-modified.**j**meta" instead of ".meta"

**Version of dependency-check used**
6.1.5

**Log file**
>[ERROR] Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.jmeta; received 404 -- resource not found
>org.owasp.dependencycheck.data.update.exception.UpdateException: Unable to download meta file: >https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.jmeta; received 404 -- resource not found
>    at org.owasp.dependencycheck.data.update.NvdCveUpdater.getMetaFile (NvdCveUpdater.java:351)
>    at org.owasp.dependencycheck.data.update.NvdCveUpdater.getUpdatesNeeded (NvdCveUpdater.java:385)
>    at org.owasp.dependencycheck.data.update.NvdCveUpdater.update `(NvdCveUpdater.java:122)`

**To Reproduce**
1. head over to nvd (https://nvd.nist.gov/vuln/data-feeds) and fetch the latest modified url from the feed
2. in a project performing the dependency check, set these values in the pom:
  `<cveUrlModified>https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.json.zip</cveUrlModified>`
  `<cveUrlBase>https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-%d.json.gz</cveUrlBase>`
3. execute update-only

**Expected behavior**
A ".meta" url instead of a ".jmeta" so the download succeeds.

**Additional context**
The bug seems to reside in NvdCveUpdater.java, getMetaFile(String url):
`final String metaUrl = url.substring(0, url.length() - 7) + "meta";`
Extracting this snippet into a main() and feeding it with "https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.json.zip", results in a ".jmeta" url instead of ".meta".
I believe cutting off the last 7 chars is not a perfect solution, I'd suggest splitting at "."s for filename creation.

**Comment by freddiN** [comment]
I made a terrible mistake: I used the .zip instead of the .gz

Id still suggest to use "splitting at ." instead of "url.substring(0, url.length() - 7) + "meta"" in the code, though ... as a windows user I gravitated towards the .zip instead of the .gz.

**Comment by nhumblot** [comment]
> I made a terrible mistake: I used the .zip instead of the .gz
> 
> Id still suggest to use "splitting at ." instead of "url.substring(0, url.length() - 7) + "meta"" in the code, though ... as a windows user I gravitated towards the .zip instead of the .gz.

Hello, :wave:

Improving this method is not enough as there is nothing to handle the zip file afterwards. The `NvdCveParser` handles only gzip files right now. If we want to support zip files as well as gzip ones, we have to update `NvdCveParser.parse(File file)`. I will continue to work on it and submit a PR.

An update in the documentation will be provided also, to tell `--cveUrlModified` can also handle zip files.

If maintainers prefer to support gzip only, please let me know in this issue.

**Comment by jeremylong** [comment]
I see no reason to support the ZIP file format for the CVE URLs. We could report an error if we receive a `.ZIP` extension indicating that the user needs to supply the `.GZ` file.

In all honesty - after looking at the code some more I not even sure why this is two parameters... The base URL is sufficient to determine the URL for the modified file.

**Comment by nhumblot** [comment]
I see two good things in keeping the two urls:

1. If somehow, this interface change and a new url must be used (or the custom mirror has a different url), users of dependency-check will be able to configure it and have it working
2. We keep backward compatibility

But as you said, we can improve how we handle these urls. Right now, we must set the two if we want to use this configuration, as stated in `CliParser.java` (from `dependency-check-cli`).
```
final String base = getStringArgument(ARGUMENT.CVE_BASE_URL);
final String modified = getStringArgument(ARGUMENT.CVE_MODIFIED_URL);
if ((base != null && modified == null) || (base == null && modified != null)) {
    final String msg = "If one of the CVE URLs is specified they must all be specified; please add the missing CVE URL.";
    throw new ParseException(msg);
}
```
We can make `cveUrlModified` optional, even when `cveBaseUrl` is set by applying the following rule:
```
GIVEN cveUrlBase is not null and set to '<url>/nvdcve-1.1-%d.json.gz'
AND cveUrlModified is null
WHEN settings are loaded
THEN cveUrlModified is set to '<url>/nvdcve-1.1-modified.json.gz'
```
If it's ok for you, I can open a PR with these changes. Please do not hesitate to amend this proposal if you have another idea. :slightly_smiling_face:

**Comment by jeremylong** [comment]
Yes a PR to make the CVE Modified URL option would be great. This would likely need to be done in the Maven Plugin, Ant Task, and the CLI. If you can do all three great - otherwise I can copy code as required into the maven and ant projects. Thanks!
