### ISSUE TITLE
ExecutionException/NullPointer on Update

### ISSUE THREAD

**Issue by rshelby5** [dependency-check/DependencyCheck#3339]
https://github.com/jeremylong/DependencyCheck/issues/3306

This is still an issue. Is there any workaround because setting autoUpdate to false does not solve this issue.

**Comment by jeremylong** [comment]
Log file? stack trace? what command are you using to run ODC? How is it configured? Are you using a mirror of the NVD?

**Comment by rshelby5** [comment]
@jeremylong this is fixed. Just had to update to the latest version. Thanks!
