### ISSUE TITLE
Error "Could not perform Node Audit analysis. Invalid payload submitted to Node Audit API" arising if package-lock.json is generated with NPM 7(?!)

### ISSUE THREAD

**Issue by js-dot** [dependency-check/DependencyCheck#3341]
**Describe the bug**
Dependency check executed within our build system failed for a frontend developer who generated the package-lock.json with NPM 7 (7.11.1 and 7.7.5). After some analysis and testing we discovered that generating the package-lock.json on the very same project with NPM 6 (6.14.12) resulted in dependency-check running successfully. According to the NPM 7 changelog they introduced a new package-lock format (v2) which, however, is supposed to be backwards-compatible. After all, this is based only on our observations, we are not absolutely sure whether this is due to NPM 7 at all.

**Version of dependency-check used**
The problem occurs using version 5.3.2, 6.1.5 and 6.1.6 (no other versions were tested) of the maven plugin. Further settings can be seen in the log.

**Log file**
[This log](https://gist.github.com/js-dot/5b991a416185e7921c5a2d4d3b7fbccb) is a redacted (due to company and possible sensitive information...) excerpt (the full log is close to 400mb) of the full log resulting from an execution of dependency-check 6.1.6. I know that I do not provide the (most likely) most valuable information, the package-lock.json, but it is gigantic and is full of company stuff.

**To Reproduce**
1. Generate package-lock.json with NPM 7
2. Run dependencycheck with NodeAuditAnalyzer enabled

**Expected behavior**
Dependency-check, respectively the NodeAuditAnalyzer is able to analyze the package-lock.json.

**Comment by JoepWeijers** [comment]
I can't reproduce this locally using a simple project with npm 7.11.1. The following steps create a small project, add some dependencies and the scan with dependency-check 6.1.6 finishes successful:
```
npm init
npm install --save is-even
dependency-check.bat --scan .
```

However, we have seen this same thing happening when people were using both npm 6 and npm 7. Npm 6 does not fully work correctly with `lockfileVersion: 2`. An example that broke analysis for us: `npm set-version [NEW_VERSION]` with npm 6 would update the `version` in the package lock, but not the `packages."",version`.

The solution for us was to regenerate the package-lock.json with npm 7 and not let npm 6 touch it anymore.

**Comment by js-dot** [comment]
I am 80% sure that in our case the package-lock.json was generated with npm 7 only (and has not been touched by npm 6 thereafter). Still, your information is very valuable for us, thank you!

However, in the meantime we did not encounter that problem again (which might also be due to developers not having updated to npm 7 yet, though)

If nobody can reproduce this issue in terms of discovering a fault in dependency-check and not in npm, we might close the issue here?

**Comment by jeremylong** [comment]
I wasn't able to re-produce the issue...
