### ISSUE TITLE
LuceneUtils.escapeLuceneQuery (wrong shift for size)

### ISSUE THREAD

**Issue by awhitford** [dependency-check/DependencyCheck#335]
I stumbled across this code and it looks like a small bug...

``` java
    public static String escapeLuceneQuery(final CharSequence text) {

        if (text == null) {
            return null;
        }

        int size = text.length();
        size = size >> 1;
        final StringBuilder buf = new StringBuilder(size);

        appendEscapedLuceneQuery(buf, text);

        return buf.toString();
    }
```

Why is `size` being shifted _right_?  (Shouldn't it be shifted _left_?)

I'm thinking the idea is to double the size to accommodate the potential escaping that may occur (so some characters are doubled with the addition of the escape character).  Alas, the right shift is shrinking the buffer instead of growing it, likely causing a guaranteed reallocation to expand.

I propose:

``` java
        final int size = text.length() << 1;
```

**Comment by jeremylong** [comment]
Thanks for catching this!

--Jeremy
