### ISSUE TITLE
False Positive on com.neovisionaries:nv-i18n

### ISSUE THREAD

**Issue by jashaj** [dependency-check/DependencyCheck#3352]
False positive on library com.neovisionaries:nv-i18n.jar - reported as `cpe:2.3:a:i18n_project:i18n:*:*:*:*:*:asp.net:*:* versions up to (excluding) 2.1.15`

```xml
<dependency>
  <groupId>com.neovisionaries</groupId>
  <artifactId>nv-i18n</artifactId>
  <version>1.27</version>
</dependency>
```

**Comment by jody-mcdonnell** [comment]
As noted in https://github.com/jeremylong/DependencyCheck/issues/3407, the same cpe is being picked up as a false positive against the org.apache.xmlgraphics:batik-codec dependency.

**Comment by mprins** [comment]
see https://github.com/jeremylong/DependencyCheck/pull/3369
