### ISSUE TITLE
Disabling the bundling analyzer

### ISSUE THREAD

**Issue by spelletierlamothe** [dependency-check/DependencyCheck#3355]
Hi, I would like to know if the solution [here](https://github.com/jeremylong/DependencyCheck/issues/2118#issuecomment-517916384) is still suppose to work for Dependency Check 6.1.1 and above?

We have added the "-Danalyzer.dependencybundling.enabled=false" argument in the JAVA_OPTS environment variable but the bundling analyzer still execute. Is there another way other than using the properties file?

I have search through the codebase to see if there was another way to load the settings but I haven't found any.

Thank you.

**Comment by jeremylong** [comment]
Yes - the JAVA_OPTS should work. How are you running ODC?

If using the CLI - try running with `--log odc.log` and near the top the properties are listed to see if the JAVA_OPTS are correctly being passed in?
