### ISSUE TITLE
Owasp dependency check on GitHub projects

### ISSUE THREAD

**Issue by sourabhsparkala** [dependency-check/DependencyCheck#3357]
I am trying to scan a cloned GitHub project in my local by using Dependencycheck CLI.

That is by providing `-scan /{cloned github project}`. Is this something which can be achieved with OWASP dependency check `CLI` or `core`?

Please let me know the starting point on how to achieve this if this is possible.

**Comment by mprins** [comment]
it would only work if you have a local clone of the project and build that; any CLI usage is documented on the CLI page and the readme https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html

**Note**: as the name says this tool scans dependencies, not code.

**Comment by sourabhsparkala** [comment]
@mprins 

Thank you for the reply. Please let me know if this makes sense.

- My application clones few OSS GitHub projects like https://github.com/FasterXML/jackson-databind and analyzes them.
- A step in analysis is to get the list of Vulnerabilities reported for this `jackson-databind` project.
- I am trying to find a way to invoke `OWASP dependency check` on this OSS `jackson-databind` project from my application. 
- I am trying to see what can be used `OWASP cli` or `OWASP core` as a dependency in my application to trigger the scan on a cloned OSS project.

I am not sure if this is achievable. But any inputs would be appreciated.

Thanks

**Comment by jeremylong** [comment]
ODC does not analyze github repos. You would need to build jackson-databind and scan the resulting build artifacts.
