### ISSUE TITLE
Best way to scan C/C++ code

### ISSUE THREAD

**Issue by udplume** [dependency-check/DependencyCheck#3363]
I am trying to use dependency-check for scanning some C / C++ code.

Are there any specific steps to be followed for C/C++ code. 
For eg. 
Does the code need to be built before running the scan ?

Does it require use of Experimental Analyzers ? 

I believe 'cmake' is the relevant analyzer for C/C++ code, is that correct ?

If so , as per

https://jeremylong.github.io/DependencyCheck/analyzers/index.html

CMake is used as default as a File Type analyzer , but is also listed under Experimental analyzer as are many of the other analyzers. Do these analyzers do something extra when the --enableExperimental flag is used ?

**Comment by jeremylong** [comment]
CMake is an experimental analyzer. To enable the experimental analyzers you have to add `--enableExperimental`. I have updated the documentation so the CMake is no longer listed twice..
