### ISSUE TITLE
False Positive on jenkins.war

### ISSUE THREAD

**Issue by wagde-orca** [dependency-check/DependencyCheck#3364]
When reporting a false positive please include:
- The location of the dependency (Maven GAV, URL to download the dependency, etc.)
https://get.jenkins.io/war-stable/2.235.5/jenkins.war
sha1 729c99f619fdd0472e4d48a919ed4c4a24293ade
- The CPE that is believed to be false positive
```
      "vulnerabilityIds": [
        {
          "id": "cpe:2.3:a:jenkins:jenkins:1.395:*:*:*:*:*:*:*",
          "confidence": "MEDIUM",
          "url": "https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Ajenkins&cpe_product=cpe%3A%2F%3Ajenkins%3Ajenkins&cpe_version=cpe%3A%2F%3Ajenkins%3Ajenkins%3A1.395"
        }
      ],
```

for some reason the version evidence which is chosen is 
```
          {
            "type": "version",
            "confidence": "MEDIUM",
            "source": "Manifest",
            "name": "hudson-version",
            "value": "1.395"
          },
```

although there is an eviidence with the right version and confidence HIGH
```
          {
            "type": "version",
            "confidence": "HIGH",
            "source": "Manifest",
            "name": "Implementation-Version",
            "value": "2.235.5"
          },
```

We see these FPs in almost all jenkins 2.x.x version

**Comment by aikebah** [comment]
Fixing the versions does not resolve the FPs yet. The LTS versions of Jenkins are listed under `cpe:2.3:a:jenkins:jenkins:*:*:*:*:lts:*:*:*` coordinates in NVD and the running releases under `cpe:2.3:a:jenkins:jenkins:*:*:*:*:-:*:*:*`

So the LTS version of the war will hit the running-releases affected software entry as the fixes in LTS are backported from a higher running release version

**Comment by aikebah** [comment]
But at least the FPs from versions lower than the starting revision of the LTS version are now no longer listed as the version gets established correctly

**Comment by jeremylong** [comment]
@aikebah with https://github.com/jeremylong/DependencyCheck/pull/3556 - can this be closed?

**Comment by aikebah** [comment]
@jeremylong The reported issue is closed, so maybe yes, but then we should open a new issue for the fact that FPs still exist for LTS versions due to how they're registered at NVD.

**Comment by jeremylong** [comment]
I just created https://github.com/jeremylong/DependencyCheck/issues/3581
