### ISSUE TITLE
jsrepository.json.lock left over if canceling during NVD CVE update processing

### ISSUE THREAD

**Issue by echalone** [dependency-check/DependencyCheck#3370]
**Describe the bug**
The file data/jsrepository.json.lock persists if the tool has been canceled during NVD CVE update processing.

**Version of dependency-check used**
6.1.6

**First call (generating lock file)**
C:\WINDOWS\system32\cmd.exe /D /S /C "C:\dependency-check\bin\dependency-check.bat --project MyProject --scan C:\MyProject\Source\**\*.*proj --out C:\MyProject\TestResults\dependency-check --format HTML --failOnCVSS 10"
[INFO] Checking for updates
[INFO] NVD CVE requires several updates; this could take a couple of minutes.
[INFO] Download Started for NVD CVE - 2003
[INFO] Download Started for NVD CVE - 2002
[INFO] Download Complete for NVD CVE - 2003  (1046 ms)
[INFO] Download Started for NVD CVE - 2004
[INFO] Processing Started for NVD CVE - 2003
[INFO] Processing Complete for NVD CVE - 2003  (829 ms)
[INFO] Download Complete for NVD CVE - 2002  (2859 ms)
[INFO] Download Started for NVD CVE - 2005
[INFO] Processing Started for NVD CVE - 2002
[INFO] Download Complete for NVD CVE - 2004  (2516 ms)
[INFO] Download Started for NVD CVE - 2006
[INFO] Processing Started for NVD CVE - 2004
[INFO] Processing Complete for NVD CVE - 2002  (1688 ms)
[INFO] Download Complete for NVD CVE - 2005  (1813 ms)
[INFO] Download Started for NVD CVE - 2007
[INFO] Processing Started for NVD CVE - 2005
[INFO] Processing Complete for NVD CVE - 2004  (1282 ms)
[INFO] Processing Complete for NVD CVE - 2005  (1306 ms)
[INFO] Download Complete for NVD CVE - 2006  (2556 ms)
[INFO] Download Started for NVD CVE - 2008
[INFO] Processing Started for NVD CVE - 2006
[INFO] Download Complete for NVD CVE - 2007  (1493 ms)
[INFO] Download Started for NVD CVE - 2009
[INFO] Processing Started for NVD CVE - 2007
[INFO] Download Complete for NVD CVE - 2009  (2660 ms)
[INFO] Download Started for NVD CVE - 2010
[INFO] Processing Started for NVD CVE - 2009
[INFO] Download Complete for NVD CVE - 2008  (2785 ms)
[INFO] Download Started for NVD CVE - 2011
[INFO] Processing Started for NVD CVE - 2008
[INFO] Download Complete for NVD CVE - 2011  (1380 ms)
[INFO] Download Started for NVD CVE - 2012
[INFO] Processing Started for NVD CVE - 2011
[INFO] Processing Complete for NVD CVE - 2007  (5062 ms)
[INFO] Download Complete for NVD CVE - 2010  (2700 ms)
[INFO] Download Started for NVD CVE - 2013
[INFO] Processing Started for NVD CVE - 2010
[INFO] Processing Complete for NVD CVE - 2006  (6141 ms)
[INFO] Download Complete for NVD CVE - 2012  (2304 ms)
[INFO] Download Started for NVD CVE - 2014
[INFO] Processing Started for NVD CVE - 2012
[INFO] Download Complete for NVD CVE - 2013  (2708 ms)
[INFO] Download Started for NVD CVE - 2015
[INFO] Processing Started for NVD CVE - 2013
[INFO] Download Complete for NVD CVE - 2014  (1740 ms)
[INFO] Download Started for NVD CVE - 2016
[INFO] Processing Started for NVD CVE - 2014
[INFO] Download Complete for NVD CVE - 2015  (2806 ms)
[INFO] Download Started for NVD CVE - 2017
[INFO] Processing Started for NVD CVE - 2015
[INFO] Download Complete for NVD CVE - 2016  (3603 ms)
[INFO] Download Started for NVD CVE - 2018
[INFO] Processing Started for NVD CVE - 2016
[INFO] Download Complete for NVD CVE - 2017  (1990 ms)
[INFO] Download Started for NVD CVE - 2019
[INFO] Processing Started for NVD CVE - 2017
[INFO] Download Complete for NVD CVE - 2018  (1661 ms)
[INFO] Download Started for NVD CVE - 2020
[INFO] Processing Started for NVD CVE - 2018
[INFO] Download Complete for NVD CVE - 2019  (1937 ms)
[INFO] Download Started for NVD CVE - 2021
[INFO] Processing Started for NVD CVE - 2019
[INFO] Download Complete for NVD CVE - 2020  (2411 ms)
[INFO] Processing Started for NVD CVE - 2020
[INFO] Download Complete for NVD CVE - 2021  (1522 ms)
[INFO] Processing Started for NVD CVE - 2021
[INFO] Processing Complete for NVD CVE - 2009  (15949 ms)
[INFO] Processing Complete for NVD CVE - 2011  (20508 ms)
<canceled via CTRL+C>

**Second call (waiting forever for lock file to be released)**
C:\WINDOWS\system32\cmd.exe /D /S /C "C:\dependency-check\bin\dependency-check.bat --project MyProject --scan C:\MyProject\Source\**\*.*proj --out C:\MyProject\TestResults\dependency-check --format HTML --failOnCVSS 10"
[INFO] Checking for updates
[INFO] NVD CVE requires several updates; this could take a couple of minutes.
[INFO] Download Started for NVD CVE - 2008
[INFO] Download Started for NVD CVE - 2010
[INFO] Download Complete for NVD CVE - 2008  (2792 ms)
[INFO] Download Started for NVD CVE - 2012
[INFO] Processing Started for NVD CVE - 2008
[INFO] Download Complete for NVD CVE - 2010  (2870 ms)
[INFO] Download Started for NVD CVE - 2013
[INFO] Processing Started for NVD CVE - 2010
[INFO] Download Complete for NVD CVE - 2013  (1693 ms)
[INFO] Download Started for NVD CVE - 2014
[INFO] Processing Started for NVD CVE - 2013
[INFO] Download Complete for NVD CVE - 2012  (1865 ms)
[INFO] Download Started for NVD CVE - 2015
[INFO] Processing Started for NVD CVE - 2012
[INFO] Download Complete for NVD CVE - 2015  (2911 ms)
[INFO] Download Started for NVD CVE - 2016
[INFO] Processing Started for NVD CVE - 2015
[INFO] Download Complete for NVD CVE - 2014  (3224 ms)
[INFO] Download Started for NVD CVE - 2017
[INFO] Processing Started for NVD CVE - 2014
[INFO] Download Complete for NVD CVE - 2016  (1578 ms)
[INFO] Download Started for NVD CVE - 2018
[INFO] Processing Started for NVD CVE - 2016
[INFO] Download Complete for NVD CVE - 2017  (1906 ms)
[INFO] Download Started for NVD CVE - 2019
[INFO] Processing Started for NVD CVE - 2017
[INFO] Download Complete for NVD CVE - 2018  (1672 ms)
[INFO] Download Started for NVD CVE - 2020
[INFO] Processing Started for NVD CVE - 2018
[INFO] Download Complete for NVD CVE - 2020  (2867 ms)
[INFO] Download Started for NVD CVE - 2021
[INFO] Processing Started for NVD CVE - 2020
[INFO] Download Complete for NVD CVE - 2019  (4934 ms)
[INFO] Processing Started for NVD CVE - 2019
[INFO] Download Complete for NVD CVE - 2021  (1209 ms)
[INFO] Processing Started for NVD CVE - 2021
[INFO] Processing Complete for NVD CVE - 2010  (29845 ms)
[INFO] Processing Complete for NVD CVE - 2021  (22905 ms)
[INFO] Processing Complete for NVD CVE - 2012  (33438 ms)
[INFO] Processing Complete for NVD CVE - 2008  (36366 ms)
[INFO] Processing Complete for NVD CVE - 2013  (35001 ms)
[INFO] Processing Complete for NVD CVE - 2015  (35462 ms)
[INFO] Processing Complete for NVD CVE - 2014  (36149 ms)
[INFO] Processing Complete for NVD CVE - 2016  (35905 ms)
[INFO] Processing Complete for NVD CVE - 2017  (39152 ms)
[INFO] Processing Complete for NVD CVE - 2018  (38335 ms)
[INFO] Processing Complete for NVD CVE - 2019  (34619 ms)
[INFO] Processing Complete for NVD CVE - 2020  (35624 ms)
[INFO] Download Started for NVD CVE - Modified
[INFO] Download Complete for NVD CVE - Modified  (922 ms)
[INFO] Processing Started for NVD CVE - Modified
[INFO] Processing Complete for NVD CVE - Modified  (532 ms)
[INFO] Begin database maintenance
[INFO] Updated the CPE ecosystem on 116155 NVD records
[INFO] Removed the CPE ecosystem on 3907 NVD records
[INFO] End database maintenance (9437 ms)
[WARN] A new version of dependency-check is available. Consider updating to version 6.1.6.
[INFO] Lock file found 'C:\dependency-check\data\jsrepository.json.lock'
[INFO] Existing update in progress; waiting for update to complete
...will wait forever here...

**To Reproduce**
1. Call dependency check tool
2. Cancel with CTRL+C during NVD CVE update processing
3. The file data/jsrepository.json.lock will be created and not be deleted again
4. Re-run dependency check tool
5. Dependency check tool will now wait forever for lock file to be released

**Expected behavior**
The data/jsrepository.json.lock file is either not created or would be deleted after canceling of dependency check tool.

**Comment by mprins** [comment]
You are terminating the Java VM/runtime with CTRL-C; the JVM therefor does not get the chance to run the shutdown hooks that ODC has put in place to cleanup the lock file in case of abnormal program (ODC) termination.

see https://github.com/jeremylong/DependencyCheck/blob/5d2c571a3a8e79cdf49e22f25af0d42fa658a9a0/core/src/main/java/org/owasp/dependencycheck/utils/WriteLock.java#L135-L202

**Comment by echalone** [comment]
Well, that's a problem for the Azure DevOps Pipeline task since the agent will basically cancel that step with CTRL+C if the pipeline was cancelled:
https://marketplace.visualstudio.com/items?itemName=dependency-check.dependencycheck

So the lock file will remain when cancelling in the wrong moment and will prevent the next build from being executed past the OWASP dependency checker step.

**Comment by jeremylong** [comment]
I think we've done everything we can within code to add a shutdown hook. Unfortunately, in some cases this may not get called.

https://github.com/jeremylong/DependencyCheck/blob/3d097c4838d21d861753a0ea77cde92af19fac40/core/src/main/java/org/owasp/dependencycheck/utils/WriteLockCleanupHook.java#L29

**Comment by echalone** [comment]
I've built in a removal of lock files for the extension mentioned by me, so at least there we can live with it now
