### ISSUE TITLE
Easiest way to use only one or two analyzers?

### ISSUE THREAD

**Issue by robross0606** [dependency-check/DependencyCheck#3371]
The CLI seems unreasonably complicated if you only want to use _one_ analyzer for your project (i.e. `npm audit`).  What is the simplest way to stop the tool from trying to use 10+ analyzers by default?  Is there a way to disable all but one without listing `--disable*` for each one individually?

**Comment by jeremylong** [comment]
If you only want the npm audit analyzer consider just running 'npm audit'
and don't use ODC.

Jeremy

**Comment by robross0606** [comment]
I need the OWASP report and integration with Jenkins/Sonar.  There are just a LOT of analyzers that default to enabled.  Even ones like “node.js” that are problematic and recommended to be turned off, are on by default.  Is there some type of concise list for a properties file somewhere?

**Comment by jeremylong** [comment]
I suppose you could use a properties file and put all the keys in there:
https://github.com/jeremylong/DependencyCheck/blob/6d263594e57c399300cb80bf6000e0b6a5d770e4/utils/src/main/java/org/owasp/dependencycheck/utils/Settings.java#L281
