### ISSUE TITLE
RetireJS Analyzer - Error 

### ISSUE THREAD

**Issue by rsrinivasan-cs** [dependency-check/DependencyCheck#3376]
Version  - 6.1.6
During the run of dependency check scan, I get the below error:

12:45:13 [DependencyCheck] [WARN] An error occurred while analyzing 'xxx/package-lock.json?chart.js' (RetireJS Analyzer).
12:45:19 [DependencyCheck] [INFO] Finished RetireJS Analyzer (107 seconds)
12:45:20 [DependencyCheck] [INFO] Finished Sonatype OSS Index Analyzer (1 seconds)
12:45:21 [DependencyCheck] [INFO] Finished Vulnerability Suppression Analyzer (1 seconds)
12:50:48 [DependencyCheck] [INFO] Finished Dependency Bundling Analyzer (326 seconds)
12:50:59 [DependencyCheck] [INFO] Analysis Complete (741 seconds)
12:50:59 [DependencyCheck] [INFO] Writing report to: xxx/dependency-check-report.xml
12:51:07 [DependencyCheck] [ERROR] java.io.FileNotFoundException: xxx/package-lock.json?chart.js (No such file or directory)

The package-lock.json file has the below contents regarding chart.js
    "chart.js": {
      "version": "2.3.0",
      "resolved": "https://registry.npmjs.org/chart.js/-/chart.js-2.3.0.tgz",
      "integrity": "xxx",
      "requires": {
        "chartjs-color": "^2.0.0",
        "moment": "^2.10.6"
      }
    },

Dependency check is looking for the package-lock.json?chart.js file, which does not exist.

Please let me know if there are any thoughts to fix the issue.

**Comment by rsrinivasan-cs** [comment]
Experts, Anyone is able to answer the above question? Thanks in advance.

**Comment by jeremylong** [comment]
There is a bug - working on a fix now. This will likely happen with any npm package that ends with `.js`. You can safely ignore the error.

**Comment by rsrinivasan-cs** [comment]
@jeremylong , Thank you for the response.
