### ISSUE TITLE
Dependency Check have a lot of vulnerability from exemple folder and old_splash_page

### ISSUE THREAD

**Issue by patriciamarchand** [dependency-check/DependencyCheck#3379]
Hello,
Dependency check scan bring me a lot of vulnerability and I have to add it in suppression file. 
It mostly comes from files in folder examples and old_spash page. This folder are not necessary in the npm package to launch Backstop Test. Could it be a good idea to remove it from the package distributed?

File Path: 
C:\...\node_modules\backstopjs\ **examples** \angularAppWithCssTransitions\angular.min.js
C:\...\node_modules\backstopjs\ **examples** \myCoolProject\dist\js\bootstrap.js
C:\...\node_modules\backstopjs\ **examples** \responsiveDemo\dist\js\bootstrap.min.js
C:\...\node_modules\backstopjs\ **examples** \myCoolProject\dist\js\bootstrap.min.js
C:\...\node_modules\backstopjs\ **old_splash_page_v2.0** \js\vendor\bootstrap.js

![image](https://user-images.githubusercontent.com/6225238/118306291-3835d900-b4b7-11eb-9730-460d702c85c0.png)

By removing it, I will have only to temporary remove the vulnarebility from Resemble.
C:\0-projets\dsd\packages\library\node_modules\node-resemble-js\node_modules\jpeg-js\package.json

**Comment by albuch** [comment]
Hi @patriciamarchand, this is probably a question better asked at https://github.com/garris/BackstopJS as they are the maintainer of the backstopjs npm package.
However, if you like to exclude the example folder from this specific or from even all npm packages you can use a file path regular expression in your [suppression xml file](https://jeremylong.github.io/DependencyCheck/general/suppression.html), e.g.:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<suppressions xmlns="https://jeremylong.github.io/DependencyCheck/dependency-suppression.1.3.xsd">
    <suppress>
        <notes><![CDATA[
        This suppresses all CVEs for the given file path
        ]]></notes>
        <filePath regex="true">^.*\/node_modules\/.*?\/example\/.*$</packageUrl>
        <cvssBelow>11</cvssBelow>
    </suppress>
</suppressions>
```

**Comment by patriciamarchand** [comment]
Sorry! I was thinking to be on the gitHub repo of BackstopJs after checking that kind of possibility with dependency check! Thanks for the tips.
