### ISSUE TITLE
False Positive on org.apache.xmlgraphics:batik-i18n:1.14

### ISSUE THREAD

**Issue by cula011** [dependency-check/DependencyCheck#3382]
False positive on library `batik-i18n-1.14.jar` - reported as both `cpe:2.3:a:apache:batik:1.14:*:*:*:*:*:*:*` (correct) and `cpe:2.3:a:i18n_project:i18n:1.14:*:*:*:*:*:*:*` (incorrect).

```    
<!-- https://mvnrepository.com/artifact/org.apache.xmlgraphics/batik-i18n -->
<dependency>
    <groupId>org.apache.xmlgraphics</groupId>
    <artifactId>batik-i18n</artifactId>
    <version>1.14</version>
</dependency>
```

**Comment by mprins** [comment]
please check for duplicates when logging an issue; there are many describing your problem already such as #3350

**Comment by cula011** [comment]
Apologies. I did search for issues with `batik-i18n`, but made the mistake of leaving the default `is:open` filter.
