### ISSUE TITLE
Why '[WARNING] Unable to find node module' pops up during dc analysis?

### ISSUE THREAD

**Issue by EvgeniaPatsoni** [dependency-check/DependencyCheck#3387]
Hello,

I am running a Dependency Check analysis on a project using maven's dc plugin. The analysis is executed successfully but I am not sure why a WARNING is shown for a bunch of node modules, e.g.: 

```
[WARNING] Unable to find node module: /path/to/project/node_modules/tsutils/package.json

[WARNING] Unable to find node module: /path/to/project/node_modules/ua-parser-js/package.json

[WARNING] Unable to find node module: /path/to/project/node_modules/v8flags/package.json

[WARNING] Unable to find node module: /path/to/project/node_modules/void-elements/package.json
```
These modules are indeed never installed and don't exist under the node_modules directory, thus why is the Analyzer looking for them? Is this a default behavior?

Here is my dc configuration, in case it helps.

```
<plugin>
	<groupId>org.owasp</groupId>
	<artifactId>dependency-check-maven</artifactId>
	<version>6.1.6</version>
	<configuration>
		<format>ALL</format>
			<failOnError>false</failOnError>
			<scanSet>
				<fileSet>
					<directory>.</directory>
					<includes>
						<include>ui-web/package.json</include>
						<include>ui-web/package-lock.json</include>
						<include>ui-config/**</include>
					</includes>
				</fileSet>
			</scanSet>
	</configuration>
</plugin>
```

**Comment by jeremylong** [comment]
There are many issues with the `Node.js Package Analyzer` and some of the features are planned to be removed (actually the entire analyzer will be removed). In the meantime I would recommend disabling it as it does not actually add much except noise to the report.  I would add `<nodeAnalyzerEnabled>false</nodeAnalyzerEnabled>` to your configuration.  The Node Audit Analyzer is currently the primary and most effective analyzer for node.

**Comment by ed-devops-d2** [comment]
Adding `<nodeAnalyzerEnabled>false</nodeAnalyzerEnabled>` did the trick. Thank you very much for the detailed explanation.

**Comment by EvgeniaPatsoni** [comment]
Adding `<nodeAnalyzerEnabled>false</nodeAnalyzerEnabled>` did the trick. Thank you very much for the detailed explanation.
