### ISSUE TITLE
Indicate how to contribute to the documentation

### ISSUE THREAD

**Issue by libnoon** [dependency-check/DependencyCheck#3388]
Hello,

Unless I'm mistaken, the DependencyCheck repository does not indicate how to contribute to the documentation by proposing changes (though it does indicate where the documentation could be read).

Could you please put this information somewhere, such as in the README?  Even if it's by sending patches to an email address.
(Yes, I would like to add something missing to the documentation).

Thanks!

Best regards
Fabrice

**Comment by jeremylong** [comment]
All of the documentation is in the source code repository and is generated using `mvn site:staging`.

- https://github.com/jeremylong/DependencyCheck/tree/main/src/site/markdown
- https://github.com/jeremylong/DependencyCheck/tree/main/ant/src/site/markdown
- https://github.com/jeremylong/DependencyCheck/tree/main/maven/src/site/markdown
- https://github.com/jeremylong/DependencyCheck/tree/main/cli/src/site/markdown

**Comment by libnoon** [comment]
Thanks!  I have created a pull request accordingly.
