### ISSUE TITLE
Different Scan Result on Sitefinity CMS

### ISSUE THREAD

**Issue by azwarfy612** [dependency-check/DependencyCheck#3389]
Hi, so currently I'm working on a website using Sitefinity, and did a dependency-check with this tools. However, there is a slight difference. I have 2 environment, where one of them is a fresh Sitefinity without any content and so on, the other is Sitefinity that already have content from my client.

When I scanned the fresh Sitefinity, there is no vulnerability detected on any .dll files. However, when I scanned the one with the contents, it flagged \bin\stdole.dll as Medium vulnerability.

May I know how this discrepancy happens? From my understanding, stdole.dll is default file from Sitefinity, and my client shouldn't be able to change it.

**Comment by jeremylong** [comment]
I know nothing about Sitefinity - my first question on your fresh site does the DLL exist? Had you performed a build yet?

**Comment by azwarfy612** [comment]
yes, both stdole.dll exist in both version in same path.

Any suggestion how I can find answer? Myself not sure asking Sitefinity support going to help either, and my client kind of pushing for answer.

**Comment by azwarfy612** [comment]
Yes, both file stdole.dll exist in both version, in same path.

Would it be possible to continue this via email? I probably need to share the result of my scan to make the explanation better and probably finding the issue. But due to secrecy matter, I cannot share the details in here.

**Comment by jeremylong** [comment]
https://github.com/jeremylong/DependencyCheck/blob/e1ca2479505b22aad490456c9ba821cdd1093da5/.github/workflows/coverity.yml#L30
