### ISSUE TITLE
[ERROR] Unable to initialize the Retire JS respository

### ISSUE THREAD

**Issue by neil-n-brown** [dependency-check/DependencyCheck#3393]
**Describe the bug**
ODC failing to run intermittently because of issues with RetireJS repository. Errors shown in the build log:

build	19-May-2021 08:41:19	[WARN] Retire JS repository is empty or missing - attempting to force the update
build	19-May-2021 08:41:19	[ERROR] Exception occurred initializing RetireJS Analyzer.
build	19-May-2021 08:41:21	[ERROR] Unable to initialize the Retire JS respository

Cli Commands used in the script: ${bamboo.DEPENDENCY_CHECK_CLI_HOME}/dependency-check.sh --project "ourprojectname" --scan $libDir --format XML --out $workspace --propertyfile ${bamboo.ODC_propertyfile} --cveUrlModified ${bamboo.ODC_cveUrlMod} --cveUrlBase ${bamboo.ODC_cveUrlBase} --disableCentral --disableOssIndex --proxyserver ${bamboo.PROXY_SERVER_HOST} --proxyport ${bamboo.PROXY_SERVER_PORT}

**Version of dependency-check used**
The problem occurs using version 6.1.6 of the cli via Bamboo pipeline script

**Log file**
build	19-May-2021 08:41:19	[WARN] Retire JS repository is empty or missing - attempting to force the update
build	19-May-2021 08:41:19	[ERROR] Exception occurred initializing RetireJS Analyzer.
build	19-May-2021 08:41:20	[INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
build	19-May-2021 08:41:20	[INFO] Finished Dependency Bundling Analyzer (0 seconds)
build	19-May-2021 08:41:20	[INFO] Analysis Complete (5 seconds)
build	19-May-2021 08:41:21	[ERROR] Unable to initialize the Retire JS respository

**Expected behavior**
Expect for ODC to complete activities successfully all the time but at the moment in is temperamental. There are no changes made to the build plan or ODC config when it does run successfully.

**Comment by jeremylong** [comment]
Unable to reproduce. Looking at your setup it appears you may be behind a proxy. The data for the retire JS analyzer is her: https://raw.githubusercontent.com/Retirejs/retire.js/master/repository/jsrepository.json

You can mirror that locally like you do with the NVD data.

**Comment by neil-n-brown** [comment]
I was able to resolve by proxy bypass to the the repo domain

**Comment by neil-n-brown** [comment]
I was able to resolve by proxy bypass to the the repo domain
