### ISSUE TITLE
How to fix sun.security.validator.ValidatorException

### ISSUE THREAD

**Issue by vijaya-lakshmi-venkatraman** [dependency-check/DependencyCheck#3402]
A newbie to Dependency Check here.
I have setup DC on my Windows machine and executing via CLI.
I see a couple of things:
1) Warning - An error occurred while analyzing 'some.dll' (Sonatype OSS Index Analyzer)
2) Error - Failed to request component-reports

Upon checking the logs I see that this is due to certificate:
`Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
`
Tried to JAVA_OPTS as mentioned [here](https://github.com/jeremylong/DependencyCheck/issues/2222#issuecomment-536521721) but the issue still persists.

Please can someone help me how to fix this?

**Comment by vijaya-lakshmi-venkatraman** [comment]
I did go through https://github.com/jeremylong/DependencyCheck/issues/728 as well.
Should I be downloading & compiling InstallCerts.java file and run it like this:
`java https://ossindex.sonatype.org/`

Please advice

**Comment by jeremylong** [comment]
Without knowing your environment - yes, my guess is you need to install the cert.

**Comment by vijaya-lakshmi-venkatraman** [comment]
I tried downloading the sonatype org cert, added to the keystore but the issue still persists. 
please can you tell me if there is anything i could try?

**Comment by ChameleonTartu** [comment]
@vijaya-lakshmi-venkatraman Did you manage to resolve this issue?

@jeremylong It looks like I have the same issue in Travis CI (Mac OSX) Java 9 and Java 10 versions: https://travis-ci.com/github/ChameleonTartu/amazon-mws-client-runtime-maven/jobs/516159284

Is there any way I can overcome it for non-LTS releases? Note: It works in Linux Java 8 - 11 versions.

**Comment by jeremylong** [comment]
Only thing I can think of is install the cert. In some cases you may have a proxy that might be causing issues - in which case you would need to install the cert used by the proxy.

**Comment by vijaya-lakshmi-venkatraman** [comment]
@ChameleonTartu No, I have tried adding the certificate of the failing website (Sonatype.org from my logs) to my JAVA cacerts file. The issue still persists. 
@jeremylong Yes, I am behind corporate proxy. Please can you provide any documentation/reference to install the cert used by the proxy?
