### ISSUE TITLE
False Positive on batik-i18n-1.14.jar

### ISSUE THREAD

**Issue by jody-mcdonnell** [dependency-check/DependencyCheck#3407]
False positive on library  batik-i18n-1.14.jar - reported as `cpe:2.3:a:i18n_project:i18n:*:*:*:*:*:asp.net:*:*`
```xml
        <dependency>
            <groupId>org.apache.xmlgraphics</groupId>
            <artifactId>batik-codec</artifactId>
            <version>1.14</version>
            <exclusions>
                <exclusion>
                    <groupId>xml-apis</groupId>
                    <artifactId>xml-apis</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>commons-logging</groupId>
                    <artifactId>commons-logging</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>commons-io</groupId>
                    <artifactId>commons-io</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```
Note that batik-codec includes batik-i18n.
Note that this is the same cpe/behaviour as reported in [https://github.com/jeremylong/DependencyCheck/issues/3352](url)

**Comment by mprins** [comment]
duplicate

**Comment by jody-mcdonnell** [comment]
As mentioned by @mprins, this was a duplicate. The original issue is https://github.com/jeremylong/DependencyCheck/pull/3369, and that issue has been merged.

Closing this issue.

**Comment by jody-mcdonnell** [comment]
This was a duplicate of https://github.com/jeremylong/DependencyCheck/pull/3369.
