### ISSUE TITLE
Ignoring dev dependencies: required section not ignored

### ISSUE THREAD

**Issue by inaboe** [dependency-check/DependencyCheck#3409]
Hello,
I have a question regarding the dev dependencies in the package-lock.json.
We are using the owasp dependency maven plugin in version 6.2.0 in a java project with angular frontend.
The settings are: nodeAuditSkipDevDependencies: true. 
This results in a report which seems to ignore the 
dev dependency itself but not the depencencies in the required section. e.g. if the following dependency is part of the package-lock.json , url-parse is found in the report.
`sockjs-client": {
      "version": "1.4.0",
      "resolved": "https://registry.npmjs.org/sockjs-client/-/sockjs-client-1.4.0.tgz",
      "integrity": "sha512-5zaLyO8/nri5cua0VtOrFXBPK1jbL4+1cebT/mmKA1E1ZXOvJrII75bPu0l0k843G/+iAbhEqzyKr0w/eCCj7g==",
      "dev": true,
      "requires": {
        "debug": "^3.2.5",
        "eventsource": "^1.0.7",
        "faye-websocket": "~0.11.1",
        "inherits": "^2.0.3",
        "json3": "^3.3.2",
        "url-parse": "^1.4.3"
      }`

We also tried it with the following parameters: disableNodeJS: true and disableRetireJS: true which didn't change the result.

Thanks,
Ina

**Comment by jeremylong** [comment]
Unable to reproduce:

```bash
npm install sockjs-client@1.4.0 --save-dev
dependency-check.sh -o . -s . --disableNodeJS --disableRetireJS
```

`url-parse` was not included in the report.
