### ISSUE TITLE
Report CPE link broken

### ISSUE THREAD

**Issue by taicomjp** [dependency-check/DependencyCheck#3411]
**Describe the bug**
The CPE URL on html report(dependency-check-report.html) is broken(Page Not Found)

**Version of dependency-check used**
The problem occurs using version 6.2.0 of the cli

**Log file**
When reporting errors, 99% of the time log file output is required. Please post the log file as a [gist](https://gist.github.com/) and provide a link in the new issue.

**To Reproduce**
1. Download & Extract Dependency Check from Github
2. Set up PATH variable to the location of the script
3. Go to the path where the bat file is located
4. Run depedency-check.bat --project xxxxxxx --scan "D:\Jenkins\workspace\xxxxx" 

**Expected behavior**
NVD CPE link

**Additional context**
Using Windows Server 2019

**Comment by jeremylong** [comment]
I'm unable to reproduce this. When I generate the report I get links like this:

https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Aapache&cpe_product=cpe%3A%2F%3Aapache%3Acommons_fileupload&cpe_version=cpe%3A%2F%3Aapache%3Acommons_fileupload%3A1.2.1

Which takes you to the NVD.  Is there a specific dependency that generates broken links?
