### ISSUE TITLE
Oodles of "[WARNING] No analyzer could be found for..."

### ISSUE THREAD

**Issue by wilx** [dependency-check/DependencyCheck#3418]
**Describe the bug**

I get oodles of warnings like this

```
[WARNING] No analyzer could be found for 'org.apache.servicemix.bundles:org.apache.servicemix.bundles.spring-beans:jar:4.3.30.RELEASE_1:compile' in project com.XYZ
```

But the report seems normal.

**Version of dependency-check used**

The problem occurs using version 6.2.0 of the depdendency-check-maven plugin.

**Comment by jeremylong** [comment]
Any chance you could provide a `pom.xml` that demonstrates the behavior?

**Comment by wilx** [comment]
I do the `aggregate` on top POM of the entire project. The `com.XYZ` were always some submodule at least 2 levels deep in the project modules hierarchy.

**Comment by jeremylong** [comment]
I'm more interested in how `org.apache.servicemix.bundles:org.apache.servicemix.bundles.spring-beans:jar:4.3.30.RELEASE_1:compile` was included in the pom.

**Comment by wilx** [comment]
There is a component of the product which uses `osgilibs:org.springframework.core` dependency (our nearly empty artifact which contains `Require-Bundle: org.apache.servicemix.bundles.spring-core;bundle-version="${version.servicemix}";visibility:=reexport`). The `osgilibs:org.springframework.core` POM has the ServiceMix dependency as `provided`:

```
	<dependencies>
		<dependency>
			<groupId>org.apache.servicemix.bundles</groupId>
			<artifactId>org.apache.servicemix.bundles.spring-core</artifactId>
			<version>${version.servicemix}</version>
			<scope>provided</scope>
		</dependency>
	</dependencies>
```

**Comment by jeremylong** [comment]
I've figured out what is causing the warnings. They can be safely ignored and a patch will be included in the next release.
