### ISSUE TITLE
Feature request: DotNet configure version

### ISSUE THREAD

**Issue by Marvin-Brouwer** [dependency-check/DependencyCheck#3424]
I noticed I got some vulnerability reports on NuGet packages that were reported for netcore2.1 and lower however, my application is on netcore3.1.
Because of that, I'd like to have a flag where I can set the dotnet version to eliminate the need of suppressing every vulnerability that is not applicable.

**Comment by jeremylong** [comment]
Sounds like you have some false positives. I'd rather see which dependencies are causing the misidentification and fix the engine. Some of them may already be flagged as issues with the `FP Report` label.

**Comment by jeremylong** [comment]
I have no intention of building a feature to specify the .net version and hide related vulnerabilities. Instead, we need to tune the engine.
