### ISSUE TITLE
What is the top scanned counts refer to ?

### ISSUE THREAD

**Issue by asamkamalesan** [dependency-check/DependencyCheck#3429]
So, in the report - I see the counts and version are something like below.

```
-      dependency-check version: 6.2.1
- 	Report Generated On: Tue, 8 Jun 2021 17:42:28 GMT
- 	Dependencies Scanned: 3 (3 unique)
- 	Vulnerable Dependencies: 0
- 	Vulnerabilities Found: 0
- 	Vulnerabilities Suppressed: 0
```

What are these counts refer to ? - because in my angular application, I am pretty much sure I have more than 3 deps apart from devDeps, but you can see in the above counts - it says it scanned 3 deps ?

So, I just want to know what are the counts refer to in the above bullets ?

**Comment by asamkamalesan** [comment]
If there are any document explaining about it also much enough - I scanned my level best in the OWASP site, but unable to find a related document. Please let me know if anything available on explaining the scanned reports.

**Comment by jeremylong** [comment]
Unfortunately - the files scanned for npm projects is just the number of vulnerable dependencies. For many of the other tech stacks that are analyzed it is the full count of everything that is scanned.  We are working on making this consistent.

**Comment by asamkamalesan** [comment]
> Unfortunately - the files scanned for npm projects is just the number of vulnerable dependencies. For many of the other tech stacks that are analyzed it is the full count of everything that is scanned. We are working on making this consistent.

But vulnerable dependencies shows 0 in the above report !! - so still confused !!!
