### ISSUE TITLE
False Positive on json-logic-js:2.0.1

### ISSUE THREAD

**Issue by engmengchoon** [dependency-check/DependencyCheck#3433]
False positive on nodejs module json-logic-js - reported as cpe:2.3:a:*:json-logic-js:2.0.1:*:*:*:*:*:*:*

  "main": "logic.js",
  "name": "json-logic-js",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/jwadhams/json-logic-js.git"
  }
  "version": "2.0.1"

For reference, the following npm advisories has stated remediation upgrade to version 2.0.0:
https://www.npmjs.com/advisories/1542

**Comment by aikebah** [comment]
Reported the invalid vulnerability details to the source of the FP: the OSSIndex

**Comment by aikebah** [comment]
Resolved by update of OSSINDEX
