### ISSUE TITLE
DependencyCheck 6.2.1 freezes during scanning

### ISSUE THREAD

**Issue by proo4509** [dependency-check/DependencyCheck#3434]
the dependencycheck 6.2.1 freezes after [INFO] Finished False Positive Analyzer. Nothing happens after that. No error, no time out.

[INFO] Analysis Started
[INFO] Finished Archive Analyzer (0 seconds)
[INFO] Finished File Name Analyzer (0 seconds)
[INFO] Finished Jar Analyzer (0 seconds)
[INFO] Finished Central Analyzer (5 seconds)
[INFO] Finished Dependency Merging Analyzer (0 seconds)
[INFO] Finished Version Filter Analyzer (0 seconds)
[INFO] Finished Hint Analyzer (0 seconds)
[INFO] Created CPE Index (1 seconds)
[INFO] Finished CPE Analyzer (1 seconds)
[INFO] Finished False Positive Analyzer (0 seconds)

version 6.2.1
same scan with 6.1.6 works fine

**Comment by transparentink** [comment]
I encountered same issue with 6.2.1.
If I leave the scan running for multiple hours, it eventually provides an error.
I don't want to hijack your issue with my error log, but I can post it if needed.

Downgrading to version 6.1.6 resolved the issue.

**Comment by mprins** [comment]
duplicate, see https://github.com/jeremylong/DependencyCheck/issues/3408#issuecomment-858493309
