### ISSUE TITLE
Error accessing NVD meta data

### ISSUE THREAD

**Issue by tabacman86** [dependency-check/DependencyCheck#3442]
Replicate on both Jenkins and CLI.
Error of:
`[ERROR] Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta
org.owasp.dependencycheck.data.update.exception.UpdateException: Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta`

Can't resolve the URL.

Are there any alternatives?

**Comment by mprins** [comment]
You can host your own mirror of the feeds or use a centralized database with the CVE data, both of which you can  keep up-to-date using a separate process.

**Comment by tabacman86** [comment]
Thanks - is there any documentation how to host it?

**Comment by Georg311** [comment]
FYI, I have the same problem with the latest Version, downloading fails

Using a local Mirror works

**Comment by Georg311** [comment]
FYI, nvd.nist.gov is down
https://twitter.com/NIST/status/1404079064982380545

**Comment by hoerup** [comment]
seems like nist.gov has spun up an extra nameserver so resolution of nvd.nist.gov works again

**Comment by tabacman86** [comment]
Thank you all!
