### ISSUE TITLE
postgresql driver always saying not detected

### ISSUE THREAD

**Issue by mehdibenfeguir** [dependency-check/DependencyCheck#3447]
using maven  this is few contents of my pom.xml

<plugin>
                <groupId>org.owasp</groupId>
                <artifactId>dependency-check-maven</artifactId>
                <version>6.2.0</version>
                <configuration>
	                <autoUpdate>true</autoUpdate>
	                <cveValidForHours>5</cveValidForHours>
	                 <databaseDriverName>org.postgresql.Driver</databaseDriverName>   // tried org.postgresql also
                    <connectionString>jdbc:postgresql://databaselinkhere</connectionString>
                    <databaseUser>jenkins</databaseUser>
                    <databasePassword>${dbpass}</databasePassword>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            
                             <goal>update-only</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

<dependency>
                        <groupId>org.postgresql</groupId>
                        <artifactId>postgresql</artifactId>
                        <version>42.2.21</version>
        </dependency>

**Comment by mehdibenfeguir** [comment]
exact message as a result of "maven clean verify"

[ERROR] Failed to execute goal org.owasp:dependency-check-maven:6.2.0:update-only (default) on project mul-project-template-artifact: An exception occurred connecting to the local database. Please see the log file for more details.: Unable to load database driver: Unable to load database driver 'org.postgresql.Driver' -> [Help 1]


also when using org.postgresql only this is the result 
[ERROR] Failed to execute goal org.owasp:dependency-check-maven:6.2.0:update-only (default) on project mul-project-template-artifact: An exception occurred connecting to the local database. Please see the log file for more details.: Unable to load database driver: Unable to load database driver 'org.postgresql' -> [Help 1]

**Comment by jeremylong** [comment]
How are you including the postgresql driver?  For maven the best way would be to do something like this:

```xml
    <build>
        <plugins>
            <plugin>
                <groupId>org.owasp</groupId>
                <artifactId>dependency-check-maven</artifactId>
                <version>6.2.2</version>
                <dependencies>
                    <dependency>
                        <groupId>org.postgresql</groupId>
                        <artifactId>postgresql</artifactId>
                        <version>42.2.20</version>
                    </dependency>
                </dependencies>

<!-- any other configuration -->

            </plugin>
        </plugins>
    </build>
```

**Comment by mehdibenfeguir** [comment]
Thanks
That worked, I had declared the postgresql dependency in the general dependencies tag instead of inside plugin tag
