### ISSUE TITLE
Default CVSS Version

### ISSUE THREAD

**Issue by skharab-anaplan** [dependency-check/DependencyCheck#3448]
Hi Team,

I wanted to confirm what is the CVSS version used in maven plugin reporting and is there is a way to change or override that version?

**Comment by jeremylong** [comment]
CVSS scores are complicated. Some of the vulnerabilities reported do not even have a CVSS score. There are others that may have a CVSS v2 but not a CVSS v3. We do our best with what we have and are open to suggestions and PRs.

You can see in the velocity template how we are determining the "highest" severity for a given dependency: https://github.com/jeremylong/DependencyCheck/blob/3e352c4fbf7aa5c2ffd9fda43f7461a1188732cd/core/src/main/resources/templates/htmlReport.vsl#L762-L785

Similar logic exists in other places where we use the severity or score - we look at all the severity scores we have and evaluate them all.  Yes, not ideal - but to deal with inconsistent data its what was built.

**Comment by marcelstoer** [comment]
Think what you're looking for is here: https://jeremylong.github.io/DependencyCheck/dependency-check-maven/check-mojo.html#failBuildOnCVSS

> The default is 11 which means since the CVSS scores are 0-10, by default the build will never fail.

**Comment by skharab-anaplan** [comment]
I think collectively I have got my answer. Thanks a lot guys,
