### ISSUE TITLE
poor performance of sorting by Highest Severity column in HTML report

### ISSUE THREAD

**Issue by wilx** [dependency-check/DependencyCheck#3449]
**Describe the bug**
My HTML report is 35,619,264 bytes in size. I can click on Dependency column and it sorts nearly imediately. But when I click the Highest Severity the page stops responding.

**Version of dependency-check used**
The problem occurs using version 6.2.2 of the Maven plugin HTML report.

**Log file**
```
Scan Information (show less):

    dependency-check version: 6.2.2
    Report Generated On: Wed, 16 Jun 2021 15:20:19 +0200
    Dependencies Scanned: 6802 (6468 unique)
    Vulnerable Dependencies: 185
    Vulnerabilities Found: 841
    Vulnerabilities Suppressed: 43
    NVD CVE Checked: 2021-06-16T15:17:13
    NVD CVE Modified: 2021-06-16T14:00:53
    VersionCheckOn: 2021-06-16T15:17:13
```

**To Reproduce**
1. Open sufficiently large generated HTML report.
2. Click on Highest Severity column
3. ...
4. See browser pop up
![image](https://user-images.githubusercontent.com/1098563/122227829-8aec2180-ceb7-11eb-8996-d504076edb37.png)

**Expected behavior**
Sorting by any column should be (nearly) instantaneous.

**Comment by shuehner** [comment]
Hello,
I'm seeing similar huge slowness even with smaller html reports  (around 6MB) where content comes from jar analyzer plugin (using 6.1.6 version).

**Comment by mprins** [comment]
sorting is done using the "jQuery Stupid Table Plugin by Joseph McCullough" see: https://github.com/jeremylong/DependencyCheck/blob/3e352c4fbf7aa5c2ffd9fda43f7461a1188732cd/core/src/main/resources/templates/htmlReport.vsl#L35

you are welcome to propose a better alternative

**Comment by wilx** [comment]
Well, it is capable of sorting by the Dependency column fast but not by the Highest Severity. I am suggesting there is maybe something on our part that is wrong with how we provide the sortable data set to it?

**Comment by wilx** [comment]
I see one potential issue. The template declares the Highest Severity field as sorted by `int` value: [`<th class="sortable" data-sort="int"    title="The highest CVE Severity">Highest&nbsp;Severity</th>`](https://github.com/jeremylong/DependencyCheck/blob/main/core/src/main/resources/templates/htmlReport.vsl#L706)

But the rendered report contains floating point in the attribute value: `<td data-sort-value="98.0">CRITICAL</td>`

But the Stupid-Table-Plugin does support [`float`](https://github.com/joequery/Stupid-Table-Plugin/blob/master/stupidtable.js#L37).

**Comment by jeremylong** [comment]
thanks for the analysis and PR!
