### ISSUE TITLE
Performance improvements - 6.2.2

### ISSUE THREAD

**Issue by mfoo** [dependency-check/DependencyCheck#3454]
Hi! Firstly, thanks for this excellent project!

I was in the middle of preparing a bug report for 6.2.0, but I found #3408 and indeed 6.2.2 seems to resolve the problem :+1:. As part of that report I ran the dependency check on our codebase under YourKit by specifying `-agentpath` as part of `JAVA_OPTS` to see if I could locate the problem. The scan found some things though that might be useful to report. Below is the flame graph for the analysis that I've annotated. The project is a monorepo and has a lot of dependencies that we're in the process of cleaning up (`Dependencies Scanned: 92768 (44297 unique)`), so this size may be relative to the performance. Luckily the flame graph shows % of time so hopefully it'll be similar on smaller projects.

![Flame graph](https://i.imgur.com/DSqkkn1.png)

**Issue 1 and Issue 2**
8% (170 seconds) of my analysis was spent in `Dependency.getVulnerableSoftwareIdentifiers`, which looks like this:

```java
public synchronized Set<Identifier> getVulnerableSoftwareIdentifiers() {
    return Collections.unmodifiableSet(new TreeSet<>(this.vulnerabileSoftwareIdentifiers));
}
```

(Also note the typo `vulnerabile` -> `vulnerable`)

`getSoftwareIdentifiers` does the same thing, as does `getSuppressedIdentifiers`:

```java
public synchronized Set<Identifier> getSoftwareIdentifiers() {
    return Collections.unmodifiableSet(new TreeSet<>(softwareIdentifiers));
}
```

`getSoftwareIdentifiers` took 11% (232 seconds) of my build just calling `TreeSet.addAll`.

I was wondering if the additional `new TreeSet<>(...)` was unnecessary? `vulnerabileSoftwareIdentifiers` is already a `TreeSet<>`, meaning `new TreeSet<>(...)` will sort it again, and then it's returning `Collections.unmodifiableSet` which I don't think has any sorting guarantees so any time spent sorting is wasted.

After removing these two `new TreeSet<>(...)`s for issue 1 and issue 2 the tests still pass and the flame graph looks better. `DependencyBundlingAnalyzer.evaluateDependencies` doesn't appear in the flame graph at all.

All in all it removed somewhere between 5 and 10 minutes off of my build (the runtime seems to fluctuate, so my confidence here is low - the change I have seen could be due to that fluctuation and I'd appreciate thoughts from somebody who knows the project better!).

Here's the flame graph after:

![Optimised flame graph](https://i.imgur.com/fzWl5yy.png)

**Issue 3**
`Dependency.getMainAndroidDependency` took 512 seconds (24%) of my build. It sounds like this is related to Android on mobile devices, but my project is not an Android project and so ideally this section could be skipped.

Unfortunately this method:

```java
public File getActualFile() {
    return new File(this.actualFilePath);
}
```

on my Linux laptop with an SSD seems to be fairly slow. Since it's only being used to get the `File.getName()` it doesn't seem like there's much point it internally calling `UnixFileSystem.normalize`. I looked in `Dependency` and added `getActualFileName`:

```java
public String getActualFileName() {
    return Paths.get(this.actualFilePath).getFileName().toString();
}
```

and modified `getMainAndroidDependency` to call it. The tests all pass but it looks like it got slower. Is there a faster method of doing this? Also, can I disable this Android check?

**Issue 4**
It looks like `RetireJSAnalyzer.analyzeDependency` spends quite a lot of time calls in `Matcher.find` [here](https://github.com/h3xstream/burp-retire-js/blob/50fcfb32e87283a8168f6c64724f526012fbb7f4/retirejs-core/src/main/java/com/h3xstream/retirejs/util/RegexUtil.java#L20) via [this method](https://github.com/h3xstream/burp-retire-js/blob/master/retirejs-core/src/main/java/com/h3xstream/retirejs/repo/VulnerabilitiesRepository.java#L103), but I don't know enough to say if this is avoidable / could be run in paralel.

**Bonus issue**
I can see that `AbstractDependencyComparingAnalyzer.analyzeDependency` spends 120-140 seconds in my builds calling `Iterable.forEach`, and all of the time is spent inside `Dependency.equals`. This is `dependenciesToRemove.forEach((d) -> engine.removeDependency(d));`, where this removes the dependency from a `List<Dependency>`. Is it possible to use a `HashSet` instead? (Is ordering important?) When the list is large this is quite slow.

---

Any thoughts would be greatly appreciated - I don't mind raising pull requests but I'd like to make sure these would be useful first!

**Comment by jeremylong** [comment]
Sorry about the delay in getting back to this.  For issue 3 see https://github.com/jeremylong/DependencyCheck/pull/3554. I think that should reduce the execution time.

**Comment by jeremylong** [comment]
For issue 4, while not my library, I agree that the `find` could probably be run in parallel.

**Comment by jeremylong** [comment]
For the bonus issue - if we switched to a HashSet we would have to convert it back to a list and sort it prior to writing the reports. However, during the longer analysis phase a HashSet could likely be used.

**Comment by jeremylong** [comment]
I believe most of the identified issues have been resolved. There was one issue around `dependenciesToRemove.forEach((d) -> engine.removeDependency(d))` that will not be resolved yet.
