### ISSUE TITLE
Allow to specify source of suppressed shaded dependencies

### ISSUE THREAD

**Issue by IdamkinI** [dependency-check/DependencyCheck#3459]
As far as I know right now the shaded dependencies should be suppressed as regular ones by specifying ID of shaded dependency in some way. There are cases where pom files of vulnerable dependencies are included in jar meta inf however the class files are not, in which case the plugin will detected not really shaded dependency as vulnerable.

I would preferer to specify the source of such shaded dependency in suppression, so in case it end up in project as transitive dependency from other source (another dependency that shades it, or as a regular one) the plugin will still report it as vulnerable.

**Comment by jeremylong** [comment]
This request does not align with the project direction. Currently, suppressions are done at the dependency level not at the transitive level.

**Comment by IdamkinI** [comment]
I understand that when vulnerable dependency find it way in the project it doesn't really matter where it comes from.

In situation I've described the vulnerable dependency was falsely detected as being included in the project. It actually wasn't shaded in the jar as reported by dependency plugin, but instead just the pom file was put in the meta info.

The only way I can deal with it right now is to suppress the vulnerable dependency as it is not really included as dependency in my project. In that case I would have no way of detecting the case where it was actually included in the project as it is already suppressed.

Since the shaded dependency detection is not ideal, and such false positive shaded detections are possible, I would argue there is still value in this feature for shade dependencies.

**Comment by IdamkinI** [comment]
I understand that when vulnerable dependency find it way in the project it doesn't really matter where it comes from.

In situation I've described the vulnerable dependency was falsely detected as being included in the project. It actually wasn't shaded in the jar as reported by dependency plugin, but instead just the pom file was put in the meta info.

The only way I can deal with it right now is to suppress the vulnerable dependency as it is not really included as dependency in my project. In that case I would have no way of detecting the case where it was actually included in the project as it is already suppressed.

Since the shaded dependency detection is not ideal, and such false positive shaded detections are possible, I would argue there is still value in this feature for shaded dependencies.
