### ISSUE TITLE
Is there a way to exclude devDependencies from scans for npm projects?

### ISSUE THREAD

**Issue by mvs5465** [dependency-check/DependencyCheck#3462]
Say a project has [dev dependencies](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#devdependencies) and their package.json looks [like this](https://docs.npmjs.com/specifying-dependencies-and-devdependencies-in-a-package-json-file):

```
"name": "my_package",
"version": "1.0.0",
"dependencies": {
  "my_dep": "^1.0.0",
  "another_dep": "~2.2.0"
},
"devDependencies" : {
  "my_test_framework": "^3.1.0".
  "another_dev_dep": "1.0.0 - 1.2.0"
}
```
is there a way to only scan the `dependencies` and not the `devDependencies`?

Similar but not the same question as https://github.com/jeremylong/DependencyCheck/issues/3409

**Comment by Marx314** [comment]
humm like using args --nodeAuditSkipDevDependencies
https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html ?

**Comment by mvs5465** [comment]
Perfect, thanks @Marx314 !
