### ISSUE TITLE
Export Control Classification Number

### ISSUE THREAD

**Issue by mjofwh** [dependency-check/DependencyCheck#3464]
Hi,

Could you provide me the Export Classification Control Number(ECCN) information of your software?

If you do not have your software classified with an ECCN, please kindly answer the following questions so that we may self-classify:

Q1. Does the software perform any encryption or utilize any encryption processes? Yes/No

Q2. In case that the answer to Q1 is Yes, please indicate whether you notified BIS and ENC Encryption Request Coordinator via email of the Internet location (e.g., URL or Internet address) of your publicly available encryption source code.
Or please indicate whether you provided each of them a copy of your publicly available encryption source code or not.

Thank you in advance for your cooperation.
Regards,

**Comment by mprins** [comment]
there is no ECCN, there is TLS encryption. 
Please do your homework yourself and check the available source code or pay up by sponsoring the developer: https://github.com/sponsors/jeremylong

**Comment by mjofwh** [comment]
OK，thank you!
