### ISSUE TITLE
Analyzing each package.json of individual node_modules 

### ISSUE THREAD

**Issue by wassermandh** [dependency-check/DependencyCheck#3484]
Hello,

I'm pretty new to dependency-check and am attempting to implement it in some of our Python and JS repos. I've noticed that when I run it in the root of my project (e.g. dependency-check --project "project-name" --scan . ) I will often see warnings like this: 

[WARN] Unable to find node module: /Users/\*\*/my_project/node_modules/package/\*\*/node_modules/\*\*/package.json

So it looks like dependency-check is looking at the package.json of my node_modules. I am able to get rid of these warnings using the "--exclude" option, however, I'm wondering if there is any recommendation regarding whether we should ignore these or not. Would we be potentially missing anything important if we did? Any guidance is greatly appreciated -- thank you!

**Comment by jeremylong** [comment]
Sorry for the delayed response - no, you can safely ignore these warnings. These are coming from the node package analyzer - which is slated to be re-written. In fact, I would recommend just disabling the node package analyzer and only using the node audit analyzer.
