### ISSUE TITLE
Backwards compatibility of database with older clients

### ISSUE THREAD

**Issue by ghost** [dependency-check/DependencyCheck#3486]
Since the documentation is scarce on the matter, I'm wondering if there's something one should look out for when upgrading through versions. In my case it's a 6.1.* -> 6.2.* update. Does skimming through the schema diff between versions suffice? 
Are more recent databases with a schema from, for example, version 6.2.* capable to communicate with 6.1.* clients without issues?

**Comment by jeremylong** [comment]
We generally try to keep things backwards compatible - the tool itself will report if the database is incompatible with the version of ODC being used. 

TL;DR - there is a schema version and a version of ODC that really do not have anything in common. ODC is able to a database with any schema with the same major version and and an equal or higher minor version. This is not very transparent to the user as we do not report the database schema version. If there is a breaking database schema change we try to note that in the release notes and we will increment the major version of ODC itself.

**Comment by ghost** [comment]
Thank you for the quick reply, this answers my question.
