### ISSUE TITLE
Maven dependency-check does not honor -Dformat or -Dformats options

### ISSUE THREAD

**Issue by gl-mc** [dependency-check/DependencyCheck#3489]
**Describe the bug**
When running the maven dependency-check plugin via the command line,  options for report output formats (-Dformat=XML or -Dformats=XML,HTML,CSV) cannot be specified via the command line. Other options like e.g. -DassemblyAnalyzerEnabled=false work fine. Supplying output formats via the command line should also be possible, when formats are not specified in the POM. The HTML and CSV reports are always generated regardless of the format specification on the command line.

**Version of dependency-check used**
The problem occurs using version 6.1.1, 6.1.5 to 6.2.2 of the maven plugin. I did not test versions prior to 6.1.1

**Log file**
https://gist.github.com/gl-mc/9835b445e0f28b4b35fb1b9eb034202b

**To Reproduce**
1. Choose a Java project of your choice
2. Remove any dependency-check-maven plugin sections from the POM, e.g. by using the xslt stylesheet https://gist.github.com/gl-mc/732f3c66dfb00698a42a5fb973d65a36 and xstlproc. Command line would be 
xsltproc dep-check-pom-remover.xslt pom.xml > pom.new.xml && mv pom.new.xml pom.xml
3. Run a mvn plugin target with the -Dformat or -Dformats switch, e.g.
mvn org.owasp:dependency-check-maven:6.2.2:check -DfailOnError=false -DskipProvidedScope=true -DnuspecAnalyzerEnabled=false -DassemblyAnalyzerEnabled=false -Dformat=XML -Dformats=HTML,CSV,XML
4. only HTML and CSV files are produced in target/ folder, but no XML file as expected. Other switches seem to work correctly.

**Expected behavior**
File formats defined with -Dformat and -Dformats are created in target/ directory

**Additional context**
I also tried to use -DFormat(s) (with a capital F), but that didn't make any difference

**Comment by jeremylong** [comment]
Just ran the following and got a JSON report:

```bash
$ mvn verify -Dformat=JSON
...
[INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
[INFO] Finished Dependency Bundling Analyzer (0 seconds)
[INFO] Analysis Complete (23 seconds)
[INFO] Writing report to: /Users/jeremy/Projects/odc-falsepositives/target/dependency-check-report.json
...
```

Or using formats:

```bash
$ mvn verify -Dformats=XML,CSV
...
[INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
[INFO] Finished Dependency Bundling Analyzer (0 seconds)
[INFO] Analysis Complete (23 seconds)
[INFO] Writing report to: /Users/jeremy/Projects/odc-falsepositives/target/dependency-check-report.xml
[INFO] Writing report to: /Users/jeremy/Projects/odc-falsepositives/target/dependency-check-report.csv
...
```

**Comment by gl-mc** [comment]
Agree it's a FP.

**Comment by gl-mc** [comment]
The settings were introduced through a parent pom, which was not removed when generating mvn help:effective-pom.
Thanks!
