### ISSUE TITLE
Keeping suppression files clean

### ISSUE THREAD

**Issue by creckord** [dependency-check/DependencyCheck#3491]
**Is your feature request related to a problem? Please describe.**
It is often the case that the dependency check finds a vulnerability that for whatever reason we decide to not act on. Either because there currently is no fix available, or because it's not deemed relevant, or something keeps us from updating at this point.

So the vulnerability ends up in a local suppression file in the project.

Later, we do end up updating the affected dependency, but of course nobody remembers cleaning up the suppressions file, making it accumulate cruft over time. This makes it hard to check up on the suppressions that are actually still relevant.

**Describe the solution you'd like**
It would be great to have either a flag for the regular dependency check, or a separate goal, that compares the currently detected vulnerabilities against the suppressions file and warns (or fails) on every suppression entry that didn't match anything.

**Comment by Marx314** [comment]
We had similar issue and decided to use ["until" attribute of the "suppress" tag](https://jeremylong.github.io/DependencyCheck/general/suppression.html) when we had a library that no fixes existed. We simply put up a date to review the vulnerability. That way we enforce a regular review of our vulnerable dependency.

Also Dependency Check warn of "expired rule" for the suppression file so you see the rule that are expired and are actually already fixed. <3

**Comment by creckord** [comment]
Ah, wasn't aware of the until attribute. Yes, that looks good.
