### ISSUE TITLE
brew install dependency-check - - not installed

### ISSUE THREAD

**Issue by davehodg** [dependency-check/DependencyCheck#3493]
On a new, up to date (11.4) Mac, ran brew install dependency-check. Nothing installed. Got a logs dir though!

Don't know which version of dependency-check as it didn't seem to install.

**Comment by aikebah** [comment]
Brew formula is external to this repository. You should file your issue with the [brew community](https://github.com/Homebrew/homebrew-core).
Current [brew formula](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/dependency-check.rb) should install version 6.2.2 from the looks of it.
