### ISSUE TITLE
False Positive on mssql-django

### ISSUE THREAD

**Issue by poipoii** [dependency-check/DependencyCheck#3500]
False Positive on mssql-django - 1.0rc1: https://pypi.org/project/mssql-django/#files
reported as `cpe:2.3:a:django_project:django:0.96:*:*:*:*:*:*:*`, `cpe:2.3:a:django_project:django:1.0:*:*:*:*:*:*:*`

```
mssql-django==1.0rc1
```

**Comment by aikebah** [comment]
@poipoii Would you be able to generate the suppression XML snippet for the CPE? (There should be suppress button on the HTML report besides the CPE)
I have no Python environment to create it myself, but would be happy to include the suppression in the set of FP fixes I'm working on.

**Comment by poipoii** [comment]
@aikebah Sure
```
<?xml version="1.0" encoding="UTF-8"?>
<suppressions xmlns="https://jeremylong.github.io/DependencyCheck/dependency-suppression.1.3.xsd">
   <suppress>
      <notes><![CDATA[
      file name: mssql-django:1.0rc1
      ]]></notes>
      <packageUrl regex="true">^pkg:pypi/mssql\-django@.*$</packageUrl>
      <cpe>cpe:/a:django_project:django</cpe>
   </suppress>
</suppressions>
```

**Comment by aikebah** [comment]
@poipoii Thanks, included the suppression in the false-positive fixes set I'm working on
