### ISSUE TITLE
UpdateException: Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta

### ISSUE THREAD

**Issue by cforce** [dependency-check/DependencyCheck#3502]
Is this permanent?
How can i enable caching instead trying to resolve each time and possible fail because backend is not available
What upstream mirror are available?

```
Caused by: org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during analysis:
	UpdateException: Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta
		caused by DownloadFailedException: Download failed, unable to retrieve 'https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta'; Error downloading file https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta; unable to connect.
		caused by DownloadFailedException: Error downloading file https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta; unable to connect.
		caused by DownloadFailedException: Error retrieving https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta; received response code 503; Service Unavailable
	NoDataException: No documents exist
    at org.owasp.dependencycheck.Engine.throwFatalExceptionCollection (Engine.java:1089)

```

**Comment by jeremylong** [comment]
While ODC does cache data locally when used in some build environments the local cache gets thrown away. ODC has a data directory that contains an H2 database. The database should be saved between usage in build systems. For the CLI it the data directory is in the same folder hierachy as the shell script. For Maven it is stored in the local repository under `~/.m2/repository/org/owasp/dependency-check-data`. You can also specify the data directory in the ODC configuration.

An alternative would be to use a centralized database: https://jeremylong.github.io/DependencyCheck/data/database.html

Another option would be caching the NVD locally: https://jeremylong.github.io/DependencyCheck/data/mirrornvd.html

**Comment by cforce** [comment]
I use maven in azure devops which preserves maven repo. According to you shall not need to download each time but seems like that is not always working

**Comment by keysightschaefer** [comment]
Using the following:

 <groupId>org.owasp</groupId>
<artifactId>dependency-check-maven</artifactId>
<version>6.3.1</version>

I'm receiving the following related failure to download:

[ERROR] Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2005.meta
org.owasp.dependencycheck.data.update.exception.UpdateException: Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2005.meta
    at org.owasp.dependencycheck.data.update.NvdCveUpdater.getMetaFile (NvdCveUpdater.java:349)
    at org.owasp.dependencycheck.data.update.NvdCveUpdater.getUpdatesNeeded (NvdCveUpdater.java:401)
    at org.owasp.dependencycheck.data.update.NvdCveUpdater.update (NvdCveUpdater.java:122)
    at org.owasp.dependencycheck.Engine.doUpdates (Engine.java:873)
    at org.owasp.dependencycheck.Engine.doUpdates (Engine.java:846)

What is interesting is that I can CURL that same URL from my machine:

$ curl https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2005.meta
lastModifiedDate:2021-08-23T13:59:40-04:00
size:19934361
zipSize:1346182
gzSize:1346046
sha256:3A0C9FA9FF9630B8FF3B5988591A33ED99D3791014D0142883E9426643BCEFC3

And a browser properly shows the same content.

So this appears to be a bug related to the java code or JVM:

$ java --version
openjdk 11.0.3 2019-04-16 LTS
OpenJDK Runtime Environment Zulu11.31+11-CA (build 11.0.3+7-LTS)
OpenJDK 64-Bit Server VM Zulu11.31+11-CA (build 11.0.3+7-LTS, mixed mode)

**Comment by Tanmeet03** [comment]
same issue is coming for me too since yesterday

**Comment by jeremylong** [comment]
This should be fixed with https://github.com/jeremylong/DependencyCheck/pull/3690 - release pending.
