### ISSUE TITLE
I would like the Node Package Analyzer to be able to skip dev dependencies. 

### ISSUE THREAD

**Issue by Aeyaa** [dependency-check/DependencyCheck#3506]
In a project I work on, we frequently fail security scans due to dev only dependencies.  

**Describe the solution you'd like**
I am aware of the --nodeAuditSkipDevDependencies flag, and I would like a similar option to be available for the Node Package analyzer. 

**Additional context**
Sometimes the node package analyzer seems to pick up CVEs that the Node Audit analyzer does not, which makes me uncomfortable disabling the Node Package analyzer all together. Instead, I would just like to be able to skip dev dependencies in the Node Package analyzer.

**Comment by jeremylong** [comment]
The node package analyzer is planned for retirement as it is today. Some of its functionality will be folded into the node audit analyzer.

**Comment by tmuldoon** [comment]
@jeremylong Can you expand on your statement that the node package analyzer is planned for retirement? We have built a framework that depends upon the CVE id format and we'd prefer to use this analyzer over the node audit analyzer (which, as you know, uses a very different id format). So, why retire the n.p. analyzer?

PS: Thank you!! The tool is exceptional.

**Comment by jeremylong** [comment]
Some of the code from the node package analyzer will be incorporated into the node audit analyzer. So in the future the CVE data will be included with the info from Node Audit. Note, by not using the node audit analyzer you are likely going to have false negatives as the database used by `npm audit` has non-CVE related vulnerabilities.
