### ISSUE TITLE
jQuery version numbers

### ISSUE THREAD

**Issue by baffles** [dependency-check/DependencyCheck#3517]
**Describe the bug**
jQuery version numbers are influenced by the filename in some cases.

If I scan a folder containing jquery-1.6.4.min.js, Dependency-Check reports this as jquery version 1.6.4.min. If I rename that file to jquery-1.6.4.min2.js, again, I'll get version 1.6.4.min2. However, if I rename the file to jquery-3.5.1.min.js, then DC properly detects it as jquery 1.6.4 (and reports it as version 1.6.4).

**Version of dependency-check used**
The problem occurs using version 6.2.2 of the CLI.

**To Reproduce**
1. Put jQuery 1.6.4 in a folder (jquery-1.6.4.min.js)
2. Run a scan. The report will indicate jquery version "1.6.4.min"
3. Rename jquery-1.6.4.min.js to jquery-1.6.4.min2.js. Re-scan. The report will now indicate jquery version "1.6.4.min2"
4. Rename jquery-1.6.4.min2.js to jquery-3.5.1.min.js. Re-scan. The report will now indicate jquery version "1.6.4"
5. Finally, put another copy of jQuery 1.6.4 named jquery-1.6.4.min2.js alongside the fake jquery-3.5.1.min.js. Re-scan. The report will now indicate jquery version "1.6.4.min2" again and list jquery-3.5.1.min.js as a related dependency.

**Expected behavior**
I would expect the dependency to be reported as jquery version "1.6.4" in all scenarios above.

**Comment by jeremylong** [comment]
This is expected behavior using evidence based detection: https://jeremylong.github.io/DependencyCheck/general/internals.html

**Comment by baffles** [comment]
How are the version numbers detected for JS files? It seems like DC is able to verify the information being inferred from the filename, seemingly by hash, since if I rename the file to something completely incorrect, it gets detected properly.

In that case, why isn't hash a higher confidence than whatever random stuff comes from the filename? Is there any way for us to get the actual detected version for JS components? In my example above, "1.6.4.min" and "1.6.4.min2" are not real jQuery versions; it's just jQuery 1.6.4, but DC doesn't seem to expose that at all.
