### ISSUE TITLE
Azure DevOps task hangs when downloading the installer from GitHub

### ISSUE THREAD

**Issue by calumtomeny** [dependency-check/DependencyCheck#3518]
**Describe the bug**
The Azure DevOps task hangs at the point of `Downloading Dependency Check latest installer from GitHub..`

![image](https://user-images.githubusercontent.com/939917/125967976-a9509d26-4ab0-4882-80fa-010f11360bf4.png)

**Version of dependency-check used**
6.0.4

**Log file**
Screenshot provided above.

**To Reproduce**
1. Add the `Dependency Check` task to a build.
2. Run the build.

**Expected behavior**
The task executes successfully or an error is thrown.

**Additional context**
I have added some logging to the task:
```
console.log('Getting latest...');
let response = yield client.get(url);
console.log('...Downloaded latest.');
```
In the case above the first log would execute but the second log was never reached.

**Comment by jeremylong** [comment]
Consider opening the ticket on the azure devops issues: https://github.com/dependency-check/azuredevops
