### ISSUE TITLE
Use case to use a mirror of CVE contents when the plugin maintains its own ?

### ISSUE THREAD

**Issue by tvdinh** [dependency-check/DependencyCheck#3519]
My understanding is that the plugin downloads and maintains its own CVE content. And there's an example of manually configuring a mirror of the CVE content explicitly: https://jeremylong.github.io/DependencyCheck/dependency-check-maven/index.html (Example 5):

```
<project>
    ...
    <build>
        ...
        <plugins>
            ...
            <plugin>
                <groupId>org.owasp</groupId>
                <artifactId>dependency-check-maven</artifactId>
                <version>6.2.2</version>
                <configuration>
                    <cveUrlModified>http://internal-mirror.mycorp.com/nvdcve-1.1-modified.json.gz</cveUrlModified>
                    <cveUrlBase>http://internal-mirror.mycorp.com/nvdcve-1.1-%d.json.gz</cveUrlBase>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            ...
        </plugins>
        ...
    </build>
    ...
</project>
```

My question is why it is (in some case) needed ? Is this to improve performance as it has a local cache ? If so isn't required to be downloaded every run ?

**Comment by mprins** [comment]
because corporate policies exist to make a developers life harder... eg. "a build server can not connect to the internet"

**Comment by jeremylong** [comment]
https://jeremylong.github.io/DependencyCheck/data/index.html

**Comment by tvdinh** [comment]
> https://jeremylong.github.io/DependencyCheck/data/index.html

thanks.
