### ISSUE TITLE
Additional OssIndexAnalyzer config options to prevent HTTP 429 responses on large scans.

### ISSUE THREAD

**Issue by RasmusOlesen** [dependency-check/DependencyCheck#3521]
We are currently scanning +10k dependencies (Dependencies Scanned: 11447 (11438 unique))
When the oss_cache directory is cleared or expires, we always run into "To Many Requests" errors from the OssIndexAnalyzer.
We then need to run the scan multiple times, getting the same error, until the oss_cache is fully populated again.

I have a couple of ideas on how to fix this:

**Add a batchSize config option: analyzer.ossindex.batchsize**
The default batchsize in org.sonatype.ossindex.service.client.OssindexClientConfiguration is set to 128.
Being able to increase this value might fix the problem, since there will be fewer requests to https://ossindex.sonatype.org/, and there will be longer intervals between them (depending on how the amount of requests over time is calculated).

**Configurable request delay: analyzer.ossindex.request.delay**
A full scan of this size already takes +20 minutes. If adding a 3s or 5s delay between each requst to https://ossindex.sonatype.org/ can prevent the scan from terminating, that would be a great option in my opinion.

**Configurable request retry count: analyzer.ossindex.request.retry.count**
I don't like this options since it just "brute forces" the necessary requests.

**Comment by jeremylong** [comment]
PRs accepted.
