### ISSUE TITLE
Please provide a "owasp/dependency-check-daily" docker image with full database

### ISSUE THREAD

**Issue by lathspell** [dependency-check/DependencyCheck#3525]
**Is your feature request related to a problem? Please describe.**

Currently, all my Java projects run Dependency-Check as Gradle plugin and maintain their own local CVE database in the build cache folder. If that folder gets deleted, e.g. because the build fails for some reason it has to rebuild which takes long. It also takes a lot of disk space which sometimes leads to failing builds as well.

**Describe the solution you'd like**

It would be more convenient if I could just run a "owasp/dependency-check-daily:latest" Docker image that scans the project source with an already included CVE database that is max one day old without having to download and parse every CVE myself. And also without having to add yet another plugin to my build scripts.

A daily build of that Docker image with the latest CVE data is probably ok for most people.

**Describe alternatives you've considered**

**Additional context**

There is a Docker image https://hub.docker.com/r/daniiiol/dependency-check-prepared which claims to be based on your image and has just added 
`RUN /usr/share/dependency-check/bin/dependency-check.sh --project WarmUp --out /report/ --scan .`.

That already sounds like the perfect solution but I'm probably not the only one who's not comfortable with scanning my source code by some random guys docker image so I'd prefer if the image would be provided by OWASP or at least the author of the scanner.

**Comment by jeremylong** [comment]
See https://hub.docker.com/r/owasp/dependency-check-action

**Comment by jeremylong** [comment]
This is the docker image used by the github ODC action: https://github.com/dependency-check/Dependency-Check_Action

**Comment by lathspell** [comment]
That looks exactly right!

Could you write an image description for https://hub.docker.com/r/owasp/dependency-check-action ?
At least some links to
  https://github.com/dependency-check/DependencyCheck_Builder and 
  https://github.com/dependency-check/Dependency-Check_Action

**Comment by lathspell** [comment]
Also, the current image has a cached database of the vulnerabilities but takes ~40s for the "Central Analyzer" to run. Presumably because it downloads project specific things from Maven Central. Would it be possible to document the directory used for that cache so that it could be saved by e.g. the Gitlab CI/CD Daemon between runs. Having to wait 40s kind of destroys the benefits from a pre-filled docker image.

**Comment by bjansen** [comment]
@jeremylong the Docker image hasn't been updated in the last 8 days because GitHub Actions decided that nothing happens in the builder repo anymore:

<img width="983" alt="image" src="https://user-images.githubusercontent.com/281528/128192144-b84690f0-e63d-4ba1-bdb4-2e3a814a1462.png">

Do you have enough permissions to do something about it, or do I need to contact someone else?

**Comment by russelljdjacobs** [comment]
Has anyone managed to use the docker image from https://github.com/dependency-check/DependencyCheck_Builder with the gradle plugin?

**Comment by jeremylong** [comment]
Not sure how that would work... I suppose you could pull the latest image and then copy the database out to local host.

**Comment by russelljdjacobs** [comment]
That was my intention yes. Or copy to another build image for pipelines

Would be good to know what command to use to do this though

**Comment by jeremylong** [comment]
The following would copy the current data from the docker image.

```shell
id=$(docker create owasp/dependency-check-action:latest)       
docker cp $id:/usr/share/dependency-check/data ./data    
docker rm -v $id
```
