### ISSUE TITLE
GoModAnalyser is failed in 6.2.2 (seen its fixed in previous versions)

### ISSUE THREAD

**Issue by chanduaki** [dependency-check/DependencyCheck#3533]
steps to reproduce:
1. create a file with the below script
```
import os,subprocess
# DependencyCheck
    #DependencyCheck - Requirements
os.system('sudo apt update')
os.system('sudo apt install openjdk-11-jdk')
os.system('java -version')
    # Install Maven
os.system('sudo apt install maven')
    # Install Dot net
os.system('wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb')
os.system('sudo dpkg -i packages-microsoft-prod.deb')
os.system('rm packages-microsoft-prod.deb')

os.system('sudo apt-get update')
os.system('sudo apt-get install -y apt-transport-https')
os.system('sudo apt-get install -y dotnet-sdk-3.1')
os.system('sudo apt-get install -y aspnetcore-runtime-3.1')
    # Install GO
subprocess.call('cd $HOME/Desktop/devsecops/tools; sudo wget https://golang.org/dl/go1.15.5.linux-amd64.tar.gz', shell=True)
subprocess.call('cd $HOME/Desktop/devsecops/tools; sudo tar -C /usr/local -xzf go1.15.5.linux-amd64.tar.gz', shell=True)
subprocess.call('cd $HOME/Desktop/devsecops/tools; echo "export PATH=$PATH:/usr/local/go/bin" >>  ~/.bashrc', shell=True)
subprocess.call('cd $HOME/Desktop/devsecops/tools; source ~/.bashrc', shell=True)
subprocess.call('cd $HOME/Desktop/devsecops/tools; go version', shell=True)

    # Yarn
os.system('sudo apt update')
os.system('sudo apt install nodejs npm')
os.system('sudo npm install --global yarn')
    # Clone DependencyCheck
subprocess.call('cd $HOME/Desktop/devsecops/tools; sudo git clone https://github.com/jeremylong/DependencyCheck.git', shell=True)
subprocess.call('cd $HOME/Desktop/devsecops/tools/DependencyCheck; mvn org.owasp:dependency-check-maven:6.0.0:purge', shell=True)
subprocess.call('cd $HOME/Desktop/devsecops/tools/DependencyCheck; sudo mvn -s settings.xml install', shell=True)

    # Testing DependencyCheck
subprocess.call('cd $HOME/Desktop/devsecops/tools/DependencyCheck; sudo ./cli/target/release/bin/dependency-check.sh -h', shell=True)
subprocess.call('cd $HOME/Desktop/devsecops/tools/DependencyCheck; sudo ./cli/target/release/bin/dependency-check.sh --out . --scan ./src/test/resources', shell=True)

```
2. run the script `python3 <filename>`

what i am seeing ?
![image](https://user-images.githubusercontent.com/54622987/126626973-426f61ee-4924-4767-803b-62a568593484.png)

what i want to see?
- successfuly Build

In previous versions , i had seen this issue was `fixed` but i am seeing again 
could u suggest what i am missing

**Comment by aikebah** [comment]
You should look for the root cause earlier on in the log or in the surefire testlog to get the remainder of the error message that gets ellipsized in the end-of-build reporting of the error by Maven (`Runtime java.io.IOException: Cannot run p...`)

Something appears to fail on your system with the call to go, but without the rest of the IOException message it's impossible to tell what that might be.

If still not enough information is available in those logs you could try running the maven build in debug mode with exception stacktrace reporting enabled `subprocess.call('cd $HOME/Desktop/devsecops/tools/DependencyCheck; sudo mvn -s settings.xml install -e -X', shell=True)`

In my case builds of DependencyCheck succeed locally using Go 1.16.6

**Comment by chanduaki** [comment]
@aikebah 

I had tried with Go version `1.16.6` still `Build` was a failure

Machine : `Ubuntu 18.04`

**Comment by aikebah** [comment]
@chanduaki So did you also follow up on my other remark: to check the logs in detail to find the root cause message(s) for the failure?

**Comment by aikebah** [comment]
@chanduaki Would like to help you dig deeper into this, but I don't have a box to run your custom python-based environment processing. If you can share a log of a build in debug mode (mvn.... -e -X) I'm willing to take a look at it.

**Comment by chanduaki** [comment]
@aikebah 

i had added the log file below, can u please look into it

[dependency_check_log.txt](https://github.com/jeremylong/DependencyCheck/files/6949309/dependency_check_log.txt)

Thank you

**Comment by aikebah** [comment]
```
[WARN] Warnings from `go`: go: updates to go.mod needed, disabled by -mod=readonly

[ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.289 s <<< FAILURE! - in org.owasp.dependencycheck.analyzer.GolangModAnalyzerTest
[ERROR] testGoMod(org.owasp.dependencycheck.analyzer.GolangModAnalyzerTest)  Time elapsed: 0.288 s  <<< ERROR!
org.owasp.dependencycheck.analyzer.exception.AnalysisException: Error parsing stream
Caused by: javax.json.stream.JsonParsingException: Invalid token=EOF at (line no=1, column no=0, offset=-1). Expected tokens are: [CURLYOPEN, SQUAREOPEN, STRING, NUMBER, TRUE, FALSE, NULL]
```

Looks like the go on your system (the one in the default path) insists on modifying the go.mod (likely in order to add `go <version>` to it), which it's not allowed to as it gets called to run in read-only mode.

That's a case I've seen as well with older go versions, but gets resolved for me with go 1.16.6. A you sure that the Go version 1.16.6 becomes the default Go in you system?

**Comment by chanduaki** [comment]
Thanks for your quick response @aikebah

i had installed the go version as go 1.6.6 as a default one for the other machine
```
# go version
go version go1.16.6 linux/amd64

# which go
/usr/local/go/bin/go
```
Still facing the same issue. can you please tell me where exactly I am missing?
[org.owasp.dependencycheck.data.golang.GoModJsonParserTest.txt](https://github.com/jeremylong/DependencyCheck/files/6950865/org.owasp.dependencycheck.data.golang.GoModJsonParserTest.txt)
[org.owasp.dependencycheck.analyzer.GolangDepAnalyzerTest.txt](https://github.com/jeremylong/DependencyCheck/files/6950866/org.owasp.dependencycheck.analyzer.GolangDepAnalyzerTest.txt)
[org.owasp.dependencycheck.analyzer.GolangModAnalyzerTest.txt](https://github.com/jeremylong/DependencyCheck/files/6950867/org.owasp.dependencycheck.analyzer.GolangModAnalyzerTest.txt)

**Comment by aikebah** [comment]
```
-------------------------------------------------------------------------------
Test set: org.owasp.dependencycheck.analyzer.GolangModAnalyzerTest
-------------------------------------------------------------------------------
Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.013 s <<< FAILURE! - in org.owasp.dependencycheck.analyzer.GolangModAnalyzerTest
testGoMod(org.owasp.dependencycheck.analyzer.GolangModAnalyzerTest)  Time elapsed: 0.007 s  <<< ERROR!
java.lang.RuntimeException: java.io.IOException: Cannot run program "go" (in directory "/home/ib-developer/Desktop/Product_security/devsecops/DependencyCheck/core/target/temp/dctempa2c4db3c-34e8-4cd3-8a40-b257733c1989"): error=2, No such file or directory
	at org.owasp.dependencycheck.analyzer.GolangModAnalyzerTest.testGoMod(GolangModAnalyzerTest.java:97)
Caused by: java.io.IOException: Cannot run program "go" (in directory "/home/ib-developer/Desktop/Product_security/devsecops/DependencyCheck/core/target/temp/dctempa2c4db3c-34e8-4cd3-8a40-b257733c1989"): error=2, No such file or directory
	at org.owasp.dependencycheck.analyzer.GolangModAnalyzerTest.testGoMod(GolangModAnalyzerTest.java:97)
Caused by: java.io.IOException: error=2, No such file or directory
	at org.owasp.dependencycheck.analyzer.GolangModAnalyzerTest.testGoMod(GolangModAnalyzerTest.java:97)
```

Looks like there is no 'go' in the system path of the user that runs the mvn command in your build. (The test runs 'go'-commands assuming that go is installed on the system path for the user that runs the build)), or the tempfolder creation  failed for whatever reason.

**Comment by chanduaki** [comment]
Thanks for the quick response @aikebah 

> Looks like there is no 'go' in the system path of the user that runs the mvn command in your build. 
Here is the wrong step i did 

Followed the below steps to resolve it

1. remove the existing go paths in ~/.bashrc file
2. remove the go 
3. installed the go 1.16.6 using `sudo snap install go --classic`
4. verified the go path `which go ` results as `/snap/bin/go`
5. Run the DependencyCheck requirements using ` sudo mvn -s settings.xml install `

Requirements are still installing. I hope no issues will occur 
once i will give reply to this thread after successful build

Thanks for your support
@chanduaki

**Comment by chanduaki** [comment]
![image](https://user-images.githubusercontent.com/54622987/128635006-bfeffc04-cc8b-4a66-be43-2f3e9cb96cfc.png)

**Comment by aikebah** [comment]
Good to see you managed to succeed in fixing it
