### ISSUE TITLE
Interested in learning the logic which maps a library to CPE

### ISSUE THREAD

**Issue by anshubansal2000** [dependency-check/DependencyCheck#3536]
I am looking for the logic which maps a developer library to CPE information.  I have already reviewed Jeremy's presentation which talks about lucene indexes. 

Would you be able to point me in right direction?

**Comment by jeremylong** [comment]
The wiki discusses this some: https://github.com/jeremylong/DependencyCheck/wiki

The actual matching is done in the CPEAnalyzer: https://github.com/jeremylong/DependencyCheck/blob/main/core/src/main/java/org/owasp/dependencycheck/analyzer/CPEAnalyzer.java

Basically, we make a lucene index of the CPE vendor/product information and do searches with some added analyzers using the collected evidence.
