### ISSUE TITLE
Is this a false positive?

### ISSUE THREAD

**Issue by vijaya-lakshmi-venkatraman** [dependency-check/DependencyCheck#3553]
Hello,
My code has a reference to [marshmallow-enum](https://github.com/justanr/marshmallow_enum)
Upon running Dependency Check, the report displays:

```
pkg:pypi/marshmallow-enum@1.4  (Confidence:Highest)
cpe:2.3:a:marshmallow_project:marshmallow:1.4:*:*:*:*:*:*:*  (Confidence:Highest)
```

Is this counted as a false positive because it is not the marshmallow project included in my code but a utility for it?

**Comment by vijaya-lakshmi-venkatraman** [comment]
I observe the same with the below packages:

- [SQLAlchemy-JSONField](https://github.com/penguinolog/sqlalchemy_jsonfield)
```
pkg:pypi/sqlalchemy-jsonfield@0.9.0  (Confidence:Highest)
cpe:2.3:a:sqlalchemy:sqlalchemy:0.9.0:*:*:*:*:*:*:*  (Confidence:Low) 
```
- [SQLAlchemy-Utils](https://github.com/kvesteri/sqlalchemy-utils)
```
pkg:pypi/sqlalchemy-utils@0.37.7  (Confidence:Highest)
cpe:2.3:a:sqlalchemy:sqlalchemy:0.37.7:*:*:*:*:*:*:*  (Confidence:Low)  suppress
```
- [marshmallow-sqlalchemy](https://github.com/marshmallow-code/marshmallow-sqlalchemy)
```
pkg:pypi/marshmallow-sqlalchemy@0.23.1  (Confidence:Highest)
cpe:2.3:a:marshmallow_project:marshmallow:0.23.1:*:*:*:*:*:*:*  (Confidence:Highest)  suppress
cpe:2.3:a:sqlalchemy:sqlalchemy:0.23.1:*:*:*:*:*:*:*  (Confidence:Highest)  suppress
```
- [zope.deprecation](https://github.com/zopefoundation/zope.deprecation)

```
pkg:pypi/zope.deprecation@4.4.0  (Confidence:Highest)
cpe:2.3:a:zope:zope:4.4.0:*:*:*:*:*:*:*  (Confidence:Highest)  suppress
```
- [python3-openid](https://github.com/necaris/python3-openid)
```
pkg:pypi/python3-openid@3.2.0  (Confidence:Highest)
cpe:2.3:a:openid:openid:3.2.0:*:*:*:*:*:*:*  (Confidence:Highest)  suppress
```
I cannot seem to find these packages reported with vulnerabilities in other websites like Sonatype. 
Please can you help me @jeremylong ?

**Comment by jeremylong** [comment]
Please see https://jeremylong.github.io/DependencyCheck/general/thereport.html.
