### ISSUE TITLE
Failed to request component-reports

### ISSUE THREAD

**Issue by Face-cp3** [dependency-check/DependencyCheck#3558]
[DependencyCheck] [WARN] An error occurred while analyzing 'xxx.jar' (Sonatype OSS Index Analyzer).
[DependencyCheck] [ERROR] Failed to request component-reports.

The problem is not 100% recurrent.I integrated OWASP Dependency Check into Jenkins,I tried adding agentsm,but it didn't work.
Is there a way to retry or catch exceptions?
![jenkins](https://user-images.githubusercontent.com/35024425/127795924-591647a4-d855-43da-8d1e-f9ca39641173.png)
![error](https://user-images.githubusercontent.com/35024425/127795927-dd31f99c-b57d-4548-8979-deff8c5037b0.png)

**Comment by ponmudivn** [comment]
check this #2371

**Comment by Face-cp3** [comment]
> check this #2371
Disable ossindexAnalyzer ？Is there any other way ？

**Comment by aikebah** [comment]
Retrying would likely likely worsen the percentage, assuming your internet connectivity is fine and you hit the [rate limit](https://ossindex.sonatype.org/doc/rest) for OSSINDEX.
DependencyCheck can work with your OSSINDEX credentials if you have them to raise the limit. See the [CLI configuration page](https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html) for details.

**Comment by aikebah** [comment]
Note that the limit is source-IP-based, so in your case everything/everyone that requests component reports via that proxy counts.
