### ISSUE TITLE
scanning yarn.lock reports 0 dependencies scanned

### ISSUE THREAD

**Issue by lambersond** [dependency-check/DependencyCheck#3565]
When I scan my `yarn.lock` file, it's reporting 0 dependencies scanned when there are 0 vulnerabilities found. If I update my package.json, remove a resolution, and rerun, the dependency checker, reports 1 dependency scanned, 1 vulnerability found. 

I sent a POST to https://registry.npmjs.org/-/npm/v1/security/audits with the `Node Audit Payload` from the log, and I got a response with a total dep count.

```json
{
    "actions": [],
    "advisories": {},
    "muted": [],
    "metadata": {
        "vulnerabilities": {
            "info": 0,
            "low": 0,
            "moderate": 0,
            "high": 0,
            "critical": 0
        },
        "dependencies": 1928,
        "devDependencies": 0,
        "optionalDependencies": 0,
        "totalDependencies": 1928
    }
}
```

Is this the intended result?

**Comment by jeremylong** [comment]
Does yarn audit return zero vulnerable dependencies?

**Comment by lambersond** [comment]
yes, it reports 0 vulnerable dependencies and the total scanned.
![Screen Shot 2021-08-06 at 9 01 39 AM](https://user-images.githubusercontent.com/23364363/128514257-6aed3c6a-7a7c-4f9c-9cdd-5c72542078f1.png)

**Comment by jeremylong** [comment]
Just wanted to make sure. At the moment ODC only reports on the vulnerable dependencies for npm and yarn projects. We are planning on reworking this to include all dependencies but we do not have an ETA yet.

**Comment by ejayt** [comment]
You mention npm in the previous comment but I wanted to make sure that `npm audit` will be addressed in this issue as well? The same issue is happening.

**Comment by jeremylong** [comment]
Yes - when the functionality gets reworked we will cover both yarn and npm.

**Comment by ejayt** [comment]
Is there a issue ticket that we can follow to track when the fix will be implemented?
