### ISSUE TITLE
Advanced command line help: disable should be enable

### ISSUE THREAD

**Issue by avantti** [dependency-check/DependencyCheck#3566]
In the advanced command line help the explanation of --enableNexus should not be 'disable'!

--enableNexus                                Disable the Nexus Analyzer.

Change it to 'Enable the Nexus Analyzer' may be correct.

**Comment by jeremylong** [comment]
The command line argument is correct - by default the Nexus Analyzer is disabled. Most users do not use or need this analyzer.
