### ISSUE TITLE
RetireJs fails to find file

### ISSUE THREAD

**Issue by nickcaballero** [dependency-check/DependencyCheck#3578]
**Describe the bug**
A dependency from package.json seems to create a pseudo file dependency, like `ui/package-lock.json?chart.js` which then results in a `java.io.FileNotFoundException` at org/owasp/dependencycheck/analyzer/RetireJsAnalyzer.java:278.

**Version of dependency-check used**
Gradle plugin version 6.1.5.

**Log file**
https://gist.github.com/nickcaballero/c6bb57f2658c76d2cda59b94a76bf07f

**To Reproduce**
Run `dependencyCheck` on a Node project that has a dependency on `"chart.js": "^2.9.3"`.

**Expected behavior**
Should not attempt to locate the non-existent file: `package-lock.json?chart.js (No such file or directory)`

**Comment by jeremylong** [comment]
Do you have an example project to replicate this behavior?

**Comment by nickcaballero** [comment]
I don't - it does happen consistently with 6.1.5 though. However, it looks like it works in 6.2.2.
