### ISSUE TITLE
Hanging for 5.3.2 of the plugin

### ISSUE THREAD

**Issue by marky-mark** [dependency-check/DependencyCheck#3590]
09:28:06  [INFO] NVD CVE requires several updates; this could take a couple of minutes.
09:28:06  [INFO] Download Started for NVD CVE - 2012
09:28:06  [INFO] Download Started for NVD CVE - 2011
09:28:07  [INFO] Download Complete for NVD CVE - 2011  (763 ms)
09:28:07  [INFO] Download Started for NVD CVE - 2013
09:28:07  [INFO] Processing Started for NVD CVE - 2011
09:28:07  [INFO] Download Complete for NVD CVE - 2012  (795 ms)
09:28:07  [INFO] Download Started for NVD CVE - 2014
09:28:07  [INFO] Processing Started for NVD CVE - 2012
09:28:08  [INFO] Download Complete for NVD CVE - 2013  (769 ms)
09:28:08  [INFO] Download Complete for NVD CVE - 2014  (784 ms)
09:28:08  [INFO] Download Started for NVD CVE - 2015
09:28:08  [INFO] Processing Started for NVD CVE - 2014
09:28:08  [INFO] Download Started for NVD CVE - 2016
09:28:08  [INFO] Processing Started for NVD CVE - 2013
09:28:09  [INFO] Download Complete for NVD CVE - 2016  (787 ms)
09:28:09  [INFO] Download Complete for NVD CVE - 2015  (793 ms)
09:28:09  [INFO] Download Started for NVD CVE - 2017
09:28:09  [INFO] Download Started for NVD CVE - 2018
09:28:10  [INFO] Download Complete for NVD CVE - 2018  (901 ms)
09:28:10  [INFO] Download Started for NVD CVE - 2019
09:28:10  [INFO] Download Complete for NVD CVE - 2017  (1451 ms)
09:28:10  [INFO] Download Started for NVD CVE - 2020
09:28:11  [INFO] Download Complete for NVD CVE - 2019  (843 ms)
09:28:11  [INFO] Download Started for NVD CVE - 2021
09:28:11  [INFO] Download Complete for NVD CVE - 2020  (901 ms)
09:28:11  [INFO] Download Complete for NVD CVE - 2021  (792 ms)

Hangs after here

**Comment by mprins** [comment]
please try with a supported release (eg. 6.2.2)

**Comment by jeremylong** [comment]
Any luck with the latest version of ODC?

**Comment by marky-mark** [comment]
Yes all works perfect!

Thanks for your help
