### ISSUE TITLE
Add CLI support for disabling Filename Analyzer

### ISSUE THREAD

**Issue by eric-winkler** [dependency-check/DependencyCheck#3593]
**Is your feature request related to a problem? Please describe.**
In the microsoft .net world, dependencies are defined via references inside `.csproj` files. The names of the `.csproj` files themselves rarely (never?) reflect a third party dependency. False positive matches can be significantly reduced if the evidence excludes `.csproj` filename analysis.

**Describe the solution you'd like**
Extend the analyzer configuration options available on the CLI to allow disabling the filename analyzer.

**Describe alternatives you've considered**
Manual exclusions via suppressions xml

**Additional context**
A recent example of where this would be useful is:
csproj filename: `LoanEligibilityV2ReadModel.Tests.csproj`
CPI: `cpe:2.3:a:model_project:model:2.6.1:*:*:*:*:*:*:*`

**Comment by jeremylong** [comment]
Thanks for the PR!
