### ISSUE TITLE
ERROR - Exception occurred initializing Assembly Analyzer (.NET, on macOS BigSur?)

### ISSUE THREAD

**Issue by Keith-Albright-Bose** [dependency-check/DependencyCheck#3595]
**Describe the bug**
Trying to run scan on Android/Kotlin project in Android Studio 4.2 using Gradle plugin.  This on a MacBook Pro running Big Sur.
Get the above error trying to run a scan.  Didn't spot anything in Idea log nor with --info or --debug options turned on.
Was able to run a scan from command line but that only shows gradle.jar vulnerabilities and not any project dependency issues.

**Version of dependency-check used**
The problem occurs using version 6.2.2 of owasp, 4.2.2 of android.tools.gradle, and 6.7.1 of gradle

**Log file**
_When reporting errors, 99% of the time log file output is required. Please post the log file as a [gist](https://gist.github.com/) and provide a link in the new issue._
Running in terminal, no specific gradlew log that I can find and no additional info in Idea log from Android Studio.
Copy of console output:

Analysis Started
Finished Archive Analyzer (2 seconds)
Finished File Name Analyzer (0 seconds)
Finished Jar Analyzer (0 seconds)
An error occurred with the .NET AssemblyAnalyzer, please see the log for more details.
Exception occurred initializing Assembly Analyzer.
Finished Dependency Merging Analyzer (0 seconds)

**To Reproduce**
_Steps to reproduce the behavior:_
1. Go to 'terminal.'
2. Enter './gradlew dependencyCheckAnalyze'
3. Wait for build to complete.

**Expected behavior**
A scan of dependencies along with any vulnerabilities

**Additional context**
Mobile application with various Android libraries

**Comment by jeremylong** [comment]
If you scan a DLL or EXE file - the assembly analyzer attempts to initialize itself. Unfortunately, the assembly analyzer requires dotnet 3.1 to be installed. If you are not scanning .NET code simply disable the assembly analyzer.
