### ISSUE TITLE
Difference report by using gradle plugin and command line

### ISSUE THREAD

**Issue by lhtuan** [dependency-check/DependencyCheck#3596]
I am using this tool for my Android project. I tried with both command line and gradle plugin. But the reports are completely difference, it makes me confuse.
So can i have your advise about this case, which method is recommended for Android project.

Thanks.

**Comment by jeremylong** [comment]
In 99% of the cases I would recommend using the gradle plugin over the CLI. The gradle plugin is able to retrieve dependency information from the gradle itself as opposed to the CLI attempting to identify dependencies in the packaged build artifacts.

**Comment by lhtuan** [comment]
Thank you.
