### ISSUE TITLE
Mirror for Sonatype OSS Index Analyzer?

### ISSUE THREAD

**Issue by anic** [dependency-check/DependencyCheck#3605]
Since there is a mirror of  NVD (CPE/CVE JSON) data from NIST, see [https://github.com/stevespringett/nist-data-mirror]. Is there a mirror for  Sonatype OSS Index Analyzer?

In my company, dependency-check is used in a offline server which cannot connect to https://ossindex.sonatype.org/

**Comment by mprins** [comment]
Unlikely; it is a violation of the [TOS](https://ossindex.sonatype.org/tos) 
You could contact Sonatype for an on-premise solution

**Comment by jeremylong** [comment]
You can disable the OSS Index Analyzer - small increase in false negatives and false positives.

**Comment by Lzmupupup** [comment]
> Since there is a mirror of NVD (CPE/CVE JSON) data from NIST, see [https://github.com/stevespringett/nist-data-mirror]. Is there a mirror for Sonatype OSS Index Analyzer?
> 
> In my company, dependency-check is used in a offline server which cannot connect to https://ossindex.sonatype.org/

Can you help me use it in a offline server please
