### ISSUE TITLE
I am in a scenario where there are no jar files to scan a file. So I am downloading the folder and running the scan against it, the results say Dependencies scanned 0, is this an issue ?

### ISSUE THREAD

**Issue by anilmukkamala** [dependency-check/DependencyCheck#3610]
![image](https://user-images.githubusercontent.com/89027166/130857191-17b979c9-a707-43be-9927-e823d3a49f93.png)

**Comment by anilmukkamala** [comment]
dependency-check.bat --project Accountorder-master --scan C:\accountorder-master --out C:\DC\accountorder-master-folder.html 

I am using that command. accountorder-master is the folder that I am running against.

**Comment by aikebah** [comment]
Looks like you're running against a checkout from version control. What build-tool is used for the accountorder project?

**Comment by anilmukkamala** [comment]
yeah, I downloaded the file from Gitlab, extracted and running against it. There is no build tool, all deliverables are zipped and deployed as  a package on the integration server.

**Comment by aikebah** [comment]
Well, whatever your technology your package content is, it's clearly not something that DependencyCheck can scan, so it's useless to scan it with DependencyCheck.

**Comment by aikebah** [comment]
(or it's only supported with the experimental analyzers (with a significant risk of false positives/negatives) which need to be [explicitly enabled](https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html)

**Comment by anilmukkamala** [comment]
Thanks for the response. Can we scan WebMethods Artifacts using CLI or is there any way to run dependency check on them ?

**Comment by aikebah** [comment]
From he limited knowledge I have of the webmothods ecosystem I would think OWASP dependencycheck's only (limited) use would be in scanning (opensource) java libraries that you include as building blocks for java based services.
So for example if you have a java-service that uses the apache commons-compress library for unzipping files DependencyCheck could warn you when your solution is packaging commons-compress lower than v1.21, when you scan the full package folder that includes the commons-compress.jar, that the included commons-compress is vulnerable to a [denial-of-service risk for specially crafted zip-files](https://lists.apache.org/thread.html/r9a23d4dbf4e34d498664080bff59f2893b855eb16dae33e4aa92fa53@%3Cannounce.apache.org%3E)

There is no support for webmethods' native projects (e.g. flow.xml)
