### ISSUE TITLE
TLS Connection Reset

### ISSUE THREAD

**Issue by ShrihariVKale** [dependency-check/DependencyCheck#3615]
Issue - TLS Connection Reset
OWASP dependency check command line tool - version - 6.2.2 
JDK Version- 16.0.2
OS - Windows
Screenshot - 
<img width="492" alt="NetworkConnectionReset" src="https://user-images.githubusercontent.com/89638297/131113406-2f58b02f-6192-44a4-9048-14267caa0b80.png">

As per in error log, tried resolution  “http://jeremylong.github.io/DependencyCheck/data/tlsfailure.html” however ‘lib/ext’ folder is not available in JDK folder also lib/Security/java.security file is not present.
Those are found in conf/java.security hence tried with it, also followed subsequent comments from that resolution thread, however getting same error

Can you please suggest resolution for above issue with respect to mentioned environment. 

Note: We have firewall restrictions. tried NIST data mirror, however there are errors for it as well.

**Comment by mprins** [comment]
>  ‘lib/ext’ folder is not available in JDK folder also lib/Security/java.security file is not present.

because you are not running on Java 8, which is the recommended platform ATM (but in this case Java 8 probably won't solve your problems)

> Note: We have firewall restrictions

You'll have to work around those with your sys-admin, not something we can fix for you
