### ISSUE TITLE
Central Analyzer Disabled error

### ISSUE THREAD

**Issue by rahulvyadav85** [dependency-check/DependencyCheck#362]
I'm trying to configure dependency-check ant for one of my project. I followed following steps, but I'm getting "Central analyzer disabled" error when I run build.xml of the my project.

1) Downloaded the zip for release 1.3.1
2) Unzipped it.
3) Defined taskdef and target for dependency-check.(http://jeremylong.github.io/DependencyCheck/dependency-check-ant/index.html & http://jeremylong.github.io/DependencyCheck/dependency-check-ant/configuration.html)
4) Prior to this I created target to update  the local repository and it created data directory at the place where I unzipped the jar and has dc.h2.db file as its content.

Any help would be appreciated.

**Comment by jeremylong** [comment]
Thanks for pointing this issue out. I just looked at the ant task and the
Central analyzer is disabled by default (this is incorrect). This will be
fixed in the next release.  In the meantime you can enable this via
configuration by adding the attribute:

   centralAnalyzerEnabled="true"

--Jeremy

**Comment by rahulvyadav85** [comment]
@jeremylong Thanks for your prompt reply. Could you just point exactly how should I make this change?

**Comment by jeremylong** [comment]
Sorry for the delay. As indicated in the documentation pages you linked to above you can simply add the centralAnalyzerEnabled attribute to the dependency-check node:

``` xml
<target name="dependency-check" description="Dependency-Check Analysis">
    <dependency-check projectname="Hello World"
                      reportoutputdirectory="${basedir}"
                      centralAnalyzerEnabled="true"
                      reportformat="ALL">

        <fileset dir="lib">
            <include name="**/*.jar"/>
        </fileset>
    </dependency-check>
</target>
```
