### ISSUE TITLE
analyzer.swift.package.resolved.enabled=true is missing from conf

### ISSUE THREAD

**Issue by JuhaO81** [dependency-check/DependencyCheck#3620]
Noticed that analyzer.swift.package.resolved.enabled=true is missing from dependencycheck.properties but doc says it is enabled. Is this a mistake?

https://github.com/jeremylong/DependencyCheck/blob/main/core/src/main/resources/dependencycheck.properties
https://github.com/jeremylong/DependencyCheck/blob/125751267e5b8775c08451862fe1595c15493e3c/ant/src/site/markdown/configuration.md

PS
Took the project down, added this config and compiled the project but have some run time issues so not able to test my self. Access to https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta fails with some cert issues

**Comment by aikebah** [comment]
It is enabled by [default](https://github.com/jeremylong/DependencyCheck/blob/4f7c7fc0cd9ce3707983e25be56fd77303c539a4/core/src/main/java/org/owasp/dependencycheck/analyzer/AbstractAnalyzer.java#L90) if a setting is not present. But, as it is an experimental analyzer it will only be loaded if you enable the experimental analyzers

**Comment by nhumblot** [comment]
Hi @JuhaO81 :wave: 

Even if the property is not set in `dependencycheck.properties` it is enabled if experimental analyzers are enabled.

Given the following implementation in `src/main/java/org/owasp/dependencycheck/analyzer/AbstractAnalyzer.java`:
```
    /**
     * Initializes the analyzer with the configured settings.
     *
     * @param settings the configured settings to use
     */
    @Override
    public void initialize(Settings settings) {
        this.settings = settings;
        final String key = getAnalyzerEnabledSettingKey();
        this.setEnabled(settings.getBoolean(key, true));
    }
```

If a key is not set, enabled is set to `true` by default.

Still, I'm going to add a couple of changes and submit a PR to improve the documentation to make it more explicit in this regard and prevent this question being raised.
