### ISSUE TITLE
Gradle plug-in: only verify artifacts used in main application

### ISSUE THREAD

**Issue by bramklg** [dependency-check/DependencyCheck#363]
We currently use the Gradle dependencyCheck plug-in for an Android project. The problem is that the checker flags libraries with CVE's that are only used by unit test plug-ins, they don't end up in the actual application.

It would be nice if we could configure the dependency check plug-in so that it only verifies the artifacts that actually end up in the application.

**Comment by willis7** [comment]
I still think there is value in having the option to analyse all. I will try and add a feature to make it optional for the plugin user.

**Comment by jeremylong** [comment]
A configuration option has been added to skip dependency groups that begin with `test`. This will be available in the next release.

**Comment by bramklg** [comment]
Thanks allot! :smile:
