### ISSUE TITLE
Maven Dependency Check - Redirect External URL to Artifactory

### ISSUE THREAD

**Issue by ParthibanSG** [dependency-check/DependencyCheck#3632]
Hi,

I am currently investigating the dependency check plugin usage and we are using "Artifactory Maven 3" jenkins plugin for our maven build and security scans. We tried to use "Invoke dependency check" but it seems that Dependency Check is identifying vulnerabilities with JARs of Artifactory cache which comes as part of "Artifactory Maven 3" plugin and those are not part of source code

I read posts regarding the usage of dependency check for maven and best practice suggested is to use dependency-check-maven instead of the generic one. Hence, I just included a maven goal in my run with "org.owasp:dependency-check-maven:check" and I can see that latest version of the plugin is downloaded but scan doesn't get completed successfully due to Sonatype URL connectivity.

We modified the URL for NIST data feed to our artifactory and it is able to download them for processing. However, we have hit roadblock with Sonatype Analyzer and below is the error observed with 5.3.2 and 6.3.1

14:12:40 [pool-12-thread-1] DEBUG org.owasp.dependencycheck.utils.SSLSocketFactoryEx - TLSv1.2
14:12:40 [pool-12-thread-1] DEBUG org.owasp.dependencycheck.utils.SSLSocketFactoryEx - TLSv1.3
14:12:40 [pool-12-thread-1] DEBUG org.sonatype.ossindex.service.client.transport.HttpUrlConnectionTransport - Connecting to: https://ossindex.sonatype.org/api/v3/component-report
14:12:40 [pool-12-thread-1] DEBUG org.owasp.dependencycheck.analyzer.OssIndexAnalyzer - Error requesting component reports

**Comment by aikebah** [comment]
There are a couple of analyzers in DependencyCheck that [expect internet access](https://jeremylong.github.io/DependencyCheck/data/index.html). Among those is the Sonatype OSSIndexAnalyzer.
If your environment does not allow for proxied access to internet you should disable those analyzers in the [maven configuration](https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html).

**Comment by ParthibanSG** [comment]
> There are a couple of analyzers in DependencyCheck that [expect internet access](https://jeremylong.github.io/DependencyCheck/data/index.html). Among those is the Sonatype OSSIndexAnalyzer.
> If your environment does not allow for proxied access to internet you should disable those analyzers in the [maven configuration](https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html).

Our environment already has access to Internet to connect to Sonatype website, etc... I replaced dependency-check-maven with usual dependency-check and the run is success without any connectivity issues and as I mentioned, it still provides vulnerabilities from cache which are not part of source code...

**Comment by aikebah** [comment]
Then scroll back to the full stacktrace for the error you posted. If it's not in the log enable exceptionstracktrace logging in maven in addition to the debug logging (add `-e` to the commandline). Do you run into a SSL certificate trust issue? Or is it another exception?
