### ISSUE TITLE
Outdated gpg key for archive signature

### ISSUE THREAD

**Issue by Cor-J** [dependency-check/DependencyCheck#3635]
Hello,

The key in use to sign the cli zip is outdated

`gpg --verify dependency-check-6.3.1-release.zip.asc`
`gpg: assuming signed data in 'dependency-check-6.3.1-release.zip'                                                       `
`gpg: Signature made Wed Sep  1 14:32:56 2021 CEST                                                                       `
`gpg:                using RSA key F9514E84AE3708288374BBBE097586CFEA37F9A6                                              `
`gpg: Good signature from "Jeremy Long <jeremy.long@gmail.com>" [expired]                     `                           
`**gpg: Note: This key has expired!**                                                                                        `
`Primary key fingerprint: F951 4E84 AE37 0828 8374  BBBE 0975 86CF EA37 F9A6 `

Do I assume it is still safe to use?

**Comment by jeremylong** [comment]
I updated the cert for the 6.4.0 release.  Thanks for pointing this out.

**Comment by jeremylong** [comment]
```shell
$ gpg --verify dependency-check-6.4.0-release.zip.asc 
gpg: assuming signed data in 'dependency-check-6.4.0-release.zip'
gpg: Signature made Mon Oct 11 14:38:47 2021 EDT
gpg:                using RSA key 259A55407DD6C00299E6607EFFDE55BE73A2D1ED
gpg: Good signature from "Jeremy Long <jeremy.long@gmail.com>" [ultimate]
```
