### ISSUE TITLE
Link to CVSS->severity rating in your docs

### ISSUE THREAD

**Issue by marcelstoer** [dependency-check/DependencyCheck#3637]
At first I was little lost in mapping the CVSS values (0-10) in your tool configurations to the severity rating (LOW-CRITICAL) in the output. Then I went looking in the NIST documentation and found this https://nvd.nist.gov/vuln-metrics/cvss.

IMO it would be helpful to link to NIST from e.g. here https://jeremylong.github.io/DependencyCheck/dependency-check-maven/check-mojo.html#failBuildOnCVSS.

**Comment by mprins** [comment]
please prepare a pull request with your suggestion

**Comment by marcelstoer** [comment]
Being unfamiliar with project it's hard to assess for me where this should be linked from. I'm quite certain it's much more than just this one example I found.

**Comment by marcelstoer** [comment]
Thanks Jeremy.
