### ISSUE TITLE
Use with mysql in maven report not possible

### ISSUE THREAD

**Issue by amandel** [dependency-check/DependencyCheck#364]
Looks like this is a limitation of maven - which could be worked around in `dependency-check-maven`.

I've a issue when using a central mysql database.

In the usual plugin build step I can define additional dependencies - the mysql driver:

``` xml
<build>
    <plugins>
        <plugin>
          <groupId>org.owasp</groupId>
          <artifactId>dependency-check-maven</artifactId>
          <version>1.3.1</version>
          <executions>
              <execution>
                  <!-- Does not produce any result <inherited>false</inherited> -->
                  <goals>
                      <goal>check</goal>
                  </goals>
                  <configuration>
                        <format>ALL</format>
                        <databaseUser>dcuser</databaseUser>
                        <databasePassword>dcuser</databasePassword>
                        <connectionString>jdbc:mysql://D4DE3ESY0000293.gdc-bln01.t-systems.com:3306/dependencycheck</connectionString>
                        <databaseDriverName>com.mysql.jdbc.Driver</databaseDriverName>
                  </configuration> 
              </execution>
          </executions>
            <dependencies>
                <dependency>
                    <groupId>mysql</groupId>
                    <artifactId>mysql-connector-java</artifactId>
                    <version>5.1.36</version>
                </dependency>
            </dependencies>
        </plugin>
    </plugins>
</build>             
```

Unfortunately while it is possible to define additional dependencies in the `<build>` element, this is not the case inside the `<reporting>` element. Which gives me no chance to pull the mysql connector from the net and put it to the classpath of the plugin.

Might be i miss something? Otherwise it might be helpful to have a `dependency-check-mysql-maven` artifact that is equal to `dependency-check-maven` but adds the `mysql-connector-java` dependency.

**Comment by hansjoachim** [comment]
I haven't tested this myself, but have you tried adding the additional dependency to `dependency-check-maven` in `pluginManagement`? With Maven 3, plugins in `reporting` will check `pluginManagement` when resolving version number, but I don't know if it looks up additional configuration as well. (See http://maven.apache.org/plugins/maven-site-plugin/maven-3.html#Version_Resolution) Worth a shot to see what the effective POM/a testrun makes of it.

Beware that if you are running an older version of Maven 3 (pre 3.1), you might get warnings saying version  numbers aren't defined for plugins in `reporting` when they are listed in `pluginManagement`. See https://issues.apache.org/jira/browse/MSITE-443?focusedCommentId=14451732&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14451732 and/or #346 for more information.

**Comment by amandel** [comment]
Thanks for the feedback - actually I tried this already with no luck. Unfortunately I do not have the maven version I used at hand. I'll check that (was 3.x)

**Comment by jeremylong** [comment]
I appologize about the delay of the response - and it appears Hans already posted one of my two ideas to resolve your issue.  Using the pluginManagement section might work (if you are using the latest maven). As such, the folllowing might resolve the issue:

``` xml
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.owasp</groupId>
                    <artifactId>dependency-check-maven</artifactId>
                    <version>1.3.1</version>
                    <dependencies>
                        <dependency>
                            <groupId>mysql</groupId>
                            <artifactId>mysql-connector-java</artifactId>
                            <version>5.1.36</version>
                        </dependency>
                    </dependencies>
                </plugin>
            </plugins>
        </pluginManagement>
```

Alternatively, you could specify the `databaseDriverPath` in the configuration. You could point it to your local `.m2/repository/path/to/driver.jar`.

However, the best resolution would be if the maven team resolved issue [MSITE-444](https://issues.apache.org/jira/browse/MSITE-444).

--Jeremy

**Comment by amandel** [comment]
Thanks for the feedback. I voted for MSITE-444.
I did some tests and it looks like the `pluginManagement` solution works only if the plugin is also used in the `build`section. 
This feels quite fragile to me. Since I have to support a lot of jobs with as little change in the pom, creating a _derived_ version of the plugin with the required database configuration (as default) and the required mysql dependency seems a reasonable solution. Am I missing something? Actually I don't know if this is just a matter of some pom.xml or if it also requires some java code.

**Comment by jeremylong** [comment]
I think the easiest would be to create a POM that includes the MySQL driver and load this into your companies repo.

**Comment by amandel** [comment]
You mean to modify and replace the original pom? 

I've no knowledge about writing a maven plugin. To get a version of the plugin with the additional dependency and changed default values, as see it now, I would need to 'copy' the whole `dependency-check-maven` module code into a new module and do my modifications. Since the maven code is well separated from the actual dependency check, this is not to much code, but actually much more than I expected. (I'm not a fan of c&p).

**Comment by jeremylong** [comment]
Copy and paste should not be needed. I can post a sample in the morning
(eastern).

Jeremy

**Comment by amandel** [comment]
Great, that would be helpful.

**Comment by jeremylong** [comment]
Update - I have a _mostly_ working example. However, in building the example for you I found a bug in the HTML report's velocity template that will need to be fixed. I'll need a few more days to resolve this and provide the example. However, if all you needed is the XML report (for use with ThreadFix) - then I can post a working example.

--jeremy

**Comment by amandel** [comment]
I've no hurry and also I do not need the HTML report -> you to choose whatever is more effective for you

**Comment by jeremylong** [comment]
I put together a working example of how you could solve the problem locally. If you built the [dependency-check-maven-mysql](https://gist.github.com/jeremylong/63e90cd6103ff9e41b6a) project you can then store this in your companies repo. The interesting thing about this solution is that you can also modify any of the default settings in the mojo.properties (in this example I added the connection string setting, take a look at the KEYS in the [Settings.java](https://github.com/jeremylong/DependencyCheck/blob/master/dependency-check-utils/src/main/java/org/owasp/dependencycheck/utils/Settings.java#L46) to know the property names.

Let me know if that works until Maven fixes the bug in the reporting section.

--Jeremy

**Comment by amandel** [comment]
Cool - this works relay fine and is exactly what I was looking for. Thanks very much!

A minor issue, `autoupdate` does not seem to be respected? At least I could not set it to false as default.

**Comment by jeremylong** [comment]
Regarding the autoupdate not being able to be set - this is because there are hard-coded defaults in the base mojo. I will have to refactor this in a future version.

**Comment by amandel** [comment]
Ok. It is not an issue for me.
