### ISSUE TITLE
JDK dependency (with homebrew)

### ISSUE THREAD

**Issue by pvegh** [dependency-check/DependencyCheck#3650]
For some reason we're stuck with 6.2.2 on the CI, probably because when our pipeline was set up 6.2.2 depended on java 11.
Now it depends on java 16. Is it really necessary? Could it run independently?

**Comment by mprins** [comment]
Actually java 8 is the recommended version. You may need to contact the publisher of https://formulae.brew.sh/formula/dependency-check

**Comment by jeremylong** [comment]
I know ODC runs on Java 11 - I have not actually tested it on higher versions of Java. I'll likely bump the Java version on the docker image to test now that 17 is out (the next LTS version).
