### ISSUE TITLE
Getting Error when scanning saying "Unable to download meta file"

### ISSUE THREAD

**Issue by Whimmery** [dependency-check/DependencyCheck#3662]
Hello,
I am currently getting an error when first starting up the scan as soon as it is checking for updates. Currently running the newest version of OWASP Dependency-Check 6.3.1 release but not sure what is the matter, could you please help guide me on what could be causing this issue? 

![image](https://user-images.githubusercontent.com/31230311/134009764-ad112727-21fd-4539-bbf7-8b90a499d1ec.png)

**Comment by mprins** [comment]
> could you please help guide me on what could be causing this issue?

It's either a network issue on your end or the nvd.nist.gov site that provides the vulnerability data is down.
FWIW I've just now successfully updated my database with fresh data from  nvd.nist.gov without any problems

**Comment by Whimmery** [comment]
Thank you mprins, appreciate your insight! That greatly helps narrow the issues down. the website is also working on my end so it might be a networking issue if that's the case
