### ISSUE TITLE
DependencyNotFoundException: Unable to resolve system scoped dependency: com.sun:tools:jar:1.8.0:system

### ISSUE THREAD

**Issue by khbac** [dependency-check/DependencyCheck#3663]
jdk 1.8 (oracle)
dependency check version 6.3.1
maven 3.5

[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.owasp:dependency-check-maven:6.3.1:aggregate (default-cli) on project modernisation: One or more exceptions occurred during dependency-check analysis: One or more exceptions occurred during analysis:
[ERROR] 	DependencyNotFoundException: Unable to resolve system scoped dependency: com.sun:tools:jar:1.8.0:system
[ERROR] 	DependencyNotFoundException: Unable to resolve system scoped dependency: com.sun:tools:jar:1.8.0:system
[ERROR] 	DependencyNotFoundException: Unable to resolve system scoped dependency: com.sun:tools:jar:1.8.0:system
[ERROR] -> [Help 1]

**Comment by aikebah** [comment]
Sounds like it's not a bug, you should check the pom, sounds like there is an invalid system path for the tools.jar in your pom

**Comment by khbac** [comment]
there's no sytem path at all. if I call dependency-check-maven with java 11 (open jdk) it works.

**Comment by aikebah** [comment]
Well, there should be some item in the dependency tree that defines a dependency on com.sun:tools:jar:1.8.0:system, as otherwise DependencyCheck would not try to resolve it.

As running it with java 11 works without problem it looks as if some pom on the path triggers the dependency on the JDK tools.jar depending on the JVM it's run on.

Without access to your project structure it's impossible to determine what that would be.

You can try to get clarity from maven on it by using

```
mvn dependency:tree -Dincludes=com.sun:tools
```
(with JDK 8 of course, as apparently the dependency is absent for JDK 11)

**Comment by khbac** [comment]
You are right I find this dependency in plugin weblogic-maven-plugin 
<dependency>
          <groupId>com.sun</groupId>
          <artifactId>tools</artifactId>
          <version>1.8.0</version>
          <scope>system</scope>
          <systemPath>${java.home}/../lib/tools.jar</systemPath>
   </dependency>

and within the build jenkins the property java.home does'nt exist (we define JAVA_HOME instead)

**Comment by aikebah** [comment]
Seems strange to me that your project would have a *dependency* on a maven plugin. Typically a maven plugin is configured to run in a build, not to be a depended-upon library.

**Comment by khbac** [comment]
we have a piepline with multiple stage (build + dependency check + analyse sonar + ...). we use weblogic-maven-plugin to compile jsp in stage build. may be in stage dependency check it scan CVE in relation with this plugin

**Comment by aikebah** [comment]
But the error you get sounds as if you have the plugin listed in `<dependencies>` section of the pom.xml. A maven plugin only needs to be listed in the `<build><plugins>` section to use it in your build.

**Comment by Ripp13** [comment]
I have the same exception, in my project the tools.jar dependency comes from an Arquillian library:

[INFO] --- maven-dependency-plugin:3.1.2:tree (default-cli) @ ywb-check-beheerde-testcomponenten ---
[INFO] nl.belastingdienst.ywb:ywb-check-beheerde-testcomponenten:war:1.0.0-SNAPSHOT
[INFO] \- io.openliberty.arquillian:arquillian-liberty-managed:jar:1.0.8:compile
[INFO]    \- com.sun:tools:jar:1.6.0:system
[INFO] ------------------------------------------------------------------------

FYI: the project is a project that has been created to check commonly used test-dependencies in my company in one go so we can monitor security issues for those dependencies (my department supports Java development teams).
When using Adopt OpenJDK 8 I get the issue with tools.jar. When using Adopt OpenJDK 11 there's no such issue.

Exception that is shown in the dep.check report:
exception: org.owasp.dependencycheck.exception.DependencyNotFoundException: Unable to resolve system scoped dependency: com.sun:tools:jar:1.6.0:system
org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.collectMavenDependencies(BaseDependencyCheckMojo.java:1308)
org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.collectDependencies(BaseDependencyCheckMojo.java:1467)
org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.scanArtifacts(BaseDependencyCheckMojo.java:1114)
org.owasp.dependencycheck.maven.AggregateMojo.scanDependencies(AggregateMojo.java:69)
org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.runCheck(BaseDependencyCheckMojo.java:1719)
org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.execute(BaseDependencyCheckMojo.java:966)
org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
org.apache.maven.cli.MavenCli.execute(MavenCli.java:972)
org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)

Used versions:
Maven version:
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 1.8.0_292, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.11.0-37-generic", arch: "amd64", family: "unix"

dependency-check-maven:6.3.2

**Comment by aikebah** [comment]
@Ripp13 If you look at the pom of that library you'll see why you have different behaviour between running with jdk8 and jdk11: depending on the jvm version the library takes a different profile which triggers different dependencies. For java 8 you need a tools.jar present on your system and you'll have to define the appropriate path to it in order to allow it to be resolved.

Within the dependencyManagement section of your top-level pom override the dependency of arquillian-liberty-managed
The arquillian pom-file defines it as:

```xml
        <dependency>
          <groupId>com.sun</groupId>
          <artifactId>tools</artifactId>
          <version>1.6.0</version>
          <scope>system</scope>
          <systemPath>${java.home}/../lib/tools.jar</systemPath>
        </dependency>
```
And as per the error your system doesn't have a tools.jar present at `${java.home}/../lib/tools.jar` (does it have the openjdk JDK installed? Or do you only have the openjdk JRE?)

You'll need to put an identical entry in your top-level pom dependencyManagement  in order to override the systemPath with the location of tools.jar on your system (or configure an appropriate java.home system property). 

As an alternative solution you could configure the plugin to skip system-scoped dependencies - https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html.

**Comment by Ripp13** [comment]
@aikebah Thank you for the explanation. There is a tools.jar in ${java.home}/../lib for my OpenJDK 8, but I haven't got a JAVA_HOME set on my system. Setting that doesn't seem to fix the issue.

Skipping system-scoped dependencies does the trick however. Thanks.

**Comment by khbac** [comment]
I confirm that cleaning weblogic-maven-plugin from dependencies resolve my problem (whatever jdk 1.8 or jdk 11)

**Comment by cubistico** [comment]
While the solution from @aikebah [proposed in this comment](https://github.com/jeremylong/DependencyCheck/issues/3663#issuecomment-939956025) works, it ceases to work when JDK >8 is used.

We eventually solved it by adding 

` <skipSystemScope>true</skipSystemScope>  `

to the configuration of the dependency-check-plugin. 

See also [issue #729 ](https://github.com/jeremylong/DependencyCheck/issues/729)
