### ISSUE TITLE
org.owasp.dependencycheck.analyzer.exception.AnalysisException: org.owasp.dependencycheck.data.nuget.NuspecParseException: Unable to parse nuspec

### ISSUE THREAD

**Issue by edgarleebc** [dependency-check/DependencyCheck#3672]
Hi All,

I am scanning my Application and I am getting the following Analysis Exception:
org.owasp.dependencycheck.analyzer.exception.AnalysisException: org.owasp.dependencycheck.data.nuget.NuspecParseException: Unable to parse nuspec

exception: org.owasp.dependencycheck.analyzer.exception.AnalysisException: org.owasp.dependencycheck.analyzer.exception.AnalysisException: org.owasp.dependencycheck.data.nuget.NuspecParseException: Unable to parse nuspec
org.owasp.dependencycheck.analyzer.NuspecAnalyzer.analyzeDependency(NuspecAnalyzer.java:182)
org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:836)

Am looking for help to understand the issue and how this can be resolved.

Thanks,
Edgar

**Comment by jeremylong** [comment]
Apparently our nuspec parser is not able to parse the `.nuspec` file in your application (reference https://docs.microsoft.com/en-us/nuget/reference/nuspec). Any chance you can provide the nuspec file?

**Comment by edgarleebc** [comment]
Hi Jeremy,

Thanks you very much for the reply.

The nuspec file should be as attached.

Thanks,
Edgar

**Comment by jeremylong** [comment]
No nuspec file was added to the github issue. Might be an issue with replying by email?

**Comment by edgarleebc** [comment]
Hi, Please find the link below (GITHUB doesn't allow me to upload the filetype.)

https://www.dropbox.com/s/iohj1kst53v4hdy/SIUtilities.csproj.nuspec?dl=0

Thanks for the assistance.,
Edgar

**Comment by jeremylong** [comment]
Your `nuspec` file has a capitolized `Description` element. Per the [nuspec xsd](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Packaging/compiler/resources/nuspec.xsd#L71) the `description` element should be lower case.
