### ISSUE TITLE
Consider NVD API for CVE data feed

### ISSUE THREAD

**Issue by jeremylong** [dependency-check/DependencyCheck#3676]
The NVD now has an API to download the data feed: https://csrc.nist.gov/CSRC/media/Projects/National-Vulnerability-Database/documents/web%20service%20documentation/Automation%20Support%20for%20CVE%20Retrieval.pdf

Pros: 
- Reduce the number of items to download and process for incremental updates - if run daily, instead of processing the last week of updates using the API only the previous day's updates would need to be processed.
- May help reduce load on the NVD caused by ODC
- Likely won't affect the overall update process as the current downloads finish well before the data is processed and stored in the H2 database.

Cons:
- No longer able to use the nist-data-mirror without major re-work of the data mirror.
  - As the actual processing of the JSON elements won't change we might be able to keep a legacy update mode.

Should ODC be modified to use the API instead of JSON files?

**Comment by Jules182** [comment]
Hi, the CVE Data feeds will be discontinued in September 2023. Do you have any plans to update to the NVD API? https://nvd.nist.gov/vuln/data-feeds#JSON_FEED
