### ISSUE TITLE
Dependency check gets stuck on downloading updates

### ISSUE THREAD

**Issue by echalone** [dependency-check/DependencyCheck#3681]
**Describe the bug**
Sometimes the dependency check gets just stuck after printing out "[INFO] Checking for updates". Sometimes it manages to print out "[INFO] Download Started for NVD CVE - Modified" too before getting stuck. We had it run for 10 hours before canceling. This doesn't happen every time though, sometimes it still works, especially with older dependency check versions, and sometimes it just cancels because of a timeout.

We have this problem at least since September 9th, 2021, 4 pm UTC. It seems to be independent of the dependency-check version used, since I was able to reproduce it with 6.3.2, 6.3.1, 6.3.0 and 6.2.2, though older versions seem to rather cancel due to a timeout than getting stuck. We did not experience this problem before and are using dependency check since at least June this year, if not longer. I've also tried to call the URLs with which it seems to have problems (according to the log files) in a browser without any problem. They load extremly fast.

**Version of dependency-check used**
At least 6.3.2, 6.3.1, 6.3.0 and 6.2.2. More likely to appear with 6.3.2 though.

**Log file**
[Logfile if 6.3.2 gets stuck](https://gist.github.com/echalone/a91ae490f6510dc8380e6969fa3b0d88)
[Output if 6.3.2 manages to cancel](https://gist.github.com/echalone/b5cff729f338c65fe4bc23ad919abc79)
[Logfile if 6.3.0 cancels due to timeout](https://gist.github.com/echalone/25bc80f92e96b3154a940b961af20129)

**To Reproduce**
``C:\dependency-check\bin\dependency-check.bat --project MyProj --scan C:\SourceFolder\*.*proj --out C:\DependencyCheckOutput --format HTML --format XML --failOnCVS 10``

**Expected behavior**
To not get stuck on checking for updates and to not run into a timeout. Even if a timeout occurs, it should at least not get stuck.

**Additional context**
Java Version used: JRE 1.8.0_261 (has not changed since before problem occurs)
OS used: Windows 10 21H1 Build 19043.1165 and Build 19043.1237 (happens on both)

**Comment by jeremylong** [comment]
The NVD put in rate limiting in September. The latest release 6.4.1 (or 6.4.1.1 for gradle) should resolve these issues.
