### ISSUE TITLE
Show versions in the report for all dependencies

### ISSUE THREAD

**Issue by Subramanian-ERS** [dependency-check/DependencyCheck#3686]
I can see that the report shows the versions only for the dependencies that have vulnerabilities. How can I modify the code to show the versions for all dependencies irrespective of whether they contain vulnerabilities or not? I would like to use this tool for inventory purposes as well. So the versions would really help.

**Comment by jeremylong** [comment]
All dependencies and versions are included in the HTML, XML, JSON, etc. reports. I'm confused as to the question?

The HTML report does have a link near the top that shows all dependencies - by default it only shows the vulnerable dependencies.

**Comment by Subramanian-ERS** [comment]
@jeremylong Yes, I am aware of the link to show all dependencies. Upon selecting it, I am viewing the list of dependencies, but the package column has no value. Attaching the screenshot for your reference.

![image](https://user-images.githubusercontent.com/73224279/135815655-56763b41-396f-4d1d-9a40-47e2ec98272a.png)

**Comment by jeremylong** [comment]
In some cases we do not have enough information to generate a package-URL identifier. This is generally the case when we are scanning files (like JS) on disk that are not being managed by some form of package manager.
