### ISSUE TITLE
received response code 403; Forbidden

### ISSUE THREAD

**Issue by Premfer** [dependency-check/DependencyCheck#3687]
Hi Team,

We are using OWASP Dependency check build task in azure CI pipeline, It was functioning fine but now we are getting

 Error retrieving https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta; received response code 403; Forbidden

Kindly let know what to be checked.

**Comment by jeremylong** [comment]
duplicate https://github.com/jeremylong/DependencyCheck/issues/3502
