### ISSUE TITLE
Dependency check fails if build WAR/JAR is failed

### ISSUE THREAD

**Issue by aejazuddinam** [dependency-check/DependencyCheck#3704]
Hi Jeremy,
We've noticed if the maven build for building war/jar is failed and not success, we can manage to run dependency check after that but it gives an empty report with 0 components/vulnerabilities, it is dependent on the success of build to display accurate report. 

Is there a way we can test so we don’t publish data in failure scenarios?
If that were so, we could always try and run the dependency check rather than just in success cases.

Regards,
Aejaz

**Comment by mprins** [comment]
yes, but please show your configuration, pom and commands used so we can help

**Comment by jeremylong** [comment]
If the build fails as you have pointed out dependency-check runs successfully and reports zero findings. Works as expected. This is not an ODC issue rather an issue with calling ODC after you already know the build failed.
