### ISSUE TITLE
NVE CVE Updater – What happens during an update?

### ISSUE THREAD

**Issue by ejayt** [dependency-check/DependencyCheck#3708]
What does a NVE CVE update do exactly? 

Does it dump the current data and download a fresh copy? 

Does it update only what it needs? If this is the case, does it also clean up anything stale? Should the data directory be purged every now and then? 

How big can the data-directory get overtime?

**Comment by jeremylong** [comment]
During the initial update the entire NVD CVE data feed is downloaded, processed, and stored in a local H2 database. If you run ODC at least once every 7 days only 2 smaller files need to be downloaded to keep the ODC database up-to-date. If you go beyond the 7 days an incremental update will still occur; however, it will take longer as it will re-process any of the yearly CVE data feed files that have been updated.

It is recommended to always keep your data directory; do not run the purge command unless the H2 database becomes corrupted somehow.

In terms of size - the H2 database between executions is around 120MB. However, during execution this can grow quite a bit. Additionally, the data directory contains a cache that is used to keep data around to speed up repeated executions. Unfortunately, the size of the cache is a little dependent upon your usage of the tool and I do not have any good stats on the size.

**Comment by ejayt** [comment]
> the size of the cache is a little dependent upon your usage of the tool

By "usage of the tool", do you mean when the tool scans dependencies? In what event does something get stored in the cache?

**Comment by jeremylong** [comment]
Results from Central (if using the CLI, ANT, or Docker integrations and the central analyzer is enabled), Results from npm audit's APIs if scanning npm, yarn, or pnmp, data from the OSS Index if the OSS Index Analyzer is enabled. Basically, most times when the tool (e.g. dependency-check) calls out to another system during execution.
