### ISSUE TITLE
Is travis-ci being used anymore?

### ISSUE THREAD

**Issue by sellersj** [dependency-check/DependencyCheck#3712]
I think that the CI activities have moved to github actions, but it's unclear to me if there are still things remaining in travis-ci.

If travis-ci is dead, then the pom should be updated so the published site points to the correct place.
https://github.com/jeremylong/DependencyCheck/blob/main/pom.xml#L103

Changed to
https://github.com/jeremylong/DependencyCheck/actions

**Comment by jeremylong** [comment]
Thanks - yes, everything has moved to github actions (for better or worse: https://github.com/jeremylong/musical-octo-carnival). I'll try and get this updated in the morning.
