### ISSUE TITLE
Input on getting results even if the build fails

### ISSUE THREAD

**Issue by aejazuddinam** [dependency-check/DependencyCheck#3714]
Hi ,
This is rather a question not an issue, need advise on this.

Whenever the build fails, the dependency checks run successfully and reports zero findings with empty report as expected.

What I was thinking is that dependency check only needs the dependency information from the Maven build. So even if there are compilation failures or test errors the information we need to generate dependency data is good. So what I was trying to understand was if we ran a check in those scenarios will we get a working report and can we distinguish error cases?

**Note: i use below CLI command for DC after maven build**
dependencycheck additionalArguments: '--scan "./" --prettyPrint --out build/dependency-check-report --format ALL --cveUrlModified=*/CVE/NIST/nvdcve-1.1-modified.json.gz --cveUrlBase=*/CVE/NIST/nvdcve-1.1-%d.json.gz --retireJsUrl=*/CVE/RetireJS/jsrepository.json --disableCentral true --disableCentralCache false --disableOssIndex false', odcInstallation: 'DependencyCheck'

**Comment by jeremylong** [comment]
There are some build failures that would be an issue for ODC - like not being able to download the dependencies or there was an unreadable pom.xml. However, if it was just a compilation error you are correct that ODC should work.

One thing to note about your above command - as you are using the CLI I would highly recommend doing something like:

```shell
mvn dependency:copy-dependencies 
```

Before calling the CLI.
