### ISSUE TITLE
Bump xstream to 1.4.18

### ISSUE THREAD

**Issue by alan-czajkowski** [dependency-check/DependencyCheck#3719]
**core/pom.xml**:
```
        <dependency>
            <groupId>com.thoughtworks.xstream</groupId>
            <artifactId>xstream</artifactId>
            <version>1.4.8</version>
            <scope>test</scope>
            <optional>true</optional>
        </dependency>
```

as per: https://mvnrepository.com/artifact/com.thoughtworks.xstream/xstream

**Comment by jeremylong** [comment]
This is an optional test dependency - it is known vulnerable so that ODC can test to make sure it finds the vulnerabilities.  ODC does not actually use or distribute this, or any of the optional test, dependencies.
