### ISSUE TITLE
False positives with Geronimo specs

### ISSUE THREAD

**Issue by victornoel** [dependency-check/DependencyCheck#372]
Hi,

I noticed some false positives that would be useful for the community.

The Geronimo project has released many specs package for many Java API.
These specs are not geronimo per se, but are identified as such, they usually only contain interfaces.

For example there is:
org.apache.geronimo.specs:geronimo-jms_1.1_spec:1.1.1
mistaken for
cpe:/a:apache:geronimo:1.1.1

More generally, I suspect that all of the maven artefacts in the groupId org.apache.geronimo.specs (http://search.maven.org/#search|ga|1|g%3A%22org.apache.geronimo.specs%22) are susceptible to get mistaken for cpe:/a:apache:geronimo:*

I think they should all be added to the suppression file.

Thanks

**Comment by jeremylong** [comment]
Thanks for the false positive report - I completely agree and have added a suppression rule for this.

--Jeremy
