### ISSUE TITLE
Azure CI OWASP Dependency check task failing to download

### ISSUE THREAD

**Issue by milyas-salik** [dependency-check/DependencyCheck#3724]
I installed the dependency check extension for my Azure CI. As mentioned in the link : [https://marketplace.visualstudio.com/items?itemName=dependency-check.dependencycheck&ssr=false#qna](https://marketplace.visualstudio.com/items?itemName=dependency-check.dependencycheck&ssr=false#qna
)
I followed the steps mentioned, but getting the below issue.. 

**Hostname/IP doesn't match certificate's altnames: "Host: api.github.com. is not in the cert's altnames: DNS:*.ABC.com, DNS:ABC.com"
Unhandled error condition detected.**

Please do the needful.

**Comment by jeremylong** [comment]
I do not believe anyone on this issue board maintains the Azure Dev Ops extension. Please open a ticket here: https://github.com/dependency-check/azuredevops

**Comment by milyas-salik** [comment]
Thanks @jeremylong for you reply.

Opened the issue here : https://github.com/dependency-check/azuredevops/issues/90
