### ISSUE TITLE
Could not get unknown property 'waitTime' with version 6.4.1 with Gradle

### ISSUE THREAD

**Issue by rashidi** [dependency-check/DependencyCheck#3726]
**Describe the bug**
Executing `dependencyCheckAnalyze` will return an error `Could not get unknown property 'waitTime' for extension 'dependencyCheck' of type org.owasp.dependencycheck.gradle.extension.DependencyCheckExtension.`

**Version of dependency-check used**
The problem occurs using version 6.4.1 of the gradle plugin (cli, gradle plugin, maven plugin, etc.)

**Log file**
[Logs on GitHub Actions](https://github.com/rashidi/dependency-check-gh-3762/runs/3865860720#step:5:236)

**To Reproduce**
1. Create the following `build.gradle`

```groovy
plugins {
    id 'org.owasp.dependencycheck' version '6.4.1'
    id 'java'
}

group = 'gradle'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '17'

repositories {
    mavenCentral()
}

test {
    useJUnitPlatform()
}
```

2. Execute `gradle dependencyCheckAnalyze`

**Expected behavior**
Build successful

**Additional context**
JDK: 17
Gradle version: 7.2
Repository: [rashidi/dependency-check-gh-3762](https://github.com/rashidi/dependency-check-gh-3762)

**Comment by michaelbrewer** [comment]
same issue here.

**Comment by jeremylong** [comment]
Just pushed 6.4.1.1 which resolves this.
