### ISSUE TITLE
How to check which Java is being used when running ODC

### ISSUE THREAD

**Issue by aejazuddinam** [dependency-check/DependencyCheck#3728]
Hi,
This is a question not an issue. Im using CLI command but seems by java is not being picked, how do i check with CLI which java path ODC is using ? any options for debugging that.

**CLI:**
dependencycheck additionalArguments: '--scan "./" --prettyPrint --out build/dependency-check-report --format ALL --cveUrlModified=*/nvdcve-1.1-modified.json.gz --cveUrlBase=*/CVE/NIST/nvdcve-1.1-%d.json.gz --retireJsUrl=*/CVE/RetireJS/jsrepository.json --disableCentral true --disableCentralCache false --disableOssIndex false', odcInstallation: 'DependencyCheck'

**Comment by mprins** [comment]
perhaps add `-showversion` as a first option to get the JVM; it can't show the path though, just the JVM in use

**Comment by aejazuddinam** [comment]
Hi @mprins , can you please give an example of CLI , is there any way to find the java path being used ?
-showversion also displaying syntax errors

**Comment by jeremylong** [comment]
run `java --version`

**Comment by aejazuddinam** [comment]
I'll reframe it, not in the linux server to check what is the java path/version( java --versio),

Im checking in ODC CLI command it there is anything to check java version use&its path, only i see --v (which gives only ODC version)  as an option in ODC CLI.

**Comment by mprins** [comment]
it's not functionality available in ODC
