### ISSUE TITLE
Wrong result of check when running in Jenkins

### ISSUE THREAD

**Issue by haugsrud** [dependency-check/DependencyCheck#3729]
**Describe the bug**
When I run dependency-check for the same project locally (Mac) I get 0 vulnerabilities, whereas I get 380 when I run it in Jenkins via the plugin.

**Version of dependency-check used**
The problem occurs using version 6.3.1 of Dependency-check.

Mac OS locally. Command 'dependency-check --scan target --disableAssembly'

Jenkins version 2.277.3.

The command to trigger dependency-check in Jenkins is:
`dependencycheck additionalArguments: '--data /dependency-checker-db-6 --scan target --disableAssembly --noupdate --suppression owasp/suppression.xml --format XML --format HTML --log dependencyCheckLog.txt', odcInstallation: 'dependency-check-6.3.1`

**Log file**
Log from local run (ok):
https://gist.github.com/haugsrud/1e03197bab9e287d4f1d3bd9c4378cf0

Log from Jenkins run (not ok):
https://gist.github.com/haugsrud/9e1f86ab931d6ea89535a9a1b1c1315c

**To Reproduce**
1. Run the project locally
2. Get expected result with no vulnerabilities
3. Run the project in Jenkins
4. Get 380 vulnerabilities which I believe is all false positives

**Expected behavior**
I expect the result to be like this, which is the one I get when run locally:
<img width="418" alt="image" src="https://user-images.githubusercontent.com/44436052/136938409-0d21c32d-613d-4380-b9c8-9f5198a102a4.png">

But when running in Jenkins I get this:
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/44436052/136938470-fdde220e-d348-4961-8831-aaf4948654a2.png">

**Additional context**
I want to know how Dependency-check works in regard to running a pipeline in Jenkins. How does it pick up use of Jenkins and hence report issues that don't exist when I run it locally?

EDIT:
This is a multi-module maven-project. I think this might cause some of the issues as other projects who are not multi-module run fine in the same pipeline.

**Comment by mprins** [comment]
You've set up to scan a directory; is the contents of the directory exactly the same on both platforms?

in any case it's better to use one of the options that uses a dependencymangement (maven, gradle,..) instead of the cli

**Comment by haugsrud** [comment]
> You've set up to scan a directory; is the contents of the directory exactly the same on both platforms?
> 
> in any case it's better to use one of the options that uses a dependencymangement (maven, gradle,..) instead of the cli

Yes, I scan the same. Both locally and in the Jenkins pipeline I run 'mvn clean install' first, then run the dependency-check. 

We have run the same pipeline for numerous applications, but I have not experienced this difference before. 

It seems that Dependency-check somehow gets hold of information that a jenkins instance is running and wrongfully lists older vulnerabilities for this Jenkins instance. Every single CVE that is listed are referring to a vulnerability for an older Jenkins-version than we are running.

**Comment by jeremylong** [comment]
This is not an ODC issue- rather the issue is on jenkins. Whatever is being placed into the "target" directory is being scanned.  The logs you posted - are not the actual logs from ODC that we would need to debug this further. We would need the `--log dependencyCheckLog.txt` file.

**Comment by haugsrud** [comment]
@jeremylong here is the log from dependencyCheckLog.txt: https://gist.github.com/haugsrud/f64268eebbd0041806a3fa4dea6ae266

In addition I have tried running the check via maven and this command (first I run mvn clean install):
`mvn org.owasp:dependency-check-maven:aggregate -DsuppressionFile=owasp/suppression.xml -Dodc.outputDirectory=. -DdataDirectory=/dependency-checker-db-6 -DautoUpdate=false -Dformats=HTML,XML`

When I run it this way I get a completely different result in the dependency-check report
<img width="460" alt="image" src="https://user-images.githubusercontent.com/44436052/137135698-e396082c-4e75-404b-b170-86ae998808ad.png">

**Comment by jeremylong** [comment]
The report from the Maven plugin is likely the most accurate. With the CLI it is only scanning the build artifacts. So if you have not run `mvn package` you will get zero results on a maven project. Also, if you are using the CLI/docker image to scan a Maven project and the build artifacts are not a WAR or spring-boot archive - you would likely need to run `mvn dependency:copy-dependencies package` prior to running ODC.

**Comment by haugsrud** [comment]
Thank you for your answer, I guess my issue came from this being the first project not being a WAR and that caused the issue since I were using the CLI. 

I have changed my pipelines to use the Maven plugin for all maven projects. I'll close this issue.
