### ISSUE TITLE
Scan other parts of my landscape; not just my code

### ISSUE THREAD

**Issue by Jurrie** [dependency-check/DependencyCheck#3731]
I have implemented Dependency Check in my Maven build, and it sometimes flags CVEs. I'm pleased with it! However, there are components in my landscape that I want to check for known CVE's, but are not in my code. Take for example my database server: PostgreSQL.

There are CVE's on PostgreSQL in the NVD. As far as I can tell, all that is missing is a file type analyzer. Maybe something that scans the output of `dpkg -l` on Debian, or `yum list installed` on CentOS.

If I would build such a file type analyzer, I could use Cron to periodically scan my system for CVE's in the NVD. Is this a good way to go? Or am I completely wrong here, and are there better routes to take?

An alternative would be to create a file type analyzer that simply reads a static file of software components that are in my landscape. This would be less ideal, but it would allow keeping an eye out for CVE's on systems where I can not run Dependency Check. Is something like this available?

**Comment by jeremylong** [comment]
ODC has several base suppression rules for the Postgres server as the majority of users are scanning applications that use the driver. Additionally, ODC does not incorporate any OS or Hardware CVEs in the database (of course, this is configurable).

My suggestion would be to take a look at dependency-track.

**Comment by Jurrie** [comment]
Thanks Jeremy, Dependency Track seems a more suited choice.
