### ISSUE TITLE
Issue from dependency-check display on "issue"

### ISSUE THREAD

**Issue by Dubouchj** [dependency-check/DependencyCheck#3733]
Is it possible to see issues/vulnerabilities from **dependency-check report** on the issue of the SonarQube project (/project/issues?id=test&resolved=false)? 

I did some tests with this [project](https://github.com/dependency-check/dependency-check-sonar-plugin/tree/master/examples/multi-project-csproj) which display 3 vulnerabilities but It is not display on the "Issues"

![image](https://user-images.githubusercontent.com/33114629/136986400-3639bb27-8223-4808-a46a-ded9a8b1041d.png)
![image](https://user-images.githubusercontent.com/33114629/136986424-dad5e56b-641c-4689-b56c-77e399d032d8.png)

**Comment by jeremylong** [comment]
I do not believe anyone on this board works on the sonar plugin - try posting your question on https://github.com/dependency-check/dependency-check-sonar-plugin/issues
