### ISSUE TITLE
It seems DependencyCheck is no longer compatible with jdk8?

### ISSUE THREAD

**Issue by Grimoren** [dependency-check/DependencyCheck#3737]
**Describe the bug**
Build failing with this error using the latest version.
         Required by:
         project :
         > No matching variant of org.owasp:dependency-check-gradle:6.4.1.1 was found. The consumer was configured to find a runtime of a library compatible with Java 8, packaged as a jar, and its dependencies declared externally but:
         - Variant 'apiElements' capability org.owasp:dependency-check-gradle:6.4.1.1 declares a library, packaged as a jar, and its dependencies declared externally:
         - Incompatible because this component declares an API of a component compatible with Java 11 and the consumer needed a runtime of a component compatible with Java 8
         - Variant 'javadocElements' capability org.owasp:dependency-check-gradle:6.4.1.1 declares a runtime of a component, and its dependencies declared externally:
         - Incompatible because this component declares documentation and the consumer needed a library
         - Other compatible attributes:
         - Doesn't say anything about its target Java version (required compatibility with Java 8)
         - Doesn't say anything about its elements (required them packaged as a jar)
         - Variant 'runtimeElements' capability org.owasp:dependency-check-gradle:6.4.1.1 declares a runtime of a library, packaged as a jar, and its dependencies declared externally:
         - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8
         - Variant 'sourcesElements' capability org.owasp:dependency-check-gradle:6.4.1.1 declares a runtime of a component, and its dependencies declared externally:
         - Incompatible because this component declares documentation and the consumer needed a library
         - Other compatible attributes:
         - Doesn't say anything about its target Java version (required compatibility with Java 8)
         - Doesn't say anything about its elements (required them packaged as a jar)A clear and concise description of what the bug is.

**To Reproduce**
Run with the latest version of dependency check on jdk8 

**Expected behavior**

**Additional context**

**Comment by aikebah** [comment]
Most definitely the gradle plugin is compatible with java 8, as can be seen from its [build workflow](https://github.com/dependency-check/dependency-check-gradle/blob/00a39108c6e2b9688cef7c46465b7d288a18a565/.github/workflows/build.yml#L18)

You appear to run into an incompatibility of the gradle plugin with modern gradle versions.

Duplicate of https://github.com/dependency-check/dependency-check-gradle/issues/232

**Comment by jeremylong** [comment]
A work around is listed in the gradle issue 232 and a long term fix will be included in the next release.
