### ISSUE TITLE
"No matching variant" of owasp was found after upgrade to 6.4.1.1. Is this compatibility issue with java version?

### ISSUE THREAD

**Issue by Olsson93** [dependency-check/DependencyCheck#3740]
After upgrading to 6.4.1.1 I get the following error, am I missing a configuration or is this an issue with the Java version I'm running?

> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve org.owasp:dependency-check-gradle:6.4.1.1.
     Required by:
         project :
         project : > org.owasp.dependencycheck:org.owasp.dependencycheck.gradle.plugin:6.4.1.1
      > No matching variant of org.owasp:dependency-check-gradle:6.4.1.1 was found. The consumer was configured to find a runtime of a library compatible with Java 8, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '7.2' but:
          - Variant 'apiElements' capability org.owasp:dependency-check-gradle:6.4.1.1 declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares an API of a component compatible with Java 11 and the consumer needed a runtime of a component compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.2')
          - Variant 'javadocElements' capability org.owasp:dependency-check-gradle:6.4.1.1 declares a runtime of a component, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.2')
          - Variant 'runtimeElements' capability org.owasp:dependency-check-gradle:6.4.1.1 declares a runtime of a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.2')
          - Variant 'sourcesElements' capability org.owasp:dependency-check-gradle:6.4.1.1 declares a runtime of a component, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.2')

**Comment by jeremylong** [comment]
duplicate of https://github.com/dependency-check/dependency-check-gradle/issues/232
