### ISSUE TITLE
OpenPGP signature issues

### ISSUE THREAD

**Issue by imrejonk** [dependency-check/DependencyCheck#3745]
According to the [Installation & Usage](https://jeremylong.github.io/DependencyCheck/dependency-check-cli/index.html) section in the documentation, the dependency-check release assets are signed with this OpenPGP key ID: `F9514E84AE3708288374BBBE097586CFEA37F9A6`. However, this key expired on October 13th, and a newer (unexpired) version of the key is not available on the keyservers.

Furthermore, the release assets have been signed with OpenPGP key ID `259A55407DD6C00299E6607EFFDE55BE73A2D1ED` since version 6.4.0. This could indicate that the release assets have been compromised, or that the signing key has simply been rotated. In any case, it would be nice to have this clarified.

Maybe @jeremylong can shed some light on this?

**Comment by mprins** [comment]
duplicates #3635

**Comment by imrejonk** [comment]
Thanks, that confirms that the key was indeed rotated. Could someone publish the new key somewhere? I can't verify the 6.4.0 and 6.4.1 releases right now.

**Comment by aikebah** [comment]
@imrejonk The correct key-reference to download can be found in the issue comment where Jeremy self-validated the signature https://github.com/jeremylong/DependencyCheck/issues/3635#issuecomment-940370981

**Comment by imrejonk** [comment]
Ah, I see that the public key has now been uploaded to the key servers. Thanks!
