### ISSUE TITLE
Dependency Check doesn't show anything on Docker container with Gradle project

### ISSUE THREAD

**Issue by rios0rios0** [dependency-check/DependencyCheck#3752]
**Describe the bug**
Dependency check doesn't work when it is running inside the official Docker image, and the project is a Gradle Java project, with folders "buildSrc" and "src", mounted in the container at "/project".

**Version of dependency-check used**
The problem occurs using version 6.4.1 of the Docker (Gradle plugin works)

**Log file**
Doesn't apply.

**To Reproduce**
1. Go to the project folder.
2. Execute: `docker run --volume $(pwd):/project --volume $(pwd)/.owasp:/usr/share/dependency-check/data owasp/dependency-check:6.4.1 --scan '/project' --failOnCVSS 5 --format "ALL" --out "/project/build/reports" --project api`
3. The CLI will conclude the analysis by saying that doesn't have any problem.
4. Run with Gradle plugin, and it has 5 issues

**Expected behavior**
The same output of the Gradle plugin.

**Additional context**
With container:
```
[INFO] Finished Version Filter Analyzer (0 seconds)
[INFO] Finished Hint Analyzer (0 seconds)
[INFO] Created CPE Index (1 seconds)
[INFO] Finished CPE Analyzer (2 seconds)
[INFO] Finished False Positive Analyzer (0 seconds)
[INFO] Finished NVD CVE Analyzer (0 seconds)
[INFO] Finished RetireJS Analyzer (2 seconds)
[INFO] Finished Sonatype OSS Index Analyzer (1 seconds)
[INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
[INFO] Finished Dependency Bundling Analyzer (0 seconds)
[INFO] Analysis Complete (51 seconds)
[INFO] Writing report to: /project/build/reports/dependency-check-report.xml
[INFO] Writing report to: /project/build/reports/dependency-check-report.html
[INFO] Writing report to: /project/build/reports/dependency-check-report.json
[INFO] Writing report to: /project/build/reports/dependency-check-report.csv
```
With Gradle plugin:
```
Generating report for project api
Found 5 vulnerabilities in project api
One or more dependencies were identified with known vulnerabilities in API:
<-- REMOVED UNNECESSARY -->

See the dependency-check report for more details.
```

**Comment by jeremylong** [comment]
The ODC docker image is just the CLI. You would see the same results as the CLI is intended to scan the build artifacts - not the source code. If using the CLI/Docker image on a gradle project you would need to do something like the following:

### build.gradle

```groovy
// Add the copyDependencies task
task copyDependencies(type: Copy) {
  from configurations.default
  into 'dependencies'
}
```
 
Then run the build on the command prompt followed by running the scan:

```shell
$ ./gradlew build copyDependencies
$ dependency-check.sh -s ./build -o ./build/reports
```

Depending on your build - the `copyDependencies` task may or may not be needed. It would not be needed if you were building a WAR file or a spring-boot jar - as all of the dependencies are included in the resulting build artifacts.

In reality, a better approach would be to just use the ODC gradle plugin. The team highly recommends using the Maven, Gradle, or SBT plugins to run the scans as information from the build system itself is able to be used in the analysis.

**Comment by rios0rios0** [comment]
Thanks for the clarification.
