### ISSUE TITLE
Support NIST API key

### ISSUE THREAD

**Issue by magJ** [dependency-check/DependencyCheck#3760]
https://nvd.nist.gov/general/news/API-Key-Announcement

NIST recently announced that within six months, requests to their NVD APIs will require acquiring and using an API key, in order to avoid further throttling.

Could we please add support for configuring an API key?

**Comment by mprins** [comment]
ODC does not currently support/use the NVD API, see #3676

**Comment by magJ** [comment]
Ah I see, I'll close this then, if API support is built, it will probably be addresses at that point anyway.
