### ISSUE TITLE
$cpeSort cannot be resolved

### ISSUE THREAD

**Issue by awhitford** [dependency-check/DependencyCheck#377]
When running `mvn -X dependency-check:check` on a project, I am seeing this:

```
[DEBUG] Null reference [template 'templates/HtmlReport.vsl', line 635, column 46] : $cpeSort cannot be resolved.
```

This suggests that there is a template issue.

**Comment by jeremylong** [comment]
These Velocity debug warnings are on my todo list for the next release. We only realized this was an issue when we moved from JUL to SLF4J - I had never run the reporting with the velocity logging level at debug...  Note, these do not affect the output of the report.

**Comment by jeremylong** [comment]
This has been fixed and the current snapshot.
