### ISSUE TITLE
*.lib files does not checked even if is present in false negative hints file

### ISSUE THREAD

**Issue by ferben** [dependency-check/DependencyCheck#3774]
*.dll library are scanned properly, but *.lib file is not scanned even if I force it by hint.xml file.
Example:
  ```
<hint>
    <given>
      <fileName contains="my.lib" regex="false" caseSensitive="false"/>
    </given>
    <add>
      <evidence type="vendor" source="hint analyzer" name="vendor" value="alladin" confidence="HIGHEST"/>
      <evidence type="product" source="hint analyzer" name="product" value="hasp_srm_run-time" confidence="HIGHEST"/>
      <evidence type="version" source="hint analyzer" name="version" value="3.11" confidence="HIGHEST"/>
    </add>
  </hint>
```

**Comment by jeremylong** [comment]
DLL are scanned in two ways - once to check if it is a dotnet assembly and once if it is a PE executable format. The native scanning for C/C++ projects is not that strong in ODC and the tool primarily looks at cmake and autoconf files. We are looking at conan in the future.
