### ISSUE TITLE
False negative hint file how to

### ISSUE THREAD

**Issue by ferben** [dependency-check/DependencyCheck#3775]
Hello,
I need scan my C++ project, where is included pcre2 source code.
Is there are any posibility to modify False Negative xml file to report it:

Following example does not work:
```
 <hint>
    <given>
      <fileName contains="pcre2.h" regex="false" caseSensitive="false"/>
    </given>
    <add>
      <evidence type="vendor" source="hint analyzer" name="vendor" value="pcre" confidence="HIGHEST"/>
      <evidence type="product" source="hint analyzer" name="product" value="pcre" confidence="HIGHEST"/>
      <evidence type="version" source="hint analyzer" name="version" value="10.36" confidence="HIGHEST"/>
    </add>
  </hint>
```
dependency-check found the file:
```
2021-11-02 10:33:44,390 org.owasp.dependencycheck.App:358
DEBUG - Found file C:\my\work\Src\pcre2\pcre2.h
```

But in xml/html missing info about used library.

Can I fix it by modify hint file or is there any other possibility to force add pcre2 lib into dependency-check?

Thank you

**Comment by jeremylong** [comment]
ODC does not actually "scan" header files. The logging in the scanner could be much improved as it does indicate that a header file is being analyzed. ODC can analyze autoconf and cmake files.
