### ISSUE TITLE
The versions of packages are wrong if package contains well known name

### ISSUE THREAD

**Issue by tomaso** [dependency-check/DependencyCheck#3779]
**Describe the bug**
We have some packages that include name of other package in their name. The version of such included package is then considered to be identical to the main package and it completely fools the version comparison for the "included" package.

For example any jar file containing the string "gradle" is considered to be a part of Gradle build system. Then dependency check tries to guess the version, so if it finds e.g. file "gradle-test-logger-plugin-2.1.1.jar", it marks it as "cpe:2.3:a:gradle:gradle:2.1.1:::::::*" so it thinks it is a Gradle v2.1.1. And it then reports various old CVEs that were fixed in Gradle 5.6 (we're actually using Gradle 7.2).

**Version of dependency-check used**
The problem occurs using version 6.1.6 and also 6.4.1

**To Reproduce**
1. Include a package called gradle-my-custom-package-2.1.1.jar in your dependencies
2. Run dependency check (docker run --rm  --volume $PWD:/src:z  --volume /tmp/a:/tmp/a owasp/dependency-check:6.4.1 --scan /src --format ALL --project my-project --out /tmp/a --disableAssembly
3. See the gradle-my-custom-package causing CVEs reported for "cpe:2.3:a:gradle:gradle:2.1.1:::::::*"

**Expected behavior**
The deps check should recognize that the version of used gradle was actually higher and so there is no security issue in the deps.

**Comment by mprins** [comment]
It would help if you used a dependency management aware tool (maven, gradle) to run ODC  and not the command-line tool which basically only has filenames to look at

**Comment by jeremylong** [comment]
As @mrpins already pointed out - you'll almost always get better results using the gradle plugin on gradle projects. Additionally, this is expected behavior. Please see https://jeremylong.github.io/DependencyCheck/general/internals.html

You can easily create suppression rules for these FP using the HTML report, see https://jeremylong.github.io/DependencyCheck/general/thereport.html and https://jeremylong.github.io/DependencyCheck/general/suppression.html

**Comment by Lars5678** [comment]
We have the same problem with Maven.

For us it was the string "mysql". We use the MySql version 8.x which is not vulnerable. But we still have our own lib, e.g. de.custom.custom-mysql:5.0.8

ODC now says that we are using a vulnerable version of MySql. Just the mysql:mysql-connector-java:5.0.8 which is not correct.

Ok, now you can suppress the mysql:mysql-connector-java:5.0.8 version, but then you won't notice if someone uses it.
Or does ODC then recognize that from the SHA?

But the far worse problem is that the build fails if this exact library does not exist in Maven Central. The ODC plugin wants to load this dependency.

What should one do here then? No report is created with a Supress entry with a SHA.
