### ISSUE TITLE
how to use GrokAssembly with DependencyCheck cli?

### ISSUE THREAD

**Issue by BodyCSoulN** [dependency-check/DependencyCheck#3792]
How can i use GrokAssembly with DependencyCheck cli on windows 10?

**Comment by jeremylong** [comment]
GrokAssembly is an internal tool used by ODC to inspect assembly files. You need to have dotnet 3.1 installed and you should be able to analyze dotnet DLLs and EXEs.

**Comment by BodyCSoulN** [comment]
of course i have installed them, and then?
