### ISSUE TITLE
Update brew formula to latest release 6.5.0

### ISSUE THREAD

**Issue by dehlen** [dependency-check/DependencyCheck#3794]
Hi,

could you please update the Homebrew formula to the latest release 6.5.0? Since this version fixes the analyzer for the Swift Package Manager I need to update to this version and would really love to install via Homebrew.

I just executed your sha-cli script for you to make it easier to update the formula:
"e27ab0c010a447e5d2ac62063112c3e1a25364193450cb4345fc18defb4511a2".

<img width="679" alt="CleanShot 2021-11-12 at 10 06 55@2x" src="https://user-images.githubusercontent.com/680180/141441056-f41f80c0-2a13-4e8c-9a08-d203e71d1f17.png">

Kind regards,
David

**Comment by jeremylong** [comment]
So sorry I missed that on the last release.  I really need to look into fully automating the publishing to homebrew.

The PR to update homebrew is here: https://github.com/Homebrew/homebrew-core/pull/89264

**Comment by dehlen** [comment]
Thank you very much :) Your work is really appreciated. I'll close this since you already made the PR.

**Comment by carlocab** [comment]
You can use this GitHub action to automate updating the Homebrew formula: https://github.com/dawidd6/action-homebrew-bump-formula

**Comment by dehlen** [comment]
Hey, sorry to reopen again but is it possible that v6.5.0 is not installable at the moment? On the website the 6.4.1 release is referenced at the moment which probably does not work correctly with the live check method in the brew formula?

**Comment by dehlen** [comment]
Nevermind although the version specified on the homepage is still the old one I found the mistake on our end:

> For stability and for increased build performance by default the macOS VMs have brew installed but the main source is changed from the official https://github.com/Homebrew/homebrew-core 12 to the Bitrise maintained mirror https://github.com/bitrise-io/homebrew-core 16 (and similarly for homebrew cask changed from https://github.com/Homebrew/homebrew-cask 3 to https://github.com/bitrise-io/homebrew-cask 5 ).
> 
> The mirror is updated frequently but it follows the official repo with a delay.

... which is why our CI is currently not seeing the new formula.

**Comment by jeremylong** [comment]
I also just fixed the versions on the OWASP project page. Somehow I missed that on the last release..
