### ISSUE TITLE
Parent target Report showes zero scanned dependencies in Multi-pom project

### ISSUE THREAD

**Issue by m-coder99** [dependency-check/DependencyCheck#3795]
I configuring the dependency-check plugin in maven project. It is multi-pom project. I configure the dependency-check plugin in parent pom, though it is generating the report in all child module. It scanning dependencies from parent target/lib folder where I download the dependency. The report generated in parent target file showes scanned dependecies zero. why? Could you please tell @jeremylong.

**Comment by mprins** [comment]
In general a `pom` artifact does/should not have dependencies, does yours? 

You should use the `aggregate` goal for multi-module projects: https://jeremylong.github.io/DependencyCheck/dependency-check-maven/aggregate-mojo.html
