### ISSUE TITLE
Is dependency-check plugin able to scan the jars from target folder

### ISSUE THREAD

**Issue by m-coder99** [dependency-check/DependencyCheck#3796]

**Comment by aikebah** [comment]
Able yes, but you shouldn't do it and just let it scan your maven project with the maven plugin. Yields better results with fewer false positives and potentially false negatives.

**Comment by jeremylong** [comment]
If you need to scan the target folder - be sure to run something like `mvn dependency:copy-dependencies` to ensure all of the dependencies are in the target folder. By default they would not be.
