### ISSUE TITLE
PHP support

### ISSUE THREAD

**Issue by youssef-chtourou** [dependency-check/DependencyCheck#3799]
Hello
Thanks for your effort
Does this plugin support PHP (symphony) ?
if yes , how i can integrate them ?

**Comment by mprins** [comment]
there is exprimental composer support but not symphony as you can see in the docs: https://jeremylong.github.io/DependencyCheck/analyzers/index.html

**Comment by youssef-chtourou** [comment]
Hello
how i can start scan on php ?

**Comment by jeremylong** [comment]
If using composer you can run:

```shell
$ dependency-check.sh --enableExperimental -s [path/to/scan] -o [path/to/generated/reports]
```
