### ISSUE TITLE
Empty reports and disabled pip and python analyzers

### ISSUE THREAD

**Issue by ghost** [dependency-check/DependencyCheck#3806]
I am running DependencyCheck (v6.5.0.) CLI in Azure DevOps to scan python scripts for vulnerabilities. I used the option **--enableExperimental** to enable the Python and Pip analyzers. However, the plugin produces empty reports

![image](https://user-images.githubusercontent.com/59301914/142244584-004854b6-1e7e-407e-baef-738fe2548a72.png)

![image](https://user-images.githubusercontent.com/59301914/142245299-19f875ca-df02-4177-bb4d-a395d60698c3.png)

Looking at the logs, I checked that the analyzers are indeed enabled

![image](https://user-images.githubusercontent.com/59301914/142245302-2d58a877-ac98-4e25-92c4-ad837336f0b2.png)

However, further in the log, I noticed that the analyzers have been skipped

![image](https://user-images.githubusercontent.com/59301914/142245865-c059e707-50dc-4102-b3a6-2872701bcd1a.png)

This is the command I am using in the Azure DevOps pipeline (I am not using the extension)

`dependency-check.sh --project 'testing_owasp' -l '$(System.DefaultWorkingDirectory)/log.txt' --enableExperimental --format 'ALL' --scan $(System.DefaultWorkingDirectory)/**/* --data "$(System.DefaultWorkingDirectory)/owasp-cache/depcheck-v6" --noupdate --disableOssIndex`

Notice that I am using a local database since I am working in an air-gapped environment.

Do you know why are the analyzers skipped ? 

Thanks !

**Comment by ghost** [comment]
Any hints ?

**Comment by mprins** [comment]
How have you defined your dependencies? using a `requirements.txt` and/or  a `PipFile`?.... 

https://github.com/jeremylong/DependencyCheck/blob/5beebdf2b24dbeecd4725912d7872665a5449b5b/core/src/main/java/org/owasp/dependencycheck/analyzer/PipAnalyzer.java#L62

https://github.com/jeremylong/DependencyCheck/blob/5beebdf2b24dbeecd4725912d7872665a5449b5b/core/src/main/java/org/owasp/dependencycheck/analyzer/PipfileAnalyzer.java#L62

**Comment by mprins** [comment]
also see https://github.com/jeremylong/DependencyCheck/blob/main/src/site/markdown/analyzers/pip.md and https://github.com/jeremylong/DependencyCheck/blob/main/src/site/markdown/analyzers/python.md

**Comment by ghost** [comment]
I used a requirements.txt file with a known vulnerability of pillow==2.5.0 to test the plugin

**Comment by jeremylong** [comment]
Sorry about the delay - my best guess would be that `--scan $(System.DefaultWorkingDirectory)/**/* ` from your command is not being interpreted correctly. Leave the /**/* off as it is not needed.
