### ISSUE TITLE
Is it possible to run DependencyCheck with input file?

### ISSUE THREAD

**Issue by nayuku** [dependency-check/DependencyCheck#3815]
I've got input file.txt structured like this:

org.json:json		20180813
com.jcraft:jsch		0.1.54
info.jerrinot:subzero-all		0.10
com.github.nmorel.gwtjackson:gwt-jackson		0.15.4
....

Is it possible to scan those dependencies from file or transform this input file into something that DependencyCheck can work with?

**Comment by mprins** [comment]
looks like you have alle the coordinates needed to transform that into a Gradle or Maven dependency structure

**Comment by nayuku** [comment]
@mprins Thanks, I transformed it to Maven structure and run with `mvn org.owasp:dependency-check-maven:check` and it worked. However there was error with 40 packages, (they are not in maven repo) so i still needed to check them manualy ;/

**Comment by jeremylong** [comment]
If those packages are in another repository just configure maven to use the other repo in addition to central.
