### ISSUE TITLE
composer.lock <> path - different results

### ISSUE THREAD

**Issue by kmengel242** [dependency-check/DependencyCheck#3816]
Hello,
we use composer for our php projects. 
If I tell the dependency-check directly the composer.lock file as input parameter, I get different (less) results than if I tell the directory where the composer.lock file is located.

Although the included javascript libraries are also included in composer.lock, they are only found and listed if I specify the path.

Apparently, retireJS is only executed when I specify the path and not when I scan the composer.lock file directly.

Is this a bug or intentional?

Many thanks and best regards
Ka!

**Comment by jeremylong** [comment]
This is by design. The RetireJS analyzer needs to scan the actual JS files; whereas the PHP composer analyzer only looks at the composer.lock file. 

Recommendation - don't just scan the composer.lock, scan the whole application.
