### ISSUE TITLE
Should suppressionFile work for all sub projects when specified in allProjects? 

### ISSUE THREAD

**Issue by dafunker** [dependency-check/DependencyCheck#3821]
We have `dependencyCheck` configured in `allProjects` so that the format gets applied to all projects including the one created at the root level for `dependencyCheckAggregate` task. However, we have noticed that when `suppressionFile` is configured in the same place it does not apply the suppression to the sub projects or the aggregated result.

When the same value is set in `subprojects` block instead, the expected CVE's are removed. Is this a bug, by design, or some configuration error?

Our allProjects block is as follows:
```
allprojects {
  dependencyCheck {
    formats = ['CSV', 'HTML', 'JUNIT']
    suppressionFile = file("${rootDir}/config/dependency-check/suppressions.xml")
    analyzers {
      assemblyEnabled = false
    }
  }
}
```

We run ODP using `./gradlew clean dependencyCheckAggregate`

**Comment by SHAZAM-Analytics** [comment]
We are seeing the same thing with maven using the latest version with both aggregated and non aggregated projects.  Ironically there is only one service (one pom.xml) file.  The reports are correctly generated but the suppressions are ignored.

     <plugin>
        <groupId>org.owasp</groupId>
        <artifactId>dependency-check-maven</artifactId>
        <version>6.5.3</version>
        <inherited>false</inherited>
        <configuration>
          <skipProvidedScope>true</skipProvidedScope>
          <skipRuntimeScope>true</skipRuntimeScope>
          <dataDirectory>c:/[Redacted Path]/depcheckdata/</dataDirectory>
          <outputDirectory>c:/[Redacted Path]/tools/dependency/</outputDirectory>
          <suppressionFiles>
            <suppressionFile>c:\[Redacted Path]\project-suppressions.xml</suppressionFile>
          </suppressionFiles>
          <formats>
            <format>html</format>
            <format>json</format>
          </formats>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>check</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

The debug output from maven shows the file is read but ignored.

21:51:36.0569802 - [399] - ${suppressionFile}
21:51:36.0569802 - [400] - ${suppressionFilePassword}
21:51:36.0579814 - [401] - ${suppressionFileServerId}
21:51:36.0579814 - [402] - ${suppressionFileUser}
21:51:36.0579814 - [403] - 
21:51:36.0579814 - [404] - c:\[Redacted Path]\project-suppressions.xml${suppressionFiles}

Unable to solve. :(

**Comment by jeremylong** [comment]
i have been unable to reproduce this. if a sample project could be provided we might be able to provide more help.

**Comment by stefanrybacki** [comment]
same here
