### ISSUE TITLE
.NET AssemblyAnalyzer, is .NET 6 supported

### ISSUE THREAD

**Issue by AshleyEke** [dependency-check/DependencyCheck#3833]
Hello,

I am in the process of update from .NET Core 3.1 to .NET 6 and I am finding the following error in my previously working dependency check script:
```
[INFO] Finished File Name Analyzer (0 seconds)
[WARN] An error occurred with the .NET AssemblyAnalyzer, please see the log for more details.
[ERROR] Exception occurred initializing Assembly Analyzer.
[INFO] Finished Dependency Merging Analyzer (0 seconds)
[INFO] Finished Version Filter Analyzer (0 seconds)
[INFO] Finished Hint Analyzer (0 seconds)
[INFO] Created CPE Index (4 seconds)
[INFO] Finished CPE Analyzer (5 seconds)
[INFO] Finished False Positive Analyzer (0 seconds)
[INFO] Finished NVD CVE Analyzer (0 seconds)
[WARN] Unable to determine Package-URL identifiers for 38 dependencies
[INFO] Finished Sonatype OSS Index Analyzer (0 seconds)
[INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
[INFO] Finished Dependency Bundling Analyzer (0 seconds)
[INFO] Analysis Complete (6 seconds)
[ERROR] Could not execute .NET AssemblyAnalyzer
```

The dependency check version in use is 6.5.0 and the exact same script still works absolutely fine on this same dependency check version but with the .NET Core 3.1 SDK rather than .NET 6 SDK.

Therefore, my question is a simple one, is this because .NET 6 is not supported in dependency check yet? And if so, when can we expect it to be supported?

Many thanks.

**Comment by jeremylong** [comment]
Unfortunately - you need to have dotnet core 3.1 available to run the scan as grokassemly is still compiled using 3.1. It will still be able to scan assemblies using .NET 6
