### ISSUE TITLE
Unable to create aliases of H2 Functions when connecting with PostgreSQL database

### ISSUE THREAD

**Issue by drago2592** [dependency-check/DependencyCheck#3837]
Hi,

I am trying to connect dependency checker with PostgreSQL database. I have created the db and restored the schema.sql into it.
During that there are 2 aliases being created for the H2 Functions:
updateVulberability
insertSoftware

Due to that whenever I scan, it's throwing an issue  stating the alias is not found. 

I kindly request you to help me out on solving this issue.

**Comment by mprins** [comment]
there is no `schema.sql` in this repository so it is hard to help you with that.

there is a script to initialise a PG database here: https://github.com/jeremylong/DependencyCheck/blob/main/core/src/main/resources/data/initialize_postgres.sql and a property file: https://github.com/jeremylong/DependencyCheck/blob/main/core/src/main/resources/data/dbStatements_postgresql.properties

please foll;ow https://jeremylong.github.io/DependencyCheck/data/database.html

**Comment by drago2592** [comment]
Thanks for the reference shared. I am able to create the db now and point it to the scan..
