### ISSUE TITLE
Guidance for Scanning Javascript Project

### ISSUE THREAD

**Issue by pinkfloydx33** [dependency-check/DependencyCheck#3838]
We're getting started with using dependency-check and I'm looking for guidance regarding the arguments we *should* be passing. We've got a front-end JavaScript application. I've tried several combinations of Node Audit vs Package scanning as well as including/excluding the `node_modules` folder.  It seems like the guidance here is to disable the package scanner `--disableNodeJS` and only use the Audit scanner, but when I do that the reports only list out **my source files** and never any packages.

I've tried scanning *with* the `node_modules` folder included, but when I do that I end up with a report that's ~25mb and identifies all of the _individual files_ within those packages which doesn't seem right. I'm assuming I should be excluding this folder, but I haven't been able to find any official stance. Common sense is telling me to exclude it simply based on the size of the reports.

Here are some high-level descriptions of the results of several scans. Each scan was run with the Node Audit scanner enabled (I did not explicitly disable it), but with  `--nodeAuditSkipDevDependencies` as the scanner apparently can't handle aliases and will crash for this particular project. I am scanning the root of my repository (where my packages.json file is located). 

| # | node_modules | NodePackageScanner |  `--nodePackageSkipDevDependencies` |  Size  |  Description |
| - | ----------------- | ------------------- | ------------------------------------------- | -------| --------- |
| 1 | included           |  no                        | no    | 22mb |  Lists out every single files in all dependencies, but doesn't seem to list the dependency packages themselves, nor any CVEs |
| 2 | included           | yes                        | yes |  22mb |  Same as above, just with 15 more files |
| 3 | excluded          | no                         | no  |  125kb | List out MY individual source files only, but no deps/packages |
| 4 | excluded          | yes                        | no  |  5mb |  List out deps/dev-deps by package including CVE |
| 5 | excluded          | yes                        | yes |  200kb | List out deps by package including CVE |

It seems to me that the two "best" scans (# 4/5) were _without_ the `--disableNodeJS` flag, or rather _with_ the Node Package scanner enabled. That seems to go against the guidance I've seen in a few other issues, which is making me think that I'm just doing something wrong. Perhaps I'm just not expecting the right thing. If it matters this is a brand new project with only a handful of files (but lots of dependencies thanks to Vue and Vuetify)

Any guidance would be greatly appreciated.

**Comment by jeremylong** [comment]
Does `npm audit` work? In 99.9% of the cases the results of ODC and npm audit would be the same.

**Comment by pinkfloydx33** [comment]
Yes it does report a bunch of things. I purposely haven't updated yet to see if I can get the two things to match. I think most (or all) of the issues are Dev dependencies... I'm on my cell so couldn't say 100% but I am pretty sure the results were the same as No.4 in my list above. But that's *without* the disableNodeJs flag.

I'd expect No.3 to be the match for npm audit, but it's not. Perhaps that's because I have to pass nodeAuditSkipDevDependencies to the scanner due to the alias issue? I suppose that would make sense, but should the scanner be reporting the individual file names from my project (versus package names only)? That seems wrong to me, but again I'm not really sure what I should expect... Hence the question

**Comment by evyaroshevich** [comment]
I ran tests on my project and had reports larger than 50 MB. Basically, the entire size of the report was occupied by *js files.
First, I added **--exclude “\*\*/\*js"** to the options and the result made me happy. Then I added the **--disableRetireJS** option instead of the exception and the report was the same as before. P.S. I don't see the point in excluding the node_modules directories, because I want to find vulnerabilities in included libraries.
_dependency-check.sh -s $BUILD_DIR -f ALL --disableRetireJS [--nodeAuditSkipDevDependencies] [--nodePackageSkipDevDependencies]_
