### ISSUE TITLE
False positive with apache woden

### ISSUE THREAD

**Issue by victornoel** [dependency-check/DependencyCheck#384]
Hi,

It seems apache woden is mistaken for apache ssl, for the artefact org.apache.woden:woden-impl-dom:1.0M9 (http://search.maven.org/#search|ga|1|1%3A%22ac649d2a2c4fdd49149aefc27164e90f8312bde1%22) I get the following cpe resolved:
cpe:/a:apache-ssl:apache-ssl:1.0.m9

Thanks!

**Comment by jeremylong** [comment]
Thanks for reporting this!

A patch has been added to the snapshot build and will be included in the next release.

--Jeremy
