### ISSUE TITLE
How to run dependencycheck aggregate for gradle projects ?

### ISSUE THREAD

**Issue by sainadhakrishna** [dependency-check/DependencyCheck#3847]
Hi,

Please bear with me.
I am a complete beginner in using the dependencycheck.

I am planning to run the dependencycheck on my project and here we have a significant number of child gradle projects under one main project.

I am able to run the scan and it generates individual reports for each project.

Can some one point me as to how we can run the scan so that a single aggregate report will be generated for all set of projects ?

Thanks in advance

**Comment by jeremylong** [comment]
Use the `dependencyCheckAggregate` task: https://jeremylong.github.io/DependencyCheck/dependency-check-gradle/configuration-aggregate.html

**Comment by sainadhakrishna** [comment]
So, say if i have one base build.gradle file and multiple build.gradle files for individual sub projects

In base build.gradle file i will:
Add the dependency org.owasp:dependency-check-gradle:${project.version}
Add the line: check.dependsOn dependencyCheckAggregate
Define the dependencyCheck task. 

Is it right ?
Because i don' see anywhere in the page where we are defining the dependencyCheckAggregate task like we are doing for dependencyCheckAnalyze

and how do we invoke the scan in that case ?

**Comment by jeremylong** [comment]
```
./gradlew dependencyCheckAggregate
```

**Comment by sainadhakrishna** [comment]
Thank you @jeremylong .,! I will check on this.

I had another question.
Is it possible to run the dependency-check commandline tool on gradle projects ? Will it show all the vulnerabilities as it shows up when we run the gradle task of dependencycheck ?

**Comment by jeremylong** [comment]
No - the CLI cannot be used to run against a gradle project. Some do use the ODC CLI on the `./build` directory - but honestly the results are not as accurate; also depending on what the project is you may need to add a command to download the dependencies (similar to `mvn dependency:copy-dependencies`). Using the CLI on a gradle build (or maven build) without downloading the dependencies can cause you to miss transitive dependencies (again, this entirely depends on the build itself though).  

Times when you would not need to download the dependencies when using the CLI to scan a build directory would be if you are building an EAR, WAR, or a spring-boot JAR. In those cases all the transitive dependencies are bundled into the build artifact already. In almost every other case if using the CLI you need to download the transitive dependencies. For gradle, I believe this requires adding a task - so I would highly recommend just using the gradle plugin as the results will be more accurate.

**Comment by sainadhakrishna** [comment]
Thanks a lot @jeremylong

Wishing you a very Happy New year..!

**Comment by clivejefferies** [comment]
I have tried the aggregate command on an Android project with multiple modules, but all the individual reports are still generated.

**Comment by jeremylong** [comment]
Does the root report contain the aggregated results? did you use `<inherited>false</inherited>`?

**Comment by clivejefferies** [comment]
No, it's not there. I am using gradle, so not sure how I would use 'inherited'.

**Comment by jeremylong** [comment]
oh - inherited is for maven. For gradle - don't apply the plugin to the child modules.

**Comment by jeremylong** [comment]
you would have to share more about the configuration and execution for me to help more.

**Comment by clivejefferies** [comment]
I am a bit limited on what I can share, but here is an example of the module structure:
![Screenshot 2024-01-03 at 15 44 16](https://github.com/jeremylong/DependencyCheck/assets/973791/cae0c7a5-7c19-41fd-adfd-3132e58f0e44)

Each module has it's own Gradle file, and when running it creates a report for each module, but does not aggregate. Here is the documentation for modules in Android: https://developer.android.com/studio/projects

**Comment by jeremylong** [comment]
to do an aggregate you would need to have a build.gradle at the root that includes the dependency-check plugin and task configuration.
