### ISSUE TITLE
False Positive on org.eclipse.jetty.orbit:javax.mail.glassfish:1.4.1.v201005082020 and org.eclipse.jetty.orbit:javax.security.auth.message:1.0.0.v201108011116

### ISSUE THREAD

**Issue by Anshu2405** [dependency-check/DependencyCheck#3886]
False positive on library javax.mail.glassfish-1.4.1.v201005082020.jar  - reported as cpe:2.3:a:eclipse:jetty:1.4.1:201005082020:*:*:*:*:*:*
and cpe:2.3:a:jetty:jetty:1.4.1:201005082020:*:*:*:*:*:*
```xml
<dependency>
   <groupId>org.eclipse.jetty.orbit</groupId>
    <artifactId>javax.mail.glassfish</artifactId>
    <version>1.4.1.v201005082020</version>
</dependency>
```

**Comment by aikebah** [comment]
Will be fixed by 66a576a58c8242e27d9c314d8443a1480641c07b when 7.1.1 is released
