### ISSUE TITLE
Exclude files using direct engine invocation

### ISSUE THREAD

**Issue by henrychen0220** [dependency-check/DependencyCheck#3891]
Hi, I am currently using the [org.owasp:dependency-check-core:6.5.0](https://mvnrepository.com/artifact/org.owasp/dependency-check-core) release of OWASP dependency check. When running the scan through

```
engine.scan(directory)
```

I would like to exclude some of the paths inside the directory.

I see that the CLI version does have the `--exclude` option when runnning: https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html. 

However, I do not see any configuration that I can add in the Settings class when creating the OWASP engine. Is the `exclude` option currently supported in the java release?

**Comment by aikebah** [comment]
No, you need to filter out your excludes yourself. You could review the CLI code https://github.com/jeremylong/DependencyCheck/blob/main/cli/src/main/java/org/owasp/dependencycheck/App.java#L243
and https://github.com/jeremylong/DependencyCheck/blob/main/cli/src/main/java/org/owasp/dependencycheck/App.java#L321 for a sample on how it could be done.
