### ISSUE TITLE
java.lang.SecurityException: Invalid signature file digest for Manifest main attributes

### ISSUE THREAD

**Issue by backslash-f** [dependency-check/DependencyCheck#39]
Hello! Any idea on why I'm getting this issue?

Basically I cloned the repo and ran:

"C:\DependencyCheck\dependency-check-cli\target\release\bin\dependency-check.bat" -f ALL -a MY-PROJECT -s "C:\jenkins\workspace\MY-PROJECT" -o "C:\jenkins\workspace\MY-PROJECT"

The log:

Dez 16, 2013 11:27:56 AM org.owasp.dependencycheck.data.update.StandardUpdate up
date
INFO: NVD CVE requires several updates; this could take a couple of minutes.
Dez 16, 2013 11:27:56 AM org.owasp.dependencycheck.data.update.CallableDownloadT
ask call
INFO: Download Started for NVD CVE - 2002
Dez 16, 2013 11:27:56 AM org.owasp.dependencycheck.data.update.CallableDownloadT
ask call

[...]

(everything ok until here)

INFO: Processing Complete for NVD CVE - 2013

Exception in thread "main" java.lang.SecurityException: Invalid signature file d
igest for Manifest main attributes
        at sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVeri
fier.java:240)
        at sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier
.java:193)
        at java.util.jar.JarVerifier.processEntry(JarVerifier.java:305)
        at java.util.jar.JarVerifier.update(JarVerifier.java:216)
        at java.util.jar.JarFile.initializeVerifier(JarFile.java:345)
        at java.util.jar.JarFile.getInputStream(JarFile.java:412)
        at org.owasp.dependencycheck.analyzer.JarAnalyzer.retrievePom(JarAnalyze
r.java:365)
        at org.owasp.dependencycheck.analyzer.JarAnalyzer.analyzePOM(JarAnalyzer
.java:283)
        at org.owasp.dependencycheck.analyzer.JarAnalyzer.analyze(JarAnalyzer.ja
va:225)
        at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:336)

```
    at org.owasp.dependencycheck.App.runScan(App.java:126)
    at org.owasp.dependencycheck.App.run(App.java:103)
    at org.owasp.dependencycheck.App.main(App.java:71)
```

My java version:

C:\DependencyCheck> java -version
java version "1.7.0_45"
Java(TM) SE Runtime Environment (build 1.7.0_45-b18)
Java HotSpot(TM) Client VM (build 24.45-b08, mixed mode, sharing)

Let me know if you have something in mind...

Thank you in advance,
- Fernando

**Comment by backslash-f** [comment]
(Just to mention, I performed "mvn clean install" before that).

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Dependency-Check .................................. SUCCESS [0.789s]
[INFO] Dependency-Check Core ............................. SUCCESS [6:49.951s]
[INFO] Dependency-Check Command Line ..................... SUCCESS [6.372s]
[INFO] Dependency-Check Ant Task ......................... SUCCESS [40.644s]
[INFO] Dependency-Check Maven Plugin ..................... SUCCESS [12.486s]
[INFO] Dependency-Check Jenkins Plugin ................... SUCCESS [0.140s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7:50.747s
[INFO] Finished at: Mon Dec 16 11:15:36 BRST 2013
[INFO] Final Memory: 33M/87M
[INFO] ------------------------------------------------------------------------

**Comment by jeremylong** [comment]
Fernando,

Apparently I missed updating an error message (splitting the stack trace
out to verbose logging). The analysis should have continued beyond this
exception - please let me know if it did not. I will fix the error message
and I have an idea on how to get around this problem - but without access
to a JAR that causes the problem I can't be sure; but something appears to
be wrong with the signature of the JAR file.

I've corrected the error reporting in my local branch - but due to other
changes in flight it may take a few more days before it is pushed to github.

--Jeremy

**Comment by backslash-f** [comment]
Hey, Jeremy. Thanks for taking a look at this issue.

The analysis stops, unfortunately. On my first message I pasted the stack trace -- after that, the analysis stops.

Ok, I'll wait for your changes to be pushed. Take your time. ;-)

Thanks again,
- Fernando

**Comment by jeremylong** [comment]
The code to fix this issue has been pushed to the current snapshot. There are other changes in flight that will delay this being pushed to an official release for a week or two.

**Comment by backslash-f** [comment]
Jeremy, just pulled / ran an analysis and that did the trick. Fixed. Thanks a lot, you rock!
