### ISSUE TITLE
suppressionFile to suppress CVE doesn't fully work?

### ISSUE THREAD

**Issue by gregoryjobox** [dependency-check/DependencyCheck#3907]
Unsure if it is a bug, so will post a question.

suppressionFile to suppress CVE doesn't seem to fully work in dependency-check with Gradle.

Trying to suppress this:

`h2-1.4.200.jar	cpe:2.3:a:h2database:h2:1.4.200:*:*:*:*:*:*:*	pkg:maven/com.h2database/h2@1.4.200`

The suppress button gives the following XML:

```
<suppress>
   <notes><![CDATA[
   file name: h2-1.4.200.jar
   ]]></notes>
   <sha1>f7533fe7cb8e99c87a43d325a77b4b678ad9031a</sha1>
   <cpe>cpe:/a:h2database:h2</cpe>
</suppress>
```

which results in the report that still has the above JAR in the list, with same Severity, only with these columns blank: CPE and Confidence.

**Comment by jeremylong** [comment]
With that suppression rule - if you have the OSS Index Analyzer enabled may still flag the vulnerability. I might suggest just suppressing the CVE if you are not vulnerable.

**Comment by gregoryjobox** [comment]
Thank you, that worked.
