### ISSUE TITLE
How can I add or Upgrade the score of a CVE

### ISSUE THREAD

**Issue by Janpopan** [dependency-check/DependencyCheck#3908]
The NIST CVE scores are sometimes too late for 0 days.
Log4Shell Scores came 3-4 days to late.
So the DependencyChecker did not alert early.

What can I do in an enterprise setup without connection to ossindex to modify the score of an CVE or to add CVEs for internal legacy components?

**Comment by jeremylong** [comment]
One option would be to mirror the NVD data feeds. If a scenario like this arrises in the future - add the entry your mirror. Alternatively, a new data source could be created to add these 0 day CVEs - we accept PRs.

**Comment by jeremylong** [comment]
One other thing to note - if you enable the OSS Index Analyzer in many cases the vulnerability is added to their data set faster than the NVD (in addition they have vulnerabilities not found in the NVD).
