### ISSUE TITLE
multiple suppression files in Maven command line

### ISSUE THREAD

**Issue by itruk** [dependency-check/DependencyCheck#3914]
is there a way to use multiple suppression files with the Maven command line syntax?

e.g.
`mvn -DsuppressionFile=supFileGlobal.xml -DsuppressionFile=supFileProject.xml org.owasp:dependency-check-maven:6.5.0:check`

I know how to do it in pom.xml, but not in the command line.

**Comment by aikebah** [comment]
Based on the code and some google results I expect 

`mvn -DsuppressionFiles="supFileGlobal.xml supFileProject.xml" org.owasp:dependency-check-maven:6.5.0:check`

to work. Think it's faster for you to validate than for me to create a doghouse sample to validate my assumption. The main part would be in finding out the correct syntax to make maven properly feed the String\[\] typed suppressionFiles configuration parameter from its assigned property (note the plural form). According to the first search results it would need to be a space-separated list of strings.

**Comment by aikebah** [comment]
Turns out that sometimes you shouldn't trust the first Google hit, but the following should work (whether the quotes are required depends on your actual filepaths versus your shell, but better safe than sorry

`mvn -DsuppressionFiles="supFileGlobal.xml,supFileProject.xml" org.owasp:dependency-check-maven:6.5.0:check`

for me it properly yields

```
[ERROR] Failed to execute goal org.owasp:dependency-check-maven:6.5.0:check (default-cli) on project DependencyCheckValidation: One or more exceptions occurred during dependency-check analysis: One or more exceptions occurred during analysis:
[ERROR] 	InitializationException: Warn initializing the suppression analyzer: Failed to load supFileGlobal.xml, caused by Unable to create temp file for suppression file. Failed to load supFileProject.xml, caused by Unable to create temp file for suppression file. 
[ERROR] 		caused by SuppressionParseException: Failed to load supFileGlobal.xml, caused by Unable to create temp file for suppression file. Failed to load supFileProject.xml, caused by Unable to create temp file for suppression file. 
[ERROR] 	InitializationException: Warn initializing the suppression analyzer: Failed to load supFileGlobal.xml, caused by Unable to create temp file for suppression file. Failed to load supFileProject.xml, caused by Unable to create temp file for suppression file. 
[ERROR] 		caused by SuppressionParseException: Failed to load supFileGlobal.xml, caused by Unable to create temp file for suppression file. Failed to load supFileProject.xml, caused by Unable to create temp file for suppression file.
```

Which shows that DependencyCheck did consider both suppressionfiles as a result of the command.

**Comment by aikebah** [comment]
Oh... and just to state the obvious: of course you should be using 
`mvn -DsuppressionFiles="supFileGlobal.xml,supFileProject.xml" org.owasp:dependency-check-maven:6.5.1:check` 
in order to also benefit from the latest fixes, improvements and FP suppressions.

**Comment by itruk** [comment]
Thanks Hans! `-DsuppressionFileS` plus the quotes did the trick. closing.
