### ISSUE TITLE
Could not connect to Central search issue

### ISSUE THREAD

**Issue by umeshPathak** [dependency-check/DependencyCheck#3915]
Hi,
I have added the cert of  https://search.maven.org in my JDK-11 cacerts file. But still, am getting below error 
```
DEBUG - Searching Central url https://search.maven.org/solrsearch/select?q=1:0235ba8b489512805ac13a8f9ea77a1ca5ebe3e8&wt=xml
2021-12-23 14:06:50,958 org.owasp.dependencycheck.analyzer.CentralAnalyzer:346

```
Error in the console -

> [WARN] An error occurred while analyzing 'c:\mypro\WEB-INF\lib\asm-analysis-7.1.jar' (Central Analyzer).
> [ERROR] Could not connect to Central search. Analysis failed.
> java.io.IOException: Finally failed connecting to Central search. Giving up after 7 tries.
>         at org.owasp.dependencycheck.analyzer.CentralAnalyzer.fetchMavenArtifacts(CentralAnalyzer.java:364)
>         at org.owasp.dependencycheck.analyzer.CentralAnalyzer.analyzeDependency(CentralAnalyzer.java:229)
>         at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
>         at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
>         at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
>         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
>         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>         at java.base/java.lang.Thread.run(Thread.java:834)
> Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
>         at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:128)
>         at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
>         at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
>         at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:259)
>         at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1329)
>         at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1204)
>         at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1151)
>         at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
>         at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
>         at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
>         at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:178)
>         at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
>         at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
>         at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
>         at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
>         at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
>         at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
>         at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:163)
>         at org.owasp.dependencycheck.data.central.CentralSearch.searchSha1(CentralSearch.java:169)
>         at org.owasp.dependencycheck.analyzer.CentralAnalyzer.fetchMavenArtifacts(CentralAnalyzer.java:341)
>         ... 8 common frames omitted
> Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
>         at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:385)
>         at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:290)
>         at java.base/sun.security.validator.Validator.validate(Validator.java:264)
>         at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:321)
>         at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:221)
>         at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
>         at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1313)
>         ... 23 common frames omitted
> Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
>         at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
>         at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
>         at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
>         at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:380)
>         ... 29 common frames omitted

**Comment by jeremylong** [comment]
is there a proxy in between you and Central?

**Comment by umeshPathak** [comment]
YEs, I have mentioned the proxy details using the command line switches. I am not getting the unknownhost exception. I am getting the certificate issue. How can we we bypass the certificate issues ? 
Can you provide the switch like --ignoreSSL=true ?    :) 

Can we use OkHttpClient for the same ?

I am using dependency-check-cli-6.5.0.jar. OS is Windows 10.

**Comment by aikebah** [comment]
Your proxy is likely re-encrypting traffic and using temporary on-demand generated certificates signed by an internal selfsigned root-CA certificate. That root-CA certificate is the certificate you need to put into the truststore (telling Java to trust 'any certificate issued by my proxy')
