### ISSUE TITLE
Linux Offline Use

### ISSUE THREAD

**Issue by calebwhitt** [dependency-check/DependencyCheck#3926]
I'm trying to follow the steps [here](https://jeremylong.github.io/DependencyCheck/data/cachenvd.html) to set up a nist-data-mirror for use with the dependency check. I've cloned [nist-data-mirror](https://github.com/stevespringett/nist-data-mirror) and have downloaded the `.json.gz` files. However when passing these options:

`./bin/dependency-check.sh \
--cveUrl20Base nist-data-mirror/nvdcve-1.1-%d.json.gz \
--cveUrl12Base nist-data-mirror/nvdcve-%d.json.gz \
--cveUrl20Modified nist-data-mirror/nvdcve-1.1-modified.json.gz \
--cveUrl12Modified nist-data-mirror/nvdcve-1.1-modified.json.gz \
--data nist-data-mirror \
--scan /home/caleb.whittington/test-scan/ \
--report JSON`

I see this error:
`Unrecognized option: --cveUrl20Base`

I'm not sure if I'm misunderstanding how the dependencycheck works, or how the nist-data-mirror works. I'm using the dependencycheck CLI version 6.5.1

Any help would be greatly appreciated.

**Comment by aikebah** [comment]
That documented script is for an outdated version (note the `dependency-check-1.2.11` in the path in the script). See [CLI configuration doc](https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html) for the valid parameters.

For using your nist-data-mirror downloaded files you should use `--cveUrlModified` and `--cveUrlBase` arguments (and leave out the cveUrl20* and cveUrl12* variants.

To keep things tidy you might want to remove `--data` from your call. `--data` defines where DependencyCheck will create its caches and database.
Note that the shell-script on the 'Snapshotting the NVD' page is intended for using parallel date-stamped instances of the CVE database, which is why the data is forced to be side-by-side with the mirror. 

As indicated in the CLI-documentation in the typical case you would omit the --data).

For the typical offline usage I would expect you'd periodically re-synchronise (update/overwrite) the NIST NVD mirror files, in which case it would be more appropriate to store the data outside of the NIST NVD mirror folder (let DependencyCheck use its default location).

**Comment by calebwhitt** [comment]
Hi @aikebah 👋🏻

Firstly, thank you so much for your response. I'll look into that further. What did you mean by this?  

> For the typical offline usage I would expect you'd periodically re-synchronise (update/overwrite) the NIST NVD mirror files, in which case it would be more appropriate to store the data outside of the NIST NVD mirror folder (let DependencyCheck use its default location)

**Comment by aikebah** [comment]
What I would expect for offline use of the tool is that, while offline, you'd still want to be 'up to date with current state of affairs', so you would typically create a new mirror of the NIST NVD datastreams from time to time on a connected system and overwrite the current offline mirror with it.

When you keep Dependency Check's internal datastorage separate from your mirror you can just delete/replace the entire mirror data folder and still benefit from cached data for NVD streams that have not modified since last import.

While that would still be possible if you place DependencyCheck's internal data caches in the same spot you would in that case have to be careful to just copy over the new mirrored files (and not delete anything from the folder (leaving all other files, which dependencycheck creates, in place). If you remove all data from the folder before copying the new mirrored data DependencyCheck will on the next run have to re-create it's full internal database based on the NVD datastreams.

**Comment by calebwhitt** [comment]
@aikebah Thank you for your explanation. I have moved the mirrored files to a new directory, `tmp-data-mirror`. However, I think I am still misunderstanding something, because when I try the following command:

`./bin/dependency-check.sh --cveUrlModified tmp-data-mirror/nvdcve-1.1-modified.json.gz --cveUrlBase tmp-data-mirror --scan /home/caleb.whittington/test-scan --format JSON`

I'm seeing the following output:

`[INFO] Checking for updates
[ERROR] Meta file url is invalid: tmp-data-mirror/nvdcve-1.1-modified.meta
org.owasp.dependencycheck.data.update.exception.UpdateException: Meta file url is invalid: tmp-data-mirror/nvdcve-1.1-modified.meta
	at org.owasp.dependencycheck.data.update.NvdCveUpdater.doMetaDownload(NvdCveUpdater.java:402)
	at org.owasp.dependencycheck.data.update.NvdCveUpdater.getMetaFile(NvdCveUpdater.java:355)
	at org.owasp.dependencycheck.data.update.NvdCveUpdater.getUpdatesNeeded(NvdCveUpdater.java:458)
	at org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:132)
	at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:875)
	at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:680)
	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:606)
	at org.owasp.dependencycheck.App.runScan(App.java:256)
	at org.owasp.dependencycheck.App.run(App.java:188)
	at org.owasp.dependencycheck.App.main(App.java:83)
Caused by: java.net.MalformedURLException: no protocol: tmp-data-mirror/nvdcve-1.1-modified.meta
	at java.net.URL.<init>(URL.java:610)
	at java.net.URL.<init>(URL.java:507)
	at java.net.URL.<init>(URL.java:456)
	at org.owasp.dependencycheck.data.update.NvdCveUpdater.doMetaDownload(NvdCveUpdater.java:377)
	... 9 common frames omitted
[INFO] Skipping RetireJS update since last update was within 24 hours.
[WARN] Unable to update 1 or more Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.
[ERROR] Unable to continue dependency-check analysis.
[ERROR] One or more fatal errors occurred
[ERROR] Meta file url is invalid: tmp-data-mirror/nvdcve-1.1-modified.meta
[ERROR] No documents exist`

Could this be an issue with the mirrored files? 
<img width="1425" alt="Screenshot 2021-12-30 at 11 58 34" src="https://user-images.githubusercontent.com/42133752/147750019-9c1c57c6-aea6-4236-b4df-8d2e908ea6b3.png">

Thank you for your help with this

**Comment by jeremylong** [comment]
try:

```bash
./bin/dependency-check.sh --cveUrlModified file:///./tmp-data-mirror/nvdcve-1.1-modified.json.gz --cveUrlBase file:///./tmp-data-mirror --scan /home/caleb.whittington/test-scan --format JSON
```

The argument is expecting a URL - you can use the file protocol to reference a file on disk.

**Comment by calebwhitt** [comment]
@jeremylong seeing this output now:
`[INFO] Checking for updates
[ERROR] Unable to download meta file: file:///./tmp-data-mirror/nvdcve-1.1-modified.meta
org.owasp.dependencycheck.data.update.exception.UpdateException: Unable to download meta file: file:///./tmp-data-mirror/nvdcve-1.1-modified.meta
	at org.owasp.dependencycheck.data.update.NvdCveUpdater.doMetaDownload(NvdCveUpdater.java:410)
	at org.owasp.dependencycheck.data.update.NvdCveUpdater.getMetaFile(NvdCveUpdater.java:355)
	at org.owasp.dependencycheck.data.update.NvdCveUpdater.getUpdatesNeeded(NvdCveUpdater.java:458)
	at org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:132)
	at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:875)
	at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:680)
	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:606)
	at org.owasp.dependencycheck.App.runScan(App.java:256)
	at org.owasp.dependencycheck.App.run(App.java:188)
	at org.owasp.dependencycheck.App.main(App.java:83)
Caused by: org.owasp.dependencycheck.utils.DownloadFailedException: Download failed, unable to retrieve 'file:/./tmp-data-mirror/nvdcve-1.1-modified.meta'; Download failed, file ('file:/./tmp-data-mirror/nvdcve-1.1-modified.meta') does not exist
	at org.owasp.dependencycheck.utils.Downloader.fetchContent(Downloader.java:187)
	at org.owasp.dependencycheck.data.update.NvdCveUpdater.doMetaDownload(NvdCveUpdater.java:381)
	... 9 common frames omitted
Caused by: org.owasp.dependencycheck.utils.DownloadFailedException: Download failed, file ('file:/./tmp-data-mirror/nvdcve-1.1-modified.meta') does not exist
	at org.owasp.dependencycheck.utils.HttpResourceConnection.fetch(HttpResourceConnection.java:155)
	at org.owasp.dependencycheck.utils.Downloader.fetchContent(Downloader.java:182)
	... 10 common frames omitted
[INFO] Skipping RetireJS update since last update was within 24 hours.
[WARN] Unable to update 1 or more Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.
[ERROR] Unable to continue dependency-check analysis.
[ERROR] One or more fatal errors occurred
[ERROR] Unable to download meta file: file:///./tmp-data-mirror/nvdcve-1.1-modified.meta
[ERROR] No documents exist`

**Comment by jeremylong** [comment]
I rarely use the file protocol - obviously something is wrong with what I suggested.  Looking at SO - maybe don't put the slashes?   `file:tmp-data-mirror/nvdcve-1.1-modified.json.gz` Or just put in the fully qualified path...

**Comment by calebwhitt** [comment]
@jeremylong Interesting, I'll check that out soon. 

How would you normally use the data mirror? Would you host it somewhere?

**Comment by jeremylong** [comment]
In many cases people do host the NVD - such as the docker container: https://github.com/stevespringett/nist-data-mirror#docker

**Comment by calebwhitt** [comment]
I'm a complete noob here 🙈 How would you reference that docker container when using the dependencycheck CLI?

**Comment by aikebah** [comment]
If you start it according to the documentation you will be able to reach the mirror at http://localhost/

So you would configure the CLI to use
http://localhost/nvdcve-1.1-modified.json.gz
and
http://localhost/nvdcve-1.1-%d.json.gz

**Comment by calebwhitt** [comment]
Thanks both. I've now got it working 🎉 I'm hosting the NVD using the Docker container, as suggested by Jeremy above.

For reference, this was the final command that worked: 
`./bin/dependency-check.sh --cveUrlModified http://localhost/nvdcve-1.1-modified.json.gz --cveUrlBase http://localhost --scan /home/caleb.whittington/test-scan --format JSON`

**Comment by aikebah** [comment]
@calebwhitt Should not work if no previous database is available or the database is too old to just process the Modified stream from NVD: your cveUrlBase is wrong, it needs the full patterned filename format for the year-by-year full-year datastreams as indicated in my response.

try 
`./bin/dependency-check.sh --purge`
to remove your current database and then try again you'll see it fail to download the 2002 through 2022 datastreams as it will try to download each of those directly from `http://localhost` instead of from locations like `http://localhost/nvdcve-1.1-2002.json.gz`

**Comment by calebwhitt** [comment]
@aikebah I purged the database and tried the following command:
`./bin/dependency-check.sh --cveUrlModified http://localhost/nvdcve-1.1-modified.json.gz --cveUrlBase http://localhost/nvdcve-1.1-%d.json --scan /home/caleb.whittington/test-scan --format JSON`

I got the following output:
`[INFO] Checking for updates
[INFO] NVD CVE requires several updates; this could take a couple of minutes.
[INFO] Download Started for NVD CVE - 2002
[ERROR] An exception occurred downloading NVD CVE - 2002
Some CVEs may not be reported. Reason: Requested resource does not exists - received a 404
[INFO] Download Started for NVD CVE - 2003
[ERROR] An exception occurred downloading NVD CVE - 2003
Some CVEs may not be reported. Reason: Requested resource does not exists - received a 404
[INFO] Download Started for NVD CVE - 2004
[ERROR] An exception occurred downloading NVD CVE - 2004
Some CVEs may not be reported. Reason: Requested resource does not exists - received a 404
[INFO] Download Started for NVD CVE - 2005
[ERROR] An exception occurred downloading NVD CVE - 2005
Some CVEs may not be reported. Reason: Requested resource does not exists - received a 404
[INFO] Download Started for NVD CVE - 2006
[ERROR] An exception occurred downloading NVD CVE - 2006
Some CVEs may not be reported. Reason: Requested resource does not exists - received a 404
^C[INFO] Download Started for NVD CVE - 2007
[ERROR] An exception occurred downloading NVD CVE - 2007
Some CVEs may not be reported. Reason: Requested resource does not exists - received a 404
[INFO] Download Started for NVD CVE - 2008
[ERROR] An exception occurred downloading NVD CVE - 2008
Some CVEs may not be reported. Reason: Requested resource does not exists - received a 404`

**Comment by aikebah** [comment]
Which would indicate that your NIST NVD mirror is incomplete (or something else is running on localhost at port 80 blocking your docker container from binding to it)

**Comment by aikebah** [comment]
I just validated the instructions on the nist-data-mirror site and can confirm that when you follow the recipe there you should be able to run a successful initialisation of the database using

`./bin/dependency-check.sh --cveUrlModified http://localhost/nvdcve-1.1-modified.json.gz --cveUrlBase http://localhost/nvdcve-1.1-%d.json.gz --updateonly`

To verify that your docker container runs properly on your machine you can point your browser to http://localhost which should yield a directory-listing of all the downloaded NVD feed files.

**Comment by aikebah** [comment]
And I just noted that your command still had an improper URL: you should use the .json.gz versions of the stream, not the .json version.

**Comment by calebwhitt** [comment]
Great spot. I was missing `.gz`, but even with that added, I still get the same output `Requested resource does not exist`.

Running `curl http://localhost` I see:
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<html>
 <head>
  <title>Index of /</title>
 </head>
 <body>
<h1>Index of /</h1>
<ul><li><a href="nvdcve-1.1-2002.meta"> nvdcve-1.1-2002.meta</a></li>
<li><a href="nvdcve-1.1-2003.meta"> nvdcve-1.1-2003.meta</a></li>
<li><a href="nvdcve-1.1-2004.meta"> nvdcve-1.1-2004.meta</a></li>
<li><a href="nvdcve-1.1-2005.meta"> nvdcve-1.1-2005.meta</a></li>
<li><a href="nvdcve-1.1-2006.meta"> nvdcve-1.1-2006.meta</a></li>
<li><a href="nvdcve-1.1-2007.meta"> nvdcve-1.1-2007.meta</a></li>
<li><a href="nvdcve-1.1-2008.meta"> nvdcve-1.1-2008.meta</a></li>
<li><a href="nvdcve-1.1-2009.meta"> nvdcve-1.1-2009.meta</a></li>
<li><a href="nvdcve-1.1-2010.meta"> nvdcve-1.1-2010.meta</a></li>
<li><a href="nvdcve-1.1-2011.meta"> nvdcve-1.1-2011.meta</a></li>
<li><a href="nvdcve-1.1-2012.meta"> nvdcve-1.1-2012.meta</a></li>
<li><a href="nvdcve-1.1-2013.json"> nvdcve-1.1-2013.json</a></li>
<li><a href="nvdcve-1.1-2013.json.gz"> nvdcve-1.1-2013.json.gz</a></li>
<li><a href="nvdcve-1.1-2013.meta"> nvdcve-1.1-2013.meta</a></li>
<li><a href="nvdcve-1.1-2014.meta"> nvdcve-1.1-2014.meta</a></li>
<li><a href="nvdcve-1.1-2015.json"> nvdcve-1.1-2015.json</a></li>
<li><a href="nvdcve-1.1-2015.json.gz"> nvdcve-1.1-2015.json.gz</a></li>
<li><a href="nvdcve-1.1-2015.meta"> nvdcve-1.1-2015.meta</a></li>
<li><a href="nvdcve-1.1-2016.meta"> nvdcve-1.1-2016.meta</a></li>
<li><a href="nvdcve-1.1-2017.meta"> nvdcve-1.1-2017.meta</a></li>
<li><a href="nvdcve-1.1-2018.json"> nvdcve-1.1-2018.json</a></li>
<li><a href="nvdcve-1.1-2018.json.gz"> nvdcve-1.1-2018.json.gz</a></li>
<li><a href="nvdcve-1.1-2018.meta"> nvdcve-1.1-2018.meta</a></li>
<li><a href="nvdcve-1.1-2019.meta"> nvdcve-1.1-2019.meta</a></li>
<li><a href="nvdcve-1.1-2020.json"> nvdcve-1.1-2020.json</a></li>
<li><a href="nvdcve-1.1-2020.json.gz"> nvdcve-1.1-2020.json.gz</a></li>
<li><a href="nvdcve-1.1-2020.meta"> nvdcve-1.1-2020.meta</a></li>
<li><a href="nvdcve-1.1-2021.json"> nvdcve-1.1-2021.json</a></li>
<li><a href="nvdcve-1.1-2021.json.gz"> nvdcve-1.1-2021.json.gz</a></li>
<li><a href="nvdcve-1.1-2021.meta"> nvdcve-1.1-2021.meta</a></li>
<li><a href="nvdcve-1.1-2022.json"> nvdcve-1.1-2022.json</a></li>
<li><a href="nvdcve-1.1-2022.json.gz"> nvdcve-1.1-2022.json.gz</a></li>
<li><a href="nvdcve-1.1-2022.meta"> nvdcve-1.1-2022.meta</a></li>
<li><a href="nvdcve-1.1-modified.json"> nvdcve-1.1-modified.json</a></li>
<li><a href="nvdcve-1.1-modified.json.gz"> nvdcve-1.1-modified.json.gz</a></li>
<li><a href="nvdcve-1.1-modified.meta"> nvdcve-1.1-modified.meta</a></li>
</ul>
</body></html>
```

which suggested that the mirror is running correctly 🤔

**Comment by aikebah** [comment]
it suggests the mirror is still busy downloading the data     
    nvdcve-1.1-2002.json
    nvdcve-1.1-2002.json.gz
    nvdcve-1.1-2002.meta
    nvdcve-1.1-2003.json
    nvdcve-1.1-2003.json.gz
    nvdcve-1.1-2003.meta
    nvdcve-1.1-2004.json
    nvdcve-1.1-2004.json.gz
    nvdcve-1.1-2004.meta
    nvdcve-1.1-2005.json
    nvdcve-1.1-2005.json.gz
    nvdcve-1.1-2005.meta
    nvdcve-1.1-2006.json
    nvdcve-1.1-2006.json.gz
    nvdcve-1.1-2006.meta
    nvdcve-1.1-2007.json
    nvdcve-1.1-2007.json.gz
    nvdcve-1.1-2007.meta
    nvdcve-1.1-2008.json
    nvdcve-1.1-2008.json.gz
    nvdcve-1.1-2008.meta
    nvdcve-1.1-2009.json
    nvdcve-1.1-2009.json.gz
    nvdcve-1.1-2009.meta
    nvdcve-1.1-2010.json
    nvdcve-1.1-2010.json.gz
    nvdcve-1.1-2010.meta
    nvdcve-1.1-2011.json
    nvdcve-1.1-2011.json.gz
    nvdcve-1.1-2011.meta
    nvdcve-1.1-2012.json
    nvdcve-1.1-2012.json.gz
    nvdcve-1.1-2012.meta
    nvdcve-1.1-2013.json
    nvdcve-1.1-2013.json.gz
    nvdcve-1.1-2013.meta
    nvdcve-1.1-2014.json
    nvdcve-1.1-2014.json.gz
    nvdcve-1.1-2014.meta
    nvdcve-1.1-2015.json
    nvdcve-1.1-2015.json.gz
    nvdcve-1.1-2015.meta
    nvdcve-1.1-2016.json
    nvdcve-1.1-2016.json.gz
    nvdcve-1.1-2016.meta
    nvdcve-1.1-2017.json
    nvdcve-1.1-2017.json.gz
    nvdcve-1.1-2017.meta
    nvdcve-1.1-2018.json
    nvdcve-1.1-2018.json.gz
    nvdcve-1.1-2018.meta
    nvdcve-1.1-2019.json
    nvdcve-1.1-2019.json.gz
    nvdcve-1.1-2019.meta
    nvdcve-1.1-2020.json
    nvdcve-1.1-2020.json.gz
    nvdcve-1.1-2020.meta
    nvdcve-1.1-2021.json
    nvdcve-1.1-2021.json.gz
    nvdcve-1.1-2021.meta
    nvdcve-1.1-2022.json
    nvdcve-1.1-2022.json.gz
    nvdcve-1.1-2022.meta
    nvdcve-1.1-modified.json
    nvdcve-1.1-modified.json.gz
    nvdcve-1.1-modified.meta

is the complete list you should have

**Comment by calebwhitt** [comment]
That's weird. The mirror has been running for the last five days at least. Is there any reason why it wouldn't download all the files?

**Comment by aikebah** [comment]
some kind of error in the image or during download... you could try logging in to the container `docker exec -it mirror /bin/sh` and check the contents of /tmp/nvd as a first step

if that one appears complete you could try to manually kick-off the re-synchronisation with
`/mirror.sh` in that same container shell

**Comment by aikebah** [comment]
And check `/var/log/supervisord.log` for any strange errors. A successfull startup would yield something like

```
2022-01-04 17:43:38,278 INFO Set uid to user 0 succeeded
2022-01-04 17:43:38,281 INFO supervisord started with pid 1
2022-01-04 17:43:39,263 INFO spawned: 'crond' with pid 8
2022-01-04 17:43:39,265 INFO spawned: 'httpd' with pid 9
2022-01-04 17:43:39,266 INFO spawned: 'initialize_htdocs' with pid 10
2022-01-04 17:43:40,303 INFO success: crond entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-01-04 17:43:40,303 INFO success: httpd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-01-04 17:43:40,303 INFO success: initialize_htdocs entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-01-04 17:44:52,603 INFO exited: initialize_htdocs (exit status 0; expected)
```

The initialize_htdocs takes care of the initial run of the nist-data-mirror, follow-up runs are scheduled as a cron-task under user mirror every 4 hours at the hour

**Comment by calebwhitt** [comment]
@aikebah again, thanks for your help with this.

I removed and rebuilt the Docker container. I'm now seeing this when I run `curl http://localhost`:
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<html>
 <head>
  <title>Index of /</title>
 </head>
 <body>
<h1>Index of /</h1>
<ul></ul>
</body></html>
```

I see all the files in `/tmp/nvd` on the container:
```
/tmp/nvd # ls
nvdcve-1.1-2002.json         nvdcve-1.1-2009.json.gz      nvdcve-1.1-2016.meta
nvdcve-1.1-2002.json.gz      nvdcve-1.1-2009.meta         nvdcve-1.1-2017.json
nvdcve-1.1-2002.meta         nvdcve-1.1-2010.json         nvdcve-1.1-2017.json.gz
nvdcve-1.1-2003.json         nvdcve-1.1-2010.json.gz      nvdcve-1.1-2017.meta
nvdcve-1.1-2003.json.gz      nvdcve-1.1-2010.meta         nvdcve-1.1-2018.json
nvdcve-1.1-2003.meta         nvdcve-1.1-2011.json         nvdcve-1.1-2018.json.gz
nvdcve-1.1-2004.json         nvdcve-1.1-2011.json.gz      nvdcve-1.1-2018.meta
nvdcve-1.1-2004.json.gz      nvdcve-1.1-2011.meta         nvdcve-1.1-2019.json
nvdcve-1.1-2004.meta         nvdcve-1.1-2012.json         nvdcve-1.1-2019.json.gz
nvdcve-1.1-2005.json         nvdcve-1.1-2012.json.gz      nvdcve-1.1-2019.meta
nvdcve-1.1-2005.json.gz      nvdcve-1.1-2012.meta         nvdcve-1.1-2020.json
nvdcve-1.1-2005.meta         nvdcve-1.1-2013.json         nvdcve-1.1-2020.json.gz
nvdcve-1.1-2006.json         nvdcve-1.1-2013.json.gz      nvdcve-1.1-2020.meta
nvdcve-1.1-2006.json.gz      nvdcve-1.1-2013.meta         nvdcve-1.1-2021.json
nvdcve-1.1-2006.meta         nvdcve-1.1-2014.json         nvdcve-1.1-2021.json.gz
nvdcve-1.1-2007.json         nvdcve-1.1-2014.json.gz      nvdcve-1.1-2021.meta
nvdcve-1.1-2007.json.gz      nvdcve-1.1-2014.meta         nvdcve-1.1-2022.json
nvdcve-1.1-2007.meta         nvdcve-1.1-2015.json         nvdcve-1.1-2022.json.gz
nvdcve-1.1-2008.json         nvdcve-1.1-2015.json.gz      nvdcve-1.1-2022.meta
nvdcve-1.1-2008.json.gz      nvdcve-1.1-2015.meta         nvdcve-1.1-modified.json
nvdcve-1.1-2008.meta         nvdcve-1.1-2016.json         nvdcve-1.1-modified.json.gz
nvdcve-1.1-2009.json         nvdcve-1.1-2016.json.gz      nvdcve-1.1-modified.meta
```

Running `mirror.sh` doesn't do anything.

I'm seeing an exit 1 in `/var/log/supervisord.log`:
```
/tmp/nvd # cat /var/log/supervisord.log
2022-01-04 18:20:52,685 INFO Set uid to user 0 succeeded
2022-01-04 18:20:52,688 INFO supervisord started with pid 1
2022-01-04 18:20:53,692 INFO spawned: 'crond' with pid 7
2022-01-04 18:20:53,694 INFO spawned: 'httpd' with pid 8
2022-01-04 18:20:53,697 INFO spawned: 'initialize_htdocs' with pid 9
2022-01-04 18:20:54,780 INFO success: crond entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-01-04 18:20:54,780 INFO success: httpd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-01-04 18:20:54,781 INFO success: initialize_htdocs entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-01-04 18:21:07,988 INFO exited: initialize_htdocs (exit status 1; not expected)
```

**Comment by calebwhitt** [comment]
I realised this thread is now more related to the nist-data-mirror, rather than the dependency check. Please see this new issue here: https://github.com/stevespringett/nist-data-mirror/issues/103.

Thank you both for your help!

**Comment by calebwhitt** [comment]
Just wanted to add finally that this command does work successfully when all .json.gz files are hosted correctly on localhost. Thank you @aikebah @jeremylong for your support, much appreciated.

```
./bin/dependency-check.sh --cveUrlModified http://localhost/nvdcve-1.1-modified.json.gz --cveUrlBase http://localhost/nvdcve-1.1-%d.json.gz
```

**Comment by itsecforu** [comment]
> @aikebah again, thanks for your help with this.
> 
> I removed and rebuilt the Docker container. I'm now seeing this when I run `curl http://localhost`:
> 
> ```
> <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
> <html>
>  <head>
>   <title>Index of /</title>
>  </head>
>  <body>
> <h1>Index of /</h1>
> <ul></ul>
> </body></html>
> ```
> 
> I see all the files in `/tmp/nvd` on the container:
> 
> ```
> /tmp/nvd # ls
> nvdcve-1.1-2002.json         nvdcve-1.1-2009.json.gz      nvdcve-1.1-2016.meta
> nvdcve-1.1-2002.json.gz      nvdcve-1.1-2009.meta         nvdcve-1.1-2017.json
> nvdcve-1.1-2002.meta         nvdcve-1.1-2010.json         nvdcve-1.1-2017.json.gz
> nvdcve-1.1-2003.json         nvdcve-1.1-2010.json.gz      nvdcve-1.1-2017.meta
> nvdcve-1.1-2003.json.gz      nvdcve-1.1-2010.meta         nvdcve-1.1-2018.json
> nvdcve-1.1-2003.meta         nvdcve-1.1-2011.json         nvdcve-1.1-2018.json.gz
> nvdcve-1.1-2004.json         nvdcve-1.1-2011.json.gz      nvdcve-1.1-2018.meta
> nvdcve-1.1-2004.json.gz      nvdcve-1.1-2011.meta         nvdcve-1.1-2019.json
> nvdcve-1.1-2004.meta         nvdcve-1.1-2012.json         nvdcve-1.1-2019.json.gz
> nvdcve-1.1-2005.json         nvdcve-1.1-2012.json.gz      nvdcve-1.1-2019.meta
> nvdcve-1.1-2005.json.gz      nvdcve-1.1-2012.meta         nvdcve-1.1-2020.json
> nvdcve-1.1-2005.meta         nvdcve-1.1-2013.json         nvdcve-1.1-2020.json.gz
> nvdcve-1.1-2006.json         nvdcve-1.1-2013.json.gz      nvdcve-1.1-2020.meta
> nvdcve-1.1-2006.json.gz      nvdcve-1.1-2013.meta         nvdcve-1.1-2021.json
> nvdcve-1.1-2006.meta         nvdcve-1.1-2014.json         nvdcve-1.1-2021.json.gz
> nvdcve-1.1-2007.json         nvdcve-1.1-2014.json.gz      nvdcve-1.1-2021.meta
> nvdcve-1.1-2007.json.gz      nvdcve-1.1-2014.meta         nvdcve-1.1-2022.json
> nvdcve-1.1-2007.meta         nvdcve-1.1-2015.json         nvdcve-1.1-2022.json.gz
> nvdcve-1.1-2008.json         nvdcve-1.1-2015.json.gz      nvdcve-1.1-2022.meta
> nvdcve-1.1-2008.json.gz      nvdcve-1.1-2015.meta         nvdcve-1.1-modified.json
> nvdcve-1.1-2008.meta         nvdcve-1.1-2016.json         nvdcve-1.1-modified.json.gz
> nvdcve-1.1-2009.json         nvdcve-1.1-2016.json.gz      nvdcve-1.1-modified.meta
> ```
> 
> Running `mirror.sh` doesn't do anything.
> 
> I'm seeing an exit 1 in `/var/log/supervisord.log`:
> 
> ```
> /tmp/nvd # cat /var/log/supervisord.log
> 2022-01-04 18:20:52,685 INFO Set uid to user 0 succeeded
> 2022-01-04 18:20:52,688 INFO supervisord started with pid 1
> 2022-01-04 18:20:53,692 INFO spawned: 'crond' with pid 7
> 2022-01-04 18:20:53,694 INFO spawned: 'httpd' with pid 8
> 2022-01-04 18:20:53,697 INFO spawned: 'initialize_htdocs' with pid 9
> 2022-01-04 18:20:54,780 INFO success: crond entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2022-01-04 18:20:54,780 INFO success: httpd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2022-01-04 18:20:54,781 INFO success: initialize_htdocs entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2022-01-04 18:21:07,988 INFO exited: initialize_htdocs (exit status 1; not expected)
> ```

How  you solve it?

**Comment by dadurex** [comment]
Ehmm, securityContext 101

https://github.com/stevespringett/nist-data-mirror/blob/master/k8s/nist-data-mirror/values.yaml#L130-L131

maybe simply change USER to `nvdmirror` instead of setting it by securityContext.
