### ISSUE TITLE
Execution broken with latest updates

### ISSUE THREAD

**Issue by awhitford** [dependency-check/DependencyCheck#393]
I just pulled the latest code and now using it breaks.

Looks like the _deprecated_ `aggregate` parameter is _null_, then line 355 of `BaseDependencyCheckMojo` is attempting a boolean check:

```
    private void validateAggregate() throws MojoExecutionException {
        if (aggregate) {
            final String msg = "Aggregate configuration detected - as of dependency-check 1.2.8 this no longer supported. "
                    + "Please use the aggregate goal instead.";
            throw new MojoExecutionException(msg);
        }
    }
```

Why not simply remove the _deprecated_ `aggregate` parameter?

Alternatively, it can be defaulted to `false`.

**Comment by jeremylong** [comment]
Sorry about that, I mised two coding tasks into a single commit and obviously failed to test the changes to aggregate - I added a null check. This was left in to avoid breaking builds when people upgraded to a new version of dependency-check.
