### ISSUE TITLE
Merging multiple dependency check outputs together 

### ISSUE THREAD

**Issue by mgrove-citco** [dependency-check/DependencyCheck#3932]
We have two separate builds: one for Java (backend using maven) and one for React (frontend using npm / yarn). Is there a way to combine the output of running dependency-check on both frontend and backend into a single set of files (html report, junit xml, and so on)? Sometimes, other systems (like SonarQube plugin for dependency-check) only allow for a single input html or json file, so unless we have separate projects in those systems for our application as a whole, we can only use dependency-check on frontend or backend - not both.

**Comment by jeremylong** [comment]
Unfortunately - no. At this time the core project does not provide a way to aggregate results outside of the aggregation capabilities in the gradle and maven plugins.  One option if both code bases were on the build server at the same time would be to use the Maven plugin and add a scan set that points to the npm project. Something like:
```xml
    <plugin>
      <groupId>org.owasp</groupId>
      <artifactId>dependency-check-maven</artifactId>
      <version>6.5.2</version>
      <configuration>
          <scanSet>
                <fileSet>
                    <directory>path/to/npm/project</directory>
                </fileSet>
          </scanSet>
      </configuration>
      <executions>
          <execution>
              <goals>
                  <goal>check</goal>
              </goals>
          </execution>
      </executions>
    </plugin>
```
