### ISSUE TITLE
Output URL of Github repo

### ISSUE THREAD

**Issue by bjk7119** [dependency-check/DependencyCheck#3935]
Hi 😄 

I got .jar file analysis result of my source code using dependency-check-py tool.
But, when the url is the github's url, the url is not full url but just (owner)-(repo_name) format.
ex) whitesource/pecoff4j-maven

present output : whitesource/pecoff4j-maven
expected output : https://github.com/whitesource/pecoff4j-maven

So, could you fix it to output full url of github?

**Comment by jeremylong** [comment]
I'm not sure what `dependency-check-py` is or how I would fix it. Assuming you mean dependency-check CLI? If so - what command did you use and do you have an example requirements.txt or similar supported file?

**Comment by bjk7119** [comment]
Yes right.
I mean dependency-check CLI.

I used this command because I wanted to get only jar analysis result .
`dependency-check --scan . --out . --disableArchive --disableAssembly --disableRetireJS --disableNodeJS --disableNodeAudit --disableNugetconf --disableNuspec --disableOpenSSL --disableOssIndex --disableBundleAudit -f ALL`

The follwoing capture is html result file and I can see Vendor > pom > url > **google/j2objc** (highlight)
So, I hope the url represents full url such as 'https://github.com/google/j2objc/'.


![image](https://user-images.githubusercontent.com/81218204/149714193-02cffd37-1f2f-4de8-a4e7-e1423628b6b3.png)

**Comment by bjk7119** [comment]
@jeremylong 
Is this possible to progress, sir?
If not, could you please let me know?

**Comment by jeremylong** [comment]
You are looking at the evidence section - some information is stripped out to prevent FP. We currently do not list the SCM or URLs in the report.
