### ISSUE TITLE
Using developers/developer.organization element from pom.xml.

### ISSUE THREAD

**Issue by tomcz7** [dependency-check/DependencyCheck#3942]
Hi
I was wondering if using organization from developers/developer element in the pom.xml would be good eg. when organization is not in the pom.xml and it couldn't be detected properly using other elements.

eg like for https://repo1.maven.org/maven2/io/ktor/ktor-server-core/1.6.0/ktor-server-core-1.6.0.pom
which has vulnerabilities registered as 
https://nvd.nist.gov/products/cpe/detail/1078155?namingFormat=2.3&orderBy=CPEURI&keyword=ktor&status=FINAL

But in the pom there is no element named jetbrains except developers/developer.organization
but is used in cpe string.

**Comment by jeremylong** [comment]
Thank you for the suggestion. This will be included in the 7.0.0 release via PR https://github.com/jeremylong/DependencyCheck/pull/3952.
