### ISSUE TITLE
Make suppression file optional

### ISSUE THREAD

**Issue by strangelookingnerd** [dependency-check/DependencyCheck#3947]
**Is your feature request related to a problem? Please describe.**
I use dependency check with maven. All definitions and configuration of the plugin is done in a parent pom that is released regularly.
Other modules depend on this parent in order to get the same configuration. However if I need a suppression for a CVE on a module I have to define the build/plugin configuration every time with a suppression file. If I define a suppression file in the parent pom I get an error for that file being missing on modules that don't define / need it.

**Describe the solution you'd like**
Make the suppression files optional. If a file does not exist there should be no harm - a warning in the log would be more than sufficient. However this allows me to define a _commonly named_ suppression file in my parent pom and have my modules decide whether or not they want to define it.

**Describe alternatives you've considered**
I tried having an artifact that does include a "central" suppression file and have it as a dependency for my modules so the file would be available in the classpath. However this is cumbersome in my scenario plus I actually do want to define the suppression **in** the module for better visibility / maintainability of dependencies and CVE.
Another approach would be to have an empty suppression file in all my modules which does not seem like a feasible solution.

**Additional context**
I'm willing to provide a PR however I wanted to first check if this feature is according to other peoples expectation.

**Comment by aikebah** [comment]
You can use profiles in your parent pom to that effect if you combine it with a standard convention on filter location.

```xml
    <profiles>
        <!-- The following profile runs the dependency-check as part of the build with a suppressionFile
        (active if src/main/dependency-check/filter.xml is present) -->
        <profile>
            <id>odc-filtered</id>
            <activation>
                <file>
                    <exists>${basedir}/src/main/dependency-check/filter.xml</exists>
                </file>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.owasp</groupId>
                        <artifactId>dependency-check-maven</artifactId>
                        <version>${odc.version}</version>
                        <configuration>
                            <suppressionFiles>
                                <suppressionFile>${basedir}/src/main/dependency-check/filter.xml</suppressionFile>
                            </suppressionFiles>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>check</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <!-- The following profile runs the dependency-check as part of the build without a suppressionFile
        (active if src/main/dependency-check/filter.xml is missing) -->
        <profile>
            <id>odc-unfiltered</id>
            <activation>
                <file>
                    <missing>${basedir}/src/main/dependency-check/filter.xml</missing>
                </file>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.owasp</groupId>
                        <artifactId>dependency-check-maven</artifactId>
                        <version>${odc.version}</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>check</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
```

**Comment by aikebah** [comment]
That way you can even include a central suppression file for common in-company false positive CPE matches if desired (you can list more than one suppression file in the first and you could include the overall company-suppression file in the second profile in that case (these broad in-company suppressions could be used to avoid that e.g. `com.mycompany:oracle:1.0:jar` - some incompany generic library with oracle DB related utlitities - would get linked to the Oracle DB version 1.0 by lack of a better match)

**Comment by strangelookingnerd** [comment]
@aikebah Thanks for your response. That's actually a quite elegant solution I must say.

I'd still prefer it if the absence of a configured suppression file (remote, local or in classpath) would not cause the whole analyzer to abort. As a user I'd be happy to see the failure as  an warning / error in the log and continue with the analysis regardless (or even have it configurable?). But again, maybe that's just me.

**Comment by mprins** [comment]
I feel that a missing suppression file is a configuration error and should throw an error.

**Comment by jeremylong** [comment]
As there is a solution to your problem (thanks @aikebah!) and the fact that I agree with @mprins on this. I'm going to close the enhancement request.

**Comment by donatelloOo** [comment]
I am also very surprised this file is mandatory.

When using aggregate goal + child modules, it's a common pattern that most of the modules won't need a suppressionFile, but the plugin configuration being controlled on a TOP pom, the file location is standardized.
In this case, the modules that doesn't define an empty file are failing, which is a bit unnecessary.

This workaround works, but is very verbose for a simple stuff which could be a single property like "ignoreMissingSupressionFile".
It also have a strong limitation, that prevent enabling a specific profile (for instance when running on CICD build).

Another problem related to this, is that the aggregate goal is not reusing individual module's suppressionFile, so even if a CVE is suppressed on a child module, the aggregate report will still show it.

For these reasons, I would recommend reopening this issue.

**Comment by aikebah** [comment]
In the case of an aggregate scan you should not run the goal on the child modules. ODC should only be configured as an aggregate scan on the top-level, so it only needs a suppressionfile at the top level containing all suppressions for your moduleset.

**Comment by aikebah** [comment]
For the maven case it means defining the plugin with `<inherited>false</inherited>` in the toplevel pom

https://maven.apache.org/guides/mini/guide-configuring-plugins.html#Using_the_inherited_Tag_In_Build_Plugins

when you configure it for the aggregate goal

**Comment by donatelloOo** [comment]
> For the maven case it means defining the plugin with `<inherited>false</inherited>` in the toplevel pom
> 
> https://maven.apache.org/guides/mini/guide-configuring-plugins.html#Using_the_inherited_Tag_In_Build_Plugins
> 
> when you configure it for the aggregate goal

This trick can work in small multi-module projects, but here is an example where it does not work:

```
top-project
 - pom.xml (contains dependencyManagement, profiles, and plugins configuration)
```

where:
``` xml
                    <plugin>
                        <groupId>org.owasp</groupId>
                        <artifactId>dependency-check-maven</artifactId>
                        <executions>
                            <execution>
                                <id>dependency-check</id>
                                <!-- <inherited>false</inherited> -->
                                <goals>
                                    <goal>aggregate</goal>
                                </goals>
                            </execution>
                        </executions>
                        <!-- see https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html -->
                        <configuration>
                            <formats>
                                <format>html</format> <!-- for Sonar -->
                                <format>json</format> <!-- for Sonar -->
                                <format>xml</format>  <!-- for Jenkins -->
                            </formats>
                            <suppressionFile>${dependency-check.suppressionFile}</suppressionFile>
                        </configuration>
                    </plugin>
```

```
app-component
- pom.xml (parent is top-project pom.xml non relative reference)
- dependency-check-suppressions.xml
- module1
  - pom.xml
- module2
  - pom.xml 
```
where pom files are as simple as possible / no additional dependency-check configuration or eventually a reference to a suppression file (this could be also removed if file was optional / ignored if not present) :
``` xml
    <properties>
        <!-- configuration: OWASP dependency-check CVE suppression -->
        <dependency-check.suppressionFile>${project.basedir}/dependency-check-suppressions.xml</dependency-check.suppressionFile>
    </properties>
```

Here, if `<inherits>false</inherits>` is set, the aggregate goal is not executed at all on `app-component` project, because it's already a child of top-project, so we need to put inherits=true (default) and let the aggregate goal execute on all child modules.

**Comment by aikebah** [comment]
Sounds like a company / cross-project generic parent?

Currently on mobile, I'll get back with a recommendation for such a case when back on the laptop. In my dayjob we have a similar setup (configuring the check goal in the top-level pom, which gets applied to any simple (single top-level pom) library), where all we need to do in such a multimodule project is a small config override in app-component pom to change the goal to aggregate and stop inheritance. (configs are inherited from top-level company maven parent).

**Comment by aikebah** [comment]
top-level pom: recommended to have a setup like [my comment](https://github.com/jeremylong/DependencyCheck/issues/3947#issuecomment-1005024826) flexible enough to activate/deactivate filtering based on the presence of the suppression file in the project, modified to take the goal from a property (e.g. `<goal>${odc.goal}</goal>`) also defined in the top-level pom:
```xml
    <properties>
        <odc.goal>check</odc.goal>
    </properties>
```

app-component project would then hold the suppressions file for the app-component multimodule structure and have in its pom.xml only the following related to dependency-check

```xml
    ...
    <properties>
        <odc.goal>aggregate</odc.goal>
    </properties>

    <build>
        <plugins>
           ...
            <plugin>
                <groupId>org.owasp</groupId>
                <artifactId>dependency-check-maven</artifactId>
                <inherited>false</inherited>
            </plugin>
        </plugins>
           ...
    </build>
```

The rest of its configuration will be inherited from the top-level pom

Single-level projects inherit the default 'check' based execution from the top-level project and don't need any reference to dependency-check in their pom
