### ISSUE TITLE
[ERROR] Could not execute .NET AssemblyANalyzer on Windows 10

### ISSUE THREAD

**Issue by Lowell130** [dependency-check/DependencyCheck#3949]
Hello,
i have small issues on Dependency-check and .NET binary dependency check

there is my enviroment
- Windows 10 version 10.0.19043
- Dotnet 6.0.101 on path C:\Program files\dotnet
- Dependency-check plugin 6.5.1 on path C:\dependency-check
- Dotnet SDK 6.0.101 on path C:\Program files\dotnet\sdk

When i start a scan with these commands: C:\dependency-check\bin\dependency-check.bat --scan /path/of/source/ --format HTML --out /path/of/source/report.html --log /path/of/source/report.log

i got results only for npm dependency that exist on my sources file and see and error about .NET assembly like that:
[ERROR] Could not execute .NET AssemblyANalyzer

what's wrong?
Thanks

**Comment by jeremylong** [comment]
at the moment donet 3.1 is required to run ODC. It will still be able to analyze assemblies built for the new runtime. We will likely update to the most recent LTS version soon.

**Comment by jeremylong** [comment]
I just opened a ticket (#3951) to track the update - which will be planned for the 7.0 release.
