### ISSUE TITLE
DependencyCheck can be integrated with Azure Devops

### ISSUE THREAD

**Issue by salnakuruvi** [dependency-check/DependencyCheck#3957]
DependencyCheck can be integrated with Azure Devops ? if yes please help us with some Documentation

**Comment by jeremylong** [comment]
https://www.google.com/search?q=dependency+check+azure+devops

https://marketplace.visualstudio.com/items?itemName=dependency-check.dependencycheck

https://github.com/dependency-check/azuredevops/blob/main/build/README.md

**Comment by salnakuruvi** [comment]
Thank you @jeremylong
