### ISSUE TITLE
Potential vulnerability with H2

### ISSUE THREAD

**Issue by javixeneize** [dependency-check/DependencyCheck#3959]
Hi

I am not sure if dependency check would be affected by that, but i know it uses H2 database. https://www.infosecurity-magazine.com/news/researchers-new-log4shelllike-java/

Can you check this please?

**Comment by mrjonstrong** [comment]
Looks like it is used [https://github.com/jeremylong/DependencyCheck/blob/40630a16532e57c8315b3f155010c9628ccca078/pom.xml#L144](https://github.com/jeremylong/DependencyCheck/blob/40630a16532e57c8315b3f155010c9628ccca078/pom.xml#L144)
But it's patched in 2.0.206, however looks from this PR #3928 that upgrading from V1 to V2 is not straightforward.

**Comment by mprins** [comment]
ODC does not run the H2 Console application, nor does it run H2 in server mode

**Comment by javixeneize** [comment]
That’s what I thought ;) I will close it then
