### ISSUE TITLE
False Positive on play-cache, play-ehcache cachecontrol, shiro-cache

### ISSUE THREAD

**Issue by philipwhiuk** [dependency-check/DependencyCheck#3963]
A sample JVM (Scala) dependency can be obtained by Maven/SBT.

The conflicts are with a CPE for a Rust Library.

False positive on multiple Play Framework Scala libraries  - e.g. play-cache_2.12-2.8.2.jar - which are reported as matching:

`cpe:2.3:a:cache_project:cache:2.8.2`

Maven
```xml
<dependency>
   <groupId>com.typesafe.play</groupId>
   <artifactId>play-cache_2.12</artifactId>
   <version>2.8.2</version>
</dependency>
```

**Comment by aikebah** [comment]
This appears to have resolved itself, cannot reproduce with an up-to-date maven plugin (7.1.0)
