### ISSUE TITLE
Dependency Check 6.4.1 - vulnerabilities reported for files unders node_modules even with exclude pattern for node_modules folder is used

### ISSUE THREAD

**Issue by vinodkumarb78** [dependency-check/DependencyCheck#3964]
**Describe the bug**
I'm trying to exclude the node_modules folder which is found inside the wars folder (Example : "wars/nehr-onlinehelp-theme/node_modules"), as part of the dependency check scanning.  Please note that the "wars" folder is directly in the WORKSPACE. 
 I've tried the below patterns to exclude, but still the scan for the artifacts under the "node_modules" folder are reported with vulnerabilities. 

wars/\*\*/node_modules/\*\*
wars/\*\*/node_modules
\*\*/wars/\*\*/node_modules
\*\*/wars/\*\*/node_modules/\*\*
\*\*/node_modules/\*\*

I also tried options to explicitly exclude the folder and also 1 of the files with full hardcoded path.

wars/sstp-portal-theme/node_modules/\*\*
\*\*/wars/sstp-portal-theme/node_modules/\*\*
wars/sstp-portal-theme/node_modules
\*\*/wars/sstp-portal-theme/node_modules
\*\*/wars/nehr-portal-theme/node_modules/gulp-prompt/node_modules/ansi-regex/package.json

**Version of dependency-check used**
I'm using the v6.4.1 CLI version of the Dependency Check tool.

**Log file**
The log size id 5.6 GB. Hence unable to upload the full depcheck.log.
Hence, have uploaded snippets of the log where applicable for node_modules folder.

Refer to the link below:
https://gist.github.com/vinodkumarb78/56074d9594fdc6b8ffcca15b2c37ab8d

CSV report output:
https://gist.github.com/vinodkumarb78/e6839924c738741704cf2ef8b45c014b

**Expected behavior**
There shouldn't be any vulnerabilities referencing "node_modules" directories.  Which is currently not the case per the CSV report outpu.

**Comment by jeremylong** [comment]
The node modules directory is not actually being "scanned' per se. Rather - if the package-lock.json referenced a module the node package analyzer reads the package.json to collect information used in vulnerability identification. With PR #3970 - we are correcting the file path to show the reference within the package-lock.json (the package management file that was actually scanned).

**Comment by vinodkumarb78** [comment]
Thank you for your response and addressal of reported issue.
