### ISSUE TITLE
dependancyCheck analyse stop always at "Finished False Positive Analyzer"

### ISSUE THREAD

**Issue by ilyesDjerroud** [dependency-check/DependencyCheck#3971]
Please delete any un-needed section from the following issue template:

### Reporting Bugs/Errors
When reporting errors, 99% of the time log file output is required. Please post the log file as a [gist](https://gist.github.com/) and provide a link in the new issue.

### Reporting False Positives
When reporting a false positive please include:
- The location of the dependency (Maven GAV, URL to download the dependency, etc.)
- The CPE that is believed to be false positive
  - Please report the CPE not the CVE

#### Example
False positive on library foo.jar - reported as cpe:/a:apache:tomcat:7.0
```xml
<dependency>
   <groupId>org.sample</groupId>
   <artifactId>foo</artifactId>
   <version>1.0</version>
</dependency>
```

**Comment by jeremylong** [comment]
We would need a lot more information to assist.  A debug log (if using the CLI as `--log=odc.log`).
