### ISSUE TITLE
No major version found for postcss 8.4.5

### ISSUE THREAD

**Issue by fabienheureux** [dependency-check/DependencyCheck#3977]
**Describe the bug**
Running dependency check fails while looking for postcss 8.4.5

**Version of dependency-check used**
I can't determine the version, it is ran by a CI I don't have access, but I know it is a fairly recent version. 

**Log file**
https://gist.github.com/fabienheureux/bd4019ec5f8f9fed3f62dfee739d1946
  
**Expected behavior**
It seems like there is an existing major version of postcss 8.4.5 :thinking:  https://www.npmjs.com/package/postcss

**Comment by jeremylong** [comment]
see https://github.com/jeremylong/DependencyCheck/issues/3956

**Comment by fabienheureux** [comment]
Oh sorry, I looked for a postcss related issue but did not think of looking for a more generic issue. 
Thanks for the quick reply !

**Comment by jeremylong** [comment]
No worries - the next release will be within a day or two.
