### ISSUE TITLE
Configuration option to disable disclaimer

### ISSUE THREAD

**Issue by pdenooijer** [dependency-check/DependencyCheck#3981]
Currently every time the dependency check is ran, it will display a disclaimer when starting the analysis process. This disclaimer is very verbose and therefore clouds the logging in for instance a CI environment.

It would be awesome if there could be an extra (advanced) option that disables this disclaimer. By enabling this option the user acknowledges the disclaimer. This option should be turned off by default of course, so new users will see the warning.  

I already checked out the code to find out if there is already such a feature, but I could not find it. The disclaimer is always logged to the INFO level. I could create a pull request with the above feature if that would speed up the process.

**Comment by jeremylong** [comment]
See https://github.com/jeremylong/DependencyCheck/issues/3011

**Comment by pdenooijer** [comment]
I tried to find an other issue but failed, thanks for responding so quickly.
