### ISSUE TITLE
Explain in more detail how CPE matching works

### ISSUE THREAD

**Issue by dkroehan** [dependency-check/DependencyCheck#3988]
Hi!

I currently try to understand how the matching of CPEs on a given project and it's dependencies work. My intention is to better understand the reasons for some false-positives.

I recently had a false-positive where an artifact called `mywebsocketmock` matched against the CPE `cpe:/a:mock-server:mockserver` and I was wondering a lot how this could possibly match.

So far I couldn't find much resources about how the CPE matching works in detail.
What I found so far is:
https://jeremylong.github.io/DependencyCheck/general/internals.html
https://github.com/jeremylong/DependencyCheck/issues/2232#issuecomment-541247832
https://github.com/jeremylong/DependencyCheck/blob/main/core/src/main/java/org/owasp/dependencycheck/analyzer/CPEAnalyzer.java

Therefore, I would like to ask if you could provide a more detailed "how it works" documentation with regards to the CPE matching logic. Maybe based on an example CPE like the above one, with the steps involved in matching / non-matching.

**Comment by aikebah** [comment]
A good way to resolve your main issue and understand why a specific FP match is matched is looking at the evidences collected (listed in the report).

In you specific case: there is a good chance that among those evidences there is a package level .mock. or a textual entry that contains the word mock.

Enabling debug logging may also shed more light on it: among others it will trigger the debug log statements in the CPEAnalyzer that will list the exact search terms used for vendor- and product- search (L275/278) as well as the results (L296) of verifying search-results with the evidences of the dependency at hand (L641-676)

Essentially the algorithm comes down to 'let lucene text search determine the best matches for all the words of the evidences' (L273-305), filter out items that appear to be an invalid match (L293, L641-676) and find the best match (L287-302, L814-979) in evidence quality among the filter-validated top-results  from Lucene'

As it looks for the top-matching lucene results, it may well result in a result that only has a low resemblence with your actual dependency if the actual dependency has no CVE registered against itself and therefore is nit present in the vulnerabilities database (and thus not present in the lucene CPE index that is searched for matching entries)
