### ISSUE TITLE
Option to fail instead of logging `Some CVEs may not be reported`

### ISSUE THREAD

**Issue by vemv** [dependency-check/DependencyCheck#3991]
**Is your feature request related to a problem? Please describe.**

From time to time I see `Some CVEs may not be reported` whenever a download fails. Regardless of its root cause, logging this instead of failing doesn't quite meet my expectations.

**Describe the solution you'd like**

An option, perhaps opt-in, to rethrow `DownloadFailedException` instead of following the current behavior (log, then ignore)

#### Additional context

The feature is hinted in https://github.com/jeremylong/DependencyCheck/issues/520 which was closed for unrelated reasons.

Thanks - V

**Comment by jeremylong** [comment]
I would agree - but rather than an option, ODC should likely just fail.

**Comment by vemv** [comment]
Sounds good to me :)

**Comment by aikebah** [comment]
@jeremylong How about using the 7.0 to make this backward incompatible change in behaviour? Typically I would expect users take a closer look at release notes on a major version bump.

**Comment by vemv** [comment]
Thank you!
