### ISSUE TITLE
Ant fails with NoSuchMethodError on apache common codec

### ISSUE THREAD

**Issue by jordankoehn** [dependency-check/DependencyCheck#3995]
**Describe the bug**
6.1.0 is the last version to run successful 
6.1.1 gets this error
java.lang.NoSuchMethodError: org.apache.commons.codec.digest.DigestUtils.<init>(Ljava/lang/String;)V
6.1.2 through 6.5.3 gets this error
java.lang.NoSuchMethodError: org.apache.commons.codec.digest.DigestUtils.md5Hex(Ljava/io/InputStream;)Ljava/lang/String;

**Version of dependency-check used**
6.1.1+

**Log file**
[gist](https://gist.github.com/jordankoehn/15b4057b1edc7859766f25e9ebdf785d)

**To Reproduce**
1. Run dependency check via ant, scanning jars
2. Fails with above error

**Expected behavior**
dependency check should run via ant, with same args as the cli version of the software

**Additional context**
Runs successfully using the cli version of the software

**Comment by mprins** [comment]
I look like you are providing an incompatible version of commons-codec, as you can see from the pom.xml ODC needs 1.15
https://github.com/jeremylong/DependencyCheck/blob/28b752cc5cffd5f4979a40d18959bc92fbe85314/pom.xml#L1122-L1126

since you have failed to provide your configuration we can only guess

**Comment by jordankoehn** [comment]
Here are the files in the lib folder, commons-codec 1.15 is one of them

aho-corasick-double-array-trie-1.2.3.jar
dependency-check-ant-6.5.3.jar
lucene-analyzers-common-8.11.1.jar
android-json-0.0.20131108.vaadin1.jar
dependency-check-core-6.5.3.jar
lucene-core-8.11.1.jar
annotations-23.0.0.jar
dependency-check-utils-6.5.3.jar
lucene-queries-8.11.1.jar
ant-1.10.12.jar
error_prone_annotations-2.7.1.jar
lucene-queryparser-8.11.1.jar
ant-launcher-1.10.12.jar
failureaccess-1.0.1.jar
lucene-sandbox-8.11.1.jar
checker-qual-3.12.0.jar
gson-2.8.5.jar
minlog-1.3.1.jar
commons-beanutils-1.9.4.jar
guava-31.0.1-jre.jar
ossindex-service-api-1.8.1.jar
commons-codec-1.15.jar
h2-1.4.199.jar
ossindex-service-client-1.8.1.jar
commons-collections-3.2.2.jar
j2objc-annotations-1.3.jar
packager-core-0.17.0.jar
commons-collections4-4.4.jar
jackson-annotations-2.13.1.jar
packager-rpm-0.17.0.jar
commons-compress-1.21.jar
jackson-core-2.13.1.jar
package-url-java-1.1.1.jar
commons-dbcp2-2.9.0.jar
jackson-databind-2.13.1.jar
packageurl-java-1.4.1.jar
commons-digester-2.1.jar
jackson-module-afterburner-2.13.1.jar
pecoff4j-0.0.2.1.jar
commons-io-2.11.0.jar
javax.inject-1.jar
retirejs-core-3.0.3.jar
commons-jcs-core-2.2.1.jar
javax.json-1.1.4.jar
semver4j-3.1.0.jar
commons-lang3-3.12.0.jar
javax.ws.rs-api-2.0.1.jar
slf4j-api-1.7.32.jar
commons-logging-1.2.jar
jcl-over-slf4j-1.7.28.jar
spotbugs-annotations-4.5.3.jar
commons-pool2-2.10.0.jar
jdiagnostics-1.0.7.jar
toml4j-0.7.2.jar
commons-text-1.9.jar
joda-time-2.10.4.jar
velocity-engine-core-2.3.jar
commons-validator-1.7.jar
jsoup-1.14.3.jar
xz-1.8.jar
compiler-0.9.6.jar
jsr305-3.0.2.jar
cpe-parser-2.0.2.jar
listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar

**Comment by jeremylong** [comment]
So did you unzip the [dependency-check-ant-6.5.3-release.zip](https://github.com/jeremylong/DependencyCheck/releases/download/v6.5.3/dependency-check-ant-6.5.3-release.zip) into the libs folder? Looking at your listing it doesn't appear so. If you had you would have a libs folder in the libs folder.

Now maybe the packaging on the ant task is wrong - but its been this way for years. The dependency-check-ant JAR file contains the following MANIFEST.MF. Notice the classpath has all of the dependencies in the lib directory.

```
Manifest-Version: 1.0
Implementation-Title: Dependency-Check Ant Task
Implementation-Version: 6.5.3
Class-Path: lib/dependency-check-core-6.5.3.jar lib/jdiagnostics-1.0.7
 .jar lib/pecoff4j-0.0.2.1.jar lib/commons-jcs-core-2.2.1.jar lib/comm
 ons-logging-1.2.jar lib/packageurl-java-1.4.1.jar lib/cpe-parser-2.0.
 2.jar lib/semver4j-3.1.0.jar lib/slf4j-api-1.7.32.jar lib/commons-col
 lections4-4.4.jar lib/commons-compress-1.21.jar lib/commons-io-2.11.0
 .jar lib/commons-lang3-3.12.0.jar lib/commons-text-1.9.jar lib/common
 s-dbcp2-2.9.0.jar lib/commons-pool2-2.10.0.jar lib/lucene-core-8.11.1
 .jar lib/lucene-analyzers-common-8.11.1.jar lib/lucene-queryparser-8.
 11.1.jar lib/lucene-queries-8.11.1.jar lib/lucene-sandbox-8.11.1.jar 
 lib/velocity-engine-core-2.3.jar lib/h2-1.4.199.jar lib/javax.json-1.
 1.4.jar lib/jsoup-1.14.3.jar lib/jackson-databind-2.13.1.jar lib/jack
 son-annotations-2.13.1.jar lib/jackson-core-2.13.1.jar lib/jackson-mo
 dule-afterburner-2.13.1.jar lib/retirejs-core-3.0.3.jar lib/android-j
 son-0.0.20131108.vaadin1.jar lib/minlog-1.3.1.jar lib/compiler-0.9.6.
 jar lib/ossindex-service-client-1.8.1.jar lib/ossindex-service-api-1.
 8.1.jar lib/javax.ws.rs-api-2.0.1.jar lib/package-url-java-1.1.1.jar 
 lib/javax.inject-1.jar lib/jcl-over-slf4j-1.7.28.jar lib/joda-time-2.
 10.4.jar lib/gson-2.8.5.jar lib/guava-31.0.1-jre.jar lib/failureacces
 s-1.0.1.jar lib/listenablefuture-9999.0-empty-to-avoid-conflict-with-
 guava.jar lib/checker-qual-3.12.0.jar lib/error_prone_annotations-2.7
 .1.jar lib/j2objc-annotations-1.3.jar lib/toml4j-0.7.2.jar lib/aho-co
 rasick-double-array-trie-1.2.3.jar lib/commons-validator-1.7.jar lib/
 commons-digester-2.1.jar lib/commons-collections-3.2.2.jar lib/common
 s-beanutils-1.9.4.jar lib/packager-rpm-0.17.0.jar lib/packager-core-0
 .17.0.jar lib/xz-1.8.jar lib/dependency-check-utils-6.5.3.jar lib/com
 mons-codec-1.15.jar lib/jsr305-3.0.2.jar lib/annotations-23.0.0.jar l
 ib/spotbugs-annotations-4.5.3.jar
Build-Jdk-Spec: 1.8
Created-By: Maven JAR Plugin 3.2.1
Implementation-Vendor: OWASP
```

So one would need to have:
```bash
├── dependency-check-ant.jar
└── lib
    ├── aho-corasick-double-array-trie-1.2.3.jar
    ├── android-json-0.0.20131108.vaadin1.jar
    ├── annotations-23.0.0.jar
    ├── checker-qual-3.12.0.jar
    ├── commons-beanutils-1.9.4.jar
    ├── commons-codec-1.15.jar
    ├── commons-collections-3.2.2.jar
    ├── commons-collections4-4.4.jar
    ├── commons-compress-1.21.jar
    ├── commons-dbcp2-2.9.0.jar
    ├── commons-digester-2.1.jar
    ├── commons-io-2.11.0.jar
    ├── commons-jcs-core-2.2.1.jar
    ├── commons-lang3-3.12.0.jar
    ├── commons-logging-1.2.jar
    ├── commons-pool2-2.10.0.jar
    ├── commons-text-1.9.jar
    ├── commons-validator-1.7.jar
    ├── compiler-0.9.6.jar
    ├── cpe-parser-2.0.2.jar
    ├── dependency-check-ant-6.5.3.jar
    ├── dependency-check-core-6.5.3.jar
    ├── dependency-check-utils-6.5.3.jar
    ├── error_prone_annotations-2.7.1.jar
    ├── failureaccess-1.0.1.jar
    ├── gson-2.8.5.jar
    ├── guava-31.0.1-jre.jar
    ├── h2-1.4.199.jar
    ├── j2objc-annotations-1.3.jar
    ├── jackson-annotations-2.13.1.jar
    ├── jackson-core-2.13.1.jar
    ├── jackson-databind-2.13.1.jar
    ├── jackson-module-afterburner-2.13.1.jar
    ├── javax.inject-1.jar
    ├── javax.json-1.1.4.jar
    ├── javax.ws.rs-api-2.0.1.jar
    ├── jcl-over-slf4j-1.7.28.jar
    ├── jdiagnostics-1.0.7.jar
    ├── joda-time-2.10.4.jar
    ├── jsoup-1.14.3.jar
    ├── jsr305-3.0.2.jar
    ├── listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
    ├── lucene-analyzers-common-8.11.1.jar
    ├── lucene-core-8.11.1.jar
    ├── lucene-queries-8.11.1.jar
    ├── lucene-queryparser-8.11.1.jar
    ├── lucene-sandbox-8.11.1.jar
    ├── minlog-1.3.1.jar
    ├── ossindex-service-api-1.8.1.jar
    ├── ossindex-service-client-1.8.1.jar
    ├── package-url-java-1.1.1.jar
    ├── packager-core-0.17.0.jar
    ├── packager-rpm-0.17.0.jar
    ├── packageurl-java-1.4.1.jar
    ├── pecoff4j-0.0.2.1.jar
    ├── retirejs-core-3.0.3.jar
    ├── semver4j-3.1.0.jar
    ├── slf4j-api-1.7.32.jar
    ├── spotbugs-annotations-4.5.3.jar
    ├── toml4j-0.7.2.jar
    ├── velocity-engine-core-2.3.jar
    └── xz-1.8.jar
```

**Comment by jeremylong** [comment]
Also - in reference to how you may have setup the task in your ant build take a look at: https://jeremylong.github.io/DependencyCheck/dependency-check-ant/

Again, maybe the tool is not packaged well. But it has been this way for years.

**Comment by zabbal** [comment]
On a related note, what's the proper place to look for version 1.15? Looking at https://mvnrepository.com/artifact/org.apache.commons/org.apache.commons.codec I can only see 1.3.0-smth
