### ISSUE TITLE
False Positive on camel-activemq-3.14.0.jar

### ISSUE THREAD

**Issue by nita-au** [dependency-check/DependencyCheck#3998]
False positive on library camel-activemq-3.14.0.jar - reported as `cpe:2.3:a:apache:activemq:3.14.0` and `cpe:2.3:a:apache:camel:3.14.0`

```xml
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-activemq</artifactId>
    <version>3.14.0</version>
</dependency>
```

Seems to be matching on camel-activemq-starter-3.14.0.jar

**Comment by aikebah** [comment]
Appears to have been resolved in more recent versions, currently only identified as the camel CPE, which is valid as the library is part of the Camel project, which has a single CPE in the NVD
