### ISSUE TITLE
Version Evidence Removed

### ISSUE THREAD

**Issue by colezlaw** [dependency-check/DependencyCheck#40]
I'm having a hard time determining exactly the circumstances, but it seems that any evidence added to the version collection is removed if it's unable to make a CPE match otherwise.

We created a new analyzer which attempts to identify the product and version of some internal files. If we do the following:

```
dependency.getVersionEvidence().addEvidence(source, name, version, Evidence.Confidence.HIGHEST);
dependency.getProductEvidence().addEvidence(source, name, product, Evidence.Confidence.HIGHEST);
```

Then no version evidence shows in the report. The only time version information shows up is if we add a vendor evidence, and that vendor is able to be matched. Even if the Version and Product together make an exact match, if the vendor is missing, the version information is removed.

I suspect this is because the CPE matching is done in an iterative fashion, and it stops working if it can't identify a product. This is challenging because the modules in question don't really have any vendor information in the files themselves.

**Comment by jeremylong** [comment]
I'm not sure exactly what is going on as no where in the pipeline of
analyzers is evidence removed. What phase does your analyzer run in? Also,
the reports only show evidence that is used in the determination of the CPE
identifier; but I don't think this should come into play for you as you are
using HIGHEST.

I'll try to put together a test case to see if I can replicate the problem
(knowing the analyzer phase would be helpful). Any chance you could provide
the source code for the analyzer?

--Jeremy

**Comment by colezlaw** [comment]
It was during `INFORMATION_COLLECTION`, and I believe it's as you described - it's not that the version information is being dropped, it's that it's just not used in the determination when it's not able to determine a product. The specific example I had was when adding evidence for product `log4net` version `1.2.9_beta` (I just made a test analyzer with hardcoded values). If you don't add vendor evidence, or if the vendor evidence is `log4net` (or something else that isn't Apache), the version evidence doesn't show up in the evidence list (although the vendor and product evidence do). If you change the vendor evidence to `apache` or `Apache Software Foundation`, etc., the version information shows up.

```
public void analyze(Dependency dependency, Engine engine) {
  logger.info("Checking dependency " + dependency.getFileName());

  // If you change the below to apache, the version info shows
  // if you remove it, or leave it as log4net, it's still gone
  dependency.getVendorEvidence().addEvidence("demo", "magic", "log4net", Evidence.Confidence.MEDIUM);
  dependency.getProductEvidence().addEvidence("demo", "magic", "log4net", Evidence.Confidence.HIGHEST);
  dependency.getVersionEvidence().addEvidence("demo", "magic", "1.2.9_beta", Evidence.Confidence.HIGHEST);
}
```

The problem is that some of the analyzers I'm looking at writing (for Information Collection) might be able to get a pretty good product, but not necessarily a good vendor. For example, if I can identify Maven coordinates without a POM for a product, I might end up with `commons-logging` as a product. The Maven group for it is `commons-logging`. Unless I start adding hard-coded vendor checks for things like those, then I'm not going to be able to give an accurate vendor, although the product and version will be accurate. .NET assemblies also often have a product name and version, but the company information is either missing or inaccurate.

**Comment by jeremylong** [comment]
I've got a number of changes in flight, but in my local copy I just
modified the CPE analyzer to "use" the version evidence at the same time it
is utilizing the Vendor/Product evidence. This will solve the problem of
the evidence disappearing from the report. I'll close this bug when I push
the code to github.

--Jeremy

**Comment by colezlaw** [comment]
That's awesome! Looking forward to it.

I sent a pull request for a new analyzer which will look up an artifact on
a Nexus  repository. More description is available in the pull request.

**Comment by jeremylong** [comment]
The code to fix this issue has been pushed to the current snapshot. Other changes are still in flight so it may be a week or two before this gets released in an official version.
