### ISSUE TITLE
Please share which version of DependencyCheck supports .NET6

### ISSUE THREAD

**Issue by salnakuruvi** [dependency-check/DependencyCheck#4000]
Please share which version of DependencyCheck supports .NET6

**Comment by jeremylong** [comment]
Current versions of ODC require dotnet 3.1 to be installed in order to run the analyzer. The analyzed DLL files can be built using dotnet 6 - but currently the 3.1 runtime is required.  When 7.0.0 is released the GrokAssembly.dll will be recompiled using dotnet 6.

**Comment by salnakuruvi** [comment]
Thank you jeremylong 
Once we install dotnet 3.1, Can we analyze application src build using .NET 6?

**Comment by jeremylong** [comment]
Yes
