### ISSUE TITLE
Timestamps wrong/missing in 6.5.x-release.zip

### ISSUE THREAD

**Issue by ianwilliams1** [dependency-check/DependencyCheck#4003]
**Describe the bug**
Timestamps are missing / incorrect from dependency-check-6.5.x-release.zip.
It is causing confusion as it is displayed as either 1980-00-00, or a date far into the future!

**Version of dependency-check used**
The problem occurs using version dependency-check-6.5.0-release.zip or higher.

**To Reproduce**
```
[/home/user]$ wget https://github.com/jeremylong/DependencyCheck/releases/download/v6.4.1/dependency-check-6.4.1-release.zip
[/home/user]$ unzip -l dependency-check-6.4.1-release.zip | head                                                            
Archive:  dependency-check-6.4.1-release.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  10-11-2021 21:23   dependency-check/
        0  10-11-2021 21:23   dependency-check/bin/
        0  10-11-2021 21:23   dependency-check/lib/
        0  10-11-2021 21:23   dependency-check/plugins/
        0  10-11-2021 21:02   dependency-check/licenses/
        0  10-11-2021 21:02   dependency-check/licenses/commons-cli/
     4139  10-11-2021 21:23   dependency-check/bin/completion-for-dependency-check.sh
[/home/user]$ wget https://github.com/jeremylong/DependencyCheck/releases/download/v6.5.0/dependency-check-6.5.0-release.zip
[/home/user]$ unzip -l dependency-check-6.5.0-release.zip | head
Archive:  dependency-check-6.5.0-release.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  00-00-1980 04:08   dependency-check/
        0  00-00-1980 04:08   dependency-check/bin/
        0  00-00-1980 04:08   dependency-check/lib/
        0  00-00-1980 04:08   dependency-check/plugins/
        0  00-00-1980 04:08   dependency-check/licenses/
        0  00-00-1980 04:08   dependency-check/licenses/commons-cli/
     4189  00-00-1980 04:08   dependency-check/bin/completion-for-dependency-check.sh
[/home/user]$ wget https://github.com/jeremylong/DependencyCheck/releases/download/v6.5.3/dependency-check-6.5.3-release.zip
[/home/user]$ unzip -l dependency-check-6.5.3-release.zip | head
Archive:  dependency-check-6.5.3-release.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  00-00-1980 04:08   dependency-check/
        0  00-00-1980 04:08   dependency-check/bin/
        0  00-00-1980 04:08   dependency-check/lib/
        0  00-00-1980 04:08   dependency-check/plugins/
        0  00-00-1980 04:08   dependency-check/licenses/
        0  00-00-1980 04:08   dependency-check/licenses/commons-cli/
     4189  00-00-1980 04:08   dependency-check/bin/completion-for-dependency-check.sh
```

When unzipping onto RHEL system, we see a date in the future:
```
[/home/user]$ ls -lago dependency-check
total 44
drwxr-xr-x 6  4096 Aug  5  2092 .
drwxrwxr-x 7  4096 Jan 18 10:06 ..
drwxr-xr-x 2  4096 Aug  5  2092 bin
drwxr-xr-x 2  4096 Aug  5  2092 lib
drwxr-xr-x 3  4096 Aug  5  2092 licenses
-rw-r--r-- 1 11358 Aug  5  2092 LICENSE.txt
-rw-r--r-- 1  1003 Aug  5  2092 NOTICE.txt
drwxr-xr-x 2  4096 Aug  5  2092 plugins
-rw-r--r-- 1  1500 Aug  5  2092 README.md
```
In 7-Zip, we see nothing:
![image](https://user-images.githubusercontent.com/45702008/150049736-580a07cb-07c6-458d-96ec-cabc211f9fe7.png)

**Comment by jeremylong** [comment]
With 6.5.0 we started producing [reproducible builds](https://reproducible-builds.org/). See the release notes: https://github.com/jeremylong/DependencyCheck/blob/main/RELEASE_NOTES.md#version-650-2021-11-08. In order to make a Java build reproducible the timestamps on the files must be set to a consistent value.

I highly recommend the use of reproducible builds as it allows independent verification of the build integrity. Reproducible builds using Maven or gradle is simple and requires setting a property or two:

* Maven: https://maven.apache.org/guides/mini/guide-reproducible-builds.html
* Gradle: https://docs.gradle.org/current/userguide/working_with_files.html#sec:reproducible_archives
* sbt: https://github.com/raboof/sbt-reproducible-builds

**Comment by ianwilliams1** [comment]
I understand the "reproducible builds" concept and that " _In order to make a Java build reproducible the timestamps on the files must be set to a consistent value._" 

However, that should be a "**valid timestamp**".

[FAQ](https://maven.apache.org/guides/mini/guide-reproducible-builds.html#faq)

> Q. Can the project.build.outputTimestamp property in pom.xml be updated automatically at release time?
> A. Yes.

_The [Apache maven documentation](https://maven.apache.org/guides/mini/guide-reproducible-builds.html#how-do-i-configure-my-maven-build) probably needs clarification on the feature usage. (separate issue)_

I would suggest the time be the time of the [last git commit](https://reproducible-builds.org/docs/source-date-epoch/):
> To set SOURCE_DATE_EPOCH to the last modification of a git repository you can use ‘git log’, for example in shell:
> `SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)`

I just know that as a user, seeing an invalid (and [fixed? - ie: "1" ](https://github.com/jeremylong/DependencyCheck/blob/main/pom.xml#:~:text=%3Cproject.build.outputTimestamp%3E1%3C/project.build.outputTimestamp%3E)) timestamp is confusing, misleading and I'd suggest wrong. I'd classify  it is a bug as it could impact backup / restore operations of the systems (ie: time stamp 2092-08-05 is  2,226,182,400 seconds  in the future).

Not entirely sure how you'd go about implementing that in the context of this project (am just a user here).

**Comment by jeremylong** [comment]
Thank you for the feedback. I was originally following the referenced maven documentation. I did a little more research and found the `git-commit-id-plugin` so we can easily reference the data from git.

See https://github.com/jeremylong/DependencyCheck/pull/4007
