### ISSUE TITLE
While using ODC 6.0.3 in azure pipeline (application code build using .net 6)

### ISSUE THREAD

**Issue by salnakuruvi** [dependency-check/DependencyCheck#4050]
We are facing the below error while running ODC 6.0.3 in azure pipeline (application code build using .net 6)

[ERROR] Could not execute .NET AssemblyAnalyzer
Dependency Check completed with exit code 242.
Dependency Check reports:
[ '/home/xyz/dependency-check-report.html' ]
Dependency Check failed with message "Dependency Check exited with an error code (exit code: 242)."
##[error]Dependency Check exited with an error code (exit code: 242).

**Comment by mprins** [comment]
.net 3 is required to run the old ODC versions, you will need to wait for #4032 / version 7 to be released to used .not 6 or build your own snapshot from source

**Comment by jeremylong** [comment]
Note that you can still analyze dotnet 6 assemblies - but ODC requires the dotnet 3.1 runtime to execute.
