### ISSUE TITLE
dependency-check-ant dependency-check doesn't support the nested "reportFormat" element.

### ISSUE THREAD

**Issue by Blir** [dependency-check/DependencyCheck#4052]
Hello, based on the [documentation](https://jeremylong.github.io/DependencyCheck/dependency-check-ant/configuration.html), it appears the correct way to specify to only generate JSON and HTML reports for example, is to nest two `<reportFormat>` elements inside the `<dependency-check>` element. Is the documentation wrong? Am I missing something? I am running version 6.5.3.

ant build file snippet:
```
        <target name="dependency-check" description="Dependency-Check Analysis">
                <dependency-check projectname="omitted"
                                reportoutputdirectory="${dependency-check.home}/reports/"
                                centralAnalyzerUseCache="false">

                        <reportFormat format="HTML" />

                        <fileset dir="lib">
                                <include name="**/*.jar"/>
                        </fileset>
                        <fileset dir="src\main\webapp\js">
                                <include name="jquery*.js"/>
                        </fileset>
                </dependency-check>
        </target>
```

Output from ant:
```
[omitted@omitted sonar-test]$ ant -buildfile ~/omitted/sonar.xml dependency-check
Buildfile: /home/omitted/sonar.xml

dependency-check:

BUILD FAILED
/home/omitted/sonar.xml:35: dependency-check doesn't support the nested "reportFormat" element.

Total time: 0 seconds
```

**Comment by aikebah** [comment]
The starting snippet show the way to specify it (don't have an ant project to doublecheck): specify reportFormat as an attribute on the task rather than a nested element.

Documentation or implementation needs a fix to ensure that documentation and implementation are in sync.

**Comment by Blir** [comment]
I do recall the `reportFormat` attribute working as you described. However, how can you specify two explicit output formats using that attribute? In other words, how can you get JSON and HTML output without specifying ALL?

**Comment by aikebah** [comment]
Looking into that, but I think it's currently not possible, I am investigating how to solve it. Currently the only option is to either do one specific report or generate all of them

**Comment by aikebah** [comment]
The latter can be done with reportformat `ALL`
