### ISSUE TITLE
NullPointerException checking jackson-databind 2.13.1

### ISSUE THREAD

**Issue by nvervelle** [dependency-check/DependencyCheck#4058]
**Describe the bug**
A `NullPointerException` is thrown when analyzing one module

**Version of dependency-check used**
The problem occurs using version 6.5.3 of the gradle plugin

**Log file**
```
> Task :xxx:dependencyCheckAnalyze
Verifying dependencies for project xxx

Failed to fetch component-report for: pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.13.1
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "org.owasp.dependencycheck.analyzer.OssIndexAnalyzer.reports" is null
        at org.owasp.dependencycheck.analyzer.OssIndexAnalyzer.enrich(OssIndexAnalyzer.java:235)
        at org.owasp.dependencycheck.analyzer.OssIndexAnalyzer.analyzeDependency(OssIndexAnalyzer.java:158)
        at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**To Reproduce**
I haven't created a reproducible example. If needed, I will try to do it.

**Expected behavior**
No exception thrown.

**Additional context**
Java 17

**Comment by nhumblot** [comment]
Hello, :wave: 

I tried reproducing your issue without success. Here is my minimal working example: https://github.com/nhumblot/owasp-dependency-check-test-directory/tree/4058-jackson-databind/dependency-check-gradle-sample

```
19:17:14: Executing 'dependencyCheckAnalyze'...


> Task :dependencyCheckAnalyze
Verifying dependencies for project dependency-check-gradle-sample
Checking for updates and analyzing dependencies for vulnerabilities
Generating report for project dependency-check-gradle-sample
Found 0 vulnerabilities in project dependency-check-gradle-sample

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
19:17:16: Execution finished 'dependencyCheckAnalyze'.
```

Could you please share a reproducing example?
Thank you for your help. :slightly_smiling_face:

**Comment by nvervelle** [comment]
Hi,

I tried reproducing it again on my current code base, and didn't have any luck to see this problem again even on our complete code. :thinking: 
I don't see how I can make a reproducing example...

Probably best to close this issue. If I see this happening again, I will try to track down the problem to something small and reproducible.

Only thing I can think of :
In [`OssIndexAnalyzer`](https://github.com/jeremylong/DependencyCheck/blob/main/core/src/main/java/org/owasp/dependencycheck/analyzer/OssIndexAnalyzer.java), you're using `synchronized(FETCH_MUTIX)` in [`closeAnalyzer()`](https://github.com/jeremylong/DependencyCheck/blob/main/core/src/main/java/org/owasp/dependencycheck/analyzer/OssIndexAnalyzer.java#L126) and [`analyzeDependency()`](https://github.com/jeremylong/DependencyCheck/blob/main/core/src/main/java/org/owasp/dependencycheck/analyzer/OssIndexAnalyzer.java#L134), but [the call to enrich()](https://github.com/jeremylong/DependencyCheck/blob/main/core/src/main/java/org/owasp/dependencycheck/analyzer/OssIndexAnalyzer.java#L160) is made outside of the synchronized block. Is it possible that you have a race condition ?
* synchronized block is executed in `analyzeDependency()` => `reports` is set to a value
* synchronized block is executed in `closeAnalyzer()` => `reports` is set to null
* end of `analyzeDependency()` is executed with `reports` equals to null producing the bug ?

**Comment by nhumblot** [comment]
Hi, 👋 

Thank you for your quick answer, I'll dive into the code and look for possible edge cases. 🙂
