### ISSUE TITLE
Add own vulnerability database

### ISSUE THREAD

**Issue by italvi** [dependency-check/DependencyCheck#4059]
Hello, unfortunately I did not find this topic in your documentation. Lets say I have a REST API where I can send request to with name, version, cpe, etc. and search for vulnerabilities. Is it possible to add it to dependency-check so dependency-check request this API for vulnerabilities? Is the format on which dependency-check would send this requests defined?

Thanks in forward!

**Comment by jeremylong** [comment]
ODC is open source - you could simply write your own analyzer.

**Comment by italvi** [comment]
Could you be so kind and guide me to the right folders? I found the AnalysisTask in core/src/main/java/org/owasp)/dependencycheck/. Is this the right starting point to understand how to implement an own analyzer?

**Comment by mprins** [comment]
implement https://github.com/jeremylong/DependencyCheck/blob/main/core/src/main/java/org/owasp/dependencycheck/analyzer/Analyzer.java or extend one of the abstract analyzers.
see also: https://jeremylong.github.io/DependencyCheck/dependency-check-core/apidocs/index.html

probably you want to look into how NexusAnalyzer works
