### ISSUE TITLE
Could not connect to Central search UnknownHostException

### ISSUE THREAD

**Issue by TPanic98** [dependency-check/DependencyCheck#4060]
Error log:
[DependencyCheck] [ERROR] Could not connect to Central search. Analysis failed.
[DependencyCheck] java.io.IOException: Finally failed connecting to Central search. Giving up after 7 tries.
[DependencyCheck] 	at org.owasp.dependencycheck.analyzer.CentralAnalyzer.fetchMavenArtifacts(CentralAnalyzer.java:364)
[DependencyCheck] 	at org.owasp.dependencycheck.analyzer.CentralAnalyzer.analyzeDependency(CentralAnalyzer.java:229)
[DependencyCheck] 	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
[DependencyCheck] 	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
[DependencyCheck] 	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
[DependencyCheck] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[DependencyCheck] 	at java.lang.Thread.run(Thread.java:748)
[DependencyCheck] Caused by: java.net.UnknownHostException: search.maven.org
[DependencyCheck] 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:196)
[DependencyCheck] 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:394)
[DependencyCheck] 	at java.net.Socket.connect(Socket.java:606)
[DependencyCheck] 	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
[DependencyCheck] 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
[DependencyCheck] 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
[DependencyCheck] 	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:292)
[DependencyCheck] 	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:395)

###Jenkins Config：

--project xxx
--noupdate 
--format ALL
--log /opt/jenkins/tools/dependency-check-6.5.3/logs/logs.log
-o ${WORKSPACE}/target/
--disableNodeJS 
--disableOssIndex 
--enableRetired 
--failOnCVSS 11
--cveUrlModified http://172.15.3.42:8088/mirror-directory/nvdcve-1.1-modified.json.gz
--cveUrlBase http://172.15.3.42:8088/mirror-directory/nvdcve-1.1-2022.json.gz
--retireJsUrl http://172.15.3.42:8088/jsrepository.json
--disableAssembly
--nexus http://172.16.221.89:8081/repository/rm-central/
--nexusUser dev
--nexusPass xxx

Im OffLine Model

Question: How to config it

**Comment by jeremylong** [comment]
If you have nexus configured - you can just `--disableCentral`.

**Comment by aikebah** [comment]
And note that for invocations without the `--noupdate` you'll want to use a different `--cveBaseUrl` as that value should have a `%d` placeholder at the spot where the year is in the filenames `--cveUrlBase http://172.15.3.42:8088/mirror-directory/nvdcve-1.1-%d.json.gz`.
See also the [CLI argument documentation](https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html).


For your quoted invocation the cveUrlModified and cveUrlBase are obsolete as you already instruct dependencyCheck to skip trying to update the cveDB, so it will not evaluate the NVD CVE datafiles.
