### ISSUE TITLE
Nuget scanner updates - scan *.csproj files and packages.lock.json

### ISSUE THREAD

**Issue by Bjego** [dependency-check/DependencyCheck#4063]
**Is your feature request related to a problem? Please describe.**
Hey guys,
you are scanning nuget packages already. But the handling of nuget packages has been changed in the last couple of years. Usually package references are now stored in the project files *.csproj instead of a packages.config file. There is an packages.lock.json file now as well. The json file is analogous to npms lock file.

Due to this fact, my projects aren't scanning the nuget references anymore, just the dlls in the build output.

https://devblogs.microsoft.com/nuget/enable-repeatable-package-restores-using-a-lock-file/

**Describe the solution you'd like**
Please update the nuget scanner to use:
- packages.lock.json (json) files as primary source ,
-  the project files *.csproj (xml) as secondary
-   packages.config file (xml) as last source for nuget scanning.

When implementing this change, please keep in mind that there can be multiple csproj and also multiple packages.lock.json files. One file per project, eg. myfrontend.csproj and mylogic.csproj. Both would have a separate packages.lock.json and also different pacakges refferenced in the *.csproj files.

**Describe alternatives you've considered**
Guess there aren't really alternatives. As using packages.lock.json is recommended these days and you would need to change your whole project setup to use pacakges.config files in .net 6 and .net core projects these days.

**Additional context**
Nothing

Thanks in advance!

**Comment by Bjego** [comment]
Hey, here are the references for:
- packages in a csproj file: https://docs.microsoft.com/en-gb/nuget/consume-packages/package-references-in-project-files

**Comment by carlin-q-scott** [comment]
It supports scanning `*.csproj`; just specify that with the scan argument.

Windows CLI:
`dependency-check.bat --scan "**\*.csproj"`

Azure DevOps Task:
`scanPath: '"**\*.csproj"'`
