### ISSUE TITLE
Malformed \uxxxx encoding error on some python packages

### ISSUE THREAD

**Issue by 31deR** [dependency-check/DependencyCheck#4072]
Hello! Thank you very much for this tool! Please help to troubleshoot problem that i facing

**Describe the bug**
On Some Python packages scanner returns error "[ERROR] Malformed \uxxxx encoding."
For example [torchmetrics-0.7.1-py3-none-any.whl](https://files.pythonhosted.org/packages/e6/57/8575aca0e9f3b16385b1b4d8247fe56cfbb1a4e56e38b36fc97361ec4e4b/torchmetrics-0.7.0-py3-none-any.whl#sha256=908f6c129ba84864176c23217ab548069a59f1db555b08f20d2f20274564f90a)

**Version of dependency-check used**
The problem occurs using version 6.4.1 of the cli

**Log file**
ODC scan failed with 242.

Output: [WARN] dbPassword used on the command line, consider moving the password to a properties file using the key `data.password` and using the --propertyfile argument instead
[INFO]

Dependency-Check is an open source tool performing a best effort analysis of 3rd party dependencies; false positives and false negatives may exist in the analysis performed by the tool. Use of the tool and the reporting provided constitutes acceptance for use in an AS IS condition, and there are NO warranties, implied or otherwise, with regard to the analysis or its use. Any use of the tool and the reporting provided is at the user’s risk. In no event shall the copyright holder or OWASP be held liable for any damages whatsoever arising out of or in connection with the use of this tool, the analysis performed, or the resulting report.

About ODC: https://jeremylong.github.io/DependencyCheck/general/internals.html
False Positives: https://jeremylong.github.io/DependencyCheck/general/suppression.html

💖 Sponsor: https://github.com/sponsors/jeremylong

[INFO] Analysis Started
[INFO] Finished File Name Analyzer (0 seconds)
[WARN] An unexpected error occurred during analysis of '/var/www/fossproxy/media/scan_files/torchmetrics-0.7.1-py3-none-any_uSCJKmJ.whl' (Python Distribution Analyzer): Malformed \uxxxx encoding.
[ERROR]
java.lang.IllegalArgumentException: Malformed \uxxxx encoding.
at java.util.Properties.loadConvert(Properties.java:574)
at java.util.Properties.load0(Properties.java:391)
at java.util.Properties.load(Properties.java:341)
at org.owasp.dependencycheck.analyzer.PythonDistributionAnalyzer.getManifestProperties(PythonDistributionAnalyzer.java:376)
at org.owasp.dependencycheck.analyzer.PythonDistributionAnalyzer.collectWheelMetadata(PythonDistributionAnalyzer.java:293)
at org.owasp.dependencycheck.analyzer.PythonDistributionAnalyzer.collectMetadataFromArchiveFormat(PythonDistributionAnalyzer.java:232)
at org.owasp.dependencycheck.analyzer.PythonDistributionAnalyzer.analyzeDependency(PythonDistributionAnalyzer.java:185)
at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
[INFO] Finished Python Distribution Analyzer (0 seconds)
[INFO] Finished Dependency Merging Analyzer (0 seconds)
[INFO] Finished Version Filter Analyzer (0 seconds)
[INFO] Finished Hint Analyzer (0 seconds)
[INFO] Created CPE Index (0 seconds)
[INFO] Finished NPM CPE Analyzer (0 seconds)
[INFO] Created CPE Index (1 seconds)
[INFO] Finished CPE Analyzer (1 seconds)
[INFO] Finished False Positive Analyzer (0 seconds)
[INFO] Finished NVD CVE Analyzer (0 seconds)
[INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
[INFO] Finished Dependency Bundling Analyzer (0 seconds)
[INFO] Analysis Complete (1 seconds)
[INFO] Writing report to: /tmp/tmpefbnb52d/dependency-check-report.json
[INFO] Writing report to: /tmp/tmpefbnb52d/dependency-check-report.html
[ERROR] Malformed \uxxxx encoding.

Error output:

**Comment by aikebah** [comment]
It's a bug in the metadataparsing of the PythonDistributionAnalyzer as that does not properly parse the METADATA

Python metadata according to [the spec](https://packaging.python.org/en/latest/specifications/core-metadata/) uses a format derived from email standards, with a prescribed encoding of UTF-8.

Parsing it with the java Properties class to get the key/value pairs is wrong in more than one way: 
* it does not properly cater for the possibility of a description as the 'message body', where your error is triggered as the description contains `\url...` which is not a unicode character reference, so the Properties class throws an illegalArgumentException as it expects any string starting with \u to represent a 4-digit unicode character reference.
* java.lang.Properties is expecting a properties file encoded with iso-8859-1, so when the metadata would use accented UTF-8 encoded text it would likely break or cause improper characters as UTF-8 encoded characters would be interpreted with the iso-8859-1 characterset.

**Comment by 31deR** [comment]
> It's a bug in the metadataparsing of the PythonDistributionAnalyzer as that does not properly parse the METADATA
> 
> Python metadata according to [the spec](https://packaging.python.org/en/latest/specifications/core-metadata/) uses a format derived from email standards, with a prescribed encoding of UTF-8.
> 
> Parsing it with the java Properties class to get the key/value pairs is wrong in more than one way:
> 
> * it does not properly cater for the possibility of a description as the 'message body', where your error is triggered as the description contains `\url...` which is not a unicode character reference, so the Properties class throws an illegalArgumentException as it expects any string starting with \u to represent a 4-digit unicode character reference.
> * java.lang.Properties is expecting a properties file encoded with iso-8859-1, so when the metadata would use accented UTF-8 encoded text it would likely break or cause improper characters as UTF-8 encoded characters would be interpreted with the iso-8859-1 characterset.

Thnx for detailed explanation!!

**Comment by jeremylong** [comment]
@aikebah are you swapping out the Properties or do you want me to?

https://github.com/jeremylong/DependencyCheck/blob/82c6b94195abad414d86310d501fc5d34bc16fc7/core/src/main/java/org/owasp/dependencycheck/analyzer/PythonDistributionAnalyzer.java#L370-L371

**Comment by aikebah** [comment]
@jeremylong Did not start yet, so fine by me if you work on fixing it.

**Comment by SrikanthShyamanur** [comment]
@jeremylong @aikebah Is there a branch which has solution for this ? or can you please highlight what is the workaround for this ?

**Comment by 31deR** [comment]
> @jeremylong @aikebah Is there a branch which has solution for this ? or can you please h

**Comment by jeremylong** [comment]
@aikebah I have not been able to get to this yet.

**Comment by aikebah** [comment]
@jeremylong OK... then I'll start work on it

**Comment by aikebah** [comment]
@31deR @SrikanthShyamanur Any of you able to try out the snapshot from branch [issue-4072](https://github.com/jeremylong/DependencyCheck/tree/issue-4072)? I don't have a Python build-environment on my system so I have to fully depend on the specs, but a snapshot built from that branch should be able to properly process Python package metadata that's currently failing on the malformed \uxxxx encoding error.

**Comment by SrikanthShyamanur** [comment]
@aikebah I picked this solution into 6.5.3 and ran the scan, this issue seems to be resolved, but my scan still fails at the end after 3 hours of run without any error/exception.

**Comment by 31deR** [comment]
> @aikebah I picked this solution into 6.5.3 and ran the scan, this issue seems to be resolved, but my scan still fails at the end after 3 hours of run without any error/exception.

tets

**Comment by 31deR** [comment]
@aikebah excuse me my stupidy, but how can i get prepared cli  tool(like this [dependency-check-7.0.0-release.zip](https://github.com/jeremylong/DependencyCheck/releases/download/v7.0.0/dependency-check-7.0.0-release.zip) from this branch https://github.com/jeremylong/DependencyCheck/tree/issue-4072?

**Comment by 31deR** [comment]
@aikebah tried to compile, but failing
<img width="800" alt="image" src="https://user-images.githubusercontent.com/60350660/159498822-920bee9b-f42b-417b-8039-7c735f93d0c2.png">

Not familiar with java to resolve it... pls help

**Comment by 31deR** [comment]
by the way, to check PythonDistributionAnalyzer it's no need to install any python environment. Just download [torchmetrics-0.7.1-py3-none-any.whl](https://files.pythonhosted.org/packages/e6/57/8575aca0e9f3b16385b1b4d8247fe56cfbb1a4e56e38b36fc97361ec4e4b/torchmetrics-0.7.0-py3-none-any.whl#sha256=908f6c129ba84864176c23217ab548069a59f1db555b08f20d2f20274564f90a) or[ opencv_python-4.5.5.64-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl](https://files.pythonhosted.org/packages/67/50/665a503167396ad347957bea0bd8d5c08c865030b2d1565ff06eba613780/opencv_python-4.5.5.64-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl#sha256=b293ced62f4360d9f11cf72ae7e9df95320ff7bf5b834d87546f844e838c0c35) and scan it.

**Comment by aikebah** [comment]
@31deR The error you run into is caused by the absence of the depenency-check-utils jar file in your local repository. I think it would be resolved by running `mvn install` instead of your current call which is likely either `mvn verify` or `mvn package`.

And thanks for the hint that I don't need a python environment set up, but can simply download and scan those packages with the CLI. Completely overlooked that option due to my bias as a user of DependencyCheck within the build-pipeline of maven+java projects.

**Comment by 31deR** [comment]
@aikebah it was "maven compile" call. Tried mvn install -DskipTests, and it`s ok now. But after it where i can find and run cli dependency-check.sh ?

**Comment by aikebah** [comment]
The resulting CLI package you can find inside the cli/target folder as `dependency-check-7.0.1-SNAPSHOT-release.zip`

**Comment by 31deR** [comment]
@aikebah cool! can see it! thank you very much!

**Comment by aikebah** [comment]
`mvn verify` would've worked sufficiently as well, likely even `mvn package`. The issue is that with `mvn compile` there is no jar-file created for the dependency-check-utils submodule, so when the enforcer plugin tries to validate that all dependencies of the dependency-check-core module are compatible with Java8 it breaks because maven cannot hand it the location of the jar-file that represents the dependency-check-utils library. That jar-file is not created when running the compile phase of maven, it will be created by the package phase, which comes later. And there is no 7.0.1-SNAPSHOT vesion of the jar-file available in any of the configured repositories (which for a default maven install is only Maven Central, where only the release-versions of DependencyCheck libraries can be found in addition to the user-specific <user-home>/.m2/repository folder of locally installed libraries) nor among the 'jar files created in the current build' (known as the Maven Reactor). The latter is where maven would've been able to deliver the jar-file from for the `mvn verify` and `mvn package` phases.

**Comment by 31deR** [comment]
@aikebah thank's a lot for your explanation!

Tested this problem packages
torchmetrics-0.7.1-py3-none-any.whl
opencv_python-4.5.5.64-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
detectron2-0.6+cpu-cp36-cp36m-linux_x86_64.html

Now it's ok!

Example

/Users/user/PycharmProjects/Tools/venv/bin/python 
/Users/user/PycharmProjects/Tools/scanners/odc/odc_main.py
7-0-1-PRE/bin/dependency-check.sh --scan /Users/user/PycharmProjects/Tools/scanners/target/whl/torchmetrics-0.7.0-py3-none-any.whl --format HTML --enableExperimental --disableOssIndex --disableNodeJS --retireJsUrl http://127.0.0.1:8000/jsrepository/ --out report/torchmetrics-0.7.0-py3-none-any.html
[INFO] Checking for updates
[INFO] Skipping NVD check since last check was within 4 hours.
[INFO] Skipping RetireJS update since last update was within 24 hours.
[INFO] Check for updates complete (383 ms)
[INFO] 

Dependency-Check is an open source tool performing a best effort analysis of 3rd party dependencies; false positives and false negatives may exist in the analysis performed by the tool. Use of the tool and the reporting provided constitutes acceptance for use in an AS IS condition, and there are NO warranties, implied or otherwise, with regard to the analysis or its use. Any use of the tool and the reporting provided is at the user’s risk. In no event shall the copyright holder or OWASP be held liable for any damages whatsoever arising out of or in connection with the use of this tool, the analysis performed, or the resulting report.


   About ODC: https://jeremylong.github.io/DependencyCheck/general/internals.html
   False Positives: https://jeremylong.github.io/DependencyCheck/general/suppression.html

💖 Sponsor: https://github.com/sponsors/jeremylong


[INFO] Analysis Started
[INFO] Finished File Name Analyzer (0 seconds)
[INFO] Finished Python Distribution Analyzer (0 seconds)
[INFO] Finished Dependency Merging Analyzer (0 seconds)
[INFO] Finished Version Filter Analyzer (0 seconds)
[INFO] Finished Hint Analyzer (0 seconds)
[INFO] Created CPE Index (1 seconds)
[INFO] Finished NPM CPE Analyzer (1 seconds)
[INFO] Created CPE Index (2 seconds)
[INFO] Finished CPE Analyzer (2 seconds)
[INFO] Finished False Positive Analyzer (0 seconds)
[INFO] Finished NVD CVE Analyzer (0 seconds)
[INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
[INFO] Finished Dependency Bundling Analyzer (0 seconds)
[INFO] Analysis Complete (4 seconds)
[INFO] Writing report to: /Users/user/PycharmProjects/Tools/scanners/odc/report/torchmetrics-0.7.0-py3-none-any.html

Process finished with exit code 0

**Comment by 31deR** [comment]
![Uploading image.png…]()

**Comment by 31deR** [comment]
<img width="400" alt="image" src="https://user-images.githubusercontent.com/60350660/159712537-79642854-e7b1-4f7a-8710-caf6e9ddd3f1.png">

**Comment by 31deR** [comment]
<img width="400" alt="image" src="https://user-images.githubusercontent.com/60350660/159713240-50264aa0-165a-45c3-9010-15df41ebb5a3.png">

**Comment by aikebah** [comment]
Thanks for validating. I'll promote the draft-PR to a regular PR so that it can be included in the next release. Unfortunately we just missed the cut-off for 7.0.1.
