### ISSUE TITLE
.Net dependency-check report is missing vulnerable dependencies

### ISSUE THREAD

**Issue by sspizzirri** [dependency-check/DependencyCheck#4075]
Hi,
We finally made our job work and depedency-check is running, but we are with a few doubts about it.
Purposely injected some vulnerable dependencies to our demo project, and what we found out is that, while it's working, it isn't showing in the report all of them. However, using a dotnet tool to scan our code, shows all. 

The command we use is the following: 
dotnet list package --vulnerable

And here are some pictures of both reports:
![image](https://user-images.githubusercontent.com/48492915/153922995-970aee6b-788d-4e80-b574-66cf8f69303c.png)![image](https://user-images.githubusercontent.com/48492915/153923017-bff5b537-494c-448e-b4b4-0ae95cb03a57.png)

What can we do about it? Is there like a database with vulnerable dependencies to update?, Do we need to upgrade our dep-check version? 
Thanks in advance!

**Comment by jeremylong** [comment]
Do you have a sample project you can provide?
