### ISSUE TITLE
403 error from ossindex.sonatype.org

### ISSUE THREAD

**Issue by ScottDish** [dependency-check/DependencyCheck#4078]
**Describe the bug**
When running dependency check via gradle owasp plugin task, OSS Index Analyzer fails on first jar with below debug output. Subsequent jars appear to be analyzed without additional errors until spring-boot-starter-tomcat, which also fails to request component-reports with a 403. The overall analysis step fails.

**Version of dependency-check used**
The problem occurs using version 6.5.3 of the gradle plugin (cli, gradle plugin, maven plugin, etc.)

**Log file**
gist link: https://gist.github.com/ScottDish/f18c4205af6ca290ac719876ba3c48ac

**To Reproduce**
1. Go to 'project root dir'
2. Run ' ./gradlew --debug dependencyCheckAnalyze'
3. See error

**Expected behavior**
Complete analysis with no vulnerabilities found.

**Additional context**
Gradle 6.9.2 
Spring Boot 2.6.3
Problem appears related to network security (running this within a corporate network), but I can't determine the exact issue. I suspect that it might be a problem with SSL certificates, but can't find any certificates from sonatype that make this work. The issue seems to go away (analysis completes without any error) if I run from outside the corporate network.

**Comment by mprins** [comment]
How is an upstream server telling you "403 Forbidden" a bug in ODC? perhaps you are hitting rate limiting somewhere in your corp. network or at Sonatype

**Comment by ScottDish** [comment]
This might be a bug in ODC or it might not. I cannot tell what the problem is based on what I know or can see in the output. When running the dependency check via the plugin, the check fails and vaguely blames Sonatype. Running with --debug then shows a stacktrace indicating that the underlying cause of the failure is a 403 response from Sonatype. But "I" don't call Sonatype. ODC does that. My security team asked me to open an issue with ODC to find out if anything can be determined from there. So I did that. If the issue is something that needs to be configured on my end, I'll be happy to hear what that is and fix it. If it's something between ODC and Sonatype, then I assume someone else will take care of it.

**Comment by jeremylong** [comment]
You are likely hitting rate limiting from Sonatype. See https://github.com/sonatype-nexus-community/ossindex-gradle-plugin#:~:text=The%20token%20can%20be%20retrieved,settings%20page%20of%20the%20user.&text=com%20ossindexToken%3Def40752eeb642ba1c3df1893d270c6f9fb7ab9e1-,In%20your,gradle%20file%2C%20add%20the%20following.&text=The%20credentialed%20rate%20limit%20is,for%20up%20to%20128%20packages.

We likely need to add this link and info to the project and error message...

**Comment by nhumblot** [comment]
Hi, :wave: 

Based on https://issues.sonatype.org/browse/OSSRH-54803,

It looks like this is a more like a ban than a simple too many requests. Some IPs can be registered on a deny list by sonatype if there is an high amount of requests sent to sonatype.

@ScottDish, I suggest you to reach sonatype if you still face http 403 responses.

`core/src/main/java/org/owasp/dependencycheck/analyzer/OssIndexAnalyzer.java` already handle `429 Too Many Requests` responses with an `OSS Index rate limit exceeded` message but do not provide any specific information when getting a 403. I am going to work on submitting a PR displaying a message going this way.
