### ISSUE TITLE
[FP]: spring-security-core-5.5.4.jar CWE-862

### ISSUE THREAD

**Issue by waltervalentini** [dependency-check/DependencyCheck#4099]
### Package URl

pkg:maven/org.springframework.security/spring-security-core@5.5.4

### CPE

CWE-862: Missing Authorization

### ODC Integration

{"label"=>"Maven Plugin"}

### ODC Version

6.5.3

### Description

It started to been reported on 21-02-2022.

**Comment by aikebah** [comment]
Spring project raised the subject with Sonatype to get OSSINDEX fixed for this

**Comment by aikebah** [comment]
OSSIndex issue is https://github.com/OSSIndex/vulns/issues/249

**Comment by aikebah** [comment]
Resolved by the OSSIndex update to their new vulnerability database
