### ISSUE TITLE
Do you need .NET Core Runtime or SDK? 

### ISSUE THREAD

**Issue by rcooper85** [dependency-check/DependencyCheck#4100]
Hi, just wanted to know if you need the .NET Core SDK or Runtime to use the dotnet assembly analyzer?

**Comment by jeremylong** [comment]
Looking at the Dockerfile - looks like runtime:

https://github.com/jeremylong/DependencyCheck/blob/9682614da18349f01078f7ce4938a8cdf4b1e1ea/Dockerfile#L7

Note that with 7.0.0 we are upgrading to dotnet core 6.
