### ISSUE TITLE
Jenkins CPE found in empty project (With edited manifest)

### ISSUE THREAD

**Issue by Crazysabbath** [dependency-check/DependencyCheck#4113]
**Describe the bug**
When jenkins and release strings are in Manifest file, jekins CPE for release plugin is found.

**Version of dependency-check used**
Tested with 6.1.1 and 6.5.3

**To Reproduce**
1. Create simple java project without any dependencies
2. Build it
3. Edit Manifest in jar file and add: Build-Tag: jenkins-test release-1
4. cpe:2.3:a:jenkins:release: is present in report

**Expected behavior**
I would expect jenkins CPE to not be present. Or have I misunderstood how this works? 

**Additional context**
If instead of release, snapshot string is present, no cpe is found (I suppose snapshot plugin does not have vulnerabilities in jenkins, have not checked that)

**Comment by aikebah** [comment]
The behaviour you describe is expected given [how DependencyCheck works](https://jeremylong.github.io/DependencyCheck/general/internals.html)

The contents of the Build-Tag from your manifest get added as evidences (alongside other metadata) to try and derive the vendor/product that the jar represents. Upon searching for known CPEs it (wrongly) finds the jenkins release plugin as the best match for the evidences encountered in your project. (the full list of evidences encountered and considered you can find in the report)

**Comment by jeremylong** [comment]
@aikebah I wonder if we should allow the configuration of manifest entries to skip?

**Comment by aikebah** [comment]
@jeremylong Might be good to allow users to set additional entries not-yet excluded by default. 

Think such an additional skip would be more manageable than having to repeat all the already coded exclusions of manifest entries when all you need is one (or a few) more.

**Comment by Crazysabbath** [comment]
Thanks for the information. Such a skip indeed would be welcome. I suppose this can be closed.
