### ISSUE TITLE
Explanation for argument 'enableNexus' says it disables the Nexus analyzer

### ISSUE THREAD

**Issue by andham** [dependency-check/DependencyCheck#4114]
**Describe the bug**
The argument 'enableNexus' indicates that it will enable the Nexus analyzer. But the explanation text says that it disables it. Which is it?

**Version of dependency-check used**
6.5.3

**Expected behavior**
The name and the explanation should be consistent. As the argument is called enableXXX, I assume that it is disabled by default and that the argument will enable it.

**Comment by aikebah** [comment]
Where did you spot this. I thought the CLI configuration page would be off, but that clearly states

>Sets whether the Nexus Analyzer will be used (requires Nexus v2 or Pro v3). You can configure the Nexus URL to utilize an internally hosted Nexus server.

**Comment by aikebah** [comment]
Nevermind... already spotted it... the CLI argument is off indeed

https://github.com/jeremylong/DependencyCheck/blob/b00dd86b1799996be779ab22e9e3ee97c23ce3c6/cli/src/main/java/org/owasp/dependencycheck/CliParser.java#L455
