### ISSUE TITLE
Dependency check resulting in a failure because of a database connection issue

### ISSUE THREAD

**Issue by sushanth-krishnaswamy** [dependency-check/DependencyCheck#4125]
**Describe the bug**
The owasp dependency check is failing for the `latest` image ( pointing to `7.0.0` at the time of the issue ). The error logs state that it is not being able to connect to the database. 

**Version of dependency-check used**
The problem occurs on the image tagged `latest` which , during the time of the issue, pointed to `7.0.0`. Reverting to `6.5.3` seemed to resolve the issue. 

**Log file**

<img width="1423" alt="Screen Shot 2022-02-28 at 1 29 01 PM" src="https://user-images.githubusercontent.com/23304976/156038490-6ee09fc9-5f57-4d4d-8a1c-0884a3fb9bed.png">

**To Reproduce**
1. Setup the owasp dependency checks using the docker image as shown here https://github.com/jeremylong/DependencyCheck#docker . 
2. Issue occurs when `DC_VERSION` is `7.0.0` ( at that time, `latest` ). The issue is resolved when `DC_VERSION` is `6.5.3` .

**Comment by mprins** [comment]
Did you follow the release notes? https://github.com/jeremylong/DependencyCheck/releases/tag/v7.0.0

**Comment by paksydavid** [comment]
I had the same issue and I also did not read the release notes. But I can confirm that running a purge (in my case the `dependencyCheckPurge` Gradle task) and then running the dependency check again was working.
