### ISSUE TITLE
NVD CVE load for 2003, 2004, etc?

### ISSUE THREAD

**Issue by colezlaw** [dependency-check/DependencyCheck#413]
When my NVD CVE updater does a full update, it only pulls for the following years (or so it seems):
2002, 2007, 2009, 2010, 2011, 2012, 2013, 2014, 2015.

If I look at the database, it does indeed have CVE's for 2003, 2004, 2005, 2006, and 2008 - but the log never shows that those get downloaded.

Not really an issue, but I'm very puzzled.

**Comment by colezlaw** [comment]
Eh - nevermind. If I delete the database and start over, it does indeed download those. I guess those were just the ones that were up-to-date.

**Comment by jeremylong** [comment]
I've noticed similiar things. The database is being kept up to date; there just may not be changes to a few of the files so there is no need to re-download them.
