### ISSUE TITLE
[FP]: mariadb-java-client

### ISSUE THREAD

**Issue by latenightwreck** [dependency-check/DependencyCheck#4143]
### Package URl

pkg:maven/org.mariadb.jdbc/mariadb-java-client@3.0.3

### CPE

cpe:2.3:a:mariadb:mariadb:3.0.3:*:*:*:*:*:*:*

### ODC Integration

{"label"=>"Gradle Plugin"}

### ODC Version

7.0.0

### Description

It seems the CPE is hitting for the actual MariaDB, where this jar is for connecting to a Maria/MySQL database.

**Comment by mprins** [comment]
duplicates #4133 (apart from the version number which is probably irrelevant for the solution)

**Comment by latenightwreck** [comment]
> duplicates #4133 (apart from the version number which is probably irrelevant for the solution)

100% does. My issue searching failed me then ;_; The can be closed then! Thank you!
