### ISSUE TITLE
Database needs to be isolated to the version of the Maven plugin

### ISSUE THREAD

**Issue by awhitford** [dependency-check/DependencyCheck#416]
I have several projects.  Some projects may still reference version 1.3.1 and I changed one project (experimentally) to use 1.3.2.

Once I build the project referencing plugin version 1.3.2, it upgrades the database. Now I can't build the project(s) that reference 1.3.1 anymore because it tells me that the database version is different or something. 

This strikes me as a major _design flaw_. Changing the `dependency-check-data` directory to be organized by version seems like the logical solution.  It would appear that simply removing `data.directory` from `mojo.properties` may solve the issue.

**Comment by jeremylong** [comment]
We can separate the data directories based on the database schema version (currently 3.0). This should be an easy fix.

**Comment by jeremylong** [comment]
This will be included in the 1.3.3 release.
