### ISSUE TITLE
Error when creating a report for a Python-Project

### ISSUE THREAD

**Issue by morzan1001** [dependency-check/DependencyCheck#4169]
Hi I would like to have a python project of mine checked with the dependencychecker. Unfortunately, when generating the report, an error always occurs and I haven't found a way to determine a little more precisely where the problem is. The output of my gitlab runner that does the check looks like this: 

```
[INFO] Analysis Started
[INFO] Finished Archive Analyzer (0 seconds)
[INFO] Finished File Name Analyzer (0 seconds)
[INFO] Finished Assembly Analyzer (4 seconds)
[INFO] Finished Python Distribution Analyzer (0 seconds)
[INFO] Finished Python Package Analyzer (4 seconds)
[INFO] Finished pip Analyzer (0 seconds)
[INFO] Finished Autoconf Analyzer (0 seconds)
[INFO] Finished PE Analyzer (0 seconds)
[INFO] Finished Dependency Merging Analyzer (0 seconds)
[INFO] Finished Version Filter Analyzer (0 seconds)
[INFO] Finished Hint Analyzer (0 seconds)
[INFO] Created CPE Index (1 seconds)
[INFO] Finished NPM CPE Analyzer (1 seconds)
[INFO] Created CPE Index (1 seconds)
[INFO] Finished CPE Analyzer (3 seconds)
[INFO] Finished False Positive Analyzer (0 seconds)
[INFO] Finished NVD CVE Analyzer (0 seconds)
[INFO] Finished RetireJS Analyzer (0 seconds)
[INFO] Finished Sonatype OSS Index Analyzer (8 seconds)
[INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
[INFO] Finished Dependency Bundling Analyzer (0 seconds)
[INFO] Analysis Complete (23 seconds)
[INFO] Writing report to: /builds/<projectname>/reports/dependency-check-report.json
[ERROR] Error generating the report for <projectname>
```

I am using the latest Docker image and as a call I used the following: 

`/usr/share/dependency-check/bin/dependency-check.sh --project <projectname> --out reports/ --format JSON --format HTML --scan . --enableExperimental --failOnCVSS 7`

I hope someone of you may be able to help me, thank you

**Comment by aikebah** [comment]
Best way to further investigate your issue is using increased logging to a logfile. The `--log` as listed in the cli configuration documentation. https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html

**Comment by morzan1001** [comment]
Hi, thanks for the tip with the logs, i tried some more and the problem was finally that the folder the dependency scanner should write to was created by another job before and since the dependency scanner works with its own user, it didn't have the permissions to put its results in that folder. I fixed that now. Thanks again for the quick reply
