### ISSUE TITLE
dependency-check-maven encrypt databasePassword

### ISSUE THREAD

**Issue by edgedalmacio** [dependency-check/DependencyCheck#417]
Reference: http://stackoverflow.com/questions/12299181/use-encrypted-data-in-a-maven-pom

**Comment by jeremylong** [comment]
Thanks for pointing this out - I'll include this in the next release.  For my notes, a code example is found [here](https://github.com/mojohaus/sql-maven-plugin/blob/master/src/main/java/org/codehaus/mojo/sql/SqlExecMojo.java#L857).

**Comment by jeremylong** [comment]
This has been implemented in the 1.3.4-SNAPSHOT and will be included in the next release.

Thanks again for pointing this feature out!

--Jeremy
