### ISSUE TITLE
Gradle 7.4 does not work with DepCheck 7.0.0

### ISSUE THREAD

**Issue by rschnitk** [dependency-check/DependencyCheck#4181]
**Describe the bug**
The combination of Gradle 7.4 and DepCheck 7.0.0 does not work.

**Version of dependency-check used**
The problem only occurs using version 7.0.0 with Gradle 7.4. 
Gradle 7.3.x is ok. Or Gradle 7.4 plus DepCheck 6.5.3 is ok.

**Log file**
Could not find method sha256Checksum() for arguments [my-app:1.1.1] on task ':dependencyCheckAnalyze' of type org.owasp.dependencycheck.gradle.tasks.Analyze.

**To Reproduce**
1. Upgrade to Gradle Wrapper 7.4 or 7.4.1
2. Run Task dependencyCheckAnalyze
3. See error

**Expected behavior**
Fix sha256Checksum() usage

**Comment by jeremylong** [comment]
See https://github.com/dependency-check/dependency-check-gradle/issues/251 - will be fixed in 7.0.1 which should be released shortly.
