### ISSUE TITLE
Handle errors in component-reports more gracefully

### ISSUE THREAD

**Issue by sithmein** [dependency-check/DependencyCheck#4202]
Although we are using the Sonartype OSS index with authentication we are still getting the infamous "Failed to request component-reports" error frequently (several times a week). As this completely fails the build this is quite annoying for our developers. If I understand correctly, the data received from the OSS index is cached on disk. Could the Maven plug-in be improved such that it uses the cached data in case the OSS index returns in error (for whatever reason) - even if the cached files are outdated? Ideally this option is configurable so that the current behaviour is retained. If this new option is enabled a warning would be issued instead of an error and the check continues with the currently available data.
I would be willing to work on a PR if you believe this option makes sense and are willing to include it.

**Comment by ryandutton** [comment]
This is something I would also be interested in. As another suggestion, would it be plausible to have a retry option if an analyser fails, helping this particular bug where the request times out before it can be fulfilled?

**Comment by sithmein** [comment]
Thanks for applying the changes so quickly!
Is there a rough estimate when they will be part of a release? Currently we are using an internal build but we would like to get back to the official version as soon as possible.
