### ISSUE TITLE
Andriod dependencies

### ISSUE THREAD

**Issue by seanboylan** [dependency-check/DependencyCheck#421]
I am using the Dependency checker CLI to check a gradle based project for an android client build. I first ran the full build and then ran the dependency checker. I don't think it find all the correct dependencies.
Would I have more success using the gradle plugin?

**Comment by jeremylong** [comment]
Yes, using a build plugin, either Maven or Gradle, will do a better job of finding the dependencies. This is especially true for dependencies that might be `provided` or shaded in the resulting code. These build plugins actually look at the dependencies defined in the pom.xml or gradle build.

**Comment by seanboylan** [comment]
Hi Jeremy - thanks for the feedback. I have plumbed in the gradle plugin. 
buildscript {
repositories {
mavenLocal()
mavenCentral()
maven {url snapshotRepo}
maven {url releaseRepo}
}
dependencies {
classpath 'com.android.tools.build:gradle:1.3.1'
classpath 'com.synchronoss.gradle:jira-report-plugin:1.0.6'
classpath 'com.jakewharton.sdkmanager:gradle-plugin:0.12.0'
classpath 'com.synchronoss.gradle-plugins:gradle-plugins-all:2.1.10'
classpath 'org.owasp:dependency-check-gradle:1.3.3'
}
}

apply plugin: 'org.owasp.dependencycheck'

However when I run './gradlew dependencyCheck --info' I get no dependencies found.
./gradlew assemble builds all the apk correctly.

If I run /gradlew :clients:syncdrive:dependencies I get a full dependency tree with the cpe's correctly listed

Any suggestions. 
Regards
Sean

**Comment by jeremylong** [comment]
Any chance you could provide a complete build.gradle file? What you provided does not specify any dependencies.

--Jeremy
