### ISSUE TITLE
Option to change NVD data cache path

### ISSUE THREAD

**Issue by pelletier197** [dependency-check/DependencyCheck#4214]
**Is your feature request related to a problem?**
Yes. I am working in Gitlab CI, and I am trying to put cache the the dependency-check cache data for my CI. Since we have multiple pipelines, I am under impression that we get rate-limited by the website dependency-check uses to get the CVEs, which causes pipelines to fail many times a day randomly. 

What I want to do is to cache the NVD data in my pipeline, so that it doesn't re-fetch them all the time.

**Describe the solution you'd like**
I haven't found anything documented that indicates there is a way to change the cache data path. If there is already such thing, feel free to close the issue and just refer me to the documentation.

Ideally, I would like the ability to provide an alternative cache path to the default one. In docker, the cache path is `/usr/share/dependency-check/data`. 

**Describe alternatives you've considered**
For now, I've managed to do a work-around by copying the cache before the step into the project, and then restoring that do `/usr/share/dependency-check/data` before running dependency-check. It works, but it's a little inconvenient.

**Comment by albuch** [comment]
There are several ways to optimize for rate limiting:
1. Use a prebuilt image in your pipeline that e.g. is built nightly and only updates the database on build. This greatly reduces the amount of requests that your network is sending to NVD. You could adapt the same steps for your Gitlab CI pipelines as the Github Action: https://github.com/dependency-check/Dependency-Check_Action (this is the nightly build job for the image: https://github.com/dependency-check/DependencyCheck_Builder) 
2. Create a local mirror of the NVD feeds with https://github.com/stevespringett/nist-data-mirror and cache your local database in your pipelines
3. Use a central database for all pipelines and don't update the database form the pipelines but with one schedule/cron job. This comes with downsides as well, as this would only work if all pipelines use the same major version of dependency check.

From my experience option 2) is sufficient. We don't get any rate limiting issues anymore after implementing this. Option 1 would include other data sources as well like retireJS and OSSIndex, however I haven't come across rate limiting issues there yet form our pipelines.

You can find more details as well in the docs: https://jeremylong.github.io/DependencyCheck/data/index.html

**Comment by pelletier197** [comment]
Thank you for your answer. We'll check if we can implement a daily build of a docker image, that's a good idea we didn't think about.

Although, I still feel like the ability of changing the cache path would be nice (either through env variable or argument). Do you think it can still be a possibility?

**Comment by albuch** [comment]
I'm not 100% sure and can't check as I'm currently on a different computer without any projects with DC but I think to remember the `dataDirectory` includes the default database directy along with all downloads from NVD, retire.js etc. 
For the Maven Plugin you can find the option in the Advanced Configuration section: https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html 
Similiar configuration parameter exists for all other build integrations and the CLI.

**Comment by albuch** [comment]
Hi @pelletier197,
just double checked on my other computer: the before mentioned setting `dataDirectory` is what you are looking for, it includes all downloads (NVD, OSSIndex, retrie.js) along with the default H2 database

**Comment by pelletier197** [comment]
You are absolutely right. I totally missed that configuration after looking multiple times. In this case, I'll just close the issue and use this. I'll open again if I case an issue.

Thank you very much!

**Comment by carlin-q-scott** [comment]
The CLI argument is '--data dataDirectoryPath'.
https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html
