### ISSUE TITLE
[FP]: netty-incubator-codec-classes-quic identified as netty:netty

### ISSUE THREAD

**Issue by stefanscheidt** [dependency-check/DependencyCheck#4229]
### Package URl

pkg:maven/io.netty.incubator/netty-incubator-codec-classes-quic@0.0.25.Final

### CPE

`cpe:2.3:a:netty:netty:0.0.25:*:*:*:*:*:*:*`

### ODC Integration

{"label"=>"Maven Plugin"}

### ODC Version

7.0.0

### Description

It may well be the case that other netty-incubator artifacts are also affected.

We could fix our issues with this suppression:

```
    <suppress>
        <notes><![CDATA[CPE disputed for netty-incubator-*]]></notes>
        <gav regex="true">^io\.netty\.incubator:netty\-incubator\-.*:.*$</gav>
        <cpe>cpe:/a:netty:netty</cpe>
    </suppress>
```

**Comment by aikebah** [comment]
Will be solved by #4193
