### ISSUE TITLE
Add Oracle DB Support

### ISSUE THREAD

**Issue by rrialq** [dependency-check/DependencyCheck#423]
I use Oracle DB for store data, so I need the Oracle DB support.
@jeremylong
I've forked the project and I've create the sql and properties files to add this support to OracleDB.
I am testing now, but I think in a few days I will do the pull request, if you think it is interesting.

**Comment by jeremylong** [comment]
That would be awesome!

**Comment by kaimago** [comment]
@rrialq that would be great. We are using Oracle Db, too

**Comment by jeremylong** [comment]
Support has been added to the 1.3.5-SNAPSHOT via PR #447.  This will be included in the next release.
