### ISSUE TITLE
Multi-version support on the same machine (prior to and after 7.0) with the same Gradle cache

### ISSUE THREAD

**Issue by yonyes** [dependency-check/DependencyCheck#4244]
**Is your feature request related to a problem? Please describe.**
We have a single machine that builds and tests all of our services before they are merged into the main branch (aka Pull Requests). Since there are many services, we can't upgrade them all at once. The last version (7.0) introduced breaking changes, and we can't simply use the suggestion of reloading the database, as parts of the services still use the version prior to 7.0. 

**Describe the solution you'd like**
Provide an option to configure the DB version, or support multiple versions on the same machine (using the same Gradle cache).

**Comment by jeremylong** [comment]
This is already possible. To accomplish this you need to specify the data directory. See the advanced configuration here: https://jeremylong.github.io/DependencyCheck/dependency-check-gradle/configuration.html
