### ISSUE TITLE
Command Line Version 7.0.0 Dep Check - Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta

### ISSUE THREAD

**Issue by yettsyjk** [dependency-check/DependencyCheck#4248]
Hi, 
What is the way to repair version 7.0.0 for Command Line when experiencing error: Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta?
Assumptions: 
1. We confirmed Windows environment variable PATH matched PATH of \bib directory
2. We confirmed certs (https://jeremylong.github.io/DependencyCheck/) for keytool
3. We confirmed active version of Java installed on local machine
4. After running command 'dependency-check.bat -version', we confirmed 7.0.0 installed on local machine
5. After running command for project scan the following result prints: Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta
[ERROR] Unable to continue dependency-check analysis.
[ERROR] One or more fatal errors occurred
[ERROR] Unable to download meta file: Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta
[ERROR] No documents exist
6. We reviewed 'See https://github.com/jeremylong/DependencyCheck/issues/3682#issuecomment-933343804', and result is persistent
Thank you in advance for your assistance.

**Comment by jeremylong** [comment]
Please provide the full log file (i.e. using `--log odc.log`.

**Comment by yettsyjk** [comment]
We uninstalled and installed 7.0.4 version CLI, no issues. Please close this https://github.com/jeremylong/DependencyCheck/issues/4248 thanks
