### ISSUE TITLE
Gradle Plugin 7.0.1 - Could not find matching constructor for: java.io.File(File)

### ISSUE THREAD

**Issue by rewgoes** [dependency-check/DependencyCheck#4253]
**Describe the bug**
I can't run the scan after upgrading to version 7.0.x

**Version of dependency-check used**
The problem occurs using version 7.0.0 and 7.0.1 of the gradle plugin

**Log file**
Error: Could not find matching constructor for: java.io.File(File)
Log files:
https://gist.github.com/rewgoes/e04eb1c2bedccfeefd8fd8e5f53ebdd1
https://gist.github.com/rewgoes/01a39d30062cada20d1a3256287c9066

**To Reproduce**
Just run ./gradlew dependencyCheckAnalyze --info

**Expected behavior**
It should not fail

**Comment by ghost** [comment]
I also confirm this on Gradle 7.2 and 7.4.1 using Dependency Check 7.0.0 and 7.0.1 using the dependencyCheckAggregate task.

As a workaround, I downgraded Dependency Check to 6.5.3

**Comment by j-lebek** [comment]
Same for me: Gradle 7.4.1 and dependency-check 7.0.1
```
* What went wrong:
Execution failed for task ':dependencyCheckAggregate'.
> Could not find matching constructor for: java.io.File(File)
```
Just updated from dependency-check 6.5.3 to 7.0.1 yesterday. (Needed to skip 7.0.0 due to [#247](https://github.com/dependency-check/dependency-check-gradle/issues/247))

**Comment by chadlwilson** [comment]
This is a dupe of https://github.com/dependency-check/dependency-check-gradle/issues/258 reported against the plugin rather than the core project. The bug is on the plugin rather than the core I believe.
