### ISSUE TITLE
The EngineVersionCheck.shouldUpdate() deletes the value of the CURRENT_ENGINE_RELEASE

### ISSUE THREAD

**Issue by rrialq** [dependency-check/DependencyCheck#426]
When the value of the CURRENT_ENGINE_RELEASE property is the same as the value of the updateToVersion the method updates the property with the empty string value.
This seems no sense, since this property is used to compare against the last release readed from web.
The problem is that the value is overwritten with an empty string, because when no new version is available the code is executed one of twice.
1. When properties does not match then CURRENT_ENGINE_RELEASE property is updated.
2. Next time the properties match, so the CURRENT_ENGINE_RELEASE property is overwritten with the empty string (I think has no sense).
3. Next time properties does not match, so CURRENT_ENGINE_RELEASE property is updated.

In OracleDB there is no difference between empty strings and null: it stores a null string. After that when the plugin read the records in properties table and stores its values in HashMap it fails with a NullPointerException.

**Comment by jeremylong** [comment]
This should now be resolved in the current snapshot.
