### ISSUE TITLE
How to disable dependency-check plugin on certain build?

### ISSUE THREAD

**Issue by patpatpat123** [dependency-check/DependencyCheck#4266]
Hello Jeremy, hello Team,

First of all, since this is my first post, I wanted to say a big thanks for this project.
This dependency check helped me fixed some nasty CVE, as well as preventing some to go to prod. Many thanks.

I have a question please. **How to disable dependency-check please?**
While this seems like a noob question, (and maybe it is 😛) I would like to explain.

During our development cycle, we commit code and regularly perform CI/CD on our repo.
The CI/CD tool is _cloud base_, meaning it is an entire new instance of CI/CD, _every_ time we commit, even a one liner code.

And we have this in the pom file:

```
 <plugin>
                <groupId>org.owasp</groupId>
                <artifactId>dependency-check-maven</artifactId>
                <version>7.0.1</version>
                <configuration>
                    <assemblyAnalyzerEnabled>false</assemblyAnalyzerEnabled>
                    <formats>
                        <format>html</format>
                        <format>json</format>
                    </formats>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

With that, every time there is a build, the build takes very very long, due to this phase:

```
[INFO] NVD CVE requires several updates; this could take a couple of minutes.
         [INFO] Download Started for NVD CVE - 2002
         [INFO] Download Complete for NVD CVE - 2002  (171 ms)
         [INFO] Processing Started for NVD CVE - 2002
         [INFO] Processing Complete for NVD CVE - 2014  (7844 ms)
         [INFO] Download Started for NVD CVE - 2016
         [INFO] Download Complete for NVD CVE - 2016  (456 ms)
         [INFO] Processing Started for NVD CVE - 2016
         [INFO] Processing Complete for NVD CVE - 2015  (6070 ms)
         [INFO] Download Started for NVD CVE - 2017
         [INFO] Download Complete for NVD CVE - 2017  (459 ms)
         [INFO] Processing Started for NVD CVE - 2017
         [INFO] Processing Complete for NVD CVE - 2016  (6895 ms)
         [INFO] Download Started for NVD CVE - 2018
         [INFO] Download Complete for NVD CVE - 2018  (406 ms)
         [INFO] Processing Started for NVD CVE - 2018
         [INFO] Processing Complete for NVD CVE - 2017  (8320 ms)
         [INFO] Download Started for NVD CVE - 2019
         [INFO] Download Complete for NVD CVE - 2019  (377 ms)
         [INFO] Processing Started for NVD CVE - 2019
         [INFO] Processing Complete for NVD CVE - 2018  (7276 ms)
         [INFO] Download Started for NVD CVE - 2020
         [INFO] Download Complete for NVD CVE - 2020  (345 ms)
         [INFO] Processing Started for NVD CVE - 2020
         [INFO] Processing Complete for NVD CVE - 2019  (6935 ms)
         [INFO] Download Started for NVD CVE - 2021
         [INFO] Download Complete for NVD CVE - 2021  (348 ms)
         [INFO] Processing Started for NVD CVE - 2021
         [INFO] Download Started for NVD CVE - 2022
         [INFO] Download Complete for NVD CVE - 2022  (154 ms)
         [INFO] Processing Started for NVD CVE - 2022
         [INFO] Processing Complete for NVD CVE - 2020  (8715 ms)
         [INFO] Processing Complete for NVD CVE - 2022  (1183 ms)
         [INFO] Processing Complete for NVD CVE - 2021  (8566 ms)
         [INFO] Download Started for NVD CVE - Modified
         [INFO] Download Complete for NVD CVE - Modified  (131 ms)
         [INFO] Processing Started for NVD CVE - Modified
         [INFO] Processing Complete for NVD CVE - Modified  (1066 ms)
         [INFO] Begin database maintenance
         [INFO] Updated the CPE ecosystem on 124178 NVD records
         [INFO] Removed the CPE ecosystem on 3507 NVD records
         [INFO] Cleaned up 9 orphaned NVD records
         [INFO] End database maintenance (11540 ms)
         [INFO] Begin database defrag
         [INFO] End database defrag (4159 ms)
         [INFO] Check for updates complete (115413 ms)
```

We literally time each and every step of the build, and we are sure this is the step taking most of the time.
Again, since our CI/CD solution is cloud based, this happens 100% of the time.
We made sure, because when we run the same on a local machine, this happen the first time, and after, will not happen (maybe some kind of ache mechanism).

On the other hand, at the end of day, we will and do run a giant CI/CD pipeline, where we run tons of static analysis, to promote whatever got committed during the day. At this point of time, dependency-check is truly a magnificent tool.

Therefore, during the day, what we end up doing is to comment out or remove the dependency plugin, so the builds remains fast.
Then, at the end of day, just before the big EOD CI/CD pipeline, we un-comment the plugin, and look forward to seeing the report.

This method of doing is definitely not smart, and I believe we are doing it the wrong way.

Therefore, my questions, 

- What is the correct way please?
- How to prevent this very long _(download+update)_ during our cloud based ephemeral CI/CD?
- How to disable the plugin, without us commenting out the plugin during the day when we commit, and later un commenting before the EOD big analysis?

Thank you in advanced for your time, and again, wanted to say thanks for this great project.

**Comment by jeremylong** [comment]
You can solve this problem a couple of ways:

1. Cache the data directory between executions.
2. Use a profile and put the ODC maven plugin in the profile and only activate it when you are running the final check.

**Comment by Janpopan** [comment]
@patpatpat123 

https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html

as @jeremylong writes, you could skip the whole plugin with the setting of the <skip> flag.

You could also use the database approach.
One project your OWASP DB every day an all other projects use this database. The setup is also described in the link

**Comment by patpatpat123** [comment]
Hello,

Thank you both for your clear write up.
On my end, the CI solution is very ephemeral. Meaning, one commit will spin a build in Azure, another build will spin a build in Google, another build in our own Jenkins, etc, so migrating the database every time seems hard.

With that said, the solution with the profile, or the flag seems to be the solution.
Wanted to say thanks again for the pointers, and wishing you a good day.
