### ISSUE TITLE
Internal dependencies mis-identified

### ISSUE THREAD

**Issue by milyas-salik** [dependency-check/DependencyCheck#4283]
Dear @jeremylong ,

I have integrated the OWASP plugin as a task in my SonarQube Azure CI. In the results, I found that it displays the vulnerabilities for the DLLs which are internal to us, and for those whose part of the text is matching with the text of the 3rd party DLLs that have known vulnerabilities.

Kindly fix it if it's a known issue, we are using version 6.5.3.

<img width="773" alt="image" src="https://user-images.githubusercontent.com/79843909/160565149-bd9bb093-73c9-4c5d-8a45-dde443522224.png">

You can see in teh above image, we are not using elasticsearch.dll, ScottBrady.IdentifyModel.dll but the issue pops up on other DLLs due to matching text.

**Comment by jeremylong** [comment]
Please consider reading a out how [dependency-check works](https://jeremylong.github.io/DependencyCheck/general/internals.html), [how to read the report](https://jeremylong.github.io/DependencyCheck/general/thereport.html), and most important for you [how to suppress false positives](https://jeremylong.github.io/DependencyCheck/general/suppression.html).

If these are internal DLLs - the easiest solution is to generate the HTML report and then create suppression rules.
