### ISSUE TITLE
Virus warning on check

### ISSUE THREAD

**Issue by somera** [dependency-check/DependencyCheck#4284]
**Describe the bug**
With 7.01 and 7.0.2 I got virus warning.

![image](https://user-images.githubusercontent.com/8334250/160587086-a752bb49-6cd0-4840-bdbd-18fed3fa1023.png)

Can anybody confirm this?

**Version of dependency-check used**
7.0.1, 7.0.2

**Comment by jeremylong** [comment]
1. what appears to be flagged is a data file that is downloaded from NVD.
2. the JSON file likely contains a text string for a recent vulnerability that your AV is picking up.

**Comment by somera** [comment]
> 1. what appears to be flagged is a data file that is downloaded from NVD.
> 2. the JSON file likely contains a text string for a recent vulnerability that your AV is picking up.

1. Yes
2. Yes, but 1-2 weeks ago it works fine. I can't reconfigure the AV software in this case. I will take a look on this.

**Comment by somera** [comment]
@jeremylong after update the NVD's and upgrade to 7.0.3 the virus warning is gone.
