### ISSUE TITLE
Make possible to see suppressed files in a seperate suppressed list

### ISSUE THREAD

**Issue by Grimoren** [dependency-check/DependencyCheck#4292]
**Is your feature request related to a problem? Please describe.**
Not necessarily a problem but there is some concern around suppressing too much. Would like to able to see what is suppressed, if we have concerns about suppressing actual issues. 

**Describe the solution you'd like**
Possibly make the suppressed vulnerabilities section expandable showing the suppressed vulnerabilities. 
**Describe alternatives you've considered**
No alternatives

**Additional context**

**Comment by aikebah** [comment]
The HTML report already has this - all the way at the bottom is a section on the suppressed vulnerabilities (collapsed by default)

**Comment by jeremylong** [comment]
The XML and JSON reports also contain the suppressed vulnerabilities.
