### ISSUE TITLE
Does --exclude for CLI work inside of archives?

### ISSUE THREAD

**Issue by lweitzel01** [dependency-check/DependencyCheck#4323]
All,

I am trying to use the --exclude option to ignore certain jar files.   However, it appears that the exclude pattern is not being applied to files inside the war file.

As a test, I used --exclude **/*.jar.  This excluded all jar files in the directory, but still processed that jar files inside the war file.

Is there a way to make the --exclude pattern also work inside archives??

**Comment by jeremylong** [comment]
No - the exclude argument could only be used to exclude the entire WAR, not just files inside the WAR. You would have to explode the WAR in order to exclude specific JAR files contained within.
