### ISSUE TITLE
Please add debug options to dependency resolution

### ISSUE THREAD

**Issue by bodhi-one** [dependency-check/DependencyCheck#4337]
We have a maven project which is using the dependency-check-maven plugin.  Without doing any code changes on our side to this project we started failing with this error message:

12:53:33  [ERROR] Failed to execute goal org.owasp:dependency-check-maven:7.0.4:check (default) on project someProjectJarWeMaintain: One or more exceptions occurred during dependency-check analysis: One or more exceptions occurred during analysis:
12:53:33  [ERROR] 	DependencyNotFoundException: Expected dependency not found in resolved artifacts for dependency org.slf4j:slf4j-api:jar:1.7.25:compile of project-artifact someProjectJarWeMaintain
12:53:33  [ERROR] 	DependencyNotFoundException: Expected dependency not found in resolved artifacts for dependency org.apache.maven:maven-settings:jar:2.0.6:compile of project-artifact someProjectJarWeMaintain
12:53:33  [ERROR] 	DependencyNotFoundException: Expected dependency not found in resolved artifacts for dependency org.codehaus.plexus:plexus-utils:jar:1.4.2:compile of project-artifact someProjectJarWeMaintain
12:53:33  [ERROR] 	DependencyNotFoundException: Expected dependency not found in resolved artifacts for dependency org.apache.maven:maven-plugin-registry:jar:2.0.6:compile of project-artifact someProjectJarWeMaintain
12:53:33  [ERROR] 	DependencyNotFoundException: Expected dependency not found in resolved artifacts for dependency org.apache.maven:maven-plugin-api:jar:2.0.6:compile of project-artifact someProjectJarWeMaintain
12:53:33  [ERROR] 	DependencyNotFoundException: Expected dependency not found in resolved artifacts for dependency org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-9-stable-1:compile of project-artifact someProjectJarWeMaintain
12:53:33  [ERROR] 	DependencyNotFoundException: Expected dependency not found in resolved artifacts for dependency org.apache.maven:maven-repository-metadata:jar:2.0.6:compile of project-artifact someProjectJarWeMaintain
12:53:33  [ERROR] 	DependencyNotFoundException: Expected dependency not found in resolved artifacts for dependency classworlds:classworlds:jar:1.1-alpha-2:compile of project-artifact someProjectJarWeMaintain
12:53:33  [ERROR] 	DependencyNotFoundException: Expected dependency not found in resolved artifacts for dependency org.apache.maven:maven-model:jar:2.0.6:compile of project-artifact someProjectJarWeMaintain
12:53:33  [ERROR] 	DependencyNotFoundException: Expected dependency not found in resolved artifacts for dependency org.apache.maven:maven-project:jar:2.0.6:compile of project-artifact someProjectJarWeMaintain
12:53:33  [ERROR] 	DependencyNotFoundException: Expected dependency not found in resolved artifacts for dependency org.apache.maven:maven-artifact:jar:2.0.6:compile of project-artifact someProjectJarWeMaintain
12:53:33  [ERROR] 	DependencyNotFoundException: Expected dependency not found in resolved artifacts for dependency org.apache.maven.wagon:wagon-provider-api:jar:1.0-beta-2:compile of project-artifact someProjectJarWeMaintain
12:53:33  [ERROR] 	DependencyNotFoundException: Expected dependency not found in resolved artifacts for dependency org.apache.maven:maven-profile:jar:2.0.6:compile of project-artifact someProjectJarWeMaintain
12:53:33  [ERROR] 	DependencyNotFoundException: Expected dependency not found in resolved artifacts for dependency xml-resolver:xml-resolver:jar:1.2:compile of project-artifact someProjectJarWeMaintain
12:53:33  [ERROR] 	DependencyNotFoundException: Expected dependency not found in resolved artifacts for dependency org.apache.maven:maven-artifact-manager:jar:2.0.6:compile of project-artifact someProjectJarWeMaintain
12:53:33  [ERROR] 	DependencyNotFoundException: Expected dependency not found in resolved artifacts for dependency stax:stax-api:jar:1.0.1:compile of project-artifact someProjectJarWeMaintain
12:53:33  [ERROR] -> [Help 1]
12:53:33  [ERROR] 

This issue started occurring while we had been on dependency-check-maven version 6.5.3 for some time (no issues here a few weeks ago) and this same issue is still present in version 7.0.4.  We have been building this project previously without issues.

In order to get around this error we had to add each of these above dependencies to our project pom.xml

Using mvn dependency:tree on our 'someProjectJarWeMaintain' we are not able to see any conflicting dependencies as listed above.  In fact for many entries such as plexus-utils, we do not refer to this dependency explicitly anywhere in of the other projects we maintain which are dependencies of this project which is failing.   We are able to build many other of our projects which do not have this error.

For this case it would be extremely helpful if there was a debug/diagnostic option for dependency-check-maven plugin to be able to dump/output some kind of listing which indicates where/why/how it has concluded the above dependencies are 'missing'.

**Comment by aikebah** [comment]
Running maven with debugging/exception stacktrace logging should be surfacing more detail in such cases. (`mvn -e -X <your further commandline>`) no clue why it breaks for you. As the dependencies are in the dependency tree (otherwise you wouldn't get the exception) they should be resolvable from your project.
In my experience exceptions like this surface if there is an issue connecting to a maven repository (and typically after first failure remains until either you run maven with -U option to retry failed release downloads (and re-evaluate snapshots for up-to-dateness)), or clear out your maven local repository.

**Comment by jeremylong** [comment]
As @aikebah already provided the solution to resolving the issue I am going to close the ticket. The debugging functionality already exists in maven.
