### ISSUE TITLE
Executing the initialize_oracle.sql result to ORA-01450

### ISSUE THREAD

**Issue by RonenSHL** [dependency-check/DependencyCheck#4342]
**Describe the bug**
I was trying to create an in house Oracle DB using the [https://github.com/jeremylong/DependencyCheck/blob/main/core/src/main/resources/data/initialize_oracle.sql](initialize_oracle.sql)
once executing the script I'm getting:
[ERROR] Message    : ORA-01450: maximum key length (6398) exceeded

**Log file**
[ERROR] SQL State  : 72000
[ERROR] Error Code : 1450
[ERROR] Message    : ORA-01450: maximum key length (6398) exceeded
[ERROR] Location   : /var/lib/jenkins/workspace/UP-EU-30-SYNC-INT/sw/src/main/resources/db/migration/V1__initialize_oracle.sql (/var/lib/jenkins/workspace/UP-EU-30-SYNC-INT/sw/src/main/resources/db/migration/V1__initialize_oracle.sql)
[ERROR] Line       : 132
[ERROR] Statement  : CREATE UNIQUE INDEX idxCpeEntry ON cpeEntry(part, vendor, product, version, update_version, edition, lang, sw_edition, target_sw, target_hw, other)

**Expected behavior**
I would appreciate any hint to solve this issue.

**Comment by mprins** [comment]
see http://dba-oracle.com/t_ora_01450_maximum_key_length_exceeded.htm
seems you need 16K blocks for the index

**Comment by RonenSHL** [comment]
The index cpeEntry  is for the table, the script should create the table as follows :
CREATE TABLE cpeEntry (id INT NOT NULL PRIMARY KEY, part CHAR(1), vendor VARCHAR(255), product VARCHAR(255),
version VARCHAR(255), update_version VARCHAR(255), edition VARCHAR(255), lang VARCHAR(20), sw_edition VARCHAR(255), 
target_sw VARCHAR(255), target_hw VARCHAR(255), other VARCHAR(255), ecosystem VARCHAR(255));

Considering your suggestion, what should be changed in your opinion?

**Comment by mprins** [comment]
yes and your problem is that all those fields add up to more that what is allowed for the length of an index in your oracle database instance, so changing the blocksize of your database instance to 16k blocks or at least the location of the index should fix your problem; your dba can do this for you.
making any or all of those varchar values smaller will fix the index problem at the risk of failure during insert, dropping the unique index will probably give you other problems.

personally I would chose anything else over using oracle

**Comment by RonenSHL** [comment]
Thanks @mprins , any good expirience with Postgres?

**Comment by mprins** [comment]
not with DependencyCheck specifically, but in general yes, much better.
We use a shared maven repository with the default H2 database that gets updated once a day in a separate job on Jenkins

**Comment by RonenSHL** [comment]
@mprins just wanted to update that with your hint to change to 16K blocks, the DB Schema was successfuly created, thank you!
You also mentioned that you are using a separate job on Jenkins to update the DB on a daily base,
could you please share the Job config or any referance how to create such job?
That it is also our plan to use Jenkins for that task,

**Comment by mprins** [comment]
@RonenSHL  I run a job that just does `mvn -U org.owasp:dependency-check-maven:update-only` which updates the embedded database as I don't use a dbms, and only use maven. 
You should be able to add relevant connection parameters to that using https://jeremylong.github.io/DependencyCheck/dependency-check-maven/update-only-mojo.html

**Comment by RonenSHL** [comment]
I managed to solve this issue and to update the Oracle DB using Jenkins Job.
Thanks for the support.
