### ISSUE TITLE
Performance Issues of Maintain Database with h2 1.4+

### ISSUE THREAD

**Issue by albuch** [dependency-check/DependencyCheck#436]
When using h2 version 1.4.x I see huge performance decrease and disk space increase during the database maintenance task.
The task normally only takes up a couple of seconds with h2 1.3.x. With 1.4.190 it takes more than 30 minutes (I never let it run till it finishes and stopped after ~ 30 minutes) and database file size increases to more than 3 GB.
File size for 1.3 is ~250MB.

Connection string for 1.4 is jdbc:h2:file:%s;FILE_LOCK=FS;AUTOCOMMIT=ON;

Any idea whats causing this issue?

I'm trying to integrate DependecyCheck with a SBT plug-in to scan applications developed with play framework that come bundled with a h2 db v1.4+ 
I could force downgrade the version in the project to scan but that would be just a workaround that needs to be done for every project individually.

**Comment by jeremylong** [comment]
I have no idea why this is happening. While not ideal could you shade 1.3.x in the SBT plugin to get around the issue? Alternatively, we could look into upgrading the dependency-check-core.

--Jeremy

**Comment by albuch** [comment]
Hi Jeremy,
overriding the dependency version of h2 in build.sbt as a workaround is fine though a bit tedious and might not work for projects that require a specific h2 version for integration testing.
If I find the time I will dig a bit deeper into h2 what causes the issue. Just wanted to check if someone had similar issues with h2 1.4.x

Thanks,
Alexander
