### ISSUE TITLE
Q: how/when do you release?

### ISSUE THREAD

**Issue by marcelstoer** [dependency-check/DependencyCheck#4388]
I see there are no open issues for 7.1.0 as per https://github.com/jeremylong/DependencyCheck/milestone/44.

So, I was wondering what your release process/schedule is.

**Comment by patpatpat123** [comment]
Interested by this :)

**Comment by jeremylong** [comment]
We release approximately monthly and are due to release soon. I've had some other things arise during the hours I normally spend working on ODC and have not had the time to update the documentation for the release. This weekend if not before we should see a new release.

**Comment by marcelstoer** [comment]
Thanks - for the quick reply and even more so for the huge effort you pour into this project.

**Comment by patpatpat123** [comment]
Wanted to leave a thank you as well
