### ISSUE TITLE
Unable to use local nvd json files with dependency-check utility

### ISSUE THREAD

**Issue by beena-yatin-kanyal** [dependency-check/DependencyCheck#4390]
I am in a corporate environment hence the dependency-check aggregate command is not working fine and error logs[1] are attached (it looks to be an upstream error). So I tried to set up the local NVD cache by downloading the` nvdcve-1.1-modified.json.gz` and `nvdcve-1.1-modified.json` files from the NVD website but still while running the dependency-check aggregate command it is pointing to the NVD website to download the metadata file. Can someone please suggest what is the issue here? 

`build.gradle` file configuration is shown below -
```
plugins {
    id "org.owasp.dependencycheck" version "7.0.4.1"
}

ext.publishUser = project.hasProperty('artifactoryUser') ? project.artifactoryUser : ''
ext.publishPassword = project.hasProperty('artifactoryPassword') ? project.artifactoryPassword : ''

subprojects {
    apply plugin: "io.spring.dependency-management"

    apply plugin: "org.owasp.dependencycheck"
    dependencyCheck {
        autoUpdate = false
        cve {
            urlBase = 'C:/Users/somefolder/Downloads/nvdcve-1.1-modified.json.gz'
            urlModified = 'C:/Users/somefolder/Downloads/nvdcve-1.1-modified.json.gz'
        }
        failOnError = true
        format = 'ALL'
        outputDirectory = 'security-report'
    }
}
```
[1] - Error logs attached -
[errorlogs.txt](https://github.com/jeremylong/DependencyCheck/files/8522887/errorlogs.txt)

**Comment by beena-yatin-kanyal** [comment]
also, it would be great if someone can point out how to set up the NVD mirror? or use the dependency check inside a docker image by still pointing the code on the host system and not inside image.

**Comment by beena-yatin-kanyal** [comment]
Even tried with the below configuration[1] but still had no luck as it still returns the below error.

`Caused by: org.owasp.dependencycheck.utils.DownloadFailedException: Download failed, unable to retrieve 'https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta'; Error downloading file https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta; unable to connect.`

Gradle config[1] -
```
plugins {
    id "org.owasp.dependencycheck" version "7.0.4.1"
}

ext.publishUser = project.hasProperty('artifactoryUser') ? project.artifactoryUser : ''
ext.publishPassword = project.hasProperty('artifactoryPassword') ? project.artifactoryPassword : ''

subprojects {
    apply plugin: "io.spring.dependency-management"

    apply plugin: "org.owasp.dependencycheck"
    dependencyCheck {
        autoUpdate = false
        cve {
            urlBase = 'http://localhost/nvdcve-1.1-%d.json.gz'
            urlModified = 'http://localhost/nvdcve-1.1-modified.json.gz'
        }
        failOnError = true
        format = 'ALL'
        outputDirectory = 'security-report'
    }
}
```

docker container -
![image](https://user-images.githubusercontent.com/46935197/164272802-cd2b764b-deea-41ce-b8c2-fd1cbf2b59fd.png)

**Comment by jeremylong** [comment]
Your second config using the nvdmirror looks correct.  Are you sure that the mirror had completely copied the NVD? It takes more than a minute to fully populate the mirror.  Also, I haven't tested the nvdmirror docker image since the NVD introduced rate limiting...

**Comment by jeremylong** [comment]
I think I just figured out the issue.  I'm guessing you are running:

```shell
./gradlew dependencyCheckUpdate
```

And you are seeing the issue?  Either use `allprojects` instead of `subprojects` or copy the config to the parent level for the update. Also - the output directory as configured will give you fits. You need to use: 

```groovy
outputDirectory = "$buildDir/security-report"
```

**Comment by beena-yatin-kanyal** [comment]
> Your second config using the nvdmirror looks correct. Are you sure that the mirror had completely copied the NVD? It takes more than a minute to fully populate the mirror. Also, I haven't tested the nvdmirror docker image since the NVD introduced rate limiting...

@jeremylong - I checked inside the mirror docker container at the `/tmp` folder but the count of the files there is 0. Seems like the error is with the NVD docker image. Could it be? Also if I point the CVE url to the NVD mirror as in the above configuration the utility still fetching the required configuration from the actual NVD database. Let me try with other commands like check-aggregate and see if it helps? I will update the results here.

**Comment by beena-yatin-kanyal** [comment]
> I think I just figured out the issue. I'm guessing you are running:
> 
> ```shell
> ./gradlew dependencyCheckUpdate
> ```
> 
> And you are seeing the issue? Either use `allprojects` instead of `subprojects` or copy the config to the parent level for the update. Also - the output directory as configured will give you fits. You need to use:
> 
> ```groovy
> outputDirectory = "$buildDir/security-report"
> ```

@jeremylong - Let me make this change in the configuration and see if it helps. I will update the results here.
