### ISSUE TITLE
Warning: Key is not certified with a trusted signature!

### ISSUE THREAD

**Issue by lpeterson333** [dependency-check/DependencyCheck#4404]
Hi.  When trying to verify the signatures for the OWASP dependency check CLI tool from https://jeremylong.github.io/DependencyCheck/dependency-check-cli/index.html  this warning was received.  Is it safe to use?

gpg: assuming signed data in 'dependency-check-7.1.0-release.zip'
gpg: Signature made 4/23/2022 6:00:20 AM Eastern Daylight Time
gpg:                using RSA key 259A55407DD6C00299E6607EFFDE55BE73A2D1ED
gpg: Good signature from "Jeremy Long <jeremy.long@gmail.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 259A 5540 7DD6 C002 99E6  607E FFDE 55BE 73A2 D1ED

**Comment by aikebah** [comment]
@lpeterson333 The warning you get tells you that GPG cannot say for sure that the key really belongs to Jeremy Long.
The signature itself is valid, and the key matches the expected key (fingerprint) - as implicitly documented at the [CLI documentation](https://jeremylong.github.io/DependencyCheck/dependency-check-cli/index.html) in the gpg recvkeys command.

So yes, your download was validated and is safe to use.

**Comment by jeremylong** [comment]
See https://serverfault.com/a/569923
