### ISSUE TITLE
suppressions.xml not being respected

### ISSUE THREAD

**Issue by bane73** [dependency-check/DependencyCheck#442]
I cannot seem to get the maven plugin to respect the suppressions.xml file -- and I cannot find clear documentation to ensure that I'm using the correct filename and storing it in a valid place in the project.

So I looked into the project's unit tests and found this file: https://github.com/jeremylong/DependencyCheck/blob/master/dependency-check-core/src/test/resources/suppressions.xml

I copied that file to my project at /src/main/resources/suppressions.xml.
I then modified the <cvssBelow>-entry and set it to 10 -- expecting it to suppress basically everything.
But it still is failing on maven-install for components rated at 6:

```
Dependency-Check Failure:
[ERROR] One or more dependencies were identified with vulnerabilities that have a CVSS score greater then '6.0'
```

Am I missing something?

Note: I am using the maven plugin v1.3.3

**Comment by jeremylong** [comment]
I just re-ran the examples using the following:

``` xml
<plugin>
    <groupId>org.owasp</groupId>
    <artifactId>dependency-check-maven</artifactId>
    <version>1.3.3</version>
    <configuration>
        <failBuildOnCVSS>3</failBuildOnCVSS>                    
        <suppressionFile>${basedir}/suppression.xml</suppressionFile>
    </configuration>
    <executions>
        <execution>
            <goals>
                <goal>check</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

The suppression file contains:

``` xml
    <suppress>
        <notes><![CDATA[
        This suppresses all CVE entries that have a score below CVSS 7.
        ]]></notes>
        <cvssBelow>10</cvssBelow>
    </suppress>
```

If you run this with `mvn -X verify` you should see a line in the resulting output like this one:

```
[DEBUG] Setting: suppression.file='C:\Users\jeremy\Desktop\demo\maven/suppression.xml'
```

With that are you able to figure out what is going wrong on your side?

--Jeremy

**Comment by bane73** [comment]
Sorry, been busy with other tasks.

Yes, this indeed helped -- thank you!
I had missed the fact that I needed to provide the `<suppressionFile>`-param in the POM.
Works great now.  :)
