### ISSUE TITLE
How to run only RetireJS analyzer scan?

### ISSUE THREAD

**Issue by Whimmery** [dependency-check/DependencyCheck#4429]
I was wondering but for the analyzers like RetireJS, is there a way to scan only using it?

**Comment by aikebah** [comment]
Use the various xxx analyzer enabled/disabled configuration properties of your integration of choice you can disable the various default enabled analyzers. See the [documentation pages](https://jeremylong.github.io/DependencyCheck/) of your integration of choice (maven, cli, gradle, ant) for the exact configuration switch names as they may differ from integration to integration.
Most analyzers run by default, so you'll have to explicitly switch them off.

However I'm wondering: if you really only want to run RetireJSAnalyzer, why not use [their own CLI-scanner](https://github.com/retirejs/retire.js/) instead?
