### ISSUE TITLE
Broken Link suppression.html

### ISSUE THREAD

**Issue by frankbryce** [dependency-check/DependencyCheck#443]
The link https://jeremylong.github.io/DependencyCheck/suppression.html no longer exists, but is
being linked as the help page for the suppression pop up window.  Screenshot attached as to which link is broken.

I'm using v1.3.3

![capture](https://cloud.githubusercontent.com/assets/5658950/12354678/7df816f2-bb65-11e5-90eb-86b15b522de3.PNG)

**Comment by jeremylong** [comment]
Thanks for reporting this! The link should have been http://jeremylong.github.io/DependencyCheck/general/suppression.html. This has been fixed in the code base and will be included in the next release.

**Comment by frankbryce** [comment]
You are welcome, love the tool!
