### ISSUE TITLE
Support nonProxyHosts parameter in settings.xml

### ISSUE THREAD

**Issue by christiangalsterer** [dependency-check/DependencyCheck#444]
Allow to support nonProxyHosts parameter when proxy is configured in settings.xml. This is needed that for some URL the proxy shall be used and for some not.

If you interested I can look into and submit a PR.

**Comment by jeremylong** [comment]
PR are always welcome - I'm still trying to resolve the aggregate goal issue so I might not get to this very soon.

**Comment by christiangalsterer** [comment]
Ok, will try to create a PR in the next 1-2 weeks (currently travelling therefore in limited bandwidth).

**Comment by christiangalsterer** [comment]
I have an implementation available. I hope to submit a PR in the next days after testing,

**Comment by jeremylong** [comment]
Thanks for the PR to close this issue!
