### ISSUE TITLE
Update of Commons Lang3 prohibits suppressions on Jenkins Plugin

### ISSUE THREAD

**Issue by stevespringett** [dependency-check/DependencyCheck#445]
Suppressions in the Jenkins plugin no longer work as a result of 041d3c5312993e5d9ec367a66af215207717b7f1.

https://issues.jenkins-ci.org/browse/JENKINS-32279 refers to the issue.

I would recommend this commit be reverted in order to restore suppression functionality to the Jenkins plugin. In addition, any other calls that require the latest Lang3 version will also need to be reverted.

Attached is the output of a Jenkins scan with Commons Lang3 3.4 being forced into the classpath via shading to the plugin jar. Assembly produces the same result.

[log.txt](https://github.com/jeremylong/DependencyCheck/files/96439/log.txt)

**Comment by jeremylong** [comment]
Do you know what version of commons lang is supported in the Jenkins environment?

--Jeremy

**Comment by jeremylong** [comment]
The change you indicated has been reverted. Can you verify that the snapshot works with Jennkins?

Thanks!

**Comment by stevespringett** [comment]
I have verified that after reverting the change, the Jenkins plugin works as expected. The issue appears to be that of classloaders. The Dependency-Check Jenkins plugin is built on top of https://github.com/jenkinsci/analysis-core-plugin , which the PMD, FindBugs, and Checkstyle plugins are also built on. Analysis-core currently uses commons-lang 3.3.2. It appears the classloader for analysis-core is preceding the classloader for DC Jenkins plugin thus causing the problem. It's finding 3.3.2 first.
