### ISSUE TITLE
Difference between mavne dependency and plugin?

### ISSUE THREAD

**Issue by lako12** [dependency-check/DependencyCheck#4468]
Hello,

i started using dependency-check but i didn't understand what is the difference between plugin and dependency. I have tried to use only the plugin and it seems to work.
I also noticed that if I add the dependency, in the report I get 2 cpe added:
cpe: 2.3: a: h2database: h2: 1.4.200: *: *: *: *: *: *: *
cpe: 2.3: a: apache: maven: 3.0.5: *: *: *: *: *: *: *

dependency used:
```
<dependency>
  <groupId>org.owasp</groupId>
  <artifactId>dependency-check-maven</artifactId>
  <version>7.1.0</version>
  <type>maven-plugin</type>
</dependency>
```

plugin used:
```
<plugin>
    <groupId>org.owasp</groupId>
    <artifactId>dependency-check-maven</artifactId>
    <version>7.1.0</version>
    <executions>
        <execution>
            <goals>
                <goal>check</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

Thanks!

**Comment by jeremylong** [comment]
You should not add dependency-check as a dependency. Dependencies are those that are used by the software once it is built. Whereas plugins are used to build/analyze the software.

**Comment by lako12** [comment]
ok, thanks!
