### ISSUE TITLE
FailOnCVSS option does not respect suppression file

### ISSUE THREAD

**Issue by Sti2nd** [dependency-check/DependencyCheck#4470]
**Describe the bug**
Using the `--failOnCVSS 9` flag and passing in suppression file with all the critical vulnerabilities suppressed still fails the build.

**Version of dependency-check used**
The problem occurs using version 7.1.0 of the cli (automatically downloaded by Jenkins).

**Log file**
Cannot provide since it is closed-source project.

**To Reproduce**

1. Have a project with critical vulnerabilities. Create a suppression file for all the critical vulnerabilities.
2. Run the CLI with `--failOnCVSS 9` option
3. Jenkins build still fails

**Expected behavior**
Build doesn't fail (since all the critical vulnerabilities are suppressed).

**Additional context**
Critical vulnerabilities were suppressed successfully.
![image](https://user-images.githubusercontent.com/6373430/166690940-8e8f5f24-639b-4137-8f07-7ddcc36321be.png)

I am using Jenkins pipelines and passing in the CLI option like this:

```groovy
dependencyCheck (
    additionalArguments: "--failOnCVSS 9",
    odcInstallation: 'latest' // 7.1.0
)
```

**Workaround**:
Managed to work around this by using the following code in Jenkins after the dependencyCheck. (Inspired by https://stackoverflow.com/a/66013797/6113915)

```groovy
dependencyCheckPublisher (
    pattern: '',
    failedTotalCritical: 1
)
```

I tried with the exact same suppression file and the build now passes. When I remove one suppression it fails.

**Comment by aikebah** [comment]
If you did the suppressions correctly the dependencyCheck CLI check should pass with all your criticals in the suppressed section of the XML... whether the Jenkins plugin reads the report wrongly and therefor still fails the build,  your suppression is not effective or there is some other error happening in the analysis that makes your build fail (non-zero return code due to 'errors occurred' rather than 'too high severity) is hard to tell as you can not provide a report.

**Comment by aikebah** [comment]
Note that the Jenkins plugin for ODC is a project separate from this repository. This repository is only about the ODC tool, not the integration in Jenkins.

**Comment by Sti2nd** [comment]
You are right in that it could be Jenkins failing the build and the CLI working perfectly. I should probably have tested the CLI directly. I have already spent a good amount of time and I am happy with the workaround so the issue can be closed. ✌️

Thank you for looking at the issue and replying.
