### ISSUE TITLE
Ability to detect  non-maven dependencies?

### ISSUE THREAD

**Issue by ivojonker** [dependency-check/DependencyCheck#4481]
I just discovered some of my war projects included some old/vulnerable jars due to them being copied as webresource.

Example:
/WebContent/WEB-INF/lib/commons-fileupload-1.3.1.jar

In combination with /pom.xml:
```
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-war-plugin</artifactId>
				<configuration>
					<webResources>
						<webResource>
							<directory>WebContent</directory>
						</webResource>
					</webResources>
				</configuration>
			</plugin>
```

It turns out the vulnerable dependency was not found.

Is there a mode to detect this? I imagine the same might apply for .ear/lib's

**Comment by aikebah** [comment]
I expect that adding the WebContent folder as part of a scanSet in the maven plugin should surface it. (although the best solution is of course to transform the project to make commons-fileupload a runtime dependency to gain other benefits like being able to spot an outdated dependency by `mvn versions:display-dependency-updates`)
