### ISSUE TITLE
Blank CVSS Scores for RetireJS Analyzer

### ISSUE THREAD

**Issue by madarmp** [dependency-check/DependencyCheck#4488]
While testing the tool, I came across blank CVSS scores for all the vulnerabilities detected through RetireJS Analyzer.

Is this situation normal? If not, is there any fix for this since I scanned all the GitHub issues and couldn't find anything similar?

**Comment by jeremylong** [comment]
RetireJS may not have CVSS scores as their data does not contain the score: https://github.com/RetireJS/retire.js/blob/master/repository/jsrepository.json
