### ISSUE TITLE
[FP]: quarkus-fs-util-0.0.9.jar

### ISSUE THREAD

**Issue by tasso94** [dependency-check/DependencyCheck#4489]
### Package URl

pkg:maven/io.quarkus/quarkus-fs-util@0.0.9

### CPE

cpe:2.3:a:quarkus:quarkus:0.0.9:*:*:*:*:*:*:*

### ODC Integration

{"label"=>"Maven Plugin"}

### ODC Version

6.3.1

### Description

`quarkus-fs-util-0.0.9.jar` is a dependency of the latest Quarkus version 2.9.0 and has a dedicated versioning:
https://github.com/quarkusio/quarkus/blob/2.9.0.Final/independent-projects/bootstrap/pom.xml#L69

This leads to flagging this dependency with all vulnerabilities in Quarkus versions >= 0.0.9.

**Comment by aikebah** [comment]
Please upgrade to latest version before filing FP reports. This is already fixed in at least 7.1.0
