### ISSUE TITLE
Dependency Check 7.1.0 installed but no action, how to find if properly installed?

### ISSUE THREAD

**Issue by yettsyjk** [dependency-check/DependencyCheck#4492]
Hi Team, 

I have installed v7.1.0 Dependency check CLI for Windows and when I run `dependency-check.bat -h` OR `dependency-check.bat --help` OR `dependency-check.bat --log odc.log` command there is no visible activity. Only new line.
What is the recommended command to view if the installation was succcessful? Thanks

Assumptions:
1. Yes, verified environment file updated to reflect location of '\dependency-check\bin' (as admin)
2. Yes, certificates successfully added to keytool (as admin)
3. Yes, verified latest version of Java on local machine
4. Using CLI command 'dependency-check.bat --project name of the jar file --scan Path of jar file --out where you want your output file(Path)'
5. Using documentation: https://jeremylong.github.io/DependencyCheck/dependency-check-cli/index.html

**Comment by mprins** [comment]
what does `dependency-check.bat --help` do for you?

**Comment by yettsyjk** [comment]
Hi mprins thanks for your response - 
When entering that command there is no action, no response. only new command line
'abstracted'\Java\jre1.8.0_321\bin>dependency-check.bat --help 

also tried `dependency-check.bat --log odc.log `

**Comment by mprins** [comment]
sorry, I have no idea what's going on there...

**Comment by yettsyjk** [comment]
Yay! it's alive 
Issue: user error
Resolved: step missing was updating environment file path for installed version of jre (current installated version)
referenced: https://stackoverflow.com/questions/15796855/java-is-not-recognized-as-an-internal-or-external-command - replace with your latest version
Close question -
