### ISSUE TITLE
AnalysisException: OSS Index rate limit exceeded in a multi-module Maven build

### ISSUE THREAD

**Issue by haumacher** [dependency-check/DependencyCheck#4497]
In a multi-module build, where I'm checking all modules for vulnerable dependencies, I get the error "AnalysisException: OSS Index rate limit exceeded" after quite a view modules (79) have been checked successfully. I thought, the access to the OSS index was locally cached and only updated once for the whole build?

From the build log I see the download only once when the first module is analyzed:

```
[INFO] Download Started for NVD CVE - 2008
[INFO] Download Complete for NVD CVE - 2008  (1204 ms)
[INFO] Processing Started for NVD CVE - 2008
...
[INFO] Processing Complete for NVD CVE - Modified  (4832 ms)
[INFO] Begin database maintenance
[INFO] Updated the CPE ecosystem on 120398 NVD records
[INFO] Removed the CPE ecosystem on 2 NVD records
[INFO] Cleaned up 248 orphaned NVD records
[INFO] End database maintenance (15010 ms)
[INFO] Begin database defrag
[INFO] End database defrag (4510 ms)
[INFO] Check for updates complete (219766 ms)
```

However, while each module is build, I get the following lines reported:

```
[INFO] Checking for updates
[INFO] Skipping NVD check since last check was within 4 hours.
[INFO] Skipping RetireJS update since last update was within 24 hours.
[INFO] Check for updates complete (6 ms)
```

This sounds like no network access should occur. Unfortunately, from the exception it is not clear from what part of the code the original problem was thrown:

```
Caused by: org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during analysis:
	AnalysisException: OSS Index rate limit exceeded
		caused by TransportException: Unexpected response; status: 429
    at org.owasp.dependencycheck.Engine.analyzeDependencies (Engine.java:665)
    at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.runCheck (BaseDependencyCheckMojo.java:1813)
    at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.execute (BaseDependencyCheckMojo.java:1001)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    ...
```

The cache does not need to be configured separately? I'm using the following configuration:

```
	<plugin>
		<groupId>org.owasp</groupId>
		<artifactId>dependency-check-maven</artifactId>
		<version>7.1.0</version>
	        <configuration>
	                <format>ALL</format>
	                <skipProvidedScope>true</skipProvidedScope>
	                <suppressionFile>http://tl/trac/wiki/DependencyCheckSuppressions?format=txt</suppressionFile>
	                <suppressionFileServerId>tl-trac</suppressionFileServerId>
	        </configuration>
	</plugin>
```

**Version of dependency-check used**
I'm using version 7.1.0 of the Maven dependency-check plugin.

**Comment by mprins** [comment]
> The cache does not need to be configured separately?

No it is stored in your local maven repository by default

Are you running `mvn dependency-check:aggregate` (https://jeremylong.github.io/DependencyCheck/dependency-check-maven/aggregate-mojo.html)

**Comment by haumacher** [comment]
No, I'm running `mvn install dependency-check:check` from the reactor module producing JUnit reports that are processed later on.

**Comment by mprins** [comment]
OK, that will invocate the scanner for each module separately; 
AFAIK the OSS Index lookup is not cached it uses the service directly, I don't think Sonatype provides a download, but I may be wrong

**Comment by haumacher** [comment]
If I switch to `dependency-check:aggregate`, is there a way to make my build fail, if a vulnerable dependency is found. Currently I'm not using Maven reports/site generation but process the test results with Jenkins.

**Comment by mprins** [comment]
both `check` and `aggregate` are report goals, you can set [failBuildOnCVSS](https://jeremylong.github.io/DependencyCheck/dependency-check-maven/aggregate-mojo.html#failBuildOnCVSS) just like for `check` 

you can try if it solves your problem using `mvn clean package org.owasp:dependency-check-maven:aggregate -DfailBuildOnCVSS=1`

**Comment by haumacher** [comment]
Thanks a lot, I'm absolutely happy with this solution - works like a charm - much better than the multitude of single reports.
