### ISSUE TITLE
Unable to load database: dependency-check-maven 1.0.8

### ISSUE THREAD

**Issue by phsh** [dependency-check/DependencyCheck#45]
Hi, 
I have problems with running the dependendency-check-maven
mvn org.owasp:dependency-check-maven:1.0.8:check 

Jan 21, 2014 1:09:05 PM org.owasp.dependencycheck.Engine doUpdates
WARNING: Unable to update Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.
Jan 21, 2014 1:09:06 PM org.owasp.dependencycheck.Engine analyzeDependencies
SEVERE: Unable to load database

mvn -version
Apache Maven 3.0.5 
Java version: 1.7.0_25, vendor: Oracle Corporation

mvn org.owasp:dependency-check-maven:1.0.7:check does the download of the database

What has changed, or what am I missing?

**Comment by jeremylong** [comment]
fantastic... I have a feeling I know what the issue is and apparently something planned for 1.1.0 may have accidentally gotten into the 1.0.8 release. I'll do some testing later today and may need to push a bug fix release as 1.1.0 won't be ready for a week or two.

**Comment by phsh** [comment]
Thanks for the update. Now I know that I'm not crazy...

**Comment by jeremylong** [comment]
Okay, I've done a bit of testing. Cleared out my local repository.and ran:

mvn org.owasp:dependency-check-maven:1.0.8:check

Worked fine on my end. What operating system are you running? Did you build the Maven plugin yourself or did you just let maven download it from central?

**Comment by phsh** [comment]
mvn -version 
Apache Maven 3.0.5 (r01de14724cdef164cd33c7c8c2fe155faf9602da; 2013-02-19 14:51:28+0100)
Maven home: /usr/local/bin/apache-maven-3.0.5
Java version: 1.7.0_25, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.8.0-27-generic", arch: "amd64", family: "unix"

I have removed my repository .m2/repository
The version is downloaded from central.
Still not working...
What are you running? mvn -version

**Comment by phsh** [comment]
mvn -version
Apache Maven 3.0.3 (r1075438; 2011-02-28 18:31:09+0100)
Maven home: /usr/share/maven
Java version: 1.6.0_35, vendor: Apple Inc.
Java home: /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
Default locale: en_US, platform encoding: MacRoman
OS name: "mac os x", version: "10.7.4", arch: "x86_64", family: "mac"

can't do it on my mac either.

**Comment by stevespringett** [comment]
Having the same issue here Jeremy.

mvn -version
Apache Maven 3.0.3 (r1075438; 2011-02-28 11:31:09-0600)
Maven home: /usr/share/maven
Java version: 1.7.0_51, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_51.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.8.5", arch: "x86_64", family: "mac"

**Comment by jeremylong** [comment]
Works on Windows:

Apache Maven 3.1.1 (0728685237757ffbf44136acec0402957f723d9a; 2013-09-17 11:22:2
2-0400)
Maven home: c:\java\apache-maven-3.1.1
Java version: 1.7.0_45, vendor: Oracle Corporation
Java home: c:\Progra~1\Java\jdk1.7.0_45\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"

I've sent an email to Steve to test the 1.1.0-SNAPSHOT - this is related to loading the database driver. If this is fixed in the snapshot I will likely wrap a few things up and push the 1.1.0 release sooner then I was planning.

**Comment by jeremylong** [comment]
This has been resolved in 1.1.0-SNAPSHOT. The release version should be released this weekend.
