### ISSUE TITLE
ignoreFailures property 

### ISSUE THREAD

**Issue by kaimago** [dependency-check/DependencyCheck#450]
When you running DC with a central DB, a DB failure is causing a lot of trouble. Specially when all projects in the company are using DC by default.

It would be helpfull to have a configuration property like "ignoreFailures" which ignores all failures, except the failBuildOnCVSS-Error.

What do you think ?

**Comment by jeremylong** [comment]
Are the failures due to different schema versions? I.e. one project may be using dependency-check 1.2.1 and another is suing 1.3.4 (i.e. issue #429)?

**Comment by kaimago** [comment]
it's about failures when the database has maintaince or crashed or network-problems...

**Comment by jeremylong** [comment]
I am starting work on issue #215 - as part of the effort I will likely add the proposed ignoreFailures property to the Ant, Maven, Gradle, and sbt plugins.

**Comment by jeremylong** [comment]
This was implemented as part of #215; maven, ant, gradle, etc. now have a failOnError property that defaults to true but can be set to false to skip errors.
