### ISSUE TITLE
dependency-check@7.1.0  Exception occurred initializing Yarn Audit Analyzer. (from windows10)

### ISSUE THREAD

**Issue by susuJiang** [dependency-check/DependencyCheck#4508]
C:\Software\dependency-check-7.1.0-release\dependency-check\bin>dependency-check --out . -s C:\Project\program\survey-ui\yarn.lock

[INFO] Checking for updates
[INFO] Skipping NVD check since last check was within 4 hours.
[INFO] Skipping RetireJS update since last update was within 24 hours.
[INFO] Check for updates complete (12 ms)
[INFO]

Dependency-Check is an open source tool performing a best effort analysis of 3rd party dependencies; false positives and false negatives may exist in the analysis performed by the tool. Use of the tool and the reporting provided constitutes acceptance for use in an AS IS condition, and there are NO warranties, implied or otherwise, with regard to the analysis or its use. Any use of the tool and the reporting provided is at the user’s risk. In no event shall the copyright holder or OWASP be held liable for any damages whatsoever arising out of or in connection with the use of this tool, the analysis performed, or the resulting report.

   About ODC: https://jeremylong.github.io/DependencyCheck/general/internals.html
   False Positives: https://jeremylong.github.io/DependencyCheck/general/suppression.html

? Sponsor: https://github.com/sponsors/jeremylong

[INFO] Analysis Started
[INFO] Finished File Name Analyzer (0 seconds)
[INFO] Finished Dependency Merging Analyzer (0 seconds)
[INFO] Finished Version Filter Analyzer (0 seconds)
[INFO] Finished Hint Analyzer (0 seconds)
[INFO] Created CPE Index (1 seconds)
[INFO] Finished CPE Analyzer (1 seconds)
[INFO] Finished False Positive Analyzer (0 seconds)
[INFO] Finished NVD CVE Analyzer (0 seconds)
[WARN] The Yarn Audit Analyzer has been disabled. Yarn executable was not found.
[ERROR] Exception occurred initializing Yarn Audit Analyzer.
[WARN] Unable to determine Package-URL identifiers for 1 dependencies
[INFO] Finished Sonatype OSS Index Analyzer (0 seconds)
[INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
[INFO] Finished Dependency Bundling Analyzer (0 seconds)
[INFO] Analysis Complete (1 seconds)
[INFO] Writing report to: C:\Software\dependency-check-7.1.0-release\dependency-check\bin\.\dependency-check-report.html
[ERROR] Unable to read yarn audit output.

**Comment by mprins** [comment]
> [WARN] The Yarn Audit Analyzer has been disabled. Yarn executable was not found.
[ERROR] Exception occurred initializing Yarn Audit Analyzer.

is the yarn executable in the search path? if not why not configure that using the `--yarn` option: https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html

**Comment by susuJiang** [comment]
> 
**I added the path of yarn, but the path is still wrong**

C:\Software\dependency-check-7.1.0-release\dependency-check\bin>dependency-check --yarn C:\Users\cheryl.jiang\AppData\Local\Yarn\bin --out . -s C:\Project\program\survey-ui\yarn.lock
[INFO] Checking for updates
[INFO] Skipping NVD check since last check was within 4 hours.
[INFO] Skipping RetireJS update since last update was within 24 hours.
[INFO] Check for updates complete (12 ms)
[INFO]

Dependency-Check is an open source tool performing a best effort analysis of 3rd party dependencies; false positives and false negatives may exist in the analysis performed by the tool. Use of the tool and the reporting provided constitutes acceptance for use in an AS IS condition, and there are NO warranties, implied or otherwise, with regard to the analysis or its use. Any use of the tool and the reporting provided is at the user’s risk. In no event shall the copyright holder or OWASP be held liable for any damages whatsoever arising out of or in connection with the use of this tool, the analysis performed, or the resulting report.


   About ODC: https://jeremylong.github.io/DependencyCheck/general/internals.html
   False Positives: https://jeremylong.github.io/DependencyCheck/general/suppression.html

? Sponsor: https://github.com/sponsors/jeremylong


[INFO] Analysis Started
[INFO] Finished File Name Analyzer (0 seconds)
[INFO] Finished Dependency Merging Analyzer (0 seconds)
[INFO] Finished Version Filter Analyzer (0 seconds)
[INFO] Finished Hint Analyzer (0 seconds)
[INFO] Created CPE Index (1 seconds)
[INFO] Finished CPE Analyzer (1 seconds)
[INFO] Finished False Positive Analyzer (0 seconds)
[INFO] Finished NVD CVE Analyzer (0 seconds)
[WARN] Provided path to `yarn` executable is invalid.
[WARN] The Yarn Audit Analyzer has been disabled. Yarn executable was not found.
[ERROR] Exception occurred initializing Yarn Audit Analyzer.
[WARN] Unable to determine Package-URL identifiers for 1 dependencies
[INFO] Finished Sonatype OSS Index Analyzer (0 seconds)
[INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
[INFO] Finished Dependency Bundling Analyzer (0 seconds)
[INFO] Analysis Complete (1 seconds)
[INFO] Writing report to: C:\Software\dependency-check-7.1.0-release\dependency-check\bin\.\dependency-check-report.html
[ERROR] Unable to read yarn audit output.

**Comment by susuJiang** [comment]
> > [WARN] The Yarn Audit Analyzer has been disabled. Yarn executable was not found.
> > [ERROR] Exception occurred initializing Yarn Audit Analyzer.
> 
> is the yarn executable in the search path? if not why not configure that using the `--yarn` option: https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html

**Comment by mprins** [comment]
I think it needs to be the exact path to the executable, not a search directory, something like `C:\Users\cheryl.jiang\AppData\Local\Yarn\bin\yarn ` or `C:\Users\cheryl.jiang\AppData\Local\Yarn\bin\yarn.exe`

see https://github.com/jeremylong/DependencyCheck/blob/a1a9f2beed2b35ea37fed7860fb1bd1ce021e8a0/core/src/main/java/org/owasp/dependencycheck/analyzer/YarnAuditAnalyzer.java#L192-L194

**Comment by susuJiang** [comment]
> I think it needs to be the exact path to the executable, not a search directory, something like `C:\Users\cheryl.jiang\AppData\Local\Yarn\bin\yarn ` or `C:\Users\cheryl.jiang\AppData\Local\Yarn\bin\yarn.exe`
> 
> see
> 
> https://github.com/jeremylong/DependencyCheck/blob/a1a9f2beed2b35ea37fed7860fb1bd1ce021e8a0/core/src/main/java/org/owasp/dependencycheck/analyzer/YarnAuditAnalyzer.java#L192-L194


**I changed the path, but this time there was no error report analysis, and the error was prompted directly on the command line.**

C:\Software\dependency-check-7.1.0-release\dependency-check\bin>dependency-check --yarn C:\Software\nvmAndNode\nodejs\yarn.cmd --out . -s C:\Project\program\survey-ui\yarn.lock
[INFO] Checking for updates
[INFO] Skipping NVD check since last check was within 4 hours.
[INFO] Skipping RetireJS update since last update was within 24 hours.
[INFO] Check for updates complete (12 ms)
[INFO]

Dependency-Check is an open source tool performing a best effort analysis of 3rd party dependencies; false positives and false negatives may exist in the analysis performed by the tool. Use of the tool and the reporting provided constitutes acceptance for use in an AS IS condition, and there are NO warranties, implied or otherwise, with regard to the analysis or its use. Any use of the tool and the reporting provided is at the user’s risk. In no event shall the copyright holder or OWASP be held liable for any damages whatsoever arising out of or in connection with the use of this tool, the analysis performed, or the resulting report.


   About ODC: https://jeremylong.github.io/DependencyCheck/general/internals.html
   False Positives: https://jeremylong.github.io/DependencyCheck/general/suppression.html

? Sponsor: https://github.com/sponsors/jeremylong


[INFO] Analysis Started
[INFO] Finished File Name Analyzer (0 seconds)
[INFO] Finished Dependency Merging Analyzer (0 seconds)
[INFO] Finished Version Filter Analyzer (0 seconds)
[INFO] Finished Hint Analyzer (0 seconds)
[INFO] Created CPE Index (1 seconds)
[INFO] Finished CPE Analyzer (1 seconds)
[INFO] Finished False Positive Analyzer (0 seconds)
[INFO] Finished NVD CVE Analyzer (0 seconds)
[INFO] Finished Yarn Audit Analyzer (2 seconds)
[WARN] An error occurred while analyzing 'C:\Project\program\survey-ui\yarn.lock?glob-parent' (Sonatype OSS Index Analyzer).
[WARN] An error occurred while analyzing 'C:\Project\program\survey-ui\yarn.lock?yargs-parser' (Sonatype OSS Index Analyzer).
[WARN] An error occurred while analyzing 'C:\Project\program\survey-ui\yarn.lock?faker' (Sonatype OSS Index Analyzer).
[WARN] An error occurred while analyzing 'C:\Project\program\survey-ui\yarn.lock?ejs' (Sonatype OSS Index Analyzer).
[WARN] An error occurred while analyzing 'C:\Project\program\survey-ui\yarn.lock?node-notifier' (Sonatype OSS Index Analyzer).
[WARN] An error occurred while analyzing 'C:\Project\program\survey-ui\yarn.lock?nth-check' (Sonatype OSS Index Analyzer).
[WARN] An error occurred while analyzing 'C:\Project\program\survey-ui\yarn.lock?node-forge' (Sonatype OSS Index Analyzer).
[INFO] Finished Sonatype OSS Index Analyzer (71 seconds)
[INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
[INFO] Finished Dependency Bundling Analyzer (0 seconds)
[INFO] Analysis Complete (74 seconds)
[INFO] Writing report to: C:\Software\dependency-check-7.1.0-release\dependency-check\bin\.\dependency-check-report.html
[ERROR] Failed to request component-reports
[ERROR] Failed to request component-reports
[ERROR] Failed to request component-reports
[ERROR] Failed to request component-reports
[ERROR] Failed to request component-reports
[ERROR] Failed to request component-reports
[ERROR] Failed to request component-reports

**Comment by aikebah** [comment]
That's the next analyzer after Yarn Audit Analyzer and likely it's having trouble connecting to the internet to contact OSSIndex. More detail can be obtained by add `--log odc.log` and then checking the debug log messages in the file odc.log.

**Comment by susuJiang** [comment]
> That's the next analyzer after Yarn Audit Analyzer and likely it's having trouble connecting to the internet to contact OSSIndex. More detail can be obtained by add `--log odc.log` and then checking the debug log messages in the file odc.log.

**Thanks, problem solved**
