### ISSUE TITLE
dependency-check-ant/installation.html link broken

### ISSUE THREAD

**Issue by mkienenb** [dependency-check/DependencyCheck#451]
Both the "Installation" left-side menu item and the Usage.html "installation guide" link point to a missing file.  The Usage menu item no longer shows up, so perhaps this page is obsolete in any case.

`https://jeremylong.github.io/DependencyCheck/dependency-check-ant/installation.html`

**Comment by jeremylong** [comment]
Thanks for pointing this out. The reference to installation.html should have been changed to index.html. I have corrected this in the repo and will publish the correction soon.

--jeremy
