### ISSUE TITLE
Plans for VEX support?

### ISSUE THREAD

**Issue by ThomGeG** [dependency-check/DependencyCheck#4516]
I just saw the announcement from Dependency-Track that it supports the creation and consumption of VEX: https://www.issuewire.com/owasp-makes-significant-advancements-in-sbom-effectiveness-and-risk-prioritization-1733145415969712

My company already uses Dependency-Check for our vulnerability scans and prefer its suppression files than Dependency-Track's take on vulnerability auditing. We're interested in the ability to turn the suppression files into VEX we can distribute, so I'm curious if there's any plans to natively support generating it in some capacity.

Cheers

**Comment by mprins** [comment]
in general suppression files, at least mine, don't have the amount of detail that is required for a useful VEX document. 
See for example https://github.com/jeremylong/DependencyCheck/blob/main/core/src/test/resources/suppressions.xml that has a suppression for anything lower that CVSS 7

**Comment by raboof** [comment]
> in general suppression files, at least mine, don't have the amount of detail that is required for a useful VEX document.

That's true, but perhaps it could be extended to allow such detail?

> See for example https://github.com/jeremylong/DependencyCheck/blob/main/core/src/test/resources/suppressions.xml that has a suppression for anything lower that CVSS 7

I don't think a VEX file is required to be exhaustive (for one thing it cannot contain references to vulnerabilities that have not yet been found :) ), so just ignoring the "anything lower that CVSS 7" statement when generating VEX might be fine.

Vice-versa, it could be interesting to consider allowing VEX files as input like suppressions files?
