### ISSUE TITLE
version 7.1.0 cli ossindex '403'

### ISSUE THREAD

**Issue by yettsyjk** [dependency-check/DependencyCheck#4517]
Hi Team,

I'm experiencing an error when HTML report is created with OSSIndex error code 403. 
Could you please take a look and provide some  advice? 
HTML log Analysis Exceptions results:
'Unexpected response; status: 403
cause: org.sonatype.ossindex.service.client.transport.Transport$TransportException: Unexpected response; status: 403
org.sonatype.ossindex.service.client.transport.HttpUrlConnectionTransport.post(HttpUrlConnectionTransport.java:106)'

dependency-check version: 7.1.0 CLI
Dependencies Scanned: 148

When we ran command `dependency-check.bat --log odc.log` no results no logs provided

**To Reproduce**
1. installed version 7.1.0 CLI
2. verified certificates, environmental file, java version properly installed
3. scanned a .war file with dependencies 
4. HTML report populated but missing portions of report, identfied by section header 'Analysis Exceptions'

**Expected behavior**
on HTML report we were expecting a section header 'Summary' that did not populate. 
We were expecting columns Dependency, Vulnerability IDs, Package, Highest Severity, CVE Count, Confidence, and Evidence Count

Thanks

**Comment by aikebah** [comment]
Do you have a proxy configured that requires authentication and/or filters to only allow certain outbound traffic?

HTTP 403 on the Ossindex access indicates that some host travelled on your path to it responds with HTTP forbidden.

**Comment by yettsyjk** [comment]
Hi @aikebah, 
Thanks for the assist. I'm looking into this. However, I can confirm that we were not able to replicate this issue on a separate machine on the same network with the same version CLI installed. 
Is there a recommend log command to run?
Cheers,

**Comment by aikebah** [comment]
@yettsyjk `dependency-check.bat --log odc.log` should yield a odc.log file containing debug logging on your system (in the working directory where you started the command)
