### ISSUE TITLE
suppression file location in multi-module build

### ISSUE THREAD

**Issue by cproinger** [dependency-check/DependencyCheck#452]
Hi, i have a question i cannot answer from the information in the docs. 

the owasp dependency-check maven-plugin allows to configure a [suppressionFile](https://jeremylong.github.io/DependencyCheck/general/suppression.html). I have multiple projects that should use the same information. is there any way i can configure this? does this value support http-urls?

**Comment by jeremylong** [comment]
Yes, the suppressionFile property will accept URL based paths (http, https, and file URLs).
