### ISSUE TITLE
Prevent failing when CVE update fails

### ISSUE THREAD

**Issue by MaJa1980** [dependency-check/DependencyCheck#4531]
Hi!

Sometimes dependency check failes with updating the local CVE database because server is not reachable for whatever reason. This causes a dependency check fail. Is there any option to skip the update in this case and proceed?

Best, Martin

**Comment by aikebah** [comment]
Yes, see the [documentation](https://jeremylong.github.io/DependencyCheck/) for the tool you use (CLI/maven/gradle/ant/sbt), if you use Jenkins plugin to run the analysis then you need the CLI documentation, as it uses the CLI behind the scenes. 

All of them have a configuration option to not update the database (as long as a database from a previous run is available), as well as an option to only update the database.

Typically for CI environments with a shared data location one would create a special periodic build to run only the update of the CVE database and run the analysis during regular builds with the option that disables the update of the database.
