### ISSUE TITLE
Unable to perform a dependency check on executable jars

### ISSUE THREAD

**Issue by Ardesco** [dependency-check/DependencyCheck#454]
The dependency check is failing to open executable jars and as a result not reporting on the dependencies in them.

For more info on executable jars have a look at:

http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#getting-started-first-application-executable-jar

Scanning works fine and displays errors if the jar is not executable, it just doesn't flag any problems if the jar is executable.

**Comment by Ardesco** [comment]
It's specifically this that's causing the problem:

http://docs.spring.io/spring-boot/docs/1.3.0.BUILD-SNAPSHOT/reference/htmlsingle/#deployment-service

> Fully executable jars work by embedding an extra script at the front of the file. Not all tools currently accept this format so you may not always be able to use this technique.

The extra script embedded at the front of the file seems to confuse whatever is trying to open the archive.

**Comment by jeremylong** [comment]
This has been fixed in the current snapshot. Jar files contained in fully executable jars created by Spring-Boot will now be correctly scanned. This will be included in the next release.
