### ISSUE TITLE
Copy-paste error in maven plugin.xml

### ISSUE THREAD

**Issue by OrangeDog** [dependency-check/DependencyCheck#4543]
**Describe the bug**
The details of `ossindexAnalyzerUseCache` are a copy of `ossindexAnalyzerEnabled`:
```xml
<name>ossindexAnalyzerUseCache</name>
<type>java.lang.Boolean</type>
<required>false</required>
<editable>true</editable>
<description>Whether or not the Sonatype OSS Index analyzer is enabled.</description>
```

**Version of dependency-check used**
dependency-check-maven 7.1.0

**Comment by mprins** [comment]
should be fixed here: https://github.com/jeremylong/DependencyCheck/blob/c236dbf3b63ad3cc229a6a079a244d354da5ce46/maven/src/main/java/org/owasp/dependencycheck/maven/BaseDependencyCheckMojo.java#L622-L633

like: https://github.com/jeremylong/DependencyCheck/blob/c236dbf3b63ad3cc229a6a079a244d354da5ce46/ant/src/main/java/org/owasp/dependencycheck/taskdefs/Check.java#L336-L343

**Comment by jeremylong** [comment]
@aikebah I see you created the branch with the fix - but not the PR?

https://github.com/jeremylong/DependencyCheck/compare/issue-4543

**Comment by aikebah** [comment]
Hmm... completely missed out on creation of the PR...
