### ISSUE TITLE
Possible to exclude Ant Pattern in dependency-check-maven?

### ISSUE THREAD

**Issue by ctnelson1997** [dependency-check/DependencyCheck#4544]
Hello!

Using the dependency-check-cli, it is possible to exclude files from being scanned using the `exclude` arg. However, using dependency-check-maven, `odc.excludes` is designed specifically to exclude certain artifacts (rather than Ant matching files/directories). This is problematic when trying to ignore .wars, .jars, .ears, etc. produced in the "target" folder when running an aggregate scan. I realize there is `scanDir`, but I am looking for something opposite, like `ignoreAntPath`. Is there something analogous to `exclude` in dependency-check-maven? 

Thanks for all your work!

**Comment by aikebah** [comment]
I do not see how you would run into trouble with these? Can you share more info on how these problematic archives hit you?

**Comment by ctnelson1997** [comment]
When the `target` folder is scanned, (because it cannot be ignored), it generates duplicates for the same issue.

e.g. A vulnerable dependency in `project-web`, child of `project-parent` is reported for both `project-web` and `project-parent` as the dependency is both picked up in the POM of `project-web` and as a WAR archive in the `target` folder of `pom-parent`.

**Comment by aikebah** [comment]
Would you be able to share a reproducer project for your issue? I fail to see how this would happen. I would not expect the war archive to appear in the target of project-parent, only in the target of project-web as its build-artifact.

**Comment by jeremylong** [comment]
Why would you need to configure the maven plugin to scan the target directory? The maven plugin gathers the necessary information from the build itself - scanning the target directory should not be necassary.
