### ISSUE TITLE
How to suppress new OSSIndex issues?

### ISSUE THREAD

**Issue by OrangeDog** [dependency-check/DependencyCheck#4553]
Neither `<cve>sonatype-2007-0004</cve>` nor `<vulnerabilityName>sonatype-2007-0004</vulnerabilityName>` appear to work to suppress this issue:

> `commons-httpclient-3.1.jar (pkg:maven/commons-httpclient/commons-httpclient@3.1, cpe:2.3:a:apache:commons-httpclient:3.1:*:*:*:*:*:*:*, cpe:2.3:a:apache:httpclient:3.1:*:*:*:*:*:*:*) : [sonatype-2007-0004] CWE-770: Allocation of Resources Without Limits or Throttling`

**Comment by OrangeDog** [comment]
The `<vulnerabilityName>` matches the whole description, so the easiest way is probably:

```xml
<vulnerabilityName regex="true">\[sonatype-2007-0004\].*</vulnerabilityName>
```

**Comment by ramonaEs** [comment]
Try reading the following issue. As per OSSIndex, all bugs from last week should be resolved. 
#4535 
You could try clearing the cache.

**Comment by OrangeDog** [comment]
@ramonaEs there is no bug here, it was just a question.

**Comment by jeremylong** [comment]
@OrangeDog yes - using the vulnerability name is how you would suppress the findings from the OSS Index.
