### ISSUE TITLE
[ERROR] Unable to connect to the database

### ISSUE THREAD

**Issue by frankbryce** [dependency-check/DependencyCheck#457]
version 1.3.4

When running the command

```
CALL bin/dependency-check.bat --project "<REPLACED_FOR_POSTING>" --out "<REPLACED_FOR_POSTING>" --scan "<REPLACED_FOR_POSTING>" --suppression suppression.xml -l log.txt
```

I get the error 

```
[ERROR] Unable to connect to the dependency-check database; analysis has stopped
```

My directory structure has <path_to>/bin and <path_to>/repo in the same directory.

Here is the log file as a result of the run.
[log.txt](https://github.com/jeremylong/DependencyCheck/files/157217/log.txt)

Ps. I realize that this might not be a bug, but something that I have misconfigured.  I have successfully run dependency check several times in the past, though, so I wasn't sure what changed.

**Comment by jeremylong** [comment]
Is the directory that contains the bin and repo 'writeable'? The CLI tool
creates the data directory in that location. Alternatively, you could try
specifying a different data directory (see the `--data` argument here
http://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html
).

Does that help?

--Jeremy

**Comment by frankbryce** [comment]
Unfortunately not, the directory is writable and I'm running as administrator and not with the same error.  In the log, there appears to be a Primary key error in the DB

```
Unique index or primary key violation: "SYS_ID ON PUBLIC.SYS(ID) VALUES ( /* key:1229 */ 24, 0, 3, 'CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_F8C2A57E_4F73_4F3E_86EB_6B51F84FC2E1 START WITH 25569 BELONGS_TO_TABLE')" [23505-176]
```

**Comment by jeremylong** [comment]
What OS are you using? Do you remember which version of dependency-check worked previously for you?

I did a little research on this and it appears to be an issue with H2 (similar issues discused [here](https://groups.google.com/forum/#!topic/h2-database/LfJX1m2h56g)).

--Jeremy

**Comment by frankbryce** [comment]
Windows 10, and the last version that worked for me is 1.3.3.

Also note that I downloaded the tagged versions of 1.3.3 and 1.3.4 on github and built Dependency-Check myself.

**Comment by jeremylong** [comment]
Well that is unfortunate as that is the same OS as me... What about Java version? Does 1.3.3 still work?

**Comment by jeremylong** [comment]
As there has been no-response since the March 12th question - I am closing this issue. if this is still a problem please re-open the issue.

Best Regards,

Jeremy

**Comment by ioverzero** [comment]
Version 1.4. I am having the same issue:

[ERROR] Unable to connect to the dependency-check database; analysis has stopped

I downloaded the cli but when I get the error when running the command:

./dependency-check.sh --project Testing --out /home/user/Documents/project --scan /home/user/Documents/project

**Comment by frankbryce** [comment]
After downgrading to 1.3.3, the issue went away for me.  I have not yet tried 1.4.  It could be possible that downgrading to 1.3.3 worked because I removed some sort of cached file during that process.  I apologize for not responding earlier, I have my github notifications set so that I'll see it in the future.
