### ISSUE TITLE
Dependency Check CLI: NVD URL Access Proxy Authentication Issue

### ISSUE THREAD

**Issue by guptaa6** [dependency-check/DependencyCheck#4570]
Hi

We are facing authentication issue while executing dependency check via batch script and passing proxy configuration through CLI arguments(proxyserver, proxyport, proxypass, proxyuser).  

As per our analysis proxy credentials are not passed via CLI as network logs shows authentication issue with messages as:
a. Access Denied(authentication_failed)
b. Your credentials could not be authenticated: "Credentials are missing". You will not be permitted access until your credentials can be verified.

Also wanted to share that, we are able to successfully access NVD URL via 'cURL' with usage of same proxy credentials passed as CLI arguments in batch script.

CMD Batch Execution Issue logs attached in screenshot for your reference: 
<img width="755" alt="DependencyCheck_NVD_URL_Access_Issue" src="https://user-images.githubusercontent.com/106756178/171796363-b1f83b6d-ad07-480b-98e0-41d41e0521c6.png">
DependencyCheck_NVD_URL_Access_Issue.png

Dependency Check Version Used: 7.1.0

CLI Arguments Reference link: https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html

Batch Script CLI dummy command: dependency-check.bat --project "myproject" --scan C:\dependency-check --out C:\dependency-check\reports --proxyserver <PROXY_SERVER_IP> --proxyport <PROXY_SERVER_PORT> --proxypass <PROXY_USER_PASSWORD> --proxyuser <PROXY_USER>

Please review and suggest us on steps we can take to resolve the issue.

Thanks

**Comment by aikebah** [comment]
What Java version do you use? Looks a lot like https://stackoverflow.com/questions/41806422/java-web-start-unable-to-tunnel-through-proxy-since-java-8-update-111

For which the codebase has the mentioned fix in place
https://github.com/jeremylong/DependencyCheck/blob/c236dbf3b63ad3cc229a6a079a244d354da5ce46/utils/src/main/java/org/owasp/dependencycheck/utils/URLConnectionFactory.java#L99
but maybe for your version of Java they no longer work?

**Comment by aikebah** [comment]
Or maybe it never worked, but people needing this already had the local JVM patched with the same.

See also https://github.com/jeremylong/DependencyCheck/issues/718

**Comment by guptaa6** [comment]
Hi @aikebah 

Thanks for your response.

Wanted to update that issue still persists at our end with suggested change to reactivate the authentication scheme with Java VM arguments(jdk.http.auth.tunneling.disabledSchemes and jdk.http.auth.proxying.disabledSchemes) as empty.

<DEPNDENCY_CHECK_FOLDER>/bin/dependency-check.bat file snapshot for your reference which was modified with suggeted change:
![dependency_check_batch](https://user-images.githubusercontent.com/106756178/173887757-d0ba3a3b-3ef4-42ed-8cfa-57f655be2dd4.png)

Reference Link: https://www.oracle.com/java/technologies/javase/8u111-relnotes.html

Java Version Used at our end: 1.8.0_241

Please find below network logs debug extract for the unauthenticated transaction for your reference:
<img width="415" alt="Network_Logs_15June" src="https://user-images.githubusercontent.com/106756178/173887068-f9129a91-a4db-489b-9813-ccfddc93308d.PNG">

CMD Batch Execution Issue logs attached in screenshot for your reference:
![image](https://user-images.githubusercontent.com/106756178/173887227-3aa0b789-316f-46b4-96b3-e885366436de.png)

Please can you help review and and suggest next steps we can take to resolve the issue.

Thanks

**Comment by aikebah** [comment]
Your screenshot shows a modified, but unsaved batch-file. Are you sure you saved before running?

**Comment by guptaa6** [comment]
Hi @aikebah 

Thanks for the response.

Yes please issue persistence details presented here are with validation done after batch file is saved.

Screenshot shared here was for sample purpose only.

Thanks

**Comment by aikebah** [comment]
Then all that's left would be networktracing the requests to the proxy. It should (based on the config) contain the proxy-authentication, but the response of the proxy that you quote appears to suggest differently. As the channel to the proxy itself is unencrypted you should be able to read the data until the TLS tunnel is being opened to the destination site.
