### ISSUE TITLE
error when running 'java' is not recognized...

### ISSUE THREAD

**Issue by griddd** [dependency-check/DependencyCheck#458]
I recently found this project, but am a bit confused.  When running dependency-check.bat from the command line, I'm getting the error "'java' is not recognized as an internal or external command, operable program or batch file."

Does dependency-check require Java?  I don't have Java on my PC, but would like to run dependency-check against some .NET software.

**Comment by stevespringett** [comment]
Dependency-Check, the tool itself, is written in Java and requires a Java Runtime Environment to be installed on your machine. Dependency-Check is not limited to scanning Java dependencies. It can scan dependencies written for Python, Node.js, and of course .NET including .exe, .dll, and NuGet.

**Comment by griddd** [comment]
Thanks for the info, Steve.
