### ISSUE TITLE
Ability to provide a file of asset CPEs to scan

### ISSUE THREAD

**Issue by jonathangull** [dependency-check/DependencyCheck#4580]
Hi I would like to supply a file with list of assets(hardware,operating system,application) to depdency-check as input to scan. 

e.g ./dependency-check --scan "assets.txt"

a@MacBook-Air bin % cat assets.txt                        
cpe:2.3:h:cisco:isr_4331:-:*:*:*:*:*:*:*
cpe:2.3:o:cisco:ios:15.6\(1.22\)t:*:*:*:*:*:*:*

Is this possible

**Comment by aikebah** [comment]
Hardware and operating system are not in the scope of dependency-check.

Scanning of a list of assets (bill-of-materials) is more the scope of OWASP DependencyTrack: https://dependencytrack.org/
It allows you to upload the bill-of-materials in CycloneDX format which includes a field for listing the CPE.

Not sure whether DependencyTrack analysis includes Hardware and OS CPE vulnerabilities in its scans or only the application CPEs (which is the subset of CPEs that DependencyCheck uses). The CycloneDX SBOM is capable of including operating systems and hardware (devices).
