### ISSUE TITLE
Is there a wrong message about "minimist:1.2.6"?

### ISSUE THREAD

**Issue by NPC-RX** [dependency-check/DependencyCheck#4589]
In a recent dependency check, we noticed a puzzling report.
The version of "minimist" mentioned in the screenshot that is vulnerable is before 1.2.6, and minimist 1.2.6 does not indicate the existence of vulnerabilities.
Is this a wrong message?
![dependencycheckversion](https://user-images.githubusercontent.com/20533538/172972704-e19ad54e-a4e6-4eb8-beb9-51ace5b128d1.png)
![reportissues-minimist1](https://user-images.githubusercontent.com/20533538/172972680-90becc51-daa8-4a56-b9bc-5aa089bbfcc1.png)
![reportissues-minimist2](https://user-images.githubusercontent.com/20533538/172972687-7354aac5-1124-47c6-8f16-596262218839.png)

**Comment by mprins** [comment]
please try with a currently supported version eg 7.1.0 and not one more than a year old
