### ISSUE TITLE
Whitelist of reported CVEs instead of suppressions

### ISSUE THREAD

**Issue by thscheer** [dependency-check/DependencyCheck#4590]
Is there any way to whitelist a reported CVEs with a mitigation (or explanation why the CVE is not in scope), so that the CVE is still reported in the output list (not like suppression where it is completly removed from the output) e.g. using whitlist in risk gate threshholds.

**Comment by aikebah** [comment]
Suppression is not removed from the output, but moved to a (default collapsed) section of the report.
