### ISSUE TITLE
ODC update lock file with updates disabled blocks massive parallel runs of ODC on shared datafolder

### ISSUE THREAD

**Issue by ghost** [dependency-check/DependencyCheck#4604]
**Describe the bug**
When using the same ODC database for multiple parallel executions (around 50), with **updates disabled** (argument `--noupdate`), the ODC executions start hanging after a few seconds/minutes because the ODC database lock file is suddenly present, as if there was an update in progress.

I run ODC with the following command:

```bash
./bin/dependency-check.sh --noupdate --data /mnt/efs/odc_data --scan /my/scan/path/ --project myprojectname --format "JSON" --enableExperimental --out /my/report/path/myprojectname.json'
```

Note that the updates are managed separately with a scheduled execution everyday of the following command (and it works as expected):

**Version of dependency-check used**
The problem occurs using version 7.1.1 of the CLI

**Log file**

```log
[INFO] Lock file found `/mnt/efs/odc_data/odc.update.lock`
[INFO] Existing update in progress; waiting for update to complete
```

The process times out after 15min and it is still in this same state.

**Expected behavior**
No lock file appears (ODC is only supposed to read the database, not write), and the parallel scans works.

**Additional context**

**Comment by aikebah** [comment]
sounds like one of the parallel builds (or some other build using the same data share) is missing the no update flag. Are you sure that there is absolutely no build also using the /mnt/efs/odc_data share parallel to your 50 or so builds that is not using the flag to prevent database updates?

**Comment by ghost** [comment]
Thank you for your quick reply. No other system has access to the `/mnt/efs/odc_data` directory and all ODC executions are run with the `--noupdate` flag.

To give you a bit more context, I use the ODC container image that I run in parallel using a shared NFS for the ODC database. The point is to avoid having to create the ODC database at each run (when starting the image from scratch), so there is only one, shared with all the ODC executions.

**Comment by aikebah** [comment]
Sounds like the massive parallelism is indeed blocking you on I/O level.
For the --no-update ODC CLI takes a write-lock on the database to ensure it will not change, copies the database to a temporary location and then releases the lock.
Then it starts the remainder of its analysis using the copied database.

Going by the size of the database on my system (122Mb) you would need a bandwidth of app. 7 megabyte/s on the I/O to make 50 copies complete within your mentioned 15 minutes (which I assume is a container timeout that you set in your environment; lock acquisition attempts of ODC time out in 40 minutes, which would require app. 2.5 megabyte/s on the I/O.

**Comment by aikebah** [comment]
For such amounts of parallel invocation you may be better off spinning up a database server to hold the CVE database, though be aware that the initial load of CVE data to the database may take a significant amount of time (so typically you would first want to schedule only the dataload and only modify your build configurations once the initial database load has completed). In the past we've seen reports of initial database load taking significantly more than a business day to complete. Subsequent updates are expected to complete in reasonable time when you schedule a daily update process as only the NVD modified datastream needs to be processed.

**Comment by ghost** [comment]
Unfortunately, I cannot change the container timeout, as it runs on AWS Lambda which only allows 15min maximum executions. During these 15 minutes I usually schedule 5 ODC executions (one by one).

If I use a dedicated database, how does it solve the I/O issue? Is the behavior different (a lock file while making a local copy in each execution)?

(I am not worried about the initial database load or its update duration afterwards, but thank you for the useful information)

**Comment by aikebah** [comment]
Dedicated database would be an external Relational database Server (Postgresql, MySql, mariadb, Oracle, MSSQL)... so there is no copying around needed for the H2 database (as H2 supports only a single process interacting with the database it needs to be copied from the ODC data folder to a temporary folder to allow more than one ODC instance to run in parallel)

See also https://jeremylong.github.io/DependencyCheck/data/database.html for the central database support

**Comment by ghost** [comment]
Thank you for the clear explanations. I will try moving to an RDS instance to fix my issues.
