### ISSUE TITLE
Python Dependency check

### ISSUE THREAD

**Issue by anilmukkamala** [dependency-check/DependencyCheck#4605]
I am trying to run dependency check on python project, below is the command that I used. 

dependency-check.bat --project lambda --scan C:/SAST/dw-intrado-lambda-main/src --out C:/Users/anil.mukkamala/Desktop/DC/lambda.html --log C:/Users/anil.mukkamala/Desktop/DC/lambda.log

It is not retruning any issues nor scanning any dependencies. 

Attached is the log file.
[lambda.log](https://github.com/jeremylong/DependencyCheck/files/8901582/lambda.log)

Can I know what would be the possible soulution for this.

**Comment by aikebah** [comment]
Just read [the docs](https://jeremylong.github.io/DependencyCheck/analyzers/index.html) more carefully.

Python is among the **experimental** analyzers... which means they need explicit activation.

For [cli](https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html) that means `--enableExperimental` is required
