### ISSUE TITLE
[FP]: r2dbc-postgresql

### ISSUE THREAD

**Issue by mikehalmamoj** [dependency-check/DependencyCheck#4616]
### Package URl

pkg:maven/org.postgresql/r2dbc-postgresql@0.9.1.RELEASE

### CPE

`cpe:/a:postgresql:postgresql`

### ODC Integration

{"label"=>"Gradle Plugin"}

### ODC Version

7.1.0.1

### Description

r2dbc-postgresql has changed Maven coordinates - the group has changed from `io.r2dbc` to `org.postgresql`.

So [this false positive](https://github.com/jeremylong/DependencyCheck/issues/3004) has come up again - and needs a similar fix.

**Comment by mikehalmamoj** [comment]
Like the GitHub Action 😄. Just be careful, it seems to have slipped in an extra backtick on the cpe.

**Comment by chadlwilson** [comment]
Hmm, this one has been lingering around for a while :-( (the github actions issue with backticks is related to not having the full `:*:*:*` CPE string. If you remove the backticks in your case it will work correctly.

**Comment by aikebah** [comment]
Resolved by #4755
