### ISSUE TITLE
[FP]: jackson-xc

### ISSUE THREAD

**Issue by tobiasstadler** [dependency-check/DependencyCheck#4621]
### Package URl

pkg:maven/org.codehaus.jackson/jackson-xc@1.9.13

### CPE

cpe:2.3:a:fasterxml:jackson-databind:1.9.13:*:*:*:*:*:*:*

### ODC Integration

{"label"=>"Maven Plugin"}

### ODC Version

7.1.1

**Comment by aikebah** [comment]
@tobiasstadler As a side note: Are you aware that this module has changed coordinates ages ago for version 2.x?

https://mvnrepository.com/artifact/org.codehaus.jackson/jackson-xc

**Comment by tobiasstadler** [comment]
Yes, I am well aware of that and I want to get rid of it. But unfortunately it is part of a client library for some external service I have to use.

**Comment by jeremylong** [comment]
approved
