### ISSUE TITLE
How to load the supression.xml from the classpath (via a library)

### ISSUE THREAD

**Issue by EugenMayer** [dependency-check/DependencyCheck#4642]
I have a library project which i build just for the purpose of sharing the owasp supression across different projects.

![image](https://user-images.githubusercontent.com/136934/177202441-c56873cd-3f1e-4952-9ab2-0d3d41d61d25.png)

Now in my projects, i consume this library like this:

```
	implementation("platform.owasp:supressions")
```

and then in the project i want to apply the suppressions the gradle configuration
```
dependencyCheck {
    formats = [ "HTML", "JSON"]
    suppressionFiles = [
            "owasp-dependency-check-suppressions.xml",
    ]
}
```

Still when starting the dependencyCheck is see

```
Unable to read suppression file 'owasp-dependency-check-suppressions.xml'
```

Is the actuall syntax for supressionFiles wrong in that sence. i tried it with `classpath:owasp-dependency-check-suppressions.xml`

gradle plugin 7.1.1
gradle 7.4.2
java 17

**Comment by nhumblot** [comment]
Hi :wave: 

If you want to reference the path of the file, you need to set the relative path from the module root ([sample](https://github.com/nhumblot/owasp-dependency-check-test-directory/commit/20ace5f750b794c2aca213a26ed188b252807302)).

Please let us know if does solve the issue you are facing. :slightly_smiling_face:

**Comment by EugenMayer** [comment]
Thank you. By your suggestion, now using

```
    suppressionFiles = [
            // load from the classpath of the platform-owasp-supressions library
            "src/main/resources/owasp-dependency-check-suppressions.xml",
    ]
```

and still getting 

```
Unable to read suppression file 'src/main/resources/owasp-dependency-check-suppressions.xml'
```

And this is the path in the library

```
 ls src/main/resources/owasp-dependency-check-suppressions.xml 
src/main/resources/owasp-dependency-check-suppressions.xml
```


If i look at your example, it has nothing to do with loading from the classpath, does it? This is just a usual module and a project based filepath to the local supressing.xml? Am i wrong about hat?

As mentioned above, i want to consume the supressings.xml which is in the classpath shipped by a library and is not part of the project i'am applying the dependency check

**Comment by EugenMayer** [comment]
Anything else I could provide to make this question / issue more understandable? Let me know

**Comment by aikebah** [comment]
> I have a library project which i build just for the purpose of sharing the owasp supression across different projects.
> 

I would recommend using a different approach if possible: host the suppressionfile on a web url. In case of a hosted git repository you may even be able to directly reference the raw github/gitlab/bitbucket URL so you don't need a separate webserver for it.
I've successfully used such an approach within my company, in my case using a (public) gitlab pages site instead of direct gitlab repository raw file link, as our gitlab server doesn't allow for unauthenticated access to repositories.

Classpath references are not supported, but URLs are.

**Comment by EugenMayer** [comment]
Are you sure? 

https://github.com/jeremylong/DependencyCheck/issues/1878#issuecomment-487533799

Explicitly uses a library to load the suppressions from. Also on https://jeremylong.github.io/DependencyCheck/dependency-check-gradle/configuration.html unser supressionFile you find

---
The file path to the XML suppression file - used to suppress false positives. The configured value can be a local file path, a URL to a suppression file, or even a reference to a file on the class path (see https://github.com/jeremylong/DependencyCheck/issues/1878#issuecomment-487533799)
---

Thank you for your help

**Comment by aikebah** [comment]
Ah... right I stand corrected. Even resource-loading is supported.

**Comment by EugenMayer** [comment]
Well in this case the question is, how the syntax is expected. At least with gradle this seems not to work with 7.1.1

**Comment by aikebah** [comment]
Worth a try (no guarantees) "/owasp-dependency-check-suppressions.xml" (make explicit that you want to load a resource from the root (no package).

But there is also a chance that this is a Java 17 related issue, with the module- vs classpath tightening up of class- and resource-access.

https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/ClassLoader.html#getResourceAsStream(java.lang.String) is what gets internally used for a 'plain string' (not a `file:` / `http:` / `https:` URL) when that string cannot be resolved as a file from the project root.

**Comment by EugenMayer** [comment]
should we consider upgrading this from question to bugfix, what do you think?

I tried your suggestion, but still i get

Unable to read suppression file '/owasp-dependency-check-suppressions.xml'

Since we are using java17, it might be an issue and i assume we might try working on that, so this might no longer be question?

**Comment by aikebah** [comment]
I'll try to get a similar dummy project setup and see if I can reproduce a working setup on Java 8 and a failing setup on Java 17. (I presume your company is fully on Java 17 so that you can't test whether the setup works for gradle/java8 combo)

**Comment by EugenMayer** [comment]
Hmm yes i will not be able to use java8 here, i would need to create a dummy too. if i may suggest, maybe put that dummy into the examples, surely worth it. not only as the test case but also as a documentation how it should be done. what do you think?

**Comment by fmarot** [comment]
Hello, I use the Maven plugin and not the Gradle one but I think they should behave the same so I want to share what's working in Maven for me:
* I package the supression.xml  in a jar, in a subfolder (so it is located originally in ./src/main/resources/subfolder/supression.xml).
* Then when I want to read it, I reference it as a project dependency and this works just by prefixing with the folder:
```
    <suppressionFiles>
           <!-- common whitelists from elsewhere (from classpath, pulled as Maven dependencies) -->
           <suppressionFile>subfolder/supression.xml</suppressionFile>
    </suppressionFiles>
```
I hope this may help.

**Comment by EugenMayer** [comment]
> Hello, I use the Maven plugin and not the Gradle one but I think they should behave the same so I want to share what's working in Maven for me:
> 
> * I package the supression.xml  in a jar, in a subfolder (so it is located originally in ./src/main/resources/subfolder/supression.xml).
> 
> * Then when I want to read it, I reference it as a project dependency and this works just by prefixing with the folder:
> 
> ```
> 
>     <suppressionFiles>
> 
>            
> 
>            <suppressionFile>subfolder/supression.xml</suppressionFile>
> 
>     </suppressionFiles>
> 
> ```
> 
> I hope this may help.

I do the same? Just without the subfolder. Are you using java11+ since we raised the question of modules being the cause

**Comment by aikebah** [comment]
You need to put the library on the buildscript classpath, not on the dependencies of your project.

So I expect something along the lines of
```gradle
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath ( [ 'org.owasp:dependency-check-gradle:7.1.1',
                 "platform.owasp:supressions" ] )
    }
}
```

to work for your library

**Comment by fmarot** [comment]
> . Are you using java11+ ? since we raised the question of modules being the cause

Yes, using Java 11

**Comment by EugenMayer** [comment]
i now use 

```
buildscript {
    dependencies {
        classpath ( [ 'org.owasp:dependency-check-gradle:7.1.1', "de.kontextwork.dw.platform.owasp:supressions:0.0.6" ] )
    }
}
```

and this works - i can nwo load the resource form the classpath - while using java17. 

Thank you a lot!
