### ISSUE TITLE
java analyzer with the relevant CVEs for a dependency

### ISSUE THREAD

**Issue by jtarchie** [dependency-check/DependencyCheck#465]
We've been evaluating the tool. A _feature_ we noticed with the Ruby Bundle Audit Analyzer is that when a dependency version has a CVE, then when that dependency's version is bumped the CVE is no longer reported by the tool. We are not able to replicate that same behavior with the Java Analyzer and were wondering if this was a feature in that Analyzer or is the feature exclusive to the Ruby Bundle Audit Analyzer?

**Comment by jeremylong** [comment]
This entirely depends upon the data in the NVD and the data collected. If you can provide a specific example (possibly the reports from both scans) I can try to determine what is happening.

That being said, I would still recommend using Bundler Audit for Ruby applications and Retire.js for Node applications. Support was added to dependency-check but the hand currated databases used by those tools will likely provide more accurate results for the languages covered.

--Jeremy

**Comment by jeremylong** [comment]
As no specific example has been provided I am closing this issue. If you can provide a specific example, please re-open the issue.

Best Regards,

--jeremy
