### ISSUE TITLE
[FP]: Hibernate Commons Annotations confused with Hibernate ORM itself

### ISSUE THREAD

**Issue by chadlwilson** [dependency-check/DependencyCheck#4651]
### Package URl

pkg:maven/org.hibernate/hibernate-commons-annotations@3.2.0.Final

### CPE

cpe:/a:hibernate:hibernate_orm

### ODC Integration

{"label"=>"Gradle Plugin"}

### ODC Version

7.2.1

### Description

Hibernate Commons Annotations is a different project, versioned separately to the core "Hibernate ORM", so CVEs against this are misleading and false positives.

See https://mvnrepository.com/artifact/org.hibernate/hibernate-commons-annotations

**Comment by aikebah** [comment]
approved
