### ISSUE TITLE
[FP]: jruby-rack confused for jruby itself

### ISSUE THREAD

**Issue by chadlwilson** [dependency-check/DependencyCheck#4652]
### Package URl

pkg:maven/org.jruby.rack/jruby-rack@1.1.21

### CPE

cpe:/a:jruby:jruby

### ODC Integration

{"label"=>"Gradle Plugin"}

### ODC Version

7.1.1

### Description

jruby-rack is an independent add-on to JRuby, and not the same as JRuby itself. See https://github.com/jruby/jruby-rack and https://mvnrepository.com/artifact/org.jruby.rack/jruby-rack

**Comment by aikebah** [comment]
approved
