### ISSUE TITLE
[FP]: eclipse angus smtp confused for eclipse IDE

### ISSUE THREAD

**Issue by chadlwilson** [dependency-check/DependencyCheck#4653]
### Package URl

pkg:maven/org.eclipse.angus/smtp@1.0.0

### CPE

cpe:/a:eclipse:eclipse_ide

### ODC Integration

{"label"=>"Gradle Plugin"}

### ODC Version

7.1.1

### Description

The Eclipse IDE is a completely different thing to the Eclipse Angus SMTP provider (previously: JavaMail SMTP)

See https://mvnrepository.com/artifact/org.eclipse.angus/smtp and https://projects.eclipse.org/projects/ee4j.angus

**Comment by PaulFridrick** [comment]
Same false positive for me, and for the following packages : 
- pkg:maven/org.eclipse.angus/imap@1.0.0
- pkg:maven/org.eclipse.angus/pop3@1.0.0
- pkg:maven/org.eclipse.angus/smtp@1.0.0
- pkg:maven/org.eclipse.angus/angus-mail@1.0.0

**Comment by chadlwilson** [comment]
Fixed in `7.4.1`
