### ISSUE TITLE
Revision in POM being used to report vulnerability in report

### ISSUE THREAD

**Issue by s3nl** [dependency-check/DependencyCheck#4666]
**Describe the bug**
Hi!

I have the following entry in a project POM:
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns=http://maven.apache.org/POM/4.0.0 xmlns:xsi=http://www.w3.org/2001/XMLSchema-instance
         xsi:schemaLocation=[http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd](http://maven.apache.org/POM/4.0.0%20http:/maven.apache.org/xsd/maven-4.0.0.xsd)>

    <modelVersion>4.0.0</modelVersion>
    <groupId>groupid</groupId>
    <artifactId>artefactId</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <parent>
        <groupId>groupId</groupId>
        <artifactId>artefactId</artifactId>
        <version>5.2.1</version>
    </parent>

    <properties>
        <revision>1.4.0</revision>                   
        <aad.version>5.2.2</aad.version>
    </properties>

So, when Dependency Check is done, it reports the following:
cpe:2.3:a:pivotal_software:spring_framework:1.4.0:*:*:*:*:*:*:*  (Confidence:Low) 

If we change the revision to e.g 1.3.3 it will report:
cpe:2.3:a:pivotal_software:spring_framework:1.3.3:*:*:*:*:*:*:*  (Confidence:Low) 

If we change the revision to 9.9.9 it won't report any vulnerabilities.

How does this work with Dependency Check? Can I still use the revision property in my POM?

**Version of dependency-check used**
The problem occurs using version 7.1.1 of the cli

**Log file**
no logfile (yet) would have to scrub the company names out of it, will take a while, if you really need it, will provide then..

**To Reproduce**
see above description

**Expected behavior**
Expect to be able use the revision property in the POM file

**Additional context**
None.

**Comment by aikebah** [comment]
Behaviour seems appropriate to me. According to what you state the revision property is properly substituted to the version of your library. I suspect from the minimal description that you provide that you encounter is a false-positive CPE match to spring-framework (`pivotal_software:spring_framework`) for your project, so that when the revision-property is low enough you get reports on vulnerabilities of that framework?

**Comment by aikebah** [comment]
Note that for Maven projects you typically get much better results (fewer FPs) when you use the Maven plugin instead of the CLI to scan your project.

`mvn org.owasp:dependency-check-maven:7.1.1:check`
