### ISSUE TITLE
Unable to use mirrored CVE files, "Unrecognized option: --cveUrl20Base"

### ISSUE THREAD

**Issue by functicons** [dependency-check/DependencyCheck#4672]
**Describe the bug**

I'm following this [doc](https://jeremylong.github.io/DependencyCheck/data/cachenvd.html) to run `dependency-check.sh` (v7.1.1) in offline mode with mirrored CVE files. But the flags are not recognized.

```
$ ./bin/dependency-check.sh \
    --cveUrl20Base $NVD/nvdcve-2.0-%d.xml.gz \
    --cveUrl12Base $NVD/nvdcve-%d.xml.gz \
    --cveUrl20Modified $NVD/nvdcve-2.0-Modified.xml.gz \
    --cveUrl12Modified $NVD/nvdcve-Modified.xml.gz \
    --scan ~/tmp \
    --out ~/tmp/cve_scanner 

Unrecognized option: --cveUrl20Base
usage: Dependency-Check Core [--advancedHelp] [--enableExperimental]
       [--exclude <pattern>] [-f <format>] [--failOnCVSS <score>] [-h]
       [--junitFailOnCVSS <score>] [-l <file>] [-n] [-o <path>]
       [--prettyPrint] [--project <name>] [-s <path>] [--suppression
       <file>] [-v]
```

I don't see any of these flags documented at  https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html.

Also the CVE files download with the latest nist-data-mirror looks like the following, no 1.2 or 2.0, only 1.1, and they are json instead of xml files:

```
$ ls -l ~/tmp/cve_db/

-rw-r--r--  1 dagang primarygroup 1.4M Jul 15 17:39 nvdcve-1.1-2002.json.gz
-rw-r--r--  1 dagang primarygroup  165 Jul 15 17:39 nvdcve-1.1-2002.meta
-rw-r--r--  1 dagang primarygroup 425K Jul 15 17:39 nvdcve-1.1-2003.json.gz
-rw-r--r--  1 dagang primarygroup  162 Jul 15 17:39 nvdcve-1.1-2003.meta
...
-rw-r--r--  1 dagang primarygroup 5.7M Jul 15 17:39 nvdcve-1.1-2021.json.gz
-rw-r--r--  1 dagang primarygroup  166 Jul 15 17:39 nvdcve-1.1-2021.meta
-rw-r--r--  1 dagang primarygroup 2.2M Jul 15 17:39 nvdcve-1.1-2022.json.gz
-rw-r--r--  1 dagang primarygroup  165 Jul 15 17:39 nvdcve-1.1-2022.meta
-rw-r--r--  1 dagang primarygroup 798K Jul 15 17:39 nvdcve-1.1-modified.json.gz
-rw-r--r--  1 dagang primarygroup  163 Jul 15 17:39 nvdcve-1.1-modified.meta
-rw-r--r--  1 dagang primarygroup  98K Jul 15 17:39 nvdcve-1.1-recent.json.gz
-rw-r--r--  1 dagang primarygroup  160 Jul 15 17:39 nvdcve-1.1-recent.meta
```

Need help to get this running. Thanks in advance!

**Version of dependency-check used**
The problem occurs using version 7.1.1 of the CLI.

**Log file**
(see above)

**To Reproduce**
(see above)

**Expected behavior**
The documents should be updated to reflect the current status of the CLI.

**Additional context**

**Comment by functicons** [comment]
It seems that I should use `--cveUrlBase` and `--cveUrlModified` according to [1], so [2] should be updated.

[1]: https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html
[2]: https://jeremylong.github.io/DependencyCheck/data/cachenvd.html

**Comment by jeremylong** [comment]
Thanks for pointing out the incorrect documentation. The fix will be published with the next release.
