### ISSUE TITLE
Keep an eye on DWF for possible future inclusion

### ISSUE THREAD

**Issue by dwvisser** [dependency-check/DependencyCheck#468]
Keep an eye on the[ Distributed Weakness Filing project](https://github.com/distributedweaknessfiling/DWF-Documentation). At some point, it may be desirable to expand DependencyCheck to use it in addition to NVD.

**Comment by jeremylong** [comment]
The DWF appears to be assisting in CVE assignments. It does not appear to be a unique vulnerability list. As such, there is no need to include it into ODC.
