### ISSUE TITLE
.bat file doesn't open

### ISSUE THREAD

**Issue by Unbroken09** [dependency-check/DependencyCheck#4689]
Hello, I have a problem. When I try to open the .bat file because I use Windows 10, the app just flashes and then it's gone. I don't know what to do, I just want to solve some problem and now I have more because I know nothing how to use or even run this app. Thanks in advance.

**Comment by jeremylong** [comment]
OWASP dependency-check is a command line tool. Run the `.bat` file from the command prompt.
