### ISSUE TITLE
Support multiple versions on the same Azure DevOps Build Agent

### ISSUE THREAD

**Issue by PascalTurbo** [dependency-check/DependencyCheck#4705]
At the moment you can not use multiple Versions of DependencyCheck using Azure DevOps on the same host because all versions are using the same database that might not be compatible (like the step from v6.x to v7.x).

When using DependencyCheck on a shared Build Agent, every project using this agent must upgrade dependency check version at the same time. It would be better that every version uses its own cache so each project can decide whether or not to upgrade the version

**Comment by jeremylong** [comment]
This is not the correct repository for this issue. If there is an issue or enhancement for the AzureDevOps integration please report it here: https://github.com/dependency-check/azuredevops/issues
