### ISSUE TITLE
Could not execute .NET AssemblyAnalyzer on Azure DevOps after upgrading to Version 7.1.1

### ISSUE THREAD

**Issue by PascalTurbo** [dependency-check/DependencyCheck#4706]
I'm using the latest version of the Azure DevOps Plugin (6.0.0.4). After upgrading DependencyCheck from 6.5.3 to 7.1.1 I get the following error

```
[WARN] An error occurred with the .NET AssemblyAnalyzer, please see the log for more details.
[ERROR] Exception occurred initializing Assembly Analyzer.
[ERROR] Could not execute .NET AssemblyAnalyzer
```

When executing the command on the host directly, it works without errors. I also checked the .net Version in build context but it equals the version set by "--dotnet".

```
/opt/build-agent/_work/_tasks/dependency-check-build-task_47ea1f4a-57ba-414a-b12e-c44f42765e72/6.0.4/dependency-check/bin/dependency-check.sh --project MyProject --scan /opt/build-agent/_work/120/s/**/* --out /opt/build-agent/_work/120/s/dependency-check/ --format JUNIT --format HTML --format JSON --disableYarnAudit --disablePnpmAudit --cveUrlBase=http://192.168.1.25/nvdcve-1.1-%d.json.gz --cveUrlModified=http://192.168.1.25/nvdcve-1.1-modified.json.gz --dotnet /usr/bin/dotnet
```

I double checked the behavior by moving back to 6.5.3 and deleting all the caches - with 6.5.3 it runs smoothly.

**Comment by jeremylong** [comment]
Please consider reading the release notes when upgrading a major version: https://github.com/jeremylong/DependencyCheck/blob/main/RELEASE_NOTES.md#version-700-2022-02-28

The analyzer requires the dotnet core 6.0 runtime to be installed.

**Comment by PascalTurbo** [comment]
@jeremylong dotnet is installed in Version 6.0.100-rc.2.21503.1

**Comment by jeremylong** [comment]
If there are multiple runtimes installed you may need to point ODC to the correct installation using `--dotnet <path>`.

**Comment by PascalTurbo** [comment]
This seems to be Azure DevOps Related so I've created a new issue there https://github.com/dependency-check/azuredevops/issues/106
