### ISSUE TITLE
RubyGemspecAnalyzer doesn't work for Rakefile?

### ISSUE THREAD

**Issue by biancajiang** [dependency-check/DependencyCheck#471]
Even RubyGemspecAnalyzer.java has a FILTER to support both .gemspec and Rakefile:
private static final FileFilter FILTER
            = FileFilterBuilder.newInstance().addExtensions(GEMSPEC).addFilenames("Rakefile").build();

Its analyzeFileType() only uses patterns for .gemspec for all cases:

```
    final Matcher matcher = GEMSPEC_BLOCK_INIT.matcher(contents);  //line 118
    if (matcher.find()) {
    ...
```

So matcher.find() is always false for Rakefile.

Is this an overlook?

**Comment by jeremylong** [comment]
I did not author this plugin - I believe including the Rakefile was in early testing but there are issues with identifying the exact version used. The gemspec file contains more accurate informattion. We likely need to exclude the rakefile from the FileFilter.
