### ISSUE TITLE
InvalidPathException: Illegal char exception when a valid file name containing special character

### ISSUE THREAD

**Issue by manumuve** [dependency-check/DependencyCheck#4716]
We're getting this error with Dependency Check 7.1.1:

`Analysis Exceptions
Illegal char <?> at index 48: ClientApp/dist/assets/images/Titulo_Pol_Protecci?n_Datos.png
exception: java.nio.file.InvalidPathException: Illegal char <?> at index 48: ClientApp/dist/assets/images/Titulo_Pol_Protecci?n_Datos.png`

The file implied is inside a .zip file, and its file name is Titulo_Pol_Protección_Datos.png (please, notice the **ó** character).
This file name is valid in Windows and we don't have any other issue related to it when using other tools, only with Dependency Check.

Is there any way to solve this?
Thanks in advance.

**Comment by aikebah** [comment]
Is there a longer stacktrace you can share? This clearly relates to character set issues while processing filenames from a zip-file, but would like to have some pointers on where exactly in our codebase this exception occurs.

**Comment by aikebah** [comment]
If there is no stacktrace it would also be helpful if you could share a dummy project / scan that exhibits this behavior so that we can reproduce and debug the issue locally.

**Comment by manumuve** [comment]
I think I got it.

It seems that when compressing files with an obsolete version of 7Zip, if the file names contains special characters this info is not stored and the special characters are replaced for some kind of replacement character and can't be processed in some use cases like in GNU/Linux systems or by Java apps like Dependency Check.

Please take a look at this 7Zip discussion thread about it: https://sourceforge.net/p/sevenzip/discussion/45797/thread/dddbd68b23

I have attached the full stacktrace and a .zip with the original file which was throwing the exception and a copy of if, but added to the .zip with the latest 7Zip version. Dependency Check only fails with the first one.




[app.zip](https://github.com/jeremylong/DependencyCheck/files/9226868/app.zip)
[stacktrace.txt](https://github.com/jeremylong/DependencyCheck/files/9226871/stacktrace.txt)
