### ISSUE TITLE
Showing transitive dependencies

### ISSUE THREAD

**Issue by rfc-st** [dependency-check/DependencyCheck#4717]
Hello, 

Is there any way with Dependency Check (or in its roadmap) to show the transitivity of dependencies in a clear way? For example, something similar to:

https://imgur.com/a/oOyf0wp

Or similar to the output of '_mvn dependency:tree_' for Maven and '_npm list_' for NPM.

Thanks!.

**Comment by aikebah** [comment]
No and none is planned. In reports there are the project modules that have it as a (direct or transitive) dependency. From there on you need to use your project dependency management features to deep-dive for the transitive dependencies.
e.g.

![image](https://user-images.githubusercontent.com/2175611/181903801-ac2ce4fe-2325-4a90-b2dd-c129f32de8fa.png)
