### ISSUE TITLE
RubyBundleAuditAnalyzer should disable itself if there's Exception during initialization

### ISSUE THREAD

**Issue by biancajiang** [dependency-check/DependencyCheck#472]
I don't have bundle_audit installed.  when I run a scan, RubyBundleAuditAnalyzer.initializeFileTypeAnalyzer() throws an Exception.  This exception is not currently handled by RubyBundleAuditAnalyzer.

As a result, RubyBundleAuditAnalyzer is still enabled, and later on RubyGemspecAnalyzer gets disabled.  No actual Ruby analyzers are be available in this case.

RubyBundleAuditAnalyzer should disable itself if there's exception during initialization.  As a result, RubyGemspecAnalyzer would be left intact.

**Comment by biancajiang** [comment]
I noticed the build is skipping RubyBundleAuditAnalyzerTest.  Should it be included?  Theoretically it should pass now.

**Comment by jeremylong** [comment]
Still seeing the exception during setup
https://dependency-check.ci.cloudbees.com/job/dependency-check/501/org.owasp$dependency-check-core/testReport/org.owasp.dependencycheck.analyzer/RubyBundleAuditAnalyzerTest/testAnalysis/
which
causes the junit assume (here
https://github.com/jeremylong/DependencyCheck/blob/master/dependency-check-core/src/test/java/org/owasp/dependencycheck/analyzer/RubyBundleAuditAnalyzerTest.java#L67)
to skip the test.

--Jeremy

**Comment by biancajiang** [comment]
Ah!  I overlooked analyzer.initialize() in setup().  I will update that and test with bundle-audit disabled.
