### ISSUE TITLE
Stuck [INFO] Finished Vulnerability Suppression Analyzer (0 seconds)

### ISSUE THREAD

**Issue by callmeurpapa** [dependency-check/DependencyCheck#4724]
this step can take several hours

We see that java uses almost the entire cpu core.

There are now 16 RAM and 16 cores

What is the best place to pay attention to?

**Comment by makeitstatic** [comment]
How did you fix this issue? I also have it.

**Comment by callmeurpapa** [comment]
yap, disable logs ^-^
