### ISSUE TITLE
Dependency check analyze is stuck at 0 percent, gives no error

### ISSUE THREAD

**Issue by RaviFis1** [dependency-check/DependencyCheck#4740]
When running ./gradlew dependencyCheckAnalyze, nothing is happening, no error, no progress

<img width="417" alt="owaspissue" src="https://user-images.githubusercontent.com/99728909/183711115-b9fc1ac5-f3a3-429d-90d0-3c694a4fb538.PNG">

**Comment by BillyBolton** [comment]
Same issue here.
```
<-------------> 0% EXECUTING [12m 4s]
> :internalAPI:dependencyCheckAnalyze
```

I solved it by updating to the most current plugin version: https://plugins.gradle.org/plugin/org.owasp.dependencycheck

**Comment by mhoennig** [comment]
We have version 'org.owasp:dependency-check-maven:7.1.1' running. It worked up until we added these dependencies to our project:
```
    plugin: id 'io.openapiprocessor.openapi-processor' version '2022.2'
    implementation 'org.openapitools:jackson-databind-nullable:0.2.3'
    implementation 'org.modelmapper:modelmapper:3.1.0'
    testImplementation 'io.rest-assured:spring-mock-mvc'
```

Now it gets stuck at 17%:
```
> Task :dependencyCheckAnalyze
Verifying dependencies for project hsadmin-ng
Checking for updates and analyzing dependencies for vulnerabilities
<==-----------> 17% EXECUTING [1m 13s]
> :dependencyCheckAnalyze
```

Purging the database did not help.

**Comment by mhoennig** [comment]
Today it's working like a charm - without any change. Maybe it got stuck fetching some resource? In that case it would be a good idea to have shorter timeouts and stop fetching with a clear error message.

**Comment by aikebah** [comment]
Likely the build was stuck on a stale writelock and would've errorred out after 40 minutes. See also #4910
