### ISSUE TITLE
How to define configuration for dependency check in gradle & kotlin DSL

### ISSUE THREAD

**Issue by ghost** [dependency-check/DependencyCheck#4741]
This is working in groovy Gradle:

```
dependencyCheck {
    autoUpdate=false
    cveValidForHours=1
    format='ALL'
}
```
But how we can rewrite this that it works in Kotlin DSL?

**Comment by aikebah** [comment]
How about reading up in the [fine documentation](https://docs.gradle.org/current/userguide/migrating_from_groovy_to_kotlin_dsl.html) of Gradle
