### ISSUE TITLE
[FP]: r2dbc-postgresql reported as `cpe:2.3:a:postgresql:postgresql:0.9.1:release:*:*:*:*:*:*`

### ISSUE THREAD

**Issue by chadlwilson** [dependency-check/DependencyCheck#4755]
### Package URl

pkg:maven/org.postgresql/r2dbc-postgresql@0.9.1.RELEASE

### CPE

`cpe:2.3:a:postgresql:postgresql:0.9.1:release:*:*:*:*:*:*`

### ODC Integration

{"label"=>"Gradle Plugin"}

### ODC Version

7.1.1

### Description

r2dbc-postgresql is the R2DBC driver for postgres and is completely different to postgresql itself.

**Comment by aikebah** [comment]
approved
