### ISSUE TITLE
RubyBundleAuditAnalyzer lost original file path

### ISSUE THREAD

**Issue by biancajiang** [dependency-check/DependencyCheck#476]
Use RubyBundleAuditAnalyzer to analyze Gemfile.lock will lose the file's original path b/c a temp file is created for each vulnerability found and its path in the temp dir is used.  Eg. from RubyBundleAuditAnalyzerTest.testAnalysis(), the returned dependency looks like:

Dependency{ 
**fileName**='Gemfile-redcarpet678732797223096147.lock',
**actualFilePath**='/var/folders/s4/_lmbxxyd75s4jysxry9qnskr0000gn/T/dctemp/Gemfile-redcarpet678732797223096147.lock',
**filePath**='/var/folders/s4/_lmbxxyd75s4jysxry9qnskr0000gn/T/dctemp/Gemfile-redcarpet678732797223096147.lock'}

I can see why the temp file path is used for more desirable checksum etc.  But shouldn't the original Gemfile.lock file path and name also be preserved?  Like the ArchiveAnalyzer will preserve the logical path of elements inside compressed files with **fileName** and **filePath**, and use **actualFilePath** for the temporarily decompressed path in temp dir.  In this case, it's a gem found inside Gemfile.lock file.  But the real path is not available in any attributes of the dependency.

**Comment by biancajiang** [comment]
Any preference using one path attribute over another?  I'm happy to provide a PR for this.

**Comment by jeremylong** [comment]
Again, I agree with you. The actualFilePath should not be changed; it is not used in the report. But the others, as you have pointed out, can and should be updated to provide the additional information. If you have time to work on this great.

--Jeremt
