### ISSUE TITLE
[FP]: apache-mime4j as apache james server

### ISSUE THREAD

**Issue by twwd** [dependency-check/DependencyCheck#4777]
### Package URl

pkg:maven/org.apache.james/apache-mime4j@0.6

### CPE

cpe:/a:apache:james

### ODC Integration

{"label"=>"Maven Plugin"}

### ODC Version

7.1.2, 7.1.1, 7.0.1, 7.0.0

### Description

This false-positive was already reported in #4213 but the fix doesn't work.

**Comment by aikebah** [comment]
approved
