### ISSUE TITLE
Does DependencyCheck support R language ?

### ISSUE THREAD

**Issue by salnakuruvi** [dependency-check/DependencyCheck#4791]
Does Dependency Check support R language ?

**Comment by mprins** [comment]
DependencyCheck uses packaging/dependency manifests such als `pom.xml`, `package.json` etc. as listed in the documentation: https://jeremylong.github.io/DependencyCheck/analyzers/index.html 

DependencyCheck is not a language agnostic tool, it does not scan code

**Comment by jeremylong** [comment]
At the moment nothing has been built for the R ecosystem. PRs welcome.

**Comment by salnakuruvi** [comment]
Thank you

**Comment by salnakuruvi** [comment]
Thank you
