### ISSUE TITLE
Is there any way to get Software Bill of materials(SBOM) in DependencyCheck?

### ISSUE THREAD

**Issue by chakravarthi2u** [dependency-check/DependencyCheck#4792]
Hi Team,

Is there any way to get Software Bill of materials(SBOM) in DependencyCheck repo? I want to get SBOM list from artifactory using this repo. Is this possible?

Please suggest.

Thanks
Chakravarthi

**Comment by aikebah** [comment]
No clue what you try to achieve. We publish our artifacts in Maven Central, we don't publish an SBOM, but the SBOM can be generated by SBOM generating tools from our pom-file (e.g. the [CycloneDX maven plugin](https://github.com/CycloneDX/cyclonedx-maven-plugin).

From what I find on the web the in the Artifactory ecosystem JFrog appears to offer Xray as a toolset to do just that automatically for you on libraries for which the pom files are published on maven central.

**Comment by davewichers** [comment]
Are you asking if DC can generate an SBOM, like this request: #2233? If so, sounds like this is either really hard, or simply a No, given the issue has been open 2.5 years.

Or do you want an SBOM to be created for DependencyCheck? If that's what you are after, then this project could likely adopt the cyclonedx plugin config specified in the OWASP AntiSamy pom.xml file, which does generate an SBOM as you can see here: https://repo1.maven.org/maven2/org/owasp/antisamy/antisamy/1.7.2/.

**Comment by marcelstoer** [comment]
I feel this should be closed in light of the discussions on linked issues.

**Comment by jeremylong** [comment]
@marcelstoer - I would agree with you on this. While I would be confident in ODC producing an SBOM if you were using the maven or gradle plugin - or if you were using the CLI to scan something that had a lock file.
