### ISSUE TITLE
RetireJS analyzer does not seem to work from the Gradle plugin

### ISSUE THREAD

**Issue by msaubier** [dependency-check/DependencyCheck#4794]
I am attempting to utilize the RetireJS analyzer from the Gradle plugin (v7.1.2), but it doesn't seem to be working.  The JavaScript files I want to scan are showing up on the report, but the package/evidence for most of these files is blank and the scan is not detecting a known vulnerability for jszip.  The JavaScript files that don't seem to be getting scanned properly are located within the "grails-app/assets" scan set folder.  Below is my configuration of the dependencyCheck task in our build.gradle file and a sample of the report showing the missing package/evidence information for jquery and jszip.  I'm not sure if this is a bug or something wrong with how I'm configuring the gradle task.  Any thoughts/advice would be appreciated.

```
dependencyCheck {
    formats=["HTML","JUNIT"]
    suppressionFile="${rootProject.projectDir}/suppression.xml"
    failBuildOnCVSS=7.0

    scanSet = ['./package-lock.json','grails-app/assets','javascript']

    analyzers {
        nodeAudit {
            enabled = true
            yarnEnabled = false
            skipDevDependencies=true
        }

        retirejs {enabled = true}

        assemblyEnabled = false
    }
}
```

![image](https://user-images.githubusercontent.com/45213604/187694222-d66b6c08-9842-47b8-b82c-d9e601b7a0a8.png)

**Comment by jeremylong** [comment]
The retirejs analyzer is likely working as expected as it works exactly like RetireJS. The analyzer does not collect evidence as do other analyzers in ODC - rather it uses the pattern matching within RetireJS. Additionally, only client side JS is enabled in the RetireJS Analyzer. All npm packages should be identified via the npm analyzer (or yarn, pnpm, etc.).

**Comment by msaubier** [comment]
I can confirm it is working as expected.  I will close this ticket.
