### ISSUE TITLE
How to use a custom velocity template for reports?

### ISSUE THREAD

**Issue by gesellix** [dependency-check/DependencyCheck#4799]
We're trying to create a JSON formatted report to ease the integration with our monitoring tools. The existing JSON report doesn't include the overiew/summary like the HTML report, so we're working on a custom template which might be proposed here as soon as we're confident that it makes sense for other users.

Looking at https://github.com/jeremylong/DependencyCheck/blob/d8e090229b238394ee0792db74e47f07ba18fa6a/core/src/main/java/org/owasp/dependencycheck/reporting/ReportGenerator.java#L299-L305 we hoped that a custom report.vsl file could be used via CLI (e.g. as `--format /path/to/report.vsl`), but the CliParser fails at https://github.com/jeremylong/DependencyCheck/blob/041d9b0449e487fa1b3de1b24e00a3efc2eb627a/cli/src/main/java/org/owasp/dependencycheck/CliParser.java#L148-L160

Can you tell how to provide a custom template?

**Comment by gesellix** [comment]
I have opened #4800 as kind of a quick fix, because it seems like the custom templates are already working for the Ant/Maven plugins, and the CliParser being a bit too restrictive.

**Comment by jeremylong** [comment]
This will be included in the next release.

**Comment by gesellix** [comment]
Thanks a lot!
