### ISSUE TITLE
[FP]: easyuploads reported as vaadin

### ISSUE THREAD

**Issue by jeremylong** [dependency-check/DependencyCheck#4806]
### Package URl

pkg:maven/org.vaadin.addon/easyuploads@8.0.1

### CPE

`cpe:2.3:a:vaadin:vaadin:8.0.1:*:*:*:*:*:*:*`

### ODC Integration

{"label"=>"Maven Plugin"}

### ODC Version

7.1.1

### Description
   
_No response_

**Comment by aikebah** [comment]
approved
