### ISSUE TITLE
Plans for the next release?

### ISSUE THREAD

**Issue by gesellix** [dependency-check/DependencyCheck#4825]
Hey @jeremylong, do you have any plans when a new release will be made? We're excited to get https://github.com/jeremylong/DependencyCheck/pull/4800 working, otherwise we have to maintain an ugly workaround in our GitHub Action.
Any feedback is much appreciated. Thanks!

**Comment by jeremylong** [comment]
Sorry for the delay - I've been fairly busy and haven't kept up with the project as much as i would like. I'm hoping monday/tuesday.

**Comment by gesellix** [comment]
Thanks! I surely don't want to put any pressure on you, it's only to get a rough idea when we could check back. If there's any chance to help with the project in general, just ask :)

**Comment by marcelstoer** [comment]
7.2.0 is out

**Comment by gesellix** [comment]
This is great, thanks!
