### ISSUE TITLE
which ca-store in npm version of owasp-dependency-check using?

### ISSUE THREAD

**Issue by enemarke** [dependency-check/DependencyCheck#4837]
Hi

I'm behind a cooperate proxy that is doing TLS inspection. Just doing

`npm install owasp-dependency-check -g`
and running
`owasp-dependency-check`
fails with TLS error.

* I have tried updating systems ca with root cert from our proxy.
* I have tried ignoring ssl on npm level.

I have also tested just downloading the latest version and running the shell script. That I can get to work by updating java keystore with the proxy certificate. 

Any suggestions on where to configure the ca for the npm version?

**Comment by aikebah** [comment]
That's something to check with its authors https://github.com/etnetera/owasp-dependency-check according to google results.

**Comment by aikebah** [comment]
And it depends on what part of dependendency-check CLI (which is what it wraps) runs into the TLS issue.

**Comment by enemarke** [comment]
Thanks. I'll try the other project.
