### ISSUE TITLE
Ability to pre-fetch the CVE data

### ISSUE THREAD

**Issue by RochesterinNYC** [dependency-check/DependencyCheck#484]
Hi, after reading through the docs and the command line help, I can't seem to find any references to an ability to prefetch or download the CVE data before actually trying to scan for vulnerabilities.

It seems that you're able to accomplish this by running DependencyCheck on any directory (including an empty one) as it will download the CVE data before scanning. However, I wanted to check if there was an inherent/supported way to do this before resorting to this workaround.

Thanks for the stellar tool.

**Comment by stevespringett** [comment]
Refer to the --updateonly flag

https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html

**Comment by RochesterinNYC** [comment]
Great, exactly what I'm looking for. Thanks for the reference.
