### ISSUE TITLE
Detected outdated suppressions

### ISSUE THREAD

**Issue by Jurrie** [dependency-check/DependencyCheck#4840]
We are using the OWASP Dependency Check for a while now, and the suppression file has grown. Suppressions get outdated when we bump a dependency to a newer version, or when we bump the version of Dependency Check itself. As a consequence, our suppressions file has some stale suppressions. I would like to clean it up.

I could do that manually, but that would be a lot of tedious work.

Could the OWASP Dependency Check plugin track which suppression it has hit, and when it is done report all suppressions it did not hit? Those suppressions are candidate for removal.

**Comment by mprins** [comment]
This is available in the current release: https://github.com/jeremylong/DependencyCheck/issues/4685

You just need to run with `debug` logging enabled, with Maven use `-X` as a commandline option

**Comment by Jurrie** [comment]
Aah, I totally missed this! Thanks!
