### ISSUE TITLE
Gradle-Plugin Release 7.2.0 not available in public repository

### ISSUE THREAD

**Issue by renegrob** [dependency-check/DependencyCheck#4850]
According to https://jeremylong.github.io/DependencyCheck/dependency-check-gradle/index.html and https://github.com/jeremylong/DependencyCheck/tree/v7.2.0 there should be a version 7.2.0 but the artifacts don't seem to be published (yet?)
I can't finad a version 7.2x on https://plugins.gradle.org/m2/org/owasp/dependency-check-gradle/

**Comment by mprins** [comment]
I've had several projects update semi-automatically since yesterday, so it is at least available from Maven Central without  any problems

**Comment by renegrob** [comment]
It seems to be only an issue for the gradle-plugin: https://search.maven.org/search?q=g:org.owasp%20dependency*

**Comment by renegrob** [comment]
Indeed it seems that https://github.com/dependency-check/dependency-check-gradle has not yet been released, but the project page https://jeremylong.github.io/DependencyCheck/dependency-check-gradle/index.html already references the version 7.2.0. I'm not sure if that's just a temporary inconsistency and normal or a mistake.

**Comment by jeremylong** [comment]
Gradle is not included in the automated release process as it is in a different repository - unfortunately yesterday life happened and I could not get to the gradle or homebrew releases. I am working on them now.
