### ISSUE TITLE
Cannot define proxy server by command line on Maven Plugin

### ISSUE THREAD

**Issue by rcsilva83** [dependency-check/DependencyCheck#4855]
**Describe the bug**
One way to define an HTTP Proxy on Maven is using the JVM properties `http.proxyHost`, `http.proxyPort` and `http.nonLocalHosts`. This can by done by defining `MAVEN_OPTS` or by command line (`mvn package -Dhttp.proxyHost=10.10.0.100 -Dhttp.proxyPort=8080`). However, the Dependency Check Maven plugin isn't respecting these properties and defines the proxy only by `settings.xml`, which is very difficult for me in my use case.

**Version of dependency-check used**
The problem occurs using version 7.2.0 of the maven plugin

**Log file**
https://gist.github.com/rcsilva83/fc447ce4abe8be7cdcb5d362348b3b0f

**To Reproduce**
1. Run `mvn dependency-check:check -Dhttp.proxyHost=myproxyserver -Dhttp.proxyPort=8080 '-Dhttp.nonProxyHosts=host.internal|*.internal'`

**Expected behavior**
Dependency Check Maven plugin uses `myproxyserver:8080` as proxy server.

**Additional context**

**Comment by aikebah** [comment]
Not a bug, the http.proxyHost / http.proxyPort / http.nonProxyHosts system properties are indeed not taken into account by the maven plugin, but while that may not have been what you expected it doesn't constitute a bug.
How to use proxies is documented in our [gitlab pages](https://jeremylong.github.io/DependencyCheck/data/proxy.html) for each of the integrations.

For the [maven plugin](https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html) it's configuring the proxy in the maven settings.xml and then referring to it with the `mavenSettingsProxyId`

`mvn dependency-check:check -DmavenSettingsProxyId=<the id of the desired proxy config in your settings.xml>`

**Comment by rcsilva83** [comment]
The problem is that it's very difficult for me in my build pipeline to configure the proxy on `settings.xml`. Additionally, it opens a door to download dependencies from the Internet instead of our corporate Maven repository, which is very undesirable in my organization. I need the proxy just for the `dependency-check:check` goal, so I can use enable all the analyzers.

Is there is any reason why the system properties are not taken into account?
