### ISSUE TITLE
Add recording compensating controls for vulnerabilty

### ISSUE THREAD

**Issue by kpopple** [dependency-check/DependencyCheck#4864]
**Is your feature request related to a problem? Please describe.**
As a medical device developer, I track the vulnerabilities in several versions of released software.  This software is not easily updated due to the need to verify its safe operation for every change, including cybersecurity patching.   While DependencyTrack is great at listing the vulnerabilities in a specific software version, it would be very nice to be able to attach the compensating controls to a vulnerability.
 
**Describe the solution you'd like**
The compensating controls should be stored in a database table (compensating controls catalog) and which can be referenced by each vulnerability for a product.  The compensating controls should have a field to enter a reference to the external system requirement or requirements (a text field).  It would be nice for a compensating controls GUI page to be able to list all the vulnerabilities and software products using the control.

Each identified vulnerability for a software product would have a list of compensating controls selected from the compensating controls catalog.

**Describe alternatives you've considered**
I am currently using text files for each vulnerability with an analysis of the issue and the associated compensating control.  This is a very poor solution as the compensating controls are not shared and it is not easily managed.   
I have also used spread sheets, which provided a common set of compensating controls to attach to each vulnerability.

**Additional context**
none

**Comment by kpopple** [comment]
An additional field to add is the residual risk (score) after the compensating controls for a vulnerability.

**Comment by aikebah** [comment]
@kpopple You do realize that DepenencyTrack (which you name in your description) is an entirely different project?

Is your proposal for this project, or for [DependencyTrack](https://github.com/DependencyTrack/dependency-track)

Asking as I think DependencyTrack seems to me the more appropriate tool for your scenario (tracking multiple versions of a 'done' product in maintenance over time for newly discovered vulnerabilities in its bill of materials) and this tool is a cleaner fit in my view for the continuous scanning of the latest-and-greatest edition during continued development to avoid releasing a new version without upgrading known-vulnerable components.

**Comment by kpopple** [comment]
Oops, I intended to put that in dependency Track not dependency Check.  They are both good tools for different purposes.

Thanks for letting me know
Ken

**Comment by kpopple** [comment]
You are correct, I accidently entered this in the DependencyCheck issues and not where it belongs in DependencyTrack.

**Comment by kpopple** [comment]
Closing and moving to DependencyTrack.
