### ISSUE TITLE
Sonar detects dependency reports and fails due to having 'html' bugs.

### ISSUE THREAD

**Issue by sspizzirri** [dependency-check/DependencyCheck#4873]
Hi, we implemented python scanner por our Python projects, and when we run sonar-scanner the problem we're having is that sonar looks into these reports and shows lots of bugs and so on.
Is there any way to stop this (And not only excluding this directory from sonar)
Does this issue has to do with where sonar scanner is scanning its files? Like is there an issue with how we define sources and such.
**sonar.project.properties:**
sonar.sources=app
sonar.tests=tests
sonar.test.exclusions=tests/**,migrations/**
sonar.coverage.exclusions=tests/**,migrations/**

How we call the scanner: 
sonar-scanner $SONAR_CLI_VARS
SONAR_CLI_VARS= -Dsonar.qualitygate.wait=true -Dsonar.sourceEncoding=UTF-8 -Dsun.jnu.encoding=UTF-8 -Dfile.encoding=UTF-8 -Dsonar.sources=app -Dsonar.scm.provider=git -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.url=$CI_SERVER_URL -Dsonar.gitlab.api_version=v4

Can someone help me where I'm doing something wrong?
Thanks !

**Comment by aikebah** [comment]
You should check with the sonar documentation how to make it properly scan only your project sources.
