### ISSUE TITLE
Unable to read suppression file after upgrading from 7.1.2 to 7.2.1

### ISSUE THREAD

**Issue by SingingBush** [dependency-check/DependencyCheck#4874]
Using maven I used to have a working config using `${project.basedir}/owasp-suppressions.xml` in the path to _suppressionFile_:

```
    <plugin>
        <groupId>org.owasp</groupId>
        <artifactId>dependency-check-maven</artifactId>
        <version>7.1.2</version>
        <configuration>
            <suppressionFile>${project.basedir}/owasp-suppressions.xml</suppressionFile>
        </configuration>
        <executions>
            <execution>
                <goals>
                    <goal>check</goal>
                </goals>
            </execution>
        </executions>
    </plugin>
```

after bumping the version up to _7.2.1_ I got the following error

```
Error:  Failed to execute goal org.owasp:dependency-check-maven:7.2.1:check (default) on project chargebee-client: One or more exceptions occurred during dependency-check analysis: One or more exceptions occurred during analysis:
Error:  	InitializationException: Warn initializing the suppression analyzer: Failed to load /home/github/_work/my-project/my-project/sub-module/owasp-suppressions.xml, caused by Unable to read suppression file. 
Error:  		caused by SuppressionParseException: Failed to load /home/github/_work/my-project/my-project/sub-module/owasp-suppressions.xml, caused by Unable to read suppression file. 
Error:  	InitializationException: Warn initializing the suppression analyzer: Failed to load /home/github/_work/my-project/my-project/sub-module/owasp-suppressions.xml, caused by Unable to read suppression file. 
Error:  		caused by SuppressionParseException: Failed to load /home/github/_work/my-project/my-project/sub-module/owasp-suppressions.xml, caused by Unable to read suppression file.
```

I was able to work around it by changing to using `./owasp-suppressions.xml`

```
    <plugin>
        <groupId>org.owasp</groupId>
        <artifactId>dependency-check-maven</artifactId>
        <version>7.2.1</version>
        <configuration>
            <suppressionFile>./owasp-suppressions.xml</suppressionFile>
        </configuration>
        <executions>
            <execution>
                <goals>
                    <goal>check</goal>
                </goals>
            </execution>
        </executions>
    </plugin>
```

**Comment by mprins** [comment]
`${project.basedir}` might not be what you think in a multimodule build, but is seems you have redacted the logging so... here's the doc: https://maven.apache.org/guides/introduction/introduction-to-the-pom.html#Available_Variables

**Comment by SingingBush** [comment]
the build log is for a private project. It's not the use of `${project.basedir}` that was the problem though, that's worked perfectly fine since dependency check was added to the project. The only thing that changed when the problem occurred was the change to the version number

**Comment by mprins** [comment]
Maven plugins never see `${project.basedir}` the pom file is expanded during parsing, so it is outside the control of any plugin, plugins just get the path injected.

In any case you will have to provide some means of reproducing your problem.

all I can tell it works without any issues for me in eg. this project: 
https://github.com/B3Partners/brmo/blob/05fb71489fa67a621a1b96e1c837a4f96a080215/pom.xml#L1079-L1090
as you can see in https://github.com/B3Partners/brmo/actions/runs/3079008323/jobs/4974916567

**Comment by jeremylong** [comment]
The reason this "worked" before is that ODC would have logged this as a warning and not bubbled the exception up. If a suppression file is not found the build will fail. Sorry for not making that clear in the release notes - the change was buried in a larger change around how suppression rules are handled.

Consider using `${session.executionRootDirectory}` for aggregate builds? see https://stackoverflow.com/a/7676673/1995422

Alternatively, one could use the `<inherited>false</inherited>` in the plugin configuration for an aggregate build so that ODC is not directly executed in all child projects - rather just executed once at the parent level.
