### ISSUE TITLE
How to use dependency-check offline

### ISSUE THREAD

**Issue by ninjaboy224** [dependency-check/DependencyCheck#4881]
Hi,

I have installed dependency-check to a linux RedHat system which is unable to connect to the internet.

I have mapped a windows drive containing all the nvdcve files to the linux server on mount point /mnt/owasp. So the files I am referring to are nvdcve-1.1-%d.json.gz where %d is 2002 to 2022. I also have nvdcve-1.1-modified.json.gz and nvdcve-1.1-recent.json.gz in that same folder.

I have tried the following command:
dependency-check.sh --propertiesfile dependency-check.properties --scan testapp

where dependency-check.properties is:
cve.url-1.1.modified=file://mnt/owasp/nvdcve-1.1-modified.json.gz
cve.url-1.1.base=file://mnt/owasp/nvdcve-1.1-%d.json.gz

And also:
dependency-check.sh --cveUrlModified /mnt/owasp/nvdcve-1.1-modified.json.gz --cveUrlBase /mnt/owasp/nvdcve-1.1-%d.json.gz --scan testapp

but in each case I receive:
[ERROR] One or more fatal errors occurred
[ERROR] Unable to connect to the dependency-check database

In the logs I see:
DEBUG - Unable to get connection string
java.io.IOException: Unable to create the h2 data directory '/opt/dependency-check/data'

Please can someone advise what I am doing wrong?

**Comment by ninjaboy224** [comment]
I have moved on from this error by running the dependency-check.sh as root user. I now get the following error:
[WARN] Unable to update 1 or more Cached Web DataSource, using local data instead.
[ERROR] One or more fatal errors occurred
[ERROR] Failed to initialise the RetiredJS repo
[ERROR] No documents exist

So running the command again with --noupdate option I get:
[ERROR] Unable to continue dependency-check analysis
[ERROR] One or more fatal errors occurred
[ERROR] No documents exist

**Comment by aikebah** [comment]
See the documentation on online resources: https://jeremylong.github.io/DependencyCheck/data/index.html

Besides the NVD datastreams you should also mirror the RetireJS repository (or disable the RetireJSAnalyzer) and disable the OSSIndexAnalyzer and the Central Analyzer.

See [cli configuration](https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html) page for the necessary configuration options.

If you customize the datafolder (`-d` or `--data`) to a folder that your regular user can write to you should be able to run the CLI as a normal user rather than the root user. The default location is a `data` folder inside the dependency check CLI installation folder. As you installed into a root-only writeable folder structure (under `/opt`) you cannot use the default data location and need to customize it to allow a regular user to run the CLI.

**Comment by ninjaboy224** [comment]
Thank you for your help. I wasn't aware there were other repos that I had to mirror. I will give it a go and feed back.

**Comment by ninjaboy224** [comment]
So I have got it running such that I get no errors and get an Exit Code: 0, but am slightly concerned that I have disabled everything! The command I am running is:
`dependency-check.sh --cveUrlModified file:////mnt/owasp/nvdcve-1.1-modified.json.gz --cveUrlBase file:///mnt/owasp/nvdcve-1.1-%d.json.gz --disableRetireJS --disableOssIndex --disableCentral --disableNodeAudit --log nvd.log--scan testapp
`
An addition to what you advised given that I am running offline, I disabled NodeAudit as it was giving me errors. 

Please can you advise if what I am doing is valid?
Thank you

**Comment by aikebah** [comment]
RetireJS you would be able to remain enabled by also putting a copy of the retireJS repository on your mountpoint side-by-side with the NVD datastream mirror (using `--retireJsUrl <url>` to tell the CLI where you made it available. The URL to the file to mirror you can find on the [CLI configuration page](https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html))

By disabling the OSSIndex and NodeAudit (required as they are online-only vulnerability sources) you increase the chances of missing out on some recent vulnerabilities present in their vulnerability data, but not (yet) accounted for in the NVD datastreams or RetireJS.

By disabling Central analyzer you only have a higher chance of running into false-positives if your projects use jar/zip files that are available at maven central.

**Comment by chovyy** [comment]
> By disabling the OSSIndex and NodeAudit (required as they are online-only vulnerability sources) you increase the chances of missing out on some recent vulnerabilities present in their vulnerability data, but not (yet) accounted for in the NVD datastreams or RetireJS.

It would be nice to have the ability to proxy these services too, see also #5036.
