### ISSUE TITLE
[FP]: kotlin-annotation-processing-gradle incorrectly detected as "processing:processing"

### ISSUE THREAD

**Issue by chadlwilson** [dependency-check/DependencyCheck#4897]
### Package URl

pkg:maven/org.jetbrains.kotlin/kotlin-annotation-processing-gradle@1.7.20 

### CPE

`cpe:2.3:a:processing:processing:1.7.20:*:*:*:*:*:*:*`

### ODC Integration

{"label"=>"Gradle Plugin"}

### ODC Version

7.2.1

### Description

The Kotlin Annotation Processing library is not the same thing as Processing Foundation (https://github.com/processing/processing4/)

**Comment by jeremylong** [comment]
approved
