### ISSUE TITLE
[FP]: testcontainers-mariadb confused for actual mariadb database

### ISSUE THREAD

**Issue by chadlwilson** [dependency-check/DependencyCheck#4898]
### Package URl

pkg:maven/org.testcontainers/mariadb@1.17.3

### CPE

`cpe:2.3:a:mariadb:mariadb:1.17.3:*:*:*:*:*:*:*`

### ODC Integration

{"label"=>"Gradle Plugin"}

### ODC Version

7.2.1

### Description

The testcontainers MariaDB extensions is different to MariaDB itself :-)

**Comment by jeremylong** [comment]
approved
