### ISSUE TITLE
[FP]: r2dbc-mariadb confused for MariaDB itself

### ISSUE THREAD

**Issue by chadlwilson** [dependency-check/DependencyCheck#4899]
### Package URl

pkg:maven/org.mariadb/r2dbc-mariadb@1.1.2 

### CPE

`cpe:2.3:a:mariadb:mariadb:1.1.2:*:*:*:*:*:*:*`

### ODC Integration

{"label"=>"Gradle Plugin"}

### ODC Version

7.2.1

### Description

The R2DBC driver for MariaDB is not the same thing as MariaDB itself.

**Comment by aikebah** [comment]
approved
