### ISSUE TITLE
[FP]: testcontainers-mysql confused for MySQL DB itself

### ISSUE THREAD

**Issue by chadlwilson** [dependency-check/DependencyCheck#4900]
### Package URl

pkg:maven/org.testcontainers/mysql@1.17.3 

### CPE

`cpe:2.3:a:mysql:mysql:1.17.3:*:*:*:*:*:*:*`

### ODC Integration

{"label"=>"Gradle Plugin"}

### ODC Version

7.2.1

### Description

The TestContainers MySQL extension is not the same thing as the MySQL DB itself.

**Comment by aikebah** [comment]
approved
