### ISSUE TITLE
[FP]: accessors-smart-1.2.jar

### ISSUE THREAD

**Issue by jeremylong** [dependency-check/DependencyCheck#4907]
### Package URl

pkg:maven/net.minidev/accessors-smart@1.2

### CPE

`cpe:2.3:a:json-smart_project:json-smart-v1:1.2:*:*:*:*:*:*:*`

### ODC Integration

{"label"=>"Gradle Plugin"}

### ODC Version

7.2.1

### Description

accessors-smart-1.2.jar is identified incorrectly as json-smart.

**Comment by aikebah** [comment]
approved
