### ISSUE TITLE
Sonar not showing vulnerabilities on it's UI except for master branch

### ISSUE THREAD

**Issue by sspizzirri** [dependency-check/DependencyCheck#4911]
Hello,
I'm having this issue, where the only time sonar blocks my Pipeline is on branch master.
The rest of branchs or features, sonar isn't even blocking me and also not showing the vulnerabilities on Vulnerabilites section. 
The thing is, if I go to more-> dependency-check, I can see the report and It's vulnerabilities.
Can someone guide me a little bit? 
I'm using 7.2.1 on the .sh and 2.0.8 on the sonar plugin.
![Captura de Pantalla 2022-10-06 a la(s) 17 19 27](https://user-images.githubusercontent.com/48492915/194410512-99ed594d-0675-41a5-bdf8-0ffca196ec3e.png)
![image](https://user-images.githubusercontent.com/48492915/194410573-02fbef5e-2229-44c0-8bfa-fe862b583f2c.png)

**Comment by aikebah** [comment]
assuming that you also run dependencycheck on your branches' build pipelines this question is likely better addressed to the dependency-check sonarqube plugin: https://github.com/dependency-check/dependency-check-sonar-plugin.

**Comment by sspizzirri** [comment]
> assuming that you also run dependencycheck on your branches' build pipelines this question is likely better addressed to the dependency-check sonarqube plugin: https://github.com/dependency-check/dependency-check-sonar-plugin.

Yes, actually I added a comment in an existing thread. But is not as quick as maybe posting it here. Nevertheless, thanks a lot for the help!
