### ISSUE TITLE
Unable to see Vulnerabilities reported by dependency-check

### ISSUE THREAD

**Issue by kunal-deshmukh-deltatre** [dependency-check/DependencyCheck#4924]
Hello @jeremylong ,

We have installed the Enterprise Sonarqube server on-prem and pushing project analysis and dependency-check results to this server. But Sonarqube Server is not able to display vulnerabilities that are found by dependency-check. Though we are able to see HTML reports on sonar. 
This is happening for any kind of project (MSBuild, Typescript, or Java).

But If I spin up the local Sonarqube server and do the analysis locally with dependency-check it works perfectly fine as expected. 

We have also installed Dependency-Check Plugin on the SonarQube server.

SonarQube Version : Version 9.6.1
dependency-check: version 7.2.1

Let me know if you need more information. We are kind of stuck and unable to understand why it is not working on Hosted SonarQube Server

**Comment by mprins** [comment]
It seems a SonarQube problem,  not a Dependency-Check, I suggest you contact SonarQube

**Comment by jeremylong** [comment]
The sonar plugin is here: https://github.com/dependency-check/dependency-check-sonar-plugin 

Please raise this issue on the sonar plugin's repo.
