### ISSUE TITLE
[FP]: azure-resourcemanager-appplatform

### ISSUE THREAD

**Issue by laurentgo** [dependency-check/DependencyCheck#4931]
### Package URl

pkg:maven/com.azure.resourcemanager/azure-resourcemanager-appplatform@2.19.0

### CPE

cpe:2.3:a:microsoft:platform_sdk:2.19.0:*:*:*:*:*:*:*

### ODC Integration

{"label"=>"Maven Plugin"}

### ODC Version

7.2.1

**Comment by aikebah** [comment]
approved
