### ISSUE TITLE
[FP]: Apache Datasketches mistaken for Sketch

### ISSUE THREAD

**Issue by laurentgo** [dependency-check/DependencyCheck#4932]
### Package URl

pkg:maven/org.apache.datasketches/datasketches-java@2.0.0

### CPE

cpe:2.3:a:sketch:sketch:2.0.0:*:*:*:*:*:*:*

### ODC Integration

{"label"=>"Maven Plugin"}

### ODC Version

7.2.1

### Description

Apache DataSketches (https://datasketches.apache.org/) is being mistaken for Sketch (https://www.sketch.com)

**Comment by aikebah** [comment]
approved
