### ISSUE TITLE
is Brewfile supported?

### ISSUE THREAD

**Issue by pappalar** [dependency-check/DependencyCheck#4937]
Hello! 
I would like to use dependency-check to verify vulnerabilities in dependencies locked via Brewfile.

Is this something the tool supports?

**Comment by aikebah** [comment]
brew files are not supported. All available analyzers (some of which only available as 'experimental') are listed at our [github page on the analyzers](https://jeremylong.github.io/DependencyCheck/analyzers/index.html)
