### ISSUE TITLE
[FP]: Apache Flink Hadoop FS artifact interpreted as Apache Hadoop

### ISSUE THREAD

**Issue by laurentgo** [dependency-check/DependencyCheck#4940]
### Package URl

pkg:maven/org.apache.flink/flink-hadoop-fs@1.15.1

### CPE

cpe:2.3:a:apache:hadoop:1.15.1:*:*:*:*:*:*:*

### ODC Integration

{"label"=>"Maven Plugin"}

### ODC Version

7.2.1

### Description

The Apache Flink artifact used to use the Hadoop FileSystem API is confused with the Apache Hadoop artifacts themselves

**Comment by aikebah** [comment]
approved
