### ISSUE TITLE
[FP]:  Flink Akka RPC loader matches Akka

### ISSUE THREAD

**Issue by laurentgo** [dependency-check/DependencyCheck#4941]
### Package URl

pkg:maven/org.apache.flink/flink-rpc-akka-loader@1.15.1 

### CPE

cpe:2.3:a:akka:akka:1.15.1:*:*:*:*:*:*:*

### ODC Integration

{"label"=>"Maven Plugin"}

### ODC Version

7.2.1

### Description

The Apache Flink Akka RPC loader is detected as belonging to the Akka project.

**Comment by aikebah** [comment]
approved
