### ISSUE TITLE
[FP]: Apache HBase Hadoop compatibility matches Apache Hadoop

### ISSUE THREAD

**Issue by laurentgo** [dependency-check/DependencyCheck#4942]
### Package URl

pkg:maven/org.apache.hbase/hbase-hadoop-compat@2.2.0

### CPE

cpe:2.3:a:apache:hadoop:2.2.0:*:*:*:*:*:*:*

### ODC Integration

{"label"=>"Maven Plugin"}

### ODC Version

7.2.1

### Description

The Apache HBase Hadoop compat library (which allows Hbase to work with multiple versions of Apache Hadoop) is mistaken for one of the Apache Hadoop libraries themselves

**Comment by aikebah** [comment]
approved
