### ISSUE TITLE
[FP]: Apache HBase Zookeeper helper matches Apache Zookeeper

### ISSUE THREAD

**Issue by laurentgo** [dependency-check/DependencyCheck#4944]
### Package URl

pkg:maven/org.apache.hbase/hbase-zookeeper@2.2.0

### CPE

cpe:2.3:a:apache:zookeeper:2.2.0:*:*:*:*:*:*:*

### ODC Integration

{"label"=>"Maven Plugin"}

### ODC Version

7.2.1

### Description

The Apache HBase Zookeeper artifact (which contains classes used by HBase to interact with Zookeeper) is mistaken for Apache Zookeeper itself

**Comment by aikebah** [comment]
approved
