### ISSUE TITLE
[FP]: Apache Iceberg catalog for Hive Metastore matches Apache Hive

### ISSUE THREAD

**Issue by laurentgo** [dependency-check/DependencyCheck#4946]
### Package URl

pkg:maven/org.apache.iceberg/iceberg-hive-metastore@0.14.1

### CPE

cpe:2.3:a:apache:hive:0.14.1:*:*:*:*:*:*:* 

### ODC Integration

{"label"=>"Maven Plugin"}

### ODC Version

7.2.1

### Description

The Apache Iceberg catalog for Hive Metastore is mistaken for Apache Hive itself

**Comment by aikebah** [comment]
approved
