### ISSUE TITLE
[FP]: PF4J library matches Sonatype Nexus

### ISSUE THREAD

**Issue by laurentgo** [dependency-check/DependencyCheck#4947]
### Package URl

pkg:maven/org.pf4j/pf4j@3.6.0 

### CPE

cpe:2.3:a:sonatype:nexus:3.6.0:*:*:*:*:*:*:*

### ODC Integration

{"label"=>"Maven Plugin"}

### ODC Version

7.2.1

### Description

PF4J library is being mistaken for Sonatype Nexus product

**Comment by aikebah** [comment]
approved
