### ISSUE TITLE
[FP]: Opentracing gRPC instrumentation matches gRPC

### ISSUE THREAD

**Issue by laurentgo** [dependency-check/DependencyCheck#4948]
### Package URl

pkg:maven/io.opentracing.contrib/opentracing-grpc@0.2.0

### CPE

cpe:2.3:a:grpc:grpc:0.2.0:*:*:*:*:*:*:*

### ODC Integration

{"label"=>"Maven Plugin"}

### ODC Version

7.2.1

### Description

OpenTracing instrumentation library for gRPC is mistaken for gRPC itself

**Comment by aikebah** [comment]
approved
