### ISSUE TITLE
[FP]: Protobuf Jackson library matches gRPC

### ISSUE THREAD

**Issue by laurentgo** [dependency-check/DependencyCheck#4949]
### Package URl

pkg:maven/org.curioswitch.curiostack/protobuf-jackson@1.2.0

### CPE

cpe:2.3:a:grpc:grpc:1.2.0:*:*:*:*:*:*:*

### ODC Integration

{"label"=>"Maven Plugin"}

### ODC Version

7.2.1

### Description

The Jackson external library for protobuf messages is mistaken for gRPC itself

**Comment by aikebah** [comment]
approved
