### ISSUE TITLE
[FP]: Apache Twill Zookeeper library matches Apache Zookeeper

### ISSUE THREAD

**Issue by laurentgo** [dependency-check/DependencyCheck#4952]
### Package URl

pkg:maven/org.apache.twill/twill-zookeeper@0.14.0

### CPE

cpe:2.3:a:apache:zookeeper:0.14.0

### ODC Integration

{"label"=>"Maven Plugin"}

### ODC Version

7.2.1

### Description

Apache Twill client for Zookeeper is mistaken for Apache Zookeeper itself

**Comment by aikebah** [comment]
approve

**Comment by aikebah** [comment]
approved
