### ISSUE TITLE
Will Dependency Check able to identify Jquery and Bootstrap vulnerabilities in our code

### ISSUE THREAD

**Issue by Mridulau** [dependency-check/DependencyCheck#4955]
Hi @jeremylong 

Please let us know if Dependency check tool can scan Jquery and Bootstrap. If yes where it is displayed in report?
Currently we are 6.5.3 version.

**Comment by jeremylong** [comment]
it entirely depends on how you are using these libraries. If you are using a Maven/Gradle project and are using webjars - then absolutely. If you have the files in the repository and are using the RetireJS analyzer they should be flagged if a known vulnerable version is used.

If you are referencing JQuery on a CDN - ODC would not find this.
