### ISSUE TITLE
System.Threading.Tasks.Extensions.dll is considered low Dependency Check

### ISSUE THREAD

**Issue by sabreKarlo** [dependency-check/DependencyCheck#4957]
System.Threading.Tasks.Extensions:4.5.2, the task confidence is considered low in dependency check. Is there any workaround for this? Can help to find an answer with this?

**Comment by jeremylong** [comment]
https://jeremylong.github.io/DependencyCheck/general/internals.html
https://jeremylong.github.io/DependencyCheck/general/thereport.html
https://jeremylong.github.io/DependencyCheck/general/suppression.html

See the above three links. I'm not sure what your question is exactly - the confidence is just how confident ODC is that the CPE was identified correctly.
