### ISSUE TITLE
OSS Index Analyzer - returning 500 when '/' is URL encoded

### ISSUE THREAD

**Issue by davetobin** [dependency-check/DependencyCheck#4958]
**Describe the bug**
Already raised an issue in https://github.com/sonatype/ossindex-public but raising here in case it should be handled in Dependency Check. Feel free to close.

It looks like Dependency Check 6.5.3 URL encodes `/` to `%2F` and currently it appears that requesting a component-report returns 500 due to this.

Full details here: https://github.com/sonatype/ossindex-public/issues/38

**Version of dependency-check used**
The problem occurs using version 6.5.3 of the maven plugin.

**Comment by jeremylong** [comment]
Do you have a sample npm project that causes this error that you can share?

**Comment by davetobin** [comment]
@jeremylong I don't, unfortunately, but it looks like the issue has been resolved now. Thanks!

Dependency check and api calls that were failing yesterday are working now as expected, returning 200.

```
curl -X 'POST' \
  'https://ossindex.sonatype.org/api/v3/authorized/component-report' \
  -H 'accept: application/vnd.ossindex.component-report.v1+json' \
  -H 'authorization: Basic $TOKEN' \
  -H 'Content-Type: application/vnd.ossindex.component-report-request.v1+json' \
  -d '{
  "coordinates": [
    "pkg:npm/%40babel%2Fplugin-transform-unicode-regex@7.18.6"
  ]
}
'
```
now returns
```
200
[
  {
    "coordinates": "pkg:npm/%40babel%2Fplugin-transform-unicode-regex@7.18.6",
    "reference": "https://ossindex.sonatype.org/component/pkg:npm/%40babel%2Fplugin-transform-unicode-regex@7.18.6?utm_source=mozilla&utm_medium=integration&utm_content=5.0",
    "vulnerabilities": []
  }
]
```
