### ISSUE TITLE
Request scanning in profiles.

### ISSUE THREAD

**Issue by CasperNLD** [dependency-check/DependencyCheck#4964]
Hi,

I have found out that if a dependency is within a profile, that it is not checked.
When i moved the dependency into the generic section, I do get the right warnings.

I would like to have the dependencies checked of the active profiles. And I would like to have an option to scan all the profiles, even the non-active ones.
This would be a big help.

**Comment by jeremylong** [comment]
The dependencies in the active profile are scanned by default. Scanning all profiles is a bit more of a challenge...

**Comment by CasperNLD** [comment]
Hi, 
You are right, active profile is indeed checked.
With a clean project I did get a correct warning. 

I now found out that the problem lies in dependencies of a plugin that are not checked.
```
        <profile>
            <id>sonar</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.gmaven</groupId>
                        <artifactId>groovy-maven-plugin</artifactId>
                        <version>2.0</version>
                        <executions>
                            <execution>
                                <id>workaround</id>
                                <phase>validate</phase>
                                <goals>
                                    <goal>execute</goal>
                                </goals>
                                <configuration>
...
                                </configuration>
                            </execution>
                        </executions>
                        <dependencies>
                            <dependency>
                                <groupId>org.codehaus.groovy</groupId>
                                <artifactId>groovy-all</artifactId>
                                <version>2.1.5</version>
                            </dependency>
                        </dependencies>
                    </plugin>
```
I will rewrite it. 
Checking within all profiles would still be a help, since we work with multiple parents and before we 'use' the profile, we need to update several parent to get this fixed.
However, now on our part this would be less urgent.
Thanks in advance for considering.

**Comment by CasperNLD** [comment]
Rewriting it, means duplication of the versions and that would negate any simplifying we are trying to achieve.
So it seems that this issue is related to #4035.
This item can be closed and I will add my vote to that issue.

**Comment by jeremylong** [comment]
@CasperNLD regarding scanning profiles - as stated that would be fairly difficult. However, if you ensured that every dependency (even those in profiles) was also listed in the DependencyManagement section - you could then include the dependency management section in the scan via configuration.
