### ISSUE TITLE
Getting a java error in a CVE check on launch

### ISSUE THREAD

**Issue by mushu999** [dependency-check/DependencyCheck#4966]
Is this something wrong on *my* system? Here is the error:
```
[INFO] Processing Started for NVD CVE - 2021
Oct 19, 2022 1:48:15 PM com.fasterxml.jackson.module.blackbird.util.ReflectionHack$Java9Up init
WARNING: Unable to find Java 9+ MethodHandles.privateLookupIn.  Blackbird is not performing optimally!
java.lang.NoSuchMethodException: no such method: java.lang.invoke.MethodHandles.privateLookupIn(Class,Lookup)Lookup/invokeStatic
        at java.lang.invoke.MemberName.makeAccessException(Unknown Source)
. . .
```
So do I need to update my Java installation? This is version 7.3.0 of dependency-check code on Windows 10. I run it like I always do. Just updated from ver 7.1.1 and left the **data** directory from the earlier version.

**Comment by mprins** [comment]
Where is the ERROR? I only see a WARNING...

> So do I need to update my Java installation?

you have not told us which version you are using, so it is difficult to advise

**Comment by jeremylong** [comment]
This is an expected warning when running on Java 8. See other projects responses: https://issuehint.com/issue/dropwizard/dropwizard/5318#84997997

Everything will still work as expected.
