### ISSUE TITLE
CPE CVE Mapping

### ISSUE THREAD

**Issue by parimala-kathir** [dependency-check/DependencyCheck#4973]
[hadoop-0.13.0-core.jar] This is my jar. We need to analyze whether this has known vulnerabilities or not. 

As per Dependency checker(5.3.2) the corresponding CPE mapped with 5 CVEs
-------------------cpe:2.3:a:apache:hadoop:0.13.0:*:*:*:*:*:*:* |   | CRITICAL | 5

But as per Dependency checker(7.3.0) the corresponding CPE mapped with 0 CVEs
-------------------hadoop-0.13.0-core.jar |   |   |   | 0

**Comment by jeremylong** [comment]
So - have you actually looked at the CVEs to know if they are correct? 5.3.2 is old and unsupported - many bugs and false positives have been fixed since then.

**Comment by parimala-kathir** [comment]
NVD also shows 5 CVEs for CPE (cpe:2.3:a:apache:hadoop:0.13.0:*:*:*:*:*:*:*)

**Comment by parimala-kathir** [comment]
If NVD shows crct result then is there any bug/issue in 7.3.0
