### ISSUE TITLE
Could reach Database

### ISSUE THREAD

**Issue by Mridulau** [dependency-check/DependencyCheck#4980]
Hi Jeremylong,

Currently we are using version 6.2.2 which was worling fine all these days. From last 1 week it giving the below error. And we are not connected to the interenet.

Error:

[Dependency] [ERROR] Exception occurred initializing Jar Analyzer.
[Dependency] [ERROR] Unable to create temp directory '/tmp/dctemp1c3a6260-05ec-4481-8430-61fd556f1894/check9174020675887913617tmp/70'.
[Dependency] [ERROR] Unable to create temp directory '/tmp/dctemp1c3a6260-05ec-4481-8430-61fd556f1894/check9174020675887913617tmp/71'.
[Dependency] [ERROR] Unable to create a temporary file
[Dependency] [ERROR] An exception occurred accessing the database

Can you please guide on resolving this issue.  Why its giving error as that it cannot access database?
How to fix this error?
we are using linux environment
and gradle plugin

Thank you,
Mridula U

**Comment by aikebah** [comment]
looks like someone changed permissions of the user that runs dependencycheck in a way that prevents it from creating folder structures within `/tmp` or your `/tmp`  is running out of space (or available inodes). As it reports an error on creation of the temporary folder where it copies information so that the scan can run in isolation of other parallel runs of dependencycheck.

**Comment by aikebah** [comment]
gut feel would be the out-of-space/inodes condition, as I otherwise would expect the issue to already be reported on the initial folder (`/tmp/dctemp1c3a6260-05ec-4481-8430-61fd556f1894`) rather than more deeply nested in the folder structures

**Comment by aikebah** [comment]
Oh... and on second read... it's not the isolated-copy datafolder,  but the folder where it temporarily extracts an archive for detailed analysis.

**Comment by aikebah** [comment]
Nevertheless I would recommend to update to a current version as there have been many fixes for false positives in between 6.2.2 and 7.3.1
