### ISSUE TITLE
Is there a front-end to DependencyCheck to allow checking code over the network?

### ISSUE THREAD

**Issue by mushu999** [dependency-check/DependencyCheck#4987]
I'd like to set up DC to run n an internal server at work and have a front end that lets our other developers go to a webpage and enter the UNC path to their root codebase and select certain options, perhaps a cookie-based exclusion list, and then perform a code analysis and return the results in a popup webpage window.

Rather than reinvent the wheel, wondering if anyone else has already done something like this or knows where I might find more info on building this?

**Comment by mprins** [comment]
Have your CI service do it on development branches

**Comment by jeremylong** [comment]
There is no UI/web-app for dependency-check. Take a look at dependency-track - it works differently then dependency-check and may suite your needs.
