### ISSUE TITLE
What is the idea with the generated suppressions?

### ISSUE THREAD

**Issue by marcelstoer** [dependency-check/DependencyCheck#4992]
A [ton of FP issues](https://github.com/jeremylong/DependencyCheck/issues?q=is%3Aissue+generatedsuppressions+is%3Aclosed) were resolved with near zero human intervention - fantastic! However, I didn't find any information yet what the intention of https://github.com/jeremylong/DependencyCheck/tree/generatedSuppressions is. 

Should it become part of the ["real" base file](https://github.com/jeremylong/DependencyCheck/blob/main/core/src/main/resources/dependencycheck-base-suppression.xml) at some point? Or, more generally, how are we supposed to use the generated file?

**Update**
By poking through the commits on [false-positive-approvals.yml](https://github.com/jeremylong/DependencyCheck/blob/main/.github/workflows/false-positive-approvals.yml) I found #4723 which appears to have kick-started this. #4901 is related.

Based on what I learned from the linked issues and code changes they initiated I conclude that

- in order to use the 30+ FP suppressions that were automatically processed in recent weeks I need to set `-DsuppressionFiles=https://jeremylong.github.io/DependencyCheck/suppressions/publishedSuppressions.xml`  - at least until 8.0 is released.

@jeremylong @aikebah Correct?

**Comment by aikebah** [comment]
@marcelstoer correct. The automated usage of it is scheduled for the 8.x release and until it's out you can add `https://jeremylong.github.io/DependencyCheck/suppressions/publishedSuppressions.xml` to your own suppressionfile(s) (if any) to benefit from the fast-tracked suppressions resulting from the automation after core committer approval.

**Comment by marcelstoer** [comment]
Thanks for the confirmation. What triggered this question was the fact that I found those 30+ FP fixes merged but not being part of the 7.2.0, 7.2.1 or 7.3.0 releases - they only went into the generated file AFAIU. Would it make sense to regularly transfer the generated suppressions manually to `dependencycheck-base-suppression.xml` until 8.0 is out, assuming there will be more 7.x releases before 8.0?

**Comment by jeremylong** [comment]
Also see https://github.com/jeremylong/DependencyCheck/pull/5004. I meant to do this on earlier 7.x releases (since we started generating the file).

**Comment by marcelstoer** [comment]
Sorry to bother you again. 8.0 isn't out yet but https://jeremylong.github.io/DependencyCheck/suppressions/publishedSuppressions.xml is now a 404? Is that intentional?

[95b86db39eeb21c980f59a8d020f962dc1ae0fe0](https://github.com/jeremylong/DependencyCheck/commit/95b86db39eeb21c980f59a8d020f962dc1ae0fe0) from December 4th in the `gh-pages` branch removed this file.

**Comment by aikebah** [comment]
@jeremylong gut feel is this is an unanticipated side-effect of the release workflow?

**Comment by jeremylong** [comment]
@aikebah see https://github.com/jeremylong/DependencyCheck/pull/5120

**Comment by marcelstoer** [comment]
@jeremylong thanks for restoring the file 👍
