### ISSUE TITLE
No cpes with <part> = o || h included

### ISSUE THREAD

**Issue by vulnchecker** [dependency-check/DependencyCheck#500]
Hi Jeremy,

my company is trying to use DependencyCheck Core API (Version 1.3.6) for scanning all assets like applications, hardware components, operating systems for vulnerabilities.

For the matching to our hardware components and operating systems, we need the cpes like
'cpe:/o...' or 'cpe:/h...' besides the already included ones ('cpe:/a...'). Not your issue, but you know how we can fix this? There should be a kind of filter which is doing that.

We are using a MySQL Database (Schema Version 3.0) if this information helps you.

**Comment by jeremylong** [comment]
I would really caution against using this - the methodology used by dependency-check works when sufficient evidence is able to be collected (see [How dependency-check works](http://jeremylong.github.io/DependencyCheck/general/internals.html)). I really don't know if you'll be able to gather enough data to perform correct identification.

Given this; if you really want to update dependency-check to include other types of CPE (hardware, os) you could clone the repo; update [line 85 of the CPEHandler](https://github.com/jeremylong/DependencyCheck/blob/master/dependency-check-core/src/main/java/org/owasp/dependencycheck/data/update/cpe/CPEHandler.java#L85).

Does that help?

**Comment by stevespringett** [comment]
This enhancement would also be useful for Dependency-Track or any other application that leverages the API and provides their own evidence.

**Comment by jeremylong** [comment]
An additional property was created to control the "starts with" filter. See [dependency-check.properties](https://github.com/jeremylong/DependencyCheck/blob/master/dependency-check-core/src/main/resources/dependencycheck.properties#L62). As this is not intended to be used for dependency-check maven, gradle, etc. it is not being exposed as a configuration option. If one wants to enable this they will have to specifically set the property.
