### ISSUE TITLE
Parse error in xml file

### ISSUE THREAD

**Issue by viniciusnavarro** [dependency-check/DependencyCheck#5000]
I have a problem when trying to build in Jenkins in a multimodule maven project there is an xml parsing error. I can't understand the reason, because if we try to build it locally, it works without problems.

The error is:

`Caused by: org.owasp.dependencycheck.xml.pom.PomParseException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.`

Anyone have an idea what it could be?

**DC Version:**
5.2.4

Logs:

[log_jenkins.txt](https://github.com/jeremylong/DependencyCheck/files/9889879/log_jenkins.txt)

[log_jenkins2.txt](https://github.com/jeremylong/DependencyCheck/files/9889922/log_jenkins2.txt)

**Comment by jeremylong** [comment]
5.2.4 is no longer supported. Please try ODC 7.2.1.
