### ISSUE TITLE
Automatic way to update versions (Example 7.2.1 to 7.3.0) ? 

### ISSUE THREAD

**Issue by AadiN17** [dependency-check/DependencyCheck#5002]
Hi @jeremylong,
Can you please share if we have any update through command line using any argument or a command to update the versions for dependency check or we have to go through the entire process of downloading and extracting the zip. I have already followed all the steps mentioned here https://jeremylong.github.io/DependencyCheck/dependency-check-cli/index.html but I dont see the version upgrade happening? Can you please advise if I am missing anything in here ?
I am trying to upgrade the version to upgrade the apache-common-text issues.

**Comment by jeremylong** [comment]
Currently, the CLI does not have an automated upgrade process. You would currently need to download the zip and extracting the zip.  If using a mac - we do have a homebrew formula.
