### ISSUE TITLE
When skipping Node dev dependencies, still output any findings to the report

### ISSUE THREAD

**Issue by henrykuijpers** [dependency-check/DependencyCheck#5003]
**Is your feature request related to a problem? Please describe.**
We are using the "skip dev dependencies" for our functionality that generates CSS/JS code and executes unit tests for JS code that already exist. We have configured the dependency check to skip dev dependencies, as they will not be active in our production code.

**Describe the solution you'd like**
While this solves our many many findings, it would actually be useful to still see output in the dependency check about these dev dependencies, so that we can still act on them if required. But just not let them fail our build.

**Describe alternatives you've considered**
If dev dependencies are skipped, it would be nice to still find them (filter them out for the failure decision), but still output any finding on that dependency.

**Comment by jeremylong** [comment]
One can simply scan the dev dependencies in a second scan configured not to fail the build.
