### ISSUE TITLE
Does DependencyCheck support scanning Docker Containers?

### ISSUE THREAD

**Issue by rseeton** [dependency-check/DependencyCheck#5009]
Dependency check CLI allows me to scan various archive objects (tar ball, etc) and to scan my repos using gradle or maven build frameworks.

Can also be used to scan docker containers as well?

Thanks.

**Comment by mprins** [comment]
You want to scan images or containers?... I use Trivy to scan images and compose files

Currently not possible with DC, though in theory a Dockerfile or compose file can be a type of manifest if it uses FROM instructions. 
I'm not sure how good https://dso.docker.com/explore?search=images is and if the data is publicly available

**Comment by jeremylong** [comment]
ODC does not scan docker containers.
