### ISSUE TITLE
define a proxy in Jenkins plugin

### ISSUE THREAD

**Issue by mbaluda** [dependency-check/DependencyCheck#501]
When using the CLI version of the tool I use the parameters proxyserver, proxyport, proxyuserand proxypass.
How can I set the same parameters in the Jenkins plugin?

best regards,
Mauro

**Comment by stevespringett** [comment]
When the Dependency-Check Jenkins Plugin performs an analysis, it retrieves the proxy information (if found) from the global Jenkins configuration. Configure it there and the DC plugin will use it.

**Comment by stevespringett** [comment]
When the Dependency-Check Jenkins Plugin performs an analysis, it retrieves the proxy information (if found) from the global Jenkins configuration. Configure it there and the DC plugin will use it.

**Comment by mbaluda** [comment]
Thanks Steve,
Unfortunately I don't have control over the Jenkins configuration, can I set the proxy in a java property or as an environment variable?

Mauro

**Comment by stevespringett** [comment]
You'll need the Jenkins administrator to configure the proxy settings then. Another approach, and one a lot of enterprises use, is to mirror the NVD on your internal network. You could use https://github.com/stevespringett/nist-data-mirror or something similar to mirror it, and simply point Dependency-Check to the mirror.
