### ISSUE TITLE
Getting InitializationException: Unable to read yarn audit output after update

### ISSUE THREAD

**Issue by cdwijayarathna** [dependency-check/DependencyCheck#5010]
We have recently upgraded the dependency-check version from 6.5.0 - 7.3.0.
Now we are getting the following error while running the analysis.

```
Failed to execute goal org.owasp:dependency-check-maven:7.3.0:aggregate (OWASP-vulnerbility-check) on project test-project: One or more exceptions occurred during dependency-check analysis: One or more exceptions occurred during analysis:
17:33:30  [ERROR] InitializationException: Unable to read yarn audit output.
17:33:30  [ERROR] caused by IOException: Cannot run program "yarn": error=2, No such file or directory
17:33:30  [ERROR] caused by IOException: error=2, No such file or directory
```
We are running on the recreated new DB.
Any idea on what would be causing this and how to solve this?

**Comment by mprins** [comment]
yarn is not on the path or does not exist on the machine

**Comment by cdwijayarathna** [comment]
Is it a new requirement when upgrading from 6.5 to 7.3 ?

**Comment by jeremylong** [comment]
The error only occurs if you scan a project that has a `yarn.lock` and yarn is not installed.

**Comment by cdwijayarathna** [comment]
Thanks, I have removed yarn.lock since we don't use it and now the error is not there.
