### ISSUE TITLE
Improving reproducible build

### ISSUE THREAD

**Issue by nhumblot** [dependency-check/DependencyCheck#5026]
**Is your feature request related to a problem? Please describe.**
@hboutemy is working on reproducible builds and encounter issues with DependencyCheck on this topic.

https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/org/owasp/dependency-check/README.md

**Describe the solution you'd like**
The script should end in success when testing for reproducible builds for future versions.

**Describe alternatives you've considered**

No alternative has been considered

**Additional context**

His PR #4302 improved the situation, but is not enough. His script still detects diffs.

Wen talking together, he identified a small typo in the PR, which needs to be fixed among other issues: https://github.com/jeremylong/DependencyCheck/pull/4302/files#r1014648841

Other issues needs to be investigated by executing the script available in the reproducible-central repository.

Commits total count and tags in generated `git.properties` should be removed. We will need to upgrade the `maven-plugin-plugin` too.

**Comment by hboutemy** [comment]
@nhumblot #5079 provided
