### ISSUE TITLE
drop <mavenSettingsProxyId> from dependency-check-maven plugin configuration

### ISSUE THREAD

**Issue by mischa-n** [dependency-check/DependencyCheck#5040]
Dear Jeremy,

warm thanks for your brilliant work in the last years, this plugin is a must-have.

**Our Goal**
We try to avoid any connection to untrusted (external) resources in our CI process.
For some few exceptions we allow accessing external servers by a proxy. The proxy must be declared for each use case separately, so we are aware of the risc and know which component is using the proxy for what kind of resource.
 
**Current Solution for the dependency-check-maven plugin**
The plugin uses one of the <proxies> from the Maven settings.xml. 
The targeted proxy must be set <active> as you correctly described in https://groups.google.com/g/dependency-check/c/8p_0j4oMcAA/m/otagX2LRAwAJ.

**The Problem**
There are some other Maven plugins that look in the Maven settings.xml for active proxies and use them automatically, e.g. the https://github.com/eirslett/frontend-maven-plugin/ (but there may be more).
If we configure active proxies, we loose control and may silently access untrusted sources. 

**Describe the solution you'd like**
The proxy definition should be part of the dependency-check-maven configuration and not used for anything else.

**Describe alternatives you've considered**
The dependency-check-maven plugin might pick up a named inactive proxy definition from the Maven settings.xml, but other plugins could scan for those proxy definitions too (the frontend-maven-plugin doesn't).

**Comment by mischa-n** [comment]
Looked in the source code and found https://github.com/jeremylong/DependencyCheck/blob/969892a677e49e8c1d71cc6d65eac8a9400de169/maven/src/main/java/org/owasp/dependencycheck/maven/BaseDependencyCheckMojo.java#L2343

I'm using Maven 3.8.6 and tried many times: the plugin picks up the proxy with the matching <id> only if it's set <active> too - strange.

**Comment by jeremylong** [comment]
I'm a little confused on the ask. This should be possible by setting the maven settings proxy id?

**Comment by mischa-n** [comment]
Damn, I should improve my english.

No matter if you configure the `<mavenSettingsProxyId>` or not: in Maven 3.5 and 3.8 `org.apache.maven.settings.Settings.getProxies()` will return only proxies set to `<active>true</active>`. Therefore `org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.getMavenProxy()` may not pick up an **inactive** proxy.

--> We have to provide 2 **active** proxies like suggested in https://groups.google.com/g/dependency-check/c/8p_0j4oMcAA/m/otagX2LRAwAJ
--> the https://github.com/eirslett/frontend-maven-plugin/ will automatically use this proxies 
--> we would open a hole when doing this

**Comment by mprins** [comment]
TBH it sounds like things are working as designed for Maven, but don't match your very specific case.
Have you considered using profiles to switch/activate proxies or having an internal mirror of the nvd so you don't need any proxy at all?....

**Comment by mischa-n** [comment]
The proxy determined in `org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.getMavenProxy()` is used in more components, for example in the `CentralAnalyzer` doing a SHA search (that is not applicable to a mirror).

Yes: I understand the reason behind hiding inactive proxies in Maven.

But: I don't think my use case is special: 
Having limited internet access is caused by security concerns. And I want to allow exceptionally internet access to **trusted** components. 
I want to provide access for the trusted dependency-check-maven plugin.
I don't trust every other plugin and therefore don't want to provide a globally available proxy definition.

_I don't see how I may activate a Maven profile for a specific plugin only._

**Comment by jeremylong** [comment]
Only run the plugin when the profile is active? Honestly - if you have a plugin you don't trust why is it in your build at all?

**Comment by mischa-n** [comment]
I don't talk about "my build" but hundreds of pipelines from different projects and teams. I want them to manually activate the proxy for selected plugins. 

Providing the active proxy only when a specific Maven profile is active, will result in tons of pipelines where the profile is always active - developers tend to take the shortest path.

**Comment by jeremylong** [comment]
If you don't trust a plugin don't use it. If it was really malicious the plugin could search for proxies (inspecting the settings.xml, even proxies that are not active, etc.). In its current state - the ODC plugin is working as expected, following Maven standards.

While I understand the concern raised - solving the issue on a plugin by plugin basis is the incorrect solution. I would suggest working with the Maven team to see if they are willing to re-architect how plugins and proxies work so the concern can be solved at an ecosystem level as opposed to one off solutions (which would be trivial to bypass for a malicious plugin).
