### ISSUE TITLE
host exception while reading hive table from pyspark..it is showing list of tables but not able to read data from hive table 

### ISSUE THREAD

**Issue by abhi413sh** [dependency-check/DependencyCheck#5041]
answer = self.gateway_client. send_command command) -> 1321 return_value = get_return_value 1322 answer, self.gateway_client, self.target_id, self.name) 1323 /ui/jupyterhub_data/anaconda3/lib/python3.8/site-packages/pyspark/sql/utils.py in deco(*a, **kw) 194 #
Hide where the exception came from that shows a non-Pythonic 195 # JVM exception message. --> 196 raise converted from None 197 else: raise 198

IllegalArgumentException: java.net.UnknownHostException: bdacdh-ns

**Comment by jeremylong** [comment]
I think you may have posted this question on the wrong project.
