### ISSUE TITLE
shaded dependency

### ISSUE THREAD

**Issue by parimala-kathir** [dependency-check/DependencyCheck#5043]
HI,

How do you capture shaded dependencies? What are all not captured under this shaded dependency?
Only jars in maven repo captured?

Ref : Vulnerable dependencies not found on shaded jars on some cases #2324

Thanks.

**Comment by jeremylong** [comment]
It depends on how the fat/uber/shaded jar is built. For those built with the Maven Shade Plugin - we extract the POM from the resulting JAR files. Howecer, fat and uber jars (built with other plugins) do not carry the pom.xml documents for the included JAR files - as such, ODC likely won't flag anything.

The best bet is to scan the project that is building the shaded jar using the Maven plugin.

**Comment by parimala-kathir** [comment]
If possible kindly share the document regarding shaded dependency capturing in OWASP dependency checker.

**Comment by parimala-kathir** [comment]
From this doc  https://github.com/jeremylong/DependencyCheck/wiki/How-does-it-work%3F

> For instance, the JarAnalyzer will collect information from the Manifest, pom.xml, and the **package names within the JAR.**

your answer was contradict with the above lines(package names within the JAR)

**Comment by parimala-kathir** [comment]
What about Binary scanning option in ODC?

**Comment by jeremylong** [comment]
See the discussion here: https://github.com/jeremylong/DependencyCheck/issues/5084
