### ISSUE TITLE
Future of the plugin with upcoming changes from NVD in late 2023?

### ISSUE THREAD

**Issue by rmontag-ap** [dependency-check/DependencyCheck#5047]
NVD has announced the end of the JSON data feeds in favor of the v2 API:
https://nvd.nist.gov/General/News/changes-to-feeds-and-apis
https://nvd.nist.gov/vuln/data-feeds

Is it planned to migrate the maven plugin to the new v2 API instead of using the JSON 1.1 feeds?
If yes, is there already a timeline when the first versions of the plugin will be available?

E.g. Steve Springett has already announced EOL of his nist-data-mirror (https://github.com/stevespringett/nist-data-mirror) with no successor planned, which we are using in conjunction with this plugin in our CI/CD :-(

Thanks,
    Rainer

**Comment by mprins** [comment]
duplicates #4732

**Comment by rmontag-ap** [comment]
Thanks!
