### ISSUE TITLE
Is it possible to suppress specific vulnerabilities, but only if they are via a specific dependency path?

### ISSUE THREAD

**Issue by xenomachina** [dependency-check/DependencyCheck#5049]
Let's suppose:

- my team is using a library, "rubberbandfind", which in turn uses the "leglesslizardmarkup" library
- there's a known vulnerability when using leglesslizardmarkup in a certain way
- we've determined that rubberbandfind is using leglesslizardmarkup in a way that is safe
- we aren't using leglesslizardmarkup directly

I know we can suppress the leglesslizardmarkup CVE, but the problem is if another library we use starts using it in an unsafe way, or even if our our teams forgets about the vulnerability and starts using it in an unsafe way, DependencyCheck will not be able to warn us.

So is there a way we could tell DependencyCheck to suppress that leglesslizardmarkup CVE, but only if the only path to leglesslizardmarkup is via our dependency on rubberbandfind?

**Comment by jeremylong** [comment]
If using the maven plugin I believe you can use the `excludes` config: https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html...  Its been a while since I looked at that implementation though.

**Comment by xenomachina** [comment]
We're using the Gradle plugin, and it unfortunately appears that it doesn't have an `excludes` parameter, as far as I can tell.

**Comment by jeremylong** [comment]
With gradle - generally users have scopes they want to skip rather then an individual dependency...
