### ISSUE TITLE
BaseDependencyCheckMojo mkdirs result true is no error

### ISSUE THREAD

**Issue by TorstenKruse** [dependency-check/DependencyCheck#505]
Our jenkins logs this error about dir not able to create, but it will exist after the dependency check. I think there is just a "!" missing in the condition, because mkdirs() returns true, if dir was created.

`1003   0  
             if (!parent.isDirectory() && parent.mkdirs()) {
 1004    0  
                 getLog().error(String.format("Directory '%s' does not exist and cannot be created; unable to write data file.",
 1005    0  
                         parent.getAbsolutePath()));
 1006       
             }`

**Comment by jeremylong** [comment]
Thanks for pointing this out!
