### ISSUE TITLE
Can you provide a demo project for cmake dependency analysis?

### ISSUE THREAD

**Issue by LincWong** [dependency-check/DependencyCheck#5052]
In mine case, CMake Analyzer does not match any dependencies

I want to know how cmake dependency analysis works, 

which keywords are needed in cmakelists.txt and *.cmake to match;

In the test/resources directory, I did not see the corresponding example;

**Comment by mprins** [comment]
https://github.com/jeremylong/DependencyCheck/tree/main/core/src/test/resources/cmake ?

**Comment by LincWong** [comment]
你好，我已经收到你的邮件了。

**Comment by LincWong** [comment]
my fault :(
