### ISSUE TITLE
Confidence - Low

### ISSUE THREAD

**Issue by parimala-kathir** [dependency-check/DependencyCheck#5055]
Constraints to mark CPE as confidence Low or Evidence as  confident Low

**Comment by jeremylong** [comment]
CPE confidence is explained here: https://jeremylong.github.io/DependencyCheck/general/internals.html

**Comment by jeremylong** [comment]
Highly recommend reading this as well: https://jeremylong.github.io/DependencyCheck/general/thereport.html
