### ISSUE TITLE
Unable to purge the database when using a non-default connection string

### ISSUE THREAD

**Issue by mtcolman** [dependency-check/DependencyCheck#5057]
Hi, I'm running Dependency Check on OpenShift/Kubernetes with a separate postgresql database. I've upgraded to v7.3.0 and from v6.x. I've encountered this error:

```
[ERROR] One or more fatal errors occurred
[ERROR] Unable to connect to the dependency-check database
```

And I can see this on the main README:
> 7.0.0 Upgrade Notice
> 
> If upgrading to 7.0.0 or higher, there were breaking changes. If you get an error indicating you can't connect to the database you will need to run the purge command to remove the old database:
> 
>     gradle: ./gradlew dependencyCheckPurge
>     maven: mvn org.owasp:dependency-check-maven:7.0.0:purge
>     cli: dependency-check.sh --purge

I'm using the CLI, so I've tried `dependency-check.sh --purge`, but I need to provide credentials and a connection string to the database which runs in a separate pod.

I then get this error:
```
Unable to purge the database when using a non-default connection string
```

I've had a look at the purge code (https://github.com/jeremylong/DependencyCheck/blob/main/cli/src/main/java/org/owasp/dependencycheck/App.java#L136) and I can see:
```
        if (cli.isPurge()) {
            final String connStr = cli.getStringArgument(CliParser.ARGUMENT.CONNECTION_STRING);
            if (connStr != null) {
                LOGGER.error("Unable to purge the database when using a non-default connection string");
                exitCode = -3;
            } else {
```

So does this mean I cannot use this method, and are you please aware of an alternative?

Thanks,

Matt

**Comment by jeremylong** [comment]
Correct - the purge command only works if using the default embedded H2 database. Literally, purge just deletes the H2 database. If you need to recreate the postgresql database - you would just follow the standard procedures of dropping the tables and re-creating them: https://github.com/jeremylong/DependencyCheck/blob/main/core/src/main/resources/data/initialize_postgres.sql

Note that the upgrades to the database may need to be run as ODC does not automatically update the schema when using an external database. We may in the future as we have a long overdue request to use flywheel or liquibase.

The update scripts can be found here: https://github.com/jeremylong/DependencyCheck/blob/main/core/src/main/resources/data/

**Comment by mtcolman** [comment]
Thanks @jeremylong, appreciate the response.
