### ISSUE TITLE
link to 7.3.1 on owasp.org gives an error

### ISSUE THREAD

**Issue by proo4509** [dependency-check/DependencyCheck#5063]
according to owasp.org version 7.3.1 is available but the hyperlink https://github.com/jeremylong/DependencyCheck/releases/download/v7.3.1/dependency-check-7.3.1-release.zip doesn't work

**Comment by mprins** [comment]
It seems the tag was pushed, but not "released": 
https://github.com/jeremylong/DependencyCheck/releases/tag/v7.3.1

**Comment by proo4509** [comment]
yes i think so too.
Would be great to have a static download url without version number btw...

**Comment by jeremylong** [comment]
There was an issue releasing to Central (https://github.com/jeremylong/DependencyCheck/actions/runs/3478970662) that caused the rest of the release process to fail. I'm pushing 7.3.2 now.

Regarding the static URL - many do something like:

```bash
VERSION=$(curl -s https://jeremylong.github.io/DependencyCheck/current.txt)
curl -s "https://github.com/jeremylong/DependencyCheck/releases/download/v$VERSION/dependency-check-$VERSION-release.zip" --output dependency-check.zip
```

I suppose we should document that somewhere...

**Comment by cmuchinsky** [comment]
Is part of the release process that failed the creation of a corresponding `dependency-check-gradle` release, or is that handled separately after the fact?

**Comment by jeremylong** [comment]
gradle release happens manually afterwards. I will be publishing the gradle plugin (7.3.2) after https://github.com/jeremylong/DependencyCheck/actions/runs/3496820002 completes and the core project is released.

**Comment by jeremylong** [comment]
7.3.2 has been published (including the gradle plugin and PR for the homebrew formula).
