### ISSUE TITLE
Update to .NET 7 and "An error occurred with the .NET AssemblyAnalyzer"

### ISSUE THREAD

**Issue by ruben0909** [dependency-check/DependencyCheck#5077]
**Describe the bug**
.NET AssemblyAnalyzer fails in my pipeline in Azure Devops , when I update the .csproj to .NET 7.
I read that is necessary install .NET6 Runtime in a separate folder and i did it in "$(Agent.TempDirectory)\dotnet"
and use  "--dotnet $(Agent.TempDirectory)\dotnet" to force use .NET 6 Runtime.
¿When DependencyCheck would be updated to .NET 7?
¿Somebody has .NET 7 project and Dependency Check working in Azure Devops?

**Version of dependency-check used**
The problem occurs using version 6.0.0.4 of the [Azure Devops  plugin](https://marketplace.visualstudio.com/items?itemName=dependency-check.dependencycheck)
Dependency-Check Core version 7.3.2

**Log file**
[Log File.](https://gist.github.com/ruben0909/96222b4c8b8c0f905c64d8ad3381ecb9)

**To Reproduce**
1. Create a pipeline
2. Use task
```- task: UseDotNet@2
         inputs:
           version: '6.0.x'
           packageType: sdk
           installationPath : '$(Agent.TempDirectory)\dotnet'
       - task: UseDotNet@2
         inputs:
           version: '7.0.x'
           packageType: sdk
           installationPath : '$(Agent.ToolsDirectory)/dotnet'
       - task: dependency-check-build-task@6
         inputs:
           enableVerbose: true
           projectName: '${{parameters.SonarProjectKeyId}}'
           scanPath: '${{parameters.SourceFolder}}'
           format: 'HTML,JSON'
           reportsDirectory: '$(System.DefaultWorkingDirectory)/TestResults'
           additionalArguments: '--disableYarnAudit  --dotnet $(Agent.TempDirectory)\dotnet'
```
3. Run Pipeline

**Expected behavior**
Use Dependency Check with .NET 7 projects successfully in Azure Devops.

**Additional context**
Command
`C:\Windows\system32\cmd.exe /D /S /C "D:\a\_tasks\dependency-check-build-task_55555555-5555-5555-5555-555555555555\6.0.4\dependency-check\bin\dependency-check.bat --project XXXXXX --scan D:\a\1\s\src --out D:\a\1\s\TestResults --format HTML --format JSON --disableYarnAudit --dotnet D:\a\_temp\dotnet"`
Relevant parts

```
[WARN] An error occurred with the .NET AssemblyAnalyzer, please see the log for more details.
[ERROR] Exception occurred initializing Assembly Analyzer.
------
[ERROR] Could not execute .NET AssemblyAnalyzer
------
##[error]Dependency Check exited with an error code (exit code: 4294967282).
```

**Comment by jeremylong** [comment]
dotnet 7 assemblies can be scanned - but ODC contains an assembly that requires the dotnet core 6 runtime to be able to scan assemblies.

**Comment by ruben0909** [comment]
The Azure Devops Build Agent has strange behavior when it has multiple .NET Core installed.
I have been able to fix it by first installing .NET 7 SDK to compile the project and .NET 6 just before executing the Dependency Check task, all of this in the default folder.
Thank you very much
