### ISSUE TITLE
False positives coming from incorrectly detected CPE

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [dependency-check/DependencyCheck#5085]
Thanks for fixing https://github.com/jeremylong/DependencyCheck/issues/5048 

There is another library with the same problem (the last one), but I am unable to use a False Positive report by myself so describing the problem here:

The file path: C:\Users\<user>\.gradle\caches\modules-2\files-2.1\com.liferay.portal\release.portal.api\7.4.3.19-ga19\f86cfb6b1f03e0732e1946ed3f81968a17605669\release.portal.api-7.4.3.19-ga19.jar\META-INF/maven/com.liferay.portal/com.liferay.support.tomcat/pom.xml

It is a custom extension for tomcat integration, but detected as Liferay itself:

Deduced CPEs:
* `[cpe:2.3:a:liferay:liferay:6.0.6:*:*:*:*:*:*:*]` (Confidence:Highest)
* `[cpe:2.3:a:liferay:liferay_portal:6.0.6:*:*:*:*:*:*:*]` (Confidence:Highest)
* `[cpe:2.3:a:liferay:portal:6.0.6:*:*:*:*:*:*:*]` (Confidence:Highest)

This rule could fix it:
```
    <suppress base="true">
       <notes><![CDATA[
       Suppresses false positives per issue #FIXME
       ]]></notes>
       <packageUrl regex="true">^pkg:maven/com\.liferay\.portal/com\.liferay\.support\.tomcat@.*$</packageUrl>
       <cpe>cpe:/a:liferay:liferay</cpe>
       <cpe>cpe:/a:liferay:liferay_portal</cpe>
       <cpe>cpe:/a:liferay:portal</cpe>
    </suppress>
```
Thanks!

**Comment by aikebah** [comment]
The problem I see with just suppressing the CPE is that it IS a library that is part of the regular liferay source repo (while using a different version), so I'm not sure that NVD would actually register CVEs - should they arise - inside this module under a separate CPE rather than under the CPE of the liferay portal, using the version of the main portal release to denote the vulnerable software.

@jeremylong what do you think (as you decided to take the slf4j util as a suppression which is a similar case)

**Comment by aikebah** [comment]
Note: there are a few more of such cases that don't trigger FPs (yet)... as their version currently supercedes the main portal version numbers. A quick glance on the github repo shows..

```
portal-impl (60.1.0)
support-tomcat (6.0.1)
util-bridges (10.0.0)
util-java (17.1.5)
util-slf4j (6.0.9)
util-taglib (10.1.1)
portal-test (14.2.0)
```

If we do take them as CPE suppressions I think we should include all of them

**Comment by jeremylong** [comment]
This is always a balancing act of FP vs. FN. I don't know enough about liferay - is it a server that would be deployed, maintained and these apps are just deployed to it? Or do you end up packaging everything into a single WAR for a liferay application?

**Comment by jan-tosovsky-cz** [comment]
The Liferay portal can be used for building websites. It is a kind of container with standard modules (discussions, blogs, wiki), but there is API you can use for integrating your custom OSGi modules. Such a custom module has `compileOnly group: "com.liferay.portal", name: "release.portal.api"` dependency, which depends on many other shaded dependencies:

<img width="334" alt="image" src="https://user-images.githubusercontent.com/3907898/203948691-53d60500-6165-4ef7-9e1f-73f3a342b031.png">

Those dependencies in the com.liferay.portal package are all (as @aikebah correctly stated) detected as 
```
<cpe>cpe:/a:liferay:liferay</cpe>
<cpe>cpe:/a:liferay:liferay_portal</cpe>
<cpe>cpe:/a:liferay:portal</cpe>
```
and combined with the version of the particular library. Such a combination is nonsense. Those below the released Liferay version (7.4.xx), i.e. `util-slf4j` and `support-tomcat`, are shown in the report as affected by Liferay CVEs.

So, If CPE is detected as Liferay, it should be combined with the correct Liferay version. However, this version is not listed in the evidence table. So the workaround is to have these libs in the exception list, but indeed, it may be risky.

**Comment by jeremylong** [comment]
@aikebah I think we can suppress these - as `kernel` and `impl` would be the artifacts that actually flag the version of liferay.

**Comment by jan-tosovsky-cz** [comment]
Just a note, to make things more complicated, there is unequal relation between `impl` or `kernel` versions vs Liferay version.
E.g. Liferay versions 7.4.3.19-ga19 (used for CPE, see [NVD](https://nvd.nist.gov/products/cpe/search/results?namingFormat=2.3&orderBy=CPEURI&keyword=liferay&status=FINAL&startIndex=600)) contains `impl` 32.0.1 and `kernel` 44.1.0.

**Comment by aikebah** [comment]
@jan-tosovsky-cz But I think we can safely assume that any such project will always have one of the 'correct versions' liferay artifacts in its dependencies, so that the dependency on a vulnerable version of the liferay portal framework would typically surface.

**Comment by aikebah** [comment]
Besides the `kernel` addition already indicated by @jan-tosovsky-cz I spotted two more libraries with individual versions in the DependencyCheck report for `pkg:maven/com.liferay.portal/release.portal.api@7.4.3.19-ga19` that receive the main liferay CPE assignment:
* `com.liferay.portletmvc4spring:com.liferay.portletmvc4spring.test`
* `com.liferay:biz.aQute.bnd.annotation`
I'll also include these in the PR to the suppressions
