### ISSUE TITLE
Why OSSIndex is called although <ossindexAnalyzerEnabled> is false?

### ISSUE THREAD

**Issue by mh-bmg** [dependency-check/DependencyCheck#5091]
We have several projects where we use the OWASP dependency-check-maven plugin. The plugin is defined in the build/plugins section; either with goal "check" or "aggregate". Latter in the parent pom for multi module projects.

```
<plugin>
    <groupId>org.owasp</groupId>
    <artifactId>dependency-check-maven</artifactId>
    <version>7.2.1</version>
    <configuration>
        <formats>HTML,JSON</formats>
        <cveValidForHours>168</cveValidForHours>
        <ossindexAnalyzerEnabled>false</ossindexAnalyzerEnabled> 
    </configuration>
    <executions>
        <execution>
            <goals>
                <goal>aggregate</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

In all we first ran in the problem that we couldn't access OSSIndex of Sonatype (we have no account there). We got this error (check is performed by Jenkins):

```
[ERROR] AnalysisException: OSS Index access forbidden
[ERROR] caused by TransportException: Unexpected response; status: 403
```

After some research we added `<ossindexAnalyzerEnabled>false</ossindexAnalyzerEnabled>` to our poms. This solved the problem for all projects but the two multi module projects. Jenkins still received the above mentioned error. Locally all runs smoothly.

We start the check with `mvn clean org.owasp:dependency-check-maven:aggregate` (or with "check" as goal).

Why is the OSS Index still called by our multi module projects although it should not be called according to the configuration?
Do you need further informations?
Did I miss anything?

===

In a first approach we defined the dependency-check-maven plugin for the multi module projects in a separate profile in the section reporting/plugins (same plugin configuration as above). We started the check with `mvn site -Pcheck-dependencies -P!default`.

More strangely than now, the check of one multi module project didn't try to connect to OSS Index but the check of the other multi module project did. After moving the plugin definition to the build/plugins section we got rid of this problem. But now both still tries to connect to OSSIndex.

**Comment by jeremylong** [comment]
Guessing based on the description that the configuration is not consistent. If you execute the plugin via the `site` - the configuration must be in the site plugin's configuration; see [example 2](https://jeremylong.github.io/DependencyCheck/dependency-check-maven/index.html). When running the `site` the plugin will not read the configuration from the build/plugins (and vs. versa).

**Comment by mh-bmg** [comment]
Running the check via `site` was the first approach. Now we configured the dependency-check-maven Plugin in every project inside "build/plugins" and run the check for our multi-module projects via `mvn org.owasp:dependency-check-maven:aggregate`.
This leads to the first mentioned situation (above "===").
Before this we tried the approach mentioned below "===". Sorry, is a bit confusing. Don't mind this one anymore.

**Comment by mh-bmg** [comment]
Wait. It's not completed. ;)
"Don't mind this one anymore" was only regarded to the text below "===" in my first posting. :)

I still have the problem that our multi-module projects performs the OSSIndex check.

**Comment by jeremylong** [comment]
If you have an example project that exhibits the behavior of disabling the OSS Index Analyzer yet the aggregate is till calling it - I would love to see that.

**Comment by mh-bmg** [comment]
I found the issue. Jenkins loaded the old pom where the flag was not set.
And further some modules referenced also an old parent pom version.

Thanks for reading and the support. :)
