### ISSUE TITLE
JCS log spam when using the Central Analyzer cache from Ant

### ISSUE THREAD

**Issue by slieschke** [dependency-check/DependencyCheck#5096]
**Describe the bug**
Dependency checking from Ant using the Central Analyzer cache outputs about a screen's worth of JCS logging at both the start and end of the output.

**Version of dependency-check used**
The problem occurs using version 7.3.1 of the Ant task.

**Log file**
See https://gist.github.com/slieschke/82434d9f030feeb3b4bc520527bb37ce for example output.

**To Reproduce**
Run a dependency check from Ant with `centralAnalyzerUseCache="true"`.

**Expected behavior**
See https://gist.github.com/slieschke/525e30902dc5cdad71f504e1630861a6 for expected output.

**Comment by jeremylong** [comment]
Resolution is pending https://github.com/apache/commons-jcs/pull/120. We can't upgrade JCS and fix the logging until the issue is resolved.
