### ISSUE TITLE
bundle-audit issues

### ISSUE THREAD

**Issue by austinc88** [dependency-check/DependencyCheck#511]
I'm trying to scan some Ruby projects with DependencyCheck 1.3.6, however I keep getting the following error:

[WARN] Exception from bundle-audit process: java.io.IOException: Cannot run program "bundle-audit" (in directory "C:\Users<UserName>\AppData\Local\Temp\dctemp"): CreateProcess error=2, The system cannot find the file specified. Disabling Ruby Bundle Audit Analyzer
[ERROR] Exception occurred initializing Ruby Bundle Audit Analyzer.

I have the gem bundler-audit installed, and I am able to run bundle-audit in a Ruby project directory.

Does anyone have any ideas how to fix this

**Comment by jeremylong** [comment]
You likely need to add the path to bundler audit binary via the `--bundleAudit` argument as documented in the `--advancedHelp` or on the [documentation page](http://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html).

Let me know if that solves your problem.

--Jeremy

**Comment by austinc88** [comment]
Hi Jeremy,

Thanks for the guidance. That helped resolve that issue!

**Comment by colezlaw** [comment]
@jeremylong I'm not super familiar with Ruby gems, and I can look at this some more, but is there a possibility of us being able to find it when it's not on the path - either by looking for GEM_HOME, or something else in the environment to possibly be able to figure out where it is if it's not specified? I understand we could get this wrong (maybe they're using a rvm and we maybe pick up a global path before the rvm path or something?)

I can try to figure out what I can, but didn't know how much you already know about where gems go or where they may or may not already be on the path.
