### ISSUE TITLE
Expectations for next release

### ISSUE THREAD

**Issue by Dannyzen** [dependency-check/DependencyCheck#513]
Hey there,
There have been some pull requests accepted to master that I'd like to use. Is master stable? If not, when might be an acceptable expectation for when the next release (1.3.7) will be cut and posted in the /releases section?

**Comment by jeremylong** [comment]
I'm finishing up a few items in the gradle plugin, updating the documentation, etc. and I expect to be releasing 1.4.0 within 1 week.
