### ISSUE TITLE
Unable to detect dependencies Swift

### ISSUE THREAD

**Issue by emanuelcaesar** [dependency-check/DependencyCheck#5145]
I ran it using
`dependency-check --enableExperimental --project "ProjectName.xcodeproject" --scan "." --out "../Reports/dependency" --noupdate'
`
But I get 0 results:
`
dependency-check version: 7.4.1
Report Generated On: Tue, 13 Dec 2022 13:03:01 +0100
Dependencies Scanned: 0 (0 unique)
Vulnerable Dependencies: 0
Vulnerabilities Found: 0
Vulnerabilities Suppressed: 0
NVD CVE Checked: 2022-12-13T12:46:07
NVD CVE Modified: 2022-12-13T07:00:02
VersionCheckOn: 2022-11-16T16:09:15
`

Thank you

**Comment by aikebah** [comment]
Hard to tell from so little information what could be going wrong in your project.

SwiftPackageManagerAnalyzer requires `Package.swift` to be found in your project
SwiftPackageResolvedAnalyzer requires `Package.resolved` to be found in your project

If neither of them is present it's logical that it would not find anything. If both are present you should rerun with debug logging (add `--log odc.log`) and check that (or post it in a gist and link it here)
