### ISSUE TITLE
Retest wrong location for the node_modules folder #5119

### ISSUE THREAD

**Issue by ngyl88** [dependency-check/DependencyCheck#5146]
**Describe the bug**
It's a follow up of #5119 

**Version of dependency-check used**
The problem occurs since version 7.4.0 and 7.4.1 of the published docker image.

**Additional context**
[Link to the original report (closed ticket but unresolved)](https://github.com/jeremylong/DependencyCheck/issues/5119#issuecomment-1350163407)

**Comment by jeremylong** [comment]
duplicate, resolved with https://github.com/jeremylong/DependencyCheck/pull/5135
