### ISSUE TITLE
[7.0.1]Unable to write non-standard VSL output to a directory

### ISSUE THREAD

**Issue by viniciusnavarro** [dependency-check/DependencyCheck#5148]
Hello

I'm using the version 7.0.1 and I'm having a problem that I don't understand, the error is:

"caused by ReportException: Unable to write non-standard VSL output to a directory, please specify a file name"

Debub info:
[build] [DEBUG] "velocimacro.library.path" is not set. Trying default library: velocimacros.vtl
[build] [DEBUG] Default library velocimacros.vtl not found. Trying old default library: VM_global_library.vm
[build] [DEBUG] Old default library VM_global_library.vm not found.
[build] [DEBUG] allowInline = true: VMs can be defined inline in templates
[build] [DEBUG] allowInlineToOverride = false: VMs defined inline may NOT override previous VM definitions
[build] [DEBUG] allowInlineLocal = false: VMs defined inline will be global in scope if allowed.
[build] [DEBUG] autoload off: VM system will not automatically reload global library macros

Does anyone have any idea what this problem could be?

**Comment by jeremylong** [comment]
How did you run dependency-check? How was it configured?

**Comment by viniciusnavarro** [comment]
**The pom configuration:**

<plugin>

    <groupId>org.owasp</groupId>
    <artifactId>dependency-check-maven</artifactId>
    <version>7.0.1</version>
    <configuration>
        <format>xml, html</format>
        <assemblyAnalyzerEnabled>false</assemblyAnalyzerEnabled>
        
        <connectionTimeout>600000</connectionTimeout>
        <autoUpdate>true</autoUpdate>
        <dataDirectory></dataDirectory>
    </configuration>
    <executions>
        <execution>
            <goals>
                <goal>aggregate</goal>
            </goals>
        </execution>
    </executions>

</plugin>


**The command I'm using to run the project is:**

mvn verify -Panalysis -DskipTests

Important information, I run this step in Jenkins

**Comment by jeremylong** [comment]
The correct way to specify multiple formats in Maven is:

```xml
                    <formats>
                        <format>JSON</format>
                        <format>HTML</format>
                    </formats>
```

**Comment by viniciusnavarro** [comment]
Bingo!

That was exactly it! thanks for the help @jeremylong
