### ISSUE TITLE
[FP]: apache-jsieve-core is mistaken for Apache James.

### ISSUE THREAD

**Issue by jonas-hollm** [dependency-check/DependencyCheck#5168]
### Package URl

pkg:maven/org.apache.james/apache-jsieve-core@0.7

### CPE

`cpe:2.3:a:apache:james:0.7:*:*:*:*:*:*:*`

### ODC Integration

{"label"=>"Maven Plugin"}

### ODC Version

7.4.1

### Description

apache-jsieve-core is wrongly identified as part of the Apache James project.

**Comment by aikebah** [comment]
approved
