### ISSUE TITLE
[FP]: queue-activemq-guice is mistaken for Apache ActiveMQ

### ISSUE THREAD

**Issue by jonas-hollm** [dependency-check/DependencyCheck#5171]
### Package URl

pkg:maven/org.apache.james/queue-activemq-guice@3.7.2

### CPE

`cpe:2.3:a:apache:activemq:3.7.2:*:*:*:*:*:*:*`

### ODC Integration

{"label"=>"Maven Plugin"}

### ODC Version

7.4.1

### Description

queue-activemq-guice is wrongly identified as part of Apache ActiveMQ.

**Comment by aikebah** [comment]
approved
