### ISSUE TITLE
[FP]: reactor-rabbitmq is mistaken for VMware RabbitMQ

### ISSUE THREAD

**Issue by jonas-hollm** [dependency-check/DependencyCheck#5172]
### Package URl

pkg:maven/io.projectreactor.rabbitmq/reactor-rabbitmq@1.5.4

### CPE

`cpe:2.3:a:vmware:rabbitmq:1.5.4:*:*:*:*:*:*:*`

### ODC Integration

{"label"=>"Maven Plugin"}

### ODC Version

7.4.1

### Description

reactor-rabbitmq is wrongly identified as part of VMware RabbitMQ.

**Comment by aikebah** [comment]
approved
