### ISSUE TITLE
Gradle plugin: "Cannot cast object" error when JAVA_TOOL_OPTIONS with proxy settings is defined

### ISSUE THREAD

**Issue by ldrag** [dependency-check/DependencyCheck#5174]
Hi, I have encountered an issue when using dependency-check-gradle plugin in version 7.4.1 with JAVA_TOOL_OPTIONS.

Steps to reproduce:
1. Define JAVA_TOOL_OPTIONS env with value:
` "-Dhttps.proxyHost=proxy.my-domain.com -Dhttps.proxyPort=8080 -Dhttp.nonProxyHosts=localhost|127.*|[::1]|*.my-domain.com"`
2. Run `gradle dependencyCheckAnalyze`

This results in the following error:
```
> Task :dependencyCheckAnalyze FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dependencyCheckAnalyze'.
> Cannot cast object 'localhost|127.*|[::1]|*.my-domain.com' with class 'java.lang.String' to class 'java.util.List'
```

What is interesting is that if I e.g. remove `Dhttps.proxyHost` and leave `https.proxyPort` and `http.nonProxyHosts` settings all seems to work fine.

I would appreciate if someone could have a look at the issue.

**Comment by jeremylong** [comment]
Will be fixed with 7.4.2 which should be released shortly. See https://github.com/dependency-check/dependency-check-gradle/pull/298
