### ISSUE TITLE
scanning project of golang failed by dependency-check

### ISSUE THREAD

**Issue by ninianxing** [dependency-check/DependencyCheck#5184]
Dear all,
    I add the parameter "--enableExperimental" to scanning the golang project, but it cancelled because of errors.
There were 2 warnings as follow,
    1. missing go.sum entry:to add it.
    2. Path to go exec executable does not exist.
I have tried these ways to solve them, but it doesn't take effect.
    1. use 'go mod tidy' before running dependency-check command.
    2. add the GOPATH or GOROOT in parameter '--go'. 
Urgently waiting for your reply.
Tks a lot.

**Comment by aikebah** [comment]
`--go` needs the full path of the go executable (when it cannot be found on the executable path of the user that runs the dependencycheck tool). Neither of the variables mentioned represents the go executable itself (which would typically reside at `${GOROOT}/bin/go`).

**Comment by ninianxing** [comment]
Thanks a lot. 
I modified and it can running the analyzer. 
But I have another question , the log shows "Warnings from go go:github.com/Azure/xxxx:missing go.sum entry: to add it xxx", then the scanning cancelled.

**Comment by aikebah** [comment]
That warning comes directly from go and as you can find on [Go.dev's documentation on dependencies](https://go.dev/doc/modules/managing-dependencies#enable_tracking) go.sum is meant to be checked-in to version control so it _should_ be present in your project sources.
It assume that it triggers an exit-code that makes DependencyCheck consider the go command failed (exit code not 0 or 1), so that scanning gets cancelled. Without logs not much to help you out, but the go.sum you should fix in your setup anyhow from the go.dev docs.

**Comment by ninianxing** [comment]
There is go.sum in my project. DependencyCheck copied project files to /tmp and running analyzer in /tmp.  I found go.sum doesn't copy to /tmp, so it error. 
![log](https://user-images.githubusercontent.com/103549973/210474697-9f6b0400-738d-4895-9da3-d8a076b9a538.jpeg)

**Comment by aikebah** [comment]
Not quite.... what goes into /tmp is an extracted zip-file to scan its contents. From the looks of the error message there is a zipfile in your project with a coredns-1.7.0 go module that appears to have unusable content in its embedded go.mod (I suspect a 0-byte file) 

Edit: Going by the error message you're using an outdated unsupported version of DependencyCheck (<6.3.0)... please try version 7.4.3, which should yield a more useful error message in relation to the error that would show that it's not reading the go.mod as suggested by the names, but reading the output that go generates for "go list -json -m all", which appears to be breaking on your system in some way.
