### ISSUE TITLE
CLI - Cli execution with params file ignores oss parameter settings

### ISSUE THREAD

**Issue by pteichner85** [dependency-check/DependencyCheck#5194]
CLI version: 7.4.2

I have used the --properties file with all my required properties as shown below. The CLI still tries to run the OSS scanner though dispite **disableOssIndex** and **ossindexAnalyzerEnabled**

Its also evident that the maven plugin (ossindexAnalyzerEnabled) and the CLI uses inconsistent params

Params file:
```
scan=${WORKSPACE}/package.json
scan=${WORKSPACE}/package-lock.json
exclude=${WORKSPACE}/node_modules
cve.url.base=${owaspRepoURI}/nvdcve-1.1-%d.json.gz
cve.url.modified=${owaspRepoURI}/nvdcve-1.1-modified.json.gz
retireJsUrl=${owaspRepoURI}/jsrepository.json
cve.user=${USERNAME}
cve.password=${PASSWORD}
disableOssIndex=true
ossindexAnalyzerEnabled=false
junitFailOnCVSS=10
format=JSON,XML,HTML
disableAssembly=true
disableMSBuild=true
disableRetireJS=true
disableYarnAudit=true
log=owasp_log.log
out=owasp_reports
```

**Comment by pteichner85** [comment]
As a side note exclude was also ignored when added to properties file

**Comment by aikebah** [comment]
essentially the same as #5196, so closing this one as a duplicate
