### ISSUE TITLE
CLI: Allow for HTTP auth settings for Retire JS respository

### ISSUE THREAD

**Issue by pteichner85** [dependency-check/DependencyCheck#5195]
**Describe the bug**
The download of retire JS behind a HTTP auth fails

**Version of dependency-check used**
CLI 7.4.2

**Log file**

**To Reproduce**
1. Configure CLI with custom retireJS url
2. Configure cve user and password
3. Run cli 

**Expected behavior**
Using the maven plugin the retireJS file is downloaded with the cve user / password

**Comment by pteichner85** [comment]
Actually it doesn't work on Maven either - it was simplfy cached

**Comment by aikebah** [comment]
cve user and password have been added to authenticate to (mirrors of) the NVD CVE datastream URLs. Authentication configuration for a retireJS URL is simply not available right now.

**Comment by aikebah** [comment]
Updated title and label to change it into an enhancement request
