### ISSUE TITLE
Cli execution with params file ignores certain paramaters

### ISSUE THREAD

**Issue by pteichner85** [dependency-check/DependencyCheck#5196]
**Describe the bug**
When using the properties file as a parameter, certain settings get ignored

**Version of dependency-check used**
CLI 7.4.2

**Log file**
[<script src="https://gist.github.com/pteichner/92c61d3782d44157af38f2a587c92cbe.js"></script>](https://gist.github.com/pteichner/92c61d3782d44157af38f2a587c92cbe)

**To Reproduce**
1. Use the following properties file
```
scan=${WORKSPACE}/package.json
scan=${WORKSPACE}/package-lock.json
exclude=${WORKSPACE}/node_modules
cve.url.base=${owaspRepoURI}/nvdcve-1.1-%d.json.gz
cve.url.modified=${owaspRepoURI}/nvdcve-1.1-modified.json.gz
retireJsUrl=${owaspRepoURI}/jsrepository.json
cve.user=${USERNAME}
cve.password=${PASSWORD}
disableOssIndex=true
ossindexAnalyzerEnabled=false
junitFailOnCVSS=10
format=JSON,XML,HTML
disableAssembly=true
disableMSBuild=true
disableRetireJS=true
disableYarnAudit=true
log=owasp_log.log
out=owasp_reports
```

**Expected behavior**
All those settings **disableMSBuild**, **disableRetireJS** should be taken into account

**Additional context**

**Comment by jeremylong** [comment]
Wow - i just realized that is not documented very well.  When using the properties file you need to use the internal property names as found here: https://github.com/jeremylong/DependencyCheck/blob/main/core/src/main/resources/dependencycheck-cache.properties
