### ISSUE TITLE
Retry or Fail option for failed downloads?

### ISSUE THREAD

**Issue by poblish** [dependency-check/DependencyCheck#520]
I'm getting quite a few `Download Failed for NVD CVE` / `Some CVEs may not be reported` messages (no more detail than that) running the plugin from within AWS, with the result that empty reports get generated. `-DcveValidForHours=0` isn't really helping, and shouldn't be necessary anyway.

Is there any way we can configure the plugin to treat a failed download as a FATAL (or at least non-zero exit code) error, or else configure an automatic retry (every x seconds, up to y times etc.)?

**Comment by jeremylong** [comment]
That is probably a good idea - especially if the database is empty to begin with.

Can you enable logging to see if there is a specific error occurring when the downloads fail? (see the [documentation site](http://jeremylong.github.io/DependencyCheck/) for info on how to do this for whichever variant you are using).

**Comment by poblish** [comment]
I seem to be getting 403s back after the first 20-25 requests: https://gist.github.com/poblish/ffcec0472421ead22406831f4192dd29

Could it be rate-limiting targeting EC2 instances? We have a pool of 10-20 that might potentially all perform lookups in parallel (but only on demand - there have been no other runs today), so if it is indeed limiting we might have to revisit that approach.

**Comment by jeremylong** [comment]
That is possible - I have not personally run into NIST rate limiting
anything I've been doing. One way you could limit the number of update
calls would be to utilize a centralized database
http://jeremylong.github.io/DependencyCheck/data/database.html for all of
your dependency-check scans. Have most of the nodes setup not to update the
database, giving that responsibility to a single instance of ODC.

--Jeremy

**Comment by poblish** [comment]
In the end I restricted the number of concurrent requests to 3, and the errors have stopped - so I assume it was rate-limiting of a sort. Happy to close this issue as unnecessary.
