### ISSUE TITLE
Unable to find node module

### ISSUE THREAD

**Issue by mahzad** [dependency-check/DependencyCheck#5207]
I used ODC for keycloak but there are warns same with bellow: 
Unable to find node module: C:\Projects\keycloak-20.0.1\keycloak-20.0.1\themes\src\main\resources\theme\keycloak.v2\account\src\node_modules\stylehacks\node_modules\dot-prop\package.json

what do I do ?

**Comment by aikebah** [comment]
From the small amount of information you provide it's hard to give any further advice....
* what are you scanning (gut feel: an extracted source tarball)
* how are you scanning (ODC has different scanners for different build tools)

to really scan the keycloak project fir vulnerable dependencies (which I assume you attempt to do) you would typically clone their github repository, check out the tag for the version you're interested in and run the maven plugin of ODC against it.

**Comment by mahzad** [comment]
what are you scanning? 
All of source code keycloack 20.0.1 , it is  an open source identity and access management solution.
how are you scanning ? using maven plugin and just disabled Assembly analyzer in POM file.

**Comment by aikebah** [comment]
Then I would expect node.js related analyzers to run fine when you've made sure to first build the project so that the NPM plugin puts the node modules where the belong

`mvn package -DskipTests` before running the dependency-check plugin should typically do the trick (and for keycloak will download half of the internet if you've never built it before due to the size of it's dependency-tree.

**Comment by mahzad** [comment]
thanks , After installing nodjs my problem is solved . but these warning is remained. 

[WARNING] dependency skipped: node module patternfly-bootstrap-treeview seems optional and not installed
[WARNING] dependency skipped: node module @nicolo-ribaudo/chokidar-2 seems optional and not installed
[WARNING] dependency skipped: node module fsevents seems optional and not installed
[INFO] Finished Node.js Package Analyzer (49 seconds)
please answer this question.
 You or someone else has analyzed the output of the ODC project on Keycloak .  Is it suitable  for keycloack below configuration ? I want to generate good report without false negative.
rubygemsAnalyzerEnabled , bundleAuditAnalyzerEnabled and yarnAuditAnalyzerEnabled are disabled in root POM file.
