### ISSUE TITLE
Every update triggers a full update / 2023 datastream not loading

### ISSUE THREAD

**Issue by DaveBhoyGreen** [dependency-check/DependencyCheck#5215]
Dependency Check v7.4.3 CLI (also v7.4.1).

When the database realises it needs to update (after 4 hours since the previous update) it re-downloads and re-processes all data files from **nvdcve-1.1-2002.json.gz** onwards. Previously,  only **nvdcve-1.1-modified.json.gz** would be downloaded and processed.

Also, **nvdcve-1.1-2023.json.gz** is not downloaded, just **nvdcve-1.1-2023.meta**.

This behaviour seems to have started since the turn of the year (unsure if this is significant).

edit: Add log

[nvdache directory](https://user-images.githubusercontent.com/102809061/210790323-ad0de10f-5d6c-4730-affc-cd13474f1fe1.jpg)

[Update output.txt](https://github.com/jeremylong/DependencyCheck/files/10352503/Update.output.txt)

[dc.log](https://github.com/jeremylong/DependencyCheck/files/10353266/dc.log)

**Comment by preston-brown-icf** [comment]
This is also happening on 7.3.0.

**Comment by aikebah** [comment]
> This behaviour seems to have started since the turn of the year (unsure if this is significant).
> 
It is... and will auto-resolve when the first succesful import of a 2023 datastream is done.

There is a provision to not break due to absence of a datastream early in the year, but regardless of that it will do a full update of everything as long as no data has been loaded for the new year, since before checking the availability of the datastream a flag is already set that a full update is required because at least one year (the year just started) has never been loaded into the database.

We should definitely fix this, but once 7.4.4 is out (fixing the current issue in loading NVD data) the issue will be invisible for almost a year as by now the datastream of 2023 is present, so after the next successful update it will be seen by DependencyCheck that data for 2023 has been loaded and data-age is checked to see if full- or modified-only update is required.

**Comment by aikebah** [comment]
Hmmm..scratch the 'will be resolved after 7.4.4 can successfully load' I spotted some more bugs in the logic - should be fine again (until next year.... but before that I expect to develop a fix) after January 10.
As 7.4.4 should go out ASAP (issue 5220) and a fix of the download logic would need a bit better testing to ensure that this time it will really 'do the right thing early in the new year' I'm not going to rush the patch to try-and-squeeze it in for 7.4.4.

**Comment by aikebah** [comment]
On second thought.... fixing it is unnecessary as by the next turn-of-year there will be no more NVD datafeeds to import as the NIST is [phasing them out this year](https://nvd.nist.gov/general/news/change-timeline)

**Comment by aikebah** [comment]
Keeping the ticket open until 10 January has passed

**Comment by njsurat** [comment]
Any update on issue as still getting error finding CVE 2023 as below.

`> Task :dependencyCheckUpdate

Error downloading NVD CVE - 2023 Reason: Requested resource does not exists - received a 404

> Task :dependencyCheckUpdate
The execution of the download was interrupted
org.owasp.dependencycheck.data.update.exception.UpdateException: The execution of the download was interrupted
	at org.owasp.dependencycheck.data.update.NvdCveUpdater.performUpdate(NvdCveUpdater.java:289)
	at org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:136)`

**Comment by stevenpila** [comment]
> Any update on issue as still getting error finding CVE 2023 as below.
> 
> `> Task :dependencyCheckUpdate
> 
> Error downloading NVD CVE - 2023 Reason: Requested resource does not exists - received a 404
> 
> > Task :dependencyCheckUpdate
> > The execution of the download was interrupted
> > org.owasp.dependencycheck.data.update.exception.UpdateException: The execution of the download was interrupted
> > at org.owasp.dependencycheck.data.update.NvdCveUpdater.performUpdate(NvdCveUpdater.java:289)
> > at org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:136)`

Also experiencing the same issue as this currently, it affects all our builds, any solution to this one? or we can only wait for them to have the NVD CVE 2023? 
Thanks.

**Comment by aikebah** [comment]
@stevenpila  Sounds like you connect to a mirror that somehow doesn't have the 2023 datasterams. They've been available from NIST NVD for several days. My mirror had it's last update with `lastmodifieddate:2023-01-09T03:00:00-05:00`

**Comment by DaveBhoyGreen** [comment]
I can confirm my original problem(s) no longer occur, although others seem to still be having issues.

**Comment by stevenpila** [comment]
> @stevenpila Sounds like you connect to a mirror that somehow doesn't have the 2023 datasterams. They've been available from NIST NVD for several days. My mirror had it's last update with `lastmodifieddate:2023-01-09T03:00:00-05:00`

Hi, it's already working for us now and you're right, it was previously connected to a different mirror link (not the default) that still doesn't have the 2023 data streams. Thank you. :)
