### ISSUE TITLE
[FP]: Jolt json-utils mistaken for the fredsmith utils project

### ISSUE THREAD

**Issue by chadlwilson** [dependency-check/DependencyCheck#5218]
### Package URl

pkg:maven/com.bazaarvoice.jolt/json-utils@0.1.7  

### CPE

`cpe:2.3:a:utils_project:utils:0.1.7:*:*:*:*:*:*:*`

### ODC Integration

{"label"=>"Gradle Plugin"}

### ODC Version

7.4.3

### Description

The Jolt library at https://github.com/bazaarvoice/jolt is not the same thing as https://github.com/fredsmith/utils (which the CVE definitely relates to - and surprising that it has its own CPE....)

Related to #5213

**Comment by mprins** [comment]
duplicates #5213

**Comment by chadlwilson** [comment]
Fair enough, will close if we want to handle this with a non-automation suppression :-)
