### ISSUE TITLE
Global suppressions have no effect (same rule works when defined locally)

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [dependency-check/DependencyCheck#5222]
**Describe the bug**
In recent versions Liferay related FP suppressions were added to the global suppressions. (https://github.com/jeremylong/DependencyCheck/issues/5085)
However, I can still see one of libraries in the output. When exactly same definition is put into local suppression file and gradle plugin is configured accordingly, that library is suppressed.

**Version of dependency-check used**
The problem occurs using version 7.3.2 of the gradle plugin.

**To Reproduce**
build.gradle:
```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath group: "org.owasp", name: "dependency-check-gradle", version: "7.3.2"
    }
}

apply plugin: "org.owasp.dependencycheck"

dependencyCheck {
    formats = ["HTML", "XML"]
    analyzers {
        assemblyEnabled = false
        nodeEnabled = false
        nodeAudit {
            enabled = false
            yarnEnabled = false
        }
        ossIndex {
            enabled = false
        }
    }
    scanConfigurations = ["compileOnly"]
    //suppressionFile = "owasp-dependency-check-suppressions.xml"
}
```
owasp-dependency-check-suppressions.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<suppressions xmlns="https://jeremylong.github.io/DependencyCheck/dependency-suppression.1.3.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://jeremylong.github.io/DependencyCheck/dependency-suppression.1.3.xsd https://jeremylong.github.io/DependencyCheck/dependency-suppression.1.3.xsd">
    <suppress base="true">
        <notes><![CDATA[
        FP per issue #5085
        suppressing the liferay libraries that have a versioning scheme separate from the main framework version
        but get linked to the framework CPE
        ]]></notes>
        <packageUrl regex="true">^pkg:maven/com\.liferay\.portal/com\.liferay\.support\.tomcat@.*$</packageUrl>
        <cpe>cpe:/a:liferay:liferay</cpe>
        <cpe>cpe:/a:liferay:liferay_portal</cpe>
        <cpe>cpe:/a:liferay:portal</cpe>
    </suppress>
</suppressions>
```

**Expected behavior**
The `com.liferay.portal:com.liferay.support.tomcat` is suppressed by default, without custom suppression config. 

**Additional context**
It is unclear why another library, `com.liferay.portal:com.liferay.util.slf4j`, is suppressed correctly.

**Comment by aikebah** [comment]
Global suppressions are only taken into account when you configure them in your build-file as an additional suppressionFile. The change to use them by default (requiring internet access) is scheduled for v8 (#4901)
For v7.x you need to add the global suppressions published URL as an additional suppression-file.

**Comment by aikebah** [comment]
Suppressions from the global suppressions are added to the packaged suppressions when not forgotten shortly before the release for the 7.x series

**Comment by aikebah** [comment]
7.3.2 is several releases back, so will definitely miss out on a series of suppressions included in the later 7.x releases (7.4.3 is current latest)

**Comment by jan-tosovsky-cz** [comment]
A good spot! I overlooked my version is 7.3.2 (not 7.4.2). It makes a lot of sense now. I can't test it actually because of https://github.com/jeremylong/DependencyCheck/issues/5220 but I will keep you updated when possible.

**Comment by jan-tosovsky-cz** [comment]
I just mistakenly specified an outdated version in my gradle config.
