### ISSUE TITLE
dependency-check does not resume after failed database updates

### ISSUE THREAD

**Issue by xthk** [dependency-check/DependencyCheck#524]
Hi all,

I've noticed that dependency-check (at least 1.4.0) does not handle failed database updates as I would expect. If a database update fails, the database stays in an incomplete state and a subsequent update is skipped because dependency-check assumes everything is fine and the CPE/CVE data is valid. This seems to affect H2, as well as MySQL databases. I saw this for the CLI and for the Jenkins plugin. I think this is a different issue than #523, but it may be related.

In order to reproduce the issue, there is a simple shell script:
- [no_resume_after_failed_db_update.sh.txt](https://github.com/jeremylong/DependencyCheck/files/340893/no_resume_after_failed_db_update.sh.txt)

```
$ ./no_resume_after_failed_db_update.sh
++ mktemp -d dependency-check_XXXXXXXX
+ DATA_DIR=dependency-check_tp7QpBaY
+ MY_PID=77213
+ sleep 10
+ dependency-check --data dependency-check_tp7QpBaY --updateonly
[INFO] Checking for updates
[INFO] NVD CVE requires several updates; this could take a couple of minutes.
[INFO] Download Started for NVD CVE - 2002
[INFO] Download Started for NVD CVE - 2003
[INFO] Download Started for NVD CVE - 2004
[INFO] Download Complete for NVD CVE - 2003  (1329 ms)
[INFO] Download Started for NVD CVE - 2005
[INFO] Processing Started for NVD CVE - 2003
[INFO] Download Complete for NVD CVE - 2002  (1400 ms)
[INFO] Download Started for NVD CVE - 2006
[INFO] Download Complete for NVD CVE - 2004  (1617 ms)
[INFO] Download Started for NVD CVE - 2007
[INFO] Download Complete for NVD CVE - 2005  (659 ms)
[INFO] Download Started for NVD CVE - 2008
[INFO] Download Complete for NVD CVE - 2006  (1091 ms)
[INFO] Download Started for NVD CVE - 2009
[INFO] Download Complete for NVD CVE - 2008  (949 ms)
[INFO] Download Started for NVD CVE - 2010
[INFO] Processing Complete for NVD CVE - 2003  (2389 ms)
[INFO] Processing Started for NVD CVE - 2002
[INFO] Download Complete for NVD CVE - 2009  (1487 ms)
[INFO] Download Started for NVD CVE - 2011
[INFO] Download Complete for NVD CVE - 2010  (1115 ms)
[INFO] Download Started for NVD CVE - 2012
+ kill 77213
+ ls -sR dependency-check_tp7QpBaY
total 14472
14464 dc.h2.db          8 dc.lock.db
+ dependency-check --data dependency-check_tp7QpBaY --updateonly
[INFO] Checking for updates
[INFO] Skipping NVD check since last check was within 4 hours.
[INFO] Check for updates complete (2905 ms)
+ ls -sR dependency-check_tp7QpBaY
total 7544
7544 dc.h2.db
```

Please note, that there may occur a race condition, the "sleep 10" is just a rough guess and should help to reproduce in most cases.

There is a workaround, just set "cveValidForHours" to zero. Unfortunately the config interface for the Jenkins plugin does not offer this setting.

**Comment by jeremylong** [comment]
Thanks for the bug report; sorry it took me so long to respond. This issue has been resolved. The CVE updated timestamp is only saved after the update has completed. Thus, if the update gets interrupted it will run the update on the next execution even if under the 4 hour window.
