### ISSUE TITLE
Tips for false positive detection

### ISSUE THREAD

**Issue by mahzad** [dependency-check/DependencyCheck#5242]
Hi
ODC reports vulnerabilities for undertow web server module in shrinkwrap-container-undertow Artifact  although extracting  shrinkwrap-container-undertow artifact result to below classes , Can I say artifact reported is vulnerable?
org\jboss\shrinkwrap\undertow\api\UndertowHttpHandlerArchive.class
org\jboss\shrinkwrap\undertow\api\UndertowHttpHandlerArchiveImpl.class
org\jboss\shrinkwrap\undertow\api\UndertowWebArchive.class
org\jboss\shrinkwrap\undertow\api\UndertowWebArchiveImpl.class

**Comment by aikebah** [comment]
That's something you'd have to deduce from the various CVE's reported for it.

ODC reports vulnerabilities at a best-effort-linked vendor/product/version level when registered in the NVD, with a risk of mismatching the CPE due to the text-based search it does (and at component level for various other sources - e.g. OSSINDEX, node audit, RetireJS). Many products consist of multiple components, so the specific library that you use may or may not be affected.

Findings from OSSINDEX you can assume to really apply to the library (as OSSINDEX uses the package-URL to link vulnerabilities with libraries), findings from NVD may apply to another part of a framework and can even be wrongly linked to another product (false positive CPE match).

**Comment by mahzad** [comment]
please  comment on the specific example I mentioned.

**Comment by aikebah** [comment]
@mahzad We don't triage security issues in this project

**Comment by mahzad** [comment]
Thanks for guidelines

**Comment by mahzad** [comment]
> Findings from OSSINDEX you can assume to really apply to the library (as OSSINDEX uses the package-URL to link vulnerabilities with libraries), findings from NVD may apply to another part of a framework and can even be wrongly linked to another product (false positive CPE match).

please give  me an example for this? thanks

**Comment by aikebah** [comment]
Triage is left to the users by examining the evidences put forward in the CVEs reported together with the actual library being scanned.

So what you would do is: use the references under the various reported vulnerabilities and sort out whether the classes of the shrinkwrap-container-undertow component are the subject of the reported vulnerability. Frequently among the references are links to the commit that fixed it or the release-announcement that has the related bug-ticket referenced as a good starting point for where exactly in the codebase of a project the vulnerability resided.

If shrinkwrap-container-undertow is wrongly linked in your opinion to some CPE the appropriate follow-up would be to file a FP report issue for it, providing a rationale on why it should not have been linked up to that CPE.

If the CPE is valid, but the CVEs only are applicable to another part of the same product suppression would be up to a local suppression file.

Findings from OSSINDEX can be recognized as they have a listing that has `(OSSINDEX)` as a suffix in the title. The findings from the NVD have just the CVE as the title.

**Comment by mahzad** [comment]
> If the CPE is valid, but the CVEs only are applicable to another part of the same product suppression would be up to a local suppression file.
 if A library depended on B ( spring core is part of spring framework) and B ( springframework) had CVEs SO A (spring core ) is vulnerable. Is it correct?

**Comment by mahzad** [comment]
> If the CPE is valid, but the CVEs only are applicable to another part of the same product suppression would be up to a local suppression file.

 if" A " library depended on "B "(  ex. spring core is part of spring framework) and B ( spring framework) had CVEs SO A (spring core ) is vulnerable. Is it correct?

**Comment by aikebah** [comment]
> > If the CPE is valid, but the CVEs only are applicable to another part of the same product suppression would be up to a local suppression file.
> 
> if" A " library depended on "B "( ex. spring core is part of spring framework) and B ( spring framework) had CVEs SO A (spring core ) is vulnerable. Is it correct?

Strictly spoken: No, "A" is not vulnerable, but depends on vulnerable libraries. (In the end the production deployment would still contain vulnerabilities from project "B", so there would still be a security fix required). 

If you were to suppress a CVE for project "A" (as spring CVEs are typically linked to all parts of the framework) ODC would still report the CVE, but only for "B" and no longer also for "A".

In your example case: both libraries are part of the same framework, so there is no sense in upgrading "B" to a security-fixed version without also updating "A". 

As an example why "A" is not to be considered vulnerable by itself, assume your project depends on project "C" (aGreatUtilProject) which in turn depends on "D" (e.g. an old version of log4j2 with vulnerabilities)) you can force an update of the transitive dependency "D" (overrule the version to a newer version, backward compatible with the version that "C" depends on, but patched for the known vulnerabilities) which would yield a project with no vulnerabilities at all.

**Comment by mahzad** [comment]
Thank you for your very good explanation
