### ISSUE TITLE
upgrade_5.3.sql ia missing

### ISSUE THREAD

**Issue by rpaasche** [dependency-check/DependencyCheck#5251]
**Describe the bug**
Upgrade script to database schema version 5.3 is missing.

Workaround:
Rebuild the database with the initialize script.

**Comment by aikebah** [comment]
It's not, upgrade-scripts are using a 'from' version. The script to update to 5.3 is:

https://github.com/jeremylong/DependencyCheck/blob/main/core/src/main/resources/data/upgrade_5.2.1.sql

(that is: assuming that you are currently up-to-date at version 5.2.1)

**Comment by rpaasche** [comment]
Argh thank you.
