### ISSUE TITLE
I am not able to refer to the suppression.xml file in a common project included as a dependency

### ISSUE THREAD

**Issue by jainishan** [dependency-check/DependencyCheck#5257]
I have a handful of projects and all of them include a common dependency (let's call it common-project) and it is defined like this:

```
<dependency>
	<groupId>com.mycom</groupId>
	<artifactId>common-project</artifactId>
	<version>1.0.23</version>
</dependency>
````

All of these projects have dependency check step in the builds somewhere, and so far have their own suppressions file.

```
<plugin>
		<groupId>org.owasp</groupId>
			<artifactId>dependency-check-maven</artifactId>
			<version>7.3.0</version>
			<configuration>
				<format>ALL</format>
				<failBuildOnCVSS>8</failBuildOnCVSS>
				<suppressionFiles>
					<suppressionFile>owasp-suppression.xml</suppressionFile>
				</suppressionFiles>
			</configuration>
			<executions>
				<execution>
					<goals>
						<goal>check</goal>
					</goals>
				</execution>
			</executions>
</plugin>
```

Whenever a new vulnerability comes in which we need to suppress, it becomes a pain to update all of the projects. So I decided to centralize the suppression file and the best place to put that seems like the common-project.

Now, I prepare a 'master' suppression file and put it in src/main/resources of common-project and I can confirm that it is available at the root level of common-project-1.0.23.jar

Now the problem is that I just can't seem to be able to include it in the downstream project. 
Amongst other things, 
I tried referring to the file inside of the JAR:

````
<plugin>
	<groupId>org.owasp</groupId>
	<artifactId>dependency-check-maven</artifactId>
	<version>7.3.0</version>
	<configuration>
		<format>ALL</format>
		<failBuildOnCVSS>8</failBuildOnCVSS>
		<suppressionFiles>
			<suppressionFile>${settings.localRepository}/com/mycom/common-project/1.0.23/common-project-1.0.23.jar/owasp-suppression.xml</suppressionFile>
		</suppressionFiles>
	</configuration>
	<executions>
		<execution>
			<goals>
				<goal>check</goal>
			</goals>
		</execution>
	</executions>
</plugin>

```
I would get a warning mentioning it was not able to find the file:

```
[WARNING] Unable to read suppression file '/Users/me/.m2/repository/com/mycom/common-project/1.0.23/common-project-1.0.23.jar/owasp-suppression.xml
```

And also tried specifying this dependency again:
````
			<plugin>
				<groupId>org.owasp</groupId>
				<artifactId>dependency-check-maven</artifactId>
				<version>7.4.4</version>
				<configuration>
					<format>ALL</format>
					<failBuildOnCVSS>8</failBuildOnCVSS>
					<suppressionFiles>
						<suppressionFile>owasp-suppression.xml</suppressionFile>
					</suppressionFiles>
				</configuration>
				<dependencies>
					<dependency>
	                                    <groupId>com.mycom</groupId>
	                                    <artifactId>common-project</artifactId>
	                                   <version>1.0.23</version>
                                         </dependency>
				</dependencies>
				<executions>
					<execution>
						<goals>
							<goal>check</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
```

And this one complains that the artifact common-project is not found in maven central repo.


So what would be the standard way of referring to suppressions file inside of a dependency jar ?
Should I be copying the file out from the jar using some plugin ?

**Comment by ericheythedev** [comment]
I'm currently experiencing a similar issue after upgrading from 7.1.2 to 7.4.4 due to the 5220 issue fix the other day.
I have multiple mvn sub-projects, and the parent pom file has the plugin config and defines where the suppression-file is, such as:
<suppressionFile>${project.basedir}/owasp/...  </supressionFile>
This no longer works once upgraded and am getting a SuppressionParseException, caused by Unable to read suppression file.
The project.basedir appears to be evaluating wrong, being eval'd against each subproject (which each sub project does not have the suppression file, only the parent).

**Comment by aikebah** [comment]
@ericheythedev that's a completely different scenario from the loading-from-classpath

**Comment by aikebah** [comment]
@jainishan The error message appears to suggest that maven is unable to locate your common-project artifact.

My gut feel is that you need to customize the pluginRepositories of your project to include your private artifact repository where the common-project artifact resides. See also https://maven.apache.org/pom.html#plugin-repositories and https://maven.apache.org/pom.html#the-super-pom
You likely have defined an additional repository, but rely on the maven default pluginRepositories.

Don't know for sure, as I've always worked in environments where a datacenter-local repository-mirror is setup, so any request - be it from the pluginRepositories or the repositories - towards central is redirected to that mirror, which also hosts the private artifacts.

**Comment by jainishan** [comment]
@aikebah your gut feeling was correct. I didn't realise it until now that we are supposed to configure pluginrepositories in addition to repositories when we have custom ones.
I added <pluginRepositories> and the second solution worked for me. 
Although having to redefine a dependency in the plugin looks a bit annoying but it gets the work done. I wish there was a cleaner way - like simply referring to the existing dependency as it has been imported in the dependencies section.

**Comment by aikebah** [comment]
I think there is a cleaner way from configuration perspective: host a suppression-file with common false positives 'publicly' on an intranet webserver. Then you only need to configure the suppressionFile URL (you can specify multiple suppressionfiles if needed)

**Comment by jainishan** [comment]
I considered storing on artifactory as well but then we have the issues with access and accidental overrides. Thus went with this common project.
