### ISSUE TITLE
problem downloading 7x gradle plugin

### ISSUE THREAD

**Issue by ThomasCraigNelson** [dependency-check/DependencyCheck#5258]
I want the fix for https://github.com/jeremylong/DependencyCheck/issues/5220, but when I changed to 

classpath 'org.owasp:dependency-check-gradle:7.4.4'

I get 
> Failed to notify dependency resolution listener.
   > cannot recognise keyAlgorithm: 22

However for 
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'org.owasp:dependency-check-gradle:6.1.6'
    }
}
it works.  This seems like a difference in how things were deployed to maven repo?  Is there a workaround?  Should I report a bug?
Thanks,
Tom

**Comment by aikebah** [comment]
Sounds like you're using a (likely old) gradle version that doesn't understand the algorithm of the PGP signature used to validate that the plugin artifacts reached your system unmodified.

**Comment by aikebah** [comment]
Algorithm 22 turns out to be EdDSA (https://github.com/bcgit/bc-java/blob/7221f2d1d5903ba7a39546c0739251827a71b67d/pg/src/main/java/org/bouncycastle/bcpg/PublicKeyAlgorithmTags.java#L21), which was added in BouncyCastle 1.60

It's likely one of the dependencies that is signing artifacts with such a key, as the key used for signing the artifacts of DependencyCheck itself is an RSA key.
Your gradle classpath is apparently having a BouncyCastle older than v1.60 which does not yet have support for EdDSA public keys.

**Comment by ThomasCraigNelson** [comment]
I get the same issue with gradle 7.6 which they claim is the latest.  In addition, I attempted to "extend" openjdk 17 by creating jre/lib/ext and copying 
cp /home/tnelson/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcpg-jdk18on/1.71/d42ad9fe1b89246bb4ca2a45c0646bf6f6066013/bcpg-jdk18on-1.71.jar jre/lib/ext

Also edited conf/security/java.security with
security.provider.13=org.bouncycastle.jce.provider.BouncyCastleProvider

Also tried adding:
buildscript {
    repositories {
        mavenCentral()
    }
// run with gradle dependencyCheckAnalyze
    dependencies {
        classpath 'org.owasp:dependency-check-gradle:7.4.4'
        classpath 'org.bouncycastle:bcprov-jdk18on:1.71'
    }
}
To my gradle file.  None of this helped.  Anybody have more suggestions?  Thanks.

**Comment by aikebah** [comment]
check your project classpath. As BC changed their coordinates there may still be a bcprov-jdk15on (or bcprov-jdk14) that wins the race on your classpath for delivering the bouncycastlemimplementation classes.

 (the runtime resolved classpath that is, including transitive deps; not familiar enough with the gradle environment to get more specific than this, but it's important to remember that 'the first found class matching package-qualified classname' is used by java, so if you have multiple bouncycastle lib version on the classpath you may end up with a different class then you expect to get)

**Comment by ThomasCraigNelson** [comment]
I did find that settings.gradle was pulling in older versions and stopped doing so when I added excludes:
    classpath('com.github.vlsi.gradle:checksum-dependency-plugin:1.28.0') {
      // Gradle ships kotlin-stdlib which is good enough
      exclude(group: "org.jetbrains.kotlin", module:"kotlin-stdlib")
     exclude(group: "org.bouncycastle", module:"bcprov-jdk15on")
    }

still trying to resolve 7.4.4, BUT 6.1.5 stopped having the #5220 , problem so my urgency is lower and it may be some time before I resume figuring out how to get 7.4.4 to work for me.

**Comment by ThomasCraigNelson** [comment]
I found a resolution.  It turns out there was interference between an older version of com.github.vlsi.gradle:checksum-dependency-plugin and org.owasp:dependency-check-gradle:7.4.4, moving checksum-dependency-plugin to version 1.86, updating the def expectedSha512 = [ construct for it as needed, the owasp plugin started behaving properly.

Thanks to all for suggestions.  Thanks.
