### ISSUE TITLE
False positive analysis

### ISSUE THREAD

**Issue by Dhanxy** [dependency-check/DependencyCheck#5260]
Hi team, I'm telling you that I'm trying to perform an analysis excluding false positives.
I have reviewed the DependencyCheck documentation and I have created the xml file but I don't understand how to proceed. Could you tell me how to proceed? Should I configure something in the gradle file? What command should I run? Note that I am using Gradle 7.6

**Comment by aikebah** [comment]
Look again and let us know where you get stuck and what you already did.

https://jeremylong.github.io/DependencyCheck/dependency-check-gradle/index.html

all the configuration listed ends up in your gradle buildfile if you want to use them.

**Comment by Dhanxy** [comment]
I executed the command and the result is successful but the vulnerability is not excluded.

What I am doing is the following:

In the html file, I click on "suppress" then on "Complete XML doc".

I copied the XML code and created an XML file and pasted the code.

Later I copied the file and placed it in the folder of the project to analyze.

Finally, I run the command and it's successful but it doesn't exclude the false positive.

Am I skipping a step? or am i doing something wrong?

**Comment by aikebah** [comment]
From your description it looks like you did not configure a `suppressionFile` or `suppressionFiles` for the dependency-check plugin in your gradle build file. Dependency-check makes no assumptions about suppressionfile-filename or -location, so you always need to be explicit on what suppression file(s) (if any) is to be used in the scan (https://jeremylong.github.io/DependencyCheck/dependency-check-gradle/configuration.html)

**Comment by Dhanxy** [comment]
I managed to execute the suppression of false positives.

In the build.gradle file I was missing the following:

dependencyCheck {
    suppressionFile = file("file.xml")
}

I take advantage of asking, what is the difference between the following commands:

"./gradlew dependencyCheckAnalyze" and "gradle dependencyCheckAnalyze --info"

**Comment by aikebah** [comment]
@Dhanxy For `gradle` versus `./gradlew` see https://docs.gradle.org/current/userguide/gradle_wrapper.html
The first invokes the standard gradle installed in your system, the second starts a gradle version (downloading it if needed) that matches the gradle-wrapper.properties configuration stored within the project. 

The `--info` is a parameter that tells gradle that you want more verbose logging
https://docs.gradle.org/current/userguide/logging.html

So the first command runs dependencycheck using the gradle-wrapper defined and managed gradle at default loglevel (lifecycle), the second runs dependencycheck using the system-installed gradle at info loglevel.

**Comment by Dhanxy** [comment]
Thank you very much for the help
