### ISSUE TITLE
Finding number of cve records created by ODC cli tool 

### ISSUE THREAD

**Issue by Dnu12** [dependency-check/DependencyCheck#5262]
Hi team,

     How could I find out number of cve records created by ODC CLI tool ?

**Comment by Dnu12** [comment]
@aikebah Any help on this ?

**Comment by mprins** [comment]
please explain why you think that ODC generates CVE records?

**Comment by Dnu12** [comment]
Oh sorry.I mean how many cves were downloaded from nvd feeds and inserted into db tables ? 
We've taken ODC source code and have made changes to store cves and cpes into our product db .(We only changed storing part ) .Now when we run ODC in our product ,number of vulnerable components is higher for same build compared with one run using ODC CLI tool (without any changes).So I wanted to make sure that our product db and db used by ODC ClI has same number of cves to start with.

**Comment by Dnu12** [comment]
@jeremylong @aikebah Please help on this ?

**Comment by jeremylong** [comment]
download h2 and use `h2.sh` to open the database and query?

**Comment by Dnu12** [comment]
Maybe can we show it in terminal before starting the analysis ?

**Comment by Dnu12** [comment]
what url should be used ? I don't have any 'dependency-check-data' inside my .m2 folder in my user home ( it only has dependency-check-core jar ) @jeremylong .

**Comment by Dnu12** [comment]
Hi @jeremylong , I connected with local h2 db file and queried count(*) from vulnerability,cpeentry and software tables .And their respective counts are 152600,229035 and 1104883 .Which is lesser than record counts we have in our product db .Respective counts in our product db are 192305(cves count ),365665(cpes count) and 2173680(mapping records count) . 

What should I do to do scan with full cve,cpe datas in CLI ? ( I tried 'sh dependency_check.sh --purge' and 'sh dependency_check.sh -s 'build_path' but not working ) . Please let me know if I'm doing something wrong ? ( Do I miss something to download full cve and cpes record ? ). Thanks for all the help. :smiley:  @aikebah

**Comment by jeremylong** [comment]
ODC filters several CVE entries out as they are not relevant to analyzing the application layer. take a look at the code in ODC - its public and is the best source of truth as to why you might be seeing a difference from your product db.
