### ISSUE TITLE
General report from maven multiple modules

### ISSUE THREAD

**Issue by guessw4o** [dependency-check/DependencyCheck#5267]
I have project with 6 modules, plugin check all modules -> find vulnerabilities -> creating reports(json, html) in module folder and write all this in log. But in general log he dont write about all this vulnerabilities in every module.
How I can do this?

**Comment by jeremylong** [comment]
Use the aggregate goal: https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html
