### ISSUE TITLE
 Could not execute .NET AssemblyAnalyzer

### ISSUE THREAD

**Issue by joedesjunior** [dependency-check/DependencyCheck#5269]
I'm a problem before config my pom.xml with: 

```
<build>
                <plugins>
                    <plugin>
                        <groupId>org.sonarsource.scanner.maven</groupId>
                        <artifactId>sonar-maven-plugin</artifactId>
                        <version>3.7.0.1746</version>
                    </plugin>
                    <plugin>
                        <groupId>org.owasp</groupId>
                        <artifactId>dependency-check-maven</artifactId>
                        <version>7.4.4</version>
                        <configuration>
                            <skipProvidedScope>true</skipProvidedScope>
                            <skipRuntimeScope>true</skipRuntimeScope>
                            <formats>HTML,XML,JSON</formats>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>check</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
```
```
09:11:49  [ERROR] Failed to execute goal org.owasp:dependency-check-maven:7.4.4:check (default) on project web-bff: One or more exceptions occurred during dependency-check analysis: One or more exceptions occurred during analysis:
09:11:49  [ERROR] 	InitializationException: Could not execute .NET AssemblyAnalyzer
```

anyone with the same error?

**Comment by aikebah** [comment]
Which version(s) of dotnet runtime do you have installed? (You must have at least one, otherwise you would've had another error-message, which is indicating that the dotnet runtime is not installed prompting you to either install it or disable the analyzer to prevent the error-message. That error message would still allow the analysis to run to a successful completion)

The analyzer requires a dotnet runtime version 6.x (to 6.x or above, but 6.x; you can have multiple dotnet runtimes side-by-side)

In case you're wondering why it is running the Assembly Analyzer: This is likely triggered by your maven project because one or more of your dependencies have a .dll with native code (JNI) for windows environments embedded in the jar file.

**Comment by jeremylong** [comment]
If you are positive you do not have .NET assemblies - you can just disable the analyzer.

**Comment by HaGGi13** [comment]
Hello @aikebah,
hello @jeremylong 

Just to be sure, it is enough to have the .NET Runtime installed, so it is not the .NET Desktop Runtime or even the .NET SDK needed?

It would be helpful if it's listed on this page [OWASP / Dependency-Check / documentation / Assembly Analyzer](https://jeremylong.github.io/DependencyCheck/analyzers/assembly-analyzer.html) too. It just states:

> .NET core 6.x needs to be installed for this analyzer to work.

In my case, we have dedicated OWASP DC agents which execute the OWASP DC only, so we are able to keep them clean and as simple as possible. Therefore we want to avoid to install a SDK if it's not needed. AFAIK no .NET app build is needed to analyze .NET projects or am I wrong? Couldn't find any detailed information about this too.

Thank you in advance for a reply.

BR, Chris

**Comment by jeremylong** [comment]
the dotnet 6 runtime is sufficient.

**Comment by HaGGi13** [comment]
@jeremylong thank you a lot for the reply.

May I ask you if my last paragraph is right too or is a build of a .NET application necessary before a DC analysis is executed? Please give an advice or point me to a doc where it's explained.

> In my case, we have dedicated OWASP DC agents which execute the OWASP DC only, so we are able to keep them clean and as simple as possible. Therefore we want to avoid to install a SDK if it's not needed. AFAIK no .NET app build is needed to analyze .NET projects or am I wrong? Couldn't find any detailed information about this too.

**Comment by jeremylong** [comment]
There are analyzers for both dotnet project files (nuget managed dependencies) and there are analyzers that will inspect the actual DLL files. For dotnet, I would recommend building the project and publishing it to a local folder and including that in the scan.
