### ISSUE TITLE
NVD deprecation on V1 API and Data Feeds - Any Impacts?

### ISSUE THREAD

**Issue by Lingom-R** [dependency-check/DependencyCheck#5286]
Hi,
NVD announced that they are going to deprecate the V1 API and retire the Data feeds as they are launching the V2 of their API. Does it impact DependencyCheck or DependencyCheck have plans to use the NVD's v2 API?

End of Life announcement from NIST Data Mirror:   https://github.com/stevespringett/nist-data-mirror/

**Comment by jeremylong** [comment]
Nope - couldn't possibly have an impact `</sarcasm>`. see #4732
