### ISSUE TITLE
live updates on dependency check failures

### ISSUE THREAD

**Issue by javabeanz** [dependency-check/DependencyCheck#529]
Applications that have been deployed, are not monitored for newly discovered dependency vulnerabilities, maybe DependencyCheck can support this; perhaps with some event (pub/sub) mechanism.

**Comment by jeremylong** [comment]
There are a couple ways people have been handling this. One, setup a Jenkins job to monitor a folder and put all of your deployed WAR files into the folder. Run the report weekly to see if anything new crops up.  Another mechanism is to use @stevespringett 's [dependency-track](https://github.com/stevespringett/dependency-track).

**Comment by javabeanz** [comment]
Don't you think this is a feature the Maven plugin could facilitate, that
is, to report only deltas (new vulns) ?

**Comment by jeremylong** [comment]
You would have to elaborate on what you think the Maven plugin could facilitate. You could run the maven plugin on your tagged/released version and upload the XML results to something like ThreadFix or do a diff with the last run.

**Comment by javabeanz** [comment]
What about near-real time updates ? You get a message when there is a new
vuln found in a dependency that matters, as a push service. All
applications using that dependency, and applications further down the
service chain, would get that message.

**Comment by jeremylong** [comment]
That is more what dependency-track was written to do.
