### ISSUE TITLE
7.4.4  Database schema does not match this version of dependency-check

### ISSUE THREAD

**Issue by Tord-BG** [dependency-check/DependencyCheck#5292]
**Describe the bug**
We are running a centralpostgres-DB and after update to clients v7.4.4 we get the error stated in the subject. 

**Version of dependency-check used**
7,4,4 , have tried to run the upgrade-scripts both in main and in branch 7.4.4 wiich provide version values from 5.3 to 5,4 for the DB but didnt help. 

**Log file**
 Failed to execute goal org.owasp:dependency-check-maven:7.4.4:update-only (default) on project UpdateDepCheck: An exception occurred connecting to the local database. Please see the log file for more details. Database schema does not match this version of dependency-check: Database schema is out of date -> [Help 1]

**To Reproduce**
1.Do dep-check with central db on version 7.4.4
2. Try upgrade / init-scripts available

**Expected behavior**
An update of the DB when using the update-only goal in maven

**Comment by thpe1000** [comment]
We're are experiencing the same issue

**Comment by aikebah** [comment]
https://github.com/jeremylong/DependencyCheck/blob/220140becf5a94da2b7e66514224af032b2ac3eb/core/src/main/resources/data/upgrade_5.2.1.sql

Is the script that should work. You should double-check your postgresql schema to validate that it really updated the version row of the Properties table to 5.3

```sql
UPDATE Properties SET `value`='5.3' WHERE ID='version'; 
```

Does your postgresql instance use a schema/database and did you not modify the script to match your schema/database or update your postgresql query-session to default to that schema/database?

**Comment by aikebah** [comment]
Note: it's more than just the Properties update.... also the other DDL would require the prefixing of your schema/database if that is indeed what causes your failures.

**Comment by Tord-BG** [comment]
Hi again and thanks for reply. Realized that I had been running the init-scripts which altered the psw to the db, stupid of me! 

However, the version 5.4 stated in script from master-branch work and not the 5.3 which are in the upgrade-script in branch 7.4.4

My issue has been resolved
