### ISSUE TITLE
commandline tool is lacking useful debug information to handle secure cloud environments

### ISSUE THREAD

**Issue by uvwildos** [dependency-check/DependencyCheck#5298]
In a secure environment we are always happy when something is working, but if not it can always have numerous reasons.

So configuring a base url (not well documented which endpoint is referred to)
and then reducing the failed requests to just HTTP responses is not sufficient in helping other than saying it does not work!
There is hardly any info to find on getting this to work, and the log doesn't tell us why.

**So please consider this feature request:**

It would be very helpful to find the relevant information to analyse the connecting failure in the DEBUG log, or with some additional parameter to increase the connection log level. 
In particular the debugging of headless systems inside a k8s cluster or an cloud instances in more secure and complex network environments (e.g. java-slaves) relies on logs only.

I understand that the central search is the better supported way to go, 
But since the maven central stopped working reliably on 12. january 2023 for some higher frequented CICD systems,
using the internal nexus instance became mandatory and the unsatisfying log and documentation situation an issue.

https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html
Example: http://domain.enterprise/nexus/service/local/ is not supported anymore in current nexus versions 3.3X

`~/dependency-check/bin/dependency-check.sh -l ~/workspace/depCheck.log --disableCentral --enableNexus --nexus https://domain.enterprise/nexus/service/rest/  --nexusUser $USERNAME--nexusPass $PASSWORD`
or
`~/dependency-check/bin/dependency-check.sh -l ~/workspace/depCheck.log --disableCentral --enableNexus --nexus https://domain.enterprise/nexus/service/rest/v1/search/assets  --nexusUser $USERNAME--nexusPass $PASSWORD`
        **[WARN] Expected 200 result from Nexus, got 404**
does not connect , whereas

`curl  -u $USERNAME:$PASSWORD https://domain.enterprise/nexus/service/rest/v1/search/assets`
works

I am at a loss here. this seems like the same issue as 
https://github.com/jeremylong/DependencyCheck/issues/230 from 2015  ?!?

Dependency-Check Core version 7.4.4

**Comment by jeremylong** [comment]
Regarding documentation - did you read anything on the documentation site? Such as the page titled [Internet Access Required](https://jeremylong.github.io/DependencyCheck/data/index.html)?

**Comment by uvwildos** [comment]
Sure. I downloaded the source code and saw the log entries created lacking the info. 
But setting up debugging for my use case was not so straight forward and cannot be done easy enough on the cloud node.
It does download the indexes and does connect to central.... which then fails with 502 since Thursday.

But since this is a public server there is no way to contact the operations team. I asked sonatype. 

As usual support never works on my levels of questions. Support these days is more focused on closing tickets, than helping a user and its usually based on limited understanding of the system at hand.

**Comment by aikebah** [comment]
Regarding the 502: that HTTP code already tells you that it's an issue somewhere upstream in a proxy (Bad Gateway) and is usually not giving any useful information. You'd have to contact the first gateway to check if it's from them... if not find out what the next gateway is... until you reach the point where the gateway would be something out of your perimeter and accept that apparently 'the internet' is temporarily broken.

See also https://status.maven.org/ which indeed indicates that the internet can sometimes be broken.

You don't give any indication what kind of info would be needed according to your view in order to do more, but I suspect that there is very little information to report beyond the HTTP status.

**Comment by aikebah** [comment]
In the typical case that would only be checking once with the admins of the proxy at the edge of your secure cloud, but potentially there could be multiple proxies chained

**Comment by uvwildos** [comment]
so with a lot of demand from the large user community, the maven.org server has been fixed and we can carry on with out business.... thanks for the feedback.

this is like a wont fix status I'd say

**Comment by uvwildos** [comment]
With a lot of demand from the large user community, 
the maven.org server has been fixed and we can carry on with out business.... thanks for the feedback.

so I close this with a wont fix status ....
