### ISSUE TITLE
DependencyCheck 8.0.0 writes in dependency-check-data/7.0

### ISSUE THREAD

**Issue by nils-christian** [dependency-check/DependencyCheck#5312]
Hi!

**Describe the bug**

When using the DependencyCheck maven plugin in Version 8.0.0, it writes the database still into dependency-check-data/7.0. I assume that this is wrong, because the release notes state:

`Breaking: the database schema updated - if using an external database the update scripts must be run!`

**Version of dependency-check used**
The problem occurs using version 8.0.0 of the maven plugin.

**Expected behavior**

Version 8.0.0 of the maven plugin should write its data to dependency-check-data/8.0

**Comment by jeremylong** [comment]
Actually - this is correct. The database schema is upgraded automatically when using the embedded H2 database. This is breaking for anyone using an external database.

**Comment by nils-christian** [comment]
Hi @jeremylong,

I see, thank you for the answer. So it is not an issue to use both Version 7.X and 8.X of the maven plugin with the same maven repository? 7.X can still use the database written by 8.X?
