### ISSUE TITLE
Similartools to keep track of JDK CVE:s

### ISSUE THREAD

**Issue by profTwinglings** [dependency-check/DependencyCheck#5316]
I am a user of dependency check and happily using it to detect CVE's for any maven dependencies, and by doing a special project I even managed to import Tomcat for scanning.

But how can I scan my Java JDK in a similar fashion? How are you doing these things in your build-pipelines? Im using several git branches with yaml files keeping track of JDK versions, but how can I automatically scan them for vulnerabilities?

**Comment by aikebah** [comment]
Typically I would opt to not be explicit in pipeline files on the patch-version of java (but only on major versions) and ensure in other ways that e.g. 'the Java 11 used in my pipelines' is always the latest patch release available.

So pipeline would say 'use jdk11' and somewhere I would have an administrator of the CI environment monitor the java releases and ensure that when jdk11 april-patches 2024 is available jdk11 is updated to it.

It's how I manage our legacy Jenkins instance at work and how a central department manages the docker images used in Gitlab runners and Jenkins instances of the new build forge.
Developers just specify that they want the jdk8/11/17 flavor and buildsystem admins ensure that those are at a patched version.

**Comment by profTwinglings** [comment]
> Typically I would opt to not be explicit in pipeline files on the patch-version of java (but only on major versions) and ensure in other ways that e.g. 'the Java 11 used in my pipelines' is always the latest patch release available.
> 
> So pipeline would say 'use jdk11' and somewhere I would have an administrator of the CI environment monitor the java releases and ensure that when jdk11 april-patches 2024 is available jdk11 is updated to it.
> 
> It's how I manage our legacy Jenkins instance at work and how a central department manages the docker images used in Gitlab runners and Jenkins instances of the new build forge. Developers just specify that they want the jdk8/11/17 flavor and buildsystem admins ensure that those are at a patched version.

Thanks for the detailed info @aikebah. What im looking for is the tooling how buildsystems admins ensure that the jdk's are a patched version? There should be some tool that can send notifications when vulnerable Java-versions are out there. 

We are currently sending out the JDK embedded with our product, which would force us to monitor vulnerabilities across JDK's.

**Comment by jeremylong** [comment]
One option would be to spin up an instance of dependency-track.

**Comment by aikebah** [comment]
> We are currently sending out the JDK embedded with our product, which would force us to monitor vulnerabilities across JDK's.

>> One option would be to spin up an instance of dependency-track.

+1 to that. For continuous monitoring on shipped products based on software composition dependency-track is doing a nice job. We have the two in tandem-usage as well. dependency-track monitoring the packaged-and-shipped versions of our software and dependency-check guarding the libraries during the development pipeline.
