### ISSUE TITLE
Error connecting to the database with CLI

### ISSUE THREAD

**Issue by ioverzero** [dependency-check/DependencyCheck#532]
Version 1.4.0.

Running on Ubuntu 14.04, I installed the dependency check cli from http://jeremylong.github.io/DependencyCheck/dependency-check-cli/index.html

and I followed the instructions, and then tried to test the program with:

./dependency-check.sh --project Testing --out . --scan /home/juan/Documents/project

but I get the following error:

[ERROR] Unable to connect to the dependency-check database; analysis has stopped

which I saw was closed issue #457, therefore no help is currently available.

**Comment by ecki** [comment]
I would suggest you create a logfile with the --logfile "log.txt" option and share this with us.

**Comment by jeremylong** [comment]
Also, Java 6/7 users are experiencing an issue with HTTPS connections to the NVD (see issue #523). This has been resolved in the current snapshot and will be published soon.

**Comment by ioverzero** [comment]
Okay I tried the following commands and didn't get a log file generated (a non-empty one), but they might be useful:

user@computer:~/DepCheck/dependency-check$ ./bin/dependency-check.sh --project Testing --out . --scan /home/user/Documents/project --log logfile.txt
[INFO] Checking for updates
[WARN] Unable to download the NVD CVE data; the results may not include the most recent CPE/CVEs from the NVD.
[INFO] If you are behind a proxy you may need to configure dependency-check to use the proxy.
[INFO] Check for updates complete (2231 ms)
[ERROR] No documents exist

Unable to continue dependency-check analysis.
[ERROR] There was an IO error while attempting to generate the report.

**Comment by ioverzero** [comment]
Java version info:

user@computer:~/DepCheck/dependency-check$ java -version
java version "1.7.0_101"
OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-0ubuntu0.14.04.1)
OpenJDK Server VM (build 24.95-b01, mixed mode)

**Comment by jeremylong** [comment]
This is likely related to https://github.com/jeremylong/DependencyCheck/issues/523#issuecomment-231458697. The comment linked to provides a likely solution.  The core engine has been updated to resolve this issue and a new version will be released shortly.

**Comment by jeremylong** [comment]
1.4.1 was released this morning and the patch to resolve this issue was included.
