### ISSUE TITLE
Central Analyzer is taking 20 times longer to finish in new (v8.0.0) version

### ISSUE THREAD

**Issue by ghost** [dependency-check/DependencyCheck#5338]
Hi,

I was wondering if anyone else has noticed similar behavior after moving to the new v8.0.0 version? In version 7.4.4 it took approx 70 seconds for Central Analyzer to finish, and in version 8.0.0 it takes approx 1800 seconds. I have included screenshots of those times:
- v8.0.0
![Screenshot 2023-01-18 at 09 26 49](https://user-images.githubusercontent.com/96594829/213127119-1c718688-3e93-4ed2-9ee2-d5b271541e73.png)

- v7.4.4
![Screenshot 2023-01-18 at 09 26 05](https://user-images.githubusercontent.com/96594829/213127126-c911f9e5-c2f3-4a62-bf5c-a2a24c07a7cf.png)

**Comment by aikebah** [comment]
My gut feel would be that you are checking a large dependency set and are hitting the instability of Maven Central Search - https://status.maven.org/

When nothing is overridden in configuration DependencyCheck retries 3 times with 1500ms pauses in between first and second try, 3000ms pause between second and third try).

I would expect warnings however in your build logs on
`Unable to download pom.xml for <the dependency> from Central....` if indeed the retries are at the root of it.

**Comment by ghost** [comment]
I don't see such logs, but I have now changed the version to 7.4.4 and I see the same issue, Central Analyzer is now taking more than 30 mins...and will probably hit the timeout (1h) of our runner. But it could be that issue is maven.org as currently status page is reporting some intermittent timeout errors.

**Comment by ghost** [comment]
Thanks @aikebah, I will close this question as it clearly is not connected to new version.

**Comment by aikebah** [comment]
Ah... I get it... if at least one of the tries succeeds... then nothing is logged. And with the earlier reported 'approximately one in 4 requests' you're likely to have at least one of the three requests succeed.

Don't know how your CI infrastructure is organized, and how much of your dependencies would be resolvable from maven central, but if you provide a persistent data location for dependencycheck you may be able to speed up the scans as by default also the central search results are cached in the datadirectory alongside the CVE database.
