### ISSUE TITLE
[FP]: io.openliberty.grpc.1.0.internal*jar is being tripping multiple Google gRPC CVEs

### ISSUE THREAD

**Issue by rseeton** [dependency-check/DependencyCheck#5343]
### Package URl

pkg:maven/dev/io.openliberty.grpc.1.0.internal@1.0.62.cl220320220302-1100  

### CPE

`cpe:2.3:a:grpc:grpc:1.0.62.cl220320220302.1100:*:*:*:*:*:*:*`

### ODC Integration

{"label"=>"CLI"}

### ODC Version

8.0.0

### Description

The scan of the Open Liberty 22.0.0.3 package is tripping a lot of CVEs - it looks like at least some are poorly formed CPEs.

Thanks!

**Comment by rseeton** [comment]
I've evidently entered the pkg data incorrectly.  I'm not entirely clear on what the correct setup should be, but the following Kotlin Gradle call works:

**_implementation("io.openliberty.api:io.openliberty.grpc.1.0:1.0.62")_**

**Comment by aikebah** [comment]
The correct setup you should be able to copy/paste from the report. There should be nothing to construct there, dependencycheck should already build it for you from the maven coordinates

**Comment by aikebah** [comment]
But maybe what you scanned was a snapshot-version of the library, as for 'the real deal' I would expect it to end in `@1.0.62` with the gradle coordinates you mention.

**Comment by rseeton** [comment]
Hmmm... I will need to follow-up with the team packaging this third-party component.

@aikebah  - Quesiton - How does dependency check assemble the pkg information - specifically, I'm wondering where to it might be finding the trailing characters - cpe:2.3:a:grpc:grpc:1.0.62.**_cl220320220302.1100_**:*:*:*:*:*:*:*

Thanks.

**Comment by rseeton** [comment]
@aikebah  - Ah, found it:
META-INF/maven/dev/com.ibm.ws.webcontainer/pom.xml

which contains the reference:

 <version>1.1.62.cl220320220302-1100</version>
 
 This version tag, combined with the /maven/**dev**/ path suggests that our copy is not the official release.  
 
 I will close this ticket (and [5344](https://github.com/jeremylong/DependencyCheck/issues/5344) ) as these are our problem, not yours. 
 
 Thanks!
 Richard Seeton

**Comment by rseeton** [comment]
@aikebah   - I've done some more digging and am reopening.  

The 'pom.xml' file included in the official OpenLiberty releases ( https://openliberty.io/start/ ) copy of the io.openliberty.grpc.1.0.internal_1.0.62.jar has the following version tag:

<version>1.0.62.cl220320220302-1100</version>

This matches the pom.xml file included in the io.openliberty.grpc.1.0.internal_1.0.62.jar pulled from Maven Central using **_implementation("io.openliberty.api:io.openliberty.grpc.1.0:1.0.62")_**.  

Unfortunately, the pom.xml version  and the Maven pkg reference mismatch prevents the Central Analyzer from matching the file with the correct CPE, resulting in a False Positive. 

Ideally, IBM would package the Open Liberty version cleanly in the pom file, or Maven would use the pom file's version. However, for now, Dependency Check is throwing false positives for IBM Open Liberty.

I'm not sure how the Dependency Check wants to deal with this issue.

**Comment by aikebah** [comment]
With the centralAnalyzer enabled I would expect the CLI to link the two (centralAnalyzer looks up the maven artifact using the SHA1 of the jar)

**Comment by aikebah** [comment]
Unless IBM is packaging a different 1.0.62 jar than published on Maven Central

**Comment by rseeton** [comment]
And I can confirm that the files in the IBM package from https://openliberty.io/start/ package don't match what is on Maven Central.  

Okay - I'll follow-up with IBM to see if I can sort out what their thoughts are. 

Thanks for your patience.
