### ISSUE TITLE
sizeof-agent.jar not reported in HTML output using CLI v1.4.2

### ISSUE THREAD

**Issue by demasb** [dependency-check/DependencyCheck#536]
The sizeof-agent.jar is not being included in the HTML output when using v1.4.2 of the CLI. It was previously included in v1.4.0 and earlier. The sizeof-agent.jar is a transitive library to ehache and is currently not vulnerable.

The attached TestApp.war (named TestApp.war.txt so that it could be uploaded) file contains two libraries: ehcache-core-2.6.12-20160203.011908-43 and commons-collections-3.2.1.2. This file can be used as a test sample to demonstrate the issue. Also attached are log files generated by v1.4.2 and v1.4.0.

[test_1-4-0.txt](https://github.com/jeremylong/DependencyCheck/files/399940/test_1-4-0.txt)
[test_1-4-2.txt](https://github.com/jeremylong/DependencyCheck/files/399941/test_1-4-2.txt)
[TestApp.war.txt](https://github.com/jeremylong/DependencyCheck/files/399943/TestApp.war.txt)

**Comment by jeremylong** [comment]
Sorry for the delay on this. A reset() was missed when we added the ability to scan fully executable JAR files (from spring-boot). This has been resolved in the snapshot version and will be included in the next release.
