### ISSUE TITLE
[FP]: False positive for spatial4j against smiley

### ISSUE THREAD

**Issue by jubui** [dependency-check/DependencyCheck#5372]
### Package URl

`pkg:maven/org.locationtech.spatial4j/spatial4j@0.7`

### CPE

`cpe:2.3:a:smiley_project:smiley:0.7:*:*:*:*:*:*:*`

### ODC Integration

None

### ODC Version

7.4.4

### Description

Likely reported due to dev named Smiley, in the pom.xml file

![image](https://user-images.githubusercontent.com/55841907/214097009-34dfbc71-da6a-4eda-91df-5fcc167d39ff.png)

**Comment by aikebah** [comment]
approved
