### ISSUE TITLE
[FP]: Apache Commons Net is mistakenly flagged

### ISSUE THREAD

**Issue by hpoettker** [dependency-check/DependencyCheck#5374]
### Package URl

pkg:maven/commons-net/commons-net@3.9.0

### CPE

`cpe:2.3:a:ftp_project:ftp:3.9.0:*:*:*:*:*:*:*`

### ODC Integration

{"label"=>"Gradle Plugin"}

### ODC Version

7.4.4

**Comment by aikebah** [comment]
Use an up-to-date version and you'll see it disappear
