### ISSUE TITLE
False positive with artifact using "Nagios" word

### ISSUE THREAD

**Issue by righettod** [dependency-check/DependencyCheck#538]
Hello,

I meet a false positive when I run DependencyCheck Command CLI (last version) against the attached jar file (renamed as ZIP for the upload).

[NagiosTBOX-2-SNAPSHOT-JAR.zip](https://github.com/jeremylong/DependencyCheck/files/411058/NagiosTBOX-2-SNAPSHOT-JAR.zip)

The tool find CVE for Nagios but the artifact do not use any dependency from Nagios (and not dependency at all). In fact the tool spot Nagios issues because the word "**Nagios**" is used into:
-  ArtifactId
- GroupId
- Artifact name

Is it normal ?

Thanks in advance.

**Comment by jeremylong** [comment]
Yes, this is normal. We have tried to tune the engine as best we can and we continue to try to improve the tool - but false positives like this do show up. In general, it is a fairly simple onboarding process for an application team to run ODC, look at the report, and create a suppression file for the application. In most cases this would take less then 10 minutes as the false positives are normally obvious to a human.

I would highly suggesting reading about [how the tool works](http://jeremylong.github.io/DependencyCheck/general/internals.html), [reading the report](http://jeremylong.github.io/DependencyCheck/general/thereport.html), and [suppressing false positives](http://jeremylong.github.io/DependencyCheck/general/suppression.html). While the HTML report does contain buttons to assist in generating the suppression file, the suppression file is based on SHA1 hashes - if you read the article on suppressing false positives there are other ways to suppress false positives (generally suppressing by GAV, without the version number, works best:

``` xml
    <suppress base="true">
        <notes><![CDATA[
        Suppress drop wizard false positive for Jetty.
        ]]></notes>
        <gav regex="true">io\.dropwizard:dropwizard-jetty:.*</gav>
        <cpe>cpe:/a:jetty:jetty</cpe>
    </suppress>
```

**Comment by righettod** [comment]
Thanks you very much for your answer.
