### ISSUE TITLE
Dependency-check is failing on CircleCi for multiple projects - started today

### ISSUE THREAD

**Issue by ifarberov-tw** [dependency-check/DependencyCheck#5383]
Dependency-check is executed for several of my projects on CircleCi using following command:
docker run -v /src:/src:z   owasp/dependency-check  --scan /src --format "ALL" --project na-leaveplanner --out /report

It has been failing for all projects with different errors during each attempt, some referring to connectivity issues, while others to DB-related errors.

See two sample logs attached.

Please assist in getting this issue resolved.
[dc1.log](https://github.com/jeremylong/DependencyCheck/files/10502710/dc1.log)
[dc2.log](https://github.com/jeremylong/DependencyCheck/files/10502711/dc2.log)

**Comment by aikebah** [comment]
That's something to address with your CircleCI maintainers as they are clearly networking-issues.

**Comment by jeremylong** [comment]
It's also possible the NVD was down temporarily.
