### ISSUE TITLE
Exclude specific files from ArchiveAnalyzer

### ISSUE THREAD

**Issue by urld** [dependency-check/DependencyCheck#5410]
**Is your feature request related to a problem? Please describe.**
Since ArchiveAnalyzer now reports unreadable zips correctly thanks to #5371, i get the following exception: `AnalysisException: java.util.zip.ZipException: encrypted ZIP entry not supported`

**Describe the solution you'd like**
I think that this is a perfectly fine default behavior, but I'd like to exclude known unreadable zip files (i.e. password protected entries).
There is already the `<excludes>` configuration option in the maven plugin, but as i understand it, this does not work on file level, but only on the maven module level.

**Describe alternatives you've considered**
As i workaround i completely disabled the ArchiveAnalyzer, which is ok in the short term.

**Comment by jeremylong** [comment]
I believe you can accomplish this with using the `<scanSet>` configuration. See the documentation: https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html

The default scanned directories are listed in the above documentation - be sure to include these if you configure the `scanSet`. The Maven `fileSet` does allow for excludes.

```xml
<scanSet>
    <fileSet>
        <directory>src/test</directory>
    </fileSet>
    <fileSet>
        <directory>src/main</directory>
    </fileSet>
</scanSet>
```

**Comment by urld** [comment]
Thanks, this worked for me:
```xml
<scanSet>
    <fileSet>
        <directory>src/main/resources</directory>
        <excludes>
            <exclude>**/path/to/encrypted.zip</exclude>
        </excludes>
    </fileSet>
    <fileSet>
        <directory>src/main/webapp</directory>
    </fileSet>
    
    ...
    
</scanSet>
```

Totally missed the scanSet option.
