### ISSUE TITLE
Dependency-check for maven giving timeout to maven-central.

### ISSUE THREAD

**Issue by sspizzirri** [dependency-check/DependencyCheck#5412]
Hi! 
We're experiencing some issues with dependency-check specifically when we analyze Maven projects, the thing is that we receive timeouts from Maven-central when the dependency-check analysis starts.
```
[WARN] An error occurred while analyzing '/tmp/dctempb8d2c904-06d3-4ce5-bf76-8ef17532c3b8/check17011560875707404417tmp/1/BOOT-INF/lib/spring-web-5.3.15.jar' (Central Analyzer).
[ERROR] Could not connect to Central search. Analysis failed.
```
In the meantime, we're using as a temporary solution the flag `--disableCentral`, but we need to know what main problem really is.
We tried adding a `--log `flag to save a file of the verbose logs, but the pipeline fails and timeouts before we can actually see the job artifact, therefore the dependency-check verbose logs.
![Captura de pantalla 2023-02-02 a la(s) 09 05 01](https://user-images.githubusercontent.com/48492915/216319951-2feaa46e-e015-4f63-96d9-e751770376d9.png)
Is there a way we can see what is really happening and why is it failing to connect to maven-central?
Thanks a lot!
Pd: Yes, we have a proxy and it's configured like so:
`--proxyserver **--proxyport ** --nonProxyHosts *.**
Pd 2: We're using dep-check version 7.2.1

**Comment by jeremylong** [comment]
When scanning Maven projects I would highly recommend using the Maven Plugin:

```
mvn org.owasp:dependency-check-maven:8.0.2:aggregate
```

The Maven plugin does not utilize the Central Analyzer.
