### ISSUE TITLE
Pip analyzer searches multiple packages on Pascalcase package names

### ISSUE THREAD

**Issue by cjschaef** [dependency-check/DependencyCheck#5413]
**Describe the bug**
When using the [Pip analyzer](https://jeremylong.github.io/DependencyCheck/analyzers/pip.html) to process `requirements.txt` files, the `DependencyCheck` tool will perform searches for multiple packages/components if the Python package name is PascalCase (likely also including camelCase). This will result in incorrect CVE's being flagged for a package, due to multiple search attempts being made.

**Version of dependency-check used**
$ dependency-check/bin/dependency-check.sh --version
Dependency-Check Core version 8.0.2

**Log file**
`requirements.txt` file
```
$ cat /home/cjschaef/dependencycheck-pascalcase/requirements.txt 
GitPython==3.1.30
```

I could provide the entire logs, but the key logs are here, where it shows that multiple searches are being conducted for the one package
```
DEBUG - Begin Analysis of '/home/cjschaef/dependencycheck-pascalcase/requirements.txt' (False Positive Analyzer)
2023-02-02 12:25:22,775 org.owasp.dependencycheck.Engine:673
INFO  - Finished False Positive Analyzer (0 seconds)
2023-02-02 12:25:22,775 org.owasp.dependencycheck.Engine:823
DEBUG - Initializing NVD CVE Analyzer
2023-02-02 12:25:22,775 org.owasp.dependencycheck.Engine:758
DEBUG - Starting NVD CVE Analyzer
2023-02-02 12:25:22,775 org.owasp.dependencycheck.Engine:806
DEBUG - Parallel processing with up to 8 threads: NVD CVE Analyzer.
2023-02-02 12:25:22,775 org.owasp.dependencycheck.AnalysisTask:86
DEBUG - Begin Analysis of '/home/cjschaef/dependencycheck-pascalcase/requirements.txt' (NVD CVE Analyzer)
2023-02-02 12:25:22,777 org.owasp.dependencycheck.data.nvdcve.CveDB:622
DEBUG - Cache miss for cpe:2.3:a:git:git:3.1.30:*:*:*:*:*:*:*
2023-02-02 12:25:22,808 org.owasp.dependencycheck.data.nvdcve.CveDB:622
DEBUG - Cache miss for cpe:2.3:a:gitpython_project:gitpython:3.1.30:*:*:*:*:*:*:*
2023-02-02 12:25:22,809 org.owasp.dependencycheck.data.nvdcve.CveDB:622
DEBUG - Cache miss for cpe:2.3:a:python:python:3.1.30:*:*:*:*:*:*:*
2023-02-02 12:25:22,884 org.owasp.dependencycheck.data.nvdcve.CveDB:622
DEBUG - Cache miss for cpe:2.3:a:python_software_foundation:python:3.1.30:*:*:*:*:*:*:*
2023-02-02 12:25:22,891 org.owasp.dependencycheck.Engine:673
INFO  - Finished NVD CVE Analyzer (0 seconds)
```

**To Reproduce**
1. Create a `requirements.txt` file simply with `GitPython==3.1.30`
2. Run the `DependencyCheck` tool, in my case bash script using experimental analyzers to include Pip (`./dependency-check.sh --enableExperimental ...`)
3. Review the flagged CVE's for the PascalCase package, showing CVE's for incorrect packages (in this case `Python==3.1.30`)

**Expected behavior**
The tool should either only perform a search for the Python package name (`gitpython`), and not also `git` and `python`. Or, the documentation should be updated to inform users that they should format their `requirements.txt` to be all lower case, since I believe Pip doesn't care about case in `requirements.txt` (although there may be some nuances I'm not familiar with).

**Additional context**
This is likely a big issue for Python Packages that contain the `Python` name (case sensitive) reported from Pip, and `pip freeze`, as very old versions of Python have numerous CVE's (like in this case `Python==3.1.x`).

**Comment by jeremylong** [comment]
@aikebah thoughts on this? I think this could reduce FP on a few of the supported ecosystems where we are only able to get a limited amount of evidence from the package files.

**Comment by aikebah** [comment]
@jeremylong For the specific FPs referenced here (git and python) I think we could safely create broad suppression of the product terms as both git and python are native executables (as long as we don't have support for native libraries other than dotNet libraries I think we could even mark plain 'git' and 'python' as fully ignorable terms in the evidences).

Regarding an overall strategy of using only the package as a whole I'm not sure whether that would be safe as I think there are several frameworks that have all kinds of library-names with the framework name embedded in it, so they might trigger false negatives on components of the single framework if we don't to split on words.

**Comment by jeremylong** [comment]
@aikebah after reviewing another FN report I identified an issue with just using lowercase everything. As the NVD does often - they will add "framework" or "project" into the CPE. If everything is all lowercase the [ADDITIONAL_STOP_WORDS](https://github.com/jeremylong/DependencyCheck/blob/283492441fe1cde22464e118e4c9ac13b9f25a46/core/src/main/java/org/owasp/dependencycheck/data/lucene/SearchFieldAnalyzer.java#L41) are not processed as `yiisoftware` is a single term to Lucene. See https://github.com/jeremylong/DependencyCheck/pull/5434.

**Comment by jeremylong** [comment]
@aikebah while this could cause more FP - any opinion on adding something like a `LowerCaseStopWordTokenizingFilter` (https://github.com/jeremylong/DependencyCheck/tree/main/core/src/main/java/org/owasp/dependencycheck/data/lucene). That would specifically look for `framework`, `package`, etc. contained in a token and if found add the token minus the stop word back into the search....  I may open a new ticket to add this.

**Comment by jeremylong** [comment]
@aikebah moving this to https://github.com/jeremylong/DependencyCheck/issues/5443
