### ISSUE TITLE
Fasle positive on tomact-api

### ISSUE THREAD

**Issue by parimala-kathir** [dependency-check/DependencyCheck#5417]
ODC7.4.1
tomcat-api-8.5.40.jar | cpe:2.3:a:apache:tomcat:8.5.40:*:*:*:*:*:*:*cpe:2.3:a:apache_tomcat:apache_tomcat:8.5.40:*:*:*:*:*:*:* | pkg:maven/org.apache.tomcat/tomcat-api@8.5.40 | CRITICAL | 23 | Highest | 25
-- | -- | -- | -- | -- | -- | --

maven
https://mvnrepository.com/artifact/org.apache.tomcat/tomcat-api/8.5.40

The jar has no vulnerabilities as per maven

**Comment by mprins** [comment]
> ODC7.4.1

Please use a supported version: https://github.com/jeremylong/DependencyCheck/security/policy

**Comment by parimala-kathir** [comment]
ODC 8.0.2



tomcat-api-8.5.40.jar | cpe:2.3:a:apache:tomcat:8.5.40:*:*:*:*:*:*:*cpe:2.3:a:apache_tomcat:apache_tomcat:8.5.40:*:*:*:*:*:*:* | pkg:maven/org.apache.tomcat/tomcat-api@8.5.40 | CRITICAL* | 23 | Highest | 25
-- | -- | -- | -- | -- | -- | --

same result

**Comment by aikebah** [comment]
tomcat-api jar file is released together with the rest of tomcat as a whole.
DependencyCheck does in general not distinguish individual libraries of such a framework project. Doing that would need OWASP DependencyCheck to maintain a database of which CVE pertains to which part of a framework that is released as a whole. 

So the best advice I can give is to bump the API to latest tomcat 8.x in your project, or create your own suppression.
