### ISSUE TITLE
Broken link in HTML report

### ISSUE THREAD

**Issue by mehradn7** [dependency-check/DependencyCheck#5418]
Hello,

The Maven package spring-retry appears in the Dependency Check report with the version number not being substituted:

<img width="1180" alt="image" src="https://user-images.githubusercontent.com/35630862/216664870-f1cdf22a-e774-44c1-b584-41159778f500.png">

Which causes the hyperlink to be broken:  [pkg:maven/org.springframework.retry/spring-retry@%24%7Brevision%7D](https://ossindex.sonatype.org/component/pkg:maven/org.springframework.retry/spring-retry@%24%7Brevision%7D?utm_source=dependency-check&utm_medium=integration&utm_content=8.0.2)

The original POM file can be found here: https://repo1.maven.org/maven2/org/springframework/retry/spring-retry/1.3.4/spring-retry-1.3.4.pom

Thank you and have a nice day.

Regards,

**Version of dependency-check used**
Maven plugin 8.0.2

**Comment by jeremylong** [comment]
Amazingly even the referenced POM says that the version is `${revision}` which URL encodes to `%24%7Brevision%7D`... Not much we can do when people publish garbage.

**Comment by marcelstoer** [comment]
Oh bummer, looks like they use [CI friendly versions](https://maven.apache.org/maven-ci-friendly.html) but misconfigured the flatten plugin.
