### ISSUE TITLE
Suppressing Vulnerabilities from NPM

### ISSUE THREAD

**Issue by cdwijayarathna** [dependency-check/DependencyCheck#5419]
Hi all, 
I am attempting to temporally suppress the following vulnerability reported in one of my NPM dependencies. 

```
@angular/core:6.1.10 | NPM1088994 | Medium |  
-- | -- | -- | --
File Path : /Users/jenkins/workspace/_XX/XX/package-lock.json?@angular/core
SHA-1 : 
SHA-256: 
Description: A vulnerability was found in Angular up to 11.0.4/11.1.0-next.2. It has been classified as problematic. Affected is the handling of comments. The manipulation leads to cross site scripting. It is possible to launch the attack remotely but it might require an authentication first. Upgrading to version 11.0.5 and 11.1.0-next.3 is able to address this issue. The name of the patch is ba8da742e3b243e8f43d4c63aa842b44e14f2b09. It is recommended to upgrade the affected component.
```

I am able to suppress this like follows : 

```
<suppress until="2023-06-01Z">
       <notes><![CDATA[
       we're working on replacing it
       ]]></notes>
       <sha1>84a6ddd152234ccebf42cddaa03390f09c784da7</sha1>
       <vulnerabilityName>1088994</vulnerabilityName>
    </suppress>
```

However, I have noticed that this vulnerabilityName (1088994) is updated whenever we recreate the DB with dependency check version updates, and the suppression is no longer working. Is there a better way for handling this?

**Comment by aikebah** [comment]
Labeling as bug/enhancement as apparently with the move of the NPM Audit API backed by GHSA database the NPM Audit `id` is no longer a stable reference. It seems most appropriate to switch to the `github_advisory_id` for the unique identifier used as vulnerability-name.

**Comment by aikebah** [comment]
@jeremylong WDYT... shall I work on a PR to switch to the GHSA advisory as the vulnerability-name for NPM audit findings?
