### ISSUE TITLE
Dependency Check as Java Library

### ISSUE THREAD

**Issue by chovyy** [dependency-check/DependencyCheck#5420]
Since Dependency Check is build in Java, it would be cool to also have a plain Java API besides the CLI interface and the several tool plugins.

Would it be a big effort to provide a library that can be used to build other Java applications above Dependency Check?

Something like...

```Java
DependencyCheck dc = new DependencyCheck(dcConfiguration);
dc.scan(pathToJars, outPath);
```

**Comment by mprins** [comment]
use https://github.com/jeremylong/DependencyCheck/tree/main/core

**Comment by jeremylong** [comment]
as Mark pointed out - the core library can be used. Examples on how to use it can be found in the CLI, Maven, and Ant modules. There is also [DependencyCheckScanAgent.java](https://github.com/jeremylong/DependencyCheck/blob/main/core/src/main/java/org/owasp/dependencycheck/agent/DependencyCheckScanAgent.java) - but this hasn't been kept up to date like the other standard interfaces. In reality - just using the core engine isn't that hard.

**Comment by chovyy** [comment]
Alright, thanks. I will try it that way. It's not actually the same as a Maven managed library, but it will work too, I guess.

**Comment by mprins** [comment]
> It's not actually the same as a Maven managed library

Oh, but it is actually a Maven managed library:
https://github.com/jeremylong/DependencyCheck/blob/45080ab3ee309d9ed6945cc37bdd53594d3c6ac3/core/pom.xml#L20-L27

https://search.maven.org/artifact/org.owasp/dependency-check-core

**Comment by chovyy** [comment]
Oh, ok, I should have noticed the pom.xml, but I was just: Ok, cool, he pointed me to a subtree of the source code, that's nice, but not exactly what I was looking for. But actually, it was. I'm so sorry. Thank you very much.
