### ISSUE TITLE
[FP]: Version mismatch in Talend's log4j

### ISSUE THREAD

**Issue by mehradn7** [dependency-check/DependencyCheck#5426]
### Package URl

pkg:maven/org.talend.libraries/log4j-1.2.16@6.0.0

### CPE

cpe:2.3:a:apache:log4j:6.0.0:*:*:*:*:*:*:*

### ODC Integration

{"label"=>"CLI"}

### ODC Version

8.0.2

### Description

Hello,

Talend has released its own flavour of Log4J, hosted in their own repo https://talend-update.talend.com/nexus/content/repositories/libraries/org/talend/libraries/log4j-1.2.16/6.0.0/ (this repo is referenced in mvnrepository.com), but with a different versioning model (see -6.0.0 suffix in package version), which causes a wrong CPE to be associated to it (6.0.0 vs 1.2.16):

cpe:2.3:a:apache:log4j:6.0.0:*:*:*:*:*:*:*

<img width="596" alt="image" src="https://user-images.githubusercontent.com/35630862/217008283-29f6412a-5f8c-4cb3-9b95-413e8125bfea.png">

This is also problematic when the "genuine" Log4J (from Apache) (pkg:maven/log4j/log4j@1.2.16) is also a dependency of the same project, because both JARs then become Related Dependencies and none of the "true" Log4J CVEs are detected on Apache's Log4J:

<img width="657" alt="image" src="https://user-images.githubusercontent.com/35630862/217009885-4c861562-d2cd-4263-9ed6-e1c14cede50a.png">

Is it possible to simply add a suppression on Talend's Log4J ? This seems the easiest solution, moreover there is no NVD CPE entry for Talend's Log4J and I guess one can assume that there is no proven link between Talend's Log4J and Apache's one, each of them following their own lifecycle.

Thanks in advance and have a nice day.

Regards,

**Comment by aikebah** [comment]
We don't intend to mitigate this, it's considered a proprietary library and the CPE is properly matched at the best possible location as Talend has versioned the library as version 6.0.0

**Comment by mehradn7** [comment]
Hi @aikebah, thanks for your answer.
I am not sure though how it differs from usual FP suppressions such as snakeyaml's one (https://github.com/jeremylong/DependencyCheck/issues/5233)? 

IMHO it is a simple vendor mismatch, Talend's log4j is assigned to Apache's log4j which is a different product, so couldn't we just add this as a "regular" suppression like below?

``` xml

<suppress base="true">
   <packageUrl regex="true">^pkg:maven/org\.talend\.libraries/log4j-.*$</packageUrl>
   <cpe>cpe:/a:apache:log4j</cpe>
</suppress>
```

Thanks again.

Regards,

**Comment by aikebah** [comment]
Talends package appears to simply be a re-distribution of apache's log4j

```xml
  <name>Talend Third party library : log4j-1.2.16.jar</name>
  <description>Logging API provided by Apache Software Foundation</description>
  <url>http://logging.apache.org/log4j</url>
```
