### ISSUE TITLE
Database defrag runs even if no updates

### ISSUE THREAD

**Issue by karstenspang** [dependency-check/DependencyCheck#5440]
**Describe the bug**
The database defrag is done, even if the database was not updated. This makes the build take about 4 seconds longer for each module. In my project, dependency-check is run four times; check of three modules, and an aggregate report.

**Version of dependency-check used**
The problem occurs using version 8.0.2 of the maven plugin

**Log file**
[log from the aggregate report](https://gist.github.com/karstenspang/0ea2127b3529599b67040e8c2f3940f6)

**To Reproduce**
Run the build twice, shortly after each other.

**Expected behavior**
The database defrag is run only after updates to the database, like it was in earlier version, e.g. 7.4.4.

**Comment by jeremylong** [comment]
I've been meaning to fix this - thanks for reporting the issue. This will be fixed in 8.1.0 which should be released this weekend.
