### ISSUE TITLE
Slow start ~15 minutes of CLI

### ISSUE THREAD

**Issue by DmitriyMaksimov** [dependency-check/DependencyCheck#5445]
**Describe the bug**
When running on CI, using CLI it takes a long time (about 15 minutes on standard run, 24 minutes when logging enabled).
Update and checks relatively fast (15 minutes on normal run), but initial start is very slow.
CLI output:
```
[2023-02-13T01:51:44.014Z] C:\workspace\integration-service-sonarqube>C:/dependency-check-8.0.2/bin/dependency-check.bat --project "Integration service" --exclude "**/UnitTests.*.dll" --exclude "**/obj/**/*" --exclude "**/*.pdb"  --exclude "**/*.cs" --exclude "**/*.png" --exclude "**/*.gif" --scan "src/**/*" -l dependency-check.log
[2023-02-13T02:14:17.310Z] [INFO] Checking for updates
... skipped
[2023-02-13T02:19:03.235Z] [INFO] Check for updates complete (302232 ms)
... skipped
[2023-02-13T02:43:14.037Z] [INFO] Analysis Complete (1442 seconds)
[2023-02-13T02:43:14.037Z] [INFO] Writing report to: C:\workspace\dependency-check-report.html
```

There is a ~22 minutes pause in log file as well:
```
2023-02-13 01:51:48,686 org.owasp.dependencycheck.utils.Settings:1176
DEBUG - Settings.getDataFile() - file: 'C:\dependency-check-8.0.2\data'
2023-02-13 02:13:55,655 org.owasp.dependencycheck.utils.Settings:1176
```

**Version of dependency-check used**
The problem occurs using version 8.0.1 of the cli.

**Log file**
[Log file](https://gist.github.com/DmitriyMaksimov/7071ca379ab9228e5df2ee9ddb5e64a6)

**To Reproduce**
Can't provide steps to reproduce - it's running on private Jenkins CI.

**Expected behavior**
Expected to see no "pause" between start of cli and start of processing/upgrades.

**Additional context**
Checking .Net dependencies.

**Comment by mprins** [comment]
Is your cache persistent? because snipping the log makes you hide information from us to analyse your problem if not the whole database will need to be downloaded and created each ci run...

also it's odd that the log says
`DEBUG - Settings.getDataFile() - file: 'C:\dependency-check-8.0.2\data'` but you say you are using 8.0.1

**Comment by DmitriyMaksimov** [comment]
Sorry, yes, we are using `8.0.2`.
We do not persist cache - each build uses a new build agent.
Each run the cli download and upgrade DB, but **before** that it wait/pause ~15 minutes.

**Comment by aikebah** [comment]
It's likely running into multiple retries downloading the NIST NVD datastreams as, because you don't persist the database, you are likely hitting the rate-limiter on NIST NVD for 'excessive download frequency'.
The pauses in-between downloads increase with every retry.

**Comment by aikebah** [comment]
It is strongly recommended to provision some persistent storage in your build infrastructure that you mount in your builds if you care for bandwidth usage and build-speed. You're wasting resources by constantly rebuilding the database from scratch.

**Comment by aikebah** [comment]
After looking at the log.... my suspicion is that you run into memory constraints with heavy garbage collection in between 01:51 and 02:13 due to the size of your project (17k files).

**Comment by aikebah** [comment]
In that 20 minute period it is  checking each found file against the analyzers to validate if at least one analyzer will accept it (filtering out found files that no analyzer is capable of handling)

**Comment by aikebah** [comment]
My gut feel is that your exclusion patterns do not filter what you think they will.... fixing those up might improve the build as well..

I see logs like

`2023-02-13 01:51:48,295 org.owasp.dependencycheck.App:390
DEBUG - Found file C:\workspace\integration-service-sonarqube\src\UnitTests.Adaptive.Tenants.ServiceContracts\bin\Release\net6.0\testhost.dll`

Which I expect you assume to filter out by `--exclude "**/UnitTests.*.dll"`, but that's not how Ant-style filename patterns work. It would save approximately 8k (almost half) of the hits from the shared log.

**Comment by DmitriyMaksimov** [comment]
Thank you very much for your response!
I fixed the exclusion filter and add more exclusions - now the initial "pause" reduced to ~2 minutes.
