### ISSUE TITLE
Github Workflow - FP Issue evaluation fails on missing pkg and cannot be re-run

### ISSUE THREAD

**Issue by rseeton** [dependency-check/DependencyCheck#5451]
**Describe the bug**
Dependency check will detect vulnerabilities without a 'pkg' value.  
When reporting FP issues and no pkg is provided the issues workflow (evaluate false positives) will fail due to the missing pkg information.  Subsequently adding the pkg information to the FP issue description will trigger a rerun of the evaluate false positives workflow... unfortunately this rerun will fail (not sure where the parsing fails)

**Version of dependency-check used**
Attempting to report false positives from any package (specificially 8.0.2 & 8.1.0) under the github.com issues tab.  The failure appears to lie in the issues workflow.

**Log file**
See https://github.com/jeremylong/DependencyCheck/issues/5449 

**To Reproduce**
1. Create FP Issue with empty/missing/invalid Package details 
2. The evaluate false positive workfow process will fail and attach 'pending more information' label
3. Edit the problem description and assign a valid Package string
4. The evaluate false positive workfow process continues to fail

The same details (with the updated package detail) can be assigned to clean/new FP Issue and this will cleanly trigger the evaluate false positive workflow

**Expected behavior**
Ideally, if we fix the problem description, the evaluation process would be able to run to completion.

**Additional context**

**Comment by jeremylong** [comment]
I've seen this as well... but I haven't been able to figure out how to fix this...

**Comment by rseeton** [comment]
@jeremylong  - I'll take a crack at this and let you know what I find.
