### ISSUE TITLE
[FP]: cron-utils identified as fredsmith utils

### ISSUE THREAD

**Issue by karstenspang** [dependency-check/DependencyCheck#5458]
### Package URl

pkg:maven/com.cronutils/cron-utils@9.2.0

### CPE

`cpe:2.3:a:utils_project:utils:9.2.0:*:*:*:*:*:*:*`

### ODC Integration

{"label"=>"Maven Plugin"}

### ODC Version

8.0.2

**Comment by mprins** [comment]
this should be fixed with https://github.com/jeremylong/DependencyCheck/commit/04438ecf5e732c2bdb0c4747b9d7bb81a5a77804 

You might like to try with the current release: https://github.com/jeremylong/DependencyCheck/releases/tag/v8.1.0

**Comment by karstenspang** [comment]
I confirm that this has been fixed in 8.1.0
