### ISSUE TITLE
[FP]: Oracle JDBC driver internationalization support identified as Oracle database

### ISSUE THREAD

**Issue by karstenspang** [dependency-check/DependencyCheck#5459]
### Package URl

pkg:maven/com.oracle.database.nls/orai18n@19.18.0.0

### CPE

`cpe:2.3:a:oracle:database:19.18.0.0:*:*:*:*:*:*:*`

### ODC Integration

{"label"=>"Maven Plugin"}

### ODC Version

8.0.2

**Comment by aikebah** [comment]
approved
