### ISSUE TITLE
External database update taking hours/days to complete

### ISSUE THREAD

**Issue by ryrizo** [dependency-check/DependencyCheck#546]
### Issue

Using a Jenkins job to update my external database in AWS RDS. First successful run took 3.5 days. Update a few hours later took 45 minutes. I expected the first run to take longer, but both times seem pretty slow. Any help would be much appreciated!
### Database and Connector
- MySQL 5.7.11 Engine hosted on AWS RDS
- MySQL Java connector 5.1.39
### Console Output and Logs

First update took 3.5 days (missed the log file on this run):
- [Console output](https://gist.github.com/ryrizo/9150637ff99f8c692d26417b4f8b5945)

Update a few hours later took 45 minutes:
- [Most recent log file](https://gist.github.com/ryrizo/8d26d8c6e670c23d535830fc3a9250d2)

**Comment by jeremylong** [comment]
Unfortunately, I've seen this as well with MySQL. I am still not sure which of the SQL statement(s) is causing the performance issue. In the future I may look into converting some of the SQL statements to stored procs for MySQL.

**Comment by ryrizo** [comment]
Thanks for the response @jeremylong. It appeared the connection would change to a sleep status for a period of time for each statement executed. The updates are finishing in a couple hours, which is fast enough to support daily updates.

**Comment by jeremylong** [comment]
1.4.3 was released this morning (announcement will be sent out shortly via mailing list and twitter). I would highly recommend upgrading and while you do so - recreate the MySQL database. This is for other reasons then the slow updates - however, I did make a change to remove batch mode when using MySQL.   While I'm still doing more research on this - can you tell me if after upgrading to 1.4.3 the updates are still slow?

**Comment by ryrizo** [comment]
Looks much better!
- Post upgrade to 1.4.3 - updates now in the 10-15 minute range. 
- Most recent 1.4.2 update took 2.5 hours. 

After recreating the database - a full database update took 5 days.

**Comment by jeremylong** [comment]
thanks for confirming that this is fixed
