### ISSUE TITLE
[FP]: Oracle JDBC driver internationalization support identified as Oracle database

### ISSUE THREAD

**Issue by karstenspang** [dependency-check/DependencyCheck#5460]
### Package URl

pkg:maven/com.oracle.database.nls/orai18n@19.18.0.0

### CPE

`cpe:2.3:a:oracle:oracle_database:19.18.0.0:*:*:*:*:*:*:*`

### ODC Integration

{"label"=>"Maven Plugin"}

### ODC Version

8.0.2

**Comment by mprins** [comment]
duplicates #5459

**Comment by karstenspang** [comment]
No, it is not a duplicate. The cpe is different.

**Comment by aikebah** [comment]
approved
