### ISSUE TITLE
[FP]: zstd-jni identified as FreeBSD

### ISSUE THREAD

**Issue by karstenspang** [dependency-check/DependencyCheck#5461]
### Package URl

pkg:maven/com.github.luben/zstd-jni@1.5.2-1

### CPE

`cpe:2.3:a:freebsd:freebsd:1.5.2.1:*:*:*:*:*:*:*`

### ODC Integration

{"label"=>"Maven Plugin"}

### ODC Version

8.0.2

**Comment by aikebah** [comment]
approved
