### ISSUE TITLE
OWASP DC 8.0.2 cli failure on node app due to Python Analyzer finding node module using poetry

### ISSUE THREAD

**Issue by brandon-pangilinan** [dependency-check/DependencyCheck#5464]
**Describe the bug**
OWASP CLI scanner fails when scanning a node app when the python analyzer finds a node module using a pyproject.toml file. 

**Version of dependency-check used**
The problem occurs using version 8.0.2 of the CLI.

**Log file**
[OWASP DC 8.0.2 Fail](https://gist.github.com/brandon-pangilinan/00799f32d8fe1809998126653b15be20)

**To Reproduce**
1. Run OWASP CLI on node based app with node_gyp as a module
2. See error

**Expected behavior**
Pipeline shows that OWASP scan failed with exit code 14, and that a pyproject.toml was found, but no requirements.txt or poetry.lock file. 

**Additional context**

**Comment by mprins** [comment]
does it fail with the current release? which is 8.1.0

please see https://github.com/jeremylong/DependencyCheck/issues/4995 and https://github.com/jeremylong/DependencyCheck/pull/5409

**Comment by jeremylong** [comment]
Thanks for the report - I agree we should not throw the error if the `pyproject.toml` is in the `node_modules` directory.

Additionally, as you are scanning a node application I would highly recommend adding `--retirejsFilterNonVulnerable` to reduce the overall size of the report and scan time.
