### ISSUE TITLE
Does dependency-check support scanning .Net's .deps.json files?

### ISSUE THREAD

**Issue by daxin09pp** [dependency-check/DependencyCheck#5468]
Does dependency-check support scanning .Net's .deps.json files? If not, can dependency-check support it in the future? Thanks!

Introduction for .deps.json file:
https://github.com/dotnet/cli/blob/v2.0.0/Documentation/specs/runtime-configuration-file.md

**Comment by jeremylong** [comment]
No - not at the moment. ODC scans the DLL assemblies themselves and the project files (although we have an enhancement request still open around `Dependency.packages.props` files [#1948](https://github.com/jeremylong/DependencyCheck/issues/1948).
