### ISSUE TITLE
Transitive Maven dependencies overriden but still detected by DependencyCheck

### ISSUE THREAD

**Issue by mehradn7** [dependency-check/DependencyCheck#5472]
Hello,

I have a Maven project which transitively depends on jackson-databind 2.12.4. Some of my dependencies use jackson-databind themselves, but with a lower version (e.g. 2.11.4), so Maven picks the more relevant one (2.12.4) and only adds this one to the project classpath. Typically, a verbose Maven dependency tree displays the following:

`[INFO]    |  |  +- (com.fasterxml.jackson.core:jackson-databind:jar:2.12.4:compile - version managed from 2.11.4)
`

However, jackson-databind 2.11.4 still appears in the DependencyCheck (Maven plugin) report because it is embedded in one of my dependencies' JAR:

![image](https://user-images.githubusercontent.com/35630862/219752754-6fe58fc8-ddcd-4f1e-80c7-50ee35967885.png)

so I end up with a report including a version of jackson-databind which is actually not in the classpath (I acknowledge this is the expected behaviour from DependencyCheck).

Is there a way to prevent that ? I guess it should not be easy to implement in any case, but given that the DependencyCheck Maven plugin is integrated within the Maven build process, do you think there is a way for it to be aware of the project classpath and filter out irrelevant dependencies?

Thanks for your suggestions.

Regards,

**Comment by jeremylong** [comment]
Sorry to let you know - in this case the report is correct. You might override the dependency for some uses - but because it is embedded in `my-library-1.0.0.jar` you have jackson version 2.11.4 in your project because it is embedded in my-library-1.0.0.

**Comment by mehradn7** [comment]
Hello,
The report is absolutely correct indeed, this is what I meant when I said
>I acknowledge this is the expected behaviour from DependencyCheck

I would like to know if there is a way to filter out such dependencies that do not end up in the classpath of the project :) (either within DependencyCheck itself, or with any other workaround that you would have in mind).

Thanks !

**Comment by jeremylong** [comment]
No - I can't think of any good way... Maybe a suppression rule?

**Comment by mehradn7** [comment]
I could indeed use a suppression rule to filter out dependencies with file path containing strings such as 'BOOT-INF/lib' (I guess this is what you had in mind), but I was hoping there is a cleaner way to detect the classpath within the DependencyCheck Maven Mojo.
Thanks
