### ISSUE TITLE
[FP]: jaxb-core detected as Java_SE

### ISSUE THREAD

**Issue by mehradn7** [dependency-check/DependencyCheck#5485]
### Package URl

pkg:maven/com.sun.xml.bind/jaxb-core@2.3.0

### CPE

cpe:2.3:a:oracle:java_se:2.3.0:*:*:*:*:*:*:*

### ODC Integration

{"label"=>"CLI"}

### ODC Version

8.1.0

### Description

Hello,

The 2 folllowing Maven packages:
- pkg:maven/com.sun.xml.bind/jaxb-core@2.3.0
- pkg:maven/org.glassfish.jaxb/jaxb-core@2.3.0

are incorrectly associated to CPE `cpe:2.3:a:oracle:java_se:2.3.0:*:*:*:*:*:*:*`

probably because of the following hint evidence:

<img width="1516" alt="image" src="https://user-images.githubusercontent.com/35630862/220328288-8a58ce2a-f7ba-4741-8c5f-cc6299f8c2dc.png">
<img width="1502" alt="image" src="https://user-images.githubusercontent.com/35630862/220328709-89a2dba5-d042-4900-8f7d-daacee2c542d.png">

Thank you.

Regards,

**Comment by aikebah** [comment]
Not due to the hint, which is just making sure that the companies 'Sun' and 'Oracle' are both taken into account for searching CPEs. The JavaSE FP CPE match stems from other evidence obtained from the Manifest.
