### ISSUE TITLE
NVD CVE download fails most of the time

### ISSUE THREAD

**Issue by santiagomarrone** [dependency-check/DependencyCheck#5488]
**Describe the bug**

Many executions fail due to a random connection error at the time of downloading NVD CVE reports.

```
Download Failed for NVD CVE - 2011
Some CVEs may not be reported.
Reason: Download failed, unable to copy 'https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2011.json.gz' to '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/dctemp518ba1ed-0b85-4cb5-9a26-3ba96fc9445f/cve2011_11933256866251921291.json.gz'
Error downloading file https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2011.json.gz ; unable to connect.
If you are behind a proxy you may need to configure dependency-check to use the proxy.
```

**Version of dependency-check used**

I have tried both the Azure DevOps extension and the CLI release running on an Azure DevOps agent. Version is 8.1.0.

**Log file**

[Logs: Azure DevOps extension](https://gist.github.com/santiagomarrone/cade6e3f8aaa26a241eeca3781436b32)
[Logs: CLI](https://gist.github.com/santiagomarrone/f05463fde2be0ed1c08e1b7d9ec692fa)

**To Reproduce**

I'm testing the Azure DevOps extension as follows.

```
- script: |
      brew install gpg2
      curl -sSL https://rvm.io/mpapis.asc | gpg --import -
      curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -        
      curl -sSL https://get.rvm.io | bash -s stable
      source /Users/runner/.rvm/scripts/rvm
      rvm install ruby-2.7.5
      rvm use 2.7.5 --default
      gem install bundler -v 2.1.4
      bundle install
      gem install bundler-audit
      which bundle-audit
      echo '##vso[task.prependpath]/Users/runner/.rvm/gems/ruby-2.7.5/bin'
      bundle-audit update
  displayName: 'Install pre-requisites'

- task: dependency-check-build-task@6
  displayName: 'Check dependencies'
  inputs:
      format: "XML, JSON, JUNIT"
      enableVerbose: true
      additionalArguments: '--disableBundleAudit --disableYarnAudit'
```` 

I'm testing the CLI release as follows.

```
- script: |
      brew install dependency-check
      dependency-check --scan "$(System.DefaultWorkingDirectory)"
```

**Expected behavior**

Dependency check running consistently on an Azure DevOps pipeline.

**Additional context**
- 1/5 executions are successful
- 4/5 executions fail with this error
- The error is not specific to a particular report, as you can see that it failed for 2008 on my latest run with CLI and then failed for 2016 on my latest run with Azure DevOps extension

**Comment by mprins** [comment]
duplicates #5447

**Comment by santiagomarrone** [comment]
Thanks, @mprins. I will follow-up this topic on [Issue #5447](https://github.com/jeremylong/DependencyCheck/issues/5447).
