### ISSUE TITLE
[FP]: CosmosDB detected as SQL Project

### ISSUE THREAD

**Issue by laurentgo** [dependency-check/DependencyCheck#5491]
### Package URl

pkg:maven/com.microsoft.azure/azure-cosmosdb@2.2.0

### CPE

cpe:2.3:a:www-sql_project:www-sql:2.2.0:*:*:*:*:*:*:*

### ODC Integration

{"label"=>"Maven Plugin"}

### ODC Version

8.1.0

**Comment by jeremylong** [comment]
approved
