### ISSUE TITLE
How to download "Database" 

### ISSUE THREAD

**Issue by Mridulau** [dependency-check/DependencyCheck#5494]
Hi Jeremylong,

I have downloaded the latest version of Dependency-check 
version : 8.1.0

Under Assets heading: [dependency-check-8.1.0-release.zip](https://github.com/jeremylong/DependencyCheck/releases/download/v8.1.0/dependency-check-8.1.0-release.zip)

After unzipping I could not see data folder. Now where i need to download it explicitly

Can you please provide the link to download "Data" Folder

Thank you,
Mridula U

**Comment by mprins** [comment]
the directory is created and the data is downloaded when the tool is started, see https://github.com/jeremylong/DependencyCheck#internet-access

vulnerability data is not distributed with the tool

**Comment by Mridulau** [comment]
Hi @mprins ,

Apologize, I didn't not get your answer. 

In the previous version in the download folder itself  I could see "data" folder where it contains "cache" , "nvdcache", "odc.mv.db" folders.

Where as in the latest version of dep-check I am not seeing it. Can you please guide on how to explicitly install the contents of data folder

PFA
FYI - @jeremylong 

<img width="430" alt="Dep-check" src="https://user-images.githubusercontent.com/43175836/221114150-5a044079-22cf-42e8-852e-17090e9abf95.png">

**Comment by jeremylong** [comment]
As Mark already stated - if you download the zip file for 8.1.0 and extract it you will have a folder that looks like this:

![image](https://user-images.githubusercontent.com/862914/221171272-23e7bd4e-fab9-4e27-9e7a-c1c0bd47d50b.png)

When you run `dependency-check.bat` (which is contained in the `bin` directory) it will create the data directory.

**Comment by Mridulau** [comment]
Hi @jeremylong 

As you suggested I ran dependency-check.sh and I saw data folder but the scanning is not successful as it not able to find database
[ERROR] Autoupdate is disabled and the database does not exist

Our linux machine dont have internet connection . Can you let us know how to install the database ?
