### ISSUE TITLE
Setting skipTestGroups to false causes dotnet runtime to be required on a java project

### ISSUE THREAD

**Issue by jtconsol** [dependency-check/DependencyCheck#5495]
**Describe the bug**

When setting the property `skipTestGroups` to `false`, scanning my java project with `gradlew dependencyCheckAnalyze` fails because it can't find the "dotnet 6.0 runtime or sdk". The project scans fine without the property set.

**Version of dependency-check used**

Version 8.1.0.

**Log file**

```
InitializationException: Could not execute .NET AssemblyAnalyzer, is the dotnet 6.0 runtime or sdk installed?
```

Here's the [full log output with stacktrace](https://gist.github.com/jtconsol/a90752e73a91b8a9a8c0f6602e78ba9d).

**To Reproduce**

1. Run `gradlew dependencyCheckAnalyze --stacktrace`
2. Observe log output.

**Expected behavior**

Should not fail because of that.

**Comment by jtconsol** [comment]
Maybe just to explain what I'm trying to do: I'd like to have test code and dependencies scanned as well.

**Comment by jtconsol** [comment]
Follow-up: I get the same behaviour with `scanBuildEnv = true`.

**Comment by jeremylong** [comment]
That is because your test dependencies and build dependencies must contain a DLL (which could be buried inside a JAR). If you know there is no dotnet code - you can just disable the AssemblyAnalyzer.

**Comment by jtconsol** [comment]
Ah, thanks, wasn't aware that this is necessary. Option reference here https://jeremylong.github.io/DependencyCheck/dependency-check-gradle/configuration.html#Analyzer_Configuration
