### ISSUE TITLE
NVD API v2 support?

### ISSUE THREAD

**Issue by smurf667** [dependency-check/DependencyCheck#5505]
Hello,

I was looking into using DependencyCheck in an enterprise environment, and we have no/limited internet connectivity where I would like to perform the checks. I see that it is [possible to mirror](https://jeremylong.github.io/DependencyCheck/data/cachenvd.html) the vulnerability data and then use the mirror instead.

Now I have stumbled across an "end of life" notification in the/a mirroring tool: https://github.com/stevespringett/nist-data-mirror/
It references this NVD announcement: https://nvd.nist.gov/General/News/changes-to-feeds-and-apis

...will DependencyCheck switch to the NVD 2.0 APIs?

Thank you!

**Comment by mprins** [comment]
duplicates #4732

**Comment by smurf667** [comment]
My question is treated in #4732
