### ISSUE TITLE
How to disable hostedSuppressions

### ISSUE THREAD

**Issue by alfred-thomas** [dependency-check/DependencyCheck#5508]
I am looking to disable `hostedSuppressions` when using the Gradle plugin `8.0.1` since the URL is not accessible via our proxy. Initially I tried adding this in my Gradle config

```
hostedSuppressions {
     enabled = false
}
```
This did not work. I get the error below:
`Could not set unknown property 'enabled' for object of type org.owasp.dependencycheck.gradle.extension.HostedSuppressionsExtension`

I then noticed documentation states 
`hostedSuppressions | enabled | The number of hours to wait before checking for new updates of the hosted suppressions file`

http://jeremylong.github.io/DependencyCheck/dependency-check-gradle/configuration.html

Is this correct and intentional? And what can I do to disable this feature?

**Comment by jeremylong** [comment]
Combination of missing configuration and copy/paste error. This will be fixed in 8.1.1 - which should be releases shortly.
