### ISSUE TITLE
Regression: Jar Analyzer fails 8.1.1

### ISSUE THREAD

**Issue by Xaseron** [dependency-check/DependencyCheck#5518]
**Describe the bug**
When we upgrade the container image to 8.1.1 the jar analyzer fails with `java.lang.NullPointerException: Cannot invoke "java.util.Properties.containsKey(Object)" because "pomProperties" is null`

**Version of dependency-check used**
The problem occurs using version container image 8.1.1

**Log file**
https://gist.github.com/Xaseron/1758afa99c93715096a6760070717043

**To Reproduce**

**Expected behavior**
Should work fine as with 8.1.0

**Additional context**
The cause is probably: 
Prefer pom.properties G/A/V over pom.xml G/A/V to resolve GAV interpolation issues (https://github.com/jeremylong/DependencyCheck/pull/5473)

**Comment by schdief** [comment]
dupe, already fixed: https://github.com/jeremylong/DependencyCheck/pull/5512
