### ISSUE TITLE
Missing artifact for 8.1.1 on Maven Central

### ISSUE THREAD

**Issue by dominik-stronk** [dependency-check/DependencyCheck#5520]
I don't know the details behind publishing artifacts to Maven Central, but by comparison to previous releases current one should have already been available by now.
https://mvnrepository.com/artifact/org.owasp/dependency-check-maven

**Comment by cmuchinsky** [comment]
Indeed, I have noticed the same thing, although given the likelihood of a `8.1.2` release soon I'm not sure it will matter

**Comment by dominik-stronk** [comment]
It matters to someone who waits for some of those FPs resolutions.

**Comment by cmuchinsky** [comment]
> It matters to someone who waits for some of those FPs resolutions.

Agreed, waiting on those myself, I'm hoping 8.1.2 won't suffer the same delays making it to maven central

**Comment by jeremylong** [comment]
Weirdly enough if you actually go to central you'll find the released version:

https://central.sonatype.com/artifact/org.owasp/dependency-check-maven/8.1.1

**Comment by dominik-stronk** [comment]
In that case, sorry for the false alarm.

**Comment by jeremylong** [comment]
no worries - I've seen things take time occasionally to get reported in mvnrepository.
