### ISSUE TITLE
Newtonsoft.json 12.0.2/3 missing as vulnerable in report

### ISSUE THREAD

**Issue by mmatonok** [dependency-check/DependencyCheck#5530]
Hi,

I have .net core 3.1 project with nuget  Newtonsoft.json 12.0.3 version.  per report there is not vulnerability, but seems this is not correct, when I compare with nuget.org site.
https://www.nuget.org/packages/newtonsoft.json/12.0.3

Could you explain that or please let me know what parameters in azure devop Owasp dependency checker I need to setup to report also this nuget.  I setup scan for *.csproj and additional scan for  dll.  I can see Newtonsoft.Json.dll in report but without any vulnerability score.

Thanks,
M

**Comment by jeremylong** [comment]
The vulnerability in question does not have a CVE: https://github.com/advisories/GHSA-5crp-9r3c-p9vr

At the moment dependency-check primarily uses the data from the NVD not the GitHub Security Advisories. Yes - we have plans to incorporate additional data - but we are not there yet.
