### ISSUE TITLE
DOC: Improving Results with Hints

### ISSUE THREAD

**Issue by stevespringett** [dependency-check/DependencyCheck#555]
When browsing https://jeremylong.github.io/DependencyCheck, I noticed that there wasn't a section for 'Improving Results'. Perhaps we should add a how-to on using the HintAnalyzer and provide some documentation on how to create hint files.

**Comment by jeremylong** [comment]
That is planned - but I was waiting a bit as I ironed out some of the hint analyzer. The last release created the opportunity to add version hints; but I think a bit more work needs to be done on this. Possibly adding the ability to do `<and>` and `<or>` tags within the hints for different types of evidence.

**Comment by jeremylong** [comment]
Documentation added via PR #587
