### ISSUE TITLE
Does the Nexus Analyzer work with Nexus OSS 3?

### ISSUE THREAD

**Issue by 13CSherman** [dependency-check/DependencyCheck#5558]
The Central Analyzer has been quite unstable as of late. We are looking into alternatives such as using the Nexus Analyzer instead.
I see in the documentation that it requires Nexus Pro. But I saw from a old comment on issue #1193 that it worked with Nexus OSS 2. I am currently looking at Nexus OSS 3. Is there any updates to the documentation that I'm missing here?

**Comment by aikebah** [comment]
No, see #5319, NexusAnalyzer was built for Nexus v2 and in v3 the REST API was completely renewed.
