### ISSUE TITLE
Struts2 v2.3.30 reporting false positive vulnerabilities in HTML output using CLI v1.4.3

### ISSUE THREAD

**Issue by demasb** [dependency-check/DependencyCheck#558]
Struts2 v2.3.30 is reporting false positives using the CLI v1.4.3. CLI v1.4.0 does not report the false positives. The false positives are related to cpe: cpe:/a:apache:struts:2.0.0 up to cpe:/a:apache:struts:2.3.28 (there are about 50 or so) and to maven: org.apache.struts:struts2-core:2.3.30.

Attached are log files for both the v1.4.3 and v1.4.0 test runs using the attached TestApp.war file (renamed toTestApp.war.txt to make it uploadable).

[Test_1-4-0.txt](https://github.com/jeremylong/DependencyCheck/files/459117/Test_1-4-0.txt)
[Test_1-4-3.txt](https://github.com/jeremylong/DependencyCheck/files/459118/Test_1-4-3.txt)
[TestApp.war.txt](https://github.com/jeremylong/DependencyCheck/files/459112/TestApp.war.txt)

**Comment by jeremylong** [comment]
I updated the version matching algorithm slightly to correct this false positive. The fix will be included in the next release.

Thanks!
