### ISSUE TITLE
Building Dependency-Check without running tests does not work

### ISSUE THREAD

**Issue by Marcono1234** [dependency-check/DependencyCheck#5583]
**Describe the bug**
The README of this project suggests the following to command to build the project without running any tests:
```
mvn -s settings.xml install -Dmaven.test.skip=true
```
([README section link](https://github.com/jeremylong/DependencyCheck#building-without-running-tests))

However, that command fails for the "Dependency-Check Ant Task" module:
```
...
[INFO] -------------------< org.owasp:dependency-check-ant >-------------------
[INFO] Building Dependency-Check Ant Task 8.2.1-SNAPSHOT                  [5/7]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Dependency-Check 8.2.1-SNAPSHOT:
[INFO] 
[INFO] Dependency-Check ................................... SUCCESS [  6.542 s]
[INFO] Dependency-Check Utils ............................. SUCCESS [  8.800 s]
[INFO] Dependency-Check Core .............................. SUCCESS [ 11.010 s]
[INFO] Dependency-Check Command Line ...................... SUCCESS [  4.587 s]
[INFO] Dependency-Check Ant Task .......................... FAILURE [  0.038 s]
[INFO] Dependency-Check Maven Plugin ...................... SKIPPED
[INFO] Dependency-Check Plugin Archetype .................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  36.797 s
[INFO] Finished at: 2023-03-22T20:46:46Z
[INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal on project dependency-check-ant: Could not resolve dependencies for project org.owasp:dependency-check-ant:jar:8.2.1-SNAPSHOT: Could not find artifact org.owasp:dependency-check-core:jar:tests:8.2.1-SNAPSHOT -> [Help 1]
```

My assumption is that `-Dmaven.test.skip=true` also skips creation of a test artifact, which is however required by later steps.
To verify that this is not caused by a mistake I made with my local setup, I let GitHub actions run the same command and it fails with the same error ([log](https://github.com/Marcono1234/DependencyCheck/actions/runs/4494328354/jobs/7906670683#step:9:583)).

**Version of dependency-check used**
`main` (9ca6da02496797e930653e236d48bb6aba79da5d)

**Log file**
See for example log of GitHub actions run: https://github.com/Marcono1234/DependencyCheck/actions/runs/4494328354/jobs/7906670683

**To Reproduce**
1. Clone Dependency-Check
2. Run
    ```
    mvn -s settings.xml install -Dmaven.test.skip=true
    ```

**Important:** You might have to first increase the Dependency-Check project version, specify a temporary local Maven repository, or remove existing artifacts from your local Maven repository. Otherwise from a previous `mvn install` execution the missing `org.owasp:dependency-check-core:jar:tests` might already exist in your local Maven repository (?).

**Expected behavior**
The Maven build should succeed

**Comment by jeremylong** [comment]
You can use `-DskipTests=true`.

**Comment by Marcono1234** [comment]
Thanks, that works. Have created #5595 to adjust the README.

**Comment by Marcono1234** [comment]
@jeremylong, a slightly related question, is it actually necessary to run `mvn ... install` or does it suffice to run `mvn ... verify`? That is, is there any configured plugin which is not run when only using `verify`?

`install` has the disadvantage that it places the artifacts in the local Maven repository, which could cause issues. Also, it looked to me like when using `install` certain changes (e.g. to the HTML report template) were not picked up anymore (but maybe there was something else wrong with my setup; haven't investigated it much more).

**Comment by jeremylong** [comment]
verify works

**Comment by aikebah** [comment]
@Marcono1234 It depends on the use-case. You would need to run `mvn install` when you would want to subsequently use the created maven plugin (or subsequently use the created jars for building a snapshot gradle plugin). When you want to use the CLI `mvn verify` or even `mvn package` would suffice.
