### ISSUE TITLE
Could not detect vulnerability on dotnet 6.0

### ISSUE THREAD

**Issue by viniciusvmda** [dependency-check/DependencyCheck#5594]
I created the following sample web project using dotnet 6.0 on windows WSL with a known CVE (https://security.snyk.io/vuln/SNYK-DOTNET-RESTSHARP-1316436)

`
dotnet add package RestSharp --version 106.6.10
`

[MyVulnerableProject.zip](https://github.com/jeremylong/DependencyCheck/files/11051423/MyVulnerableProject.zip)

If I use the `dotnet list package --vulnerable`, it shows the vulnerability, but it is not shown using dependency-check. It always shows a problem in the project dll, even if I remove the dependency.
![image](https://user-images.githubusercontent.com/6676509/227223124-8148ec51-3576-4b4d-8b73-54b9f076f54b.png)

I am currently using the following code 
`
~/tools/dependency-check/bin/dependency-check.sh --project MyVulnerableProject --scan bin/Debug/net6.0/*.dll --format HTML --format JSON --out dependency-check
`  

Am I doing something wrong?
Thanks in advance.

**Comment by viniciusvmda** [comment]
@jeremylong

**Comment by aikebah** [comment]
DependencyCheck is not scanning dependencies of your dll, it is scanning dependencies of a dotnet project. Were you to scan the RestSharp package's dll or your full dotnet project I would expect it to surface the vulberability.

**Comment by viniciusvmda** [comment]
> DependencyCheck is not scanning dependencies of your dll, it is scanning dependencies of a dotnet project. Were you to scan the RestSharp package's dll or your full dotnet project I would expect it to surface the vulberability.

I was scanning the path containing the DLLs with regular expression:

**Comment by viniciusvmda** [comment]
> DependencyCheck is not scanning dependencies of your dll, it is scanning dependencies of a dotnet project. Were you to scan the RestSharp package's dll or your full dotnet project I would expect it to surface the vulberability.

I was scanning the path containing the DLLs with regular expression:
`bin/Debug/net6.0/*.dll`

**It reported the vulnerability in Resharp when I scanned the whole folder:
`bin/Debug/net6.0`**

Thank you!

**Comment by jeremylong** [comment]
dependency-check will also scan project files...(nuget, csproj, etc.).
