### ISSUE TITLE
dependency-check-maven incompatible with maven 3.0 since v1.4.3

### ISSUE THREAD

**Issue by aikebah** [dependency-check/DependencyCheck#560]
In dependency-check v1.4.3 a dependency was created on Eclipse Aether dependency resolution classes which are in Maven since version 3.1 (as a replacement of Sonatype Aether) . Hence as of 1.4.3 dependency-check requires maven 3.1+ or higher. Older versions of maven will run into ClassNotFoundException for org.eclipse.aether.\* classes.

I think it would be good to add a prerequisites section in the POM to indicate that the plugin needs maven 3.1+ to run:

<pre>
  &lt;prerequisites>
    &lt;maven>3.1.0&lt;/maven>
  &lt;/prerequisites>
</pre>

**Comment by jeremylong** [comment]
Added the 3.1 pre-req as this will also allow us to solve the duplicate class issue in #552 due to the org.slf4j.impl.StaticLoggerBinder.
