### ISSUE TITLE
dependencycheck update fails using openJDK

### ISSUE THREAD

**Issue by Phone911** [dependency-check/DependencyCheck#561]
When performing dependencycheck (version 143) updateonly processing using the openJDK version 1.8.0_101 we get the following failure:

[INFO] Checking for updates
[ERROR] IO Exception: Connection reset
[ERROR] IO Exception: Connection reset
[WARN] Unable to download the NVD CVE data; the results may not include the most recent CPE/CVEs from the NVD.
[INFO] If you are behind a proxy you may need to configure dependency-check to use the proxy.
[ERROR] Unable to download the NVD CVE data.

When we run the same script using Java HotSpot (Oracle Java) version 1.8.0_74 the update process works:

[INFO] Checking for updates
[INFO] Download Started for NVD CVE - Modified
[INFO] Download Complete for NVD CVE - Modified  (675 ms)
[INFO] Processing Started for NVD CVE - Modified
[INFO] Processing Complete for NVD CVE - Modified  (15251 ms)
[INFO] Begin database maintenance.
[INFO] End database maintenance.
[INFO] Check for updates complete (19503 ms)

I am including log files from both runs.

[dc-openjdk.txt](https://github.com/jeremylong/DependencyCheck/files/474693/dc-openjdk.txt)
[dc-hotspot.txt](https://github.com/jeremylong/DependencyCheck/files/474694/dc-hotspot.txt)

**Comment by biancajiang** [comment]
+1.

**Comment by jeremylong** [comment]
1.4.3 works for me (well, 1.4.4-SNAPSHOT - but there is no difference in the download code). Which is unfortunate for both you and me as I want to be able to help solve this problem. Attached are two runs using openjdk and ibm jdk and in both the download works correctly:

[ibm_jdk.txt](https://github.com/jeremylong/DependencyCheck/files/477186/ibm_jdk.txt)
[open_jdk.txt](https://github.com/jeremylong/DependencyCheck/files/477187/open_jdk.txt)

Is there any chance you are behind a proxy? Could we try adding `-Djavax.net.debug=all` and providing the log?

**Comment by Phone911** [comment]
Both these runs were from the same machine with the same proxy. We also tried running on a different proxy and got the same results. I would think this is evidence that the proxy is not the problem.

Gary Burchett

Tel: +1 (919) 531-6995
Mobile: +1 (919) 413-3146

**Comment by jeremylong** [comment]
Could you try adding `-Djavax.net.debug=all` and providing the log?

**Comment by biancajiang** [comment]
@jeremylong I found my silly problem.

I forgot to push the changes from 1.4.3 release to my branch I used for build!  So my build was run w/o the fix.  Once the build is aligned with 1.4.3, it passes!  Sorry about the churns!

My local mac machine seems to have some JVM conflict I'm still looking.

FYI, I do not use proxy.

**Comment by Phone911** [comment]
Here are runs with the two javas. I did an export JAVAOPTS=”-Djavax.net.debug=all” and ran the two scripts.

Gary Burchett

Tel: +1 (919) 531-6995
Mobile: +1 (919) 413-3146

**Comment by jeremylong** [comment]
@Phone911 can you re-run the failing script using the following (minor typo in the export above, and I'll need a slightly different log):

```
export JAVA_OPTS=-Djavax.net.debug=all
dependency-check.sh --updateonly > debug.txt 2>&1
```

And then post the debug.txt file here. This only needs to be done for the failing instance. The debug.txt should contain a TON of data on algorithms, cert stores, the TLS handshake, etc.

--Jeremy

**Comment by Phone911** [comment]
I apologize for the error in setting JAVA_OPTS. Attached is the console and the --log output.

Gary Burchett

Tel: +1 (919) 531-6995
Mobile: +1 (919) 413-3146

**Comment by mikjo** [comment]
I just reproduced this on a system that definitely has no proxy in place. I was trying to reproduce #570 on a system without a mysql database and without a proxy to make sure it was a clean reproducer, but instead ran into this issue. It looks to me like a protocol error; I was expecting `no cipher suites in common` but I just see the connection reset; see the bottom of [this gist](https://gist.github.com/mikjo/ba1c8b23c8b88644426d25f8a6323661)

**Comment by dayer4b** [comment]
this is happening for me too.  Installing and using Oracle java makes the problem go away

**Comment by jeremylong** [comment]
@mikjo looking at the log you provided via gist - can you confirm if that is from dependency-check 1.4.2 or 1.4.3?  It looks like it would be from 1.4.2 - the algorithm list was removed from dependency-check and that resolved the issue with lines like this from the javax.net.debug log:

```
Ignoring unavailable cipher suite: TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA
Ignoring unavailable cipher suite: TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA
Ignoring unavailable cipher suite: TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
```

I am still having trouble replicating this issue. I just installed Ubuntu 16.04, ran `sudo apt-get install openjdk-8-jre`, and then ran dependency-check and everything worked:

``` bash
jeremy@box:/media/sf_box/dependency-check/bin$ ./dependency-check.sh --updateonly
[INFO] Checking for updates
[INFO] NVD CVE requires several updates; this could take a couple of minutes.
[INFO] Download Started for NVD CVE - 2004
[INFO] Download Started for NVD CVE - 2003
[INFO] Download Started for NVD CVE - 2002
[INFO] Download Complete for NVD CVE - 2003  (1468 ms)
[INFO] Download Started for NVD CVE - 2005
[INFO] Processing Started for NVD CVE - 2003
[INFO] Download Complete for NVD CVE - 2004  (1836 ms)
[INFO] Download Started for NVD CVE - 2006
[INFO] Download Complete for NVD CVE - 2002  (2253 ms)
[INFO] Download Started for NVD CVE - 2007
[INFO] Download Complete for NVD CVE - 2005  (2093 ms)
[INFO] Download Started for NVD CVE - 2008
[INFO] Download Complete for NVD CVE - 2006  (2862 ms)
[INFO] Download Started for NVD CVE - 2009
[INFO] Download Complete for NVD CVE - 2007  (2740 ms)
[INFO] Download Started for NVD CVE - 2010
[INFO] Download Complete for NVD CVE - 2008  (2769 ms)
[INFO] Download Started for NVD CVE - 2011
[INFO] Download Complete for NVD CVE - 2009  (2797 ms)
[INFO] Download Started for NVD CVE - 2012
[INFO] Download Complete for NVD CVE - 2010  (3497 ms)
[INFO] Download Started for NVD CVE - 2013
[INFO] Download Complete for NVD CVE - 2012  (4182 ms)
[INFO] Download Started for NVD CVE - 2014
[INFO] Processing Complete for NVD CVE - 2003  (10384 ms)
[INFO] Processing Started for NVD CVE - 2004
[INFO] Download Complete for NVD CVE - 2013  (4115 ms)
[INFO] Download Started for NVD CVE - 2015
[INFO] Download Complete for NVD CVE - 2011  (6589 ms)
[INFO] Download Started for NVD CVE - 2016
[INFO] Download Complete for NVD CVE - 2014  (2833 ms)
[INFO] Download Started for NVD CVE - Modified
[INFO] Download Complete for NVD CVE - 2015  (2331 ms)
[INFO] Download Complete for NVD CVE - 2016  (2150 ms)
[INFO] Download Complete for NVD CVE - Modified  (1281 ms)
[INFO] Processing Complete for NVD CVE - 2004  (10252 ms)
[INFO] Processing Started for NVD CVE - 2002
[INFO] Processing Complete for NVD CVE - 2002  (6138 ms)
[INFO] Processing Started for NVD CVE - 2005
[INFO] Processing Complete for NVD CVE - 2005  (6469 ms)
[INFO] Processing Started for NVD CVE - 2006
[INFO] Processing Complete for NVD CVE - 2006  (9723 ms)
[INFO] Processing Started for NVD CVE - 2007
[INFO] Processing Complete for NVD CVE - 2007  (9736 ms)
[INFO] Processing Started for NVD CVE - 2008
[INFO] Processing Complete for NVD CVE - 2008  (15926 ms)
[INFO] Processing Started for NVD CVE - 2009
[INFO] Processing Complete for NVD CVE - 2009  (22103 ms)
[INFO] Processing Started for NVD CVE - 2010
[INFO] Processing Complete for NVD CVE - 2010  (33365 ms)
[INFO] Processing Started for NVD CVE - 2012
[INFO] Processing Complete for NVD CVE - 2012  (38186 ms)
[INFO] Processing Started for NVD CVE - 2013
[INFO] Processing Complete for NVD CVE - 2013  (30386 ms)
[INFO] Processing Started for NVD CVE - 2011
[INFO] Processing Complete for NVD CVE - 2011  (312469 ms)
[INFO] Processing Started for NVD CVE - 2014
[INFO] Processing Complete for NVD CVE - 2014  (21286 ms)
[INFO] Processing Started for NVD CVE - 2015
[INFO] Processing Complete for NVD CVE - 2015  (12322 ms)
[INFO] Processing Started for NVD CVE - 2016
[INFO] Processing Complete for NVD CVE - 2016  (8086 ms)
[INFO] Processing Started for NVD CVE - Modified
[INFO] Processing Complete for NVD CVE - Modified  (38446 ms)
[INFO] Begin database maintenance.
[INFO] End database maintenance.
[INFO] Check for updates complete (601412 ms)
jeremy@box:/media/sf_box/dependency-check/bin$ java -version
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)
```

**Comment by johnsonm** [comment]
I was @mikjo while I was at SAS; I am now posting from my personal account. The tests at SAS were on CentOS 7 and RHEL 7. I don't have access to those systems to re-test. Those were the tests running through a proxy.

For the tests not running through a proxy, I ran them on machines of my own. I definitely downloaded what was advertised as 1.4.3. Perhaps you accidentally posted 1.4.2 as 1.4.3? I no longer have the environment that I created for doing that test. The download was in a tmpfs /tmp, and I have since rebooted, so I don't have that download. I was running Fedora 23 at the time, and have since updated the system to Fedora 24, so I don't even have the same system software running.

I don't know whether Red Hat removes some encryption algorithms from their builds of OpenJDK due to patent concerns.

**Comment by jeremylong** [comment]
There have been two issues open trying to resolve this issue. I have posted the solution to the other [thread in issue#523](https://github.com/jeremylong/DependencyCheck/issues/523#issuecomment-257044886). Short answer, if you are running into this problem install and use Bouncy Castle.

**Comment by lpearson05** [comment]
FYI: The latest OpenJDK is working for me without BouncyCastle.

```
$ java -version
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-b15)
OpenJDK 64-Bit Server VM (build 25.111-b15, mixed mode)
```

_more environment info in [original comment on #523]( https://github.com/jeremylong/DependencyCheck/issues/523#issuecomment-267772666)_
