### ISSUE TITLE
OWASP throwing Invalid tool ID 6.3.1 error

### ISSUE THREAD

**Issue by chetan-alti** [dependency-check/DependencyCheck#5610]
Hai everyone,

I'm using OWASP scan from last year. I have configured in the Jenkins using OWASP Dependency- check plugin . But from last few days I'm facing the error `Invalid tool ID 6.3.1 `(also 6.3.1 is the name I configured in the global tools ). I have configured install automatically (install from [dl.bintray.com](http://dl.bintray.com/) ). The scan not working properly and report is also not generating.

I'm unable to find the fix 😕. If anyone have any idea on this please reply back.

Thank you in advance

Regards

**Comment by jeremylong** [comment]
We do not support the Jenkins plugin. The support site for the Jenkins plugin is: https://issues.jenkins.io/browse/JENKINS-68082?jql=resolution%20is%20EMPTY%20and%20component%3D18029

**Comment by chetan-alti** [comment]
I'm sorry. Thanks for the replay
