### ISSUE TITLE
How to improve download + processing performance by using the *.properties file?

### ISSUE THREAD

**Issue by HaGGi13** [dependency-check/DependencyCheck#5617]
Hello,

I am referring to the values of the file [`dependencycheck.properties`](https://github.com/jeremylong/DependencyCheck/blob/main/core/src/main/resources/dependencycheck.properties) in this question.  

Following mentioned adjustments would be part of the a dedicated `dc.properties` file that is addressed in parameter `--propertyfile` on execution.

1. I am wondering why the default amount of threads to use for downloading files/definitions is defined as `1`. Would it has any negative effect to increase it up to `5` or `10`?
https://github.com/jeremylong/DependencyCheck/blob/d702c4d18c21782076435e362f379c798970ec81/core/src/main/resources/dependencycheck.properties#L73
2. Why is the wait time after a download defined with 4000ms (4s)? Does it has an negative effect or does it interfere with the processing itself if it is decreased to 500ms instead?
https://github.com/jeremylong/DependencyCheck/blob/d702c4d18c21782076435e362f379c798970ec81/core/src/main/resources/dependencycheck.properties#L63

Thank you in advance for any response.

BR, Chris

**Comment by aikebah** [comment]
See https://github.com/jeremylong/DependencyCheck/issues/3639 for a bit of the history on why it's set as it is.
Change at your own risk, if you use the nist-data-mirror to have a local mirror of the datafeeds that dependency-check uses for building its database it would be safe to increase parallelism / decrease wait time to zero.

**Comment by jeremylong** [comment]
Basically - if you are hitting the NVD data feeds at a faster rate you are likely going to hit their rate limit and be blocked.

**Comment by HaGGi13** [comment]
Okay, thank you for your reply.
Closed.
