### ISSUE TITLE
Is dependency check using mvn command generate the dependency list.

### ISSUE THREAD

**Issue by Lingom-KSR** [dependency-check/DependencyCheck#5627]
Hi,
Would like to know if dependency check is using maven commands to list the dependencies in the project. 

If not,  how Dependency Check generating the dependency list? (I understand that the tools is looking for Jar file, but besides). Also, want to know, is there any difference in the dependencies list provided by Dependency Check and the "mvn dependency:tree".

If it is the repeated question, please redirect me to the original question.

Thank You.

**Comment by jeremylong** [comment]
No, the CLI version of dependency check is only looking at the files on disk that are scanned. So if you are using the CLI to scan a Java project you should probably run something like `mvn package dependency:copy-dependencies` and then scan the target directory.

This is why we recommend using the dependency-check-maven plugin to scan maven projects and the gradle plugin to scan gradle projects. The results will be much more accurate.
