### ISSUE TITLE
Request: Link to current release without version number

### ISSUE THREAD

**Issue by wurstbrot** [dependency-check/DependencyCheck#563]
As a Dockerfile-Manager I would like to download the current release by a link like https://bintray.com/jeremy-long/owasp/download_file?file_path=dependency-check-current-release.zip
without version number. Is it possbile to have a link to the current release?

In that case, I do not need to check for a new release and each docker user will be able to download the current release after the automatic build processes in the night.

**Comment by jeremylong** [comment]
You can get the current version # from this file: http://jeremylong.github.io/DependencyCheck/current.txt

It is a single line file with the currently released version. As such, you should be able to run a script within docker that grabs the version number, builds the download path, and downloads the ZIP.  Would that work?

**Comment by wurstbrot** [comment]
Perfect, thank you.
