### ISSUE TITLE
How does hosted suppression work?

### ISSUE THREAD

**Issue by s3nl** [dependency-check/DependencyCheck#5663]
Hi there,

I've had a look in the Dependency check repo and I came accross multiple suppression files. Maybe I missed it but which one should I be using for the hosted suppression file?

**Comment by jeremylong** [comment]
You should not have to configure the hosted suppression file. However, if you look at the [documentation](https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html) the default location for the hosted suppression file is: https://jeremylong.github.io/DependencyCheck/suppressions/publishedSuppressions.xml

**Comment by s3nl** [comment]
Ok, thanks for the clarification. What is the difference between the publishedSuppressions.xml and the file at https://raw.githubusercontent.com/jeremylong/DependencyCheck/main/core/src/main/resources/dependencycheck-base-suppression.xml and https://github.com/jeremylong/DependencyCheck/blob/generatedSuppressions/generatedSuppressions.xml? 

We're looking to simulate hosted suppression in an air gapped scenario and we don't know which file is the most complete for us to use.

**Comment by jeremylong** [comment]
https://raw.githubusercontent.com/jeremylong/DependencyCheck/main/core/src/main/resources/dependencycheck-base-suppression.xml is the suppression rules bundled into dependency-check-core.jar. The generatedSuppressions are a staging area that is used to generated the [publishedSuppressions.xml](https://jeremylong.github.io/DependencyCheck/suppressions/publishedSuppressions.xml). Occasionally, we will copy the suppressions from the `publishedSuppressions.xml` into the `dependencycheck-base-suppression.xml`.

**Comment by s3nl** [comment]
Ok thanks for the clarification. Does this mean that the ```publishedSuppressions.xml``` is always filled? Are the contents ever deleted or is it append only?

**Comment by jeremylong** [comment]
We have not yet truncated the publishedSuppressions.xml - if we do it will only be at a major release and we would only trim the oldest entries that have been in the base suppression file for several versions.

**Comment by s3nl** [comment]
Ok thanks. Will close this one now.
