### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space on python project analysis

### ISSUE THREAD

**Issue by tassadar81** [dependency-check/DependencyCheck#5671]
**Describe the bug**
java.lang.OutOfMemoryError: Java heap space

**Version of dependency-check used**
The problem occurs using version 8.2.1 and previous version of the command line version

**Log file**
When reporting errors, 99% of the time log file output is required. Please post the [log file](https://gist.github.com/tassadar81/769b25bf51a51d1583c422c756df610e)

**To Reproduce**
analyze a project with this dependency /site-packages/cmake/data/share/cmake-3.26/Modules/FindFLTK2.cmake' (CMake Analyzer): Java heap spac

**Comment by jeremylong** [comment]
Maybe try increasing the heap space?

```
export JAVA_OPTS="-Xms6144m -Xmx6144m -XX:NewSize=256m -XX:MaxNewSize=356m -XX:PermSize=256m -XX:MaxPermSize=356m"
```

**Comment by tassadar81** [comment]
@jeremylong i saw it reaching always the maximum possible, last exectution it reached about 22Gibytes of ram on 24 available, so no 6 won't help

**Comment by aikebah** [comment]
There is indeed a structural flaw in the mechanism to detect selfreferences in the CMakeAnalyzer

```
...
Removed selfreferencing var FLTK_DIR (with value ${FLTK_INCLUDE_DIR})
Removed selfreferencing var FLTK_INCLUDE_DIR (with value ${FLTK_DIR})
Key FLTK_INCLUDE_PATH encountered
nextKey = FLTK_INCLUDE_PATH
nextKey = FLTK_INCLUDE_DIR
chainsize = 2
nextKey = FLTK_DIR
chainsize = 3
nextKey = FLTK_INCLUDE_DIR
chainsize = 4
nextKey = FLTK_DIR
chainsize = 5
nextKey = FLTK_INCLUDE_DIR
chainsize = 6
nextKey = FLTK_DIR
chainsize = 7
nextKey = FLTK_INCLUDE_DIR
...
```
as you can see for checking the FLTK_INCLUDE_PATH for circular references (one of the three CMake variables triggering an OoM condition) it is traversing the circular variable references of FLTK_DIR and FLTK_INCLUDE_DIR until it reaches OoM

**Comment by nhumblot** [comment]
Hi :wave: 

I'm sorry for this, this is due to a logic flaw in the method detecting self referencing variables I implemented a year ago. I have a fix on my workstation and will provide a PR soon.
