### ISSUE TITLE
Dependency Check exited with an error code (exit code: 14)

### ISSUE THREAD

**Issue by vdhalgara** [dependency-check/DependencyCheck#5673]
Hello @jeremylong.

I'm trying to use Dependency Check in AzDO Release Pipeline and keep running into an issue below where I am seeing an exit code 14.

Dependency-Check Core version 8.2.1

Log:
[tasklog_7.log](https://github.com/jeremylong/DependencyCheck/files/11298001/tasklog_7.log)

Thank you!

**Comment by jeremylong** [comment]
I'd start with looking for errors in the log:

```
[ERROR] Warn initializing the suppression analyzer: Failed to load D:\agents\_work\r52\a, caused by java.io.FileNotFoundException: D:\agents\_work\r52\a (Access is denied). 
2023-04-21T14:43:42.2291133Z 
```
