### ISSUE TITLE
Keeping the suppressions file in parent project while the child projects are picking up parent from repository

### ISSUE THREAD

**Issue by jainishan** [dependency-check/DependencyCheck#5677]
I have a parent project which I use to define library versions and some plugins. This is an independent project and contains nothing other than POM (for now) and is supposed to be inherited by several other children/microservices using the <parent> tag and load the artifact pushed to internal repositories. So, none of the projects are within same folder structure, everything is independent.

parent project POM excerpt:
```xml   
 <groupId>com.mine</groupId>
    <artifactId>parent</artifactId>
    <version>0.0.1</version>
    <packaging>pom</packaging>
    <name>parent POM (BOM)</name>
    <description> parent POM (BOM)</description>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.7.10</version>
        <relativePath />
    </parent>
```

Usage:
```xml 
<parent>
        <groupId>com.mine</groupId>
        <artifactId>parent</artifactId>
        <version>0.0.1</version>
        <relativePath/>
    </parent>
    <artifactId>child-project</artifactId>
    <version>1.0.0</version>
```

Since the main purpose is to define lib versions centrally in the parent POM, I think it makes sense to configure dependency-check plugin in the parent itself along with the suppressions file to keep everything centralised.

In the parent POM:
```xml
<plugins>
                <plugin>
                    <groupId>org.owasp</groupId>
                    <artifactId>dependency-check-maven</artifactId>
                    <version>8.2.1</version>
                    <configuration>
                        <format>ALL</format>
                        <failBuildOnCVSS>8</failBuildOnCVSS>
                        <suppressionFile>owasp-suppressions.xml</suppressionFile>
                    </configuration>
                    <executions>
                        <execution>
                            <goals>
                                <goal>check</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
```

Now the problem is, triggering check in any of the child project warns me about not being able to find suppressions file.
I have placed the suppressions file in the root of the parent project but no matter what I try, it is not able to load the file.

I tried:
- Moving the file to src/main/resources
- `<suppressionFile>${basedir}/owasp-suppressions.xml</suppressionFile>`
- `<suppressionFile>../owasp-suppressions.xml</suppressionFile>`
- `<suppressionFile>../parent/owasp-suppressions.xml</suppressionFile>`

How can I make sure that entire configuration remains in the parent and just inheriting it in a project should make it all work ?

**Comment by jeremylong** [comment]
Maybe:

`<suppressionFile>${session.executionRootDirectory}/owasp-suppressions.xml</suppressionFile>`

or this (but - this appears to be an internal property that you may not want to use):

`<suppressionFile>${maven.multiModuleProjectDirectory}/owasp-suppressions.xml</suppressionFile>`

Or just use the aggregate report and do not inherit the plugin into the child modules.

**Comment by jainishan** [comment]
Both of them result in the same error:

`
[WARNING] Unable to read suppression file '<absolute_path_to_child_project_DIR>/owasp-suppressions.xml'
`

I have removed the plugin from child POM and it is getting executed in the child project from the parent POM. But since I am triggering it from child, the values to these path variables seems to be passed on from the child project context.

I am not sure what do you mean by using the aggregate report.

**Comment by jeremylong** [comment]
The aggregate goal will generate a single report for the entire maven project:

```
<plugins>
                <plugin>
                    <groupId>org.owasp</groupId>
                    <artifactId>dependency-check-maven</artifactId>
                    <version>8.2.1</version>
                    <configuration>
                        <format>ALL</format>
                        <failBuildOnCVSS>8</failBuildOnCVSS>
                        <suppressionFile>owasp-suppressions.xml</suppressionFile>
                    </configuration>
                    <executions>
                        <execution>
                            <goals>
                                <goal>aggregate</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
```

**Comment by jainishan** [comment]
Ok, found the issue - The packaging of parent is of type POM. Only the POM.xml is being deployed and used by the child project.

Reading about it, it makes sense to have only POM file being used as a parent and not have anything like a jar or a war.

In my use case, we have this parent POM to define versions of all the libraries and other plugin configs to be used in several microservices. I see it fitting that we define the suppressions file here in the parent somehow - if a lib version cannot be updated, we add the suppression that shall be inherited in all microservices at once along with the version update. Right now the problem is that all/most of the microservices start to die in a "mass outage fashion" and we have to put the exact suppression in all of them individually to unblock.

Hosting the suppressions file doesn't look neat as then the lib version update would be separated from the update of suppressions file. I see them hosted together and updated together.

I see that inline suppressions is also not an option. Is there something I can do to achieve this centralization in parent POM/project ?

**Comment by liefke** [comment]
@jainishan: I'm using it like this:

_mainproject/pom.xml_:

	<properties>
		<mainproject.dir>${project.basedir}</mainproject.dir>
	</properties>
       ...
	<plugin>
		<groupId>org.owasp</groupId>
		<artifactId>dependency-check-maven</artifactId>
		<configuration>
			<suppressionFiles>
				<suppressionFile>${mainproject.dir}/tools/suppression.xml</suppressionFile>
			</suppressionFiles>
		</configuration>
	</plugin>

_mainproject/module/pom.xml_:

	<properties>
		<mainproject.dir>${project.basedir}/...</mainproject.dir>
	</properties>

This is useful for references to all files, which reside in the _mainproject_ dir.

**Comment by jainishan** [comment]
@liefke thanks for the sample code. I can imagine it would resolve the issue of execution happening in the child project.
In my case, the packaging is of POM type, and thus suppressions.xml will never be pushed along with the POM.

**Comment by jeremylong** [comment]
@jainishan have you actually tried the solution provided? The dependency-check project itself has a top level pom project that sets properties: https://github.com/jeremylong/DependencyCheck/blob/9586cc14513f2296ae8d62c9b3cc1d0665738e5a/pom.xml#L377-L391

**Comment by jainishan** [comment]
@jeremylong I tried the solutions provided and syntax wise they should work. It will not work in my case because of the project structure I have.
I have a parent project with POM packaging and it's own pipeline. Whenever we release a version of this, the POM.xml file is pushed to the artifactory in that version path. The child project can then define this version as parent and maven will fetch the POM file.
Unless I explicitly push suppressions file along with the POM file into artifactory, the above solutions will not work for me. I need to execute the check goal on child project only and this one has no way of accessing resource files in parent project.

**Comment by jeremylong** [comment]
If everyone put the suppression file in the exact same location and file name you could get clever with profiles (if some projects do not have a suppression file); see https://github.com/jeremylong/DependencyCheck/issues/3947#issuecomment-1005024826
