### ISSUE TITLE
[ERROR] Could not execute .NET AssemblyANalyzer on Linux

### ISSUE THREAD

**Issue by RobSHK** [dependency-check/DependencyCheck#5680]
Hello,

While DC is running using the CLI the following error is visible in the log:

> 2023-04-26 12:05:48,172 org.owasp.dependencycheck.App:213
> ERROR - Could not execute .NET AssemblyAnalyzer
> 2023-04-26 12:05:48,172 org.owasp.dependencycheck.App:214
> DEBUG - unexpected error
> org.owasp.dependencycheck.exception.InitializationException: Could not execute .NET AssemblyAnalyzer
>         at org.owasp.dependencycheck.analyzer.AssemblyAnalyzer.prepareFileTypeAnalyzer(AssemblyAnalyzer.java:372)
>         at org.owasp.dependencycheck.analyzer.AbstractFileTypeAnalyzer.prepareAnalyzer(AbstractFileTypeAnalyzer.java:83)
>         at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.prepare(AbstractAnalyzer.java:102)
>         at org.owasp.dependencycheck.Engine.initializeAnalyzer(Engine.java:824)
>         at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:660)
>         at org.owasp.dependencycheck.App.runScan(App.java:259)
>         at org.owasp.dependencycheck.App.run(App.java:191)
>         at org.owasp.dependencycheck.App.main(App.java:86)
> 2023-04-26 12:05:48,172 org.owasp.dependencycheck.utils.Settings:842_

The --dotnet is set correctly as follows:
--dotnet '/usr/bin/dotnet'
As well I can find it in the log:
DEBUG - Setting: analyzer.assembly.dotnet.path='/usr/bin/dotnet'

The path to dotnet is also correct:
$ which dotnet
/usr/bin/dotnet
$ dotnet --version
3.1.426

Any help would be much appriciated.

**Comment by jeremylong** [comment]
[dotnet 6 (runtime or sdk) is required.](https://jeremylong.github.io/DependencyCheck/analyzers/assembly-analyzer.html)

**Comment by RobSHK** [comment]
Thanks, after installing dotnet6 it works fine.
