### ISSUE TITLE
Need basic help with running it

### ISSUE THREAD

**Issue by Yozhika** [dependency-check/DependencyCheck#5687]
Hi,

Updating my question after reading some documentation:
I started using dependency-check for scanning open source software. And I have a couple of questions:
1. Is File type analyzers where I will find the answer whether it works for exe and msi ? I found exe in the list but no msi.

2. I saw in the Wiki it says it updates itself. Just want to confirm - do I need to do something to update/upgrade the installer version? Is there an update schedule? How often is it updated?

3. Are we ok using it in corporate environment or is there a paid version?
4. Do I have to compile it with maven or other instrument? Or is it enough if I just downloaded the installer and use it in cli to scan?
5. I scanned the dependency-check installer and it says it uses snakeyaml-1.33.jar, which has a critical vuln. When will this be patched?

Thanks,
Alina

**Comment by aikebah** [comment]
On 1.: That's correct the File type analyzers define what file types can be scanned (and their implementation details define what metadata of those files is taken into account in the logic to link discovered files to sources of vulnerability-data).

On 2/4/5: There is no installer for this project. There is the binary distribution as a CLI and there are the various integration plugins for build tools. If a build-tool plugin for your build-tool is available that is the best way to use it. The CLI has a much higher chance of misidentifying dependencies.

On 2: Where did you read that? This tool does not update itself, it only updates the vulnerability data, not the application itself.

On 3: As this is licensed under the [apache license](https://github.com/jeremylong/DependencyCheck/blob/main/LICENSE.txt) use in a corporate environment depends solely on your company software policy - do they allow the use of community-supported open source software, or do require a support contract on any tool used? There is no paid version of this project.

**Comment by aikebah** [comment]
The snakeyaml dependency is transitive (via jackson-dataformat-yaml), will be upgraded in the next release and is only in use in the experimental Dart analyzer.
