### ISSUE TITLE
Error when running check or purge in 1.4.3

### ISSUE THREAD

**Issue by Greenjam94** [dependency-check/DependencyCheck#569]
### Description

Updated from 1.4.2 to 1.4.3. Running either purge or check will cause a failure, rolling back to 1.4.2 I do not get the same issue. [Log file is linked here](https://gist.github.com/Greenjam94/4d6ea9f654e5c4d510d3cc0c2681bef1)

**Comment by Greenjam94** [comment]
I'm running maven 3.1.1 and using java 1.8.0_91 so I don't think this is a duplicate of earlier issues.

**Comment by jeremylong** [comment]
I still don't fully understand what is going on as this class is supposed to be in 3.1.x - still researching. One question though - are your other plugins up to date `mvn versions:display-plugin-updates`)?

**Comment by Greenjam94** [comment]
That output is [here](https://gist.github.com/Greenjam94/62db1dca2de8e783770cde3901e167dc)

Some things to note about my implementation. First, I have a parent pom that breaks into many children poms, the example above is the one I'm currently working on. Secondly, my projects do not have the <prerequisites> tag. Both poms are using maven 3.1.1 when I run `mvn -v`

**Comment by Greenjam94** [comment]
This isn't an issue, sorry for the confusion.

The problem was with my IDE setup. While M2_HOME is set to 3.1.1, the IDE was using an earlier version that was bundled internally. That's why my terminal output says I'm using 3.1.1 but I was getting errors related to missing files while running inside the IDE.
