### ISSUE TITLE
[FP]: Apache directory LDAP API binding for MINA mistaken for MINA itself

### ISSUE THREAD

**Issue by chadlwilson** [dependency-check/DependencyCheck#5704]
### Package URl

pkg:maven/org.apache.directory.api/api-ldap-net-mina@1.0.3

### CPE

`cpe:2.3:a:apache:mina:1.0.3:*:*:*:*:*:*:*`

### ODC Integration

{"label"=>"Gradle Plugin"}

### ODC Version

8.2.1

### Description

The LDAP API factory for MINA is mistaken for MINA itself. The API factory has a separate dependency on the real MINA version (via [`mina-core`](https://mvnrepository.com/artifact/org.apache.directory.api/api-ldap-net-mina/1.0.3)).

**Comment by aikebah** [comment]
approved
