### ISSUE TITLE
Using Individual  Experimental Analyzers

### ISSUE THREAD

**Issue by ralph-wright** [dependency-check/DependencyCheck#5709]
Is there a direct way to individually enable experimental analyzers?   My understanding is that if you use `--enableExperimental` ,  all of the experimental analyzers are enabled.   Each can be turned off using something like, `--disableRubygems`. 

Seems like there should be a way to enable each one, such as `--enableRubygems`.   Am I missing something?

**Comment by aikebah** [comment]
Your analysis is correct. Such an option to enable only a single experimental analyzer is indeed not present. To do that you need to enable experimental analyzers and then disable the ones you don't want with the current codebase.
