### ISSUE TITLE
Vulnerabilities found in npm@9.6.6 which is latest version in strip-ansi

### ISSUE THREAD

**Issue by aggarwalmanuj17** [dependency-check/DependencyCheck#5722]
I have a long list of vulnerabilities after deploying my npm project on the docker container but after changing OS I am left with only one vulnerability related to npm which is strip-ansi.
It is inside the npm package only when I run the npm list command.

I am having different versions of strip-ansi in my dependency tree and the latest version is "7.0.1".
I am attaching the dependency tee image also.
Could anyone help me in resolving this issue?
![Dependency Tree](https://github.com/jeremylong/DependencyCheck/assets/51327845/12954b8d-c4f7-45ad-b755-4d7abf459d02)

**Comment by aikebah** [comment]
@aggarwalmanuj17 You're better off asking such a question to the NPM community. Though I suspect that your project should not even depend on NPM (unless your project is some kind of extension to NPM it would use NPM for build, but not depend on it). NPM knows that the dependency on strip-ansi 6.x cannot be replaced by/upgraded to 7.x nor the other way around (new major, indicating backward-incompatible change), so it puts both strip-ansi 6.0.1 and strip-ansi 7.01 packages in the dependency-tree (the various packages have a range-constraint on their dependency to strip-ansi that prevents using a different major version)
