### ISSUE TITLE
Unable to disable oss dependency check through maven

### ISSUE THREAD

**Issue by pteichner** [dependency-check/DependencyCheck#5728]
**Describe the bug**
When using mvn command line passing in the variable "-DossindexAnalayzerEnabled=false" doesn't not disable the loss check and during the scan oss scanning is still initiated. 

**Version of dependency-check used**
The problem occurs using version 8.2.1 of the maven plugin

**Log file**
None

**To Reproduce**
1. Run mvn from shell using provided parameter

**Expected behavior**
oss should be disabled

**Comment by aikebah** [comment]
If you correct your spelling mistake it should work just fine

"-DossindexAnalyzerEnabled=false" instead of "-DossindexAnal*__a__*yzerEnabled"

**Comment by pteichner** [comment]
> If you correct your spelling mistake it should work just fine
> 
> "-DossindexAnalyzerEnabled=false" instead of "-DossindexAnal*__a__*yzerEnabled"

Thanks, I will double check because I manually typed this bug up on another laptop so didn't copy paste here, but did on my other laptop.

On a side note when running a maven project would you recommend using the jenkins plug in or the maven? I tried executing the tests using the jenkins plug in and it worked fine for a node based project but seems to have completely missed the maven components.

**Comment by aikebah** [comment]
> On a side note when running a maven project would you recommend using the jenkins plug in or the maven? I tried executing the tests using the jenkins plug in and it worked fine for a node based project but seems to have completely missed the maven components.

Most definitely you'd want to use the maven plugin for scanning a maven project. The Jenkins plugin runs the CLI, which only scans file within the project folder structure and does not handle maven dependencies unless you first `mvn dependency:copy-dependencies` to get your dependencies into the project folder structure.
And even if you do, the CLI will have less-reliable CPE detection compared to the maven plugin.

**Comment by pteichner** [comment]
![IMG_20230524_073155.jpg](https://github.com/jeremylong/DependencyCheck/assets/92022180/33a8e853-b8e0-447d-8b09-96923b7c33a5)

![IMG_20230524_072918.jpg](https://github.com/jeremylong/DependencyCheck/assets/92022180/a0c204c5-0708-479c-9adc-7631d4b52214)

**Comment by pteichner** [comment]
Apologies the 2 systems don't mix

**Comment by pteichner** [comment]
Just to add to this - I've also tried passing in ossindexAnalyzerUrl and ossIndexServerId (got the properties out of the BaseDepenecyCheckMojo.java file) 

- Despite the enabled set to false it still attempts to analyze
- It complains about ossindex.sonatype.org as Unknown Host exception (air-gapped env) despite the var being overridden

**Comment by pteichner** [comment]
Okay don't be too mad, but I've missed a \ for one of the new lines it's working fine :D

**Comment by aikebah** [comment]
Glad to hear it works for you now. I was about to try and reproduce by actually running an invocation with the property on the commandline. Up to now I used code-browse on the iPad to double-check the code-flow of the property, which seemed to be fine.

**Comment by pteichner** [comment]
My mistake sorry
