### ISSUE TITLE
java.lang.IllegalArgumentException: Field must have either 

### ISSUE THREAD

**Issue by Pamir** [dependency-check/DependencyCheck#576]
### Reporting Bugs/Errors

23-Sep-2016 12:44:35    java.lang.IllegalArgumentException: Field must have either TokenStream, String, Reader or Number value; got stored,indexed,tokenized<product:>
build   23-Sep-2016 12:44:35        at org.apache.lucene.document.Field.tokenStream(Field.java:555)
build   23-Sep-2016 12:44:35        at org.apache.lucene.index.DocInverterPerField.processFields(DocInverterPerField.java:103)
build   23-Sep-2016 12:44:35        at org.apache.lucene.index.DocFieldProcessor.processDocument(DocFieldProcessor.java:248)
build   23-Sep-2016 12:44:35        at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:253)
build   23-Sep-2016 12:44:35        at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:455)
build   23-Sep-2016 12:44:35        at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1534)
build   23-Sep-2016 12:44:35        at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1204)
build   23-Sep-2016 12:44:35        at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1185)
build   23-Sep-2016 12:44:35        at org.owasp.dependencycheck.data.cpe.CpeMemoryIndex.buildIndex(CpeMemoryIndex.java:214)
build   23-Sep-2016 12:44:35        at org.owasp.dependencycheck.data.cpe.CpeMemoryIndex.open(CpeMemoryIndex.java:119)
build   23-Sep-2016 12:44:35        at org.owasp.dependencycheck.analyzer.CPEAnalyzer.open(CPEAnalyzer.java:159)
build   23-Sep-2016 12:44:35        at org.owasp.dependencycheck.analyzer.CPEAnalyzer.initialize(CPEAnalyzer.java:133)
build   23-Sep-2016 12:44:35        at org.owasp.dependencycheck.Engine.initializeAnalyzer(Engine.java:442)
build   23-Sep-2016 12:44:35        at org.owasp.dependencycheck.maven.MavenEngine.initializeAnalyzer(MavenEngine.java:137)
build   23-Sep-2016 12:44:35        at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:380)
build   23-Sep-2016 12:44:35        at org.owasp.dependencycheck.maven.MavenEngine.analyzeDependencies(MavenEngine.java:95)
build   23-Sep-2016 12:44:35        at org.owasp.dependencycheck.maven.CheckMojo.runCheck(CheckMojo.java:97)
build   23-Sep-2016 12:44:35        at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.execute(BaseDependencyCheckMojo.java:423)
build   23-Sep-2016 12:44:35        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
build   23-Sep-2016 12:44:35        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
build   23-Sep-2016 12:44:35        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
build   23-Sep-2016 12:44:35        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
build   23-Sep-2016 12:44:35        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
build   23-Sep-2016 12:44:35        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
build   23-Sep-2016 12:44:35        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
build   23-Sep-2016 12:44:35        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
build   23-Sep-2016 12:44:35        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:318)
build   23-Sep-2016 12:44:35        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:153)
build   23-Sep-2016 12:44:35        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
build   23-Sep-2016 12:44:35        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
build   23-Sep-2016 12:44:35        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
build   23-Sep-2016 12:44:35        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
build   23-Sep-2016 12:44:35        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
build   23-Sep-2016 12:44:35        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
build   23-Sep-2016 12:44:35        at java.lang.reflect.Method.invoke(Method.java:606)
build   23-Sep-2016 12:44:35        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
build   23-Sep-2016 12:44:35        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
build   23-Sep-2016 12:44:35        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
build   23-Sep-2016 12:44:35        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)
### Reporting False Positives

When reporting a false positive please include:
- The location of the dependency (Maven GAV, URL to download the dependency, etc.)
- The CPE that is believed to be false positive
  - Please report the CPE not the CVE

**Comment by jeremylong** [comment]
Please upgrade to 1.4.3 and delete your existing database (consider using
the purge goal for this).

--jeremy

**Comment by jeremylong** [comment]
@Pamir did upgrading and purging the local database resolve the issue?

**Comment by jeremylong** [comment]
Closing this issue due to lack of response from @Pamir

**Comment by Pamir** [comment]
Hi Jeremy,

Sorry for my late response. Yes it fixes the problem. 

Kind Regards
Pamir
