### ISSUE TITLE
[FP]: jruby-jzlib confused for JRuby itself

### ISSUE THREAD

**Issue by chadlwilson** [dependency-check/DependencyCheck#5762]
### Package URl

pkg:maven/org.jruby/jzlib@1.1.5

### CPE

`cpe:/a:jruby:jruby`

### ODC Integration

{"label"=>"Gradle Plugin"}

### ODC Version

8.2.1

### Description

jruby-jzlib is an independent artifact from jruby itself, versioned independently, and a fork of JCraft's jzlib: https://github.com/jruby/jzlib

**Comment by aikebah** [comment]
approved


@chadlwilson hope to take a look later to review whether we should put a broader suppression in place in a next release for the tool-embedded suppressions, but this will get it out of the way for this lib
