### ISSUE TITLE
[FP]: Apache Sling Commons OSGi linked to incorrect CPE (Apache Sling)

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [dependency-check/DependencyCheck#5774]
### Package URl

pkg:maven/org.apache.sling/org.apache.sling.commons.osgi@2.4.0

### CPE

`cpe:2.3:a:apache:sling:2.4.0:*:*:*:*:*:*:*`

### ODC Integration

{"label"=>"Gradle Plugin"}

### ODC Version

8.2.1

### Description

The Sling Commons OSGi library is a part of the Apache Sling project, but it can be used standalone.
https://github.com/apache/sling-org-apache-sling-commons-osgi

However, it is incorrectly assigned to the parent project CPE, moreover, using the version of the OSGi library. This causes false positive reports.

**Comment by aikebah** [comment]
approved
