### ISSUE TITLE
Create Slack channel for this project

### ISSUE THREAD

**Issue by DinisCruz** [dependency-check/DependencyCheck#578]
it is a nice what to communicate and ask quick questions

**Comment by DinisCruz** [comment]
done https://owasp.slack.com/archives/proj-dependency-check

**Comment by jeremylong** [comment]
Fantastic - hopefully someone with knowledge about dependency-check will actually monitor this and respond to questions. I never set this up as I don't use slack, can't use slack during my work hours, etc.

**Comment by stevespringett** [comment]
I use it all the time for work and I also monitor various OWASP channels in Slack. Keeping track of the DC channel isn't a big deal, but if others on the core team want to contribute to, that would be great.

**Comment by DinisCruz** [comment]
What we can do (like what happened yesterday) is to point the users to open an issue here
