### ISSUE TITLE
Can't get WebhookPublisher to successfully send JSON payload to AWS API Gateway

### ISSUE THREAD

**Issue by jesseadams** [dependency-check/DependencyCheck#5784]
**Describe the bug**
I wanted to inspect the payloads of events that would be sent out to an outbound webhook. I created a simple AWS API gateway that accepts a `POST` with a json payload, logs it, and returns it as well in the response. 

This works great with curl.

```
curl -X POST -H "Content-Type: application/json" -d '{"foo": "bar"}' https://nix213jk8a.execute-api.us-east-2.amazonaws.com
{"foo": "bar"}
```

But when I try to use it with the notification configuration it just fails when trying to send notifications through the API server.

```
2023-06-20 15:35:10,766 ERROR [WebhookPublisher] An error was encountered publishing notification to Outbound Webhookwith HTTP Status : 403 Forbidden Destination: https://nix213jk8a.execute-api.us-east-2.amazonaws.com Response: {"message":"Forbidden"}
```

**Version of dependency-check used**
The problem occurs using version 4.8.0 of the api server.

**Log file**
Recent logs: https://gist.github.com/jesseadams/62889214435dd8c10c4880af91c1cb97

**To Reproduce**
1. Configure an outbound webhook alert using `org.dependencytrack.notification.publisher.WebhookPublisher` with the correct API gateway URL
2. Submit an SBOM to process and wait for it to completely process, thus generating notifications.
3. See lambda executions with the payload in the AWS CloudWatch log console

**Expected behavior**
I would expect to see the payloads showing up in the CloudWatch logs of the lambda, just like when I send manual tests via curl requests.

**Additional context**
I feel like I am just missing something really simple, but the documentation is pretty basic.

https://docs.dependencytrack.org/integrations/notifications/#outbound-webhooks

**Comment by aikebah** [comment]
@jesseadams You're in the wrong github. DependencyTrack is at https://github.com/DependencyTrack/dependency-track
