### ISSUE TITLE
[FP]: Minio.AspNetCore

### ISSUE THREAD

**Issue by echalone** [dependency-check/DependencyCheck#5788]
### Package URl

pkg:nuget/Minio.AspNetCore@5.0.0

### CPE

cpe:2.3:a:minio:minio:5.0.0:*:*:*:*:*:*:*

### ODC Integration

None

### ODC Version

8.3.1

### Description

A false positive for the MinIO project ( https://github.com/minio/minio ) is reported, when in reality it is the Minio.AspNetCore NuGet package ( https://www.nuget.org/packages/Minio.AspNetCore ; https://github.com/appany/Minio.AspNetCore ) which uses the MinIO-DotNet nuget package ( https://www.nuget.org/packages/Minio ; https://github.com/minio/minio-dotnet ). Both of these packages use a completely different version numbering format from the original MinIO project, which is why a bunch of CVEs get reported since the dependency check assumes it's always some version below those with a vulnerability.
Also happens for other versions of Minio.AspNetCore

**Comment by aikebah** [comment]
approved
