### ISSUE TITLE
Way to skip the maven execution on a CI server

### ISSUE THREAD

**Issue by DinisCruz** [dependency-check/DependencyCheck#579]
In a maven build is there a way to explicitly skip the execution of this check

Here is the relevant pom.xml config

```
            <plugin>
                <groupId>org.owasp</groupId>
                <artifactId>dependency-check-maven</artifactId>
                <version>1.4.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

I'm using `mvn install -DskipTests` to trigger the build

**Comment by mprins** [comment]
you can just use `skip` or `-Ddependency-check.skip=true` see: http://jeremylong.github.io/DependencyCheck/dependency-check-maven/check-mojo.html#skip

**Comment by jeremylong** [comment]
Thanks @mprins! beat me to providing this answer.
