### ISSUE TITLE
Move repo to OWASP organization

### ISSUE THREAD

**Issue by DinisCruz** [dependency-check/DependencyCheck#580]
Given the popularity and importance of this project, it will be good to move it to https://github.com/owasp/DependencyCheck/

Let me know if you need help with that

**Comment by jeremylong** [comment]
When OWASP figures out how to not clutter their repo with dead projects I'll consider this. There is currently no OWASP badges for repos, in github itself no way to determine the flagship projects from dead projects, etc.

I'll help and contribute as I can to solve some of these issues; but at the moment I see no value in moving the repo.

**Comment by DinisCruz** [comment]
fair enough
