### ISSUE TITLE
Cannot auto-detect encoding, not enough chars

### ISSUE THREAD

**Issue by baderbuddy** [dependency-check/DependencyCheck#581]
### Reporting Bugs/Errors

When reporting errors, 99% of the time log file output is required. Please post the log file as a [gist](https://gist.github.com/) and provide a link in the new issue.

[WARN] Exception extracting archive 'cb-never-called-1.0.1.tgz'.
[WARN] An unexpected error occurred during analysis of 'C:\Users<username>\AppData\Local\Temp\dctemp\check8105387734635396870tmp\20\package\test\fixtures\config\package.json'
[INFO] Creating the CPE Index
[INFO] CPE Index Created (3014 ms)
[INFO] Analysis Complete (18771 ms)
[ERROR] Cannot auto-detect encoding, not enough chars

when scanning npm-3.10.8.tgz, it appears that file is 0 bytes https://github.com/npm/npm/blob/master/test/fixtures/config/package.json could the dependency check not throw an error on files like this?
### Reporting False Positives

When reporting a false positive please include:
- The location of the dependency (Maven GAV, URL to download the dependency, etc.)
- The CPE that is believed to be false positive
  - Please report the CPE not the CVE
#### Example

False positive on library foo.jar - reported as cpe:/a:apache:tomcat:7.0

``` xml
<dependency>
   <groupId>org.sample</groupId>
   <artifactId>foo</artifactId>
   <version>1.0</version>
</dependency>
```

**Comment by baderbuddy** [comment]
I'm using dependency check 1.4.3, it looks like older versions might not have had this problem.

**Comment by jeremylong** [comment]
@baderbuddy versions older then 1.4.0 hide a lot of exceptions that we have been cleaning up. Sorry for the inconvenience.  Can you tell me what OS and JDK you are using?  Also, just to make sure I'm testing with the exact same tarball - do you have a link I could download npm-3.10.8.tgz?

**Comment by baderbuddy** [comment]
Windows 7, JDK 1.8.0_51, [npm 3.10.8](https://github.com/npm/npm/archive/v3.10.8.tar.gz) Thank you for looking into this.

**Comment by jeremylong** [comment]
This is not an issue with dependency-check - but rather the tar ball itself. 7zip runs into the exact same issue with the file.

![image](https://cloud.githubusercontent.com/assets/862914/19212322/b5d33ece-8d1c-11e6-9e57-a37da34590ec.png)
