### ISSUE TITLE
Defined artefact version in the hints file is ignored

### ISSUE THREAD

**Issue by bondarei** [dependency-check/DependencyCheck#5812]
**Describe the bug**
A defined version 3.4.11 for the avcodec-vsdk-57.dll in the hints file doesn't appear in the report as part of a cpe. The report contains only
[cpe:2.3:a:ffmpeg:ffmpeg:57:*:*:*:*:*:*:*] (Confidence:Highest) 
[cpe:2.3:a:ffmpeg-sdk_project:ffmpeg-sdk:57:*:*:*:*:*:*:*](Confidence:Highest) 

**Version of dependency-check used**
The problem occurs using dependency-check version: 8.0.1 of the cli.

**To Reproduce**
Execute scan with cli tool of the attached assembly with the attached hints file and verify the report.

**Expected behavior**
expected something like this:
[cpe:2.3:a:ffmpeg:ffmpeg:3.4.11:*:*:*:*:*:*:*](Confidence:Highest) 
[cpe:2.3:a:ffmpeg:ffmpeg:57:*:*:*:*:*:*:*](Confidence:Highest)

**Additional context**
[hints.zip](https://github.com/jeremylong/DependencyCheck/files/11957852/hints.zip)
[avcodec-vsdk-57.zip](https://github.com/jeremylong/DependencyCheck/files/11957862/avcodec-vsdk-57.zip)

**Comment by bondarei** [comment]
Similar behavior with dotnet-hosting-6.0.15-win.exe which can be downloaded here: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-aspnetcore-6.0.15-windows-hosting-bundle-installer 

Version of dependency-check used
The problem occurs using dependency-check version: 8.0.1 of the cli.

Steps to reproduce the behavior:
Execute scan with cli tool of the attached assembly with the attached hints file and verify the report.

Expected:
cpe:2.3:a:microsoft:.net:6.0.15
[hints.zip](https://github.com/jeremylong/DependencyCheck/files/11980583/hints.zip)

**Comment by aikebah** [comment]
@bondarei no need for further examples... root-cause is already identified. ODC will fail to honour any version info from hints if there is only one version identified in the initial evidence gathering.

**Comment by bondarei** [comment]
@aikebah Thanks for your fast response! In the second example, the evidence type="product" source="hint analyzer" name="product" value=".net" confidence="HIGHEST" is also ignored, the report contains only cpe:2.3:a:microsoft:.**net_framework**:6.0.15 but I would expect also follow cpe:2.3🅰️microsoft:**.net**:6.0.15

**Comment by aikebah** [comment]
@bondarei That second example is a different issue, with a yet unknown, but different cause. I've opened a secondary ticket for that, so that we can resolve the issues individually.

**Comment by jeremylong** [comment]
This issue appears to have been closed with #5818.
