### ISSUE TITLE
How to increase java heap size?

### ISSUE THREAD

**Issue by Tahetuul** [dependency-check/DependencyCheck#5820]
Hello! I have JDK 20, Dependency-check 8.3.1 (Command Line on Windows 10). When I try to scan my project (it's big), it ends with an error:  java.lang.OutOfMemoryError: Java heap space. 

[Log with error.txt](https://github.com/jeremylong/DependencyCheck/files/12016515/Log.with.error.txt)

How to increase java heap size? I tried to find a solution on the Internet, but unfortunately I didnt succeed.

**Comment by aikebah** [comment]
setting environment variable `JAVA_OPTS` to have at least an appropriate -Xmx should do the trick e.g. set `JAVA_OPTS` to `-Xmx16g` for a max heap of 16 GiB for the dependency check JVM

If you run the CLI from a command shell make sure to either set it inside that shell session or use a command shell that was started after setting the environment variable. Existing open command shells do not get the environment variables that get set after they were opened unless you set them from within that command shell.

Also be aware that many .bat/.cmd scripts of java based applications share that same JAVA_OPTS environment value to set additional parameters for the jvm invocation. 

Some use it just to add onto arguments they set (like in dependency-check.bat), others (e.g. Wildfly's standalone.conf.bat) may use it as an override to their defaults, which is to say that in case JAVA_OPTS is set (some of) their own default JVM parameters are skipped.

**Comment by aikebah** [comment]
Having said that... you may also be running into #5671 with you project, which would mean it will only work with the next release of ODC (the fix is merged, but there has not been any new release yet)
