### ISSUE TITLE
Error running with maven 2.2.1

### ISSUE THREAD

**Issue by avaneesh-c** [dependency-check/DependencyCheck#583]
Trying to use the dependency-check-maven plugin with a maven version of 2.2.1 and seeing the following error while running it. Is there anything I need to do to get it resolved. [Gist](https://gist.github.com/achittin/885778d71761cc4058587af020ac8c3a)

**Comment by doergn** [comment]
Had the same issue here with Maven 3.0.5. After updating to latest Maven (3.3.9) it works fine.
So seems like you need at least 3.1 (see https://github.com/jeremylong/DependencyCheck/issues/584)
