### ISSUE TITLE
OWASP Dependency Check 8.3.1 fails with exit code 13 on azure pipeline task

### ISSUE THREAD

**Issue by akash-onedealerlane** [dependency-check/DependencyCheck#5837]
I pass the Dependency file of c# it works sometimes. some time fails.
if I run 10 times pipeline 3 times it fails.
Does anyone have any suggestions for this BUG?
task: dependency-check-build-task@6
displayName: “OWASP Scan”
inputs:
projectName: “API”
scanPath: “src/**/DependencyInjection.cs”
format: “XML, HTML”
dependencyCheckVersion: 8.2.1
retryCountOnTaskFailure: 5
continueOnError: true
![image](https://github.com/jeremylong/DependencyCheck/assets/129958569/32409469-f726-46ba-aed0-111b5f910992)
![image](https://github.com/jeremylong/DependencyCheck/assets/129958569/0690b740-44d3-4331-bde8-dd33ce83490f)

**Comment by aikebah** [comment]
You give too little detail of your failing build. More of your log would be needed to see which item breaks (there is a partial stacktrace in the log screenshot)

**Comment by akash-onedealerlane** [comment]
![image](https://github.com/jeremylong/DependencyCheck/assets/129958569/ec49b754-88ac-4802-b48c-c3ce20ea15e6)
please check this look like not connected to server of owasp

**Comment by aikebah** [comment]
It's not the server of OWASP, but of NIST NVD. You should check your network connectivity in collaboration with your Azure admins.

See also http://jeremylong.github.io/DependencyCheck/data/index.html

**Comment by aikebah** [comment]
Note: as it is intermittent failure you could be running into rate-limits (typically http 403 or 429) or the instability of the NVD website (typically http 503).
Having a mirror of NVD in your CI environment, or having a persistent datalocation for DC in your environment that is mounted in each build pipeline can help stableizing the environment.

**Comment by aikebah** [comment]
In my company's CI environment we have a mirror solution that is updated every two hours (using the nist datamirror linked on the documentation). Every now and then it fails on a http 503, but on the next run it typically mirrors fine again.
As the builds use the local mirror they always run fine (but may sometimes lag behind by a small amount of time)
