### ISSUE TITLE
Suppression path url not working Azure DevOps

### ISSUE THREAD

**Issue by jegrz** [dependency-check/DependencyCheck#5852]
Hi 
As written in the documentation, you can specify a suppression file in different ways "The argument can be a local file path, a URL to a suppression file, or even a reference to a file on the class path"
I need it to point to an url, but it always takes it from the local base directory, i.e.:

     task: dependency-check-build-task@6
     inputs:
      ..
         suppressionPath: 'https://example.com/suppression.xml'

That results in 

`dependency-check.sh --project myProject --out /home/vsts/work/1/TestResults/dependency-check --scan /home/vsts/work/1/s/target/myProject.jar --format HTML --format JUNIT --failOnCVSS 8 --suppression /home/vsts/work/1/s/https://example.com/suppression.xml`

while /home/vsts/work/1/s/https://example.com/suppression.xml is obviously not where the file is. What am I missing?

**Comment by aikebah** [comment]
The part you're overlooking is that the Azure DevOps dependency-check-task is a wrapper around the CLI. 

Apparently, from the symptoms you see, the authors have hardcoded it to prepend any suppression-path with the Azure DevOps workspace folder before handing it over to the CLI.

So it would be something to raise as a feature request (support for URL based suppression paths) to the dependency-check-task authors.

**Comment by aikebah** [comment]
As a work-around, similar to what the creator of https://github.com/dependency-check/azuredevops/issues/98 did for their issue you might be able to abuse the additionalArguments for the time being to get a `--suppression` argument that correctly uses your URL.

**Comment by jegrz** [comment]
@aikebah thanks for the hint. That should work for me.
