### ISSUE TITLE
How to Download NVD data manually and run dependency check with that data

### ISSUE THREAD

**Issue by sivaswami** [dependency-check/DependencyCheck#586]
Hi,
Its a great tool !!!
But I have limitations to connect to external sites automatically. I can download NVD data once a week. Is there any way, I can use a custom NVD source to scan for vulnerabilities ?

**Comment by stevespringett** [comment]
Check out 
https://jeremylong.github.io/DependencyCheck/data/mirrornvd.html

**Comment by sivaswami** [comment]
Thank you very much for the reply. I tried and I am getting the below message. Any suggestions.
[ERROR] No documents exist
Unable to continue dependency-check analysis.
[ERROR] One or more fatal errors occured
[ERROR] No documents exist

**Comment by sivaswami** [comment]
Thank you very much for the reply. I had some issues downloading. I changed my JDK and download is working fine for NVD. Still trying out with sample scan ...
