### ISSUE TITLE
New approach to updating DependencyCheck database

### ISSUE THREAD

**Issue by hunchoB** [dependency-check/DependencyCheck#5869]
Hello!
The NIST website contains information about retiring all legacy data feeds (will be only API) to December 15th, 2023.

Will it affect the process of regular updating DependencyCheck database? API will be have rate limits, maximum size of downloading records in one request will be 2000. 

Is this fact taken into account in the development plans for DependencyCheck project?

**Comment by rmontag-ap** [comment]
Here is a comment from Jeremy Long regarding this: https://github.com/jeremylong/DependencyCheck/issues/4732#issuecomment-1637861929
