### ISSUE TITLE
SimpleIcons - Icon Request

### ISSUE THREAD

**Issue by alex-hedley** [dependency-check/DependencyCheck#5870]
I've raised an Icon Request on [SimpleIcons](https://simpleicons.org) to easily allow for [Shields.io](https://shields.io) badges to be created

[Icon] Dependency-Check #9246
https://github.com/simple-icons/simple-icons/issues/9246

i.e. 

`[![Dependency-Check](https://img.shields.io/badge/DependencyCheck-f78d0a.svg?style=for-the-badge&logo=dependencycheck&logoColor=white)](https://owasp.org/www-project-dependency-check/)`

[![Dependency-Check](https://img.shields.io/badge/DependencyCheck-f78d0a.svg?style=for-the-badge&logo=dependencycheck&logoColor=white)](https://owasp.org/www-project-dependency-check/)

You could link to the artifact or deployed report via a badge.

**Comment by jeremylong** [comment]
I'm not sure where we would use a badge like this - being the core project. Maybe there would be a use in some of the integrations like the github action, ADO, or sonar plugin?

**Comment by alex-hedley** [comment]
I was thinking more for the user of the tool, they add it to their repo as a way to link to the artefact of the run.
