### ISSUE TITLE
Dependencies are now being listed as hotspots in SonarQube Project

### ISSUE THREAD

**Issue by glalfstad-fadv** [dependency-check/DependencyCheck#5895]
**Environment:**
Pipeline using Azure DevOps
SonarQube Enterprise Edition Version 8.9.9 (build 56886)
Gradle 8.1
SonarQube Gralde Plugin 3.5.0.2730

**Problem**
We have an Azure Pipeline that builds using Gradle and the OWASP Dependency Report is published to SonarQube (visible under More → HTML Dependency-Check) but require the issues to be listed under Security Hotspots. Under “Security Hotspots” states “There are no Security Hotspots to review.”

azure-pipelines.yml

  - task: SonarQubePrepare@5
    inputs:
      SonarQube: 'SonarQube [our sonarqube URL]'
      scannerMode: 'CLI'
      configMode: 'file'
      extraProperties: |
        sonar.dependencyCheck.reportPath=dependency-check-report.html
        sonar.dependencyCheck.htmlReportPath=$(Agent.TempDirectory)/dependency-scan-results/CA/dependency-check-report.html
        sonar.dependencyCheck.jsonReportPath=$(Agent.TempDirectory)/dependency-scan-results/CA/dependency-check-report.json
        sonar.dependencyCheck.xmlReportPath=$(Agent.TempDirectory)/dependency-scan-results/CA/dependency-check-report.xml
        sonar.dependencyCheck.severity.blocker=9.0
        sonar.dependencyCheck.severity.critical=7.0
        sonar.dependencyCheck.severity.major=4.0
        sonar.dependencyCheck.summarize=true
        sonar.dependencyCheck.securityHotspot=true
        sonar.verbose=true

  - task: dependency-check-build-task@6
    inputs:
      projectName: 'XtdForce CA'
      scanPath: '$(system.defaultworkingdirectory)/ca'
      format: 'ALL'
      reportsDirectory: '$(Agent.TempDirectory)/dependency-scan-results/CA'
      additionalArguments: '--disableAssembly --disableNodeJS --disablePnpmAudit --disableNodeAudit --disableRetireJS --format HTML --format JSON --format XML'

**What we have tried:**
If in the "dependency-check-build-task@6" task we down grade to version 7.0.0 (dependencyCheckVersion: '7.0.0') then we get all the hotspots listed as lows. Is the issue that the SonarQube version is 8.0?

![image](https://github.com/jeremylong/DependencyCheck/assets/46571235/c96c0a3e-cbfd-48d8-ae75-2aa796e1dab3)

**Comment by aikebah** [comment]
@GAlfstad Dependency report issue registration within SonarQube is the responsibility of the SonarQube plugin, which is separate from this project and can be found at https://github.com/dependency-check/dependency-check-sonar-plugin

You likely suffer from https://github.com/dependency-check/dependency-check-sonar-plugin/issues/748

**Comment by jeremylong** [comment]
The issue is with the dependency-check-sonar-plugin - not the core project.
