### ISSUE TITLE
[FP]: core.wcm.components.core wrongfully linked to adobe download_manager

### ISSUE THREAD

**Issue by fahol-coop** [dependency-check/DependencyCheck#5904]
### Package URl

pkg:maven/com.adobe.cq/core.wcm.components.core@2.23.2

### CPE

cpe:2.3:a:adobe:download_manager:2.23.2:*:*:*:*:*:*:*

### ODC Integration

{"label"=>"Maven Plugin"}

### ODC Version

8.4.0

**Comment by aikebah** [comment]
approved
