### ISSUE TITLE
[Question] Deprecation of the NIST vulnerabilities "legacy data feed"

### ISSUE THREAD

**Issue by j3rem1e** [dependency-check/DependencyCheck#5914]
Hello,

NIST will deprecate the support of the json data feed if I understood correctly.

How will this affect this project ? will it be alwais possible to mirrors sources to use in offline mode ? my production environment doesn't have access to internet.

Thanks!

**Comment by jeremylong** [comment]
https://github.com/jeremylong/DependencyCheck/issues/4732
