### ISSUE TITLE
Missing hosted suppression and empty Retire JS reported inccorectly

### ISSUE THREAD

**Issue by pteichner** [dependency-check/DependencyCheck#5946]
**Describe the bug**
Using the CLI with the self-hosted JS file and self-hosted suppression files configured the analyzer gives an incorrect warning of those components empty or missing.

It feels the analyzer takes too long as well, last run was 591 seconds.

**Version of dependency-check used**
8.2.1 and retested on 8.4.0 with the same result

**Log file**
Nothing to mention

**To Reproduce**
1. configure the config file
2. checkout a node project
3. Run analysis using CLI

**Expected behavior**
Considering the config file has both of these values configured it shouldn't be reporting them as missing. Also the analyzer should take a lot less time

**Additional context**

**Comment by aikebah** [comment]
Sounds to me like there are timeouts attempting to download your self-hosted resources. Enable debug logging and closely verify your log file for issues.

**Comment by pteichner** [comment]
I have and the parameters on the cli are passed in - according to the log files as well. However the log file still gives WARN for both the suppression and the retire JS files.
