### ISSUE TITLE
[FP]: mysql lib on npm, not mysql server.

### ISSUE THREAD

**Issue by dennys** [dependency-check/DependencyCheck#5948]
### Package URl

pkg:npm/mysql

### CPE

cpe:2.3:a:mysql:mysql:2.18.1:*:*:*:*:*:*:* cpe:2.3:a:mysql_project:mysql:2.18.1:*:*:*:*:*:*:*	

### ODC Integration

{"label"=>"Docker"}

### ODC Version

8.0

### Description

I use dependency-check to scan my node.js, this 'mysql' is a library of nodejs, not MySQL database server.
Any suggestion to fix it?

I use this docker: https://hub.docker.com/r/owasp/dependency-check

This is my script.
```
/usr/share/dependency-check/bin/dependency-check.sh --scan "./" --format ALL --project "App1" --failOnCVSS 0 
```

**Comment by aikebah** [comment]
approved
