### ISSUE TITLE
[FP]: False positive on io.asyncer:r2dbc-mysql

### ISSUE THREAD

**Issue by jchrys** [dependency-check/DependencyCheck#5953]
### Package URl

`pkg:maven/io.asyncer/r2dbc-mysql@1.0.3`

### CPE

`cpe:2.3:a:mysql:mysql:1.0.3:*:*:*:*:*:*:*)`

### ODC Integration

{"label"=>"Maven Plugin"}

### ODC Version

8.4.0

### Description

it seems false positive where io.asyncer:r2dbc-mysql:* is being mistaken for for mysql:mysql:*.

related issue: https://github.com/asyncer-io/r2dbc-mysql/issues/148

**Comment by aikebah** [comment]
approved
