### ISSUE TITLE
[FP]: netty-incubator-codec-native-quic detected as quic

### ISSUE THREAD

**Issue by chadlwilson** [dependency-check/DependencyCheck#5956]
### Package URl

pkg:maven/io.netty.incubator/netty-incubator-codec-native-quic@0.0.50.Final

### CPE

`cpe:2.3:a:quic_project:quic:0.0.50:*:*:*:*:*:*:*`

### ODC Integration

{"label"=>"Gradle Plugin"}

### ODC Version

8.4.0

### Description

The Netty codec for quic is versioned independently and a different project to quic itself - it actually uses https://github.com/cloudflare/quiche which is a separate implementation with its own versioning.

Similar to #5913 and #5879

**Comment by aikebah** [comment]
approved
