### ISSUE TITLE
[FP]: netty-incubator-codec-native-quic detected as chromium_project

### ISSUE THREAD

**Issue by chadlwilson** [dependency-check/DependencyCheck#5968]
### Package URl

pkg:maven/io.netty.incubator/netty-incubator-codec-native-quic@0.0.50.Final

### CPE

`cpe:2.3:a:chromium_project:chromium:0.0.50:*:*:*:*:*:*:*`

### ODC Integration

{"label"=>"Gradle Plugin"}

### ODC Version

8.4.0

### Description

Similar to https://github.com/jeremylong/DependencyCheck/issues/5956 and #5967 - really not sure how this is getting so confused.

**Comment by aikebah** [comment]
approved
