### ISSUE TITLE
odc.update.lock blocks builds

### ISSUE THREAD

**Issue by srcimon** [dependency-check/DependencyCheck#5975]
We use the Dependency Check with option `<autoUpdate>false</autoUpdate>` in all of our builds. The database is updated with a central job. We did this, because we experiences some issues with canceld builds in the past.

But it seems that the plugin creates a `odc.update.lock` even when update is turned off via `<autoUpdate>false</autoUpdate>`. If a build using the plugin is canceld in the "right" moment the `odc.update.lock` doesn't get deleted an all build using that database are blocked.

```
11:48:13 [INFO] Lock file found `/xyz/.m2/repository/org/owasp/dependency-check-utils/8.2.1/../../dependency-check-data/7.0/odc.update.lock`
11:48:13 [INFO] Existing update in progress; waiting for update to complete
```

Any ideas why the lock file is created even with `<autoUpdate>false</autoUpdate>`?

**Comment by srcimon** [comment]
So it turned out that we misconfigured the plugin. We ran the dependency check in every sib module of our projects. That cost a lot of time and made the described issue much more lilely to appear.

**Comment by jeremylong** [comment]
So this is solved and can be closed?

**Comment by srcimon** [comment]
Yes it did. Sorry, couldn't close the issue with the github app then.
