### ISSUE TITLE
HTML Report Filesize

### ISSUE THREAD

**Issue by creasoft-dag** [dependency-check/DependencyCheck#5977]
Hello,

ist it possible to filter all the "non-vulnerable" dependencies from the HTML report?
The dependency check report of my node project has 0 vulnerabilities and 107 MB.
A lot of "notvulnerable" tr elements.
```
<tr class="notvulnerable">
   <td data-sort-value="@ANT-DESIGN-ICONS-NPM-4.8.1-827069ACB9-ABD3603EA9.ZIP: AIMOUTLINED.JS">
      <a href="#l14_6bdce89c8080ad77ecee989e8949e4eeec04a8ea">@ant-design-icons-npm-4.8.1-827069acb9-abd3603ea9.zip: AimOutlined.js</a>
   </td>
   <td data-sort-value=""></td>
   <td data-sort-value=""></td>
   <td data-sort-value="-10">&nbsp;</td>
   <td>0</td><td data-sort-value="0"></td>
   <td>0</td>
</tr>
```

Can't find a parameter for the dependency check cli tool to filter these.

Thanks in advance

**Comment by jeremylong** [comment]
You might try `--retirejsFilterNonVulnerable`.
