### ISSUE TITLE
when 8.4.1 will be released?

### ISSUE THREAD

**Issue by ZheSun88** [dependency-check/DependencyCheck#5995]
Hi, we are waiting for [a fix](https://github.com/jeremylong/DependencyCheck/pull/5927) which has been labelled 8.4.1 as milestone. 
do we have an estimation on when we can get it?

**Comment by jeremylong** [comment]
Goal is this week - I've had some things come up that have taken a bit more of my time then expected.

**Comment by ZheSun88** [comment]
great.. thanks.. now i can close this ticket.. :-)
