### ISSUE TITLE
dependency-check for python: requirements.txt not analyzed

### ISSUE THREAD

**Issue by ilseva** [dependency-check/DependencyCheck#5999]
I try to use the `--enableExperimental` flag to analyze the dependencies of a python project but it does not report any vulnerabilities.
If I create a venv on the source folder and install the dependencies into using the requirements.txt, the dependency-check discovers some vulnerabilites.
Why?
Thanks for you support.

**Comment by rs38** [comment]
does this help?
https://github.com/jeremylong/DependencyCheck/pull/2526

**Comment by ilseva** [comment]
yes, but is it already merged?
I'm using the 8.4.0.

**Comment by aikebah** [comment]
Yes it's merged, but I suspect @rs38 was aiming at that you likely suffer from the clear restriction mentioned in the ticket

> Does not detect transitive dependencies.

**Comment by ilseva** [comment]
Thanks @aikebah, I missed the comments related to transitive dependencies.
