### ISSUE TITLE
Graceful recovery from UpdateException due to IOException

### ISSUE THREAD

**Issue by stevespringett** [dependency-check/DependencyCheck#6]
There should be a way to recover from a source website (such as NIST) being down or the content being unavailable. At the time of this writing, http://static.nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-modified.xml returns a 503, so DependencyCheck fails. However, I think it would be good to attempt to use cached information (even if its not up to date) in an attempt to gracefully fail from this scenario. I would not want a build machine running a DependencyCheck job failing because of this.

Perhaps DatabaseUpdater.java:134 should be changed to not throw an UpdateException, but rather some other type of exception which, if DependencyCheck could recover from, only display a warning upon a failure and perhaps exit with a specific exit code.

**Comment by jeremylong** [comment]
I believe this is fixed. Even throwing the UpdateException, see line 250 in the Engine, you can see that we only log the message - but the analysis continues. I know I did make some other changes during the NVD outage that also helped address the issue. Additionally, the logging level used to log the error near line 250 in the engine has been changed from severe to warning.

Overall, I think the "logging" needs to be reworked throughout the application.
