### ISSUE TITLE
Jenkins plugin - golang dependency

### ISSUE THREAD

**Issue by reynaldiwong** [dependency-check/DependencyCheck#6007]
how do i scan for golang dependency on jenkins?

**Comment by aikebah** [comment]
Jenkins plugin (https://plugins.jenkins.io/dependency-check-jenkins-plugin/) has its own github project and uses JIRA for issue management. Its inner workings for performing a scan use the CLI, so the [CLI Documentation](http://jeremylong.github.io/DependencyCheck/dependency-check-cli/index.html) might be helpful in finding out what arguments to try and feed into the Jenkins plugin.
