### ISSUE TITLE
Possible to alter the html that's generated?

### ISSUE THREAD

**Issue by spyhunter99** [dependency-check/DependencyCheck#601]
I'd may open a PR for this. Essentially, I wrote a site plugin for gradle and part of what it does is scan through common reports looking for summary information, like the total number of warnings from checkstyle, etc. The summary info is rolled up into the generated website. I'm attempting to do the same for the dependency checker but the html is not well suited towards parsing or pulling out this data. Is there a hook for this?

Looking at the xml, it doesn't looks like there is a summary or anything else along those lines to quickly locate. Perhaps I'm missing something?

**Comment by jeremylong** [comment]
No the XML does not have a summary, you would have to parse the XML and create your own summary.  Your PR was merged and will be included in the next release (hopefully within the week).

**Comment by spyhunter99** [comment]
Need to reopen this. although it was merged, the change did not appear to be in 1.4.4

**Comment by jeremylong** [comment]
@spyhunter99 sorry about that - not sure how that got removed. I added the span you wanted back in; however, I did change the name of the span from volnCount to vulnerableCount.

**Comment by spyhunter99** [comment]
probably just a bad merge. no worries
