### ISSUE TITLE
Supported CVE/CPE APIs

### ISSUE THREAD

**Issue by dietzsch** [dependency-check/DependencyCheck#6025]
On November 3rd 2022 NVD had accounced that they release a 2.0 version of their APIs, maintain 1.0 and 2.0 for one year in parallel and then shutdown the 1.0 API. At the moment I see in the documentation of Dependency Check that still the 1.0 API is used by default. 
Does the OWASP Dependency Check Plugin also support the new 2.0 version?

**Comment by jeremylong** [comment]
Thank you for spending 1 minute actually searching the issues. https://github.com/jeremylong/DependencyCheck/issues/4732

**Comment by dietzsch** [comment]
sorry, I haven't seen this issue and also my search had not found it. Anyway, thank you for the link to the correct issue!
