### ISSUE TITLE
Exception occurred initializing RetireJS Analyzer when using gradle plugin

### ISSUE THREAD

**Issue by anabright** [dependency-check/DependencyCheck#6028]
**Describe the bug**
I get error "Exception occurred initializing RetireJS Analyzer" when running `./gradlew dependencyCheckAnalyze`

**Version of dependency-check used**
`latest.release` version of the Gradle plugin which at the time of writing is `8.4.2`

**Log file**
```
./gradlew dependencyCheckAnalyze 

> Task :dependencyCheckAnalyze
Verifying dependencies for project switchboard
Checking for updates and analyzing dependencies for vulnerabilities
Exception occurred initializing RetireJS Analyzer.

Region [NODEAUDIT] : Not alive and dispose was called, filename: NODEAUDIT
Region [CENTRAL] : Not alive and dispose was called, filename: CENTRAL
Region [POM] : Not alive and dispose was called, filename: POM
```

**To Reproduce**
Run `./gradlew dependencyCheckAnalyze`

**Expected behavior**
It should run the dependency check

**Additional context**
My build.gradle.kts file:
```
plugins {
	val kotlinVersion = "1.9.10"
	id("org.springframework.boot") version "3.1.5"
	id("io.spring.dependency-management") version "1.1.3"
	id("org.owasp.dependencycheck") version "latest.release"
	kotlin("jvm") version kotlinVersion
	kotlin("plugin.spring") version kotlinVersion
}

repositories {
	mavenCentral()
	maven {
		setUrl("https://jitpack.io")
	}
}

dependencies {
	...
}

kotlin {
	jvmToolchain(17)
}

dependencyCheck {
    failBuildOnCVSS = 4f
    failOnError = true
    suppressionFile = "config/dependency-check-suppressions.xml"
	analyzers.assemblyEnabled = false
}
```

**Comment by TheMorganHub** [comment]
Same error here but with Maven.

**Comment by gigamac** [comment]
same here in node pipeline -  we are using github action from docker base image:
`owasp/dependency-check-action`

**Comment by aurelien-baudin** [comment]
I just enter a new issue on that subject on the [Retire.js repo](https://github.com/RetireJS/retire.js): https://github.com/RetireJS/retire.js/issues/423

I think the last commit on this project is missing an `info`property

**Comment by RubenGonz2** [comment]
Same problem here. I'm just starting with this plugin.

Is there any workaround to do this plugin works in an Android project?

**Comment by RikuXan** [comment]
You can utilize the retireJsUrl configuration property to set the download URL to the last working commit, should be [https://raw.githubusercontent.com/RetireJS/retire.js/0fe12bb575eda270536dc0ce47fca0dd17b6ab33/repository/jsrepository.json](https://raw.githubusercontent.com/RetireJS/retire.js/0fe12bb575eda270536dc0ce47fca0dd17b6ab33/repository/jsrepository.json)

**Comment by RubenGonz2** [comment]
Thank you @RikuXan , you put me on the right direction. I just disabled the retirejs feature with 

```
analyzers.retirejs.enabled = false
```
as we're not using JS libraries.

**Comment by veselov** [comment]
Offending file: [jsrepository.json](https://github.com/jeremylong/DependencyCheck/files/13219291/jsrepository.json)
URL https://raw.githubusercontent.com/Retirejs/retire.js/master/repository/jsrepository.json

A few notes, with respect, - debugging this was a bit too complicated.
Only using debug output it became possible to look at the contents. The error is logged with the file name that is removed after execution completes, so it can't even be investigated for content.
The URL where it's downloaded from is also only seen with debugging output.
Sifting through the debugging output can be quite onerous.

This isn't the first time this has happened, AFAIR.
I think it'd be reasonable to handle this as a WARNING, and ignore the offending entry. 
The workaround would be to use a direct RetireJS commit URL, which means projects have to be reconfigured to do that until this is fixed by RetireJS, which requires monitoring when they have actually done it, then going through all active branches and removing the crutch.

Thank you.

**Comment by thisjustin816** [comment]
> You can utilize the retireJsUrl configuration property to set the download URL to the last working commit, should be https://raw.githubusercontent.com/RetireJS/retire.js/0fe12bb575eda270536dc0ce47fca0dd17b6ab33/repository/jsrepository.json

I tried adding `--retireJsUrl https://raw.githubusercontent.com/RetireJS/retire.js/0fe12bb575eda270536dc0ce47fca0dd17b6ab33/repository/jsrepository.json` 
 and still getting this same failure.

I'm using the Azure Pipelines task.

**Comment by veselov** [comment]
> > You can utilize the retireJsUrl configuration property to set the download URL to the last working commit, should be https://raw.githubusercontent.com/RetireJS/retire.js/0fe12bb575eda270536dc0ce47fca0dd17b6ab33/repository/jsrepository.json
> 
> I tried adding `--retireJsUrl https://raw.githubusercontent.com/RetireJS/retire.js/0fe12bb575eda270536dc0ce47fca0dd17b6ab33/repository/jsrepository.json` and still getting this same failure.
> 
> I'm using the Azure Pipelines task.

I don't know whether these CLI options match Maven plugin option names, but you need to ask the plugin to force update the JSON. It should be something like `--retireJsForceUpdate` for you.

**Comment by ddjonline** [comment]
FYI I've been able to use the following to get past the error today using the maven CLI (have to both force the update and override the url to use the previous version of the RetireJs jsrepository.json before the latest commit from earlier today)

`mvn  -DskipTests org.owasp:dependency-check-maven:check -DfailBuildOnCVSS=8.5 -DretireJsForceUpdate=true -DretireJsUrl=https://raw.githubusercontent.com/RetireJS/retire.js/0fe12bb575eda270536dc0ce47fca0dd17b6ab33/repository/jsrepository.json`

**Comment by thisjustin816** [comment]
> > > You can utilize the retireJsUrl configuration property to set the download URL to the last working commit, should be https://raw.githubusercontent.com/RetireJS/retire.js/0fe12bb575eda270536dc0ce47fca0dd17b6ab33/repository/jsrepository.json
> > 
> > 
> > I tried adding `--retireJsUrl https://raw.githubusercontent.com/RetireJS/retire.js/0fe12bb575eda270536dc0ce47fca0dd17b6ab33/repository/jsrepository.json` and still getting this same failure.
> > I'm using the Azure Pipelines task.
> 
> I don't know whether these CLI options match Maven plugin option names, but you need to ask the plugin to force update the JSON. It should be something like `--retireJsForceUpdate` for you.

Same result adding the force update argument

**Comment by thisjustin816** [comment]
> > > > You can utilize the retireJsUrl configuration property to set the download URL to the last working commit, should be https://raw.githubusercontent.com/RetireJS/retire.js/0fe12bb575eda270536dc0ce47fca0dd17b6ab33/repository/jsrepository.json
> > > 
> > > 
> > > I tried adding `--retireJsUrl https://raw.githubusercontent.com/RetireJS/retire.js/0fe12bb575eda270536dc0ce47fca0dd17b6ab33/repository/jsrepository.json` and still getting this same failure.
> > > I'm using the Azure Pipelines task.
> > 
> > 
> > I don't know whether these CLI options match Maven plugin option names, but you need to ask the plugin to force update the JSON. It should be something like `--retireJsForceUpdate` for you.
> 
> Same result adding the force update argument

Looks like it's a bug with the Azure Pipelines Task: #6032

If I put the retireJs arguments at the beginning of the CLI arguments then it's working.

**Comment by ESPLouis** [comment]
FYI anyone using maven and not requiring JS scanning, this is a temp fix retireJsAnalyzerEnabled:

```
            <plugin>
                <groupId>org.owasp</groupId>
                <artifactId>dependency-check-maven</artifactId>
                <version>${dependency-check-maven.version}</version>
                <configuration>
                    
                    <retireJsAnalyzerEnabled>false</retireJsAnalyzerEnabled>
                
                </configuration>
            </plugin>
```

**Comment by aurelien-baudin** [comment]
They've just fixed it.
Tickets can be closed

**Comment by anabright** [comment]
> They've just fixed it. Tickets can be closed

It's still happening for me

**Comment by parasil** [comment]
I confirm that it is working for us too. They fixed it.

**Comment by Marx314** [comment]
@anabright
> > They've just fixed it. Tickets can be closed
> 
> It's still happening for me

https://github.com/jeremylong/DependencyCheck/blob/0a43232db2cc772c2f2ada6e7111891484132191/core/src/main/resources/dependencycheck.properties#L126
since you're probably having the invalid version and DC does not update it since it was cached since less then 24 hours you got three options

1. running task `dependencyCheckPurge` and `dependencyCheckUpdate` as suggested in the issue #6029
2. `rm jsrepository.json`
3. setting the argument at line 126 to 1

good luck

**Comment by chadlwilson** [comment]
I think this one can probably be closed now @anabright?
