### ISSUE TITLE
Dependency Check Fails to Run (Failed to initialize the RetireJS repo)

### ISSUE THREAD

**Issue by ESPLouis** [dependency-check/DependencyCheck#6033]
**Describe the bug**
Dependency check fails to run

**Version of dependency-check used**
The problem occurs using version 8.4.2 and 8.4.0 of the maven plugin. This issue occurs locally and also in fresh CI pipeline builds.

**Log file**
Caused by: org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during analysis:
	InitializationException: Failed to initialize the RetireJS repo: `/tmp/dctempdb7ca8ec-0109-4999-8ebd-b1a42d7d43dc/jsrepository.json` appears to be malformed. Please delete the file or run the dependency-check purge command and re-try running dependency-check.
		caused by JSONException: No value for info
    at org.owasp.dependencycheck.Engine.analyzeDependencies (Engine.java:689)

**To Reproduce**
Run the dependency check goal

**Expected behavior**
Process should complete successfully 

**Additional context**
This appears to be an issue with RetireJS repo

**Comment by ESPLouis** [comment]
Apologies looking further this issue appears to be related to Your issue is the same as https://github.com/jeremylong/DependencyCheck/issues/6028 and https://github.com/jeremylong/DependencyCheck/issues/6029

**Issue raised on RetireJS repo:**
https://github.com/RetireJS/retire.js/issues/423

**Comment by ESPLouis** [comment]
Closing as already raised

**Comment by eoftedal** [comment]
retire.js issue has been fixed
