### ISSUE TITLE
Stuck while building the source

### ISSUE THREAD

**Issue by Dnu12** [dependency-check/DependencyCheck#6037]
I cloned 8.4.2 snapshot using 'git clone --depth 1 https://github.com/jeremylong/DependencyCheck.git'. I tried to build it using ' mvn -s settings.xml install -DskipTests=true' . But it's stuck at 'Downloading from central: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/jackson-bom/2.15.3/jackson-bom-2.15.3.pom' for long time . 

I'd java 11 as default . I changed java 8 as default thinking issue might be because of that one . But even with java8 as default,facing same issue. 

I'm trying it from private network(intranet). Tried with internet connection also .Same issue occuring .Can some one help on this ?

**Comment by Dnu12** [comment]
![Screenshot from 2023-11-03 10-28-04](https://github.com/jeremylong/DependencyCheck/assets/28951334/f8fedd72-4773-4e08-9e74-bec5259e41e0)

**Comment by nolddor** [comment]
what's the output of:
`telnet repo.maven.apache.org 443` 

it looks like a network issue at your side.

Also try to add `-X` for more verbosity to see if you spot any error.
