### ISSUE TITLE
false positive on smiley-http-proxy-servlet-1.7.jar - reported as cpe:/a:shttp:shttp:1.7

### ISSUE THREAD

**Issue by javathought** [dependency-check/DependencyCheck#604]
False positive on library smiley-http-proxy-servlet-1.7.jar - reported as cpe:/a:shttp:shttp:1.7
```xml
        <dependency>
            <groupId>org.mitre.dsmiley.httpproxy</groupId>
            <artifactId>smiley-http-proxy-servlet</artifactId>
            <version>1.7</version>
        </dependency>
```

The CPE refers to an old (2007) C httpd server on windows, when the jar is a java proxy initiated in 2011

**Comment by jeremylong** [comment]
Thanks for pointing this out, FP resolved in 1.4.4 which should be released shortly.
