### ISSUE TITLE
NVD Data Feeds - On December 15th, 2023, the NVD plans to retire all legacy data feeds

### ISSUE THREAD

**Issue by RobSHK** [dependency-check/DependencyCheck#6046]
According to [https://nvd.nist.gov/vuln/data-feeds](https://github.com/DependencyTrack/dependency-track/discussions/url), On December 15th, 2023, the NVD plans to retire all legacy data feeds.
Would this affect Dependency Check in any way?

**Comment by jeremylong** [comment]
see:
- https://github.com/jeremylong/DependencyCheck/issues/4732
- https://github.com/jeremylong/DependencyCheck/pull/5978
