### ISSUE TITLE
Error - Not alive and dispose was called

### ISSUE THREAD

**Issue by SandwichCZ** [dependency-check/DependencyCheck#6073]
**Describe the bug**
When scanning a Maven project for vulnerabilities, new errors have started appearing after upgrading to version 8.4.3 (see attached log excerpt). The issue is reproducible 100 % of the time in our project, but did not occur on any previous versions of the plugin.

**Version of dependency-check used**
The problem occurs using version 8.4.3 of the Maven plugin.

**Log file**
```
...
See the dependency-check report for more details.


[INFO] Cache event queue destroyed: CacheEventQueue [listenerId=-744276867, cacheName=NODEAUDIT]
[INFO] Cache event queue destroyed: CacheEventQueue [listenerId=-744276867, cacheName=CENTRAL]
[INFO] Cache event queue destroyed: CacheEventQueue [listenerId=-744276867, cacheName=POM]
[ERROR] Region [NODEAUDIT] : Not alive and dispose was called, filename: NODEAUDIT
[ERROR] Region [CENTRAL] : Not alive and dispose was called, filename: CENTRAL
[ERROR] Region [POM] : Not alive and dispose was called, filename: POM
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
...
```

**To Reproduce**
1. Start dependency scanning of a Maven project.
2. Wait for it to finish.
3. See errors.

**Expected behavior**
No errors are displayed, preferably also no `Cache event queue destroyed` messages.

**Comment by nam178** [comment]
Same, I'm getting the same error using the CLI
```
[ERROR] Region [NODEAUDIT] : Not alive and dispose was called, filename: NODEAUDIT
[INFO] In dispose, destroying event queue.
[ERROR] Region [CENTRAL] : Not alive and dispose was called, filename: CENTRAL
[INFO] In dispose, destroying event queue.
[ERROR] Region [POM] : Not alive and dispose was called, filename: POM
```

**Comment by j-aho** [comment]
I cut out a part of the "debug log" and attached it
[dependency-check-NODEAUDIT.log](https://github.com/jeremylong/DependencyCheck/files/13376239/dependency-check-NODEAUDIT.log)

The /opt/dependency-check/data/cache/NODEAUDIT.key is 0 bytes
`-rw-r--r--. 1 user user 0 Nov 16 09:23 /opt/dependency-check/data/cache/NODEAUDIT.key`

It do manage to write the the report dependency-check-report.htm before this happens.

On MS-Windows with version 8.1.2 this don't happen, on Linux with version 8.1.2/8.4.2/8.4.3 it happens for one of my projects.
This do not happen with other projects and I have no clue at all what causing this and I really wish it wouldn't throw this an error (let it exit with 0 IMHO). The projects I have looked at are using nodejs/C#

**Comment by jeremylong** [comment]
This is a completely ignorable error. It makes zero sense that this is reported by JCS as an error as opposed to a debug message. It does not affect the functioning of the cache at all.

**Comment by j-aho** [comment]
Sadly I can't ignore it as it exits with error code 14, had it exited with 0 then the build system wouldn't have stopped.

**Comment by jeremylong** [comment]
@j-aho you should see a line that says "One or more fatal errors occurred" in the output. What is directly below that line?

**Comment by jeremylong** [comment]
@j-aho I'm 99.9% positive this "error" reported stating 'Not alive and dispose was called' is not the source of the exit code 14.

**Comment by j-aho** [comment]
Okay, then I'll try to figure out what it may be.
(Seems excluding **/.git/** did the trick)

**Comment by thett01** [comment]
Hi @jeremylong , 
These errors made the pipeline fail. I'm using Dependency Check AzureDevops. 
My version is 9.0.0
What can I do right now?
```
[ERROR] Region [NODEAUDIT] : Not alive and dispose was called, filename: NODEAUDIT
[INFO] In dispose, destroying event queue.
[ERROR] Region [CENTRAL] : Not alive and dispose was called, filename: CENTRAL
[INFO] In dispose, destroying event queue.
[ERROR] Region [POM] : Not alive and dispose was called, filename: POM
[ERROR] One or more fatal errors occurred
[ERROR] Unable to connect to the database - if this error persists it may be due to a corrupt database. Consider running `purge` to delete the existing database

Dependency Check completed with exit code 13.
Dependency Check reports:
[]
Dependency Check failed with message "Dependency Check exited with an error code (exit code: 13)."
##[error]Dependency Check exited with an error code (exit code: 13)
```

**Comment by j-aho** [comment]
@thett01 I was a bit curious about the error codes and opened an issue about it #6075 where Jeremy gave me this link:
https://github.com/jeremylong/DependencyCheck/blob/main/cli/src/main/java/org/owasp/dependencycheck/App.java

So there seems to be something that causes an fatal error, not related to the above errors as far as I understood.

@jeremylong would it be possible to log the file (full path) that causes the actual error? When I "fixed" my issue it was a bit of try and error.

**Comment by jeremylong** [comment]
Please don't combine issues into a single ticket like this. Yes, due to capacity issues with the NVD API 9.0.0 has issues. See #6107.

**Comment by Hacksoull** [comment]
Is there no fix as at now? because I experience the same issue on my circleCi. 

![image](https://github.com/jeremylong/DependencyCheck/assets/135615068/17701cec-c205-4c9c-88a8-1538db90f0f2)

**Comment by alireza1371** [comment]
I have the same issue, is there any update on this?

**Comment by j-aho** [comment]
@alireza1371 the exit code (like 14 from @Hacksoull screenshot) has nothing to do with the error message displayed in the screenshot

For Error codes you can look at: https://github.com/jeremylong/DependencyCheck/blob/main/cli/src/main/java/org/owasp/dependencycheck/App.java

Sadly it will not give much information, most likely it can be some files that causes the issue, try to exclude directories like **.git** from the scanning. 

Here is a small example when scanning **dependency-check.sh --dotnet /usr/bin/dotnet -s /usr/include/ -o /tmp ; echo "EXIT CODE: $?"**:

> [ERROR] Region [NODEAUDIT] : Not alive and dispose was called, filename: NODEAUDIT
> [INFO] In dispose, destroying event queue.
> [ERROR] Region [CENTRAL] : Not alive and dispose was called, filename: CENTRAL
> [INFO] In dispose, destroying event queue.
> [ERROR] Region [POM] : Not alive and dispose was called, filename: POM
> EXIT CODE: 0

So the error is there, but do not affect the writing of the report and exiting it as if nothing had happen. Sure it had been nice if the error could have been warning or info, think less people would be confused.
