### ISSUE TITLE
Is there a description of the different error/exit codes?

### ISSUE THREAD

**Issue by j-aho** [dependency-check/DependencyCheck#6075]
Is there a documentation over the different error/exit codes that dependency check uses?

It could be handy to know what the error/exit code means when trying to figure out what goes wrong.

**Comment by jeremylong** [comment]
These have not been documented - because in general you need the output/log to understand the error. In general, an error log message is written out when the error code is set:

https://github.com/jeremylong/DependencyCheck/blob/main/cli/src/main/java/org/owasp/dependencycheck/App.java#L167

**Comment by j-aho** [comment]
Thanks, that gives me a bit understanding of the error/exit code, but from the logs I could just see two exceptions, but not anything I could say what caused them, excluding the git directory seemed to get rid of them.

Would it be possible to exclude with help of the properties file?

**Comment by jeremylong** [comment]
not that I can think of. You could use the `--exclude` option.

**Comment by j-aho** [comment]
yes, I have, was just hoping I could do that over properties, then I could just change the property file and get all the builds to ignore the git directory instead of going into each build and add the --exclude option and in some cases need to keep in mind on the max number of options that ms-cmd allows.

As you already answered my original question, I'll close this one.
