### ISSUE TITLE
unable to make dependencyCheck part of check task graph

### ISSUE THREAD

**Issue by johnscancella** [dependency-check/DependencyCheck#610]
When adding `check.dependsOn dependencyCheck` to my build.gradle like you normally would to make sure a task is run as part of another task I get

`Cannot convert org.owasp.dependencycheck.gradle.extension.CheckExtension_Decorated@586b3f34 to a task.`

full output here: https://gist.github.com/johnscancella/0518026971f05730d6e1edd32b927e0d

**Comment by jeremylong** [comment]
Try this:

``` groovy
check.dependsOn tasks['dependencyCheck']
```

In 1.4.4 it automatically binds itself to check; however, I am about to push 1.4.4.1 to resolve this (see issue [#26](https://github.com/jeremylong/dependency-check-gradle/issues/26)).  See the commented out code for binding [here](https://github.com/jeremylong/dependency-check-gradle/blob/master/src/main/groovy/org/owasp/dependencycheck/gradle/DependencyCheck.groovy#L69).
