### ISSUE TITLE
[FP]: Numerous projects erroneously identified as Hamba avro 

### ISSUE THREAD

**Issue by karstenspang** [dependency-check/DependencyCheck#6102]
### Package URl

pkg:maven/com.syniverse.gsm.etl/tap2ipc@2.10.0

### CPE

`cpe:2.3:a:avro_project:avro:2.10.0:*:*:*:*:*:*:*`

### ODC Integration

{"label"=>"Maven Plugin"}

### ODC Version

8.4.3

### Description

The mentioned package and many other of our internal packages are identified as Hamba avro. Some of the packages have "avro" in their names and some do not.

**Comment by aikebah** [comment]
Non-public dependencies have to be mitigated by the authors themselves. The HTML report will have all evidences harvested by DependencyCheck. You'll likely to find avro references in all of them (in some other item than the groupId/ artifactId).

**Comment by karstenspang** [comment]
You are right, the mentioned dependency has the word avro in its description.

My point is that the CPE should match hamba avro only, not everything with avro in it. There have been several similar cases in the past with identifiers like xxx_project, matching xxx in a lot of other packages.
