### ISSUE TITLE
JarAnalyzer fails to parse Jar. Exists with String index out of range: -1

### ISSUE THREAD

**Issue by stevespringett** [dependency-check/DependencyCheck#611]
When Dependency-Check CLI analyzes a old version of xsom, it fails with the following error:

[WARN] An unexpected error occurred during analysis of '/Users/steve/Downloads/mapping-services-dc_trunk-PSG_TEST/destinationFolder/plugins/com.sun.xml.xsom_3.3.0.v20161018-0713/1/xsom-20070323.jar' (Jar Analyzer): String index out of range: -1
[

The issue can be replicated by scanning the following artifact:
https://mvnrepository.com/artifact/com.sun.xsom/xsom/20070323

**Comment by stevespringett** [comment]
The issue has been observed with DC 1.4.3 and 1.4.4 using both the CLI and Jenkins plugin.

**Comment by stevespringett** [comment]
JarAnalyzer appears to be failing when parsing the manifest, specifically:

Build-Id: (private build)

**Comment by jeremylong** [comment]
Thanks for reporting this - the fix will be included in the next release.

--Jeremy
