### ISSUE TITLE
Default missing for nvd.api.delay

### ISSUE THREAD

**Issue by aikebah** [dependency-check/DependencyCheck#6111]
Spotted a minor bug while looking at the debug logs investigating on the HTTP 503 issues with closed connection pool:

Not having a default property value for `nvd.api.delay`, causes debug logging to signal 

[DEBUG] Invalid setting `NVD_API_DELAY`?

The problem occurs using version 9.0.0 of the maven plugin when running with debug logging enabled

**To Reproduce**
Run dependency-check as a maven plugin with debug-logging enabled and observe that the log message mentioned above appears. Based on code inspection other integrations will suffer from the same.

**Expected behavior**
Absence of an explicitly configured nvdApiDelay does not yield debug-logging to signal an invalid setting, but uses a sensible default without logging any issue (only configured non-numeric nvdApiDelay settings should yield the log, which I think should even be promoted to WARN level)

**Additional context**

**Comment by jeremylong** [comment]
good catch- thanks. Want me to submit a PR?

**Comment by aikebah** [comment]
Almost done creating one... will be there in few secs

**Comment by OrangeDog** [comment]
The documentation (or at least [this one](https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html)) also does not explain that the default is based on whether there's an API key or not, nor what the two values are.
