### ISSUE TITLE
[ERROR] Unable to connect to the database - if this error persists it may be due to a corrupt database. Consider running `purge` to delete the existing database

### ISSUE THREAD

**Issue by joshuawph** [dependency-check/DependencyCheck#6115]
Running the Dependency checker using Azure Devops Task. Now It produced this logs. 

Starting: Dependency Check
==============================================================================
Task         : OWASP Dependency Check
Description  : Dependency Check is a Software Composition Analysis (SCA) tool that attempts to detect publicly disclosed vulnerabilities contained within a project's dependencies.
Version      : 6.1.1
Author       : Dependency Check
Help         : [More Information](https://jeremylong.github.io/DependencyCheck/index.html)
==============================================================================
Starting Dependency Check...
Setting report directory to C:\agent\_work\26\a
Downloading Dependency Check latest installer from GitHub..
Downloading ZIP from "[https://github.com/jeremylong/DependencyCheck/releases/download/v9.0.0/dependency-check-9.0.0-release.zip"...](https://github.com/jeremylong/DependencyCheck/releases/download/v9.0.0/dependency-check-9.0.0-release.zip%22...)
Dependency Check script set to C:\agent\_work\_tasks\dependency-check-build-task_47ea1f4a-57ba-414a-b12e-c44f42765e72\6.1.1\dependency-check\bin\dependency-check.bat
Invoking Dependency Check...
Path: C:\agent\_work\_tasks\dependency-check-build-task_47ea1f4a-57ba-414a-b12e-c44f42765e72\6.1.1\dependency-check\bin\dependency-check.bat
Arguments: --project "ManageServiceTest1" --out "C:\agent\_work\26\a" --scan "C:\agent\_work\26\s\**\*.csproj" --format HTML --format JSON --format JUNIT
C:\Windows\system32\cmd.exe /D /S /C "C:\agent\_work\_tasks\dependency-check-build-task_47ea1f4a-57ba-414a-b12e-c44f42765e72\6.1.1\dependency-check\bin\dependency-check.bat --version"
Dependency-Check Core version 9.0.0

Searching for left over lock files...
found no left over lock files, continuing...
C:\Windows\system32\cmd.exe /D /S /C "C:\agent\_work\_tasks\dependency-check-build-task_47ea1f4a-57ba-414a-b12e-c44f42765e72\6.1.1\dependency-check\bin\dependency-check.bat --project ManageServiceTest1 --out C:\agent\_work\26\a --scan C:\agent\_work\26\s\**\*.csproj --format HTML --format JSON --format JUNIT"
[INFO] Instance is null, returning unconfigured instance
[INFO] Using system property [[jcs.logSystem] [slf4j]]
[INFO] Setting default auxiliaries to "ODC"
[INFO] setting defaultCompositeCacheAttributes to [ useLateral = true, useRemote = true, useDisk = true, maxObjs = 0, maxSpoolPerRun = -1, diskUsagePattern = UPDATE, spoolChunkSize = 2 ]
[INFO] setting defaultElementAttributes to [ IS_LATERAL = false, IS_SPOOL = true, IS_REMOTE = false, IS_ETERNAL = false, MaxLifeSeconds = 86400, IdleTime = 1800, CreateTime = 1700711221767, LastAccessTime = 1700711221767, getTimeToLiveSeconds() = 86400, createTime = 1700711221767 ]
[INFO] initialized MemoryCache for CENTRAL
[INFO] Constructed cache with name [CENTRAL] and cache attributes [ useLateral = true, useRemote = true, useDisk = true, maxObjs = 0, maxSpoolPerRun = -1, diskUsagePattern = UPDATE, spoolChunkSize = 2 ]
[INFO] No cache event logger defined for auxiliary [jcs.auxiliary.ODC]
[INFO] Using standard serializer [org.apache.commons.jcs3.utils.serialization.StandardSerializer@4ff8d125] for auxiliary [jcs.auxiliary.ODC]
[INFO] Region [CENTRAL] : Set maxKeySize to: "1,000,000"
[INFO] Region [CENTRAL] : Cache file root directory: C:\agent\_work\_tasks\dependency-check-build-task_47ea1f4a-57ba-414a-b12e-c44f42765e72\6.1.1\dependency-check\data\cache
[INFO] Region [CENTRAL] : Indexed Disk Cache is alive.
[INFO] initialized MemoryCache for POM
[INFO] Constructed cache with name [POM] and cache attributes [ useLateral = true, useRemote = true, useDisk = true, maxObjs = 0, maxSpoolPerRun = -1, diskUsagePattern = UPDATE, spoolChunkSize = 2 ]
[INFO] No cache event logger defined for auxiliary [jcs.auxiliary.ODC]
[INFO] Using standard serializer [org.apache.commons.jcs3.utils.serialization.StandardSerializer@65a15628] for auxiliary [jcs.auxiliary.ODC]
[INFO] Region [POM] : Set maxKeySize to: "1,000,000"
[INFO] Region [POM] : Cache file root directory: C:\agent\_work\_tasks\dependency-check-build-task_47ea1f4a-57ba-414a-b12e-c44f42765e72\6.1.1\dependency-check\data\cache
[INFO] Region [POM] : Indexed Disk Cache is alive.
[INFO] In DISPOSE, [NODEAUDIT] disposing of memory cache.
[INFO] Memory Cache dispose called.
[INFO] In DISPOSE, [CENTRAL] fromRemote [false]
[INFO] In DISPOSE, [CENTRAL] auxiliary [CENTRAL]
[INFO] In DISPOSE, [CENTRAL] put 0 into auxiliary [CENTRAL]
[INFO] In dispose, destroying event queue.
[INFO] Cache event queue destroyed: CacheEventQueue [listenerId=-95859998, cacheName=CENTRAL]
[INFO] Region [CENTRAL] : Saving keys to: CENTRAL, key count: 0
[INFO] Region [CENTRAL] : Finished saving keys.
[INFO] Region [CENTRAL] : Shutdown complete.
[INFO] In DISPOSE, [CENTRAL] disposing of memory cache.
[INFO] Memory Cache dispose called.
[INFO] In DISPOSE, [POM] fromRemote [false]
[INFO] In DISPOSE, [POM] auxiliary [POM]
[INFO] In DISPOSE, [POM] put 0 into auxiliary [POM]
[INFO] In dispose, destroying event queue.
[INFO] Cache event queue destroyed: CacheEventQueue [listenerId=-95859998, cacheName=POM]
[INFO] Region [POM] : Saving keys to: POM, key count: 0
[INFO] Region [POM] : Finished saving keys.
[INFO] Region [POM] : Shutdown complete.
[INFO] In DISPOSE, [POM] disposing of memory cache.
[INFO] Memory Cache dispose called.
[INFO] In dispose, destroying event queue.
[ERROR] Region [NODEAUDIT] : Not alive and dispose was called, filename: NODEAUDIT
[INFO] In dispose, destroying event queue.
[ERROR] Region [CENTRAL] : Not alive and dispose was called, filename: CENTRAL
[INFO] In dispose, destroying event queue.
[ERROR] Region [POM] : Not alive and dispose was called, filename: POM
[ERROR] One or more fatal errors occurred
[ERROR] Unable to connect to the database - if this error persists it may be due to a corrupt database. Consider running `purge` to delete the existing database

Dependency Check completed with exit code 13.
Dependency Check reports:
[]
Dependency Check failed with message "Dependency Check exited with an error code (exit code: 13)."
##[error]Dependency Check exited with an error code (exit code: 13).
Ending Dependency Check...

**Comment by echalone** [comment]
We have the same problem

**Comment by pvanoostrum** [comment]
We are also having the same problem

**Comment by AndreaCuneo** [comment]
same here

**Comment by mertartanbtc** [comment]
same here

**Comment by mertartanbtc** [comment]
same here

**Comment by yansifw** [comment]
same problem with 9.0.0 after purging local DB

**Comment by thett01** [comment]
same here

**Comment by jeremylong** [comment]
I'm betting the error is different after purging. See #6107
