### ISSUE TITLE
[ERROR] Unable to connect to the database - if this error persists it may be due to a corrupt database. 

### ISSUE THREAD

**Issue by mertartanbtc** [dependency-check/DependencyCheck#6116]
Hi,
[ERROR] Region [NODEAUDIT] : Not alive and dispose was called, filename: NODEAUDIT
[INFO] In dispose, destroying event queue.
[ERROR] Region [CENTRAL] : Not alive and dispose was called, filename: CENTRAL
[INFO] In dispose, destroying event queue.
[ERROR] Region [POM] : Not alive and dispose was called, filename: POM
[ERROR] One or more fatal errors occurred
[ERROR] Unable to connect to the database - if this error persists it may be due to a corrupt database. Consider running `purge` to delete the existing database
##[error]Bash exited with code '13'.

I have a dependency check task on Azure Pipelines, but I get an error as above in version 9.0.0.

**Comment by jeremylong** [comment]
Have you purged the database? See https://github.com/jeremylong/DependencyCheck#breaking-changes

**Comment by RobSHK** [comment]
@jeremylong it is mentioned "9.0.0 contains breaking changes which requires updates to the database. If using an externally hosted database the schema will need to be updated." I couldn't find any new Upgrade_*.sql or initialize.sql scripts in https://github.com/jeremylong/DependencyCheck/tree/main/core/src/main/resources/data
We are using Oracle Data Base which is getting updated nightly.
Is there any changes to Data Base Schema?

**Comment by jeremylong** [comment]
@RobSHK technically you don't need to recreate the database schema - but due to how properties are stored it will completely re-populate the database. It would likely be better to start with a clean database.
