### ISSUE TITLE
How to use the nvdApiKey in a Maven pom.xml

### ISSUE THREAD

**Issue by NathanDotTo** [dependency-check/DependencyCheck#6117]
**Is your feature request related to a problem? Please describe.**
This is a note about how to use the NVD API Key in a Maven pom.xml. I can't see where in the various MD files this would fit, else I would create a PR. The main documentation for Maven appears to be in files in the web site that I don't know how to provide a PR for.

The configuration is:

```
<configuration>
  ...
   <nvdApiKey>${env.NVDAPIKEY}</nvdApiKey>
</configuration>

**Describe the solution you'd like**
Ideally, this would be described in the Maven documentation. 

Note that I have used an environment variable so that the value could be set in one place, and kept secret from the code.

**Describe alternatives you've considered**
See above, if I can find where this should go, I would create a PR.

**Comment by ahoehma** [comment]
I think another way would be to run 

mvn -DnvdApiKey=XXXX 

Right?

**Comment by NathanDotTo** [comment]
Yes, that can work too, with the use of an environment variable at the CLI.Perfectly happy to write this up in a PR. Just need some guidance as to where best to put it.Regards Nathan On 23 Nov 2023, at 12:16, Andreas Höhmann ***@***.***> wrote:﻿
I think another way would be to run
mvn -DnvdApiKey=XXXX
Right?

**Comment by jeremylong** [comment]
This is just how maven works - you can pass almost any configurable argument on a plugin using `-Darg=value`.  I don't think this needs to be documented. Also, using an API key like that can expose the key in various ways... logs, history, etc.

**Comment by NathanDotTo** [comment]
Good point. This issue was created by me as the top level README suggests referring other documentation for how best to use the API key. I don't see such documentation elsewhere though, so I am suggesting that I help with that.This does need careful thought though. Perhaps it is better to simply use an environment variable to be read by the Maven, and other, plugin, and explicitly not logged. Open to discussion, obviously, but providing a secure mechanism to avoid exposing the API key would, I think, help here.On 23 Nov 2023, at 13:05, Jeremy Long ***@***.***> wrote:﻿
This is just how maven works - you can pass almost any configurable argument on a plugin using -Darg=value.  I don't think this needs to be documented. Also, using an API key like that can expose the key in various ways... logs, history, etc.

**Comment by jeremylong** [comment]
https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html lists the parameters. Sure, I didn't explicitly give examples - but its a maven plugin. If you know the arguments you can configure it. Also, most IDEs will have some level of autocomplete.  If you think more documentation is needed - we accept PRs.

**Comment by dbwiddis** [comment]
I know this issue is closed but it's presently the top search engine result for "How to use the nvdApiKey in a Maven pom" :-)

I'm using 9.0.1 and have this working passing my key on the command line with `-DnvdApiKey=my-key-here` (with the exception of the errors noted on #6141.

But I can't seem to get it working using my settings.xml file.   I looked at the setup in #6106 and configured appropriately, putting my key in the password field:
```xml
<!-- settings.xml -->
    <server>
      <id>nvd</id>
      <password>****</password>
    </server>
```
and updated my pom.xml:
```xml
<plugin>
    <groupId>org.owasp</groupId>
    <artifactId>dependency-check-maven</artifactId>
    <configuration>
        <nvdApiServerId>nvd</nvdApiServerId>
    </configuration>
    <executions>
        <execution>
            <goals>
                <goal>check</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```
But it doesn't use the key. I've even tried directly hard-coding my NVD API key in a `<nvdApiKey>` property in the configuration and it doesn't work.

Am I missing something obvious about how I'm supposed to configure these advanced properties?

**Comment by dbwiddis** [comment]
> Am I missing something obvious about how I'm supposed to configure these advanced properties?

Well, it seems to work by just declaring a `<property>` in the settings.xml.  Which doesn't seem to match what others are doing...

**Comment by NathanDotTo** [comment]
Just for the sake of ease, I am popping this to the top of the message stack (note that I am building my own 9.0.1). The API key value is set in the environment, so as to avoid the risk of it being checked in.

<plugin>
                <groupId>org.owasp</groupId>
                <artifactId>dependency-check-maven</artifactId>
                <version>9.0.1</version>
                <configuration>
...
                    <nvdApiKey>${env.NVDAPIKEY}</nvdApiKey>
                </configuration>
