### ISSUE TITLE
Recoverable I/O exception (java.net.SocketException) caught when processing request to {s}->[https://services.nvd.nist.gov:443](https://services.nvd.nist.gov/

### ISSUE THREAD

**Issue by ahoehma** [dependency-check/DependencyCheck#6119]
Since 9.0.0 I see something like this in my gitlab build ... is this "normal"?

2450 [INFO] Checking for updates
154771 [INFO] Recoverable I/O exception (java.net.SocketException) caught when processing request to {s}->[https://services.nvd.nist.gov:443](https://services.nvd.nist.gov/)
416914 [INFO] Recoverable I/O exception (java.net.SocketException) caught when processing request to {s}->[https://services.nvd.nist.gov:443](https://services.nvd.nist.gov/)
679059 [INFO] Recoverable I/O exception (java.net.SocketException) caught when processing request to {s}->[https://services.nvd.nist.gov:443](https://services.nvd.nist.gov/)
941202 [INFO] Recoverable I/O exception (java.net.SocketException) caught when processing request to {s}->[https://services.nvd.nist.gov:443](https://services.nvd.nist.gov/)
1203346 [INFO] Recoverable I/O exception (java.net.SocketException) caught when processing request to {s}->[https://services.nvd.nist.gov:443](https://services.nvd.nist.gov/)
1465490 [INFO] Recoverable I/O exception (java.net.SocketException) caught when processing request to {s}->[https://services.nvd.nist.gov:443](https://services.nvd.nist.gov/)
1727635 [INFO] Recoverable I/O exception (java.net.SocketException) caught when processing request to {s}->[https://services.nvd.nist.gov:443](https://services.nvd.nist.gov/)
1989778 [INFO] Recoverable I/O exception (java.net.SocketException) caught when processing request to {s}->[https://services.nvd.nist.gov:443](https://services.nvd.nist.gov/)
2251922 [INFO] Recoverable I/O exception (java.net.SocketException) caught when processing request to {s}->[https://services.nvd.nist.gov:443](https://services.nvd.nist.gov/)

**Comment by jeremylong** [comment]
Unfortunately yes. When building the `open-vulnerability-client` I was unable to figure out how to suppress these informational messages.

**Comment by ahoehma** [comment]
Alright. Thanks for the info.
I was just wondering what this "{s}" is all about :) Looks like a missing value for a placeholder or something.
And at the end its just an info-log. So not critical I guess.
May I can just configure the maven plugin to log only warnings?

**Comment by jeremylong** [comment]
That comes from the Apache HTTP Client. Possibly a slight difference between how the loggers format entries.  regardless, it can be ignored.

**Comment by ahoehma** [comment]
Ok. So from my point of view we can close this ticket here.

**Comment by nestle1936** [comment]
I am working with azure devops pipeline and the same issue occure.
the pipeline stock here and failed after 30min event if the delay is `--nvdApiDelay 300000` :

`[INFO] Region [NODEAUDIT] : Cache file root directory: /agent/_work/_tasks/dependency-check-build-task_47ea1f4a-57ba-414a-b12e-c44f42765e72/6.1.1/dependency-check/data/cache
[INFO] Region [NODEAUDIT] : Indexed Disk Cache is alive.
[INFO] Parsed regions [CENTRAL, POM, NODEAUDIT]
[INFO] Finished configuration in 178 ms.
[INFO] Checking for updates
[INFO] NVD API has 171,457 records in this update
[INFO] Recoverable I/O exception (java.io.IOException) caught when processing request to {s}->[https://services.nvd.nist.gov:443](https://services.nvd.nist.gov/)`

Can we reopen this issue

**Comment by RedEfire** [comment]
Same for me (on azure devops)
`[INFO] Downloaded 10,000/171,546 (6%)
[INFO] Recoverable I/O exception (java.io.InterruptedIOException) caught when processing request to {s}->[https://services.nvd.nist.gov:443](https://services.nvd.nist.gov/)`

**Comment by fishbone1** [comment]
Same here. I wonder if you can see whether there is an actual problem or not. First I thought it's due to the missing API key. But now someone else told me to have the same problems even with API key. In both cases we can only connect via proxy. So I wonder if this API connection respects the proxy settings (`--proxyserver` and `--proxyport`).

**Comment by ahoehma** [comment]
Hmmm ... now I realized too that this logging is really showing a problem :) I run my maven stuff in gitlab behind company proxy etc. and its not working anymore.

**Comment by TheRealChrisS** [comment]
For me it's working when specifying the proxy like this:
`mvn dependency-check:aggregate -DnvdApiKey=<api_key> -DproxyHost=<proxy_host> -DproxyPort=<proxy_port>`

Instead of:
`mvn dependency-check:aggregate -DnvdApiKey=<api_key> -Dproxyserver=<proxy_host> -Dproxyport=<proxy_port>`

**Comment by kingca31** [comment]
> For me it's working when specifying the proxy like this: `mvn dependency-check:aggregate -DnvdApiKey=<api_key> -DproxyHost=<proxy_host> -DproxyPort=<proxy_port>`
> 
> Instead of: `mvn dependency-check:aggregate -DnvdApiKey=<api_key> -Dproxyserver=<proxy_host> -Dproxyport=<proxy_port>`

This worked great for me! thank you!
