### ISSUE TITLE
Separating analyzer jars

### ISSUE THREAD

**Issue by colezlaw** [dependency-check/DependencyCheck#612]
The discussion at https://groups.google.com/forum/#!topic/dependency-check/3EYUyFlbp-w got me working on something different. Whenever I had written new analyzers, I misunderstood the way the Service Loader worked, and I would add my analyzers to dependency-check-core, and add their names to the existing `org.owasp.dependencycheck.analyzer.Analyzer` file. However, it turns out that each analyzer could live in its own jar file with its own `META-INF/services/org.owasp.dependencycheck.analyzer.Analyzer`.

So there are a number of steps to make things a bit easier, both in terms of disabling existing analyzers and adding new ones:

1. Add a `contrib` top level directory to the CLI distribution and set `ENDORSED_DIR` to `contrib` in the shell script/batch file - so folks making new analyzers can just drop their jar file into that directory.
1. Move all of the existing analyzers into their own Maven projects with their own services file. To disable an analyzer, just move its jar file out of the analyzers directory.
1. Make a Maven project archetype for making new analyzers which has the template services file already. I know that you can prompt for new things in a template, but I'm not certain if it can make new files with user-provided names (it can make user-specified directories).

**Comment by jeremylong** [comment]
1) I've been planning on adding a "plugins" directory to the CLI for this purpose and I'm pretty sure the same could be accomplished by adding a dependency to the plugin.

2) For the core analyzers I think I would rather add properties to disable them. While the directory would work great for the CLI I just think it become more of a pain for the other plugins (having to define excludes).

3) Making an arch type for an analyzer is likely a good idea as it would make developing a plugin a lot easier.

**Comment by colezlaw** [comment]
Well, a demo of the archetype is available:

```
$ mvn archetype:generate \
  -DarchetypeRepository=https://dl.bintray.com/c0leslaw/maven
  -DarchetypeGroupId=org.owasp
  -DarchetypeArtifactId=dependencycheck-archetype-analyzer
  -DarchetypeVersion=1.4.4
```

**Comment by colezlaw** [comment]
As things work right now, 2 (my idea) won't work very well anyway because there are integration tests that depend on some of the unit tests. As I was trying out separating the analyzers, this began to unravel very quickly. 2 (your idea) should still work.

**Comment by jeremylong** [comment]
Enabled properties have been added to all analyzers and updaters. The plugins directory, archetype for a plugin, and instructions for using still need to be created.

**Comment by jeremylong** [comment]
@colezlaw thanks for the suggestions and discussion. A plugin archetype has been added; with the archetype and other changes this issue is considered closed.
