### ISSUE TITLE
How to use the nvd api key in de gralde plugin

### ISSUE THREAD

**Issue by Sjoerd97** [dependency-check/DependencyCheck#6121]
While I seem to have configured the use of the key exactly like the documentation prescribes: 
    
```
    dependencyCheck {
        nvd {
            apiKey = '<api-key>'
            delay = 16000
        }
    }
```

I still get the following notice: 
   
    `An NVD API Key was not provided - it is highly recommended to use an NVD API key as the update can take a VERY long time without an API Key`

**Comment by jeremylong** [comment]
What you have listed is correct. When I use that configuration I can put an invalid API key and see that the NVD immediately returns a 404 and when I put the correct key I do not see the log message you've indicated.

**Comment by Sjoerd97** [comment]
Oh that is weird, on my side it continues downloading regardless of the key I use and eventually fails with a 503. The 503 issue I know of. I have heard that others had trouble with their first requested api key. perhaps ill request a second one

**Comment by Sjoerd97** [comment]
Different key same troubles unfortunately...

**Comment by Anonymous-422** [comment]
What about adding that like: 
dependency-check.bat --project "Project name" --scan ..\..\pathx --retireJsUrl
https://raw.githubusercontent.com/RetireJS/retire.js/master/repository/jsrepository.json
--nvdApiKey XXXXb-4XX1-8XXF-daXXXXXXXXf

**Comment by chadlwilson** [comment]
If you are getting that message, Gradle is not configuring the plugin correctly. 

You may need to include the wider context from your `build.gradle` - perhaps you are including that fragment in the wrong location and it is being ignored. The 4 space indent makes me suspicious :-)

**Comment by Sjoerd97** [comment]
There is indeed a wider context, its just that the plugin was working before the major version bump. So it was in the right location before...

**Comment by chadlwilson** [comment]
Well there was no `nvd` config before the major version bump so I guess it depends which config you were trying to set/override beforehand as there was no similar thing to an API key or delay. Anyway, if folks can't replicate your issue due to lack of context, there's probably not much help that can be provided.

**Comment by Sjoerd97** [comment]
Understandable, I am not keen on sharing more context since the repo is part of a private enterprise repository.
What I can share with others is that the following fixed the issue for me:

```    
dependencyCheck {
        failBuildOnCVSS = 11
        failOnError = false
        formats = ['JUNIT', 'HTML', 'JSON']
        data {
            directory = "${rootDir}/owasp"
        }
        suppressionFiles = ['shared-owasp-suppressions.xml']
        analyzers {
            assemblyEnabled = false
        }
        nvd {
            apiKey = '<api-key>'
            delay = 16000
        }
    }

   task owaspCheck(type: Jar) {
        dependsOn tasks.findByName("dependencyCheckAnalyze")
    }
```    
    
 Unfortunately now I get 404 errors from the server...

**Comment by chadlwilson** [comment]
Normally one would create a simple reproducer, as people can't guess whether you are writing your build.gradle properly, whether you have a multi-project build etc etc, whether you have other plugins interfering with things, your gradle version, whether you have just put the config in the wrong place etc etc,

Sounds like it must have been a gradle configuration problem in any case. So I suppose you can close this issue.

**Comment by chadlwilson** [comment]
> Unfortunately now I get 404 errors from the server...

If you are getting `404` errors, re-generate your API key from the link in the email you got sent by NVD. There seem to be some issues with keys sometimes.

**Comment by fosJoddie** [comment]
After hitting my head against the proverbial wall for a few days on a similar issue, this is what eventually helped me

> > Unfortunately now I get 404 errors from the server...
> 
> If you are getting `404` errors, re-generate your API key from the link in the email you got sent by NVD. There seem to be some issues with keys sometimes.

Indeed, this seems to be the issue. If you are like me, and you have a bad habbit of leaving your tabs open in your browser, you might end up with remaking your key a couple of time just by reopening your browser tabs. 

Now, getting a 404 status code back from an API because your key is invalid/unrecognized is a first from me. 

Normally I'd say maybe DependencyCheck could print out a: "Got unexpected 404 found from API, maybe your API key is wrong" instead of just doing a build failed generic error: " Error updating the NVD Data".

My (working) setup in my `build.gradle` is simply:

```
dependencyCheck  {
    nvd {
        apiKey='<apikey>'
    }
}
```

**Comment by chadlwilson** [comment]
> > If you are getting `404` errors, re-generate your API key from the link in the email you got sent by NVD. There seem to be some issues with keys sometimes.
> 
> Indeed, this seems to be the issue. If you are like me, and you have a bad habbit of leaving your tabs open in your browser, you might end up with remaking your key a couple of time just by reopening your browser tabs.

Yeah, I think that's exactly what happened to me too. Also if more than one person (in, say, a team) has access to the email they could end up regenerating the key too. It's quite odd that it's not a one-time-only email link.

> Normally I'd say maybe DependencyCheck could print out a: "Got unexpected 404 found from API, maybe your API key is wrong" instead of just doing a build failed generic error: " Error updating the NVD Data".

Good idea, might be a good opportunity for opening a specific issue at https://github.com/jeremylong/Open-Vulnerability-Project or raising a PR? :-)

**Comment by Sjoerd97** [comment]
@chadlwilson, thanks for the tip. This was my first time ever raising an issue on github, so I can appreciate the feedback

**Comment by Sjoerd97** [comment]
Ill see if I can regenerate the key again. previous attempt wasnt successful.
Question can be closed anyway since the initial question has been answered

**Comment by jeremylong** [comment]
You can test if your API key is valid using the curl command documented in the open-vulnerabillity-project repo: https://github.com/jeremylong/Open-Vulnerability-Project/tree/main/vulnz#api-key-is-used-and-a-404-error-occurs

**Comment by alwyn** [comment]
Is this API key relevant to anyone who uses the database as part of their CI pipeline?

Reading the terms it feels more like it is meant for people who write tools that access that database, e.g. the Owasp dependency check plugin.  Shouldn't the end user be ignorant of this key?
