### ISSUE TITLE
DB migration issue -  The write format 2 is smaller than the supported format 3 [2.2.224/5]

### ISSUE THREAD

**Issue by sergeykad** [dependency-check/DependencyCheck#6122]
**Describe the bug**
The following error occurs: `MVStoreException: The write format 2 is smaller than the supported format 3 [2.2.224/5]`

**Version of dependency-check used**
9.0.0 of the Gradle plugin

**Log file**
```
Caused by: org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during analysis:
	DatabaseException: Unable to connect to the database - if this error persists it may be due to a corrupt database. Consider running `purge` to delete the existing database
		caused by DatabaseException: Unable to connect to the database
		caused by JdbcSQLNonTransientConnectionException: Unsupported database file version or invalid file header in file "/home/ubuntu/.gradle/dependency-check-data/7.0/odc.mv.db" [90048-224]
		caused by MVStoreException: The write format 2 is smaller than the supported format 3 [2.2.224/5]
	at org.owasp.dependencycheck.Engine.throwFatalDatabaseException(Engine.java:748)
	at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:714)
	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:633)
	at org.owasp.dependencycheck.gradle.tasks.AbstractAnalyze.analyze(AbstractAnalyze.groovy:100)
	... 122 more
```

**To Reproduce**
Upgrade from the previous version

**Expected behavior**
No error occurs and DB is transparently upgraded if needed.

**Additional context**
The error occurs on the CI environment and it is not trivial to perform a DB purge there.

**Comment by jeremylong** [comment]
It is really weird how a major version update might have breaking changes... except that is almost the [definition of a major version change](https://semver.org/).
> MAJOR version when you make incompatible API changes

There are several reasons this could have happened and is clearly documented that you may need to run purge: https://github.com/jeremylong/DependencyCheck#breaking-changes

**Comment by sergeykad** [comment]
There is no need to be so hostile about it. While major version upgrades can introduce compatibility issues, it's not an absolute certainty. Compatibility breaks can occur unintentionally, even in major releases. And while the documentation acknowledges potential database issues during upgrades, it doesn't provide specific details or claim that upgrades cannot be completed without purging the database. The problem I'm encountering could be unrelated or potentially resolvable without purging the data.

**Comment by jeremylong** [comment]
@sergeykad sorry about that. Its been a week with all the failures because of the availability at the NVD and the breaking change you've stumbled upon here.

Basically, the way the properties for the updates are stored in the database has changed from the data feed vs the API - you'll have to do a complete reload.
