### ISSUE TITLE
Database Breaking Changes with 9.0.0

### ISSUE THREAD

**Issue by kcbimonte** [dependency-check/DependencyCheck#6134]
In the latest release notes, it says that the database will need to have its schema updated.

> 9.0.0 contains breaking changes which requires updates to the database. If using an externally hosted database the schema will need to be updated.

However, looking at the initialize scripts, none of them have been updated with the newest release.
- https://github.com/jeremylong/DependencyCheck/tree/main/core/src/main/resources/data

Are external database schema upgrades required or is just a truncate of all tables needed? If a schema update is needed, when can we expect the new SQL Initialization scripts (specifically MySQL)?

**Comment by jeremylong** [comment]
Technically what is documented is wrong. However, the first update will end up over-writing all data, etc. It would be better to just start with a clean database.

**Comment by jeremylong** [comment]
Also, if using an H2 database and you use the data directory argument - the update will fail unless you purge.

**Comment by kcbimonte** [comment]
Understood. Thank you for the clarification.
