### ISSUE TITLE
Q. How to use nvdValidForHours in Azure Devops

### ISSUE THREAD

**Issue by tlogik** [dependency-check/DependencyCheck#6142]
Hi.
It is a bit unclear to me how the extension for Azure Devops is doing a kind of cache for the NVD data download.
The argument --nvdValidForHours is default 4 hours.
but i would like to know how it is cached locally in Azure Devops?
Can anybody elaborate or point to the code that does it so I can see what goes on?
Thanks

**Comment by jeremylong** [comment]
You should ask the question here: https://github.com/dependency-check/azuredevops
