### ISSUE TITLE
NVD API request failures are occurring / Code: 504 / No documents exist

### ISSUE THREAD

**Issue by mhp-borisbojic** [dependency-check/DependencyCheck#6147]
**Describe the bug**
Running has many timeouts with `dependency-check:9.0.1:check`, even with running it multiple times.

**Version of dependency-check used**
dependency-check:9.0.1:check (with NVD API Key)

Apache Maven 3.9.5 (57804ffe001d7215b5e7bcb531cf83df38f93546)
Maven home: /opt/homebrew/Cellar/maven/3.9.5/libexec
Java version: 18.0.2, vendor: Amazon.com Inc., runtime: /Users/borisbojic/.sdkman/candidates/java/18.0.2-amzn
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "14.1.1", arch: "aarch64", family: "mac"

**Log file**
```
[WARNING] NVD API request failures are occurring; retrying request for the 9 time
[INFO] NVD API has 171.546 records in this update
[INFO] Downloaded 10.000/171.546 (6%)
[WARNING] NVD API request failures are occurring; retrying request for the 5 time
UpdateException: Error updating the NVD Data
[ERROR] 		caused by NvdApiException: NVD Returned Status Code: 504
[ERROR] 	NoDataException: No documents exist

```

**To Reproduce**
Run the dependency check

**Expected behavior**
Dependency check runs as expected (download database, run the check)

**Additional context**

**Comment by jeremylong** [comment]
see #6144
