### ISSUE TITLE
Android - aar file

### ISSUE THREAD

**Issue by SecDev215** [dependency-check/DependencyCheck#615]
Can I scan Android dependencies (AAR file) ?

**Comment by jeremylong** [comment]
Out of the box right now - I don't think so. However, I believe we could easily add an analyzer for AAR files.

--Jeremy

**Comment by SecDev215** [comment]
Thank you for your quick reply. Would be useful given that we can scan dependencies jar files but not aar files for android development.

**Comment by jeremylong** [comment]
I've looked at a couple of AAR files. What we can extract for identification:
1. Information from the file name
2. Package name from the android manifest
3. Package names from the class files contained in the classes.jar file (possibly use a similar filtering technique as the JAR analyzer)
4. Attempt to see if there is a manifest in class.jar - however, it appears that this, if present, is almost always nearly blank.
5. Retrieve the GAV coordinates from Maven Central (if present)

**Comment by spyhunter99** [comment]
it works as far as i can tell, via the gradle plugin

**Comment by jeremylong** [comment]
Android AAR file support was added in a previous version and we forgot to link back to this enhancement request.  See one of the updates here:

https://github.com/jeremylong/DependencyCheck/blob/e5906055da5961e75373c44fb168ddab4629349f/core/src/main/java/org/owasp/dependencycheck/analyzer/JarAnalyzer.java#L186
