### ISSUE TITLE
How to use the nvd api key in the command line method?

### ISSUE THREAD

**Issue by proo4509** [dependency-check/DependencyCheck#6152]
i am trying to add a newly created and activated NVD api key according to https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html
It's not clear to me what is mandatory, but I've only tried -nvdApiKey since that's all i have (no username/password).
I tried the key with and without quotes.

call ....\dependency-check.bat --nvdApiKey "***" .....
call ....\dependency-check.bat --nvdApiKey *** .....

Keep getting [WARN] An NVD API Key was not provided - it is highly recommended to use an NVD API key as the update can take a VERY long time without an API Key
What am i doing wrong?

**Comment by proo4509** [comment]
additional info

*   Trying 18.235.227.114:443...
*   Trying [2600:1f18:268d:1ddd:fd96:dcaa:cf17:f2b2]:443...
* connect to 2600:1f18:268d:1ddd:fd96:dcaa:cf17:f2b2 port 443 failed: Bad access
* Connected to services.nvd.nist.gov (18.235.227.114) port 443
* schannel: disabled automatic use of client certificate
* ALPN: curl offers http/1.1
* ALPN: server did not agree on a protocol. Uses default.
* using HTTP/1.x
> GET /rest/json/cves/2.0\?cpeName\=cpe:2.3:o:microsoft:windows_10:1607:\*:\*:\*:\*:\*:\*:\* HTTP/1.1
> Host: services.nvd.nist.gov
> User-Agent: curl/8.4.0
> Accept: application/json
> apiKey: *****
> 
* schannel: remote party requests renegotiation
* schannel: renegotiating SSL/TLS connection
* schannel: SSL/TLS connection renegotiated
* schannel: remote party requests renegotiation
* schannel: renegotiating SSL/TLS connection
* schannel: SSL/TLS connection renegotiated
< HTTP/1.1 503 Service Unavailable
< content-length: 107
< cache-control: no-cache
< content-type: text/html
< 
<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>
* Connection #0 to host services.nvd.nist.gov left intact

**Comment by jeremylong** [comment]
you may have to run the curl command multiple times - due to load generated by the ODC users we are seeing a lot of 503 errors right now.

**Comment by proo4509** [comment]
ok, i did and the key seems to be recognized, but:

[WARN] NVD API request failures are occurring; retrying request for the 5 time
[INFO] Recoverable I/O exception (org.apache.hc.core5.http.ConnectionClosedException) caught when processing request to {s}->https://services.nvd.nist.gov:443
[WARN] NVD API request failures are occurring; retrying request for the 6 time
[WARN] NVD API request failures are occurring; retrying request for the 7 time
[WARN] NVD API request failures are occurring; retrying request for the 8 time
[WARN] NVD API request failures are occurring; retrying request for the 9 time
[WARN] NVD API request failures are occurring; retrying request for the 10 time
[INFO] Recoverable I/O exception (org.apache.hc.core5.http.ConnectionClosedException) caught when processing request to {s}->https://services.nvd.nist.gov:443
[WARN] NVD API request failures are occurring; retrying request for the 11 time
[ERROR] Error updating the NVD Data

**Comment by kajh** [comment]
We too see this `ConnectionClosedException`, but with dependency-check-maven 9.0.1.

**Comment by jeremylong** [comment]
for connection failures see #6149

**Comment by Siddhantmishraa** [comment]
> i am trying to add a newly created and activated NVD api key according to https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html It's not clear to me what is mandatory, but I've only tried -nvdApiKey since that's all i have (no username/password). I tried the key with and without quotes.
> 
> call ....\dependency-check.bat --nvdApiKey "***" ..... call ....\dependency-check.bat --nvdApiKey *** .....
> 
> Keep getting [WARN] An NVD API Key was not provided - it is highly recommended to use an NVD API key as the update can take a VERY long time without an API Key What am i doing wrong?

i'm getting the same warning. what did you do to solve it?

**Comment by zebasxx** [comment]
The same issue here, I get the warining even if I send the API key

**Comment by bourbonbourbon** [comment]
> The same issue here, I get the warining even if I send the API key

probably using an older version
