### ISSUE TITLE
[WARN] NVD API request failures are occurring; retrying request 

### ISSUE THREAD

**Issue by Edeniltonicbx** [dependency-check/DependencyCheck#6156]
[INFO] Recoverable I/O exception (javax.net.ssl.SSLHandshakeException) caught when processing request to {s}->[https://services.nvd.nist.gov:443](https://services.nvd.nist.gov/)
[WARN] NVD API request failures are occurring; retrying request for the 5 time
[INFO] Recoverable I/O exception (javax.net.ssl.SSLHandshakeException) caught when processing request to {s}->[https://services.nvd.nist.gov:443](https://services.nvd.nist.gov/)
[WARN] NVD API request failures are occurring; retrying request for the 6 time
[INFO] Recoverable I/O exception (javax.net.ssl.SSLHandshakeException) caught when processing request to {s}->[https://services.nvd.nist.gov:443](https://services.nvd.nist.gov/)
[WARN] NVD API request failures are occurring; retrying request for the 7 time
[INFO] Recoverable I/O exception (javax.net.ssl.SSLHandshakeException) caught when processing request to {s}->[https://services.nvd.nist.gov:443](https://services.nvd.nist.gov/)
[WARN] NVD API request failures are occurring; retrying request for the 8 time
[INFO] Recoverable I/O exception (javax.net.ssl.SSLHandshakeException) caught when processing request to {s}->[https://services.nvd.nist.gov:443](https://services.nvd.nist.gov/)

**Comment by jeremylong** [comment]
Yes, that means the NVD API requests are failing. We are working through the problem with the NVD.

**Comment by shekharclover** [comment]
same issue again [WARN] NVD API request failures are occurring; retrying request for the 10 time
