### ISSUE TITLE
Dependency Check CLI should have a way to error when finding Vulnerabilities

### ISSUE THREAD

**Issue by imbeyondboredom** [dependency-check/DependencyCheck#616]
We're trying to use the DependencyCheck CLI in our CI system but we'd like it to error when a vulnerability is found.

I've hacked something into our own repo but I'd be willing to clean it up and PR it if this sounds like a good feature.

I'm thinking a flag such as the following to match the gradle plugin:
--failBuildOnCVSS  (Specifies if the build should be failed if a CVSS score above a specified level is identified. The default is 11; since the CVSS scores are 0-10, by default the build will never fail.)

**Comment by stevespringett** [comment]
If you use Jenkins, you can add a publishing step that will automatically parse the DC result from the CLI and put the build in a warning or failed stated based on a number of criteria.

But for simple failures, yes, you can use the failBuildOnCVSS if you like.

**Comment by imbeyondboredom** [comment]
I created a PR for this if you guys want to include it: #619

**Comment by jeremylong** [comment]
Thanks! #619 was merged and will be included in the next release.
