### ISSUE TITLE
The absence of data/nvdcache folder in dependency-check 9.0.1

### ISSUE THREAD

**Issue by qw1212** [dependency-check/DependencyCheck#6168]
I recently noticed a change between versions 8.4.3 and 9.0.1. In version 8.4.3, during the scanning process, a data/nvdcache folder is downloaded. However, in version 9.0.1, I couldn't find the data/nvdcache folder anymore.
I'm wonder the reason behind this change. Can someone kindly explain the reason behind the removal of the data/nvdcache folder in the newer version?

![abc_1701222895884](https://github.com/jeremylong/DependencyCheck/assets/62467963/121325bb-4b4d-40dc-873c-eb17d9f24a48)

**Comment by jeremylong** [comment]
The nvdcache folder is no longer created as 9.x does not use the soon to be deprecated NVD data feeds.
