### ISSUE TITLE
CVE 2023-36052 azure

### ISSUE THREAD

**Issue by Dhanxy** [dependency-check/DependencyCheck#6171]
I have a confusion regarding the cve 2023-36052 vulnerability in azure.

i understand that it is mitigated by updating the azure cli to a version 2.53.1

however, we only have the azure messaging-eventhubs library incorporated in its lastest version and it continues to appear.

i dont understand how we can mitigate this if the cli is not taken  care of

**Comment by marcelstoer** [comment]
I feel you should follow #6100 and close this one.
