### ISSUE TITLE
Related to nvd api issues that persist - ask for more logging

### ISSUE THREAD

**Issue by hazendaz** [dependency-check/DependencyCheck#6173]
Most of the issues are closed and this is more to ask for a feature here or at least some debugging support.

Can you add some additional logging to allow users to see during debug that its actually reading the settings.xml and trying to do something with it?  We don't need details obviously but at least some acknowledgement that it detected nvdApiServerId and any number of the others, tried to decrypt it, maybe it was not decrypted but used as is.  That data would be helpful.  I've yet to get this to even work no matter how I try it and a lot of extra logging would be much appreciated prior to 9.0.2 release (and hopefully that is soon too given the missing classes around log4j-api and jcs3).

**Comment by hazendaz** [comment]
Using 9.0.1 with jdk21 for reference.  Consistently get 403.  I see the property values are registered correctly just not seeing that it went into the respective methods and worked as it should.

I have numerous of these first.

```
[INFO] Recoverable I/O exception (org.apache.hc.core5.http.ConnectionClosedException) caught when processing request to {s}->https://services.nvd.nist.gov:443
```

Then I get error with nvd data 403.

And finally no report at all of course.

**Comment by jeremylong** [comment]
1. Recoverable I/O exception can be ignored. It is just an informational message. In a future release I'll see what I can do about removing these.
2. To the original question - yes, turn on debug logging. For maven you can use `-X`, for gradle `--debug`, and for the CLI simply add `--log odc.log`.

**Comment by jeremylong** [comment]
Also, see #6149 for issues with the API

**Comment by hazendaz** [comment]
This was part of the reason for asking for more logging.  If you take a look in the code there is no logging at all when it goes through decryption from maven settings.  Some basic logging there in debug to show its in that area would be helpful.

I've already been running debug.  Yes there may well be issues with the nvd api but I'm not sure the setup is being picked up at this point short of me building this and debugging it directly.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by hazendaz** [comment]
I'm good now, after 9.0.2 release, the setup worked correctly without further issue so no need to add more logging.  Thanks for the 9.0.2 fixes.
