### ISSUE TITLE
Commandline seems to ignore proxy settings

### ISSUE THREAD

**Issue by UlrichLohrmann** [dependency-check/DependencyCheck#6175]
**Describe the bug**
I start OWASP dependency check from the commandline on a Linux box behind a firewall using the following command line:

dependency-check.sh -o '...' -f HTML -f XML --proxyserver '...' --proxyport '...' --nonProxyHosts '...' -s '...' --nvdApiKey '...' --nvdApiDelay '16000' --disableRetireJS --disableAssembly

The Linux box is allowed to access the proxy configured with --proxyhost and --proxyport. The provided API key is also valid.

When executing the command line the scan the OWASP dependecy tool starts but "hangs" with after following log output

[INFO] Region [NODEAUDIT] : Indexed Disk Cache is alive.
[INFO] Parsed regions [CENTRAL, POM, NODEAUDIT]
[INFO] Finished configuration in 61 ms.
[INFO] Checking for updates
--> Hangs here

I modified the dependency-check.sh and added the proxy settings using standard java system properties.
.
  -Dbasedir="$BASEDIR" \
  -Dhttp.proxyHost="..." \
  -Dhttp.proxyPort="..." \
  -Dhttp.nonProxyHosts="..." \
  org.owasp.dependencycheck.App \
.

Same effect. Last log output is "Checking for update", then hangs.

I checked with our firewall admins and they told me that dependency check tries to access NVD data feed in AWS cloud directly without using the proxy.

**Version of dependency-check used**
The problem occurs using version 9.0.1 of the cli

**To Reproduce**
Execute dependency check from a Linux box behind a firewall

**Expected behavior**
Proxy settings provided by the commandline work.

Best regards
Ulrich

**Comment by Spanish93** [comment]
Duplicate and already answered:

https://github.com/jeremylong/DependencyCheck/issues/6127

**Comment by jeremylong** [comment]
I'll work on the docs (and removing the unused options) for the proxy next week. For now see #6127.
