### ISSUE TITLE
How to utilize cache the properties used by maven in offline version. 

### ISSUE THREAD

**Issue by MajoMarian** [dependency-check/DependencyCheck#6183]
Hello, 
I have a question if it is possible to setup somehow the cache properties used by maven in offline version? 
By design we are not able to connect to the internet and we are getting **[ERROR] Unable to download the NVD API cache.properties**.

Thank you very much 

Best regards
Marian

**Comment by jeremylong** [comment]
How do you have an internal cache of the NVD data? We can support other mechanisms - but right now the [vulnz CLI](https://github.com/jeremylong/Open-Vulnerability-Project/tree/main/vulnz#caching-the-nvd-cve-data) can be used to create a cache of the NVD which can then be used in more restricted environments.

Additionally, in your current mechanism - what version of the schema are you using?

**Comment by MajoMarian** [comment]
We use Vulnz to create offline copy of the data and store it on internal server, set the property to utilize it in Maven, but seemingly there is no property for Maven to use for the cache.properties file - even though its part of the local repository where the NVD files are stored  i.e.  <nvdDatafeedUrl>https://<internal-server-adress>/nvdcve-{0}.json.gz</nvdDatafeedUrl>

**Comment by jeremylong** [comment]
you don't need to specify the cache.properties. It trims the nvdcve-{0}.json.gz off of the URI and adds cache.properties. It should all happen seamlessly.

**Comment by MajoMarian** [comment]
In our configuration we setup the dependency check with following configuration but is seems that it is trying to download the data from the internet and if we set <autoupdate> to false it will fail -> cannot find the local db. 
configuration
            nvdDatafeedUrl>link/nvdcve-{0}.json.gz</nvdDatafeedUrl
configuration

Could you advise why the configuration is disregarding the specified URL? 

Thanks

**Comment by jeremylong** [comment]
Could you provide your configuration and the command used to execute maven?

**Comment by jeremylong** [comment]
just saying link/nvd... doesn't tell me much. what protocol is on the link? where in the pom is this configuration? are you configuring the plugin in the build plugins and running the plugin as a report? without details I can't answer why this isn't working for you.

**Comment by Muskan-0618** [comment]
Getting the same error:- **Unable to download the NVD API cache.properties**.
Installed the latest version of dependency check(9.0.2) and have created the offline copy of NVD-API data using Vulnz and stored it in a github repo.
Now on trying to use this command - ./dependency-check/bin/dependency-check --updateonly --data NVD-API-DATA-FEED/ --nvdDatafeed ‘github repo url/blob/main/nvdcve-{0}.json.gz’

getting this error:- 

[ERROR] Unable to download the NVD API cache.properties
org.owasp.dependencycheck.data.update.exception.UpdateException: Unable to download the NVD API cache.properties
	at org.owasp.dependencycheck.data.update.NvdApiDataSource.getRemoteCacheProperties(NvdApiDataSource.java:548)
	at org.owasp.dependencycheck.data.update.NvdApiDataSource.processDatafeed(NvdApiDataSource.java:130)
	at org.owasp.dependencycheck.data.update.NvdApiDataSource.update(NvdApiDataSource.java:108)
	at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:906)
	at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:878)
	at org.owasp.dependencycheck.App.runUpdateOnly(App.java:427)
	at org.owasp.dependencycheck.App.run(App.java:172)
	at org.owasp.dependencycheck.App.main(App.java:89)
Caused by: org.owasp.dependencycheck.utils.ResourceNotFoundException: Requested resource does not exist - received a 404
	at org.owasp.dependencycheck.utils.HttpResourceConnection.obtainConnection(HttpResourceConnection.java:233)
	at org.owasp.dependencycheck.utils.HttpResourceConnection.fetch(HttpResourceConnection.java:163)
	at org.owasp.dependencycheck.utils.Downloader.fetchContent(Downloader.java:183)
	at org.owasp.dependencycheck.data.update.NvdApiDataSource.getRemoteCacheProperties(NvdApiDataSource.java:541)
	... 7 common frames omitted

**Comment by MajoMarian** [comment]
We have central POM file which configures different plugins, the configuration specific to maven/dependency check is following (picture). It is run via following command: mvn dependency-check:aggregate -Ddependency-check.centraldb=true 
![Configuration](https://github.com/jeremylong/DependencyCheck/assets/142199624/679c2a97-a555-4c64-adae-f471ebdbf389)

**Comment by jeremylong** [comment]
can you succesfully run `curl https://internal-server/cache/cache.properties`?

**Comment by MajoMarian** [comment]
yes the curl is working.

**Comment by jeremylong** [comment]
I'm betting the issue is that you can't really host these files in a github repo - unless you hosted it on gh-pages.

```
--nvdDatafeed ‘github repo url/blob/main/nvdcve-{0}.json.gz’
```

I haven't ever tried just hosting them in a repo like that.

**Comment by MajoMarian** [comment]
We are not using the GitHub. We are storing the NIST files in c:\inetpub\wwwroot folder and the NIST files are reachable via website (IIS). Maybe the problem will be the https protocol but on another hand inside the Jenkins logs I cannot see the problem with SSL. And the funny part is that the old dependency check is working without problem.

**Comment by jeremylong** [comment]
The old dependency-check is using a different cache right?

**Comment by MajoMarian** [comment]
Okay we found the issue. The problem was inside the IIS. IIS did not allow us to open/read .properties file(s). So we added inside the MIME types extension (.properties). Now everything is working.
