### ISSUE TITLE
Any way to configure mojo.properties at runtime?

### ISSUE THREAD

**Issue by theangrydev** [dependency-check/DependencyCheck#6184]
I notice that `mojo.properties` has quite a few properties that are not exposed by the Maven plugin. 

Is there any way to provide this at runtime to the plugin? 

I guess adding a `<dependency>` inside the `<plugin>` might work to add another item to the classpath, but would require building a JAR just for this purpose.

**Comment by jeremylong** [comment]
At the moment, no. But if you set the value as an environment variable ODC will pick that up. What properties do you want to change?

**Comment by theangrydev** [comment]
I was hoping to be able to set the `cve.cpe.startswith.filter`

**Comment by jeremylong** [comment]
Wtih 9.0.0 this is no longer used and should have been removed from the properties files.  In earlier versions there was something like a `startYear` argument that could have been - but due to changes, this is no longer present.

**Comment by jeremylong** [comment]
What did you want to change with the starts with filter?

**Comment by theangrydev** [comment]
I noticed the recent issues with the NVD API and this seemed to be a key parameter, end goal is/was to stabilise my CI builds that use the plugin, that are currently failing due to intermittent HTTP error issues with the NVD API

**Comment by jeremylong** [comment]
9.0.2 should be fine now.
