### ISSUE TITLE
9.0.1 vs 9.0.2 -> +100.000 NVD API records

### ISSUE THREAD

**Issue by somera** [dependency-check/DependencyCheck#6186]
Hi,

how can I explain this?

9.0.1
```
[INFO] NVD API has 174.xxx records in this update
...
...
```

9.0.2:
```
[INFO] NVD API has 231.934 records in this update
[INFO] Downloaded 10.000/231.934 (4%)
[INFO] Downloaded 20.000/231.934 (9%)
[INFO] Downloaded 30.000/231.934 (13%)
```

The +100.000 records?

**Comment by sellersj** [comment]
With 9.0.2 they removed a filter on the API side. I'm assuming the tool now just downloads everything client side and will do any filtering on the dependency check side.

I've not had a chance to run it yet. Is it taking up significantly more disk space?

**Comment by jeremylong** [comment]
@sellersj correct - the CPE filter used by 9.0.1 was causing performance degradation on the API.

**Comment by somera** [comment]
> I've not had a chance to run it yet. Is it taking up significantly more disk space?

121MB after the download.

**Comment by somera** [comment]
thx.
