### ISSUE TITLE
Build failure with Gradle v.7.5 and ODC v.9

### ISSUE THREAD

**Issue by jazzshu** [dependency-check/DependencyCheck#6189]
## Describe the bug
Just upgraded to version 9.0.2, and it works fine on local environment where I have Gradle v.8.2.1 but it breaks on my Gitlab CI pipeline where I'm running Gradle v.7.5.
When I downgrade to version < 9 the issue doesn't occur but obviously we need to upgrade to the newer version as per the documentation. 

So the problems presents itself in ODC at  > v.9 as it tries to download a jackson-core jar at v.2.16.0. 

When checking logs in the pipeline at ODC < v.9 the jackson-core jar that it downloads is at v.2.15.0 and no problem occurs and pipeline has green light.

So I presume it has to be due to the Gradle version of the Gitlab pipeline and the jackson-core version it tries to download. 
I would need a confirmation from someone before requesting an upgrade in Gradle version in the pipeline as I have to involve other teams to do so. 

## Version of dependency-check used
The problem occurs using version > 9.

## Log file

FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring root project 'xxx-xxx'.
> java.util.concurrent.ExecutionException: org.gradle.api.GradleException: Failed to create Jar file /root/.gradle/caches/jars-9/ba626f7cb60d9f2c5700e92659afafa9/jackson-core-2.16.0.jar.

## To Reproduce
1. Use version > 9 of ODC plugin in gradle
2. Run a gradle build with Gradle v.7.5

## Expected behavior
Build should be successful and produce a ODC report but instead it fails with the error mentioned above

**Comment by jazzshu** [comment]
I confirm that you need version > 8 of Gradle to run ODC version > 9. 
I'll close this issue

**Comment by jeremylong** [comment]
9.0.2 corrects the problem described above. You should be able to use gradle 7.5 and ODC 8.9.2. Re-open this ticket if you can't

**Comment by ChavalBR** [comment]
I have the same problem, with ODC 9.02, jackson-core 2.0.16, java 17, gradle 7.6.
Error on gradle build:
'void com.fasterxml.jackson.core.base.GeneratorBase.<init>(int, com.fasterxml.jackson.core.ObjectCodec, com.fasterxml.jackson.core.io.IOContext)'

**Comment by jazzshu** [comment]
@Noed it is a known bug in gradle v.7 https://github.com/gradle/gradle/issues/24390
The simplest and effective solution it to upgrade to gradle v.8.x.x
