### ISSUE TITLE
Documentation doesn't list all reportgenerators

### ISSUE THREAD

**Issue by rddesmond** [dependency-check/DependencyCheck#6194]
**Describe the bug**
Dependency checker is great!  Small help and documentation thing I noticed.  Documentation (`--help`, `*.md`, etc) doesn't list all report formats.

**Version of dependency-check used**
The problem occurs using version 9.0.2 of the cli, but it's observed in the source at several more places.

**Log file**
```
usage: Dependency-Check Core [--advancedHelp] [--enableExperimental]
       [--exclude <pattern>] [-f <format>] [--failOnCVSS <score>] [-h]
       [--junitFailOnCVSS <score>] [-l <file>] [-n] [--nvdApiKey <apiKey>]
       [-o <path>] [--prettyPrint] [--project <name>] [-s <path>]
       [--suppression <file>] [-v]

Dependency-Check Core can be used to identify if there are any known CVE
vulnerabilities in libraries utilized by an application. Dependency-Check
Core will automatically update required data from the Internet, such as
the CVE and CPE data files from nvd.nist.gov.

...
 -f,--format <format>           The report format (HTML, XML, CSV, JSON,
                                JUNIT, SARIF, JENKINS, or ALL). The
                                default is HTML. Multiple format
                                parameters can be specified.
```

**To Reproduce**
1. Start the CLI with `--help`
2. Observe the list of formats enumerated next to `-f,--format <format>`

**Expected behavior**
The help should show all ReportGenerator formats at https://github.com/jeremylong/DependencyCheck/blob/main/core/src/main/java/org/owasp/dependencycheck/reporting/ReportGenerator.java, but it doesn't show `GITLAB`.

**Additional context**
If you search the source for this list (I found it easiest to search for https://github.com/search?q=repo%3Ajeremylong%2FDependencyCheck+CSV%2C&type=code), it shows up in several places in the documentation.  Some are missing several formats, but they are all incomplete.

**Comment by rddesmond** [comment]
I was reading through https://github.com/jeremylong/DependencyCheck/issues/6187 and one of the suggestions was to enumerate the report types that you want.  I noticed that they weren't all listed in help.

**Comment by jeremylong** [comment]
Thanks for pointing this out.

**Comment by rddesmond** [comment]
Updated link in my description.  I originally used "`SARIF`" to find the list of report formats in the code, but using "`CSV,`" is more effective.

https://github.com/search?q=repo%3Ajeremylong%2FDependencyCheck+CSV%2C&type=code
