### ISSUE TITLE
Any way to skip directory?

### ISSUE THREAD

**Issue by ismailengin** [dependency-check/DependencyCheck#6198]
Is there a way to make the cli tool to skip a directory entirely? I am trying to scan with "dir/**/*.jar" path pattern but since we have a folder (let's say called foo) under "dir" that contains like hundreds of directories which i am certain that they wont contain any jar files, i want tool to skip "dir/fool" directory completely. Otherwise script runs for more than 3-4h which causes timeout from our remote host. 

I tried using exclude but seems like exclude doesn't make the tool skip directory, it still scans just doesn't include files in report(?).

**Comment by jeremylong** [comment]
how are you specifying the exclude? It use Ant style glob patterns:

```
--exclude=dir/foo/**/*
```

**Comment by ismailengin** [comment]
I was trying to exclude two directories like below:

$exclude_string="--exclude **/audit/** --exclude **/session/**";

**Comment by jeremylong** [comment]
I might try:

$exclude_string="--exclude /audit/**/* --exclude /session/**/*";

**Comment by ismailengin** [comment]
tried your suggestion, didnt change process total time.

my guess is that ant exclude doesn't skip directories, it still scans those directories and subdirectories but just excludes them from final dir tree so process total time doesnt change? my workaround for now is just giving directories that I want to scan with multiple -s parameters instead of exclude approach

**Comment by jeremylong** [comment]
that is likely what is happening. Sorry you ran into this problem. Glad you found a solution.
