### ISSUE TITLE
[FP]: r2dbc-mssql confused for Microsoft SQL Server itself

### ISSUE THREAD

**Issue by chadlwilson** [dependency-check/DependencyCheck#6199]
### Package URl

pkg:maven/io.r2dbc/r2dbc-mssql@0.9.0.RELEASE 

### CPE

`cpe:2.3:a:microsoft:sql_server:0.9.0:release:*:*:*:*:*:*`

### ODC Integration

{"label"=>"Gradle Plugin"}

### ODC Version

9.0.2

### Description

The R2DBC MS SQL Server driver is not the same thing as Microsoft SQL Server itself :-)

**Comment by aikebah** [comment]
approved
