### ISSUE TITLE
Not able to update NVE CVE data. i am working with proxy. after run the script i dont have the cert error but got HTTP head error while update . I also used to stop HEAD by mvn -Ddownloader.quick.query.timestamp=false. but it din't work for me. 

### ISSUE THREAD

**Issue by pankaj-14** [dependency-check/DependencyCheck#620]
### Reporting Bugs/Errors
When reporting errors, 99% of the time log file output is required. Please post the log file as a [gist](https://gist.github.com/) and provide a link in the new issue.

### Reporting False Positives
When reporting a false positive please include:
- The location of the dependency (Maven GAV, URL to download the dependency, etc.)
- The CPE that is believed to be false positive
  - Please report the CPE not the CVE

#### Example
False positive on library foo.jar - reported as cpe:/a:apache:tomcat:7.0
```xml
<dependency>
   <groupId>org.sample</groupId>
   <artifactId>foo</artifactId>
   <version>1.0</version>
</dependency>
```

**Comment by jeremylong** [comment]
Very detailed issue title - however, as the issue template suggests we'll need the log to assist in debugging your issue.

**Comment by pankaj-14** [comment]
Hi Jeremy,

I am using proxy. without proxy script is working fine for me. But I need it with the proxy. can you please tell me the process how I configure it with my proxy url. I checked th NVE site and my proxy is able to download package from this site. But when I run this is script it will not update and gives the error. Can you please tell me the site links from where script hits for update . So that I can whitelist those site in my proxy.

Thanks

**Comment by jeremylong** [comment]
Look for the cveUrl12Modified argument on
http://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html.
The four urls used are listed.  Note that the %d in two of the urls are
replaced with 2002-2016.

-Jeremy

**Comment by neerajv** [comment]
Hi Jeremylong,

I tried running  https://github.com/stevespringett/nist-data-mirror/blob/master/src/NistDataMirror.java .
It did not fetch me the desired output. But Wget on the same URL is working well.
Please see the following logs : -

[root@chefserver src]# java NistDataMirror /tmp/mydata
Downloading files at Fri Nov 25 17:47:31 IST 2016
Downloading https://nvd.nist.gov/download/nvdcve-Modified.xml.gz
Download failed : Connection reset
Downloading https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-Modified.xml.gz
Download failed : Connection reset
Downloading https://nvd.nist.gov/download/nvdcve-2002.xml.gz
Download failed : Connection reset
Downloading https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2002.xml.gz
Download failed : Connection reset
Downloading https://nvd.nist.gov/download/nvdcve-2003.xml.gz
Download failed : Connection reset
Downloading https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2003.xml.gz
Download failed : Connection reset
Downloading https://nvd.nist.gov/download/nvdcve-2004.xml.gz
Download failed : Connection reset
Downloading https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2004.xml.gz
Download failed : Connection reset
Downloading https://nvd.nist.gov/download/nvdcve-2005.xml.gz
Download failed : Connection reset
Downloading https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2005.xml.gz
Download failed : Connection reset
Downloading https://nvd.nist.gov/download/nvdcve-2006.xml.gz
Download failed : Connection reset
Downloading https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2006.xml.gz
Download failed : Connection reset
Downloading https://nvd.nist.gov/download/nvdcve-2007.xml.gz
Download failed : Connection reset
Downloading https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2007.xml.gz
Download failed : Connection reset
Downloading https://nvd.nist.gov/download/nvdcve-2008.xml.gz
Download failed : Connection reset
Downloading https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2008.xml.gz
Download failed : Connection reset
Downloading https://nvd.nist.gov/download/nvdcve-2009.xml.gz
Download failed : Connection reset
Downloading https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2009.xml.gz
Download failed : Connection reset
Downloading https://nvd.nist.gov/download/nvdcve-2010.xml.gz
Download failed : Connection reset
Downloading https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2010.xml.gz
Download failed : Connection reset
Downloading https://nvd.nist.gov/download/nvdcve-2011.xml.gz
Download failed : Connection reset
Downloading https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2011.xml.gz
Download failed : Connection reset
Downloading https://nvd.nist.gov/download/nvdcve-2012.xml.gz
Download failed : Connection reset
Downloading https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2012.xml.gz
Download failed : Connection reset
Downloading https://nvd.nist.gov/download/nvdcve-2013.xml.gz
Download failed : Connection reset
Downloading https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2013.xml.gz
Download failed : Connection reset
Downloading https://nvd.nist.gov/download/nvdcve-2014.xml.gz
Download failed : Connection reset
Downloading https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2014.xml.gz
Download failed : Connection reset
Downloading https://nvd.nist.gov/download/nvdcve-2015.xml.gz
Download failed : Connection reset
Downloading https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2015.xml.gz
Download failed : Connection reset
Downloading https://nvd.nist.gov/download/nvdcve-2016.xml.gz
Download failed : Connection reset
Downloading https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2016.xml.gz
Download failed : Connection reset

WGET :- 

[root@chefserver src]# wget https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2016.xml.gz
--2016-11-25 17:48:25--  https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2016.xml.gz
Resolving nvd.nist.gov... 129.6.13.177, 2610:20:6005:13::177
Connecting to nvd.nist.gov|129.6.13.177|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1401344 (1.3M) [application/x-gzip]
Saving to: “nvdcve-2.0-2016.xml.gz”

100%[==============================================================================================================================>] 1,401,344    300K/s   in 4.6s

2016-11-25 17:48:32 (300 KB/s) - “nvdcve-2.0-2016.xml.gz” saved [1401344/1401344]

Also please tell if some how I get all the files where shall I club n place them ?  Or I need to copy them each to "data" folder ?

Thanks,
Neeraj Virmani

**Comment by jeremylong** [comment]
First, what version of Java and dependency-check are you using? Oracle JRE
8, OpenJDK 8, etc.? dependency-check 1.4.2 (1.4.4 is the latest)?

Regarding creating a local mirror of the NVD see this:
http://jeremylong.github.io/DependencyCheck/data/mirrornvd.html

--Jeremy

**Comment by neerajv** [comment]
Hi,

After i did as wrote on :-  http://jeremylong.github.io/DependencyCheck/data/mirrornvd.html

I was able to download :- 
**Command :-** 
sh nvd_download.sh NVD /tmp/neeraj/nist-data-mirror/build/libs

NVD is target folder and /tmp/neeraj/nist-data-mirror/build/libs is path of jar file “nist-data-mirror-1.0.0.jar”

[root@gitlabserver 2016-11-28]# hostname -i
10.5.3.182
[root@gitlabserver 2016-11-28]# pwd
/tmp/neeraj/NVD/2016-11-28
[root@gitlabserver 2016-11-28]# ls
dc.h2.db            nvdcve-2008.xml.gz  nvdcve-2015.xml.gz      nvdcve-2.0-2007.xml.gz  nvdcve-2.0-2014.xml.gz
nvdcve-2002.xml.gz  nvdcve-2009.xml.gz  nvdcve-2016.xml.gz      nvdcve-2.0-2008.xml.gz  nvdcve-2.0-2015.xml.gz
nvdcve-2003.xml.gz  nvdcve-2010.xml.gz  nvdcve-2.0-2002.xml.gz  nvdcve-2.0-2009.xml.gz  nvdcve-2.0-2016.xml.gz
nvdcve-2004.xml.gz  nvdcve-2011.xml.gz  nvdcve-2.0-2003.xml.gz  nvdcve-2.0-2010.xml.gz  nvdcve-2.0-Modified.xml.gz
nvdcve-2005.xml.gz  nvdcve-2012.xml.gz  nvdcve-2.0-2004.xml.gz  nvdcve-2.0-2011.xml.gz  nvdcve-Modified.xml.gz
nvdcve-2006.xml.gz  nvdcve-2013.xml.gz  nvdcve-2.0-2005.xml.gz  nvdcve-2.0-2012.xml.gz
nvdcve-2007.xml.gz  nvdcve-2014.xml.gz  nvdcve-2.0-2006.xml.gz  nvdcve-2.0-2013.xml.gz


**I am facing this issue : -**

**[root@gitlabserver neeraj]# sh dep-check-date.sh "NVD" "11/28/2016" --project virmani -s "/tmp/neeraj/my_code"**
[INFO] Checking for updates
Exception in thread "main" java.lang.IllegalArgumentException: URI has an authority component
        at java.io.File.<init>(File.java:423)
        at org.owasp.dependencycheck.utils.Downloader.getLastModified(Downloader.java:249)
        at org.owasp.dependencycheck.utils.Downloader.getLastModified(Downloader.java:228)
        at org.owasp.dependencycheck.data.update.nvd.UpdateableNvdCve.add(UpdateableNvdCve.java:101)
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.retrieveCurrentTimestampsFromWeb(NvdCveUpdater.java:330)
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.getUpdatesNeeded(NvdCveUpdater.java:259)
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:79)
        at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:678)
        at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:489)
        at org.owasp.dependencycheck.App.runScan(App.java:272)
        at org.owasp.dependencycheck.App.run(App.java:164)
        at org.owasp.dependencycheck.App.main(App.java:69)


With NoUpdate :- 

**[root@gitlabserver neeraj]# sh dep-check-date.sh "NVD" "11/28/2016" --project virmani -s "/tmp/neeraj/my_code" --noupdate**
[ERROR] No documents exist

Unable to continue dependency-check analysis.
[ERROR] One or more fatal errors occurred
[ERROR] No documents exist

==========
My env :- 
Java :- 1.8.0_91
Dependency Check version :- 1.4.4

Thanks,
Neeraj Virmani

**Comment by jeremylong** [comment]
As mentioned in the other issue - I have no idea what is in you script. However, it appears that the URL is incorrect; try googling for "URI has an authority component".

**Comment by neerajv** [comment]
I have only copied the scripts provided on the link u suggested http://jeremylong.github.io/DependencyCheck/data/mirrornvd.html You can check the script there.

Thanks

**Comment by neerajv** [comment]
The Data folder should have some old database from any previous run to resolve the issue of " No documents exist"

For URI :- there has to be an extra / in the file , ie  
--cveUrl20Modified file:///NVD/2016-11-28/nvdcve-2.0-Modified.xml.gz       CORRECT

--cveUrl20Modified file://NVD/2016-11-28/nvdcve-2.0-Modified.xml.gz         INCORRECT

Thanks,
Neeraj Virmani

**Comment by pankaj-14** [comment]
Hi jeremylong,

I am behind proxy and not able to update NVD data. I am executing following command : 
./dependency-check.sh --app "project_name" -scan "my_code_location" --proxyserver "proxy_url" --proxyport "port_number" --log "log_location" 
Please let me know what I am missing. 

While finding other options, I also try with mirror NVD data and facing same issue.
I am able to download NVD gzip file by directly putting url in browser. in Browser proxy is configured.

Please tell me what should I add above script for proxy.

**Comment by jeremylong** [comment]
@pankaj-14 couple of questions:

1. Does your proxy require authentication?
2. Are you specifying anything other then the server name in the `proxyserver` parameter (i.e. there is no http://)?
3. Does running something like the following work?

```
curl -x http://proxy_server:proxy_port https://nvd.nist.gov/download/nvdcve-Modified.xml.gz
```

**Comment by hktalent** [comment]
mac os x
cd /usr/local/Cellar/dependency-check/nist-data-mirror

wget https://nvd.nist.gov/download/nvdcve-2002.xml.gz &
wget https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2002.xml.gz &
wget https://nvd.nist.gov/download/nvdcve-2003.xml.gz &
wget https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2003.xml.gz &
wget https://nvd.nist.gov/download/nvdcve-2004.xml.gz &
wget https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2004.xml.gz &
wget https://nvd.nist.gov/download/nvdcve-2005.xml.gz &
wget https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2005.xml.gz &
wget https://nvd.nist.gov/download/nvdcve-2006.xml.gz &
wget https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2006.xml.gz &
wget https://nvd.nist.gov/download/nvdcve-2007.xml.gz &
wget https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2007.xml.gz &
wget https://nvd.nist.gov/download/nvdcve-2008.xml.gz &
wget https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2008.xml.gz &
wget https://nvd.nist.gov/download/nvdcve-2009.xml.gz &
wget https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2009.xml.gz &
wget https://nvd.nist.gov/download/nvdcve-2010.xml.gz &
wget https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2010.xml.gz &
wget https://nvd.nist.gov/download/nvdcve-2011.xml.gz &
wget https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2011.xml.gz &
wget https://nvd.nist.gov/download/nvdcve-2012.xml.gz &
wget https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2012.xml.gz &
wget https://nvd.nist.gov/download/nvdcve-2013.xml.gz &
wget https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2013.xml.gz &
wget https://nvd.nist.gov/download/nvdcve-2014.xml.gz &
wget https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2014.xml.gz &
wget https://nvd.nist.gov/download/nvdcve-2015.xml.gz &
wget https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2015.xml.gz &
wget https://nvd.nist.gov/download/nvdcve-2016.xml.gz &
wget https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2016.xml.gz &
gunzip -Nqr *.gz

**Comment by stevespringett** [comment]
Refer to https://jeremylong.github.io/DependencyCheck/data/mirrornvd.html for information on how to mirror the NVD. Once you have a local mirror, you can point Dependency-Check to the mirror.

**Comment by pankaj-14** [comment]
@jeremylong it works for me now. Thanks for your Support.
