### ISSUE TITLE
Where did cveValidForHours go with 9.x? (gradle)

### ISSUE THREAD

**Issue by EugenMayer** [dependency-check/DependencyCheck#6222]
Checked the release notes and could not find that i has been removed. I get

```
 Could not set unknown property 'cveValidForHours' for extension 'dependencyCheck' of type org.owasp.dependencycheck.gradle.extension.DependencyCheckExtension
```

by setting

```
dependencyCheck {
    cveValidForHours = 24
}
```

This used to work in 8.x and as far as i check the docs https://jeremylong.github.io/DependencyCheck/dependency-check-gradle/configuration.html i find 

```
dependencyCheck {
    autoUpdate=false
    cveValidForHours=1
    format='ALL'
}
```

I see there is `nvd.validForHours` and `hostedSuppressions.validForHours` which might be the way to now replace the value above? Could someone clarify? Thank you!

**Comment by jeremylong** [comment]
Correct, `nvd.validForHours` is the current configuration setting. Note, this may not have the desired affect until 9.0.3 is released as I noticed a small issue (see https://github.com/jeremylong/DependencyCheck/pull/6225)
