### ISSUE TITLE
Maven proxy settings not honored by NvdCveClientBuilder in NvdApiDataSource

### ISSUE THREAD

**Issue by akuhtz** [dependency-check/DependencyCheck#6230]
**Describe the bug**
The maven proxy settings not honored by NvdCveClientBuilder in NvdApiDataSource. This causes connect timeout when the rest call is made behind a proxy.

**Version of dependency-check used**
The problem occurs using version 9.0.2 of the maven plugin.

**Expected behavior**
Maven proxy settings are used to configure the proxy in NvdCveClientBuilder.

**Additional context**
Current workaround: Set the proxy host and port as system properties.
`-Dhttps.proxyHost=<my-proxy-host> -Dhttps.proxyPort=<my-proxy-port>`

**Comment by jeremylong** [comment]
https://github.com/jeremylong/DependencyCheck/issues/6127
