### ISSUE TITLE
Dependency-Check v9 now require Internet connectivity to get NVDs?

### ISSUE THREAD

**Issue by haxorof** [dependency-check/DependencyCheck#6231]
In Dependency-Check v8 and earlier it was possible to have hosts running dependency-check but itself do not have any Internet connectivity. Instead its configuration for NVDs etc points to "internal centralized cache", see picture below:
![image](https://github.com/jeremylong/DependencyCheck/assets/11457642/d2ce9dd1-b881-4e3e-9e4e-595f2ff5f7b7)

Is it that in Dependency-Check v9 this use-case is no longer supported? What I have tested so far with latest version of Maven dependency-check plugin I cannot see a configuration that keep things updated but do not use the NVD API but downloads from some other location. As of today I have a cronjob to download the NVDs and publish those internally via a web server for other host to point its dependency-check configuration to.

**Comment by jeremylong** [comment]
various solutions:

1. Use the [vulnz cli](https://github.com/jeremylong/Open-Vulnerability-Project/tree/main/vulnz#caching-the-nvd-cve-data) to create an internal nvd data feed (*.json.gz files) and configure your agents to update based on the data feed.
2. Use one node with internet access to create the `data` directory and then archive the data directory and copy the directory out to each scanning node. Documentation is still being worked on: https://github.com/jeremylong/DependencyCheck/pull/6220

**Comment by haxorof** [comment]
Thanks!
I have tested now to use the vulnz cli on the node which got the Internet access and it worked and then configured Maven dependency-check plugin having nvdDatafeedUrl pointing to the internal URL where they are exposed. Then it is all good again. 🙂
