### ISSUE TITLE
maven documentation site not being updated after version 8.2.1

### ISSUE THREAD

**Issue by sellersj** [dependency-check/DependencyCheck#6241]
**Describe the bug**
Some of the documentation seems to be correctly updated (shows version 9.0.3)
https://jeremylong.github.io/DependencyCheck/index.html
But any any of the pages under the "goals" section (at least) seem to be the from 8.2.1
https://jeremylong.github.io/DependencyCheck/dependency-check-maven/plugin-info.html

**Version of dependency-check used**
9.0.3 maven (?)

**Log file**
n/a

**To Reproduce**
1. Go to ['...'](https://jeremylong.github.io/DependencyCheck/dependency-check-maven/plugin-info.html)
2. Check the version in the upper right

**Expected behavior**
Should show the currently released version

**Additional context**
n/a

**Comment by jeremylong** [comment]
Yeah... sorry about that. They changed the reporting plugin and in the auto-updates from dependabot I missed that we needed to change the plugin.  

Thanks for catching this! The site will be updated during the next release - which given what has been going on with the NVD i expect to be soon.

**Comment by sellersj** [comment]
No worries. Thanks for all your hard work.
