### ISSUE TITLE
[FP]: jruby-rack is not the same as rack itself

### ISSUE THREAD

**Issue by chadlwilson** [dependency-check/DependencyCheck#6242]
### Package URl

pkg:maven/org.jruby.rack/jruby-rack@1.1.22

### CPE

`cpe:2.3:a:rack_project:rack:1.1.22:*:*:*:*:*:*:*`

### ODC Integration

{"label"=>"Gradle Plugin"}

### ODC Version

9.0.3

### Description

The jruby-rack project at https://github.com/jruby/jruby-rack is a different thing to the Ruby rack project at https://github.com/rack/rack (the first is a Java/JRuby native adapter for the latter)

**Comment by aikebah** [comment]
approved
