### ISSUE TITLE
KrbException: Cannot locate default realm

### ISSUE THREAD

**Issue by Casperxian** [dependency-check/DependencyCheck#6247]
**Describe the issue**
Whenever i run dependencyCheckAnalyze, it will give out the error shown below and will loop for a certain amount of times before generating the report. The task runs successfully but the error is causing it to make it run >10 minutes. 
I have never gotten KrbException before version < 9

**Version of dependency-check used**
The problem occurs using version 9.0.3 of the gradle

> Task :dependencyCheckAnalyze
Verifying dependencies for project AccessCheck
Checking for updates and analyzing dependencies for vulnerabilities

ex-0000000129 Negotiate{FAILED } authentication error: Invalid name provided (Mechanism level: KrbException: Cannot locate default realm)
ex-0000000130 Negotiate{FAILED } authentication error: Invalid name provided (Mechanism level: KrbException: Cannot locate default realm)
ex-0000000132 Negotiate{FAILED } authentication error: Invalid name provided (Mechanism level: KrbException: Cannot locate default realm)
ex-0000000131 Negotiate{FAILED } authentication error: Invalid name provided (Mechanism level: KrbException: Cannot locate default realm)
ex-0000000133 Negotiate{FAILED } authentication error: Invalid name provided (Mechanism level: KrbException: Cannot locate default realm)
ex-0000000134 Negotiate{FAILED } authentication error: Invalid name provided (Mechanism level: KrbException: Cannot locate default realm)
ex-0000000135 Negotiate{FAILED } authentication error: Invalid name provided (Mechanism level: KrbException: Cannot locate default realm)
ex-0000000136 Negotiate{FAILED } authentication error: Invalid name provided (Mechanism level: KrbException: Cannot locate default realm)
ex-0000000137 Negotiate{FAILED } authentication error: Invalid name provided (Mechanism level: KrbException: Cannot locate default realm)
ex-0000000138 Negotiate{FAILED } authentication error: Invalid name provided (Mechanism level: KrbException: Cannot locate default realm)
ex-0000000139 Negotiate{FAILED } authentication error: Invalid name provided (Mechanism level: KrbException: Cannot locate default realm)
ex-0000000140 Negotiate{FAILED } authentication error: Invalid name provided (Mechanism level: KrbException: Cannot locate default realm)
.
ex-0000000245 Negotiate{FAILED } authentication error: Invalid name provided (Mechanism level: KrbException: Cannot locate default realm)
.
.
 Task :dependencyCheckAnalyze
Generating report for project AccessCheck
Found 117 vulnerabilities in project AccessCheck

To Reproduce
runs "./gradlew dependencyCheckAnalyze"

Expected behavior
 Report generated without KrbException

**Comment by jeremylong** [comment]
I'd google the error message. It looks like a configuration file is missing for something unrelated to dependency-check.
