### ISSUE TITLE
maven:9.0.3 download not working

### ISSUE THREAD

**Issue by sysmat** [dependency-check/DependencyCheck#6248]
**Describe the bug**
- it download for more then 15minutes and then hang out

**Version of dependency-check used**
- maven:3.95
- org.owasp:dependency-check-maven:9.0.3

**Log file**
```
141285 [INFO] Downloaded 10,000/232,428 (4%)
223204 [INFO] Downloaded 20,000/232,428 (9%)
325588 [INFO] Downloaded 30,000/232,428 (13%)
463286 [INFO] Downloaded 40,000/232,428 (17%)
608630 [INFO] Downloaded 50,000/232,428 (22%)
699325 [INFO] Downloaded 60,000/232,428 (26%)
774549 [INFO] Downloaded 70,000/232,428 (30%)
886015 [INFO] Downloaded 80,000/232,428 (34%)
```

**To Reproduce**

**Expected behavior**
to work

**Additional context**
- degradation from org.owasp:dependency-check-maven:8.4.3

**Comment by sysmat** [comment]
- after 25min, error:

```
940792 [ERROR] 	UpdateException: Error updating the NVD Data
940792 [ERROR] 		caused by NvdApiException: NVD Returned Status Code: 403
940792 [ERROR] 	NoDataException: No documents exist
```

**Comment by readonlyuser1** [comment]
are you using --nvdApiKey?
https://github.com/jeremylong/DependencyCheck/issues/6149#issuecomment-1836131337

**Comment by sysmat** [comment]
@readonlyuser1 no, probably this is the problem, when provide it it works, thx
