### ISSUE TITLE
Question regarding decrease in vulnerability count after upgrading to version 9 of dependency-check

### ISSUE THREAD

**Issue by qw1212** [dependency-check/DependencyCheck#6252]
I have noticed a significant decrease in the number of vulnerabilities detected after the upgrade, even though the scanned JAR files and the scanning environment remained the same.
Prior to the upgrade, in version 8, the scan reports consistently highlighted a higher number of vulnerabilities compared to the recent version 9. To provide a clearer picture, I have attached two screenshots:
![Scan report before upgrade](https://github.com/jeremylong/DependencyCheck/assets/62467963/d9dd166f-6563-4777-8eff-3db0c2ad20b5)
and
![Scan report after upgrade](https://github.com/jeremylong/DependencyCheck/assets/62467963/55396360-0ce3-48f2-8add-4cfbe71167bf)
Could you explain the reasons behind this decrease in vulnerability count? Are there any specific changes or improvements in version 9 that could have affected the detection algorithm or the way vulnerabilities are reported?

**Comment by jeremylong** [comment]
Without more details on which vulnerable dependency was no longer identified, which CVEs are not being reported. Also, is the missing dependency now reported as a related dependency?

**Comment by qw1212** [comment]
Thank you for your response. Here are the details.
[beforeUpgrade.csv](https://github.com/jeremylong/DependencyCheck/files/13609856/beforeUpgrade.csv)
and
[afterUpgrade.csv](https://github.com/jeremylong/DependencyCheck/files/13609867/afterUpgrade.csv)

**Comment by jeremylong** [comment]
With 9.0 are using the data feed option or the API? If using the data feed - purge the database and re-run with 9.0.4. See https://github.com/jeremylong/DependencyCheck/issues/6123
