### ISSUE TITLE
Access to search.maven.org

### ISSUE THREAD

**Issue by sivaswami** [dependency-check/DependencyCheck#626]
Hi, I am trying to restrict access of dependency check to internal usage. I also downloaded NVD locally. However I noticed that dependency-check internally uses "http://search.maven.org/#search|ga" url's for evidence collection. Is there any way to override this option/network access ?

**Comment by jeremylong** [comment]
Disable the central analyzer or better, if you have a Nexus internally configure the Nexus URL.

**Comment by jeremylong** [comment]
Can this issue be closed?

**Comment by sivaswami** [comment]
Hi Jeremy,
I went through the code and It took some time to understand the code. I noticed that the search.maven.org URL is hardcoded in  the below files : 
* src/site/resources/general/SampleReport.html
* src/site/markdown/analyzers/central-analyzer.md
* src/site/markdown/analyzers/nexus-analyzer.md
* src/site/markdown/data/index.md
* dependency-check-core/src/main/java/org/owasp/dependencycheck/dependency/Dependency.java
* dependency-check-core/src/main/java/org/owasp/dependencycheck/data/central/CentralSearch.java
* dependency-check-core/src/main/java/org/owasp/dependencycheck/data/nexus/MavenArtifact.java
* dependency-check-core/src/main/resources/dependencycheck.properties
It would be easy to configure internal Nexus URL if taken from a single location.

Also please help me to understand the challenges in disabling Central Analyzer. I think the flag -Danalyzer.central.enabled=true passed at command line might help to disable Central Analyzer looking at the code. Please correct me if I am wrong.

**Comment by jeremylong** [comment]
If you specify a valid Nexus URL, via the plugin configuration, then the central analyzer would automatically get disabled; you don't need to worry about the various places within the code base that the Central URL exists (although I should likely change that to a configuration value). 

In addition, you can disable the Central Analyzer by the flag `-Danalyzer.central.enabled=false`.

**Comment by jeremylong** [comment]
Also, if you are using maven you could just configure:

```xml
<centralAnalyzerEnabled>false</centralAnalyzerEnabled>
```
See the [configuration documentation](http://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html)) for more details.

**Comment by sivaswami** [comment]
Any specific impact on disabling Central Analyzer on resolution of the jar files ?

**Comment by jeremylong** [comment]
See http://jeremylong.github.io/DependencyCheck/data/index.html. If using Maven or Gradle for your build probably not. If using something else (CLI or Ant) and a pom.xml file is not present within the JAR file - the Central Analyzer will obtain additional evidence (Group/Artifact/Version). The end result is that there is a small increase in the false negatives.
