### ISSUE TITLE
Update to 9.0.3 breaks Sonarqube Vulnerabilities report /  JSON-Analysis aborted

### ISSUE THREAD

**Issue by srcimon** [dependency-check/DependencyCheck#6261]
After upgrading the maven-dependency-check from 8.4.3 to version 9.0.3 my Sonarqube instance doesn't show vulnerabilities anymore. I've activated HTML and JSON Report. The HTML Report ist shown properly (with vulnerabilities found) in Sonarqube.
The logfile contains a generic warning concerning the JSON Report:

```
10:36:37 [INFO] ------------- Run sensors on project
10:36:37 [INFO] Sensor Dependency-Check [dependencycheck]
10:36:37 [INFO] Process Dependency-Check report
10:36:37 [INFO] Using JSON-Reportparser
10:36:38 [WARNING] JSON-Analysis aborted
10:36:38 [INFO] Upload Dependency-Check HTML-Report
```

I'm using the latest version of [dependency-check-sonar-plugin](https://github.com/dependency-check/dependency-check-sonar-plugin) 4.0.0 and I really cant tell any major difference within the JSONs created via the plugin.

If I disable the JSON report the message gets more specific and tells that there is no JSON report as expected. This shows that the report is found but cannot be processed in my initial setup:

```
10:41:35 [INFO] ------------- Run sensors on project
10:41:35 [INFO] Sensor Dependency-Check [dependencycheck]
10:41:35 [INFO] Process Dependency-Check report
10:41:35 [INFO] Using JSON-Reportparser
10:41:35 [INFO] Dependency-Check JSON report does not exists. Please check property sonar.dependencyCheck.jsonReportPath:###path-to-file###
10:41:35 [INFO] JSON-Analysis skipped/aborted due to missing report file
```

Any suggestions what might be wrong in my setup?

**Comment by jeremylong** [comment]
See https://github.com/jeremylong/DependencyCheck/pull/6245

9.0.4 will be released shortly.

**Comment by srcimon** [comment]
Thank you very much @jeremylong !

**Comment by srcimon** [comment]
Hi @jeremylong ,
the issue still occours with 9.0.4.

**Comment by jeremylong** [comment]
If the issue occurs with 9.04 then you need to raise an issue with the maintainers of the Sonarqube plugin

**Comment by srcimon** [comment]
The Problem is fixed with https://github.com/dependency-check/dependency-check-sonar-plugin/commit/2bfcbbcab316122d8f427d1d58d4a8ac9f20cac6. Field confidentialityImpact is currently unknown in dependenc-check-sonar-plugin Version 4.0.0.
