### ISSUE TITLE
Warning for unnecessary suppressions

### ISSUE THREAD

**Issue by pedrovilasboas** [dependency-check/DependencyCheck#6272]
When vulnerabilities get fixed, by a library update for example, nothing alerts that a CVE can stop being suppressed.
Would it be possible to have some warning for unnecessary CVE suppressions?

**Comment by jeremylong** [comment]
This already occurs: https://github.com/jeremylong/DependencyCheck/blob/6f972cc287b1f3e3f8b2369eeed6bb1608232401/core/src/main/java/org/owasp/dependencycheck/analyzer/UnusedSuppressionRuleAnalyzer.java#L66

**Comment by pedrovilasboas** [comment]
oh thanks a lot. Never noticed that.
