### ISSUE TITLE
azure devops plugin behind proxy never ends

### ISSUE THREAD

**Issue by gt97** [dependency-check/DependencyCheck#6273]
**Describe the bug**
I am using the dependency check plugin of azure devops on a self hosted server. The connection to internet is using a proxy server.

The command executed is:
C:\Windows\system32\cmd.exe /D /S /C "D:\azure\ag1\_work\_tool\_owasp\dependency-check\bin\dependency-check.bat --project MyProject --out D:\azure\ag1\_work\42\a\dependency-check --scan D:\azure\ag1\_work\42\a\myFolder --format ALL --proxyserver myproxy.local.net --proxyport 8080 --nvdApiKey ***"

**Version of dependency-check used**
The problem occurs using version 9.0.4

The Azure devops plugin version is 6.1.3

**Log file**
What I see in the Azure Devops console is:
C:\Windows\system32\cmd.exe /D /S /C "D:\azure\ag1\_work\_tool\_owasp\dependency-check\bin\dependency-check.bat --version"
Dependency-Check Core version 9.0.4

C:\Windows\system32\cmd.exe /D /S /C "D:\azure\ag1\_work\_tool\_owasp\dependency-check\bin\dependency-check.bat --project MyProject --out D:\azure\ag1\_work\42\a\dependency-check --scan D:\azure\ag1\_work\42\a\myFolder --format ALL --proxyserver myproxy.local.net --proxyport 8080 --nvdApiKey ***"

[WARN] NVD API request failures are occurring; retrying request for the 6 time
[INFO] Recoverable I/O exception (org.apache.hc.client5.http.HttpHostConnectException) caught when processing request to {s}->https://services.nvd.nist.gov:443
[WARN] NVD API request failures are occurring; retrying request for the 7 time
[INFO] Recoverable I/O exception (org.apache.hc.client5.http.HttpHostConnectException) caught when processing request to {s}->https://services.nvd.nist.gov:443
[WARN] NVD API request failures are occurring; retrying request for the 8 time
[INFO] Recoverable I/O exception (org.apache.hc.client5.http.HttpHostConnectException) caught when processing request to {s}->https://services.nvd.nist.gov:443
[WARN] NVD API request failures are occurring; retrying request for the 9 time
[INFO] Recoverable I/O exception (org.apache.hc.client5.http.HttpHostConnectException) caught when processing request to {s}->https://services.nvd.nist.gov:443
[WARN] NVD API request failures are occurring; retrying request for the 10 time
[INFO] Recoverable I/O exception (org.apache.hc.client5.http.HttpHostConnectException) caught when processing request to {s}->https://services.nvd.nist.gov:443
[WARN] NVD API request failures are occurring; retrying request for the 11 time
[INFO] Recoverable I/O exception (org.apache.hc.client5.http.HttpHostConnectException) caught when processing request to {s}->https://services.nvd.nist.gov:443
[INFO] Recoverable I/O exception (org.apache.hc.client5.http.HttpHostConnectException) caught when processing request to {s}->https://services.nvd.nist.gov:443
[INFO] Recoverable I/O exception (org.apache.hc.client5.http.HttpHostConnectException) caught when processing request to {s}->https://services.nvd.nist.gov:443
[INFO] Recoverable I/O exception (org.apache.hc.client5.http.HttpHostConnectException) caught when processing request to {s}->https://services.nvd.nist.gov:443
[WARN] NVD API request failures are occurring; retrying request for the 5 time
[INFO] Recoverable I/O exception (org.apache.hc.client5.http.HttpHostConnectException) caught when processing request to {s}->https://services.nvd.nist.gov:443
[WARN] NVD API request failures are occurring; retrying request for the 6 time
[INFO] Recoverable I/O exception (org.apache.hc.client5.http.HttpHostConnectException) caught when processing request to {s}->https://services.nvd.nist.gov:443
[WARN] NVD API request failures are occurring; retrying request for the 7 time
[INFO] Recoverable I/O exception (org.apache.hc.client5.http.HttpHostConnectException) caught when processing request to {s}->https://services.nvd.nist.gov:443
[WARN] NVD API request failures are occurring; retrying request for the 8 time
[INFO] Recoverable I/O exception (org.apache.hc.client5.http.HttpHostConnectException) caught when processing request to {s}->https://services.nvd.nist.gov:443
[WARN] NVD API request failures are occurring; retrying request for the 9 time
[INFO] Recoverable I/O exception (org.apache.hc.client5.http.HttpHostConnectException) caught when processing request to {s}->https://services.nvd.nist.gov:443
[WARN] NVD API request failures are occurring; retrying request for the 10 time

**Comment by jeremylong** [comment]
See the proxy configuration page: https://jeremylong.github.io/DependencyCheck/data/proxy.html

Unfortunately, we are in transition right now on how the proxy is configured.

**Comment by gt97** [comment]
@jeremylong I asked network to make a trace and looks like the cli doesn't use the proxy configuraztion:
--proxyserver myproxy.local.net --proxyport 8080

when checking for updates.

**Comment by jeremylong** [comment]
I'm shocked - did you read the documentation I linked to that stated **how** you need to set the proxy? It is possible that only setting the proxy just via the properties will work - but just the two args you've specified will fail. Please take a look at https://jeremylong.github.io/DependencyCheck/data/proxy.html

**Comment by gt97** [comment]
understood. I configured the plugin in this way:

  inputs;
      .....
      .....
      additionalArguments: '--proxyserver "myproxy.net" --proxyport "8080" --nvdApiKey "$(nvdApiKey)"'
  env:
    JAVA_TOOL_OPTIONS: "-Dhttps.proxyHost=myproxy.net -Dhttps.proxyPort=8080"  

Thankyou

**Comment by RobSHK** [comment]
I've tried the suggested configuration, but still the Pipeline igmoring the Proxy setting, 
I'm getting: 

`[ERROR] Could not connect to Central search. Analysis failed.
java.io.IOException: Finally failed connecting to Central search. Giving up after 7 tries.
	at org.owasp.dependencycheck.analyzer.CentralAnalyzer.fetchMavenArtifacts(CentralAnalyzer.java:364)
	at org.owasp.dependencycheck.analyzer.CentralAnalyzer.analyzeDependency(CentralAnalyzer.java:229)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.SocketTimeoutException: connect timed out`

am I missing something here?
```
- task: Bash@3
  inputs:
    env:
    JAVA_TOOL_OPTIONS: "-Dhttps.proxyHost=my-proxy -Dhttps.proxyPort=8080"
    targetType: 'inline'
    script: '/Owasp/dependency-check-9.0.5/bin/dependency-check.sh ...
```

**Comment by gt97** [comment]
Hi @RobSHK 
not sure but I see two difference respect my task:
 - that definition of env: should be at the same level of inputs:
 - I addede even the arguments --proxyserver and --proxyport as arguments for the script

I am using the dependency check plugin in the azure marketplace (https://marketplace.visualstudio.com/items?itemName=dependency-check.dependencycheck&targetId=28c2a7af-7473-4d9f-8a07-00377c831903&utm_source=vstsproduct&utm_medium=ExtHubManageList)
