### ISSUE TITLE
how do all *.xml to dc.h2.db

### ISSUE THREAD

**Issue by hktalent** [dependency-check/DependencyCheck#628]
os： mac os X 10.12.1
1、[INFO] Checking for updates
[ERROR] IO Exception: Connection reset
[ERROR] IO Exception: Connection reset
[WARN] Unable to download the NVD CVE data; the results may not include the most recent CPE/CVEs from the NVD.
[INFO] If you are behind a proxy you may need to configure dependency-check to use the proxy.
[ERROR] Unable to download the NVD CVE data.

2、i downlaod all *.xml
cd /usr/local/Cellar/dependency-check/1.4.4/libexec/data
ls
dc.h2.db				nvdcve-2002.xml
nvdcve-2.0-2002.xml			nvdcve-2003.xml
nvdcve-2.0-2003.xml			nvdcve-2004.xml
nvdcve-2.0-2004.xml			nvdcve-2005.xml
nvdcve-2.0-2005.xml			nvdcve-2006.xml
nvdcve-2.0-2006.xml			nvdcve-2007.xml
nvdcve-2.0-2007.xml			nvdcve-2008.xml
nvdcve-2.0-2008.xml			nvdcve-2009.xml
nvdcve-2.0-2009.xml			nvdcve-2010.xml
nvdcve-2.0-2010.xml			nvdcve-2011.xml
nvdcve-2.0-2011.xml			nvdcve-2012.xml
nvdcve-2.0-2012.xml			nvdcve-2013.xml
nvdcve-2.0-2013.xml			nvdcve-2014.xml
nvdcve-2.0-2014.xml			nvdcve-2015.xml
nvdcve-2.0-2015.xml			nvdcve-2016.xml
nvdcve-2.0-2016.xml			nvdcve-Modified.xml
nvdcve-2.0-Modified.xml			official-cpe-dictionary_v2.3.xml

3、how do all *.xml into dc.h2.db？

**Comment by stevespringett** [comment]
https://jeremylong.github.io/DependencyCheck/data/mirrornvd.html

When you run Dependency-Check, you'll need to specify these four options and point them to the URL of the mirror

cveUrl12Modified
cveUrl20Modified
cveUrl12Base
cveUrl20Base

**Comment by hktalent** [comment]
$ dependency-check --cveUrl12Modified file:///usr/local/Cellar/dependency-check/1.4.4/libexec/data/nvdcve-Modified.xml --cveUrl20Modified file:///usr/local/Cellar/dependency-check/1.4.4/libexec/data/nvdcve-2.0-Modified.xml --cveUrl12Base file:///usr/local/Cellar/dependency-check/1.4.4/libexec/data --cveUrl20Base file:///usr/local/Cellar/dependency-check/1.4.4/libexec/data   --project Testing --out . --scan /Volumes/MyWork/MyWork/JY15MD002SK/04.Implement/lib
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
[INFO] Checking for updates
[INFO] NVD CVE requires several updates; this could take a couple of minutes.
[INFO] Download Started for NVD CVE - 2002
[INFO] Download Started for NVD CVE - 2003
[INFO] Download Started for NVD CVE - 2004
[WARN] Download Failed for NVD CVE - 2003
Some CVEs may not be reported.
[WARN] Download Failed for NVD CVE - 2004
Some CVEs may not be reported.
[WARN] Download Failed for NVD CVE - 2002
Some CVEs may not be reported.
[INFO] If you are behind a proxy you may need to configure dependency-check to use the proxy.
[INFO] If you are behind a proxy you may need to configure dependency-check to use the proxy.
[INFO] If you are behind a proxy you may need to configure dependency-check to use the proxy.
[INFO] Download Started for NVD CVE - 2005
[INFO] Download Started for NVD CVE - 2007
[INFO] Download Started for NVD CVE - 2006
[WARN] Download Failed for NVD CVE - 2005
Some CVEs may not be reported.
[WARN] Download Failed for NVD CVE - 2007
Some CVEs may not be reported.
[INFO] If you are behind a proxy you may need to configure dependency-check to use the proxy.
[WARN] Download Failed for NVD CVE - 2006
Some CVEs may not be reported.
[INFO] If you are behind a proxy you may need to configure dependency-check to use the proxy.
[INFO] If you are behind a proxy you may need to configure dependency-check to use the proxy.
[INFO] Download Started for NVD CVE - 2008
[INFO] Download Started for NVD CVE - 2009
[INFO] Download Started for NVD CVE - 2010
[WARN] Download Failed for NVD CVE - 2008
Some CVEs may not be reported.
[WARN] Download Failed for NVD CVE - 2010
Some CVEs may not be reported.
[INFO] If you are behind a proxy you may need to configure dependency-check to use the proxy.
[WARN] Download Failed for NVD CVE - 2009
Some CVEs may not be reported.
[INFO] If you are behind a proxy you may need to configure dependency-check to use the proxy.
[INFO] If you are behind a proxy you may need to configure dependency-check to use the proxy.
[INFO] Download Started for NVD CVE - 2011
[INFO] Download Started for NVD CVE - 2012
[INFO] Download Started for NVD CVE - 2013
[WARN] Download Failed for NVD CVE - 2011
Some CVEs may not be reported.
[INFO] If you are behind a proxy you may need to configure dependency-check to use the proxy.
[WARN] Download Failed for NVD CVE - 2012
Some CVEs may not be reported.
[INFO] Download Started for NVD CVE - 2014
[INFO] If you are behind a proxy you may need to configure dependency-check to use the proxy.
[WARN] Download Failed for NVD CVE - 2013
Some CVEs may not be reported.
[INFO] Download Started for NVD CVE - 2015
[INFO] If you are behind a proxy you may need to configure dependency-check to use the proxy.
[WARN] Download Failed for NVD CVE - 2014
Some CVEs may not be reported.
[INFO] If you are behind a proxy you may need to configure dependency-check to use the proxy.
[INFO] Download Started for NVD CVE - 2016
[INFO] Download Started for NVD CVE - Modified
[WARN] Download Failed for NVD CVE - 2015
Some CVEs may not be reported.
[INFO] If you are behind a proxy you may need to configure dependency-check to use the proxy.
[WARN] Download Failed for NVD CVE - 2016
Some CVEs may not be reported.
[INFO] If you are behind a proxy you may need to configure dependency-check to use the proxy.
[INFO] Download Complete for NVD CVE - Modified  (1066 ms)
[INFO] Processing Started for NVD CVE - Modified
[WARN] Unable to update Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.
[ERROR] No documents exist

Unable to continue dependency-check analysis.
[ERROR] One or more fatal errors occurred
[ERROR] The download was interrupted; unable to complete the update
[ERROR] No documents exist

**Comment by hktalent** [comment]
use jdk 1.8，so ok
