### ISSUE TITLE
Different databases in 9.x and before? Behavior of versions before 9.x when NVD feeds are retired?

### ISSUE THREAD

**Issue by gbrinkmann** [dependency-check/DependencyCheck#6289]
Hi,

we have a massive QA: hundreds of projects and for most of them Bamboo Sonar plans.

All projects (Maven) are based on parent POM projects for Java8, Java11, Java17 and Java21. These parents include plugins sonar, dependency check and so on.

The older current releases (resp. current snapshots) are, the older a parent version may be, for example parent 17.0.0, 17.0.1 and so on.

1. Can I test 9.x on Bamboo, or do 9.x and before use the same database?
2. How will versions before 9.x behave when NVD feeds are retired? Worst case would of course be hundreds of failed Sonar builds using 8.x. Hopefully the unability to update from feeds is just a warning.

Regards,
Gunnar

**Comment by jeremylong** [comment]
while technically the database is the same in a lot of ways - there are differences in the values stored in the properties table. These differences would likely cause a full download of the data from the NVD again.

1. I've heard the data feeds won't be retired on 12/15 - the NVD has received a lot of push-back on this. However, this doesn't mean they won't be retired or heavily change; just that you might have more time. I'd keep working towards migrating.
2. ODC 9.x requires the use of an NVD API key for updates. If every node updates you are likely going to hit the rate limit enforced by the NVD (it is per API key - so if the key is reused on multiple builds it is easy to hit the rate limit). As such, if you have multiple builds I would highly recommend utilizing a caching strategy. There are a few options documented under The NVD Database (see items 2-4) here: https://jeremylong.github.io/DependencyCheck/data/index.html


To your last question, "How will versions before 9.x behave when NVD feeds are retired?" Unless you are using something like the nist-data-mirror - the builds will likely just start falling once the data feeds are retired.

**Comment by gbrinkmann** [comment]
Thanks for your extended support, closing answered, have a nice day,
Gunnar
