### ISSUE TITLE
How to scan a repository containing both multi-module maven project, Node.js and javascript project? 

### ISSUE THREAD

**Issue by 0xAmal** [dependency-check/DependencyCheck#6291]
when i run it shows only javascript and npm packages only could you please help

**Comment by jeremylong** [comment]
I would use the maven plugin. It should pick up all of the java dependencies and also scan the package lock file for the npm.

**Comment by mohamed-vj-mc** [comment]
Hi, Not directly related, what if the javascript project is in pnpm. 
Related issue - https://github.com/jeremylong/DependencyCheck/issues/6276

**Comment by mohamed-vj-mc** [comment]
@jeremylong Hi, Not directly related, what if the javascript project is in pnpm.
Related issue - https://github.com/jeremylong/DependencyCheck/issues/6276

**Comment by jeremylong** [comment]
Still haven't had time to look into that/fix support for pnpm. Honestly, for any npm type project you are going to get the same results just running `pnpm audit`.

**Comment by jeremylong** [comment]
in maven there is a similar configuration option for the path to pnpm. see https://github.com/jeremylong/DependencyCheck/issues/6276#issuecomment-1855820555
