### ISSUE TITLE
Exception is swallowed

### ISSUE THREAD

**Issue by beat2** [dependency-check/DependencyCheck#6302]
**Describe the bug**
When building with maven (3.9.5, mvn clean install), all that is output is:

```
[INFO] --- dependency-check:9.0.5:aggregate (default) @ my-project ---
[ERROR] Fatal exception(s) analyzing My Project
[INFO] 
[INFO] --- failsafe:2.22.0:verify (default) @ my-project ---
```
To see the problem I ran `mvn clean install -X`.

This is the main cause:

`caused by MVStoreException: The write format 3 is larger than the supported format 2 [2.1.214/5]`

Main cause is obvious, I need to purge / delete the data.

But exception is not logged in maven output (without -X), probably because of: see attached stacktrace
[stacktrace.txt](https://github.com/jeremylong/DependencyCheck/files/13673724/stacktrace.txt)

**Version of dependency-check used**
The problem occurs using version 9.0.5 of the maven plugin

**Log file**
See above.

**To Reproduce**

**Expected behavior**
An exception should be logged when building with mvn clean install.

**Additional context**

**Comment by jeremylong** [comment]
the attached stack trace is unrelated to this issue. To resolve this - you can simply run `mvn org.owasp:dependency-check-maven:purge`.

If you have the full stack trace from the `caused by MVStoreException: The write format 3 is larger than the supported format 2 [2.1.214/5]` that would be helpful.

**Comment by beat2** [comment]
Sorry, forgot about the issue. Just thought it could be related to the "swallowing" part.

Here is the requested stacktrace:
[stacktrace_2.txt](https://github.com/jeremylong/DependencyCheck/files/13742724/stacktrace_2.txt)

(I solved the issue by deleting the relevant .m2-repo-path.)
