### ISSUE TITLE
NVD caching beginner question

### ISSUE THREAD

**Issue by gbrinkmann** [dependency-check/DependencyCheck#6306]
Hi depedency check team,

to test NVD caching on my machine I

- used vulnz 5.1.0 to fill a cache directory
- placed that directory in a local tomcat on my machine
- and added
`<nvdDatafeedUrl>http://localhost:8080/nvdcache/nvdcve-{0}.json.gz</nvdDatafeedUrl>`
- and
`<autoUpdate>false</autoUpdate>`
- to my dependency check plugin config

In the maven build log for my sonar profiles I see
```
...
[DEBUG]   (f) nvdDatafeedUrl = http://localhost:8080/nvdcache/nvdcve-{0}.json.gz
...
[DEBUG] Setting: nvd.api.datafeed.url='http://localhost:8080/nvdcache/nvdcve-{0}.json.gz'
...
```

Am I right? Is it that simple to use NVD caching?

If yes we'll then maybe run a nightly vulnz cron for a mirror URL and add those params to different parent pom snapshots when updating them to dependency check 9.x

Regards,
Gunnar

**Comment by jeremylong** [comment]
Autoupdate should not be set to false. If it is false it will not use the configured data feed.

**Comment by gbrinkmann** [comment]
Thank you.

I assume the feed URL has to be SSL?

a.t.m. I'm just testing localhost with a self signed cert produce by keytool.

"_bad request_" for cache.properties without SSL and with SSL "_SunCertPathBuilderException: unable to find valid certification path to requested target_"

I'll ask an admin to provide a mirror using our valid organzation cert.

**Comment by jeremylong** [comment]
depending on your server - properties files may not be served automatically. Try upgrading to vulnz 5.1.1 and ODC 9.0.5 (or higher). recent versions of vulnz started producing meta files in addition to the cache.properties and ODC 9.0.5+ will look for the meta files if it can't get the cache.properties file.

**Comment by gbrinkmann** [comment]
Thank you again, I'll do so next week because here's weekend now - have a nice weekend :)

**Comment by gbrinkmann** [comment]
Just some final testing feedback:

I just had to allow "*localhost" in nonProxyHosts to make it work on my notebook with 9.6.0.

Files are downloaded from my "localhost tomcat mirror"

For testing purposes I for example also
- added nvdValidForHours 0 to the plugin config
- renamed (local maven repo)/.../dependency-check-data/9.0 to .../9.0-backup to force downloads

Worked like a charm.

**Comment by marcelstoer** [comment]
>  ODC 9.0.5+ will look for the meta files if it can't get the cache.properties file

Did this break in the meantime?

I tried with 11.1.0 against https://mirror.cveb.in/nvd/json/cve/1.1/ (has no `cache.properties` but `*.meta` files) and got the dreaded 404 again.

```
 mvn org.owasp:dependency-check-maven:11.1.0:aggregate -DfailBuildOnCVSS=7 -DcveStartYear=2020 -DskipProvidedScope=true -DnodeAuditSkipDevDependencies=true -DnodePackageSkipDevDependencies=true -DnvdDatafeedUrl="https://mirror.cveb.in/nvd/json/cve/1.1/nvdcve-{0}.json.gz"
...
[ERROR] Unable to download the data feed META files
org.owasp.dependencycheck.data.update.exception.UpdateException: Unable to download the data feed META files
    at org.owasp.dependencycheck.data.update.NvdApiDataSource.getRemoteCacheProperties (NvdApiDataSource.java:637)
...
caused by ResourceNotFoundException: https://mirror.cveb.in/nvd/json/cve/1.1/cache.properties - Server status: 404
```

**Comment by marcelstoer** [comment]
Sorry for the noise 😞 It should be `nvdcve-1.1-{0}.json.gz` instead of `nvdcve-{0}.json.gz`.
