### ISSUE TITLE
v9.0.6 not deployed to Docker Hub

### ISSUE THREAD

**Issue by aarongoldenthal** [dependency-check/DependencyCheck#6320]
The Dependency Check v9.0.6 Build and Deploy Release action [failed to deploy to Docker Hub](https://github.com/jeremylong/DependencyCheck/actions/runs/7222130526/job/19679169558) (required to resolve https://github.com/jeremylong/DependencyCheck/security/advisories/GHSA-qqhq-8r2c-c3f5).

**Comment by jeremylong** [comment]
Yes - we will be releasing 9.0.7 soon. Apparently 9.0.6 may have an issue on some versions of Java.

failed to publish docker: https://github.com/jeremylong/DependencyCheck/actions/runs/7222130526
fixed the problem: https://github.com/jeremylong/DependencyCheck/pull/6312
