### ISSUE TITLE
Release 1.4.4.1 is on maven central but no release tag

### ISSUE THREAD

**Issue by hgschmie** [dependency-check/DependencyCheck#633]
Guess the tag was not pushed as part of the release.

**Comment by jeremylong** [comment]
The tag for the the 1.4.4.1 release of the maven plugin was never created. The entirety of the changes for 1.4.4.1 can be found in a single commit: https://github.com/jeremylong/DependencyCheck/commit/bfa67fcba765b853e33fece6d2dd61cf7faa143a
