### ISSUE TITLE
How to find CPE using GAV

### ISSUE THREAD

**Issue by Kim-Young-Joon** [dependency-check/DependencyCheck#6331]
Hello, nice to meet you. I have a question because I want to make better use of Dependency-check.

I am currently curious about how to find CPE using GAV using Java code.
It was very easy to find a way to use Dependency-Check in the form of a plugin.
However, I couldn't easily find a way to use the code, so I posted an issue.

To explain my situation more clearly, when a specific jar is input, I would like to check the CPE from this jar. Can I ask how to do this in code rather than in the form of a plugin?

I apologize if this was a rude question.

**Comment by jeremylong** [comment]
Explanation of how it works: https://jeremylong.github.io/DependencyCheck/general/internals.html
Source code: https://github.com/jeremylong/DependencyCheck

There is no mapping of GAV to CPE/CVE. Not sure what else I can provide.

**Comment by Kim-Young-Joon** [comment]
It is very unfortunate that there is no mapping relationship between GAV and CPE/CVE.

Thank you for your reply.
I'll close the issue :)

**Comment by jeremylong** [comment]
You can use https://github.com/advisories. This project will likely move to using a different data source. With just the NVD there is no good mapping.
