### ISSUE TITLE
Failed to initialize the RetireJS repo

### ISSUE THREAD

**Issue by ZHangTong-CHINA** [dependency-check/DependencyCheck#6335]
I use the "--nvdDatafeed" parameter to use offline caching for NVD API，The command I executed is as follows：
dependency-check.sh --project "第三方依赖CVE漏洞扫描报告" --scan /opt/tzhang/tools/Open-Vulnerability-Project-main -f HTML -o test.html --nvdDatafeed http://192.168.17.10 --retireJsUrl https://raw.githubusercontent.com/Retirejs/retire.js/master/repository/jsrepository.json
![image](https://github.com/jeremylong/DependencyCheck/assets/29192101/c82559fd-5132-43ac-9acf-3b786b640d4c)
An error occurred.
![image](https://github.com/jeremylong/DependencyCheck/assets/29192101/9035f20c-9d22-4575-938b-7daf322135cd)

**Comment by beibei1028** [comment]
大佬你好，请问你是如何解决初始化RetireJS仓库失败这个问题的
