### ISSUE TITLE
Consultation on scan results

### ISSUE THREAD

**Issue by ZHangTong-CHINA** [dependency-check/DependencyCheck#6336]
Hello, I tried to scan the component "log4j api-2.7. jar" and found that the scanned CVE vulnerability is inconsistent with the official report. I am not sure what the reason is.

**Comment by ZHangTong-CHINA** [comment]
[https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-api/2.7](url)
![image](https://github.com/jeremylong/DependencyCheck/assets/29192101/171d562a-084e-4044-b502-6b8dec3c4e50)
[Dependency-Check Report.pdf](https://github.com/jeremylong/DependencyCheck/files/13734202/Dependency-Check.Report.pdf)
@jeremylong

**Comment by aikebah** [comment]
First of all: mvnrepository is not 'official report' of vulnerabilities for a library.
Second: mvnrepository is also listing the vulnerabilities in dependencies of the log4j (including test-dependencies and potentially also including optional dependencies and (dependencies of) plugins used during build. I don't know how their dependencies determination algorithm works). Dependency-check will only list the vulnerabilties for the library itself. Any of the vulnerabilities in the dependencies (if relevant for your project) will be listed separately on those dependencies.

**Comment by jeremylong** [comment]
This is why we recommend using the maven or gradle integrations vs the CLI. The CLI only scans what you point it at - in this case a single JAR file. Whereas using the maven or gradle integration ODC will look at the transitive dependencies as well.

If you look farther down in the mvnrepository you'll see that all of these vulnerabilities are, as @aikebah pointed out, in the test dependencies:

<img width="881" alt="image" src="https://github.com/jeremylong/DependencyCheck/assets/862914/88f4cc3c-ac05-4b1f-8633-1f270451aa08">

**Comment by ZHangTong-CHINA** [comment]
> Collaborator

Thank you, I understand.

**Comment by ZHangTong-CHINA** [comment]
> This is why we recommend using the maven or gradle integrations vs the CLI. The CLI only scans what you point it at - in this case a single JAR file. Whereas using the maven or gradle integration ODC will look at the transitive dependencies as well.
> 
> If you look farther down in the mvnrepository you'll see that all of these vulnerabilities are, as @aikebah pointed out, in the test dependencies:
> 
> <img alt="image" width="881" src="https://private-user-images.githubusercontent.com/862914/292214558-88f4cc3c-ac05-4b1f-8633-1f270451aa08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMjA3NTYsIm5iZiI6MTcwMzIyMDQ1NiwicGF0aCI6Ii84NjI5MTQvMjkyMjE0NTU4LTg4ZjRjYzNjLWFjMDUtNGIxZi04NjMzLTFmMjcwNDUxYWEwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMlQwNDQ3MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYzk4MGJkZGMwMGNiMGM2ODhlMzVjM2E5NzFmZmM2MGQ1ZjI2MmViOGUyZmQ0ZmVkNzBiNDQ2MzM1YWZmOGJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GMgR1aJPRAOSbLZcG9BB8cJ-kMg9C9tE-oeBMPAGp84">

Thank you, I understand. Thank you for your guidance.
