### ISSUE TITLE
Unnable to use local file for jsrepository.json

### ISSUE THREAD

**Issue by loicdesguin** [dependency-check/DependencyCheck#6346]
Hello,

To workaround the recurrent problem of certificate on remote download I tried to use a local version of the file using this configuration : 
dependencyCheck {
    nvd {
        apiKey = 'XXX'
        delay = 16000
    }
     analyzers {
     	retirejs {
     		retireJsUrl= "file:///C:/IDE/jsrepository.json"
     	}
     }
} 

But it keep trying to access to "https://raw.githubusercontent.com/RetireJS/retire.js/0fe12bb575eda270536dc0ce47fca0dd17b6ab33/repository/jsrepository.json'

What's wrong ?

Thanks
Loïc

**Comment by aikebah** [comment]
The code uses `https://raw.githubusercontent.com/Retirejs/retire.js/master/repository/jsrepository.json` as a location so my gut feel is that something in your system configures the commit-hash based jsrepository.json and overrides what you quoted in some way. I'm not familiar enough with the gradle configuration to guide you on where to look.

**Comment by jeremylong** [comment]
what version of ODC are you using and how are you calling the task in gradle? If you run with `--debug` you will see a section where all of the properties are written out - you can search for the internal property `analyzer.retirejs.repo.js.url`; it will likely be displayed twice and the second value is the one that will be used.

**Comment by loicdesguin** [comment]
Hello,

The key is 4 time in the debug : 
The third one is the correct local file but the "last" one is back to the remote file on github.

The version used : 
org.owasp:dependency-check-gradle:9.0.7

Thanks for the support
Regards

Loïc

**Comment by jeremylong** [comment]
If the key is listed 4 times you are running ODC more than once. How are you actually calling the task?

**Comment by loicdesguin** [comment]
Just with "gradlew dependencyCheckAnalyze" on the root project. (It's a sub-projects configuration

**Comment by jeremylong** [comment]
you don't have any dependsOn setup in the build.gradle? I'd need to see more of the build.gradle to be able to help.

**Comment by jeremylong** [comment]
wait - you said sub-projects. If you are only trying to run dependency-check on a single sub-project then you need to run it like:

`./gradlew :subproject_name:dependencyCheckAnalyze`

My bet is, you are running ODC twice, once with the correct configuration and once with the default configuration - just on different projects in the multi-project build.

**Comment by loicdesguin** [comment]
You're right the problem didn't occure anymore. Thanks
