### ISSUE TITLE
How to use data cached by vulnz with dependency-check maven plugin

### ISSUE THREAD

**Issue by ankurga** [dependency-check/DependencyCheck#6347]
Hello,

We are using the `dependency-check` maven plugin in more than 80 different environments which are controlled by `puppet`. We are using specifically below command in our testing scripts:

```bash
mvn --batch-mode clean org.owasp:dependency-check-maven:9.0.7:check verify \
        -DnvdApiKey=*** \
        -Pcoverage \
        -DossindexAnalyzerEnabled=false \
        -Dformats=JSON,HTML
```

After moving from datafeeds to API, we stumbled upon the `403` errors because we have a single API key and we cannot have 80 different keys for different environments.

So, after searching through different questions and PR's in this repo we decided to use [vulnz cli](https://github.com/jeremylong/Open-Vulnerability-Project/blob/main/vulnz/README.md#caching-the-nvd-cve-data) to cache the data from NVD API.

Now, after running:

```bash
vulnz cve --cache --directory ./cache
```

I have got files like below in the ./cache directory:

```bash
nvdcve-2012.json.gz
nvdcve-2012.meta
nvdcve-2023.meta
nvdcve-2023.json.gz
.
.
nvdcve-modified.meta
nvdcve-modified.json.gz
cache.properties
```

Now my question is how do I use this cache in my above mentioned maven command?

What I tried:

- Tried to server the whole cache directory over http locally and use `-DnvdApiEndpoint`. It was hitting the endpoint but never downloaded anything.
- Tried the same with `-DnvdDatafeed`, didn't even hit the local endpoint.

Our plan is to have a single server run vulnz cache to download latest data from NVD everyday and our 80 server would use our local server's cached data to run vulnerabilities scan. Any help would be appreciated. Thanks !!

**Comment by lbillinghamwrk** [comment]
I am not sure if this is useful context or not; but I think that when you reference serving the `./cache` directory, its equivalent to doing 

in one shell

```sh
$ cd ./cache

$ python3 -m http.server 8000
Serving HTTP on 0.0.0.0 port 8080 (http://0.0.0.0:800
```

Then in another shell

```sh
# verify that we are serving _something_ from the directory
$ curl http://localhost:8000
<!DOCTYPE HTML PUBLIC ... >
# the HTML for a page listing the contents of the `./cache` folder


mvn --batch-mode clean org.owasp:dependency-check-maven:9.0.7:check verify \ 
    -DnvdApiEndpoint=http://localhost:8000 \
    ... 
```

@ankurga does that give the steps to reproduce from the serving-the-cache side?

**Comment by jeremylong** [comment]
Sounds like you were going for option 2 on https://jeremylong.github.io/DependencyCheck/data/index.html.

2. [Mirror the NVD](https://jeremylong.github.io/DependencyCheck/data/mirrornvd.html) locally within your organization
3. Build the H2 database on one node and [cache the H2 database](https://jeremylong.github.io/DependencyCheck/data/cacheh2.html).

What version of ODC are you using? There was an issue with some HTTP servers not serving `*.properties` files by default. In the last point release or 2 ODC will check if it can download the cache.properties file and if it can't it will try the meta files.

**Comment by ankurga** [comment]
@lbillinghamwrk Yes, that's exactly what I was doing.

@jeremylong I am using the latest version `9.0.7`. Just to be sure, I even deleted the whole `owasp` folder before running the maven command. But my maven command is just stuck on this step:

```bash
Checking for updates
```

Also, I am just curious about the 3rd step that you mentioned:

> 3. Build the H2 database on one node and [cache the H2 database](https://jeremylong.github.io/DependencyCheck/data/cacheh2.html).

Is there anything else that needs to be done after running this command:

```bash
vulnz cve --cache --directory ./cache
```

Because I haven't done that. I am simply serving the whole `./cache` directory as a HTTP web server using python.

**Comment by jeremylong** [comment]
After you have the cache setup you should be able to use `mvn org.owasp:dependency-check-maven:check -DnvdDatafeedUrl=https://some.internal.url/nvdcve-{0}.json.gz`.

**Comment by ankurga** [comment]
Sorry, I was about to close this issue today.
@jeremylong Thanks for everything. It worked after this. :)
