### ISSUE TITLE
Error after upgrading Dependency check to 9.0.7 version

### ISSUE THREAD

**Issue by Mridula03g** [dependency-check/DependencyCheck#6351]
Hi @jeremylong 

I have downloaded new version 9.0.7 and ran first time without --noupdate and can see below error
<img width="705" alt="with noupdate" src="https://github.com/jeremylong/DependencyCheck/assets/85608136/8f549a83-74cf-40f0-b34b-b9ca0615e061">
 next i ran the command with --noupdate and i could see below error
<img width="717" alt="noupdate" src="https://github.com/jeremylong/DependencyCheck/assets/85608136/c44453c6-bedd-4996-b581-f0118d003891">

Please help us to fix the issue

Thank you,
Mridula U

**Comment by jeremylong** [comment]
ODC requires that the update be run before you can run any analysis. So the second command with `--noupdate` will fail until the update works. To figure out what the real error is to the first execution of dependency-check add `--log odc.log` and review the log for errors. Note that you may see an stack trace related to log4j - this is completely ignoreable and does not affect ODC.

**Comment by Mridula03g** [comment]
Hi @jeremylong 

I have executed the  --log command and attached the log file here. Please guide us on how to fix this issue
[odc.log](https://github.com/jeremylong/DependencyCheck/files/13806992/odc.log)

Thank you

**Comment by Mridula03g** [comment]
Hi @jeremylong 

Can you please provide the fix for the above issue

Thank you,
Mridula U

**Comment by jeremylong** [comment]
Seeing an exception like this: `java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.net.UnknownHostException: services.nvd.nist.gov` - my guess is you are behind a proxy. See https://jeremylong.github.io/DependencyCheck/data/proxy.html

**Comment by Mridula03g** [comment]
Hi @jeremylong 

Yes we are using proxy. Version 8 works fine with the proxy ,but version 9 is throwing error. We have set the proxy in below way
Please let us know if it is correct?
${DepCheckShell} --log odc.log --nvdApiKey c8dd02e3-xxxx-xxxx-xxxx-xxxxxxxxxxxx --disableRetireJS --disableCentral --disableOssIndex --disableYarnAudit --scan . --project Batch-CDR -Dhttps.proxyHost=172.xx.x.xx -Dhttps.proxyPort=8080 -Dhttp.nonProxyHosts=devops.mohhdev.local --format ALL --out "${WORKSPACE}"/devopsDir/depcheck

We have few questions
1. Does Version 9 ad later need internet access?
2. How to mirror nvd in to our local?
3. If any IP or URL or port needs to be opened for the firewall connection for version 9?
4. Please let us know EOSL for version 8

Please clearly let us know, what needs to be done for the installation and configuration for version 9 and later. 

Thank you,
Mridula U

**Comment by Mridula03g** [comment]
[version 9 output.txt](https://github.com/jeremylong/DependencyCheck/files/13840796/version.9.output.txt)
[version 9.0.7 output.txt](https://github.com/jeremylong/DependencyCheck/files/13840800/version.9.0.7.output.txt)

**Comment by jeremylong** [comment]
1. Yes, internet access is still required as documented: https://jeremylong.github.io/DependencyCheck/data/index.html
2. You can mirror the NVD files using the vulnz cli: https://github.com/jeremylong/Open-Vulnerability-Project/tree/main/vulnz#caching-the-nvd-cve-data
3. The endpoint being used to call the NVD API is: https://services.nvd.nist.gov/rest/json/cves/2.0; you may need to update the rules on the proxy/firewall
4. 8 in my opinion is already EOL; but it is still working until the NVD deprecates the data feeds: https://github.com/jeremylong/DependencyCheck/blob/main/SECURITY.md
