### ISSUE TITLE
Cli and maven plugin can not share same cache

### ISSUE THREAD

**Issue by JingLeiTalan** [dependency-check/DependencyCheck#6352]
**Describe the bug**

we have used both dependency check cli and maven plugin in our projet to analyse different projects, and we cached the odc in the same folder. But every time after run cli then run maven plugin, i have the error: 
DatabaseException: Unable to connect to the database - if this error persists it may be due to a corrupt database. Consider running `purge` to delete the existing database

I had same error  when run first maven plugin, then run the cli 

it' true that after run purge, it worked, but why they can not share the same cache ? 

Here is the configuration i used for cli:
`dependency-check.sh --scan "pathtoproject" --data "data/"  --disableOssIndex --disableNodeJS --disableRetireJS --disableAssembly --disableOssIndex --enableExperimental --nodeAuditSkipDevDependencies`
 
And here is the command i used for maven plugin:
`org.owasp:dependency-check-maven:9.0.7:aggregate -DdataDirectory=data/  -DnodeAnalyzerEnabled=false -DretireJsAnalyzerEnabled=false -DossindexAnalyzerEnabled=false -DassemblyAnalyzerEnabled=false -DenableExperimental=true -DskipProvidedScope=true -DnodeAuditSkipDevDependencies=false`

**Version of dependency-check used**
The problem occurs using version 9.0.7 of the cli, gradle plugin, maven plugin

Here is the error log:
[ERROR] Failed to execute goal org.owasp:dependency-check-maven:9.0.7:aggregate (default-cli) on project : Fatal exception(s) analyzing: One or more exceptions occurred during analysis:
[ERROR] 	DatabaseException: Unable to connect to the database - if this error persists it may be due to a corrupt database. Consider running `purge` to delete the existing database
[ERROR] 		caused by DatabaseException: Unable to connect to the database
[ERROR] 		caused by JdbcSQLNonTransientConnectionException: Unsupported database file version or invalid file header in file "data/odc.mv.db" [90048-214]
[ERROR] 		caused by MVStoreException: The write format 3 is larger than the supported format 2 [2.1.214/5]

**Comment by jeremylong** [comment]
What version of the CLI are you using? There were of course breaking changes in 9.0.0 - and if you miraculously were able to get 9.0.0 to create the database we had issues with h2 and had to revert the upgrade of h2 in 9.0.1. See the release notes here: https://github.com/jeremylong/DependencyCheck/blob/main/CHANGELOG.md#version-901-2023-11-26

Technically, following semantic versioning 9.0.1 should have been 10.0.0 - but so few people were able to get 9.0.0 to work - I considered it a broken release and didn't bother bumping the major version again.

**Comment by JingLeiTalan** [comment]
Thanks Jeremy for your answer, all it's good now :)

By the way, for project who use dendency-check-cli version 8 or 9.0.0  in a maven project with spring boot 3.2, you need to upgrade the version of dendency-check-cli version or force your project to use com.h2database:h2 2.1.214, since springboot 3.2 use com.h2database:h2 2.2.214
