### ISSUE TITLE
Packages and Dependencies to download version 9 and later

### ISSUE THREAD

**Issue by Mridula03g** [dependency-check/DependencyCheck#6366]
Hi @aikebah @jeremylong 

I am new to dependency-check. Kindly provide me the steps to install Dependency-check 9 or later version.
Our linux VM dont have internet connection ,we are behind proxy.

I downloaded the dep-check package from github and unzipped in VM and can see below folders
plugins
licenses
lib
bin
README.md
NOTICE.txt
LICENSE.txt

I tried running depcheck.sh command and can see data folder which contains
cache
odc.mv.db

and I can see errors saying that it is not able to connect to NVD
Errors:
[Dependency] [WARN] NVD API request failures are occurring; retrying request for the 5 time
[Dependency] [WARN] NVD API request failures are occurring; retrying request for the 6 time
[Dependency] [WARN] NVD API request failures are occurring; retrying request for the 7 time
[Dependency] [WARN] NVD API request failures are occurring; retrying request for the 8 time
[Dependency] [WARN] NVD API request failures are occurring; retrying request for the 9 time
[Dependency] [WARN] NVD API request failures are occurring; retrying request for the 10 time

Please suggest what steps exactly i should and download to fix this issue(dont have internet connection)
Please provide steps for offline installation

Thank you,
Mridula U

**Comment by jeremylong** [comment]
See the documentation: https://jeremylong.github.io/DependencyCheck/data/index.html
