### ISSUE TITLE
[FP]: MongoDB.Bson identified as MongoDB

### ISSUE THREAD

**Issue by echalone** [dependency-check/DependencyCheck#6376]
### Package URl

pkg:nuget/MongoDB.Bson@2.22.0

### CPE

cpe:2.3:a:mongodb:mongodb:2.22.0:*:*:*:*:*:*:*

### ODC Integration

None

### ODC Version

9.0.8

### Description

A false positive for the mongodb library (https://github.com/mongodb/mongo) is reported, when in reality it is the MongoDB.Bson NuGet package (https://www.nuget.org/packages/MongoDB.Bson).

**Comment by BenniG82** [comment]
@echalone 
I'm pretty sure this related to https://github.com/jeremylong/DependencyCheck/issues/6358
We're facing similar problems because the ecosystem of mongodb:mongodb is (often) not consistent for all CPEs

**Comment by aikebah** [comment]
approved
