### ISSUE TITLE
Need to check dependency-check rules

### ISSUE THREAD

**Issue by pedrogmagri** [dependency-check/DependencyCheck#6378]
Hey guys, I've been testing dependency-check for a few days now, it's realy useful, but I'm facing the need of having a look at its rules, I din't find them in the source code. I'd be grateful if you guys could help me.

**Comment by jeremylong** [comment]
There are no "rules" per se. See [How ODC Works](https://jeremylong.github.io/DependencyCheck/general/internals.html) and possibly the very outdated [wiki](https://github.com/jeremylong/DependencyCheck/wiki)

**Comment by pedrogmagri** [comment]
Alright, I appreciate the response, the How ODC Works will really help me, thanks.
