### ISSUE TITLE
Delete temporary files fails (directory not empty)

### ISSUE THREAD

**Issue by seancorfield** [dependency-check/DependencyCheck#6380]
**Describe the bug**
A warning appears that the JAR analyzer is unable to delete the temporary directory.

When enabling trace-level logging, the following information is logged:

```
[org.owasp.dependencycheck.analyzer.JarAnalyzer] {} [36mAttempting to delete temporary files from `/tmp/dctemp40cde27e-3043-4129-a208-16d04c35ad06/check11772992282168245675tmp`[m
[org.owasp.dependencycheck.utils.FileUtils] {} [30m/tmp/dctemp40cde27e-3043-4129-a208-16d04c35ad06/check11772992282168245675tmp[m
java.nio.file.DirectoryNotEmptyException: /tmp/dctemp40cde27e-3043-4129-a208-16d04c35ad06/check11772992282168245675tmp
	at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:289) ~[?:?]
	at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:104) ~[?:?]
	at java.base/java.nio.file.Files.delete(Files.java:1152) ~[?:?]
```

I suspect the order of files is such that it attempts to delete the directory before it has deleted all the files within it (indeed, that `check...tmp` folder contains folders called `1`, `2`, and `3`.

**Version of dependency-check used**
The problem occurs using version 9.0.8 of the library (used from the clj-holmes/clj-watson tool) (cli, gradle plugin, maven plugin, etc.)

**Log file**
When reporting errors, 99% of the time log file output is required. Please post the log file as a [gist](https://gist.github.com/) and provide a link in the new issue.

See the fragment above. Let me know if you need more detailed information.

**To Reproduce**
1. This happens when running the tool via clj-holmes/clj-watson every time (my `/tmp` folder had a large number of `dctemp...` folders before I noticed the warning).

**Expected behavior**

DependencyCheck should delete temporary files recursively in the correct order so that the top-level `dctemp...` folder is empty and also deleted.

**Additional context**

I'm running this on Ubuntu 20.04 with Temurin JDK 21.0.1.

**Comment by sellersj** [comment]
I ran into the same thing. Should be in the 9.0.9 release. I had to roll back to 9.0.7 until it comes out.
https://github.com/jeremylong/DependencyCheck/pull/6375

**Comment by seancorfield** [comment]
Cool, thanks. I'll close this as a duplicate of #6374 then.
