### ISSUE TITLE
Maven plugin: malformed documentation page

### ISSUE THREAD

**Issue by pnavato** [dependency-check/DependencyCheck#6383]
The final part of page https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html is malformed and hard to read.  The problem affects the description of the new `nvdApiKey` parameter.

BTW, since using the API key is "Highly Recommended" you could add a configuration example in the usage page at https://jeremylong.github.io/DependencyCheck/dependency-check-maven/

**Comment by jeremylong** [comment]
This will be fixed in the next release. See https://github.com/jeremylong/DependencyCheck/pull/6379
