### ISSUE TITLE
Failed to delete temporary files

### ISSUE THREAD

**Issue by OrangeDog** [dependency-check/DependencyCheck#6387]
**Describe the bug**
> [WARNING] Failed to delete the Archive Analyzer's temporary files from `C:\Users\jmh205\AppData\Local\Temp\dctempc3770ecc-ace1-4957-9821-cbe4dc9037ae\check9814232831758866394tmp`, see the log for more details
> [WARNING] Failed to delete the JAR Analyzder's temporary files from `C:\Users\jmh205\AppData\Local\Temp\dctempc3770ecc-ace1-4957-9821-cbe4dc9037ae\check15390092383622631313tmp`, see the log for more details

Not a Windows-specific issue:

> [WARNING] Failed to delete the Archive Analyzer's temporary files from `/tmp/dctemp436e5b68-9b51-4e0b-9904-55bc68dd00e1/check13502243923209963207tmp`, see the log for more details
[WARNING] Failed to delete the JAR Analyzder's temporary files from `/tmp/dctemp436e5b68-9b51-4e0b-9904-55bc68dd00e1/check14817445716398706363tmp`, see the log for more details

The directories remain after execution:
```
 Directory of C:\Users\jmh205\AppData\Local\Temp\dctemp5d469906-fbb5-4a0d-a54b-851b4f072e94

15/01/2024  11:05    <DIR>          .
15/01/2024  11:05    <DIR>          ..
15/01/2024  11:05    <DIR>          check3090585009047439685tmp
15/01/2024  11:05    <DIR>          check9030757156114494580tmp
15/01/2024  11:05           195,853 jsrepository.json
15/01/2024  11:05       129,708,032 odc.mv.db
15/01/2024  11:05               154 segments_1
15/01/2024  11:05                 0 write.lock
15/01/2024  11:05               278 _0.cfe
15/01/2024  11:05         2,920,020 _0.cfs
15/01/2024  11:05               368 _0.si
```

The `check*` directories contain many numbered directories each containing a `pom.xml`.

**Version of dependency-check used**
The problem occurs using version9.0.8 of the maven plugin

**Log file**
> [DEBUG] Closing Analyzer 'Archive Analyzer'
[DEBUG] Attempting to delete temporary files from `C:\Users\jmh205\AppData\Local\Temp\dctempc3770ecc-ace1-4957-9821-cbe4dc9037ae\check9814232831758866394tmp`
[DEBUG] Failed to delete file: C:\Users\jmh205\AppData\Local\Temp\dctempc3770ecc-ace1-4957-9821-cbe4dc9037ae\check9814232831758866394tmp (error message: C:\Users\jmh205\AppData\Local\Temp\dctempc3770ecc-ace1-4957-9821-cbe4dc9037ae\c
heck9814232831758866394tmp); attempting to delete on exit.
[WARNING] Failed to delete the Archive Analyzer's temporary files from `C:\Users\jmh205\AppData\Local\Temp\dctempc3770ecc-ace1-4957-9821-cbe4dc9037ae\check9814232831758866394tmp`, see the log for more details
[DEBUG] Closing Analyzer 'Ruby Bundle Audit Analyzer'
[DEBUG] Closing Analyzer 'File Name Analyzer'
[DEBUG] Closing Analyzer 'Jar Analyzer'
[DEBUG] Attempting to delete temporary files from `C:\Users\jmh205\AppData\Local\Temp\dctempc3770ecc-ace1-4957-9821-cbe4dc9037ae\check15390092383622631313tmp`
[DEBUG] Failed to delete file: C:\Users\jmh205\AppData\Local\Temp\dctempc3770ecc-ace1-4957-9821-cbe4dc9037ae\check15390092383622631313tmp (error message: C:\Users\jmh205\AppData\Local\Temp\dctempc3770ecc-ace1-4957-9821-cbe4dc9037ae\
check15390092383622631313tmp); attempting to delete on exit.
[WARNING] Failed to delete the JAR Analyzder's temporary files from `C:\Users\jmh205\AppData\Local\Temp\dctempc3770ecc-ace1-4957-9821-cbe4dc9037ae\check15390092383622631313tmp`, see the log for more details

**To Reproduce**
`mvn dependency-check:check`

**Expected behavior**
Not failing to delete temporary files.

**Comment by jeremylong** [comment]
See https://github.com/jeremylong/DependencyCheck/pull/6375
