### ISSUE TITLE
Every job run in Jenkins cause our node to get full because it generates multiple dctemp************

### ISSUE THREAD

**Issue by santopapi** [dependency-check/DependencyCheck#6395]
We are having a space issue after using the latest Dependency check and cause our node to get full. 

As you can see we only have 
![image](https://github.com/jeremylong/DependencyCheck/assets/34327393/5392c32e-a4b7-4205-841b-b1631235d8b5)
1.43GB free space and it's getting full in for two job runs. We don't have this kind of problem as the the previous version we used **`dependency-check-v8.1.0-release`** doesn't took much of space in multiple runs. 

Any idea how to fix it? because we are resorting to manual deletion of dctemp files to make the other jobs run. 

Thank you. 
Vince

**Comment by jeremylong** [comment]
See https://github.com/jeremylong/DependencyCheck/pull/6375. I'll try and release the fixed version shortly.
