### ISSUE TITLE
Documentation for Dependency Check Maven - Advanced configuration - not readable

### ISSUE THREAD

**Issue by Drumpe** [dependency-check/DependencyCheck#6397]
The information in the Advanced Configuration of Dependency Check Maven is scrambled 

Last Published: 2024-01-06
Version: 9.0.8

1. Go to (https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html)
2. Scroll down to Advanced Configuration

Confirmed with Firefox

**Comment by jeremylong** [comment]
Pushing a release right now that will correct the problem.
