### ISSUE TITLE
Use a CI

### ISSUE THREAD

**Issue by hgomez** [dependency-check/DependencyCheck#64]
Travis CI or CloudBees BuildHive could be used to provide Continuous Integration support.

It will help detect quickly failures and also check if a Pull-Request is mergeable.

For example, https://buildhive.cloudbees.com/job/hgomez/job/DependencyCheck/1/console

**Comment by jeremylong** [comment]
I've been planning on setting up CloudBees; since you've opened a ticket I'll make this a higher priority.

**Comment by hgomez** [comment]
It's really easy.
Long part is to create an account in CloudBees :)

**Comment by hgomez** [comment]
Your latest commit fixed build problem

https://buildhive.cloudbees.com/view/My%20Repositories/job/hgomez/job/DependencyCheck/

**Comment by jeremylong** [comment]
Cloudbees account created - I will finish this ticket over the weekend.

**Comment by jeremylong** [comment]
I'm far enough along setting up Cloudbees that I am going to close this issue.
