### ISSUE TITLE
Fail dependency-check ant target when it cannot update the 'NVD CVE data'

### ISSUE THREAD

**Issue by oosterholt** [dependency-check/DependencyCheck#640]
When autoupdate is enabled, the dependency-check ant target should fail when it cannot update its 'NVD CVE data'.

```
Logging produced when it cannot update:
Checking for updates
Unable to download the NVD CVE data; the results may not include the most recent CPE/CVEs from the NVD.
If you are behind a proxy you may need to configure dependency-check to use the proxy.
Check for updates complete (3009 ms)
```

Without failing the ant target it might stay unnoticed for quite a while when using Continuous Integration servers like Jenkins.

**Comment by jeremylong** [comment]
Great point; this is likely true for all interfaces. I'll change the default to error on an update exception and add a configuration option to ignore update errors when possible so if there are users that want to keep the current behavior in place they can.

**Comment by jeremylong** [comment]
I just double checked - this was actually included in the fix for https://github.com/jeremylong/DependencyCheck/issues/215.  This should be the default behavior if using 1.4.2 or later.  I just tested this in 1.4.5-SNAPSHOT and when offline the ant build fails due to an inability to update.
