### ISSUE TITLE
Need Help To Connect into Azure SQL Server

### ISSUE THREAD

**Issue by kauemendes** [dependency-check/DependencyCheck#6403]
Hey everyone, I would like to know if someone has an example on how to configure de CLI to connect into Microsoft SQL Server hosted into Azure. 

I have been trying in the past two days. I connect into the Database by DBeaver with the credentials. But for some reason with CLI I can't.

These are some attempts of the CLI that I have been trying.

1.  `dependency-check --project test --out ./dependency-check --scan . --disableBundleAudit --nodeAuditSkipDevDependencies --format HTML --nvdDatafeed https://localcache/nvdcve-\{0\}.json.gz --dbDriverPath /cve/jdbc/mssql/mssql-jdbc-12.4.2.jre8.jar --connectionString "jdbc:sqlserver://***.database.windows.net:1433;database=dependencycheckencrypt=true;user=dependencycheck_drw;password=***;encrypt=true;loginTimeout=30;"`

2.  `dependency-check --project test --out ./dependency-check --scan . --disableBundleAudit --nodeAuditSkipDevDependencies --format HTML --nvdDatafeed https://localcache/nvdcve-\{0\}.json.gz --connectionString "jdbc:sqlserver://***.database.windows.net:1433;database=dependencycheckencrypt=true;user=dependencycheck_drw;password=***;encrypt=true;loginTimeout=30;" --dbDriverPath /cve/jdbc/mssql/mssql-jdbc-12.4.2.jre8.jar --dbPassword "***" --dbUser "dependencycheck_drw"`

Also try using the .properties file, but I believe the configuration that I use there is not good as well. 
3. `dependency-check --project test --out ./dependency-check --scan . --disableBundleAudit --nodeAuditSkipDevDependencies --format HTML --nvdDatafeed https://localcache/nvdcve-\{0\}.json.gz --propertyfile ./dependencycheck.properties`

Current dependency-check version is 9.0.9 and the DBversion is 5.4

Is not quite clear for me if I have to use also the `--dbPassword` `--dbUser` parameters. 

I was able to connect into the database and run the initialize sql statements. If some one can give an example of how to do it. It would be great. 

Thanks 🚀

**Comment by jeremylong** [comment]
Have you used `--log` and looked at any exception messages there?  Have you tried using the `--dbPassword` and `--dbUser` options?

**Comment by kauemendes** [comment]
It works I was missing the `--dbDriverName "com.microsoft.sqlserver.jdbc.SQLServerDriver"` parameter. 

The `--log` flag really helped me. Thanks @jeremylong !
