### ISSUE TITLE
Unable to disable 'bundle-audit' when using Dependency-Check Jenkins plugin

### ISSUE THREAD

**Issue by fpmosley** [dependency-check/DependencyCheck#641]
### Reporting Bugs/Errors
When reporting errors, 99% of the time log file output is required. Please post the log file as a [gist](https://gist.github.com/) and provide a link in the new issue.

### Reporting False Positives
When reporting a false positive please include:
- The location of the dependency (Maven GAV, URL to download the dependency, etc.)
- The CPE that is believed to be false positive
  - Please report the CPE not the CVE

#### Example
False positive on library foo.jar - reported as cpe:/a:apache:tomcat:7.0
```xml
<dependency>
   <groupId>org.sample</groupId>
   <artifactId>foo</artifactId>
   <version>1.0</version>
</dependency>
```

I'm running Dependency-Check, using the Jenkins plugin, to analyze Jar files. I keep getting the following error:

```
[DependencyCheck] Analyzing Dependencies
[DependencyCheck] One or more exceptions were thrown while executing Dependency-Check
[DependencyCheck] Exception Caught: org.owasp.dependencycheck.exception.InitializationException
[DependencyCheck] Cause: bundle-audit failure
[DependencyCheck] Message: Exception from bundle-audit process: java.io.IOException: Cannot run program "bundle-audit" (in directory "/tmp/dctemp81a64758-ffa4-4a2e-aaee-d0ed3caa9ec8"): error=2, No such file or directory. Disabling Ruby Bundle Audit Analyzer
Build step 'Invoke OWASP Dependency-Check analysis' marked build as failure
```

This is not a Ruby project so I do not not need bundler audit. I see from the command-line there is a way to disable `bundle-audit`, but do not see a way to do that in the Jenkins configuration.

**Comment by stevespringett** [comment]
You can globally configure the Jenkins plugin. In the system configuration you can enable/disable individual analyzers as well as configure other aspects of the plugin.

**Comment by fpmosley** [comment]
In the System Configuration there is no option for bundle-audit.

**Comment by stevespringett** [comment]
Looks like an oversight. I'll add that to the next Jenkins release (1.4.5) - but this is the wrong tracker for that. https://issues.jenkins-ci.org/browse/JENKINS-40931

I'm sure the rest of the team would like to see logs to see what's going on with the bundle-audit analyzer though.

**Comment by fpmosley** [comment]
When will 1.4.5 be released?

**Comment by jeremylong** [comment]
I don't have a jenkins instance running atm - but if you can pass a `-Danalyzer.bundle.audit.enabled=false` you can disable the bundle audit analyzer.

As far as 1.4.5, I still have a few important items in the works and I do not have a firm timeline yet.

**Comment by fpmosley** [comment]
Since we are using the Jenkins plugin, and the "Invoke OWASP Dependency-Check analysis" post-build step to run it, where would we pass in that flag? Am I missing the ability to pass in additional flags/options?

**Comment by stevespringett** [comment]
Not sure where you would pass that in. Perhaps when starting Jenkins or the script that's invoked to start the slaves.

**Comment by jeremylong** [comment]
Yeah, sorry - that could be set as an environment variable as `analyzer.bundle.audit.enabled=false` or as a startup command to Jenkins `-Danalyzer.bundle.audit.enabled=false'.  Best we have until the next version.

**Comment by dspringer** [comment]
Actually I have been getting this same issue on version 1.4.5 with the Jenkins plugin. I have tried injecting the environment variables you mentioned into the build process, but the error still persists as it does not actually change the state to false.

Also is there a place that I can go to to find the documentation for the way this plugin works with NodeJS projects? I thought it scanned package.json, but when I add a package that I know has vulnerabilities, it doesn't find any vulnerabilities. This leads me to believe that I must run "npm install" for it to work. This is how I stumbled on this issue.

**Comment by stevespringett** [comment]
@dspringer if you're having issues with the Jenkins plugin, open an issue  https://issues.jenkins-ci.org

The existing NodeJs analyzer isn't all that valuable since the Javascript community is relatively immature compared to most. Most vulnerabilities in Node modules are not recorded in the NVD, hence the reason for creating the NSP analyzer available in the upcoming 2.0 release.

**Comment by dspringer** [comment]
@stevespringett Thank you very much for such a speedy response! Do you have an estimate of when we should expect the 2.0 release?

**Comment by stevespringett** [comment]
v2.0.0 of the Jenkins plugin was released two days ago and should be available on the update site.
