### ISSUE TITLE
[FP]: wiremock-spring-boot

### ISSUE THREAD

**Issue by blazej-lesny-payu-gpo** [dependency-check/DependencyCheck#6431]
### Package URl

pkg:maven/com.maciejwalkowiak.spring/wiremock-spring-boot@2.1.0

### CPE

`cpe:2.3:a:wiremock:wiremock:2.1.0:*:*:*:*:*:*:*`

### ODC Integration

{"label"=>"Maven Plugin"}

### ODC Version

9.0.7

### Description

The plugin spots an issue with a vulnerable wiremock version (below 2.16.0) by checking for `*wiremock*:*wiremock*`. The library's version is `2.1.0`, lower than `2.16.0`. However, the library actually uses wiremock version `3.3.1`, which is not vulnerable.

**Comment by blazej-lesny-payu-gpo** [comment]
The automatically generated suppression above is missing one additional CPE. I tested locally the following suppression, which doesn't report false-positive:

```xml
<suppress base="true">
   <notes><![CDATA[
   FP per issue #6431
   ]]></notes>
   <packageUrl regex="true">^pkg:maven/com\.maciejwalkowiak\.spring/wiremock-spring-boot@.*$</packageUrl>
   <cpe>cpe:/a:wiremock:wiremock</cpe>
   <cpe>cpe:/a:wire:wire</cpe>
</suppress>
```

**Comment by chadlwilson** [comment]
@aikebah this one looks legit to me. I guess the separate CPE can be handled with another FP report specific to that CPE.

**Comment by aikebah** [comment]
approved
