### ISSUE TITLE
Please add a "purge if necessary" parameter

### ISSUE THREAD

**Issue by volkert-fastned** [dependency-check/DependencyCheck#6440]
**Is your feature request related to a problem? Please describe.**
In our CI/CD set-up, we are automatically caching the vulnerability database after each successful build. As a result, the pipeline now fails on each build that uses version 9.x of the DependencyCheck plugin instead of 8.x, because the cached database is still in the outdated 8.x format.  

**Describe the solution you'd like**
It would be useful if a `purgeIfNecessary` variant could be implemented that will automatically try to purge or migrate the local/cached database only when it's found to be of an incompatible version.

**Describe alternatives you've considered**
We could add the `purge` option to our CI/CD pipeline, but then the vulnerability data is effectively no longer cached, which would considerably slow down each build. We could also try to manually delete the cache, but that's quite tedious, at least in the way that we currently have it set up.

Thank you kindly for considering this.

**Comment by jeremylong** [comment]
When breaking changes are implemented we update the data directory as well. For instance, this is the data directory for Maven:

<img width="710" alt="image" src="https://github.com/jeremylong/DependencyCheck/assets/862914/4201a62a-2e7a-438b-be8a-1848150af93e">

I'd recommend updating your caching strategy to work off of major version numbers.

**Comment by volkert-fastned** [comment]
@jeremylong That would require us to implement some kind of XML parsing to extract the version number of the Dependency Check plugin from `pom.xml` and then compare it with the previous successful build. And then add conditional logic to the pipeline to include the `purge` parameter only in the case of a major SemVer update. It's doable, but it's quite inconvenient. Especially for something that doesn't happen that often.

Is there a reason why you're not keen on implementing a `purgeIfNecessary` parameter?

**Comment by volkert-fastned** [comment]
@jeremylong Is there perhaps a file in the local database that only gets changed in case of a new incompatible database structure? Because we could then use that file to mark the cache invalid whenever it changes. That would be a simple solution.

**Comment by jeremylong** [comment]
This will be updated when non-backward compatible changes are made:
https://github.com/jeremylong/DependencyCheck/blob/main/core/src/main/resources/dependencycheck.properties#L17
