### ISSUE TITLE
[FP]: swagger-parser-safe-url-resolver flagged for parse-url_project

### ISSUE THREAD

**Issue by nhumblot** [dependency-check/DependencyCheck#6441]
### Package URl

pkg:maven/io.swagger.parser.v3/swagger-parser-safe-url-resolver@2.1.20

### CPE

cpe:2.3:a:parse-url_project::::::::*

### ODC Integration

None

### ODC Version

9.0.9

### Description

This FP has already been declared in #5754 but the suppression rule got limited to the version 2.1.14, which raises an alert again when using another one as a dependency.

**Comment by aggeboe** [comment]
Possible duplicate of https://github.com/jeremylong/DependencyCheck/issues/6422

**Comment by nhumblot** [comment]
> Possible duplicate of https://github.com/jeremylong/DependencyCheck/issues/6422

Sorry, I didn't see your ticket 😦
