### ISSUE TITLE
Dependency Check download failed from NVD

### ISSUE THREAD

**Issue by Matheos96** [dependency-check/DependencyCheck#6444]
**Describe the bug**
Started getting 
`
Some CVEs may not be reported. Reason: Download failed, unable to copy 'file:/dependency-check/NVD/2024-02-02/nvdcve-1.1-2019.json.gz' to '/tmp/dctempc0c002c3-6d22-4b9a-8f70-7fa710fbfc11/cve2019_12428249475753729854.json.gz'; Download failed, file ('file:/dependency-check/NVD/2024-02-02/nvdcve-1.1-2019.json.gz') does not exist
`
today. Anyone else? 

**Version of dependency-check used**
8.2.1 shell script

**Log file**
https://gist.github.com/Matheos96/569dc5f221eda0e180fa168844f2b76d

**Comment by jeremylong** [comment]
if you have file:/// configured - this error is going to be unique to your env.

**Comment by Matheos96** [comment]
Yeah I kind of figured but it started so randomly I blindly believed it would be some server issue...

Now it more seems like it is an issue with our Docker Image that contains the NVD files. We rebuild the image once per day in a separate GitLab pipeline, but apparently we also use the docker cache... So I think that is what messes it up. We don't REALLY re-download the NVDs once per day, because of the cache...

Disabling the cache and creating a new image and using THAT in our pipeline that broke, fixed the issue.

Sorry about the faulty report. BTW, was there talk of some "official" dependency-check Docker image / solution? How is that coming along, or am I mistaken?

**Comment by jeremylong** [comment]
ODC has been published as an image for a while: https://hub.docker.com/search?q=dependency-check

**Comment by Matheos96** [comment]
@jeremylong Thanks! I now remember subscribing to the issue https://github.com/jeremylong/Open-Vulnerability-Project/pull/114 waiting for its docker image to be published. I am a bit unsure what vulnz is now, compared to ODC... Need to research what we actually want

**Comment by jeremylong** [comment]
vulnz is a CLI that can create a mirror of the NVD data which can then be ingested (faster) than the NVD API. While we don't advertise this a lot - you might want to look at the image https://hub.docker.com/r/owasp/dependency-check-action

**Comment by Matheos96** [comment]
> vulnz is a CLI that can create a mirror of the NVD data which can then be ingested (faster) than the NVD API. While we don't advertise this a lot - you might want to look at the image https://hub.docker.com/r/owasp/dependency-check-action

Thanks! I will definitely look into that. We are running ODC in our GitLab pipeline on "shared runners" - meaning we cannot really use volumes to persist the cache. This manner of pulling the latest image of yours each time could be a good alternative I guess :)
