### ISSUE TITLE
No output, miss usage ?  

### ISSUE THREAD

**Issue by VoidScute** [dependency-check/DependencyCheck#6451]
i currently have done a small script to start my scan but i currently have 0 real output/start. 

```bash
bash myscript.sh
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
OpenJDK 64-Bit Server VM warning: Option -Xdebug was deprecated in JDK 22 and will likely be removed in a future release.
OpenJDK 64-Bit Server VM warning: Option -Xnoagent was deprecated in JDK 22 and will likely be removed in a future release.
Listening for transport dt_socket at address: 8000
```

the myscript.sh content : 
```
bash /home/user/dependency-check/bin/dependency-check.sh \
  --nvdApiKey  ${key} \
  --format HTML \
  --format GITLAB \
  --failOnCVSS 3 \
  --out /home/user/project/reports/dependency-check/ \
  --project project \
  --scan /home/user/project/sources \
  --debug \
  --log /home/user/project/reports/dependencies.log
```

Nothing happen and no log files.

**Comment by jeremylong** [comment]
remove `--debug`.

**Comment by VoidScute** [comment]
ok if i understand well --debug start je java debuging server ? somethig like gdb so need a cli to go to next instruction right ? 

if yes do you have good documentation to start with it in connad line ? (i know little out of scope here)

**Comment by jeremylong** [comment]
https://jeremylong.github.io/DependencyCheck/dependency-check-cli/index.html

You'll notice `--debug` isn't even documented. This is a somewhat hidden parameter because the only people that would use it are the developers of dependency-check.
