### ISSUE TITLE
Running Dependency checks without Internet connection

### ISSUE THREAD

**Issue by mgonzcast** [dependency-check/DependencyCheck#6472]
I need to use the dependency check in an offline machine.

What I am currently doing is to download the NVD repositories in a machine connected to the Internet and copy the files under the \.m2\repository\org\owasp\dependency-check-data\9.0 

`mvn -nsu org.owasp:dependency-check-maven:aggregate -Dformats="xml,html" -Ddependency-check.skip="false" -DretireJsForceUpdate="true" -DnvdValidForHours="0" -DnvdApiKey=MY_NVD_KEY -DretireJsURL="https://github.com/Retirejs/retire.js/master/repository/jsrepository.json"`

This downloads the jsrepository.json locally. If I run:

`mvn -nsu org.owasp:dependency-check-maven:aggregate -Dformats="xml,html" -Ddependency-check.skip="false" -DnvdValidForHours="168" -DnvdApiKey=MY_NVD_KEY -Danalyzer.retirejs.repo.js.url="file:///C:\Users\myuser\.m2\repository\org\owasp\dependency-check-data\9.0\jsrepository.json"`

I get:

```
[ERROR] Failed to execute goal org.owasp:dependency-check-maven:9.0.9:aggregate (default-cli) on project espres-core: One or more exceptions occurred during dependency-check analysis: One or more exceptions occurred during analysis:
[ERROR]         InitializationException: Failed to initialize the RetireJS repo: `C:\Users\myfile\AppData\Local\Temp\dctemp313132c7-095d-47d9-86dc-209f8329209d\jsrepository.json` appears to be malformed. Please delete the file or run the dependency-check purge command and re-try running dependency-check.
```

The only way to make it run is using:

`mvn -nsu org.owasp:dependency-check-maven:aggregate -Dformats="xml,html" -Ddependency-check.skip="false" -DnvdValidForHours="168" -DnvdApiKey=MY_NVD_KEY -DretireJsAnalyzerEnabled="false"`

But I would like to know if It is possible to run using the Js Analyzer with a cached copy of the jsrepository.json file

**Comment by aikebah** [comment]
You should just continue to work with `-DretireJsUrl`. The cached copy you should place somewhere else, as ODC will try to download the file from retireJsUrl and save it into `<maven-local-repository>/org/owasp/dependency-check-data/9.0/jsrepository.json`
