### ISSUE TITLE
Version upgrade from 8.x.x

### ISSUE THREAD

**Issue by Sjoerd97** [dependency-check/DependencyCheck#6475]
I have read in the documentation that support for version 8 is suspended and api calls to nvd might fail from 15th of December 2023. Meanwhile our projects still run fine on 8.4.3, there seems to be no urgency to upgrade...
Will in fact api calls soon start to fail? Should we upgrade anytime soon?

**Comment by jeremylong** [comment]
This project has little to no control over the NVD API and data feeds. They put a notice up saying the data feeds would be taken down. however, they received enough feedback that they did not take down the data feeds - but said that they may eventually. I have no idea if/when the upgrade will become mandatory.

**Comment by Sjoerd97** [comment]
Thanks for the insights!

**Comment by Sjoerd97** [comment]
Thanks for the insights
