### ISSUE TITLE
<configuration> not read (<cveUrl20Base> etc.)

### ISSUE THREAD

**Issue by DirkPodolak** [dependency-check/DependencyCheck#649]
I set up an Artifactory cache (in a docker container on CoreOS) for the NIST NVD data, so I want to use for example `http://coreos-artifactory:8081/artifactory/nvd-download/nvdcve-Modified.xml.gz`. I added my URLs in my pom.xml (I use the maven plugin) like this:
```xml
            <plugin>

                <!-- see http://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html -->

                <groupId>org.owasp</groupId>
                <artifactId>dependency-check-maven</artifactId>
                <version>1.4.5</version>

                <configuration>
                    <cveUrl12Modified>http://coreos-artifactory:8081/artifactory/nvd-download/nvdcve-Modified.xml.gz</cveUrl12Modified>
                    <cveUrl20Modified>http://coreos-artifactory:8081/artifactory/nvd-feeds/nvdcve-2.0-Modified.xml.gz</cveUrl20Modified>
                    <cveUrl12Base>http://coreos-artifactory:8081/artifactory/nvd-download/nvdcve-%d.xml.gz</cveUrl12Base>
                    <cveUrl20Base>http://coreos-artifactory:8081/artifactory/nvd-feeds/nvdcve-2.0-%d.xml.gz</cveUrl20Base>
                </configuration>

                <executions>
                    <execution>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

The problem is, maven still tries to download from nvd.nist.gov:
`[ERROR] Unable to resolve domain 'nvd.nist.gov'`

Here is some output: https://gist.github.com/DirkPodolak/a8790e5ad0dafdb0a16b971e85e6c6f3

This is called in Jenkins with

`sh "/usr/bin/mvn -f ProjectA/pom.xml org.owasp:dependency-check-maven:1.4.5:purge"`
`sh "/usr/bin/mvn -f ProjectA/pom.xml org.owasp:dependency-check-maven:1.4.5:check"`

When I add parameters with -D, it works, like this
`sh "/usr/bin/mvn -f ProjectA/pom.xml org.owasp:dependency-check-maven:1.4.5:check -DcveUrl12Modified=http://coreos-artifactory:8081/artifactory/nvd-download/nvdcve-Modified.xml.gz -DcveUrl20Modified=http://coreos-artifactory:8081/artifactory/nvd-feeds/nvdcve-2.0-Modified.xml.gz -DcveUrl12Base=http://coreos-artifactory:8081/artifactory/nvd-download/nvdcve-%d.xml.gz -DcveUrl20Base=http://coreos-artifactory:8081/artifactory/nvd-feeds/nvdcve-2.0-%d.xml.gz"`

It seems like the <configuration> block in my pom.xml is never read. I'm in version 1.4.5.

**Comment by jeremylong** [comment]
I just tested your example on my local machine and it works perfectly. What version of Maven are you using? Can you try running this with `-X` and provide the output?  Also, is there any chance in the pom hierarchy that dependency-check is defined somewhere else and it is running without the configuration you provided?

**Comment by DirkPodolak** [comment]
I'm using mvn 3.2.5, I added a maven log with more details [here](https://gist.github.com/DirkPodolak/d89ae0e0a98278fd05a892e6d84a6b71). I also uploaded a project [here](https://github.com/DirkPodolak/ProjectA).

Can this be a problem with having a maven multi module project?

**Comment by jeremylong** [comment]
Somehow your dependency-check configuration is not being read and the base 1.4.5 configuration is being used.  In jenkins can you run `/usr/bin/mvn -f ProjectA/pom.xml verify` instead of `/usr/bin/mvn -f ProjectA/pom.xml org.owasp:dependency-check-maven:1.4.5:check`?  While this would kick off the entire build it should pick up the dependency-check configuration. If dependency-check doesn't run then you have dependency-check misconfigured in your pom hierarchy.

**Comment by DirkPodolak** [comment]
Hm, I think after doing lots of stuff in Maven I got "dependency check" to work, although I have no idea what had happened. I assume my poor understanding ov Maven is the problem here. Sorry for bothering you and thanks for your support.
