### ISSUE TITLE
Warning messages for NVD API showing up repeatedly

### ISSUE THREAD

**Issue by zxuan99** [dependency-check/DependencyCheck#6497]
![Dependency check error message](https://github.com/jeremylong/DependencyCheck/assets/96758533/0ef0f0e4-8ba0-400e-a249-7e4e5cadec98)
Hi, I have tried to generate the output for the library folder in the dependency folder. However, it keeps showing the warning message - "NVD API request failures are occurring; retrying request for the x times" after it has almost downloaded finished the NVD API data feeds. 

Anyone can share if it is a bug or i have not configured it correctly?

**Comment by devnewton** [comment]
Same bug for me (no proxy, with or without API key).

**Comment by jeremylong** [comment]
NVD API may be experiencing issues. To limit the amount of disruption this can cause see:

- https://jeremylong.github.io/DependencyCheck/data/mirrornvd.html
- https://jeremylong.github.io/DependencyCheck/data/cacheh2.html
