### ISSUE TITLE
DependencyMergingAnalyzer also merges all evidences to main 

### ISSUE THREAD

**Issue by biancajiang** [dependency-check/DependencyCheck#650]
@jeremylong Thanks for #630!  I actually had some local changes very similar but yours is great!

The only side effect is that by merging all evidences to the main dependency, the boundary of dependencies from distinctive analyzers is blur now.  

#### Example
when both dependency by CocoaPodsAnalyzer and dependency by SwiftPackageManagerAnalyzer co-exist (which is not uncommon), it's great DependencyMergingAnalyzer will recognize it and make the CocoaPodsAnalyzer depd the main one, SwiftPackageManagerAnalyzer depd the related.  But by merging the evidence to the main dependency sort of "polluted" the evidence in SwiftPackageManagerAnalyzer depd, even though all evidence are still available from the related dependencies.  

Can the evidence be kept in their original dependency objects so the boundary are kept?  If any use case needs the complete list of evidence, they can still be collected from the bundled dependencies? 

I'd be happy to provide a PR if this sounds reasonable.

**Comment by jeremylong** [comment]
I can't think of a use case for needing the evidence separated more then is already done by the "source" field? As these two package management systems are pointing at the same dependency/artifact - the evidence should be the same. Do you have a concrete reason why this would be needed?

**Comment by biancajiang** [comment]
In addition to vulnerability, we also use the packages identification and their metadata (evidences) for other purposes, where consistent results for packages is key.  So when multiple artifacts co-exist, the distinction of the main vs. related dependencies is important. For example, when both Swift.package and .podspec exist for the same package, evidences from the main dependency source always has priority, unless other sources provide higher confidence evidence.  It worked well before v1.4.5.

Interestingly, it seems the related dependencies do not have evidences anymore, even after [the evidence merge to the main dependency](https://github.com/jeremylong/DependencyCheck/blob/master/dependency-check-core/src/main/java/org/owasp/dependencycheck/analyzer/DependencyMergingAnalyzer.java#L179-L181) is removed.  But I haven't found when the evidence removal was done.  

Any reasons for this change?

**Comment by biancajiang** [comment]
@jeremylong PR #654 is available.

We heavily rely on package metadata for open source package and license for legal compliance purpose.  Hence we are a bit more sensitive to the consistency of package metadata.  The new test class should be able to cover the two cases here.

**Comment by jeremylong** [comment]
@biancajiang one solution to meet your needs would be to disable the core dependency merging analyzer and replace it with your own. would that work?

**Comment by jeremylong** [comment]
@biancajiang I saw you closed the PR. Do you have a solution to this? If the current functionality does not suite your needs, my above solution should work and would allow you to incorporate your modifications into your deployed instance of ODC. If that works I'd like to close this issue. If not, we can discuss other solutions.
