### ISSUE TITLE
CMake Analyser 

### ISSUE THREAD

**Issue by VxrbL** [dependency-check/DependencyCheck#6505]
Hi, newbie to Dependency Check here, just wondering if someone could give me an explanation of how the experimental CMake Analyser works? I have a repo that I want to scan and have set the tool up as a Jenkins plugin, however when I scan the project it doesn't seem to pick up used libraries at all. So yeah a description of the ways in which vulnerabilities are detected would be great (I have also looked at the documentation and didn't seem to find much that helped).

Thanks:)

**Comment by jeremylong** [comment]
See https://jeremylong.github.io/DependencyCheck/analyzers/cmake.html

It is experimental and not a lot of work has gone into this analyzer.

**Comment by VxrbL** [comment]
Hi thanks for the reply Jeremy! I understand that it is experimental and the false positives/negatives that are likely to appear, I was just wondering the patterns that the analyser specifically looks for (i.e. is it looking for find_package() function instances in CMakeLists.txt files) and whether it just scans the plaintext or if other analytical processes take place?

Would be grateful for any further information.

**Comment by jeremylong** [comment]
Best place to find answers like this in an OSS project is the source code:

https://github.com/jeremylong/DependencyCheck/blob/main/core/src/main/java/org/owasp/dependencycheck/analyzer/CMakeAnalyzer.java

**Comment by VxrbL** [comment]
Thank you, found what I was looking for:)
