### ISSUE TITLE
[error]Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by Johnyb32** [dependency-check/DependencyCheck#6508]
I'm getting intermittent failures with the dependency check extension from the Visual Studio Marketplace in the Azure DevOps pipeline.

Here is the output:

Starting: Run dependency security checks

Task         : OWASP Dependency Check
Description  : Dependency Check is a Software Composition Analysis (SCA) tool that attempts to detect publicly disclosed vulnerabilities contained within a project's dependencies.
Version      : 6.1.3
Author       : Dependency Check
Help         : [More Information](https://jeremylong.github.io/DependencyCheck/index.html)

Starting Dependency Check...
Setting report directory to /azp/_work/16/s/depedancy-check-results/
Creating report directory at /azp/_work/16/s/depedancy-check-results/
Downloading Dependency Check latest installer from GitHub..
Cannot read property 'find' of undefined
##[error]Cannot read property 'find' of undefined
##[error]Unhandled error condition detected.
Ending Dependency Check...
Finishing: Run dependency security checks

**Comment by jeremylong** [comment]
Sounds like an issue with the AzureDevops plugin - which isn't supported here. I'd raise the issue here: https://github.com/dependency-check/azuredevops
