### ISSUE TITLE
New Vulnerability in v8 compared with v7

### ISSUE THREAD

**Issue by juanmanuelromeraferrio** [dependency-check/DependencyCheck#6510]
I'm running two different versions of Dependency Check on the same project, version 7.4.4 and version 8.4.2. I have noticed that version 8.4.2 reports a new vulnerability.

Version 7.4.4
<img width="1672" alt="Screenshot 2024-03-08 at 14 56 17" src="https://github.com/jeremylong/DependencyCheck/assets/9562899/e824373a-b666-4afb-acc6-d6938fad1ced">

Version 8.4.2
<img width="1329" alt="Screenshot 2024-03-08 at 14 55 21" src="https://github.com/jeremylong/DependencyCheck/assets/9562899/f63c19a2-f084-4fc1-b842-472a48b06f04">

<img width="1073" alt="Screenshot 2024-03-08 at 15 00 06" src="https://github.com/jeremylong/DependencyCheck/assets/9562899/6d0718c5-cbae-4a33-9d85-8404e97848c9">

Why am I experiencing this difference?

**Comment by jeremylong** [comment]
Bug fixes? new features? 7.x isn't even supported.
