### ISSUE TITLE
Different results depending on search path despite same identifier

### ISSUE THREAD

**Issue by bvwidt** [dependency-check/DependencyCheck#6511]
I use the CLI on Windows in the version 9.0.9 to check a .ASP.NET MVC project with NET Framework 4.8.

I have run the following two commands but I got different results.
I understand that in the first one DependencyCheck also checks existing DLLs.
In the report I see that the same identifiers with highest confidence are used but only in one vulnerabilities are shown. Why?
Why does the check on just the packages.config files not show vulnerabilities even tough the same dependencies in the same versions are found. (See attached screenshots.)

```powershell
PS ...\dependency-check\bin> .\dependency-check.bat --enableExperimental --project 'MyProj' --nvdApiKey <myApiKey> --scan 'C:\path\to\the\project\' -o C:\out\put\path
```

```powershell
PS ...\dependency-check\bin> .\dependency-check.bat --enableExperimental --project 'MyProj' --nvdApiKey <myApiKey> --scan 'C:\path\to\the\project\**\packages.config' -o C:\out\put\path
```

---
---

![Simple](https://github.com/jeremylong/DependencyCheck/assets/2772161/3cb4e45a-ebba-44a9-9349-edeb66b368fa)

---

![Fancy](https://github.com/jeremylong/DependencyCheck/assets/2772161/8440a396-956b-49c1-a462-98a20c2fcdff)

**Comment by jeremylong** [comment]
Because when scanning .NET applications more information can be gleaned from the DLL - which improves the matching. See [how dependency-check works](https://jeremylong.github.io/DependencyCheck/general/internals.html).
