### ISSUE TITLE
Ability to list obsolet suppressions

### ISSUE THREAD

**Issue by mathze** [dependency-check/DependencyCheck#6512]
**Is your feature request related to a problem? Please describe.**
Maintaining suppressions is quite expensive when it comes to obsolet entries. To figure out obsolet suppressions I need to remove single CVEs or manipulate the `until`-date, run dependency-check and check if it shows an error.

**Describe the solution you'd like**
A 'task'/'command' which lists all CVE's which no longer apply.

**Describe alternatives you've considered**
n.a.

**Additional context**
- I'm using the gradle plugin, but this enhancement would be beneficial to all tools.
- I'm using multiple suppression-files, it would be great to also see in which file the obsolet CVE resist.

**Comment by jeremylong** [comment]
Unused suppression rules are already written to the output:

```
LOGGER.info("Suppression Rule had zero matches: {}", rule.toString());
```

**Comment by jeremylong** [comment]
so you could simply grep for this.

**Comment by mathze** [comment]
Thank you for your fast reply.
Unfortunately this does not seem to work.
I've added a suppression not within my project and run `gradlew dependencyCheckAnalyze` task, but the log-message does not occur.
Maybe gradle-plugin is suppressing it in some way?

**Comment by aikebah** [comment]
Gradle in my limited experience suppresses almost all output unless you tell it to use plain console rendering. I typically resort to use the --console=plain CLI option to make gradle show me output of plugins. Maybe that would help in surfacing the logs that the plugin definitely generates.

**Comment by mathze** [comment]
`--info` did the trick :)
Thanks a lot.
