### ISSUE TITLE
Improvement: Sensible default autodetect suppression file for maven plugin

### ISSUE THREAD

**Issue by aikebah** [dependency-check/DependencyCheck#653]
Embracing the maven paradigm of convention over configuration I think it would be good if src/main/dependency-check/suppressions.xml would be automatically be picked up when it is present and the suppression file location is not overridden in the pom-file with a specific configuration value.

For corporate maven environments having such a autodetect default for the suppression files would allow dependency-check plugin to be fully configured in an enterprise parent pom file without the need to override/extend the plugin configuration in project pom files that hit false-positives.

In the past I managed to get this done by just including a filter in the dependency-check plugin configuration. The absence of the filter file would not break the build, it would just trigger a warning and FileNotFoundException stacktrace in the output and continue analysing the project without suppressions. But with the fixes for #215 as can be seen in the issue-comments the absence of a configured filter file is now considered to be a fatal error.

The strategy that I'm considering for this: 
- pom-configured suppression-file (different from the default) still breaking builds (could do an early kill if also checked for existence in the maven plugin)
- if suppression file configured is the default location it is searched for on the file system; when present on the file-system it's added to the settings otherwise it is set to empty string by the maven plugin 

If you consider this a good improvement I'm offering to code it and deliver the results as a pull-request.

**Comment by jeremylong** [comment]
This can be accomplished using core maven functionality; profile activation based on the presence of a file:

```xml
<build>
    <plugins>
        <plugin>
            <groupId>org.owasp</groupId>
            <artifactId>dependency-check-maven</artifactId>
            <version>1.4.5</version>
            <executions>
                <execution>
                    <goals>
                        <goal>check</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>
<profiles>
    <profile>
        <id>dc-suppression</id>
        <activation>
            <file>
                <exists>${basedir}/src/main/config/suppression.xml</exists>
            </file>
        </activation>
        <build>
            <plugins>
                <plugin>
                    <groupId>org.owasp</groupId>
                    <artifactId>dependency-check-maven</artifactId>
                    <configuration>
                        <suppressionFile>${basedir}/src/main/config/suppression.xml</suppressionFile>
                    </configuration>
                </plugin>
            </plugins>
        </build>
    </profile>
</profiles>
```

The only issue might be multi-module builds where you want to have a single suppression file for the entire build. In which case, you could likely just add a second profile that looks for `${project.parent.basedir}/src/main/config/suppression.xml`.

Will this work for you?

**Comment by aikebah** [comment]
That would definitely work for me. Closing this issue since file-based activation of a profiles solves the issue and is cleaner than hard-coding a default with suppression of its usage when the file is not found on the filesystem.
