### ISSUE TITLE
[FP]: org.apache.camel.quarkus/camel-quarkus-core@2.16.0 mixed up with with the outdated org.apache.camel:camel-core@2.16.0

### ISSUE THREAD

**Issue by zenonwch** [dependency-check/DependencyCheck#6538]
### Package URl

pkg:maven/org.apache.camel.quarkus/camel-quarkus-core@2.16.0

### CPE

cpe:2.3:a:apache:camel:2.16.0:*:*:*:*:*:*:*

### ODC Integration

{"label"=>"Maven Plugin"}

### ODC Version

8.4.3

### Description

<img width="1712" alt="image" src="https://github.com/jeremylong/DependencyCheck/assets/17174214/8bb7bc9c-3811-4603-ac67-e3ca2d49f96f">

Vulnerability IDs: [cpe:2.3:a:apache:camel:2.16.0:\*:\*:\*:\*:\*:\*:\*](https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Aapache&cpe_product=cpe%3A%2F%3Aapache%3Acamel&cpe_version=cpe%3A%2F%3Aapache%3Acamel%3A2.16.0)

Package: [pkg:maven/org.apache.camel.quarkus/camel-quarkus-core@2.16.0](https://ossindex.sonatype.org/component/pkg:maven/org.apache.camel.quarkus/camel-quarkus-core@2.16.0?utm_source=dependency-check&utm_medium=integration&utm_content=8.4.3)

**Comment by aikebah** [comment]
approved
