### ISSUE TITLE
Unable to find Dependency-Check reports to parse on Version 9.0.10

### ISSUE THREAD

**Issue by shekharclover** [dependency-check/DependencyCheck#6553]
[INFO] Cache event queue destroyed: CacheEventQueue [listenerId=-2089300313, cacheName=CENTRAL]
[INFO] Region [CENTRAL] : Saving keys to: CENTRAL, key count: 0
[INFO] Region [CENTRAL] : Finished saving keys.
[INFO] Region [CENTRAL] : Shutdown complete.
[INFO] In DISPOSE, [CENTRAL] disposing of memory cache.
[INFO] Memory Cache dispose called.
[INFO] In DISPOSE, [POM] fromRemote [false]
[INFO] In DISPOSE, [POM] auxiliary [POM]
[INFO] In DISPOSE, [POM] put 0 into auxiliary [POM]
[INFO] In dispose, destroying event queue.
[INFO] Cache event queue destroyed: CacheEventQueue [listenerId=-2089300313, cacheName=POM]
[INFO] Region [POM] : Saving keys to: POM, key count: 0
[INFO] Region [POM] : Finished saving keys.
[INFO] Region [POM] : Shutdown complete.
[INFO] In DISPOSE, [POM] disposing of memory cache.
[INFO] Memory Cache dispose called.
[INFO] In dispose, destroying event queue.
[ERROR] Region [NODEAUDIT] : Not alive and dispose was called, filename: NODEAUDIT
[INFO] In dispose, destroying event queue.
[ERROR] Region [CENTRAL] : Not alive and dispose was called, filename: CENTRAL
[INFO] In dispose, destroying event queue.
[ERROR] Region [POM] : Not alive and dispose was called, filename: POM
[ERROR] One or more fatal errors occurred
[ERROR] Unable to connect to the dependency-check database
ERROR: Mark build as failed because of exit code 13
[Pipeline] dependencyCheckPublisher
Collecting Dependency-Check artifact
Unable to find Dependency-Check reports to parse

**Comment by aikebah** [comment]
`[ERROR] One or more fatal errors occurred
[ERROR] Unable to connect to the dependency-check database`

You have an error in your config in some way preventing the CLI from opening a connection to its database.

Without a database dependencycheck will crash, so the Jenkins plugin will not be able to find a report.

**Comment by shekharclover** [comment]
[INFO] Checking for updates
[WARN] An NVD API Key was not provided - it is highly recommended to use an NVD API key as the update can take a VERY long time without an API Key
[ERROR] Error updating the NVD Data; the NVD returned a 403 or 404 error

**Comment by aikebah** [comment]
Check your version #6817
