### ISSUE TITLE
Accelerate CVE DB update: replace TreeSets in Vulnerability by HashSets

### ISSUE THREAD

**Issue by stefanneuhaus** [dependency-check/DependencyCheck#656]
The sets `Vulnerability.vulnerableSoftware` and `Vulnerability.references` use TreeSets. Maintaining the order is especially for vulnerableSoftware quite expensive, as items are very frequently added and `VulnerableSoftware.compareTo()` involves stuff like String splitting.

The only two places where these two collections are being used are:
* `CveDb.updateVulnerability()`: VulnerableSoftware and Reference entities are being inserted into the DB. The order should not matter here, I guess.
* `Vulnerability.toString()`

**Comment by stefanneuhaus** [comment]
I provided a PR that replaces the TreeSets by HashSets.
* `Vulnerability.toString()`: I do not know, where this is being used. Looks like a convenience method for debugging. But at least I guess it is being called rarely. For convenience I kept the sorted output at this place.
* `VulnerabilityTest.testSoftwareSorting()`: Though the sorting was explicitly tested, I hope that there is actually no strong need for this. I removed the test case.

On my machine the speedup for DB update was ~2 min. It dropped from 3:48 min to 1:45 min.

**Comment by jeremylong** [comment]
Thanks - I think I had originally used a sorted set so that the reports (HtmlReport.vsl](https://github.com/jeremylong/DependencyCheck/blob/master/dependency-check-core/src/main/resources/templates/HtmlReport.vsl#L852) would display a sorted list. It will be better to sort the list only on display.

I appreciate the PR.
