### ISSUE TITLE
Last upgrade of dependency-check-gradle:9.1.0 fails creating jackson jar file

### ISSUE THREAD

**Issue by CasaSky** [dependency-check/DependencyCheck#6565]
**Describe the bug**
After upgrading to version dependency-check-gradle:9.1.0  the build fails during clean step.

**Version of dependency-check used**
gradle plugin org.owasp:dependency-check-gradle **9.1.0**

**To Reproduce**
`
sh-3.2$ ./gradlew clean
FAILURE: Build failed with an exception.
What went wrong:
A problem occurred configuring project ':apps:x-service'.
java.util.concurrent.ExecutionException: org.gradle.api.GradleException: Failed to create Jar file /.gradle/caches/jars-9/6b475b24173502a904998db53a2faa11/jackson-core-2.16.1.jar.
`

**Expected behavior**
Successful build

**Comment by jeremylong** [comment]
You need to upgrade gradle. They resolved this bug.

**Comment by CasaSky** [comment]
It works pretty fine with gradle 8.7.
