### ISSUE TITLE
Jenkins Plugin : Dependency-Check v9.x doesn't work with a proxy

### ISSUE THREAD

**Issue by tybobab** [dependency-check/DependencyCheck#6566]
**Describe the bug**
Dependency-Check v9.x doesn't work with a proxy and can't update

**Version of dependency-check used**
Dependency-Check v9.0.9
Dependency-Check v9.0.10

**Log file**
2024-03-22 17:59:31,714 io.github.jeremylong.openvulnerability.client.nvd.RateMeter:83
DEBUG - Ticket taken At: 17:59:31; count: 1; by 49
2024-03-22 17:59:31,715 io.github.jeremylong.openvulnerability.client.nvd.RateLimitedClient:197
DEBUG - Requested At: 17:59:31; URI: /rest/json/cves/2.0?resultsPerPage=2000&startIndex=0
2024-03-22 18:03:52,168 io.github.jeremylong.openvulnerability.client.nvd.NvdApiRetryStrategy:68
DEBUG - Retrying request /rest/json/cves/2.0?resultsPerPage=2000&startIndex=0 : 2 time
2024-03-22 18:06:03,240 io.github.jeremylong.openvulnerability.client.nvd.NvdApiRetryStrategy:68
DEBUG - Retrying request /rest/json/cves/2.0?resultsPerPage=2000&startIndex=0 : 3 time
2024-03-22 18:08:14,312 io.github.jeremylong.openvulnerability.client.nvd.NvdApiRetryStrategy:68
DEBUG - Retrying request /rest/json/cves/2.0?resultsPerPage=2000&startIndex=0 : 4 time

Caused by: org.apache.hc.client5.http.ConnectTimeoutException: Connect to
[https://services.nvd.nist.gov:443](https://services.nvd.nist.gov/)
[services.nvd.nist.gov/54.85.30.225] failed: Connection timed out

**To Reproduce**
- Configure in jenkins a dependency check tool
![image](https://github.com/jeremylong/DependencyCheck/assets/166109904/6feab32c-a3ce-493c-94ef-9f19bcb60ae8)

- In a Jenkins Job, use the dependency check tool and configure the proxy with --proxyserver and --proxyport
![image](https://github.com/jeremylong/DependencyCheck/assets/166109904/05af400a-0ca4-49fb-8679-7735f0f4fcd9)

**Expected behavior**
Depedency Check can use a proxy to do the updates

**Additional context**
I tried Dependency-Check v9.x on another jenkins who is not behind a proxy and the updates work well. 
The updates work well with Dependency-Check v8.x behind a proxy.

**Comment by Spanish93** [comment]
Not a bug, just read the documentation:
https://jeremylong.github.io/DependencyCheck/data/proxy.html

Need to set proxy information on java tools option

**Comment by aikebah** [comment]
Also note that the Jenkins plugin is managed outside of this repository. For Jenkins plugin issues your first place to look is its plugin documentation and its support links (https://plugins.jenkins.io/dependency-check-jenkins-plugin/)

The Jenkins plugin is an external project that uses the CLI variant of this project to run a scan. The exact ways it offers to provide the various required flags for proxy usage I don't know, but you should be able to set the required proxy control variables in some way. If not, the plugin's JIRA would be the location to raise an issue, as the CLI itself is capable of running using a proxy (as pointed to by @Spanish93 )
