### ISSUE TITLE
Are we updating the .NET core dependencies of the Assembly Analyzer to latest version

### ISSUE THREAD

**Issue by dragon040** [dependency-check/DependencyCheck#6575]
Right now .NET core 6.x needs to be installed for this analyzer to work. 

The error says [ERROR] Could not execute .NET AssemblyAnalyzer, is the dotnet 6.0 runtime or sdk installed?

 but even after installing the latest SDK and not dotnet 6 it doest work.

**Comment by aikebah** [comment]
The hard requirement is that at least version 6 of the dotnet runtime is available, not 'version 6 or newer', so installing only latest dotnet SDK will indeed not be sufficient, you need to install v6 of the runtime or sdk too for it to work.

**Comment by jeremylong** [comment]
I'll update the grokassembly project to use 8

**Comment by jeremylong** [comment]
See https://github.com/jeremylong/DependencyCheck/pull/6580
