### ISSUE TITLE
Exception Caught: org.owasp.dependencycheck.analyzer.exception.AnalysisException [DependencyCheck] Cause: zip file is empty

### ISSUE THREAD

**Issue by bmekewar** [dependency-check/DependencyCheck#658]
https://github.com/jeremylong/DependencyCheck/issues/570

This issue is reappeared in 1.4.5

[DependencyCheck] Scanning: /disk1/jenkins/jobs/ACS-OASG-DATABASE-9.0-RPM/workspace
[DependencyCheck] Analyzing Dependencies
[DependencyCheck] One or more exceptions were thrown while executing Dependency-Check
[DependencyCheck] Exception Caught: org.owasp.dependencycheck.analyzer.exception.AnalysisException
[DependencyCheck] Cause: zip file is empty
[DependencyCheck] Message: Exception occurred reading the JAR file (oasg-12c-PSU-160419.zip: opatchauto-core.jar).
Build step 'Invoke OWASP Dependency-Check analysis' marked build as failure
[DependencyCheck] Skipping publisher since build result is FAILURE
[ANALYSIS-COLLECTOR] Skipping publisher since build result is FAILURE

Not sure how to fix it. I suspect if Zip file is big enough to scan (say 2GB) will temp folders still holds the extracted JAR reference folder for scan.

But its mentioned its been fixed in 1.4.4 but re-appearing in 1.4.5.
Please let me know if there are any workaround to fix this issue.

**Comment by jeremylong** [comment]
Is there a download link for the zip file somewhere?  I'd like to be able to replicate the problem in my environment.

**Comment by bmekewar** [comment]
Unfortunately i can not share this file due to corporate security policies.
Zip File is also 2GB in size. 

But if you can verify this with ** _opatchauto-core.jar_ ** this jar; you might be able to reproduce.

Thanks

**Comment by jeremylong** [comment]
Unfortunately, I can't find a copy of opatchauto-core.jar. I have built very large archives and have only been able to replicate using a "broken" zip - i.e. one which other tools, such as 7zip, report errors also.

Any chance the zip file you are scanning has errors when expanded by 7zip?
