### ISSUE TITLE
Enhancement: Add section in report detailing suppressed vulnerabilities 

### ISSUE THREAD

**Issue by seanboylan** [dependency-check/DependencyCheck#66]
Just upgraded to version 1.1.1

Report improvements are very good.

I am using the vulnerability suppression functionality for dependencies that are only used for test purposes and not include in the production image (e.g jetty)

It would be good if the Dependency Check Report included a (collapsed) section detailing the vulnerability suppression that have been applied.

**Comment by jeremylong** [comment]
Good idea. I'll work on this soon.

Jeremy

**Comment by jeremylong** [comment]
full solution to this issue has been pushed to 1.1.5-SNAPSHOT and will be in the next release.
