### ISSUE TITLE
Open Source License Compliance

### ISSUE THREAD

**Issue by sametr35** [dependency-check/DependencyCheck#6606]
Hi,

Does OWASP Dependency-Check scan for open-source license compliance? Typically, SCA tools verify the licenses of the open-source components in your codebase to ensure compliance with their terms. Additionally, if you have documentation or a webpage about it, could you please share the link?

**Comment by jeremylong** [comment]
ODC will report a license if it sees one - but I would not rely on this feature.

**Comment by mirabilos** [comment]
Speaking as someone who audits the licences of all dependencies: the licence metadata in the POMs is often wrong or at the very least incomplete anyway. If you want to ensure full compliance, you *will* have to inspect *every single* dependency (including transitive dependencies) **manually**, and yes, that often includes looking at every single file…

**Comment by jeremylong** [comment]
I completely agree with @mirabilos - researching licensing can be a complicated, tedious task.
