### ISSUE TITLE
Accelerate CVE DB update: parallelize fetching last modification timestamps

### ISSUE THREAD

**Issue by stefanneuhaus** [dependency-check/DependencyCheck#661]
When checking the need for updating the CVE DB the last modification timestamps of the yearly CVE update files are being fetched from a remote host. Currently (year 2017) this sums up to 17 requests. As these requests are being executed sequentially this can make up a couple of seconds (depeding on the internet connection). This could easily be parallelized.

**Comment by jeremylong** [comment]
Thanks for the PR!
