### ISSUE TITLE
java.lang.ClassNotFoundException: org.owasp.dependencycheck.App

### ISSUE THREAD

**Issue by vaparnab** [dependency-check/DependencyCheck#6628]
New installation in ec2 gives this error. 
Followed steps from https://jeremylong.github.io/DependencyCheck/dependency-check-cli/index.html

/usr/bin/dependency-check.sh --version
Error: Could not find or load main class org.owasp.dependencycheck.App
Caused by: java.lang.ClassNotFoundException: org.owasp.dependencycheck.App

Java version in 21.0.2

**Comment by aikebah** [comment]
It would be an anti-pattern to unpack the CLI zip in /usr

So my guess would be you misread the instructions and moved the shellscript to /usr/bin instead of putting the bin folder of the extracted CLI distribution on the PATH environment variable
