### ISSUE TITLE
Restoring Maven 3.0 compatibility

### ISSUE THREAD

**Issue by aikebah** [dependency-check/DependencyCheck#663]
Within my company we are working on a gradual migration from Maven 3.0 to Maven 3.3. We would like to do those in regular maintenance. Incompatibility of the DependencyCheck maven plugin with Maven 3.0 means that until we do that maintenance we can no longer run periodic scans on the codebase of the individual projects until we've made them Maven 3.1+ capable (there are more plugins out there with a 3.0/3.1 version brake that all need careful updating when migrating from 3.0 to 3.1+).

Having Dependency-check be equally capable of running on Maven 3.0 as well as 3.1+ would thus be a great benefit to us as it will enable us to continue scanning all our projects periodically for newly discovered vulnerabilities in our maven-based CI-environment. (We recently found out that our current scans no longer work due to the fix for the symptom mentioned in issue #562, but the fix for that is in 1.4.3 which already requires running Maven 3.1+). 

Looking at the basic functionality of DependencyCheck I suspect that the only reason for incompatibility with older versions of Maven is the dependency-resolution, which was changed to Eclipse Aether in August 2016. 

Is this dependency resolution indeed the only reason for the Maven 3.1+ requirement? 
If so I would propose to use the same version-agnostic depedency resolution that is used by the maven community themselves in e.g. the maven-dependency-plugin for its artifact resolution for dependency:source (using helper libraries from the org.apache.maven.shared groupId). I would be willing to invest time on getting BaseDependencyCheckMojo to resolve artifacts in a similar way and file a pull-request, but before taking the effort would like to ensure that this is indeed the only reason for the Maven 3.1+ requirement of the plugin.

**Comment by jeremylong** [comment]
The issue with dependency resolution is the aggregate goal. At the time the
parent is executing the dependencies of the child modules have not been
resolved.

If you can propose something that will allow the resolution of dependencies
in child modules that will work with 3.0 and later - please let me know.

--jeremy

**Comment by aikebah** [comment]
I want to experiment along the lines of the AbstractDependencyFilterMojo logic of resolving artifacts as present in getClassifierTranslatedDependencies (which gets called for the not-yet resolved source dependencies on the dependency:source goal). 

See [http://svn.apache.org/viewvc/maven/plugins/tags/maven-dependency-plugin-3.0.0/src/main/java/org/apache/maven/plugins/dependency/fromDependencies/AbstractDependencyFilterMojo.java?view=markup#l396](http://svn.apache.org/viewvc/maven/plugins/tags/maven-dependency-plugin-3.0.0/src/main/java/org/apache/maven/plugins/dependency/fromDependencies/AbstractDependencyFilterMojo.java?view=markup#l396) for the source.

I expect that similar logic can be used within DependencyCheck plugin to do the resolution of not-yet resolved artifacts.  I'll keep you posted on the results and will pay specific attention to the aggregate goal.

**Comment by aikebah** [comment]
Finalizing my local changes, cleaning up the modified code a bit before committing, but the preliminary results seem to indicate that with only minor changes to the code it's now working across maven 3.0 and 3.3 (locally testing with mvn 3.0.5 and 3.3.3 on JDK 8).
Pull-request expected to follow Wednesday.

Testing using [Sonatype Maven Example multimodule web spring](https://github.com/sonatype/maven-example-en/blob/master/chapter-multimodule-web-spring.asciidoc), with an added reporting-section with the aggregate configuration of DependencyCheck in the top-level POM and an added distributionManagement site configuration (to make the site goals work)

First running a mvn install on that project once (as otherwise the project internal dependencies cannot be found and result in a build failures halfway through) and then using the following mvn commands, with maven local repo cache cleaned before each attempt for all but the org-structure:

mvn clean site:site site:stage
mvn clean org.owasp:dependency-check-maven:1.4.6-SNAPSHOT:aggregate
mvn clean org.owasp:dependency-check-maven:1.4.6-SNAPSHOT:check

any other scenario's you would deem worthy of testing before finalizing my commit/PR?

**Comment by jeremylong** [comment]
The PR has been merged and will be included in the next release.
