### ISSUE TITLE
The maven plugin does not take into account the vendor, hence many false positives

### ISSUE THREAD

**Issue by zenonwch** [dependency-check/DependencyCheck#6658]
**Describe the bug**
We have the [federation-graphql-java-support-api ](https://mvnrepository.com/artifact/com.apollographql.federation/federation-graphql-java-support-api) dependency in our project, but the dependency-check-maven plugin reports a HIGH vulnerability for it with references for the other vendor library [cpe:2.3:a:apollo_project:apollo:2.0.8:*:*:*:*:*:*:*](https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Aapollo_project&cpe_product=cpe%3A%2F%3Aapollo_project%3Aapollo&cpe_version=cpe%3A%2F%3Aapollo_project%3Aapollo%3A2.0.8).

The [pkg:maven/com.apollographql.federation/federation-graphql-java-support-api@2.0.8](https://ossindex.sonatype.org/component/pkg:maven/com.apollographql.federation/federation-graphql-java-support-api@2.0.8?utm_source=dependency-check&utm_medium=integration&utm_content=9.1.0) has no any known vulnerability nor in the OSS INDEX nor in the NVD

<img width="1767" alt="image" src="https://github.com/jeremylong/DependencyCheck/assets/17174214/7256f404-b647-44c6-bce9-3a078e6a9d26">

This is not the first time when the plugin matches only a "couple of symbols" from the library naming (in the current case the word `apollo`) instead of matching the whole vendor and library names. (https://github.com/jeremylong/DependencyCheck/issues/6538)

**Version of dependency-check used**
The problem occurs using versions 8.4.3 and 9.1.0 of the Maven plugin

**To Reproduce**
1. Add the [federation-graphql-java-support-api ](https://mvnrepository.com/artifact/com.apollographql.federation/federation-graphql-java-support-api) library to the maven dependencies of the project
2. Run the dependency-check-maven plugin

**Expected behavior**
Only vulnerabilities related to the project's dependencies are present in the dependency-check-maven plugin's  report

**Comment by zenonwch** [comment]
Another one example
<img width="1859" alt="image" src="https://github.com/jeremylong/DependencyCheck/assets/17174214/0f4365c1-5386-4759-aac7-a5fd21aa3e5a">
The plugin mixed up our library with the library from the Maven repo

**Comment by OrangeDog** [comment]
The maven group and the CPE vendor often differ for major products. Also, many forks would have a different vendor but have the same vulnerabilities from the shared code.

It is better IMO to have a few false positives like these that you can notice and suppress, than to have many silent false negatives.

Though I agree that dependency check does get a little overenthusiastic about matching these `x_project:x` CPEs to anything containing the word `x`. It doesn't account for Bayes' theorum, unfortunately.

Your second example is because you've named your project exactly the same as a popular open source project. Even a human would assume it's a fork from a first glance.

**Comment by zenonwch** [comment]
I expect that each fork should have its own CPE. What if I fork a project without vulnerabilities, but introduce them in my forked version? By such logic - a project will have a false negative.

**Comment by OrangeDog** [comment]
If someone reports a CVE specifically in that fork then it will get its own CPE, but the NVD is not going to actively track every time anyone makes a fork of anything, even if that were possible to do.

All vulnerabilities that have been introduced but not yet reported are "false negatives", wherever they are.

**Comment by zenonwch** [comment]
And one more: what if I fork a library with vulnerability and give it a totally different name?
How plugin will detect that my forked version has a vulnerability?
IMHO: it's strange to try to "predict" vulnerabilities in a "might be" forked libraries.

Maybe it would be nice to have a configuration flag, that allows to switch on/off strict library name comparison.

**Comment by OrangeDog** [comment]
It doesn't detect it, nor does it try to predict anything.
It's just trying to match artefacts to CPEs, and being strict about it would miss a huge number of issues.

**Comment by zenonwch** [comment]
But I have feelings, that plugin even doesn't try, just found similar letters in the dependency that I use, and in the CPE dependency 😄 .
Anyway - the ability to change comparison behavior would be appreciated.

**Comment by aikebah** [comment]
Feel free to build **and maintain** a full packageUrl-to-CPE index API covering all publicly available packages and we might consider after some time to take it as a trustworthy source of CPE attribution.

Unfortunately there is no authoritive resource to map a library from package coordinates to a CPE, so fuzzy matching and taking the best available match is the best we can do for now (but, as already documented, has a chance of surfacing false positives, for which the suppression mechanism was introduced)

**Comment by aikebah** [comment]
Vendor is incorporated in the matching logic, but not as an authoritive field for the CPE vendor, as there are many cases where vendor in CPE does not match vendor in pom-file.

**Comment by zenonwch** [comment]
@OrangeDog, @aikebah - thanks for the responses.
Will close the question.
