### ISSUE TITLE
[FP]: pkg:nuget/dbup-postgresql@5.0.40

### ISSUE THREAD

**Issue by scrocquesel-ml150** [dependency-check/DependencyCheck#6662]
### Package URl

pkg:nuget/dbup-postgresql@5.0.40

### CPE

`cpe:2.3:a:postgresql:postgresql:5.0.40:*:*:*:*:*:*:*`

### ODC Integration

{"label"=>"CLI"}

### ODC Version

 9.1.0

### Description

Same as https://github.com/jeremylong/DependencyCheck/issues/3608, this is a client library and cpe seems to target server vulnerabilities

**Comment by aikebah** [comment]
approved
