### ISSUE TITLE
javax.servlet.jsp.jstl-1.2.4 false positive using cli v1.4.4

### ISSUE THREAD

**Issue by demasb** [dependency-check/DependencyCheck#672]
The javax.servlet.jsp.jstl-1.2.4 is reporting a false positive with the CPEs:  
- cpe:/a:oracle:glassfish:1.2.4
- cpe:/a:oracle:glassfish_server:1.2.4.
  
The library is located here:
http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.glassfish.web%22%20AND%20a%3A%22javax.servlet.jsp.jstl%22

POM entry is:
```xml
<dependency>
    <groupId>org.glassfish.web</groupId>
    <artifactId>javax.servlet.jsp.jstl</artifactId>
    <version>1.2.4</version>
</dependency>
```

**Comment by jeremylong** [comment]
The fix for this has been committed and will be included in the next release.

Thanks!
