### ISSUE TITLE
OWASP Depedency Checker support for both C and C++ codebase

### ISSUE THREAD

**Issue by pentesty** [dependency-check/DependencyCheck#6723]
Hi Team,

Our requirement is to scan repositories for Software Composition Analysis (SCA) and we are looking after a tool which does this task for both C and C++ codebase. Can you please confirm if Dependency Checker does support both C and C++ codebase for SCA.

Regards,
Vicky

**Comment by jeremylong** [comment]
poorly - and only if they use CMake. See https://jeremylong.github.io/DependencyCheck/analyzers/cmake.html
