### ISSUE TITLE
Unable to connect to central search

### ISSUE THREAD

**Issue by sathish94git** [dependency-check/DependencyCheck#6739]
Can someone guide me with the below error? 

[INFO] Analysis Started
[INFO] Finished Archive Analyzer (3 seconds)
[INFO] Finished File Name Analyzer (0 seconds)
[INFO] Finished Jar Analyzer (1 seconds)
[ERROR] Could not connect to Central search. Analysis failed.
java.io.IOException: Finally failed connecting to Central search. Giving up after 7 tries.

**Comment by aikebah** [comment]
Running with debug logging should surface more detail. The error indicates that in some way you have a connectivity error towards Maven Central search facility (search.maven.org unless you've overridden it in your configuration)
Depending on the exact timing when you had issues it may have been during short interruptions of Maven's "legacy search" as listed on https://status.maven.org/
