### ISSUE TITLE
The lastest dependecy check release version  is taking more than 40 min utes to build ot check for nvd updates any reason?  is something wrong?

### ISSUE THREAD

**Issue by pavanbakkani** [dependency-check/DependencyCheck#6747]
[INFO] Checking for updates

**Comment by danshome** [comment]
I'm seeing the same thing.  It's taking forever to update. We are using 9.2.0.  I haven't changed a thing in weeks and we are getting...


22:25:01 [INFO] Checking for updates
22:26:20 [INFO] NVD API has 255,482 records in this update
22:27:08 [WARNING] NVD API request failures are occurring; retrying request for the 5 time
22:27:09 [WARNING] NVD API request failures are occurring; retrying request for the 5 time
22:28:14 [INFO] Downloaded 10,000/255,482 (4%)
22:28:17 [WARNING] NVD API request failures are occurring; retrying request for the 5 time
22:28:23 [WARNING] NVD API request failures are occurring; retrying request for the 5 time
22:29:03 [INFO] Downloaded 20,000/255,482 (8%)
22:29:55 [INFO] Downloaded 30,000/255,482 (12%)
22:30:08 [WARNING] NVD API request failures are occurring; retrying request for the 5 time
22:30:36 [INFO] Downloaded 40,000/255,482 (16%)

**Comment by chadlwilson** [comment]
Probably due to https://github.com/jeremylong/DependencyCheck/issues/6746 and https://github.com/jeremylong/Open-Vulnerability-Project/issues/163

**Comment by mertartanbtc** [comment]
I'm having the same problem

**Comment by chadlwilson** [comment]
There's work ongoing to fix the root issue within ODC, but it'll require an upgrade. "Me too" doesn't help anyone. :-)
