### ISSUE TITLE
[Feature Request] Add support for CSV output format

### ISSUE THREAD

**Issue by mceli2** [dependency-check/DependencyCheck#675]
It would be good for the command line tool to have the option to save the output in CSV format so the results can be imported to other platforms, such as IBM Security AppScan Enterprise which allows the import of issues from other scanners in CSV format:
[https://www.ibm.com/support/knowledgecenter/SSW2NF_9.0.1/com.ibm.ase.help.doc/topics/t_workflow_import_issues.html](url)

**Comment by jeremylong** [comment]
Thanks for the suggestion - this should be fairly easy to implement.

**Comment by jeremylong** [comment]
CSV format will be included in the next release.
