### ISSUE TITLE
gradle plugin version 10.0.0 not yet available

### ISSUE THREAD

**Issue by soleetions** [dependency-check/DependencyCheck#6763]
The documentation (https://jeremylong.github.io/DependencyCheck/dependency-check-gradle/) mentions version 10.0.0 for the gradle plugin.

On the gradle site (https://plugins.gradle.org/plugin/org.owasp.dependencycheck), the latest version is still 9.2.0
Local build also reports that it can't find version 10.0.0

When can we expect version 10.0.0 for the gradle plugin?

**Comment by jeremylong** [comment]
sorry - I had other commitments yesterday and ran out of time. The gradle plugin has been published.

Note - with 10.0.0 you may see `[ERROR] Updating CVE-####-#####`. This was leftover debug code that will be removed with 10.0.1.

**Comment by soleetions** [comment]
Thanks for adding!
