### ISSUE TITLE
Maven plugin: Improve SNAPSHOT version detection for virtual dependencies

### ISSUE THREAD

**Issue by blutorange** [dependency-check/DependencyCheck#6766]
**Is your feature request related to a problem? Please describe.**

When using the aggregate goal, the plugin should detect dependencies with versions such as `8.2.0-SNAPSHOT+feature.x` or `8.2.0-SNAPSHOT.feature-x` and use a virtual dependency. Currently, it treats such dependencies as stable versions that are read from the local or remote repository. In a multi-module project, when the Maven build does not include the install goal, this may result in vulnerabilities being detected that are not present anymore.

When I set the version to e.g. `8.2.0-SNAPSHOT`, the maven build includes messages such as

> [INFO] Found snapshot reactor project in aggregate for group.id:artifact-id:8.2.0-SNAPSHOT - creating a virtual dependency as the snapshot found in the repository may contain outdated dependencies.

Once I set the version to e.g. `8.2.0-SNAPSHOT.feature-x`, it does not include such messages anymore.

Note 1: We do not run the install goal in CI builds to prevent issues when multiple build jobs attempt to write files to the local repository.

Note 2: We use versions such as `8.2.0-SNAPSHOT+feature.x` for feature branches so it does not collide with the main branch.

**Describe the solution you'd like**

Virtual dependencies were introduced by #1601 (see also the flag `virtualSnapshotsFromReactor`). To determine whether a dependency is a snapshot, it [calls the isSnapshot method on the Maven artifact](https://github.com/aikebah/DependencyCheck/blob/754dec1cdc8457bcd8062e87b1021ae4e60ac543/maven/src/main/java/org/owasp/dependencycheck/maven/BaseDependencyCheckMojo.java#L2826). When I check the Maven repo, it seem the [Artifact#isSnapshot](https://github.com/apache/maven/blob/57fd0dc69bd089d106738313ba8d3f7230f9315c/maven-artifact/src/main/java/org/apache/maven/artifact/ArtifactUtils.java#L51-L64) method essentially just detects versions such as `x.y.z-SNAPSHOT`, `x.y.z-LATEST-20240830-221431.2` (with the `SNAPSHOT` or `LATEST` prefix and optional a timestamp) as snapshots.

As far as I'm aware, there's no well-defined definition when a Maven version is a snapshot. But the current behavior seems to narrow to me. My suggestion would be as follows:

* Keep the current check for whether a version is snapshot, but when it reports false, also check the following
  * The version should be a valid https://semver.org/, possibly  with an optional patch version
  * The pre-release version, when present, consists one one or more identifiers. Check whether any of these identifiers is equal to either `SNAPSHOT` or `LATEST`.
  * Ignore build metadata

**Comment by aikebah** [comment]
If you were to mvn deploy your build maven would put your binaries in the releases repository. 

It's exactly why we rely on Maven's decision whether something is a snapshot or not.

In the maven ecosystem a SNAPSHOT is anything that Maven's Artifact#isSnapshot considers a snapshot. And that is anything that ends in either `-SNAPSHOT` or `-<YYYYMMDD.HHmmss>-<buildnumber>`, the second format is Maven's 'uniqueSnapshots' format.

SemVer is dealing with versioning of releases. The prerelease in semver is meant for stable versions of alpha/beta/release-candidate releases.
