### ISSUE TITLE
Problem running DependencyCheck offline mode

### ISSUE THREAD

**Issue by tamtam22** [dependency-check/DependencyCheck#678]
Log: https://gist.github.com/tamtam22/059ef651caa0ddc90f8297b134f23eee

Prerequisite: Workstation is offline

1) I used the NIST Data Mirror plugin and downloaded all files to "C:\Users\User\nvd_nist_mirror"

2) In my java file, this is how I define it:
```java
Settings.initialize();
Settings.setString(Settings.KEYS.CONNECTION_TIMEOUT, "10000");
Settings.setBoolean(Settings.KEYS.ANALYZER_CENTRAL_ENABLED, false);

try {
    // C:/Users/User/nvd_nist_mirror/
    String cve_db_location = new File(getClass().getProtectionDomain().getCodeSource().getLocation().toURI().getPath()).getParent().replace("\\", "/") + "/nvd_nist_mirror/";
    Settings.setString(Settings.KEYS.CVE_MODIFIED_12_URL, "file:///" + cve_db_location + "nvdcve-Modified.xml.gz");
    Settings.setString(Settings.KEYS.CVE_MODIFIED_20_URL, "file:///" + cve_db_location + "nvdcve-2.0-Modified.xml.gz");
    Settings.setString(Settings.KEYS.CVE_SCHEMA_1_2, "file:///" + cve_db_location + "nvdcve-%d.xml.gz");
    Settings.setString(Settings.KEYS.CVE_SCHEMA_2_0, "file:///" + cve_db_location + "nvdcve-2.0-%d.xml.gz");
    Settings.setInt(Settings.KEYS.CVE_CHECK_VALID_FOR_HOURS, 168);
    Settings.setBoolean(Settings.KEYS.AUTO_UPDATE, false);
    LOGGER.info("Using cached NVD NIST mirror at " + cve_db_location);
} catch (Exception ex) {
    LOGGER.error("Failed to use cached NVD NIST mirror");
    ex.printStackTrace();
}
```

The dc.h2.db file in /data is only 64kb.

How do i go about fixing this or forcing the db to update based on the offline files?

Interestingly in the log file it shows file:/ instead of file:/// , and if I add 2 more slashes, the exception shows file:///// instead of file:///

**Comment by stevespringett** [comment]
I have not tried file URLs, but do attest that HTTP URLs work. My org has a centralized NVD mirror that is accessible over HTTP.

**Comment by tamtam22** [comment]
Yes HTTP works fine, not a problem.

This only happens when performed "offline" for the first time, in conjunction with NIST Data Mirror plugin.

With HTTP, the dc.h2.db is at least a few MB. However, when initializing while offline the size is only 64kb. If I copy over the dc.h2.db which is in MB to replace the 64kb db, then everything works like normal. So I suspect the db is not updated as it should while offline.

I tried tinkering with AUTO_UPDATE true while offline but it is still 64kb

**Comment by jeremylong** [comment]
Delete the local DB file. Set autoupdate to true. Then try re-running and if it fails can you please provide the full log not just the snippet with the error?

**Comment by tamtam22** [comment]
When I created a brand new project with the following code, the update works (while offline). I shall mark this as solved and continue checking on my application instead.

For those interested in the test code (just to test if it works...):

~~~~
package com.test.test;

import org.owasp.dependencycheck.Engine;
import org.owasp.dependencycheck.utils.Settings;

import java.io.File;
import java.util.ArrayList;

public class Main {

	public static void main(String[] args) {
		String cve_db_location = "C:/Users/User/nvd_nist_mirror/";

		Settings.initialize();
		Settings.setString(Settings.KEYS.CONNECTION_TIMEOUT, "10000");
		Settings.setBoolean(Settings.KEYS.ANALYZER_CENTRAL_ENABLED, false);

		Settings.setString(Settings.KEYS.CVE_MODIFIED_12_URL, "file:///" + cve_db_location + "nvdcve-Modified.xml.gz");
		Settings.setString(Settings.KEYS.CVE_MODIFIED_20_URL, "file:///" + cve_db_location + "nvdcve-2.0-Modified.xml.gz");
		Settings.setString(Settings.KEYS.CVE_SCHEMA_1_2, "file:///" + cve_db_location + "nvdcve-%d.xml.gz");
		Settings.setString(Settings.KEYS.CVE_SCHEMA_2_0, "file:///" + cve_db_location + "nvdcve-2.0-%d.xml.gz");

		Settings.setInt(Settings.KEYS.CVE_CHECK_VALID_FOR_HOURS, 168);
		Settings.setBoolean(Settings.KEYS.AUTO_UPDATE, true);

		try {
			Engine engine = new Engine();
			engine.scan(new ArrayList<File>());
			engine.analyzeDependencies();
		} catch (Exception ex) {
			ex.printStackTrace();
		}
	}
}
~~~~

Output:
https://gist.github.com/tamtam22/5edab2ea675eb9cdcd90b75dfddf5f30#file-gistfile1-txt

**Comment by tamtam22** [comment]
Hi,

Re-opening this again. I found the issue:

The path in Settings.getDataFile() cannot contain spaces, otherwise the operation will fail...

`C:/Users/User/spacecheck/nvd_nist_mirror/` <-- OK
`C:/Users/User/space check/nvd_nist_mirror/` <-- ERROR

Log file showing error because there is a space in Settings.getDataFile():
https://gist.github.com/tamtam22/b2fca26b4136764e9f3b0768ba045a34

**Comment by stevespringett** [comment]
Glad you narrowed down the issue. Based on this new information, I do not think the issue is with Dependency-Check. [RFC-3986](https://www.ietf.org/rfc/rfc3986.txt) requires that spaces and other special characters are percent encoded.

This would mean the following code would potentially solve the issue:

```java
Settings.setString(Settings.KEYS.CVE_MODIFIED_12_URL, URLEncoder.encode("file:///" + cve_db_location + "nvdcve-Modified.xml.gz", "UTF-8"));
Settings.setString(Settings.KEYS.CVE_MODIFIED_20_URL, URLEncoder.encode("file:///" + cve_db_location + "nvdcve-2.0-Modified.xml.gz", "UTF-8"));
Settings.setString(Settings.KEYS.CVE_SCHEMA_1_2_URL, URLEncoder.encode("file:///" + cve_db_location + "nvdcve-%d.xml.gz", "UTF-8"));
Settings.setString(Settings.KEYS.CVE_SCHEMA_2_0, URLEncoder.encode("file:///" + cve_db_location + "nvdcve-2.0-%d.xml.gz", "UTF-8"));
```

Let us know the results.

**Comment by stevespringett** [comment]
Actually, that code may not work, the %d may end up double encoded. So you may have to resort to encoding just the cve_db_location manually instead to account for spaces and other characters.

**Comment by tamtam22** [comment]
Thanks for the speedy reply. I tried and yup there seems to be some url error.
Path with space: `C:/Users/User/My Projects`
So I tried with just encoding the cve_db_location, and modified code to as follows:
```java
String jarLocation = new File(getClass().getProtectionDomain().getCodeSource().getLocation().toURI().getPath()).getParent().replace("\\", "/");
String cve_db_location = jarLocation + "/nvd_nist_mirror/";
String data_location = jarLocation + "/data/";

Settings.setString(Settings.KEYS.CVE_MODIFIED_12_URL, "file:///" + URLEncoder.encode(cve_db_location, "UTF-8") + "nvdcve-Modified.xml.gz");
Settings.setString(Settings.KEYS.CVE_MODIFIED_20_URL, "file:///" + URLEncoder.encode(cve_db_location, "UTF-8") + "nvdcve-2.0-Modified.xml.gz");
Settings.setString(Settings.KEYS.CVE_SCHEMA_1_2, "file:///" + URLEncoder.encode(cve_db_location, "UTF-8") + "nvdcve-%d.xml.gz");
Settings.setString(Settings.KEYS.CVE_SCHEMA_2_0, "file:///" + URLEncoder.encode(cve_db_location, "UTF-8") + "nvdcve-2.0-%d.xml.gz");

LOGGER.info("Using cached NVD NIST mirror at " + cve_db_location);
Settings.setString(Settings.KEYS.DATA_DIRECTORY, URLEncoder.encode(data_location, "UTF-8"));
```

Unfortunately encountered another error (UnknownFormatConversionException) - see log:
https://gist.github.com/tamtam22/52af7fab2a630eaf048ec21a1871f506

The %2F is creating a conflict with the String.format inside the for loop at `private UpdateableNvdCve retrieveCurrentTimestampsFromWeb()` in NveCveUpdater.java , there's too many % in the String.format

**Comment by stevespringett** [comment]
For a quickfix, try just encoding the unknown part of the path..

```java
String cve_db_location = "C:/Users/User/nvd nist mirror/";
String encodedPath = URLEncoder.encode(cve_db_location, "UTF-8");

Settings.setString(Settings.KEYS.CVE_MODIFIED_12_URL, "file:///" + encodedPath + "nvdcve-Modified.xml.gz");
Settings.setString(Settings.KEYS.CVE_MODIFIED_20_URL, "file:///" + encodedPath + "nvdcve-2.0-Modified.xml.gz");
Settings.setString(Settings.KEYS.CVE_SCHEMA_1_2, "file:///" + encodedPath + "nvdcve-%d.xml.gz");
Settings.setString(Settings.KEYS.CVE_SCHEMA_2_0, "file:///" + encodedPath + "nvdcve-2.0-%d.xml.gz");
```

If for some reason that does not work, you could also do a regex search/replace. For example: 

```java
String cve_db_location = "C:/Users/User/nvd nist mirror/";
String encodedPath = cve_db_location.replaceAll(" ", "%20");
```

**Comment by tamtam22** [comment]
Hi steve,

Tried both quick fixes, unfortunately they don't work as expected.

Log:
https://gist.github.com/tamtam22/d1afe79f7c57a401f4f2606988ec8301

**Comment by jeremylong** [comment]
Sorry for the delayed response to this - the issue is the URL encoded space being sent to String.formater. So you could escape the percent by doing the following:

```java
String cve_db_location = "C:/Users/User/nvd nist mirror/";
String encodedPath = URLEncoder.encode(cve_db_location, "UTF-8");

Settings.setString(Settings.KEYS.CVE_MODIFIED_12_URL, "file:///" + encodedPath + "nvdcve-Modified.xml.gz");
Settings.setString(Settings.KEYS.CVE_MODIFIED_20_URL, "file:///" + encodedPath + "nvdcve-2.0-Modified.xml.gz");
Settings.setString(Settings.KEYS.CVE_SCHEMA_1_2, "file:///" + encodedPath.replace("%","%%") + "nvdcve-%d.xml.gz");
Settings.setString(Settings.KEYS.CVE_SCHEMA_2_0, "file:///" + encodedPath.replace("%","%%") + "nvdcve-2.0-%d.xml.gz");
```

**Comment by tamtam22** [comment]
I applied the fix as mentioned but still running into exception problems with "No documents exist"

https://gist.github.com/tamtam22/c294803354feb0b07ddf057e2f4d8958

**Comment by tamtam22** [comment]
I applied the fix as mentioned but still running into exception problems with "No documents exist"

Debug log (first run with no data downloaded yet):
https://gist.github.com/tamtam22/38bfba46418f4539e0aab8ec29dd76fc

Debug log (Subsequent runs):
https://gist.github.com/tamtam22/8814aab725f81ffaa02390701d7255bb

The DB file in [jar]/data/dc.h2.db is only 64kb. Tested on a fresh project with internet connection.

I noticed there is space in JDBC connection string as well, but there's no error shown so I can't confirm if it is because of that.

**Comment by jeremylong** [comment]
The error is with the file URI not being correct. If the connection string was wrong you would not end up with an empty database.  What I would recommend is setting up a unit test in your code to create the file URI and then test if the file URI is valid.

**Comment by tamtam22** [comment]
Thanks for pointing in the right direction. The URI was incorrect due to the + (plus) sign during encoding.

Solution as such (for those who need):
```java
String jar_location = new File(getClass().getProtectionDomain().getCodeSource().getLocation().toURI().getPath()).getParent().replace("\\", "/");
String cve_db_location = jar_location + "/nvd_nist_mirror/";
String encodedPath = URLEncoder.encode(cve_db_location, "UTF-8").replace("+", "%20");

Settings.setString(Settings.KEYS.CVE_MODIFIED_12_URL, "file:///" + encodedPath + "nvdcve-Modified.xml.gz");
Settings.setString(Settings.KEYS.CVE_MODIFIED_20_URL, "file:///" + encodedPath + "nvdcve-2.0-Modified.xml.gz");
Settings.setString(Settings.KEYS.CVE_SCHEMA_1_2, "file:///" + encodedPath.replace("%", "%%") + "nvdcve-%d.xml.gz");
Settings.setString(Settings.KEYS.CVE_SCHEMA_2_0, "file:///" + encodedPath.replace("%", "%%") + "nvdcve-2.0-%d.xml.gz");

Settings.setInt(Settings.KEYS.CVE_CHECK_VALID_FOR_HOURS, 744); // every 30 days
Settings.setBoolean(Settings.KEYS.AUTO_UPDATE, true);
```
