### ISSUE TITLE
Bump PostgresQL version schema to version 5.5

### ISSUE THREAD

**Issue by ghilainm** [dependency-check/DependencyCheck#6780]
https://github.com/jeremylong/DependencyCheck/blob/4d47fb91f53df538670f433b6017653efcca5fbc/core/src/main/resources/data/initialize_postgres.sql#L327

**Comment by chadlwilson** [comment]
This has been done at https://github.com/jeremylong/DependencyCheck/pull/6779 already, awaiting a release/build.

**Comment by jeremylong** [comment]
This doesn't need a "release" as users will generally grab this from the repo.
