### ISSUE TITLE
Can dependency-check scan remote repositiories?

### ISSUE THREAD

**Issue by eve1ynjiang** [dependency-check/DependencyCheck#6782]
In the --scan parameter is there a way to access a github repository remotely? Or do I have to clone it and store it locally?

**Comment by aikebah** [comment]
> The path to scan - this option can be specified multiple times. It is also possible to specify Ant style paths (e.g. ‘directory/**/*.jar’); if using an Ant style path it is highly recommended that you use single quotes around the path so that the shell itself does not automatically perform replacements

path to scan, so no, you cannot scan repositories, you have to clone it on the filesystem.
