### ISSUE TITLE
Adding a configurable update window

### ISSUE THREAD

**Issue by danfoley1991** [dependency-check/DependencyCheck#6783]
Appreciate the work that does into maintaining this plugin. My aim is to reduce API usage as much as possible. 

Current setup: On a 3 hourly basis, I set my CI to refresh the database such that every other build that gets carried out reuses the same NIST database built, avoiding most API calls.

The NIST database doesn't require reaching out to update for a fixed 240 minute window. As my NIST cache build only kicks off every 3 hours, one build may not reach out to get the latest as the cache is still valid. This means 1 hour later when the 240 minutes expires, all other CI builds start reaching out and hitting rate limits. 

I use an API key and have increased delay to help this but what would be ideal is if the 240 minutes config could be configurable so that i can reduce it to a slightly smaller time for my 3 hour cache refresh build. This would ensure that the cache is always up to date and avoids and other builds reaching out.

I'm happy to make the code change and contribute but wanted to run it back the maintainers to ensure its ok.

**Comment by danfoley1991** [comment]
I think I'm being blind, NVD_API_VALID_FOR_HOURS looks to be the config i need

**Comment by aikebah** [comment]
@danfoley1991 Clearly not blind... as you managed to find it on a second read
