### ISSUE TITLE
The database index "idxVulnerability" on the column "vulnerability.cve" is redundant

### ISSUE THREAD

**Issue by nikita-efremov1** [dependency-check/DependencyCheck#6788]
We have found two indices on the "vulnerability.cve" column in the postgreSql database:
1. The first one is created [automatically](https://github.com/jeremylong/DependencyCheck/blob/v10.0.1/core/src/main/resources/data/initialize_postgres.sql#L19) because of column uniqueness.
2. The second one is created [manually](https://github.com/jeremylong/DependencyCheck/blob/v10.0.1/core/src/main/resources/data/initialize_postgres.sql#L77).

Since "cve" column is unique is doesn't make sense to create a separated index.
Sometimes it might lead to performance issues.
This is relevant at least for [postgreSql](https://www.postgresql.org/docs/current/indexes-unique.html), [Oracle](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/constraint.html), mysql and mssql databases.

![Screenshot 2024-07-02 at 13 58 34](https://github.com/jeremylong/DependencyCheck/assets/104001148/8fffb6c9-171d-42a9-a8d2-15bc2c4871ce)

**Comment by jeremylong** [comment]
good enough - the second index can be removed. We accept PRs.
