### ISSUE TITLE
False positive CPE (cpe:/a:jcore:jcore:0.7.2) for Apache mime4j

### ISSUE THREAD

**Issue by tazle** [dependency-check/DependencyCheck#679]
False positive CPE for org.apache.james:apache-mime4j-core:0.7.2, reported as cpe:/a:jcore:jcore:0.7.2. Based on CVEs, cpe:/a:jcore:jcore is some PHP CMS.

**Comment by jeremylong** [comment]
Thanks, the suppression rule has been added and will be included in the next release.
