### ISSUE TITLE
SQL-Error and wrong version in initialize_mysql.sql since v10.0.0

### ISSUE THREAD

**Issue by SiffKopp** [dependency-check/DependencyCheck#6790]
**Comma missing at the end of the line.
Table-creation fails.**

https://github.com/jeremylong/DependencyCheck/blob/4d47fb91f53df538670f433b6017653efcca5fbc/core/src/main/resources/data/initialize_mysql.sql#L189

**Version must be 5.5. Update-Script for 10.0.1 checks for schema-version and stops.**

https://github.com/jeremylong/DependencyCheck/blob/4d47fb91f53df538670f433b6017653efcca5fbc/core/src/main/resources/data/initialize_mysql.sql#L382

**Comment by jeremylong** [comment]
already resolved. See the current version of the file.

**Comment by jeremylong** [comment]
https://github.com/jeremylong/DependencyCheck/blob/26ef335342b0bec8bb10fdb3a7fbda95692a1fb8/core/src/main/resources/data/initialize_mysql.sql#L382

**Comment by SiffKopp** [comment]
Cool, thx.
