### ISSUE TITLE
Version 10.0.1 is taking longer to complete the 9.2.0

### ISSUE THREAD

**Issue by debbiehawkes** [dependency-check/DependencyCheck#6793]
After upgrading from owasp/dependency-check:9.2.0 to 10.0.1, the time taken to execute the dependency check has increased from ~5 mins to ~40 mins. 

I'm using the exact same command, the only difference is the docker image version being used.

Has anyone else experience this?

**Comment by chadlwilson** [comment]
Duplicate of #6758 

It's not directly caused by the update.
