### ISSUE TITLE
NVD API update is hanging

### ISSUE THREAD

**Issue by ghost** [dependency-check/DependencyCheck#6797]
I am getting this issue on the latest 10.0.1 version. My maven apps are working as expected with the new version. 

My API key is valid. 

./gradlew dependencyCheckAggregate

> Task :dependencyCheckAggregate
Verifying dependencies for project
Checking for updates and analyzing dependencies for vulnerabilities
Unable to update 1 or more Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.
Unable to continue dependency-check analysis.

Region [NODEAUDIT] : Not alive and dispose was called, filename: NODEAUDIT
Region [CENTRAL] : Not alive and dispose was called, filename: CENTRAL
Region [POM] : Not alive and dispose was called, filename: POM

> Task :dependencyCheckAggregate FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dependencyCheckAggregate'.
> Analysis failed.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.6.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 40m 12s
1 actionable task: 1 executed

**Comment by chadlwilson** [comment]
This is probably a duplicate of #6758

You may have to increase retries or delays. Otherwise, need to turn on more detailed logging, such as with `--info` to see what is going on.
