### ISSUE TITLE
Update to the latest CWE

### ISSUE THREAD

**Issue by jeremylong** [dependency-check/DependencyCheck#68]
We need to refresh the CWE data to use the newest version.

**Comment by hgomez** [comment]
What does it means ?

**Comment by jeremylong** [comment]
Sorry - wrote the wrong thing yesterday. I meant update to the latest CWE. In the NVD CVE data all we get is the CWE ID #. The tool has a serialized hashmap of the CWE data so that we can lookup the CWE name based on the CWE ID.
