### ISSUE TITLE
Dependency-Check-plugin failing while updating NVD

### ISSUE THREAD

**Issue by 1-mrudulaahire** [dependency-check/DependencyCheck#6806]
Hello Team, 
I am just upgraded Dependency-Check-plugin to version 9.2.0. as per recommended without an NVD API key as it not compulsory. With updated verification
when tried on local environment it run sucessfully. Download and updated all NVD. But when i am trying it same config on Jenkins it failing there while at start only with below exception of 403/404.

Why is this difference?

Environment: maven
Config set for Dependency-Check-plugin

<Plugin>
  <groupid>org.owasp</groupid>
<artifactid>Dependency-Check-plugin</artifactid>
<Version>9.2.0</Version>
<inherited>false</inherited>
<dependencies>
<dependency>
<groupid>org.owasp</groupid>
<artifactid>Dependency-Check-plugin</artifactid>
<Version>9.2.0</Version>
</dependency>
<config...>
<assemblyAnalyzerEnabled> false</assemblyAnalyzerEnabled>
<nugetConfAnalyzerEnabled>false</nugetConfAnalyzerEnabled>
<failBuidOnCVSS>0</failBuidOnCVSS>
</config...>
<execution>
....
</execution>
</dependencies>
</Plugin>

**Comment by jeremylong** [comment]
Two things - you must upgrade to 10.0.0+ due to changes at the NVD. Second, see https://github.com/jeremylong/DependencyCheck/issues/6758

**Comment by njefsky** [comment]
10.0.1 still fails, we run this on AzureDevops and TeamCity agents and all are failing at this point.

**Comment by jeremylong** [comment]
See #6758
