### ISSUE TITLE
Database error when upgrading from v9.1.0 to v10.0.2

### ISSUE THREAD

**Issue by i-dodds** [dependency-check/DependencyCheck#6824]
Hello,

Following the recent issues with the NVD service I'm upgrading to v10.0.2 of the maven plugin.  However, I'm receiving the following exception during the maven build:

[INFO] [ERROR] Failed to execute goal org.owasp:dependency-check-maven:10.0.2:check (default) on project my-service: Fatal exception(s) analyzing my-service: One or more exceptions occurred during analysis:
[INFO] [ERROR] DatabaseException: Unable to connect to the dependency-check database
[INFO] [ERROR] caused by DatabaseException: Database schema does not match this version of dependency-check
[INFO] [ERROR] caused by DatabaseException: Unable to upgrade the database schema from 5.4 to 5.5
[INFO] [ERROR] caused by JdbcSQLSyntaxErrorException: Duplicate column name "V4VERSION"; SQL statement:
[INFO] [ERROR] ALTER TABLE vulnerability ADD   COLUMN v4version VARCHAR(5) [42121-214]

All I have done is change the plugin version from 9.1.0 to 10.0.2 in the POM.xml file.  I'm not using a central database, this is my plugin config:

                    <plugin>
                        <groupId>org.owasp</groupId>
                        <artifactId>dependency-check-maven</artifactId>
                        <version>10.0.2</version>
                        <configuration>
                            <nvdApiKey>[my API key]</nvdApiKey>
                            <formats>HTML,JSON</formats>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>check</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>

Any advice on how to proceed would be appreciated, e.g. do I need to remove the local database to allow the new version to be created?

Best regards,
Ian.

**Comment by jeremylong** [comment]
Not sure what happend - it is almost like it tries to update the DB twice. The best option would be to simply:

```shell
mvn org.owasp:dependency-check-maven:purge
mvn org.owasp:dependency-check-maven:update-only
```

**Comment by i-dodds** [comment]
Thank you Jeremy, that worked a treat.

Best regards,
Ian.

**Comment by balacloudtech** [comment]
@jeremylong I am using the below pom.xml , when i try to upgrade the dependency database check from 7 to 8 , it is showing the error as ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++01:01:34  [ERROR] Failed to execute goal org.owasp:dependency-check-maven:8.4.3:update-only (default-cli) on project dependency-check-db-sync: An exception occurred connecting to the local database. Please see the log file for more details. Database schema does not match this version of dependency-check: Database schema is out of date -> [Help 1]+++++++++
How to resolve it ?
Pom/xml files is below : ```xml
<?xml version="1.0" encoding="UTF-8"?>
<project>
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.tvh.paas</groupId>
    <artifactId>dependency-check-db-sync</artifactId>
    <version>1</version>
    <build>
        <plugins>
            <plugin>
                <groupId>org.owasp</groupId>
                <artifactId>dependency-check-maven</artifactId>
                <version>7.2.1</version>
                <configuration>
                    <formats>HTML,XML</formats>
                    <databaseDriverName>com.mysql.cj.jdbc.Driver</databaseDriverName>
                    <connectionString>jdbc:mysql://dependency-check-db.tools.parts.tvh.com:3306/dependencycheck?useSSL=false&amp;allowPublicKeyRetrieval=true</connectionString>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>purge</goal>
                        </goals>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>mysql</groupId>
                        <artifactId>mysql-connector-java</artifactId>
                        <version>8.0.24</version>
                    </dependency>
                    <dependency>
                        <groupId>com.google.cloud.sql</groupId>
                        <artifactId>mysql-socket-factory</artifactId>
                        <version>1.5.0</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>
</project>
```

**Comment by jeremylong** [comment]
We do not provide update scripts for mysql. Easiest option would be to recreate the database.
