### ISSUE TITLE
gradle plugin doesn't link to github

### ISSUE THREAD

**Issue by johnscancella** [dependency-check/DependencyCheck#683]
when you visit https://plugins.gradle.org/plugin/org.owasp.dependencycheck
it lists the github link as git@github.com:jeremylong/dependency-check-gradle.git which is incorrect and causes a error when you try to click on it.

**Comment by jeremylong** [comment]
See https://github.com/jeremylong/dependency-check-gradle/issues/36. fix will be included in the next release.
