### ISSUE TITLE
--nvdDatafeed parameter is not recognized

### ISSUE THREAD

**Issue by dgroh** [dependency-check/DependencyCheck#6833]
**Describe the bug**
As described [here](https://github.com/jeremylong/DependencyCheck/issues/6641#issuecomment-2220940988), the arg `--nvdDatafeed` is not working. I get the following error: 

> Unrecognized option: --nvdDatafeed file:///builds/platform/service-api/cache

**Version of dependency-check used**
The problem occurs using version  v10.0.2 of the cli.

**Log file**
> dependency-check.sh --scan ./target/service-api-1.95.0-feature.11047.jar --nvdApiKey [MASKED] --failOnCVSS=7 --disableAssembly --out target/owasp-dependency-check -f HTML -f XML -f JSON --nvdDatafeed "file:///builds/platform/service-api/cache"
Unrecognized option: --nvdDatafeed "file:///builds/banking-platform/service-mfa-api/cache"
usage: Dependency-Check Core [--advancedHelp] [--enableExperimental]
       [--exclude <pattern>] [-f <format>] [--failOnCVSS <score>] [-h]
       [--junitFailOnCVSS <score>] [-l <file>] [-n] [--nvdApiKey <apiKey>]
       [-o <path>] [--prettyPrint] [--project <name>] [-s <path>]
       [--suppression <file>] [-v]

**To Reproduce**
1. Create a local cache using vulnz
2. Scan the depencies with dependency-check cli using the `--nvdDatafeed` argument using `file://` protocol

**Expected behavior**
dependency-check cli should load data from the cache URL provided in `--nvdDatafeed`.

**Additional context**

**Comment by jeremylong** [comment]
try `--nvdDatafeed=file:///builds/platform/service-api/cache`

**Comment by dgroh** [comment]
Thanks @jeremylong this did the. Still, I realized one thing - wrapping the URL in quotes would lead to an error of:

> org.owasp.dependencycheck.data.update.NvdApiDataSource.getRemoteCacheProperties(NvdApiDataSource.java:601)
...
Caused by: java.net.URISyntaxException: Illegal character in scheme name at index 0: "file:///builds/platform/service-api/cache"/cache.properties

I don't know if this is disired behaviour, but from the usability it does not feel right.

I've also tried to clone the repo to contribute, but I was not able to build. I've followed the exact same steps from the README.

Here is the output:

```sh
[ERROR] Tests run: 484, Failures: 0, Errors: 2, Skipped: 11
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Dependency-Check 10.0.3-SNAPSHOT:
[INFO]
[INFO] Dependency-Check ................................... SUCCESS [  1.272 s]
[INFO] Dependency-Check Utils ............................. SUCCESS [  7.358 s]
[INFO] Dependency-Check Core .............................. FAILURE [ 19.412 s]
[INFO] Dependency-Check Command Line ...................... SKIPPED
[INFO] Dependency-Check Ant Task .......................... SKIPPED
[INFO] Dependency-Check Maven Plugin ...................... SKIPPED
[INFO] Dependency-Check Plugin Archetype .................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  28.363 s
[INFO] Finished at: 2024-07-11T14:33:19+02:00
[INFO] ------------------------------------------------------------------------
```

I'll close this issue and would appreciate a feedback for above mentioned points.

Thanks
