### ISSUE TITLE
[FP]: groupId and artifactId are ignored

### ISSUE THREAD

**Issue by slawekjaranowski** [dependency-check/DependencyCheck#6839]
### Package URl

pkg:maven/commons-discovery/commons-discovery@0.2

### CPE

cpe:2.3:a:spirit-project:spirit:0.2:*:*:*:*:*:*:*

### ODC Integration

{"label"=>"Maven Plugin"}

### ODC Version

10.0.2

### Description

Looks like only version is used, but groupId and artifactId are ignored.
It can be more general problem

**Comment by aikebah** [comment]
approved

@slawekjaranowski It's not about ignoring groupId/artifactId, It's about no CVE being registered against commons-discovery yet and therefor an improper CPE match is found to be 'best matching CPE' for the combination of evidences gathered from the dependency and the CPEs found in the NVD CVE data. If there had been a CVE registered against commons-discovery that would've resulted in a much better match.
