### ISSUE TITLE
Json, Html Exports are to large

### ISSUE THREAD

**Issue by TomasJurnicky** [dependency-check/DependencyCheck#6847]
Hello

**Is your feature request related to a problem? Please describe.**
We have a problem with exports. Our Android project has more than 150 modules. It is a really large app, with around 800 screens. We implemented a dependency check and ran dependencyCheckAggregate under the app module, which should scan all modules. It is working, but the JSON export is more than 500MB, and the HTML export is also more than 500MB. We cannot send this export to analytics tools like SonarQube because it is too large. We checked the JSON report and found many unnecessary parameters, such as "includedBy", "versionEvidence", "evidenceCollected", "projectReferences", and "productEvidence".

**Describe the solution you'd like**
Could you please implement some optimisations for the export ?

version [9.0.10](org.owasp:dependency-check-gradle:9.0.10)

**Comment by jeremylong** [comment]
These fields may be unnecessary to you - but these values are actually used by some (including me). You can always create your own report template and use it instead of the default templates provided.

**Comment by TomasJurnicky** [comment]
Hello Jeremy,

Thank you for the fast response. I checked the documentation, but I did not find how to create my own template or how to optimise the export. Could you please send an example?

**Comment by jeremylong** [comment]
Note that ODC 9.0.10 is no longer supported. See https://github.com/jeremylong/DependencyCheck/blob/main/SECURITY.md

Regarding the templates - just copy one of the [core templates](https://github.com/jeremylong/DependencyCheck/tree/main/core/src/main/resources/templates), update it, and instead of a `--format JSON` just do a `--format path/to/your/template`.

**Comment by jeremylong** [comment]
And sorry - the template language is velocity as opposed to something modern.

**Comment by ahmadalfy** [comment]
@jeremylong would you be open to accept a PR that update the HTML template to use less JavaScript and achieve the same results?

**Comment by jeremylong** [comment]
Sure - we are always open for PRs.
