### ISSUE TITLE
Gradle plugin doesn't work with Gradle 3.4+

### ISSUE THREAD

**Issue by RaySinnema** [dependency-check/DependencyCheck#685]
```
* What went wrong:
Execution failed for task ':dependencyCheck'.
> Resolving configuration 'apiElements' directly is not allowed
```
This happens because [there are now default configurations that are not resolvable](https://docs.gradle.org/3.4/release-notes.html#configurations-can-be-unresolvable), so the code needs to check before resolving a configuration.

**Comment by jeremylong** [comment]
1.4.5.1 was just published which resolves this issue.  See https://github.com/jeremylong/dependency-check-gradle/issues/31
