### ISSUE TITLE
Can I use dependency-check for cache or vulnz?

### ISSUE THREAD

**Issue by dgroh** [dependency-check/DependencyCheck#6857]
We observed that we can use `dependency-check-cli` for caching by utilizing the `--data` parameter. The method we employed involves executing a scan and then saving the vulnerability data in a Docker image. This cached image can be used for faster subsequent scans.

We are also aware of the `vulnz` tool, and we have tested it in conjunction with `dependency-check-cli` using the `--nvdDatafeed` argument.

Could you clarify the main differences between these two approaches? Which approach is recommended for optimal performance and reliability?

**Comment by dgroh** [comment]
Could you also please explain this statement about the `--data` argument for the `dependency-check-cli`?

_The location of the data directory used to store persistent data. **This option should generally not be set.**_

Why should this option generally not be set?

**Comment by jeremylong** [comment]
Regarding the "This option should generally not be set." - this was an old recommendation that should have been removed. See https://github.com/jeremylong/DependencyCheck/pull/6860

Regarding which option is best - keeping a docker image up to date or using the vulnz CLI to create a cache is more of a personal choice. In some ways, just keeping the docker image up to date might work better as other things in the data directory will be cached between executions.
