### ISSUE TITLE
Produce output file even if no dependency is found

### ISSUE THREAD

**Issue by v6ak** [dependency-check/DependencyCheck#686]
I'd like to scan all projects, even those that don't have any dependency (yet). But when I scan some Maven project with no dependency, it does not produce any output XML file, which causes failure when processing it further.

**Comment by jeremylong** [comment]
To be clear, what you would like is an empty report to be generated?  That seems entirely reasonable and I'm a little surprised it doesn't do that already... I will take a closer look at the code and try to resolve this in the near future.

**Comment by v6ak** [comment]
Yes, this is exactly what I'd like to get. The report would ideally include metadata about freshness of the database, like other reports do, but no dependencies.
