### ISSUE TITLE
Log4Net vulnerability

### ISSUE THREAD

**Issue by crowster** [dependency-check/DependencyCheck#6861]
I just run the last dependency check version (dependency-check-10.0.2) and I have a highest error for log4net , the version is 2.0.15
I already updated it to 2.0.17 but the same issue. 

There are no CVE associated and no comments about how to solve it. Could it be considered a false positive?

**Comment by aikebah** [comment]
Try reading up on http://jeremylong.github.io/DependencyCheck/general/thereport.html to get some clues on how to read the report.

The information you provide is far from sufficient to judge what's happening on your side.
