### ISSUE TITLE
Using nvdDatafeedUrl fails with Unexpected close marker '}': expected ']' error

### ISSUE THREAD

**Issue by usteinha** [dependency-check/DependencyCheck#6876]
Hi, I started using vulnz Docker image with latest version 6.1.7 to cache NVD data for my Java projects.
Projects are built using Maven, so I use the `dependency-check-maven` plugin 10.0.3, configured with `nvdDatafeedUrl` to use the cached NVD data.
Unfortunately it happens, that the Maven build fails due to "Unexpected close marker '}': expected ']'" after downloading all NVD data from the cache.

Here is the log from the Maven build:
> [INFO] Download Started for NVD Cache - http://xx.xx.xx.xx/nvdcve-2024.json.gz
> [ERROR] java.util.concurrent.ExecutionException: com.fasterxml.jackson.databind.JsonMappingException: Unexpected close marker '}': expected ']' (for Array starting at [Source: REDACTED (StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION disabled); line: 1, column: 8154126])
> at [Source: REDACTED (StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION disabled); line: 1, column: 8154155] (through reference chain: io.github.jeremylong.openvulnerability.client.nvd.DefCveItem["cve"]->io.github.jeremylong.openvulnerability.client.nvd.CveItem["references"]->java.util.ArrayList[20]->io.github.jeremylong.openvulnerability.client.nvd.Reference["tags"]->java.util.ArrayList[2])
> org.owasp.dependencycheck.data.update.exception.UpdateException: java.util.concurrent.ExecutionException: com.fasterxml.jackson.databind.JsonMappingException: Unexpected close marker '}': expected ']' (for Array starting at [Source: REDACTED (StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION disabled); line: 1, column: 8154126])
> at [Source: REDACTED (StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION disabled); line: 1, column: 8154155] (through reference chain: io.github.jeremylong.openvulnerability.client.nvd.DefCveItem["cve"]->io.github.jeremylong.openvulnerability.client.nvd.CveItem["references"]->java.util.ArrayList[20]->io.github.jeremylong.openvulnerability.client.nvd.Reference["tags"]->java.util.ArrayList[2])
> at org.owasp.dependencycheck.data.update.NvdApiDataSource.processFuture (NvdApiDataSource.java:264)
> at org.owasp.dependencycheck.data.update.NvdApiDataSource.processDatafeed (NvdApiDataSource.java:174)
> at org.owasp.dependencycheck.data.update.NvdApiDataSource.update (NvdApiDataSource.java:114)
> at org.owasp.dependencycheck.Engine.doUpdates (Engine.java:906)
> at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase (Engine.java:711)
> at org.owasp.dependencycheck.Engine.analyzeDependencies (Engine.java:637)
> at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.runCheck (BaseDependencyCheckMojo.java:1967)
> at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.execute (BaseDependencyCheckMojo.java:1150)
> at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
> at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
> at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
> at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
> at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
> at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
> at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
> at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
> at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
> at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
> at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
> at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
> at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
> at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
> at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
> at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
> at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke (Method.java:566)
> at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
> at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
> at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
> at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
> Caused by: java.util.concurrent.ExecutionException: com.fasterxml.jackson.databind.JsonMappingException: Unexpected close marker '}': expected ']' (for Array starting at [Source: REDACTED (StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION disabled); line: 1, column: 8154126])
> at [Source: REDACTED (StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION disabled); line: 1, column: 8154155] (through reference chain: io.github.jeremylong.openvulnerability.client.nvd.DefCveItem["cve"]->io.github.jeremylong.openvulnerability.client.nvd.CveItem["references"]->java.util.ArrayList[20]->io.github.jeremylong.openvulnerability.client.nvd.Reference["tags"]->java.util.ArrayList[2])
> at java.util.concurrent.FutureTask.report (FutureTask.java:122)
> at java.util.concurrent.FutureTask.get (FutureTask.java:191)
> at org.owasp.dependencycheck.data.update.NvdApiDataSource.processFuture (NvdApiDataSource.java:257)
> at org.owasp.dependencycheck.data.update.NvdApiDataSource.processDatafeed (NvdApiDataSource.java:174)
> at org.owasp.dependencycheck.data.update.NvdApiDataSource.update (NvdApiDataSource.java:114)
> at org.owasp.dependencycheck.Engine.doUpdates (Engine.java:906)
> at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase (Engine.java:711)
> at org.owasp.dependencycheck.Engine.analyzeDependencies (Engine.java:637)
> at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.runCheck (BaseDependencyCheckMojo.java:1967)
> at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.execute (BaseDependencyCheckMojo.java:1150)
> at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
> at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
> at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
> at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
> at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
> at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
> at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
> at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
> at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
> at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
> at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
> at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
> at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
> at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
> at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
> at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
> at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke (Method.java:566)
> at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
> at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
> at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
> at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
> Caused by: com.fasterxml.jackson.databind.JsonMappingException: Unexpected close marker '}': expected ']' (for Array starting at [Source: REDACTED (StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION disabled); line: 1, column: 8154126])
> at [Source: REDACTED (StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION disabled); line: 1, column: 8154155] (through reference chain: io.github.jeremylong.openvulnerability.client.nvd.DefCveItem["cve"]->io.github.jeremylong.openvulnerability.client.nvd.CveItem["references"]->java.util.ArrayList[20]->io.github.jeremylong.openvulnerability.client.nvd.Reference["tags"]->java.util.ArrayList[2])
> at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath (JsonMappingException.java:402)
> at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath (JsonMappingException.java:373)
> at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize (StringCollectionDeserializer.java:223)
> at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize (StringCollectionDeserializer.java:184)
> at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize (StringCollectionDeserializer.java:27)
> at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet (FieldProperty.java:138)
> at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize (BeanDeserializer.java:310)
> at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize (BeanDeserializer.java:177)
> at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray (CollectionDeserializer.java:361)
> at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize (CollectionDeserializer.java:246)
> at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize (CollectionDeserializer.java:30)
> at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet (FieldProperty.java:138)
> at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize (BeanDeserializer.java:310)
> at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize (BeanDeserializer.java:177)
> at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet (FieldProperty.java:138)
> at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize (BeanDeserializer.java:310)
> at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize (BeanDeserializer.java:177)
> at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue (DefaultDeserializationContext.java:342)
> at com.fasterxml.jackson.databind.ObjectMapper._readValue (ObjectMapper.java:4881)
> at com.fasterxml.jackson.databind.ObjectMapper.readValue (ObjectMapper.java:3035)
> at org.owasp.dependencycheck.data.update.nvd.api.CveApiJson20CveItemSource.readItem (CveApiJson20CveItemSource.java:75)
> at org.owasp.dependencycheck.data.update.nvd.api.CveApiJson20CveItemSource.next (CveApiJson20CveItemSource.java:69)
> at org.owasp.dependencycheck.data.update.nvd.api.NvdApiProcessor.updateCveDb (NvdApiProcessor.java:117)
> at org.owasp.dependencycheck.data.update.nvd.api.NvdApiProcessor.call (NvdApiProcessor.java:102)
> at org.owasp.dependencycheck.data.update.nvd.api.NvdApiProcessor.call (NvdApiProcessor.java:40)
> at java.util.concurrent.FutureTask.run (FutureTask.java:264)
> at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
> at java.lang.Thread.run (Thread.java:829)
> Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected close marker '}': expected ']' (for Array starting at [Source: REDACTED (StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION disabled); line: 1, column: 8154126])
> at [Source: REDACTED (StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION disabled); line: 1, column: 8154155]
> at com.fasterxml.jackson.core.JsonParser._constructReadException (JsonParser.java:2643)
> at com.fasterxml.jackson.core.base.ParserBase._reportMismatchedEndMarker (ParserBase.java:1386)
> at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._closeObjectScope (UTF8StreamJsonParser.java:3897)
> at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken (UTF8StreamJsonParser.java:731)
> at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextTextValue (UTF8StreamJsonParser.java:1304)
> at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize (StringCollectionDeserializer.java:203)
> at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize (StringCollectionDeserializer.java:184)
> at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize (StringCollectionDeserializer.java:27)
> at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet (FieldProperty.java:138)
> at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize (BeanDeserializer.java:310)
> at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize (BeanDeserializer.java:177)
> at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray (CollectionDeserializer.java:361)
> at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize (CollectionDeserializer.java:246)
> at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize (CollectionDeserializer.java:30)
> at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet (FieldProperty.java:138)
> at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize (BeanDeserializer.java:310)
> at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize (BeanDeserializer.java:177)
> at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet (FieldProperty.java:138)
> at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize (BeanDeserializer.java:310)
> at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize (BeanDeserializer.java:177)
> at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue (DefaultDeserializationContext.java:342)
> at com.fasterxml.jackson.databind.ObjectMapper._readValue (ObjectMapper.java:4881)
> at com.fasterxml.jackson.databind.ObjectMapper.readValue (ObjectMapper.java:3035)
> at org.owasp.dependencycheck.data.update.nvd.api.CveApiJson20CveItemSource.readItem (CveApiJson20CveItemSource.java:75)
> at org.owasp.dependencycheck.data.update.nvd.api.CveApiJson20CveItemSource.next (CveApiJson20CveItemSource.java:69)
> at org.owasp.dependencycheck.data.update.nvd.api.NvdApiProcessor.updateCveDb (NvdApiProcessor.java:117)
> at org.owasp.dependencycheck.data.update.nvd.api.NvdApiProcessor.call (NvdApiProcessor.java:102)
> at org.owasp.dependencycheck.data.update.nvd.api.NvdApiProcessor.call (NvdApiProcessor.java:40)
> at java.util.concurrent.FutureTask.run (FutureTask.java:264)
> at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
> at java.lang.Thread.run (Thread.java:829)

**Comment by jeremylong** [comment]
The issue is not with ODC. See https://github.com/jeremylong/Open-Vulnerability-Project/issues/203

best option - purge the cache and start over.
