### ISSUE TITLE
Trend Chart

### ISSUE THREAD

**Issue by jlanzarotta** [dependency-check/DependencyCheck#6878]
Hello,

I have the dependencycheck plugin configured and running under Jenkins; however, the Trend Chart is never displayed.  All I get is the "Latest Dependency-Check".  Any idea why this is happening?

Thanks.

**Comment by aikebah** [comment]
The Jenkins plugin is managed outside of this repository. For Jenkins plugin issues your first place to look is its plugin documentation and its support links (https://plugins.jenkins.io/dependency-check-jenkins-plugin/)

**Comment by jlanzarotta** [comment]
> The Jenkins plugin is managed outside of this repository. For Jenkins plugin issues your first place to look is its plugin documentation and its support links (https://plugins.jenkins.io/dependency-check-jenkins-plugin/)

Thanks, I will give that link a look.
