### ISSUE TITLE
AssemblyAnalyzer, which and Solaris

### ISSUE THREAD

**Issue by rrialq** [dependency-check/DependencyCheck#688]
In Solaris the ```which``` command is essentially the same as the first versions, so the exit status is allways 0. 

When **AssemblyAnalyzer** execs ```which mono``` in Solaris and **mono** is not installed, the exit status is 0, so **AssemblyAnalyzer** thinks mono is installed.

To solve this, change the ```which``` with ```type```, in this context the exit status will work as expected in Solaris too.

<table>
    <tr>
        <th rowspan="2">Command</th>
        <th colspan="2">Linux exit status</th>
        <th colspan="2">Solaris exit status</th>
    </tr>
    <tr>
        <th>When found</th>
        <th>When not found</th>
        <th>When found</th>
        <th>When not found</th>
    </tr>
    <tr>
        <td>which mono</td>
        <td>0</td>
        <td>1</td>
        <td>0</td>
        <td>0</td>
    </tr>
    <tr>
        <td>type mono</td>
        <td>0</td>
        <td>1</td>
        <td>0</td>
        <td>1</td>
    </tr>
</table>

**Comment by jeremylong** [comment]
Thanks for the information; I will do some testing and hopefully this small change will make it into the next release.
