### ISSUE TITLE
Make configurable CVE URL

### ISSUE THREAD

**Issue by hgomez** [dependency-check/DependencyCheck#69]
CVEs URL should be configurable in Maven and Ant projects like in Jenkins Plugin

**Comment by hgomez** [comment]
Done for Maven, closing this one

**Comment by jeremylong** [comment]
This still needs to be added to the Ant task. After I commit the maven PR I'll do some copy paste into the task.

**Comment by hgomez** [comment]
Yep. I'm more focused on Maven since we're using it and it's more efficient to grab dependencies in most case.

**Comment by jeremylong** [comment]
This has been pushed to 1.1.2-SNAPSHOT (this was a partial duplicate of issue #71).
