### ISSUE TITLE
Support maven plugin parallel executions

### ISSUE THREAD

**Issue by mattnelson** [dependency-check/DependencyCheck#690]
When using the dependency check maven plugin in a parallel build `mvn dependency-check:check -T 2` the following warning occurs. I haven't noticed any issues running the plugin in parallel mode, but that isn't a certification that it is in fact thread safe.

```
[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but project      *
[WARNING] * contains the following plugin(s) that have goals not marked   *
[WARNING] * as @threadSafe to support parallel building.                  *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against maven-core                              *
[WARNING] *****************************************************************
[WARNING] The following goals are not marked @threadSafe in alva-example-war:
[WARNING] org.owasp:dependency-check-maven:1.4.5:check
[WARNING] *****************************************************************
```

**Comment by jeremylong** [comment]
After much review and work, I finally realized it will take a lot of rework to make the Maven plugin thread safe. Some of this work can be seen in PR #705. I plan on merging #705 as it does resolve a few other issues I identified. However, at this time dependency-check should not be run using a multi-threaded build.  I will leave these ticket open to continue to track the work to make ODC threadsafe.
