### ISSUE TITLE
In my project i have custom and missing dependencies, that means i am unable to build the project. Can i somehow run maven dependency check plugin and obtain info only about the working dependencies

### ISSUE THREAD

**Issue by manoelacmn** [dependency-check/DependencyCheck#6904]
For example let's say  this is a fragment of my pom file:
```
(...)
<dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.8.9</version> <!-- check latest version for GSON -->
        </dependency>
           <dependency>
            <groupId>com.googffele.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.8.9</version> 
        </dependency>
  (...)
```

As it's possible to see the last dependency is invalid and it can not be checked, the example above is just a example of a missing depedency. 

If i run "mvn org.owasp:dependency-check-maven:check -DskipTests=true", it resuts in error and don't get the scan.

My goal is to get the result only for valid ones

**Comment by jeremylong** [comment]
You might be able to configure `failOnError` to false. As this would be a standard maven build error - I'm not 100% sure if that would work.

See https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html

**Comment by aikebah** [comment]
The only solution is to comment out the invalid ones. Maven will simply refuse to run anything when one of your dependencies is not resolvable.
