### ISSUE TITLE
Is there any way to specify Python version used in environment?

### ISSUE THREAD

**Issue by tymons** [dependency-check/DependencyCheck#6908]
Currently, I am running the dependency-check on the `requirements.txt` file and the Python virtual environment folder.

Is there a way to specify the Python version being used so that I do not receive notifications about CVEs targeting Python versions lower than the one in use?

I appreciate your help.

**Comment by OrangeDog** [comment]
CPEs do not encode the target language/platform version, and dependency check's CPE matcher does not look at the platform (if specified) in the first place.

Basically, the CVE ecosystem is not set up to support what you want.
