### ISSUE TITLE
Also exclude `jcl-over-slf4j` from the `org.sonatype.ossindex:ossindex-service-client` dependency

### ISSUE THREAD

**Issue by Vampire** [dependency-check/DependencyCheck#6911]
`org.sonatype.ossindex:ossindex-service-client` depends on `org.apache.httpcomponents:httpclient` but excludes `commons-logging:commons-logging` and instead badly depends on `jcl-over-slf4j` explicitly while not even using the `commons-logging` API itself.

This easily causes problems (most often silently unless you have some protection) if any other dependency (like other dependencies of this project) depend on `commons-logging`: sonatype/ossindex-public#51.

As you explicitly exclude `org.apache.httpcomponents:httpclient` from your `org.sonatype.ossindex:ossindex-service-client` dependency, I suggest you also exclude the `jcl-over-slf4j` dependency as with that exclude it is totally pointless anyway, at least until that upstream bug got fixed and you depend on a newer version with that fix.

**Comment by Vampire** [comment]
Great, thanks. :-)
Don't want to jostle, just to know, is there a timeline for the 10.0.4 release that includes this? :-)

**Comment by jeremylong** [comment]
I'll likely have time to do my final rounds of testing and publish 10.0.4 Saturday morning. 11.0 will likely follow shortly thereafter.
