### ISSUE TITLE
ODC does not report enough details for some exceptions

### ISSUE THREAD

**Issue by v6ak** [dependency-check/DependencyCheck#692]
Exception message is sometimes pretty non-descriptive. For example, ConcurrentModificationException or NullPointerException have often null message. Without knowing the exception type, and stacktrace the messages are rather useless. Printing just exception message might be OK for some specific cases, but not for the generic one.

However, logging just error message without useful details is exactly what dependency-check-cli/src/main/java/org/owasp/dependencycheck/App.java does when handling ExceptionCollection, i.e., a collection of various exception types:

                for (Throwable e : ex.getExceptions()) {
                    LOGGER.error(e.getMessage());
                }

This should be written in better way:

                for (Throwable e : ex.getExceptions()) {
                    LOGGER.error("Error during scan", e);
                }

There might be multiple similar places. This is the one I have found.

**Comment by jeremylong** [comment]
Thank you for pointing this out. In some cases we specifically only write the error message out and then follow it with a debug logging of the exception. This results in the console output having the error message and then one can view the log file for more details.  I will look into enhancing the specific line item you call out - I'm always trying to make the error reporting more useful.
