### ISSUE TITLE
Running SonarQube on localhost, DependencyCheck cannot find HTML report

### ISSUE THREAD

**Issue by maglez** [dependency-check/DependencyCheck#6923]
Hello,

I'm running my SonarQube locally. I installed the DependencyCheck plugging and I manage to generate the json and html reports which I can manually open but SonarQube cannot find. On SonarQube, it shows a message that says...

No HTML-Report found. Please check property sonar.dependencyCheck.htmlReportPath

I added the below to my sonar-project.properties file...

sonar.dependencyCheck.htmlReportPath=dependency-check-report.html

I tried a few combinations such as putting the full path to the file as in $HOME/mypath/dependency-check-report.html and ./dependency-check-report.html but always same result, the plugin seems like it can't find the report.

Any suggestion on how to write that path when running SonarQube locally?

Thank you.

**Comment by aikebah** [comment]
This is more a topic for the Sonarqube community, but as I use it myself as well I might still be able to help you towards the solution. (The sonarqube plugin to load DependencyCheck reports has its own github project at https://github.com/dependency-check/dependency-check-sonar-plugin)

The location where your sonarqube server resides is irrelevant. The property needs to have the right value for the sonarqube scanner that you run.

You're talking about the plugin not finding it regardless of what you enter in sonar-project.properties.
How do you run sonarqube scanner?

**Comment by maglez** [comment]
I got it working. While I was preparing to answer your question, I noticed that my scan was failing. Well, the scan was showing on the command line as 'INFO  EXECUTION SUCCESS' but on SonarQube, on the Background Tasks, it showed as failed with an error as 'java.lang.OutOfMemoryError: Java heap space'.

I realise that running out of memory was because I was creating the Dependency Check report on the root of the project and SonarQube was analysing that file too but it was too large to cope with it.

I moved the report files to a sud-directory and added it to the exclude list of the scanner. After doing this, it all worked fine and now I get SonarQube to open the report.

Thank you @aikebah for coming back to me willing to help, that is great :-)

A follow up question though... On my sonar-project.properties, I had to set the absolute path to my reports. Is there a way to use some env variable?

This is my sonar-project.properties content...
```
sonar.projectKey=myproject

# Remove autogenerated files and do not remove testing files
sonar.exclusions=**/.dependecycheck/*

# Include code coverage analysis
sonar.go.coverage.reportPaths=coverage.out

# Vulnerability Checks
sonar.dependencyCheck.jsonReportPath=/home/mycomputer/path/to/project/myproject/.dependecycheck/dependency-check-report.json
sonar.dependencyCheck.htmlReportPath=/home/mycomputer/path/to/project/myproject/.dependecycheck/dependency-check-report.html

sonar.dependencyCheck.severity.high=7.0
sonar.dependencyCheck.severity.medium=4.0
sonar.dependencyCheck.severity.low=0.0

sonar.dependencyCheck.securityHotspot=true
```

Is there a way to substitute /home/mycomputer/path/to/project/ by a variable? I have tried using the $HOME variable to shorten that path but it did not work.

Thanks.

**Comment by aikebah** [comment]
I have mainly experience with the maven-plugin as the sonar-scanner in use, where the configuration goes into the pom.xml and can use maven property configuration parameters.

Based on the plugin's default (targeting Jenkins) of `${WORKSPACE}/dependency-check-report.html` can you try what happens when you replace `$HOME` by `${HOME}`? Not sure it would work, but maybe env variable references in sonar-project.properties  need to be braces-delimited to be properly replaced.

**Comment by aikebah** [comment]
Looks like indeed the `${ }` demarcation is required as per https://github.com/SonarSource/sonar-scanner-cli/blob/a3c341f0b95704ed1b1d17e2273fb0458a9c5db6/src/main/java/org/sonarsource/scanner/cli/PropertyResolver.java#L30

**Comment by aikebah** [comment]
Gut feel browsing further in that codebase is that you need to use `${env.HOME}` as the placeholder for your env-variable that points to the user-home folder.

**Comment by maglez** [comment]
Yeap, ${env.HOME} worked great!

Thanks a lot for your help, this will make things so much easier.
