### ISSUE TITLE
 [INFO] Checking for updates [WARN] An NVD API Key was not provided - it is highly recommended to use an NVD API key as the update can take a VERY long time without an API Key [ERROR] Error updating the NVD Data; the NVD returned a 403 or 404 error

### ISSUE THREAD

**Issue by shekharclover** [dependency-check/DependencyCheck#6924]

**Comment by shekharclover** [comment]
![image](https://github.com/user-attachments/assets/69345d6d-c732-42e2-9121-00c6f4a51cdb)

**Comment by aikebah** [comment]
Check your version #6817

**Comment by aikebah** [comment]
also note that if this is in CI not using an API key is extremely likely to exceed the limits if multiple jobs in parallel are running an update in parallel. In CI environments you should configure some shared persistent storage to store and reuse the data.
