### ISSUE TITLE
Support to CVSSv3.0

### ISSUE THREAD

**Issue by elrond30** [dependency-check/DependencyCheck#693]
Hello,
I would like to know, if Dependency Check will supporet CVSSv3.0 score. NVD have the two version scores in his web, and can be interesting that Demedency Check inform about CVSSv3.0 score. There is any plan?

Thanks in advance

**Comment by jeremylong** [comment]
As soon as the NVD CVE data feed incorporates CVSSv3.0 we will begin working on this. You can see the current data feeds here: https://nvd.nist.gov/vuln/data-feeds

**Comment by elrond30** [comment]
Thanks for the information.

**Comment by jeremylong** [comment]
Closing this enhancement request in favor of #707 which provides additional information.
