### ISSUE TITLE
 The certificate for nvd.nist.gov expired on 01/09/2024.

### ISSUE THREAD

**Issue by glesys-andreas** [dependency-check/DependencyCheck#6942]
The certificate for nvd.nist.gov has expired on 01/09/2024.
![image](https://github.com/user-attachments/assets/82e41d42-3fa4-4e08-9ce9-7d1c16380fdb)

**Comment by pabmartine** [comment]
Why has this issue been closed? The certificates are still expired.

**Comment by jeremylong** [comment]
Because this project doesn't have any control over the nvd?

**Comment by pabmartine** [comment]
👍



Un saludo
Pablo Martín
