### ISSUE TITLE
Export reports from Sonarqube

### ISSUE THREAD

**Issue by honoref** [dependency-check/DependencyCheck#6947]
Is-it possible to export html report (or json report too) from Sonarqube IHM ?
If not, does it be possible to add a link/button for than ? 
It should be more simple for users  than use the devtools of browser ;-)

Thank's
François

**Comment by aikebah** [comment]
@honoref Sonarqube plugin is another GH project - https://github.com/dependency-check/dependency-check-sonar-plugin

But why not have CI publish the report in some other tool than Sonarqube if you want people to download it.

After all the reports are simply build outputs (which the SonarQube plugin happens to parse and publish as SonarQube issues and an in-sonarqube rendering of the HTML file) so you could treat them as a build artifacts in your CI.
