### ISSUE TITLE
[Question] What's the difference between this tool and owasp-dep-scan

### ISSUE THREAD

**Issue by WestFarmer** [dependency-check/DependencyCheck#6948]
there was another tool: [owasp-dep-scan](https://github.com/owasp-dep-scan/dep-scan)

this caused me confusion, can someone clarify this.

**Comment by aikebah** [comment]
The two are unrelated, independent projects that have both listed their project under the OWASP umbrella. There might be more similar tools in the full list of projects that have [registered with OWASP](https://owasp.org/projects/).

owasp-dep-scan is in their incubator projects list, defined by them as

>Incubator Projects: OWASP Incubator projects represent the experimental playground where projects are still being fleshed out, ideas are still being proven, and development is still underway.
