### ISSUE TITLE
autoupdate Property is ignored in Property file in depdency-check CLI

### ISSUE THREAD

**Issue by catango** [dependency-check/DependencyCheck#696]
Defect description
============
Setting
"autoupdate = false" 
in the property file, assigned by the -P argument of the CLI is ignored. Property is always overwritten with "true", when no cli Argument "noupdate" is supplied.

Same behaviour might apply to other boolean properties in dependency-check CLI

Expected behaviour
============
Boolean properties should be applied and not overwritten by default value

**Comment by jeremylong** [comment]
Thank you for the report. I'm pretty sure I know exactly why you are seeing this (incorrect) behavior. I will try and resolve this for the next release.
