### ISSUE TITLE
Support for Php and Javascript dependencies and Gitlab integration

### ISSUE THREAD

**Issue by nhajiyani** [dependency-check/DependencyCheck#697]
Seems like it should but wanted to confirm, if this dependency checker supports to identify Php and Javascript dependencies?

Additionally any advice on which is the shortest path to integrating it with a Gitlab repository?

Thanks.

**Comment by jeremylong** [comment]
For PHP - there is an experimental analyzer if you use PHP Composer. See the [documentation here](http://jeremylong.github.io/DependencyCheck/analyzers/index.html).

For JavaScript, there is currently no support. For Node.js I recommend looking at the Node Security Project and for client side JS take a look at Retire.js (which also does node.js). Links to these can be found on the [related work](http://jeremylong.github.io/DependencyCheck/related.html) page.

As to GitLab integration - dependency-check works best as a build plugin for Maven or Gradle. I would recommend getting it added to the build.
