### ISSUE TITLE
OSS Index Analyzer Integration with PostgreSQL

### ISSUE THREAD

**Issue by juanmanuelromeraferrio** [dependency-check/DependencyCheck#6971]
Hi,

I’m looking to start using the **OSS Index Analyzer** and would like to better understand how it works. In our current architecture, we are using a PostgreSQL database to store the vulnerability data from Dependency Check, which is obtained via the NVD REST API.

We typically run our scans with the `--noupdate` flag to avoid updating the database, relying on the local data stored in PostgreSQL for generating reports.

My question is related to how the OSS Index Analyzer works in this setup. From what I understand, the vulnerability information provided by OSS Index is not stored in our database.

Is this correct? Is there any way to store OSS Index data in our PostgreSQL database to avoid making an API request to OSS Index for each scan?

Thank you!

**Comment by aikebah** [comment]
See #3605 mirroring OSSINDEX data would be a violation of their terms of service.

**Comment by aikebah** [comment]
The OSSIndexAnalyzer uses OSSINDEX's library that has built-in caching functionality and stores the caches within the DependencyCheck data folder.

So as long as you ensure that the dependencycheck data folder is on persistent storage shared across your builds it will typically re-use cached data for the same version of a dependency use by another project/build.
