### ISSUE TITLE
Jenkin with PostgreSQL

### ISSUE THREAD

**Issue by ammaraziz493** [dependency-check/DependencyCheck#6972]
Is there any way to store a new user data of jenkins directly into the PostgreSQL.
THANKS.

**Comment by jeremylong** [comment]
I do not understand your question. Do you mean add a new user `jenkins` to the PostgreSQL DB?

**Comment by ammaraziz493** [comment]
Yes , new user data store in DB.

**Comment by ammaraziz493** [comment]
> I do not understand your question. Do you mean add a new user `jenkins` to the PostgreSQL DB?

Yes , new user data store in DB.

**Comment by jeremylong** [comment]
not sure why you can't? What is the purpose of the "new user data store"? Why is this a question for dependency-check?

**Comment by ammaraziz493** [comment]
> not sure why you can't? What is the purpose of the "new user data store"? Why is this a question for dependency-check?

Sorry, I am new at GitHub so i think i can ask any question in issues section. Again Sorry and thanks for my help.

**Comment by jeremylong** [comment]
more then happy to help - I just don't understand what you are trying to do.

**Comment by jeremylong** [comment]
If you want to create a new user in PostgreSQL - it has nothing to do with dependency-check; see https://www.postgresql.org/docs/8.0/sql-createuser.html. However, why do you want to add a user may be related to dependency-check and we can answer questions. but without knowing the goal it is hard to help.

**Comment by ammaraziz493** [comment]
> If you want to create a new user in PostgreSQL - it has nothing to do with dependency-check; see https://www.postgresql.org/docs/8.0/sql-createuser.html. However, why do you want to add a user may be related to dependency-check and we can answer questions. but without knowing the goal it is hard to help.

Actually I want to store a new user created by Jenkin directly into PostgreSQL.
By the way thanks for help.

**Comment by jeremylong** [comment]
so absolutely nothing related to this projet...
