### ISSUE TITLE
Gradle Plugin for owasp-dependency-check version 10.0.4 not available at maven central

### ISSUE THREAD

**Issue by mjbs82** [dependency-check/DependencyCheck#6973]
Hello! 

We have noticed that the gradle plugin has not been uploaded as usual for the recent version 10.0.4 

https://repo.maven.apache.org/maven2/org/owasp/dependency-check-gradle/

Is this intended? Do you plan to upload it there?

Thank you.

**Comment by jeremylong** [comment]
It is on the standard gradle plugin portal. We had an issue publishing and I haven't been able to resolve it. I'm likely going to revert a few changes and the next version will be back on central.

**Comment by jeremylong** [comment]
See https://github.com/dependency-check/dependency-check-gradle/pull/402

**Comment by mjbs82** [comment]
Thanks a lot for your response, we will wait for the next version! Closing the ticket.

**Comment by mjbs82** [comment]
Hello, gradle plugin for version 11.0.0 still not available at maven central. Any plan to upload it? https://repo.maven.apache.org/maven2/org/owasp/dependency-check-gradle/11.0.0/dependency-check-gradle-11.0.0.pom

**Comment by mjbs82** [comment]
Ok already read: https://plugins.gradle.org/plugin/org.owasp.dependencycheck
