### ISSUE TITLE
[Feature Request] Add "notes" of suppressions file to the dependency-check report

### ISSUE THREAD

**Issue by rzanner** [dependency-check/DependencyCheck#698]
It would be nice to have the content of the <notes> tag of a provided suppressions file in the created dependency-check report (esp. HTML). 

This way you could see at first glance, why a certain dependency or vulnerability is suppressed.

**Comment by jeremylong** [comment]
Duplicate of issue #651. I am going to try to be better about correctly labeling tickets and leaving them open until the fix/enhancement has been released. This is pending the next release.
