### ISSUE TITLE
Dependency-check not scanning all the jars in the given directory

### ISSUE THREAD

**Issue by champaanand** [dependency-check/DependencyCheck#6985]
Hello , We have a requirement to scan the jar files which are kept under one directory. (dependency-check version 10.0.4)
Command used - **./bin/dependency-check.sh --out . --format CSV --nvdApiKey xxxxxxx --scan /root/dependency-check/jars_3.1.3**

While this command shows the report/vuln for 4 jars only while I have around 26 jars in the directory jars_3.1.3.

If I run the command separately for each jar it does report the vulnerability for all the 26 jars
(./bin/dependency-check.sh --out . --format CSV --nvdApiKey xxxxxxx  --scan /root/dependency-check/jars_3.1.3/abs.jar      
./bin/dependency-check.sh --out . --format CSV --nvdApiKey xxxxxxx  --scan /root/dependency-check/jars_3.1.3/def.jar) 
Please let me know if there is anything missing.

**Comment by champaanand** [comment]
Tried the below option as well: (all the jars are present under ./jars_3.1.3/ directory
./bin/dependency-check.sh --out . --format CSV --nvdApiKey xxxxxx --scan ./jars_3.1.3/*.jar

**Comment by jeremylong** [comment]
By default ODC will combine related JAR files. See if there are related
dependencies listed.

**Comment by champaanand** [comment]
All the 26 jars are independent. (This is not jenkins integrated, we are running on the command line)
Any parameter do we need to set?

**Comment by jeremylong** [comment]
did you see in the report the related JARs section(s)?

**Comment by champaanand** [comment]
@jeremylong I don't see any column with the name **related** in the report.

"Project","ScanDate","DependencyName","DependencyPath","Description","License","Md5","Sha1","Identifiers","CPE","CVE","CWE","Vulnerability","Source","CVSSv2_Severity","CVSSv2_Score","CVSSv2","CVSSv3_BaseSeverity","CVSSv3_BaseScore","CVSSv3","CPE Confidence","Evidence Count","VendorProject","Product","Name","DateAdded","ShortDescription","RequiredAction","DueDate","Notes"

Searched for the missing jar names in the report, they are not found.

**Comment by jeremylong** [comment]
The CSV report is garbage for actual analysis of the CVEs and how things are reported. Look at the HTML report.

**Comment by champaanand** [comment]
HTML report shows the related jars. CSV format is not recommended is it?

**Comment by jeremylong** [comment]
I only created the CSV report because of the many requests for it - in my opinion, it isn't useful because it is hard to determine if something is a false positive by just looking at the CSV report. Additionally, the HTML report gives you the ability to generate suppression rules in case you run into FP.

**Comment by champaanand** [comment]
great, thanks for the response @jeremylong
