### ISSUE TITLE
binary

### ISSUE THREAD

**Issue by AJquetta** [dependency-check/DependencyCheck#6987]
Hi, does dependency-check scan binary and generate sbom of it. 

for example: sample.bin as an import and export sample.json.

is it possible with this tool, if yes what would be exact command and if not, is there any open source tool which can help me with that.

Thanks.

**Comment by aikebah** [comment]
DependencyCheck is not a tool for creating an SBOM. You'd be better of taking a look at the [CycloneDX](https://cyclonedx.org/) website for the various tools within the SBOM exosystem.
