### ISSUE TITLE
False positive on Splunk Java SDK

### ISSUE THREAD

**Issue by wwftw** [dependency-check/DependencyCheck#699]
Splunk java sdk was detected as splunk enterprise version hence fail for all splunk versions which has since uplifted to resolve vulnerability.

False positive on splunk sdk splunk-1.6.2.jar - reported as cpe:/a:splunk:splunk:1.6.2.0
```xml
<dependency>
   <groupId>com.splunk</groupId>
   <artifactId>splunk</artifactId>
   <version>1.6.2</version>
</dependency>
```

**Comment by jeremylong** [comment]
Thanks for the report, I will try to include a fix in the next release.
