### ISSUE TITLE
False positive on Spring Cloud netflix core - cpe:/a:pivotal:spring_framework:1.2.5

### ISSUE THREAD

**Issue by philippn** [dependency-check/DependencyCheck#700]
Hi there,
first of all, thanks for your work! Your plugin is very valuable and much appreciated.

False positive on library \spring-cloud-netflix-core-1.2.5.RELEASE.jar - reported as cpe:/a:pivotal:spring_framework:1.2.5
```xml
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-netflix-core</artifactId>
    <version>1.2.5.RELEASE</version>
</dependency>
```

Details: The reported problem is actually not in the said library, but in Spring Framework itself. An affected version of Spring framework is transitively referenced by the dependency on Spring Boot 1.4.2, so this might still be correct in some cases.

In my case however, the version of spring framework is overridden because I'm using a higher version of Spring Boot (1.4.5) as parent. And that in turn depends on Spring Framework 4.3.7, which is not affected anymore.

Thanks in advance for your time!

**Comment by philippn** [comment]
The same is also the case for 

spring-cloud-commons-1.1.7.RELEASE.jar
cpe: cpe:/a:pivotal:spring_framework:1.1.7   Confidence:LOW 
cpe: cpe:/a:pivotal_software:spring_framework:1.1.7   Confidence:LOW
maven: org.springframework.cloud:spring-cloud-commons:1.1.7.RELEASE   Confidence:HIGHEST

and

spring-cloud-context-1.1.7.RELEASE.jar
cpe: cpe:/a:context_project:context:1.1.7   Confidence:LOW
cpe: cpe:/a:pivotal:spring_framework:1.1.7   Confidence:LOW
cpe: cpe:/a:pivotal_software:spring_framework:1.1.7   Confidence:LOW
maven: org.springframework.cloud:spring-cloud-context:1.1.7.RELEASE   Confidence:HIGHEST

**Comment by jeremylong** [comment]
Thanks for the bug report, I will try and include a fix in the next release.
