### ISSUE TITLE
Why do I run into the problem Error: could not open `{failsafeArgLine}'?

### ISSUE THREAD

**Issue by CH3SCN** [dependency-check/DependencyCheck#7010]
It seems the problem originates from here...
`            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-invoker-plugin</artifactId>
                        <configuration>
                            
                            <parallelThreads>4</parallelThreads>
                            <mavenOpts>${failsafeArgLine}</mavenOpts>
                            <cloneProjectsTo>${project.build.directory}/it</cloneProjectsTo>
                            <localRepositoryPath>target/local-repo</localRepositoryPath>
                            <properties>
                                <odc.version>${project.version}</odc.version>
                            </properties>
                        </configuration>
                        <executions>
                            <execution>
                                <id>integration-test</id>
                                <goals>
                                    <goal>install</goal>
                                    <goal>run</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>`
![Screenshot 2024-10-06 161403](https://github.com/user-attachments/assets/f4b1f849-a3af-4a9a-a4bf-77bd6b5e9822)

**Comment by aikebah** [comment]
It's because you invoke the test execution for debugging somehow in an incorrect way.

The way you run the testcase invocation does not configure the failSafeArgLine variable, resulting in it being used verbatim as the property-reference.

In a normal maven build this would be set by the JaCoCo plugin in a preparation phase before the integration tests:

https://github.com/jeremylong/DependencyCheck/blob/5c7b1b64ca4be2631a0e7a7639e9f1d4f3d8a4e6/pom.xml#L598-L609

**Comment by CH3SCN** [comment]
Then, how to configure the failSafeArgLine variable?

**Comment by aikebah** [comment]
Try following the [Readme](https://github.com/jeremylong/DependencyCheck?tab=readme-ov-file#intellij-idea)
