### ISSUE TITLE
Push functionality for new vulnerabilities

### ISSUE THREAD

**Issue by javabeanz** [dependency-check/DependencyCheck#702]
Please consider a push mode for the Dependency Check library.  Once an application is in production, it is typically not built anymore, and therefore not monitored on new dependency vulns. The Maven plugin is now a 'pull' mode, it would be great if there were a 'push', where new vulns come in without a build of the application. My first guess would be to use a nosql db for this.

**Comment by stevespringett** [comment]
The agent can be used if you have a software bill of materials in a database somewhere. This would allow you to actively monitor components for new vulnerabilities for software that's no longer built.

You can also use Dependency-Track for this task. V1 can do this today but is deprecated in favor of v3 currently in active development. Both of these use the agent under the hood.

For application monitoring at runtime check out issue #585

**Comment by jeremylong** [comment]
@javabeanz as Steve pointed out, dependency-track is likely the best option for the functionality you are looking for.
