### ISSUE TITLE
pom.xml not analyzed in CLI/Jenkins

### ISSUE THREAD

**Issue by colezlaw** [dependency-check/DependencyCheck#703]
Please delete any un-needed section from the following issue template:

### Reporting Bugs/Errors
https://gist.github.com/colezlaw/e6106b38aac09d5eca58c77981d50382

When using the CLI to analyze a directory, if the project is a Maven project, `pom.xml` is not analyzed. The log shows that `pom.xml is not a file`:

    DEBUG - Found file /Users/willstranathan/src/naenae/pom.xml
    DEBUG - Path passed to scanFile(File) is not a file: /Users/willstranathan/src/naenae/pom.xml. Skipping the file.

This also ends up impacting the Jenknis plugin. If we analyze the project using the Maven plugin, it identifies everything, but when analyzing as just a directory, the pom is not analyzed.

**Comment by jeremylong** [comment]
This is expected behavior. Instead of running the CLI directly, maybe you could use a script to check if it is a maven, gradle, or sbt build based on the presence of build files in the scanned directory and run the appropriate build command, such as:

```
mvn org.owasp:dependency-check-maven:1.4.5:check
```
