### ISSUE TITLE
Hint Analyzer: Remove Evidence Based on Regex

### ISSUE THREAD

**Issue by jeremylong** [dependency-check/DependencyCheck#704]
Update the hint analyzer to remove evidence based on a regex value instead of the exact match mechanism used now. An example of the current way to remove single items of evidence can be found in the dependencycheck-base-hint.xml. See #664 for more information/example.

**Comment by aikebah** [comment]
@jeremylong If I understand correctly what is to be introduced is allowing to specify a regex for `<evidence ...>` inside `<given>` and `<remove>`

Should regexes only apply to the value clause, or also be applicable to the other entries?

Offering to work on creating a PR for this one once the requirements are clear.

**Comment by jeremylong** [comment]
The idea is to make the hint analyzer more flexible.  Currently we can define match rules like:

```
<evidence type="vendor" source="pom" name="parent-groupid" value="org.springframework.boot" confidence="HIGHEST"/>
```
This requires an exact match to the value and confidence. When implementing the improvement it would be good to allow a regex on the value. It may also be good to make the source and confidence optional and if blank it would match any. However, I don't think the name needs to have a regex applied.

**Comment by aikebah** [comment]
Jeremy, while looking at implementing this I spotted a TODO in the code of the HintAnalyzer (https://github.com/jeremylong/DependencyCheck/blob/816e17a67b35a044cea8260968dfbce12f23b586/dependency-check-core/src/main/java/org/owasp/dependencycheck/xml/hints/HintParser.java#L84)

It is indeed trivial to support multiple schemas at once (solving this issue would introduce the 3rd iteration of the hints XSD), given that namespaces are used.

https://docs.oracle.com/javase/tutorial/jaxp/sax/validation.html points for the advanced multi-namespace parsing to the DOM Validation trail of the tutorial https://docs.oracle.com/javase/tutorial/jaxp/dom/validating.html which indicates that the `http://java.sun.com/xml/jaxp/properties/schemaSource` factory-property can be an array of String/InputStream/InputSource/File and apparently even an Object array that contains a mixture of those.

Shall I update the code as part of fixing this issue, or shall I create a separate pull-request (and accompanying issue) that just resolves this TODO (and cleans up the similar multiple-schemas code of the SuppressionParser)?

**Comment by jeremylong** [comment]
I'm fine with both being solved in a single PR - truly appreciate you working on this. I should point out that there are significant changes coming to the analyzers - but don't worry, when I get around to merging the update(s) I will update any PRs that are still based on the 2.x analyzer API (the 3.0.0 is in development trying to fix a couple of threading issues).

**Comment by aikebah** [comment]
Needs a little more testing and checking code cleanliness before committing to my branch and issueing a PR, but the preliminary results are promising. I am able to get rid of the Netflix FP using my local build using 

```
<hints xmlns="https://jeremylong.github.io/DependencyCheck/dependency-hint.1.3.xsd">
    <hint>
        <given>
            <evidence type="vendor" name="module-origin" value="^git@github.com:.+" regex="true"/>
        </given>
        <remove>
            <evidence type="vendor" name="module-origin" value="^git@github.com:.+" regex="true"/>
        </remove>
    </hint>
</hints>

```

(So it wasn't the github URL in the pom, but the git-uri in the module-origin that triggered the false link to git as a software product)
