### ISSUE TITLE
Skip dependency scan via a gradle cli command?

### ISSUE THREAD

**Issue by EugenMayer** [dependency-check/DependencyCheck#7052]
Running a gradle task 'allTests' (kotlin-multiplatform) the dependency check is run without us actually wanting this.

I assume the task is not part of the test-group and thus not skipped.

Thus the question, can we provide a gradle argument to deactivate dep. scanning in such cases?

Thanks

**Comment by chadlwilson** [comment]
Dep check isn't run as part of any other task by default in any of my gradle projects (kotlin or otherwise).

You sure this isn't something in your gradle config or some other plugin?

**Comment by EugenMayer** [comment]
I rechecked the run to ensure it's not nonsense - and it was layer8. There was no scan and the delay of that run had other reasons.

I'am really sorry to have wasted your time on this! (closing the question humbly :) )
