### ISSUE TITLE
Option to skip corrupt data with a warning message

### ISSUE THREAD

**Issue by DominikAmon** [dependency-check/DependencyCheck#7097]
There where three out of more than three hundred thousand entries in the NVD corrupt were corrupt. [Currently, the process fails entirely due to these corrupt entries](https://github.com/jeremylong/DependencyCheck/issues/7067). 

I'd like to propose a feature that would allow the process to continue even if corrupt entries are encountered. Instead of failing, the process could skip these entries with a warning message. Alternatively, there could be an option to configure this behavior.

This would enable projects to be scanned without being halted by a small number of corrupt entries.

Thank you for your time and consideration.

**Comment by jeremylong** [comment]
As discussed previously in #7067 - the issue with implementing a feature like this is that the your local DB could get out of synch.
