### ISSUE TITLE
What can dependency-check scan for in an APK?

### ISSUE THREAD

**Issue by sushi2k** [dependency-check/DependencyCheck#7107]
Hi, 

I've got a simple Android app that has one vulnerable dependency that I added via `build.gradle.kts`

```
               implementation ("com.squareup.okhttp3:okhttp:4.8.0")
```

I scanned now in 2 ways:

First by adding dependency-check in Android Studio into the `build.gradle.kts`:

```groovy
plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("org.owasp.dependencycheck") version "10.0.4" 
}

dependencyCheck {
    formats = listOf("HTML", "XML", "JSON") // Generate reports in HTML, JSON and XML format
    nvd {
        apiKey = "MY-KEY"
        delay = 16000
    }
}
```

This works when I execute ` ./gradlew dependencyCheckAnalyze` and it generates a report for me and it finds 35 Vulnerable Dependencies and 83 Vulnerabilities and also finds the vulnerable `okhttp` dependency:

<img width="1480" alt="image" src="https://github.com/user-attachments/assets/a77aef10-4c6d-4fb7-9862-77078699fc69">

<img width="1434" alt="image" src="https://github.com/user-attachments/assets/331316a9-7b43-409b-82ad-13a47142ab75">

Afterwards I created an APK file out of the same project and scanned the APK file via cli by executing:

```bash
$ dependency-check --nvdApiKey MY-KEY -s app-debug.apk
```

The generated report is empty.

<img width="524" alt="image" src="https://github.com/user-attachments/assets/8de58b46-cbb6-4543-a253-a1db229d9b3f">

Is this now a limitation of SCA tools, that they will usually fail to scan an APK, because of 2 reasons:

- **Transformed format**: The libraries are no longer in their original format but are part of the app binaries compiled into DEX format.
- **Lack of metadata**: Information such as the library version or name is stripped or altered when building the mobile app.

What is the supposed output when scanning an APK and are my assumptions listed above correct in the context of `dependency-check`?

**Comment by jeremylong** [comment]
You are correct. APKs, for the most part, do not contain the 3rd party JAR file in a similar manner to other archives like WARs. As such, the only real way to scan an android application is to scan the build itself. For ODC the main reason you can't scan an APK is the lack of meta-data. Other tools that look at things like file hashes - the transformation to DEX can be an issue.

**Comment by sushi2k** [comment]
Noted and thanks for clarifying and the swift response @jeremylong!
