### ISSUE TITLE
Warning: Explicitly loaded driver org.h2.Driver from classpath

### ISSUE THREAD

**Issue by OrangeDog** [dependency-check/DependencyCheck#7118]
**Describe the bug**
> [INFO] --- dependency-check:11.1.0:check (default-cli) @ demo ---
> [WARNING] Explicitly loaded driver org.h2.Driver from classpath; if JDBCv4 service loading is supported by the driver you should remove the dbDriver configuration

Message is also duplicated to stderr.

**Version of dependency-check used**
Maven plugin 11.1.0

**To Reproduce**
1. `mvn dependency-check:check`

**Expected behavior**
No warnings

**Additional context**
Related to #7115?

**Comment by jeremylong** [comment]
Understand the warning - but for [reasons](https://github.com/jeremylong/DependencyCheck/issues/7092) we've had to revert to legacy driver loading mechanisms.

**Comment by aikebah** [comment]
@jeremylong I think for the same reason we should remove this warning, which was introduced to signal uses of the explicit drivername triggering the 'legacy way' of driver registration where not required (assuming that JDBC 4 SPI driver loading would work flawlessly, which has been proven to be a wrong assumption.

https://github.com/jeremylong/DependencyCheck/pull/6938/files#diff-1bd6d053c4d3e4fd27267ae889d2f7b7fa257855e928959564295c1736e815d1

**Comment by jeremylong** [comment]
Thank you @aikebah - I completely missed that I had written this log message. fixing this shortly.

**Comment by aikebah** [comment]
> Thank you @aikebah - I completely missed that I had written this log message. fixing this shortly.

That's because you didn't... I wrote it, you only merged it.
