### ISSUE TITLE
Determine state and value of Node.js analyzer

### ISSUE THREAD

**Issue by stevespringett** [dependency-check/DependencyCheck#712]
In my testing creating the Node Security Platform (nsp) analyzer, I used the existing Node.js experimental analyzer as a baseline.

When testing https://github.com/OWASP/NodeGoat I discovered that the Node.js analyzer had a 100% false positive rate and a 100% false negative rate, whereas the nsp analyzer had a 100% true positive rate without any evidence of false positives. - HTML report attached.

This was only a single test of a single project, so I don't know if these results are indicative of Node.js analysis as a whole. But it does raise the question... Is the Node.js analyzer providing value to the userbase?

[dependency-check-report.html.zip](https://github.com/jeremylong/DependencyCheck/files/952344/dependency-check-report.html.zip)

**Comment by jeremylong** [comment]
Steve - I have been planning on going through and removing some of the experimental analyzers; specifically the node analyzer. As you've pointed out there are better options for Node.js.
