### ISSUE TITLE
java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.util.NativeImageUtil.isInNativeImage()Z

### ISSUE THREAD

**Issue by Aravind202leo** [dependency-check/DependencyCheck#7140]
I was trying to upgrade the fasterxml from  2.15.x to 2.18.0 
during this upgrade I' getting this following exception

Dependency error for fasterxml:
preload on startup in Web application: "cloud".
A MultiException has 2 exceptions. They are:
1. java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.util.NativeImageUtil.isInNativeImage()Z
2. java.lang.IllegalStateException: Unable to perform operation: post construct on org.glassfish.jersey.jackson.internal.FilteringJacksonJaxbJsonProvider

What should be the solution

**Comment by stevenschlansker** [comment]
Did you make sure that there are no mismatched Jackson versions? From the limited detail available it looks like a mismatch where you run some jars as 2.18 and other jars are still on 2.15

**Comment by aikebah** [comment]
@Aravind202leo How is this OWASP DependencyCheck related? You appear to get you issue in a 'cloud' web application?

We already moved away from 2.15.x with version 9.0.0 and current version of the project is already depending on 2.18.1

**Comment by Aravind202leo** [comment]
yes this is a cloud web application
