### ISSUE TITLE
`dependency-check-maven:11.1.0:aggregate` produces a HTML report that says `dependency-check version: 10.0.4`.

### ISSUE THREAD

**Issue by wilx** [dependency-check/DependencyCheck#7154]
**Describe the bug**
`dependency-check-maven:11.1.0:aggregate` produces a HTML report that says `dependency-check version: 10.0.4`. Wrong version.

**Version of dependency-check used**
`dependency-check-maven:11.1.0`

**Expected behavior**
The version in the report should be correct.

**Additional context**
Is is possible that it is because the following snippet should be using `project.version` instead?
https://github.com/jeremylong/DependencyCheck/blob/7685228a428b123ba108f8f9d70b7f1b1fb4cbc8/core/src/main/resources/dependencycheck.properties#L1-L2

**Comment by jeremylong** [comment]
I would double-check the version of dependency-check you are using. If the report says 10.0.4 - you are using 10.0.4 not 11.1.0.

**Comment by wilx** [comment]
I am hitting some issue with the DB with 11.1.0 but the ultimate problem is that the target directory is not getting cleaned up before the scan.
