### ISSUE TITLE
Experimental Python analyzers incorrectly identify vulnerabilities for a package (python-gitlab)

### ISSUE THREAD

**Issue by NioXen** [dependency-check/DependencyCheck#7159]
**Describe the bug**
When using the Python experimental analyzers, the python package [python-gitlab](https://pypi.org/project/python-gitlab/) is incorrectly identified as the Gitlab platform.

From the report
| Dependency          | Vulnerability IDs                                  | Package                                       | Highest Severity | CVE Count | Confidence | Evidence Count |
| ------------------- | -------------------------------------------------- | --------------------------------------------- | ---------------- | --------- | ---------- | -------------- |
| gitlab:5.0.0        | cpe:2.3:a:gitlab:gitlab:5.0.0:\*:\*:\*:\*:\*:\*:\* | pkg:pypi/gitlab <br>pkg:pypi/gitlab@5.0.0     | CRITICAL         | 209       | Medium     | 4              |
| pip:24.2            |                                                    | pkg:pypi/pip@24.2                             | HIGH             | 1         |            | 3              |
| pip:24.2            |                                                    | pkg:pypi/pip@24.2                             | HIGH             | 1         |            | 2              |
| python-gitlab:5.0.0 | cpe:2.3:a:gitlab:gitlab:5.0.0:\*:\*:\*:\*:\*:\*:\* | pkg:pypi/python-gitlab@5.0.0                  | CRITICAL         | 209       | Highest    | 3              |
| python-gitlab:5.0.0 | cpe:2.3:a:gitlab:gitlab:5.0.0:\*:\*:\*:\*:\*:\*:\* | pkg:pypi/python-gitlab@5.0.0                  | CRITICAL         | 209       | Highest    | 3              |
| urllib3:1.26.18     |                                                    | pkg:pypi/urllib3 <br>pkg:pypi/urllib3@1.26.18 | MEDIUM           | 1         |            | 3              |

**Version of dependency-check used**
The problem occurs using version 11.1.0 of the cli 

**Log file**
If required, I can upload this from a different machine because the log from my work machine has sensitive information.

**To Reproduce**
1. Create `requirements.txt` with content `python-gitlab==5.0.0`
2. `python -m venv env && source /env/bin/activate`
3. `pip install -r requirements.txt`
4. `dependency-check --scan . --enableExperimental`

**Expected behavior**
`python-gitlab` should not display vulnerabilities for the Gitlab platform.

**Additional context**
I'm not sure if this would be more appropriate as a False Positive report, however I think this is more of an issue with how the analyzers identify the vulnerability IDS

**Comment by aikebah** [comment]
Your finding is simply a false positive (in short the application logic is: find traces of information (evidences) on the dependencies and then do a best-match correlation to the CPEs). 
The CPE (Common Platform Enumeration) is the unique key for an application that is used in the NVD database to link known CVEs  to the software products that are affected by the vulnerability.

**Comment by NioXen** [comment]
Thank you for the explanation

In the False Positive report template, it specifies only adding a single CVE. I'm happy to re-open this issue as a false positive report, but I'm hesitant to open ~200 issues for each entry. Is there a preferable way for me to raise these?

**Comment by aikebah** [comment]
Quoting from that template:

>If filing a CPE report you do not need to add the CVEs. Note that most reports should be for incorrectly matched CPEs.

**Comment by aikebah** [comment]
Your report would be a CPE report as the python-gitlab package is not the gitlab software, so the false positive is about an incorrectly linked CPE.

**Comment by NioXen** [comment]
Perfect, thank you for your time
I'll close this issue and open the correct type
