### ISSUE TITLE
Gradle version compatibility with Java 8

### ISSUE THREAD

**Issue by EddeCCC** [dependency-check/DependencyCheck#7168]
Greetings,

I am trying to use the **DependencyCheck Gradle plugin with version 10.0.4** in my Java Gradle project.
Since we are using Java 8, **Gradle 7.6.4** is the latest version we can use currently.

Are these versions compatible? When running `./gradlew dependencyCheckAnalyze`, the following error appears:
```
Execution failed for task ':dependencyCheckAnalyze'.
> Class org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated does not implement the requested interface org.gradle.api.Named

```

It seems like the plugin expects a more modern Gradle class. I believe the Gradle `DefaultConfiguration` only implements the `Named` interface since version 8.*

Do you know, what is the latest version of the DependencyCheck plugin that works with Gradle 7?

**Comment by jeremylong** [comment]
Duplicate of https://github.com/dependency-check/dependency-check-gradle/issues/411

This should be fixed in 11.0.0+. Yes, that does mean ODC requires Java 11.

**Comment by jeremylong** [comment]
11.0.0+ is compatible with Gradle 7 - but does require a Java 11 runtime.

**Comment by EddeCCC** [comment]
Thanks for your answer. 
Since I cannot use 11.0.0+ I downgraded to 10.0.3, which removed the mentioned error. 
I guess just version 10.0.4 requires Gradle 8. However, I couldn't find the source code of the version.

Best Regards
