### ISSUE TITLE
Explicitly loaded driver org.h2.Driver from classpath; if JDBCv4 service loading is supported by the driver you should remove the dbDriver configuration

### ISSUE THREAD

**Issue by patpatpat123** [dependency-check/DependencyCheck#7173]
Hello team,

Before opening this issue, I had a look at the changes from:

```
Breaking Changes in 11.0.0

Java 11 is now required to run dependency-check 11.0.0 or higher

H2 database upgrade

11.0.0 contains breaking changes using the local H2 database. A full download of the NVD data will occur. Note that if you are using a shared data directory the h2 database file is not compatible with older versions of dependency-check. If you run into problems you may need to run a purge:

```

I made sure that I have a high version of Java.

However, upon this simple command: `mvn site`

There is now this new warning `Explicitly loaded driver org.h2.Driver from classpath; if JDBCv4 service loading is supported by the driver you should remove the dbDriver configuration`

May I ask what does it mean, and how can I fix this warning?

Thank you

**Comment by aikebah** [comment]
Sounds like you're running 11.1.0, which partly reverted the changes in 11.0.0 after several advanced configurations failed to load the H2 driver using JDBC4 SPI driver-discovery (#7092). 

The codebase was restored to configuring an explicit database driver classname (triggering explicit JDBC driver registration by using Class.forName as was required by JDBC prior to JDBC4), but the warning message that was added to the codebase in 11.0.0 for setups that still used the driver classname configuration was not reverted (#7118). This will be resolved in the next release.

For now you can simply ignore the warning.

**Comment by patpatpat123** [comment]
Very clear, thank you!
