### ISSUE TITLE
IO Exception: Unable to tunnel through proxy. Proxy returns  "HTTP/1.1 407 Proxy Authentication Required"

### ISSUE THREAD

**Issue by dhamaris** [dependency-check/DependencyCheck#718]
Hello, I am running my application with Maven 3.1.1, Java 8 and currently facing this error:

https://gist.github.com/dhamaris/d4c30b22456bc68d3c6cb2c33111561b

My plugin and proxy configuration is

https://gist.github.com/dhamaris/3032568832532b3e99625910baade067

**Comment by jeremylong** [comment]
Can you try removing the proxy configuration from the dependency-check plugin and then run (of course configuring the correct host, etc.):

```
mvn -Dhttp.proxyHost=host -Dhttp.proxyPort=8080 -Dhttp.proxyUser=someUserName -Dhttp.proxyPassword=somePassword org.owasp:dependency-check-maven:1.4.5:update-only -X
```

Does that work in your case? If that does, I have a possible idea on how to resolve the issue.

**Comment by dhamaris** [comment]
@jeremylong  It does not work, it throws the same error. I wonder if it has to do with my maven or java version, or maybe something to do with a firewall configuration? I currently use:
Maven: Apache Maven 3.1.1 
Java version: 1.8.0_131
Otherwise this proxy works fine, it downloads dependencies from http://uk.maven.org/maven2 without any errors.

**Comment by dhamaris** [comment]
I got it solved putting this under JRE -> VM Arguments:
-Djdk.http.auth.tunneling.disabledSchemes=""

**Comment by jeremylong** [comment]
Glad you figured this out - I bet others will run into the same issue. See the section titled [Disable Basic authentication for HTTPS tunneling](http://www.oracle.com/technetwork/java/javase/8u111-relnotes-3124969.html).
