### ISSUE TITLE
Continued Java 8 support

### ISSUE THREAD

**Issue by theangrydev** [dependency-check/DependencyCheck#7182]
Are there any community efforts to maintain Java 8 support? I have some projects that are unable to move to Java 11

**Comment by aikebah** [comment]
You know that with Java 11 (and 17 and 21) as the JDK that runs your build tools you can still create classes targeting Java 8?

More and more tools are requiring java 11 (or higher) as a minimal version.

**Comment by aikebah** [comment]
In my day-job we have plenty of projects still targeting Java 8 runtimes, but all builds are at least at Java 11, soon Java 17, as tools used in the build require it.

**Comment by theangrydev** [comment]
@aikebah I've had clients doing unspeakable things with rt.jar 😂 but yes something like this could work if I ran the dependency check as a separate plugin run from the main build, thanks

**Comment by aikebah** [comment]
Yeah... I get the gist... similar to putting system-scoped dependencies to `<systemPath>${tools.jar}</systemPath>` in your poms and publishing them on on maven central.
