### ISSUE TITLE
scan error

### ISSUE THREAD

**Issue by topsekadmin** [dependency-check/DependencyCheck#7187]
log shwo below:

[WARN] An error occurred with the .NET AssemblyAnalyzer, please see the log for more details.
dependency-check requires dotnet 8.0 core runtime or sdk to be installed to analyze assemblies.
[ERROR] Exception occurred initializing Assembly Analyzer.
[WARN] No lock file exists - this will result in false negatives; please run `npm install --package-lock`
[WARN] Analyzing `/opt/test/sesam/packages/common/package.json` - however, the node_modules directory does not exist. Please run `npm install` prior to running dependency-check
[WARN] No lock file exists - this will result in false negatives; please run `npm install --package-lock`
[WARN] Unable to find node module: /opt/test/sesam/packages/main/node_modules/nprogress/package.json
[WARN] Unable to find node module: /opt/test/sesam/packages/main/node_modules/qiankun/package.json
[WARN] Unable to find node module: /opt/test/sesam/packages/main/node_modules/vue/package.json
[WARN] Unable to find node module: /opt/test/sesam/packages/main/node_modules/pinia/package.json
[WARN] Unable to find node module: /opt/test/sesam/packages/main/node_modules/vue-router/package.json
[WARN] Unable to find node module: /opt/test/sesam/packages/main/node_modules/element-plus/package.json
[WARN] Unable to find node module: /opt/test/sesam/packages/main/node_modules/@element-plus/icons-vue/package.json
[WARN] Unable to find node module: /opt/test/sesam/packages/main/node_modules/axios/package.json
[WARN] Unable to find node module: /opt/test/sesam/packages/main/node_modules/vue-i18n/package.json
[WARN] Unable to find node module: /opt/test/sesam/packages/main/node_modules/vite-plugin-svg-icons/package.json
[WARN] Unable to find node module: /opt/test/sesam/packages/main/node_modules/crypto-js/package.json
[WARN] Unable to find node module: /opt/test/sesam/packages/main/node_modules/pinia-plugin-persistedstate/package.json
[WARN] Unable to find node module: /opt/test/sesam/packages/main/node_modules/vue3-cookies/package.json
[WARN] No lock file exists - this will result in false negatives; please run `npm install --package-lock`
[WARN] Analyzing `/opt/test/sesam/packages/vue3Vite/package.json` - however, the node_modules directory does not exist. Please run `npm install` prior to running dependency-check
[WARN] dependency skipped: node module @esbuild/aix-ppc64 seems optional and not installed
[WARN] dependency skipped: node module @esbuild/android-arm seems optional and not installed
[WARN] dependency skipped: node module @esbuild/android-arm64 seems optional and not installed
[WARN] dependency skipped: node module @esbuild/android-x64 seems optional and not installed
[WARN] dependency skipped: node module @esbuild/darwin-arm64 seems optional and not installed

When I perform a scanning task, it prompts that the. net SDK is not installed, but I have already installed it
[root@xxxxxx dotnet]# ./dotnet --version
8.0.404

I have also installed npm and executed npm install
[root@xxxx sesam]# npm install
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: '@achrinza/node-ipc@9.2.2',
npm warn EBADENGINE   required: { node: '8 || 10 || 12 || 14 || 16 || 17' },
npm warn EBADENGINE   current: { node: 'v20.18.1', npm: '10.8.2' }
npm warn EBADENGINE }

up to date in 15s

268 packages are looking for funding
  run `npm fund` for details

May I ask how to solve this problem?

**Comment by aikebah** [comment]
You likely don't have dotnet is the OS path (note how you use `./dotnet` in the dotnet installation folder and not simply dotnet in root's home folder).

If you don't have dotnet in the system path you must explicitly configure the dotnet executable location for the assemblyanalyzer to be able to run

**Comment by aikebah** [comment]
on the npm install output you already see what your issue is for the nodejs part of the project: your project's dependencies hard require a lower version of nodejs than the version installed on the system. Either upgrade the project's dependencies to versions that are compatible with nodejs v20 or downgrade the active nodejs on your system to a compatible version.

**Comment by topsekadmin** [comment]
> on the npm install output you already see what your issue is for the nodejs part of the project: your project's dependencies hard require a lower version of nodejs than the version installed on the system. Either upgrade the project's dependencies to versions that are compatible with nodejs v20 or downgrade the active nodejs on your system to a compatible version.

OK，thank you for your help
