### ISSUE TITLE
Ownership and licensing

### ISSUE THREAD

**Issue by elharo** [dependency-check/DependencyCheck#7203]
It's a little unusual that the package name is org.owasp but this lives in a personal github repo instead of the owasp repo. Individual files appear to be copyrighted by individual contributors. Clarifying ownership and whether this project is officially supported by the OWasp Foundation would be useful.

**Comment by jeremylong** [comment]
See https://owasp.org/www-project-dependency-check/

**Comment by jeremylong** [comment]
also - how is this "unusual"?  It is listed as a [Flagship Project](https://owasp.org/projects/) on owasp.org. This repo was created a long time ago - when it was difficult to get a repo setup in the owasp organization on github. Moving the repo now would be detrimental to the project. If we were going to move this repo - it would likely be to the dependency-check organization; yet it is still an OWASP project.

There are many OWASP projects that do not live in the OWASP org. Several of the flagship projects are not in the owasp org.

**Comment by elharo** [comment]
As is, the repo depends on the continued availability and activity of a single person. If anything unexpected happens to you — career shift, meteor strike, hospitalization, etc. — it would halt progress on this project until folks realized there was a problem and the project could be migrated. It's easier to prepare for the unexpected in advance rather than after the fact from a laptop in a hospital bed (which I had to do last month).
