### ISSUE TITLE
[Enhancement request] Possibility to add the date of the scan (date of the page generation) in the html report

### ISSUE THREAD

**Issue by patpatpat123** [dependency-check/DependencyCheck#7213]
**Is your feature request related to a problem? Please describe.**
The html report created by dependency check is super helpful.
The issues are clearly described, the esthetic is quite good.
However, when looking at the html page, we often ask ourselves, when was the page generated? I.e. when did we run the check to generate this report? Was this page generated by a scan performed couple of minutes back? Or was it there from last week?

**Describe the solution you'd like**
Would it be possible to bake in the actual date to the report, like in those places (see screenshots)
I "painted" in red where we would hope to see the report, just to give an idea.
Maybe adding the info on the top near the banner
<img width="784" alt="Screenshot 2024-11-20 at 11 26 40" src="https://github.com/user-attachments/assets/8d63d2e2-9d80-4739-9953-82aca621667f">

Or at the bottom of the page
<img width="697" alt="Screenshot 2024-11-20 at 11 26 48" src="https://github.com/user-attachments/assets/ec00c111-a219-4862-a27e-07b7c93b283d">

**Describe alternatives you've considered**
As of now, as alternative, we run a command at the OS level to get the created date.

**Additional context**
Screenshots attached

**Comment by jeremylong** [comment]
The requested date is already present; see the scan information section:

<img width="468" alt="image" src="https://github.com/user-attachments/assets/dcb7531c-2c62-4be9-b95e-138273c7c7b6">

**Comment by patpatpat123** [comment]
Many thanks, closing
