### ISSUE TITLE
How to prevent dependency-check from using dates when calling the NIST api in version 11.X?

### ISSUE THREAD

**Issue by ftiercelin** [dependency-check/DependencyCheck#7219]
This question is triggered by [issue #7164](https://github.com/jeremylong/DependencyCheck/issues/7164)
The failure to execute the dependency-check with version 11.X is caused by dates not accepted by the NIST api.

Traces of an execution without issue:
```
[DEBUG] requesting URI: https://services.nvd.nist.gov/rest/json/cves/2.0?resultsPerPage=2000&startIndex=0
```

Traces of an execution ending up in failure "NVD Returned Status Code: 404 - Invalid ISO 8601 date/time format, see documentation."
```
[DEBUG] requesting URI: https://services.nvd.nist.gov/rest/json/cves/2.0?lastModStartDate=2024-11-24T01%3A04%3A56-05&lastModEndDate=2025-03-24T01%3A04%3A56-05&resultsPerPage=2000&startIndex=0
```
The dates, although seemingly valid are triggering the issue - possibly due to an implementation issue on NIST side.
Both executions are for the same pom.xml:
```xml
<plugin>
	<groupId>org.owasp</groupId>
	<artifactId>dependency-check-maven</artifactId>
	<version>11.0.0</version>
	<configuration>
		<failBuildOnCVSS>0</failBuildOnCVSS>
		<skipProvidedScope>true</skipProvidedScope>
		<skipTestScope>true</skipTestScope>
		<failOnError>true</failOnError>
		<suppressionFile>src/owasp.suppression.xml</suppressionFile>
		<nvdApiKey>********-****-****-****-************</nvdApiKey>
	</configuration>
	<executions>
		<execution>
			<goals>
				<goal>check</goal>
			</goals>
		</execution>
	</executions>
</plugin> 
```

In both cases, the arguments ``resultsPerPage=2000&startIndex=0`` should be enough, no need for dates.
Is there a way to configure the client not to use dates when calling the NIST api?
or is there a reason to use dates on the system facing the issue?

Thanks

**Comment by jeremylong** [comment]
The dates are necassary as we are retrieving 0-2000 in the given date range. The question is why is the date invalid? From your request, the start date is: `2024-11-24T01:04:56-05`

From another job that works I grabbed:
https://services.nvd.nist.gov/rest/json/cves/2.0?lastModStartDate=2024-12-02T11%3A15%3A09Z&lastModEndDate=2025-04-01T11%3A15%3A09Z&resultsPerPage=1000&startIndex=0

Which has a start date of `2024-12-02T11:15:09Z`.

What JVM are you using, what timezone are you in (guessing by -5 you are Eastern)?

**Comment by ftiercelin** [comment]
@jeremylong , that's the most intriguing part. I'm Europe/Dublin, which, at this time of the year, is exactly UTC
```
timedatectl status | grep "Time zone"
                Time zone: Europe/Dublin (GMT, +0000)
/usr/lib/jvm/java-17-openjdk-amd64/bin/java --version
openjdk 17.0.13 2024-10-15
OpenJDK Runtime Environment (build 17.0.13+11-Ubuntu-2ubuntu122.04)
OpenJDK 64-Bit Server VM (build 17.0.13+11-Ubuntu-2ubuntu122.04, mixed mode, sharing)

ZonedDateTime.now(ZoneId.systemDefault())=2024-12-03T16:54:10.898666585Z[Europe/Dublin]
```

I suspect the following:
1. I ran last week the plugin with 
`` <nvdDatafeedUrl>https://mirror.cveb.in/nvd/json/cve/1.1/nvdcve-1.1-{0}.json.gz</nvdDatafeedUrl>``
2. this has stored in the database a last modified date which is not UTC but UTC-5 (US East Coast)
3. the date is retrieved by plugin at my next execution:
```java
ZonedDateTime lastModifiedRequest = dbProperties.getTimestamp(DatabaseProperties.NVD_API_LAST_MODIFIED);
``` 
   location: org.owasp.dependencycheck.data.update.NvdApiDataSource line 302
4. the date is not sanitized to UTC and passed to builder#withLastModifiedFilter, which requires UTC dates
_Use a range of no more than 120 days on the last modified dates to filter the results. The ZonedDateTime objects must be set to UTC._
5. I suggest to add at line 309 the following code:
```java
        	lastModifiedRequest=lastModifiedRequest.withZoneSameInstant( ZoneId.of("UTC") );

```

If that's ok with you I can work on a PR

**Comment by jeremylong** [comment]
12.0.0 will be published in the next couple of days. I just need to do some testing on the report updates.
