### ISSUE TITLE
[FP]: memcache-asg-java-client incorrectly indentified as memcached

### ISSUE THREAD

**Issue by tobias** [dependency-check/DependencyCheck#7225]
### Package URl

pkg:maven/com.datomic/memcache-asg-java-client@1.1.0.36 

### CPE

cpe:2.3:a:memcached:memcached:1.1.0.36:*:*:*:*:*:*:* 

### ODC Integration

None

### ODC Version

10.0.2

### Description

https://github.com/advisories/GHSA-47qj-rqv2-98f2 is a vulnerability in the memcached server, however it is being matching on a memcached client published by a third party vendor. This is similar to #7207, but with a different CPE.

**Comment by aikebah** [comment]
approved
