### ISSUE TITLE
An error occurred with the .NET AssemblyAnalyzer, is the dotnet 8.0 runtime or sdk installed?

### ISSUE THREAD

**Issue by senindmitriy** [dependency-check/DependencyCheck#7236]
**Describe the bug**
By scanning .net of the project I get the error:
`[ERROR] An error occurred with the .NET AssemblyAnalyzer, is the dotnet 8.0 runtime or sdk installed?`
The project is built on .NET 6.0
.NET 6 is installed, the --dotnet parameter specifying the path did not help.

In the old version ODC 8.3.1, there was no such problem using the analyzer.NET Assembly

**Version of dependency-check used**
The problem occurs using version 10.0.4

**Log file**
```
[INFO] Analysis Complete (16 seconds)
[INFO] Writing HTML report to: Z:\gitlab-runner\builds\tWZLEjHWQ\0\test.html
[ERROR] An error occurred with the .NET AssemblyAnalyzer, is the dotnet 8.0 runtime or sdk installed?
```

**Comment by jeremylong** [comment]
You can still analyze .NET 6 assemblies - you just need the .NET 8 runtime to do so.

**Comment by jeremylong** [comment]
dotnet 6 is EOL. As such, we upgraded to requiring dotnet 8. See https://github.com/dotnet/core/blob/main/release-notes/6.0/README.md

**Comment by senindmitriy** [comment]
> dotnet 6 is EOL. As such, we upgraded to requiring dotnet 8. See https://github.com/dotnet/core/blob/main/release-notes/6.0/README.md

Is there an alternative option?
If I install .NET 8 then it will break my build. Yes, this is a strange behavior, I have a fixed version in the project on .NET6, however, I have not solved this problem yet.

**Comment by jeremylong** [comment]
You can have multiple versions of dotnet installed.

**Comment by senindmitriy** [comment]
Yes, the problem is solved, thank you!
