### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError on org.owasp.dependencycheck.utils.Downloader.getInstance()

### ISSUE THREAD

**Issue by AlexAndrascu** [dependency-check/DependencyCheck#7240]
**Describe the bug**

We're encountering the following `Exception` every time the NVD update is performed:

```
Exception in thread "main" java.lang.NoSuchMethodError: 'org.owasp.dependencycheck.utils.Downloader org.owasp.dependencycheck.utils.Downloader.getInstance()'

at org.owasp.dependencycheck.App.run(App.java:167)
at org.owasp.dependencycheck.App.main(App.java:90)
```
the dependency checker fails immediately after. 

**Version of dependency-check used**
The problem occurs using version 11.1.0 of the maven plugin.

**Log file**
-

**To Reproduce**
-

**Expected behavior**
No exception

**Additional context**
-

**Comment by chadlwilson** [comment]
Do you have a simple POM that reproduces this? Likely a clash in dependencies somehow, but unusual that the error is for an ODC utils class.

**Comment by jeremylong** [comment]
Can you provide: `mvn dependency:resolve-plugins`?

**Comment by AlexAndrascu** [comment]
Never mind this. I think this was an internal issue after all. I'll reopen with further details if needed.

Thank you both for your prompt replies!
