### ISSUE TITLE
SSL Error - PKIX path building failed

### ISSUE THREAD

**Issue by kgoudped** [dependency-check/DependencyCheck#728]
hello jeremy .. i installed sonar-dependency-check plugin on sonarqube and i configured pom.xml with maven plugin
```xml
 <reporting>
                           <plugins>
                               <plugin>
                                     <groupId>org.owasp</groupId>
                                     <artifactId>dependency-check-maven</artifactId>
                                      <version>1.4.5</version>
                                 </plugin>
                               </plugins>
                     </reporting>
```
and when i run the build it gives me below error

```
11-May-2017 02:18:04	[ERROR] IO Exception: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
11-May-2017 02:18:05	[ERROR] IO Exception: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
11-May-2017 02:18:05	[WARNING] Unable to download the NVD CVE data; the results may not include the most recent CPE/CVEs from the NVD.
11-May-2017 02:18:05	[INFO] If you are behind a proxy you may need to configure dependency-check to use the proxy.
```

i added env variables as `JAVA_TOOL_OPTIONS="-Djavax.net.ssl.trustStore="/usr/lib/jvm/java-1.8.0/jre/lib/security/cacerts"` and additional parameters as `-Ddownloader.quick.query.timestamp=false`
and nothing worked.
 
[MONGO-AA-JOB1-62.txt](https://github.com/jeremylong/DependencyCheck/files/992017/MONGO-AA-JOB1-62.txt)

**Comment by jeremylong** [comment]
My initial guess based on the log file is that the cacerts file you are using does not contain a necessary cert. In googling your error message I found this article with a simple Java class one could use to diagnose this problem: https://confluence.atlassian.com/kb/unable-to-connect-to-ssl-services-due-to-pkix-path-building-failed-779355358.html

**Comment by jeremylong** [comment]
When investigating a different issue I found the same issue. This revolves around not have the correct cert in your keystore.  See the [Install Cert](https://github.com/jeremylong/InstallCert) example, which is a clone of a previously documented solution.
