### ISSUE TITLE
Tons of checkXXXXXtmp folders under /tmp

### ISSUE THREAD

**Issue by hgomez** [dependency-check/DependencyCheck#73]
I noticed tons of checkXXXXXtmp (XXXX is timestamp) under /tmp dir after nightly scan of our projects.

It seems ArchiveAnalyzer and JarAnalyzer housekeeping didn't works as expected.

**Comment by hgomez** [comment]
I saw temp directory removal in close method, wondering if it's called ?

**Comment by jeremylong** [comment]
With what you are seeing, are the temp directories empty?

**Comment by hgomez** [comment]
Nope, there is contents relative to binaries analyzed by DC

**Comment by jeremylong** [comment]
Okay, in 1.1.2-SNAPSHOT I've updated the deleting on logging of the temporary files. I still need to do some more testing, but the logging should help me figure out what is going on if the update to the delete doesn't fix the issue.

**Comment by hgomez** [comment]
Good. Any date for 1.1.2 ?

**Comment by jeremylong** [comment]
I'm hoping to release 1.1.2 this weekend - although we are still trying to
solve one last bug were on some systems the database structure doesn't get
created.

--Jeremy

**Comment by jeremylong** [comment]
1.1.2 was released.and my testing shows this _should_ be fixed now. I'm closing the issue; if you are still seeing this as an issue after upgrading - please re-open the issue.

Thanks!
