### ISSUE TITLE
Add support for multiple suppression files

### ISSUE THREAD

**Issue by skirge** [dependency-check/DependencyCheck#730]
Please add support for multiple suppression files on command line.
We have a global company suppression file but sometimes we need per project suppression.

**Comment by jeremylong** [comment]
This is a great idea - thanks for the suggestion.

**Comment by pwhittlesea** [comment]
I am thinking of looking into this as we have a similar use case in my office.

It is slightly different in that we are using the Maven plugin so I would look to support that as well.

I have a couple of options on how to implement this in the code but I would appreciate your thoughts before I start.

My preference is **1** as it allows 1..x files however the changes required in the code are more widespread and it would not be backwards compatible to the user (it is also probably the slowest).
**2** solves this issue but may not be 'future-proof' (not that we need to be) with regard to having more than 2 files.
**3** has the least impact but introduces an inconsistent API as this will be the only property with a delimiter (that I know of).

#### Option 1
Allow multiple `suppressionFile`s.
##### Maven
```xml
<plugins>
    <plugin>
        <groupId>org.owasp</groupId>
        <artifactId>dependency-check-maven</artifactId>
        <configuration>
            <suppresionFiles>
                <suppressionFile>parent-check-exclude.xml</suppressionFile>
                <suppressionFile>project-check-exclude.xml</suppressionFile>
            </suppresionFiles>
        </configuration>
    </plugin>
</plugins>
```
##### CLI
```sh
dependency-check.sh \
  --project "My App Name" \
  --scan "/java/application/lib" \
  --suppression "parent-check-exclude.xml" \
  --suppression "project-check-exclude.xml"
```
##### Ant
Needs investigation.
#### Option 2
Add an additional property for an extra file (I'm super open to suggestions on the name of the property).
##### Maven
```xml
<plugins>
    <plugin>
        <groupId>org.owasp</groupId>
        <artifactId>dependency-check-maven</artifactId>
        <configuration>
            <globalSuppressionFile>parent-check-exclude.xml</globalSuppressionFile>
            <suppressionFile>project-check-exclude.xml</suppressionFile>
        </configuration>
    </plugin>
</plugins>
```
##### CLI
```sh
dependency-check.sh \
  --project "My App Name" \
  --scan "/java/application/lib" \
  --globalSuppression "parent-check-exclude.xml" \
  --suppression "project-check-exclude.xml"
```
##### Ant
```xml
<target name="dependency-check" description="Dependency-Check Analysis">
    <dependency-check projectName="Hello World"
                      reportOutputDirectory="${basedir}"
                      reportFormat="ALL"
                      suppressionFile="parent-check-exclude.xml"
                      globalSuppressionFile="project-check-exclude.xml">
        <fileset dir="lib">
            <include name="**/*.jar"/>
        </fileset>
    </dependency-check>
</target>
```
#### Option 3
Allow the `suppressionFile` to have a delimeter which we can split on.
##### Maven
```xml
<plugins>
    <plugin>
        <groupId>org.owasp</groupId>
        <artifactId>dependency-check-maven</artifactId>
        <configuration>
            <suppressionFile>parent-check-exclude.xml|project-check-exclude.xml</suppressionFile>
        </configuration>
    </plugin>
</plugins>
```
##### CLI
```sh
dependency-check.sh \
  --project "My App Name" \
  --scan "/java/application/lib" \
  --suppression "parent-check-exclude.xml|project-check-exclude.xml"
```
##### Ant
```xml
<target name="dependency-check" description="Dependency-Check Analysis">
    <dependency-check projectName="Hello World"
                      reportOutputDirectory="${basedir}"
                      reportFormat="ALL"
                      suppressionFile="parent-check-exclude.xml|project-check-exclude.xml">
        <fileset dir="lib">
            <include name="**/*.jar"/>
        </fileset>
    </dependency-check>
</target>
```

Has either of you had any thoughts on what you would want the API to look like (@jeremylong @skirge)?

**Comment by stevespringett** [comment]
IMO, I prefer option 1 followed by option 3. I would not recommend option 2.

What would occur in the event of conflicts? Which rule wins? Are they processed in order they are specified?

**Comment by pwhittlesea** [comment]
> What would occur in the event of conflicts? Which rule wins? Are they processed in order they are specified?

Is it possible for suppressions to conflict? If there are two files that happen to suppress the same CVE on a dependency, in different ways, don't you end in the same final state? With the CVE suppressed?

Admittedly I have only spent a few hours looking though the code.

**Comment by jeremylong** [comment]
Option 1 is the best.

**Comment by fuyili** [comment]
is this feature available for Jenkins plugin? @jeremylong

**Comment by stevespringett** [comment]
The Jenkins plugin (publisher step) will honor the suppressions made in the CLI or build plugins, but the Jenkins plugin does not yet implement multiple suppression files.

While the CLI, build plugins all have the option to support both the old way (single suppression) and new way (multiple suppressions), the Jenkins plugin has to support only the new way and do so in a fashion that does not break the configuration for existing jobs for the thousands of orgs currently using it. Doing so is a non-starter. I haven't had a chance to investigate to see if this is possible or what kinds of workarounds are necessary to allow both. PR's are always welcome, as i likely will not have an opportunity to implement this any time soon.
