### ISSUE TITLE
Import Non-Application CVEs

### ISSUE THREAD

**Issue by jeremylong** [dependency-check/DependencyCheck#733]
Currently, a property exists (`cve.cpe.startswith.filter`) that controls the CPEs imported. However, this is not used in the CVE Importer so the property is not functioning as expected.

Enhance the NVD CVE Importer to utilize the starts with filter.

**Comment by v6ak** [comment]
You have filled this bug shortly after I was playing with debugger. When updating, it did not hit CPEHandler line `Settings.getString(Settings.KEYS.CVE_CPE_STARTS_WITH_FILTER, "cpe:/a:")` (maybe it would hit it later, maybe it would never hit it at all), but there is a hardcoded prefix in classes NvdCve12Handler and NvdCve20Handler. I'll try to replace it. Are you aware about any other place?

**Comment by v6ak** [comment]
So, replacing in NvdCve20Handler is rather straightforward. In NvdCve12Handler, it seems to be somehow hardcoded and I don't think I fully understand the code. It seems that CVE 1.2 and CVE 2.0 are processed, but the following two comments from NvdCve12Handler look like a mutual contradiction for me:

> * CPEs that have previous versions specified. The previous version information is not in the 2.0 version of the schema
> * and is useful to ensure accurate identification (or at least complete).


>                /*yes yes, this may not actually be an "a" - it could be an OS, etc. but for our
>                 purposes this is good enough as we won't use this if we don't find a corresponding "a"
>                 in the nvd cve 2.0. */

**Comment by jeremylong** [comment]
The issue is that the NVD CVE 1.2 does not actually specify whether the software is an OS, Hardware, or Application. The CVE 1.2 handler defaulted to making everything an application - because the only thing that was used from the data feed was whether or not "all previous versions" were affected. This flag was not present in the 2.0 schema.  So ODC brings in both data feeds, made everything from the 1.2 format an "a" and then we cycle through the software identified in the 2.0 schema, compare the CPEs, and mark the "all previous version" flag if they match.  It was hard-coded in the 1.2 handler because at the time of writing it the 2.0 handler only imported application CPEs.

The best thing to do might be to hold off fixing this in the XML parsers and wait the month or so until we build a JSON parser for the new data feeds available. See issue #707.

**Comment by v6ak** [comment]
OK, it makes sense to wait rather to further hack with getting two such XMLs together.

**Comment by jeremylong** [comment]
This should be resolved with the 5.0.0-M1.
