### ISSUE TITLE
Getting NoSuchMethod exception

### ISSUE THREAD

**Issue by nimeshkb** [dependency-check/DependencyCheck#736]
I am getting NoSuchMethod exception(for org.owasp.dependencycheck.utils.Settings.setStringIfNotEmpty method) when I am trying to run dependency check for my project, build script below . I have verified that this method  exists and is also available inside the Utils jar 
![error](https://cloud.githubusercontent.com/assets/8285931/26150179/8a801988-3afd-11e7-8052-641f924f1672.png)

Could you please check this and provide details to resolve this.

Thanks in advance.

##
<project name="dependency-check" default="dependency-check" >

<property name="dependency-check.home" value="C:\QA\iSOM\Dependancy\ANT_POC\dependency-check-ant-1.4.4-release\dependency-check-ant"/>
<path id="dependency-check.path">
   <pathelement location="${dependency-check.home}/dependency-check-ant.jar"/>
    <fileset dir="${dependency-check.home}/lib">
        <include name="*.jar"/>
    </fileset>
</path>

<target name="dependency-check" description="Dependency-Check Analysis">
    <dependency-check projectname="Hello World"
                      reportoutputdirectory="D:/Sterling/Sterling93_Jars/temp"
                      reportformat="ALL">
 
        <fileset dir="D:/Sterling/Sterling93_Jars">
            <include name="**/*.jar"/>
        </fileset>
    </dependency-check>
</target>
</project>
###

**Comment by jeremylong** [comment]
It appears you are using the ODC-ant 1.4.0?  Please see if you still have
this issue with 1.4.5.

**Comment by nimeshkb** [comment]
Thanks for the quick response.

I am getting same error with 1.4.5 also :( 
![image](https://cloud.githubusercontent.com/assets/8285931/26151079/7afeb8d0-3b01-11e7-9667-b8c22afca4e9.png)

**Comment by jeremylong** [comment]
Any  chance you have an old copy of dependency-check-ant on the classpath? Possibly even in the ant/lib directory?
