### ISSUE TITLE
A required class was missing while executing org.owasp:dependency-check-maven:1.4.5:check: org/joda/time/ReadableInstant

### ISSUE THREAD

**Issue by asicfr** [dependency-check/DependencyCheck#737]
Using dependency-check-maven:1.4.5, when i launch mvn dependency-check:check i got an exception : 
A required class was missing while executing org.owasp:dependency-check-maven:1.4.5:check: org/joda/time/ReadableInstant

### Reporting Bugs/Errors
https://gist.github.com/asicfr/6384a069ab589294a349403cc27e9db7

Thx

**Comment by jeremylong** [comment]
Editing previous reply (as I had replied to the wrong thread). Any chance you could supply the POM?

**Comment by asicfr** [comment]
My test pom.
[pom.txt](https://github.com/jeremylong/DependencyCheck/files/1018794/pom.txt)

**Comment by jeremylong** [comment]
@asicfs I just built the provided pom and did not receive the error: [build-log.txt](https://github.com/jeremylong/DependencyCheck/files/1034125/build-log.txt) - this was with 3.3.9 and Java 8.  You can also see a travis-ci build showing a (successful build](https://travis-ci.org/jeremylong/DependencyCheck/builds/236869020#L3969) using Java 7.

What version of Maven and Java are you using? Can you think of anything else unique about your environment?

**Comment by asicfr** [comment]
I use Apache Maven 3.3.9 and Java 1.8.0_131.

**Comment by jeremylong** [comment]
That is the same configuration used to create the above build-log.txt. Maybe clear your local m2 repo of anything joda-time related (`~/.m2/repository/joda-time/joda-time`)? I'm at a loss as I am unable to reproduce this issue.

**Comment by dovydascc** [comment]
Had the same issue. Deleting ~/.m2/repository/joda-time fixed this.

**Comment by jeremylong** [comment]
The only use of `joda.time` is in the OSS Index Analyzer. I have opened an issue (https://github.com/sonatype/ossindex-public/issues/8) to have them convert from `joda.time` to `java.time`.
