### ISSUE TITLE
Windows defender malware alert

### ISSUE THREAD

**Issue by aureFeliu** [dependency-check/DependencyCheck#748]
Hello Jeremy, I´m trying to download DependencyCheck from OWASP's site (https://www.owasp.org/index.php/OWASP_Dependency_Check) but I am getting an error message from Windows Defender saying that malware was found on the file and the file is then deleted. This happens on Windows 10, but not on Windows 7. Do you know why this might be happening? 
Here are the analysis results for the command line and the ant task downloads: https://www.virustotal.com/es/file/129323b238c372b156c0c315d0b365518025765f3c0855f0ec6ac385f91b91be/analysis/1495710693/
https://www.virustotal.com/es/file/b7cfcecf9a7f327969bb6ff398f2caa5180e0b7ab71044bbf9fc945248c40152/analysis/1495711077/

Regards
Aurelio

**Comment by jeremylong** [comment]
Thanks for reporting this- researching now.

**Comment by aureFeliu** [comment]
Hi Jeremy, thanks for answering and looking into it. I have tried downloading version 1.4 from bintray's archive and I am having the same problem. 

Regards

**Comment by jeremylong** [comment]
Windows defender is blocking this because of the contained GrokAssembly.exe. I have submitted a ticket to MS indicating I believe this to be a false positive - I'll update the ticket when I know more.

**Comment by jeremylong** [comment]
The 2.0.0-SNAPSHOT of the CLI can be downloaded from dependency-check's [CI workspace](https://dependency-check.ci.cloudbees.com/job/dependency-check/ws/dependency-check-cli/target/). This is stable and contains a ton of improvements that I'm hoping to release soon.

**Comment by jeremylong** [comment]
If you update your malware definitions in the Windows Defender Security Center as of Sunday, 5/28/2017 OWASP dependency-check's download from bintray is no longer blocked or detected as malware. I've tested 1.4.4 and 1.4.5.

**Comment by aureFeliu** [comment]
Great! Just tested it and downloaded without any problems. 
Thank you for the quick response
