### ISSUE TITLE
dependency-check command line tool fails when there is no space /tmp/

### ISSUE THREAD

**Issue by vinod272** [dependency-check/DependencyCheck#749]
dependency-check command line tool fails when there is no space /tmp/
an option to change the /tmp location will be  very useful

**Comment by mprins** [comment]
the jvm provides that already eg. `java -Djava.io.tmpdir=/path/to/tmpdir yourcommand` as well as siply setting the tmp environment variable to the richt location

**Comment by vinod272** [comment]
Ok, thank you

-Vinod

**Comment by jeremylong** [comment]
Another option would be to create a properties file containing:

temp.directory=/path/to/temp

and then call

./dependency-check.sh -P path/to/my.properties
