### ISSUE TITLE
Analysis hangs at "INFO: Extracted GrokAssembly.exe to /tmp/GKA8373919150344041065.exe"

### ISSUE THREAD

**Issue by backslash-f** [dependency-check/DependencyCheck#75]
Hi,

I may be missing something. Please advise.
1. Clone https://github.com/jeremylong/DependencyCheck.git
2. cd DependencyCheck / mvn install [ok]
3. dependency-check.sh -u MYPROXY -p 8080 -f ALL -a MYSTUFF -s MYSTUFF -o MYSTUFF

The console hangs showing me this:
Feb 20, 2014 3:16:22 PM org.owasp.dependencycheck.Engine analyzeDependencies
INFO: Analysis Starting
Feb 20, 2014 3:16:22 PM org.owasp.dependencycheck.analyzer.AssemblyAnalyzer initialize
INFO: Extracted GrokAssembly.exe to /tmp/GKA6711291815386601568.exe

Am I doing this right? This is what I have in /etc/environment:

PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/home/brbuild/DependencyCheck/dependency-check-cli/target/release/bin:/usr/lib/mono"

MONO_PATH="/usr/lib/mono"

(Notice that I can execute "mono" in the console)

Thanks,
- Fernando

**Comment by jeremylong** [comment]
Sorry for the delayed response. Can you re-run this with '--log dc.log' and post the log file to help us debug what is going on?

Thanks,

Jeremy

**Comment by colezlaw** [comment]
What OS and JRE version do you have as well? Need to see if I can duplicate this.

**Comment by backslash-f** [comment]
Hey! It's ok, thanks for taking a look. 

Mm, good stuff on the '--log dc.log'.

So I restarted the job like two hours ago with that flag and it is still running. (Just to mention, I did a git pull today).

I also append a "&" at the end of the command, so we can observe the log file.
In it, I notice the following:

Feb 24, 2014 7:39:57 AM org.owasp.dependencycheck.data.nvdcve.ConnectionFactory initialize
FINE: Loading driver: org.h2.Driver
Feb 24, 2014 7:39:58 AM org.owasp.dependencycheck.utils.Settings getDataFile
FINE: Settings.getDataFile() - file: '/home/brbuild/DependencyCheck/dependency-check-cli/target/release/data'
Feb 24, 2014 7:39:58 AM org.owasp.dependencycheck.data.nvdcve.ConnectionFactory getConnectionString
FINE: File path for H2 file: '/home/brbuild/DependencyCheck/dependency-check-cli/target/release/data/cve.2.9'
Feb 24, 2014 7:39:58 AM org.owasp.dependencycheck.utils.Settings getDataFile
FINE: Settings.getDataFile() - file: '/home/brbuild/DependencyCheck/dependency-check-cli/target/release/data'
Feb 24, 2014 7:39:58 AM org.owasp.dependencycheck.data.nvdcve.ConnectionFactory initialize
FINE: Need to create DB Structure: false
Feb 24, 2014 7:39:58 AM org.owasp.dependencycheck.data.nvdcve.ConnectionFactory initialize
FINE: Loading database connection
Feb 24, 2014 7:39:58 AM org.owasp.dependencycheck.data.nvdcve.ConnectionFactory initialize
FINE: Connection String: jdbc:h2:file:/home/brbuild/DependencyCheck/dependency-check-cli/target/release/data/cve.2.9;AUTO_SERVER=TRUE;AUTOCOMMIT=ON;
Feb 24, 2014 7:39:58 AM org.owasp.dependencycheck.data.nvdcve.ConnectionFactory initialize
FINE: Database User: dcuser
Feb 24, 2014 7:57:57 AM org.owasp.dependencycheck.Engine analyzeDependencies
FINE:
BEGIN ANALYSIS

[...] // loads of info

// Issue
Feb 24, 2014 7:58:03 AM org.owasp.dependencycheck.data.nexus.NexusSearch searchSha1
FINE: Searching Nexus url http://repository.sonatype.org/service/local/identify/sha1/16313e02a793435009f1e458fa4af5d879f6fb11
Feb 24, 2014 7:59:06 AM org.owasp.dependencycheck.analyzer.NexusAnalyzer analyze
FINE: Could not connect to nexus repository
java.net.ConnectException: Connection timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:579)
        at java.net.Socket.connect(Socket.java:528)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
        at sun.net.www.http.HttpClient.New(HttpClient.java:308)
        at sun.net.www.http.HttpClient.New(HttpClient.java:326)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:996)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:932)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:850)
        at org.owasp.dependencycheck.data.nexus.NexusSearch.searchSha1(NexusSearch.java:82)
        at org.owasp.dependencycheck.analyzer.NexusAnalyzer.analyze(NexusAnalyzer.java:161)
        at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:333)
        at org.owasp.dependencycheck.App.runScan(App.java:109)
        at org.owasp.dependencycheck.App.run(App.java:86)
        at org.owasp.dependencycheck.App.main(App.java:56)

There are loads of entries like that (Could not connect to nexus repository).
Below is the latest one:

Feb 24, 2014 9:54:44 AM org.owasp.dependencycheck.analyzer.NexusAnalyzer analyze
FINE: Could not connect to nexus repository
java.net.ConnectException: Connection timed out
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:579)
    at java.net.Socket.connect(Socket.java:528)
    at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
    at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
    at sun.net.www.http.HttpClient.New(HttpClient.java:308)
    at sun.net.www.http.HttpClient.New(HttpClient.java:326)
    at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:996)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:932)
    at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:850)
    at org.owasp.dependencycheck.data.nexus.NexusSearch.searchSha1(NexusSearch.java:82)
    at org.owasp.dependencycheck.analyzer.NexusAnalyzer.analyze(NexusAnalyzer.java:161)
    at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:333)
    at org.owasp.dependencycheck.App.runScan(App.java:109)
    at org.owasp.dependencycheck.App.run(App.java:86)
    at org.owasp.dependencycheck.App.main(App.java:56)

(Observe the time on both entries -- it's running like forever... :D (That gave me the impression that it hung)).

Could this be a network issue? But I can ping anything and apt-get update / upgrade, for instance... (just brainstorming)

Regarding my OS version: this is a Ubuntu machine x64 12.10

Java stuff:
java version "1.7.0_51"
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode) ]

Let me know if you need more info or the entire log (it is still "running", tho).

Thanks,
- Fernando

**Comment by colezlaw** [comment]
Aha - now we're getting somewhere. Unfortunately, the Nexus analyzer right now doesn't use the proxy, so you'll need to set analyzer.nexus.enabled=false in your dependencycheck.properties, or point analyzer.nexus.url at an internal Nexus repository.

I'll work on some debugging there and make the Nexus analyzer do a "test run" first and then decide to disable itself. That shouldn't take too long, then need to add the proxy support to it.

**Comment by jeremylong** [comment]
Ah.. I have a thought.

Will - does the NexusAnalyzer use the proxy/port as the downloader?  If
not, this may be the issue...  Let me know and I can update it if necessary.

--Jeremy

**Comment by backslash-f** [comment]
Great, we are making progress.

I think I'll redirect to an internal Nexus server, then.

Which, exactly, is(are) the file I need to edit?

/DependencyCheck$ find . -name dependencycheck.properties
./dependency-check-core/target/classes/dependencycheck.properties
./dependency-check-core/target/test-classes/dependencycheck.properties
./dependency-check-core/src/test/resources/dependencycheck.properties
./dependency-check-core/src/main/resources/dependencycheck.properties

Thanks!
- Fernando

**Comment by colezlaw** [comment]
Jeremy - right. The problem is that it doesn't use the proxy. I've got on my to do list to refactor the existing http connection stuff, but also want to handle internal repos where you shouldn't use a proxy correctly.

**Comment by colezlaw** [comment]
Fernando - the one in `target/classes`

**Comment by colezlaw** [comment]
@jeremylong @Conaaando I've created a pull request which will resolve this and another open question we had. It will use the proxy if the user has configured it but hasn't changed the Nexus settings. If they change the Nexus settings and want to skip the proxy, there's a property for that as well.

That also adds a preflight request which will disable the analyzer if the preflight request fails. So in @Conaaando's case, if the proxy wasn't responding or Central wasn't responding or something, it would skip attempting to make further requests because the first failed. (Actually, in the documented circumstance, everything should "just work" because the proxy is configured.)

**Comment by backslash-f** [comment]
Looks promising! I pulled your pull request #76 [locally](https://help.github.com/articles/checking-out-pull-requests-locally) and I'm about to trigger another analysis using it. Will post an update soon.

Thanks,
- Fernando

**Comment by backslash-f** [comment]
Unfortunately it stills throws 'could not connect' at me:

Feb 25, 2014 4:38:49 AM org.owasp.dependencycheck.data.nexus.NexusSearch searchSha1
FINE: Searching Nexus url http://repository.sonatype.org/service/local/identify/sha1/7200de14823ec2a27aed8240870d4054535d4b1b
FINE: Could not connect to nexus repository
java.net.ConnectException: Connection timed out
    at java.net.PlainSocketImpl.socketConnect(Native Method)

This was with pull request #76 and this is what I have in the .properties file:

cat /home/brbuild/DependencyCheck/dependency-check-core/target/classes/dependencycheck.properties

application.name=Dependency-Check Core
application.version=1.1.2-SNAPSHOT
autoupdate=true
max.download.threads=3

temp.directory defaults to System.getProperty("java.io.tmpdir")
temp.directory=[path to temp directory]

.# the path to the data directory; the [JAR] signifies to use the relative path
.# to the dependency-check-core JAR file. This path is only used to construct
.# the connection string for the H2 driver (or other drivers that require a file path.
.# to be supplied. If you are using another database (MySQL, Oracle, etc.) this property
.# will not be used. The data.directory will be resolved and if the connection string
.# below contains a %s then the data.directory will replace the %s.
data.directory=[JAR]/data
data.connection_string=jdbc:h2:file:%s;AUTO_SERVER=TRUE;AUTOCOMMIT=ON;
.#data.connection_string=jdbc:mysql://localhost:3306/dependencycheck
.# user name and password for the database connection. The inherent case is to use H2.
.# As such, this unsecure username/password exist.
data.user=dcuser
data.password=DC-Pass1337!
.# The following are only used if the DB Driver is not JDBC4 compliant and/or the driver
.# is not in the current classpath. Setting these properties will add the give path(s) to
.# the class loader and then register the driver with the DriverManager. If the class is
.# not in the path you must specify both the driver name (aka the fully qualified driver name)
.# and the driver path. The driver path can be a semi-colon separated list of files/directories
.# to ensure any and all needed files can be added to the classpath to load the driver.
.# For non-JDBC4 drivers in the classpath only the driver_name needs to be set.
.# For MOST situations these properties likely do not need to be set.
data.driver_name=org.h2.Driver
data.driver_path=

.# the number of days that the modified nvd cve data holds data for. We don't need
.# to update the other files if we are within this timespan. Per NIST this file
.# holds 8 days of updates, we are using 7 just to be safe.
cve.url.modified.validfordays=7

.# the path to the modified nvd cve xml file.
cve.url-1.2.modified=http://nvd.nist.gov/download/nvdcve-modified.xml
cve.url-2.0.modified=http://static.nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-modified.xml
cve.startyear=2002
cve.url-2.0.base=http://static.nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-%d.xml
cve.url-1.2.base=http://nvd.nist.gov/download/nvdcve-%d.xml

.# the URL for searching Nexus for SHA-1 hashes and whether it's enabled
analyzer.nexus.enabled=true
analyzer.nexus.url=http://repository.sonatype.org/service/local/
.# If set to true, the proxy will still ONLY be used if the proxy properties (proxy.url, proxy.port)
.# are configured
analyzer.nexus.proxy=true

proxy.url=MY-PROXY-IP
proxy.port=8080

I also tried without setting proxy.url and proxy.port and analyzer.nexus.proxy=false, but the error is the same.

Ah, I also tried to set analyzer.nexus.enabled to false. Same error. O.o

Is my dependencycheck.properties being considered at all? :D

**Comment by colezlaw** [comment]
Sorry - there are a few ways to work around this.

If you're running the CLI straight out of the build from github, you'll need to make `dependency-check-cli/target/release/etc` and then copy the `dependencycheck.properties` to there and modify that one (it uses the one first on the classpath).

_or_

You can specify which properties file to use with the `-p` option on the command-line.

_or_

You can set the environment variable `JAVA_OPTS` to include whatever properties you want to override. For example:

``` bash
JAVA_OPTS="-Dproxy.url=localhost -Dproxy.port=8080" bin/dependency-check.sh ...
```

Unfortunately, I've got some sort of a problem where it's not loading the DB schema, so I'm having a hard time making sure that's 100% accurate.

**Comment by backslash-f** [comment]
Yes, I'm using the CLI from github (clone / pull / mvn install in root).

I started with JAVA_OPTS but unfortunately that did not work. I specify the arguments like in your example and I also put it in /etc/environment.

-p option is a no go too. Assuming that I'm using it right:

dependency-check.sh -p /home/brbuild/DependencyCheck/dependency-check-core/target/classes/dependencycheck.properties  -u MYPROXY -p 8080 -f ALL -a MYSTUFF -s MYSTUFF -o MYSTUFF  --log dc.log&

I think I'll try the first option, then...

**Comment by backslash-f** [comment]
(Just to make it clear, from the dc.log, the error is the same):

FINE: Searching Nexus url http://repository.sonatype.org/service/local/identify/sha1/8493982bba1727106d767034bd0d8e77bc1931a9
Feb 25, 2014 12:42:09 PM org.owasp.dependencycheck.analyzer.NexusAnalyzer analyze
FINE: Could not connect to nexus repository
java.net.ConnectException: Connection timed out

**Comment by colezlaw** [comment]
I'm not convinced that that's the newest code. The first thing you'd see is
that the preflight request failed and that it was disabling the
NexusAnalyzer. Should say something like:

There was an issue getting Nexus status. Disabling analyzer.

**Comment by backslash-f** [comment]
All right. I'll cleanup this environment and start from scratch.

**Comment by jeremylong** [comment]
Any luck? Can this issue be closed?

**Comment by backslash-f** [comment]
Hey man! Sorry, I've been busy with other issues. The server that I previously mentioned is located in my workplace. Since it's Carnival holiday here in Brazil, I won't have access to it till Thursday. But based on @colezlaw answers / pull request, I believe you could close this issue. My environment seems to be too dirty at this point to serve as reference. :-D Thanks!

**Comment by colezlaw** [comment]
FWIW, I tested this on a corporate network where external access requires
an authenticated proxy and it behaved as expected:
- proxy info set, it "just works"
- no proxy info set, it fails early and disables the Nexus analyzer
- no proxy set, and internal  repository works.
- proxy set, and internal Nexus repo works when setting
  JAVA_OPTS="-Danalyzer.nexus.proxy=false"

None of these required any changes to dependencycheck.properties.

**Comment by jeremylong** [comment]
I just added the configuration of whether or not the nexus analyzer should use the configured proxy. I am closing this issue.
