### ISSUE TITLE
"Error resolving X in project Y" for dependencies without analyzer

### ISSUE THREAD

**Issue by ercpe** [dependency-check/DependencyCheck#754]
Our parent POM references a dependency with a `type` that doesn't have a matching analyzer (a `properties` file in this `case):

```xml
<dependencies>
    <dependency>
        <groupId>foo.bar</groupId>
        <artifactId>third-party-licenses</artifactId>
        <type>license.properties</type>
        <version>[1.0-SNAPSHOT,)</version>
    </dependency>
</dependencies>
```
The dependency-check maven plugin now complains that it cannot resolve the dependency:
`[ERROR] Error resolving 'foo.bar:third-party-licenses:license.properties:1.0-SNAPSHOT' in project X`. Otherwise its working just fine.

Now i'm wondering: Is it safe to exclude artifacts in `BaseDependencyCheckMojo.excludeFromScan` not only by scope but by type too? And does it warrant a configuration option to allow users to exclude artifacts by type?

**Comment by jeremylong** [comment]
Yes, an exclude by type should be included. When this is implemented we should use a regex to match the type.

**Comment by ercpe** [comment]
What's the timeline for the release?

**Comment by jeremylong** [comment]
Soon - I've been upgrading the ODC-gradle plugin (nearly done) and then I should be pushing the 2.0.0 release.
