### ISSUE TITLE
SHA-256 mismatch for dependency-check-1.4.5-release.zip

### ISSUE THREAD

**Issue by ilovezfs** [dependency-check/DependencyCheck#758]
@jeremylong Homebrew users currently cannot install dependency-check due to a SHA-256 checksum mismatch for dependency-check-1.4.5-release.zip.

Jan 22 17:36:47 2017 the checksum was
129323b238c372b156c0c315d0b365518025765f3c0855f0ec6ac385f91b91be

Now it appears to be
5ba6934ef5ccefb47b1984448704f86133840b4bb7aaa463ff46dbccdf196dba

Have you been hacked? We'll need to understand why the file has changed before the checksum can be updated in Homebrew. Thanks!

**Comment by jeremylong** [comment]
No, we were not hacked. Windows Defender was flagging OWASP dependency-check (incorrectly) as malware (see issue #748). In part of my efforts to understand the problem I rebuilt the tagged version (1.4.5) on a clean Ubuntu box and re-uploaded it to bintray - without realizing the downstream consequences to the brew install. No virus was contained in the original or newly uploaded version - I contacted the Windows Defender Support and the virus definitions were updated shortly thereafter.
