### ISSUE TITLE
Allow dependency check to be run on bootclasspath

### ISSUE THREAD

**Issue by anderruiz** [dependency-check/DependencyCheck#761]
The current dependency check version does not if it is loaded on bootclasspath because it relies on the current classloader of many classes to retrieve files. In this case NPE are thrown as the classloader is null. Those solve it, this method should be used:

```java
ClassLoader.getSystemResourceAsStream("resource");
```

I'm submitting a PR to fix this. I will include a minor trace fix in DownloadTask also.

Additionally I did some changes (that I'm not including in the PR for now) to allow dependency check to be used with JDK6 while using JDK7 syntax using retrolambda and animal-sniffer maven plugins. JDK6 compatibility can be kept only changing two classes. If you are interested in the patch let me know.

**Comment by jeremylong** [comment]
Thanks for the PR!  Regarding the Java 6 comparability - I have no interest in supporting Java 6 (heck, I don't want to support Java 7).  If you are still running Java 6 you are part of the problem that this project is trying to highlight.  *Upgrade*

A release is nearly ready - so this should be published soon.
