### ISSUE TITLE
where to download the cve data

### ISSUE THREAD

**Issue by JoyChou93** [dependency-check/DependencyCheck#763]
where to download the cve data in your code.

**Comment by jeremylong** [comment]
The NVD data download starts with the [NvdCveUpdater](https://github.com/jeremylong/DependencyCheck/blob/master/dependency-check-core/src/main/java/org/owasp/dependencycheck/data/update/NvdCveUpdater.java).

**Comment by JoyChou93** [comment]
And how to know if the NVD CVE data is updated ?

**Comment by jeremylong** [comment]
As I stated before - all of this is in the [NvdCveUpdater](https://github.com/jeremylong/DependencyCheck/blob/master/dependency-check-core/src/main/java/org/owasp/dependencycheck/data/update/NvdCveUpdater.java).
