### ISSUE TITLE
DependencyCheck compatible with Jenkins pipelines

### ISSUE THREAD

**Issue by javixeneize** [dependency-check/DependencyCheck#768]
Hi

At the moment i am using dependency check as a step in a jenkins job, but i am planning to move to jenkins pipelines (it is, building all the jobs in a jenkinsfile)

Is this plugin compatible with this? Is there any documentation for this?

Thanks

**Comment by stevespringett** [comment]
Refer to https://issues.jenkins-ci.org/browse/JENKINS-37437
