### ISSUE TITLE
Analyse issues with Oracle.ManagedDataAccessIOP.dll

### ISSUE THREAD

**Issue by AnthonyDasse** [dependency-check/DependencyCheck#771]
Hello, 
I use version dependency-check-1.4.5.
When I run an analysis on my DLL I have a problem with the DLL (and only with this DLL).

See error with dependencyCheck command line tool :

[WARN] Return code 5 from GrokAssembly
[WARN] An error occurred while analyzing 'D:\wwwroot\myproject\REFERASSEMBLY\Oracle.ManagedDataAccess.12.1.2400\bin\x86\Oracle.ManagedDataAccessIOP.dll' (Assembly Analyzer).

Regards.

**Comment by jeremylong** [comment]
The source code for GrokAssembly can be found [here](https://github.com/jeremylong/GrokAssembly/blob/master/GrokAssembly/Program.cs).  Error code 5 is from a very broad catch...  Any chance that DLL is available for download to non-Oracle clients?

**Comment by AnthonyDasse** [comment]
No, It's only for Oracle.
The issue come from GrokAssembly ?

**Comment by jeremylong** [comment]
Yes, the GrokAssembly is .NET code that extracts information from the DLLs that is then used by dependnency-check for library identification. If the GrokAssembly fails to extract information an error code will be returned to dependency-check that results in some cases with an exception.

**Comment by AnthonyDasse** [comment]
In fact, I tested with Grokassemby and I have the bug.
I close this bug and I open it on Grokassembly?

**Comment by jeremylong** [comment]
@Thorada - yes, please open the bug against GrokAssembly.  Any chance you would be able to debug the analysis and assist us in figuring out what needs to be updated as we don't have access to the failing DLL?

**Comment by AnthonyDasse** [comment]
Ok @jeremylong . Yes, i can debug GrokAssembly to help you.

**Comment by jeremylong** [comment]
@Thorada thanks! let us know if there is anything we can do to help.

**Comment by jeremylong** [comment]
This may be related to a report on the [ODC mailing list](https://groups.google.com/forum/#!topic/dependency-check/Axlwi5MOaJE).

**Comment by jeremylong** [comment]
GrokAssembly has been updated since this ticket was opened. If this issue persists please open a new ticket.
