### ISSUE TITLE
Queries in NVD Database download script takes too long to finish with Postgres DB

### ISSUE THREAD

**Issue by jazvillagra** [dependency-check/DependencyCheck#772]
I've downloaded the NVD database to a centralized Postgres DB, following these instructions:
1. Create user and database to use on Postgres, making sure remote access is enabled.
2. Connect to DB and run [this script](https://github.com/jeremylong/DependencyCheck/blob/master/dependency-check-core/src/main/resources/data/initialize_postgres.sql)

The first NVD CVE task took approx. 49 minutes. The Query `DELETE FROM cpeEntry WHERE id not in (SELECT CPEEntryId FROM software)` found in [this script](https://github.com/jeremylong/DependencyCheck/blob/master/dependency-check-core/src/main/resources/data/dbStatements_postgreSQL.properties) takes 30 minutes to finish (the subselect is made over a table that contains 1.5+ million rows). 
Plus, the maintenance task took 177 minutes.
The amount of time that takes to finish this process is too much, considering the _h2_ per file download takes about 15 minutes, with the same internet connection.

Is there any way I could reduce the time it takes to finish the download and insert on Postgres DB?

Thanks for your help :smile:

**Comment by jeremylong** [comment]
All of the Postgres database scripts can be found in github [here](https://github.com/jeremylong/DependencyCheck/tree/master/dependency-check-core/src/main/resources/data). I'm guessing there are either indexes that should be created or different ways to perform the same query/update that will work faster on Postgres. However, I am not a database performance tuning guru.
