### ISSUE TITLE
Maven plugin ignores standard directory conventions

### ISSUE THREAD

**Issue by stevespringett** [dependency-check/DependencyCheck#773]
The Maven plugin doesn't seem to support the scanning of directories like the CLI does. This causes problems when using standard Maven conventions like src/main/webapp and src/main/resources where scannable files may reside such as javascript, package.json, and .NET assemblies.

For webapps, scanning the resulting war after the fact is not an option as some of the evidence may have been altered or omitted during assembly (i.e. the minification of javascript or the omission of package.json).

IMO, the Maven plugin should be able to scan all directories defined through standard Maven conventions. Defaults should be provided and enabled by default and overridable through configuration.

**Comment by jeremylong** [comment]
Completely agree. This should be added to the gradle plugin as well.

**Comment by jeremylong** [comment]
When implementing consider using [FileSets](https://maven.apache.org/shared/file-management/fileset.html) to allow control over what is scanned.

**Comment by stevespringett** [comment]
I've added this to the Maven plugin. I'll let someone more familiar with Groovy add it to the Gradle plugin.
