### ISSUE TITLE
Jenkins plugin - Update not working

### ISSUE THREAD

**Issue by javixeneize** [dependency-check/DependencyCheck#778]
Hi

I have noticed that the job i have to update the DB is not working anymore
Building on master in workspace /jenkins/workspace/DepCheckDB
[DependencyCheck] OWASP Dependency-Check Plugin v1.4.5
[DependencyCheck] Executing Dependency-Check with the following options:
[DependencyCheck]  -name = DepCheckDB
[DependencyCheck]  -outputDirectory = /jenkins/workspace/DepCheckDB
[DependencyCheck]  -dataDirectory = /dcheckDB
[DependencyCheck]  -verboseLogFile = /jenkins/workspace/DepCheckDB/dependency-check.log
[DependencyCheck]  -dataMirroringType = none
[DependencyCheck]  -isQuickQueryTimestampEnabled = false
[DependencyCheck]  -useMavenArtifactsScanPath = false
[DependencyCheck]  -jarAnalyzerEnabled = false
[DependencyCheck]  -nodeJsAnalyzerEnabled = false
[DependencyCheck]  -composerLockAnalyzerEnabled = false
[DependencyCheck]  -pythonDistributionAnalyzerEnabled = false
[DependencyCheck]  -pythonPackageAnalyzerEnabled = false
[DependencyCheck]  -rubyBundlerAuditAnalyzerEnabled = false
[DependencyCheck]  -rubyGemAnalyzerEnabled = false
[DependencyCheck]  -cocoaPodsAnalyzerEnabled = false
[DependencyCheck]  -swiftPackageManagerAnalyzerEnabled = false
[DependencyCheck]  -archiveAnalyzerEnabled = false
[DependencyCheck]  -assemblyAnalyzerEnabled = false
[DependencyCheck]  -centralAnalyzerEnabled = false
[DependencyCheck]  -nuspecAnalyzerEnabled = false
[DependencyCheck]  -nexusAnalyzerEnabled = false
[DependencyCheck]  -autoconfAnalyzerEnabled = false
[DependencyCheck]  -cmakeAnalyzerEnabled = false
[DependencyCheck]  -opensslAnalyzerEnabled = false
[DependencyCheck]  -showEvidence = true
[DependencyCheck]  -format = XML
[DependencyCheck]  -autoUpdate = true
[DependencyCheck]  -updateOnly = true
[DependencyCheck] Unable to connect to the Dependency-Check database
[DependencyCheck] Unable to retrieve the database connection string
Build step 'Invoke OWASP Dependency-Check NVD update only' marked build as failure

This job has been working for months without any problem

If i run an update via command line, it works perfectly

Any idea what could be the problem? Has any url changed?

**Comment by stevespringett** [comment]
When using the CLI to update, are you specifying the --data option?

--data /dcheckDB

You might want to remove the contents of /dcheckDB and run the update again from the Jenkins plugin. Under most circumstances, you want to disable autoUpdate on Jenkins jobs when using a shared data directory. Reason being is that when two Jenkins jobs run simultaneously, they will both try to update the shared data directory and will end up corrupting it. 

So individual jobs should have autoUpdate disabled when using a shared data directory to avoid corruption. However, you still need to update the directory. So create a dedicated job that will block all other DC jobs that performs the updateOnly on the shared data directory on a daily basis. 

If you believe there is a defect, open a ticket here: https://issues.jenkins-ci.org

**Comment by javixeneize** [comment]
Hi

When running CLI it works totally fine just with the --update argument.

This dcheckDB job is totally cleared now. However, suddenly it doesnt give
an error anymore, but it keeps blocked at this updating step without doing
anything. Maybe they are restarting any service or something?

Do you know what is the exact command executed from jenkins for the
updateonly task?

thanks

**Comment by stevespringett** [comment]
The Jenkins plugin doesn't call the CLI. It uses the same methods in the core module to perform nearly identical tasks. For networking however, the Jenkins plugin will use the proxy server defined in the Jenkins global configuration.

**Comment by javixeneize** [comment]
Hi

Suddenly it works fine today again...

[DependencyCheck] Performing NVD update only
Finished: SUCCESS

I know this is not the right place to ask but... when will 2.0 be
released? Cant wait for pipeline integration!

Thanks

**Comment by jeremylong** [comment]
I know there are a few things people are looking for in the next release as its been a while since our last release.  I'm hoping to make this happen this weekend - I just have to finish some work on the gradle plugin and it should be good to go.

If the update is working now - can this ticket be closed?

**Comment by javixeneize** [comment]
Sure, will close it now
