### ISSUE TITLE
format of ALL does not include XML output

### ISSUE THREAD

**Issue by grillba** [dependency-check/DependencyCheck#779]
The XML output is not included when specify --format "ALL" on the command line, instead only the HTML and VULN outputs are produced.

The help states the following which implies ALL would include XML too.

`-f,--format <format> The output format to write to (XML, HTML, VULN, ALL). The default is HTML.`

Thoughts?
Ta, Mark

**Comment by grillba** [comment]
Scratch this one. Appears I was doing something stupid!

**Comment by jeremylong** [comment]
No worries - for a second there I thought I had done something stupid in the code ;)

--Jeremy
