### ISSUE TITLE
CLI execution - no documents exist

### ISSUE THREAD

**Issue by javixeneize** [dependency-check/DependencyCheck#780]
Hi

Its me again... :(

I am having problems when reading from the db. Let me explain what i am doing:

1 - I have a job that downloads daily the NVD database updates. 
2 - I am copying this db file in my workspace and running this
3- I have another job that runs depcheck against this database. 
 + dependency-check.sh --scan /jenkins/workspace/DCTest --project test --noupdate
[ERROR] No documents exist

4- Ok... I need to specify the database as an argument. Lets go for it
+ dependency-check.sh --scan /jenkins/workspace/DCTest --project test --noupdate -d /path/to/dc.h2.db
[ERROR] Unable to connect to the database

5 - According to https://github.com/jeremylong/DependencyCheck/issues/410, i need to send the connection string jdbc:h2:file:%s;FILE_LOCK=FS;AUTOCOMMIT=ON;

+ dependency-check.sh --scan /jenkins/workspace/DCTest --project test --noupdate -d /path/to/dc.h2.db --connectionString jdbc:h2:file:%s;FILE_LOCK=FS;AUTOCOMMIT=ON;
[ERROR] Unable to connect to the database

Any idea on how can i solve this?

Thanks

**Comment by jeremylong** [comment]
The issue appears to be your `-d` argument.  `-d` is "The location of the data directory used to store persistent data."  It looks like you are specifying the full file path - and in this will cause ODC to fail.

**Comment by javixeneize** [comment]
It solves the issue now. Thanks!
