### ISSUE TITLE
project failed when switching from 1.4.5 to 2.0.0

### ISSUE THREAD

**Issue by YanFenGuo** [dependency-check/DependencyCheck#782]
I'm using it in gradle script like below:
project.buildscript {
				repositories {
					jcenter()
				}
				dependencies {
					classpath 'org.owasp:dependency-check-gradle:latest.integration'
				}
			}

project.afterEvaluate {
				project.apply plugin: 'org.owasp.dependencycheck'
				project.dependencyCheck { ****}
				_project.tasks.dependencyCheck.doFirst {*****}_
}

### Reporting Bugs/Errors
03:25:57 > Could not find property 'dependencyCheck' on task set.
03:25:57 
03:25:57 * Try:
03:25:57 Run with --debug option to get more log output.
03:25:57 
03:25:57 * Exception is:
03:25:57 org.gradle.api.ProjectConfigurationException: A problem occurred configuring root project 'container-monitoring_master-B564AZZXCRJOHXR6EUQFM6PMC53W75NO47SOSU7SFINTJCCKTCYQ'.
03:25:57 	at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:79)
03:25:57 	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:74)
03:25:57 	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:61)
03:25:57 	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:521)
03:25:57 	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:92)
03:25:57 	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:42)
03:25:57 	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
03:25:57 	at org.gradle.initialization.DefaultGradleLauncher$2.run(DefaultGradleLauncher.java:125)
03:25:57 	at org.gradle.internal.Factories$1.create(Factories.java:22)
03:25:57 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
03:25:57 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
03:25:57 	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:122)
03:25:57 	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
03:25:57 	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
03:25:57 	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
03:25:57 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
03:25:57 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
03:25:57 	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
03:25:57 	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
03:25:57 	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
03:25:57 	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
03:25:57 	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
03:25:57 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
03:25:57 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
03:25:57 	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
03:25:57 	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:45)
03:25:57 	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
03:25:57 	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
03:25:57 	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
03:25:57 	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
03:25:57 	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
03:25:57 	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
03:25:57 	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
03:25:57 	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
03:25:57 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
03:25:57 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
03:25:57 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
03:25:57 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
03:25:57 	at org.gradle.launcher.Main.doAction(Main.java:33)
03:25:57 	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
03:25:57 	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
03:25:57 	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
03:25:57 	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
03:25:57 	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
03:25:57 	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
03:25:57 	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
03:25:57 Caused by: groovy.lang.MissingPropertyException: Could not find property 'dependencyCheck' on task set.
03:25:57 	at org.gradle.api.internal.AbstractDynamicObject.propertyMissingException(AbstractDynamicObject.java:43)
03:25:57 	at org.gradle.api.internal.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:35)
03:25:57 	at org.gradle.api.internal.CompositeDynamicObject.getProperty(CompositeDynamicObject.java:97)
03:25:57 	at org.gradle.api.internal.tasks.DefaultTaskContainer_Decorated.getProperty(Unknown Source)
03:25:57 	at com.ibm.ecm.cloud.gradle_init.InitializationPlugin$_apply_closure1$_closure7.doCall(InitializationPlugin.groovy:140)
03:25:57 	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
03:25:57 	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
03:25:57 	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
03:25:57 	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
03:25:57 	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
03:25:57 	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
03:25:57 	at com.sun.proxy.$Proxy11.afterEvaluate(Unknown Source)
03:25:57 	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:67)
03:25:57 	... 44 more
03:25:57 

### Reporting False Positives
project.tasks.dependencyCheck.doFirst reports error Could not find property ‘dependencyCheck’ on task set.

Now I use back to 1.4.5 and my project works fine.

**Comment by jeremylong** [comment]
Apparently, I missed an import update to the documentation. I'll fix this shortly.  

The `dependencyCheck` task had to be renamed to `dependencyCheckAnalyze`.

**Comment by mattnelson** [comment]
> Apparently, I missed an import update to the documentation. I'll fix this shortly.

Can the upgrade notes be fixed as well?
https://github.com/jeremylong/DependencyCheck#upgrading-from-1xx-to-2xx

**Comment by jeremylong** [comment]
done.

Thanks for pointing this out.

**Comment by YanFenGuo** [comment]
Thank you for quick response.
