### ISSUE TITLE
False Positive on jersey-client-2.22.1.jar

### ISSUE THREAD

**Issue by trophies** [dependency-check/DependencyCheck#786]
False positive on library jersey-client-2.22.1.jar - reported as cpe:/a:oracle:oracle_client:2.22.1

```xml
<dependency>
   <groupId>org.glassfish.jersey.core</groupId>
   <artifactId>jersey-client</artifactId>
   <version>2.22.1</version>
</dependency>
```

Note: While I was seeing this reported previously, I've since added a it to my false positives xml to suppress it, but it no longer shows up in the list of suppressed vulnerabilities.

**Comment by jeremylong** [comment]
The 2.0.0 release added this as one of the "base" suppression rules. These do not show up in the list of suppressed vulnerabilities.
