### ISSUE TITLE
java.util.MissingResourceException when trying to use owasp plugin with Postgres

### ISSUE THREAD

**Issue by evg1001** [dependency-check/DependencyCheck#793]
When I try to use version 2.0.1 of the owasp dependency check plugin for maven it fails with error:

Can't find resource for bundle java.util.PropertyResourceBundle, key MERGE_PROPERTY -> [Help 1]

For full error log please check here:
https://gist.github.com/evg1001/e1a01a50ccb5602e7164fc1db6b5033a

**Comment by jeremylong** [comment]
@evg1001 Any chance you could re-run the failed execution with the `-X` option and look for the entry in the log file: 

`Database product: ` 

Then post the line from the log file here?

**Comment by stefanneuhaus** [comment]
I just observed the "Database product:" line in the reported error log: https://gist.github.com/evg1001/e1a01a50ccb5602e7164fc1db6b5033a#file-maven_owasp_dependency_plugin_error-txt-L305
