### ISSUE TITLE
No vulnerabilities found in jenkins pipeline

### ISSUE THREAD

**Issue by javixeneize** [dependency-check/DependencyCheck#795]
Hi

I have found a behaviour that is a bit odd...

If i run this in a freestyle project, it runs perfectly fine, but, if i run this as part of a pipeline, although it runs correctly, it doesnt detect any vulnerability.

I am checking this with a project that i have with vulnerable versions in purpose

The steps in my pipeline are:

step([$class: 'DependencyCheckBuilder', datadir: '${WORKSPACE}', hintsFile: '', includeCsvReports: false, includeHtmlReports: true, includeJsonReports: true, isAutoupdateDisabled: true, outdir: '', scanpath: '${WORKSPACE}', skipOnScmChange: false, skipOnUpstreamChange: false, suppressionFile: '', zipExtensions: ''])
    step([$class: 'DependencyCheckPublisher', canComputeNew: false, defaultEncoding: '', failedTotalHigh: '0', healthy: '', pattern: '', unHealthy: '', unstableTotalNormal: '0'])

Report says:

0 vulnerabilities from one analysis.
No warnings since build 1.
New zero warnings highscore: no warnings since yesterday!

Using the freestyle project, this is what i have:

26 vulnerabilities from one analysis.
26 new vulnerabilities
Plug-in Result:Failed - 8 warnings of priority High exceed the threshold of 0 by 8

Any idea where could be the problem?

Thanks

**Comment by stevespringett** [comment]
@javixeneize  it's my understanding that variables (in the format ${VAR} cannot be used this way in pipeline. Try removing ${WORKSPACE} from datadir and scanpath so that they are blank to see if it works. Also, Jenkins specific issues need to be created on the Jenkins issue tracker https://issues.jenkins-ci.org/

**Comment by javixeneize** [comment]
You are totally right. It works now

I suggest to update the help in the pipeline syntax, as it says


The base directory to scan. If empty, the workspace will be used by default. Dependency-Check will scan this directory and all subdirectories thereof. 
Paths may contain Jenkins environment variables such as ${WORKSPACE} and ${BUILD_NUMBER}.Multiple scan paths may be defined by separating the paths with a comma (i.e. dir1, dir2, dir3)Paths may also be defined using Ant-style pattern sets. For example:**/commons*.jar**/*com*.jar**/*dir*/*.jar
--
