### ISSUE TITLE
Error analysing NodeJS

### ISSUE THREAD

**Issue by javixeneize** [dependency-check/DependencyCheck#797]
Hi

Im having a problem when analysing nodeJS projects. The error i have is:

[DependencyCheck] Exception Caught: java.lang.ClassCastException
[DependencyCheck] Message: org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl cannot be cast to javax.json.JsonString
[DependencyCheck] Exception Caught: org.owasp.dependencycheck.analyzer.exception.AnalysisException
[DependencyCheck] Message: Could not perform NSP analysis. Invalid payload submitted to Node Security Platform.

Checking your code, looks like i have an error 400

        case 400:
                    LOGGER.debug("Invalid payload submitted to Node Security Platform. Received response code: {} {}",
                            conn.getResponseCode(), conn.getResponseMessage());
                    throw new AnalysisException("Could not perform NSP analysis. Invalid payload submitted to Node Security Platform.");

Have you ever seen this before?

On top of that, since you are using NSP to analyse the dependencies, is the code or the report being uploaded somewhere?

Thanks

**Comment by jeremylong** [comment]
The NSP analyzer takes information from the `package.json` file and sends it to NSP for analysis (URL: https://api.nodesecurity.io/check).

Any chance you could share a package.json so we can debug what is going on?

**Comment by javixeneize** [comment]
Hi

No, sorry, i cant share this package....

**Comment by bzuu** [comment]
I am seeing the same issue on multiple NPM packages. You can reproduce it locally by doing the following:

- Create a new directory
- Run `npm init` in the new directory, accept all the defaults
- Run `npm install bower`, which at the time of writing installs bower@1.8.0
- Now run dependency check on this directory `dependency-check.bat --project "example" --scan my_directory`

Running this on Windows 10 with dependency check 2.0.1

Log attached
[output.zip](https://github.com/jeremylong/DependencyCheck/files/1165834/output.zip)

**Comment by stevespringett** [comment]
@bzuu Using the steps above, I can reproduce the error. However, when performing a scan like this, you are saying to recursively scan `my_directory` and for every package.json file you encounter, submit it to the NSP API. __That's not what you want to do__. Bower itself has 268 modules and some of them may have package.json files that the NSP service does not like. It's also possible that submitting so many requests to scan over 268 package.json files, the NSP service simply errors out.

The command you want to execute is:
`dependency-check.bat --project "example" --scan my_directory\package.json`

**Comment by javixeneize** [comment]
How to do it in a pipeline? Is there an option to specify that?

**Comment by stevespringett** [comment]
@javixeneize The documentation is in Jenkins and Jenkins itself can automatically create a sample script for you

**Comment by stevespringett** [comment]
@bzuu I think it may be smart to improve the NspAnalyzer so that it ignores package.json files inside the node_modules directory. This way, users would be able to simply scan an entire directory (like what you attempted to do) without worrying about making too many requests to NSP.

I can't think of any downside to this. Thoughts?

**Comment by bzuu** [comment]
@stevespringett That sounds like a good idea. I wasn't aware of this, however had noticed the analysis took quite long on our actual project. So both from the perspective of not overloading the NSP api and performance this seems like a good enhancement to me.

**Comment by javixeneize** [comment]
I also agree its a good improvement. Getting better and better ;)

**Comment by stevespringett** [comment]
The fix is in the current SNAPSHOT and will be included in the next release.
