### ISSUE TITLE
Issues with mixed java and javascript projects

### ISSUE THREAD

**Issue by Fraserhardy** [dependency-check/DependencyCheck#805]
I am having trouble with running dependency check against our whole project. We have a mixture of java and javascript libraries covering our backend and front end. It seems if I give only the jar folders to the cli I get a report covering the jars, however if I give both these and the frontend folders then I only get the front-end dependencies: 

`dependency-check --project QudiniApp --scan lib libs` Shows only jar files in the report. 

`dependency-check --project QudiniApp --scan front-end-build public lib libs` shows only package.json files in the report. 

Am I doing something completely wrong here or is this an issue with scanning mixed language projects?

**Comment by jeremylong** [comment]
The correct call would be:

```dependency-check --project QudiniApp --scan front-end-build --scan public --scan lib --scan libs```

You can specify more then one `--scan` option, but it can only take a single path.

**Comment by Fraserhardy** [comment]
Ah I see! Yes that worked. Thanks for the clarification.
