### ISSUE TITLE
dependency-check-maven:2.0.1 ignores suppressionFile system property

### ISSUE THREAD

**Issue by ahubold** [dependency-check/DependencyCheck#806]
after updating from 1.4.5 to 2.0.1, my suppression file is ignored when I invoke the Maven goal from the command line as follows:

`mvn org.owasp:dependency-check-maven:2.0.1:aggregate -DsuppressionFile=suppressions.xml ...`

The report is generated but no false positives get suppressed. This used to work with 1.4.5
Property `-DsuppressionFiles` (plural) also does not work.

**Comment by jeremylong** [comment]
Sorry about that - when support for multiple suppression files was added we accidentally introduced this issue. The fix will be included in the next release.
