### ISSUE TITLE
Missing resource MERGE_PROPERTY for oracle database

### ISSUE THREAD

**Issue by laudenbach** [dependency-check/DependencyCheck#808]
I updated from version 1.4.5 to 2.0.1. When running with Oracle, now I get an MissingResourceException, telling, the resource for MERGE_PROPERTY is missing.

Stacktrace: https://gist.github.com/laudenbach/c5575c8c5aa2acbe99591ad80f0fa79c

Looking at the code, there is really no entry for MERGE_PROPERTY, wheter in` src/main/resources/data/ 	dbStatements.properties`, nor in `dbStatements_oracle.properties`.

**Comment by jeremylong** [comment]
Just realized the mistake with this and I have added a patch. The `MERGE_PROPERTY` was added to speed up some operations and was added to H2, MySQL, and postgreSQL. There is a fallback for Oracle (to use a slower insert/update). An example for MySQL can be found in the [properties ](https://github.com/jeremylong/DependencyCheck/blob/master/dependency-check-core/src/main/resources/data/dbStatements_mysql.properties#L15)and [initialization script](https://github.com/jeremylong/DependencyCheck/blob/master/dependency-check-core/src/main/resources/data/upgrade_mysql_2.9.sql#L5).

If someone could write an equivalent merge procedure for Oracle it would be appreciated. If not, the patch I put in will resolve the exception.
