### ISSUE TITLE
[Enhancement] CSV report format

### ISSUE THREAD

**Issue by piyushml20** [dependency-check/DependencyCheck#809]
CSV report format doesn't contain GAV, CPE confidence and evidence count fields. These fields are present in HTML report format. It would be good to have these fields as part of CSV too.

**Comment by elenoir** [comment]
I take care of it.

**Comment by piyushml20** [comment]
I moved to 3.0.1 and CSV report doesn't contain CPE confidence and evidence count fields. Am I doing something wrong?

**Comment by jeremylong** [comment]
While I am seeing the CPE confidence... It appears I missed one thing when making changes to the 3.x branch.  If you are not seeing the CPE confidence can you open a new issue and include a sample report?

**Comment by jeremylong** [comment]
Note - I did just patch the issue with the evidence count. That fix will be included in the next release.
