### ISSUE TITLE
Utilize the update and edition fields from the CPE when matching

### ISSUE THREAD

**Issue by jeremylong** [dependency-check/DependencyCheck#811]
Consider using the update and edition fields when performing CPE matching as this may reduce some FP. 

See the [google groups discussion](https://groups.google.com/forum/#!searchin/dependency-check/m22%7Csort:relevance/dependency-check/Tu_l6xETNiA/gpbKo5PIBAAJ)

**Comment by javixeneize** [comment]
Hi Jeremy

I have more FP regarding DB2 now. Im using db2jcc4-4.19.26.jar, which is DB2 Version 10.5, FP6, and the report flags issues related to DB2 Version 8, 9 etc...

There is no GAV in the report, the closest i have is the CPE -- cpe:/a:ibm:db2:4.19.26
