### ISSUE TITLE
Version 2.0+ fails with Gradle < 3.3

### ISSUE THREAD

**Issue by Thunderforge** [dependency-check/DependencyCheck#822]
Running this plugin with a Gradle version less than version 3.3 fails with the following error:

```
Execution failed for task ':MyProject:dependencyCheckAnalyze'.
> Could not find method getDisplayName() for arguments [] on project ':MyProject' of type org.gradle.api.Project.
```

This is because [getDisplayName()](https://docs.gradle.org/3.3/javadoc/org/gradle/api/Project.html#getDisplayName()) was introduced in Gradle 3.3.

Either a fallback should be included for if this functionality is not available, or the documentation should note that Dependency Check 2.0+ requires Gradle 3.3+ to run.

**Comment by jeremylong** [comment]
This was fixed with the 2.1.0 release. See https://github.com/jeremylong/dependency-check-gradle/pull/51.
