### ISSUE TITLE
check goal fails with multiple proxy definitions

### ISSUE THREAD

**Issue by sam-afsa** [dependency-check/DependencyCheck#831]
I have two proxy definitions in Maven settings.xml. The definitions are for different protocols (HTTP and HTTPS) and can be disambiguated on that basis. The definitions have different IDs.

These are the relevant log entries:

```
[INFO] --- dependency-check-maven:2.1.0:check (default) @ parent-pom ---
[WARNING] Multiple proxy definitions exist in the Maven settings. In the dependency-check configuration set the mavenSettingsProxyId so that the correct proxy will be used.
```

```
[ERROR] Failed to execute goal org.owasp:dependency-check-maven:2.1.0:check (default) on project parent-pom: Execution default of goal org.owasp:dependency-check-maven:2.1.0:check failed: Ambiguous proxy definition -> [Help 1]
```

I am using an ancient version of Maven because I work for a glacier:
```
$ mvn -version
Apache Maven 3.1.1 (0728685237757ffbf44136acec0402957f723d9a; 2013-09-18 01:22:22+1000)
Maven home: redacted
Java version: 1.7.0_75, vendor: Oracle Corporation
Java home: redacted
Default locale: en_AU, platform encoding: Cp1252
OS name: "redacted", version: "redacted", arch: "amd64", family: "windows"
```

Current workaround is to specify `mavenSettingsProxyId` in the POM as suggested but I'd prefer not to have to do that.

**Comment by jeremylong** [comment]
Unfortunately, specifying the mavenSettingsProxyId is the only solution to this problem (currently). Allowing for multiple proxies and using the right one based on protocol (within the core engine) would be fairly low on the priority list right now - but PRs are welcome.

**Comment by sam-afsa** [comment]
I would like to create a PR but I would need to have development time approved by my employer. It would also be very low on their priority list and I'm not sure I could convince them it's worth it.

**Comment by Tholian** [comment]
Hi, ran into the same issue know because the admin of the jenkins configured more proxies now, so the build is failing.

Tieing the id of a settings entry into the pom does not feels that good for me.
It's a pity that the issue was closed.

Do you see any chance to reopen it and fix it?

Best regards

**Comment by jeremylong** [comment]
I'll put this back on the list of enhancements - but as I said before there are a ton of other things I'm working on.  PRs are welcome.
