### ISSUE TITLE
Unable to access the local database

### ISSUE THREAD

**Issue by giacgbj** [dependency-check/DependencyCheck#833]
Logs: https://gist.github.com/giacgbj/84dd509c2c4916e18b7bfc9827b13d0a

- I've run the job many times before posting this issue
- I'm using an internal mirror which works
- the directory /home/jenkins/workspace/FooProject/dependency-check-data is writeable (775) by the user which launches Jenkins and it's removed each time the job is executed
- the dbs permissions are:
 -rw-rw-r-- 1 jenkins jenkins 2107392 Aug  5 22:19 dc.h2.db
 -rw-rw-r-- 1 jenkins jenkins     116 Aug  5 22:19 dc.lock.db
 -rw-rw-r-- 1 jenkins jenkins   43174 Aug  5 22:19 dc.trace.db

**Comment by rompic** [comment]
sounds a little bit like https://github.com/jeremylong/DependencyCheck/issues/100 to me.
https://github.com/jeremylong/DependencyCheck/issues/100#issuecomment-38585732 -> "To recover from your current situation, you can either delete the whole data directory, or you might be able to just delete the .lock file in the data directory."

**Comment by giacgbj** [comment]
If the .lock file is in "dependency-check-data" directory, that directory is removed before each build.

**Comment by stevespringett** [comment]
Ensure you have auto update enabled in the job. If you're removing the project workspace for each build, autoupdate will need to be enabled so it can rebuild the database each time. Assuming that is done, do you have either of these plugins installed?

- https://wiki.jenkins.io/display/JENKINS/Pipeline+Maven+Plugin
- https://wiki.jenkins.io/display/JENKINS/Liquibase+Runner

These potentially could cause conflicts as they use beta versions of H2 instead of the stable 1.3 branch that Dependency-Check and the Jenkins H2 plugin uses.

**Comment by rompic** [comment]
Having a separate job that updates the database regularly is a massive performance Improvement as far as I know.
See E.g. https://medium.com/@PrakhashS/checking-vulnerabilities-in-3rd-party-dependencies-using-owasp-dependency-check-plugin-in-jenkins-bedfe8de6ba8
https://blog.dominikschadow.de/2015/07/using-owasp-dependency-check-as-jenkins-plugin/

**Comment by giacgbj** [comment]
@stevespringett Autoupdate is enabled (from the gist, i think it's the autoupdate='true' property).
"Unfortunately", I don't have those plugins installed.

@rompic I know I can do that (and I will), but it wouldn't solve this issue. It would be only moved to a single job and all the others would probably get a NoDataException.

**Comment by giacgbj** [comment]
It still fails randomly.

Could it be a concurrency issue?

In the logs I see:
#download   threads: 12
#processing threads: 8

**Comment by jeremylong** [comment]
Are there a large number of builds on this server? I'm not sure how you have things setup - but is it possible that one job is deleting the database directory while another job is using it?

**Comment by giacgbj** [comment]
That's not possible: the builds are sequential. The database directory ("dependency-check-data", I suppose) is different for each job and is always wiped out before each build.

**Comment by jeremylong** [comment]
This is believed to be fixed in the 3.0.0-SNAPSHOT - unfortunately, you would have to build that yourself for now to test.

**Comment by rompic** [comment]
is this part of 3.0.1? still see the same issue

**Comment by jeremylong** [comment]
@rompic yes, this should have been fixed in 3.0.1. If after deleting the data directory and re-running ODC if you are still seeing this issue please open a new issue.
