### ISSUE TITLE
use proxysettings from maven-settings

### ISSUE THREAD

**Issue by davidkarlsen** [dependency-check/DependencyCheck#84]
It would be better if the plugin uses mavens settings.xml for proxy settings: https://maven.apache.org/settings.html#Proxies .
Change the config to inject ${settings}, and optionally a serverId .
Use the proxy config with the given serverId for proxy config, optionally if settings.xml only contain one proxy config and the config no serverId, use the one single config entry.

**Comment by jeremylong** [comment]
Thanks! I will get the PR into the next release.

--Jeremy

**Comment by jeremylong** [comment]
The PR to resolve this has been merged into 1.1.4-SNAPSHOT. The documentation will still need to be updated so I will leave this issue open until I can get to this within the next day or two.

Thanks again for the suggestion and the PR.

**Comment by jeremylong** [comment]
The documentation has been updated. This issue is now closed.

**Comment by davidkarlsen** [comment]
Sorry for my ignorance but where are the docs?
The docs at: http://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html and http://jeremylong.github.io/DependencyCheck/dependency-check-maven/usage.html seem to be the same old.

Should I remove the old way of configuring it - will be confusing for the user to have two ways of doing it and the older way taking preference.

**Comment by jeremylong** [comment]
I haven't released 1.1.4 yet, when I do the docs will be updated.

Sorry for the delay, I am currently traveling on business and the amount of
time I have to spend on this project has suffered a little. I'm hoping by
this weekend I will be able to release 1.1.4.

Best Regards,

Jeremy

**Comment by jeremylong** [comment]
The updated documentation can be found in github until 1.1.4 is published:

https://github.com/jeremylong/DependencyCheck/blob/master/dependency-check-maven/src/site/markdown/configuration.md

--Jeremy
