### ISSUE TITLE
Support skipping maven report generation

### ISSUE THREAD

**Issue by mattnelson** [dependency-check/DependencyCheck#842]
When declaring the dependency check plugin in a parent pom, I would like to disable report generation for specific modules. Specifically in testing modules since I do not care about the vulnerability of the dependencies used for the tests and to help with build times.

**Comment by jeremylong** [comment]
In your test modules add the following to your build:

```xml
<plugin>
  <groupId>org.owasp</groupId>
  <artifactId>dependency-check-maven</artifactId>
  <configuration>
    <skip>true</skip>
  </configuration>
</plugin>
```

**Comment by AndrewJCarr** [comment]
The issue stems from having the report sets configured in the parent pom and being unable to override the report set in maven.

```
<reporting><plugins>
<plugin>
    <groupId>org.owasp</groupId>
    <artifactId>dependency-check-maven</artifactId>
    <reportSets>
        <reportSet>
            <reports>
                <report>aggregate</report>
            </reports>
        </reportSet>
    </reportSets>
</plugin>
</plugins></reporting>
```

The enabling of the skip option (as above) works for the build aspect but does not have any effect during site generation. It performs the download/analysis of the NVD database files during the site generation if they have not yet occured. This impacts the site generation times for the modules that have no need for OWASP scanning (mainly integration tests) if we leverage a common parent pom. 

It appears that if we place the following behavior in BaseDependencyCheckMojo#generate, the skip configuration would be honored during site generation. Would you be open to a pull request for this behavior?

```
if (skip) {
    getLog().info("Skipping " + getName(Locale.US) + " report generation");
}
```

**Comment by jeremylong** [comment]
Yes, please submit a PR - we missed this when we originally added the skip. 

Thanks!

**Comment by AndrewJCarr** [comment]
No problem. I'll put one up in a few days or so - need to carve out some time to get the project compiling, etc.

**Comment by AndrewJCarr** [comment]
I opened PR #858 to add the skip functionality. Sorry it took so long to get a tiny fix submitted.
