### ISSUE TITLE
AnalysisException on empty .json file

### ISSUE THREAD

**Issue by apeppelsICTU** [dependency-check/DependencyCheck#844]
I'm using Depensency Checker in the Jenkins plugin form, however this issue is present in the command line version.
Empty .json files are not handled gracefully, and throw an exception when the parser is trying to determine the encoding. Output in my case:

[DependencyCheck] Scanning: C:\Jenkins\workspace\SensitiveApplicationRedacted\
[DependencyCheck] Analyzing Dependencies
[DependencyCheck] One or more exceptions were thrown while executing Dependency-Check
[DependencyCheck] Exception Caught: org.owasp.dependencycheck.analyzer.exception.AnalysisException
[DependencyCheck] Cause: Cannot auto-detect encoding, not enough chars
[DependencyCheck] Message: Failed to parse C:\Jenkins\workspace\SensitiveApplicationRedacted\node_modules\npmconf\test\fixtures\package.json file.

Some info on the source of the issue as per [RFC 4627](https://tools.ietf.org/rfc/rfc4627.txt)

> JSON text SHALL be encoded in Unicode. The default encoding is
> UTF-8.
> 
> Since the first two characters of a JSON text will always be ASCII characters [RFC0020], it is possible to determine whether an octet
> stream is UTF-8, UTF-16 (BE or LE), or UTF-32 (BE or LE) by looking
> at the pattern of nulls in the first four octets.
> 
>        00 00 00 xx  UTF-32BE
>        00 xx 00 xx  UTF-16BE
>        xx 00 00 00  UTF-32LE
>        xx 00 xx 00  UTF-16LE
>        xx xx xx xx  UTF-8

**Comment by jeremylong** [comment]
Thanks for the bug report!
