### ISSUE TITLE
Generate HTML report possible small type-o _bank  or _blank

### ISSUE THREAD

**Issue by PeterLenahan** [dependency-check/DependencyCheck#855]
### Reporting Bugs/Errors

Did you mean to use the window target name    _bank  or _blank   ?

<a href="http://jeremylong.github.io/DependencyCheck/general/thereport.html" target="_bank">How&nbsp;to&nbsp;read&nbsp;the&nbsp;report</a> | 

<a href="http://jeremylong.github.io/DependencyCheck/general/suppression.html" target="_bank">Suppressing false positives</a> |

Getting Help: <a href="https://groups.google.com/forum/#!forum/dependency-check" target="_blank">google group</a> |

**Comment by jeremylong** [comment]
Thanks for pointing that out; it will be fixed in the next release.

**Comment by PeterLenahan** [comment]
your welcome, !! :)
