### ISSUE TITLE
Disable .NET Analysis

### ISSUE THREAD

**Issue by hgomez** [dependency-check/DependencyCheck#86]
Could we have a way to disable .Net Analysis from CLI/Ant/Maven scan ?

It's a bit disturbing to get "WARNING: An error occured with the .NET AssemblyAnalyzer" and a stack trace in Maven Plugin when analysing stock Java projects. 

[INFO] --- dependency-check-maven:1.1.3:check (default-cli) @ dm-server ---
Mar 12, 2014 2:20:40 PM org.owasp.dependencycheck.Engine analyzeDependencies
INFO: Analysis Starting
Mar 12, 2014 2:20:40 PM org.owasp.dependencycheck.analyzer.AssemblyAnalyzer initialize
WARNING: An error occured with the .NET AssemblyAnalyzer; this can be ignored unless you are scanning .NET dlls. Please see the log for more details.
Mar 12, 2014 2:20:40 PM org.owasp.dependencycheck.Engine analyzeDependencies
SEVERE: Exception occurred initializing Assembly Analyzer.
Mar 12, 2014 2:20:45 PM org.owasp.dependencycheck.Engine analyzeDependencies
INFO: Analysis Complete

**Comment by jeremylong** [comment]
Completely agree.  I think there are two solutions to this:

1) We configure each "file type" analyzer to have an on/off configuration
option. That way as we expand into JavaScript, Node.JS, and possibly other
languages we can disable analyzers for technologies we don't care about.
2) We disable the "file type" analyzers that didn't flag a file during the
scan.

I think from a usability standpoint the second option might be best, but it
may need to be a combination of the two...

--Jeremy

**Comment by colezlaw** [comment]
I was thinking through the same sorts of things. I think 2 is a good idea, but:
1. It may require two passes through everything - the Mono analyzer makes that complaint during initialization, so if we were to depend only on 2, we'd have to know all the file types before initialization - which means that all archives would also have to be crawled beforehand.
2. Doing 2 doesn't preclude the ability to do 1.
3. Doing 1 and 2 doesn't preclude turning off individual analyzers. For example, the Nuspec analyzer may still be useful, and doesn't require that Mono be available.

**Comment by jeremylong** [comment]
I was actually considering a slightly more drastic reworking of the initialization for the analyzers that would make it possible to make method 2 work. I'm still debating this in my head and once I've reached what I think would be a workable design I'll post my thoughts and we can discuss.

**Comment by jeremylong** [comment]
I have implemented solution 2 (where analyzers will not be active if they don't have any files to scan). Individual flags to turn off the specific analyzers will be added soon.

**Comment by jeremylong** [comment]
The code to support disabling specific analyzers has been pushed to 1.1.4-SNAPSHOT. We will hopefully be publishing 1.1.4 shortly.
