### ISSUE TITLE
Depcheck not working in jenkins slaves

### ISSUE THREAD

**Issue by javixeneize** [dependency-check/DependencyCheck#861]
Hi

I think this has been previously reported (https://issues.jenkins-ci.org/browse/JENKINS-45782) and solved in the next version of the jenkins plugin

Any idea when this new version will be released?

Thanks

**Comment by stevespringett** [comment]
There are no known issues with slave execution in the current release. If you experience an issue with 2.1.1 Jenkins plugin, please fill out a ticket here https://issues.jenkins-ci.org/

**Comment by javixeneize** [comment]
Yes. I was still in the previous version. That one works perfect
