### ISSUE TITLE
NPM False Postivies - mistaking NPMs for other binaries

### ISSUE THREAD

**Issue by ismisepaul** [dependency-check/DependencyCheck#864]
The following NPMs are reported but are false positives as DP thinks they are other binaries;

1. cmd-shim/package.json - reports as the UEFI bootloader Shim cpe:2.3:a:shim:shim:-:*:*:*:*:*:*:*
2. node_modules/normalize-git-url/package.json - reports as is_git_directory function in setup.c in Git cpe:2.3:a:git:git:*:*:*:*:*:*:*:*
3. sshpk/node_modules/getpass/package.json - reports as visionmedia cpe:2.3:o:fedoraproject:fedora:19:*:*:*:*:*:*:*

Scanning with nodeJsAnalyzerEnabled = true

**Comment by stevespringett** [comment]
The Node analyzer will likely be removed in the near future. In my personal testing it's got a near 100% false positive and negative rate. To scan Node packages, use the nspanalyzer instead.

**Comment by stevespringett** [comment]
@ismisepaul Refer to #870 for further details.

**Comment by jeremylong** [comment]
The node analyzer has been retired in 3.0.0. As such, this ticket will be closed.
