### ISSUE TITLE
False Positive detecting NPM CLI

### ISSUE THREAD

**Issue by ismisepaul** [dependency-check/DependencyCheck#865]
DP is reporting "The CLI in npm before 2.15.1 and 3.x before 3.8.3, as used in Node.js 0.10 before 0.10.44, 0.12 before 0.12.13, 4 before 4.4.2, and 5 before 5.10.0, includes bearer tokens with arbitrary requests, which allows remote HTTP servers to obtain sensitive information by reading Authorization headers."

The following NPMs have been flagged;

- fstream-npm/package.json
- npm-install-checks/package.json
- npm-user-validate/package.json 
- validate-npm-package-name/package.json
- gitignore-and-npmignore-2.tar/npm-test-gitignore/package.json
- gitignore-and-npmignore.tar/package/package.json

CPE for all: cpe:2.3:a:ibm:sdk:1.1.0.20:*:*:*:*:nodejs:*:* 

```xml
<configuration>
  <nodeVersion>v4.4.7</nodeVersion>
  <npmVersion>3.10.5</npmVersion>
   <installDirectory>target</installDirectory>
</configuration>
```

Scanning with nodeJsAnalyzerEnabled = true

**Comment by stevespringett** [comment]
@ismisepaul Please use the NSP analyzer instead of the Node analyzer. Refer to #870 for detailes. The Node analyzer will likely be deprecated in the future release.

**Comment by jeremylong** [comment]
The node analyzer has been retired in 3.0.0. As such, this ticket will be closed.

**Comment by ammy1999** [comment]
please, I add  dependency check  as a plugin jenkin , as result I have a lot of false positives, so How can I delete them ( as maven project with suppression code) thanks,
