### ISSUE TITLE
Default location of data-directory should be documented

### ISSUE THREAD

**Issue by icyerasor** [dependency-check/DependencyCheck#868]
Neither [in the Database config](https://jeremylong.github.io/DependencyCheck/data/database.html) nor  the [CLI documentation](https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html) mentions what the "default" location of the databse directory is.
As it seems to turns out, it is:
`data.directory='[JAR]/data'`

thus, the h2-db files reside in the .m2-repository at
> [.m2-repository]/org/owasp/dependency-check-data/3.0/

Would have saved me an hour if I found this documented somewhere.
If you point me to the right location (is the documentation checked in?), I'm willing to update it myself.

Keep up the good work.

**Comment by jeremylong** [comment]
The documentation is in the maven site; for this the best place to document it would likely be: https://github.com/jeremylong/DependencyCheck/blob/master/dependency-check-maven/src/site/markdown/configuration.md

**Comment by lli-hiya** [comment]
I don't have ~/.m2 folder and do you know where can I find the directory?

**Comment by jeremylong** [comment]
Are you using the CLI, Ant, gradle, maven????

**Comment by lli-hiya** [comment]
I am using the SBT dependency check: https://github.com/albuch/sbt-dependency-check

**Comment by lli-hiya** [comment]
I found it. For the SBT one, the data directory by default is: `~/.ivy2/cache/org.owasp/dependency-check-utils/jars/data`
