### ISSUE TITLE
reportOutputDirectory and outputDirectory for Maven Plugin

### ISSUE THREAD

**Issue by hgomez** [dependency-check/DependencyCheck#87]
reportOutputDirectory could be set from outside but didn't seems to be used in plugin.
outputDirectory is not a property setable from outside and defaulted to ${project.build.directory}

Should

```
r.generateReports(outputDirectory.getCanonicalPath(), format);
```

Replaced by 

```
r.generateReports(reportOutputDirectory.getCanonicalPath(), format);
```

Or outputDirectory exposed as a setable property and reportOutputDirectory removed ?

**Comment by jeremylong** [comment]
Okay, I need to do some more testing. I believe reportOutputDirectory maps to target/site. The outputDirectory (unless configured) maps to target (but I think there is a bug there now). However, you should only configure the outputDirectory for non-site builds and the reportOutputDirectory shouldn't be changed.  But I'll do some testing soon and update the code and ticket.

**Comment by jeremylong** [comment]
I've added the "outputDirectory" to the [Dependency-Check's Maven Configuration](http://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html#) and corrected the code to use it when not generating the site report(s). This is in the 1.1.4-SNAPSHOT now and will be published during the next release.

The reportOutputDirectory is still used, but it is not a property that should be set by the user and as such, is not documented in the configuration.
