### ISSUE TITLE
Trying to run the jenkins plugin fails to update the database

### ISSUE THREAD

**Issue by stephanerenou** [dependency-check/DependencyCheck#876]
Hello,
I am trying to use the jenkins plugin 2.1.1
I tried it via a basic plugin script of via a regular jenkins job, and in both cases, I am getting the same error:
[DependencyCheck] Performing NVD update only
[DependencyCheck] Unable to update the Dependency-Check database

Is there a way I can get more debugging information?

My pipeline is as:
pipeline {
    agent any
    stages {
        stage('update') {
            steps {
                dependencyCheckUpdateOnly ''
            }
        }
    }
}

To be noted, I am running the CLI version without concern on that same box.
Thanks for any help getting more logs

**Comment by stevespringett** [comment]
In Jenkins system logs, create a logger for org.owasp and set the detail to ALL

**Comment by stephanerenou** [comment]
thanks for the quick response.
I forced my update to store into /var/dependency that is a folder that exists on my disk and my jenkins user has rigths to write to it but the exception I am getting is now: 
org.h2.jdbc.JdbcSQLException: Error opening database: "Unsupported lock method serialized" [8000-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.store.FileLock.getExceptionFatal(FileLock.java:455)
	at org.h2.store.FileLock.lockFile(FileLock.java:347)
	at org.h2.store.FileLock.lock(FileLock.java:135)
	at org.h2.engine.Database.open(Database.java:662)
	at org.h2.engine.Database.openDatabase(Database.java:276)
	at org.h2.engine.Database.<init>(Database.java:270)
	at org.h2.engine.Engine.openSession(Engine.java:64)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.engine.Engine.createSession(Engine.java:27)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:354)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.getConnection(ConnectionFactory.java:233)

**Comment by stevespringett** [comment]
In Dependency-Check v2.1.1, the JDBC URL changed from:

```jdbc:h2:file:%s;AUTOCOMMIT=ON;FILE_LOCK=SERIALIZED;```
to
```jdbc:h2:file:%s;MV_STORE=FALSE;AUTOCOMMIT=ON;```

This is due to shipping a newer version of H2. The default JDBC URL was changed in the Jenkins plugin as well as the core. However, if you're specifying the URL yourself, you'll need to update it.

**Comment by stephanerenou** [comment]
I am not trying to set anything beside the folder location of my data that I did set to /var/dependency.
From what I see in the logs, the conection string appears as correct as it is now set to:
Setting: data.connection_string='jdbc:h2:file:%s;MV_STORE=FALSE;AUTOCOMMIT=ON;'
Setting: autoupdate='true'
Setting: data.directory='/var/dependency'

and further:
Connection String: 'jdbc:h2:file:/var/dependency/dc;MV_STORE=FALSE;AUTOCOMMIT=ON;'
Settings.getDataFile() - file: '/var/dependency'
but this folder is empty as this is the first time I run the component using that folder.

**Comment by stevespringett** [comment]
The message: 

> Unsupported lock method serialized

 suggests that Jenkins is resolving an older version of H2 instead of using the H2 distribution included with the Jenkins plugin.

Ensure all your other plugins are up-to-date. Also, these two plugins will likely cause issues since they use the older H2 version

https://github.com/jenkinsci/database-h2-plugin
https://github.com/jenkinsci/jenkow-plugin

**Comment by stephanerenou** [comment]
Thanks for the feedback. 
I just tried to roll back dependency-check plugin to 2.1.0, and now I am able to get my workflow to run without using the pipeline integration for the moment as the method is not known, but at least that allows me to get rid of the CLI in my job. I will investigate to find which plugin is creating the issue, but I don't have any of the two above as far as I can see. I have some plugins that are not running the latest release, but I don't want to break existing jobs with a massive upgrade for the moment.

**Comment by matcornic** [comment]
I faced the same problem. I deleted the h2 database and it works now (even with version 3). history is lost, but it was ok for my context.

I could not try it, but maybe a simple delete of the lock could have been enough. I had 3 files in the workspace

```
-rw-r--r-- 1 jenkins jenkins 502673408 oct.   4 13:34 dc.h2.db
-rw-r--r-- 1 jenkins jenkins       123 oct.   4 13:34 dc.lock.db
-rw-r--r-- 1 jenkins jenkins     21535 août  12 05:57 dc.trace.db
```
Onyl dc.h2.db is really needed as the plugin only recreated it when I removed the three.
