### ISSUE TITLE
Documentation and report don't match code for `<failBuildOnCVSS/>`

### ISSUE THREAD

**Issue by lorenzoernesto** [dependency-check/DependencyCheck#878]
The text `One or more dependencies were identified with vulnerabilities that have a CVSS score greater than '6.9':` from the ouput of the Maven `check` goal and "Create the DependencyCheck-report.html and fail the build for CVSS greater than 8." from [example 3 of the usage documentation](https://jeremylong.github.io/DependencyCheck/dependency-check-maven/index.html#Example_3:) both indicate that the `<failBuildOnCVSS/>` configuration is a greater-than (>) check, but the [code](https://github.com/jeremylong/DependencyCheck/blob/master/dependency-check-maven/src/main/java/org/owasp/dependencycheck/maven/BaseDependencyCheckMojo.java#L1183) appears to be doing a greater-than-or-equal-to (>=) check.

The documentation and code should match.

I didn't do a pull-request because I wasn't sure whether the intention was greater-than or greater-than-or-equal.

**Comment by jeremylong** [comment]
Thanks for letting us know - this will be included in the next released.
