### ISSUE TITLE
Ignore specific types of metadata to improve accuracy

### ISSUE THREAD

**Issue by stevespringett** [dependency-check/DependencyCheck#88]
Some Java frameworks rely on metadata that is of no use to Dependency-Check and may contribute to an increase in false positives.

An example is Apache Felix and the use of the 'ipojo-components' tag in the manifest. This tag can be extremely long and contributes no useful information for the identification of the library, yet has the potential to mis-identify the library based on the tags contents.

Also of potential omission is anything containing 'classpath', for example 'Bundle-Classpath' used in OSGi.

**Comment by jeremylong** [comment]
The JarAnalyzer already ignores some nodes from the manifest. I'll look at
expanding this to ensure all classpath type entries are ignored.

--Jeremy

**Comment by jeremylong** [comment]
I improved the regex that looks for "classpath" like entries, added ipojo-components and ipojo-extensions to the list of entries to ignore. I am closing this issue until we find additional entry types we should be ignoring.
