### ISSUE TITLE
typo in warning-message

### ISSUE THREAD

**Issue by janmaterne** [dependency-check/DependencyCheck#887]
### Reporting Bugs/Errors
[INFO] --- dependency-check-maven:2.1.1:check (default) @ myProject ---
[WARNING] No analzer could be found for 'org.jboss.spec:jboss-javaee-6.0:pom:3.0.3.Final:provided' in project myProject
[INFO] Checking for updates
[INFO] starting getUpdatesNeeded() ...

There is a typo in the WARNING message:
s/analzer/analyzer/

**Comment by stefanneuhaus** [comment]
Appears to be fixed by #916.
