### ISSUE TITLE
FileNameAnalyzer.IGNORED_FILES should probably be extended

### ISSUE THREAD

**Issue by bentmann** [dependency-check/DependencyCheck#888]
The `FileNameAnalyzer` uses `IGNORED_FILES` to tell whether it should populate vendor and product evidence. I suspect this blacklist should be extended to exclude files which are pulled in by other analyzers but knowingly do never denote either vendor or product.

The following is a concrete suggestion for additions based on other analyzers:
- composer.lock
- configure.in
- configure.ac
- Gemfile.lock
- METADATA
- PKG-INFO
- package.json
- Package.swift

As is, the following evidence is reported for e.g. a Gemfile.lock which seems inappropriate/misleading:
````
"vendorEvidence": {
  "evidence": [
    {
      "name": "name",
      "source": "file",
      "value": "Gemfile",
      "used": true,
      "confidence": "HIGH"
    }
  ]
},
"productEvidence": {
  "evidence": [
    {
      "name": "name",
      "source": "file",
      "value": "Gemfile",
      "used": true,
      "confidence": "HIGH"
    }
  ]
},
````
![bogus-evidence](https://user-images.githubusercontent.com/138698/30613096-1ea4c9d8-9d87-11e7-8a44-bc74f637bc79.png)

**Comment by jeremylong** [comment]
Thank you for the suggestion.

**Comment by bentmann** [comment]
Thanks
