### ISSUE TITLE
How to read response result in jenkins plugin

### ISSUE THREAD

**Issue by javixeneize** [dependency-check/DependencyCheck#900]
Hi

I have noticed that when there are vulnerabilities detected, the build is marked as failed, but it doesnt break it

I would like to have the ability to break the build if the dependency check step returns a failed result

Is there any way i could i read this result? The analyse method doesnt return any value. If not, could it be a good enhancement to return this value?

Here are two examples of an OK and KO execution:

[DependencyCheck] Plug-in Result: Success - no threshold has been exceeded

DependencyCheck] Plug-in Result: Failed - <a href="dependency-check-jenkins-pluginResult">2 warnings</a> of <a href="dependency-check-jenkins-pluginResult/HIGH">priority High</a> exceed the threshold of 0 by 2

**Comment by javixeneize** [comment]
Hi

Any update on this please?

**Comment by stevespringett** [comment]
I don't think this is possible with the current Jenkins plugin structure. Publishers and Builders are decoupled from each other. The DT publisher does not rely on the DT builder and vice versa. So there's really no way to read in the results and utilize the Jenkins recorder functionality in a builder step.

However, you should be able to achieve similar functionality using a shell step in a job quite easily.

After the DC job executes, add a shell step that does something like this:

```bash
DCreport=dependency-check-report.xml
SearchString='<vulnerabilities>'

if grep -q $SearchString "$DCreport"; then
  echo Vulnerabilities Found. Breaking Build!!!
  exit 1
fi
```

I haven't actually tested this, but something similar should work.

**Comment by javixeneize** [comment]
Hm... it would not work if I have relaxed the number of errors to break the
build, but it gives me an idea

Anyway it would be a good addition to the plugin to break the build
immediately if the threshold is bypassed. As this is an input data for the
plugin it could be done

I will play with this sh script and let you know

Thanks!

**Comment by javixeneize** [comment]
Hi

I tested this and it works really well. But i still feel like it is a good improvement for the script

Thanks!
