### ISSUE TITLE
Data Source Logos

### ISSUE THREAD

**Issue by jeremylong** [dependency-check/DependencyCheck#903]
As more data-sources and/or external plugin integration (bundle-audit, nsp, etc.) are being considered for dependency-check - we need a better way to recognize these other tools and/or data sources.

An initial though is have the analyzers expose an optional logo (svn) and/or an attribution tag line. This would then be used in the HTML report to display a set of logos with the alt-text set to the attribution. This should be displayed in possibly to the right of the "scan information" section?  For other output formats the attribution tag line would be written out. Lastly, in the summary after the build the attribution tags (when present) should be output to the log/console.

**Comment by stevespringett** [comment]
I was recently headed down the same path with Dependency-Track and asked for SVG versions of the NVD logo. The request was denied with the following explanation:

> Unfortunately, we don't give out our logos for use as it's use implies endorsement or participation in a product or event. 

I agree we do need a better way of recognizing them, but we may need to do so without their logos.

**Comment by stevespringett** [comment]
This is currently how DTv3 presents this information: 
![dtv3_about](https://user-images.githubusercontent.com/3878933/31145380-3c283996-a849-11e7-82a3-81062cd583e8.png)
