### ISSUE TITLE
Enhance the introduction of `ecosystem` from PR #893

### ISSUE THREAD

**Issue by jeremylong** [dependency-check/DependencyCheck#904]
PR #893 started to introduce the concept of an ecosystem - so we could flag each dependency as being from a particular ecosystem.

Initial thought: an ecosystem registration process should be created in the core engine to create a set of ecosystems. To do this we could add `getEcosystem()` to the `Analyzer` interface.

Some future plans for the ecosystem concept is FP reduction. Several CVEs are obviously for a particular ecosystem (php, python, etc.). In those cases we could expand the NVD database to include the concept of ecosystem and being to mark the various CPE as belonging to a particular ecosystem. Then when we do CPE matching - if the ecosystems don't match we could reject the match.

Some of the things we should watch out for are [WebJars](https://www.webjars.org/) - which ecosystem would these get put into? Its a JAR file (which should get flagged as Java, but in reality it is just client side javascript). Thus, if/when we integrate retire.js and/or being scanning JS using a new custom analyzer we need to make sure that WebJars don't create false negatives (I don't think they will when we add a JS analyzer we should also consider JAR files an archive so that we can specifically scan for embedded JS).

**Comment by brianf** [comment]
I think the webjar one is a good model to consider. I could easily imagine that after processing, you might end up with a dependency for the webjar itself with evidence containing its coordinates etc. If you did deeper inspection of the jars and find js that has evidence, those might be separate dependencies with their own evidence. Then the ecosystem would be JS vs Java / Maven for those. My thought on the ecosystem was to reflect on the dependency and then it might help tune the search or display results accordingly.

**Comment by jeremylong** [comment]
This was included in the 5.0.0 release.
