### ISSUE TITLE
False positives: Windows file identification needs more elements for decision making

### ISSUE THREAD

**Issue by randomstability** [dependency-check/DependencyCheck#907]
I'm really not sure how to classify this issue, but based on a scan of my Windows computers "Program Files", it led to lots of false positives.    **I know this isn't a realistic use case, but I feel it reveals some concerns regarding detection accuracy.**

Upon researching a few of them,  it seems like the "evidence" consists solely of the file name. And that didn't really line up with the identified CPE.  This matching alone should be revised, or have some flag to require more evidence.

At the very least, this Windows file parser should be including other common items like "digital signature", "file version", "copyright" or "company name" in its "evidence".  This seems like it would have greatly reduced the false positives.

I am completely unaware of the projects capability to scan "any" exe/dll, but if the intent is only to scan a limited technical set of them, you may want to includes ways to isolate that set as a first step in the scan.

**Examples for false positive:**

**Example 1:**

**File Path:** C:\Program Files (x86)\Adobe\Acrobat Reader DC\Reader\AcroCEF\RdrServicesUpdater.exe

**Evidence:** File name: RdrServicesUpdater

**Identifiers** cpe: cpe:/a:services_project:services:-   Confidence:LOW

My analysis - The only thing similar between the file found and the CPE, is the word "services".  That is a crazy poor association.  But I don't know how this is actually determined.

**Microsoft Office FPs:**
There were a ton of FPs related to the ADDINS directory.  These seemed to mis-identify the product and its version by only matching a portion of the "grokassembly product" value.

**File Path:**  C:\Program Files (x86)\Microsoft Office\Office16\ADDINS\PowerPivot Excel Add-in\fi\Microsoft.AnalysisServices.Excel.Common.FrontEnd.resources.dll
**Evidence:** grokassembly, product:  Microsoft.AnalysisServices.Excel.BackEnd.resources
**Identifiers** cpe: cpe:/a:microsoft:excel:11.0.0.0   Confidence:LOW

I don't know that this issue is directly actionable,  but I'm fairly confident that addressing each individual false positive is the wrong thing to do.

I would like to have the ability to tighten up the detection engine to better match these fields.  Some flag to say "exact product name match" or something.

Possibly using "CPE Confidence" as a filter also for results seems a reasonable first step in this effort.

I also think that a scan like this (for Windows "Program Files") is a simple test that can be performed to identify the progress on false positive prevention.

**Comment by jeremylong** [comment]
ODC can only scan .NET assemblies. There are still a high number of FP as I currently do not have a .NET development environment to do the necessary testing - but resolving a large portion of the FP would be fairly easy (if one had the environment with nuget, etc. setup).

As to using other properties from the DLL - that is what the grok assembly tool does (an embedded .NET exe in dependency-check). The grok assembly tool is called on each .NET assembly to extract the extended property information and use that as evidence for product identification.

The use case of scanning `Program Files` is not really supported as most of these will not be .NET assemblies. The intended use of dependency-check is to analyze your build artifacts (final exe/dll and dependent dlls).

I'll have to consider whether or not none .NET exe/dll should be excluded entirely.

**Comment by jeremylong** [comment]
The grok assembly utility was improved to include additional evidence as part of the 5.0.0 release.
