### ISSUE TITLE
Jenkins plugin detects spring-context-support-3.0.7 but cli version does not

### ISSUE THREAD

**Issue by pachulo** [dependency-check/DependencyCheck#917]
I'm using version 2.1.1 and having a problem with DependencyCheck. It seems like the command line tool is not detecting a dependency but the Jenkins plugin does detect it.

The dependency is `spring-context-support-3.0.7.RELEASE.jar` and if I execute the `dependency:tree` goal in my local machine, where the cli is not detecting it, I can see it in multiple modules:

```
$ mvn dependency:tree | grep -B6 spring-context-support -
[INFO] |  +- aopalliance:aopalliance:jar:1.0:compile
[INFO] |  +- org.springframework:spring-beans:jar:3.0.7.RELEASE:compile
[INFO] |  \- org.springframework:spring-core:jar:3.0.7.RELEASE:compile
[INFO] |     \- commons-logging:commons-logging:jar:1.1.1:compile
[INFO] +- org.springframework:spring-test-mvc:jar:1.0.0.M2:test
[INFO] |  +- org.springframework:spring-webmvc:jar:3.0.7.RELEASE:test
[INFO] |  |  \- org.springframework:spring-context-support:jar:3.0.7.RELEASE:test
--
[INFO] +- org.directwebremoting:dwr:jar:3.0.0-RELEASE:compile
[INFO] +- net.sf.json-lib:json-lib-ext-spring:jar:1.0.2:compile
[INFO] |  +- net.sf.json-lib:json-lib:jar:jdk15:2.2.2:compile
[INFO] |  |  +- commons-beanutils:commons-beanutils:jar:1.7.0:compile
[INFO] |  |  \- net.sf.ezmorph:ezmorph:jar:1.0.4:compile
[INFO] |  +- org.springframework:spring-webmvc:jar:3.0.7.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-context-support:jar:3.0.7.RELEASE:compile
--
[INFO] |  +- org.directwebremoting:dwr:jar:3.0.0-RELEASE:compile
[INFO] |  \- net.sf.json-lib:json-lib-ext-spring:jar:1.0.2:compile
[INFO] |     +- net.sf.json-lib:json-lib:jar:jdk15:2.2.2:compile
[INFO] |     |  +- commons-beanutils:commons-beanutils:jar:1.7.0:compile
[INFO] |     |  \- net.sf.ezmorph:ezmorph:jar:1.0.4:compile
[INFO] |     +- org.springframework:spring-webmvc:jar:3.0.7.RELEASE:compile
[INFO] |     |  \- org.springframework:spring-context-support:jar:3.0.7.RELEASE:compile
--
[INFO] |  +- com.xxxx.xxxx.xxxx:dwr:jar:12.9.2-SNAPSHOT:compile
[INFO] |  |  +- org.directwebremoting:dwr:jar:3.0.0-RELEASE:compile
[INFO] |  |  \- net.sf.json-lib:json-lib-ext-spring:jar:1.0.2:compile
[INFO] |  |     +- net.sf.json-lib:json-lib:jar:jdk15:2.2.2:compile
[INFO] |  |     |  \- net.sf.ezmorph:ezmorph:jar:1.0.4:compile
[INFO] |  |     +- org.springframework:spring-webmvc:jar:3.0.7.RELEASE:compile
[INFO] |  |     |  \- org.springframework:spring-context-support:jar:3.0.7.RELEASE:compile
--
[INFO] |  +- com.xxxx.xxxx.xxxx:dwr:jar:12.9.2-SNAPSHOT:compile
[INFO] |  |  +- org.directwebremoting:dwr:jar:3.0.0-RELEASE:compile
[INFO] |  |  \- net.sf.json-lib:json-lib-ext-spring:jar:1.0.2:compile
[INFO] |  |     +- net.sf.json-lib:json-lib:jar:jdk15:2.2.2:compile
[INFO] |  |     |  \- net.sf.ezmorph:ezmorph:jar:1.0.4:compile
[INFO] |  |     +- org.springframework:spring-webmvc:jar:3.0.7.RELEASE:compile
[INFO] |  |     |  \- org.springframework:spring-context-support:jar:3.0.7.RELEASE:compile

...
```

I can also see the jar downloaded:

```
$ find . -iname spring-context-support-3.0.7*
./bo-webapp/target/bo-webapp/WEB-INF/lib/spring-context-support-3.0.7.RELEASE.jar
./portal-demo/target/portal-demo-webapp/WEB-INF/lib/spring-context-support-3.0.7.RELEASE.jar
./portal-demo/target/war/work/com.xxxx.xxxx.xxxx/new-new-portal/WEB-INF/lib/spring-context-support-3.0.7.RELEASE.jar
```

But the dependency does not appear in the HTML report created by this command:

```
$ dependency-check --project test --connectionString jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=oracle-scan.dummy.net)(Port=1521))(CONNECT_DATA=(SERVICE_NAME=DEV12DB))) --dbDriverName oracle.jdbc.OracleDriver --dbDriverPath ~/Software/tools/ojdbc7.jar --dbUser OWASP --dbPassword XXXXXX --format HTML --noupdate
 --scan .
```

I'm:
* Using the same DependencyCheck DDBB version:
```
NVD CVE 2002: 21/09/2017 09:13:36
NVD CVE 2003: 29/08/2017 09:31:01
NVD CVE 2004: 17/08/2017 09:29:57
NVD CVE 2005: 16/09/2017 09:25:56
NVD CVE 2006: 03/09/2017 09:26:27
NVD CVE 2007: 08/09/2017 09:27:55
NVD CVE 2008: 08/09/2017 09:25:36
NVD CVE 2009: 19/09/2017 09:29:07
NVD CVE 2010: 26/09/2017 10:22:42
NVD CVE 2011: 26/09/2017 10:22:42
NVD CVE 2012: 26/09/2017 10:22:42
NVD CVE 2013: 22/09/2017 09:14:33
NVD CVE 2014: 26/09/2017 10:22:41
NVD CVE 2015: 26/09/2017 10:22:42
NVD CVE 2016: 26/09/2017 10:22:41
NVD CVE 2017: 26/09/2017 10:22:41
NVD CVE Checked: 26/09/2017 13:46:17
NVD CVE Modified: 26/09/2017 10:22:41
VersionCheckOn: 1505472782669
```
* Analyzing the exactly same source code
* Using the same version of Maven (3.5.0)
* Using Java 8 (u112 in Jenkins vs u144 in my local machine though)

On both sides...Am I missing something?

By the way, in my local machine I'm using Ubuntu 16.04 and the Jenkins version is 2.69

Thanks!

**Comment by jeremylong** [comment]
I believe I know what is going on with this and if I'm correct the fix will be published with 3.0.0. Couple of questions - is Jenkins using the dependency-check-maven plugin?

What I believe is happening is that the using the CLI the Central Analyzer is silently failing (fixed in 3.0.0). As such, when you use the CLI dependency-check may not be able to determine the GAV. As the GAV is not present on the single spring-context-support jar when the DependencyBundlingAnalyzer executes the spring-context-support.jar is not bundled into a single entry with the other spring jars.   The DependencyBundlingAnalyzer takes related jars (spring is one of the best examples) and bundles them into a single entry - in the HTML report if you expand the related JARs you will see the others listed.

In the report produced by the Jenkins execution - can you tell me if the spring-context-support.jar is actually contained in a related dependency section?  (might be easier to just search the HTML)

**Comment by pachulo** [comment]
Hi @jeremylong ! Thanks for the info!

Then if I understood it correctly, the Jenkins version of the report is the "correct" one, isn't it?

Regarding the questions:
1. No, Jenkins is not using the dependency-check-maven plugin.
2. On the Jenkins report, spring-context-support is contained as a related dependency only in it's own entry (SPRING-CONTEXT-SUPPORT-3.0.7.RELEASE.JAR)

By the way, is there any workaround for this before version 3.0.0 is released?

**Comment by jeremylong** [comment]
Its hard for me to say which is truly the correct one without having the reports - but from the information above, I would bet on the Jenkins report being the correct one.

Unfortunately, there is no workaround until 3.0.0 is released (within a week).
