### ISSUE TITLE
Suppression File in 1.1.3 command line

### ISSUE THREAD

**Issue by Francois-Royer** [dependency-check/DependencyCheck#92]
Suppression file is not taken into account when supplied on command line. 
It works fine with 1.1.2.

**Comment by jeremylong** [comment]
Sorry about that. This bug has been fixed in 1.1.4-SNAPSHOT; the team is
doing some final testing to release the version with this fix (and updated
test cases so this bug doesn't get re-introduced later).

Best Regards,

Jeremy
