### ISSUE TITLE
Supression of cpe with regex does not appear to work

### ISSUE THREAD

**Issue by rshanlever** [dependency-check/DependencyCheck#922]
My suppression file includes the following
`
<suppress>
	<notes><![CDATA[
      Liferay findings should not be reported here
      ]]></notes>
		<cpe regex="true">^cpe:\/a:liferay</cpe>
</suppress>`

But I am still getting findings with the following identifiers

(cpe:/a:liferay:liferay:6.2.10.15)||(cpe:/a:liferay:liferay_enterprise_portal:1.0)||(cpe:/a:liferay:liferay_portal:6.2.x_ee)||(cpe:/a:liferay:liferay_portal_enterprise:6.2.10.15)||(cpe:/a:liferay:portal:6.2.10.15)

Other suppression entries using a CPE that aren't regex are working as expected.  Example:

	<suppress>
		<notes><![CDATA[
      file name: com.ibm.mq-5.300.jar
      ]]></notes>
		<cpe>cpe:/a:ibm:websphere_mq:5.300</cpe>
	</suppress>

**Comment by jeremylong** [comment]
The regex provided does not match the entire CPE.  Add a `.*` to the end of your regex:

```xml
<suppress>
  <notes><![CDATA[ Liferay findings should not be reported here ]]></notes>
  <cpe regex="true">^cpe:\/a:liferay.*</cpe>
</suppress>
```
