### ISSUE TITLE
Springboot false possitives

### ISSUE THREAD

**Issue by javixeneize** [dependency-check/DependencyCheck#926]
Hi

I am having a lot of vulnerabilities reported in springboot and i have checked with springboot team about those

Apparently all of them are false possitives. It is perfectly explained in this issue i have open there -- https://github.com/spring-projects/spring-boot/issues/10620

Having said that, and given that springboot is a massively used framework, could a rule to ignore those CVEs when they are under springboot 1.5.7 (or higher) be added?

Thanks

**Comment by jeremylong** [comment]
In the future I would suggest searching the issues list as this was previously reported (#866). Unlike many other FP - this one is going to take a bit more work to resolve. The resolution to this will be tracked in #866.
