### ISSUE TITLE
integrated security

### ISSUE THREAD

**Issue by NickHarvey2** [dependency-check/DependencyCheck#927]
https://github.com/jeremylong/DependencyCheck/blob/e2a97738e176fd9bb7042f1f53a024c7c011460c/dependency-check-core/src/main/java/org/owasp/dependencycheck/data/nvdcve/ConnectionFactory.java#L156

I think this may need to be "integratedsecurity" instead of "integrated security"

Thanks again for adding this!

**Comment by jeremylong** [comment]
@NickHarvey2 `Integrated Security=true` is the correct syntax. I copied the `integrated security` and `trusted_connection` directly from the connection string documentation.

**Comment by NickHarvey2** [comment]
ah. okay. I know my team has a number of apps that use the version without the space in the connection string, but I guess either must work.
