### ISSUE TITLE
Consistency/comparison issues in domain classes

### ISSUE THREAD

**Issue by stefanneuhaus** [dependency-check/DependencyCheck#928]
- VulnerableSoftware
  - compareTo() is inconsistent with equals(): though this is no MUST requirement, the javadoc indicates that it is strongly recommended and classes that violate this SHOULD clearly indicate it. As the compareTo() logic needs to be rather sophisticated, equals() could fallback to this like `compareTo() == 0`. Example of inconsistency:
```
    @Test
    public void testEqualsAndHashCode() {
        VulnerableSoftware instance1 = new VulnerableSoftware();
        instance1.setCpe("cpe:/a:mortbay:jetty:6.1");
        VulnerableSoftware instance2 = new VulnerableSoftware();
        instance2.setCpe("cpe:/a:mortbay:jetty:6-1");

        assertEquals(0, instance1.compareTo(instance2));
        assertEquals(instance1, instance2);
    }
```

- Dependency
  - equals()/hashCode(): contract violation as only equals() respects `packagePath`.
  - compareTo() is inconsistent with equals()
    - compareTo() merely respects `filePath`.
    - compareTo() compares case-insensitive, while equals() is case-sensitive.

- Identifier
  - compareTo() is inconsistent with equals() as only equals() respects `type`.
  - compareTo() SHOULD throw a NullPointerException when comparing with `null`.

- Evidence
  - compareTo() SHOULD throw a NullPointerException when comparing with `null`.

- DependencyVersion
  - if have not looked for an inconsistency example, but it looks at least fragile:  equals() and compareTo() have different sophisticated implementations, hashCode() just relies on `versionParts`
  - no contract violation, but a bit odd: compareTo() is not connected to the implementation of VulnerableSoftware. Not sure if this can cause unexpected results. See also issue #929.

To me it seems like not all classes need to implement Comparable. If this is actually the case, I would rather refrain from it to prevent these kind of issues. Especially as objects of these classes are not immutable while also being part of ordered collections, it is not easy to ensure consistency. In fact objects are being mutated in various places.

Also Dependency inherits from EvidenceCollection, which can complicate things when correctly implementing equals()/hashCode()/Comparable or maintaining thread-safety. Falling back to composition looks like an easy win here, as EvidenceCollection is package-private and not used anywhere else.

The VulnerabilityComparator can be discarded. It is merely used in the Dependency class to maintain a `SortedSet<Vulnerability>`. But as it defines the same ordering as the natural ordering of Vulnerability, it can be simply omitted here.

**Comment by jeremylong** [comment]
Truly appreciate your analysis on this - I'll have to dig into this and figure out the reason I had purposely made the `compareTo()` different then `equals()` in a few cases.  The reasons may no longer be valid and there is, as you pointed out, a lot of cleanup that should be done around this.

**Comment by jeremylong** [comment]
Changes so far:

* Removed the usage of TreeSet which is where some of the `compareTo()` methods were used.
* `Dependency` - removed the compareTo() and fixed equals and hash to be equal.
* `Identifier` - `compareTo()` now includes the `type` and throws an NPE when comparing a null
* `Evidence` - `compareTo()` now throws an NPE when comparing a null.

These changes are in the [compare-cleanup](https://github.com/jeremylong/DependencyCheck/tree/compare-cleanup) branch.

**Comment by jeremylong** [comment]
I believe the issue with the compareTo methods have been resolved.
