### ISSUE TITLE
Unable to connect to the database (Jenkins)

### ISSUE THREAD

**Issue by stevespringett** [dependency-check/DependencyCheck#930]
With 3.0.0, the Jenkins plugin can no longer connect to the database. Changes made in https://github.com/jeremylong/DependencyCheck/commit/04dc5f84912e4cc2f48aced0007e6c4ffecfb278#diff-278a633795a884354bdf48f396801f45 no longer force loading of the JDBC driver when using the default H2 database.

As a hack, the Jenkins plugin has to force loading of the driver in order to perform scans. Specifically: 
```java
try {
    DriverLoader.load("org.h2.Driver");
} catch (DriverLoadException e) {
    //
}
```

This functionality needs to be re-implemented in the core as it will affect every ODC integration including Jenkins, Dependency-Track, and any other application that uses the core module.

**Comment by jeremylong** [comment]
Is this a blocker?

**Comment by stevespringett** [comment]
Not a blocker, as I have a workaround in place. But I think we should correct this for 3.0.1

**Comment by stevespringett** [comment]
Jenkins plugin v3.0.1 has been pushed to the Jenkins update site.
