### ISSUE TITLE
Jenkins plugin V3.0.0 connects to mavencentral?

### ISSUE THREAD

**Issue by javixeneize** [dependency-check/DependencyCheck#932]
Hi

Im having this error when running the new version 3.0.0

[DependencyCheck] One or more exceptions were thrown while executing Dependency-Check
[DependencyCheck] Exception Caught: org.owasp.dependencycheck.analyzer.exception.AnalysisException
[DependencyCheck] Cause: Finally failed connecting to Central search. Giving up after 5 tries.
[DependencyCheck] Message: Could not connect to Central search. Analysis failed.
[DependencyCheck] org.owasp.dependencycheck.analyzer.exception.AnalysisException: Could not connect to Central search. Analysis failed.
[DependencyCheck] Caused by: java.io.IOException: Could not connect to MavenCentral (403): Forbidden

I am behind a proxy, so this error makes sense, but the previous dependency check versions were not connecting to mavencentral

Why is it connecting there now?

Thanks

**Comment by jeremylong** [comment]
Actually, the connection was always attempted - in previous versions it silently failed (even when no proxy was involved if Central returned a 500). 3.0.0 corrected this behavior - so if you do not wish to include the central analyzer you need to disable it; if you do want to use it (which I would highly recommend as it improves accuracy) you need to configure a proxy - alternatively, if you had Nexus Pro you could use that instead of Central. We are planning on including an Artifactory analyzer in the future as well.

**Comment by javixeneize** [comment]
Makes sense... If i am using a local nexus repository, could i reference to it, or it needs to be the official nexus?

Regarding maven central, is it connecting to https://search.maven.org/?

Thanks

**Comment by davidkarlsen** [comment]
@jeremylong Do you have any alternative when running nexus pro v.3.x - the nexus alternative only works for v2.x

**Comment by jeremylong** [comment]
@davidkarlsen Unfortunately I don't have a Nexus Pro instance to test against. The Nexus analyzer was contributed. PRs are welcome...

@javixeneize apparently, if you have a local Nexus Pro v2.x you can configure the url and enable the NexusAnalyzer; at the same time you should likely disable the central analyzer.

**Comment by javixeneize** [comment]
Hi

Which is the expected url for nexus analyser?

Imagine i have 

https://nexus.mylocal.com/repository/maven-releases/com/whatever/project/....

What is the url the analyser expects? Its continuously giving me errors

Thanks

**Comment by javixeneize** [comment]
Hi

What is the exact nexus url i should configure in jenkins?

Thanks

**Comment by jeremylong** [comment]
Checking the [documentation](https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html) - it looks like you need to configure the url to point to the Nexus Server's REST API Endpoint "http://domain/nexus/service/local".

**Comment by ashishnm** [comment]
@jeremylong I am using automated process to create and configure jenkins server. I am installing this plugin using scripts, I am facing same issue, how can i configure or disable maaven central analyzer option to false, I am using groovy.

**Comment by jeremylong** [comment]
@ashishnm I am going to push a new release this week (today/tomorrow).  Without actually seeing your scripts I wouldn't have a clue how to assist you.

**Comment by javixeneize** [comment]
Hi

I think the main problem here is that  it needs to pro version of nexus and
it doesnt work with the standard version

Thanks

**Comment by ashishnm** [comment]
@jeremylong when you are going to publish version 3.0.2 in jenkins repo? I have updated to 3.0.1.
My pipeline code is like 
 dependencyCheckAnalyzer datadir: '', hintsFile: '', includeCsvReports: false, includeHtmlReports: false, includeJsonReports: false, includeVulnReports: false, isAutoupdateDisabled: false, outdir: '', scanpath: 'facebook-connector/target/facebook-connector-1.0.1.jar', skipOnScmChange: false, skipOnUpstreamChange: false, suppressionFile: '', zipExtensions: ''

 dependencyCheckPublisher canComputeNew: false, canRunOnFailed: true, defaultEncoding: '', healthy: '0', pattern: '', unHealthy: '1000'

also I am trying to scan python files and getting with 0 unique warnings and 0 duplicates. Does this plugin scanning for python working fine. It is also pipeline syntax. 

dependencyCheckAnalyzer datadir: '', hintsFile: '', includeCsvReports: false, includeHtmlReports: false, includeJsonReports: false, includeVulnReports: false, isAutoupdateDisabled: false, outdir: '', scanpath: 'bottle/src/bottle/**/*.py', skipOnScmChange: false, skipOnUpstreamChange: false, suppressionFile: '', zipExtensions: ''
          dependencyCheckPublisher canComputeNew: false, defaultEncoding: '', healthy: '0', pattern: '', unHealthy: '1000'

**Comment by jeremylong** [comment]
3.0.2 should already be released for Jenkins.

Jeremy

**Comment by javixeneize** [comment]
Yes, it is released. I’m already using it

There is another bug. When you analyze a models package it gives an error
in the ruby analyser (...?)

Disabling ruby analyser it works fine
