### ISSUE TITLE
Temporary files generated in Jenkins

### ISSUE THREAD

**Issue by javixeneize** [dependency-check/DependencyCheck#934]
Hi

I have seen that dependencyCheckPublisher step generates a folder in the build called "workspace-files".

Inside there, there are 2 tmp files taking 14MB of space

Since it is not a big deal for a single job, if dep check is run 100 times, it will waste 1,4 GB of space

Are those files needed for anything? If not, i think the plugin should remove those files

Thanks

**Comment by stevespringett** [comment]
This directory is defined by the Jenkins Analysis Core plugin used by FindBugs, PMD, Checkstyle, Dependency-Check, Twistlock, and all other plugins built on Analysis Core.

https://github.com/jenkinsci/analysis-core-plugin/blob/master/src/main/java/hudson/plugins/analysis/util/model/AbstractAnnotation.java

This directory stores data related to trendings, warnings (vulnerabilities in dependency-check), and other relevant data needed to display the results in the Jenkins console and display information in the optional dashboard plugin.

Use Jenkins's ability to limit the number of builds kept for a specific job. I usually only keep the last 10 builds or so. All previous builds are automatically deleted by Jenkins.
