### ISSUE TITLE
dependency-check-maven 3.0.1 not available in maven central

### ISSUE THREAD

**Issue by digitalLumberjack** [dependency-check/DependencyCheck#935]
Hi, the version 3.0.1 of dependency-check-maven is not available in maven central:
https://mvnrepository.com/artifact/org.owasp/dependency-check-maven

Is there an other repository to use, or can it be uploaded ?

**Comment by Stephan202** [comment]
@digitalLumberjack that `mvnrepository.com` website uses a cached version of Maven Central. Version 3.0.1 [_is_](https://repo1.maven.org/maven2/org/owasp/dependency-check-maven/3.0.1/) already available.

**Comment by digitalLumberjack** [comment]
Thanks, sorry for this useless issue :)
