### ISSUE TITLE
Nist mirroring didn't works anymore

### ISSUE THREAD

**Issue by hgomez** [dependency-check/DependencyCheck#94]
Hi all,

We're using internal mirroring of NIST databases (XML) and it didn't works since 
We get 404 for URLs like
- http://nvd.nist.gov/download/nvdcve-modified.xml
- http://static.nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-modified.xml
- http://static.nvd.nist.gov/feeds/xml/cpe/dictionary/official-cpe-dictionary_v2.2.xml.gz
- http://static.nvd.nist.gov/feeds/xml/cpe/dictionary/official-cpe-dictionary_v2.2.meta
- http://nvd.nist.gov/download/nvdcve-$CURR_YEAR.xml
- http://static.nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-$CURR_YEAR.xml

**Comment by hgomez** [comment]
I just did a new try and URL are back.
Any informations on your side  ?

**Comment by jeremylong** [comment]
Not sure I am completely understanding your question. Are you saying the
data from nvd.nist.gov was unavailable temporarily? I've seen that happen
from time to time; but it has generally been temporary.

--Jeremy
