### ISSUE TITLE
Feature request: Changelog/Release notes

### ISSUE THREAD

**Issue by Hipapheralkus** [dependency-check/DependencyCheck#948]
Hi,
I'm following the DependencyCheck updates, however I'm not aware of there being some "easy-to-read" changelog/release notes. For example, which changes were implemented in the major release 3.0.0, or the next 3.0.1 release. Is it possible there would be some file with changelog crated? For example something like portswigget has for each version of Burp [http://releases.portswigger.net/].
Thanks

**Comment by jeremylong** [comment]
ATM - the notes have been part of the release announcements: https://groups.google.com/forum/#!forum/dependency-check

I'll work on putting them into the [gh-site](https://jeremylong.github.io/DependencyCheck/).

**Comment by jeremylong** [comment]
Release notes have been added to the repo.
