### ISSUE TITLE
Support for wildcard in scanPath

### ISSUE THREAD

**Issue by Francois-Royer** [dependency-check/DependencyCheck#95]
Even if it's possible to add as many scanPath as needed, it would be easier to use wildcard in the following use case:

-the path contains a version number that may change.
-the path contains files/folder we don't want to scan.

**Comment by jeremylong** [comment]
For the files/folders you don't want to scan would you want a
'--exclude=something.jar' as an option too?

--Jeremy

**Comment by Francois-Royer** [comment]
Hi Jeremy,

I didn't think of excluding but more adding with finer criteria. For exemple, I have a maven target folder that contain files I want to scan and others I don't want.

With current version I have to set scanpath to "project/target" folder.

What I would like to do instead is set scanpath to "project/target/*.zip" so I scan only zip files in target and not other contents 
Is it make sense ?

but an --exclude=something*.jar can be usefull also, depending on the use case (more to exclude or more to add)

May be a ant fileset syntax/library can be use

**Comment by jeremylong** [comment]
This has been committed to 1.1.4-snapshot. Hoping to release this weekend.

--Jeremy

**Comment by Francois-Royer** [comment]
Thanks a lot Jeremy, my team will be very happy with this feature !
