### ISSUE TITLE
Exception occurred initializing Ruby Bundle Audit Analyzer

### ISSUE THREAD

**Issue by githubhs17** [dependency-check/DependencyCheck#953]
I got "Exception occurred initializing Ruby Bundle Audit Analyzer" when using docker image owasp/dependency-check and running an OWASP scan with docker run . . .

see
https://gist.github.com/githubhs17/df2978236f04f39bcc74f2eff8620caf

**Comment by jeremylong** [comment]
I just updated the docker file with mono and ruby. If you pull the latest it should work without error now.

**Comment by githubhs17** [comment]
'Thanks for the fast response, but I got the same error. And on the docker hub I see that the last build failed:
https://hub.docker.com/r/owasp/dependency-check/

**Comment by jeremylong** [comment]
Regarding the docker failure you are experiencing. Can you clear your image cache `ocker image rm owasp/dependency-check:latest` and then try running the docker command again adding `--log /report/dc.log`? If it fails again can you please provide the command you are using to run the docker image and the dc.log file?

**Comment by githubhs17** [comment]
The exception "Exception occurred initializing Ruby Bundle Audit Analyzer. / Exception from bundle-audit process: java.io.IOException: Cannot run program "bundle-audit"...." is gone away, but on the end there is always "Error generating the report for prod-authoring-homepage-ui".

For output and the used docker command see:
https://gist.github.com/githubhs17/3374dc7f17c5849785963817a707a5a5

dc.log is uploaded to
https://github.com/jeremylong/DependencyCheck/files/1417706/dc.log

**Comment by jeremylong** [comment]
It doesn't look like you included an output directory.  Try:

```bash

docker run --rm \
  -v /home/jenkins-master/workspace/uthoring-homepage-ui_master-ABB6MRTJCJFYQJAREUZ2HMYWMGGTBQGM4QK5NYJP4EYMV67SFQ5A:/src \
  -v /tmp:/usr/share/dependency-check/data \
  -v /report:/report \
  owasp/dependency-check \
  --scan /src \
  --project prod-authoring-homepage-ui \
  --format ALL \
  --suppress /src/.pipeline/scanreports/owasp-suppress.xml \
  --out /report \
  --log /report/dc.log \
```

Also - I would not recommend mapping the data directory to `tmp`. If you actually had the data directory saved between scans/overtime the scans will go much quicker and not need to pull as much data down from the NVD each time you run.

**Comment by githubhs17** [comment]
Now I got following error:
07:17:44 + docker pull owasp/dependency-check
07:17:44 Using default tag: latest
07:17:45 latest: Pulling from owasp/dependency-check
07:17:45 Digest: sha256:308cfcd27ecca17943bbb489e53c22ba827bb01357f1773d09bb6ff8d6df84d6
07:17:45 Status: Image is up to date for owasp/dependency-check:latest
[Pipeline] sh
07:17:45 [uthoring-homepage-ui_master-ABB6MRTJCJFYQJAREUZ2HMYWMGGTBQGM4QK5NYJP4EYMV67SFQ5A] Running shell script
07:17:45 + docker run --rm -v /home/jenkins-master/workspace/uthoring-homepage-ui_master-ABB6MRTJCJFYQJAREUZ2HMYWMGGTBQGM4QK5NYJP4EYMV67SFQ5A:/home/jenkins-master/workspace/uthoring-homepage-ui_master-ABB6MRTJCJFYQJAREUZ2HMYWMGGTBQGM4QK5NYJP4EYMV67SFQ5A -v /report:/report -w /home/jenkins-master/workspace/uthoring-homepage-ui_master-ABB6MRTJCJFYQJAREUZ2HMYWMGGTBQGM4QK5NYJP4EYMV67SFQ5A owasp/dependency-check --scan /home/jenkins-master/workspace/uthoring-homepage-ui_master-ABB6MRTJCJFYQJAREUZ2HMYWMGGTBQGM4QK5NYJP4EYMV67SFQ5A --project prod-authoring-homepage-ui --format ALL --suppress /src/.pipeline/scanreports/owasp-suppress.xml --out /report --log /report/dc.log
07:37:57 [WARN] Unable to update Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.
07:37:57 [ERROR] No documents exist
07:37:57 
07:37:57 Unable to continue dependency-check analysis.
07:37:57 [ERROR] One or more fatal errors occurred
07:37:57 [ERROR] Unable to obtain an exclusive lock on the H2 database to perform updates
07:37:57 [ERROR] No documents exist

see
https://gist.github.com/githubhs17/2a2e22c654f1a58613b4a17ce7eb10f1

**Comment by jeremylong** [comment]
Have you considered actually using the command I provided above?  You are getting this error because you did not map the data directory:

```
-v /tmp:/usr/share/dependency-check/data 
```

My point about the data directory is that you likely shouldn't map it to `\tmp` as this will contain persistent data that will make future invocations of dependency check faster.
