### ISSUE TITLE
Getting "No Document Exists" when running command line check (follow up to #938)

### ISSUE THREAD

**Issue by MGase401412** [dependency-check/DependencyCheck#955]
Hi Jeremy,
I corrected the urls and still have the same issue using the windows command line.

1.	Here’s the command I am running
dependency-check.bat --log "c:\log\log.txt" --cveUrl12Modified "https://nvd.nist.gov/download/nvdcve-Modified.xml.gz" --cveUrl20Modified "https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-Modified.xml.gz" --cveUrl12Base "https://nvd.nist.gov/download/nvdcve-%d.xml.gz" --cveUrl20Base "https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-%d.xml.gz" -project "APPID-152345" --scan "K:\C68204\Private-COEUseOnly\APPID-152345_ ARG_CCR"
2.	I can use my local browser to connect to the urls and download the files
3.	The log file is attached.

Can you tell me more specifically what is failing to load?

[log.txt](https://github.com/jeremylong/DependencyCheck/files/1412227/log.txt)

**Comment by jeremylong** [comment]
The failure looks like you are behind a proxy (which may be configured in your browser already).
Can you run `dependency-check.bat --purge` - just to clear out any old data from earlier failures. As you are using the default URLs there is no need to configure the --cveUrl... arguments. try running dependency-check one more time after the purge. My guess is that the error message will more explicitly point to a possible proxy issue.

**Comment by MGase401412** [comment]
Thanks Jeremy, I will work with our networking team.
