### ISSUE TITLE
Comparison method violates its general contract

### ISSUE THREAD

**Issue by matt-shaw** [dependency-check/DependencyCheck#956]
Hi,

We're using OWASP dependency checker 3.0.1, Java8, Maven 3.5.0.  We previously used version 2.1.1 and it worked ok.

When we run our automated build we get the following warnings in the log;

00:36:14 [INFO] Analysis Started
00:36:14 [WARNING] An unexpected error occurred during analysis of 'e:\MvnRepo\org\jogamp\jogl\jogl-all-main\2.3.2+2-lcd\jogl-all-main-2.3.2+2-lcd-natives-windows-amd64.jar' (Archive Analyzer): Comparison method violates its general contract!
00:36:20 [INFO] Finished Archive Analyzer (6 seconds)
00:36:20 [INFO] Finished File Name Analyzer (0 seconds)
00:36:25 [INFO] Finished Jar Analyzer (4 seconds)
00:36:26 [INFO] Finished Assembly Analyzer (1 seconds)
00:36:26 [INFO] Finished Dependency Merging Analyzer (0 seconds)
00:36:26 [INFO] Finished Version Filter Analyzer (0 seconds)
00:36:26 [INFO] Finished Hint Analyzer (0 seconds)
00:36:28 [INFO] Created CPE Index (1 seconds)
00:36:28 [INFO] Finished CPE Analyzer (1 seconds)
00:36:28 [INFO] Finished False Positive Analyzer (0 seconds)
00:36:28 [INFO] Finished Cpe Suppression Analyzer (0 seconds)
00:36:28 [INFO] Finished NVD CVE Analyzer (0 seconds)
00:36:29 [INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
00:36:29 [INFO] Finished Dependency Bundling Analyzer (0 seconds)
00:36:46 [INFO] Analysis Complete (31 seconds)
00:36:46 [WARNING] 

Then the build fails with the following error;

00:36:48 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.6:site (default-site) on project ao-ui: Error generating dependency-check-maven:3.0.1:aggregate: One or more exceptions occurred during dependency-check analysis: One or more exceptions occurred during dependency-check analysis
00:36:48 [ERROR] Comparison method violates its general contract!

Is this a bug in the OWASP dependency checker?, why does a warning cause a build failure?  What does this error text mean?

Many thanks

Matt

**Comment by jeremylong** [comment]
This is related to issue #928 (which has a good writeup of the problem). As to the warning message - in reality, that warning message should have been an error message - that is an easy fix.

Until we are able to release a fix for issue #928 you can likely just configure `<failOnError>false</failOnError>`

**Comment by matt-shaw** [comment]
Hi Jeremy,

Thanks for the feedback.  If I set that to false will genuine security issues with libraries still fail the build or is that a separate setting?

Thanks

**Comment by jeremylong** [comment]
If you have the following configuration the build will fail if vulnerable dependencies are identified - but will not fail if there is a problem running the analysis:

```xml
<configuration>
   <failOnError>false</failOnError>
   <failBuildOnCVSS>0</failBuildOnCVSS>
</configuration>
```

**Comment by jeremylong** [comment]
This issue has been resolved in a previous release.
