### ISSUE TITLE
Python project scan didn't recognize any dependencies

### ISSUE THREAD

**Issue by TwilightMercy** [dependency-check/DependencyCheck#963]
Hello,
I ran the lastest version of the tool (ver. 3.0.1) on a Python project, by using the common syntax of the tool and the **--enableExperimental** flag (for Python support):

dependency-check.bat --project PythonProject --scan PythonProjectFolder --out Reports\PythonProjectReport.html --enableExperimental

But the report contains 0 dependencies recognized by the tool. I checked in the python project folder, and all of his open source dependncies are documented in the **requirements.txt** file. 3 Questions:
1. Doesn't the tool can read the project dependencies from the **requirements.txt** file?
2. Beside the file, can't he read the **.py** code files and identify the "import XXX" commands to import external modules?
3. Generally, how the tool identify dependencies in Python projects?

Thank you very much,
Bar

**Comment by jeremylong** [comment]
You can see what the python analyzer currently does in the [documentation site here](https://jeremylong.github.io/DependencyCheck/analyzers/python.html).

The python analyzer does not yet scan the requirements.txt (see issue #548). Python is definitely on my list of things to work on in the near future.

**Comment by TwilightMercy** [comment]
I understand.
Can you also answer on my 2nd question? **.py** file with "import XXX", yet the tool doesn't recognize anything..

**Comment by jeremylong** [comment]
Regarding the .py files - this doesn't look at import statements for 3rd party libraries. Rather it appears to focus more on the __init__.py instead of all .py files.  The code can be found here: https://github.com/jeremylong/DependencyCheck/blob/master/dependency-check-core/src/main/java/org/owasp/dependencycheck/analyzer/PythonPackageAnalyzer.java#L70

Some of the documentation needs to be updated to outline that it really looks at __init__.py vs *.py.

**Comment by robertlagrant** [comment]
Is there any reason why it doesn't simply run `pip freeze` where available? That would list all the dependencies and their current installed versions.

**Comment by jeremylong** [comment]
@robertlagrant when possible we've avoided calling out to utilities that may or may not exist on the target system. However, that would be a fairly good idea - check if pip is installed/available and call out to `pip freeze` when available.
