### ISSUE TITLE
False Positive in AspNet.WebApi

### ISSUE THREAD

**Issue by putz612** [dependency-check/DependencyCheck#967]
I have several WebApi components being picked up as asp.net

|Dependency | CPE|
|-- | --|
|Microsoft.AspNet.WebApi:5.2.2 | cpe:/a:microsoft:asp.net:5.2.2|
|Microsoft.AspNet.WebApi.Client:5.2.2 | cpe:/a:microsoft:asp.net:5.2.2|
|Microsoft.AspNet.WebApi.Core:5.2.2 | cpe:/a:microsoft:asp.net:5.2.2|
|Microsoft.AspNet.WebApi.WebHost:5.2.2 | cpe:/a:microsoft:asp.net:5.2.2|

Sorry this is my first one so I do not know how to get the GroupID.  Here is the evidence if that helps.

|Type|Source|Name|Value|Confidence|
|--|--|--|--|--|
|Vendor|nuspec|owners|Microsoft,aspnet|Highest|
|Vendor|file|name|Microsoft.AspNet.WebApi|High|
|Vendor|nuspec|authors|Microsoft|High|
|Product|file|name|Microsoft.AspNet.WebApi|High|
|Product|nuspec|id|Microsoft.AspNet.WebApi|Highest|
|Product|nuspec|title|Microsoft ASP.NET Web API 2.2|Medium|
|Version|nuspec|version|5.2.2|Highest|

**Comment by jeremylong** [comment]
Thanks!  I'll do a sprint cleaning up all the report FP before the next release.

**Comment by jeremylong** [comment]
These were resolved with the fix for #872.
