### ISSUE TITLE
False positive with Ninject

### ISSUE THREAD

**Issue by putz612** [dependency-check/DependencyCheck#973]
It looks like Ninject is being picked up as NLog. Here is the evidence for one of them that got picked up as cpe: cpe:/a:nlog:nlog:3.2.3.0

|Type|Source|Name|Value|Confidence|
|--|--|--|--|--|
|Vendor|file|name|Ninject.Extensions.Logging.nlog4|High|
|Vendor|nuspec|owners|Ninject Project Contributors|Highest|
|Vendor|nuspec|authors|Ninject Project Contributors|High|
|Product|file|name|Ninject.Extensions.Logging.nlog4|High|
|Product|nuspec|id|Ninject.Extensions.Logging.nlog4|Highest|
|Version|nuspec|version|3.2.3.0|Highest|
|Version|file|name|Ninject.Extensions.Logging.nlog4|Medium|
|Version|file|version|4|Medium|

A few other instances as well.

|Dependency | CPE|
|-- | --|
|Ninject.Extensions.Logging.NLog4.dll|cpe:/a:nlog:nlog:3.2.0.0|
|Ninject.Extensions.Logging.nlog4.3.2.3.0.nupkg|cpe:/a:nlog:nlog:4.3.2.3.0|
|Ninject.Extensions.Logging.nlog4:3.2.3.0|cpe:/a:nlog:nlog:3.2.3.0|

**Comment by jeremylong** [comment]
Thanks for the FP report. The team will try to include a fix in the next release.
