### ISSUE TITLE
NSP: Invalid payload submitted to Node Security Platform

### ISSUE THREAD

**Issue by ammy1999** [dependency-check/DependencyCheck#975]
Hello,  I add the stage dependency check `stage("Dependency Check") {
                    dependencyCheckAnalyzer datadir: 'dependency-check-data', isFailOnErrorDisabled: true, hintsFile: '',
                        includeCsvReports: false, includeHtmlReports: false, includeJsonReports: false,
                        isAutoupdateDisabled: false, outdir: '', scanpath: '', skipOnScmChange: false,
                        skipOnUpstreamChange: false, suppressionFile: '', zipExtensions: '', nspAnalyzerEnabled: false
                    dependencyCheckPublisher canComputeNew: false, defaultEncoding: '', healthy: '', pattern: '', unHealthy: ''
                    archiveArtifacts allowEmptyArchive: true, artifacts: '**/dependency-check-report.xml', onlyIfSuccessful: true
                }
`
and this is `[DependencyCheck] Data directory created
[DependencyCheck] Scanning: /var/lib/jenkins/workspace/retio_2_MS_CoreRH_DEVOPS-17-IAIJQHIE6U2CTC6LNLIPROR5BEPZTVK4THP67ROQ6ZLFPQAKBMJA
[DependencyCheck] Analyzing Dependencies
[DependencyCheck] One or more exceptions were thrown while executing Dependency-Check
[DependencyCheck] Exception Caught: org.owasp.dependencycheck.analyzer.exception.AnalysisException
[DependencyCheck] Message: Could not perform NSP analysis. Invalid payload submitted to Node Security Platform.
[DependencyCheck] org.owasp.dependencycheck.analyzer.exception.AnalysisException: Could not perform NSP analysis. Invalid payload submitted to Node Security Platform.
[DependencyCheck] 	at org.owasp.dependencycheck.data.nsp.NspSearch.submitPackage(NspSearch.java:167)
[DependencyCheck] 	at org.owasp.dependencycheck.analyzer.NspAnalyzer.analyzeDependency(NspAnalyzer.java:174)
[DependencyCheck] 	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:137)
[DependencyCheck] 	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
[DependencyCheck] 	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
[DependencyCheck] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[DependencyCheck] 	at java.lang.Thread.run(Thread.java:745)
[DependencyCheck] ` 
the output , 
Should I modify the stage or the package.json ,...!! help please

**Comment by stevespringett** [comment]
What version of Dependency-Check?

Can you provide me the package.json you're scanning?

**Comment by ammy1999** [comment]
OWASP Dependency-Check Plugin v3.0.1 
package.json 

`{
  "devDependencies": {
    "generator-jhipster": "4.5.2"
  }
}`

**Comment by stevespringett** [comment]
That is an invalid package.json. The 'name' field is required per https://docs.npmjs.com/files/package.json

The native `nsp check` functionality fails gracefully here because it checks if name is not being specified and automatically assigns the name to 1. This is what `nsp check` is sending:

`{"devDependencies":{"generator-jhipster":"4.5.2"},"name":"1"}`

Dependency-Check does not compensate for invalid package.json files. If it's invalid, it will not try to correct it.

I'm going to mark this as an enhancement so that Dependency-Check compensates for a missing name field.

**Comment by stevespringett** [comment]
The enhancement will be included in the next release - 3.0.2

**Comment by ammy1999** [comment]
I add name and version in package.json, but the error still exist `java.lang.AssertionError
	at org.owasp.dependencycheck.analyzer.NspAnalyzerTest.testAnalyzePackage(NspAnalyzerTest.java:)`

**Comment by ammy1999** [comment]
Hi, build SUCCESS when I delete package.json , thank you @stevespringett
