### ISSUE TITLE
support the a skip option in maven

### ISSUE THREAD

**Issue by THausherr** [dependency-check/DependencyCheck#980]
(low prio, obviously)

suggestion: add a skip option to the maven configuration... currently, people must use `<phase/>` or `<phase>none</phase>` to skip the plugin. (I found the trick on stackoverflow when I wanted to temporarly disable the plugin pending resolution of #978 )

**Comment by jeremylong** [comment]
`skip` is already supported:

```xml
<configuration>
  <skip>true</skip>
</configuration>
```

See the [documentation](https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html) for additional configuration options.

**Comment by THausherr** [comment]
Indeed, sorry. I looked at the wrong place, or was tired, or both.
