### ISSUE TITLE
Modify the parameter of dependency Check

### ISSUE THREAD

**Issue by ammy1999** [dependency-check/DependencyCheck#985]
Hello, 
I add in jenkins file this stage: 
` stage("Dependency Check") {
                    dependencyCheckAnalyzer datadir: 'dependency-check-data', isFailOnErrorDisabled: true, hintsFile: '',
                        includeCsvReports: false, includeHtmlReports: false, includeJsonReports: false,
                        isAutoupdateDisabled: false, outdir: '', scanpath: '', skipOnScmChange: false,
                        skipOnUpstreamChange: false, suppressionFile: '', zipExtensions: ''
                    dependencyCheckPublisher canComputeNew: false, defaultEncoding: '', healthy: '', pattern: '', unHealthy: ''
                    archiveArtifacts allowEmptyArchive: true, artifacts: '**/dependency-check-report.xml', onlyIfSuccessful: true
                }`

Now , when I want add a parameter or modify a parameter , it doesn't work , So how can I modify it, is in the dependencyCheck.properties and how !! help please
thanks :)

**Comment by jeremylong** [comment]
It looks like you might be missing some commas?

**Comment by ammy1999** [comment]
No, I don't think so, I copied the stage from [https://issues.jenkins-ci.org/browse/JENKINS-46739](url)
it works fine, just I want adding a parameter

**Comment by stevespringett** [comment]
Valid pipeline that I typically use is:

```groovy
stage("Dependency Check") {
    dependencyCheckAnalyzer datadir: 'dependency-check-data', isFailOnErrorDisabled: true, hintsFile: '', includeCsvReports: false, includeHtmlReports: false, includeJsonReports: false, isAutoupdateDisabled: false, outdir: '', scanpath: '', skipOnScmChange: false, skipOnUpstreamChange: false, suppressionFile: '', zipExtensions: ''

    dependencyCheckPublisher canComputeNew: false, defaultEncoding: '', healthy: '', pattern: '', unHealthy: ''
    
    archiveArtifacts allowEmptyArchive: true, artifacts: '**/dependency-check-report.xml', onlyIfSuccessful: true
}
```
