### ISSUE TITLE
Maven Plugin Aggregate goal fails with version 3.0.2

### ISSUE THREAD

**Issue by xfh** [dependency-check/DependencyCheck#986]
Hi

Since version 3.0.2 the aggregate goal fails. A guess a MavenReport dependency was dropped.
See https://gist.github.com/xfh/0d9bbd82edbdffaefac57935822ffc19

I am using Maven version 3.3.9

**Comment by jeremylong** [comment]
The aggregate mojo is still present. Consider clearing your .m2 repo (or at least the ~/.mw/repository/org/owasp) and try the build again.

**Comment by xfh** [comment]
Indeed, now it's working again. Thanks!
