### ISSUE TITLE
API nodesecurity is down

### ISSUE THREAD

**Issue by TwilightMercy** [dependency-check/DependencyCheck#988]
Hello,

I ran today the Node js retired analyzer on a NodeJS Project using the latest version of the tool (3.0.2), and it seems that the URL: https://api.nodesecurity.io/check, which I understand the tool using to identify the dependencies - is down.

When entering the URL, the output is the follwing:
{"statusCode":404,"error":"Not Found","message":"Not Found"}

Because of that I have no results in my scan report.
Thank you,
Bar

**Comment by jeremylong** [comment]
The service is not down. You are hitting an API without sending in the correct request - of course you are going to get a 404 back...

**Comment by TwilightMercy** [comment]
This is true, because I manually opened the URL. So maybe the problem is in my scan?
The HTML report my NodeJS project (using **--enableRetired** parameter) shows that the tool recognized as Dependencies only the **"package.json"** files. It doesn't scan their content and the open source dependencies.

Example:
![1](https://user-images.githubusercontent.com/29895680/32891383-0581729a-cadb-11e7-8b8a-9994d479f440.png)
