### ISSUE TITLE
debian package available ?

### ISSUE THREAD

**Issue by ka7** [dependency-check/DependencyCheck#989]
in relation to:
( https://gitlab.com/fdroid/fdroidserver/issues/408 )

Is there a pre-build *latest* debian-package for the shell-ish version avaliable ?
might be nice ( e.g. for people who want to integrate this into travis (e.g via weekly cron-ish test-builds)

**Comment by stevespringett** [comment]
Official Debian packages are not available. However, you should be able to easily integrate this with travisci.

I haven't tried or tested this, but in your .travis.yml, put something like this in there:

```yaml
script:
- curl -L http://dl.bintray.com/jeremy-long/owasp/dependency-check-3.0.2-release.zip > dependency-check.zip
- unzip dependency-check.zip
- cd dependency-check/bin
- ./dependency-check.sh .....
```

**Comment by ka7** [comment]
ok, i see; for travis this is an option ( as they are anyway throw-away machines.. )
Is there a "howto build" doku available ?
... managed to build it ( mvn.. ) but how you come to e.g. the downloadable .zip i did not found.
( i would like to try my own .deb build, which should be nicer for upgrade, keep the downloaded files in separate dir, containing the "depends on" info, ... )

**Comment by jeremylong** [comment]
Take a look at the [Dockerfile](https://github.com/jeremylong/DependencyCheck/blob/master/Dockerfile).  That shows how you can download the latest release. In the same vein you could look at the homebrew formula for [dependency-check.rb](https://github.com/Homebrew/homebrew-core/blob/master/Formula/dependency-check.rb).

If you want to compile the project yourself for inclusion you can just run `mvn package` at the root of the project and the in `DependencyCheck\dependency-check-cli\target\` you will find the zip file.
