### ISSUE TITLE
CSV For Node Scan Doesn't Include Vulnerable Software Name.

### ISSUE THREAD

**Issue by jgamblin** [dependency-check/DependencyCheck#991]
When you scan a package.json and look at the CSV output it doesn't include the name of the vulnerable software (tagged vulnerableSoftware in the json).

**Comment by jeremylong** [comment]
This is being fixed the [issue-993](https://github.com/jeremylong/DependencyCheck/tree/issue-993) branch and will be included in the next release.

**Comment by jaikishantulswani** [comment]
/GithubDependencyCheck.sh: line 5: jq: command not found
(23) Failed writing body
cat: 'results/*.csv': No such file or directory
