### ISSUE TITLE
No way to disable ruby analyzer?

### ISSUE THREAD

**Issue by pioto** [dependency-check/DependencyCheck#992]
Please delete any un-needed section from the following issue template:

### Reporting Bugs/Errors

https://gist.github.com/pioto/39ba1cb830a0cbed952a50aed48641a6

It seems that, if the ruby bundle-audit tool is not present, then this tool will always fail the Maven build. I've even attempted to outright disable this integration, using `<rubygemsAnalyzerEnabled>false</rubygemsAnalyzerEnabled>`, but it still tries to run it.

I have no ruby in my code base, so this analyzer is irrelevant.

**Comment by jeremylong** [comment]
I think we need to update the documentation a little.  What you need to disable is the `bundleAuditAnalyzerEnabled`:

```xml
<configuration>
   <bundleAuditAnalyzerEnabled>false</bundleAuditAnalyzerEnabled>
</comfiguration>
```

There are actually two analyzers for Ruby and they work differently.

**Comment by pioto** [comment]
I'll try that, but I'd argue that the tool should still fail gracefully in the absence of this other tool, and just log a warning that it couldn't run that analysis and move on.

**Comment by jeremylong** [comment]
I'd argue that dependency-check should fail under this condition - with clearer instructions on how to disable the offending analyzer.
