### ISSUE TITLE
NodeJS scan not recognizing dependencies in package.json files

### ISSUE THREAD

**Issue by TwilightMercy** [dependency-check/DependencyCheck#993]
Hi,
I ran the NodeJS retired analyzer (with **--enableRetired** parameter) on a NodeJS Project using the latest version of the tool (3.0.2).
The HTML report  shows that the tool recognized as Dependencies only the **"package.json"** files. It doesn't scan their content and the open source dependencies.

Example:
![1](https://user-images.githubusercontent.com/29895680/32942361-7df0b388-cb91-11e7-904e-ac2fdfa441dc.png)

Any ideas?

**Comment by stevespringett** [comment]
That is the way the NodeJS analyzer was designed. In my testing, I found that it produced a 100% false positive rate and a 100% false negative rate. This analyzer has been retired due to it not being useful. No further work is currently planned on improving it.

All Node projects should use the Dependency-Check NSP analyzer, which is enabled by default. The NSP analyzer utilizes the Node Security Platform API and will scan dependencies included in package.json.

**Comment by TwilightMercy** [comment]
I understand, but if so - Even when using the default analyzers (just simply running the tool without **--enableRetired** or **enableExperimental**), I get the same results. only **package.json** files as Dependencies - and not their content.

**Comment by jeremylong** [comment]
I completely understand the issue you are facing and I am working on revamping the Node.js and NSP analyzers.

**Comment by TwilightMercy** [comment]
Ok, can you please update here when the problem is fixed?

**Comment by TwilightMercy** [comment]
Is it possible to download the updated version now, because the version is still 3.0.2

**Comment by jeremylong** [comment]
@barronen1 no.  the feature is not complete yet.  you are more then welcome to download the branch, compile it, and test it.

**Comment by TwilightMercy** [comment]
@jeremylong I understand.

Can I ask if you can guide me in short how to do that? I downloaded the whole ZIP (with the comitted files).
And tried to to compile the files you changed using the command: **javac JavaFileName.java**, but it has a lot of errors.
Am I doing it wrong?

**Comment by jeremylong** [comment]
This is a maven project.

```bash
git clone https://github.com/jeremylong/DependencyCheck.git
cd DependencyCheck
git checkout issue-993
mvn install
```

This should build version 3.0.3-SNAPSHOT.

**Comment by TwilightMercy** [comment]
I guess that **mvn install** didn't work properly while building.

------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Dependency-Check ................................... FAILURE [02:08 min]
[INFO] Dependency-Check Utils ............................. SKIPPED
[INFO] Dependency-Check Core .............................. SKIPPED
[INFO] Dependency-Check Command Line ...................... SKIPPED
[INFO] Dependency-Check Ant Task .......................... SKIPPED
[INFO] Dependency-Check Maven Plugin ...................... SKIPPED
[INFO] Dependency-Check Plugin Archetype .................. SKIPPED
[INFO] Dependency-Check Build-Reporting ................... SKIPPED

The error I found:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.20:integration-test (default) on project dependency-check-parent: Execution default of goal org.apache.maven.plugins:maven-failsafe-plugin:2.20:integration-test failed: A required class was missing while executing org.apache.maven.plugins:maven-failsafe-plugin:2.20:integration-test: javax/xml/bind/JAXBException

**Comment by TwilightMercy** [comment]
Jeremy?

**Comment by jeremylong** [comment]
Still working on the best resolution for this issue (amongst many other things).  No clue why you can't build the project - but from that error message it has to do with your environment.

**Comment by TwilightMercy** [comment]
Alright, thank you.
Please let me know when an official fix will be released to Node scans, so we can continue working.
Bar

**Comment by ammy1999** [comment]
please how can I generate the html report for a nodejs project ?? thanks

**Comment by jeremylong** [comment]
By running dependency-check and scan the root of the node.js project. Using the CLI version or using Jenkins to scan the workspace.

**Comment by jeremylong** [comment]
@barronen1 this ticket should now be resolved. The 3.1 version improved the node.js scanning.

**Comment by TwilightMercy** [comment]
Does it work with local copy of NVD db file, without internet connection? (the node.js analysis)

**Comment by jeremylong** [comment]
No, currently node.js solely uses NSP which requires sending a small amount of data to the NSP server.

**Comment by TwilightMercy** [comment]
Ok, so-
If im working in a closed network, without internet connection, and I want to scan my nodeJS project without exposing it to the internet- 
Can I take only the main package.json file from the main project folder, and scan the file in the internet?
