### ISSUE TITLE
Enhancement: support Windows UNC paths?

### ISSUE THREAD

**Issue by jfallot** [dependency-check/DependencyCheck#995]
Hello,

Under Windows I have tried to use UNC paths, by example:
`.\dependency-check --project TestProject -out . --scan \\server\ThirdParty\myproject\x.x\**\*.jar`

but got the following error:
`Invalid 'scan' argument: '\\server\ThirdParty\myproject\x.x\**\*.jar'
Unable to scan paths that start with '//'.`

Offering the ability to support UNC paths would be interesting for cases where Windows is the primary development environment.

Thanx :)

**Comment by mprins** [comment]
your path is wrong, try `\\\\server\\myUNC`
you need to escape any backslash with a backslash

**Comment by jfallot** [comment]
Thank you for the suggestion, but I get the same error:

```
.\dependency-check --project TestProject -out . --scan \\\\server\\ThirdParty\\myproject\\x.x\\**\\*.jar
Invalid 'scan' argument: '\\\\server\\ThirdParty\\myproject\\x.x\\**\\*.jar'
Unable to scan paths that start with '//'
```

**Comment by jeremylong** [comment]
For some reason I had, a LONG time ago, added a specific check preventing '\\' paths. Not entirely sure why as I can't see a reason to prevent this anymore.  I have submitted PR #996 to resolve this. The update should be in the next release.

**Comment by dwmuller** [comment]
This still (or again?) seems to be broken in 3.2.1. I get this error when I try to use UNC paths as an argument for --scan:

[ERROR] An invalid scan path was detected; unable to scan '//*' paths

Based on a little bit of searching and code inspection, I think the source of the error is scanAntStylePaths() in App.java. There's an explicit test for a '\\\\' prefix, causing an InvalidScanPathException to be thrown. It's caught in run(), where the error message in the exception is ignored and instead a misleading error message is printed.

**Comment by jeremylong** [comment]
@dwmuller I think you found a second place were we were incorrectly not allowing a unc path. Sorry about that. This will be fixed in the next release.
