### ISSUE TITLE
Failed connecting to Central search using docker image

### ISSUE THREAD

**Issue by githubhs17** [dependency-check/DependencyCheck#998]
Think this depends on issue 978 (982), which is closed now. But may be the docker container is not updated to fix this. We are using your docker image owasp/dependency-check and get still the Central search connection error:

07:45:22 [INFO] Analysis Started
07:45:24 [INFO] Finished Archive Analyzer (1 seconds)
07:45:24 [INFO] Finished File Name Analyzer (0 seconds)
07:45:26 [INFO] Finished Jar Analyzer (2 seconds)
07:45:42 [ERROR] Could not connect to Central search. Analysis failed.
07:45:42 java.io.IOException: Finally failed connecting to Central search. Giving up after 5 tries.
07:45:42 	at org.owasp.dependencycheck.analyzer.CentralAnalyzer.fetchMavenArtifacts(CentralAnalyzer.java:288)
07:45:42 	at org.owasp.dependencycheck.analyzer.CentralAnalyzer.analyzeDependency(CentralAnalyzer.java:198)
07:45:42 	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:137)
07:45:42 	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
07:45:42 	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
07:45:42 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
07:45:42 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
07:45:42 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
07:45:42 	at java.lang.Thread.run(Thread.java:748)

**Comment by jeremylong** [comment]
Can you validate that you are using `release-v3.0.2`?  

https://hub.docker.com/r/owasp/dependency-check/tags/

**Comment by githubhs17** [comment]
We are always using the latest version

04:54:13 + docker pull owasp/dependency-check
04:54:13 Using default tag: latest
04:54:14 latest: Pulling from owasp/dependency-check
04:54:14 Digest: sha256:950368b527f814aa7d8eb26c835ab47f1bf0e6fba30c0f3d08adb5f6d8e6e664
04:54:14 Status: Image is up to date for owasp/dependency-check:latest

**Comment by githubhs17** [comment]
Hi Jeremy, any idea what's going wrong. This is really important for us. Thanks, kind regards. Harry

**Comment by jeremylong** [comment]
The issue should now be fixed - update your docker image and it should work. I need to change the process that builds the docker image...

**Comment by githubhs17** [comment]
Jeremy, thanks. All scans works fine since them
